* I Peter 1

** I Peter 1:1

Peter, an apostle of Jesus Christ, to the strangers dispersed through Pontus, Cappadocia, Asia and Bithynia, elect,

** I Peter 1:2

According to the foreknowledge of God the Father, unto the sanctification of the Spirit, unto obedience and sprinkling of the blood of Jesus Christ. Grace unto you and peace be multiplied.

** I Peter 1:3

Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy hath regenerated us unto a lively hope, by the resurrection of Jesus Christ from the dead:

** I Peter 1:4

Unto an inheritance, incorruptible, and undefiled and that cannot fade, reserved in heaven for you,

** I Peter 1:5

Who, by the power of God, are kept by faith unto salvation, ready to be revealed in the last time.

** I Peter 1:6

Wherein you shalt greatly rejoice, if now you must be for a little time made sorrowful in divers temptations:

** I Peter 1:7

That the trial of your faith (much more precious than gold which is tried by the fire) may be found unto praise and glory and honour at the appearing of Jesus Christ.

** I Peter 1:8

Whom having not seen, you love: in whom also now though you see him not, you believe and, believing, shall rejoice with joy unspeakable and glorified;

** I Peter 1:9

Receiving the end of your faith, even the salvation of your souls.

** I Peter 1:10

Of which salvation the prophets have inquired and diligently searched, who prophesied of the grace to come in you.

** I Peter 1:11

Searching what or what manner of time the Spirit of Christ in them did signify, when it foretold those sufferings that are in Christ and the glories that should follow.

** I Peter 1:12

To whom it was revealed that, not to themselves but to you, they ministered those things which are now declared to you by them that have preached the gospel to you: the Holy Ghost being sent down from heaven, on whom the angels desire to look.

** I Peter 1:13

Wherefore, having the loins of your mind girt up, being sober, trust perfectly in the grace which is offered you in the revelation of Jesus Christ.

** I Peter 1:14

As children of obedience, not fashioned according to the former desires of your ignorance,

** I Peter 1:15

But according to him that hath called you, who is holy, be you also in all manner of conversation holy:

** I Peter 1:16

Because it is written: You shall be holy, for I am holy.

** I Peter 1:17

And if you invoke as Father him who, without respect of persons, judgeth according to every one's work: converse in fear during the time of your sojourning here.

** I Peter 1:18

Knowing that you were not redeemed with corruptible things, as gold or silver, from your vain conversation of the tradition of your fathers:

** I Peter 1:19

But with the precious blood of Christ, as of a lamb unspotted and undefiled

** I Peter 1:20

Foreknown indeed before the foundation of the world, but manifested in the last times for you:

** I Peter 1:21

Who through him are faithful in God who raised him up from the dead and hath given him glory, that your faith and hope might be in God.

** I Peter 1:22

Purifying your souls in the obedience of charity, with a brotherly love, from a sincere heart love one another earnestly:

** I Peter 1:23

Being born again, not of corruptible seed, but incorruptible, by the word of God who liveth and remaineth for ever.

** I Peter 1:24

For all flesh is as grass and all the glory thereof as the flower of grass. The grass is withered and the flower thereof is fallen away.

** I Peter 1:25

But the word of the Lord endureth for ever. And this is the word which by the gospel hath been preached unto you. 

* I Peter 2

** I Peter 2:1

Wherefore laying away all malice and all guile and dissimulations and envies and all detractions,

** I Peter 2:2

As newborn babes, desire the rational milk without guile, that thereby you may grow unto salvation:

** I Peter 2:3

If so be you have tasted that the Lord is sweet.

** I Peter 2:4

Unto whom coming, as to a living stone, rejected indeed by men but chosen and made honourable by God:

** I Peter 2:5

Be you also as living stones built up, a spiritual house, a holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ.

** I Peter 2:6

Wherefore it is said in the scripture: Behold, I lay in Sion a chief corner stone, elect, precious. And he that shall believe in him shall not be confounded.

** I Peter 2:7

To you therefore that believe, he is honour: but to them that believe not, the stone which the builders rejected, the same is made the head of the corner:

** I Peter 2:8

And a stone of stumbling and a rock of scandal, to them who stumble at the word, neither do believe, whereunto also they are set.

** I Peter 2:9

But you are a chosen generation, a kingly priesthood, a holy nation, a purchased people: that you may declare his virtues, who hath called you out of darkness into his marvelous light:

** I Peter 2:10

Who in times past were not a people: but are now the people of God. Who had not obtained mercy: but now have obtained mercy.

** I Peter 2:11

Dearly beloved, I beseech you, as strangers and pilgrims, to refrain yourselves from carnal desires which war against the soul,

** I Peter 2:12

Having your conversation good among the Gentiles: that whereas they speak against you as evildoers, they may, by the good works which they shall behold in you, glorify God in the day of visitation.

** I Peter 2:13

Be ye subject therefore to every human creature for God's sake: whether it be to the king as excelling,

** I Peter 2:14

Or to governors as sent by him for the punishment of evildoers and for the praise of the good.

** I Peter 2:15

For so is the will of God, that by doing well you may put to silence the ignorance of foolish men:

** I Peter 2:16

As free and not as making liberty a cloak for malice, but as the servants of God.

** I Peter 2:17

Honour all men. Love the brotherhood. Fear God. Honour the king.

** I Peter 2:18

Servants, be subject to your masters with all fear, not only to the good and gentle but also to the froward.

** I Peter 2:19

For this is thankworthy: if, for conscience towards God, a man endure sorrows, suffering wrongfully.

** I Peter 2:20

For what glory is it, if, committing sin and being buffeted for it, you endure? But if doing well you suffer patiently: this is thankworthy before God.

** I Peter 2:21

For unto this are you called: because Christ also suffered for us, leaving you an example that you should follow his steps.

** I Peter 2:22

Who did no sin, neither was guile found in his mouth.

** I Peter 2:23

Who, when he was reviled, did not revile: when he suffered, he threatened not, but delivered himself to him that judged him unjustly.

** I Peter 2:24

Who his own self bore our sins in his body upon the tree: that we, being dead to sins, should live to justice: by whose stripes you were healed.

** I Peter 2:25

For you were as sheep going astray: but you are now converted to the shepherd and bishop of your souls. 

* I Peter 3

** I Peter 3:1

In like manner also, let wives be subject to their husbands: that, if any believe not the word, they may be won without the word, by the conversation of the wives,

** I Peter 3:2

Considering your chaste conversation with fear.

** I Peter 3:3

Whose adorning, let it not be the outward plaiting of the hair, or the wearing of gold, or the putting on of apparel:

** I Peter 3:4

But the hidden man of the heart, in the incorruptibility of a quiet and a meek spirit which is rich in the sight of God.

** I Peter 3:5

For after this manner heretofore, the holy women also who trusted in God adorned themselves, being in subjection to their own husbands:

** I Peter 3:6

As Sara obeyed Abraham, calling him lord: whose daughters you are, doing well and not fearing any disturbance.

** I Peter 3:7

Ye husbands, likewise dwelling with them according to knowledge, giving honour to the female as to the weaker vessel and as to the co-heirs of the grace of life: that your prayers be not hindered.

** I Peter 3:8

And in fine, be ye all of one mind, having compassion one of another, being lovers of the brotherhood, merciful, modest, humble:

** I Peter 3:9

Not rendering evil for evil, nor railing for railing, but contrariwise, blessing: for unto this are you called, that you may inherit a blessing.

** I Peter 3:10

For he that will love life and see good days, let him refrain his tongue from evil, and his lips that they speak no guile.

** I Peter 3:11

Let him decline from evil and do good: Let him seek after peace and pursue it:

** I Peter 3:12

Because the eyes of the Lord are upon the just, and his ears unto their prayers but the countenance of the Lord upon them that do evil things.

** I Peter 3:13

And who is he that can hurt you, if you be zealous of good?

** I Peter 3:14

But if also you suffer any thing for justice' sake, blessed are ye. And be not afraid of their fear: and be not troubled.

** I Peter 3:15

But sanctify the Lord Christ in your hearts, being ready always to satisfy every one that asketh you a reason of that hope which is in you.

** I Peter 3:16

But with modesty and fear, having a good conscience: that whereas they speak evil of you, they may be ashamed who falsely accuse your good conversation in Christ.

** I Peter 3:17

For it is better doing well (if such be the will of God) to suffer than doing ill.

** I Peter 3:18

Because Christ also died once for our sins, the just for the unjust: that he might offer us to God, being put to death indeed in the flesh, but enlivened in the spirit,

** I Peter 3:19

In which also coming he preached to those spirits that were in prison:

** I Peter 3:20

Which had been some time incredulous, when they waited for the patience of God in the days of Noe, when the ark was a building: wherein a few, that is, eight souls, were saved by water.

** I Peter 3:21

Whereunto baptism, being of the like form, now saveth you also: not the putting away of the filth of the flesh, but, the examination of a good conscience towards God by the resurrection of Jesus Christ.

** I Peter 3:22

Who is on the right hand of God, swallowing down death that we might be made heirs of life everlasting: being gone into heaven, the angels and powers and virtues being made subject to him. 

* I Peter 4

** I Peter 4:1

Christ therefore having suffered in the flesh, be you also armed with the same thought: for he that hath suffered in the flesh hath ceased from sins:

** I Peter 4:2

That now he may live the rest of his time in the flesh, not after the desires of men but according to the will of God.

** I Peter 4:3

For the time past is sufficient to have fulfilled the will of the Gentiles, for them who have walked in riotousness, lusts, excess of wine, revellings, banquetings and unlawful worshipping of idols.

** I Peter 4:4

Wherein they think it strange that you run not with them into the same confusion of riotousness: speaking evil of you.

** I Peter 4:5

Who shall render account to him who is ready to judge the living and the dead.

** I Peter 4:6

For, for this cause was the gospel preached also to the dead: That they might be judged indeed according to men, in the flesh: but may live according to God, in the Spirit.

** I Peter 4:7

But the end of all is at hand. Be prudent therefore and watch in prayers.

** I Peter 4:8

But before all things have a constant mutual charity among yourselves: for charity covereth a multitude of sins.

** I Peter 4:9

Using hospitality one towards another, without murmuring,

** I Peter 4:10

As every man hath received grace, ministering the same one to another: as good stewards of the manifold grace of God.

** I Peter 4:11

If any man speak, let him speak, as the words of God. If any minister, let him do it, as of the power which God administereth: that in all things God may be honoured through Jesus Christ: to whom is glory and empire for ever and ever. Amen.

** I Peter 4:12

Dearly beloved, think not strange the burning heat which is to try you: as if some new thing happened to you.

** I Peter 4:13

But if you partake of the sufferings of Christ, rejoice that, when his glory shall be revealed, you may also be glad with exceeding joy.

** I Peter 4:14

If you be reproached for the name of Christ, you shall be blessed: for that which is of the honour, glory and power of God, and that which is his Spirit resteth upon you.

** I Peter 4:15

But let none of you suffer as a murderer or a thief or a railer or coveter of other men's things.

** I Peter 4:16

But, if as a Christian, let him not be ashamed: but let him glorify God in that name.

** I Peter 4:17

For the time is, that judgment should begin at the house of God. And if at first at us, what shall be the end of them that believe not the gospel of God?

** I Peter 4:18

And if the just man shall scarcely be saved, where shall the ungodly and the sinner appear?

** I Peter 4:19

Wherefore let them also that suffer according to the will of God commend their souls in good deeds to the faithful Creator. 

* I Peter 5

** I Peter 5:1

The ancients therefore that are among you, I beseech who am myself also an ancient and a witness of the sufferings of Christ, as also a partaker of that glory which is to be revealed in time to come:

** I Peter 5:2

Feed the flock of God which is among you, taking care of it, not by constraint but willingly, according to God: not for filthy lucre's sake but voluntarily:

** I Peter 5:3

Neither as lording it over the clergy but being made a pattern of the flock from the heart.

** I Peter 5:4

And when the prince of pastors shall appear, you shall receive a never fading crown of glory.

** I Peter 5:5

In like manner, ye young men, be subject to the ancients. And do you all insinuate humility one to another: for God resisteth the proud, but to the humble he giveth grace.

** I Peter 5:6

Be you humbled therefore under the mighty hand of God, that he may exalt you in the time of visitation:

** I Peter 5:7

Casting all your care upon him, for he hath care of you.

** I Peter 5:8

Be sober and watch: because your adversary the devil, as a roaring lion, goeth about seeking whom he may devour.

** I Peter 5:9

Whom resist ye, strong in faith: knowing that the same affliction befalls, your brethren who are in the world.

** I Peter 5:10

But the God of all grace, who hath called us unto his eternal glory in Christ Jesus, after you have suffered a little, will himself perfect you and confirm you and establish you.

** I Peter 5:11

To him be glory and empire, for ever and ever. Amen.

** I Peter 5:12

By Sylvanus, a faithful brother unto you, as I think, I have written briefly: beseeching and testifying that this is the true grace of God, wherein you stand.

** I Peter 5:13

The church that is in Babylon, elected together with you, saluteth you. And so doth my son, Mark.

** I Peter 5:14

Salute one another with a holy kiss. Grace be to all you who are in Christ Jesus. Amen.  

