* II Peter 1

** II Peter 1:1

Simon Peter, servant and apostle of Jesus Christ: to them that have obtained equal faith with us in the justice of our God and Saviour Jesus Christ.

** II Peter 1:2

Grace to you and peace be accomplished in the knowledge of God and of Christ Jesus our Lord.

** II Peter 1:3

As all things of his divine power which appertain to life and godliness are given us through the knowledge of him who hath called us by his own proper glory and virtue.

** II Peter 1:4

By whom he hath given us most great and precious promises: that by these you may be made partakers of the divine nature: flying the corruption of that concupiscence which is in the world.

** II Peter 1:5

And you, employing all care, minister in your faith, virtue: And in virtue, knowledge:

** II Peter 1:6

And in knowledge, abstinence: and in abstinence, patience: and in patience, godliness:

** II Peter 1:7

And in godliness, love of brotherhood: and in love of brotherhood, charity.

** II Peter 1:8

For if these things be with you and abound, they will make you to be neither empty nor unfruitful in the knowledge of our Lord Jesus Christ.

** II Peter 1:9

For he that hath not these things with him is blind and groping, having forgotten that he was purged from his old sins.

** II Peter 1:10

Wherefore, brethren, labour the more, that by good works you may make sure your calling and election. For doing these things, you shall not sin at any time.

** II Peter 1:11

For so an entrance shall be ministered to you abundantly into the ever-lasting kingdom of our Lord and Saviour Jesus Christ.

** II Peter 1:12

For which cause, I will begin to put you always in remembrance of these things: though indeed you know them and are confirmed in the present truth.

** II Peter 1:13

But I think it meet, as long as I am in this tabernacle, to stir you up by putting you in remembrance.

** II Peter 1:14

Being assured that the laying away of this my tabernacle is at hand, according as our Lord Jesus Christ also hath signified to me.

** II Peter 1:15

And I will endeavour that you frequently have after my decease whereby you may keep a memory of these things.

** II Peter 1:16

For we have not by following artificial fables made known to you the power and presence of our Lord Jesus Christ: but we were eyewitnesses of his greatness.

** II Peter 1:17

For he received from God the Father honour and glory, this voice coming down to him from the excellent glory: This is my beloved Son, in whom I am well pleased. Hear ye him.

** II Peter 1:18

And this voice, we heard brought from heaven, when we were with him in the holy mount.

** II Peter 1:19

And we have the more firm prophetical word: whereunto you do well to attend, as to a light that shineth in a dark place, until the day dawn and the day star arise in your hearts.

** II Peter 1:20

Understanding this first: That no prophecy of scripture is made by private interpretation.

** II Peter 1:21

For prophecy came not by the will of man at any time: but the holy men of God spoke, inspired by the Holy Ghost. 

* II Peter 2

** II Peter 2:1

But there were also false prophets among the people, even as there shall be among you lying teachers who shall bring in sects of perdition and deny the Lord who bought them: bringing upon themselves swift destruction.

** II Peter 2:2

And many shall follow their riotousness, through whom the way of truth shall be evil spoken of.

** II Peter 2:3

And through covetousness shall they with feigned words make merchandise of you. Whose judgment now of a long time lingereth not: and their perdition slumbereth not.

** II Peter 2:4

For if God spared not the angels that sinned, but delivered them, drawn down by infernal ropes to the lower hell, unto torments, to be reserved unto judgment:

** II Peter 2:5

And spared not the original world, but preserved Noe, the eighth person, the preacher of justice, bringing in the flood upon the world of the ungodly.

** II Peter 2:6

And reducing the cities of the Sodomites and of the Gomorrhites into ashes, condemned them to be overthrown, making them an example to those that should after act wickedly,

** II Peter 2:7

And delivered just Lot, oppressed by the injustice and lewd conversation of the wicked:

** II Peter 2:8

For in sight and hearing he was just, dwelling among them who from day to day vexed the just soul with unjust works.

** II Peter 2:9

The Lord knoweth how to deliver the godly from temptation, but to reserve the unjust unto the day of judgment to be tormented:

** II Peter 2:10

And especially them who walk after the flesh in the lust of uncleanness and despise government: audacious, self willed, they fear not to bring in sects, blaspheming.

** II Peter 2:11

Whereas angels, who are greater in strength and power, bring not against themselves a railing judgment.

** II Peter 2:12

But these men, as irrational beasts, naturally tending to the snare and to destruction, blaspheming those things which they know not, shall perish in their corruption:

** II Peter 2:13

Receiving the reward of their injustice, counting for a pleasure the delights of a day: stains and spots, sporting themselves to excess, rioting in their feasts with you:

** II Peter 2:14

Having eyes full of adultery and of sin that ceaseth not: alluring unstable souls: having their heart exercised with covetousness: children of malediction.

** II Peter 2:15

Leaving the right way, they have gone astray, having followed the way of Balaam of Bosor who loved the wages of iniquity,

** II Peter 2:16

But had a check of his madness, the dumb beast used to the yoke, which, speaking with man's voice, forbade the folly of the prophet.

** II Peter 2:17

These are fountains without water and clouds tossed with whirlwinds, to whom the mist of darkness is reserved.

** II Peter 2:18

For, speaking proud words of vanity, they allure by the desires of fleshly riotousness those who for a little while escape, such as converse in error:

** II Peter 2:19

Promising them liberty, whereas they themselves are the slaves of corruption. For by whom a man is overcome, of the same also he is the slave.

** II Peter 2:20

For if, flying from the pollutions of the world, through the knowledge of our Lord and Saviour Jesus Christ, they be again entangled in them and overcome: their latter state is become unto them worse than the former.

** II Peter 2:21

For it had been better for them not to have known the way of justice than, after they have known it, to turn back from that holy commandment which was delivered to them.

** II Peter 2:22

For, that of the true proverb has happened to them: The dog is returned to his vomit; and: The sow that was washed to her wallowing in the mire. 

* II Peter 3

** II Peter 3:1

Behold this second epistle I write to you, my dearly beloved, in which, I stir up by way of admonition your sincere mind:

** II Peter 3:2

That you may be mindful of those words which I told you before from the holy prophet and of your apostles, of the precepts of the Lord and Saviour.

** II Peter 3:3

Knowing this first: That in the last days there shall come deceitful scoffers, walking after their own lusts,

** II Peter 3:4

Saying: Where is his promise or his coming? For since the time that the fathers slept, all things continue as they were from the beginning of the creation.

** II Peter 3:5

For this they are wilfully ignorant of: That the heavens were before, and the earth out of water and through water, consisting by the word of God:

** II Peter 3:6

Whereby the world that then was, being overflowed with water, perished.

** II Peter 3:7

But the heavens and the earth which are now, by the same word are kept in store, reserved unto fire against the day of judgment and perdition of the ungodly men.

** II Peter 3:8

But of this one thing be not ignorant, my beloved, that one day with the Lord is as a thousand years, and a thousand years as one day.

** II Peter 3:9

The Lord delayeth not his promise, as some imagine, but dealeth patiently for your sake, not willing that any should perish, but that all should return to penance,

** II Peter 3:10

But the day of the Lord shall come as a thief, in which the heavens shall pass away with great violence and the elements shall be melted with heat and the earth and the works which are in it shall be burnt up.

** II Peter 3:11

Seeing then that all these things are to be dissolved, what manner of people ought you to be in holy conversation and godliness?

** II Peter 3:12

Looking for and hasting unto the coming of the day of the Lord, by which the heavens being on fire shall be dissolved, and the elements shall melt with the burning heat?

** II Peter 3:13

But we look for new heavens and a new earth according to his promises, in which justice dwelleth.

** II Peter 3:14

Wherefore, dearly beloved, waiting for these things, be diligent that you may be found before him unspotted and blameless in peace.

** II Peter 3:15

And account the longsuffering of our Lord, salvation: as also our most dear brother Paul, according to the wisdom given him, hath written to you:

** II Peter 3:16

As also in all his epistles, speaking in them of these things; in which are certain things hard to be understood, which the unlearned and unstable wrest, as they do also the other scriptures, to their own destruction.

** II Peter 3:17

You therefore, brethren, knowing these things before, take heed, lest being led aside by the error of the unwise, you fall from your own steadfastness.

** II Peter 3:18

But grow in grace and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and unto the day of eternity, Amen.  

