* Colossians 1

** Colossians 1:1

Paul, an apostle of Jesus Christ, by the will of God, and Timothy, a brother:

** Colossians 1:2

To the saints and faithful brethren in Christ Jesus who are at Colossa.

** Colossians 1:3

Grace be to you and peace, from God our Father and from the Lord Jesus Christ. We give thanks to God and the Father of our Lord Jesus Christ, praying always for you.

** Colossians 1:4

Hearing your faith in Christ Jesus and the love which you have towards all the saints.

** Colossians 1:5

For the hope that is laid up for you in heaven, which you have heard in the word of the truth of the gospel,

** Colossians 1:6

Which is come unto you, as also it is in the whole world and bringeth forth fruit and groweth, even as it doth in you, since the day you heard and knew the grace of God in truth.

** Colossians 1:7

As you learned of Epaphras, our most beloved fellow servant, who is for you a faithful minister of Christ Jesus;

** Colossians 1:8

Who also hath manifested your love in the spirit.

** Colossians 1:9

Therefore we also, from the day that we heard it, cease not to pray for you and to beg that you may be filled with the knowledge of his will, in all wisdom and spiritual understanding:

** Colossians 1:10

That you may walk worthy of God, in all things pleasing; being fruitful in every good work and increasing in the knowledge of God:

** Colossians 1:11

Strengthened with all might according to the power of his glory, in all patience and longsuffering with joy,

** Colossians 1:12

Giving thanks to God the Father, who hath made us worthy to be partakers of the lot of the saints in light:

** Colossians 1:13

Who hath delivered us from the power of darkness and hath translated us into the kingdom of the Son of his love,

** Colossians 1:14

In whom we have redemption through his blood, the remission of sins:

** Colossians 1:15

Who is the image of the invisible God, the firstborn of every creature:

** Colossians 1:16

For in him were all things created in heaven and on earth, visible and invisible, whether thrones, or dominations, or principalities, or powers. All things were created by him and in him.

** Colossians 1:17

And he is before all: and by him all things consist.

** Colossians 1:18

And he is the head of the body, the church: who is the beginning, the firstborn from the dead, that in all things he may hold the primacy:

** Colossians 1:19

Because in him, it hath well pleased the Father that all fulness should dwell:

** Colossians 1:20

And through him to reconcile all things unto himself, making peace through the blood of his cross, both as to the things that are on earth and the things that are in heaven.

** Colossians 1:21

And you, whereas you were some time alienated and enemies in mind in evil works:

** Colossians 1:22

Yet now he hath reconciled in the body of his flesh through death, to present you holy and unspotted and blameless before him:

** Colossians 1:23

If so ye continue in the faith, grounded and settled, and immoveable from the hope of the gospel which you have heard, which is preached in all the creation that is under heaven: whereof I Paul am made a minister.

** Colossians 1:24

Who now rejoice in my sufferings for you and fill up those things that are wanting of the sufferings of Christ, in my flesh, for his body, which is the church:

** Colossians 1:25

Whereof I am made a minister according to the dispensation of God, which is given me towards you, that I may fulfil the word of God:

** Colossians 1:26

The mystery which hath been hidden from ages and generations, but now is manifested to his saints,

** Colossians 1:27

To whom God would make known the riches of the glory of this mystery among the Gentiles, which is Christ, in you the hope of glory.

** Colossians 1:28

Whom we preach, admonishing every man and teaching every man in all wisdom, that we may present every man perfect in Christ Jesus.

** Colossians 1:29

Wherein also I labour, striving according to his working which he worketh in me in power. 

* Colossians 2

** Colossians 2:1

For I would have you know what manner of care I have for you and for them that are at Laodicea and whosoever have not seen my face in the flesh:

** Colossians 2:2

That their hearts may be comforted, being instructed in charity and unto all riches of fulness of understanding, unto the knowledge of the mystery of God the Father and of Christ Jesus:

** Colossians 2:3

In whom are hid all the treasures of wisdom and knowledge.

** Colossians 2:4

Now this I say, that no man may deceive you by loftiness of words.

** Colossians 2:5

For though I be absent in body, yet in spirit I am with you, rejoicing, and beholding your order and the steadfastness of your faith which is in Christ.

** Colossians 2:6

As therefore you have received Jesus Christ the Lord, walk ye in him:

** Colossians 2:7

Rooted and built up in him and confirmed in the faith, as also you have learned: abounding in him in thanksgiving.

** Colossians 2:8

Beware lest any man cheat you by philosophy and vain deceit: according to the tradition of men according to the elements of the world and not according to Christ.

** Colossians 2:9

For in him dwelleth all the fulness of the Godhead corporeally.

** Colossians 2:10

And you are filled in him, who is the head of all principality and power.

** Colossians 2:11

In whom also you are circumcised with circumcision not made by hand in despoiling of the body of the flesh: but in the circumcision of Christ.

** Colossians 2:12

Buried with him in baptism: in whom also you are risen again by the faith of the operation of God who hath raised him up from the dead.

** Colossians 2:13

And you, when you were dead in your sins and the uncircumcision of your flesh, he hath quickened together with him, forgiving you all offences:

** Colossians 2:14

Blotting out the handwriting of the decree that was against us, which was contrary to us. And he hath taken the same out of the way, fastening it to the cross.

** Colossians 2:15

And despoiling the principalities and powers, he hath exposed them confidently in open shew, triumphing over them in himself.

** Colossians 2:16

Let no man therefore judge you in meat or in drink or in respect of a festival day or of the new moon or of the sabbaths,

** Colossians 2:17

Which are a shadow of things to come: but the body is of Christ.

** Colossians 2:18

Let no man seduce you, willing in humility and religion of angels, walking in the things which he hath not seen, in vain puffed up by the sense of his flesh:

** Colossians 2:19

And not holding the head, from which the whole body, by joints and bands, being supplied with nourishment and compacted, groweth into the increase of God.

** Colossians 2:20

If then you be dead with Christ from the elements of this world, why do you yet decree as though living in the world?

** Colossians 2:21

Touch not: taste not: handle not.

** Colossians 2:22

Which all are unto destruction by the very use, according to the precepts and doctrines of men.

** Colossians 2:23

Which things have indeed a shew of wisdom in superstition and humility, and not sparing the body; not in any honour to the filling of the flesh. 

* Colossians 3

** Colossians 3:1

Therefore if you be risen with Christ, seek the things that are above, where Christ is sitting at the right hand of God.

** Colossians 3:2

Mind the things that are above, not the things that are upon the earth.

** Colossians 3:3

For you are dead: and your life is hid with Christ in God.

** Colossians 3:4

When Christ shall appear, who is your life, then you also shall appear with him in glory.

** Colossians 3:5

Mortify therefore your members which are upon the earth: fornication, uncleanness, lust, evil concupiscence and covetousness, which is the service of idols.

** Colossians 3:6

For which things the wrath of God cometh upon the children of unbelief.

** Colossians 3:7

In which you also walked some time, when you lived in them.

** Colossians 3:8

But now put you also all away: anger, indignation, malice, blasphemy, filthy speech out of your mouth.

** Colossians 3:9

Lie not one to another: stripping yourselves of the old man with his deeds,

** Colossians 3:10

And putting on the new, him who is renewed unto knowledge, according to the image of him that created him.

** Colossians 3:11

Where there is neither Gentile nor Jew, circumcision nor uncircumcision, Barbarian nor Scythian, bond nor free. But Christ is all and in all.

** Colossians 3:12

Put ye on therefore, as the elect of God, holy and beloved, the bowels of mercy, benignity, humility, modesty, patience:

** Colossians 3:13

Bearing with one another and forgiving one another, if any have a complaint against another. Even as the Lord hath forgiven you, so do you also.

** Colossians 3:14

But above all these things have charity, which is the bond of perfection.

** Colossians 3:15

And let the peace of Christ rejoice in your hearts, wherein also you are called in one body: and be ye thankful.

** Colossians 3:16

Let the word of Christ dwell in you abundantly: in all wisdom, teaching and admonishing one another in psalms, hymns and spiritual canticles, singing in grace in your hearts to God.

** Colossians 3:17

All whatsoever you do in word or in work, do all in the name of the Lord Jesus Christ, giving thanks to God and the Father by him.

** Colossians 3:18

Wives, be subject to your husbands, as it behoveth in the Lord.

** Colossians 3:19

Husbands, love your wives and be not bitter towards them.

** Colossians 3:20

Children, obey your parents in all things: for this is well pleasing to the Lord.

** Colossians 3:21

Fathers, provoke not your children to indignation, lest they be discouraged.

** Colossians 3:22

Servants, obey in all things your masters according to the flesh: not serving to the eye, as pleasing men: but in simplicity of heart, fearing God.

** Colossians 3:23

Whatsoever you do, do it from the heart, as to the Lord, and not to men:

** Colossians 3:24

Knowing that you shall receive of the Lord the reward of inheritance. Serve ye the Lord Christ.

** Colossians 3:25

For he that doth wrong shall receive for that which he hath done wrongfully. And there is no respect of persons with God. 

* Colossians 4

** Colossians 4:1

Masters, do to your servants that which is just and equal: knowing that you also have a master in heaven.

** Colossians 4:2

Be instant in prayer: watching in it with thanksgiving.

** Colossians 4:3

Praying withal for us also, that God may open unto us a door of speech to speak the mystery of Christ (for which also I am bound):

** Colossians 4:4

That I may make it manifest as I ought to speak.

** Colossians 4:5

Walk with wisdom towards them that are without, redeeming the time.

** Colossians 4:6

Let your speech be always in grace seasoned with salt: that you may know how you ought to answer every man.

** Colossians 4:7

All the things that concern me, Tychicus, our dearest brother and faithful minister and fellow servant in the Lord, will make known to you.

** Colossians 4:8

What I have sent to you for this same purpose, that he may know the things that concern you and comfort your hearts:

** Colossians 4:9

With Onesimus, a most beloved and faithful brother, who is one of you. All things that are done here, they shall make known to you.

** Colossians 4:10

Aristarchus, my fellow prisoner, saluteth you: and Mark, the cousin german of Barnabas, touching whom you have received commandments. If he come unto you, receive him.

** Colossians 4:11

And Jesus that is called Justus: who are of the circumcision. These only are my helpers, in the kingdom of God: who have been a comfort to me.

** Colossians 4:12

Epaphras saluteth you, who is one of you, a servant of Christ Jesus, who is always solicitous for you in prayers, that you may stand perfect and full in all the will of God.

** Colossians 4:13

For I bear him testimony that he hath much labour for you and for them that are at Laodicea and them at Hierapolis.

** Colossians 4:14

Luke, the most dear physician, saluteth you: and Demas.

** Colossians 4:15

Salute the brethren who are at Laodicea: and Nymphas and the church that is in his house.

** Colossians 4:16

And when this epistle shall have been read with you, cause that it be read also in the church of the Laodiceans: and that you read that which is of the Laodiceans.

** Colossians 4:17

And say to Archippus: Take heed to the ministry which thou hast received in the Lord, that thou fulfil it.

** Colossians 4:18

The salutation of Paul with my own hand. Be mindful of my bands. Grace be with you. Amen.  

