* Exodus 1

** Exodus 1:1

These are the names of the children of Israel, that went into Egypt with Jacob: they went in every man with his household:

** Exodus 1:2

Ruben, Simeon, Levi, Juda,

** Exodus 1:3

Issachar, Zabulon, and Benjamin,

** Exodus 1:4

Dan, and Nephthali, Gad and Aser.

** Exodus 1:5

And all the souls that came out of Jacob's thigh, were seventy: but Joseph was in Egypt.

** Exodus 1:6

After he was dead, and all his brethren, and all that generation,

** Exodus 1:7

The children of Israel increased, and sprung up into multitudes, and growing exceedingly strong they filled the land.

** Exodus 1:8

In the mean time there arose a new king over Egypt, that knew not Joseph:

** Exodus 1:9

And he said to his people: Behold the people of the children of Israel are numerous and stronger than we.

** Exodus 1:10

Come let us wisely oppress them, lest they multiply: and if any war shall rise against us, join with our enemies, and having overcome us, depart out of the land.

** Exodus 1:11

Therefore he set over them masters of the works, to afflict them with burdens: and they built for Pharao cities of tabernacles, Phithom, and Ramesses.

** Exodus 1:12

But the more they oppressed them, the more they were multiplied and increased.

** Exodus 1:13

And the Egyptians hated the children of Israel, and afflicted them and mocked them:

** Exodus 1:14

And they made their life bitter with hard works in clay and brick, and with all manner of service, wherewith they were overcharged in the works of the earth.

** Exodus 1:15

And the king of Egypt spoke to the midwives of the Hebrews: of whom one was called Sephora, the other Phua,

** Exodus 1:16

Commanding them: When you shall do the office of midwives to the Hebrew women, and the time of delivery is come: if it be a man child, kill it: if a woman, keep it alive.

** Exodus 1:17

But the midwives feared God, and did not do as the king of Egypt had commanded, but saved the men children.

** Exodus 1:18

And the king called for them and said: What is it that you meant to do, that you would save the men children?

** Exodus 1:19

They answered: The Hebrew women are not as the Egyptian women: for they themselves are skilful in the office of a midwife; and they are delivered before we come to them.

** Exodus 1:20

Therefore God dealt well with the midwives: and the people multiplied and grew exceedingly strong.

** Exodus 1:21

And because the midwives feared God, he built them houses.

** Exodus 1:22

Pharao therefore charged all his people, saying: Whatsoever shall be born of the male sex, ye shall cast into the river: whatsoever of the female, ye shall save alive. 

* Exodus 2

** Exodus 2:1

After this there went a man of the house of Levi; and took a wife of his own kindred.

** Exodus 2:2

And she conceived, and bore a son: and seeing him a goodly child, hid him three months.

** Exodus 2:3

And when she could hide him no longer, she took a basket made of bulrushes, and daubed it with slime and pitch: and put the little babe therein, and laid him in the sedges by the river's brink,

** Exodus 2:4

His sister standing afar off, and taking notice what would be done.

** Exodus 2:5

And behold the daughter of Pharao came down to wash herself in the river: and her maids walked by the river's brink. And when she saw the basket in the sedges she sent one of her maids for it: and when it was brought,

** Exodus 2:6

She opened it, and seeing within it an infant crying, having compassion on it, she said: This is one of the babes of the Hebrews.

** Exodus 2:7

And the child's sister said to her: Shall I go, and call to thee a Hebrew woman, to nurse the babe?

** Exodus 2:8

She answered: Go. The maid went and called her mother.

** Exodus 2:9

And Pharao's daughter said to her: Take this child, and nurse him for me: I will give thee thy wages. The woman took and nursed the child: and when he was grown up, she delivered him to Pharao's daughter.

** Exodus 2:10

And she adopted him for a son, and called him Moses, saying: Because I took him out of the water.

** Exodus 2:11

In those days, after Moses was grown up, he went out to his brethren: and saw their affliction, and an Egyptian striking one of the Hebrews, his brethren.

** Exodus 2:12

And when he had looked about this way and that way, and saw no one there, he slew the Egyptian and hid him in the sand.

** Exodus 2:13

And going out the next day, he saw two Hebrews quarrelling: and he said to him that did the wrong: Why strikest thou thy neighbour?

** Exodus 2:14

But he answered: Who hath appointed thee prince and judge over us? wilt thou kill me, as thou didst yesterday kill the Egyptian? Moses feared, and said: How is this come to be known?

** Exodus 2:15

And Pharao heard of this word, and sought to kill Moses: but he fled from his sight, and abode in the land of Madian, and he sat down by a well.

** Exodus 2:16

And the priest of Madian had seven daughters, who came to draw water: and when the troughs were filled, desired to water their father's flocks.

** Exodus 2:17

And the shepherds came and drove them away: and Moses arose, and defending the maids, watered their sheep.

** Exodus 2:18

And when they returned to Raguel their father, he said to them: Why are ye come sooner than usual?

** Exodus 2:19

They answered: A man of Egypt delivered us from the hands of the shepherds: and he drew water also with us, and gave the sheep to drink.

** Exodus 2:20

But he said: Where is he? why have you let the man go? call him that he may eat bread.

** Exodus 2:21

And Moses swore that he would dwell with him. And he took Sephora his daughter to wife:

** Exodus 2:22

And she bore him a son, whom he called Gersam, saying: I have been a stranger in a foreign country. And she bore another, whom he called Eliezer, saying: For the God of my father, my helper, hath delivered me out of the hand of Pharao.

** Exodus 2:23

Now after a long time the king of Egypt died: and the children of Israel groaning, cried out because of the works: and their cry went up unto God from the works.

** Exodus 2:24

And he heard their groaning, and remembered the covenant which he made with Abraham, Isaac, and Jacob.

** Exodus 2:25

And the Lord looked upon the children of Israel, and he knew them. 

* Exodus 3

** Exodus 3:1

Now Moses fed the sheep of Jethro, his father in law, the priest of Madian: and he drove the flock to the inner parts of the desert, and came to the mountain of God, Horeb.

** Exodus 3:2

And the Lord appeared to him in a flame of fire out of the midst of a bush: and he saw that the bush was on fire, and was not burnt.

** Exodus 3:3

And Moses said: I will go, and see this great sight, why the bush is not burnt.

** Exodus 3:4

And when the Lord saw that he went forward to see, he called to him out of the midst of the bush. and said: Moses, Moses. And he answered: Here I am.

** Exodus 3:5

And he said: Come not nigh hither, put off the shoes from thy feet; for the place, whereon thou standest, is holy ground.

** Exodus 3:6

And he said: I am the God of thy father, the God of Abraham, the God of Isaac, and the God of Jacob. Moses hid his face: for he durst not look at God.

** Exodus 3:7

And the Lord said to him: I have seen the affliction of my people in Egypt, and I have heard their cry because of the rigour of them that are over the works;

** Exodus 3:8

And knowing their sorrow, I am come down to deliver them out of the hands of the Egyptians, and to bring them out of that land into a good and spacious land, into a land that floweth with milk and honey, to the places of the Chanaanite, and Hethite, and Amorrhite, and Pherezite, and Hevite, and Jebusite.

** Exodus 3:9

For the cry of the children of Israel is come unto me: and I have seen their affliction, wherewith they are oppressed by the Egyptians.

** Exodus 3:10

But come, and I will send thee to Pharao, that thou mayst bring forth my people, the children of Israel, out of Egypt.

** Exodus 3:11

And Moses said to God: Who am I that I should go to Pharao, and should bring forth the children of Israel out of Egypt?

** Exodus 3:12

And he said to him: I will be with thee; and this thou shalt have for a sign that I have sent thee: When thou shalt have brought my people out of Egypt, thou shalt offer sacrifice to God upon this mountain.

** Exodus 3:13

Moses said to God: Lo, I shall go to the children of Israel, and say to them: The God of your fathers hath sent me to you. If they shall say to me: What is his name? What shall I say to them?

** Exodus 3:14

God said to Moses: I AM WHO AM. He said: Thus shalt thou say to the children of Israel: HE WHO IS, hath sent me to you.

** Exodus 3:15

And God said again to Moses: Thus shalt thou say to the children of Israel: The Lord God of your fathers the God of Abraham, the God of Isaac, and the God of Jacob hath sent me to you; this is my name for ever, and this is my memorial unto all generations.

** Exodus 3:16

Go and gather together the ancients of Israel, and thou shalt say to them: The Lord God of your fathers, the God of Abraham, the God of Isaac, and the God of Jacob, hath appeared to me, saying: Visiting I have visited you; and I have seen all that hath befallen you in Egypt.

** Exodus 3:17

And I have said the word to bring you forth out of the affliction of Egypt, into the land of the Chanaanite, and Hethite, and Amorrhite, and Pherezite, and Hevite, and Jebusite, to a land that floweth with milk and honey.

** Exodus 3:18

And they shall hear thy voice; and thou shalt go in, thou and the ancients of Israel, to the king of Egypt, and thou shalt say to him: The Lord God of the Hebrews hath called us; we will go three days' journey into the wilderness, to sacrifice unto the Lord our God.

** Exodus 3:19

But I know that the king of Egypt will not let you go, but by a mighty hand.

** Exodus 3:20

For I will stretch forth my hand, and will strike Egypt with all my wonders which I will do in the midst of them: after these he will let you go.

** Exodus 3:21

And I will give favour to this people, in the sight of the Egyptians: and when you go forth, you shall not depart empty:

** Exodus 3:22

But every woman shall ask of her neighbour, and of her that is in her house, vessels of silver and of gold, and raiment: and you shall put them on your sons and daughters, and shall spoil Egypt. 

* Exodus 4

** Exodus 4:1

Moses answered, and said: They will not believe me, nor hear my voice, but they will say: The Lord hath not appeared to thee.

** Exodus 4:2

Then he said to him: What is that thou holdest in thy hand? He answered: A rod.

** Exodus 4:3

And the Lord said: Cast it down upon the ground. He cast it down, and it was turned into a serpent, so that Moses fled from it.

** Exodus 4:4

And the Lord said: Put out thy hand, and take it by the tail. He put forth his hand, and took hold of it, and it was turned into a rod.

** Exodus 4:5

That they may believe, saith he, that the Lord God of their fathers, the God of Abraham, the God of Isaac, and the God of Jacob, hath appeared to thee.

** Exodus 4:6

And the Lord said again: Put thy hand into thy bosom. And when he had put it into his bosom, he brought it forth leprous as snow.

** Exodus 4:7

And he said: Put back thy hand into thy bosom. He put it back, and brought it out again, and it was like the other flesh.

** Exodus 4:8

If they will not believe thee, saith he, nor hear the voice of the former sign, they will believe the word of the latter sign.

** Exodus 4:9

But if they will not even believe these two signs, nor hear thy voice: take of the river water, and pour it out upon the dry land, and whatsoever thou drawest out of the river, shall be turned into blood.

** Exodus 4:10

Moses said: I beseech thee, Lord, I am not eloquent from yesterday and the day before; and since thou hast spoken to thy servant, I have more impediment and slowness of tongue.

** Exodus 4:11

The Lord said to him: Who made man's mouth? or who made the dumb and the deaf, the seeing and the blind? did not I?

** Exodus 4:12

Go therefore, and I will be in thy mouth; and I will teach thee what thou shalt speak.

** Exodus 4:13

But he said: I beseech thee, Lord, send whom thou wilt send.

** Exodus 4:14

The Lord being angry at Moses, said: Aaron the Levite is thy brother, I know that he is eloquent: behold he cometh forth to meet thee, and seeing thee, shall be glad at heart.

** Exodus 4:15

Speak to him, and put my words in his mouth: and I will be in thy mouth, and in his month, and will shew you what you must do.

** Exodus 4:16

He shall speak in thy stead to the people, and shall be thy mouth: but thou shalt be to him in those things that pertain to God.

** Exodus 4:17

And take this rod in thy hand. wherewith thou shalt do the signs.

** Exodus 4:18

Moses went his way, and returned to Jethro his father in law, and said to him; I will go and return to my brethren into Egypt, that I may see if they be yet alive. And Jethro said to him: Go in peace.

** Exodus 4:19

And the Lord said to Moses, in Madian: Go, and return into Egypt; for they are all dead that sought thy life.

** Exodus 4:20

Moses therefore took his wife, and his sons, and set them upon an ass; and returned into Egypt, carrying the rod of God in his hand.

** Exodus 4:21

And the Lord said to him as he was returning into Egypt: See that thou do all the wonders before Pharao, which I have put in thy hand: I shall harden his heart, and he will not let the people go.

** Exodus 4:22

And thou shalt say to him: Thus saith the Lord: Israel is my son, my firstborn.

** Exodus 4:23

I have said to thee: Let my son go, that he may serve me, and thou wouldst not let him go: behold I will kill thy son, thy firstborn.

** Exodus 4:24

And when he was in his journey, in the inn, the Lord met him, and would have killed him.

** Exodus 4:25

Immediately Sephora took a very sharp stone, and circumcised the foreskin of her son, and touched his feet, and said: A bloody spouse art thou to me.

** Exodus 4:26

And he let him go after she had said: A bloody spouse art thou to me, because of the circumcision.

** Exodus 4:27

And the Lord said to Aaron: Go into the desert to meet Moses. And he went forth to meet him in the mountain of God, and kissed him.

** Exodus 4:28

And Moses told Aaron all the words of the Lord, by which he had sent him, and the signs that he had commanded.

** Exodus 4:29

And they came together, and they assembled all the ancients of the children of Israel.

** Exodus 4:30

And Aaron spoke all the words which the Lord had said to Moses: and he wrought the signs before the people.

** Exodus 4:31

And the people believed. And they heard that the Lord had visited the children of Israel, and that he had looked upon their affliction: and falling down they adored. 

* Exodus 5

** Exodus 5:1

After these things, Moses and Aaron went in, and said to Pharao: Thus saith the Lord God of Israel: Let my people go, that they may sacrifice to me in the desert.

** Exodus 5:2

But he answered: Who is the Lord, that I should hear his voice, and let Israel go? I know not the Lord, neither will I let Israel go.

** Exodus 5:3

And they said: The God of the Hebrews hath called us, to go three days' journey into the wilderness, and to sacrifice to the Lord our God; lest a pestilence or the sword fall upon us.

** Exodus 5:4

The king of Egypt said to them: Why do you Moses and Aaron draw off the people from their works? Get you gone to your burdens.

** Exodus 5:5

And Pharao said: The people of the land are numerous; you see that the multitude is increased; how much more if you give them rest from their works?

** Exodus 5:6

Therefore he commanded the same day the overseers of the works, and the task-masters of the people, saying:

** Exodus 5:7

You shall give straw no more to the people to make brick, as before; but let them go and gather straw.

** Exodus 5:8

And you shall lay upon them the task of bricks, which they did before; neither shall you diminish any thing thereof, for they are idle, and therefore they cry. saying: Let us go and sacrifice to our God.

** Exodus 5:9

Let them be oppressed with works, and let them fulfil them; that they may not regard lying words.

** Exodus 5:10

And the overseers of the works, and the taskmasters, went out and said to the people: Thus saith Pharao: I allow you no straw;

** Exodus 5:11

Go, and gather it where you can find it; neither shall any thing of your work be diminished.

** Exodus 5:12

And the people was scattered through all the land of Egypt to gather straw.

** Exodus 5:13

And the overseers of the works pressed them, saying: Fulfil your work every day, as before ye were wont to do, when straw was given you.

** Exodus 5:14

And they that were over the works of the children of Israel, were scourged by Pharao's taskmasters, saying: Why have you not made up the task of bricks, both yesterday and to day, as before?

** Exodus 5:15

And the officers of the children of Israel came, and cried out to Pharao, saying: Why dealest thou so with thy servants?

** Exodus 5:16

Straw is not given us, and bricks are required of us as before; behold we, thy servants, are beaten with whips, and thy people is unjustly dealt withal.

** Exodus 5:17

And he said: You are idle, and therefore you say: Let us go and sacrifice to the Lord.

** Exodus 5:18

Go therefore and work: straw shall not be given you, and you shall deliver the accustomed number of bricks.

** Exodus 5:19

And the officers of the children of Israel saw that they were in evil case, because it was said to them: There shall not a whit be diminished of the bricks for every day.

** Exodus 5:20

And they met Moses and Aaron, who stood over against them as they came out from Pharao:

** Exodus 5:21

And they said to them: The Lord see and judge, because you have, made our savour to stink before Pharao and his servants, and you have given him a sword, to kill us.

** Exodus 5:22

And Moses returned to the Lord, and said: Lord, why hast thou afflicted this people? wherefore hast thou sent me?

** Exodus 5:23

For since the time that I went in to Pharao to speak in thy name, he hath afflicted thy people: and thou hast not delivered them. 

* Exodus 6

** Exodus 6:1

And the Lord said to Moses: Now thou shalt see what I will do to Pharao: for by a mighty hand shall he let them go, and with a strong hand shall he cast them out of his land.

** Exodus 6:2

And the Lord spoke to Moses, saying: I am the Lord

** Exodus 6:3

That appeared to Abraham, to Isaac, and to Jacob, by the name of God Almighty: and my name ADONAI I did not shew them.

** Exodus 6:4

And I made a covenant with them, to give them the land of Chanaan, the land of their pilgrimage wherein they were strangers.

** Exodus 6:5

I have heard the groaning of the children of Israel, wherewith the Egyptians have oppressed them: and I have remembered my covenant.

** Exodus 6:6

Therefore say to the children of Israel: I am the Lord who will bring you out from the work-prison of the Egyptians, and will deliver you from bondage: and redeem you with a high arm, and great judgments.

** Exodus 6:7

And I will take you to myself for my people, I will be your God: and you shall know that I am the Lord your God, who brought you out from the work-prison of the Egyptians:

** Exodus 6:8

And brought you into the land, concerning which I lifted up my hand to give it to Abraham, Isaac, and Jacob: and I will give it you to possess: I am the Lord.

** Exodus 6:9

And Moses told all this to the children of Israel: but they did not hearken to him, for anguish of spirit, and most painful work.

** Exodus 6:10

And the Lord spoke to Moses, saying:

** Exodus 6:11

Go in, and speak to Pharao king of Egypt, that he let the children of Israel go out of his land.

** Exodus 6:12

Moses answered before the Lord: Behold the children of Israel do not hearken to me: and how will Pharao hear me, especially as I am of uncircumcised lips?

** Exodus 6:13

And the Lord spoke to Moses and Aaron, and he gave them a charge unto the children of Israel, and unto Pharao the king of Egypt, that they should bring forth the children of Israel out of the land of Egypt.

** Exodus 6:14

These are the heads of their houses by their families. The sons of Ruben the firstborn of Israel: Henoch and Phallu, Hesron and Charmi.

** Exodus 6:15

These are the kindreds of Ruben. The sons of Simeon, Jamuel and Jamin, and Ahod, and Jachin, and Soar, and Saul the son of a Chanaanitess: these are the families of Simeon.

** Exodus 6:16

And these are the names of the sons of Levi by their kindreds: Gerson, and Caath, and Merari. And the years of the life of Levi were a hundred and thirty-seven.

** Exodus 6:17

The sons of Gerson: Lobni and Semei, by their kindreds.

** Exodus 6:18

The sons of Caath: Amram, and Isaar, and Hebron and Oziel. And the years of Caath's life, were a hundred and thirty-three.

** Exodus 6:19

The sons of Merari: Moholi and Musi. These are the kindreds of Levi by their families.

** Exodus 6:20

And Amram took to wife Jochabed his aunt by the father's side: and she bore him Aaron and Moses. And the years of Amram's life, were a hundred and thirty-seven.

** Exodus 6:21

The sons also of Isaar: Core, and Nepheg, and Zechri.

** Exodus 6:22

The sons also of Oziel: Mizael, and Elizaphan, and Sethri.

** Exodus 6:23

And Aaron took to wife Elizabeth the daughter of Aminadab, sister of Nahason, who bore him Nadab, and Abiu, and Eleazar, and Ithamar.

** Exodus 6:24

The sons also of Core: Aser, and Elcana, and Abiasaph. These are the kindreds of the Corites.

** Exodus 6:25

But Eleazar the son of Aaron took a wife of the daughters of Phutiel: and she bore him Phinees. These are the heads of the Levitical families by their kindreds.

** Exodus 6:26

These are Aaron and Moses, whom the Lord commanded to bring forth the children of Israel out of the land of Egypt by their companies.

** Exodus 6:27

These are they that speak to Pharao, king of Egypt, in order to bring out the children of Israel from Egypt: these are that Moses and Aaron,

** Exodus 6:28

In the day when the Lord spoke to Moses in the land of Egypt.

** Exodus 6:29

And the Lord spoke to Moses, saying: I am the Lord; speak thou to Pharao, king of Egypt, all that I say to thee.

** Exodus 6:30

And Moses said before the Lord: Lo I am of uncircumcised lips, how will Pharao hear me? 

* Exodus 7

** Exodus 7:1

And the Lord said to Moses: Behold, I have appointed thee the god of Pharao; and Aaron, thy brother, shall be thy prophet.

** Exodus 7:2

Thou shalt speak to him all that I command thee; and he shall speak to Pharao, that he let the children of Israel go out of his land.

** Exodus 7:3

But I shall harden his heart, and shall multiply my signs and wonders in the land of Egypt.

** Exodus 7:4

And he will not hear you: and I will lay my hand upon Egypt, and will bring forth my army and my people, the children of Israel, out of the land of Egypt, by very great judgments.

** Exodus 7:5

And the Egyptians shall know that I am the Lord, who have stretched forth my hand upon Egypt, and have brought forth the children of Israel out of the midst of them.

** Exodus 7:6

And Moses and Aaron did as the Lord had commanded; so did they.

** Exodus 7:7

And Moses was eighty years old, and Aaron eighty-three, when they spoke to Pharao.

** Exodus 7:8

And the Lord said to Moses and Aaron:

** Exodus 7:9

When Pharao shall say to you, Shew signs; thou shalt say to Aaron: Take thy rod, and cast it down before Pharao, and it shall be turned into a serpent.

** Exodus 7:10

So Moses and Aaron went in unto Pharao, and did as the Lord had commanded. And Aaron took the rod before Pharao and his servants, and it was turned into a serpent.

** Exodus 7:11

And Pharao called the wise men and the magicians; and they also by Egyptian enchantments and certain secrets, did in like manner.

** Exodus 7:12

And they every one cast down their rods, and they were turned into serpents: but Aaron's rod devoured their rods.

** Exodus 7:13

And Pharao's heart was hardened, and he did not hearken to them, as the Lord had commanded.

** Exodus 7:14

And the Lord said to Moses: Pharao's heart is hardened, he will not let the people go.

** Exodus 7:15

Go to him in the morning, behold he will go out to the waters: and thou shalt stand to meet him on the ' bank of the river: and thou shalt take in thy hand the rod that was turned into a serpent.

** Exodus 7:16

And thou shalt say to him: The Lord God of the Hebrews sent me to thee, saying: Let my people go to sacrifice to me in the desert: and hitherto thou wouldst not hear.

** Exodus 7:17

Thus therefore saith the Lord: In this thou shalt know that I am the Lord: behold I will strike with the rod, that is in my hand, the water of the river, and it shall be turned into blood.

** Exodus 7:18

And the fishes that are in the river, shall die, and the waters shall be corrupted, and the Egyptians shall be afflicted when they drink the water of the river.

** Exodus 7:19

The Lord also said to Moses: Say to Aaron, Take thy rod; and stretch forth thy hand upon the waters of Egypt, and upon their rivers, and streams and pools, and all the ponds of waters, that they may be turned into blood: and let blood be in all the land of Egypt, both in vessels of wood and of stone.

** Exodus 7:20

And Moses and Aaron did as the Lord had commanded: and lifting up the rod, he struck the water of the river before Pharao and his servants: and it was turned into blood.

** Exodus 7:21

And the fishes that were in the river died; and the river corrupted, and the Egyptians could not drink the water of the river, and there was blood in all the land of Egypt.

** Exodus 7:22

And the magicians of the Egyptians with their enchantments did in like manner; and Pharao's heart was hardened, neither did he hear them, as the Lord had commanded.

** Exodus 7:23

And he turned himself away, and went into his house, neither did he set his heart to it this time also.

** Exodus 7:24

And all the Egyptians dug round about the river for water to drink; for they could not drink of the water of the river.

** Exodus 7:25

And seven days were fully ended, after that the Lord struck the river. 

* Exodus 8

** Exodus 8:1

And the Lord said to Moses: Go in to Pharao, and thou shalt say to him: Thus saith the Lord: Let my people go to sacrifice to me.

** Exodus 8:2

But if thou wilt not let them go, behold I will strike all thy coasts with frogs.

** Exodus 8:3

And the river shall bring forth an abundance of frogs; which shall come up and enter into thy house, and thy bedchamber, and upon thy bed, and into the houses of thy servants, and to thy people, and into thy ovens, and into the remains of thy meats:

** Exodus 8:4

And the frogs shall come in to thee, and to thy people, and to all thy servants.

** Exodus 8:5

And the Lord said to Moses: Say to Aaron: Stretch forth thy hand upon the streams, and upon the rivers and the pools, and bring forth frogs upon the land of Egypt.

** Exodus 8:6

And Aaron stretched forth his hand upon the waters of Egypt, and the frogs came up, and covered the land of Egypt.

** Exodus 8:7

And the magicians also, by their enchantments, did in like manner, and they brought forth frogs upon the land of Egypt.

** Exodus 8:8

But Pharao called Moses and Aaron, and said to them: Pray ye to the Lord to take away the frogs from me and from my people; and I will let the people go to sacrifice to the Lord.

** Exodus 8:9

And Moses said to Pharao: Set me a time when I shall pray for thee, and for thy servants, and for thy people, that the frogs may be driven away from thee and from thy house, and from thy servants, and from thy people; and may remain only in the river.

** Exodus 8:10

And he answered: To morrow. But he said: I will do according to thy word; that thou mayest know that there is none like to the Lord our God.

** Exodus 8:11

And the frogs shall depart from thee, and from thy house, and from thy servants, and from thy people; and shall remain only in the river.

** Exodus 8:12

And Moses and Aaron went forth from Pharao: and Moses cried to the Lord for the promise, which he had made to Pharao concerning the frogs.

** Exodus 8:13

And the Lord did according to the word of Moses: and the frogs died out of the houses, and out of the villages, and out of the fields:

** Exodus 8:14

And they gathered them together into immense heaps, and the land was corrupted.

** Exodus 8:15

And Pharao seeing that rest was given, hardened his own heart, and did not hear them, as the Lord had commanded.

** Exodus 8:16

And the Lord said to Moses: Say to Aaron: Stretch forth thy rod, and strike the dust of the earth; and may there be sciniphs in all the land of Egypt.

** Exodus 8:17

And they did so. And Aaron stretched forth his hand, holding the rod; and he struck the dust of the earth, and there came sciniphs on men and on beasts: all the dust of the earth was turned into sciniphs through all the land of Egypt.

** Exodus 8:18

And the magicians with their enchantments practised in like manner, to bring forth sciniphs, and they could not: and there were sciniphs as well on men as on beasts.

** Exodus 8:19

And the magicians said to Pharao: This is the finger of God. And Pharao's heart was hardened, and he hearkened not unto them, as the Lord had commanded.

** Exodus 8:20

The Lord also said to Moses: Arise early, and stand before Pharao; for he will go forth to the waters: and thou shalt say to him: Thus saith the Lord: Let my people go to sacrifice to me.

** Exodus 8:21

But if thou wilt not let them go, behold I will send in upon thee, and upon thy servants, and upon thy houses, all kind of flies: and the houses of the Egyptians shall be filled with flies of divers kinds, and the whole land wherein they shall be.

** Exodus 8:22

And I will make the land of Gessen wonderful in that day, so that flies shall not be there: and thou shalt know that I am the Lord in the midst of the earth.

** Exodus 8:23

And I will put a division between my people and thy people: to morrow shall this sign be.

** Exodus 8:24

And the Lord did so. And there came a very grievous swarm of flies into the houses of Pharao and of his servants, and into all the land of Egypt: and the land was corrupted by this kind of flies.

** Exodus 8:25

And Pharao called Moses and Aaron, and said to them: Go and sacrifice to your God in this land.

** Exodus 8:26

And Moses said: It cannot be so: for we shall sacrifice the abominations of the Egyptians to the Lord our God: now if we kill those things which the Egyptians worship, in their presence, they will stone us.

** Exodus 8:27

We will go three days' journey into the wilderness; and we will sacrifice to the Lord our God, as he hath commanded us.

** Exodus 8:28

And Pharao said: I will let you go to sacrifice to the Lord your God in the wilderness, but go no farther: pray for me.

** Exodus 8:29

And Moses said: I will go out from thee, and will pray to the Lord: and the flies shall depart from Pharao, and from his servants, and from his people to morrow: but do not deceive any more, in not letting the people go to sacrifice to the Lord.

** Exodus 8:30

So Moses went out from Pharao, and prayed to the Lord.

** Exodus 8:31

And he did according to his word: and he took away the flies from Pharao, and from his servants, and from his people: there was not left so much as one.

** Exodus 8:32

And Pharao's heart was hardened, so that neither this time would he let the people go. 

* Exodus 9

** Exodus 9:1

And the Lord said to Moses: Go in to Pharao, and speak to him: Thus saith the Lord God of the Hebrews: Let my people go to sacrifice to me.

** Exodus 9:2

But if thou refuse, and withhold them still:

** Exodus 9:3

Behold my hand shall be upon thy fields; and a very grievous murrain upon thy horses, and asses, and camels, and oxen, and sheep.

** Exodus 9:4

And the Lord will make a wonderful difference between the possessions of Israel and the possessions of the Egyptians, that nothing at all shall die of those things that belong to the children of Israel.

** Exodus 9:5

And the Lord appointed a time, saying: To morrow will the Lord do this thing in the land.

** Exodus 9:6

The Lord therefore did this thing the next day: and all the beasts of the Egyptians died, but of the beasts of the children of Israel there died not one.

** Exodus 9:7

And Pharao sent to see; and there was not any thing dead of that which Israel possessed. And Pharao's heart was hardened, and he did not let the people go.

** Exodus 9:8

And the Lord said to Moses and Aaron: Take to you handfuls of ashes out of the chimney, and let Moses sprinkle it in the air in the presence of Pharao.

** Exodus 9:9

And be there dust upon all the land of Egypt: for there shall be boils and swelling blains both in men and beasts, in the whole land of Egypt.

** Exodus 9:10

And they took ashes out of the chimney, and stood before Pharao, and Moses sprinkled it in the air; and there came boils with swelling blains in men and beasts.

** Exodus 9:11

Neither could the magicians stand before Moses, for the boils that were upon them, and in all the land of Egypt.

** Exodus 9:12

And the Lord hardened Pharao's heart, and he hearkened not unto them, as the Lord had spoken to Moses.

** Exodus 9:13

And the Lord said to Moses: Arise in the morning, and stand before Pharao, and thou shalt say to him: Thus saith the Lord, the God of the Hebrews: Let my people go to sacrifice to me.

** Exodus 9:14

For I will at this time send all my plagues upon thy heart, and upon thy servants, and upon thy people; that thou mayst know that there is none like me in all the earth.

** Exodus 9:15

For now I will stretch out my hand to strike thee, and thy people, with pestilence, and thou shalt perish from the earth.

** Exodus 9:16

And therefore have I raised thee, that I may shew my power in thee, and my name may be spoken of throughout all the earth.

** Exodus 9:17

Dost thou yet hold back my people; and wilt thou not let them go?

** Exodus 9:18

Behold I will cause it to rain to morrow at this same hour, an exceeding great hail; such as hath not been in Egypt from the day that it was founded, until this present time.

** Exodus 9:19

Send therefore now presently, and gather together thy cattle, and all that thou hast in the field; for men and beasts, and all things that shall be found abroad, and not gathered together out of the fields which the hail shall fall upon, shall die.

** Exodus 9:20

He that feared the word of the Lord among Pharao's servants, made his servants and his cattle flee into houses:

** Exodus 9:21

But he that regarded not the word of the Lord, left his servants, and his cattle in the fields.

** Exodus 9:22

And the Lord said to Moses: Stretch forth thy hand towards heaven, that there may be hail in the whole land of Egypt upon men, and upon beasts, and upon every herb of the field in the land of Egypt.

** Exodus 9:23

And Moses stretched forth his rod towards heaven, and the Lord sent thunder and hail, and lightnings running along the ground: and the Lord rained hail upon the land of Egypt.

** Exodus 9:24

And the hail and fire mixt with it drove on together: and it was of so great bigness, as never before was seen in the whole land of Egypt since that nation was founded.

** Exodus 9:25

And the hail destroyed through all the land of Egypt all things that were in the fields, both man and beast: and the hail smote every herb of the field, and it broke every tree of the country.

** Exodus 9:26

Only in the land of Gessen, where the children of Israel were, the hail fell not.

** Exodus 9:27

And Pharao sent and called Moses and Aaron, saying to them: I have sinned this time also, the Lord is just: I and my people, are wicked.

** Exodus 9:28

Pray ye to the Lord that the thunderings of God and the hail may cease: that I may let you go, and that ye may stay here no longer.

** Exodus 9:29

Moses said: As soon as I am gone out of the city, I will stretch forth my hands to the Lord, and the thunders shall cease, and the hail shall be no more: that thou mayst know that the earth is the Lord's:

** Exodus 9:30

But I know that neither thou, nor thy servants do yet fear the Lord God.

** Exodus 9:31

The flax therefore, and the barley were hurt, because the barley was green, and the flax was now bolled;

** Exodus 9:32

But the wheat, and other winter corn were not hurt, because they were lateward.

** Exodus 9:33

And when Moses was gone from Pharao out of the city, he stretched forth his hands to the Lord: and the thunders and the hail ceased, neither did there drop any more rain upon the earth.

** Exodus 9:34

And Pharao seeing that the rain, and the hail, and the thunders were ceased, increased his sin:

** Exodus 9:35

And his heart was hardened, and the heart of his servants, and it was made exceeding hard: neither did he let the children of Israel go, as the Lord had commanded by the hand of Moses. 

* Exodus 10

** Exodus 10:1

And the Lord said to Moses: Go in to Pharao; for I have hardened his heart, and the heart of his servants: that I may work these my signs in him,

** Exodus 10:2

And thou mayst tell in the ears of thy sons, and of thy grandsons, how often I have plagued the Egyptians, and wrought my signs amongst them: and you may know that I am the Lord.

** Exodus 10:3

Therefore Moses and Aaron went in to Pharao, and said to him: Thus saith the Lord God of the Hebrews: How long refusest thou to submit to me? let my people go, to sacrifice to me.

** Exodus 10:4

But if thou resist, and wilt not let them go, behold I will bring in to-morrow the locusts into thy coasts;

** Exodus 10:5

To cover the face of the earth, that nothing thereof may appear, but that which the hail hath left may be eaten: for they shall feed upon all the trees that spring in the fields.

** Exodus 10:6

And they shall fill thy houses, and the houses of thy servants, and of all the Egyptians: such a number as thy fathers have not seen, nor thy grandfathers, from the time they were first upon the earth, until this present day. And he turned himself away, and went forth from Pharao.

** Exodus 10:7

And Pharao's servants said to him: How long shall we endure this scandal? Iet the men go to sacrifice to the Lord their God. Dost thou not see that Egypt is undone?

** Exodus 10:8

And they called back Moses, and Aaron, to Pharao; and he said to them: Go, sacrifice to the Lord your God: who are they that shall go?

** Exodus 10:9

Moses said: We will go with our young and old, with our sons and daughters, with our sheep and herds: for it is the solemnity of the Lord our God.

** Exodus 10:10

And Pharao answered: So be the Lord with you, as I shall let you and your children go: who can doubt but that you intend some great evil?

** Exodus 10:11

It shall not be so. but go ye men only, and sacrifice to the Lord: for this yourselves also desired. And immediately they were cast out from Pharao's presence.

** Exodus 10:12

And the Lord said to Moses: Stretch forth thy hand upon the land of Egypt unto the locust, that it come upon it, and devour every herb that is left after the hail.

** Exodus 10:13

And Moses stretched forth his rod upon the land of Egypt: and the Lord brought a burning wind all that day, and night; and when it was morning, the burning wind raised the locusts.

** Exodus 10:14

And they came up over the whole land of Egypt; and rested in all the coasts of the Egyptians, innumerable, the like as had not been before that time, nor shall be hereafter.

** Exodus 10:15

And they covered the whole face of the earth, wasting all things. And the grass of the earth was devoured, and what fruits soever were on the trees, which the hail had left; and there remained not any thing that was green on the trees, or in the herbs of the earth, in all Egypt.

** Exodus 10:16

Wherefore Pharao in haste called Moses and Aaron, and said to them: I have sinned against the Lord your God, and against you.

** Exodus 10:17

But now forgive me my sin this time also, and pray to the Lord your God, that he take away from me this death.

** Exodus 10:18

And Moses going forth from the presence of Pharao, prayed to the Lord:

** Exodus 10:19

And he made a very strong wind to blow from the west, and it took the locusts and cast them into the Red Sea: there remained not so much as one in all the coasts of Egypt.

** Exodus 10:20

And the Lord hardened Pharao's heart, neither did he let the children of Israel go.

** Exodus 10:21

And the Lord said to Moses: Stretch out thy hand towards heaven: and may there be darkness upon the land of Egypt so thick that it may be felt.

** Exodus 10:22

And Moses stretched forth his hand towards heaven: and there came horrible darkness in all the land of Egypt for three days.

** Exodus 10:23

No man saw his brother, nor moved himself out of the place where he was: but wheresoever the children of Israel dwelt, there was light.

** Exodus 10:24

And Pharao called Moses and Aaron, and said to them: Go, sacrifice to the Lord: let your sheep only, and herds remain, let your children go with you.

** Exodus 10:25

Moses said: Thou shalt give us also sacrifices and burnt-offerings, to the Lord our God.

** Exodus 10:26

All the flocks shall go with us; there shall not a hoof remain of them: for they are necessary for the service of the Lord our God: especially as we know not what must be offered, till we come to the very place.

** Exodus 10:27

And the Lord hardened Pharao's heart, and he would not let them go.

** Exodus 10:28

And Pharao said to Moses: Get thee from me, and beware thou see not my face any more: in what day soever thou shalt come in my sight, thou shalt die.

** Exodus 10:29

Moses answered: So shall it be as thou hast spoken, I will not see thy face anymore. 

* Exodus 11

** Exodus 11:1

And the Lord said to Moses: Yet one plague more will I bring upon Pharao and Egypt, and after that he shall let you go, and thrust you out.

** Exodus 11:2

Therefore thou shalt tell all the people, that every man ask of his friend, and every woman of her neighbour, vessels of silver and of gold.

** Exodus 11:3

And the Lord will give favour to his people in the sight of the Egyptians. And Moses was a very great man in the land of Egypt, in the sight of Pharao's servants, and of all the people.

** Exodus 11:4

And he said: Thus saith the Lord: At midnight I will enter into Egypt:

** Exodus 11:5

And every firstborn in the land of the Egyptians shall die, from the firstborn of Pharao who sitteth on his throne, even to the firstborn of the handmaid that is at the mill, and all the firstborn of beasts.

** Exodus 11:6

And there shall be a great cry in all the land of Egypt, such as neither hath been before, nor shall be hereafter.

** Exodus 11:7

But with all the children of Israel there shall not a dog make the least noise, from man even to beast; that you may know how wonderful a difference the Lord maketh between the Egyptians and Israel.

** Exodus 11:8

And all these thy servants shall come down to me, and shall worship me, saying: Go forth thou, and all the people that is under thee: after that we will go out.

** Exodus 11:9

And he went out from Pharao exceeding angry. But the Lord said to Moses: Pharao will not hear you, that many signs may be done in the land of Egypt.

** Exodus 11:10

And Moses and Aaron did all the wonders that are written, before Pharao. And the Lord hardened Pharao's heart, neither did he let the children of Israel go out of his land. 

* Exodus 12

** Exodus 12:1

And the Lord said to Moses and Aaron in the land of Egypt:

** Exodus 12:2

This month shall be to you the beginning of months; it shall be the first in the months of the year.

** Exodus 12:3

Speak ye to the whole assembly of the children of Israel, and say to them: On the tenth day of this month let every man take a lamb by their families and houses.

** Exodus 12:4

But if the number be less than may suffice to eat the lamb, he shall take unto him his neighbour that joineth to his house, according to the number of souls which may be enough to eat the lamb.

** Exodus 12:5

And it shall be a lamb without blemish, a male, of one year; according to which rite also you shall take a kid.

** Exodus 12:6

And you shall keep it until the fourteenth day of this month; and the whole multitude of the children of Israel shall sacrifice it in the evening.

** Exodus 12:7

And they shall take of the blood thereof, and put it upon both the side posts, and on the upper door posts of the houses, wherein they shall eat it.

** Exodus 12:8

And they shall eat the flesh that night roasted at the fire, and unleavened bread with wild lettuce.

** Exodus 12:9

You shall not eat thereof any thing raw, nor boiled in water, but only roasted at the fire; you shall eat the head with the feet and entrails thereof.

** Exodus 12:10

Neither shall there remain any thing of it until morning. If there be any thing left, you shall burn it with fire.

** Exodus 12:11

And thus you shall eat it: you shall gird your reins, and you shall have shoes on your feet, holding staves in your hands, and you shall eat in haste; for it is the Phase (that is the Passage) of the Lord.

** Exodus 12:12

And I will pass through the land of Egypt that night, and will kill every firstborn in the land of Egypt, both man and beast: and against all the gods of Egypt I will execute judgments; I am the Lord.

** Exodus 12:13

And the blood shall be unto you for a sign in the houses where you shall be; and I shall see the blood, and shall pass over you; and the plague shall not be upon you to destroy you, when I shall strike the land of Egypt.

** Exodus 12:14

And this day shall be for a memorial to you; and you shall keep it a feast to the Lord in your generations, with an everlasting observance.

** Exodus 12:15

Seven days shall you eat unleavened bread: in the first day there shall be no leaven in your houses; whosoever shall eat any thing leavened, from the first day until the seventh day, that soul shall perish out of Israel.

** Exodus 12:16

The first day shall be holy and solemn, and the seventh day shall be kept with the like solemnity: you shall do no work in them, except those things that belong to eating.

** Exodus 12:17

And you shall observe the feast of the unleavened bread: for in this same day I will bring forth your army out of the land of Egypt, and you shall keep this day in your generations by a perpetual observance.

** Exodus 12:18

The first month, the fourteenth day of the month, in the evening, you shall eat unleavened bread, until the one and twentieth day of the same month, in the evening.

** Exodus 12:19

Seven days there shall not be found any leaven in your houses: he that shall eat leavened bread, his soul shall perish out of the assembly of Israel, whether he be a stranger or born in the land.

** Exodus 12:20

You shall not eat any thing leavened: in all your habitations you shall eat unleavened bread.

** Exodus 12:21

And Moses called all the ancients of the children of Israel, and said to them: Go take a lamb by your families, and sacrifice the Phase.

** Exodus 12:22

And dip a bunch of hyssop in the blood that is at the door, and sprinkle the transom of the door therewith, and both the door cheeks: let none of you go out of the door of his house till morning.

** Exodus 12:23

For the Lord will pass through striking the Egyptians: and when he shall see the blood on the transom, and on both the posts, he will pass over the door of the house, and not suffer the destroyer to come into your houses and to hurt you.

** Exodus 12:24

Thou shalt keep this thing as a law for thee and thy children for ever.

** Exodus 12:25

And when you have entered into the land which the Lord will give you, as he hath promised, you shall observe these ceremonies.

** Exodus 12:26

And when your children shall say to you: What is the meaning of this service?

** Exodus 12:27

You shall say to them: It is the victim of the passage of the Lord, when he passed over the houses of the children of Israel in Egypt, striking the Egyptians, and saving our houses. And the people bowing themselves, adored.

** Exodus 12:28

And the children of Israel going forth, did as the Lord had commanded Moses and Aaron.

** Exodus 12:29

And it came to pass at midnight, the Lord slew every firstborn in the land of Egypt, from the firstborn of Pharao, who sat on his throne, unto the firstborn of the captive woman that was in the prison, and all the firstborn of cattle.

** Exodus 12:30

And Pharao arose in the night, and all his servants, and all Egypt: and there arose a great cry in Egypt; for there was not a house wherein there lay not one dead.

** Exodus 12:31

And Pharao calling Moses and Aaron, in the night, said: Arise and go forth from among my people, you and the children of Israel: go, sacrifice to the Lord as you say.

** Exodus 12:32

Your sheep and herds take along with you, as you demanded, and departing bless me.

** Exodus 12:33

And the Egyptians pressed the people to go forth out of the land speedily, saying: We shall all die.

** Exodus 12:34

The people therefore took dough before it was leavened; and tying it in their cloaks, put it on their shoulders.

** Exodus 12:35

And the children of Israel did as Moses had commanded: and they asked of the Egyptians vessels of silver and gold, and very much raiment.

** Exodus 12:36

And the Lord gave favour to the people in the sight of the Egyptians, so that they lent unto them: and they stripped the Egyptians.

** Exodus 12:37

And the children of Israel set forward from Ramesse to Socoth, being about six hundred thousand men on foot, beside children.

** Exodus 12:38

And a mixed multitude, without number, went up also with them, sheep and herds, and beasts of divers kinds, exceeding many.

** Exodus 12:39

And they baked the meal, which a little before they had brought out of Egypt in dough: and they made hearth cakes unleavened: for it could not be leavened, the Egyptians pressing them to depart, and not suffering them to make any stay; neither did they think of preparing any meat.

** Exodus 12:40

And the abode of the children of Israel that they made in Egypt, was four hundred and thirty years.

** Exodus 12:41

Which being expired, the same day all the army of the Lord went forth out of the land of Egypt.

** Exodus 12:42

This is the observable night of the Lord, when he brought them forth out of the land of Egypt: this night all the children of Israel must observe in their generations.

** Exodus 12:43

And the Lord said to Moses and Aaron: This is the service of the Phase; no foreigner shall eat of it.

** Exodus 12:44

But every bought servant shall be circumcised, and so shall eat.

** Exodus 12:45

The stranger and the hireling shall not eat thereof.

** Exodus 12:46

In one house shall it be eaten, neither shall you carry forth of the flesh thereof out of the house, neither shall you break a bone thereof.

** Exodus 12:47

All the assembly of the children of Israel shall keep it.

** Exodus 12:48

And if any stranger be willing to dwell among you, and to keep the Phase of the Lord, all his males shall first be circumcised, and then shall he celebrate it according to the manner: and he shall be as he that is born in the land: but if any man be uncircumcised, he shall not eat thereof.

** Exodus 12:49

The same law shall be to him that is born in the land, and to the proselyte that sojourneth with you.

** Exodus 12:50

And all the children of Israel did as the Lord had commanded Moses and Aaron.

** Exodus 12:51

And the same day the Lord brought forth the children of Israel out of the land of Egypt by their companies. 

* Exodus 13

** Exodus 13:1

And the Lord spoke to Moses, saying:

** Exodus 13:2

Sanctify unto me every firstborn that openeth the womb among the children of Israel, as well of men as of beasts: for they are all mine.

** Exodus 13:3

And Moses said to the people: Remember this day in which you came forth out of Egypt, and out of the house of bondage, for with a strong hand hath the Lord brought you forth out of this place: that you eat no leavened bread.

** Exodus 13:4

This day you go forth in the month of new corn.

** Exodus 13:5

And when the Lord shall have brought thee into the land of the Chanaanite, and the Hethite, and the Amorrhite, and the Hevite, and the Jebusite, which he swore to thy fathers that he would give thee, a land that floweth with milk and honey, thou shalt celebrate this manner of sacred rites in this month.

** Exodus 13:6

Seven days shalt thou eat unleavened bread: and on the seventh day shall be the solemnity of the Lord.

** Exodus 13:7

Unleavened bread shall you eat seven days: there shall not be seen any thing leavened with thee, nor in all thy coasts.

** Exodus 13:8

And thou shalt tell thy son in that day, saying: This is what the Lord did to me when I came forth out of Egypt.

** Exodus 13:9

And it shall be as a sign in thy hand, and as a memorial before thy eyes; and that the law of the Lord be always in thy mouth, for with a strong hand the Lord hath brought thee out of the land of Egypt.

** Exodus 13:10

Thou shalt keep this observance at the set time from days to days.

** Exodus 13:11

And when the Lord shall have brought thee into the land of the Chanaanite, as he swore to thee and thy fathers, and shall give it thee:

** Exodus 13:12

Thou shalt set apart all that openeth the womb for the Lord, and all that is first brought forth of thy cattle: whatsoever thou shalt have of the male sex, thou shalt consecrate to the Lord.

** Exodus 13:13

The firstborn of an ass thou shalt change for a sheep: and if thou do not redeem it, thou shalt kill it. And every firstborn of men thou shalt redeem with a price.

** Exodus 13:14

And when thy son shall ask thee to morrow, saying: What is this? thou shalt answer him: With a strong hand did the Lord bring us forth out of the land of Egypt, out of the house of bondage.

** Exodus 13:15

For when Pharao was hardened, and would not let us go, the Lord slew every firstborn in the land of Egypt, from the firstborn of man to the firstborn of beasts: therefore I sacrifice to the Lord all that openeth the womb of the male sex, and all the firstborn of my sons I redeem.

** Exodus 13:16

And it shall be as a sign in thy hand, and as a thing hung between thy eyes, for a remembrance: because the Lord hath brought us forth out of Egypt by a strong hand.

** Exodus 13:17

And when Pharao had sent out the people, the Lord led them not by the way of the land of the Philistines, which is near; thinking lest perhaps they would repent, if they should see wars arise against them, and would return into Egypt.

** Exodus 13:18

But he led them about by the way of the desert, which is by the Red Sea: and the children of Israel went up armed out of the land of Egypt.

** Exodus 13:19

And Moses took Joseph's bones with him: because he had adjured the children of Israel, saying: God shall visit you, carry out my bones from hence with you.

** Exodus 13:20

And marching from Socoth, they encamped in Etham, in the utmost coasts of the wilderness.

** Exodus 13:21

And the Lord went before them to shew the way, by day in a pillar of a cloud, and by night in a pillar of fire; that he might be the guide of their journey at both times.

** Exodus 13:22

There never failed the pillar of the cloud by day, nor the pillar of fire by night, before the people. 

* Exodus 14

** Exodus 14:1

And the Lord spoke to Moses, saying:

** Exodus 14:2

Speak to the children of Israel: Let them turn and encamp over against Phihahiroth, which is between Magdal and the sea over against Beelsephon: you shall encamp before it upon the sea.

** Exodus 14:3

And Pharao will say of the children of Israel: They are straitened in the land, the desert hath shut them in.

** Exodus 14:4

And I shall harden his heart and he will pursue you: and I shall be glorified in Pharao, and in all his army: and the Egyptians shall know that I am the Lord. And they did so.

** Exodus 14:5

And it was told the king of the Egyptians that the people was fled: and the heart of Pharao and of his servants was changed with regard to the people, and they said: What meant we to do, that we let Israel go from serving us?

** Exodus 14:6

So he made ready his chariot, and took all his people with him.

** Exodus 14:7

And he took six hundred chosen chariots, and all the chariots that were in Egypt: and the captains of the whole army.

** Exodus 14:8

And the Lord hardened the heart of Pharao, king of Egypt, and he pursued the children of Israel; but they were gone forth in a mighty hand.

** Exodus 14:9

And when the Egyptians followed the steps of them who were gone before, they found them encamped at the sea side: all Pharao's horse and chariots and the whole army were in Phihahiroth, before Beelsephon.

** Exodus 14:10

And when Pharao drew near, the children of Israel lifting up their eyes, saw the Egyptians behind them: and they feared exceedingly, and cried to the Lord.

** Exodus 14:11

And they said to Moses: Perhaps there were no graves in Egypt, therefore thou hast brought us to die in the wilderness: why wouldst thou do this, to lead us out of Egypt?

** Exodus 14:12

Is not this the word that we spoke to thee in Egypt, saying: Depart from us, that we may serve the Egyptians? for it was much better to serve them, than to die in the wilderness.

** Exodus 14:13

And Moses said to the people: Fear not: stand, and see the great wonders of the Lord, which he will do this day; for the Egyptians, whom you see now, you shall see no more for ever.

** Exodus 14:14

The Lord will fight for you, and you shall hold your peace.

** Exodus 14:15

And the Lord said to Moses: Why criest thou to me? Speak to the children of Israel to go forward.

** Exodus 14:16

But lift thou up thy rod, and stretch forth thy hand over the sea, and divide it: that the children of Israel may go through the midst of the sea on dry ground.

** Exodus 14:17

And I will harden the heart of the Egyptians to pursue you: and I will be glorified in Pharao, and in all his host, and in his chariots and in his horsemen.

** Exodus 14:18

And the Egyptians shall know that I am the Lord, when I shall be glorified in Pharao, and in his chariots, and in his horsemen.

** Exodus 14:19

And the angel of God, who went before the camp of Israel, removing, went behind them: and together with him the pillar of the cloud, leaving the forepart,

** Exodus 14:20

Stood behind, between the Egyptians' camp and the camp of Israel: and it was a dark cloud, and enlightening the night, so that they could not come at one another all the night.

** Exodus 14:21

And when Moses had stretched forth his hand over the sea, the Lord took it away by a strong and burning wind blowing all the night, and turned it into dry ground: and the water was divided.

** Exodus 14:22

And the children of Israel went in through the midst of the sea dried up; for the water was as a wall on their right hand and on their left.

** Exodus 14:23

And the Egyptians pursuing went in after them, and all Pharao's horses, his chariots and horsemen, through the midst of the sea.

** Exodus 14:24

And now the morning watch was come, and behold the Lord looking upon the Egyptian army through the pillar of fire and of the cloud, slew their host.

** Exodus 14:25

And overthrew the wheels of the chariots, and they were carried into the deep. And the Egyptians said: Let us flee from Israel; for the Lord fighteth for them against us.

** Exodus 14:26

And the Lord said to Moses: Stretch forth thy hand over the sea, that the waters may come again upon the Egyptians, upon their chariots and horsemen.

** Exodus 14:27

And when Moses had stretched forth his hand towards the sea, it returned at the first break of day to the former place: and as the Egyptians were fleeing away, the waters came upon them, and the Lord shut them up in the middle of the waves.

** Exodus 14:28

And the waters returned, and covered the chariots and the horsemen of all the army of Pharao, who had come into the sea after them, neither did there so much as one of them remain.

** Exodus 14:29

But the children of Israel marched through the midst of the sea upon dry land, and the waters were to them as a wall on the right hand and on the left:

** Exodus 14:30

And the Lord delivered Israel in that day out of the hands of the Egyptians.

** Exodus 14:31

And they saw the Egyptians dead upon the sea shore, and the mighty hand that the Lord had used against them: and the people feared the Lord, and they believed the Lord, and Moses his servant. 

* Exodus 15

** Exodus 15:1

Then Moses and the children of Israel sung this canticle to the Lord, and said: Let us sing to the Lord: for he is gloriously magnified, the horse and the rider he hath thrown into the sea.

** Exodus 15:2

The Lord is my strength and my praise, and he is become salvation to me: he is my God, and I will glorify him: the God of my father, and I will exalt him.

** Exodus 15:3

The Lord is as a man of war, Almighty is his name.

** Exodus 15:4

Pharao's chariots and his army he hath cast into the sea: his chosen captains are drowned in the Red Sea.

** Exodus 15:5

The depths have covered them, they are sunk to the bottom like a stone.

** Exodus 15:6

Thy right hand, O Lord, is magnified in strength: thy right hand, O Lord, hath slain the enemy.

** Exodus 15:7

And in the multitude of thy glory thou hast put down thy adversaries: thou hast sent thy wrath, which hath devoured them like stubble.

** Exodus 15:8

And with the blast of thy anger the waters were gathered together: the flowing water stood, the depths were gathered together in the midst of the sea.

** Exodus 15:9

The enemy said: I will pursue and overtake, I will divide the spoils, my soul shall have its fill: I will draw my sword, my hand shall slay them.

** Exodus 15:10

Thy wind blew and the sea covered them: they sunk as lead in the mighty waters.

** Exodus 15:11

Who is like to thee, among the strong, O Lord? who is like to thee, glorious in holiness, terrible and praise-worthy, doing wonders?

** Exodus 15:12

Thou stretchedst forth thy hand, and the earth swallowed them.

** Exodus 15:13

In thy mercy thou hast been a leader to the people which thou hast redeemed: and in thy strength thou hast carried them to thy holy habitation.

** Exodus 15:14

Nations rose up, and were angry: sorrows took hold on the inhabitants of Philisthiim.

** Exodus 15:15

Then were the princes of Edom troubled, trembling seized on the stout men of Moab: all the inhabitants of Chanaan became stiff.

** Exodus 15:16

Let fear and dread fall upon them, in the greatness of thy arm: let them become immoveable as a stone, until thy people, O Lord, pass by: until this thy people pass by, which thou hast possessed.

** Exodus 15:17

Thou shalt bring them in, and plant them in the mountain of thy inheritance, in thy most firm habitation, which thou hast made, O Lord; thy sanctuary, O Lord, which thy hands have established.

** Exodus 15:18

The Lord shall reign for ever and ever.

** Exodus 15:19

For Pharao went in on horseback with his chariots and horsemen into the sea: and the Lord brought back upon them the waters of the sea: but the children of Israel walked on dry ground in the midst thereof.

** Exodus 15:20

So Mary the prophetess, the sister of Aaron, took a timbrel in her hand: and all the women went forth after her with timbrels and with dances.

** Exodus 15:21

And she began the song to them, saying: Let us sing to the Lord, for he is gloriously magnified, the horse and his rider he hath thrown into the sea.

** Exodus 15:22

And Moses brought Israel from the Red Sea, and they went forth into the wilderness of Sur: and they marched three days through the wilderness, and found no water.

** Exodus 15:23

And they came into Mara, and they could not drink the waters of Mara because they were bitter: whereupon he gave a name also agreeable to the place, calling it Mara, that is, bitterness.

** Exodus 15:24

And the people murmured against Moses, saying: What shall we drink?

** Exodus 15:25

But he cried to the Lord, and he shewed him a tree, which when he had cast into the waters, they were turned into sweetness. There he appointed him ordinances, and judgments, and there he proved him,

** Exodus 15:26

Saying: If thou wilt hear the voice of the Lord thy God, and do what is right before him, and obey his commandments, and keep all his precepts, none of the evils that I laid upon Egypt, will I bring upon thee: for I am the Lord thy healer.

** Exodus 15:27

And the children of Israel came into Elim, where there were twelve fountains of water, and seventy palm trees: and they encamped by the waters. 

* Exodus 16

** Exodus 16:1

And they set forward from Elim, and all the multitude of the children of Israel came into the desert of Sin, which is between Elim and Sinai: the fifteenth day of the second month, after they came out of the land of Egypt.

** Exodus 16:2

And all the congregation of the children of Israel murmured against Moses and Aaron in the wilderness.

** Exodus 16:3

And the children of Israel said to them: Would to God we had died by the hand of the Lord in the land of Egypt, when we sat over the fleshpots, and ate bread to the full: Why have you brought us into this desert, that you might destroy all the multitude with famine?

** Exodus 16:4

And the Lord said to Moses: Behold I will rain bread from heaven for you; let the people go forth, and gather what is sufficient for every day: that I may prove them whether they will walk in my law, or not.

** Exodus 16:5

But the sixth day let them provide for to bring in: and let it be double to that they were wont to gather every day.

** Exodus 16:6

And Moses and Aaron said to the children of Israel In the evening you shall know that the Lord hath brought you forth out of the land of Egypt:

** Exodus 16:7

And in the morning you shall see the glory of the Lord: for he hath heard your murmuring against the Lord: but as for us, what are we, that you mutter against us?

** Exodus 16:8

And Moses said: In the evening the Lord will give you flesh to eat, and in the morning bread to the full: for he hath heard your murmurings, with which you have murmured against him, for what are we? your murmuring is not against us, but against the Lord.

** Exodus 16:9

Moses also said to Aaron: Say to the whole congregation of the children of Israel: Come before the Lord; for he hath heard your murmuring.

** Exodus 16:10

And when Aaron spoke to all the assembly of the children of Israel, they looked towards the wilderness; and behold the glory of the Lord appeared in a cloud.

** Exodus 16:11

And the Lord spoke to Moses, saying:

** Exodus 16:12

I have heard the murmuring of the children of Israel, say to them: In the evening you shall eat flesh, and in the morning you shall have your fill of bread; and you shall know that I am the Lord your God.

** Exodus 16:13

So it came to pass in the evening, that quails coming up, covered the camp: and in the morning a dew lay round about the camp.

** Exodus 16:14

And when it had covered the face of the earth, it appeared in the wilderness small, and as it were beaten with a pestle, like unto the hoar frost on the ground.

** Exodus 16:15

And when the children of Israel saw it, they said one to another: Manhu! which signifieth: What is this! for they knew not what it was. And Moses said to them: This is the bread which the Lord hath given you to eat.

** Exodus 16:16

This is the word that the Lord hath commanded: Let every one gather of it as much as is enough to eat; a gomor for every man, according to the number of your souls that dwell in a tent, so shall you take of it.

** Exodus 16:17

And the children of Israel did so: and they gathered, one more, another less.

** Exodus 16:18

And they measured by the measure of a gomor: neither had he more that had gathered more; nor did he find less that had provided less: but every one had gathered, according to what they were able to eat.

** Exodus 16:19

And Moses said to them: Let no man leave thereof till the morning.

** Exodus 16:20

And they hearkened not to him, but some of them left until the morning, and it began to be full of worms, and it putrified, and Moses was angry with them.

** Exodus 16:21

Now every one of them gathered in the morning, as much as might suffice to eat: and after the sun grew hot, it melted.

** Exodus 16:22

But on the sixth day they gathered twice as much, that is, two gomors every man: and all the rulers of the multitude came, and told Moses.

** Exodus 16:23

And he said to them: This is what the Lord hath spoken: To morrow is the rest of the sabbath sanctified to the Lord. Whatsoever work is to be done, do it; and the meats that are to be dressed, dress them; and whatsoever shall remain, lay it up until the morning.

** Exodus 16:24

And they did so as Moses had commanded, and it did not putrify, neither was there worm found in it.

** Exodus 16:25

And Moses said: Eat it to day, because it is the sabbath of the Lord: to day it shall not be found in the field.

** Exodus 16:26

Gather it six days; but on the seventh day is the sabbath of the Lord, therefore it shall not be found.

** Exodus 16:27

And the seventh day came; and some of the people going forth to gather, found none.

** Exodus 16:28

And the Lord said to Moses: How long will you refuse to keep my commandments, and my law?

** Exodus 16:29

See that the Lord hath given you the sabbath, and for this reason on the sixth day he giveth you a double provision: let each man stay at home, and let none go forth out of his place the seventh day.

** Exodus 16:30

And the people kept the sabbath on the seventh day.

** Exodus 16:31

And the house of Israel called the name thereof Manna: and it was like coriander seed, white, and the taste thereof like to flour with honey.

** Exodus 16:32

And Moses said: This is the word which the Lord hath commanded: Fill a gomor of it, and let it be kept unto generations to come hereafter; that they may know the bread, wherewith I fed you in the wilderness when you were brought forth out of the land of Egypt.

** Exodus 16:33

And Moses said to Aaron: Take a vessel, and put manna into it, as much as a gomor can hold; and lay it up before the Lord, to keep unto your generations,

** Exodus 16:34

As the Lord commanded Moses. And Aaron put it in the tabernacle to be kept.

** Exodus 16:35

And the children of Israel ate manna forty years, till they came to a habitable land: with this meat were they fed, until they reached the borders of the land of Chanaan.

** Exodus 16:36

Now a gomor is the tenth part of an ephi. 

* Exodus 17

** Exodus 17:1

Then all the multitude of the children of Israel setting forward from the desert of Sin, by their mansions, according to the word of the Lord, encamped in Raphidim, where there was no water for the people to drink.

** Exodus 17:2

And they chode with Moses, and said: Give us water, that we may drink. And Moses answered them: Why chide you with me? Wherefore do you tempt the Lord?

** Exodus 17:3

So the people were thirsty there for want of water, and murmured against Moses, saying: Why didst thou make us go forth out of Egypt, to kill us and our children, and our beasts with thirst?

** Exodus 17:4

And Moses cried to the Lord, saying: What shall I do to this people? Yet a little more and they will stone me.

** Exodus 17:5

And the Lord said to Moses: Go before the people, and take with thee of the ancients of Israel: and take in thy hand the rod wherewith thou didst strike the river, and go.

** Exodus 17:6

Behold I will stand there before thee, upon the rock Horeb, and thou shalt strike the rock, and water shall come out of it that the people may drink. Moses did so before the ancients of Israel:

** Exodus 17:7

And he called the name of that place Temptation, because of the chiding of the children of Israel, and for that they tempted the Lord, saying: Is the Lord amongst us or not?

** Exodus 17:8

And Amalec came, and fought against Israel in Raphidim.

** Exodus 17:9

And Moses said to Josue: Choose out men; and go out and fight against Amalec: tomorrow I will stand on the top of the hill, having the rod of God in my hand.

** Exodus 17:10

Josue did as Moses had spoken, and he fought against Amalec; but Moses, and Aaron, and Hur, went up upon the top of the hill.

** Exodus 17:11

And when Moses lifted up his hands, Israel overcame; but if he let them down a little, Amalec overcame.

** Exodus 17:12

And Moses's hands were heavy: so they took a stone, and put under him, and he sat on it: and Aaron and Hur stayed up his hands on both sides. And it came to pass, that his hands were not weary until sunset.

** Exodus 17:13

And Josue put Amalec and his people to flight, by the edge of the sword.

** Exodus 17:14

And the Lord said to Moses: Write this for a memorial in a book, and deliver it to the ears of Josue; for I will destroy the memory of Amalec from under heaven.

** Exodus 17:15

And Moses built an altar; and called the name thereof, The Lord, my exaltation, saying:

** Exodus 17:16

Because the hand of the throne of the Lord, and the war of the Lord shall be against Amalec, from generation to generation. 

* Exodus 18

** Exodus 18:1

And when Jethro the priest of Madian, the kinsman of Moses, had heard all the things that God had done to Moses, and to Israel his people, and that the Lord had brought forth Israel out of Egypt:

** Exodus 18:2

He took Sephora, the wife of Moses, whom he had sent back:

** Exodus 18:3

And her two sons, of whom one was called Gersam: his father saying, I have been a stranger in a foreign country.

** Exodus 18:4

And the other Eliezer: For the God of my father, said he, is my helper, and hath delivered me from the sword of Pharao.

** Exodus 18:5

And Jethro, the kinsman of Moses, came with his sons, and his wife to Moses into the desert, where he was camped by the mountain of God.

** Exodus 18:6

And he sent word to Moses, saying: I Jethro, thy kinsman, come to thee, and thy wife, and thy two sons with her.

** Exodus 18:7

And he went out to meet his kinsman, and worshipped and kissed him: and they saluted one another with words of peace. And when he was come into the tent,

** Exodus 18:8

Moses told his kinsman all that the Lord had done to Pharao, and the Egyptians in favour of Israel: and all the labour which had befallen them in the journey, and that the Lord had delivered them.

** Exodus 18:9

And Jethro rejoiced for all the good things that the Lord had done to Israel, because he had delivered them out of the hands of the Egyptians.

** Exodus 18:10

And he said: Blessed is the Lord, who hath delivered his people out of the hand of Egypt.

** Exodus 18:11

Now I know, that the Lord is great above all gods; because they dealt proudly against them.

** Exodus 18:12

So Jethro, the kinsman of Moses, offered holocausts and sacrifices to God: and Aaron and all the ancients of Israel came, to eat bread with him before God.

** Exodus 18:13

And the next day Moses sat to judge the people, who stood by Moses from morning until night.

** Exodus 18:14

And when his kinsman had seen all things that he did among the people, he said: What is it that thou dost among the people? Why sittest thou alone, and all the people wait from morning till night?

** Exodus 18:15

And Moses answered him: The people come to me to seek the judgment of God?

** Exodus 18:16

And when any controversy falleth out among them, they come to me to judge between them, and to shew the precepts of God, and his laws.

** Exodus 18:17

But he said: The thing thou dost is not good.

** Exodus 18:18

Thou art spent with foolish labour, both thou, and this people that is with thee; the business is above thy strength, thou alone canst not bear it.

** Exodus 18:19

But hear my words and counsels, and God shall be with thee. Be thou to the people in those things that pertain to God, to bring their words to him:

** Exodus 18:20

And to shew the people the ceremonies, and the manner of worshipping; and the way wherein they ought to walk, and the work that they ought to do.

** Exodus 18:21

And provide out of all the people able men, such as fear God, in whom there is truth, and that hate avarice, and appoint of them rulers of thousands, and of hundreds, and of fifties, and of tens,

** Exodus 18:22

Who may judge the people at all times: and when any great matter soever shall fall out, let them refer it to thee, and let them judge the lesser matters only: that so it may be lighter for thee, the burden being shared out unto others.

** Exodus 18:23

If thou dost this, thou shalt fulfil the commandment of God, and shalt be able to bear his precepts: and all this people shall return to their places with peace.

** Exodus 18:24

And when Moses heard this, he did all things that he had suggested unto him.

** Exodus 18:25

And choosing able men out of all Israel, he appointed them rulers of the people, rulers over thousands, and over hundreds, and over fifties, and over tens.

** Exodus 18:26

And they judged the people at all times: and whatsoever was of greater difficulty they referred to him, and they judged the easier cases only.

** Exodus 18:27

And he let his kinsman depart: and he returned and went into his own country. 

* Exodus 19

** Exodus 19:1

In the third month of the departure of Israel out of the land of Egypt, on this day they came into the wilderness of Sinai:

** Exodus 19:2

For departing out of Raphidim, and coming to the desert of Sinai, they camped in the same place, and there Israel pitched their tents over against the mountain.

** Exodus 19:3

And Moses went up to God; and the Lord called unto him from the mountain, and said: Thus shalt thou say to the house of Jacob, and tell the children of Israel:

** Exodus 19:4

You have seen what I have done to the Egyptians, how I have carried you upon the wings of eagles, and have taken you to myself.

** Exodus 19:5

If therefore you will hear my voice, and keep my covenant, you shall be my peculiar possession above all people: for all the earth is mine.

** Exodus 19:6

And you shall be to me a priestly kingdom, and a holy nation. These are the words thou shalt speak to the children of Israel.

** Exodus 19:7

Moses came; and calling together the elders of the people, he declared all the words which the Lord had commanded.

** Exodus 19:8

And all the people answered together: All that the Lord hath spoken, we will do. And when Moses had related the people's words to the Lord,

** Exodus 19:9

The Lord said to him: Lo, now will I come to thee in the darkness of a cloud, that the people may hear me speaking to thee, and may believe thee for ever. And Moses told the words of the people to the Lord.

** Exodus 19:10

And he said to him: Go to the people, and sanctify them to day, and to morrow, and let them wash their garments.

** Exodus 19:11

And let them be ready against the third day; for on the third day the Lord will come down in the sight of all the people, upon Mount Sinai.

** Exodus 19:12

And thou shalt appoint certain limits to the people round about, and thou shalt say to them: Take heed ye go not up into the mount, and that ye touch not the borders thereof: every one that toucheth the mount, dying he shall die.

** Exodus 19:13

No hands shall touch him, but he shall be stoned to death, or he shall be shot through with arrows: whether it be beast, or man, he shall not live. When the trumpet shall begin to sound, then let them go up into the mount.

** Exodus 19:14

And Moses came down from the mount to the people, and sanctified them. And when they had washed their garments,

** Exodus 19:15

He said to them: Be ready against the third day, and come not near your wives.

** Exodus 19:16

And now the third day was come, and the morning appeared: and behold thunders began to be heard, and lightning to flash, and a very thick cloud to cover the mount, and the noise of the trumpet sounded exceeding loud; and the people that was in the camp, feared.

** Exodus 19:17

And when Moses had brought them forth to meet God, from the place of the camp, they stood at the bottom of the mount.

** Exodus 19:18

And all Mount Sinai was on a smoke: because the Lord was come down upon it in fire, and the smoke arose from it as out of a furnace: and all the mount was terrible.

** Exodus 19:19

And the sound of the trumpet grew by degrees louder and louder, and was drawn out to a greater length: Moses spoke, and God answered him.

** Exodus 19:20

And the Lord came down upon Mount Sinai, in the very top of the mount, and he called Moses unto the top thereof. And when he was gone up thither,

** Exodus 19:21

He said unto him: Go down, and charge the people; lest they should have a mind to pass the limits to see the Lord, and a very great multitude of them should perish.

** Exodus 19:22

The priests also that come to the Lord, let them be sanctified, lest he strike them.

** Exodus 19:23

And Moses said to the Lord: The people cannot come up to Mount Sinai: for thou didst charge, and command, saying: Set limits about the mount, and sanctify it.

** Exodus 19:24

And the Lord said to him: Go, get thee down; and thou shalt come up, thou and Aaron with thee: but let not the priests and the people pass the limits, nor come up to the Lord, lest he kill them.

** Exodus 19:25

And Moses went down to the people and told them all. 

* Exodus 20

** Exodus 20:1

And the Lord spoke all these words:

** Exodus 20:2

I am the Lord thy God, who brought thee out of the land of Egypt, out of the house of bondage.

** Exodus 20:3

Thou shalt not have strange gods before me.

** Exodus 20:4

Thou shalt not make to thyself a graven thing, nor the likeness of any thing that is in heaven above, or in the earth beneath, nor of those things that are in the waters under the earth.

** Exodus 20:5

Thou shalt not adore them, nor serve them: I am the Lord thy God, mighty, jealous, visiting the iniquity of the fathers upon the children, unto the third and fourth generation of them that hate me:

** Exodus 20:6

And shewing mercy unto thousands to them that love me, and keep my commandments.

** Exodus 20:7

Thou shalt not take the name of the Lord thy God in vain: for the Lord will not hold him guiltless that shall take the name of the Lord his God in vain.

** Exodus 20:8

Remember that thou keep holy the sabbath day.

** Exodus 20:9

Six days shalt thou labour, and shalt do all thy works.

** Exodus 20:10

But on the seventh day is the sabbath of the Lord thy God: thou shalt do no work on it, thou nor thy son, nor thy daughter, nor thy manservant, nor thy maidservant, nor thy beast, nor the stranger that is within thy gates.

** Exodus 20:11

For in six days the Lord made heaven and earth, and the sea, and all things that are in them, and rested on the seventh day: therefore the Lord blessed the seventh day, and sanctified it.

** Exodus 20:12

Honour thy father and thy mother, that thou mayst be longlived upon the land which the Lord thy God will give thee.

** Exodus 20:13

Thou shalt not kill.

** Exodus 20:14

Thou shalt not commit adultery.

** Exodus 20:15

Thou shalt not steal.

** Exodus 20:16

Thou shalt not bear false witness against thy neighbour.

** Exodus 20:17

Thou shalt not covet thy neighbour's house; neither shalt thou desire his wife, nor his servant, nor his handmaid, nor his ox, nor his ass, nor any thing that is his.

** Exodus 20:18

And all the people saw the voices and the flames, and the sound of the trumpet, and the mount smoking; and being terrified and struck with fear, they stood afar off,

** Exodus 20:19

Saying to Moses: Speak thou to us, and we will hear: let not the Lord speak to us, lest we die.

** Exodus 20:20

And Moses said to the people: Fear not; for God is come to prove you, and that the dread of him might be in you, and you should not sin.

** Exodus 20:21

And the people stood afar off. But Moses went to the dark cloud wherein God was.

** Exodus 20:22

And the Lord said to Moses: Thus shalt thou say to the children of Israel: You have seen that I have spoken to you from heaven.

** Exodus 20:23

You shall not make gods of silver, nor shall you make to yourselves gods of gold.

** Exodus 20:24

You shall make an altar of earth unto me, and you shall offer upon it your holocausts and peace offerings, your sheep and oxen, in every place where the memory of my name shall be: I will come to thee, and will bless thee.

** Exodus 20:25

And if thou make an altar of stone unto me, thou shalt not build it of hewn stones; for if thou lift up a tool upon it, it shall be defiled.

** Exodus 20:26

Thou shalt not go up by steps unto my altar, lest thy nakedness be discovered. 

* Exodus 21

** Exodus 21:1

These are the judgments which thou shalt set before them.

** Exodus 21:2

If thou buy a Hebrew servant, six years shall he serve thee; in the seventh he shall go out free for nothing.

** Exodus 21:3

With what raiment he came in, with the like let him go out: if having a wife, his wife also shall go out with him.

** Exodus 21:4

But if his master gave him a wife, and she hath borne sons and daughters; the woman and her children shall be her master's: but he himself shall go out with his raiment.

** Exodus 21:5

And if the servant shall say: I love my master and my wife and children, I will not go out free:

** Exodus 21:6

His master shall bring him to the gods, and he shall be set to the door and the posts, and he shall bore his ear through with an awl: and he shall be his servant for ever.

** Exodus 21:7

If any man sell his daughter to be a servant, she shall not go out as bondwomen are wont to go out.

** Exodus 21:8

If she displease the eyes of her master to whom she was delivered, he shall let her go: but he shall have no power to sell her to a foreign nation, if he despise her.

** Exodus 21:9

But if he have betrothed her to his son, he shall deal with her after the manner of daughters.

** Exodus 21:10

And if he take another wife for him, he shall provide her a marriage, and raiment, neither shall he refuse the price of her chastity.

** Exodus 21:11

If he do not these three things, she shall go out free without money.

** Exodus 21:12

He that striketh a man with a will to kill him, shall be put to death.

** Exodus 21:13

But he that did not lie in wait for him, but God delivered him into his hands: I will appoint thee a place to which he must flee.

** Exodus 21:14

If a man kill his neighbour on set purpose, and by lying in wait for him: thou shalt take him away from my altar that he may die.

** Exodus 21:15

He that striketh his father or mother, shall be put to death.

** Exodus 21:16

He that shall steal a man, and sell him, being convicted of the guilt, shall be put to death.

** Exodus 21:17

He that curseth his father or mother, shall die the death.

** Exodus 21:18

If men quarrel, and the one strike his neighbour with a stone, or with his fist, and he die not, but keepeth his bed:

** Exodus 21:19

If he rise again and walk abroad upon his staff, he that struck him shall be quit, yet so that he make restitution for his work, and for his expenses upon the physicians.

** Exodus 21:20

He that striketh his bondman, or bondwoman, with a rod, and they die under his hands, shall be guilty of the crime.

** Exodus 21:21

But if the party remain alive a day or two, he shall not be subject to the punishment, because it is his money.

** Exodus 21:22

If men quarrel, and one strike a woman with child and she miscarry indeed, but live herself: he shall be answerable for so much damage as the woman's husband shall require, and as arbiters shall award.

** Exodus 21:23

But if her death ensue thereupon, he shall render life for life,

** Exodus 21:24

Eye for eye, tooth for tooth, hand for hand, foot for foot,

** Exodus 21:25

Burning for burning, wound for wound, stripe for stripe.

** Exodus 21:26

If any man strike the eye of his manservant or maidservant, and leave them but one eye, he shall let them go free for the eye which he put out.

** Exodus 21:27

Also if he strike out a tooth of his manservant or maidservant, he shall in like manner make them free.

** Exodus 21:28

If an ox gore a man or a woman, and they die, he shall be stoned: and his flesh shall not be eaten, but the owner of the ox shall be quit.

** Exodus 21:29

But if the ox was wont to push with his horn yesterday, and the day before, and they warned his master, and he did not shut him up, and he shall kill a man or a woman: then the ox shall be stoned, and his owner also shall be put to death.

** Exodus 21:30

And if they set a price upon him, he shall give for his life whatsoever is laid upon him.

** Exodus 21:31

If he have gored a son, or a daughter, he shall fall under the like sentence.

** Exodus 21:32

If he assault a bondman or bondwoman, he shall give thirty sicles of silver to their master, and the ox shall be stoned.

** Exodus 21:33

If a man open a pit, and dig one, and cover it not, and an ox or an ass fall into it,

** Exodus 21:34

The owner of the pit shall pay the price of the beasts: and that which is dead shall be his own.

** Exodus 21:35

If one man's ox gore another man's ox, and he die: they shall sell the live ox, and shall divide the price, and the carcass of that which died they shall part between them:

** Exodus 21:36

But if he knew that his ox was wont to push yesterday, and the day before, and his master did not keep him in; he shall pay ox for ox, and shall take the whole carcass. 

* Exodus 22

** Exodus 22:1

If any man steal an ox or a sheep, and kill or sell it: he shall restore five oxen for one ox, and four sheep for one sheep.

** Exodus 22:2

If a thief be found breaking open a house or undermining it, and be wounded so as to die: he that slew him shall not be guilty of blood.

** Exodus 22:3

But if he did this when the sun is risen, he hath committed murder, and he shall die. If he have not wherewith to make restitution for the theft, he shall be sold.

** Exodus 22:4

If that which he stole be found with him, alive, either ox, or ass, or sheep: he shall restore double.

** Exodus 22:5

If any man hurt a field or a vineyard, and put in his beast to feed upon that which is other men's: he shall restore the best of whatsoever he hath in his own field, or in his vineyard, according to the estimation of the damage.

** Exodus 22:6

If a fire breaking out light upon thorns, and catch stacks of corn, or corn standing in the fields, he that kindled the fire shall make good the loss.

** Exodus 22:7

If a man deliver money, or any vessel unto his friend to keep, and they be stolen away from him that received them: if the thief be found, he shall restore double:

** Exodus 22:8

If the thief be not known, the master of the house shall be brought to the gods, and shall swear that he did not lay his hand upon his neighbour's goods,

** Exodus 22:9

To do any fraud, either in ox, or in ass, or sheep, or raiment, or any thing that may bring damage: the cause of both parties shall come to the gods: and if they give judgment, he shall restore double to his neighbour.

** Exodus 22:10

If a man deliver ass, ox, sheep, or any beast, to his neighbour's custody, and it die, or be hurt, or be taken by enemies, and no man saw it:

** Exodus 22:11

There shall be an oath between them, that he did not put forth his hand to his neighbour's goods: and the owner shall accept of the oath, and he shall not be compelled to make restitution.

** Exodus 22:12

But if it were taken away by stealth, he shall make the loss good to the owner.

** Exodus 22:13

If it were eaten by a beast, let him bring to him that which was slain, and he shall not make restitution.

** Exodus 22:14

If a man borrow of his neighbour any of these things, and it be hurt or die, the owner not being present, he shall be obliged to make restitution.

** Exodus 22:15

But if the owner be present, he shall not make restitution, especially if it were hired, and came for the hire of his work.

** Exodus 22:16

If a man seduce a virgin not yet espoused, and lie with her: he shall endow her, and have her to wife.

** Exodus 22:17

If the maid's father will not give her to him, he shall give money according to the dowry, which virgins are wont to receive.

** Exodus 22:18

Wizards thou shalt not suffer to live.

** Exodus 22:19

Whosoever copulateth with a beast; shall be put to death.

** Exodus 22:20

He that sacrificeth to gods, shall be put to death, save only to the Lord.

** Exodus 22:21

Thou shalt not molest a stranger, nor afflict him: for yourselves also were strangers in the land of Egypt.

** Exodus 22:22

You shall not hurt a widow or an orphan.

** Exodus 22:23

If you hurt them, they will cry out to me, and I will hear their cry:

** Exodus 22:24

And my rage shall be enkindled, and I will strike you with the sword, and your wives shall be widows, and your children fatherless.

** Exodus 22:25

If thou lend money to any of my people that is poor, that dwelleth with thee, thou shalt not be hard upon them as an extortioner, nor oppress them with usuries.

** Exodus 22:26

If thou take of thy neighbour a garment in pledge, thou shalt give it him again before sunset.

** Exodus 22:27

For that same is the only thing, wherewith he is covered, the clothing of his body, neither hath he any other to sleep in: if he cry to me, I will hear him, because I am compassionate.

** Exodus 22:28

Thou shalt not speak ill of the gods, and the prince of thy people thou shalt not curse.

** Exodus 22:29

Thou shalt not delay to pay thy tithes and thy firstfruits: thou shalt give the firstborn of thy sons to me.

** Exodus 22:30

Thou shalt do the same with the firstborn of thy oxen also and sheep: seven days let it be with its dam: the eighth day thou shalt give it to me.

** Exodus 22:31

You shall be holy men to me: the flesh that beasts have tasted of before, you shall not eat, but shall cast it to the dogs. 

* Exodus 23

** Exodus 23:1

Thou shalt not receive the voice of a lie: neither shalt thou join thy hand to bear false witness for a wicked person.

** Exodus 23:2

Thou shalt not follow the multitude to do evil: neither shalt thou yield in judgment, to the opinion of the most part, to stray from the truth.

** Exodus 23:3

Neither shalt thou favour a poor man in judgment.

** Exodus 23:4

If thou meet thy enemy's ox or ass going astray, bring it back to him.

** Exodus 23:5

If thou see the ass of him that hateth thee lie underneath his burden, thou shalt not pass by, but shalt lift him up with him.

** Exodus 23:6

Thou shalt not go aside in the poor man's judgment.

** Exodus 23:7

Thou shalt fly lying. The innocent and just person thou shalt not put to death: because I abhor the wicked.

** Exodus 23:8

Neither shalt thou take bribes, which even blind the wise, and pervert the words of the just.

** Exodus 23:9

Thou shalt not molest a stranger, for you know the hearts of strangers: for you also were strangers in the land of Egypt.

** Exodus 23:10

Six years thou shalt sow thy ground, and shalt gather the corn thereof.

** Exodus 23:11

But the seventh year thou shalt let it alone, and suffer it to rest, that the poor of thy people may eat, and whatsoever shall be left, let the beasts of the field eat it: so shalt thou do with thy vineyard and thy oliveyard.

** Exodus 23:12

Six days thou shalt work: the seventh day thou shalt cease, that thy ox and thy ass may rest: and the son of thy handmaid and the stranger may be refreshed.

** Exodus 23:13

Keep all things that I have said to you. And by the name of strange gods you shall not swear, neither shall it be heard out of your mouth.

** Exodus 23:14

Three times every year you shall celebrate feasts to me.

** Exodus 23:15

Thou shalt keep the feast of unleavened bread. Seven days shalt thou eat unleavened bread, as I commanded thee, in the time of the month of new corn, when thou didst come forth out of Egypt: thou shalt not appear empty before me.

** Exodus 23:16

And the feast of the harvest of the firstfruits of thy work, whatsoever thou hast sown in the field. The feast also in the end of the year, when thou hast gathered in all thy corn out of the field.

** Exodus 23:17

Thrice a year shall all thy males appear before the Lord thy God.

** Exodus 23:18

Thou shalt not sacrifice the blood of my victim upon leaven, neither shall the fat of my solemnity remain until the morning.

** Exodus 23:19

Thou shalt carry the first-fruits of the corn of thy ground to the house of the Lord thy God. Thou shalt not boil a kid in the milk of his dam.

** Exodus 23:20

Behold I will send my angel, who shall go before thee, and keep thee in thy journey, and bring thee into the place that I have prepared.

** Exodus 23:21

Take notice of him, and hear his voice, and do not think him one to be contemned: for he will not forgive when thou hast sinned, and my name is in him.

** Exodus 23:22

But if thou wilt hear hi voice, and do all that I speak, I will be an enemy to thy enemies, and will afflict them that afflict thee.

** Exodus 23:23

And my angel shall go before thee, and shall bring thee in unto the Amorrhite, and the Hethite, and the Pherexite, and the Chanaanite, and the Hevite, and the Jebuzite, whom I will destroy.

** Exodus 23:24

Thou shalt not adore their gods, nor serve them. Thou shalt not do their works, but shalt destroy them, and break their statues.

** Exodus 23:25

And you shall serve the Lord your God, that I may bless your bread and your waters, and may take away sickness from the midst of thee.

** Exodus 23:26

There shall not be one fruitless nor barren in thy land: I will fill the number of thy days.

** Exodus 23:27

I will send my fear before thee, and will destroy all the people to whom thou shalt come: and will turn the backs of all thy enemies before thee:

** Exodus 23:28

Sending out hornets before, that shall drive away the Hevite, and the Chanaanite, and the Hethite, before thou come in.

** Exodus 23:29

I will not cast them out from thy face in one year; lest the land be brought into a wilderness, and the beasts multiply against thee.

** Exodus 23:30

By little and little I will drive them out from before thee, till thou be increased, and dost possess the land.

** Exodus 23:31

And I will set thy bounds from the Red Sea to the sea of the Palestines, and from the desert to the river: I will deliver the inhabitants of the land into your hands, and will drive them out from before you.

** Exodus 23:32

Thou shalt not enter into league with them, nor with their gods.

** Exodus 23:33

Let them not dwell in thy land, lest perhaps they make thee sin against me, if thou serve their gods; which, undoubtedly, will be a scandal to thee. 

* Exodus 24

** Exodus 24:1

And he said to Moses: Come up to the Lord, thou, and Aaron, Nadab and Abiu, and seventy of the ancients of Israel, and you shall adore afar off.

** Exodus 24:2

And Moses alone shall come up to the Lord, but they shall not come nigh; neither shall the people come up with him.

** Exodus 24:3

So Moses came and told the people all the words of the Lord, and all the judgments: and all the people answered with one voice: We will do all the words of the Lord, which he hath spoken.

** Exodus 24:4

And Moses wrote all the words of the Lord: and rising in the morning, he built an altar at the foot of the mount, and twelve titles according to the twelve tribes of Israel.

** Exodus 24:5

And he sent young men of the children of Israel, and they offered holocausts, and sacrificed pacific victims of calves to the Lord.

** Exodus 24:6

Then Moses took half of the blood, and put it into bowls; and the rest he poured upon the altar.

** Exodus 24:7

And taking the book of the covenant, he read it in the hearing of the people: and they said: All things that the Lord hath spoken, we will do, we will be obedient.

** Exodus 24:8

And he took the blood and sprinkled it upon the people, and he said: This is the blood of the covenant, which the Lord hath made with you concerning all these words.

** Exodus 24:9

Then Moses and Aaron, Nadab and Abiu, and seventy of the ancients of Israel went up:

** Exodus 24:10

And they saw the God of Israel: and under his feet as it were a work of sapphire stone, and as the heaven, when clear.

** Exodus 24:11

Neither did he lay his hand upon those of the children of Israel, that retired afar off, and they saw God, and they did eat and drink.

** Exodus 24:12

And the Lord said to Moses: Come up to me into the mount, and be there; and I will give thee tables of stone, and the law, and the commandments which I have written; that thou mayest teach them.

** Exodus 24:13

Moses rose up, and his minister Josue: and Moses going up into the mount of God,

** Exodus 24:14

Said to the ancients: Wait ye here till we return to you. You have Aaron and Hur with you: if any question shall arise, you shall refer it to them.

** Exodus 24:15

And when Moses was gone up, a cloud covered the mount.

** Exodus 24:16

And the glory of the Lord dwelt upon Sinai, covering it with a cloud six days: and the seventh day he called him out of the midst of the cloud.

** Exodus 24:17

And the sight of the glory of the Lord, was like a burning fire upon the top of the mount, in the eyes of the children of Israel.

** Exodus 24:18

And Moses entering into the midst of the cloud, went up into the mountain: And he was there forty days and forty nights. 

* Exodus 25

** Exodus 25:1

And the Lord spoke to Moses, saying:

** Exodus 25:2

Speak to the children of Israel, that they bring firstfruits to me: of every man that offereth of his own accord, you shall take them.

** Exodus 25:3

And these are the things you must take: Gold, and silver, and brass,

** Exodus 25:4

Violet and purple, and scarlet twice dyed, and fine linen, and goats' hair,

** Exodus 25:5

And rams' skins dyed red, and violet skins, and setim wood:

** Exodus 25:6

Oil to make lights: spices for ointment, and for sweetsmelling incense:

** Exodus 25:7

Onyx stones, and precious stones to adorn the ephod and the rational.

** Exodus 25:8

And they shall make me a sanctuary, and I will dwell in the midst of them:

** Exodus 25:9

According to all the likeness of the tabernacle which I will shew thee, and of all the vessels for the service thereof: and thus you shall make it:

** Exodus 25:10

Frame an ark of setim wood, the length whereof shall be of two cubits and a half; the breadth, a cubit and a half; the height, likewise, a cubit and a half.

** Exodus 25:11

And thou shalt overlay it with the purest gold, within and without; and over it thou shalt make a golden crown round about:

** Exodus 25:12

And four golden rings, which thou shalt put at the four corners of the ark: let two rings be on the one side, and two on the other.

** Exodus 25:13

Thou shalt make bars also of setim wood, and shalt overlay them with gold.

** Exodus 25:14

And thou shalt put them in through the rings that are in the sides of the ark, that it may be carried on them:

** Exodus 25:15

And they shall be always in the rings, neither shall they at any time be drawn out of them.

** Exodus 25:16

And thou shalt put in the ark the testimony which I will give thee.

** Exodus 25:17

Thou shalt make also a propitiatory of the purest gold: the length thereof shall be two cubits and a half, and the breadth a cubit and a half.

** Exodus 25:18

Thou shalt make also two cherubims of beaten gold, on the two sides of the oracle.

** Exodus 25:19

Let one cherub be on the one side, and the other on the other.

** Exodus 25:20

Let them cover both sides of the propitiatory, spreading their wings, and covering the oracle, and let them look one towards the other, their faces being turned towards the propitiatory wherewith the ark is to be covered.

** Exodus 25:21

In which thou shalt put the testimony that I will give thee.

** Exodus 25:22

Thence will I give orders, and will speak to thee over the propitiatory, and from the midst of the two cherubims, which shall be upon the ark of the testimony, all things which I will command the children of Israel by thee.

** Exodus 25:23

Thou shalt make a table also of setim wood, of two cubits in length, and a cubit in breadth, and a cubit and a half in height.

** Exodus 25:24

And thou shalt overlay it with the purest gold: and thou shalt make to it a golden ledge round about.

** Exodus 25:25

And to the ledge itself a polished crown, four inches high; and over the same another little golden crown.

** Exodus 25:26

Thou shalt prepare also four golden rings, and shalt put them in the four corners of the same table, over each foot.

** Exodus 25:27

Under the crown shall the golden rings be, that the bars may be put through them, and the table may be carried.

** Exodus 25:28

The bars also themselves thou shalt make of setim wood, and shalt overlay them with gold, to bear up the table.

** Exodus 25:29

Thou shalt prepare also dishes, and bowls, censers, and cups, wherein the libations are to be offered, of the purest gold.

** Exodus 25:30

And thou shalt set upon the table loaves of proposition in my sight always.

** Exodus 25:31

Thou shalt make also a candlestick of beaten work, of the finest gold, the shaft thereof, and the branches, the cups, and the bowls, and the lilies going forth from it.

** Exodus 25:32

Six branches shall come out of the sides, three out of one side, and three out of the other.

** Exodus 25:33

Three cups as it were nuts to every branch, and a bowl withal, and a lily: and three cups likewise of the fashion of nuts in the other branch, and a bowl withal, and a lily. Such shall be the work of the six branches, that are to come out from the shaft:

** Exodus 25:34

And in the candlestick itself shall be four cups in the manner of a nut, and at every one bowls and lilies.

** Exodus 25:35

Bowls under two branches in three places, which together make six, coming forth out of one shaft.

** Exodus 25:36

And both the bowls and the branches shall be of the same beaten work of the purest gold.

** Exodus 25:37

Thou shalt make also seven lamps, and shalt set them upon the candlestick, to give light over against.

** Exodus 25:38

The snuffers also, and where the snuffings shall be put out, shall be made of the purest gold.

** Exodus 25:39

The whole weight of the candlestick, with all the furniture thereof, shall be a talent of the purest gold.

** Exodus 25:40

Look, and make it according to the pattern that was shewn thee in the mount. 

* Exodus 26

** Exodus 26:1

And thou shalt make the tabernacle in this manner: Thou shalt make ten curtains of fine twisted linen, and violet and purple, and scarlet twice dyed, diversified with embroidery.

** Exodus 26:2

The length of one curtain shall be twenty-eight cubits; the breadth shall be four cubits. All the curtains shall be of one measure.

** Exodus 26:3

Five curtains shall be joined one to another, and the other five shall be coupled together in like manner.

** Exodus 26:4

Thou shalt make loops of violet in the sides and tops of the curtains, that they may be joined one to another.

** Exodus 26:5

Every curtain shall have fifty loops on both sides, so set on, that one loop may be against another loop, and one may be fitted to the other.

** Exodus 26:6

Thou shalt make also fifty rings of gold, wherewith the veils of the curtains are to be joined, that it may be made one tabernacle.

** Exodus 26:7

Thou shalt make also eleven curtains of goats' hair, to cover the top of the tabernacle.

** Exodus 26:8

The length of one hair-curtain shall be thirty cubits; and the breadth, four: the measure of all the curtains shall be equal.

** Exodus 26:9

Five of which thou shalt couple by themselves, and the six others thou shalt couple one to another, so as to double the sixth curtain in the front of the roof.

** Exodus 26:10

Thou shalt make also fifty loops in the edge of one curtain, that it may be joined with the other: and fifty loops in the edge of the other curtain, that it may be coupled with its fellow.

** Exodus 26:11

Thou shalt make also fifty buckles of brass, wherewith the loops may be joined, that of all there may be made one covering.

** Exodus 26:12

And that which shall remain of the curtains, that are prepared for the roof, to wit, one curtain that is over and above, with the half thereof thou shalt cover the back parts of the tabernacle.

** Exodus 26:13

And there shall hang down a cubit on the one side, and another on the other side, which is over and above in the length of the curtains, fencing both sides of the tabernacle.

** Exodus 26:14

Thou shalt make also another cover to the roof of rams' skins dyed red: and over that again another cover of violet coloured skins.

** Exodus 26:15

Thou shalt make also the boards of the tabernacle standing upright of setim wood.

** Exodus 26:16

Let every one of them be ten cubits in length, and in breadth one cubit and a half.

** Exodus 26:17

In the sides of the boards shall be made two mortises, whereby one board may be joined to another board: and after this manner shall all the boards be prepared.

** Exodus 26:18

Of which twenty shall be in the south side southward.

** Exodus 26:19

For which thou shalt cast forty sockets of silver, that under every board may be put two sockets at the two corners.

** Exodus 26:20

In the second side also of the tabernacle that looketh to the north, there shall be twenty boards,

** Exodus 26:21

Having forty sockets of silver, two sockets shall be put under each board.

** Exodus 26:22

But on the west side of the tabernacle thou shalt make six boards.

** Exodus 26:23

And again other two which shall be erected in the corners at the back of the tabernacle.

** Exodus 26:24

And they shall be joined together from beneath unto the top, and one joint shall hold them all. The like joining shall be observed for the two boards also that are to be put in the corners.

** Exodus 26:25

And they shall be in all eight boards, and their silver sockets sixteen, reckoning two sockets for each board.

** Exodus 26:26

Thou shalt make also five bars of setim wood, to hold together the boards on one side of the tabernacle.

** Exodus 26:27

And five others on the other side, and as many at the west side:

** Exodus 26:28

And they shall be put along by the midst of the boards, from one end to the other.

** Exodus 26:29

The boards also themselves thou shalt overlay with gold, and shalt cast rings of gold to be set upon them, for places for the bars to hold together the boardwork: which bars thou shalt cover with plates of gold.

** Exodus 26:30

And thou shalt rear up the tabernacle according to the pattern that was shewn thee in the mount.

** Exodus 26:31

Thou shalt make also a veil of violet, and purple, and scarlet twice dyed, and fine twisted linen, wrought with embroidered work and goodly variety:

** Exodus 26:32

And thou shalt hang it up before four pillars of setim wood, which themselves also shall be overlaid with gold, and shall have heads of gold, but sockets of silver.

** Exodus 26:33

And the veil shall be hanged on with rings, and within it thou shalt put the ark of the testimony, and the sanctuary and the holy of the holies shall be divided with it.

** Exodus 26:34

And thou shalt set the propitiatory upon the ark of the testimony, in the holy of holies.

** Exodus 26:35

And the table without the veil, and over against the table the candlestick in the south side of the tabernacle: for the table shall stand in the north side.

** Exodus 26:36

Thou shalt make also a hanging in the entrance of the tabernacle of violet, and purple, and scarlet twice dyed, and fine twisted linen with embroidered work.

** Exodus 26:37

And thou shalt overlay with gold five pillars of setim wood, before which the hanging shall be drawn: their heads shall be of gold, and the sockets of brass. 

* Exodus 27

** Exodus 27:1

Thou shalt make also an altar of setim wood, which shall be five cubits long, and as many broad, that is four square, and three cubits high.

** Exodus 27:2

And there shall be horns at the four corners of the same: and thou shalt cover it with brass.

** Exodus 27:3

And thou shalt make for the uses thereof pans to receive the ashes, and tongs and fleshhooks, and firepans: all its vessels thou shalt make of brass.

** Exodus 27:4

And a grate of brass in manner of a net; at the four corners of which, shall be four rings of brass,

** Exodus 27:5

Which thou shalt put under the hearth of the altar: and the grate shall be even to the midst of the altar.

** Exodus 27:6

Thou shalt make also two bars for the altar, of setim wood, which thou shalt cover with plates of brass:

** Exodus 27:7

And thou shalt draw them through rings, and they shall be on both sides of the altar to carry it.

** Exodus 27:8

Thou shalt not make it solid, but empty and hollow in the inside, as it was shewn thee in the mount.

** Exodus 27:9

Thou shalt make also the court of the tabernacle, in the south side whereof southward there shall be hangings of fine twisted linen of a hundred cubits long for one side.

** Exodus 27:10

And twenty pillars with as many sockets of brass, the heads of which, with their engraving, shall be of silver.

** Exodus 27:11

In like manner also on the north side there shall be hangings of a hundred cubits long, twenty pillars, and as many sockets of brass, and their heads with their engraving of silver.

** Exodus 27:12

But in the breadth of the court, that looketh to the west, there shall be hangings of fifty cubits, and ten pillars, and as many sockets.

** Exodus 27:13

In that breadth also of the court, which looketh to the east, there shall be fifty cubits.

** Exodus 27:14

In which there shall be for one side, hangings of fifteen cubits, and three pillars, and as many sockets.

** Exodus 27:15

And in the other side, there shall be hangings of fifteen cubits, with three pillars, and as many sockets.

** Exodus 27:16

And in the entrance of the court there shall be made a hanging of twenty cubits of violet and purple, and scarlet twice dyed, and fine twisted linen, with embroidered work: it shall have four pillars, with as many sockets.

** Exodus 27:17

All the pillars of the court round about shall be garnished with plates of silver, silver heads, and sockets of brass.

** Exodus 27:18

In length the court shall take up a hundred cubits, in breadth fifty, the height shall be of five cubits, and it shall be made of fine twisted linen, and shall have sockets of brass.

** Exodus 27:19

All the vessels of the tabernacle for all uses and ceremonies, and the pins both of it and of the court, thou shalt make of brass.

** Exodus 27:20

Command the children of Israel that they bring thee the purest oil of the olives, and beaten with a pestle: that a lamp may burn always,

** Exodus 27:21

In the tabernacle of the testimony, without the veil that hangs before the testimony. And Aaron and his sons shall order it, that it may give light before the Lord until the morning. It shall be a perpetual observance throughout their successions among the children of Israel. 

* Exodus 28

** Exodus 28:1

Take unto thee also Aaron thy brother with his sons, from among the children of Israel, that they may minister to me in the priest's office: Aaron, Nadab, and Abiu, Eleazar, and Ithamar.

** Exodus 28:2

And thou shalt make a holy vesture for Aaron, thy brother, for glory and for beauty.

** Exodus 28:3

And thou shalt speak to all the wise of heart, whom I have filled with the spirit of wisdom, that they may make Aaron's vestments, in which he being consecrated, may minister to me.

** Exodus 28:4

And these shall be the vestments that they shall make: A rational and an ephod, a tunic and a strait linen garment, a mitre and a girdle. They shall make the holy vestments for thy brother Aaron and his sons, that they may do the office of priesthood unto me.

** Exodus 28:5

And they shall take gold, and violet, and purple, and scarlet twice dyed, and fine linen.

** Exodus 28:6

And they shall make the ephod of gold, and violet, and purple, and scarlet twice dyed, and fine twisted linen, embroidered with divers colours.

** Exodus 28:7

It shall have the two edges joined in the top on both sides, that they may be closed together.

** Exodus 28:8

The very workmanship also, and all the variety of the work, shall be of gold, and violet, and purple, and scarlet twice dyed, and fine twisted linen.

** Exodus 28:9

And thou shalt take two onyx stones, and shalt grave on them the names of the children of Israel:

** Exodus 28:10

Six names on one stone, and the other six on the other, according to the order of their birth.

** Exodus 28:11

With the work of an engraver, and the graving of a jeweller, thou shalt engrave them with the names of the children of Israel, set in gold and compassed about:

** Exodus 28:12

And thou shalt put them in both sides of the ephod, a memorial for the children of Israel. And Aaron shall bear their names before the Lord upon both shoulders, for a remembrance.

** Exodus 28:13

Thou shalt make also hooks of gold.

** Exodus 28:14

And two little chains of the purest gold, linked one to another, which thou shalt put into the hooks.

** Exodus 28:15

And thou shalt make the rational of judgment with embroidered work of divers colours, according to the workmanship of the ephod, of gold, violet, and purple, and scarlet twice dyed, and fine twisted linen.

** Exodus 28:16

It shall be four square and doubled: it shall be the measure of a span both in length and in breadth.

** Exodus 28:17

And thou shalt set in it four rows of stones . In the first row shall be a sardius stone, and a topaz, and an emerald:

** Exodus 28:18

In the second a carbuncle, a sapphire, and a jasper:

** Exodus 28:19

In the third a ligurius, an agate, and an amethyst:

** Exodus 28:20

In the fourth a chrysolite, an onyx, and a beryl. They shall be set in gold by their rows.

** Exodus 28:21

And they shall have the names of the children of Israel: with twelve names shall they be engraved, each stone with the name of one according to the twelve tribes.

** Exodus 28:22

And thou shalt make on the rational chains, linked one to another, of the purest gold:

** Exodus 28:23

And two rings of gold, which thou shalt put in the two ends at the top of the rational.

** Exodus 28:24

And the golden chains thou shalt join to the rings, that are in the ends thereof.

** Exodus 28:25

And the ends of the chains themselves, thou shalt join together with two hooks, on both sides of the ephod, which is towards the rational.

** Exodus 28:26

Thou shalt make also two rings of gold, which thou shalt put in the top parts of the rational, in the borders that are over against the ephod, and look towards the back parts thereof.

** Exodus 28:27

Moreover also other two rings of gold, which are to be set on each side of the ephod beneath, that looketh towards the nether joining, that the rational may be fitted with the ephod,

** Exodus 28:28

And may be fastened by the rings thereof unto the rings of the ephod with a violet fillet, that the joining artificially wrought may continue, and the rational and the ephod may not be loosed one from the other.

** Exodus 28:29

And Aaron shall bear the names of the children of Israel in the rational of judgment upon his breast, when he shall enter into the sanctuary, a memorial before the Lord for ever.

** Exodus 28:30

And thou shalt put in the rational of judgment doctrine and truth, which shall be on Aaron's breast, when he shall go in before the Lord: and he shall bear the judgment of the children of Israel on his breast, in the sight of the Lord always.

** Exodus 28:31

And thou shalt make the tunic of the ephod all of violet,

** Exodus 28:32

In the midst whereof above shall be a hole for the head, and a border round about it woven, as is wont to be made in the outmost parts of garments, that it may not easily be broken.

** Exodus 28:33

And beneath at the feet of the same tunic, round about, thou shalt make as it were pomegranates, of violet, and purple, and scarlet twice dyed, with little bells set between:

** Exodus 28:34

So that there shall be a golden bell and a pomegranate, and again another golden bell and a pomegranate.

** Exodus 28:35

And Aaron shall be vested with it in the office of his ministry, that the sound may be heard, when he goeth in and cometh out of the sanctuary, in the sight of the Lord, and that he may not die.

** Exodus 28:36

Thou shalt make also a plate of the purest gold: wherein thou shalt grave with engraver's work, Holy to the Lord.

** Exodus 28:37

And thou shalt tie it with a violet fillet, and it shall be upon the mitre,

** Exodus 28:38

Hanging over the forehead of the high priest. And Aaron shall bear the iniquities of those things, which the children of Israel have offered and sanctified, in all their gifts and offerings. And the plate shall be always on his forehead, that the Lord may be well pleased with them.

** Exodus 28:39

And thou shalt gird the tunic with fine linen, and thou shalt make a fine linen mitre, and a girdle of embroidered work.

** Exodus 28:40

Moreover, for the sons of Aaron thou shalt prepare linen tunics, and girdles and mitres for glory and beauty:

** Exodus 28:41

And with all these things thou shalt vest Aaron thy brother, and his sons with him. And thou shalt consecrate the hands of them all, and shalt sanctify them, that they may do the office of priesthood unto me.

** Exodus 28:42

Thou shalt make also linen breeches, to cover the flesh of their nakedness, from the reins to the thighs:

** Exodus 28:43

And Aaron and his sons shall use them when they shall go into the tabernacle of the testimony, or when they approach to the altar to minister in the sanctuary. lest being guilty of iniquity they die. It shall be a law for ever to Aaron, and to his seed after him. 

* Exodus 29

** Exodus 29:1

And thou shalt also do this, that they may be consecrated to me in priesthood. Take a calf from the herd, and two rams without blemish,

** Exodus 29:2

And unleavened bread, and a cake without leaven, tempered with oil, wafers also unleavened, anointed with oil: thou shalt make them all of wheaten flour.

** Exodus 29:3

And thou shalt put them in a basket, and offer them: and the calf and the two rams.

** Exodus 29:4

And thou shalt bring Aaron and his sons to the door of the tabernacle of the testimony. And when thou hast washed the father and his sons with water,

** Exodus 29:5

Thou shalt clothe Aaron with his vestments, that is, with the linen garment and the tunic, and the ephod and the rational, which thou shalt gird with the girdle.

** Exodus 29:6

And thou shalt put the mitre upon his head, and the holy plate upon the mitre,

** Exodus 29:7

And thou shalt pour the oil of unction upon his head: and by this rite shall he be consecrated.

** Exodus 29:8

Thou shalt bring his sons also, and shalt put on them the linen tunics, and gird them with a girdle:

** Exodus 29:9

To wit, Aaron and his children, and thou shalt put mitres upon them; and they shall be priests to me by a perpetual ordinance. After thou shalt have consecrated their hands,

** Exodus 29:10

Thou shalt present also the calf before the tabernacle of the testimony. And Aaron and his sons shall lay their hands upon his head,

** Exodus 29:11

And thou shalt kill him in the sight of the Lord, beside the door of the tabernacle of the testimony.

** Exodus 29:12

And taking some of the blood of the calf, thou shalt put it upon the horns of the altar with thy finger, and the rest of the blood thou shalt pour at the bottom thereof.

** Exodus 29:13

Thou shalt take also all the fat that covereth the entrails, and the caul of the liver, and the two kidneys, and the fat that is upon them, and shalt offer a burn offering upon the altar:

** Exodus 29:14

But the flesh of the calf, and the hide and the dung, thou shalt burn abroad, without the camp, because it is for sin.

** Exodus 29:15

Thou shalt take also one ram, upon the head whereof Aaron and his sons shall lay their hands.

** Exodus 29:16

And when thou hast killed him, thou shalt take of the blood thereof, and pour round about the altar.

** Exodus 29:17

And thou shalt cut the ram in pieces, and having washed his entrails and feet, thou shalt put them upon the flesh that is cut in pieces, and upon his head.

** Exodus 29:18

And thou shalt offer the whole ram for a burnt offering upon the altar: it is an oblation to the Lord, a most sweet savour of the victim of the Lord.

** Exodus 29:19

Thou shalt take also the other ram, upon whose head Aaron and his sons shall lay their hands.

** Exodus 29:20

And when thou hast sacrificed him, thou shalt take of his blood, and put upon the tip of the right ear of Aaron and of his sons, and upon the thumbs and great toes of their right hand and foot, and thou shalt pour the blood upon the altar round about.

** Exodus 29:21

And when thou hast taken of the blood that is upon the altar, and of the oil of unction, thou shalt sprinkle Aaron and his vesture, his sons and their vestments. And after they and their vestments are consecrated,

** Exodus 29:22

Thou shalt take the fat of the ram, and the rump, and the fat that covereth the lungs, and the caul of the liver, and the two kidneys, and the fat that is upon them, and the right shoulder, because it is the ram of consecration:

** Exodus 29:23

And one roll of bread, a cake tempered with oil, a wafer out of the basket of unleavened bread, which is set in the sight of the Lord:

** Exodus 29:24

And thou shalt put all upon the hands of Aaron and of his sons, and shalt sanctify them elevating before the Lord.

** Exodus 29:25

And thou shalt take all from their hands; and shalt burn them upon the altar for a holocaust, a most sweet savour in the sight of the Lord, because it is his oblation.

** Exodus 29:26

Thou shalt take also the breast of the ram, wherewith Aaron was consecrated, and elevating it thou shalt sanctify it before the Lord, and it shall fall to thy share.

** Exodus 29:27

And thou shalt sanctify both the consecrated breast, and the shoulder that thou didst separate of the ram,

** Exodus 29:28

Wherewith Aaron was consecrated and his sons, and they shall fall to Aaron's share, and his sons', by a perpetual right from the children of Israel: because they are the choicest and the beginnings of their peace victims which they offer to the Lord.

** Exodus 29:29

And the holy vesture, which Aaron shall use, his sons shall have after him, that they may be anointed, and their hands consecrated in it.

** Exodus 29:30

He of his sons that shall be appointed high priest in his stead, and that shall enter into the tabernacle of the testimony to minister in the sanctuary, shall wear it seven days.

** Exodus 29:31

And thou shalt take the ram of the consecration, and shalt boil the flesh thereof in the holy place:

** Exodus 29:32

And Aaron and his sons shall eat it. The loaves also, that are in the basket, they shall eat in the entry of the tabernacle of the testimony,

** Exodus 29:33

That it may be an atoning sacrifice, and the hands of the offerers may be sanctified. A stranger shall not eat of them, because they are holy.

** Exodus 29:34

And if there remain of the consecrated flesh, or of the bread, till the morning, thou shalt burn the remainder with fire: they shall not be eaten, because they are sanctified.

** Exodus 29:35

All that I have commanded thee, thou shalt do unto Aaron and his sons. Seven days shalt thou consecrate their hands:

** Exodus 29:36

And thou shalt offer a calf for sin every day for expiation. And thou shalt cleanse the altar when thou hast offered the victim of expiation, and shalt anoint it to sanctify it.

** Exodus 29:37

Seven days shalt thou expiate the altar and sanctify it, and it shall be most holy. Every one, that shall touch it, shall be holy.

** Exodus 29:38

This is what thou shalt sacrifice upon the altar: Two lambs of a year old every day continually,

** Exodus 29:39

One lamb in the morning, and another in the evening.

** Exodus 29:40

With one lamb a tenth part of flour tempered with beaten oil, of the fourth part of a hin, and wine for libation of the same measure.

** Exodus 29:41

And the other lamb thou shalt offer in the evening, according to the rite of the morning oblation, and according to what we have said, for a savour of sweetness:

** Exodus 29:42

It is a sacrifice to the Lord, by perpetual oblation unto your generations, at the door of the tabernacle of the testimony before the Lord, where I will appoint to speak unto thee.

** Exodus 29:43

And there will I command the children of Israel, and the altar shall be sanctified by my glory.

** Exodus 29:44

I will sanctify also the tabernacle of the testimony with the altar, and Aaron with his sons, to do the office of priesthood unto me.

** Exodus 29:45

And I will dwell in the midst of the children of Israel, and will be their God:

** Exodus 29:46

And they shall know that I am the Lord their God, who have brought them out of the land of Egypt, that I might abide among them, I the Lord their God. 

* Exodus 30

** Exodus 30:1

Thou shalt make also an altar to burn incense, of setim wood.

** Exodus 30:2

It shall be a cubit in length, and another in breadth, that is, four square, and two in height. Horns shall go out of the same.

** Exodus 30:3

And thou shalt overlay it with the purest gold, as well the grate thereof, as the walls round about, and the horns. And thou shalt make to it a crown of gold round about,

** Exodus 30:4

And two golden rings under the crown on either side, that the bars may be put into them, and the altar be carried.

** Exodus 30:5

And thou shalt make the bars also of setim wood, and shalt overlay them with gold.

** Exodus 30:6

And thou shalt set the altar over against the veil, that hangeth before the ark of the testimony before the propitiatory wherewith the testimony is covered, where I will speak to thee.

** Exodus 30:7

And Aaron shall burn sweet smelling incense upon it in the morning. When he shall dress the lamps, he shall burn it:

** Exodus 30:8

And when he shall place them in the evening, he shall burn an everlasting incense before the Lord throughout your generations.

** Exodus 30:9

You shall not offer upon it incense of another composition, nor oblation, and victim, neither shall you offer libations.

** Exodus 30:10

And Aaron shall pray upon the horns thereof once a year, with the blood of that which was offered for sin; and shall make atonement upon it in your generations. It shall be most holy to the Lord.

** Exodus 30:11

And the Lord spoke to Moses, saying:

** Exodus 30:12

When thou shalt take the sum of the children of Israel, according to their number, every one of them shall give a price for their souls to the Lord, and there shall be no scourge among them, when they shall be reckoned.

** Exodus 30:13

And this shall every one give that passeth at the naming, half a sicle according to the standard of the temple. A sicle hath twenty obols. Half a sicle shall be offered to the Lord.

** Exodus 30:14

He that is counted in the number from twenty years and upwards, shall give the price.

** Exodus 30:15

The rich man shall not add to half a sicle, and the poor man shall diminish nothing.

** Exodus 30:16

And the money received, which was contributed by the children of Israel, thou shalt deliver unto the uses of the tabernacle of the testimony, that it may be a memorial of them before the Lord, and he may be merciful to their souls.

** Exodus 30:17

And the Lord spoke to Moses, saying:

** Exodus 30:18

Thou shalt make also a brazen laver with its foot to wash in: and thou shalt set it between the tabernacle of the testimony and the altar. And water being put into it:

** Exodus 30:19

Aaron and his sons shall wash their hands and feet in it:

** Exodus 30:20

When they are going into the tabernacle of the testimony, and when they are to come to the altar, to offer on it incense to the Lord,

** Exodus 30:21

Lest perhaps they die. It shall be an everlasting law to him, and to his seed by successions.

** Exodus 30:22

And the Lord spoke to Moses,

** Exodus 30:23

Saying: Take spices, of principal and chosen myrrh five hundred sicles, and of cinnamon half so much; that is, two hundred and fifty sicles, of calamus in like manner two hundred and fifty,

** Exodus 30:24

And of cassia five hundred sicles by the weight of the sanctuary, of oil of olives the measure hin:

** Exodus 30:25

And thou shalt make the holy oil of unction, an ointment compounded after the art of the perfumer,

** Exodus 30:26

And therewith thou shalt anoint the tabernacle of the testimony, and the ark of the testament,

** Exodus 30:27

And the table with the vessels thereof, the candlestick and furniture thereof, the altars of incense,

** Exodus 30:28

And of holocaust, and all the furniture that belongeth to the service of them.

** Exodus 30:29

And thou shalt sanctify all, and they shall be most holy: he that shall touch them shall be sanctified.

** Exodus 30:30

Thou shalt anoint Aaron and his sons, and shalt sanctify them, that they may do the office of priesthood unto me.

** Exodus 30:31

And thou shalt say to the children of Israel: This oil of unction shall be holy unto me throughout your generations.

** Exodus 30:32

The flesh of man shall not be anointed therewith, and you shall make none other of the same composition, because it is sanctified, and shall be holy unto you.

** Exodus 30:33

What man soever shall compound such, and shall give thereof to a stranger, he shall be cut off from his people.

** Exodus 30:34

And the Lord said to Moses: Take unto thee spices, stacte, and onycha, galbanum of sweet savour, and the clearest frankincense, all shall be of equal weight.

** Exodus 30:35

And thou shalt make incense compounded by the work of the perfumer, well tempered together, and pure, and most worthy of sanctification.

** Exodus 30:36

And when thou hast beaten all into very small powder, thou shalt set of it before the tabernacle of the testimony, in the place where I will appear to thee. Most holy shall this incense be unto you.

** Exodus 30:37

You shall not make such a composition for your own uses, because it is holy to the Lord.

** Exodus 30:38

What man soever shall make the like, to enjoy the smell thereof, he shall perish out of his people. 

* Exodus 31

** Exodus 31:1

And the Lord spoke to Moses, saying:

** Exodus 31:2

Behold, I have called by name Beseleel the son of Uri, the son of Hur, of the tribe of Juda,

** Exodus 31:3

And I have filled him with the spirit of God, with wisdom and understanding, and knowledge in all manner of work,

** Exodus 31:4

To devise whatsoever may be artificially made of gold, and silver, and brass,

** Exodus 31:5

Of marble, and precious stones, and variety of wood.

** Exodus 31:6

And I have given him for his companion Ooliab, the son of Achisamech, of the tribe of Dan. And I have put wisdom in the heart of every skilful man, that they may make all things which I have commanded thee,

** Exodus 31:7

The tabernacle of the covenant, and the ark of the testimony, and the propitiatory, that is over it, and all the vessels of the tabernacle,

** Exodus 31:8

And the table and the vessels thereof, the most pure candlestick with the vessels thereof, and the altars of incense,

** Exodus 31:9

And of holocaust, and all their vessels, the laver with its foot,

** Exodus 31:10

The holy vestments in the ministry for Aaron the priest, and for his sons, that they may execute their office, about the sacred things:

** Exodus 31:11

The oil of unction, and the incense of spices in the sanctuary, all things which I have commanded thee, shall they make.

** Exodus 31:12

And the Lord spoke to Moses, saying:

** Exodus 31:13

Speak to the children of Israel, and thou shalt say to them: See that you keep my sabbath; because it is a sign between me and you in your generations that you may know that I am the Lord, who sanctify you.

** Exodus 31:14

keep you my sabbath: for it is holy unto you: he that shall profane it, shall be put to death: he that shall do any work in it, his soul shall perish out of the midst of his people.

** Exodus 31:15

Six days shall you do work: in the seventh day is the sabbath, the rest holy to the Lord. Every one that shall do any work on this day, shall die.

** Exodus 31:16

Let the children of Israel keep the sabbath, and celebrate it in their generations. It is an everlasting covenant

** Exodus 31:17

Between me and the children of Israel, and a perpetual sign. For in six days the Lord made heaven and earth, and in the seventh he ceased from work.

** Exodus 31:18

And the Lord, when he had ended these words in Mount Sinai, gave to Moses two stone tables of testimony, written with the finger of God. 

* Exodus 32

** Exodus 32:1

And the people seeing that Moses delayed to come down from the mount, gathering together against Aaron, said: Arise, make us gods, that may go before us: For as to this Moses, the man that brought us out of the land of Egypt, we know not what has befallen him.

** Exodus 32:2

And Aaron said to them: Take the golden earrings from the ears of your wives, and your sons and daughters, and bring them to me.

** Exodus 32:3

And the people did what he had commanded, bringing the earrings to Aaron.

** Exodus 32:4

And when he had received them, he fashioned them by founders' work, and made of them a molten calf. And they said: These are thy gods, O Israel, that have brought thee out of the land of Egypt.

** Exodus 32:5

And when Aaron saw this, he built an altar before it, and made proclamation by a crier's voice, saying To morrow is the solemnity of the Lord.

** Exodus 32:6

And rising in the morning, they offered holocausts, and peace victims, and the people sat down to eat and drink, and they rose up to play.

** Exodus 32:7

And the Lord spoke to Moses, saying: Go, get thee down: thy people, which thou hast brought out of the land of Egypt, hath sinned.

** Exodus 32:8

They have quickly strayed from the way which thou didst shew them: and they have made to themselves a molten calf, and have adored it, and sacrificing victims to it, have said: These are thy gods, O Israel, that have brought thee out of the land of Egypt.

** Exodus 32:9

And again the Lord said to Moses: I see that this people is stiffnecked:

** Exodus 32:10

Let me alone, that my wrath may be kindled against them, and that I may destroy them, and I will make of thee a great nation.

** Exodus 32:11

But Moses besought the Lord his God, saying: Why, O Lord, is thy indignation enkindled against thy people, whom thou hast brought out of the land of Egypt, with great power, and with a mighty hand?

** Exodus 32:12

Let not the Egyptians say, I beseech thee: He craftily brought them out, that he might kill them in the mountains, and destroy them from the earth: let thy anger cease, and be appeased upon the wickedness of thy people.

** Exodus 32:13

Remember Abraham, Isaac, and Israel, thy servants, to whom thou sworest by thy own self, saying: I will multiply your seed as the stars of heaven: and this whole land that I have spoken of, I will give to your seed, and you shall possess it for ever:

** Exodus 32:14

And the Lord was appeased from doing the evil which he had spoken against his people.

** Exodus 32:15

And Moses returned from the mount, carrying the two tables of the testimony in his hand, written on both sides,

** Exodus 32:16

And made by the work of God; the writing also of God was graven in the tables.

** Exodus 32:17

And Josue hearing the noise of the people shouting, said to Moses: The noise of battle is heard in the camp.

** Exodus 32:18

But he answered: It is not the cry of men encouraging to fight, nor the shout of men compelling to flee: but I hear the voice of singers.

** Exodus 32:19

And when he came nigh to the camp, he saw the calf, and the dances: and being very angry, he threw the tables out of his hand, and broke them at the foot of the mount:

** Exodus 32:20

And laying hold of the calf which they had made, he burnt it, and beat it to powder, which he strewed into water, and gave thereof to the children of Israel to drink.

** Exodus 32:21

And he said to Aaron: What has this people done to thee, that thou shouldst bring upon them a most heinous sin?

** Exodus 32:22

And he answered him: Let not my lord be offended; for thou knowest this people, that they are prone to evil.

** Exodus 32:23

They said to me: make us gods, that may go before us; for as to this Moses, who brought us forth out of the land of Egypt, we know not what is befallen him.

** Exodus 32:24

And I said to them: Which of you hath any gold? and they took and brought it to me; and I cast it into the fire, and this calf came out.

** Exodus 32:25

And when Moses saw that the people were naked, (for Aaron had stripped them by occasion of the shame of the filth, and had set them naked among their enemies)

** Exodus 32:26

Then standing in the gate of the camp, he said: If any man be on the Lord's side, let him join with me. And all the sons of Levi gathered themselves together unto him:

** Exodus 32:27

And he said to them: Thus saith the Lord God of Israel: Put every man his sword upon his thigh: go, and return from gate to gate through the midst of the camp, and let every man kill his brother, and friend, and neighbour.

** Exodus 32:28

And the sons of Levi did according to the words of Moses, and there were slain that day about three and twenty thousand men.

** Exodus 32:29

And Moses said: You have consecrated your hands this day to the Lord, every man in his son and in his brother, that a blessing may be given to you.

** Exodus 32:30

And when the next day was come, Moses spoke to the people: You have sinned a very great sin: I will go up to the Lord, if by any means I may be able to entreat him for your crime.

** Exodus 32:31

And returning to the Lord, he said: I beseech thee: this people hath sinned a heinous sin, and they have made to themselves gods of gold: either forgive them this trespass,

** Exodus 32:32

Or if thou do not, strike me out of the book that thou hast written.

** Exodus 32:33

And the Lord answered him: He that hath sinned against me, him will I strike out of my book:

** Exodus 32:34

But go thou, and lead this people whither I have told thee: my angel shall go before thee. And I in the day of revenge will visit this sin also of theirs.

** Exodus 32:35

The Lord therefore struck the people for the guilt, on occasion of the calf which Aaron had made. 

* Exodus 33

** Exodus 33:1

And the Lord spoke to Moses, saying: Go, get thee up from this place, thou and thy people which thou hast brought out of the land of Egypt, into the land concerning which I swore to Abraham, Isaac, and Jacob, saying: To thy seed I will give it:

** Exodus 33:2

And I will send an angel before thee, that I may cast out the Chanaanite, and the Amorrhite, and the Hethite, and the Pherezite, and the Hevite, and the Jebusite,

** Exodus 33:3

That thou mayst enter into the land that floweth with milk and honey. For I will not go up with thee, because thou art a stiffnecked people; lest I destroy thee in the way.

** Exodus 33:4

And the people hearing these very bad tidings, mourned: and no man put on his ornaments according to custom.

** Exodus 33:5

And the Lord said to Moses: Say to the children of Israel: Thou art a stiffnecked people, once I shall come up in the midst of thee, and shall destroy thee. Now presently lay aside thy ornaments, that I may know what to do to thee.

** Exodus 33:6

So the children of Israel laid aside their ornaments by Mount Horeb.

** Exodus 33:7

Moses also taking the tabernacle, pitched it without the camp afar off, and called the name thereof, The tabernacle of the covenant. And all the people, that had any question, went forth to the tabernacle of the covenant, without the camp.

** Exodus 33:8

And when Moses went forth to the tabernacle, all the people rose up, and every one stood in the door of his pavilion, and they beheld the back of Moses, till he went into the tabernacle.

** Exodus 33:9

And when he was gone into the tabernacle of the covenant, the pillar of the cloud came down, and stood at the door, and he spoke with Moses.

** Exodus 33:10

And all saw that the pillar of the cloud stood at the door of the tabernacle. And they stood and worshipped at the doors of their tent.

** Exodus 33:11

And the Lord spoke to Moses face to face, as a man is wont to speak to his friend. And when he returned into the camp, his servant Josue, the son of Nun, a young man, departed not from the tabernacle.

** Exodus 33:12

And Moses said to the Lord: Thou commandest me to lead forth this people; and thou dost not let me know whom thou wilt send with me, especially whereas thou hast said: I know thee by name, and thou hast found favour in my sight.

** Exodus 33:13

If therefore I have found favour in thy sight, shew me thy face, that I may know thee, and may find grace before thy eyes: look upon thy people this nation.

** Exodus 33:14

And the Lord said: My face shall go before thee, and I will give thee rest.

** Exodus 33:15

And Moses said: If thou thyself dost not go before, bring us not out of this place.

** Exodus 33:16

For how shall we be able to know, I and thy people, that we have found grace in thy sight, unless thou walk with us, that we may be glorified by all people that dwell upon the earth?

** Exodus 33:17

And the Lord said to Moses: This word also, which thou hast spoken, will I do; for thou hast found grace before me, and thee I have known by name.

** Exodus 33:18

And he said: Shew me thy glory.

** Exodus 33:19

He answered: I will shew thee all good, and I will proclaim in the name of the Lord before thee: and I will have mercy on whom I will, and I will be merciful to whom it shall please me.

** Exodus 33:20

And again he said: Thou canst not see my face: for man shall not see me, and live.

** Exodus 33:21

And again he said: Behold there is a place with me, and thou shalt stand upon the rock.

** Exodus 33:22

And when my glory shall pass, I will set thee in a hole of the rock, and protect thee with my righthand till I pass:

** Exodus 33:23

And I will take away my hand, and thou shalt see my back parts: but my face thou canst not see. 

* Exodus 34

** Exodus 34:1

And after this he said: Hew thee two tables of stone like unto the former, and I will write upon them the words, which were in the tables, which thou brokest.

** Exodus 34:2

Be ready in the morning, that thou mayst forthwith go up into Mount Sinai, and thou shalt stand with me upon the top of the mount.

** Exodus 34:3

Let no man go up with thee, and let not any man be seen throughout all the mount; neither let the oxen nor the sheep feed over against it.

** Exodus 34:4

Then he cut out two tables of stone, such as had been before; and rising very early he went up into the Mount Sinai, as the Lord had commanded him, carrying with him the tables.

** Exodus 34:5

And when the Lord was come down in a cloud, Moses stood with him, calling upon the name of the Lord.

** Exodus 34:6

And when he passed before him, he said: O the Lord, the Lord God, merciful and gracious, patient and of much compassion, and true,

** Exodus 34:7

Who keepest mercy unto thousands: who takest away iniquity, and wickedness, and sin, and no man of himself is innocent before thee. Who renderest the iniquity of the fathers to the children, and to the grandchildren unto the third and fourth generation.

** Exodus 34:8

And Moses making haste, bowed down prostrate unto the earth, and adoring,

** Exodus 34:9

Said: If I have found grace in thy sight, O Lord, I beseech thee that thou wilt go with us, (for it is a stiffnecked people) and take away our iniquities and sin, and possess us.

** Exodus 34:10

The Lord answered: I will make a covenant in the sight of all, I will do signs such as were never seen upon the earth, nor in any nations; that this people, in the midst of whom thou art, may see the terrible work of the Lord which I will do.

** Exodus 34:11

Observe all things which this day I command thee: I myself will drive out before thy face the Amorrhite, and the Chanaanite, and the Hethite, and the Pherezite, and the Hevite, and the Jebusite.

** Exodus 34:12

Beware thou never join in friendship with the inhabitants of that land, which may be thy ruin:

** Exodus 34:13

But destroy their altars, break their statues and cut down their groves:

** Exodus 34:14

Adore not any strange god. The Lord his name is jealous, he is a jealous God.

** Exodus 34:15

Make no covenant with the men of those countries; lest, when they have committed fornication with their gods, and have adored their idols, some one call thee to eat of the things sacrificed.

** Exodus 34:16

Neither shalt thou take of their daughters a wife for thy son, lest after they themselves have committed fornication, they make thy sons also to commit fornication with their gods.

** Exodus 34:17

Thou shalt not make to thyself any molten gods.

** Exodus 34:18

Thou shalt keep the feast of the unleavened bread. Seven days shalt thou eat unleavened bread, as I commanded thee in the time of the month of the new corn: for in the month of the spring time thou camest out from Egypt.

** Exodus 34:19

All of the male kind that openeth the womb, shall be mine. Of all beasts; both of oxen and of sheep, it shall be mine.

** Exodus 34:20

The firstling of an ass thou shalt redeem with a sheep: but if thou wilt not give a price for it, it shall be slain. The firstborn of thy sons thou shalt redeem: neither shalt thou appear before me empty.

** Exodus 34:21

Six days shalt thou work, the seventh day thou shalt cease to plough and to reap.

** Exodus 34:22

Thou shalt keep the feast of weeks with the firstfruits of the corn of thy wheat harvest, and the feast when the time of the year returneth that all things are laid in.

** Exodus 34:23

Three times in the year all thy males shall appear in the sight of the almighty Lord the God of Israel.

** Exodus 34:24

For when I shall have taken away the nations from thy face, and shall have enlarged thy borders, no man shall lie in wait against thy land when thou shalt go up, and appear in the sight of the Lord thy God thrice in a year.

** Exodus 34:25

Thou shalt not offer the blood of my sacrifice upon leaven; neither shall there remain in the morning any thing of the victim of the solemnity of the Phase.

** Exodus 34:26

The first of the fruits of thy ground thou shalt offer in the house of the Lord thy God. Thou shalt not boil a kid in the milk of his dam.

** Exodus 34:27

And the Lord said to Moses: Write thee these words, by which I have made a covenant both with thee and with Israel.

** Exodus 34:28

And he was there with the Lord forty days and forty nights: he neither ate bread nor drank water, and he wrote upon the tables the ten words of the covenant.

** Exodus 34:29

And when Moses came down from the Mount Sinai, he held the two tables of the testimony, and he knew not that his face was horned from the conversation of the Lord.

** Exodus 34:30

And Aaron and the children of Israel seeing the face of Moses horned, were afraid to come near.

** Exodus 34:31

And being called by him, they returned, both Aaron and the rulers of the congregation. And after that he spoke to them,

** Exodus 34:32

And all the children of Israel came to him: and he gave them in commandment all that he had heard of the Lord on Mount Sinai.

** Exodus 34:33

And having done speaking, he put a veil upon his face.

** Exodus 34:34

But when he went in to the Lord, and spoke with him, he took it away until he came forth, and then he spoke to the children of Israel all things that had been commanded him.

** Exodus 34:35

And they saw that the face of Moses when he came out was horned, but he covered his face again, if at any time he spoke to them. 

* Exodus 35

** Exodus 35:1

And all the multitude of the children of Israel being gathered together, he said to them: These are the things which the Lord hath commanded to be done:

** Exodus 35:2

Six days you shall do work; the seventh day shall be holy unto you, the sabbath and the rest of the Lord: he that shall do any work on it, shall be put to death.

** Exodus 35:3

You shall kindle no fire in any of your habitations on the sabbath day.

** Exodus 35:4

And Moses said to all the assembly of the children of Israel: This is the word the Lord hath commanded, saying:

** Exodus 35:5

Set aside with you firstfruits to the Lord. Let every one that is willing and hath a ready heart, offer them to the Lord: gold, and silver, and brass,

** Exodus 35:6

Violet and purple, and scarlet twice dyed, and fine linen, goats' hair,

** Exodus 35:7

And rams' skins dyed red, and violet coloured skins, setim wood,

** Exodus 35:8

And oil to maintain lights, and to make ointment, and most sweet incense,

** Exodus 35:9

Onyx stones, and precious stones, for the adorning of the ephod and the rational.

** Exodus 35:10

Whosoever of you is wise, let him come, and make that which the Lord hath commanded:

** Exodus 35:11

To wit, the tabernacle, and the roof thereof, and the cover, the rings, and the board-work with the bars, the pillars and the sockets:

** Exodus 35:12

The ark and the staves, the propitiatory, and the veil that is drawn before it:

** Exodus 35:13

The table with the bars and the vessels, and the loaves of proposition:

** Exodus 35:14

The candlestick to bear up the lights, the vessels thereof and the lamps, and the oil for the nourishing of fires:

** Exodus 35:15

The altar of incense, and the bars, and the oil of unction, and the incense of spices: the hanging at the door of the tabernacle:

** Exodus 35:16

The altar of holocaust, and its grate of brass, with the bars and vessels thereof: the laver and its foot:

** Exodus 35:17

The curtains of the court, with the pillars and the sockets, the hanging in the doors of the entry.

** Exodus 35:18

The pins of the tabernacle, and of the court, with their little cords:

** Exodus 35:19

The vestments that are to be used in the ministry of the sanctuary, the vesture of Aaron the high priest, and of his sons, to do the office of priesthood to me.

** Exodus 35:20

And all the multitude of the children of Israel going out from the presence of Moses,

** Exodus 35:21

Offered firstfruits to the Lord with a most ready and devout mind, to make the work of the tabernacle of the testimony. Whatever was necessary to the service and to the holy vestments,

** Exodus 35:22

Both men and women gave bracelets and earrings, rings and tablets: every vessel of gold was set aside to be offered to the Lord.

** Exodus 35:23

If any man had violet, and purple, and scarlet twice dyed, fine linen and goats' hair, ramskins dyed red, and violet coloured skins,

** Exodus 35:24

Metal of silver and brass, they offered it to the Lord, and setim wood for divers uses.

** Exodus 35:25

The skilful women also gave such things as they had spun, violet, purple, and scarlet, and fine linen,

** Exodus 35:26

And goats' hair, giving all of their own accord.

** Exodus 35:27

But the princes offered onyx stones, and precious stones, for the ephod and the rational,

** Exodus 35:28

And spices and oil for the lights, and for the preparing of ointment, and to make the incense of most sweet savour.

** Exodus 35:29

All, both men and women, with devout mind offered gifts, that the works might be done which the Lord had commanded by the hand of Moses. All the children of Israel dedicated voluntary offerings to the Lord.

** Exodus 35:30

And Moses said to the children of Israel: Behold, the Lord hath called by name Beseleel, the son of Uri, the son of Hur, of the tribe of Juda,

** Exodus 35:31

And hath filled him with the spirit of God, with wisdom and understanding, and knowledge, and all learning,

** Exodus 35:32

To devise and to work in gold and silver and brass,

** Exodus 35:33

And in engraving stones, and in carpenters' work. Whatsoever can be devised artificially,

** Exodus 35:34

He hath given in his heart: Ooliab also, the son of Achisamech, of the tribe of Dan:

** Exodus 35:35

Both of them hath he instructed with wisdom, to do carpenters' work, and tapestry, and embroidery in blue and purple, and scarlet twice dyed, and fine linen, and to weave all things, and to invent all new things. 

* Exodus 36

** Exodus 36:1

Beseleel therefore, and Ooliab, and every wise man, to whom the Lord gave wisdom and understanding, to know how to work artificially, made the things that are necessary for the uses of the sanctuary, and which the Lord commanded.

** Exodus 36:2

And when Moses had called them, and every skilful man, to whom the Lord had given wisdom, and such as of their own accord had offered themselves to the making of the work,

** Exodus 36:3

He delivered all the offerings of the children of Israel unto them. And while they were earnest about the work, the people daily in the morning offered their vows.

** Exodus 36:4

Whereupon the workmen being constrained to come,

** Exodus 36:5

Said to Moses: The people offereth more than is necessary.

** Exodus 36:6

Moses therefore commanded proclamation to be made by the crier's voice: Let neither man nor woman offer any more for the work of the sanctuary. And so they ceased from offering gifts,

** Exodus 36:7

Because the things that were offered did suffice, and were too much.

** Exodus 36:8

And all the men that were wise of heart, to accomplish the work of the tabernacle, made ten curtains of twisted fine linen, and violet, and purple, and scarlet twice dyed, with varied work, and the art of embroidering:

** Exodus 36:9

The length of one curtain was twenty-eight cubits, and the breadth four: all the curtains were of the same size.

** Exodus 36:10

And he joined five curtains, one to another, and the other five he coupled one to another.

** Exodus 36:11

He made also loops of violet in the edge of one curtain on both sides, and in the edge of the other curtain in like manner,

** Exodus 36:12

That the loops might meet one against another, and might be joined each with the other.

** Exodus 36:13

Whereupon also he cast fifty rings of gold, that might catch the loops of the curtains, and they might be made one tabernacle.

** Exodus 36:14

He made also eleven curtains of goats' hair, to cover the roof of the tabernacle:

** Exodus 36:15

One curtain was thirty cubits long, and four cubits broad: all the curtains were of one measure.

** Exodus 36:16

Five of which he joined apart, and the other six apart.

** Exodus 36:17

And he made fifty loops in the edge of one curtain, and fifty in the edge of another curtain, that they might be joined one to another.

** Exodus 36:18

And fifty buckles of brass wherewith the roof might be knit together, that of all the curtains there might be made one covering.

** Exodus 36:19

He made also a cover for the tabernacle of rams' skins dyed red; and another cover over that of violet skins.

** Exodus 36:20

He made also the boards of the tabernacle of setim wood standing.

** Exodus 36:21

The length of one board was ten cubits; and the breadth was one cubit and a half.

** Exodus 36:22

There were two mortises throughout every board, that one might be joined to the other. And in this manner he made for all the boards of the tabernacle.

** Exodus 36:23

Of which twenty were at the south side southward,

** Exodus 36:24

With forty sockets of silver, two sockets were put under one board on the two sides of the corners, where the mortises of the sides end in the corners.

** Exodus 36:25

At that side also of the tabernacle, that looketh towards the north, he made twenty boards,

** Exodus 36:26

With forty sockets of silver, two sockets for every board.

** Exodus 36:27

But against the west, to wit, at that side of the tabernacle, which looketh to the sea, he made six boards,

** Exodus 36:28

And two others at each corner of the tabernacle behind:

** Exodus 36:29

Which were also joined from beneath unto the top, and went together into one joint. Thus he did on both sides at the corners:

** Exodus 36:30

So there were in all eight boards, and they had sixteen sockets of silver, to wit, two sockets under every board.

** Exodus 36:31

He made also bars of setim wood, five to hold together the boards of one side of the tabernacle,

** Exodus 36:32

And five others to join together the boards of the other side; and besides these, five other bars at the west side of the tabernacle towards the sea.

** Exodus 36:33

He made also another bar, that might come by the midst of the boards from corner to corner.

** Exodus 36:34

And the boards themselves he overlaid with gold casting for them sockets of silver. And their rings he made of gold, through which the bars might be drawn: and he covered the bars themselves with plates of gold.

** Exodus 36:35

He made also a veil of violet, and purple, scarlet and fine twisted linen, varied and distinguished with embroidery:

** Exodus 36:36

And four pillars of setim wood, which with their heads he overlaid with gold, casting for them sockets of silver.

** Exodus 36:37

He made also a hanging in the entry of the tabernacle of violet, purple, scarlet, and fine twisted linen, with the work of an embroiderer.

** Exodus 36:38

And five pillars with their heads, which he covered with gold, and their sockets he cast of brass. 

* Exodus 37

** Exodus 37:1

And Beseleel made also, the ark of setim wood: it was two cubits and a half in length, and a cubit and a half in breadth, and the height was of one cubit and a half: and he overlaid it with the purest gold within and without.

** Exodus 37:2

And he made to it a crown of gold round about,

** Exodus 37:3

Casting four rings of gold at the four corners thereof: two rings in one side, and two in the other.

** Exodus 37:4

And he made bars of setim wood, which he overlaid with gold,

** Exodus 37:5

And he put them into the rings that were at the sides of the ark to carry it.

** Exodus 37:6

He made also the propitiatory, that is, the oracle, of the purest gold, two cubits and a half in length, and a cubit and a half in breadth.

** Exodus 37:7

Two cherubims also of beaten gold, which he set on the two sides of the propitiatory:

** Exodus 37:8

One cherub in the top of one side, and the other cherub in the top of the other side: two cherubims at the two ends of the propitiatory,

** Exodus 37:9

Spreading their wings, and covering the propitiatory, and looking one towards the other, and towards it.

** Exodus 37:10

He made also the table of setim wood, in length two cubits, and in breadth one cubit, and in height it was a cubit and a half.

** Exodus 37:11

And he overlaid it with the finest gold, and he made to it a golden ledge round about,

** Exodus 37:12

And to the ledge itself he made a polished crown of gold, of four fingers breadth, and upon the same another golden crown.

** Exodus 37:13

And he cast four rings of gold, which he put in the four corners at each foot of the table,

** Exodus 37:14

Over against the crown: and he put the bars into them, that the table might be carried.

** Exodus 37:15

The bars also themselves he made of setim wood, and overlaid them with gold.

** Exodus 37:16

And the vessels for the divers uses of the table, dishes, bowls, and cups, and censers of pure gold, wherein the libations are to be offered.

** Exodus 37:17

He made also the candlestick of beaten work of the finest gold. from the shaft whereof its branches, its cups, and bowls, and lilies came out:

** Exodus 37:18

Six on the two sides: three branches on one side, and three on the other.

** Exodus 37:19

Three cups in manner of a nut on each branch, and bowls withal and lilies: and three cups of the fashion of a nut in another branch, and bowls withal and lilies. The work of the six branches, that went out from the shaft of the candlestick was equal.

** Exodus 37:20

And in the shaft itself were four cups after the manner of a nut, and bowls withal at every one, and lilies:

** Exodus 37:21

And bowls under two branches in three places, which together made six branches going out from one shaft.

** Exodus 37:22

So both the bowls, and the branches were of the same, all beaten work of the purest gold.

** Exodus 37:23

He made also the seven lamps with their snuffers, and the vessels where the snuffings were to be put out, of the purest gold.

** Exodus 37:24

The candlestick with all the vessels thereof weighed a talent of gold.

** Exodus 37:25

He made also the alter of incense of setim wood, being a cubit on every side foursquare, and in height two cubits: from the corners of which went out horns.

** Exodus 37:26

And he overlaid it with the purest gold, with its grate, and the sides, and the horns.

** Exodus 37:27

And he made to it a crown of gold round about, and two golden rings under the crown at each side, that the bars might be put into them, and the altar be carried.

** Exodus 37:28

And the bars themselves he made also of setim wood, and overlaid them with plates of gold.

** Exodus 37:29

He compounded also the oil for the ointment of sanctification, and incense of the purest spices, according to the work of a perfumer. 

* Exodus 38

** Exodus 38:1

He made also the altar of holocaust of setim wood, five cubits square, and three in height:

** Exodus 38:2

The horns whereof went out from the corners, and he overlaid it with plates of brass.

** Exodus 38:3

And for the uses thereof, he prepared divers vessels of brass, cauldrons, tongs, fleshhooks, pothooks and firepans.

** Exodus 38:4

And he made the grate thereof of brass, in manner of a net, and under it in the midst of the altar a hearth,

** Exodus 38:5

Casting four rings at the four ends of the net at the top, to put in bars to carry it:

** Exodus 38:6

And he made the bars of setim wood, and overlaid them with plates of brass:

** Exodus 38:7

And he drew them through the rings that stood out in the sides of the altar. And the altar itself was not solid, but hollow, of boards, and empty within.

** Exodus 38:8

He made also the laver of brass, with the foot thereof, of the mirrors of the women that watched at the door of the tabernacle.

** Exodus 38:9

He made also the court, in the south side whereof were hangings of fine twisted linen of a hundred cubits.

** Exodus 38:10

Twenty pillars of brass with their sockets, the heads of the pillars, and the whole graving of the work, of silver.

** Exodus 38:11

In like manner at the north side the hangings, the pillars, and the sockets and heads of the pillars were of the same measure, and work and metal.

** Exodus 38:12

But on that side that looketh to the west, there were hangings of fifty cubits, ten pillars of brass with their sockets, and the heads of the pillars, and all the graving of the work, of silver.

** Exodus 38:13

Moreover, towards the east he prepared hangings of fifty cubits:

** Exodus 38:14

Fifteen cubits of which, were on one side with three pillars, and their sockets:

** Exodus 38:15

And on the other side (for between the two he made the entry of the tabernacle) there were hangings equally of fifteen cubits, and three pillars, and as many sockets.

** Exodus 38:16

All the hangings of the court were woven with twisted linen.

** Exodus 38:17

The sockets of the pillars were of brass, and their heads with all their gravings of silver: and he overlaid the pillars of the court also with silver.

** Exodus 38:18

And he made in the entry thereof an embroidered hanging of violet, purple, scarlet, and fine twisted linen, that was twenty cubits long, and five cubits high, according to the measure of all the hangings of the court.

** Exodus 38:19

And the pillars in the entry were four, with sockets of brass, and their heads and gravings of silver.

** Exodus 38:20

The pins also of the tabernacle and of the court round about he made of brass.

** Exodus 38:21

These are the instruments of the tabernacle of the testimony, which were counted according to the commandment of Moses, in the ceremonies of the Levites, by the hand of Ithamar, son of Aaron the priest:

** Exodus 38:22

Which Beseleel, the son of Uri, the son of Hur of the tribe of Juda, had made, as the Lord commanded by Moses.

** Exodus 38:23

Having for his companion Ooliab, the son of Achisamech, of the tribe of Dan: who also was an excellent artificer in wood, and worker in tapestry and embroidery in violet, purple, scarlet, and fine linen.

** Exodus 38:24

All the gold that was spent in the work of the sanctuary, and that was offered in gifts, was nine and twenty talents, and seven hundred and thirty sicles according to the standard of the sanctuary.

** Exodus 38:25

And it was offered by them that went to be numbered, from twenty years old and upwards, of six hundred and three thousand five hundred and fifty men able to bear arms.

** Exodus 38:26

There were moreover a hundred talents of silver, whereof were cast the sockets of the sanctuary, and of the entry where the veil hangeth.

** Exodus 38:27

A hundred sockets were made of a hundred talents, one talent being reckoned for every socket.

** Exodus 38:28

And of the thousand seven hundred and seventy-five he made the heads of the pillars, which also he overlaid with silver.

** Exodus 38:29

And there were offered of brass also seventy-two thousand talents, and four hundred sicles besides,

** Exodus 38:30

Of which were cast the sockets in the entry of the tabernacle of the testimony, and the altar of brass with the grate thereof, and also the vessels that belong to the use thereof.

** Exodus 38:31

And the sockets of the court as well round about as in the entry thereof, and the pins of the tabernacle, and of the court round about. 

* Exodus 39

** Exodus 39:1

And he made, of violet and purple, scarlet and fine linen, the vestments for Aaron to wear when he ministered in the holy places, as the Lord commanded Moses.

** Exodus 39:2

So he made an ephod of gold, violet, and purple, and scarlet twice dyed, and fine twisted linen,

** Exodus 39:3

With embroidered work, and he cut thin plates of gold, and drew them small into threads, that they might be twisted with the woof of the foresaid colours,

** Exodus 39:4

And two borders coupled one to the other in the top on either side,

** Exodus 39:5

And a girdle of the same colours, as the Lord had commanded Moses.

** Exodus 39:6

He prepared also two onyx stones, fast set and closed in gold, and graven, by the art of a lapidary, with the names of the children of Israel:

** Exodus 39:7

And he set them in the sides of the ephod, for a memorial of the children of Israel, as the Lord had commanded Moses.

** Exodus 39:8

He made also a rational with embroidered work, according to the work of the ephod, of gold, violet, purple, and scarlet twice dyed, and fine twisted linen:

** Exodus 39:9

Foursquare, double, of the measure of a span.

** Exodus 39:10

And he set four rows of precious stones in it. In the first row was a sardius, a topaz, an emerald.

** Exodus 39:11

In the second, a carbuncle, a sapphire, and a jasper.

** Exodus 39:12

In the third, a ligurius, an agate, and an amethyst.

** Exodus 39:13

In the fourth, a chrysolite, an onyx, and a beryl, set and enclosed in gold by their rows.

** Exodus 39:14

And the twelve stones, were engraved with the names of the twelve tribes of Israel, each one with its several name.

** Exodus 39:15

They made also in the rational little chains, linked one to another, of the purest gold,

** Exodus 39:16

And two hooks, and as many rings of gold. And they set the rings on either side of the rational,

** Exodus 39:17

On which rings the two golden chains should hang, which they put into the hooks that stood out in the corners of the ephod.

** Exodus 39:18

These both before and behind so answered one another, that the ephod and the rational were bound together,

** Exodus 39:19

Being fastened to the girdle, and strongly coupled with rings, which a violet fillet joined, lest they should flag loose, and be moved one from the other, as the Lord commanded Moses.

** Exodus 39:20

They made also the tunic of the ephod all of violet,

** Exodus 39:21

And a hole for the head in the upper part at the middle, and a woven border round about the hole:

** Exodus 39:22

And beneath at the feet pomegranates of violet, purple, scarlet, and fine twisted linen:

** Exodus 39:23

And little bells of the purest gold, which they put between the pomegranates at the bottom of the tunic round about:

** Exodus 39:24

To wit, a bell of gold, and a pomegranate, wherewith the high priest went adorned, when he discharged his ministry, as the Lord had commanded Moses.

** Exodus 39:25

They made also fine linen tunics with woven work for Aaron and his sons:

** Exodus 39:26

And mitres with their little crowns of fine linen:

** Exodus 39:27

And linen breeches of fine linen:

** Exodus 39:28

And a girdle of fine twisted linen, violet, purple, and scarlet twice dyed, of embroidery work, as the Lord had commanded Moses.

** Exodus 39:29

They made also the plate of sacred veneration of the purest gold, and they wrote on it with the engraving of a lapidary: The Holy of the Lord:

** Exodus 39:30

And they fastened it to the mitre with a violet fillet, as the Lord had commanded Moses.

** Exodus 39:31

So all the work of the tabernacle and of the roof of the testimony was finished: and the children of Israel did all things which the Lord had commanded Moses.

** Exodus 39:32

And they offered the tabernacle, and the roof, and the whole furniture, the rings, the boards, the bars, the pillars and their sockets,

** Exodus 39:33

The cover of rams' skins dyed red, and the other cover of violet skins,

** Exodus 39:34

The veil, the ark, the bars, the propitiatory,

** Exodus 39:35

The table, with the vessels thereof, and the loaves of proposition:

** Exodus 39:36

The candlestick, the lamps, and the furniture of them, with the oil:

** Exodus 39:37

The altar of gold, and the ointment, and the incense of spices:

** Exodus 39:38

And the hanging in the entry of the tabernacle:

** Exodus 39:39

The altar of brass, the grate, the bars, and all the vessels thereof: the laver, with the foot thereof: the hangings of the court, and the pillars, with their sockets:

** Exodus 39:40

The hanging in the entry of the court, and the little cords, and the pins thereof. Nothing was wanting of the vessels, that were commanded to be made for the ministry of the tabernacle, and for the roof of the covenant.

** Exodus 39:41

The vestments also, which the priests, to wit, Aaron and his sons, use in the sanctuary,

** Exodus 39:42

The children of Israel offered, as the Lord had commanded.

** Exodus 39:43

And when Moses saw all things finished, he blessed them. 

* Exodus 40

** Exodus 40:1

And the Lord spoke to Moses, saying:

** Exodus 40:2

The first month, the first day of the month, thou shalt set up the tabernacle of the testimony,

** Exodus 40:3

And shalt put the ark in it, and shalt let down the veil before it:

** Exodus 40:4

And thou shalt bring in the table, and set upon it the things that are commanded according to the rite. The candlestick shall stand with its lamps,

** Exodus 40:5

And the altar of gold, whereon the incense is burnt before the ark of the testimony. Thou shalt put the hanging in the entry of the tabernacle,

** Exodus 40:6

And before it the altar of holocaust.

** Exodus 40:7

The laver between the altar and the tabernacle, and thou shalt fill it with water.

** Exodus 40:8

And thou shalt encompass the court with hangings, and the entry thereof.

** Exodus 40:9

And thou shalt take the oil of unction and anoint the tabernacle with its vessels, that they may be sanctified:

** Exodus 40:10

The altar of holocaust and all its vessels:

** Exodus 40:11

The laver with its foot: thou shalt consecrate all with the oil of unction, that they may be most holy.

** Exodus 40:12

And thou shalt bring Aaron and his sons to the door of the tabernacle of the testimony, and having washed them with water,

** Exodus 40:13

Thou shalt put on them the holy vestments, that they may minister to me, and that the unction of them may prosper to an everlasting priesthood.

** Exodus 40:14

And Moses did all that the Lord had commanded.

** Exodus 40:15

So in the first month of the second year, the first day of the month, the tabernacle was set up.

** Exodus 40:16

And Moses reared it up, and placed the boards and the sockets and the bars, and set up the pillars,

** Exodus 40:17

And spread the roof over the tabernacle, putting over it a cover, as the Lord had commanded.

** Exodus 40:18

And he put the testimony in the ark, thrusting bars underneath, and the oracle above.

** Exodus 40:19

And when he had brought the ark into the tabernacle, he drew the veil before it to fulfil the commandment of the Lord.

** Exodus 40:20

And he set the table in the tabernacle of the testimony, at the north side, without the veil,

** Exodus 40:21

Setting there in order the loaves of proposition, as the Lord had commanded Moses.

** Exodus 40:22

He set the candlestick also in the tabernacle of the testimony, over against the table on the south side,

** Exodus 40:23

Placing the lamps in order, according to the precept of the Lord.

** Exodus 40:24

He set also the altar of gold under the roof of the testimony, over against the veil,

** Exodus 40:25

And burnt upon it the incense of spices, as the Lord had commanded Moses.

** Exodus 40:26

And he put also the hanging in the entry of the tabernacle of the testimony,

** Exodus 40:27

And the altar of holocaust in the entry of the testimony, offering the holocaust, and the sacrifices upon it, as the Lord had commanded.

** Exodus 40:28

And he set the laver between the tabernacle of the testimony and the altar, filling it with water.

** Exodus 40:29

And Moses and Aaron, and his sons, washed their hands and feet,

** Exodus 40:30

When they went into the tabernacle of the covenant, and went to the altar, as the Lord had commanded Moses.

** Exodus 40:31

He set up also the court round about the tabernacle and the altar, drawing the hanging in the entry thereof. After all things were perfected,

** Exodus 40:32

The cloud covered the tabernacle of the testimony, and the glory of the Lord filled it.

** Exodus 40:33

Neither could Moses go into the tabernacle of the covenant, the cloud covering all things, and the majesty of the Lord shining, for the cloud had covered all.

** Exodus 40:34

If at any time the cloud removed from the tabernacle, the children of Israel went forward by their troops:

** Exodus 40:35

If it hung over, they remained in the same place.

** Exodus 40:36

For the cloud of the Lord hung over the tabernacle by day, and a fire by night, in the sight of all the children of Israel throughout all their mansions.  

