* Job 1

** Job 1:1

There was a man in the land of Hus, whose name was Job, and that man was simple and upright, and fearing God, and avoiding evil.

** Job 1:2

And there were born to him seven sons and three daughters.

** Job 1:3

And his possession was seven thousand sheep, and three thousand camels, and five hundred yoke of oxen, and five hundred she asses, and a family exceedingly great: and this man was great among all the people of the east.

** Job 1:4

And his sons went, and made a feast by houses, every one in his day. And sending, they called their three sisters, to eat and drink with them.

** Job 1:5

And when the days of their feasting were gone about, Job sent to them, and sanctified them: and rising up early, offered holocausts for every one of them. For he said: Lest perhaps my sons have sinned, and have blessed God in their hearts. So did Job all days.

** Job 1:6

Now on a certain day, when the sons of God came to stand before the Lord, Satan also was present among them.

** Job 1:7

And the Lord said to him: Whence comest thou? And he answered and said: I have gone round about the earth, and walked through it.

** Job 1:8

And the Lord said to him: Hast thou considered my servant, Job, that there is none like him in the earth, a simple and upright man, and fearing God, and avoiding evil?

** Job 1:9

And Satan answering, said: Doth Job fear God in vain?

** Job 1:10

Hast thou not made a fence for him, and his house, and all his substance round about, blessed the works of his hands, and his possession hath increased on the earth?

** Job 1:11

But stretch forth thy hand a little, and touch all that he hath, and see if he bless thee not to thy face.

** Job 1:12

Then the Lord said to Satan: Behold, all that he hath is in thy hand: only put not forth thy hand upon his person. And Satan went forth from the presence of the Lord.

** Job 1:13

Now upon a certain day, when his sons and daughters were eating and drinking wine, in the house of their eldest brother,

** Job 1:14

There came a messenger to Job, and said: The oxen were ploughing, and the asses feeding beside them,

** Job 1:15

And the Sabeans rushed in, and took all away, and slew the servants with the sword; and I alone have escaped to tell thee.

** Job 1:16

And while he was yet speaking, another came, and said: The fire of God fell from heaven, and striking the sheep and the servants, hath consumed them; and I alone have escaped to tell thee.

** Job 1:17

And while he also was yet speaking, there came another, and said: The Chaldeans made three troops, and have fallen upon the camels, and taken them; moreover, they have slain the servants with the sword: and I alone have escaped to tell thee.

** Job 1:18

He was yet speaking, and behold another came in, and said: Thy sons and daughters were eating and drinking wine in the house of their eldest brother,

** Job 1:19

A violent wind came on a sudden from the side of the desert, and shook the four corners of the house, and it fell upon thy children, and they are dead: and I alone have escaped to tell thee.

** Job 1:20

Then Job rose up, and rent his garments, and having shaven his head, fell down upon the ground, and worshipped,

** Job 1:21

And said: Naked came I out of my mother's womb, and naked shall I return thither: the Lord gave, and the Lord hath taken away: as it hath pleased the Lord, so is it done: blessed be the name of the Lord.

** Job 1:22

In all these things Job sinned not by his lips, nor spoke he any foolish thing against God. 

* Job 2

** Job 2:1

And it came to pass, when on a certain day the sons of God came, and stood before the Lord, and Satan came amongst them, and stood in his sight,

** Job 2:2

That the Lord said to Satan: Whence comest thou? And he answered, and said: I have gone round about the earth, and walked through it.

** Job 2:3

And the Lord said to Satan: Hast thou considered my servant, Job, that there is none like him in the earth, a man simple and upright, and fearing God, and avoiding evil, and still keeping his innocence? But thou hast moved me against him, that I should afflict him without cause.

** Job 2:4

And Satan answered, and said: Skin for skin; and all that a man hath, he will give for his life:

** Job 2:5

But put forth thy hand, and touch his bone and his flesh, and then thou shalt see that he will bless thee to thy face.

** Job 2:6

And the Lord said to Satan: Behold, he is in thy hand, but yet save his life.

** Job 2:7

So Satan went forth from the presence of the Lord, and struck Job with a very grievous ulcer, from the sole of the foot even to the top of his head:

** Job 2:8

And he took a potsherd and scraped the corrupt matter, sitting on a dunghill.

** Job 2:9

And his wife said to him: Dost thou still continue in thy simplicity? bless God and die.

** Job 2:10

And he said to her: Thou hast spoken like one of the foolish women: If we have received good things at the hand of God, why should we not receive evil? In all these things Job did not sin with his lips.

** Job 2:11

Now when Job's three friends heard all the evil that had befallen him, they came every one from his own place, Eliphaz, the Themanite, and Baldad, the Suhite, and Sophar, the Naamathite. For they had made an appointment to come together and visit him, and comfort him.

** Job 2:12

And when they had lifted up their eyes afar off, they knew him not, and crying out, they wept, and rending their garments, they sprinkled dust upon their heads toward heaven.

** Job 2:13

And they sat with him on the ground seven day and seven nights and no man spoke to him a word: for they saw that his grief was very great. 

* Job 3

** Job 3:1

After this, Job opened his mouth, and cursed his day,

** Job 3:2

And he said:

** Job 3:3

Let the day perish wherein I was born, and the night in which it was said: A man child is conceived.

** Job 3:4

Let that day be turned into darkness, let not God regard it from above, and let not the light shine upon it.

** Job 3:5

Let darkness, and the shadow of death, cover it, let a mist overspread it, and let it be wrapped up in bitterness.

** Job 3:6

Let a darksome whirlwind seize upon that night, let it not be counted in the days of the year, nor numbered in the months.

** Job 3:7

Let that night be solitary, and not worthy of praise.

** Job 3:8

Let them curse it who curse the day, who are ready to raise up a leviathan:

** Job 3:9

Let the stars be darkened with the mist thereof: let it expect light, and not see it, nor the rising of the dawning of the day:

** Job 3:10

Because it shut not up the doors of the womb that bore me, nor took away evils from my eyes.

** Job 3:11

Why did I not die in the womb? why did I not perish when I came out of the belly?

** Job 3:12

Why received upon the knees? why suckled at the breasts?

** Job 3:13

For now I should have been asleep and still, and should have rest in my sleep:

** Job 3:14

With kings and consuls of the earth, who build themselves solitudes:

** Job 3:15

Or with princes, that possess gold, and fill their houses with silver:

** Job 3:16

Or as a hidden untimely birth, I should not be; or as they that, being conceived, have not seen the light.

** Job 3:17

There the wicked cease from tumult, and there the wearied in strength are at rest.

** Job 3:18

And they sometime bound together without disquiet, have not heard the voice of the oppressor.

** Job 3:19

The small and great are there, and the servant is free from his master.

** Job 3:20

Why is light given to him that is in misery, and life to them that are in bitterness of soul?

** Job 3:21

That look for death, and it cometh not, as they that dig for a treasure:

** Job 3:22

And they rejoice exceedingly when they have found the grave?

** Job 3:23

To a man whose way is hidden, and God hath surrounded him with darkness?

** Job 3:24

Before I eat I sigh: and as overflowing waters, so is my roaring:

** Job 3:25

For the fear which I feared, hath come upon me: and that which I was afraid of, hath befallen me.

** Job 3:26

Have I not dissembled? have I not kept silence? have I not been quiet? and indignation is come upon me. 

* Job 4

** Job 4:1

Then Eliphaz, the Themanite, answered, and said:

** Job 4:2

If we begin to speak to thee, perhaps thou wilt take it ill; but who can withhold the words he hath conceived?

** Job 4:3

Behold thou hast taught many, and thou hast strengthened the weary hands:

** Job 4:4

Thy words have confirmed them that were staggering, and thou hast strengthened the trembling knees:

** Job 4:5

But now the scourge is come upon thee, and thou faintest: It hath touched thee, and thou art troubled.

** Job 4:6

Where is thy fear, thy fortitude, thy patience, and the perfection of thy ways?

** Job 4:7

Remember, I pray thee, who ever perished being innocent? or when were the just destroyed?

** Job 4:8

On the contrary, I have seen those who work iniquity, and sow sorrows, and reap them,

** Job 4:9

Perishing by the blast of God, and consumed by the spirit of his wrath.

** Job 4:10

The roaring of the lion, and the voice of the lioness, and the teeth of the whelps of lions, are broken:

** Job 4:11

The tiger hath perished for want of prey, and the young lions are scattered abroad.

** Job 4:12

Now there was a word spoken to me in private, and my ears by stealth, as it were, received the veins of its whisper.

** Job 4:13

In the horror of a vision by night, when deep sleep is wont to hold men,

** Job 4:14

Fear seized upon me, and trembling, and all my bones were affrighted:

** Job 4:15

And when a spirit passed before me, the hair of my flesh stood up.

** Job 4:16

There stood one whose countenance I knew not, an image before my eyes, and I heard the voice, as it were, of a gentle wind.

** Job 4:17

Shall man be justified in comparison of God, or shall a man be more pure than his maker?

** Job 4:18

Behold, they that serve him are not steadfast, and in his angels he found wickedness:

** Job 4:19

How much more shall they that dwell in houses of clay, who have an earthly foundation, be consumed as with the moth?

** Job 4:20

From morning till evening they shall be cut down: and because no one understandeth, they shall perish for ever.

** Job 4:21

And they that shall be left, shall be taken away from them: they shall die, and not in wisdom. 

* Job 5

** Job 5:1

Call now, if there be any that will answer thee, and turn to some of the saints.

** Job 5:2

Anger indeed killeth the foolish, and envy slayeth the little one.

** Job 5:3

I have seen a fool with a strong root, and I cursed his beauty immediately.

** Job 5:4

His children shall be far from safety, and shall be destroyed in the gate, and there shall be none to deliver them.

** Job 5:5

Whose harvest the hungry shall eat, and the armed man shall take him by violence, and the thirsty shall drink up his riches.

** Job 5:6

Nothing upon earth is done without a cause, and sorrow doth not spring out of the ground.

** Job 5:7

Man is born to labour, and the bird to fly.

** Job 5:8

Wherefore I will pray to the Lord, and address my speech to God:

** Job 5:9

Who doth great things, and unsearchable and wonderful things without number:

** Job 5:10

Who giveth rain upon the face of the earth, and watereth all things with waters:

** Job 5:11

Who setteth up the humble on high, and comforteth with health those that mourn.

** Job 5:12

Who bringeth to nought the designs of the malignant, so that their hands cannot accomplish what they had begun:

** Job 5:13

Who catcheth the wise in their craftiness, and disappointeth the counsel of the wicked:

** Job 5:14

They shall meet with darkness in the day, and grope at noonday as in the night.

** Job 5:15

But he shall save the needy from the sword of their mouth, and the poor from the hand of the violent.

** Job 5:16

And to the needy there shall be hope, but iniquity shall draw in her mouth.

** Job 5:17

Blessed is the man whom God correcteth: refuse not, therefore, the chastising of the Lord.

** Job 5:18

For he woundeth, and cureth: he striketh, and his hands shall heal.

** Job 5:19

In six troubles he shall deliver thee, and in the seventh, evil shall not touch thee.

** Job 5:20

In famine he shall deliver thee from death; and in battle, from the hand of the sword.

** Job 5:21

Thou shalt be hidden from the scourge of the tongue: and thou shalt not fear calamity when it cometh.

** Job 5:22

In destruction and famine thou shalt laugh: and thou shalt not be afraid of the beasts of the earth.

** Job 5:23

But thou shalt have a covenant with the stones of the lands, and the beasts of the earth shall be at peace with thee.

** Job 5:24

And thou shalt know that thy tabernacle is in peace, and visiting thy beauty, thou shalt not sin.

** Job 5:25

Thou shalt know also that thy seed shall be multiplied, and thy offspring like the grass of the earth.

** Job 5:26

Thou shalt enter into the grave in abundance, as a heap of wheat is brought in its season.

** Job 5:27

Behold, this is even so, as we have searched out: which thou having heard, consider it thoroughly in thy mind. 

* Job 6

** Job 6:1

But Job answered, and said:

** Job 6:2

O that my sins, whereby I have deserved wrath, and the calamity that I suffer, were weighed in a balance.

** Job 6:3

As the sand of the sea, this would appear heavier: therefore, my words are full of sorrow:

** Job 6:4

For the arrows of the Lord are in me, the rage whereof drinketh up my spirit, and the terrors of the Lord war against me.

** Job 6:5

Will the wild ass bray when he hath grass? or will the ox low when he standeth before a full manger?

** Job 6:6

Or can an unsavoury thing be eaten, that is not seasoned with salt? or can a man taste that which, when tasted, bringeth death?

** Job 6:7

The things which before my soul would not touch, now, through anguish, are my meats.

** Job 6:8

Who will grant that my request may come: and that God may give me what I look for?

** Job 6:9

And that he that hath begun may destroy me, that he may let loose his hand, and cut me off?

** Job 6:10

And that this may be my comfort, that afflicting me with sorrow, he spare not, nor I contradict the words of the Holy one.

** Job 6:11

For what is my strength, that I can hold out? or what is my end, that I should keep patience?

** Job 6:12

My strength is not the strength of stones, nor is my flesh of brass.

** Job 6:13

Behold there is no help for me in myself, and my familiar friends also are departed from me.

** Job 6:14

He that taketh away mercy from his friend, forsaketh the fear of the Lord.

** Job 6:15

My brethren have passed by me, as the torrent that passeth swiftly in the valleys.

** Job 6:16

They that fear the hoary frost, the snow shall fall upon them.

** Job 6:17

At the time when they shall be scattered they shall perish: and after it groweth hot, they shall be melted out of their place.

** Job 6:18

The paths of their steps are entangled: they shall walk in vain, and shall perish.

** Job 6:19

Consider the paths of Thema, the ways of Saba, and wait a little while.

** Job 6:20

They are confounded, because I have hoped: they are come also even unto me, and are covered with shame.

** Job 6:21

Now you are come: and now, seeing my affliction, you are afraid.

** Job 6:22

Did I say: Bring to me, and give me of your substance?

** Job 6:23

Or deliver me from the hand of the enemy, and rescue me out of the hand of the mighty?

** Job 6:24

Teach me, and I will hold my peace: and if I have been ignorant of any thing, instruct me.

** Job 6:25

Why have you detracted the words of truth, whereas there is none of you that can reprove me?

** Job 6:26

You dress up speeches only to rebuke, and you utter words to the wind.

** Job 6:27

You rush in upon the fatherless, and you endeavour to overthrow your friend.

** Job 6:28

However, finish what you have begun: give ear and see whether I lie.

** Job 6:29

Answer, I beseech you, without contention: and speaking that which is just, judge ye.

** Job 6:30

And you shall not find iniquity in my tongue, neither shall folly sound in my mouth. 

* Job 7

** Job 7:1

The life of man upon earth is a warfare, and his days are like the days of a hireling.

** Job 7:2

As a servant longeth for the shade, as the hireling looketh for the end of his work;

** Job 7:3

So I also have had empty months, and have numbered to myself wearisome nights.

** Job 7:4

If I lie down to sleep, I shall say: When shall I rise? and again, I shall look for the evening, and shall be filled with sorrows even till darkness.

** Job 7:5

My flesh is clothed with rottenness and the filth of dust; my skin is withered and drawn together.

** Job 7:6

My days have passed more swiftly than the web is cut by the weaver, and are consumed without any hope.

** Job 7:7

Remember that my life is but wind, and my eye shall not return to see good things.

** Job 7:8

Nor shall the sight of man behold me: thy eyes are upon me, and I shall be no more.

** Job 7:9

As a cloud is consumed, and passeth away: so he that shall go down to hell shall not come up.

** Job 7:10

Nor shall he return any more into his house, neither shall his place know him any more

** Job 7:11

Wherefore, I will not spare my mouth, I will speak in the affliction of my spirit: I will talk with the bitterness of my soul.

** Job 7:12

Am I a sea, or a whale, that thou hast enclosed me in a prison?

** Job 7:13

If I say: My bed shall comfort me, and I shall be relieved, speaking with myself on my couch:

** Job 7:14

Thou wilt frighten me with dreams, and terrify me with visions.

** Job 7:15

So that my soul rather chooseth hanging, and my bones death.

** Job 7:16

I have done with hope, I shall now live no longer: spare me, for my days are nothing.

** Job 7:17

What is a man, that thou shouldst magnify him or why dost thou set thy heart upon him?

** Job 7:18

Thou visitest him early in the morning, and thou provest him suddenly.

** Job 7:19

How long wilt thou not spare me, nor suffer me to swallow down my spittle?

** Job 7:20

I have sinned: what shall I do to thee, O keeper of men? why hast thou set me opposite to thee. and am I become burdensome to myself?

** Job 7:21

Why dost thou not remove my sin, and why dost thou not take away my iniquity? Behold now I shall sleep in the dust: and if thou seek me in the morning, I shall not be. 

* Job 8

** Job 8:1

Then Baldad, the Suhite, answered, and said:

** Job 8:2

How long wilt thou speak these things, and how long shall the words of thy mouth be like a strong wind?

** Job 8:3

Doth God pervert judgment, or doth the Almighty overthrow that which is just?

** Job 8:4

Although thy children have sinned against him, and he hath left them in the hand of their iniquity:

** Job 8:5

Yet if thou wilt arise early to God, and wilt beseech the Almighty:

** Job 8:6

If thou wilt walk clean and upright, he will presently awake unto thee, and will make the dwelling of thy justice peaceable:

** Job 8:7

In so much, that if thy former things were small thy latter things would be multiplied exceedingly.

** Job 8:8

For inquire of the former generation, and search diligently into the memory of the fathers:

** Job 8:9

(For we are but of yesterday, and are ignorant that our days upon earth are but a shadow)

** Job 8:10

And they shall teach thee: they shall speak to thee, and utter words out of their hearts.

** Job 8:11

Can the rush be green without moisture? or sedge bush grow without water?

** Job 8:12

When it is yet in flower, and is not plucked up with the hand, it withereth before all herbs.

** Job 8:13

Even so are the ways of all that forget God, and the hope of the hypocrite shall perish:

** Job 8:14

His folly shall not please him, and his trust shall be like the spider's web.

** Job 8:15

He shall lean upon his house, and it shall not stand: he shall prop it up, and it shall not rise:

** Job 8:16

He seemeth to have moisture before the sun cometh; and at his rising, his blossom shall shoot forth.

** Job 8:17

His roots shall be thick upon a heap of stones; and among the stones he shall abide.

** Job 8:18

If one swallow him up out of his place, he shall deny him, and shall say: I know thee not.

** Job 8:19

For this is the joy of his way, that others may spring again out of the earth.

** Job 8:20

God will not cast away the simple, nor reach out his hand to the evil doer:

** Job 8:21

Until thy mouth be filled with laughter, and thy lips with rejoicing.

** Job 8:22

They that hate thee, shall be clothed with confusion: and the dwelling of the wicked shall not stand. 

* Job 9

** Job 9:1

And Job answered, and said:

** Job 9:2

Indeed I know it is so, and that man cannot be justified, compared with God.

** Job 9:3

If he will contend with him, he cannot answer him one for a thousand.

** Job 9:4

He is wise in heart, and mighty in strength: who hath resisted him, and hath had peace?

** Job 9:5

Who hath removed mountains, and they whom he overthrew in his wrath, knew it not.

** Job 9:6

Who shaketh the earth out of her place, and the pillars thereof tremble.

** Job 9:7

Who commandeth the sun, and it riseth not: and shutteth up the stars, as it were, under a seal:

** Job 9:8

Who alone spreadeth out the heavens, and walketh upon the waves of the sea.

** Job 9:9

Who maketh Arcturus, and Orion, and Hyades, and the inner parts of the south.

** Job 9:10

Who doth things great and incomprehensible, and wonderful, of which there is no number.

** Job 9:11

If he come to me, I shall not see him: if he depart, I shall not understand.

** Job 9:12

If he examine on a sudden, who shall answer him? or who can say: Why dost thou so?

** Job 9:13

God, whose wrath no man can resist, and under whom they stoop that bear up the world.

** Job 9:14

What am I then, that I should answer him, and have words with him?

** Job 9:15

I, who although I should have any just thing, would not answer, but would make supplication to my judge.

** Job 9:16

And if he should hear me when I call, I should not believe that he had heard my voice.

** Job 9:17

For he shall crush me in a whirlwind, and multiply my wounds even without cause.

** Job 9:18

He alloweth not my spirit to rest, and he filleth me with bitterness.

** Job 9:19

If strength be demanded, he is most strong: if equity of judgment, no man dare bear witness for me.

** Job 9:20

If I would justify myself, my own mouth shall condemn me: if I would shew myself innocent, he shall prove me wicked.

** Job 9:21

Although I should be simple, even this my soul shall be ignorant of, and I shall be weary of my life.

** Job 9:22

One thing there is that I have spoken, both the innocent and the wicked he consumeth.

** Job 9:23

If he scourge, let him kill at once, and not laugh at the pains of the innocent.

** Job 9:24

The earth is given into the hand of the wicked, he covereth the face of the judges thereof: and if it be not he, who is it then?

** Job 9:25

My days have been swifter than a post: they have fled away and have not seen good.

** Job 9:26

They have passed by as ships carrying fruits, as an eagle flying to the prey.

** Job 9:27

If I say: I will not speak so: I change my face, and am tormented with sorrow.

** Job 9:28

I feared all my works, knowing that thou didst not spare the offender.

** Job 9:29

But if so also I am wicked, why have I laboured in vain?

** Job 9:30

If I be washed, as it were, with snow waters, and my hands shall shine ever so clean:

** Job 9:31

Yet thou shalt plunge me in filth, and my garments shall abhor me.

** Job 9:32

For I shall not answer a man that is like myself: nor one that may be heard with me equally in judgment.

** Job 9:33

There is none that may be able to reprove both, and to put his hand between both.

** Job 9:34

Let him take his rod away from me, and let not his fear terrify me.

** Job 9:35

I will speak, and will not fear him: for I cannot answer while I am in fear. 

* Job 10

** Job 10:1

My soul is weary of my life, I will let go my speech against myself, I will speak in the bitterness of my soul.

** Job 10:2

I will say to God: Do not condemn me: tell me why thou judgest me so?

** Job 10:3

Doth it seem good to thee that thou shouldst calumniate me, and oppress me, the work of thy own hands, and help the counsel of the wicked?

** Job 10:4

Hast thou eyes of flesh: or, shalt thou see as man seeth?

** Job 10:5

Are thy days as the days of man, and are thy years as the times of men:

** Job 10:6

That thou shouldst inquire after my iniquity, and search after my sin?

** Job 10:7

And shouldst know that I have done no wicked thing, whereas there is no man that can deliver out of thy hand?

** Job 10:8

Thy hands have made me, and fashioned me wholly round about, and dost thou thus cast me down headlong on a sudden?

** Job 10:9

Remember, I beseech thee, that thou hast made me as the clay, and thou wilt bring me into dust

** Job 10:10

Hast thou not milked me as milk, and curdled me like cheese?

** Job 10:11

Thou hast clothed me with skin and flesh: thou hast put me together with bones and sinews:

** Job 10:12

Thou hast granted me life and mercy, and thy visitation hath preserved my spirit.

** Job 10:13

Although thou conceal these things in thy heart, yet I know that thou rememberest all things.

** Job 10:14

If I have sinned, and thou hast spared me for an hour: why dost thou not suffer me to be clean from my iniquity?

** Job 10:15

And if I be wicked, woe unto me: and if just, I shall not lift up my head, being filled with affliction and misery.

** Job 10:16

And for pride thou wilt take me as a lioness, and returning, thou tormentest me wonderfully.

** Job 10:17

Thou renewest thy witnesses against me, and multipliest thy wrath upon me, and pains war against me.

** Job 10:18

Why didst thou bring me forth out of the womb? O that I had been consumed, that eye might not see me!

** Job 10:19

I should have been as if I had not been, carried from the womb to the grave.

** Job 10:20

Shall not the fewness of my days be ended shortly? Suffer me, therefore, that I may lament my sorrow a little:

** Job 10:21

Before I go and return no more, to a land that is dark and covered with the mist of death:

** Job 10:22

A land of misery and darkness, where the shadow of death, and no order, but everlasting horror dwelleth. 

* Job 11

** Job 11:1

Then Sophar the Naamathite answered, and said:

** Job 11:2

Shall not he that speaketh much, hear also? or shall a man full of talk be justified?

** Job 11:3

Shall men hold their peace to thee only? and when thou hast mocked others, shall no man confute thee?

** Job 11:4

For thou hast said: My word is pure, and I am clean in thy sight.

** Job 11:5

And I wish that God would speak with thee, and would open his lips to thee,

** Job 11:6

That he might shew thee the secrets of wisdom, and that his law is manifold, and thou mightest understand that he exacteth much less of thee, than thy iniquity deserveth.

** Job 11:7

Peradventure thou wilt comprehend the steps of God, and wilt find out the Almighty perfectly?

** Job 11:8

He is higher than heaven, and what wilt thou do? he is deeper than hell, and how wilt thou know?

** Job 11:9

The measure of him is longer than the earth, and broader than the sea.

** Job 11:10

If he shall overturn all things, or shall press them together, who shall contradict him?

** Job 11:11

For he knoweth the vanity of men, and when he seeth iniquity, doth he not consider it?

** Job 11:12

A vain man is lifted up into pride, and thinketh himself born free like a wild ass's colt.

** Job 11:13

But thou hast hardened thy heart, and hast spread thy hands to him.

** Job 11:14

If thou wilt put away from thee the iniquity that is in thy hand, and let not injustice remain in thy tabernacle:

** Job 11:15

Then mayst thou lift up thy face without spot, and thou shalt be steadfast, and shalt not fear.

** Job 11:16

Thou shalt also forget misery, and remember it only as waters that are passed away.

** Job 11:17

And brightness like that of the noonday, shall arise to thee at evening: and when thou shalt think thyself consumed, thou shalt rise as the day star.

** Job 11:18

And thou shalt have confidence, hope being set before thee, and being buried thou shalt sleep secure.

** Job 11:19

Thou shalt rest, and there shall be none to make thee afraid: and many shall entreat thy face.

** Job 11:20

But the eyes of the wicked shall decay, and the way to escape shall fail them, and their hope the abomination of the soul. 

* Job 12

** Job 12:1

Then Job answered, and said:

** Job 12:2

Are you then men alone, and shall wisdom die with you?

** Job 12:3

I also have a heart as well as you: for who is ignorant of these things, which you know?

** Job 12:4

He that is mocked by his friends as I, shall call upon God and he will hear him: for the simplicity of the just man is laughed to scorn.

** Job 12:5

The lamp despised in the thoughts of the rich, is ready for the time appointed.

** Job 12:6

The tabernacles of robbers abound, and they provoke God boldly; whereas it is he that hath given all into their hands:

** Job 12:7

But ask now the beasts, and they shall teach thee: and the birds of the air, and they shall tell thee.

** Job 12:8

Speak to the earth, and it shall answer thee: and the fishes of the sea shall tell.

** Job 12:9

Who is ignorant that the hand of the Lord hath made all these things?

** Job 12:10

In whose hand is the soul of every living thing, and the spirit of all flesh of man.

** Job 12:11

Doth not the ear discern words, and the palate of him that eateth, the taste?

** Job 12:12

In the ancient is wisdom, and in length of days prudence.

** Job 12:13

With him is wisdom and strength, he hath counsel and understanding.

** Job 12:14

If he pull down, there is no man that can build up: if he shut up a man, there is none that can open.

** Job 12:15

If he withhold the waters, all things shall be dried up: and if he send them out, they shall overturn the earth.

** Job 12:16

With him is strength and wisdom: he knoweth both the deceivers, and him that is deceived.

** Job 12:17

He bringeth counsellors to a foolish end, and judges to insensibility.

** Job 12:18

He looseth the belt of kings, and girdeth their loins with a cord.

** Job 12:19

He leadeth away priests without glory, and overthroweth nobles.

** Job 12:20

He changeth the speech of the true speakers, and taketh away the doctrine of the aged.

** Job 12:21

He poureth contempt upon princes, and relieveth them that were oppressed.

** Job 12:22

He discovereth deep things out of darkness, and bringeth up to light the shadow of death.

** Job 12:23

He multiplieth nations, and destroyeth them, and restoreth them again after they were overthrown.

** Job 12:24

He changeth the heart of the princes of the people of the earth, and deceiveth them that they walk in vain where there is no way.

** Job 12:25

They shall grope as in the dark, and not in the light, and he shall make them stagger like men that are drunk. 

* Job 13

** Job 13:1

Behold my eye hath seen all these things, and my ear hath heard them, and I have understood them all.

** Job 13:2

According to your knowledge I also know: neither am I inferior to you.

** Job 13:3

But yet I will speak to the Almighty, and I desire to reason with God.

** Job 13:4

Having first shewn that you are forgers of lies, and maintainers of perverse opinions.

** Job 13:5

And I wish you would hold your peace, that you might be thought to be wise men.

** Job 13:6

Hear ye therefore my reproof, and attend to the judgment of my lips.

** Job 13:7

Hath God any need of your lie, that you should speak deceitfully for him?

** Job 13:8

Do you accept this person, and do you endeavour to judge for God?

** Job 13:9

Or shall it please him, from whom nothing can be concealed? or shall he be deceived as a man, with your deceitful dealings?

** Job 13:10

He shall reprove you, because in secret you accept his person.

** Job 13:11

As soon as he shall move himself, he shall trouble you: and his dread shall fall upon you.

** Job 13:12

Your remembrance shall be compared to ashes, and your necks shall be brought to clay.

** Job 13:13

Hold your peace a little while, that I may speak whatsoever my mind shall suggest to me.

** Job 13:14

Why do I tear my flesh with my teeth, and carry my soul in my hands?

** Job 13:15

Although he should kill me, I will trust in him: but yet I will reprove my ways in his sight.

** Job 13:16

And he shall be my saviour: for no hypocrite shall come before his presence.

** Job 13:17

Hear ye my speech, and receive with your ears hidden truths.

** Job 13:18

If I shall be judged, I know that I shall be found just.

** Job 13:19

Who is he that will plead against me? let him come: why am I consumed holding my peace?

** Job 13:20

Two things only do not to me, and then from thy face I shall not be hid:

** Job 13:21

Withdraw thy hand far from me, and let not thy dread terrify me.

** Job 13:22

Call me, and I will answer thee: or else I will speak, and do thou answer me.

** Job 13:23

How many are my iniquities and sins? make me know my crimes and offenses.

** Job 13:24

Why hidest thou thy face, and thinkest me thy enemy?

** Job 13:25

Against a leaf, that is carried away with the wind, thou shewest thy power, and thou pursuest a dry straw.

** Job 13:26

For thou writest bitter things against me, and wilt consume me for the sins of my youth.

** Job 13:27

Thou hast put my feet in the stocks, and hast observed all my paths, and hast considered the steps of my feet:

** Job 13:28

Who am to be consumed as rottenness, and as a garment that is motheaten. 

* Job 14

** Job 14:1

Man born of a woman, living for a short time, is filled with many miseries.

** Job 14:2

Who cometh forth like a flower, and is destroyed, and fleeth as a shadow, and never continueth in the same state.

** Job 14:3

And dost thou think it meet to open thy eyes upon such an one, and to bring him into judgment with thee?

** Job 14:4

Who can make him clean that is conceived of unclean seed? is it not thou who only art?

** Job 14:5

The days of man are short, and the number of his months is with thee: thou hast appointed his bounds which cannot be passed.

** Job 14:6

Depart a little from him, that he may rest until his wished for day come, as that of the hireling.

** Job 14:7

A tree hath hope: if it be cut, it growth green again, and the boughs thereof sprout.

** Job 14:8

If its roots be old in the earth, and its stock be dead in the dust:

** Job 14:9

At the scent of water, it shall spring, and bring forth leaves, as when it was first planted.

** Job 14:10

But man when he shall be dead, and stripped and consumed, I pray you where is he?

** Job 14:11

As if the waters should depart out of the sea, and an emptied river should be dried up;

** Job 14:12

So man when he is fallen asleep shall not rise again; till the heavens be broken, he shall not awake, nor rise up out of his sleep.

** Job 14:13

Who will grant me this, that thou mayst protect me in hell, and hide me till thy wrath pass, and appoint me a time when thou wilt remember me?

** Job 14:14

Shall man that is dead, thinkest thou, live again? all the days in which I am now in warfare, I expect until my change come.

** Job 14:15

Thou shalt call me, and I will answer thee: to the work of thy hands thou shalt reach out thy right hand.

** Job 14:16

Thou indeed hast numbered my steps, but spare my sins.

** Job 14:17

Thou hast sealed up my offences as it were in a bag, but hast cured my iniquity.

** Job 14:18

A mountain falling cometh to nought, and a rock is removed out of its place.

** Job 14:19

Waters wear away the stones, and with inundation the ground by little and little is washed away: so in like manner thou shalt destroy man.

** Job 14:20

Thou hast strengthened him for a little while, that he may pass away for ever: thou shalt change his face, and shalt send him away.

** Job 14:21

Whether his children come to honour or dishonour, he shall not understand.

** Job 14:22

But yet his flesh, while he shall live, shall have pain, and his soul shall mourn over him. 

* Job 15

** Job 15:1

And Eliphaz the Themanite, answered, and said:

** Job 15:2

Will a wise man answer as if he were speaking in the wind, and fill his stomach with burning heat?

** Job 15:3

Thou reprovest him by words, who is not equal to thee, and thou speakest that which is not good for thee.

** Job 15:4

As much as is in thee, thou hast made void fear, and hast taken away prayers from before God.

** Job 15:5

For thy iniquity hath taught thy mouth, and thou imitatest the tongue of blasphemers.

** Job 15:6

Thy own mouth shall condemn thee, and not I: and thy own lips shall answer thee.

** Job 15:7

Art thou the first man that was born, or wast thou made before the hills?

** Job 15:8

Hast thou heard God's counsel, and shall his wisdom be inferior to thee?

** Job 15:9

What knowest thou that we are ignorant of? what dost thou understand that we know not?

** Job 15:10

There are with us also aged and ancient men, much elder than thy fathers.

** Job 15:11

Is it a great matter that God should comfort thee? but thy wicked words hinder this.

** Job 15:12

Why doth thy heart elevate thee, and why dost thou stare with thy eyes, as if they were thinking great things?

** Job 15:13

Why doth thy spirit swell against God, to utter such words out of thy mouth?

** Job 15:14

What is man that he should be without spot, and he that is born of a woman that he should appear just?

** Job 15:15

Behold among his saints none is unchangeable, and the heavens are not pure in his sight.

** Job 15:16

How much more is man abominable, and unprofitable, who drinketh iniquity like water?

** Job 15:17

I will shew thee, hear me: and I will tell thee what I have seen.

** Job 15:18

Wise men confess and hide not their fathers.

** Job 15:19

To whom alone the earth was given, and no stranger hath passed among them.

** Job 15:20

The wicked man is proud all his days, and the number of the years of his tyranny is uncertain.

** Job 15:21

The sound of dread is always in his ears: and when there is peace, he always suspecteth treason.

** Job 15:22

He believeth not that he may return from darkness to light, looking round about for the sword on every side.

** Job 15:23

When he moveth himself to seek bread, he knoweth that the day of darkness is ready at his hand.

** Job 15:24

Tribulation shall terrify him, and distress shall surround him, as a king that is prepared for the battle.

** Job 15:25

For he hath stretched out his hand against God, and hath strengthened himself against the Almighty.

** Job 15:26

He hath run against him with his neck raised up, and is armed with a fat neck.

** Job 15:27

Fatness hath covered his face, and the fat hangeth down on his sides.

** Job 15:28

He hath dwelt in desolate cities, and in desert houses that are reduced into heaps.

** Job 15:29

He shall not be enriched, neither shall his substance continue, neither shall he push his root in the earth.

** Job 15:30

He shall not depart out of darkness: the flame shall dry up his branches, and he shall be taken away by the breath of his own mouth.

** Job 15:31

He shall not believe, being vainly deceived by error, that he may be redeemed with any price.

** Job 15:32

Before his days be full he shall perish: and his hands shall wither away.

** Job 15:33

He shall be blasted as a vine when its grapes are in the first flower, and as an olive tree that casteth its flower.

** Job 15:34

For the congregation of the hypocrite is barren, and fire shall devour their tabernacles, who love to take bribes.

** Job 15:35

He hath conceived sorrow, and hath brought forth iniquity, and his womb prepareth deceits. 

* Job 16

** Job 16:1

Then Job answered, and said:

** Job 16:2

I have often heard such things as these: you are all troublesome comforters.

** Job 16:3

Shall windy words have no end? or is it any trouble to thee to speak?

** Job 16:4

I also could speak like you: and would God your soul were for my soul.

** Job 16:5

I would comfort you also with words, and would wag my head over you.

** Job 16:6

I would strengthen you with my mouth, and would move my lips, as sparing you.

** Job 16:7

But what shall I do? If I speak, my pain will not rest: and if I hold my peace, it will not depart from me.

** Job 16:8

But now my sorrow hath oppressed me, and all my limbs are brought to nothing.

** Job 16:9

My wrinkles bear witness against me, and a false speaker riseth up against my face, contradicting me.

** Job 16:10

He hath gathered together his fury against me, and threatening me he hath gnashed with his teeth upon me: my enemy hath beheld me with terrible eyes.

** Job 16:11

They have opened their mouths upon me, and reproaching me they have struck me on the cheek, they are filled with my pains.

** Job 16:12

God hath shut me up with the unjust man, and hath delivered me into the hands of the wicked.

** Job 16:13

I that was formerly so wealthy, am all on a sudden broken to pieces: he hath taken me by my neck, he hath broken me, and hath set me up to be his mark.

** Job 16:14

He hath compassed me round about with his lances, he hath wounded my loins, he hath not spared, and hath poured out my bowels on the earth,

** Job 16:15

He hath torn me with wound upon wound, he hath rushed in upon me like a giant.

** Job 16:16

I have sowed sackcloth upon my skin, and have covered my flesh with ashes.

** Job 16:17

My face is swollen with weeping, and my eyelids are dim.

** Job 16:18

These things have I suffered without the iniquity of my hand, when I offered pure prayers to God.

** Job 16:19

O earth, cover not thou my blood, neither let my cry find a hiding place in thee.

** Job 16:20

For behold my witness is in heaven, and he that knoweth my conscience is on high.

** Job 16:21

My friends are full of words: my eye poureth out tears to God.

** Job 16:22

And O that a man might so be judged with God, as the son of man is judged with his companion!

** Job 16:23

For behold short years pass away, and I am walking in a path by which I shall not return. 

* Job 17

** Job 17:1

My spirit shall be wasted, my days shall be shortened and only the grave remaineth for me.

** Job 17:2

I have not sinned, and my eye abideth in bitterness.

** Job 17:3

Deliver me, O Lord, and set me beside thee, and let any man's hand fight against me.

** Job 17:4

Thou hast set their heart far from understanding, therefore they shall not be exalted.

** Job 17:5

He promiseth a prey to his companions, and the eyes of his children shall fail.

** Job 17:6

He hath made me as it were a byword of the people, and I am an example before them.

** Job 17:7

My eye is dim through indignation, and my limbs are brought as it were to nothing.

** Job 17:8

The just shall be astonished at this, and the innocent shall be raised up against the hypocrite.

** Job 17:9

And the just man shall hold on his way, and he that hath clean hands shall be stronger and stronger.

** Job 17:10

Wherefore be you all converted, and come, and I shall not find among you any wise man.

** Job 17:11

My days have passed away, my thoughts are dissipated, tormenting my heart.

** Job 17:12

They have turned night into day, and after darkness I hope for light again.

** Job 17:13

If I wait hell is my house, and I have made my bed in darkness.

** Job 17:14

I have said to rottenness: Thou art my father; to worms, my mother and my sister.

** Job 17:15

Where is now then my expectation, and who considereth my patience?

** Job 17:16

All that I have shall go down into the deepest pit: thinkest thou that there at least I shall have rest? 

* Job 18

** Job 18:1

Then Baldad the Suhite answered, and said:

** Job 18:2

How long will you throw out words? understand first, and so let us speak.

** Job 18:3

Why are we reputed as beasts, and counted vile before you?

** Job 18:4

Thou that destroyest thy soul in thy fury, shall the earth be forsaken for thee, and shall rocks be removed out of their place?

** Job 18:5

Shall not the light of the wicked be extinguished, and the flame of his fire not shine?

** Job 18:6

The light shall be dark in his tabernacle, and the lamp that is over him, shall be put out.

** Job 18:7

The step of his strength shall be straitened, and his own counsel shall cast him down headlong.

** Job 18:8

For he hath thrust his feet into a net, and walketh in its meshes.

** Job 18:9

The sole of his foot shall be held in a snare, and thirst shall burn against him.

** Job 18:10

A gin is hidden for him in the earth, and his trap upon the path.

** Job 18:11

Fears shall terrify him on every side, and shall entangle his feet.

** Job 18:12

Let his strength be wasted with famine, and let hunger invade his ribs.

** Job 18:13

Let it devour the beauty of his skin, let the firstborn death consume his arms.

** Job 18:14

Let his confidence be rooted out of his tabernacle, and let destruction tread upon him like a king.

** Job 18:15

Let the companions of him that is not, dwell in his tabernacle, let brimstone be sprinkled in his tent.

** Job 18:16

Let his roots be dried up beneath, and his harvest destroyed above.

** Job 18:17

Let the memory of him perish from the earth, and let not his name be renowned in the streets.

** Job 18:18

He shall drive him out of light into darkness, and shall remove him out of the world.

** Job 18:19

His seed shall not subsist, nor his offspring among his people, nor any remnants in his country.

** Job 18:20

They that come after him shall be astonished at his day, and horror shall fall upon them that went before.

** Job 18:21

These then are the tabernacles of the wicked, and this the place of him that knoweth not God. 

* Job 19

** Job 19:1

Then Job answered, and said:

** Job 19:2

How long do you afflict my soul, and break me in pieces with words?

** Job 19:3

Behold, these ten times you confound me, and are not ashamed to oppress me.

** Job 19:4

For if I have been ignorant, my ignorance shall be with me.

** Job 19:5

But you set yourselves up against me, and reprove me with my reproaches.

** Job 19:6

At least now understand, that God hath not afflicted me with an equal judgment, and compassed me with his scourges.

** Job 19:7

Behold I shall cry suffering violence, and no one will hear: I shall cry aloud, and there is none to judge.

** Job 19:8

He hath hedged in my path round about, and I cannot pass, and in my way he hath set darkness.

** Job 19:9

He hath stripped me of my glory, and hath taken the crown from my head.

** Job 19:10

He hath destroyed me on every side, and I am lost, and he hath taken away my hope, as from a tree that is plucked up.

** Job 19:11

His wrath is kindled against me, and he hath counted me as his enemy.

** Job 19:12

His troops have come together, and have made themselves a way by me, and have besieged my tabernacle round about.

** Job 19:13

He hath put my brethren far from me, and my acquaintance like strangers have departed from me.

** Job 19:14

My kinsmen have forsaken me, and they that knew me, have forgotten me.

** Job 19:15

They that dwell in my house, and my maidservants have counted me as a stranger, and I have been like an alien in their eyes.

** Job 19:16

I called my servant, and he gave me no answer, I entreated him with my own mouth.

** Job 19:17

My wife hath abhorred my breath, and I entreated the children of my womb.

** Job 19:18

Even fools despised me, and when I was gone from them, they spoke against me.

** Job 19:19

They that were sometime my counsellors, have abhorred me: and he whom I loved most is turned against me.

** Job 19:20

The flesh being consumed, my bone hath cleaved to my skin, and nothing but lips are left about my teeth.

** Job 19:21

Have pity on me, have pity on me, at least you my friends, because the hand of the Lord hath touched me.

** Job 19:22

Why do you persecute me as God, and glut yourselves with my flesh?

** Job 19:23

Who will grant me that my words may be written? who will grant me that they may be marked down in a book?

** Job 19:24

With an iron pen and in a plate of lead, or else be graven with an instrument in flint stone?

** Job 19:25

For I know that my Redeemer liveth, and in the last day I shall rise out of the earth.

** Job 19:26

And I shall be clothed again with my skin, and in my flesh I shall see my God.

** Job 19:27

Whom I myself shall see, and my eyes shall behold, and not another: this my hope is laid up in my bosom.

** Job 19:28

Why then do you say now: Let us persecute him, and let us find occasion of word against him?

** Job 19:29

Flee then from the face of the sword, for the sword is the revenger of iniquities: and know ye that there is a judgment. 

* Job 20

** Job 20:1

Then Sophar the Naamathite answered, and said:

** Job 20:2

Therefore various thoughts succeed one another in me, and my mind is hurried away to different things.

** Job 20:3

The doctrine with which thou reprovest me, I will hear, and the spirit of my understanding shall answer for me.

** Job 20:4

This I know from the beginning, since man was placed upon the earth,

** Job 20:5

That the praise of the wicked is short, and the joy of the hypocrite but for a moment.

** Job 20:6

If his pride mount up even to heaven, and his head touch the clouds:

** Job 20:7

In the end he shall be destroyed like a dunghill, and they that had seen him, shall say: Where is he?

** Job 20:8

As a dream that fleeth away he shall not be found, he shall pass as a vision of the night:

** Job 20:9

The eyes that had seen him, shall see him no more, neither shall his place any more behold him.

** Job 20:10

His children shall be oppressed with want, and his hands shall render to him his sorrow.

** Job 20:11

His bones shall be filled with the vices of his youth, and they shall sleep with him in the dust.

** Job 20:12

For when evil shall be sweet in his mouth, he will hide it under his tongue.

** Job 20:13

He will spare it, and not leave it, and will hide it in his throat.

** Job 20:14

His bread in his belly shall be turned into the gall of asps within him,

** Job 20:15

The riches which he hath swallowed, he shall vomit up, and God shall draw them out of his belly.

** Job 20:16

He shall suck the head of asps, and the viper's tongue shall kill him.

** Job 20:17

Let him not see the streams of the river, the brooks of honey and of butter.

** Job 20:18

He shall be punished for all that he did, and yet shall not be consumed: according to the multitude of his devices so also shall he suffer.

** Job 20:19

Because he broke in and stripped the poor: he hath violently taken away a house which he did not build.

** Job 20:20

And yet his belly was not filled: and when he hath the things he coveted, he shall not be able to possess them.

** Job 20:21

There was nothing left of his meat, and therefore nothing shall continue of his goods:

** Job 20:22

When he shall be filled, he shall be straitened, he shall burn, and every sorrow shall fall upon him.

** Job 20:23

May his belly be filled, that God may send forth the wrath of his indignation upon him, and rain down his war upon him.

** Job 20:24

He shall flee from weapons of iron, and shall fall upon a bow of brass.

** Job 20:25

The sword is drawn out, and cometh forth from its scabbard, and glittereth in his bitterness: the terrible ones shall go and come upon him.

** Job 20:26

All darkness is hid in his secret places: a fire that is not kindled shall devour him, he shall be afflicted when left in his tabernacle.

** Job 20:27

The heavens shall reveal his iniquity, and the earth shall rise up against him.

** Job 20:28

The offspring of his house shall be exposed, he shall be pulled down in the day of God's wrath.

** Job 20:29

This is the portion of a wicked man from God, and the inheritance of his doings from the Lord. 

* Job 21

** Job 21:1

Then Job answered, and said:

** Job 21:2

Hear, I beseech you, my words, and do penance.

** Job 21:3

Suffer me, and I will speak, and after, if you please, laugh at my words.

** Job 21:4

Is my debate against man, that I should not have just reason to be troubled?

** Job 21:5

Hearken to me and be astonished, and lay your finger on your mouth.

** Job 21:6

As for me, when I remember, I am afraid, and trembling taketh hold on my flesh.

** Job 21:7

Why then do the wicked live, are they advanced, and strengthened with riches?

** Job 21:8

Their seed continueth before them, a multitude of kinsmen, and of children's children in their sight.

** Job 21:9

Their houses are secure and peaceable, and the rod of God is not upon them.

** Job 21:10

Their cattle have conceived, and failed not: their cow has calved, and is not deprived of her fruit.

** Job 21:11

Their little ones go out like a flock, and their children dance and play.

** Job 21:12

They take the timbrel, and the harp, and rejoice at the sound of the organ.

** Job 21:13

They spend their days in wealth, and in a moment they go down to hell.

** Job 21:14

Who have said to God: Depart from us, we desire not the knowledge of thy ways.

** Job 21:15

Who is the Almighty, that we should serve him? and what doth it profit us if we pray to him?

** Job 21:16

Yet because their good things are not in their hand, may the counsel of the wicked be far from me.

** Job 21:17

How often shall the lamp of the wicked be put out, and a deluge come upon them, and he shall distribute the sorrows of his wrath?

** Job 21:18

They shall be as chaff before the face of the wind, and as ashes which the whirlwind scattereth.

** Job 21:19

God shall lay up the sorrow of the father for his children: and when he shall repay, then shall he know.

** Job 21:20

His eyes shall see his own destruction, and he shall drink of the wrath of the Almighty.

** Job 21:21

For what is it to him what befalleth his house after him: and if the number of his months be diminished by one half?

** Job 21:22

Shall any one teach God knowledge, who judgeth those that are high?

** Job 21:23

One man dieth strong, and hale, rich and happy.

** Job 21:24

His bowels are full of fat, and his bones are moistened with marrow.

** Job 21:25

But another dieth in bitterness of soul without any riches:

** Job 21:26

And yet they shall sleep together in the dust, and worms shall cover them.

** Job 21:27

Surely I know your thoughts, and your unjust judgments against me.

** Job 21:28

For you say: Where is the house of the prince? and where are the dwelling places of the wicked?

** Job 21:29

Ask any one of them that go by the way, and you shall perceive that he knoweth these same things.

** Job 21:30

Because the wicked man is reserved to the day of destruction, and he shall be brought to the day of wrath.

** Job 21:31

Who shall reprove his way to his face? and who shall repay him what he hath done?

** Job 21:32

He shall be brought to the graves, and shall watch in the heap of the dead.

** Job 21:33

He hath been acceptable to the gravel of Cocytus, and he shall draw every man after him, and there are innumerable before him.

** Job 21:34

How then do ye comfort me in vain, whereas your answer is shewn to be repugnant to truth? 

* Job 22

** Job 22:1

Then Eliphaz the Themanite answered, and said:

** Job 22:2

Can man be compared with God, even though he were of perfect knowledge?

** Job 22:3

What doth it profit God if thou be just? or what dost thou give him if thy way be unspotted?

** Job 22:4

Shall he reprove thee for fear, and come with thee into judgment:

** Job 22:5

And not for thy manifold wickedness and thy infinite iniquities?

** Job 22:6

For thou hast taken away the pledge of thy brethren without cause, and stripped them naked of their clothing.

** Job 22:7

Thou hast not given water to the weary, thou hast withdrawn bread from the hungry.

** Job 22:8

In the strength of thy arm thou didst possess the land, and being the most mighty thou holdest it.

** Job 22:9

Thou hast sent widows away empty, and the arms of the fatherless thou hast broken in pieces.

** Job 22:10

Therefore art thou surrounded with snares, and sudden fear troubleth thee.

** Job 22:11

And didst thou think that thou shouldst not see darkness, and that thou shouldst not be covered with the violence of overflowing waters?

** Job 22:12

Dost not thou think that God is higher than heaven, and is elevated above the height of the stars?

** Job 22:13

And thou sayst: What doth God know? and he judgeth as it were through a mist.

** Job 22:14

The clouds are his covert, and he doth not consider our things, and he walketh about the poles of heaven.

** Job 22:15

Dost thou desire to keep the path of ages, which wicked men have spurned?

** Job 22:16

Who were taken away before their time, and a flood hath overthrown their foundation.

** Job 22:17

Who said to God: Depart from us: and looked upon the Almighty as if he could do nothing:

** Job 22:18

Whereas he had filled their houses with good things: whose way of thinking be far from me.

** Job 22:19

The just shall see, and shall rejoice, and the innocent shall laugh them to scorn.

** Job 22:20

Is not their exaltation cut down, and hath not fire devoured the remnants of them?

** Job 22:21

Submit thyself then to him, and be at peace: and thereby thou shalt have the best fruits.

** Job 22:22

Receive the law of his mouth, and lay up his words in thy heart.

** Job 22:23

If thou wilt return to the Almighty, thou shalt be built up, and shalt put away iniquity far from thy tabernacle.

** Job 22:24

He shall give for earth flint, and for flint torrents of gold.

** Job 22:25

And the Almighty shall be against thy enemies, and silver shall be heaped together for thee.

** Job 22:26

Then shalt thou abound in delights in the Almighty, and shalt lift up thy face to God.

** Job 22:27

Thou shalt pray to him, and he will hear thee, and thou shalt pay vows.

** Job 22:28

Thou shalt decree a thing, and it shall come to thee, and light shall shine in thy ways.

** Job 22:29

For he that hath been humbled, shall be in glory: and he that shall bow down his eyes, he shall be saved.

** Job 22:30

The innocent shall be saved, and he shall be saved by the cleanness of his hands. 

* Job 23

** Job 23:1

Then Job answered, and said:

** Job 23:2

Now also my words are in bitterness, and the hand of my scourge is more grievous than my mourning.

** Job 23:3

Who will grant me that I might know and find him, and come even to his throne?

** Job 23:4

I would set judgment before him, and would fill my mouth with complaints.

** Job 23:5

That I might know the words that he would answer me, and understand what he would say to me.

** Job 23:6

I would not that he should contend with me with much strength, nor overwhelm me with the weight of his greatness.

** Job 23:7

Let him propose equity against me, and let my judgment come to victory.

** Job 23:8

But if I go to the east, he appeareth not; if to the west, I shall not understand him.

** Job 23:9

If to the left hand, what shall I do? I shall not take hold on him: if I turn myself to the right hand, I shall not see him.

** Job 23:10

But he knoweth my way, and has tried me as gold that passeth through the fire:

** Job 23:11

My foot hath followed his steps, I have kept his way, and have not declined from it.

** Job 23:12

I have not departed from the commandments of his lips, and the words of his mouth I have hid in my bosom.

** Job 23:13

For he is alone, and no man can turn away his thought: and whatsoever his soul hath desired, that hath he done.

** Job 23:14

And when he shall have fulfilled his will in me, many other like things are also at hand with him.

** Job 23:15

And therefore I am troubled at his presence, and when I consider him, I am made pensive with fear.

** Job 23:16

God hath softened my heart, and the Almighty hath troubled me.

** Job 23:17

For I have not perished because of the darkness that hangs over me, neither hath the mist covered my face. 

* Job 24

** Job 24:1

Times are not hid from the Almighty: but they that know him, know not his days.

** Job 24:2

Some have removed landmarks, have taken away flocks by force, and fed them.

** Job 24:3

They have driven away the ass of the fatherless, and have taken away the widow's ox for a pledge.

** Job 24:4

They have overturned the way of the poor, and have oppressed together the meek of the earth.

** Job 24:5

Others like wild asses in the desert go forth to their work: by watching for a prey they get bread for their children.

** Job 24:6

They reap the field that is not their own, and gather the vintage of his vineyard whom by violence they have oppressed.

** Job 24:7

They send men away naked, taking away their clothes who have no covering in the cold:

** Job 24:8

Who are wet, with the showers of the mountains, and having no covering embrace the stones.

** Job 24:9

They have violently robbed the fatherless, and stripped the poor common people.

** Job 24:10

From the naked and them that go without clothing, and from the hungry they have taken away the ears of corn.

** Job 24:11

They have taken their rest at noon among the stores of them, who after having trodden the winepresses suffer thirst.

** Job 24:12

Out of the cities they have made men to groan, and the soul of the wounded hath cried out, and God doth not suffer it to pass unrevenged.

** Job 24:13

They have been rebellious to the light, they have not known his ways, neither have they returned by his paths.

** Job 24:14

The murderer riseth at the very break of day, he killeth the needy, and the poor man: but in the night he will be as a thief.

** Job 24:15

The eye of the adulterer observeth darkness, saying: No eye shall see me: and he will cover his face.

** Job 24:16

He diggeth through houses in the dark, as in the day they had appointed for themselves, and they have not known the light.

** Job 24:17

If the morning suddenly appear, it is to them the shadow of death: and they walk in darkness as if it were in light.

** Job 24:18

He is light upon the face of the water: cursed be his portion on the earth, let him not walk by the way of the vineyards.

** Job 24:19

Let him pass from the snow waters to excessive heat, and his sin even to hell.

** Job 24:20

Let mercy forget him: may worms be his sweetness: let him be remembered no more, but be broken in pieces as an unfruitful tree.

** Job 24:21

For he hath fed the barren that beareth not, and to the widow he hath done no good.

** Job 24:22

He hath pulled down the strong by his might: and when he standeth up, he shall not trust to his life.

** Job 24:23

God hath given him place for penance, and he abuseth it unto pride: but his eyes are upon his ways.

** Job 24:24

They are lifted up for a little while and shall not stand, and shall be brought down as all things, and shall be taken away, and as the tops of the ears of corn they shall be broken.

** Job 24:25

And if it be not so, who can convince me that I have lied, and set my words before God? 

* Job 25

** Job 25:1

Then Baldad the Suhite answered, and said:

** Job 25:2

Power and terror are with him, who maketh peace in his high places.

** Job 25:3

Is there any numbering of his soldiers? and upon whom shall not his light arise?

** Job 25:4

Can man be justified compared with God, or he that is born of a woman appear clean?

** Job 25:5

Behold even the moon doth not shine, and the stars are not pure in his sight.

** Job 25:6

How much more is man than rottenness and the son of man than a worm? 

* Job 26

** Job 26:1

Then Job answered, and said:

** Job 26:2

Whose helper art thou? is it of him that is weak? and dost thou hold up the arm of him that has no strength?

** Job 26:3

To whom hast thou given counsel? perhaps to him that hath no wisdom, and thou hast shewn thy very great prudence.

** Job 26:4

Whom hast thou desired to teach? was it not him that made life?

** Job 26:5

Behold the giants groan under the waters, and they that dwell with them.

** Job 26:6

Hell is naked before him, and there is no covering for destruction.

** Job 26:7

He stretched out the north over the empty space, and hangeth the earth upon nothing.

** Job 26:8

He bindeth up the waters in his clouds, so that they break not out and fall down together.

** Job 26:9

He withholdeth the face of his throne, and spreadeth his cloud over it.

** Job 26:10

He hath set bounds about the waters, till light and darkness come to an end.

** Job 26:11

The pillars of heaven tremble, and dread at his beck.

** Job 26:12

By his power the seas are suddenly gathered together, and his wisdom has struck the proud one.

** Job 26:13

His spirit hath adorned the heavens, and his obstetric hand brought forth the winding serpent.

** Job 26:14

Lo, these things are said in part of his ways: and seeing we have heard scarce a little drop of his word, who shall be able to behold the thunder of his greatness? 

* Job 27

** Job 27:1

Job also added, taking up his parable, and said:

** Job 27:2

As God liveth, who hath taken away my judgment, and the Almighty, who hath brought my soul to bitterness,

** Job 27:3

As long as breath remaineth in me, and the spirit of God in my nostrils,

** Job 27:4

My lips shall not speak iniquity, neither shall my tongue contrive lying.

** Job 27:5

God forbid that I should judge you to be just: till I die I will not depart from my innocence.

** Job 27:6

My justification, which I have begun to hold, I will not forsake: for my heart doth not reprehend me in all my life.

** Job 27:7

Let my enemy be as the ungodly, and my adversary as the wicked one.

** Job 27:8

For what is the hope of the hypocrite if through covetousness he take by violence, and God deliver not his soul?

** Job 27:9

Will God hear his cry, when distress shall come upon him?

** Job 27:10

Or can he delight himself in the Almighty, and call upon God at all times?

** Job 27:11

I will teach you by the hand of God, what the Almighty hath, and I will not conceal it.

** Job 27:12

Behold you all know it, and why do you speak vain things without cause?

** Job 27:13

This is the portion of a wicked man with God, and the inheritance of the violent, which they shall receive of the Almighty.

** Job 27:14

If his sons be multiplied, they shall be for the sword, and his grandsons shall not be filled with bread.

** Job 27:15

They that shall remain of him, shall be buried in death, and his widows shall not weep.

** Job 27:16

If he shall heap together silver as earth, and prepare raiment as clay,

** Job 27:17

He shall prepare indeed, but the just man shall be clothed with it: and the innocent shall divide the silver.

** Job 27:18

He hath built his house as a moth, and as a keeper he hath made a booth.

** Job 27:19

The rich man when he shall sleep shall take away nothing with him: he shall open his eyes and find nothing.

** Job 27:20

Poverty like water shall take hold on him, a tempest shall oppress him in the night:

** Job 27:21

A burning wind shall take him up, and carry him away, and as a whirlwind shall snatch him from his place.

** Job 27:22

And he shall cast upon him, and shall not spare: out of his hand he would willingly flee.

** Job 27:23

He shall clasp his hands upon him, and shall hiss at him, beholding his place. 

* Job 28

** Job 28:1

Silver hath beginnings of its veins, and gold hath a place wherein it is melted.

** Job 28:2

Iron is taken out of the earth, and stone melted with heat is turned into brass.

** Job 28:3

He hath set a time for darkness, and the end of all things he considereth, the stone also that is in the dark and the shadow of death.

** Job 28:4

The flood divideth from the people that are on their journey, those whom the food of the needy man hath forgotten, and who cannot be come at.

** Job 28:5

The land, out of which bread grew in its place, hath been overturned with fire.

** Job 28:6

The stones of it are the place of sapphires, and the clods of it are gold.

** Job 28:7

The bird hath not known the path, neither hath the eye of the vulture beheld it.

** Job 28:8

The children of the merchants have not trodden it, neither hath the lioness passed by it.

** Job 28:9

He hath stretched forth his hand to the flint, he hath overturned mountains from the roots.

** Job 28:10

In the rocks he hath cut out rivers, and his eye hath seen every precious thing.

** Job 28:11

The depths also of rivers he hath searched, and hidden things he hath brought forth to light.

** Job 28:12

But where is wisdom to be found, and where is the place of understanding?

** Job 28:13

Man knoweth not the price thereof, neither is it found in the land of them that live in delights.

** Job 28:14

The depth saith: It is not in me: and the sea saith: It is not with me.

** Job 28:15

The finest gold shall not purchase it, neither shall silver be weighed in exchange for it.

** Job 28:16

It shall not be compared with the dyed colours of India, or with the most precious stone sardonyx, or the sapphire.

** Job 28:17

Gold or crystal cannot equal it, neither shall any vessels of gold be changed for it.

** Job 28:18

High and eminent things shall not be mentioned in comparison of it: but wisdom is drawn out of secret places.

** Job 28:19

The topaz of Ethiopia shall not be equal to it, neither shall it be compared to the cleanest dyeing.

** Job 28:20

Whence then cometh wisdom? and where is the place of understanding?

** Job 28:21

It is hid from the eyes of all living, and the fowls of the air know it not.

** Job 28:22

Destruction and death have said: With our ears we have heard the fame thereof.

** Job 28:23

God understandeth the way of it, and he knoweth the place thereof.

** Job 28:24

For he beholdeth the ends of the world: and looketh on all things that are under heaven.

** Job 28:25

Who made a weight for the winds, and weighed the waters by measure.

** Job 28:26

When he gave a law for the rain, and a way for the sounding storms.

** Job 28:27

Then he saw it, and declared, and prepared, and searched it.

** Job 28:28

And he said to man: Behold the fear of the Lord, that is wisdom: and to depart from evil, is understanding. 

* Job 29

** Job 29:1

Job also added, taking up his parable, and said:

** Job 29:2

Who will grant me, that I might be according to the months past, according to the days in which God kept me?

** Job 29:3

When his lamp shined over my head, and I walked by his light in darkness?

** Job 29:4

As I was in the days of my youth, when God was secretly in my tabernacle?

** Job 29:5

When the Almighty was with me: and my servants round about me?

** Job 29:6

When I washed my feet with butter, and the rock poured me out rivers of oil?

** Job 29:7

When I went out to the gate of the city, and in the street they prepared me a chair?

** Job 29:8

The young men saw me, and hid themselves: and the old men rose up and stood.

** Job 29:9

The princes ceased to speak, and laid the finger on their mouth.

** Job 29:10

The rulers held their peace, and their tongue cleaved to their throat.

** Job 29:11

The ear that heard me blessed me, and the eye that saw me gave witness to me:

** Job 29:12

Because I had delivered the poor man that cried out; and the fatherless, that had no helper.

** Job 29:13

The blessing of him that was ready to perish came upon me, and I comforted the heart of the widow.

** Job 29:14

I was clad with justice: and I clothed myself with my judgment, as with a robe and a diadem.

** Job 29:15

I was an eye to the blind, and a foot to the lame.

** Job 29:16

I was the father of the poor: and the cause which I knew not, I searched out most diligently.

** Job 29:17

I broke the jaws of the wicked man, and out of his teeth I took away the prey.

** Job 29:18

And I said: I shall die in my nest, and as a palm tree shall multiply my days.

** Job 29:19

My root is opened beside the waters, and dew shall continue in my harvest.

** Job 29:20

My glory shall always be renewed, and my bow in my hand shall be repaired.

** Job 29:21

They that heard me, waited for my sentence, and being attentive held their peace at my counsel.

** Job 29:22

To my words they durst add nothing, and my speech dropped upon them.

** Job 29:23

They waited for me as for rain, and they opened their mouth as for a latter shower.

** Job 29:24

If at any time I laughed on them, they believed not, and the light of my countenance fell not on earth.

** Job 29:25

If I had a mind to go to them, I sat first, and when I sat as a king, with his army standing about him, yet I was a comforter of them that mourned. 

* Job 30

** Job 30:1

But now the younger in time scorn me, whose fathers I would not have set with the dogs of my flock:

** Job 30:2

The strength of whose hands was to me as nothing, and they were thought unworthy of life itself.

** Job 30:3

Barren with want and hunger, who gnawed in the wilderness, disfigured with calamity and misery.

** Job 30:4

And they ate grass, and barks of trees, and the root of junipers was their food.

** Job 30:5

Who snatched up these things out of the valleys, and when they had found any of them, they ran to them with a cry.

** Job 30:6

They dwelt in the desert places of torrents, and in caves of earth, or upon the gravel.

** Job 30:7

They pleased themselves among these kind of things, and counted it delightful to be under the briers.

** Job 30:8

The children of foolish and base men, and not appearing at all upon the earth.

** Job 30:9

Now I am turned into their song, and am become their byword.

** Job 30:10

They abhor me, and flee far from me, and are not afraid to spit in my face.

** Job 30:11

For he hath opened his quiver, and hath afflicted me, and hath put a bridle into my mouth.

** Job 30:12

At the right hand of my rising, my calamities forthwith arose: they have overthrown my feet, and have overwhelmed me with their paths as with waves.

** Job 30:13

They have destroyed my ways, they have lain in wait against me, and they have prevailed, and there was none to help.

** Job 30:14

They have rushed in upon me, as when a wall is broken, and a gate opened, and have rolled themselves down to my miseries.

** Job 30:15

I am brought to nothing: as a wind thou hast taken away my desire: and my prosperity hath passed away like a cloud.

** Job 30:16

And now my soul fadeth within myself, and the days of affliction possess me.

** Job 30:17

In the night my bone is pierced with sorrows: and they that feed upon me, do not sleep.

** Job 30:18

With the multitude of them my garment is consumed, and they have girded me about, as with the collar of my coat.

** Job 30:19

I am compared to dirt, and am likened to embers and ashes.

** Job 30:20

I cry to thee, and thou hearest me not: I stand up, and thou dost not regard me.

** Job 30:21

Thou art changed to be cruel toward me, and in the hardness of thy hand thou art against me.

** Job 30:22

Thou hast lifted me up, and set me as it were upon the wind, and thou hast mightily dashed me.

** Job 30:23

I know that thou wilt deliver me to death, where a house is appointed for every one that liveth.

** Job 30:24

But yet thou stretchest not forth thy hand to their consumption: and if they shall fall down thou wilt save.

** Job 30:25

I wept heretofore for him that was afflicted, and my soul had compassion on the poor.

** Job 30:26

I expected good things, and evils are come upon me: I waited for light, and darkness broke out.

** Job 30:27

My inner parts have boiled without any rest, the days of affliction have prevented me.

** Job 30:28

I went mourning without indignation; I rose up, and cried in the crowd.

** Job 30:29

I was the brother of dragons, and companion of ostriches.

** Job 30:30

My skin is become black upon me, and my bones are dried up with heat.

** Job 30:31

My harp is turned to mourning, and my organ into the voice of those that weep. 

* Job 31

** Job 31:1

I made a covenant with my eyes, that I would not so much as think upon a virgin.

** Job 31:2

For what part should God from above have in me, and what inheritance the Almighty from on high?

** Job 31:3

Is not destruction to the wicked, and aversion to them that work iniquity?

** Job 31:4

Doth not he consider my ways, and number all my steps?

** Job 31:5

If I have walked in vanity, and my foot hath made haste to deceit:

** Job 31:6

Let him weigh me in a just balance, and let God know my simplicity.

** Job 31:7

If my step hath turned out of the way, and if my heart hath followed my eyes, and if a spot hath cleaved to my hands:

** Job 31:8

Then let me sow and let another reap: and let my offspring be rooted out.

** Job 31:9

If my heart hath been deceived upon a woman, and if I have laid wait at my friend's door:

** Job 31:10

Let my wife be the harlot of another, and let other men lie with her.

** Job 31:11

For this is a heinous crime, and a most grievous iniquity.

** Job 31:12

It is a fire that devoureth even to destruction, and rooteth up all things that spring.

** Job 31:13

If I have despised to abide judgment with my manservant, or my maidservant, when they had any controversy against me:

** Job 31:14

For what shall I do when God shall rise to judge? and when he shall examine, what shall I answer him?

** Job 31:15

Did not he that made me in the womb make him also: and did not one and the same form me in the womb?

** Job 31:16

If I have denied to the poor what they desired, and have made the eyes of the widow wait:

** Job 31:17

If I have eaten my morsel alone, and the fatherless hath not eaten thereof:

** Job 31:18

(For from my infancy mercy grew up with me: and it came out with me from my mother's womb:)

** Job 31:19

If I have despised him that was perishing for want of clothing, and the poor man that had no covering:

** Job 31:20

If his sides have not blessed me, and if he were not warmed with the fleece of my sheep:

** Job 31:21

If I have lifted up my hand against the fatherless, even when I saw myself superior in the gate:

** Job 31:22

Let my shoulder fall from its joint, and let my arm with its bones be broken.

** Job 31:23

For I have always feared God as waves swelling over me, and his weight I was unable to bear.

** Job 31:24

If I have thought gold my strength, and have said to fine gold: My confidence:

** Job 31:25

If I have rejoiced over my great riches, and because my hand had gotten much.

** Job 31:26

If I beheld the sun when it shined and the moon going in brightness:

** Job 31:27

And my heart in secret hath rejoiced, and I have kissed my hand with my mouth:

** Job 31:28

Which is a very great iniquity, and a denial against the most high God.

** Job 31:29

If I have been glad at the downfall of him that hated me, and have rejoiced that evil had found him.

** Job 31:30

For I have not been given my mouth to sin, by wishing a curse to his soul.

** Job 31:31

If the men of my tabernacle have not said: Who will give us of his flesh that we may be filled?

** Job 31:32

The stranger did not stay without, my door was open to the traveller.

** Job 31:33

If as a man I have hid my sin, and have concealed my iniquity in my bosom.

** Job 31:34

If I have been afraid at a very great multitude, and the contempt of kinsmen hath terrified me: and have not rather held my peace, and not gone out of the door.

** Job 31:35

Who would grant me a hearing, that the Almighty may hear my desire: and that he himself that judgeth would write a book,

** Job 31:36

That I may carry it on my shoulder, and put it about me as a crown?

** Job 31:37

At every step of mine I would pronounce it, and offer it as to a prince.

** Job 31:38

If my land cry against me, and with it the furrows thereof mourn:

** Job 31:39

If I have eaten the fruits thereof without money, and have afflicted the son of the tillers thereof:

** Job 31:40

Let thistles grow up to me instead of wheat, and thorns instead of barley. 

* Job 32

** Job 32:1

So these three men ceased to answer Job, because he seemed just to himself.

** Job 32:2

And Eliu the son of Barachel the Buzite of the kindred of Ram, was angry and was moved to indignation: now he was angry against Job, because he said he was just before God.

** Job 32:3

And he was angry with his friends, because they had not found a reasonable answer, but only had condemned Job.

** Job 32:4

So Eliu waited while Job was speaking because they were his elders that were speaking.

** Job 32:5

But when he saw that the three were not able to answer, he was exceedingly angry.

** Job 32:6

Then Eliu the son of Barachel the Buzite answered, and said: I am younger in days, and you are more ancient, therefore hanging down my head, I was afraid to shew you my opinion.

** Job 32:7

For I hoped that greater age would speak, and that a multitude of years would teach wisdom.

** Job 32:8

But, as I see, there is a spirit in men, and the inspiration of the Almighty giveth understanding.

** Job 32:9

They that are aged are not the wise men, neither do the ancients understand judgment.

** Job 32:10

Therefore I will speak: Hearken to me, I also will shew you my wisdom.

** Job 32:11

For I have waited for your words, I have given ear to your wisdom, as long as you were disputing in words.

** Job 32:12

And as long as I thought you said some thing, I considered: but, as I see, there is none of you that can convince Job, and answer his words.

** Job 32:13

Lest you should say: We have found wisdom, God hath cast him down, not man.

** Job 32:14

He hath spoken nothing to me, and I will not answer him according to your words.

** Job 32:15

They were afraid, and answered no more, and they left off speaking.

** Job 32:16

Therefore because I have waited, and they have not spoken: they stood, and answered no more:

** Job 32:17

I also will answer my part, and will shew my knowledge.

** Job 32:18

For I am full of matter to speak of, and the spirit of my bowels straiteneth me.

** Job 32:19

Behold, my belly is as new wine which wanteth vent, which bursteth the new vessels.

** Job 32:20

I will speak and take breath a little: I will open my lips, and will answer.

** Job 32:21

I will not accept the person of man, and I will not level God with man.

** Job 32:22

For I know not how long I shall continue, and whether after a while my Maker may take me away. 

* Job 33

** Job 33:1

Hear therefore, O Job, my speeches, and hearken to all my words.

** Job 33:2

Behold now I have opened my mouth, let my tongue speak within my jaws.

** Job 33:3

My words are from my upright heart, and my lips shall speak a pure sentence.

** Job 33:4

The spirit of God made me, and the breath of the Almighty gave me life.

** Job 33:5

If thou canst, answer me, and stand up against my face.

** Job 33:6

Behold God hath made me as well as thee, and of the same clay I also was formed.

** Job 33:7

But yet let not my wonder terrify thee, and let not my eloquence be burdensome to thee.

** Job 33:8

Now thou hast said in my hearing, and I have heard the voice of thy words:

** Job 33:9

I am clean, and without sin: I am unspotted, and there is no iniquity in me.

** Job 33:10

Because he hath found complaints against me, therefore he hath counted me for his enemy.

** Job 33:11

He hath put my feet in the stocks, he hath observed all my paths.

** Job 33:12

Now this is the thing in which thou art not justified: I will answer thee, that God is greater than man.

** Job 33:13

Dost thou strive against him, because he hath not answered thee to all words?

** Job 33:14

God speaketh once, and repeateth not the selfsame thing the second time.

** Job 33:15

By a dream in a vision by night, when deep sleep falleth upon men, and they are sleeping in their beds:

** Job 33:16

Then he openeth the ears of men, and teaching instructeth them in what they are to learn.

** Job 33:17

That he may withdraw a man from the things he is doing, and may deliver him from pride.

** Job 33:18

Rescuing his soul from corruption: and his life from passing to the sword.

** Job 33:19

He rebuketh also by sorrow in the bed, and he maketh all his bones to wither.

** Job 33:20

Bread becometh abominable to him in his life, and to his soul the meat which before he desired.

** Job 33:21

His flesh shall be consumed away, and his bones that were covered shall be made bare.

** Job 33:22

His soul hath drawn near to corruption, and his life to the destroyers.

** Job 33:23

If there shall be an angel speaking for him, one among thousands, to declare man's uprightness,

** Job 33:24

He shall have mercy on him, and shall say: Deliver him, that he may not go down to corruption: I have found wherein I may be merciful to him.

** Job 33:25

His flesh is consumed with punishments, let him return to the days of his youth.

** Job 33:26

He shall pray to God, and he will be gracious to him: and he shall see his face with joy, and he will render to man his justice.

** Job 33:27

He shall look upon men, and shall say: I have sinned, and indeed I have offended, and I have not received what I have deserved.

** Job 33:28

He hath delivered his soul from going into destruction, that it may live and see the light.

** Job 33:29

Behold, all these things God worketh three times within every one.

** Job 33:30

That he may withdraw their souls from corruption, and enlighten them with the light of the living.

** Job 33:31

Attend, Job, and hearken to me, and hold thy peace, whilst I speak.

** Job 33:32

But if thou hast any thing to say, answer me, speak: for I would have thee to appear just.

** Job 33:33

And if thou have not, hear me: hold thy peace, and I will teach thee wisdom. 

* Job 34

** Job 34:1

And Eliu continued his discourse, and said:

** Job 34:2

Hear ye, wise men, my words, and ye learned, hearken to me:

** Job 34:3

For the ear trieth words, and the mouth discerneth meats by the taste.

** Job 34:4

Let us choose to us judgment, and let us see among ourselves what is the best.

** Job 34:5

For Job hath said: I am just, and God hath overthrown my judgment.

** Job 34:6

For in judging me there is a lie: my arrow is violent without any sin.

** Job 34:7

What man is there like Job, who drinketh up scorning like water?

** Job 34:8

Who goeth in company with them that work iniquity, and walketh with wicked men?

** Job 34:9

For he hath said: Man shall not please God, although he run with him.

** Job 34:10

Therefore, ye men of understanding, hear me: far from God be wickedness, and iniquity from the Almighty.

** Job 34:11

For he will render to a man his work, and according to the ways of every one he will reward them.

** Job 34:12

For in very deed God will not condemn without cause, neither will the Almighty pervert judgment.

** Job 34:13

What other hath he appointed over the earth? or whom hath he set over the world which he made?

** Job 34:14

If he turn his heart to him, he shall draw his spirit and breath unto himself.

** Job 34:15

All flesh shall perish together, and man shall return into ashes.

** Job 34:16

If then thou hast understanding, hear what is said, and hearken to the voice of my words.

** Job 34:17

Can he be healed that loveth not judgment? and how dost thou so far condemn him that is just?

** Job 34:18

Who saith to the king: Thou art an apostate: who calleth rulers ungodly:

** Job 34:19

Who accepteth not the persons of princes: nor hath regarded the tyrant, when he contended against the poor man: for all are the work of his hands.

** Job 34:20

They shall suddenly die, and the people shall be troubled at midnight, and they shall pass, and take away the violent without hand.

** Job 34:21

For his eyes are upon the ways of men, and he considereth all their steps.

** Job 34:22

There is no darkness, and there is no shadow of death, where they may be hid who work iniquity.

** Job 34:23

For it is no longer in the power of man to enter into judgment with God.

** Job 34:24

He shall break in pieces many and innumerable, and shall make others to stand in their stead.

** Job 34:25

For he knoweth their works: and therefore he shall bring night on them, and they shall be destroyed.

** Job 34:26

He hath struck them, as being wicked, in open sight.

** Job 34:27

Who as it were on purpose have revolted from him, and would not understand all his ways:

** Job 34:28

So that they caused the cry of the needy to come to him, and he heard the voice of the poor.

** Job 34:29

For when he granteth peace, who is there that can condemn? When he hideth his countenance, who is there that can behold him, whether it regard nations, or all men?

** Job 34:30

Who maketh a man that is a hypocrite to reign for the sins of the people.

** Job 34:31

Seeing then I have spoken of God, I will not hinder thee in thy turn.

** Job 34:32

If I have erred, teach thou me: if I have spoken iniquity, I will add no more.

** Job 34:33

Doth God require it of thee, because it hath displeased thee? for thou begannest to speak, and not I: but if thou know any thing better, speak.

** Job 34:34

Let men of understanding speak to me, and let a wise man hearken to me.

** Job 34:35

But Job hath spoken foolishly, and his words sound not discipline.

** Job 34:36

My father, let Job be tried even to the end: cease not from the man of iniquity.

** Job 34:37

Because he addeth blasphemy upon his sins, let him be tied fast in the mean time amongst us: and then let him provoke God to judgment with his speeches. 

* Job 35

** Job 35:1

Moreover Eliu spoke these words:

** Job 35:2

Doth thy thought seem right to thee, that thou shouldst say: I am more just than God?

** Job 35:3

For thou saidst: That which is right doth not please thee: or what will it profit thee if I sin?

** Job 35:4

Therefore I will answer thy words, and thy friends with thee.

** Job 35:5

Look up to heaven and see, and behold the sky, that it is higher than thee.

** Job 35:6

If thou sin, what shalt thou hurt him? and if thy iniquities be multiplied, what shalt thou do against him?

** Job 35:7

And if thou do justly, what shalt thou give him, or what shall he receive of thy hand?

** Job 35:8

Thy wickedness may hurt a man that is like thee: and thy justice may help the son of man.

** Job 35:9

By reason of the multitude of oppressors they shall cry out: and shall wail for the violence of the arm of tyrants.

** Job 35:10

And he hath not said: Where is God, who made me, who hath given songs in the night?

** Job 35:11

Who teacheth us more than the beasts of the earth, and instructeth us more than the fowls of the air.

** Job 35:12

There shall they cry, and he will not hear, because of the pride of evil men.

** Job 35:13

God therefore will not hear in vain, and the Almighty will look into the causes of every one.

** Job 35:14

Yea, when thou shalt say: He considereth not: be judged before him, and expect him.

** Job 35:15

For he doth not now bring on his fury, neither doth he revenge wickedness exceedingly.

** Job 35:16

Therefore Job openeth his mouth in vain, and multiplieth words without knowledge. 

* Job 36

** Job 36:1

Eliu also proceeded, and said:

** Job 36:2

Suffer me a little, and I will shew thee: for I have yet somewhat to speak in God's behalf.

** Job 36:3

I will repeat my knowledge from the beginning, and I will prove my Maker just.

** Job 36:4

For indeed my words are without a lie, and perfect knowledge shall be proved to thee.

** Job 36:5

God doth not cast away the mighty, whereas he himself also is mighty.

** Job 36:6

But he saveth not the wicked, and he giveth judgment to the poor.

** Job 36:7

He will not take away his eyes from the just, and he placeth kings on the throne for ever, and they are exalted.

** Job 36:8

And if they shall be in chains, and be bound with the cords of poverty:

** Job 36:9

He shall shew them their works, and their wicked deeds, because they have been violent.

** Job 36:10

He also shall open their ear, to correct them: and shall speak, that they may return from iniquity.

** Job 36:11

If they shall hear and observe, they shall accomplish their days in good, and their years in glory.

** Job 36:12

But if they hear not, they shall pass by the sword, and shall be consumed in folly.

** Job 36:13

Dissemblers and crafty men prove the wrath of God, neither shall they cry when they are bound.

** Job 36:14

Their soul shall die in a storm, and their life among the effeminate.

** Job 36:15

He shall deliver the poor out of his distress, and shall open his ear in affliction.

** Job 36:16

Therefore he shall set thee at large out of the narrow mouth, and which hath no foundation under it: and the rest of thy table shall be full of fatness.

** Job 36:17

Thy cause hath been judged as that of the wicked, cause and judgment thou shalt recover.

** Job 36:18

Therefore let not anger overcome thee to oppress any man: neither let multitude of gifts turn thee aside.

** Job 36:19

Lay down thy greatness without tribulation, and all the mighty of strength.

** Job 36:20

Prolong not the night that people may come up for them.

** Job 36:21

Beware thou turn not aside to iniquity: for this thou hast begun to follow after misery.

** Job 36:22

Behold, God is high in his strength, and none is like him among the lawgivers.

** Job 36:23

Who can search out his ways? or who can say to him: Thou hast wrought iniquity?

** Job 36:24

Remember that thou knowest not his work, concerning which men have sung.

** Job 36:25

All men see him, every one beholdeth afar off.

** Job 36:26

Behold, God is great, exceeding our knowledge: the number of his years is inestimable.

** Job 36:27

He lifteth up the drops of rain, and poureth out showers like floods:

** Job 36:28

Which flow from the clouds that cover all above.

** Job 36:29

If he will spread out clouds as his tent,

** Job 36:30

And lighten with his light from above, he shall cover also the ends of the sea.

** Job 36:31

For by these he judgeth people, and giveth food to many mortals.

** Job 36:32

In his hands he hideth the light, and commandeth it to come again.

** Job 36:33

He sheweth his friend concerning it, that it is his possession, and that he may come up to it. 

* Job 37

** Job 37:1

At this my heart trembleth, and is moved out of its place.

** Job 37:2

Hear ye attentively the terror of his voice, and the sound that cometh out of his mouth.

** Job 37:3

He beholdeth under all the heavens, and his light is upon the ends of the earth.

** Job 37:4

After it a noise shall roar, he shall thunder with the voice of his majesty, and shall not be found out, when his voice shall be heard.

** Job 37:5

God shall thunder wonderfully with his voice, he that doth great and unsearchable things.

** Job 37:6

He commandeth the snow to go down upon the earth, and the winter rain, and the shower of his strength.

** Job 37:7

He sealeth up the hand of all men, that every one may know his works.

** Job 37:8

Then the beast shall go into his covert, and shall abide in his den.

** Job 37:9

Out of the inner parts shall a tempest come, and cold out of the north.

** Job 37:10

When God bloweth there cometh frost, and again the waters are poured out abundantly.

** Job 37:11

Corn desireth clouds, and the clouds spread their light:

** Job 37:12

Which go round about, whithersoever the will of him that governeth them shall lead them, to whatsoever he shall command them upon the face of the whole earth:

** Job 37:13

Whether in one tribe, or in his own land, or in what place soever of his mercy he shall command them to be found.

** Job 37:14

Hearken to these things, Job: Stand, and consider the wondrous works of God.

** Job 37:15

Dost thou know when God commanded the rains, to shew his light of his clouds?

** Job 37:16

Knowest thou the great paths of the clouds, and the perfect knowledges?

** Job 37:17

Are not thy garments hot, when the south wind blows upon the earth?

** Job 37:18

Thou perhaps hast made the heavens with him, which are most strong, as if they were of molten brass.

** Job 37:19

Shew us what we may say to him: or we are wrapped up in darkness.

** Job 37:20

Who shall tell him the things I speak? even if a man shall speak, he shall be swallowed up.

** Job 37:21

But now they see not the light: the air on a sudden shall be thickened into clouds, and the wind shall pass and drive them away.

** Job 37:22

Cold cometh out of the north, and to God praise with fear.

** Job 37:23

We cannot find him worthily: he is great in strength, and in judgment, and in justice, and he is ineffable.

** Job 37:24

Therefore men shall fear him, and all that seem to themselves to be wise, shall not dare to behold him. 

* Job 38

** Job 38:1

Then the Lord answered Job out of a whirlwind, and said:

** Job 38:2

Who is this that wrappeth up sentences in unskilful words?

** Job 38:3

Gird up thy loins like a man: I will ask thee, and answer thou me.

** Job 38:4

Where wast thou when I laid the foundations of the earth? tell me if thou hast understanding.

** Job 38:5

Who hath laid the measures thereof, if thou knowest or who hath stretched the line upon it?

** Job 38:6

Upon what are its bases grounded? or who laid the corner stone thereof,

** Job 38:7

When the morning stars praised me together, and all the sons of God made a joyful melody?

** Job 38:8

Who shut up the sea with doors, when it broke forth as issuing out of the womb:

** Job 38:9

When I made a cloud the garment thereof, and wrapped it in a mist as in swaddling bands?

** Job 38:10

I set my bounds around it, and made it bars and doors:

** Job 38:11

And I said: Hitherto thou shalt come, and shalt go no further, and here thou shalt break thy swelling waves.

** Job 38:12

Didst thou since thy birth command the morning, and shew the dawning of the day its place?

** Job 38:13

And didst thou hold the extremities of the earth shaking them, and hast thou shaken the ungodly out of it?

** Job 38:14

The seal shall be restored as clay, and shall stand as a garment.

** Job 38:15

From the wicked their light shall be taken away, and the high arm shall be broken.

** Job 38:16

Hast thou entered into the depths of the sea, and walked in the lowest parts of the deep?

** Job 38:17

Have the gates of death been opened to thee, and hast thou seen the darksome doors?

** Job 38:18

Hast thou considered the breadth of the earth? tell me, if thou knowest all things.

** Job 38:19

Where is the way where light dwelleth, and where is the place of darkness?

** Job 38:20

That thou mayst bring every thing to its own bounds, and understand the paths of the house thereof.

** Job 38:21

Didst thou know then that thou shouldst be born? and didst thou know the number of thy days?

** Job 38:22

Hast thou entered into the storehouses of the snow, or hast thou beheld the treasures of the hail:

** Job 38:23

Which I have prepared for the time of the enemy, against the day of battle and war?

** Job 38:24

By what way is the light spread, and heat divided upon the earth?

** Job 38:25

Who gave a course to violent showers, or a way for noisy thunder:

** Job 38:26

That it should rain on the earth without man in the wilderness, where no mortal dwelleth:

** Job 38:27

That it should fill the desert and desolate land, and should bring forth green grass?

** Job 38:28

Who is the father of rain? or who begot the drops of dew?

** Job 38:29

Out of whose womb came the ice? and the frost from heaven who hath gendered it?

** Job 38:30

The waters are hardened like a stone, and the surface of the deep is congealed.

** Job 38:31

Shalt thou be able to join together the shining stars the Pleiades, or canst thou stop the turning about of Arcturus?

** Job 38:32

Canst thou bring forth the day star in its time, and make the evening star to rise upon the children of the earth?

** Job 38:33

Dost thou know the order of heaven, and canst thou set down the reason thereof on the earth?

** Job 38:34

Canst thou lift up thy voice to the clouds, that an abundance of waters may cover thee?

** Job 38:35

Canst thou send lightnings, and will they go, and will they return and say to thee: Here we are?

** Job 38:36

Who hath put wisdom in the heart of man? or who gave the cock understanding?

** Job 38:37

Who can declare the order of the heavens, or who can make the harmony of heaven to sleep?

** Job 38:38

When was the dust poured on the earth, and the clods fastened together?

** Job 38:39

Wilt thou take the prey for the lioness, and satisfy the appetite of her whelps,

** Job 38:40

When they couch in the dens and lie in wait in holes?

** Job 38:41

Who provideth food for the raven, when her young ones cry to God, wandering about, because they have no meat? 

* Job 39

** Job 39:1

Knowest thou the time when the wild goats bring forth among the rocks, or hast thou observed the hinds when they fawn?

** Job 39:2

Hast thou numbered the months of their conceiving, or knowest thou the time when they bring forth?

** Job 39:3

They bow themselves to bring forth young, and they cast them, and send forth roarings.

** Job 39:4

Their young are weaned and go to feed: they go forth, and return not to them.

** Job 39:5

Who hath sent out the wild ass free, and who hath loosed his bonds?

** Job 39:6

To whom I have given a house in the wilderness, and his dwellings in the barren land.

** Job 39:7

He scorneth the multitude of the city, he heareth not the cry of the driver.

** Job 39:8

He looketh round about the mountains of his pasture, and seeketh for every green thing.

** Job 39:9

Shall the rhinoceros be willing to serve thee, or will he stay at thy crib?

** Job 39:10

Canst thou bind the rhinoceros with thy thong to plough, or will he break the clods of the valleys after thee?

** Job 39:11

Wilt thou have confidence in his great strength, and leave thy labours to him?

** Job 39:12

Wilt thou trust him that he will render thee the seed, and gather it into thy barnfloor?

** Job 39:13

The wing of the ostrich is like the wings of the heron, and of the hawk.

** Job 39:14

When she leaveth her eggs on the earth, thou perhaps wilt warm them in the dust.

** Job 39:15

She forgetteth that the foot may tread upon them, or that the beasts of the field may break them.

** Job 39:16

She is hardened against her young ones, as though they were not hers, she hath laboured in vain, no fear constraining her.

** Job 39:17

For God hath deprived her of wisdom, neither hath he given her understanding.

** Job 39:18

When time shall be, she setteth up her wings on high: she scorneth the horse and his rider.

** Job 39:19

Wilt thou give strength to the horse or clothe his neck with neighing?

** Job 39:20

Wilt thou lift him up like the locusts? the glory of his nostrils is terror.

** Job 39:21

He breaketh up the earth with his hoof, he pranceth boldly, he goeth forward to meet armed men.

** Job 39:22

He despiseth fear, he turneth not his back to the sword.

** Job 39:23

Above him shall the quiver rattle, the spear and shield shall glitter.

** Job 39:24

Chasing and raging he swalloweth the ground, neither doth he make account when the noise of the trumpet soundeth.

** Job 39:25

When he heareth the trumpet he saith: Ha, ha: he smelleth the battle afar off, the encouraging of the captains, and the shouting of the army.

** Job 39:26

Doth the hawk wax feathered by thy wisdom, spreading her wings to the south?

** Job 39:27

Will the eagle mount up at thy command, and make her nest in high places?

** Job 39:28

She abideth among the rocks, and dwelleth among cragged flints, and stony hills, where there is no access.

** Job 39:29

From thence she looketh for the prey, and her eyes behold afar off.

** Job 39:30

Her young ones shall suck up blood: and wheresoever the carcass shall be, she is immediately there.

** Job 39:31

And the Lord went on, and said to Job:

** Job 39:32

Shall he that contendeth with God be so easily silenced? surely he that reproveth God, ought to answer him.

** Job 39:33

Then Job answered the Lord, and said:

** Job 39:34

What can I answer, who hath spoken inconsiderately? I will lay my hand upon my mouth.

** Job 39:35

One thing I have spoken, which I wish I had not said: and another, to which I will add no more. 

* Job 40

** Job 40:1

And the Lord answering Job out of the whirlwind, said:

** Job 40:2

Gird up thy loins like a man: I will ask thee, and do thou tell me.

** Job 40:3

Wilt thou make void my judgment: and condemn me, that thou mayst be justified?

** Job 40:4

And hast thou an arm like God, and canst thou thunder with a voice like him?

** Job 40:5

Clothe thyself with beauty, and set thyself up on high, and be glorious, and put on goodly garments.

** Job 40:6

Scatter the proud in thy indignation, and behold every arrogant man, and humble him.

** Job 40:7

Look on all that are proud, and confound them, and crush the wicked in their place,

** Job 40:8

Hide them in the dust together, and plunge their faces into the pit.

** Job 40:9

Then I will confess that thy right hand is able to save thee.

** Job 40:10

Behold behemoth whom I made with thee, he eateth grass like an ox.

** Job 40:11

His strength is in his loins, and his force in the navel of his belly.

** Job 40:12

He setteth up his tail like a cedar, the sinews of his testicles are wrapped together.

** Job 40:13

His bones are like pipes of brass, his gristle like plates of iron.

** Job 40:14

He is the beginning of the ways of God, who made him, he will apply his sword.

** Job 40:15

To him the mountains bring forth grass: there all the beasts of the field shall play.

** Job 40:16

He sleepeth under the shadow, in the covert of the reed, and in moist places.

** Job 40:17

The shades cover his shadow, the willows of the brook shall compass him about.

** Job 40:18

Behold, he will drink up a river, and not wonder: and he trusteth that the Jordan may run into his mouth.

** Job 40:19

In his eyes as with a hook he shall take him, and bore through his nostrils with stakes.

** Job 40:20

Canst thou draw out the leviathan with a hook, or canst thou tie his tongue with a cord?

** Job 40:21

Canst thou put a ring in his nose, or bore through his jaw with a buckle?

** Job 40:22

Will he make many supplications to thee, or speak soft words to thee?

** Job 40:23

Will he make a covenant with thee, and wilt thou take him to be a servant for ever?

** Job 40:24

Shalt thou play with him as with a bird, or tie him up for thy handmaids?

** Job 40:25

Shall friends cut him in pieces, shall merchants divide him?

** Job 40:26

Wilt thou fill nets with his skin, and the cabins of fishes with his head?

** Job 40:27

Lay thy hand upon him: remember the battle, and speak no more.

** Job 40:28

Behold his hope shall fail him, and in the sight of all he shall be cast down. 

* Job 41

** Job 41:1

I will not stir him up, like one that is cruel, for who can resist my countenance?

** Job 41:2

Who hath given me before that I should repay him? All things that are under heaven are mine.

** Job 41:3

I will not spare him, nor his mighty words, and framed to make supplication.

** Job 41:4

Who can discover the face of his garment? or who can go into the midst of his mouth?

** Job 41:5

Who can open the doors of his face? his teeth are terrible round about.

** Job 41:6

His body is like molten shields, shut close up with scales pressing upon one another.

** Job 41:7

One is joined to another, and not so much as any air can come between them:

** Job 41:8

They stick one to another and they hold one another fast, and shall not be separated.

** Job 41:9

His sneezing is like the shining of fire, and his eyes like the eyelids of the morning.

** Job 41:10

Out of his mouth go forth lamps, like torches of lighted fire.

** Job 41:11

Out of his nostrils goeth smoke, like that of a pot heated and boiling.

** Job 41:12

His breath kindleth coals, and a flame cometh forth out of his mouth.

** Job 41:13

In his neck strength shall dwell, and want goeth before his face.

** Job 41:14

The members of his flesh cleave one to another: he shall send lightnings against him, and they shall not be carried to another place.

** Job 41:15

His heart shall be as hard as a stone, and as firm as a smith's anvil.

** Job 41:16

When he shall raise him up, the angels shall fear, and being affrighted shall purify themselves.

** Job 41:17

When a sword shall lay at him, it shall not be able to hold, nor a spear, nor a breastplate.

** Job 41:18

For he shall esteem iron as straw, and brass as rotten wood.

** Job 41:19

The archer shall not put him to flight, the stones of the sling are to him like stubble.

** Job 41:20

As stubble will he esteem the hammer, and he will laugh him to scorn who shaketh the spear.

** Job 41:21

The beams of the sun shall be under him, and he shall strew gold under him like mire.

** Job 41:22

He shall make the deep sea to boil like a pot, and shall make it as when ointments boil.

** Job 41:23

A path shall shine after him, he shall esteem the deep as growing old.

** Job 41:24

There is no power upon earth that can be compared with him who was made to fear no one.

** Job 41:25

He beholdeth every high thing, he is king over all the children of pride. 

* Job 42

** Job 42:1

Then Job answered the Lord, and said:

** Job 42:2

I know that thou canst do all things, and no thought is hid from thee.

** Job 42:3

Who is this that hideth counsel without knowledge? Therefore I have spoken unwisely, and things that above measure exceeded my knowledge.

** Job 42:4

Hear, and I will speak: I will ask thee, and do thou tell me.

** Job 42:5

With the hearing of the ear, I have heard thee, but now my eye seeth thee.

** Job 42:6

Therefore I reprehend myself, and do penance in dust and ashes.

** Job 42:7

And after the Lord had spoken these words to Job, he said to Eliphaz the Themanite: My wrath is kindled against thee, and against thy two friends, because you have not spoken the thing that is right before me, as my servant Job hath.

** Job 42:8

Take unto you therefore seven oxen and seven rams, and go to my servant Job, and offer for yourselves a holocaust, and my servant Job shall pray for you: his face I will accept, that folly be not imputed to you: for you have not spoken right things before me, as my servant Job hath.

** Job 42:9

So Eliphaz the Themanite, and Baldad the Suhite, and Sophar the Naamathite went, and did as the Lord had spoken to them, and the Lord accepted the face of Job.

** Job 42:10

The Lord also was turned at the penance of Job, when he prayed for his friends. And the Lord gave Job twice as much as he had before.

** Job 42:11

And all his brethren came to him, and all his sisters, and all that knew him before, and they ate bread with him in his house: and bemoaned him, and comforted him upon all the evil that God had brought upon him. And every man gave him one ewe, and one earring of gold.

** Job 42:12

And the Lord blessed the latter end of Job more than his beginning. And he had fourteen thousand sheep, and six thousand camels, and a thousand yoke of oxen, and a thousand she asses.

** Job 42:13

And he had seven sons, and three daughters.

** Job 42:14

And he called the name of one Dies, and the name of the second Cassia, and the name of the third Cornustibii.

** Job 42:15

And there were not found in all the earth women so beautiful as the daughters of Job: and their father gave them inheritance among their brethren.

** Job 42:16

And Job lived after these things, a hundred and forty years, and he saw his children, and his children's children, unto the fourth generation, and he died an old man, and full of days.  

