* Philemon 1

** Philemon 1:1

Paul, a prisoner of Christ Jesus, and Timothy, a brother: to Philemon, our beloved and fellow labourer,

** Philemon 1:2

And to Appia, our dearest sister, and to Archippus, our fellow soldier, and to the church which is in thy house.

** Philemon 1:3

Grace to you and peace, from God our Father and from the Lord Jesus Christ.

** Philemon 1:4

I give thanks to my God, always making a remembrance of thee in my prayers.

** Philemon 1:5

Hearing of thy charity and faith, which thou hast in the Lord Jesus and towards all the saints:

** Philemon 1:6

That the communication of thy faith may be made evident in the acknowledgment of every good work that is in you in Christ Jesus.

** Philemon 1:7

For I have had great joy and consolation in thy charity, because the bowels of the saints have been refreshed by thee, brother.

** Philemon 1:8

Wherefore, though I have much confidence in Christ Jesus to command thee that which is to the purpose:

** Philemon 1:9

For charity sake I rather beseech, whereas thou art such a one, as Paul, an old man and now a prisoner also of Jesus Christ.

** Philemon 1:10

I beseech thee for my son, whom I have begotten in my bands, Onesimus,

** Philemon 1:11

Who hath been heretofore unprofitable to thee but now is profitable both to me and thee:

** Philemon 1:12

Whom I have sent back to thee. And do thou receive him as my own bowels.

** Philemon 1:13

Whom I would have retained with me, that in thy stead he might have ministered to me in the bands of the gospel.

** Philemon 1:14

But without thy counsel I would do nothing: that thy good deed might not be as it were of necessity, but voluntary.

** Philemon 1:15

For perhaps he therefore departed for a season from thee that thou mightest receive him again for ever:

** Philemon 1:16

Not now as a servant, but instead of a servant, a most dear brother, especially to me. But how much more to thee, both in the flesh and in the Lord?

** Philemon 1:17

If therefore thou count me a partner, receive him as myself.

** Philemon 1:18

And if he hath wronged thee in any thing or is in thy debt, put that to my account.

** Philemon 1:19

I Paul have written it with my own hand: I will repay it: not to say to thee that thou owest me thy own self also.

** Philemon 1:20

Yea, brother. May I enjoy thee in the Lord! Refresh my bowels in the Lord.

** Philemon 1:21

Trusting in thy obedience, I have written to thee: knowing that thou wilt also do more than I say.

** Philemon 1:22

But withal prepare me also a lodging. For I hope that through your prayers I shall be given unto you.

** Philemon 1:23

There salute thee Epaphras, my fellow prisoner in Christ Jesus:

** Philemon 1:24

Mark, Aristarchus, Demas and Luke, my fellow labourers.

** Philemon 1:25

The grace of our Lord Jesus Christ be with your spirit. Amen.  

