* Proverbs 1

** Proverbs 1:1

The parables of Solomon, the son of David, king of Israel,

** Proverbs 1:2

To know wisdom, and instruction:

** Proverbs 1:3

To understand the words of prudence: and to receive the instruction of doctrine, justice, and judgment, and equity:

** Proverbs 1:4

To give subtilty to little ones, to the young man knowledge and understanding.

** Proverbs 1:5

A wise man shall hear, and shall be wiser: and he that understandeth shall possess governments.

** Proverbs 1:6

He shall understand a parable and the interpretation, the words of the wise, and their mysterious sayings.

** Proverbs 1:7

The fear of the Lord is the beginning of wisdom. Fools despise wisdom and instruction.

** Proverbs 1:8

My son, hear the instruction of thy father, and forsake not the law of thy mother:

** Proverbs 1:9

That grace may be added to thy head, and a chain of gold to thy neck.

** Proverbs 1:10

My son, if sinners shall entice thee, consent not to them.

** Proverbs 1:11

If they shall say: Come with us, let us lie in wait for blood, let us hide snares for the innocent without cause:

** Proverbs 1:12

Let us swallow him up alive like hell, and whole as one that goeth down into the pit.

** Proverbs 1:13

We shall find all precious substance, we shall fill our houses with spoils.

** Proverbs 1:14

Cast in thy lot with us, let us all have one purse.

** Proverbs 1:15

My son, walk not thou with them, restrain thy foot from their paths.

** Proverbs 1:16

For their feet run to evil, and make haste to shed blood.

** Proverbs 1:17

But a net is spread in vain before the eyes of them that have wings.

** Proverbs 1:18

And they themselves lie in wait for their own blood, and practise deceits against their own souls.

** Proverbs 1:19

So the ways of every covetous man destroy the souls of the possessors.

** Proverbs 1:20

Wisdom preacheth abroad, she uttereth her voice in the streets:

** Proverbs 1:21

At the head of multitudes she crieth out, in the entrance of the gates of the city she uttereth her words, saying:

** Proverbs 1:22

O children, how long will you love childishness, and fools covet those things which are hurtful to themselves, and the unwise hate knowledge?

** Proverbs 1:23

Turn ye at my reproof: behold I will utter my spirit to you, and will shew you my words.

** Proverbs 1:24

Because I called, and you refused: I stretched out my hand, and there was none that regarded.

** Proverbs 1:25

You have despised all my counsel, and have neglected my reprehensions.

** Proverbs 1:26

I also will laugh in your destruction, and will mock when that shall come to you which you feared.

** Proverbs 1:27

When sudden calamity shall fall on you, and destruction, as a tempest, shall be at hand: when tribulation and distress shall come upon you:

** Proverbs 1:28

Then shall they call upon me, and I will not hear: they shall rise in the morning, and shall not find me:

** Proverbs 1:29

Because they have hated instruction, and received not the fear of the Lord,

** Proverbs 1:30

Nor consented to my counsel, but despised all my reproof.

** Proverbs 1:31

Therefore they shall eat the fruit of their own way, and shall be filled with their own devices.

** Proverbs 1:32

The turning away of little ones shall kill them, and the prosperity of fools shall destroy them.

** Proverbs 1:33

But he that shall hear me, shall rest without terror, and shall enjoy abundance, without fear of evils. 

* Proverbs 2

** Proverbs 2:1

My son, if thou wilt receive my words, and wilt hide my commandments with thee,

** Proverbs 2:2

That thy ear may hearken to wisdom: incline thy heart to know prudence.

** Proverbs 2:3

For if thou shalt call for wisdom, and incline thy heart to prudence:

** Proverbs 2:4

If thou shalt seek her as money, and shalt dig for her as for a treasure:

** Proverbs 2:5

Then shalt thou understand the fear of the Lord, and shalt find the knowledge of God:

** Proverbs 2:6

Because the Lord giveth wisdom: and out of his mouth cometh prudence and knowledge.

** Proverbs 2:7

He wilt keep the salvation of the righteous, and protect them that walk in simplicity,

** Proverbs 2:8

Keeping the paths of justice, and guarding the ways of saints.

** Proverbs 2:9

Then shalt thou understand justice, and judgment, and equity, and every good path.

** Proverbs 2:10

If wisdom shall enter into thy heart, and knowledge please thy soul:

** Proverbs 2:11

Counsel shall keep thee, and prudence shall preserve thee,

** Proverbs 2:12

That thou mayst be delivered from the evil way, and from the man that speaketh perverse things:

** Proverbs 2:13

Who leave the right way, and walk by dark ways:

** Proverbs 2:14

Who are glad when they have done evil, and rejoice in the most wicked things:

** Proverbs 2:15

Whose ways are perverse, and their steps infamous.

** Proverbs 2:16

That thou mayst be delivered from the strange woman, and from the stranger, who softeneth her words;

** Proverbs 2:17

And forsaketh the guide of her youth,

** Proverbs 2:18

And hath forgotten the covenant of her God: for her house inclineth unto death, and her paths to hell.

** Proverbs 2:19

None that go in unto her, shall return again, neither shall they take hold of the paths of life.

** Proverbs 2:20

That thou mayst walk in a good way: and mayst keep the paths of the just.

** Proverbs 2:21

For they that are upright, shall dwell in the earth; and the simple shall continue in it.

** Proverbs 2:22

But the wicked shall be destroyed from the earth: and they that do unjustly, shall be taken away from it. 

* Proverbs 3

** Proverbs 3:1

My son, forget not my law, and let thy heart keep my commandments.

** Proverbs 3:2

For they shall add to thee length of days, and years of life, and peace.

** Proverbs 3:3

Let not mercy aud truth leave thee, put them about thy neck, and write them in the tables of thy heart.

** Proverbs 3:4

And thou shalt find grace, and good understanding before God and men.

** Proverbs 3:5

Have confidence in the Lord with all thy heart, and lean not upon thy own prudence.

** Proverbs 3:6

In all thy ways think on him, and he will direct thy steps.

** Proverbs 3:7

Be not wise in thy own conceit: fear God, and depart from evil:

** Proverbs 3:8

For it shall be health to thy navel, and moistening to thy bones.

** Proverbs 3:9

Honour the Lord with thy substance, and give him of the first of all thy fruits;

** Proverbs 3:10

And thy barns shall be filled with abundance, and thy presses shall run over with wine.

** Proverbs 3:11

My son, reject not the correction of the Lord: and do not faint when thou art chastised by him:

** Proverbs 3:12

For whom the Lord loveth, he chastiseth: and as a father in the son he pleaseth himself.

** Proverbs 3:13

Blessed is the man that findeth wisdom, and is rich in prudence:

** Proverbs 3:14

The purchasing thereof is better than the merchandise of silver, and her fruit than the chief and purest gold:

** Proverbs 3:15

She is more precious than all riches: and all the things that are desired, are not to be compared to her.

** Proverbs 3:16

Length of days is in her right hand, and in her left hand riches and glory.

** Proverbs 3:17

Her ways are beautiful ways, and all her paths are peaceable.

** Proverbs 3:18

She is a tree of life to them that lay hold on her: and he that shall retain her is blessed.

** Proverbs 3:19

The Lord by wisdom hath founded the earth, hath established the heavens by prudence.

** Proverbs 3:20

By his wisdom the depths have broken out, and the clouds grow thick with dew.

** Proverbs 3:21

My son, let not these things depart from thy eyes: keep the law and counsel:

** Proverbs 3:22

And there shall be life to thy soul, and grace to thy mouth.

** Proverbs 3:23

Then shalt thou walk confidently in thy way, and thy foot shall not stumble:

** Proverbs 3:24

If thou sleep, thou shalt not fear: thou shalt rest, and thy sleep shall be sweet.

** Proverbs 3:25

Be not afraid of sudden fear, nor of the power of the wicked falling upon thee.

** Proverbs 3:26

For the Lord will be at thy side, and will keep thy foot that thou be not taken.

** Proverbs 3:27

Do not withhold him from doing good, who is able: if thou art able, do good thyself also.

** Proverbs 3:28

Say not to thy friend: Go, and come again: and to morrow I will give to thee: when thou canst give at present.

** Proverbs 3:29

Practise not evil against thy friend, when he hath confidence in thee.

** Proverbs 3:30

Strive not against a man without cause, when he hath done thee no evil.

** Proverbs 3:31

Envy not the unjust man, and do not follow his ways.

** Proverbs 3:32

For every mocker is an abomination to the Lord, and his communication is with the simple.

** Proverbs 3:33

Want is from the Lord in the house of the wicked: but the habitations of the just shall be blessed.

** Proverbs 3:34

He shall scorn the scorners, and to the meek he will give grace.

** Proverbs 3:35

The wise shall possess glory: the promotion of fools is disgrace. 

* Proverbs 4

** Proverbs 4:1

Hear, ye children, the instruction of a father, and attend, that you may know prudence.

** Proverbs 4:2

I will give you a good gift, forsake not my law.

** Proverbs 4:3

For I also was my father's son, tender, and as an only son in the sight of my mother:

** Proverbs 4:4

And he taught me, and said: Let thy heart receive my words, keep my commandments, and thou shalt live.

** Proverbs 4:5

Get wisdom, get prudence: forget not, neither decline from the words of my mouth.

** Proverbs 4:6

Forsake her not, and she shall keep thee: love her, and she shall preserve thee.

** Proverbs 4:7

The beginning of wisdom, get wisdom, and with all thy possession purchase prudence.

** Proverbs 4:8

Take hold on her, and she shall exalt thee: thou shalt be glorified by her, when thou shalt embrace her.

** Proverbs 4:9

She shall give to thy head increase of graces, and protect thee with a noble crown.

** Proverbs 4:10

Hear, O my son, and receive my words, that years of life may be multiplied to thee.

** Proverbs 4:11

I will shew thee the way of wisdom, I will lead thee by the paths of equity:

** Proverbs 4:12

Which when thou shalt have entered, thy steps shall not be straitened, and when thou runnest, thou shalt not meet a stumblingblock.

** Proverbs 4:13

Take hold on instruction, leave it not: keep it, because it is thy life.

** Proverbs 4:14

Be not delighted in the paths of the wicked, neither let the way of evil men please thee.

** Proverbs 4:15

Flee from it, pass not by it: go aside, and forsake it.

** Proverbs 4:16

For they sleep not, except they have done evil: and their sleep is taken away unless they have made some to fall.

** Proverbs 4:17

They eat the bread of wickedness, and drink the wine of iniquity.

** Proverbs 4:18

But the path of the just, as a shining light, goeth forwards, and increaseth even to perfect day.

** Proverbs 4:19

The way of the wicked is darksome: they know not where they fall.

** Proverbs 4:20

My son, hearken to my words, and incline thy ear to my sayings.

** Proverbs 4:21

Let them not depart from thy eyes, keep them in the midst of thy heart:

** Proverbs 4:22

For they are life to those that find them, and health to all flesh.

** Proverbs 4:23

With all watchfulness keep thy heart, because life issueth out from it.

** Proverbs 4:24

Remove from thee a froward mouth, and let detracting lips be far from thee.

** Proverbs 4:25

Let thy eyes look straight on, and let thy eyelids go before thy steps.

** Proverbs 4:26

Make straight the path for thy feet, and all thy ways shall be established.

** Proverbs 4:27

Decline not to the right hand, nor to the left: turn away thy foot from evil. For the Lord knoweth the ways that are on the right hand: but those are perverse which are on the left hand. But he will make thy courses straight, he will bring forward thy ways in peace. 

* Proverbs 5

** Proverbs 5:1

My son, attend to my wisdom, and incline thy ear to my prudence,

** Proverbs 5:2

That thou mayst keep thoughts, and thy lips may preserve instruction. Mind not the deceit of a woman.

** Proverbs 5:3

For the lips of a harlot are like a honeycomb dropping, and her throat is smoother than oil.

** Proverbs 5:4

But her end is bitter as wormwood, and sharp as a two-edged sword.

** Proverbs 5:5

Her feet go down into death, and her steps go in as far as hell.

** Proverbs 5:6

They walk not by the path of life, her steps are wandering, and unaccountable.

** Proverbs 5:7

Now, therefore, my son, hear me, and depart not from the words of my mouth.

** Proverbs 5:8

Remove thy way far from her, and come not nigh the doors of her house.

** Proverbs 5:9

Give not thy honour to strangers, and thy years to the cruel.

** Proverbs 5:10

Lest strangers be filled with thy strength, and thy labours be in another man's house,

** Proverbs 5:11

And thou mourn at the last, when thou shalt have spent thy flesh and thy body, and say;

** Proverbs 5:12

Why have I hated instruction, and my heart consented not to reproof,

** Proverbs 5:13

And have not heard the voice of them that taught me, and have not inclined my ear to masters?

** Proverbs 5:14

I have almost been in all evil, in the midst of the church and of the congregation.

** Proverbs 5:15

Drink water out of thy own cistern, and the streams of thy own well:

** Proverbs 5:16

Let thy fountains be conveyed abroad, and in the streets divide thy waters.

** Proverbs 5:17

Keep them to thyself alone, neither let strangers be partakers with thee.

** Proverbs 5:18

Let thy vein be blessed, and rejoice with the wife of thy youth:

** Proverbs 5:19

Let her be thy dearest hind, and most agreeable fawn: let her breasts inebriate thee at all times: be thou delighted continually with her love.

** Proverbs 5:20

Why art thou seduced, my son, by a strange woman, and art cherished in the bosom of another?

** Proverbs 5:21

The Lord beholdeth the ways of man, and considereth all his steps.

** Proverbs 5:22

His own iniquities catch the wicked, and he is fast bound with the ropes of his own sins.

** Proverbs 5:23

He shall die, because he hath not received instruction, and in the multitude of his folly he shall be deceived. 

* Proverbs 6

** Proverbs 6:1

My son, if thou be surety for thy friend, thou hast engaged fast thy hand to a stranger,

** Proverbs 6:2

Thou art ensnared with the words of thy mouth, and caught with thy own words.

** Proverbs 6:3

Do, therefore, my son, what I say, and deliver thyself: because thou art fallen into the hand of thy neighbour. Run about, make haste, stir up thy friend:

** Proverbs 6:4

Give not sleep to thy eyes, neither let thy eyelids slumber.

** Proverbs 6:5

Deliver thyself as a doe from the hand, and as a bird from the hand of the fowler.

** Proverbs 6:6

Go to the ant, O sluggard, and consider her ways, and learn wisdom:

** Proverbs 6:7

Which, although she hath no guide, nor master, nor captain,

** Proverbs 6:8

Provideth her meat for herself in the summer, and gathereth her food in the harvest.

** Proverbs 6:9

How long wilt thou sleep, O sluggard? when wilt thou arise out of thy sleep?

** Proverbs 6:10

Thou wilt sleep a little, thou wilt slumber a little, thou wilt fold thy hands a little to sleep:

** Proverbs 6:11

And want shall come upon thee, as a traveller, and poverty as a man armed. But if thou be diligent, thy harvest shall come as a fountain, and want shall flee far from thee.

** Proverbs 6:12

A man that is an apostate, an unprofitable man, walketh with a perverse mouth,

** Proverbs 6:13

He winketh with the eyes, presseth with the foot, speaketh with the finger.

** Proverbs 6:14

With a wicked heart he deviseth evil, and at all times he soweth discord.

** Proverbs 6:15

To such a one his destruction shall presently come, and he shall suddenly be destroyed, and shall no longer have any remedy.

** Proverbs 6:16

Six things there are, which the Lord hateth, and the seventh his soul detesteth:

** Proverbs 6:17

Haughty eyes, a lying tongue, hands that shed innocent blood,

** Proverbs 6:18

A heart that deviseth wicked plots, feet that are swift to run into mischief,

** Proverbs 6:19

A deceitful witness that uttereth lies, and him that soweth discord among brethren.

** Proverbs 6:20

My son, keep the commandments of thy father, and forsake not the law of thy mother.

** Proverbs 6:21

Bind them in thy heart continually, and put them about thy neck.

** Proverbs 6:22

When thou walkest, let them go with thee: when thou sleepest, let them keep thee, and when thou awakest, talk with them.

** Proverbs 6:23

Because the commandment is a lamp, and the law a light, and reproofs of instruction are the way of life:

** Proverbs 6:24

That they may keep thee from the evil woman, and from the flattering tongue of the stranger.

** Proverbs 6:25

Let not thy heart covet her beauty, be not caught with her winks:

** Proverbs 6:26

For the price of a harlot is scarce one loaf: but the woman catcheth the precious soul of a man.

** Proverbs 6:27

Can a man hide fire in his bosom, and his garments not burn?

** Proverbs 6:28

Or can he walk upon hot coals, and his feet not be burnt?

** Proverbs 6:29

So he that goeth in to his neighbour's wife, shall not be clean when he shall touch her.

** Proverbs 6:30

The fault is not so great when a man hath stolen: for he stealeth to fill his hungry soul:

** Proverbs 6:31

And if he be taken, he shall restore sevenfold, and shall give up all the substance of his house.

** Proverbs 6:32

But he that is an adulterer, for the folly of his heart shall destroy his own soul:

** Proverbs 6:33

He gathereth to himself shame and dishonour, and his reproach shall not be blotted out:

** Proverbs 6:34

Because the jealousy and rage of the husband will not spare in the day of revenge,

** Proverbs 6:35

Nor will he yield to any man's prayers, nor will he accept for satisfaction ever so many gifts. 

* Proverbs 7

** Proverbs 7:1

My son, keep my words, and lay up my precepts with thee. Son,

** Proverbs 7:2

Keep my commandments, and thou shalt live: and my law as the apple of thy eye:

** Proverbs 7:3

Bind it upon thy fingers, write it upon the tables of thy heart.

** Proverbs 7:4

Say to wisdom: Thou art my sister: and call prudence thy friend,

** Proverbs 7:5

That she may keep thee from the woman that is not thine, and from the stranger who sweeteneth her words.

** Proverbs 7:6

For I looked out of the window of my house through the lattice,

** Proverbs 7:7

And I see little ones, I behold a foolish young man,

** Proverbs 7:8

Who passeth through the street by the corner, and goeth nigh the way of her house,

** Proverbs 7:9

In the dark when it grows late, in the darkness and obscurity of the night.

** Proverbs 7:10

And behold a woman meeteth him in harlot's attire, prepared to deceive souls: talkative and wandering,

** Proverbs 7:11

Not bearing to be quiet, not able to abide still at home,

** Proverbs 7:12

Now abroad, now in the streets, now lying in wait near the corners.

** Proverbs 7:13

And catching the young man, she kisseth him, and with an impudent face, flattereth, saying:

** Proverbs 7:14

I vowed victims for prosperity, this day I have paid my vows.

** Proverbs 7:15

Therefore I am come out to meet thee, desirous to see thee, and I have found thee.

** Proverbs 7:16

I have woven my bed with cords, I have covered it with painted tapestry, brought from Egypt.

** Proverbs 7:17

I have perfumed my bed with myrrh, aloes, and cinnamon.

** Proverbs 7:18

Come, let us be inebriated with the breasts, and let us enjoy the desired embraces, till the day appear.

** Proverbs 7:19

For my husband is not at home, he is gone a very long journey.

** Proverbs 7:20

He took with him a bag of money: he will return home the day of the full moon.

** Proverbs 7:21

She entangled him with many words, and drew him away with the flattery of her lips.

** Proverbs 7:22

Immediately he followeth her as an ox led to be a victim, and as a lamb playing the wanton, and not knowing that he is drawn like a fool to bonds,

** Proverbs 7:23

Till the arrow pierce his liver: as if a bird should make haste to the snare, and knoweth not that his life is in danger.

** Proverbs 7:24

Now, therefore, my son, hear me, and attend to the words of my mouth.

** Proverbs 7:25

Let not thy mind be drawn away in her ways: neither be thou deceived with her paths.

** Proverbs 7:26

For she hath cast down many wounded, and the strongest have been slain by her.

** Proverbs 7:27

Her house is the way to hell, reaching even to the inner chambers of death. 

* Proverbs 8

** Proverbs 8:1

Doth not wisdom cry aloud, and prudence put forth her voice?

** Proverbs 8:2

Standing in the top of the highest places by the way, in the midst of the paths,

** Proverbs 8:3

Beside the gates of the city, in the very doors she speaketh, saying:

** Proverbs 8:4

O ye men, to you I call, and my voice is to the sons of men.

** Proverbs 8:5

O little ones understand subtlety, and ye unwise, take notice.

** Proverbs 8:6

Hear, for I will speak of great things: and my lips shall be opened to preach right things.

** Proverbs 8:7

My mouth shall meditate truth, and my lips shall hate wickedness.

** Proverbs 8:8

All my words are just, there is nothing wicked, nor perverse in them.

** Proverbs 8:9

They are right to them that understand, and just to them that find knowledge.

** Proverbs 8:10

Receive my instruction, and not money: choose knowledge rather than gold.

** Proverbs 8:11

For wisdom is better than all the most precious things: and whatsoever may be desired cannot be compared to it.

** Proverbs 8:12

I, wisdom, dwell in counsel, and am present in learned thoughts.

** Proverbs 8:13

The fear of the Lord hateth evil; I hate arrogance, and pride, and every wicked way, and a mouth with a double tongue.

** Proverbs 8:14

Counsel and equity is mine, prudence is mine, strength is mine.

** Proverbs 8:15

By me kings reign, and lawgivers decree just things.

** Proverbs 8:16

By me princes rule, and the mighty decree justice.

** Proverbs 8:17

I love them that love me: and they that in the morning early watch for me, shall find me.

** Proverbs 8:18

With me are riches and glory, glorious riches and justice.

** Proverbs 8:19

For my fruit is better than gold and the precious stone, and my blossoms than choice silver.

** Proverbs 8:20

I walk in the way of justice, in the midst of the paths of judgment,

** Proverbs 8:21

That I may enrich them that love me, and may fill their treasures.

** Proverbs 8:22

The Lord possessed me in the beginning of his ways, before he made any thing from the beginning.

** Proverbs 8:23

I was set up from eternity, and of old, before the earth was made.

** Proverbs 8:24

The depths were not as yet, and I was already conceived, neither had the fountains of waters as yet sprung out.

** Proverbs 8:25

The mountains, with their huge bulk, had not as yet been established: before the hills, I was brought forth:

** Proverbs 8:26

He had not yet made the earth, nor the rivers, nor the poles of the world.

** Proverbs 8:27

When he prepared the heavens, I was present: when with a certain law, and compass, he enclosed the depths:

** Proverbs 8:28

When he established the sky above, and poised the fountains of waters:

** Proverbs 8:29

When he compassed the sea with its bounds, and set a law to the waters that they should not pass their limits: when he balanced the foundations of the earth;

** Proverbs 8:30

I was with him forming all things: and was delighted every day, playing before him at all times;

** Proverbs 8:31

Playing in the world: and my delights were to be with the children of men.

** Proverbs 8:32

Now, therefore, ye children, hear me: blessed are they that keep my ways.

** Proverbs 8:33

Hear instruction, and be wise, and refuse it not.

** Proverbs 8:34

Blessed is the man that heareth me, and that watcheth daily at my gates, and waiteth at the posts of my doors.

** Proverbs 8:35

He that shall find me, shall find life, and shall have salvation from the Lord.

** Proverbs 8:36

But he that shall sin against me shall hurt his own soul. All that hate me love death. 

* Proverbs 9

** Proverbs 9:1

Wisdom hath built herself a house, she hath hewn her out seven pillars.

** Proverbs 9:2

She hath slain her victims, mingled her wine, and set forth her table.

** Proverbs 9:3

She hath sent her maids to invite to the tower, and to the walls of the city:

** Proverbs 9:4

Whosoever is a little one, let him come to me. And to the unwise she said:

** Proverbs 9:5

Come, eat my bread, and drink the wine which I have mingled for you.

** Proverbs 9:6

Forsake childishness, and live, and walk by the ways of prudence.

** Proverbs 9:7

He that teacheth a scorner, doth an injury to himself; and he that rebuketh a wicked man, getteth himself a blot.

** Proverbs 9:8

Rebuke not a scorner, lest he hate thee. Rebuke a wise man, and he will love thee.

** Proverbs 9:9

Give an occasion to a wise man, and wisdom shall be added to him. Teach a just man, and he shall make haste to receive it.

** Proverbs 9:10

The fear of the Lord is the beginning of wisdom: and the knowledge of the holy is prudence.

** Proverbs 9:11

For by me shall thy days be multiplied, and years of life shall be added to thee.

** Proverbs 9:12

If thou be wise, thou shalt be so to thyself: and if a scorner, thou alone shalt bear the evil.

** Proverbs 9:13

A foolish woman and clamorous, and full of allurements, and knowing nothing at all,

** Proverbs 9:14

Sat at the door of her house, upon a seat, in a high place of the city,

** Proverbs 9:15

To call them that pass by the way, and go on their journey:

** Proverbs 9:16

He that is a little one, let him turn to me. And to the fool she said:

** Proverbs 9:17

Stolen waters are sweeter, and hidden bread is more pleasant.

** Proverbs 9:18

And he did not know that giants are there, and that her guests are in the depths of hell. 

* Proverbs 10

** Proverbs 10:1

A wise son maketh the father glad: but a foolish son is the sorrow of his mother.

** Proverbs 10:2

Treasures of wickedness shall profit nothing: but justice shall deliver from death.

** Proverbs 10:3

The Lord will not afflict the soul of the just with famine, and he will disappoint the deceitful practices of the wicked.

** Proverbs 10:4

The slothful hand hath wrought poverty: but the hand of the industrious getteth riches. He that trusteth to lies feedeth the winds: and the same runneth after birds, that fly away.

** Proverbs 10:5

He that gathereth in the harvest, is a wise son: but he that snorteth in the summer, is the son of confusion.

** Proverbs 10:6

The blessing of the Lord is upon the head of the just: but iniquity covereth the mouth of the wicked.

** Proverbs 10:7

The memory of the just is with praises: and the name of the wicked shall rot.

** Proverbs 10:8

The wise of heart receiveth precepts: a fool is beaten with lips.

** Proverbs 10:9

He that walketh sincerely, walketh confidently: but he that perverteth his ways, shall be manifest.

** Proverbs 10:10

He that winketh with the eye, shall cause sorrow: and the foolish in lips shall be beaten.

** Proverbs 10:11

The mouth of the just is a vein of life: and the mouth of the wicked covereth iniquity.

** Proverbs 10:12

Hatred stirreth up strifes: and charity covereth all sins.

** Proverbs 10:13

In the lips of the wise is wisdom found: and a rod on the back of him that wanteth sense.

** Proverbs 10:14

Wise men lay up knowledge: but the mouth of the fool is next to confusion.

** Proverbs 10:15

The substance of a rich man is the city of his strength: the fear of the poor is their poverty.

** Proverbs 10:16

The work of the just is unto life: but the fruit of the wicked unto sin.

** Proverbs 10:17

The way of life, to him that observeth correction: but he that forsaketh reproofs, goeth astray.

** Proverbs 10:18

Lying lips hide hatred: he that uttereth reproach, is foolish.

** Proverbs 10:19

In the multitude of words there shall not want sin: but he that refraineth his lips, is most wise.

** Proverbs 10:20

The tongue of the just is as choice silver: but the heart of the wicked is nothing worth.

** Proverbs 10:21

The lips of the just teach many: but they that are ignorant, shall die in the want of understanding.

** Proverbs 10:22

The blessing of the Lord maketh men rich: neither shall affliction be joined to them.

** Proverbs 10:23

A fool worketh mischief as it were for sport: but wisdom is prudence to a man.

** Proverbs 10:24

That which the wicked feareth, shall come upon him: to the just their desire shall be given.

** Proverbs 10:25

As a tempest that passeth, so the wicked shall be no more: but the just is as an everlasting foundation.

** Proverbs 10:26

As vinegar to the teeth, and smoke to the eyes, so is the sluggard to them that sent him.

** Proverbs 10:27

The fear of the Lord shall prolong days: and the years of the wicked shall be shortened.

** Proverbs 10:28

The expectation of the just is joy: but the hope of the wicked shall perish.

** Proverbs 10:29

The strength of the upright is the way of the Lord: and fear to them that work evil.

** Proverbs 10:30

The just shall never be moved: but the wicked shall not dwell on the earth.

** Proverbs 10:31

The mouth of the just shall bring forth wisdom: the tongue of the perverse shall perish.

** Proverbs 10:32

The lips of the just consider what is acceptable: and the mouth of the wicked uttereth perverse things. 

* Proverbs 11

** Proverbs 11:1

A deceitful balance is an abomination before the Lord: and a just weight is his will.

** Proverbs 11:2

Where pride is, there also shall be reproach: but where humility is, there also is wisdom.

** Proverbs 11:3

The simplicity of the just shall guide them: and the deceitfulness of the wicked shall destroy them.

** Proverbs 11:4

Riches shall not profit in the day of revenge: but justice shall deliver from death.

** Proverbs 11:5

The justice of the upright shall make his way prosperous: and the wicked man shall fall by his own wickedness.

** Proverbs 11:6

The justice of the righteous shall deliver them: and the unjust shall be caught in their own snares.

** Proverbs 11:7

When the wicked man is dead, there shall be no hope any more: and the expectation of the solicitous shall perish.

** Proverbs 11:8

The just is delivered out of distress: and the wicked shall be given up for him.

** Proverbs 11:9

The dissembler with his mouth deceiveth his friend: but the just shall be delivered by knowledge.

** Proverbs 11:10

When it goeth well with the just, the city shall rejoice: and when the wicked perish, there shall be praise.

** Proverbs 11:11

By the blessing of the just the city shall be exalted: and by the mouth of the wicked it shall be overthrown.

** Proverbs 11:12

He that despiseth his friend, is mean of heart: but the wise man will hold his peace.

** Proverbs 11:13

He that walketh deceitfully, revealeth secrets: but he that is faithful, concealeth the thing committed to him by his friend.

** Proverbs 11:14

Where there is no governor, the people shall fall: but there is safety where there is much counsel.

** Proverbs 11:15

He shall be afflicted with evil, that is surety for a stranger: but he that is aware of snares, shall be secure.

** Proverbs 11:16

A gracious woman shall find glory: and the strong shall have riches.

** Proverbs 11:17

A merciful man doth good to his own soul: but he that is cruel casteth off even his own kindred.

** Proverbs 11:18

The wicked maketh an unsteady work: but to him that soweth justice, there is a faithful reward.

** Proverbs 11:19

Clemency prepareth life: and the pursuing of evil things, death.

** Proverbs 11:20

A perverse heart is abominable to the Lord: and his will is in them that walk sincerely.

** Proverbs 11:21

Hand in hand the evil man shall not be innocent: but the seed of the just shall be saved.

** Proverbs 11:22

A golden ring in a swine's snout, a woman fair and foolish.

** Proverbs 11:23

The desire of the just is all good, the expectation of the wicked is indignation.

** Proverbs 11:24

Some distribute their own goods, and grow richer: others take away what is not their own, and are always in want.

** Proverbs 11:25

The soul that blesseth, shall be made fat: and he that inebriateth, shall be inebriated also himself.

** Proverbs 11:26

He that hideth up corn, shall be cursed among the people: but a blessing upon the head of them that sell.

** Proverbs 11:27

Well doth he rise early who seeketh good things; but he that seeketh after evil things, shall be oppressed by them.

** Proverbs 11:28

He that trusteth in his riches shall fall: but the just shall spring up as a green leaf.

** Proverbs 11:29

He that troubleth his own house, shall inherit the winds: and the fool shall serve the wise.

** Proverbs 11:30

The fruit of the just man is a tree of life: and he that gaineth souls is wise.

** Proverbs 11:31

If the just man receive in the earth, how much more the wicked and the sinner. 

* Proverbs 12

** Proverbs 12:1

He that loveth correction, loveth knowledge: but he that hateth reproof, is foolish.

** Proverbs 12:2

He that is good, shall draw grace from the Lord: but he that trusteth in his own devices, doth wickedly.

** Proverbs 12:3

Man shall not be strengthened by wickedness: and the root of the just shall not be moved.

** Proverbs 12:4

A diligent woman is a crown to her husband: and she that doth things worthy of confusion, is as rottenness in his bones.

** Proverbs 12:5

The thoughts of the just are judgments: and the counsels of the wicked are deceitful.

** Proverbs 12:6

The words of the wicked lie in wait for blood: the mouth of the just shall deliver them.

** Proverbs 12:7

Turn the wicked, and they shall not be: but the house of the just shall stand firm.

** Proverbs 12:8

A man shall be known by his learning: but he that is vain and foolish, shall be exposed to contempt.

** Proverbs 12:9

Better is the poor man that provideth for himself, than he that is glorious and wanteth bread.

** Proverbs 12:10

The just regardeth the lives of his beasts: but the bowels of the wicked are cruel.

** Proverbs 12:11

He that tilleth his land shall be satisfied with bread: but he that pursueth idleness is very foolish.

** Proverbs 12:12

He that is delighted in passing his time over wine, leaveth a reproach in his strong holds. The desire of the wicked is the fortification of evil men: but the root of the just shall prosper.

** Proverbs 12:13

For the sins of the lips ruin draweth nigh to the evil man: but the just shall escape out of distress.

** Proverbs 12:14

By the fruit of his own mouth shall a man be filled with good things, and according to the works of his hands it shall be repaid him.

** Proverbs 12:15

The way of a fool is right in his own eyes: but he that is wise hearkeneth unto counsels.

** Proverbs 12:16

A fool immediately sheweth his anger: but he that dissembleth injuries is wise.

** Proverbs 12:17

He that speaketh that which he knoweth, sheweth forth justice: but he that lieth, is a deceitful witness.

** Proverbs 12:18

There is that promiseth, and is pricked as it were with a sword of conscience: but the tongue of the wise is health.

** Proverbs 12:19

The lip of truth shall be steadfast for ever: but he that is a hasty witness, frameth a lying tongue.

** Proverbs 12:20

Deceit is in the heart of them that think evil things: but joy followeth them that take counsels of peace.

** Proverbs 12:21

Whatsoever shall befall the just man, shall not make him sad: but the wicked shall be filled with mischief.

** Proverbs 12:22

Lying lips are an abomination to the Lord: but they that deal faithfully, please him.

** Proverbs 12:23

A cautious man concealeth knowledge: and the heart of fools publisheth folly.

** Proverbs 12:24

The hand of the valiant shall bear rule: but that which is slothful shall be under tribute.

** Proverbs 12:25

Grief in the heart of a man shall bring him low, but with a good word he shall be made glad.

** Proverbs 12:26

He that neglecteth a loss for the sake of a friend, is just: but the way of the wicked shall deceive them.

** Proverbs 12:27

The deceitful man shall not find gain: but the substance of a just man shall be precious gold.

** Proverbs 12:28

In the path of justice is life: but the bye-way leadeth to death. 

* Proverbs 13

** Proverbs 13:1

A wise son heareth the doctrine of his father: but he that is a scorner, heareth not when he is reproved.

** Proverbs 13:2

Of the fruit of his own month shall a man be filled with good things: but the soul of transgressors is wicked.

** Proverbs 13:3

He that keepeth his mouth keepeth his soul: but he that hath no guard on his speech shall meet with evils.

** Proverbs 13:4

The sluggard willeth, and willeth not: but the soul of them that work, shall be made fat.

** Proverbs 13:5

The just shall hate a lying word: but the wicked confoundeth, and shall be confounded.

** Proverbs 13:6

Justice keepeth the way of the innocent: but wickedness overthroweth the sinner.

** Proverbs 13:7

One is as it were rich, when he hath nothing and another is as it were poor, when he hath great riches.

** Proverbs 13:8

The ransom of a man's life are his riches: but he that is poor, beareth not reprehension.

** Proverbs 13:9

The light of the just giveth joy: but the lamp of the wicked shall be put out.

** Proverbs 13:10

Among the proud there are always contentions: but they that do all things with counsel, are ruled by wisdom.

** Proverbs 13:11

Substance got in haste shall be diminished: but that which by little and little is gathered with the hand, shall increase.

** Proverbs 13:12

Hope that is deferred afflicteth the soul: desire when it cometh, is a tree of life.

** Proverbs 13:13

Whosoever speaketh ill of any thing, bindeth himself for the time to come: but he that feareth the commandment, shall dwell in peace. Deceitful souls go astray in sins: the just are merciful, and shew mercy.

** Proverbs 13:14

The law of the wise is a fountain of life, that he may decline from the ruin of death.

** Proverbs 13:15

Good instruction shall give grace: in the way of scorners is a deep pit.

** Proverbs 13:16

The prudent man doth all things with counsel: but he that is a fool, layeth open his folly.

** Proverbs 13:17

The messenger of the wicked shall fall into mischief: but a faithful ambassador is health.

** Proverbs 13:18

Poverty and shame to him that refuseth instruction: but he that yieldeth to reproof shall be glorified.

** Proverbs 13:19

The desire that is accomplished, delighteth the soul: fools hate them that flee from evil things.

** Proverbs 13:20

He that walketh with the wise, shall be wise: a friend of fools shall become like to them.

** Proverbs 13:21

Evil pursueth sinners: and to the just good shall be repaid.

** Proverbs 13:22

The good man leaveth heirs, sons, and grandsons: and the substance of the sinner is kept for the just.

** Proverbs 13:23

Much food is in the tillage of fathers: but for others it is gathered without judgment.

** Proverbs 13:24

He that spareth the rod, hateth his son: but he that loveth him, correcteth him betimes.

** Proverbs 13:25

The just eateth and filleth his soul: but the belly of the wicked is never to be filled. 

* Proverbs 14

** Proverbs 14:1

A wise woman buildeth her house: but the foolish will pull down with her hands that also which is built.

** Proverbs 14:2

He that walketh in the right way, and feareth God, is despised by him that goeth by an infamous way.

** Proverbs 14:3

In the mouth of a fool is the rod of pride: but the lips of the wise preserve them.

** Proverbs 14:4

Where there are no oxen, the crib is empty: but where there is much corn, there the strength of the ox is manifest.

** Proverbs 14:5

A faithful witness will not lie: but a deceitful witness uttereth a lie.

** Proverbs 14:6

A scorner seeketh wisdom, and findeth it not: the learning of the wise is easy.

** Proverbs 14:7

Go against a foolish man, and he knoweth not the lips of prudence.

** Proverbs 14:8

The wisdom of a discreet man is to understand his way: and the imprudence of fools erreth.

** Proverbs 14:9

A fool will laugh at sin, but among the just grace shall abide.

** Proverbs 14:10

The heart that knoweth the bitterness of his own soul, in his joy the stranger shall not intermeddle.

** Proverbs 14:11

The house of the wicked shall be destroyed: but the tabernacles of the just shall flourish.

** Proverbs 14:12

There is a way which seemeth just to a man: but the ends thereof lead to death.

** Proverbs 14:13

Laughter shall be mingled with sorrow, and mourning taketh hold of the ends of joy.

** Proverbs 14:14

A fool shall be filled with his own ways, and the good man shall be above him.

** Proverbs 14:15

The innocent believeth every word: the discreet man considereth his steps. No good shall come to the deceitful son: but the wise servant shall prosper in his dealings, and his way shall be made straight.

** Proverbs 14:16

A wise man feareth, and declineth from evil: the fool leapeth over, and is confident.

** Proverbs 14:17

The impatient man shall work folly: and the crafty man is hateful.

** Proverbs 14:18

The childish shall possess folly, and the prudent shall look for knowledge.

** Proverbs 14:19

The evil shall fall down before the good: and the wicked before the gates of the just.

** Proverbs 14:20

The poor man shall be hateful even to his own neighbour: but the friends of the rich are many.

** Proverbs 14:21

He that despiseth his neighbour, sinneth: but he that sheweth mercy to the poor, shall be blessed. He that believeth in the Lord, loveth mercy.

** Proverbs 14:22

They err that work evil: but mercy and truth prepare good things.

** Proverbs 14:23

In much work there shall be abundance: but where there are many words, there is oftentimes want.

** Proverbs 14:24

The crown of the wise, is their riches: the folly of fools, imprudence.

** Proverbs 14:25

A faithful witness delivereth souls: and the double dealer uttereth lies.

** Proverbs 14:26

In the fear of the Lord is confidence of strength, and there shall be hope for his children.

** Proverbs 14:27

The fear of the Lord is a fountain of life, to decline from the ruin of death.

** Proverbs 14:28

In the multitude of people is the dignity of the king: and in the small number of the people the dishonour of the prince.

** Proverbs 14:29

He that is patient, is governed with much wisdom: but he that is impatient, exalteth his folly.

** Proverbs 14:30

Soundness of heart is the life of the flesh: but envy is the rottenness of the bones.

** Proverbs 14:31

He that oppresseth the poor, upbraideth his maker: but he that hath pity on the poor, honoureth him.

** Proverbs 14:32

The wicked man shall be driven out in his wickedness: but the just hath hope in his death.

** Proverbs 14:33

In the heart of the prudent resteth wisdom, and it shall instruct all the ignorant.

** Proverbs 14:34

Justice exalteth a nation: but sin maketh nations miserable.

** Proverbs 14:35

A wise servant is acceptable to the king: he that is good for nothing shall feel his anger. 

* Proverbs 15

** Proverbs 15:1

A mild answer breaketh wrath: but a harsh word stirreth up fury.

** Proverbs 15:2

The tongue of the wise adorneth knowledge: but the mouth of fools bubbleth out folly.

** Proverbs 15:3

The eyes of the Lord in every place behold the good and the evil.

** Proverbs 15:4

A peaceable tongue is a tree of life: but that which is immoderate, shall crush the spirit.

** Proverbs 15:5

A fool laugheth at the instruction of his father: but he that regardeth reproofs shall become prudent. In abundant justice there is the greatest strength: but the devices of the wicked shall be rooted out.

** Proverbs 15:6

The house of the just is very much strength: and in the fruits of the wicked is trouble.

** Proverbs 15:7

The lips of the wise shall disperse knowledge: the heart of fools shall be unlike.

** Proverbs 15:8

The victims of the wicked are abominable to the Lord: the vows of the just are acceptable.

** Proverbs 15:9

The way of the wicked is an abomination to the Lord: he that followeth justice is beloved by him.

** Proverbs 15:10

Instruction is grievous to him that forsaketh the way of life: he that hateth reproof shall die.

** Proverbs 15:11

Hell and destruction are before the Lord: how much more the hearts of the children of men?

** Proverbs 15:12

A corrupt man loveth not one that reproveth him: nor will he go to the wise.

** Proverbs 15:13

A glad heart maketh a cheerful countenance: but by grief of mind the spirit is cast down.

** Proverbs 15:14

The heart of the wise seeketh instruction: and the mouth of fools feedeth on foolishness.

** Proverbs 15:15

All the days of the poor are evil: a secure mind is like a continual feast.

** Proverbs 15:16

Better is a little with the fear of the Lord, than great treasures without content.

** Proverbs 15:17

It is better to be invited to herbs with love, than to a fatted calf with hatred.

** Proverbs 15:18

A passionate man stirreth up strifes: he that is patient appeaseth those that are stirred up.

** Proverbs 15:19

The way of the slothful is as a hedge of thorns: the way of the just is without offence.

** Proverbs 15:20

A wise son maketh a father joyful: but the foolish man despiseth his mother.

** Proverbs 15:21

Folly is joy to the fool: and the wise man maketh straight his steps.

** Proverbs 15:22

Designs are brought to nothing where there is no counsel: but where there are many counsellors, they are established.

** Proverbs 15:23

A man rejoiceth in the sentence of his mouth: and a word in due time is best.

** Proverbs 15:24

The path of life is above for the wise, that he may decline from the lowest hell.

** Proverbs 15:25

The Lord will destroy the house of the proud: and will strengthen the borders of the widow.

** Proverbs 15:26

Evil thoughts are an abomination to the Lord: and pure words most beautiful shall be confirmed by him.

** Proverbs 15:27

He that is greedy of gain troubleth his own house: but he that hateth bribes shall live. By mercy and faith sins are purged away: and by the fear of the Lord every one declineth from evil.

** Proverbs 15:28

The mind of the just studieth obedience: the mouth of the wicked overfloweth with evils.

** Proverbs 15:29

The Lord is far from the wicked: and he will hear the prayers of the just.

** Proverbs 15:30

The light of the eyes rejoiceth the soul: a good name maketh the bones fat.

** Proverbs 15:31

The ear that heareth the reproofs of life, shall abide in the midst of the wise.

** Proverbs 15:32

He that rejecteth instruction, despiseth his own soul: but he that yieldeth to reproof, possesseth understanding.

** Proverbs 15:33

The fear of the Lord is the lesson of wisdom: and humility goeth before glory. 

* Proverbs 16

** Proverbs 16:1

It is the part of man to prepare the soul: and of the Lord to govern the tongue.

** Proverbs 16:2

All the ways of a man are open to his eyes: the Lord is the weigher of spirits.

** Proverbs 16:3

Lay open thy works to the Lord: and thy thoughts shall be directed.

** Proverbs 16:4

The Lord hath made all things for himself: the wicked also for the evil day.

** Proverbs 16:5

Every proud man is an abomination to the Lord: though hand should be joined to hand, he is not innocent. The beginning of a good way is to do justice: and this is more acceptable with God, than to offer sacrifices.

** Proverbs 16:6

By mercy and truth iniquity is redeemed; and by the fear of the Lord men depart from evil.

** Proverbs 16:7

When the ways of man shall please the Lord, he will convert even his enemies to peace.

** Proverbs 16:8

Better is a little with justice, than great revenues with iniquity.

** Proverbs 16:9

The heart of man disposeth his way: but the Lord must direct his steps.

** Proverbs 16:10

Divination is in the lips of the king, his mouth shall not err in judgment.

** Proverbs 16:11

Weight and balance are judgments of the Lord: and his work all the weights of the bag.

** Proverbs 16:12

They that act wickedly are abominable to the king: for the throne is established by justice.

** Proverbs 16:13

Just lips are the delight of kings: he that speaketh right things shall be loved.

** Proverbs 16:14

The wrath of a king is as messengers of death: and the wise man will pacify it.

** Proverbs 16:15

In the cheerfulness of the king's countenance is life: and his clemency is like the latter rain.

** Proverbs 16:16

Get wisdom, because it is better than gold: and purchase prudence, for it is more precious than silver.

** Proverbs 16:17

The path of the just departeth from evils: he that keepeth his soul keepeth his way.

** Proverbs 16:18

Pride goeth before destruction: and the spirit is lifted up before a fall.

** Proverbs 16:19

It is better to be humbled with the meek, than to divide spoils with the proud.

** Proverbs 16:20

The learned in word shall find good things: and he that trusteth in the Lord is blessed.

** Proverbs 16:21

The wise in heart shall be called prudent: and he that is sweet in words, shall attain to greater things.

** Proverbs 16:22

Knowledge is a fountain of life to him that possesseth it: the instruction of fools is foolishness.

** Proverbs 16:23

The heart of the wise shall instruct his mouth: and shall add grace to his lips.

** Proverbs 16:24

Well ordered words are as a honeycomb: sweet to the soul, and health to the bones.

** Proverbs 16:25

There is a way that seemeth to a man right: and the ends thereof lead to death.

** Proverbs 16:26

The soul of him that laboureth, laboureth for himself, because his mouth hath obliged him to it.

** Proverbs 16:27

The wicked man diggeth evil, and in his lips is a burning fire.

** Proverbs 16:28

A perverse man stirreth up quarrels: and one full of words separateth princes.

** Proverbs 16:29

An unjust man allureth his friend: and leadeth him into a way that is not good.

** Proverbs 16:30

He that with fixed eyes deviseth wicked things, biting his lips, bringeth evil to pass.

** Proverbs 16:31

Old age is a crown of dignity, when it is found in the ways of justice.

** Proverbs 16:32

The patient man is better than the valiant: and he that ruleth his spirit, than he that taketh cities.

** Proverbs 16:33

Lots are cast into the lap, but they are disposed of by the Lord. 

* Proverbs 17

** Proverbs 17:1

Better is a dry morsel with joy, than a house full of victims with strife.

** Proverbs 17:2

A wise servant shall rule over foolish sons, and shall divide the inheritance among the brethren.

** Proverbs 17:3

As silver is tried by fire, and gold in the furnace: so the Lord trieth the hearts.

** Proverbs 17:4

The evil man obeyeth an unjust tongue: and the deceitful hearkeneth to lying lips.

** Proverbs 17:5

He that despiseth the poor, reproacheth his maker: and he that rejoiceth at another man's ruin, shall not be unpunished.

** Proverbs 17:6

Children's children are the crown of old men: and the glory of children are their fathers.

** Proverbs 17:7

Eloquent words do not become a fool, nor lying lips a prince.

** Proverbs 17:8

The expectation of him that expecteth is a most acceptable jewel: whithersoever he turneth himself, he understandeth wisely.

** Proverbs 17:9

He that concealeth a transgression, seeketh friendships: he that repeateth it again, separateth friends.

** Proverbs 17:10

A reproof availeth more with a wise man, than a hundred stripes with a fool.

** Proverbs 17:11

An evil man always seeketh quarrels: but a cruel angel shall be sent against him.

** Proverbs 17:12

It is better to meet a bear robbed of her whelps, than a fool trusting in his own folly.

** Proverbs 17:13

He that rendereth evil for good, evil shall not depart from his house.

** Proverbs 17:14

The beginning of quarrels is as when one letteth out water: and before he suffereth reproach, he forsaketh judgment.

** Proverbs 17:15

He that justifieth the wicked, and he that condemneth the just, both are abominable before God.

** Proverbs 17:16

What doth it avail a fool to have riches, seeing he cannot buy wisdom? He that maketh his house high, seeketh a downfall: and he that refuseth to learn, shall fall into evils.

** Proverbs 17:17

He that is a friend loveth at all times: and a brother is proved in distress.

** Proverbs 17:18

A foolish man will clap hands, when he is surety for his friend.

** Proverbs 17:19

He that studieth discords, loveth quarrels: and he that exalteth his door, seeketh ruin.

** Proverbs 17:20

He that is of a perverse heart, shall not find good: and he that perverteth his tongue, shall fall into evil.

** Proverbs 17:21

A fool is born to his own disgrace: and even his father shall not rejoice in a fool.

** Proverbs 17:22

A joyful mind maketh age flourishing: a sorrowful spirit drieth up the bones.

** Proverbs 17:23

The wicked man taketh gifts out of the bosom, that he may pervert the paths of judgment.

** Proverbs 17:24

Wisdom shineth in the face of the wise: the eyes of fools are in the ends of the earth.

** Proverbs 17:25

A foolish son is the anger of the father: and the sorrow of the mother that bore him.

** Proverbs 17:26

It is no good thing to do hurt to the just: nor to strike the prince, who judgeth right.

** Proverbs 17:27

He that setteth bounds to his words, is knowing and wise: and the man of understanding is of a precious spirit.

** Proverbs 17:28

Even a fool, if he will hold his peace, shall be counted wise: and if he close his lips, a man of understanding. 

* Proverbs 18

** Proverbs 18:1

He that hath a mind to depart from a friend, seeketh occasions: he shall ever be subject to reproach.

** Proverbs 18:2

A fool receiveth not the words of prudence: unless thou say those things which are in his heart.

** Proverbs 18:3

The wicked man, when he is come into the depths of sins, contemneth: but ignominy and reproach follow him.

** Proverbs 18:4

Words from the mouth of a man are as deep water: and the fountain of wisdom is an overflowing stream.

** Proverbs 18:5

It is not good to accept the person of the wicked, to decline from the truth of judgment.

** Proverbs 18:6

The lips of a fool intermeddle with strife: and his mouth provoketh quarrels.

** Proverbs 18:7

The mouth of a fool is his destruction: and his lips are the ruin of his soul.

** Proverbs 18:8

The words of the double tongued are as if they were harmless: and they reach even to the inner parts of the bowels. Fear casteth down the slothful: and the souls of the effeminate shall be hungry.

** Proverbs 18:9

He that is loose and slack in his work, is the brother of him that wasteth his own works.

** Proverbs 18:10

The name of the Lord is a strong tower: the just runneth to it, and shall be exalted.

** Proverbs 18:11

The substance of the rich man is the city of his strength, and as a strong wall compassing him about.

** Proverbs 18:12

Before destruction, the heart of a man is exalted: and before he be glorified, it is humbled.

** Proverbs 18:13

He that answereth before he heareth, sheweth himself to be a fool, and worthy of confusion.

** Proverbs 18:14

The spirit of a man upholdeth his infirmity: but a spirit that is easily angered, who can bear?

** Proverbs 18:15

A wise heart shall acquire knowledge: and the ear of the wise seeketh instruction.

** Proverbs 18:16

A man's gift enlargeth his way, and maketh him room before princes.

** Proverbs 18:17

The just is first accuser of himself: his friend cometh, and shall search him.

** Proverbs 18:18

The lot suppresseth contentions, and determineth even between the mighty.

** Proverbs 18:19

A brother that is helped by his brother, is like a strong city: and judgments are like the bars of cities.

** Proverbs 18:20

Of the fruit of a man's mouth shall his belly be satisfied: and the offspring of his lips shall fill him.

** Proverbs 18:21

Death and life are in the power of the tongue: they that love it, shall eat the fruits thereof.

** Proverbs 18:22

He that hath found a good wife, hath found a good thing, and shall receive a pleasure from the Lord. He that driveth away a good wife, driveth away a good thing: but he that keepeth an adulteress, is foolish and wicked.

** Proverbs 18:23

The poor will speak with supplications, and the rich will speak roughly.

** Proverbs 18:24

A man amiable in society, shall be more friendly than a brother. 

* Proverbs 19

** Proverbs 19:1

Better is the poor man, that walketh in his simplicity, than a rich man that is perverse in his lips and unwise.

** Proverbs 19:2

Where there is no knowledge of the soul, there is no good: and he that is hasty with his feet shall stumble.

** Proverbs 19:3

The folly of a man supplanteth his steps: and he fretteth in his mind against God.

** Proverbs 19:4

Riches make many friends: but from the poor man, even they whom he had, depart.

** Proverbs 19:5

A false witness shall not be unpunished: and he that speaketh lies, shall not escape.

** Proverbs 19:6

Many honour the person of him that is mighty, and are friends of him that giveth gifts.

** Proverbs 19:7

The brethren of the poor man hate him: moreover also his friends have departed far from him. He that followeth after words only, shall have nothing.

** Proverbs 19:8

But he that possesseth a mind, loveth his own soul, and he that keepeth prudence, shall find good things.

** Proverbs 19:9

A false witness shall not be unpunished: and he that speaketh lies, shall perish.

** Proverbs 19:10

Delicacies are not seemly for a fool: nor for a servant to have rule over princes.

** Proverbs 19:11

The learning of a man is known by patience: and his glory is to pass over wrongs.

** Proverbs 19:12

As the roaring of a lion, so also is the anger of a king: and his cheerfulness as the dew upon the grass.

** Proverbs 19:13

A foolish son is the grief of his father: and a wrangling wife is like a roof continually dropping through.

** Proverbs 19:14

House and riches are given by parents: but a prudent wife is properly from the Lord.

** Proverbs 19:15

Slothfulness casteth into a deep sleep, and an idle soul shall suffer hunger.

** Proverbs 19:16

He that keepeth the commandment, keepeth his own soul: but he that neglecteth his own way, shall die.

** Proverbs 19:17

He that hath mercy on the poor, lendeth to the Lord: and he will repay him.

** Proverbs 19:18

Chastise thy son, despair not: but to the killing of him set not thy soul.

** Proverbs 19:19

He that is impatient, shall suffer damage: and when he shall take away, he shall add another thing.

** Proverbs 19:20

Hear counsel, and receive instruction, that thou mayst be wise in thy latter end.

** Proverbs 19:21

There are many thoughts in the heart of a man: but the will of the Lord shall stand firm.

** Proverbs 19:22

A needy man is merciful: and better is the poor than the lying man.

** Proverbs 19:23

The fear of the Lord is unto life: and he shall abide in the fulness without being visited with evil.

** Proverbs 19:24

The slothful hideth his hand under his armpit, and will not so much as bring it to his mouth.

** Proverbs 19:25

The wicked man being scourged, the fool shall be wiser: but if thou rebuke a wise man, he will understand discipline.

** Proverbs 19:26

He that afflicteth his father, and chaseth away his mother, is infamous and unhappy.

** Proverbs 19:27

Cease not, O my son, to hear instruction, and be not ignorant of the words of knowledge.

** Proverbs 19:28

An unjust witness scorneth judgment: and the mouth of the wicked devoureth iniquity.

** Proverbs 19:29

Judgments are prepared for scorners: and striking hammers for the bodies of fools. 

* Proverbs 20

** Proverbs 20:1

Wine is a luxurious thing, and drunkenness riotous: whosoever is delighted therewith, shall not be wise.

** Proverbs 20:2

As the roaring of a lion, so also is the dread of a king: he that provoketh him, sinneth against his own soul.

** Proverbs 20:3

It is an honour for a man to separate himself from quarrels: but all fools are meddling with reproaches.

** Proverbs 20:4

Because of the cold the sluggard would not plough: he shall beg therefore in the summer, and it shall not be given him.

** Proverbs 20:5

Counsel in the heart of a man is like deep water: but a wise man will draw it out.

** Proverbs 20:6

Many men are called merciful: but who shall find a faithful man?

** Proverbs 20:7

The just that walketh in his simplicity, shall leave behind him blessed children.

** Proverbs 20:8

The king, that sitteth on the throne of judgment, scattereth away all evil with his look.

** Proverbs 20:9

Who can say: My heart is clean, I am pure from sin?

** Proverbs 20:10

Diverse weights and diverse measures, both are abominable before God.

** Proverbs 20:11

By his inclinations a child is known, if his works be clean and right.

** Proverbs 20:12

The hearing ear, and the seeing eye, the Lord hath made them both.

** Proverbs 20:13

Love not sleep, lest poverty oppress thee: open thy eyes, and be filled with bread.

** Proverbs 20:14

It is naught, it is naught, saith every buyer: and when he is gone away, then he will boast.

** Proverbs 20:15

There is gold and a multitude of jewels: but the lips of knowledge are a precious vessel.

** Proverbs 20:16

Take away the garment of him that is surety for a stranger, and take a pledge from him for strangers.

** Proverbs 20:17

The bread of lying is sweet to a man: but afterwards his mouth shall be filled with gravel.

** Proverbs 20:18

Designs are strengthened by counsels: and wars are to be managed by governments.

** Proverbs 20:19

Meddle not with him that revealeth secrets, and walketh deceitfully, and openeth wide his lips.

** Proverbs 20:20

He that curseth his father, and mother, his lamp shall be put out in the midst of darkness.

** Proverbs 20:21

The inheritance gotten hastily in the beginning, in the end shall be without a blessing.

** Proverbs 20:22

Say not: I will return evil: wait for the Lord, and he will deliver thee.

** Proverbs 20:23

Diverse weights are an abomination before the Lord: a deceitful balance is not good.

** Proverbs 20:24

The steps of men are guided by the Lord: but who is the man that can understand his own way?

** Proverbs 20:25

It is ruin to a man to devour holy ones, and after vows to retract.

** Proverbs 20:26

A wise king scattereth the wicked, and bringeth over them the wheel.

** Proverbs 20:27

The spirit of a man is the lamp of the Lord, which searcheth all the hidden things of the bowels.

** Proverbs 20:28

Mercy and truth preserve the king, and his throne is strengthened by clemency.

** Proverbs 20:29

The joy of young men is their strength: and the dignity of old men, their grey hairs.

** Proverbs 20:30

The blueness of a wound shall wipe away evils: and stripes in the more inward parts of the belly. 

* Proverbs 21

** Proverbs 21:1

As the divisions of waters, so the heart of the king is in the hand of the Lord: whithersoever he will, he shall turn it.

** Proverbs 21:2

Every way of a man seemeth right to himself: but the Lord weigheth the hearts.

** Proverbs 21:3

To do mercy and judgment, pleaseth the Lord more than victims.

** Proverbs 21:4

Haughtiness of the eyes is the enlarging of the heart: the lamp of the wicked is sin.

** Proverbs 21:5

The thoughts of the industrious always bring forth abundance: but every sluggard is always in want.

** Proverbs 21:6

He that gathereth treasures by a lying tongue, is vain and foolish, and shall stumble upon the snares of death.

** Proverbs 21:7

The robberies of the wicked shall be their downfall, because they would not do judgment.

** Proverbs 21:8

The perverse way of a man is strange: but as for him that is pure, his work is right.

** Proverbs 21:9

It is better to sit in a corner of the housetop, than with a brawling woman, and in a common house.

** Proverbs 21:10

The soul of the wicked desireth evil, he will not have pity on his neighbour.

** Proverbs 21:11

When a pestilent man is punished, the little one will be wiser: and if he follow the wise, he will receive knowledge.

** Proverbs 21:12

The just considereth seriously the house of the wicked, that he may withdraw the wicked from evil.

** Proverbs 21:13

He that stoppeth his ear against the cry of the poor, shall also cry himself, and shall not be heard.

** Proverbs 21:14

A secret present quencheth anger: and a gift in the bosom, the greatest wrath.

** Proverbs 21:15

It is joy to the just to do judgment: and dread to them that work iniquity.

** Proverbs 21:16

A man that shall wander out of the way of doctrine, shall abide in the company of the giants.

** Proverbs 21:17

He that loveth good cheer, shall be in want: he that loveth wine, and fat things, shall not be rich.

** Proverbs 21:18

The wicked is delivered up for the just: and the unjust for the righteous.

** Proverbs 21:19

It is better to dwell in a wilderness, than with a quarrelsome and passionate woman.

** Proverbs 21:20

There is a treasure to be desired, and oil in the dwelling of the just: and the foolish man shall spend it.

** Proverbs 21:21

He that followeth justice and mercy, shall find life, justice, and glory.

** Proverbs 21:22

The wise man hath scaled the city of the strong, and hath cast down the strength of the confidence thereof.

** Proverbs 21:23

He that keepeth his mouth and his tongue, keepeth his soul from distress.

** Proverbs 21:24

The proud and the arrogant is called ignorant, who in anger worketh pride.

** Proverbs 21:25

Desires kill the slothful: for his hands have refused to work at all.

** Proverbs 21:26

He longeth and desireth all the day: but he that is just, will give, and will not cease.

** Proverbs 21:27

The sacrifices of the wicked are abominable, because they are offered of wickedness.

** Proverbs 21:28

A lying witness shall perish: an obedient man shall speak of victory.

** Proverbs 21:29

The wicked man impudently hardeneth his face: but he that is righteous, correcteth his way.

** Proverbs 21:30

There is no wisdom, there is no prudence, there is no counsel against the Lord.

** Proverbs 21:31

The horse is prepared for the day of battle: but the Lord giveth safety. 

* Proverbs 22

** Proverbs 22:1

A good name is better than great riches: and good favour is above silver and gold.

** Proverbs 22:2

The rich and poor have met one another: the Lord is the maker of them both.

** Proverbs 22:3

The prudent man saw the evil, and hid himself: the simple passed on, and suffered loss.

** Proverbs 22:4

The fruit of humility is the fear of the Lord, riches and glory and life.

** Proverbs 22:5

Arms and swords are in the way of the perverse: but he that keepeth his own soul, departeth far from them.

** Proverbs 22:6

It is a proverb: A young man according to his way, even when he is old, he will not depart from it.

** Proverbs 22:7

The rich ruleth over the poor: and the borrower is servant to him that lendeth.

** Proverbs 22:8

He that soweth iniquity, shall reap evils, and with the rod of his anger he shall be consumed.

** Proverbs 22:9

He that is inclined to mercy, shall be blessed: for of his bread he hath given to the poor. He that maketh presents, shall purchase victory and honour: but he carrieth away the souls of the receivers.

** Proverbs 22:10

Cast out the scoffer, and contention shall go out with him, and quarrels and reproaches shall cease.

** Proverbs 22:11

He that loveth cleanness of heart, for the grace of his lips shall have the king for his friend.

** Proverbs 22:12

The eyes of the Lord preserve knowledge: and the words of the unjust are overthrown.

** Proverbs 22:13

The slothful man saith: There is a lion without, I shall be slain in the midst of the streets.

** Proverbs 22:14

The mouth of a strange woman is a deep pit: he whom the Lord is angry with, shall fall into it.

** Proverbs 22:15

Folly is bound up in the heart of a child, and the rod of correction shall drive it away.

** Proverbs 22:16

He that oppresseth the poor, to increase his own riches, shall himself give to one that is richer, and shall be in need.

** Proverbs 22:17

Incline thy ear, and hear the words of the wise: and apply thy heart to my doctrine:

** Proverbs 22:18

Which shall be beautiful for thee, if thou keep it in thy bowels, and it shall flow in thy lips:

** Proverbs 22:19

That thy trust may be in the Lord, wherefore I have also shewn it to thee this day.

** Proverbs 22:20

Behold I have described it to thee three manner of ways, in thoughts and knowledge:

** Proverbs 22:21

That I might shew thee the certainty, and the words of truth, to answer out of these to them that sent thee.

** Proverbs 22:22

Do no violence to the poor, because he is poor: and do not oppress the needy in the gate:

** Proverbs 22:23

Because the Lord will judge his cause: and will afflict them that have afflicted his soul.

** Proverbs 22:24

Be not a friend to an angry man, and do not walk with a furious man:

** Proverbs 22:25

Lest perhaps thou learn his ways, and take scandal to thy soul.

** Proverbs 22:26

Be not with them that fasten down their hands, and that offer themselves sureties for debts:

** Proverbs 22:27

For if thou have not wherewith to restore, what cause is there that he should take the covering from thy bed?

** Proverbs 22:28

Pass not beyond the ancient bounds which thy fathers have set.

** Proverbs 22:29

Hast thou seen a man swift in his work? he shall stand before kings, and shall not be before those that are obscure. 

* Proverbs 23

** Proverbs 23:1

When thou shalt sit to eat with a prince, consider diligently what is set before thy face:

** Proverbs 23:2

And put a knife to thy throat, if it be so that thou have thy soul in thy own power.

** Proverbs 23:3

Be not desirous of his meats, in which is the bread of deceit.

** Proverbs 23:4

Labour not to be rich: but set bounds to thy prudence.

** Proverbs 23:5

Lift not up thy eyes to riches which thou canst not have: because they shall make themselves wings like those of an eagle, and shall fly towards heaven.

** Proverbs 23:6

Eat not with an envious man, and desire not his meats:

** Proverbs 23:7

Because, like a soothsayer, and diviner, he thinketh that which he knoweth not. Eat and drink, will he say to thee: and his mind is not with thee.

** Proverbs 23:8

The meats which thou hadst eaten, thou shalt vomit up: and shalt loose thy beautiful words.

** Proverbs 23:9

Speak not in the ears of fools: because they will despise the instruction of thy speech.

** Proverbs 23:10

Touch not the bounds of little ones: and enter not into the field of the fatherless:

** Proverbs 23:11

For their near kinsman is strong: and he will judge their cause against thee.

** Proverbs 23:12

Let thy heart apply itself to instruction and thy ears to words of knowledge.

** Proverbs 23:13

Withhold not correction from a child: for if thou strike him with the rod, he shall not die.

** Proverbs 23:14

Thou shalt beat him with the rod, and deliver his soul from hell.

** Proverbs 23:15

My son, if thy mind be wise, my heart shall rejoice with thee:

** Proverbs 23:16

And my reins shall rejoice, when thy lips shall speak what is right.

** Proverbs 23:17

Let not thy heart envy sinners: but be thou in the fear of the Lord all the day long:

** Proverbs 23:18

Because thou shalt have hope in the latter end, and thy expectation shall not be taken away.

** Proverbs 23:19

Hear thou, my son, and be wise: and guide thy mind in the way.

** Proverbs 23:20

Be not in the feasts of great drinkers, nor in their revellings, who contribute flesh to eat:

** Proverbs 23:21

Because they that give themselves to drinking, and that club together, shall be consumed: and drowsiness shall be clothed with rags.

** Proverbs 23:22

Hearken to thy father, that begot thee: and despise not thy mother when she is old.

** Proverbs 23:23

Buy truth, and do not sell wisdom, and instruction, and understanding.

** Proverbs 23:24

The father of the just rejoiceth greatly: he that hath begotten a wise son, shall have joy in him.

** Proverbs 23:25

Let thy father and thy mother be joyful, and let her rejoice that bore thee.

** Proverbs 23:26

My son, give me thy heart: and let thy eyes keep my ways.

** Proverbs 23:27

For a harlot is a deep ditch: and a strange woman is a narrow pit.

** Proverbs 23:28

She lieth in wait in the way as a robber, and him whom she shall see unwary, she will kill.

** Proverbs 23:29

Who hath woe? whose father hath woe? who hath contentions? who falls into pits? who hath wounds without cause? who hath redness of eyes?

** Proverbs 23:30

Surely they that pass their time in wine, and study to drink off their cups.

** Proverbs 23:31

Look not upon the wine when it is yellow, when the colour thereof shineth in the glass: it goeth in pleasantly,

** Proverbs 23:32

But in the end, it will bite like a snake, and will spread abroad poison like a basilisk.

** Proverbs 23:33

Thy eyes shall behold strange women, and thy heart shall utter perverse things.

** Proverbs 23:34

And thou shalt be as one sleeping in the midst of the sea, and as a pilot fast asleep when the stern is lost.

** Proverbs 23:35

And thou shalt say: They have beaten me, but I was not sensible of pain: they drew me, and I felt not: when shall I awake and find wine again? 

* Proverbs 24

** Proverbs 24:1

Seek not to be like evil men, neither desire to be with them:

** Proverbs 24:2

Because their mind studieth robberies, and their lips speak deceits.

** Proverbs 24:3

By wisdom the house shall be built, and by prudence it shall be strengthened.

** Proverbs 24:4

By instruction the storerooms shall be filled with all precious and most beautiful wealth.

** Proverbs 24:5

A wise man is strong: and a knowing man, stout and valiant.

** Proverbs 24:6

Because war is managed by due ordering: and there shall be safety where there are many counsels.

** Proverbs 24:7

Wisdom is too high for a fool; in the gate he shall not open his mouth.

** Proverbs 24:8

He that deviseth to do evils, shall be called a fool.

** Proverbs 24:9

The thought of a fool is sin: and the detractor is the abomination of men.

** Proverbs 24:10

If thou lose hope, being weary in the day of distress, thy strength shall be diminished.

** Proverbs 24:11

Deliver them that are led to death: and those that are drawn to death, forbear not to deliver.

** Proverbs 24:12

If thou say: I have not strength enough: he that seeth into the heart, he understandeth, and nothing deceiveth the keeper of thy soul, and he shall render to a man according to his works.

** Proverbs 24:13

Eat honey, my son, because it is good, and the honeycomb most sweet to thy throat.

** Proverbs 24:14

So also is the doctrine of wisdom to thy soul: which when thou hast found, thou shalt have hope in the end, and thy hope shall not perish.

** Proverbs 24:15

Lie not in wait, nor seek after wickedness in the house of the just, nor spoil his rest.

** Proverbs 24:16

For a just man shall fall seven times, and shall rise again: but the wicked shall fall down into evil.

** Proverbs 24:17

When thy enemy shall fall, be not glad, and in his ruin let not thy heart rejoice:

** Proverbs 24:18

Lest the Lord see, and it displease him, and he turn away his wrath from him.

** Proverbs 24:19

Contend not with the wicked, nor seek to be like the ungodly.

** Proverbs 24:20

For evil men have no hope of things to come, and the lamp of the wicked shall be put out.

** Proverbs 24:21

My son, fear the Lord, and the king: and have nothing to do with detractors.

** Proverbs 24:22

For their destruction shall rise suddenly: and who knoweth the ruin of both?

** Proverbs 24:23

These things also to the wise: It is not good to have respect to persons in judgment.

** Proverbs 24:24

They that say to the wicked man: Thou art just: shall be cursed by the people, and the tribes shall abhor them.

** Proverbs 24:25

They that rebuke him shall be praised: and a blessing shall come upon them.

** Proverbs 24:26

He shall kiss the lips, who answereth right words.

** Proverbs 24:27

Prepare thy work without, and diligently till thy ground: that afterward thou mayst build thy house.

** Proverbs 24:28

Be not witness without cause against thy neighbour: and deceive not any man with thy lips.

** Proverbs 24:29

Say not: I will do to him as he hath done to me: I will render to every one according to his work.

** Proverbs 24:30

I passed by the field of the slothful man, and by the vineyard of the foolish man:

** Proverbs 24:31

And behold it was all filled with nettles, and thorns had covered the face thereof, and the stone wall was broken down.

** Proverbs 24:32

Which when I had seen, I laid it up in my heart, and by the example I received instruction.

** Proverbs 24:33

Thou wilt sleep a little, said I, thou wilt slumber a little, thou wilt fold thy hands a little to rest.

** Proverbs 24:34

And poverty shall come to thee as a runner, and beggary as an armed man. 

* Proverbs 25

** Proverbs 25:1

These are also parables of Solomon, which the men of Ezechias, king of Juda, copied out.

** Proverbs 25:2

It is the glory of God to conceal the word, and the glory of kings to search out the speech.

** Proverbs 25:3

The heaven above and the earth beneath, and the heart of kings is unsearchable.

** Proverbs 25:4

Take away the rust from silver, and there shall come forth a most pure vessel:

** Proverbs 25:5

Take away wickedness from the face of the king, and his throne shall be established with justice.

** Proverbs 25:6

Appear not glorious before the king, and stand not in the place of great men.

** Proverbs 25:7

For it is better that it should be said to thee: Come up hither; than that thou shouldst be humbled before the prince.

** Proverbs 25:8

The things which thy eyes have seen, utter not hastily in a quarrel: lest afterward thou mayst not be able to make amends, when thou hast dishonoured thy friend.

** Proverbs 25:9

Treat thy cause with thy friend, and discover not the secret to a stranger:

** Proverbs 25:10

Lest he insult over thee, when he hath heard it, and cease not to upbraid thee. Grace and friendship deliver a man: keep these for thyself, lest thou fall under reproach.

** Proverbs 25:11

To speak a word in due time, is like apples of gold on beds of silver.

** Proverbs 25:12

As an earring of gold and a bright pearl, so is he that reproveth the wise, and the obedient ear.

** Proverbs 25:13

As the cold of snow in the time of harvest, so is a faithful messenger to him that sent him, for he refresheth his soul.

** Proverbs 25:14

As clouds, and wind, when no rain followeth, so is the man that boasteth, and doth not fulfil his promises.

** Proverbs 25:15

By patience a prince shall be appeased, and a soft tongue shall break hardness.

** Proverbs 25:16

Thou hast found honey, eat what is sufficient for thee, lest being glutted therewith thou vomit it up.

** Proverbs 25:17

Withdraw thy foot from the house of thy neighbour, lest having his fill he hate thee.

** Proverbs 25:18

A man that beareth false witness against his neighbour, is like a dart and a sword and a sharp arrow.

** Proverbs 25:19

To trust in an unfaithful man in the time of trouble, is like a rotten tooth, and weary foot,

** Proverbs 25:20

And one that looseth his garment in cold weather. As vinegar upon nitre, so is he that singeth songs to a very evil heart. As a moth doth by a garment, and a worm by the wood: so the sadness of a man consumeth the heart.

** Proverbs 25:21

If thy enemy be hungry, give him to eat: if he thirst, give him water to drink:

** Proverbs 25:22

For thou shalt heap hot coals upon his head, and the Lord will reward thee.

** Proverbs 25:23

The north wind driveth away rain, as doth a sad countenance a backbiting tongue.

** Proverbs 25:24

It is better to sit in a corner of the housetop: than with a brawling woman, and in a common house.

** Proverbs 25:25

As cold water to a thirsty soul, so are good tidings from a far country.

** Proverbs 25:26

A just man falling down before the wicked, is as a fountain troubled with the foot and a corrupted spring.

** Proverbs 25:27

As it is not good for a man to eat much honey, so he that is a searcher of majesty shall be overwhelmed by glory.

** Proverbs 25:28

As a city that lieth open and is not compassed with walls, so is a man that cannot refrain his own spirit in speaking. 

* Proverbs 26

** Proverbs 26:1

As snow in summer, and rain in harvest, so glory is not seemly for a fool.

** Proverbs 26:2

As a bird flying to other places, and a sparrow going here or there: so a curse uttered without cause shall come upon a man.

** Proverbs 26:3

A whip for a horse, and a snaffle for an ass, and a rod for the back of fools.

** Proverbs 26:4

Answer not a fool according to his folly, lest thou be made like him.

** Proverbs 26:5

Answer a fool according to his folly, lest he imagine himself to be wise.

** Proverbs 26:6

He that sendeth words by a foolish messenger, is lame of feet and drinketh iniquity.

** Proverbs 26:7

As a lame man hath fair legs in vain: so a parable is unseemly in the mouth of fools.

** Proverbs 26:8

As he that casteth a stone into the heap of Mercury: so is he that giveth honour to a fool.

** Proverbs 26:9

As if a thorn should grow in the hand of a drunkard: so is a parable in the mouth of fools.

** Proverbs 26:10

Judgment determineth causes: and he that putteth a fool to silence, appeaseth anger.

** Proverbs 26:11

As a dog that returneth to his vomit, so is the fool that repeateth his folly.

** Proverbs 26:12

Hast thou seen a man wise in his own conceit? there shall be more hope of a fool than of him.

** Proverbs 26:13

The slothful man saith: There is a lion in the way, and a lioness in the roads.

** Proverbs 26:14

As the door turneth upon its hinges, so doth the slothful upon his bed.

** Proverbs 26:15

The slothful hideth his hand under his armpit, and it grieveth him to turn it to his mouth.

** Proverbs 26:16

The sluggard is wiser in his own conceit, than seven men that speak sentences.

** Proverbs 26:17

As he that taketh a dog by the ears, so is he that passeth by in anger, and meddleth with another man's quarrel.

** Proverbs 26:18

As he is guilty that shooteth arrows, and lances unto death.

** Proverbs 26:19

So is the man that hurteth his friend deceitfully: and when he is taken, saith: I did it in jest.

** Proverbs 26:20

When the wood faileth, the fire shall go out: and when the talebearer is taken away, contentions shall cease.

** Proverbs 26:21

As coals are to burning coals, and wood to fire, so an angry man stirreth up strife.

** Proverbs 26:22

The words of a talebearer are as it were simple, but they reach to the innermost parts of the belly.

** Proverbs 26:23

Swelling lips joined with a corrupt heart, are like an earthern vessel adorned with silver dross.

** Proverbs 26:24

An enemy is known by his lips, when in his heart he entertaineth deceit.

** Proverbs 26:25

When he shall speak low, trust him not: because there are seven mischiefs in his heart.

** Proverbs 26:26

He that covereth hatred deceitfully, his malice shall be laid open in the public assembly.

** Proverbs 26:27

He that diggeth a pit, shall fall into it: and he that rolleth a stone, it shall return to him.

** Proverbs 26:28

A deceitful tongue loveth not truth: and a slippery mouth worketh ruin. 

* Proverbs 27

** Proverbs 27:1

Boast not for to morrow, for thou knowest not what the day to come may bring forth.

** Proverbs 27:2

Let another praise thee, and not thy own mouth: a stranger, and not thy own lips.

** Proverbs 27:3

A stone is heavy, and sand weighty: but the anger of a fool is heavier than them both.

** Proverbs 27:4

Anger hath no mercy: nor fury, when it breaketh forth: and who can bear the violence of one provoked?

** Proverbs 27:5

Open rebuke is better than hidden love.

** Proverbs 27:6

Better are the wounds of a friend, than the deceitful kisses of an enemy.

** Proverbs 27:7

A soul that is full shall tread upon the honeycomb: and a soul that is hungry shall take even bitter for sweet.

** Proverbs 27:8

As a bird that wandereth from her nest, so is a man that leaveth his place.

** Proverbs 27:9

Ointment and perfumes rejoice the heart: and the good counsels of a friend are sweet to the soul.

** Proverbs 27:10

Thy own friend, and thy father's friend, forsake not: and go not into thy brother's house in the day of thy affliction. Better is a neighbour that is near than a brother afar off.

** Proverbs 27:11

Study wisdom, my son, and make my heart joyful, that thou mayst give an answer to him that reproacheth.

** Proverbs 27:12

The prudent man seeing evil hideth himself: little ones passing on have suffered losses.

** Proverbs 27:13

Take away his garment that hath been surety for a stranger: and take from him a pledge for strangers.

** Proverbs 27:14

He that blesseth his neighbour with a loud voice, rising in the night, shall be like to him that curseth.

** Proverbs 27:15

Roofs dropping through in a cold day, and a contentious woman are alike.

** Proverbs 27:16

He that retaineth her, is as he that would hold the wind, and shall call the oil of his right hand.

** Proverbs 27:17

Iron sharpeneth iron, so a man sharpeneth the countenance of his friend.

** Proverbs 27:18

He that keepeth the fig tree, shall eat the fruit thereof: and he that is the keeper of his master, shall be glorified.

** Proverbs 27:19

As the faces of them that look therein, shine in the water, so the hearts of men are laid open to the wise.

** Proverbs 27:20

Hell and destruction are never filled: so the eyes of men are never satisfied.

** Proverbs 27:21

As silver is tried in the fining-pot, and gold in the furnace: so a man is tried by the mouth of him that praiseth. The heart of the wicked seeketh after evils, but the righteous heart seeketh after knowledge.

** Proverbs 27:22

Though thou shouldst bray a fool in the mortar, as when a pestle striketh upon sodden barley, his folly would not be taken from him.

** Proverbs 27:23

Be diligent to know the countenance of thy cattle, and consider thy own flocks:

** Proverbs 27:24

For thou shalt not always have power: but a crown shall be given to generation and generation.

** Proverbs 27:25

The meadows are open, and the green herbs have appeared, and the hay is gathered out of the mountains.

** Proverbs 27:26

Lambs are for thy clothing: and kids for the price of the field.

** Proverbs 27:27

Let the milk of the goats be enough for thy food, and for the necessities of thy house, and for maintenance for thy handmaids. 

* Proverbs 28

** Proverbs 28:1

The wicked man fleeth, when no man pursueth: but the just, bold as a lion, shall be without dread.

** Proverbs 28:2

For the sins of the land many are the princes thereof: and for the wisdom of a man, and the knowledge of those things that are said, the life of the prince shall be prolonged.

** Proverbs 28:3

A poor man that oppresseth the poor, is like a violent shower, which bringeth a famine.

** Proverbs 28:4

They that forsake the law, praise the wicked man: they that keep it, are incensed against him.

** Proverbs 28:5

Evil men think not on judgment: but they that seek after the Lord, take notice of all things.

** Proverbs 28:6

Better is the poor man walking in his simplicity, than the rich in crooked ways.

** Proverbs 28:7

He that keepeth the law, is a wise son: but he that feedeth gluttons, shameth his father.

** Proverbs 28:8

He that heapeth together riches by usury and loan, gathereth them for him that will be bountiful to the poor.

** Proverbs 28:9

He that turneth away his ears from hearing the law, his prayer shall be an abomination.

** Proverbs 28:10

He that deceiveth the just in a wicked way, shall fall in his own destruction: and the upright shall possess his goods.

** Proverbs 28:11

The rich man seemeth to himself wise: but the poor man that is prudent shall search him out.

** Proverbs 28:12

In the joy of the just there is great glory: when the wicked reign, men are ruined.

** Proverbs 28:13

He that hideth his sins, shall not prosper: but he that shall confess, and forsake them, shall obtain mercy.

** Proverbs 28:14

Blessed is the man that is always fearful: but he that is hardened in mind shall fall into evil.

** Proverbs 28:15

As a roaring lion, and a hungry bear, so is a wicked prince over the poor people.

** Proverbs 28:16

A prince void of prudence shall oppress many by calumny: but he that hateth covetousness, shall prolong his days.

** Proverbs 28:17

A man that doth violence to the blood of a person, if he flee even to the pit, no man will stay him.

** Proverbs 28:18

He that walketh uprightly, shall be saved: he that is perverse in his ways, shall fall at once.

** Proverbs 28:19

He that tilleth his ground, shall be filled with bread: but he that followeth idleness, shall be filled with poverty.

** Proverbs 28:20

A faithful man shall be much praised: but he that maketh haste to be rich, shall not be innocent.

** Proverbs 28:21

He that hath respect to a person in judgment, doth not well: such a man even for a morsel of bread forsaketh the truth.

** Proverbs 28:22

A man that maketh haste to be rich, and envieth others, is ignorant that poverty shall come upon him.

** Proverbs 28:23

He that rebuketh a man, shall afterward find favour with him, more than he that by a flattering tongue deceiveth him.

** Proverbs 28:24

He that stealeth any thing from his father, or from his mother: and saith, This is no sin, is the partner of a murderer.

** Proverbs 28:25

He that boasteth and puffeth up himself, stirreth up quarrels: but he that trusteth in the Lord, shall be healed.

** Proverbs 28:26

He that trusteth in his own heart, is a fool: but he that walketh wisely, he shall be saved.

** Proverbs 28:27

He that giveth to the poor shall not want: he that despiseth his entreaty, shall suffer indigence.

** Proverbs 28:28

When the wicked rise up, men shall hide themselves: when they perish, the just shall be multiplied. 

* Proverbs 29

** Proverbs 29:1

The man that with a stiff neck despiseth him that reproveth him, shall suddenly be destroyed: and health shall not follow him.

** Proverbs 29:2

When just men increase, the people shall rejoice: when the wicked shall bear rule, the people shall mourn.

** Proverbs 29:3

A man that loveth wisdom, rejoiceth his father: but he that maintaineth harlots, shall squander away his substance.

** Proverbs 29:4

A just king setteth up the land: a covetous man shall destroy it.

** Proverbs 29:5

A man that speaketh to his friend with flattering and dissembling words, spreadeth a net for his feet.

** Proverbs 29:6

A snare shall entangle the wicked man when he sinneth: and the just shall praise and rejoice.

** Proverbs 29:7

The just taketh notice of the cause of the poor: the wicked is void of knowledge.

** Proverbs 29:8

Corrupt men bring a city to ruin: but wise men turn away wrath.

** Proverbs 29:9

If a wise man contend with a fool, whether he be angry, or laugh, he shall find no rest.

** Proverbs 29:10

Bloodthirsty men hate the upright: but just men seek his soul.

** Proverbs 29:11

A fool uttereth all his mind: a wise man deferreth, and keepeth it till afterwards.

** Proverbs 29:12

A prince that gladly heareth lying words, hath all his servants wicked.

** Proverbs 29:13

The poor man and the creditor have met one another: the Lord is the enlightener of them both.

** Proverbs 29:14

The king that judgeth the poor in truth, his throne shall be established for ever.

** Proverbs 29:15

The rod and reproof give wisdom: but the child that is left to his own will, bringeth his mother to shame.

** Proverbs 29:16

When the wicked are multiplied, crimes shall be multiplied: but the just shall see their downfall.

** Proverbs 29:17

Instruct thy son and he shall refresh thee, and shall give delight to thy soul.

** Proverbs 29:18

When prophecy shall fail, the people shall be scattered abroad: but he that keepeth the law, is blessed.

** Proverbs 29:19

A slave will not be corrected by words: because he understandeth what thou sayest, and will not answer.

** Proverbs 29:20

Hast thou seen a man hasty to speak? folly is rather to be looked for, than his amendment.

** Proverbs 29:21

He that nourisheth his servant delicately from his childhood, afterwards shall find him stubborn.

** Proverbs 29:22

A passionate man provoketh quarrels: and he that is easily stirred up to wrath, shall be more prone to sin.

** Proverbs 29:23

Humiliation followeth the proud: and glory shall uphold the humble of spirit.

** Proverbs 29:24

He that is partaker with a thief, hateth his own soul: he heareth one putting him to his oath, and discovereth not.

** Proverbs 29:25

He that feareth man shall quickly fall: he that trusteth in the Lord, shall be set on high.

** Proverbs 29:26

Many seek the face of the prince: but the judgment of every one cometh forth from the Lord.

** Proverbs 29:27

The just abhor a wicked man: and the wicked loathe them that are in the right way. The son that keepeth the word, shall be free from destruction. 

* Proverbs 30

** Proverbs 30:1

The words of Gatherer the son of Vomiter. The vision which the man spoke, with whom God is, and who being strengthened by God, abiding with him, said:

** Proverbs 30:2

I am the most foolish of men, and the wisdom of men is not with me.

** Proverbs 30:3

I have not learned wisdom, and have not known the science of saints.

** Proverbs 30:4

Who hath ascended up into heaven, and descended? who hath held the wind in his hands? who hath bound up the waters together as in a garment? who hath raised up all the borders of the earth? what is his name, and what is the name of his son, if thou knowest?

** Proverbs 30:5

Every word of God is fire tried: he is a buckler to them that hope in him.

** Proverbs 30:6

Add not any thing to his words, lest thou be reproved and found a liar:

** Proverbs 30:7

Two things I have asked of thee, deny them not to me before I die.

** Proverbs 30:8

Remove far from me vanity, and lying words. Give me neither beggary, nor riches: give me only the necessaries of life:

** Proverbs 30:9

Lest perhaps being filled, I should be tempted to deny, and say: Who is the Lord? or being compelled by poverty, I should steal, and forswear the name of my God.

** Proverbs 30:10

Accuse not a servant to his master, lest he curse thee, and thou fall.

** Proverbs 30:11

There is a generation that curseth their father, and doth not bless their mother.

** Proverbs 30:12

A generation that are pure in their own eyes, and yet are not washed from their filthiness.

** Proverbs 30:13

A generation, whose eyes are lofty, and their eyelids lifted up on high.

** Proverbs 30:14

A generation that for teeth hath swords, and grindeth with their jaw teeth, to devour the needy from off the earth, and the poor from among men.

** Proverbs 30:15

The horseleech hath two daughters that say: Bring, bring. There are three things that never are satisfied, and the fourth never saith: It is enough.

** Proverbs 30:16

Hell and the mouth of the womb, and the earth which is not satisfied with water: and the fire never saith: It is enough.

** Proverbs 30:17

The eye that mocketh at his father, and that despiseth the labour of his mother in bearing him, let the ravens of the brooks pick it out, and the young eagles eat it.

** Proverbs 30:18

Three things are hard to me, and the fourth I am utterly ignorant of.

** Proverbs 30:19

There are three things, which go well, and the fourth that walketh happily:

** Proverbs 30:20

Such also is the way of an adulterous woman, who eateth and wipeth her mouth, and saith: I have done no evil.

** Proverbs 30:21

By three things the earth is disturbed, and the fourth it cannot bear.

** Proverbs 30:22

By a slave when he reigneth: by a fool when be is filled with meat:

** Proverbs 30:23

By an odious woman when she is married: and by a bondwoman when she is heir to her mistress.

** Proverbs 30:24

There are four very little things of the earth, and they are wiser than the wise.

** Proverbs 30:25

The ants, a feeble people, which provide themselves food in the harvest:

** Proverbs 30:26

The rabbit, a weak people, which maketh its bed in the rock:

** Proverbs 30:27

The locust hath no king, yet they all go out by their bands:

** Proverbs 30:28

The stellio supporteth itself on hands, and dwelleth in kings' houses.

** Proverbs 30:29

nil

** Proverbs 30:30

A lion, the strongest of beasts, who hath no fear of any thing he meeteth:

** Proverbs 30:31

A cock girded about the loins: and a ram: and a king, whom none can resist.

** Proverbs 30:32

There is that hath appeared a fool after he was lifted up on high: for if he had understood, he would have laid his hand upon his mouth.

** Proverbs 30:33

And he that strongly squeezeth the paps to bring out milk, straineth out butter: and he that violently bloweth his nose, bringeth out blood: and he that provoketh wrath, bringeth forth strife. 

* Proverbs 31

** Proverbs 31:1

The words of king Lamuel. The vision wherewith his mother instructed him.

** Proverbs 31:2

What, O my beloved, what, O the beloved of my womb, what, O the beloved of my vows?

** Proverbs 31:3

Give not thy substance to women, and thy riches to destroy kings.

** Proverbs 31:4

Give not to kings, O Lamuel, give not wine to kings: because there is no secret where drunkenness reigneth:

** Proverbs 31:5

And lest they drink and forget judgments, and pervert the cause of the children of the poor.

** Proverbs 31:6

Give strong drink to them that are sad; and wine to them that are grieved in mind:

** Proverbs 31:7

Let them drink, and forget their want, and remember their sorrow no more.

** Proverbs 31:8

Open thy mouth for the dumb, and for the causes of all the children that pass.

** Proverbs 31:9

Open thy mouth, decree that which is just, and do justice to the needy and poor.

** Proverbs 31:10

Who shall find a valiant woman? far, and from the uttermost coasts is the price of her.

** Proverbs 31:11

The heart of her husband trusteth in her, and he shall have no need of spoils.

** Proverbs 31:12

She will render him good, and not evil all the days of her life.

** Proverbs 31:13

She hath sought wool and flax, and hath wrought by the counsel of her hands.

** Proverbs 31:14

She is like the merchant's ship, she bringeth her bread from afar.

** Proverbs 31:15

And she hath risen in the night, and given a prey to her household, and victuals to her maidens.

** Proverbs 31:16

She hath considered a field, and bought it: with the fruit of her hands she hath planted a vineyard.

** Proverbs 31:17

She hath girded her loins with strength, and hath strengthened her arm.

** Proverbs 31:18

She hath tasted, and seen that her traffic is good: her lamp shall not be put out in the night.

** Proverbs 31:19

She hath put out her hand to strong things, and her fingers have taken hold of the spindle.

** Proverbs 31:20

She hath opened her hand to the needy, and stretched out her hands to the poor.

** Proverbs 31:21

She shall not fear for her house in the cold of snow: for all her domestics are clothed with double garments.

** Proverbs 31:22

She hath made for herself clothing of tapestry: fine linen, and purple, is her covering.

** Proverbs 31:23

Her husband is honourable in the gates, when he sitteth among the senators of the land.

** Proverbs 31:24

She made fine linen, and sold it, and delivered a girdle to the Chanaanite.

** Proverbs 31:25

Strength and beauty are her clothing, and she shall laugh in the latter day.

** Proverbs 31:26

She hath opened her mouth to wisdom, and the law of clemency is on her tongue.

** Proverbs 31:27

She hath looked well on the paths of her house, and hath not eaten her bread idle.

** Proverbs 31:28

Her children rose up, and called her blessed: her husband, and he praised her.

** Proverbs 31:29

Many daughters have gathered together riches: thou hast surpassed them all.

** Proverbs 31:30

Favour is deceitful, and beauty is vain: the woman that feareth the Lord, she shall be praised.

** Proverbs 31:31

Give her of the fruit of her hands: and let her works praise her in the gates.  

