* I Chronicles 1

** I Chronicles 1:1

Adam, Seth, Enos,

** I Chronicles 1:2

Cainan, Malaleel, Jared,

** I Chronicles 1:3

Henoch, Mathusale, Lamech,

** I Chronicles 1:4

Noë, Sem, Cham, et Japtheth.

** I Chronicles 1:5

Filii Japheth : Gomer, et Magog, et Madai, et Javan, Thubal, Mosoch, Thiras.

** I Chronicles 1:6

Porro filii Gomer : Ascenez, et Riphath, et Thogorma.

** I Chronicles 1:7

Filii autem Javan : Elisa et Tharsis, Cethim et Dodanim.

** I Chronicles 1:8

Filii Cham : Chus, et Mesraim, et Phut, et Chanaan.

** I Chronicles 1:9

Filii autem Chus : Saba, et Hevila, Sabatha, et Regma, et Sabathacha. Porro filii Regma : Saba, et Dadan.

** I Chronicles 1:10

Chus autem genuit Nemrod : iste cœpit esse potens in terra.

** I Chronicles 1:11

Mesraim vero genuit Ludim, et Anamim, et Laabim, et Nephtuim,

** I Chronicles 1:12

Phetrusim quoque, et Casluim : de quibus egressi sunt Philisthiim, et Caphtorim.

** I Chronicles 1:13

Chanaan vero genuit Sidonem primogenitum suum, Hethæum quoque,

** I Chronicles 1:14

et Jebusæum, et Amorrhæum, et Gergesæum,

** I Chronicles 1:15

Hevæumque et Aracæum, et Sinæum.

** I Chronicles 1:16

Aradium quoque, et Samaræum, et Hamathæum.

** I Chronicles 1:17

Filii Sem : Ælam, et Assur, et Arphaxad, et Lud, et Aram, et Hus, et Hul, et Gether, et Mosoch.

** I Chronicles 1:18

Arphaxad autem genuit Sale, qui et ipse genuit Heber.

** I Chronicles 1:19

Porro Heber nati sunt duo filii : nomen uni Phaleg, quia in diebus ejus divisa est terra ; et nomen fratris ejus Jectan.

** I Chronicles 1:20

Jectan autem genuit Elmodad, et Saleph, et Asarmoth, et Jare,

** I Chronicles 1:21

Adoram quoque, et Huzal, et Decla,

** I Chronicles 1:22

Hebal etiam, et Abimaël, et Saba, necnon

** I Chronicles 1:23

et Ophir, et Hevila, et Jobab : omnes isti filii Jectan.

** I Chronicles 1:24

Sem, Arphaxad, Sale,

** I Chronicles 1:25

Heber, Phaleg, Ragau,

** I Chronicles 1:26

Serug, Nachor, Thare,

** I Chronicles 1:27

Abram : iste est Abraham.  

** I Chronicles 1:28

Filii autem Abraham, Isaac et Ismahel.

** I Chronicles 1:29

Et hæ generationes eorum. Primogenitus Ismahelis, Nabaioth, et Cedar, et Adbeel, et Mabsam,

** I Chronicles 1:30

et Masma, et Duma, Massa, Hadad, et Thema,

** I Chronicles 1:31

Jetur, Naphis, Cedma : hi sunt filii Ismahelis.

** I Chronicles 1:32

Filii autem Ceturæ concubinæ Abraham, quos genuit : Zamran, Jecsan, Madan, Madian, Jesboc, et Sue. Porro filii Jecsan : Saba, et Dadan. Filii autem Dadan : Assurim, et Latussim, et Laomim.

** I Chronicles 1:33

Filii autem Madian : Epha, et Epher, et Henoch, et Abida, et Eldaa : omnes hi filii Ceturæ.

** I Chronicles 1:34

Genuit autem Abraham Isaac : cujus fuerunt filii Esau, et Israël.

** I Chronicles 1:35

Filii Esau : Eliphaz, Rahuel, Jehus, Ihelom, et Core.

** I Chronicles 1:36

Filii Eliphaz : Theman, Omar, Sephi, Gathan, Cenez, Thamna, Amalec.

** I Chronicles 1:37

Filii Rahuel : Nahath, Zara, Samma, Meza.

** I Chronicles 1:38

Filii Seir : Lotan, Sobal, Sebeon, Ana, Dison, Eser, Disan.

** I Chronicles 1:39

Filii Lotan : Hori, Homam. Soror autem Lotan fuit Thamna.

** I Chronicles 1:40

Filii Sobal : Alian, et Manahath, et Ebal, Sephi et Onam. Filii Sebeon : Aja et Ana. Filii Ana : Dison.

** I Chronicles 1:41

Filii Dison : Hamram, et Heseban, et Jethran, et Charan.

** I Chronicles 1:42

Filii Eser : Balaan, et Zavan, et Jacan. Filii Disan : Hus et Aran.  

** I Chronicles 1:43

Isti sunt reges qui imperaverunt in terra Edom, antequam esset rex super filios Israël. Bale filius Beor : et nomen civitatis ejus, Denaba.

** I Chronicles 1:44

Mortuus est autem Bale, et regnavit pro eo Jobab filius Zare de Bosra.

** I Chronicles 1:45

Cumque et Jobab fuisset mortuus, regnavit pro eo Husam de terra Themanorum.

** I Chronicles 1:46

Obiit quoque et Husam, et regnavit pro eo Adad filius Badad, qui percussit Madian in terra Moab : et nomen civitatis ejus Avith.

** I Chronicles 1:47

Cumque et Adad fuisset mortuus, regnavit pro eo Semla de Masreca.

** I Chronicles 1:48

Sed et Semla mortuus est, et regnavit pro eo Saul de Rohoboth, quæ juxta amnem sita est.

** I Chronicles 1:49

Mortuo quoque Saul, regnavit pro eo Balanan filius Achobor.

** I Chronicles 1:50

Sed et hic mortuus est, et regnavit pro eo Adad : cujus urbis nomen fuit Phau, et appellata est uxor ejus Meetabel filia Matred filiæ Mezaab.  

** I Chronicles 1:51

Adad autem mortuo, duces pro regibus in Edom esse cœperunt : dux Thamna, dux Alva, dux Jetheth,

** I Chronicles 1:52

dux Oolibama, dux Ela, dux Phinon,

** I Chronicles 1:53

dux Cenez, dux Theman, dux Mabsar,

** I Chronicles 1:54

dux Magdiel, dux Hiram : hi duces Edom.   

* I Chronicles 2

** I Chronicles 2:1

Filii autem Israël : Ruben, Simeon, Levi, Juda, Issachar, et Zabulon,

** I Chronicles 2:2

Dan, Joseph, Benjamin, Nephthali, Gad, et Aser.  

** I Chronicles 2:3

Filii Juda : Her, Onan, et Sela : hi tres nati sunt ei de filia Sue Chananitide. Fuit autem Her primogenitus Juda malus coram Domino, et occidit eum.

** I Chronicles 2:4

Thamar autem nurus ejus peperit ei Phares et Zara : omnes ergo filii Juda, quinque.

** I Chronicles 2:5

Filii autem Phares : Hesron et Hamul.

** I Chronicles 2:6

Filii quoque Zaræ : Zamri, et Ethan, et Eman, Chalchal quoque, et Dara, simul quinque.

** I Chronicles 2:7

Filii Charmi : Achar, qui turbavit Israël, et peccavit in furto anathematis.

** I Chronicles 2:8

Filii Ethan : Azarias.

** I Chronicles 2:9

Filii autem Hesron qui nati sunt ei : Jerameel, et Ram, et Calubi.

** I Chronicles 2:10

Porro Ram genuit Aminadab. Aminadab autem genuit Nahasson, principem filiorum Juda.

** I Chronicles 2:11

Nahasson quoque genuit Salma, de quo ortus est Booz.

** I Chronicles 2:12

Booz vero genuit Obed, qui et ipse genuit Isai.

** I Chronicles 2:13

Isai autem genuit primogenitum Eliab, secundum Abinadab, tertium Simmaa,

** I Chronicles 2:14

quartum Nathanaël, quintum Raddai,

** I Chronicles 2:15

sextum Asom, septimum David.

** I Chronicles 2:16

Quorum sorores fuerunt Sarvia et Abigail. Filii Sarviæ : Abisai, Joab, et Asaël, tres.

** I Chronicles 2:17

Abigail autem genuit Amasa, cujus pater fuit Jether Ismahelites.

** I Chronicles 2:18

Caleb vero filius Hesron accepit uxorem nomine Azuba, de qua genuit Jerioth : fueruntque filii ejus Jaser, et Sobab, et Ardon.

** I Chronicles 2:19

Cumque mortua fuisset Azuba, accepit uxorem Caleb Ephratha, quæ peperit ei Hur.

** I Chronicles 2:20

Porro Hur genuit Uri, et Uri genuit Bezeleel.

** I Chronicles 2:21

Post hæc ingressus est Hesron ad filiam Machir patris Galaad, et accepit eam cum esset annorum sexaginta : quæ peperit ei Segub.

** I Chronicles 2:22

Sed et Segub genuit Jair, et possedit viginti tres civitates in terra Galaad.

** I Chronicles 2:23

Cepitque Gessur et Aram oppida Jair, et Canath, et viculos ejus sexaginta civitatum : omnes isti filii Machir patris Galaad.

** I Chronicles 2:24

Cum autem mortuus esset Hesron, ingressus est Caleb ad Ephratha. Habuit quoque Hesron uxorem Abia, quæ peperit ei Assur patrem Thecuæ.  

** I Chronicles 2:25

Nati sunt autem filii Jerameel primogeniti Hesron, Ram primogenitus ejus, et Buna, et Aram, et Asom, et Achia.

** I Chronicles 2:26

Duxit quoque uxorem alteram Jerameel, nomine Atara, quæ fuit mater Onam.

** I Chronicles 2:27

Sed et filii Ram primogeniti Jerameel fuerunt Moos, Jamin, et Achar.

** I Chronicles 2:28

Onam autem habuit filios Semei et Jada. Filii autem Semei : Nadab et Abisur.

** I Chronicles 2:29

Nomen vero uxoris Abisur, Abihail, quæ peperit ei Ahobban et Molid.

** I Chronicles 2:30

Filii autem Nadab fuerunt Saled et Apphaim. Mortuus est autem Saled absque liberis.

** I Chronicles 2:31

Filius vero Apphaim, Jesi : qui Jesi genuit Sesan. Porro Sesan genuit Oholai.

** I Chronicles 2:32

Filii autem Jada fratris Semei : Jether, et Jonathan. Sed et Jether mortuus est absque liberis.

** I Chronicles 2:33

Porro Jonathan genuit Phaleth, et Ziza. Isti fuerunt filii Jerameel.

** I Chronicles 2:34

Sesan autem non habuit filios, sed filias : et servum ægyptium nomine Jeraa.

** I Chronicles 2:35

Deditque ei filiam suam uxorem : quæ peperit ei Ethei.

** I Chronicles 2:36

Ethei autem genuit Nathan, et Nathan genuit Zabad.

** I Chronicles 2:37

Zabad quoque genuit Ophlal, et Ophlal genuit Obed.

** I Chronicles 2:38

Obed genuit Jehu, Jehu genuit Azariam,

** I Chronicles 2:39

Azarias genuit Helles, et Helles genuit Elasa.

** I Chronicles 2:40

Elasa genuit Sisamoi, Sisamoi genuit Sellum,

** I Chronicles 2:41

Sellum genuit Icamiam, Icamia autem genuit Elisama.  

** I Chronicles 2:42

Filii autem Caleb fratris Jerameel : Mesa primogenitus ejus ; ipse est pater Ziph : et filii Maresa patris Hebron.

** I Chronicles 2:43

Porro filii Hebron, Core, et Taphua, et Recem, et Samma.

** I Chronicles 2:44

Samma autem genuit Raham, patrem Jercaam, et Recem genuit Sammai.

** I Chronicles 2:45

Filius Sammai, Maon : et Maon pater Bethsur.

** I Chronicles 2:46

Epha autem concubina Caleb peperit Haran, et Mosa, et Gezez. Porro Haran genuit Gezez.

** I Chronicles 2:47

Filii autem Jahaddai, Regom, et Joathan, et Gesan, et Phalet, et Epha, et Saaph.

** I Chronicles 2:48

Concubina Caleb Maacha, peperit Saber, et Tharana.

** I Chronicles 2:49

Genuit autem Saaph pater Madmena Sue, patrem Machbena et patrem Gabaa. Filia vero Caleb fuit Achsa.

** I Chronicles 2:50

Hi erant filii Caleb, filii Hur primogeniti Ephratha, Sobal pater Cariathiarim.

** I Chronicles 2:51

Salma pater Bethlehem, Hariph pater Bethgader.

** I Chronicles 2:52

Fuerunt autem filii Sobal patris Cariathiarim, qui videbat dimidium requietionum.

** I Chronicles 2:53

Et de cognatione Cariathiarim, Jethrei, et Aphuthei, et Semathei, et Maserei. Ex his egressi sunt Saraitæ, et Esthaolitæ.

** I Chronicles 2:54

Filii Salma, Bethlehem, et Netophathi, coronæ domus Joab, et dimidium requietionis Sarai :

** I Chronicles 2:55

cognationes quoque scribarum habitantium in Jabes, canentes atque resonantes, et in tabernaculis commorantes. Hi sunt Cinæi, qui venerunt de Calore patris domus Rechab.   

* I Chronicles 3

** I Chronicles 3:1

David vero hos habuit filios, qui ei nati sunt in Hebron : primogenitum Amnon ex Achinoam Jezrahelitide, secundum Daniel de Abigail Carmelitide,

** I Chronicles 3:2

tertium Absalom filium Maacha filiæ Tholmai regis Gessur, quartum Adoniam filium Aggith,

** I Chronicles 3:3

quintum Saphathiam ex Abital, sextum Jethraham de Egla uxore sua.

** I Chronicles 3:4

Sex ergo nati sunt ei in Hebron, ubi regnavit septem annis et sex mensibus. Triginta autem et tribus annis regnavit in Jerusalem.

** I Chronicles 3:5

Porro in Jerusalem nati sunt ei filii, Simmaa, et Sobab, et Nathan, et Salomon, quatuor de Bethsabee filia Ammiel :

** I Chronicles 3:6

Jebaar quoque et Elisama,

** I Chronicles 3:7

et Eliphaleth, et Noge, et Nepheg, et Japhia,

** I Chronicles 3:8

necnon Elisama, et Eliada, et Elipheleth, novem :

** I Chronicles 3:9

omnes hi, filii David absque filiis concubinarum : habueruntque sororem Thamar.

** I Chronicles 3:10

Filius autem Salomonis, Roboam : cujus Abia filius genuit Asa. De hoc quoque natus est Josaphat,

** I Chronicles 3:11

pater Joram : qui Joram genuit Ochoziam, ex quo ortus est Joas :

** I Chronicles 3:12

et hujus Amasias filius genuit Azariam. Porro Azariæ filius Joatham

** I Chronicles 3:13

procreavit Achaz patrem Ezechiæ, de quo natus est Manasses.

** I Chronicles 3:14

Sed et Manasses genuit Amon patrem Josiæ.

** I Chronicles 3:15

Filii autem Josiæ fuerunt : primogenitus Johanan, secundus Joakim, tertius Sedecias, quartus Sellum.

** I Chronicles 3:16

De Joakim natus est Jechonias, et Sedecias.

** I Chronicles 3:17

Filii Jechoniæ fuerunt : Asir, Salathiel,

** I Chronicles 3:18

Melchiram, Phadaia, Senneser, et Jecemia, Sama, et Nadabia.

** I Chronicles 3:19

De Phadaia orti sunt Zorobabel et Semei. Zorobabel genuit Mosollam, Hananiam, et Salomith sororem eorum :

** I Chronicles 3:20

Hasaban quoque, et Ohol, et Barachian, et Hasadian, Josabhesed, quinque.

** I Chronicles 3:21

Filius autem Hananiæ, Phaltias pater Jeseiæ, cujus filius Raphaia : hujus quoque filius, Arnan, de quo natus est Obdia, cujus filius fuit Sechenias.

** I Chronicles 3:22

Filius Secheniæ, Semeia : cujus filii Hattus, et Jegaal, et Baria, et Naaria, et Saphat, sex numero.

** I Chronicles 3:23

Filius Naariæ, Elioënai, et Ezechias, et Ezricam, tres.

** I Chronicles 3:24

Filii Elioënai, Oduia, et Eliasub, et Pheleia, et Accub, et Johanan, et Dalaia, et Anani, septem.   

* I Chronicles 4

** I Chronicles 4:1

Filii Juda : Phares, Hesron, et Charmi, et Hur, et Sobal.

** I Chronicles 4:2

Raia vero filius Sobal genuit Jahath, de quo nati sunt Ahumai, et Laad : hæ cognationes Sarathi.

** I Chronicles 4:3

Ista quoque stirps Etam : Jezrahel, et Jesema, et Jedebos. Nomen quoque sororis eorum, Asalelphuni.

** I Chronicles 4:4

Phanuel autem pater Gedor, et Ezer pater Hosa : isti sunt filii Hur primogeniti Ephratha patris Bethlehem.

** I Chronicles 4:5

Assur vero patri Thecuæ erant duæ uxores, Halaa et Naara.

** I Chronicles 4:6

Peperit autem ei Naara, Oozam, et Hepher, et Themani, et Ahasthari : isti sunt filii Naara.

** I Chronicles 4:7

Porro filii Halaa, Sereth, Isaar et Ethnan.

** I Chronicles 4:8

Cos autem genuit Anob, et Soboba, et cognationem Aharehel filii Arum.

** I Chronicles 4:9

Fuit autem Jabes inclytus præ fratribus suis, et mater ejus vocavit nomen illius Jabes, dicens : Quia peperi eum in dolore.

** I Chronicles 4:10

Invocavit vero Jabes Deum Israël, dicens : Si benedicens benedixeris mihi, et dilataveris terminos meos, et fuerit manus tua mecum, et feceris me a malitia non opprimi. Et præstitit Deus quæ precatus est.  

** I Chronicles 4:11

Caleb autem frater Sua genuit Mahir, qui fuit pater Esthon.

** I Chronicles 4:12

Porro Esthon genuit Bethrapha, et Phesse, et Tehinna patrem urbis Naas : hi sunt viri Recha.

** I Chronicles 4:13

Filii autem Cenez, Othoniel, et Saraia. Porro filii Othoniel, Hathath, et Maonathi.

** I Chronicles 4:14

Maonathi genuit Ophra, Saraia autem genuit Joab patrem Vallis artificum : ibi quippe artifices erant.

** I Chronicles 4:15

Filii vero Caleb filii Jephone, Hir, et Ela, et Naham. Filii quoque Ela : Cenez.

** I Chronicles 4:16

Filii quoque Jaleleel : Ziph, et Zipha, Thiria, et Asraël.

** I Chronicles 4:17

Et filii Ezra, Jether, et Mered, et Epher, et Jalon, genuitque Mariam, et Sammai, et Jesba patrem Esthamo.

** I Chronicles 4:18

Uxor quoque ejus Judaia, peperit Jared patrem Gedor, et Heber patrem Socho, et Icuthiel patrem Zanoë : hi autem filii Bethiæ filiæ Pharaonis, quam accepit Mered.

** I Chronicles 4:19

Et filii uxoris Odaiæ sororis Naham patris Ceila, Garmi, et Esthamo, qui fuit de Machathi.

** I Chronicles 4:20

Filii quoque Simon, Amnon, et Rinna filius Hanan, et Thilon. Et filii Jesi, Zoheth, et Benzoheth.

** I Chronicles 4:21

Filii Sela, filii Juda : Her pater Lecha, et Laada pater Maresa, et cognationes domus operantium byssum in domo juramenti.

** I Chronicles 4:22

Et qui stare fecit solem, virique Mendacii, et Securus, et Incendens, qui principes fuerunt in Moab, et qui reversi sunt in Lahem : hæc autem verba vetera.

** I Chronicles 4:23

Hi sunt figuli habitantes in plantationibus et in sepibus, apud regem in operibus ejus : commoratique sunt ibi.  

** I Chronicles 4:24

Filii Simeon : Namuel et Jamin, Jarib, Zara, Saul.

** I Chronicles 4:25

Sellum filius ejus, Mapsam filius ejus, Masma filius ejus.

** I Chronicles 4:26

Filii Masma : Hamuel filius ejus, Zachur filius ejus, Semei filius ejus.

** I Chronicles 4:27

Filii Semei sedecim, et filiæ sex : fratres autem ejus non habuerunt filios multos, et universa cognatio non potuit adæquare summam filiorum Juda.

** I Chronicles 4:28

Habitaverunt autem in Bersabee, et Molada, et Hasarsuhal,

** I Chronicles 4:29

et in Bala, et in Asom, et in Tholad,

** I Chronicles 4:30

et in Bathuel, et in Horma, et in Siceleg,

** I Chronicles 4:31

et in Bethmarchaboth, et in Hasarsusim, et in Bethberai, et in Saarim : hæ civitates eorum usque ad regem David.

** I Chronicles 4:32

Villæ quoque eorum : Etam, et Aën, Remmon, et Thochen, et Asan, civitates quinque.

** I Chronicles 4:33

Et universi viculi eorum per circuitum civitatum istarum usque ad Baal : hæc est habitatio eorum, et sedium distributio.

** I Chronicles 4:34

Mosobab quoque et Jemlech, et Josa filius Amasiæ,

** I Chronicles 4:35

et Joël, et Jehu filius Josabiæ filii Saraiæ filii Asiel,

** I Chronicles 4:36

et Elioënai, et Jacoba, et Isuhaia, et Asaia, et Adiel, et Ismiel, et Banaia,

** I Chronicles 4:37

Ziza quoque filius Sephei filii Allon filii Idaia filii Semri filii Samaia.

** I Chronicles 4:38

Isti sunt nominati principes in cognationibus suis, et in domo affinitatum suarum multiplicati sunt vehementer.

** I Chronicles 4:39

Et profecti sunt ut ingrederentur in Gador usque ad orientem vallis, et ut quærerent pascua gregibus suis.

** I Chronicles 4:40

Inveneruntque pascuas uberes, et valde bonas, et terram latissimam et quietam et fertilem, in qua ante habitaverant de stirpe Cham.

** I Chronicles 4:41

Hi ergo venerunt, quos supra descripsimus nominatim, in diebus Ezechiæ regis Juda : et percusserunt tabernacula eorum, et habitatores qui inventi fuerant ibi, et deleverunt eos usque in præsentem diem : habitaveruntque pro eis, quoniam uberrimas pascuas ibidem repererunt.

** I Chronicles 4:42

De filiis quoque Simeon abierunt in montem Seir viri quingenti, habentes principes Phalthiam et Naariam et Raphaiam et Oziel filios Jesi :

** I Chronicles 4:43

et percusserunt reliquias, quæ evadere potuerant, Amalecitarum, et habitaverunt ibi pro eis usque ad diem hanc.   

* I Chronicles 5

** I Chronicles 5:1

Filii quoque Ruben primogeniti Israël. (Ipse quippe fuit primogenitus ejus : sed cum violasset thorum patris sui, data sunt primogenita ejus filiis Joseph filii Israël, et non est ille reputatus in primogenitum.

** I Chronicles 5:2

Porro Judas, qui erat fortissimus inter fratres suos, de stirpe ejus principes germinati sunt : primogenita autem reputata sunt Joseph.)

** I Chronicles 5:3

Filii ergo Ruben primogeniti Israël : Enoch, et Phallu, Esron, et Carmi.

** I Chronicles 5:4

Filii Joël : Samia filius ejus, Gog filius ejus, Semei filius ejus,

** I Chronicles 5:5

Micha filius ejus, Reia filius ejus, Baal filius ejus,

** I Chronicles 5:6

Beera filius ejus, quem captivum duxit Thelgathphalnasar rex Assyriorum, et fuit princeps in tribu Ruben.

** I Chronicles 5:7

Fratres autem ejus, et universa cognatio ejus, quando numerabantur per familias suas, habuerunt principes Jehiel, et Zachariam.

** I Chronicles 5:8

Porro Bala filius Azaz filii Samma filii Joël, ipse habitavit in Aroër usque ad Nebo, et Beelmeon.

** I Chronicles 5:9

Contra orientalem quoque plagam habitavit usque ad introitum eremi, et flumen Euphraten. Multum quippe jumentorum numerum possidebant in terra Galaad.

** I Chronicles 5:10

In diebus autem Saul præliati sunt contra Agareos, et interfecerunt illos, habitaveruntque pro eis in tabernaculis eorum, in omni plaga quæ respicit ad orientem Galaad.  

** I Chronicles 5:11

Filii vero Gad e regione eorum habitaverunt in terra Basan usque Selcha :

** I Chronicles 5:12

Joël in capite, et Saphan secundus : Janai autem et Saphat in Basan.

** I Chronicles 5:13

Fratres vero eorum secundum domos cognationum suarum, Michaël, et Mosollam, et Sebe, et Jorai, et Jachan, et Zie, et Heber, septem.

** I Chronicles 5:14

Hi filii Abihail, filii Huri, filii Jara, filii Galaad, filii Michaël, filii Jesesi, filii Jeddo, filii Buz.

** I Chronicles 5:15

Fratres quoque, filii Abdiel filii Guni, princeps domus in familiis suis.

** I Chronicles 5:16

Et habitaverunt in Galaad, et in Basan, et in viculis ejus, et in cunctis suburbanis Saron, usque ad terminos.

** I Chronicles 5:17

Omnes hi numerati sunt in diebus Joathan regis Juda, et in diebus Jeroboam regis Israël.

** I Chronicles 5:18

Filii Ruben, et Gad, et dimidiæ tribus Manasse, viri bellatores, scuta portantes et gladios, et tendentes arcum, eruditique ad prælia, quadraginta quatuor millia et septingenti sexaginta, procedentes ad pugnam.

** I Chronicles 5:19

Dimicaverunt contra Agareos : Ituræi vero, et Naphis, et Nodab

** I Chronicles 5:20

præbuerunt eis auxilium. Traditique sunt in manus eorum Agarei, et universi qui fuerant cum eis, quia Deum invocaverunt cum præliarentur : et exaudivit eos, eo quod credidissent in eum.

** I Chronicles 5:21

Ceperuntque omnia quæ possederant, camelorum quinquaginta millia, et ovium ducenta quinquaginta millia, et asinos duo millia, et animas hominum centum millia.

** I Chronicles 5:22

Vulnerati autem multi corruerunt : fuit enim bellum Domini. Habitaveruntque pro eis usque ad transmigrationem.  

** I Chronicles 5:23

Filii quoque dimidiæ tribus Manasse possederunt terram a finibus Basan usque Baal, Hermon, et Sanir, et montem Hermon : ingens quippe numerus erat.

** I Chronicles 5:24

Et hi fuerunt principes domus cognationis eorum : Epher, et Jesi, et Eliel, et Ezriel, et Jeremia, et Odoia, et Jediel, viri fortissimi et potentes, et nominati duces in familiis suis.

** I Chronicles 5:25

Reliquerunt autem Deum patrum suorum, et fornicati sunt post deos populorum terræ, quos abstulit Deus coram eis.

** I Chronicles 5:26

Et suscitavit Deus Israël spiritum Phul regis Assyriorum, et spiritum Thelgathphalnasar regis Assur : et transtulit Ruben, et Gad, et dimidiam tribum Manasse, et adduxit eos in Lahela, et in Habor, et Ara, et fluvium Gozan, usque ad diem hanc.   

* I Chronicles 6

** I Chronicles 6:1

Filii Levi : Gerson, Caath, et Merari.

** I Chronicles 6:2

Filii Caath : Amram, Isaar, Hebron, et Oziel.

** I Chronicles 6:3

Filii Amram : Aaron, Moyses, et Maria. Filii Aaron : Nadab et Abiu, Eleazar, et Ithamar.

** I Chronicles 6:4

Eleazar genuit Phinees, et Phinees genuit Abisue.

** I Chronicles 6:5

Abisue vero genuit Bocci, et Bocci genuit Ozi.

** I Chronicles 6:6

Ozi genuit Zaraiam, et Zaraias genuit Meraioth.

** I Chronicles 6:7

Porro Meraioth genuit Amariam, et Amarias genuit Achitob.

** I Chronicles 6:8

Achitob genuit Sadoc, et Sadoc genuit Achimaas,

** I Chronicles 6:9

Achimaas genuit Azariam, Azarias genuit Johanan,

** I Chronicles 6:10

Johanan genuit Azariam : ipse est qui sacerdotio functus est in domo quam ædificavit Salomon in Jerusalem.

** I Chronicles 6:11

Genuit autem Azarias Amariam, et Amarias genuit Achitob,

** I Chronicles 6:12

Achitob genuit Sadoc, et Sadoc genuit Sellum,

** I Chronicles 6:13

Sellum genuit Helciam, et Helcias genuit Azariam,

** I Chronicles 6:14

Azarias genuit Saraiam, et Saraias genuit Josedec.

** I Chronicles 6:15

Porro Josedec egressus est, quando transtulit Dominus Judam et Jerusalem per manus Nabuchodonosor.

** I Chronicles 6:16

Filii ergo Levi : Gersom, Caath, et Merari.

** I Chronicles 6:17

Et hæc nomina filiorum Gersom : Lobni, et Semei.

** I Chronicles 6:18

Filii Caath : Amram, et Isaar, et Hebron, et Oziel.

** I Chronicles 6:19

Filii Merari : Moholi et Musi. Hæ autem cognationes Levi secundum familias eorum.

** I Chronicles 6:20

Gersom : Lobni filius ejus, Jahath filius ejus, Zamma filius ejus,

** I Chronicles 6:21

Joah filius ejus, Addo filius ejus, Zara filius ejus, Jethrai filius ejus.

** I Chronicles 6:22

Filii Caath : Aminadab filius ejus, Core filius ejus, Asir filius ejus,

** I Chronicles 6:23

Elcana filius ejus, Abiasaph filius ejus, Asir filius ejus,

** I Chronicles 6:24

Thahath filius ejus, Uriel filius ejus, Ozias filius ejus, Saul filius ejus.

** I Chronicles 6:25

Filii Elcana, Amasai et Achimoth

** I Chronicles 6:26

et Elcana. Filii Elcana : Sophai filius ejus, Nahath filius ejus,

** I Chronicles 6:27

Eliab filius ejus, Jeroham filius ejus, Elcana filius ejus.

** I Chronicles 6:28

Filii Samuel : primogenitus Vasseni, et Abia.

** I Chronicles 6:29

Filii autem Merari, Moholi : Lobni filius ejus, Semei filius ejus, Oza filius ejus,

** I Chronicles 6:30

Sammaa filius ejus, Haggia filius ejus, Asaia filius ejus.

** I Chronicles 6:31

Isti sunt quos constituit David super cantores domus Domini, ex quo collocata est arca :

** I Chronicles 6:32

et ministrabant coram tabernaculo testimonii, canentes donec ædificaret Salomon domum Domini in Jerusalem : stabant autem juxta ordinem suum in ministerio.

** I Chronicles 6:33

Hi vero sunt qui assistebant cum filiis suis, de filiis Caath, Hemam cantor filius Johel, filii Samuel,

** I Chronicles 6:34

filii Elcana, filii Jeroham, filii Eliel, filii Thohu,

** I Chronicles 6:35

filii Suph, filii Elcana, filii Mahath, filii Amasai,

** I Chronicles 6:36

filii Elcana, filii Johel, filii Azariæ, filii Sophoniæ,

** I Chronicles 6:37

filii Thahath, filii Asir, filii Abiasaph, filii Core,

** I Chronicles 6:38

filii Isaar, filii Caath, filii Levi, filii Israël.

** I Chronicles 6:39

Et frater ejus Asaph, qui stabat a dextris ejus, Asaph filius Barachiæ, filii Samaa,

** I Chronicles 6:40

filii Michaël, filii Basaiæ, filii Melchiæ,

** I Chronicles 6:41

filii Athanai, filii Zara, filii Adaia,

** I Chronicles 6:42

filii Ethan, filii Zamma, filii Semei,

** I Chronicles 6:43

filii Jeth, filii Gersom, filii Levi.

** I Chronicles 6:44

Filii autem Merari fratres eorum, ad sinistram, Ethan filius Cusi, filii Abdi, filii Maloch,

** I Chronicles 6:45

filii Hasabiæ, filii Amasiæ, filii Helciæ,

** I Chronicles 6:46

filii Amasai, filii Boni, filii Somer,

** I Chronicles 6:47

filii Moholi, filii Musi, filii Merari, filii Levi.

** I Chronicles 6:48

Fratres quoque eorum Levitæ, qui ordinati sunt in cunctum ministerium tabernaculi domus Domini.

** I Chronicles 6:49

Aaron vero et filii ejus adolebant incensum super altare holocausti, et super altare thymiamatis, in omne opus Sancti sanctorum : et ut precarentur pro Israël juxta omnia quæ præceperat Moyses servus Dei.

** I Chronicles 6:50

Hi sunt autem filii Aaron : Eleazar filius ejus, Phinees filius ejus, Abisue filius ejus,

** I Chronicles 6:51

Bocci filius ejus, Ozi filius ejus, Zarahia filius ejus,

** I Chronicles 6:52

Meraioth filius ejus, Amarias filius ejus, Achitob filius ejus,

** I Chronicles 6:53

Sadoc filius ejus, Achimaas filius ejus.  

** I Chronicles 6:54

Et hæc habitacula eorum per vicos atque confinia, filiorum scilicet Aaron, juxta cognationes Caathitarum : ipsis enim sorte contigerant.

** I Chronicles 6:55

Dederunt igitur eis Hebron in terra Juda, et suburbana ejus per circuitum :

** I Chronicles 6:56

agros autem civitatis, et villas, Caleb filio Jephone.

** I Chronicles 6:57

Porro filiis Aaron dederunt civitates ad confugiendum Hebron, et Lobna, et suburbana ejus,

** I Chronicles 6:58

Jether quoque, et Esthemo cum suburbanis suis, sed et Helon, et Dabir cum suburbanis suis,

** I Chronicles 6:59

Asan quoque, et Bethsemes, et suburbana earum.

** I Chronicles 6:60

De tribu autem Benjamin, Gabee et suburbana ejus, et Almath cum suburbanis suis, Anathoth quoque cum suburbanis suis : omnes civitates, tredecim, per cognationes suas.

** I Chronicles 6:61

Filiis autem Caath residuis de cognatione sua dederunt ex dimidia tribu Manasse in possessionem urbes decem.

** I Chronicles 6:62

Porro filiis Gersom per cognationes suas de tribu Issachar, et de tribu Aser, et de tribu Nephthali, et de tribu Manasse in Basan, urbes tredecim.

** I Chronicles 6:63

Filiis autem Merari per cognationes suas de tribu Ruben, et de tribu Gad, et de tribu Zabulon, dederunt sorte civitates duodecim.

** I Chronicles 6:64

Dederunt quoque filii Israël Levitis civitates, et suburbana earum :

** I Chronicles 6:65

dederuntque per sortem, ex tribu filiorum Juda, et ex tribu filiorum Simeon, et ex tribu filiorum Benjamin urbes has, quas vocaverunt nominibus suis,

** I Chronicles 6:66

et his, qui erant de cognatione filiorum Caath, fueruntque civitates in terminis eorum de tribu Ephraim.

** I Chronicles 6:67

Dederunt ergo eis urbes ad confugiendum, Sichem cum suburbanis suis in monte Ephraim, et Gazer cum suburbanis suis,

** I Chronicles 6:68

Jecmaam quoque cum suburbanis suis, et Bethoron similiter,

** I Chronicles 6:69

necnon et Helon cum suburbanis suis, et Gethremmon in eumdem modum.

** I Chronicles 6:70

Porro ex dimidia tribu Manasse, Aner et suburbana ejus, Balaam et suburbana ejus : his videlicet, qui de cognatione filiorum Caath reliqui erant.

** I Chronicles 6:71

Filiis autem Gersom de cognatione dimidiæ tribus Manasse, Gaulon in Basan, et suburbana ejus, et Astaroth cum suburbanis suis.

** I Chronicles 6:72

De tribu Issachar, Cedes et suburbanis suis, et Dabereth cum suburbanis suis,

** I Chronicles 6:73

Ramoth quoque et suburbana ejus, et Anem cum suburbanis suis.

** I Chronicles 6:74

De tribu vero Aser : Masal cum suburbanis suis, et Abdon similiter,

** I Chronicles 6:75

Hucac quoque et suburbana ejus, et Rohob cum suburbanis suis.

** I Chronicles 6:76

Porro de tribu Nephthali, Cedes in Galilæa et suburbana ejus, Hamon cum suburbanis suis, et Cariathaim et suburbana ejus.

** I Chronicles 6:77

Filiis autem Merari residuis : de tribu Zabulon, Remmono et suburbana ejus, et Thabor cum suburbanis sus :

** I Chronicles 6:78

trans Jordanem quoque ex adverso Jericho contra orientem Jordanis, de tribu Ruben, Bosor in solitudine cum suburbanis suis, et Jassa cum suburbanis suis,

** I Chronicles 6:79

Cademoth quoque et suburbana ejus, et Mephaat cum suburbanis suis.

** I Chronicles 6:80

Necnon et de tribu Gad, Ramoth in Galaad et suburbana ejus, et Manaim cum suburbanis suis,

** I Chronicles 6:81

sed et Hesebon cum suburbanis suis, et Jezer cum suburbanis suis.   

* I Chronicles 7

** I Chronicles 7:1

Porro filii Issachar : Thola, et Phua, Jasub, et Simeron, quatuor.

** I Chronicles 7:2

Filii Thola : Ozi, et Raphaia, et Jeriel, et Jemai, et Jebsem, et Samuel, principes per domos cognationum suarum. De stirpe Thola viri fortissimi numerati sunt in diebus David, viginti duo millia sexcenti.

** I Chronicles 7:3

Filii Ozi : Izrahia, de quo nati sunt Michaël, et Obadia, et Joël, et Jesia, quinque omnes principes.

** I Chronicles 7:4

Cumque eis per familias et populos suos, accincti ad prælium, viri fortissimi, triginta sex millia : multas enim habuerunt uxores, et filios.

** I Chronicles 7:5

Fratres quoque eorum per omnem cognationem Issachar robustissimi ad pugnandum, octoginta septem millia numerati sunt.  

** I Chronicles 7:6

Filii Benjamin : Bela, et Bechor, et Jadihel, tres.

** I Chronicles 7:7

Filii Bela : Esbon, et Ozi, et Oziel, et Jerimoth, et Urai, quinque principes familiarum, et ad pugnandum robustissimi : numerus autem eorum, viginti duo millia et triginta quatuor.

** I Chronicles 7:8

Porro filii Bechor : Zamira, et Joas, et Eliezer, et Elioënai, et Amri, et Jerimoth, et Abia, et Anathoth, et Almath : omnes hi filii Bechor.

** I Chronicles 7:9

Numerati sunt autem per familias suas principes cognationum suarum ad bella fortissimi, viginti millia et ducenti.

** I Chronicles 7:10

Porro filii Jadihel : Balan. Filii autem Balan : Jehus, et Benjamin, et Aod, et Chanana, et Zethan, et Tharsis, et Ahisahar :

** I Chronicles 7:11

omnes hi filii Jadihel, principes cognationum suarum viri fortissimi, decem et septem millia et ducenti ad prælium procedentes.

** I Chronicles 7:12

Sepham quoque et Hapham filii Hir : et Hasim filii Aher.  

** I Chronicles 7:13

Filii autem Nephthali : Jaziel, et Guni, et Jeser, et Sellum, filii Bala.  

** I Chronicles 7:14

Porro filius Manasse, Esriel : concubinaque ejus Syra peperit Machir patrem Galaad.

** I Chronicles 7:15

Machir autem accepit uxores filiis suis Happhim, et Saphan : et habuit sororem nomine Maacha : nomen autem secundi, Salphaad, natæque sunt Salphaad filiæ.

** I Chronicles 7:16

Et peperit Maacha uxor Machir filium, vocavitque nomen ejus Phares : porro nomen fratris ejus, Sares : et filii ejus, Ulam, et Recen.

** I Chronicles 7:17

Filius autem Ulam, Badan : hi sunt filii Galaad, filii Machir, filii Manasse.

** I Chronicles 7:18

Soror autem ejus Regina peperit Virum decorum, et Abiezer, et Mohola.

** I Chronicles 7:19

Erant autem filii Semida, Ahin, et Sechem, et Leci, et Aniam.  

** I Chronicles 7:20

Filii autem Ephraim : Suthala, Bared filius ejus, Thahath filius ejus, Elada filius ejus, Thahath filius ejus, hujus filius Zabad,

** I Chronicles 7:21

et hujus filius Suthula, et hujus filius Ezer et Elad : occiderunt autem eos viri Geth indigenæ, quia descenderant ut invaderent possessiones eorum.

** I Chronicles 7:22

Luxit igitur Ephraim pater eorum multis diebus, et venerunt fratres ejus ut consolarentur eum.

** I Chronicles 7:23

Ingressusque est ad uxorem suam : quæ concepit, et peperit filium, et vocavit nomen ejus Beria, eo quod in malis domus ejus ortus esset :

** I Chronicles 7:24

filia autem ejus fuit Sara, quæ ædificavit Bethoron inferiorem et superiorem, et Ozensara.

** I Chronicles 7:25

Porro filius ejus Rapha, et Reseph, et Thale, de quo natus est Thaan,

** I Chronicles 7:26

qui genuit Laadan : hujus quoque filius Ammiud, qui genuit Elisama,

** I Chronicles 7:27

de quo ortus est Nun, qui habuit filium Josue.

** I Chronicles 7:28

Possessio autem eorum et habitatio, Bethel cum filiabus suis, et contra orientem Noran, ad occidentalem plagam Gazer et filiæ ejus, Sichem quoque cum filiabus suis, usque ad Aza cum filiabus ejus.

** I Chronicles 7:29

Juxta filios quoque Manasse, Bethsan et filias ejus, Thanach et filias ejus, Mageddo et filias ejus, Dor et filias ejus : in his habitaverunt filii Joseph, filii Israël.  

** I Chronicles 7:30

Filii Aser : Jemna, et Jesua, et Jessui, et Baria, et Sara soror eorum.

** I Chronicles 7:31

Filii autem Baria : Heber, et Melchiel : ipse est pater Barsaith.

** I Chronicles 7:32

Heber autem genuit Jephlat, et Somer, et Hotham, et Suaa sororem eorum.

** I Chronicles 7:33

Filii Jephlat : Phosech, et Chamaal, et Asoth : hi filii Jephlat.

** I Chronicles 7:34

Porro filii Somer : Ahi, et Roaga, et Haba, et Aram.

** I Chronicles 7:35

Filii autem Helem fratris ejus : Supha, et Jemna, et Selles, et Amal.

** I Chronicles 7:36

Filii Supha : Sue, Harnapher, et Sual, et Beri, et Jamra,

** I Chronicles 7:37

Bosor, et Hod, et Samma, et Salusa, et Jethran, et Bera.

** I Chronicles 7:38

Filii Jether : Jephone, et Phaspha, et Ara.

** I Chronicles 7:39

Filii autem Olla : Aree, et Haniel, et Resia.

** I Chronicles 7:40

Omnes hi filii Aser, principes cognationum, electi atque fortissimi duces ducum : numerus autem eorum ætatis quæ apta esset ad bellum, viginti sex millia.   

* I Chronicles 8

** I Chronicles 8:1

Benjamin autem genuit Bale primogenitum suum, Asbel secundum, Ahara tertium,

** I Chronicles 8:2

Nohaa quartum, et Rapha quintum.

** I Chronicles 8:3

Fueruntque filii Bale : Addar, et Gera, et Abiud,

** I Chronicles 8:4

Abisue quoque et Naaman, et Ahoë,

** I Chronicles 8:5

sed et Gera, et Sephuphan, et Huram.

** I Chronicles 8:6

Hi sunt filii Ahod, principes cognationum habitantium in Gabaa, qui translati sunt in Manahath.

** I Chronicles 8:7

Naaman autem, et Achia, et Gera, ipse transtulit eos, et genuit Osa, et Ahiud.

** I Chronicles 8:8

Porro Saharaim genuit in regione Moab, postquam dimisit Husim et Bara uxores suas.

** I Chronicles 8:9

Genuit autem de Hodes uxore sua Jobab, et Sebia, et Mosa, et Molchom,

** I Chronicles 8:10

Jehus quoque, et Sechia, et Marma : hi sunt filii ejus principes in familiis suis.

** I Chronicles 8:11

Mehusim vero genuit Abitob et Elphaal.

** I Chronicles 8:12

Porro filii Elphaal : Heber, et Misaam, et Samad : hic ædificavit Ono, et Lod, et filias ejus.

** I Chronicles 8:13

Baria autem et Sama principes cognationum habitantium in Ajalon : hi fugaverunt habitatores Geth.

** I Chronicles 8:14

Et Ahio, et Sesac, et Jerimoth,

** I Chronicles 8:15

et Zabadia, et Arod, et Heder,

** I Chronicles 8:16

Michaël quoque, et Jespha, et Joha filii Baria.

** I Chronicles 8:17

Et Zabadia, et Mosollam, et Hezeci, et Heber,

** I Chronicles 8:18

et Jesamari, et Jezlia, et Jobab filii Elphaal,

** I Chronicles 8:19

et Jacim, et Zechri, et Zabdi,

** I Chronicles 8:20

et Elioënai, et Selethai, et Eliel,

** I Chronicles 8:21

et Adaia, et Baraia, et Samarath, filii Semei.

** I Chronicles 8:22

Et Jespham, et Heber, et Eliel,

** I Chronicles 8:23

et Abdon, et Zechri, et Hanan,

** I Chronicles 8:24

et Hanania, et Ælam, et Anathothia,

** I Chronicles 8:25

et Jephdaia, et Phanuel, filii Sesac.

** I Chronicles 8:26

Et Samsari, et Sohoria, et Otholia,

** I Chronicles 8:27

et Jersia, et Elia, et Zechri, filii Jeroham.

** I Chronicles 8:28

Hi patriarchæ, et cognationum principes, qui habitaverunt in Jerusalem.

** I Chronicles 8:29

In Gabaon autem habitaverunt Abigabaon, et nomen uxoris ejus Maacha :

** I Chronicles 8:30

filiusque ejus primogenitus Abdon, et Sur, et Cis, et Baal, et Nadab,

** I Chronicles 8:31

Gedor quoque, et Ahio, et Zacher, et Macelloth :

** I Chronicles 8:32

et Macelloth genuit Samaa : habitaveruntque ex adverso fratrum suorum in Jerusalem cum fratribus suis.  

** I Chronicles 8:33

Ner autem genuit Cis, et Cis genuit Saul. Porro Saul genuit Jonathan, et Melchisua, et Abinadab, et Esbaal.

** I Chronicles 8:34

Filius autem Jonathan, Meribbaal : et Meribbaal genuit Micha.

** I Chronicles 8:35

Filii Micha, Phithon, et Melech, et Tharaa, et Ahaz.

** I Chronicles 8:36

Et Ahaz genuit Joada, et Joada genuit Alamath, et Azmoth, et Zamri : porro Zamri genuit Mosa,

** I Chronicles 8:37

et Mosa genuit Banaa, cujus filius fuit Rapha, de quo ortus est Elasa, qui genuit Asel.

** I Chronicles 8:38

Porro Asel sex filii fuerunt his nominibus : Ezricam, Bocru, Ismahel, Saria, Obdia, et Hanan : omnes hi filii Asel.

** I Chronicles 8:39

Filii autem Esec fratris ejus, Ulam primogenitus, et Jehus secundus, et Eliphalet tertius.

** I Chronicles 8:40

Fueruntque filii Ulam viri robustissimi, et magno robore tendentes arcum : et multos habentes filios ac nepotes, usque ad centum quinquaginta. Omnes hi filii Benjamin.   

* I Chronicles 9

** I Chronicles 9:1

Universus ergo Israël dinumeratus est, et summa eorum scripta est in libro regum Israël et Juda : translatique sunt in Babylonem propter delictum suum.

** I Chronicles 9:2

Qui autem habitaverunt primi in possessionibus et in urbibus suis : Israël, et sacerdotes, et Levitæ, et Nathinæi.

** I Chronicles 9:3

Commorati sunt in Jerusalem de filiis Juda, et de filiis Benjamin, de filiis quoque Ephraim, et Manasse.

** I Chronicles 9:4

Othei filius Ammiud, filii Amri, filii Omrai, filii Bonni, de filiis Phares filii Juda.

** I Chronicles 9:5

Et de Siloni : Asaia primogenitus, et filii ejus.

** I Chronicles 9:6

De filiis autem Zara, Jehuel, et fratres eorum, sexcenti nonaginta.

** I Chronicles 9:7

Porro de filiis Benjamin : Salo filius Mosollam, filii Oduia, filii Asana,

** I Chronicles 9:8

et Jobania filius Jeroham, et Ela filius Ozi, filii Mochori, et Mosollam filius Saphatiæ, filii Rahuel, filii Jebaniæ,

** I Chronicles 9:9

et fratres eorum per familias suas, nongenti quinquaginta sex. Omnes hi principes cognationum per domos patrum suorum.  

** I Chronicles 9:10

De sacerdotibus autem : Jedaia, Jojarib, et Jachin :

** I Chronicles 9:11

Azarias quoque filius Helciæ, filii Mosollam, filii Sadoc, filii Maraioth, filii Achitob, pontifex domus Dei.

** I Chronicles 9:12

Porro Adaias filius Jeroham, filii Phassur, filii Melchiæ, et Maasai filius Adiel filii Jezra, filii Mosollam, filii Mosollamith, filii Emmer.

** I Chronicles 9:13

Fratres quoque eorum principes per familias suas, mille septingenti sexaginta, fortissimi robore ad faciendum opus ministerii in domo Dei.  

** I Chronicles 9:14

De Levitis autem : Semeia filius Hassub filii Ezricam, filii Hasebia de filiis Merari.

** I Chronicles 9:15

Bacbacar quoque carpentarius, et Galal, et Mathania filius Micha, filii Zechri, filii Asaph :

** I Chronicles 9:16

et Obdia filius Semeiæ, filii Galal, filii Idithun : et Barachia filius Asa, filii Elcana, qui habitavit in atriis Netophati.

** I Chronicles 9:17

Janitores autem : Sellum, et Accub, et Telmon, et Ahimam : et frater eorum Sellum princeps,

** I Chronicles 9:18

usque ad illud tempus, in porta regis ad orientem, observabant per vices suas de filiis Levi.

** I Chronicles 9:19

Sellum vero filius Core filii Abiasaph, filii Core, cum fratribus suis, et domo patris sui, hi sunt Coritæ super opera ministerii, custodes vestibulorum tabernaculi : et familiæ eorum per vices castrorum Domini custodientes introitum.

** I Chronicles 9:20

Phinees autem filius Eleazari erat dux eorum coram Domino.

** I Chronicles 9:21

Porro Zacharias filius Mosollamia, janitor portæ tabernaculi testimonii.

** I Chronicles 9:22

Omnes hi electi in ostiarios per portas, ducenti duodecim : et descripti in villis propriis, quos constituerunt David, et Samuel videns, in fide sua,

** I Chronicles 9:23

tam ipsos quam filios eorum, in ostiis domus Domini et in tabernaculo vicibus suis.

** I Chronicles 9:24

Per quatuor ventos erant ostiarii : id est, ad orientem, et ad occidentem, et ad aquilonem, et ad austrum.

** I Chronicles 9:25

Fratres autem eorum in viculis morabantur, et veniebant in sabbatis suis de tempore usque ad tempus.

** I Chronicles 9:26

His quatuor Levitis creditus erat omnis numerus janitorum, et erant super exedras et thesauros domus Domini.

** I Chronicles 9:27

Per gyrum quoque templi Domini morabantur in custodiis suis : ut cum tempus fuisset, ipsi mane aperirent fores.  

** I Chronicles 9:28

De horum genere erant et super vasa ministerii : ad numerum enim et inferebantur vasa, et efferebantur.

** I Chronicles 9:29

De ipsis et qui credita habebant utensilia sanctuarii, præerant similæ, et vino, et oleo, et thuri, et aromatibus.

** I Chronicles 9:30

Filii autem sacerdotum unguenta ex aromatibus conficiebant.

** I Chronicles 9:31

Et Mathathias Levites primogenitus Sellum Coritæ, præfectus erat eorum quæ in sartagine frigebantur.

** I Chronicles 9:32

Porro de filiis Caath fratribus eorum, super panes erant propositionis, ut semper novos per singula sabbata præpararent.

** I Chronicles 9:33

Hi sunt principes cantorum per familias Levitarum, qui in exedris morabantur, ut die ac nocte jugiter suo ministerio deservirent.

** I Chronicles 9:34

Capita Levitarum, per familias suas principes, manserunt in Jerusalem.

** I Chronicles 9:35

In Gabaon autem commorati sunt pater Gabaon Jehiel, et nomen uxoris ejus Maacha.

** I Chronicles 9:36

Filius primogenitus ejus Abdon, et Sur, et Cis, et Baal, et Ner, et Nadab,

** I Chronicles 9:37

Gedor quoque, et Ahio, et Zacharias, et Macelloth.

** I Chronicles 9:38

Porro Macelloth genuit Samaan : isti habitaverunt e regione fratrum suorum in Jerusalem cum fratribus suis.  

** I Chronicles 9:39

Ner autem genuit Cis, et Cis genuit Saul, et Saul genuit Jonathan, et Melchisua, et Abinadab, et Esbaal.

** I Chronicles 9:40

Filius autem Jonathan, Meribbaal : et Meribbaal genuit Micha.

** I Chronicles 9:41

Porro filii Micha, Phithon, et Melech, et Tharaa, et Ahaz.

** I Chronicles 9:42

Ahaz autem genuit Jara, et Jara genuit Alamath, et Azmoth, et Zamri. Zamri autem genuit Mosa.

** I Chronicles 9:43

Mosa vero genuit Banaa, cujus filius Raphaia, genuit Elasa, de quo ortus est Asel.

** I Chronicles 9:44

Porro Asel sex filios habuit, his nominibus : Ezricam, Bocru, Ismahel, Saria, Obdia, Hanan : hi sunt filii Asel.   

* I Chronicles 10

** I Chronicles 10:1

Philisthiim autem pugnabant contra Israël, fugeruntque viri Israël Palæsthinos, et ceciderunt vulnerati in monte Gelboë.

** I Chronicles 10:2

Cumque appropinquassent Philisthæi, persequentes Saul et filios ejus, percusserunt Jonathan, et Abinadab, et Melchisua filios Saul.

** I Chronicles 10:3

Et aggravatum est prælium contra Saul, inveneruntque eum sagittarii, et vulneraverunt jaculis.

** I Chronicles 10:4

Et dixit Saul ad armigerum suum : Evagina gladium tuum, et interfice me, ne forte veniant incircumcisi isti, et illudant mihi. Noluit autem armiger ejus hoc facere, timore perterritus : arripuit ergo Saul ensem, et irruit in eum.

** I Chronicles 10:5

Quod cum vidisset armiger ejus, videlicet mortuum esse Saul, irruit etiam ipse in gladium suum, et mortuus est.

** I Chronicles 10:6

Interiit ergo Saul : et tres filii ejus, et omnis domus illius pariter concidit.

** I Chronicles 10:7

Quod cum vidissent viri Israël qui habitabant in campestribus, fugerunt : et Saul ac filiis ejus mortuis, dereliquerunt urbes suas, et huc illucque dispersi sunt : veneruntque Philisthiim, et habitaverunt in eis.

** I Chronicles 10:8

Die igitur altero detrahentes Philisthiim spolia cæsorum, invenerunt Saul et filios ejus jacentes in monte Gelboë.

** I Chronicles 10:9

Cumque spoliassent eum, et amputassent caput, armisque nudassent, miserunt in terram suam, ut circumferretur, et ostenderetur idolorum templis, et populis :

** I Chronicles 10:10

arma autem ejus consecraverunt in fano dei sui, et caput affixerunt in templo Dagon.

** I Chronicles 10:11

Hoc cum audissent viri Jabes Galaad, omnia scilicet quæ Philisthiim fecerant super Saul,

** I Chronicles 10:12

consurrexerunt singuli virorum fortium, et tulerunt cadavera Saul et filiorum ejus : attuleruntque ea in Jabes, et sepelierunt ossa eorum subter quercum, quæ erat in Jabes, et jejunaverunt septem diebus.

** I Chronicles 10:13

Mortuus est ergo Saul propter iniquitates suas, eo quod prævaricatus sit mandatum Domini quod præceperat, et non custodierit illud : sed insuper etiam pythonissam consuluerit,

** I Chronicles 10:14

nec speraverit in Domino : propter quod interfecit eum, et transtulit regnum ejus ad David filium Isai.   

* I Chronicles 11

** I Chronicles 11:1

Congregatus est igitur omnis Israël ad David in Hebron, dicens : Os tuum sumus, et caro tua.

** I Chronicles 11:2

Heri quoque et nudiustertius cum adhuc regnaret Saul, tu eras qui educebas et introducebas Israël : tibi enim dixit Dominus Deus tuus : Tu pasces populum meum Israël, et tu eris princeps super eum.

** I Chronicles 11:3

Venerunt ergo omnes majores natu Israël ad regem in Hebron, et iniit David cum eis fœdus coram Domino : unxeruntque eum regem super Israël, juxta sermonem Domini quem locutus est in manu Samuel.  

** I Chronicles 11:4

Abiit quoque David et omnis Israël in Jerusalem : hæc est Jebus, ubi erant Jebusæi habitatores terræ.

** I Chronicles 11:5

Dixeruntque qui habitabant in Jebus ad David : Non ingredieris huc. Porro David cepit arcem Sion, quæ est civitas David,

** I Chronicles 11:6

dixitque : Omnis qui percusserit Jebusæum in primis, erit princeps et dux. Ascendit igitur primus Joab filius Sarviæ, et factus est princeps.

** I Chronicles 11:7

Habitavit autem David in arce, et idcirco appellata est civitas David.

** I Chronicles 11:8

Ædificavitque urbem in circuitu a Mello usque ad gyrum ; Joab autem reliqua urbis exstruxit.

** I Chronicles 11:9

Proficiebatque David vadens et crescens, et Dominus exercituum erat cum eo.  

** I Chronicles 11:10

Hi principes virorum fortium David, qui adjuverunt eum ut rex fieret super omnem Israël, juxta verbum Domini quod locutus est ad Israël.

** I Chronicles 11:11

Et iste numerus robustorum David : Jesbaam filius Hachamoni princeps inter triginta : iste levavit hastam suam super trecentos vulneratos una vice.

** I Chronicles 11:12

Et post eum Eleazar filius patrui ejus Ahohites, qui erat inter tres potentes.

** I Chronicles 11:13

Iste fuit cum David in Phesdomim, quando Philisthiim congregati sunt ad locum illum in prælium : et erat ager regionis illius plenus hordeo, fugeratque populus a facie Philisthinorum.

** I Chronicles 11:14

Hi steterunt in medio agri, et defenderunt eum : cumque percussissent Philisthæos, dedit Dominus salutem magnam populo suo.

** I Chronicles 11:15

Descenderunt autem tres de triginta principibus ad petram, in qua erat David, ad speluncam Odollam, quando Philisthiim fuerant castrametati in valle Raphaim.

** I Chronicles 11:16

Porro David erat in præsidio, et statio Philisthinorum in Bethlehem.

** I Chronicles 11:17

Desideravit igitur David, et dixit : O si quis daret mihi aquam de cisterna Bethlehem, quæ est in porta !

** I Chronicles 11:18

Tres ergo isti per media castra Philisthinorum perrexerunt, et hauserunt aquam de cisterna Bethlehem quæ erat in porta, et attulerunt ad David ut biberet. Qui noluit, sed magis libavit illam Domino,

** I Chronicles 11:19

dicens : Absit ut in conspectu Dei mei hoc faciam, et sanguinem istorum virorum bibam : quia in periculo animarum suarum attulerunt mihi aquam. Et ob hanc causam noluit bibere : hæc fecerunt tres robustissimi.

** I Chronicles 11:20

Abisai quoque frater Joab ipse erat princeps trium, et ipse levavit hastam suam contra trecentos vulneratos, et ipse erat inter tres nominatissimus,

** I Chronicles 11:21

et inter tres secundos inclytus, et princeps eorum : verumtamen usque ad tres primos non pervenerat.

** I Chronicles 11:22

Banaias filius Jojadæ viri robustissimi, qui multa opera perpetrarat, de Cabseel : ipse percussit duos ariel Moab, et ipse descendit et interfecit leonem in media cisterna tempore nivis.

** I Chronicles 11:23

Et ipse percussit virum ægyptium, cujus statura erat quinque cubitorum, et habebat lanceam ut liciatorium texentium : descendit igitur ad eum cum virga, et rapuit hastam quam tenebat manu, et interfecit eum hasta sua.

** I Chronicles 11:24

Hæc fecit Banaias filius Jojadæ, qui erat inter tres robustos nominatissimus,

** I Chronicles 11:25

inter triginta primus, verumtamen ad tres usque non pervenerat : posuit autem eum David ad auriculam suam.  

** I Chronicles 11:26

Porro fortissimi viri in exercitu, Asahel frater Joab, et Elchanan filius patrui ejus de Bethlehem,

** I Chronicles 11:27

Sammoth Arorites, Helles Pharonites,

** I Chronicles 11:28

Ira filius Acces Thecuites, Abiezer Anathothites,

** I Chronicles 11:29

Sobbochai Husathites, Ilai Ahohites,

** I Chronicles 11:30

Maharai Netophathites, Heled filius Baana Netophathites,

** I Chronicles 11:31

Ethai filius Ribai de Gabaath filiorum Benjamin, Banaia Pharatonites,

** I Chronicles 11:32

Hurai de torrente Gaas, Abiel Arbathites, Azmoth Bauramites, Eliaba Salabonites.

** I Chronicles 11:33

Filii Assem Gezonites, Jonathan filius Sage Ararites,

** I Chronicles 11:34

Ahiam filius Sachar Ararites,

** I Chronicles 11:35

Eliphal filius Ur,

** I Chronicles 11:36

Hepher Mecherathites, Ahia Phelonites,

** I Chronicles 11:37

Hesro Carmelites, Naarai filius Asbai,

** I Chronicles 11:38

Joël frater Nathan, Mibahar filius Agarai,

** I Chronicles 11:39

Selec Ammonites, Naharai Berothites armiger Joab filii Sarviæ,

** I Chronicles 11:40

Ira Jethræus, Gareb Jethræus,

** I Chronicles 11:41

Urias Hethæus, Zabad filius Oholi,

** I Chronicles 11:42

Adina filius Siza Rubenites princeps Rubenitarum, et cum eo triginta :

** I Chronicles 11:43

Hanan filius Maacha, et Josaphat Mathanites,

** I Chronicles 11:44

Ozia Astarothites, Samma, et Jehiel filii Hotham Arorites,

** I Chronicles 11:45

Jedihel filius Samri, et Joha frater ejus Thosaites,

** I Chronicles 11:46

Eliel Mahumites, et Jeribai, et Josaia filii Elnaëm, et Jethma Moabites, Eliel, et Obed, et Jasiel de Masobia.   

* I Chronicles 12

** I Chronicles 12:1

Hi quoque venerunt ad David in Siceleg, cum adhuc fugeret Saul filium Cis, qui erant fortissimi et egregii pugnatores,

** I Chronicles 12:2

tendentes arcum, et utraque manu fundis saxa jacientes, et dirigentes sagittas, de fratribus Saul ex Benjamin.

** I Chronicles 12:3

Princeps Ahiecer, et Joas filii Samaa Gabaathites, et Jaziel, et Phallet filii Azmoth, et Baracha, et Jehu Anathotites.

** I Chronicles 12:4

Samaias quoque Gabaonites fortissimus inter triginta et super triginta. Jeremias, et Jeheziel, et Johanan, et Jezabad Gaderothites.

** I Chronicles 12:5

Et Eluzai, et Jerimuth, et Baalia, et Samaria, et Saphatia Haruphites.

** I Chronicles 12:6

Elcana, et Jesia, et Azareel, et Joëzer, et Jesbaam de Carehim :

** I Chronicles 12:7

Joëla quoque, et Zabadia filii Jeroham de Gedor.  

** I Chronicles 12:8

Sed et de Gaddi transfugerunt ad David cum lateret in deserto, viri robustissimi, et pugnatores optimi, tenentes clypeum et hastam : facies eorum quasi facies leonis, et veloces quasi capreæ in montibus :

** I Chronicles 12:9

Ezer princeps, Obdias secundus, Eliab tertius,

** I Chronicles 12:10

Masmana quartus, Jeremias quintus,

** I Chronicles 12:11

Ethi sextus, Eliel septimus,

** I Chronicles 12:12

Johanan octavus, Elzebad nonus,

** I Chronicles 12:13

Jeremias decimus, Machbanai undecimus.

** I Chronicles 12:14

Hi de filiis Gad principes exercitus : novissimus centum militibus præerat, et maximus mille.

** I Chronicles 12:15

Isti sunt qui transierunt Jordanem mense primo, quando inundare consuevit super ripas suas : et omnes fugaverunt qui morabantur in vallibus ad orientalem plagam et occidentalem.  

** I Chronicles 12:16

Venerunt autem et de Benjamin et de Juda ad præsidium in quo morabatur David.

** I Chronicles 12:17

Egressusque est David obviam eis, et ait : Si pacifice venistis ad me ut auxiliemini mihi, cor meum jungatur vobis : si autem insidiamini mihi pro adversariis meis, cum ego iniquitatem in manibus non habeam, videat Deus patrum nostrorum, et judicet.

** I Chronicles 12:18

Spiritus vero induit Amasai principem inter triginta, et ait : Tui sumus, o David, et tecum, fili Isai. Pax, pax tibi, et pax adjutoribus tuis : te enim adjuvat Deus tuus. Suscepit ergo eos David, et constituit principes turmæ.  

** I Chronicles 12:19

Porro de Manasse transfugerunt ad David, quando veniebat cum Philisthiim adversus Saul ut pugnaret : et non dimicavit cum eis, quia inito consilio remiserunt eum principes Philisthinorum, dicentes : Periculo capitis nostri revertetur ad dominum suum Saul.

** I Chronicles 12:20

Quando igitur reversus est in Siceleg, transfugerunt ad eum de Manasse, Ednas, et Jozabad, et Jedihel, et Michaël, et Ednas, et Jozabad, et Eliu, et Salathi, principes millium in Manasse.

** I Chronicles 12:21

Hi præbuerunt auxilium David adversus latrunculos : omnes enim erant viri fortissimi, et facti sunt principes in exercitu.

** I Chronicles 12:22

Sed et per singulos dies veniebant ad David ad auxiliandum ei, usque dum fieret grandis numerus, quasi exercitus Dei.  

** I Chronicles 12:23

Iste quoque est numerus principum exercitus qui venerunt ad David cum esset in Hebron, ut transferrent regnum Saul ad eum, juxta verbum Domini.

** I Chronicles 12:24

Filii Juda portantes clypeum et hastam, sex millia octingenti expediti ad prælium.

** I Chronicles 12:25

De filiis Simeon virorum fortissimorum ad pugnandum, septem millia centum.

** I Chronicles 12:26

De filiis Levi, quatuor millia sexcenti.

** I Chronicles 12:27

Jojoda quoque princeps de stirpe Aaron, et cum eo tria millia septingenti.

** I Chronicles 12:28

Sadoc etiam puer egregiæ indolis, et domus patris ejus, principes viginti duo.

** I Chronicles 12:29

De filiis autem Benjamin fratribus Saul, tria millia : magna enim pars eorum adhuc sequebatur domum Saul.

** I Chronicles 12:30

Porro de filiis Ephraim viginti millia octingenti, fortissimi robore, viri nominati in cognationibus suis.

** I Chronicles 12:31

Et ex dimidia tribu Manasse, decem et octo millia, singuli per nomina sua, venerunt ut constituerent regem David.

** I Chronicles 12:32

De filiis quoque Issachar viri eruditi, qui noverant singula tempora ad præcipiendum quid facere deberet Israël, principes ducenti : omnis autem reliqua tribus eorum consilium sequebatur.

** I Chronicles 12:33

Porro de Zabulon qui egrediebantur ad prælium, et stabant in acie instructi armis bellicis, quinquaginta millia venerunt in auxilium, non in corde duplici.

** I Chronicles 12:34

Et de Nephthali, principes mille, et cum eis instructi clypeo et hasta, triginta et septem millia.

** I Chronicles 12:35

De Dan etiam præparati ad prælium, viginti octo millia sexcenti.

** I Chronicles 12:36

Et de Aser egredientes ad pugnam, et in acie provocantes, quadraginta millia.

** I Chronicles 12:37

Trans Jordanem autem de filiis Ruben, et de Gad, et dimidia parte tribus Manasse, instructi armis bellicis, centum viginti millia.

** I Chronicles 12:38

Omnes isti viri bellatores expediti ad pugnandum, corde perfecto venerunt in Hebron, ut constituerent regem David super universum Israël : sed et omnes reliqui ex Israël uno corde erant, ut rex fieret David.

** I Chronicles 12:39

Fueruntque ibi apud David tribus diebus comedentes et bibentes : præparaverant enim eis fratres sui.

** I Chronicles 12:40

Sed et qui juxta eos erant, usque ad Issachar, et Zabulon, et Nephthali, afferebant panes in asinis, et camelis, et mulis, et bobus ad vescendum : farinam, palathas, uvam passam, vinum, oleum, boves, arietes ad omnem copiam : gaudium quippe erat in Israël.   

* I Chronicles 13

** I Chronicles 13:1

Iniit autem consilium David cum tribunis, et centurionibus, et universis principibus,

** I Chronicles 13:2

et ait ad omnem cœtum Israël : Si placet vobis, et a Domino Deo nostro egreditur sermo quem loquor, mittamus ad fratres nostros reliquos in universas regiones Israël, et ad sacerdotes et Levitas qui habitant in suburbanis urbium, ut congregentur ad nos,

** I Chronicles 13:3

et reducamus arcam Dei nostri ad nos : non enim requisivimus eam in diebus Saul.

** I Chronicles 13:4

Et respondit universa multitudo ut ita fieret : placuerat enim sermo omni populo.

** I Chronicles 13:5

Congregavit ergo David cunctum Israël, a Sihor Ægypti usque dum ingrediaris Emath, ut adduceret arcam Dei de Cariathiarim.

** I Chronicles 13:6

Et ascendit David, et omnis vir Israël, ad collem Cariathiarim, qui est in Juda, ut afferret inde arcam Domini Dei sedentis super cherubim, ubi invocatum est nomen ejus.

** I Chronicles 13:7

Imposueruntque arcam Dei super plaustrum novum, de domo Abinadab : Oza autem, et frater ejus minabant plaustrum.

** I Chronicles 13:8

Porro David, et universus Israël, ludebant coram Deo omni virtute in canticis, et in citharis, et psalteriis, et tympanis, et cymbalis, et tubis.

** I Chronicles 13:9

Cum autem pervenisset ad aream Chidon, tetendit Oza manum suam, ut sustentaret arcam : bos quippe lasciviens paululum inclinaverat eam.

** I Chronicles 13:10

Iratus est itaque Dominus contra Ozam, et percussit eum, eo quod tetigisset arcam : et mortuus est ibi coram Domino.

** I Chronicles 13:11

Contristatusque est David, eo quod divisisset Dominus Ozam : vocavitque locum illum Divisio Ozæ, usque in præsentem diem.

** I Chronicles 13:12

Et timuit Deum tunc temporis, dicens : Quomodo possum ad me introducere arcam Dei ?

** I Chronicles 13:13

et ob hanc causam non adduxit eam ad se, hoc est, in civitatem David, sed avertit in domum Obededom Gethæi.

** I Chronicles 13:14

Mansit ergo arca Dei in domo Obededom tribus mensibus : et benedixit Dominus domui ejus, et omnibus quæ habebat.   

* I Chronicles 14

** I Chronicles 14:1

Misit quoque Hiram rex Tyri nuntios ad David, et ligna cedrina, et artifices parietum, lignorumque, ut ædificarent ei domum.

** I Chronicles 14:2

Cognovitque David quod confirmasset eum Dominus in regem super Israël, et sublevatum esset regnum suum super populum ejus Israël.

** I Chronicles 14:3

Accepit quoque David alias uxores in Jerusalem, genuitque filios et filias.

** I Chronicles 14:4

Et hæc nomina eorum, qui nati sunt ei in Jerusalem : Samua, et Sobab, Nathan, et Salomon,

** I Chronicles 14:5

Jebahar, et Elisua, et Eliphalet,

** I Chronicles 14:6

Noga quoque, et Napheg, et Japhia,

** I Chronicles 14:7

Elisama, et Baaliada, et Eliphalet.  

** I Chronicles 14:8

Audientes autem Philisthiim eo quod unctus esset David regem super universum Israël, ascenderunt omnes ut quærerent eum : quod cum audisset David, egressus est obviam eis.

** I Chronicles 14:9

Porro Philisthiim venientes, diffusi sunt in valle Raphaim.

** I Chronicles 14:10

Consuluitque David Dominum, dicens : Si ascendam ad Philisthæos, et si trades eos in manu mea ? Et dixit ei Dominus : Ascende, et tradam eos in manu tua.

** I Chronicles 14:11

Cumque illi ascendissent in Baalpharasim, percussit eos ibi David, et dixit : Divisit Deus inimicos meos per manum meam, sicut dividuntur aquæ : et idcirco vocatum est nomen illius loci Baalpharasim.

** I Chronicles 14:12

Dereliqueruntque ibi deos suos, quos David jussit exuri.

** I Chronicles 14:13

Alia etiam vice Philisthiim irruerunt, et diffusi sunt in valle.

** I Chronicles 14:14

Consuluitque rursum David Deum, et dixit ei Deus : Non ascendas post eos : recede ab eis, et venies contra illos ex adverso pyrorum.

** I Chronicles 14:15

Cumque audieris sonitum gradientis in cacumine pyrorum, tunc egredieris ad bellum : egressus est enim Deus ante te, ut percutiat castra Philisthiim.

** I Chronicles 14:16

Fecit ergo David sicut præceperat ei Deus, et percussit castra Philisthinorum, de Gabaon usque Gazera.

** I Chronicles 14:17

Divulgatumque est nomen David in universis regionibus, et Dominus dedit pavorem ejus super omnes gentes.   

* I Chronicles 15

** I Chronicles 15:1

Fecit quoque sibi domos in civitate David : et ædificavit locum arcæ Dei, tetenditque ei tabernaculum.

** I Chronicles 15:2

Tunc dixit David : Illicitum est ut a quocumque portetur arca Dei nisi a Levitis, quos elegit Dominus ad portandum eam, et ad ministrandum sibi usque in æternum.

** I Chronicles 15:3

Congregavitque universum Israël in Jerusalem, ut afferretur arca Dei in locum suum, quem præparaverat ei :

** I Chronicles 15:4

necnon et filios Aaron, et Levitas.

** I Chronicles 15:5

De filiis Caath, Uriel princeps fuit, et fratres ejus centum viginti.

** I Chronicles 15:6

De filiis Merari, Asaia princeps : et fratres ejus ducenti viginti.

** I Chronicles 15:7

De filiis Gersom, Joël princeps : et fratres ejus centum triginta.

** I Chronicles 15:8

De filiis Elisaphan, Semeias princeps : et fratres ejus ducenti.

** I Chronicles 15:9

De filiis Hebron, Eliel princeps : et fratres ejus octoginta.

** I Chronicles 15:10

De filiis Oziel, Aminadab princeps : et fratres ejus centum duodecim.

** I Chronicles 15:11

Vocavitque David Sadoc et Abiathar sacerdotes, et Levitas, Uriel, Asaiam, Joël, Semeiam, Eliel, et Aminadab :

** I Chronicles 15:12

et dixit ad eos : Vos, qui estis principes familiarum Leviticarum, sanctificamini cum fratribus vestris, et afferte arcam Domini Dei Israël ad locum qui ei præparatus est :

** I Chronicles 15:13

ne ut a principio, quia non eratis præsentes, percussit nos Dominus ; sic et nunc fiat, illicitum quid nobis agentibus.

** I Chronicles 15:14

Sanctificati sunt ergo sacerdotes et Levitæ ut portarent arcam Domini Dei Israël.

** I Chronicles 15:15

Et tulerunt filii Levi arcam Dei, sicut præceperat Moyses juxta verbum Domini, humeris suis in vectibus.

** I Chronicles 15:16

Dixitque David principibus Levitarum, ut constituerent de fratribus suis cantores in organis musicorum, nablis videlicet, et lyris, et cymbalis, ut resonaret in excelsis sonitus lætitiæ.

** I Chronicles 15:17

Constitueruntque Levitas : Heman filium Joël, et de fratribus ejus Asaph filium Barachiæ : de filiis vero Merari, fratribus eorum : Ethan filium Casaiæ.

** I Chronicles 15:18

Et cum eis fratres eorum : in secundo ordine, Zachariam, et Ben, et Jaziel, et Semiramoth, et Jahiel, et Ani, Eliab, et Banaiam, et Maasiam, et Mathathiam, et Eliphalu, et Maceniam, et Obededom, et Jehiel, janitores.

** I Chronicles 15:19

Porro cantores, Heman, Asaph, et Ethan, in cymbalis æneis concrepantes.

** I Chronicles 15:20

Zacharias autem, et Oziel, et Semiramoth, et Jahiel, et Ani, et Eliab, et Maasias, et Banaias in nablis arcana cantabant.

** I Chronicles 15:21

Porro Mathathias, et Eliphalu, et Macenias, et Obededom, et Jehiel, et Ozaziu, in citharis pro octava canebant epinicion.

** I Chronicles 15:22

Chonenias autem princeps Levitarum, prophetiæ præerat, ad præcinendam melodiam : erat quippe valde sapiens.

** I Chronicles 15:23

Et Barachias, et Elcana, janitores arcæ.

** I Chronicles 15:24

Porro Sebenias, et Josaphat, et Nathanaël, et Amasai, et Zacharias, et Banaias, et Eliezer sacerdotes, clangebant tubis coram arca Dei : et Obededom et Jehias erant janitores arcæ.  

** I Chronicles 15:25

Igitur David, et omnes majores natu Israël, et tribuni, ierunt ad deportandam arcam fœderis Domini de domo Obededom cum lætitia.

** I Chronicles 15:26

Cumque adjuvisset Deus Levitas qui portabant arcam fœderis Domini, immolabantur septem tauri, et septem arietes.

** I Chronicles 15:27

Porro David erat indutus stola byssina, et universi Levitæ qui portabant arcam, cantoresque, et Chonenias princeps prophetiæ inter cantores : David autem etiam indutus erat ephod lineo.

** I Chronicles 15:28

Universusque Israël deducebant arcam fœderis Domini in jubilo, et sonitu buccinæ, et tubis, et cymbalis, et nablis, et citharis concrepantes.

** I Chronicles 15:29

Cumque pervenisset arca fœderis Domini usque ad civitatem David, Michol filia Saul prospiciens per fenestram vidit regem David saltantem atque ludentem, et despexit eum in corde suo.   

* I Chronicles 16

** I Chronicles 16:1

Attulerunt igitur arcam Dei, et constituerunt eam in medio tabernaculi quod tetenderat ei David : et obtulerunt holocausta et pacifica coram Deo.

** I Chronicles 16:2

Cumque complesset David offerens holocausta et pacifica, benedixit populo in nomine Domini.

** I Chronicles 16:3

Et divisit universis per singulos, a viro usque ad mulierem, tortam panis, et partem assæ carnis bubalæ, et frixam oleo similam.  

** I Chronicles 16:4

Constituitque coram arca Domini de Levitis, qui ministrarent, et recordarentur operum ejus, et glorificarent atque laudarent Dominum Deum Israël :

** I Chronicles 16:5

Asaph principem, et secundum ejus Zachariam : porro Jahiel, et Semiramoth, et Jehiel, et Mathathiam, et Eliab, et Banaiam, et Obededom : Jehiel super organa psalterii et lyras : Asaph autem ut cymbalis personaret :

** I Chronicles 16:6

Banaiam vero et Jaziel sacerdotes canere tuba jugiter coram arca fœderis Domini.  

** I Chronicles 16:7

In illo die fecit David principem ad confitendum Domino Asaph et fratres ejus :  

** I Chronicles 16:8

Confitemini Domino, et invocate nomen ejus :  notas facite in populis adinventiones ejus. 

** I Chronicles 16:9

Cantate ei, et psallite ei,  et narrate omnia mirabilia ejus. 

** I Chronicles 16:10

Laudate nomen sanctum ejus :  lætetur cor quærentium Dominum. 

** I Chronicles 16:11

Quærite Dominum, et virtutem ejus :  quærite faciem ejus semper. 

** I Chronicles 16:12

Recordamini mirabilium ejus quæ fecit ;  signorum illius, et judiciorum oris ejus, 

** I Chronicles 16:13

semen Israël servi ejus,  filii Jacob electi ejus. 

** I Chronicles 16:14

Ipse Dominus Deus noster :  in universa terra judicia ejus. 

** I Chronicles 16:15

Recordamini in sempiternum pacti ejus :  sermonis quem præcepit in mille generationes, 

** I Chronicles 16:16

quem pepigit cum Abraham,  et juramenti illius cum Isaac. 

** I Chronicles 16:17

Et constituit illud Jacob in præceptum,  et Israël in pactum sempiternum, 

** I Chronicles 16:18

dicens : Tibi dabo terram Chanaan,  funiculum hæreditatis vestræ : 

** I Chronicles 16:19

cum essent pauci numero,  parvi et coloni ejus. 

** I Chronicles 16:20

Et transierunt de gente in gentem,  et de regno ad populum alterum. 

** I Chronicles 16:21

Non dimisit quemquam calumniari eos,  sed increpavit pro eis reges. 

** I Chronicles 16:22

Nolite tangere christos meos,  et in prophetis meis nolite malignari. 

** I Chronicles 16:23

Cantate Domino omnis terra ;  annuntiate ex die in diem salutare ejus : 

** I Chronicles 16:24

narrate in gentibus gloriam ejus ;  in cunctis populis mirabilia ejus. 

** I Chronicles 16:25

Quia magnus Dominus, et laudabilis nimis,  et horribilis super omnes deos. 

** I Chronicles 16:26

Omnes enim dii populorum idola :  Dominus autem cælos fecit. 

** I Chronicles 16:27

Confessio et magnificentia coram eo :  fortitudo et gaudium in loco ejus. 

** I Chronicles 16:28

Afferte Domino, familiæ populorum :  afferte Domino gloriam et imperium. 

** I Chronicles 16:29

Date Domino gloriam ;  nomini ejus levate sacrificium,  et venite in conspectu ejus :  et adorate Dominum in decore sancto. 

** I Chronicles 16:30

Commoveatur a facie ejus omnis terra :  ipse enim fundavit orbem immobilem. 

** I Chronicles 16:31

Lætentur cæli, et exultet terra,  et dicant in nationibus : Dominus regnavit. 

** I Chronicles 16:32

Tonet mare et plenitudo ejus ;  exultent agri, et omnia quæ in eis sunt. 

** I Chronicles 16:33

Tunc laudabunt ligna saltus coram Domino :  quia venit judicare terram. 

** I Chronicles 16:34

Confitemini Domino, quoniam bonus :  quoniam in æternum misericordia ejus. 

** I Chronicles 16:35

Et dicite : Salva nos, Deus salvator noster,  et congrega nos, et erue de gentibus :  ut confiteamur nomini sancto tuo,  et exultemus in carminibus tuis. 

** I Chronicles 16:36

Benedictus Dominus Deus Israël,  ab æterno usque in æternum. Et dicat omnis populo : Amen, et hymnum Domino.

** I Chronicles 16:37

Reliquit itaque ibi coram arca fœderis Domini Asaph et fratres ejus, ut ministrarent in conspectu arcæ jugiter per singulos dies, et vices suas.

** I Chronicles 16:38

Porro Obededom, et fratres ejus sexaginta octo : et Obededom filium Idithun, et Hosa, constituit janitores ;

** I Chronicles 16:39

Sadoc autem sacerdotem, et fratres ejus sacerdotes, coram tabernaculo Domini in excelso quod erat in Gabaon,

** I Chronicles 16:40

ut offerrent holocausta Domino super altare holocautomatis jugiter, mane et vespere, juxta omnia quæ scripta sunt in lege Domini, quam præcepit Israëli.

** I Chronicles 16:41

Et post eum Heman, et Idithun, et reliquos electos, unumquemque vocabulo suo ad confitendum Domino, quoniam in æternum misericordia ejus.

** I Chronicles 16:42

Heman quoque et Idithun canentes tuba, et quatientes cymbala et omnia musicorum organa ad canendum Deo : filios autem Idithun fecit esse portarios.

** I Chronicles 16:43

Reversusque est omnis populus in domum suam : et David, ut benediceret etiam domui suæ.  

* I Chronicles 17

** I Chronicles 17:1

Cum autem habitaret David in domo sua, dixit ad Nathan prophetam : Ecce ego habito in domo cedrina : arca autem fœderis Domini sub pellibus est.

** I Chronicles 17:2

Et ait Nathan ad David : Omnia quæ in corde tuo sunt, fac : Deus enim tecum est.

** I Chronicles 17:3

Igitur nocte illa factus est sermo Dei ad Nathan, dicens :

** I Chronicles 17:4

Vade, et loquere David servo meo : Hæc dicit Dominus : Non ædificabis tu mihi domum ad habitandum.

** I Chronicles 17:5

Neque enim mansi in domo ex eo tempore quo eduxi Israël usque ad diem hanc : sed fui semper mutans loca tabernaculi, et in tentorio

** I Chronicles 17:6

manens cum omni Israël. Numquid locutus sum saltem uni judicum Israël, quibus præceperam ut pascerent populum meum, et dixi : Quare non ædificastis mihi domum cedrinam ?

** I Chronicles 17:7

Nunc itaque sic loqueris ad servum meum David : Hæc dicit Dominus exercituum : Ego tuli te, cum in pascuis sequereris gregem, ut esses dux populi mei Israël :

** I Chronicles 17:8

et fui tecum quocumque perrexisti, et interfeci omnes inimicos tuos coram te, fecique tibi nomen quasi unius magnorum qui celebrantur in terra.

** I Chronicles 17:9

Et dedi locum populo meo Israël : plantabitur, et habitabit in eo, et ultra non commovebitur : nec filii iniquitatis atterent eos, sicut a principio,

** I Chronicles 17:10

ex diebus quibus dedi judices populo meo Israël, et humiliavi universos inimicos tuos. Annuntio ergo tibi, quod ædificaturus sit tibi Dominus domum.

** I Chronicles 17:11

Cumque impleveris dies tuos ut vadas ad patres tuos, suscitabo semen tuum post te, quod erit de filiis tuis : et stabiliam regnum ejus.

** I Chronicles 17:12

Ipse ædificabit mihi domum, et firmabo solium ejus usque in æternum.

** I Chronicles 17:13

Ego ero ei in patrem, et ipse erit mihi in filium : et misericordiam meam non auferam ab eo, sicut abstuli ab eo qui ante te fuit.

** I Chronicles 17:14

Et statuam eum in domo mea, et in regno meo usque in sempiternum : et thronus ejus erit firmissimus in perpetuum.

** I Chronicles 17:15

Juxta omnia verba hæc, et juxta universam visionem istam, sic locutus est Nathan ad David.  

** I Chronicles 17:16

Cumque venisset rex David, et sedisset coram Domino, dixit : Quis ego sum, Domine Deus, et quæ domus mea, ut præstares mihi talia ?

** I Chronicles 17:17

sed et hoc parum visum est in conspectu tuo, ideoque locutus es super domum servi tui etiam in futurum : et fecisti me spectabilem super omnes homines, Domine Deus.

** I Chronicles 17:18

Quid ultra addere potest David, cum ita glorificaveris servum tuum, et cognoveris eum ?

** I Chronicles 17:19

Domine, propter famulum tuum juxta cor tuum fecisti omnem magnificentiam hanc, et nota esse voluisti universa magnalia.

** I Chronicles 17:20

Domine, non est similis tui, et non est alius deus absque te, ex omnibus quos audivimus auribus nostris.

** I Chronicles 17:21

Quis enim est alius, ut populus tuus Israël, gens una in terra, ad quam perrexit Deus ut liberaret et faceret populum sibi, et magnitudine sua atque terroribus ejiceret nationes a facie ejus, quem de Ægypto liberarat ?

** I Chronicles 17:22

Et posuisti populum tuum Israël tibi in populum usque in æternum, et tu, Domine, factus es Deus ejus.

** I Chronicles 17:23

Nunc igitur Domine, sermo quem locutus es famulo tuo et super domum ejus confirmetur in perpetuum, et fac sicut locutus es.

** I Chronicles 17:24

Permaneatque et magnificetur nomen tuum usque in sempiternum, et dicatur : Dominus exercituum Deus Israël, et domus David servi ejus permanens coram eo.

** I Chronicles 17:25

Tu enim, Domine Deus meus, revelasti auriculam servi tui, ut ædificares ei domum : et idcirco invenit servus tuus fiduciam, ut oret coram te.

** I Chronicles 17:26

Nunc ergo Domine, tu es Deus, et locutus es ad servum tuum tanta beneficia.

** I Chronicles 17:27

Et cœpisti benedicere domui servi tui, ut sit semper coram te : te enim, Domine, benedicente, benedicta erit in perpetuum.   

* I Chronicles 18

** I Chronicles 18:1

Factum est autem post hæc, ut percuteret David Philisthiim, et humiliaret eos, et tolleret Geth et filias ejus de manu Philisthiim,

** I Chronicles 18:2

percuteretque Moab, et fierent Moabitæ servi David, offerentes ei munera.

** I Chronicles 18:3

Eo tempore percussit David etiam Adarezer regem Soba regionis Hemath, quando perrexit ut dilataret imperium suum usque ad flumen Euphraten.

** I Chronicles 18:4

Cepit ergo David mille quadrigas ejus, et septem millia equitum, ac viginti millia virorum peditum, subnervavitque omnes equos curruum, exceptis centum quadrigis, quas reservavit sibi.

** I Chronicles 18:5

Supervenit autem et Syrus Damascenus, ut auxilium præberet Adarezer regi Soba : sed et hujus percussit David viginti duo millia virorum.

** I Chronicles 18:6

Et posuit milites in Damasco, ut Syria quoque serviret sibi, et offerret munera. Adjuvitque eum Dominus in cunctis ad quæ perrexerat.

** I Chronicles 18:7

Tulit quoque David pharetras aureas, quas habuerant servi Adarezer, et attulit eas in Jerusalem.

** I Chronicles 18:8

Necnon de Thebath et Chun urbibus Adarezer æris plurimum, de quo fecit Salomon mare æneum, et columnas, et vasa ænea.  

** I Chronicles 18:9

Quod cum audisset Thou rex Hemath, percussisse videlicet David omnem exercitum Adarezer regis Soba,

** I Chronicles 18:10

misit Adoram filium suum ad regem David, ut postularet ab eo pacem, et congratularetur ei quod percussisset et expugnasset Adarezer : adversarius quippe erat Thou Adarezer.

** I Chronicles 18:11

Sed et omnia vasa aurea, et argentea, et ænea consecravit David rex Domino, cum argento et auro quod tulerat ex universis gentibus, tam de Idumæa, et Moab, et filiis Ammon, quam de Philisthiim et Amalec.

** I Chronicles 18:12

Abisai vero filius Sarviæ percussit Edom in valle Salinarum, decem et octo millia :

** I Chronicles 18:13

et constituit in Edom præsidium, ut serviret Idumæa David : salvavitque Dominus David in cunctis ad quæ perrexerat.

** I Chronicles 18:14

Regnavit ergo David super universum Israël, et faciebat judicium atque justitiam cuncto populo suo.

** I Chronicles 18:15

Porro Joab filius Sarviæ erat super exercitum, et Josaphat filius Ahilud a commentariis :

** I Chronicles 18:16

Sadoc autem filius Achitob, et Ahimelech filius Abiathar, sacerdotes : et Susa, scriba :

** I Chronicles 18:17

Banaias quoque filius Jojadæ super legiones Cerethi et Phelethi : porro filii David, primi ad manum regis.   

* I Chronicles 19

** I Chronicles 19:1

Accidit autem ut moreretur Naas rex filiorum Ammon, et regnaret filius ejus pro eo.

** I Chronicles 19:2

Dixitque David : Faciam misericordiam cum Hanon filio Naas : præstitit enim mihi pater ejus gratiam. Misitque David nuntios ad consolandum eum super morte patris sui. Qui cum pervenissent in terram filiorum Ammon ut consolarentur Hanon,

** I Chronicles 19:3

dixerunt principes filiorum Ammon ad Hanon : Tu forsitan putas, quod David honoris causa in patrem tuum miserit qui consolentur te : nec animadvertis quod ut explorent, et investigent, et scrutentur terram tuam, venerint ad te servi ejus.

** I Chronicles 19:4

Igitur Hanon pueros David decalvavit, et rasit, et præcidit tunicas eorum a natibus usque ad pedes, et dimisit eos.

** I Chronicles 19:5

Qui cum abiissent, et hoc mandassent David, misit in occursum eorum (grandem enim contumeliam sustinuerant) et præcepit ut manerent in Jericho, donec cresceret barba eorum, et tunc reverterentur.

** I Chronicles 19:6

Videntes autem filii Ammon quod injuriam fecissent David, tam Hanon quam reliquus populus, miserunt mille talenta argenti, ut conducerent sibi de Mesopotamia, et de Syria Maacha, et de Soba currus et equites.

** I Chronicles 19:7

Conduxeruntque triginta duo millia curruum, et regem Maacha cum populo ejus. Qui cum venissent, castrametati sunt e regione Medaba. Filii quoque Ammon congregati de urbibus suis venerunt ad bellum.

** I Chronicles 19:8

Quod cum audisset David, misit Joab, et omnem exercitum virorum fortium :

** I Chronicles 19:9

egressique filii Ammon, direxerunt aciem juxta portam civitatis ; reges autem, qui ad auxilium ejus venerant, separatim in agro steterunt.  

** I Chronicles 19:10

Igitur Joab, intelligens bellum ex adverso et post tergum contra se fieri, elegit viros fortissimos de universo Israël, et perrexit contra Syrum.

** I Chronicles 19:11

Reliquam autem partem populi dedit sub manu Abisai fratris sui : et perrexerunt contra filios Ammon.

** I Chronicles 19:12

Dixitque : Si vicerit me Syrus, auxilio eris mihi : si autem superaverint te filii Ammon, ero tibi in præsidium.

** I Chronicles 19:13

Confortare, et agamus viriliter pro populo nostro, et pro urbibus Dei nostri : Dominus autem, quod in conspectu suo bonum est, faciet.

** I Chronicles 19:14

Perrexit ergo Joab et populus qui cum eo erat, contra Syrum ad prælium : et fugavit eos.

** I Chronicles 19:15

Porro filii Ammon videntes quod fugisset Syrus, ipsi quoque fugerunt Abisai fratrem ejus, et ingressi sunt civitatem : reversusque est etiam Joab in Jerusalem.

** I Chronicles 19:16

Videns autem Syrus quod cecidisset coram Israël, misit nuntios, et adduxit Syrum, qui erat trans fluvium : Sophach autem princeps militiæ Adarezer erat dux eorum.

** I Chronicles 19:17

Quod cum nuntiatum esset David, congregavit universum Israël, et transivit Jordanem, irruitque in eos et direxit ex adverso aciem, illis contra pugnantibus.

** I Chronicles 19:18

Fugit autem Syrus Israël, et interfecit David de Syris septem millia curruum, et quadraginta millia peditum, et Sophach exercitus principem.

** I Chronicles 19:19

Videntes autem servi Adarezer se ab Israël esse superatos, transfugerunt ad David, et servierunt ei : noluitque ultra Syria auxilium præbere filiis Ammon.   

* I Chronicles 20

** I Chronicles 20:1

Factum est autem post anni circulum, eo tempore quo solent reges ad bella procedere, congregavit Joab exercitum, et robur militiæ, et vastavit terram filiorum Ammon : perrexitque et obsedit Rabba. Porro David manebat in Jerusalem, quando Joab percussit Rabba et destruxit eam.

** I Chronicles 20:2

Tulit autem David coronam Melchom de capite ejus, et invenit in ea auri pondo talentum, et pretiosissimas gemmas, fecitque sibi inde diadema : manubias quoque urbis plurimas tulit ;

** I Chronicles 20:3

populum autem, qui erat in ea, eduxit, et fecit super eos tribulas, et trahas, et ferrata carpenta transire, ita ut dissecarentur et contererentur. Sic fecit David cunctis urbibus filiorum Ammon : et reversus est cum omni populo suo in Jerusalem.

** I Chronicles 20:4

Post hæc initum est bellum in Gazer adversum Philisthæos, in quo percussit Sobochai Husathites, Saphai de genere Raphaim, et humiliavit eos.

** I Chronicles 20:5

Aliud quoque bellum gestum est adversus Philisthæos, in quo percussit Adeodatus filius Saltus Bethlehemites fratrem Goliath Gethæi, cujus hastæ lignum erat quasi liciatorium texentium.

** I Chronicles 20:6

Sed et aliud bellum accidit in Geth, in quo fuit homo longissimus, senos habens digitos, id est, simul viginti quatuor : qui et ipse de Rapha fuerat stirpe generatus.

** I Chronicles 20:7

Hic blasphemavit Israël : et percussit eum Jonathan filius Samaa fratris David. Hi sunt filii Rapha in Geth, qui ceciderunt in manu David et servorum ejus.   

* I Chronicles 21

** I Chronicles 21:1

Consurrexit autem Satan contra Israël, et concitavit David ut numeraret Israël.

** I Chronicles 21:2

Dixitque David ad Joab et ad principes populi : Ite, et numerate Israël a Bersabee usque Dan : et afferte mihi numerum ut sciam.

** I Chronicles 21:3

Responditque Joab : Augeat Dominus populum suum centuplum quam sunt : nonne, domine mi rex, omnes servi tui sunt ? quare hoc quærit dominus meus, quod in peccatum reputetur Israëli ?

** I Chronicles 21:4

Sed sermo regis magis prævaluit : egressusque est Joab, et circuivit universum Israël : et reversus est Jerusalem,

** I Chronicles 21:5

deditque David numerum eorum quos circuierat : et inventus est omnis numerus Israël, mille millia et centum millia virorum educentium gladium : de Juda autem quadringenta septuaginta millia bellatorum.

** I Chronicles 21:6

Nam Levi et Benjamin non numeravit : eo quod Joab invitus exsequeretur regis imperium.

** I Chronicles 21:7

Displicuit autem Deo quod jussum erat : et percussit Israël.

** I Chronicles 21:8

Dixitque David ad Deum : Peccavi nimis ut hoc facerem : obsecro, aufer iniquitatem servi tui, quia insipienter egi.

** I Chronicles 21:9

Et locutus est Dominus ad Gad videntem Davidis, dicens :

** I Chronicles 21:10

Vade, et loquere ad David, et dic ei : Hæc dicit Dominus : Trium tibi optionem do : unum, quod volueris, elige, et faciam tibi.

** I Chronicles 21:11

Cumque venisset Gad ad David, dixit ei : Hæc dicit Dominus : Elige, quod volueris :

** I Chronicles 21:12

aut tribus annis famem ; aut tribus mensibus te fugere hostes tuos, et gladium eorum non posse evadere ; aut tribus diebus gladium Domini, et pestilentiam versari in terra, et angelum Domini interficere in universis finibus Israël : nunc igitur vide quid respondeam ei qui misit me.

** I Chronicles 21:13

Et dixit David ad Gad : Ex omni parte me angustiæ premunt : sed melius mihi est ut incidam in manus Domini, quia multæ sunt miserationes ejus, quam in manus hominum.  

** I Chronicles 21:14

Misit ergo Dominus pestilentiam in Israël : et ceciderunt de Israël septuaginta millia virorum.

** I Chronicles 21:15

Misit quoque angelum in Jerusalem ut percuteret eam : cumque percuteretur, vidit Dominus, et misertus est super magnitudine mali : et imperavit angelo qui percutiebat : Sufficit, jam cesset manus tua. Porro angelus Domini stabat juxta aream Ornan Jebusæi.

** I Chronicles 21:16

Levansque David oculos suos, vidit angelum Domini stantem inter cælum et terram, et evaginatum gladium in manu ejus, et versum contra Jerusalem : et ceciderunt tam ipse quam majores natu, vestiti ciliciis, proni in terram.

** I Chronicles 21:17

Dixitque David ad Deum : Nonne ego sum, qui jussi ut numeraretur populus ? ego, qui peccavi ? ego, qui malum feci ? iste grex, quid commeruit ? Domine Deus meus, vertatur, obsecro, manus tua in me, et in domum patris mei : populus autem tuus non percutiatur.

** I Chronicles 21:18

Angelus autem Domini præcepit Gad ut diceret Davidi ut ascenderet, exstrueretque altare Domino Deo in area Ornan Jebusæi.

** I Chronicles 21:19

Ascendit ergo David juxta sermonem Gad, quem locutus ei fuerat ex nomine Domini.

** I Chronicles 21:20

Porro Ornan cum suspexisset et vidisset angelum, quatuorque filii ejus cum eo, absconderunt se : nam eo tempore terebat in area triticum.

** I Chronicles 21:21

Igitur cum veniret David ad Ornan, conspexit eum Ornan, et processit ei obviam de area, et adoravit eum pronus in terram.

** I Chronicles 21:22

Dixitque ei David : Da mihi locum areæ tuæ, ut ædificem in ea altare Domino : ita ut quantum valet argenti accipias, et cesset plaga a populo.

** I Chronicles 21:23

Dixit autem Ornan ad David : Tolle, et faciat dominus meus rex quodcumque ei placet : sed et boves do in holocaustum, et tribulas in ligna, et triticum in sacrificium : omnia libens præbebo.

** I Chronicles 21:24

Dixitque ei rex David : Nequaquam ita fiet, sed argentum dabo quantum valet : neque enim tibi auferre debeo, et sic offerre Domino holocausta gratuita.

** I Chronicles 21:25

Dedit ergo David Ornan pro loco siclos auri justissimi ponderis sexcentos.

** I Chronicles 21:26

Et ædificavit ibi altare Domino, obtulitque holocausta et pacifica, et invocavit Dominum ; et exaudivit eum in igne de cælo super altare holocausti.

** I Chronicles 21:27

Præcepitque Dominus angelo, et convertit gladium suum in vaginam.

** I Chronicles 21:28

Protinus ergo David, videns quod exaudisset eum Dominus in area Ornan Jebusæi, immolavit ibi victimas.

** I Chronicles 21:29

Tabernaculum autem Domini, quod fecerat Moyses in deserto, et altare holocaustorum, ea tempestate erat in excelso Gabaon.

** I Chronicles 21:30

Et non prævaluit David ire ad altare ut ibi obsecraret Deum : nimio enim fuerat in timore perterritus, videns gladium angeli Domini.   

* I Chronicles 22

** I Chronicles 22:1

Dixitque David : Hæc est domus Dei, et hoc altare in holocaustum Israëli.

** I Chronicles 22:2

Et præcepit ut congregarentur omnes proselyti de terra Israël, et constituit ex eis latomos ad cædendos lapides et poliendos, ut ædificaretur domus Dei.

** I Chronicles 22:3

Ferrum quoque plurimum ad clavos januarum, et ad commissuras atque juncturas, præparavit David : et æris pondus innumerabile.

** I Chronicles 22:4

Ligna quoque cedrina non poterant æstimari, quæ Sidonii et Tyrii deportaverant ad David.

** I Chronicles 22:5

Et dixit David : Solomon filius meus puer parvulus est et delicatus : domus autem, quam ædificari volo Domino, talis esse debet ut in cunctis regionibus nominetur : præparabo ergo ei necessaria. Et ob hanc causam ante mortem suam omnes præparavit impensas.  

** I Chronicles 22:6

Vocavitque Salomonem filium suum, et præcepit ei ut ædificaret domum Domino Deo Israël.

** I Chronicles 22:7

Dixitque David ad Salomonem : Fili mi, voluntatis meæ fuit ut ædificarem domum nomini Domini Dei mei :

** I Chronicles 22:8

sed factus est sermo Domini ad me, dicens : Multum sanguinem effudisti, et plurima bella bellasti : non poteris ædificare domum nomini meo, tanto effuso sanguine coram me :

** I Chronicles 22:9

filius qui nascetur tibi, erit vir quietissimus : faciam enim eum requiescere ab omnibus inimicis suis per circuitum : et ob hanc causam Pacificus vocabitur : et pacem et otium dabo in Israël cunctis diebus ejus.

** I Chronicles 22:10

Ipse ædificabit domum nomini meo, et ipse erit mihi in filium, et ego ero illi in patrem : firmaboque solium regni ejus super Israël in æternum.

** I Chronicles 22:11

Nunc ergo fili mi, sit Dominus tecum, et prosperare, et ædifica domum Domino Deo tuo sicut locutus est de te.

** I Chronicles 22:12

Det quoque Dominus prudentiam et sensum ut regere possis Israël, et custodire legem Domini Dei tui.

** I Chronicles 22:13

Tunc enim proficere poteris, si custodieris mandata et judicia quæ præcepit Dominus Moysi ut doceret Israël. Confortare, et viriliter age : ne timeas, neque paveas.

** I Chronicles 22:14

Ecce ego in paupertate mea præparavi impensas domus Domini, auri talenta centum millia, et argenti mille millia talentorum : æris vero et ferri non est pondus, vincitur enim numerus magnitudine ; ligna et lapides præparavi ad universa impendia.

** I Chronicles 22:15

Habes quoque plurimos artifices, latomos, et cæmentarios, artificesque lignorum, et omnium artium ad faciendum opus prudentissimos,

** I Chronicles 22:16

in auro et argento et ære et ferro, cujus non est numerus. Surge igitur et fac, et erit Dominus tecum.  

** I Chronicles 22:17

Præcepit quoque David cunctis principibus Israël ut adjuvarent Salomonem filium suum :

** I Chronicles 22:18

Cernitis, inquiens, quod Dominus Deus vester vobiscum sit, et dederit vobis requiem per circuitum, et tradiderit omnes inimicos vestros in manus vestras, et subjecta sit terra coram Domino, et coram populo ejus.

** I Chronicles 22:19

Præbete igitur corda vestra et animas vestras, ut quæratis Dominum Deum vestrum : et consurgite, et ædificate sanctuarium Domino Deo, ut introducatur arca fœderis Domini, et vasa Domino consecrata, in domum quæ ædificatur nomini Domini.   

* I Chronicles 23

** I Chronicles 23:1

Igitur David, senex et plenus dierum, regem constituit Salomonem filium suum super Israël.

** I Chronicles 23:2

Et congregavit omnes principes Israël, et sacerdotes atque Levitas.

** I Chronicles 23:3

Numeratique sunt Levitæ a triginta annis et supra : et inventa sunt triginta octo millia virorum.

** I Chronicles 23:4

Ex his electi sunt, et distributi in ministerium domus Domini, viginti quatuor millia : præpositorum autem et judicum, sex millia.

** I Chronicles 23:5

Porro quatuor millia janitores, et totidem psaltæ, canentes Domino in organis quæ fecerat ad canendum.

** I Chronicles 23:6

Et distribuit eos David per vices filiorum Levi, Gerson videlicet, et Caath, et Merari.

** I Chronicles 23:7

Filii Gerson : Leedan, et Semei.

** I Chronicles 23:8

Filii Leedan : princeps Jahiel, et Zethan, et Joël, tres.

** I Chronicles 23:9

Filii Semei : Salomith, et Hosiel, et Aran, tres : isti principes familiarum Leedan.

** I Chronicles 23:10

Porro filii Semei : Leheth, et Ziza, et Jaus, et Baria : isti filii Semei, quatuor.

** I Chronicles 23:11

Erat autem Leheth prior, Ziza secundus : porro Jaus et Baria non habuerunt plurimos filios, et idcirco in una familia, unaque domo computati sunt.

** I Chronicles 23:12

Filii Caath : Amram, et Isaar, Hebron, et Oziel, quatuor.

** I Chronicles 23:13

Filii Amram : Aaron et Moyses. Separatusque est Aaron ut ministraret in Sancto sanctorum, ipse et filii ejus in sempiternum, et adoleret incensum Domino secundum ritum suum, ac benediceret nomini ejus in perpetuum.

** I Chronicles 23:14

Moysi quoque hominis Dei filii annumerati sunt in tribu Levi.

** I Chronicles 23:15

Filii Moysi : Gersom et Eliezer.

** I Chronicles 23:16

Filii Gersom : Subuel primus.

** I Chronicles 23:17

Fuerunt autem filii Eliezer : Rohobia primus : et non erant Eliezer filii alii. Porro filii Rohobia multiplicati sunt nimis.

** I Chronicles 23:18

Filii Isaar : Salomith primus.

** I Chronicles 23:19

Filii Hebron : Jeriau primus, Amarias secundus, Jahaziel tertius, Jecmaam quartus.

** I Chronicles 23:20

Filii Oziel : Micha primus, Jesia secundus.

** I Chronicles 23:21

Filii Merari : Moholi, et Musi. Filii Moholi : Eleazar et Cis.

** I Chronicles 23:22

Mortuus est autem Eleazar, et non habuit filios, sed filias : acceperuntque eas filii Cis fratres earum.

** I Chronicles 23:23

Filii Musi : Moholi, et Eder, et Jerimoth, tres.

** I Chronicles 23:24

Hi filii Levi in cognationibus et familiis suis, principes per vices, et numerum capitum singulorum qui faciebant opera ministerii domus Domini, a viginti annis et supra.

** I Chronicles 23:25

Dixit enim David : Requiem dedit Dominus Deus Israël populo suo, et habitationem Jerusalem usque in æternum.

** I Chronicles 23:26

Nec erit officii Levitarum ut ultra portent tabernaculum et omnia vasa ejus ad ministrandum.

** I Chronicles 23:27

Juxta præcepta quoque David novissima, supputabitur numerus filiorum Levi a viginti annis et supra.

** I Chronicles 23:28

Et erunt sub manu filiorum Aaron in cultum domus Domini, in vestibulis, et in exedris, et in loco purificationis, et in sanctuario, et in universis operibus ministerii templi Domini.

** I Chronicles 23:29

Sacerdotes autem, super panes propositionis, et ad similæ sacrificium, et ad lagana azyma, et sartaginem, et ad torrendum, et super omne pondus atque mensuram.

** I Chronicles 23:30

Levitæ vero ut stent mane ad confitendum et canendum Domino : similiterque ad vesperam,

** I Chronicles 23:31

tam in oblatione holocaustorum Domini, quam in sabbatis et calendis et solemnitatibus reliquis juxta numerum et cæremonias uniuscujusque rei, jugiter coram Domino.

** I Chronicles 23:32

Et custodiant observationes tabernaculi fœderis, et ritum sanctuarii, et observationem filiorum Aaron fratrum suorum, ut ministrent in domo Domini.   

* I Chronicles 24

** I Chronicles 24:1

Porro filiis Aaron hæ partitiones erant. Filii Aaron : Nadab, et Abiu, et Eleazar, et Ithamar.

** I Chronicles 24:2

Mortui sunt autem Nadab et Abiu ante patrem suum absque liberis : sacerdotioque functus est Eleazar, et Ithamar.

** I Chronicles 24:3

Et divisit eos David, id est, Sadoc de filiis Eleazari, et Ahimelech de filiis Ithamar, secundum vices suas et ministerium.

** I Chronicles 24:4

Inventique sunt multo plures filii Eleazar in principibus viris, quam filii Ithamar. Divisit autem eis, hoc est, filiis Eleazar, principes per familias sedecim : et filiis Ithamar per familias et domos suas octo.

** I Chronicles 24:5

Porro divisit utrasque inter se familias sortibus : erant enim principes sanctuarii, et principes Dei, tam de filiis Eleazar quam de filiis Ithamar.

** I Chronicles 24:6

Descripsitque eos Semeias filius Nathanaël scriba Levites, coram rege et principibus, et Sadoc sacerdote, et Ahimelech filio Abiathar, principibus quoque familiarum sacerdotalium, et Leviticarum : unam domum, quæ ceteris præerat, Eleazar : et alteram domum, quæ sub se habebat ceteros, Ithamar.

** I Chronicles 24:7

Exivit autem sors prima Jojarib, secunda Jedei,

** I Chronicles 24:8

tertia Harim, quarta Seorim,

** I Chronicles 24:9

quinta Melchia, sexta Maiman,

** I Chronicles 24:10

septima Accos, octava Abia,

** I Chronicles 24:11

nona Jesua, decima Sechenia,

** I Chronicles 24:12

undecima Eliasib, duodecima Jacim,

** I Chronicles 24:13

tertiadecima Hoppha, decimaquarta Isbaab,

** I Chronicles 24:14

decimaquinta Belga, decimasexta Emmer,

** I Chronicles 24:15

decimaseptima Hezir, decimaoctava Aphses,

** I Chronicles 24:16

decimanona Pheteia, vigesima Hezechiel,

** I Chronicles 24:17

vigesima prima Jachin, vigesima secunda Gamul,

** I Chronicles 24:18

vigesima tertia Dalaiau, vigesima quarta Maaziau.

** I Chronicles 24:19

Hæ vices eorum secundum ministeria sua, ut ingrediantur domum Domini, et juxta ritum suum sub manu Aaron patris eorum, sicut præceperat Dominus Deus Israël.

** I Chronicles 24:20

Porro filiorum Levi qui reliqui fuerant, de filiis Amram erat Subaël, et de filiis Subaël, Jehedeia.

** I Chronicles 24:21

De filiis quoque Rohobiæ, princeps Jesias.

** I Chronicles 24:22

Isaari vero filius Salemoth, filiusque Salemoth Jahath :

** I Chronicles 24:23

filiusque ejus Jeriau primus, Amarias secundus, Jahaziel tertius, Jecmaan quartus.

** I Chronicles 24:24

Filius Oziel, Micha : filius Micha, Samir.

** I Chronicles 24:25

Frater Micha, Jesia : filiusque Jesiæ, Zacharias.

** I Chronicles 24:26

Filii Merari : Moholi, et Musi. Filius Oziau : Benno.

** I Chronicles 24:27

Filius quoque Merari : Oziau, et Soam, et Zachur, et Hebri.

** I Chronicles 24:28

Porro Moholi filius, Eleazar, qui non habebat liberos.

** I Chronicles 24:29

Filius vero Cis, Jerameel.

** I Chronicles 24:30

Filii Musi : Moholi, Eder et Jerimoth : isti filii Levi secundum domos familiarum suarum.

** I Chronicles 24:31

Miseruntque et ipsi sortes contra fratres suos filios Aaron coram David rege, et Sadoc, et Ahimelech, et principibus familiarum sacerdotalium et Leviticarum, tam majores quam minores : omnes sors æqualiter dividebat.   

* I Chronicles 25

** I Chronicles 25:1

Igitur David et magistratus exercitus segregaverunt in ministerium filios Asaph, et Heman, et Idithun, qui prophetarent in citharis, et psalteriis, et cymbalis secundum numerum suum, dedicato sibi officio servientes.

** I Chronicles 25:2

De filiis Asaph : Zachur, et Joseph, et Nathania, et Asarela, filii Asaph : sub manu Asaph prophetantis juxta regem.

** I Chronicles 25:3

Porro Idithun : filii Idithun, Godolias, Sori, Jeseias, et Hasabias, et Mathathias, sex, sub manu patris sui Idithun, qui in cithara prophetabat super confitentes et laudantes Dominum.

** I Chronicles 25:4

Heman quoque : filii Heman, Bocciau, Mathaniau, Oziel, Subuel, et Jerimoth, Hananias, Hanani, Eliatha, Geddelthi, et Romemthiezer, et Jesbacassa, Mellothi, Othir, Mahazioth :

** I Chronicles 25:5

omnes isti filii Heman videntis regis in sermonibus Dei, ut exaltaret cornu : deditque Deus Heman filios quatuordecim, et filias tres.

** I Chronicles 25:6

Universi sub manu patris sui ad cantandum in templo Domini distributi erant, in cymbalis, et psalteriis, et citharis, in ministeria domus Domini juxta regem : Asaph videlicet, et Idithun, et Heman.

** I Chronicles 25:7

Fuit autem numerus eorum cum fratribus suis, qui erudiebant canticum Domini, cuncti doctores, ducenti octoginta octo.

** I Chronicles 25:8

Miseruntque sortes per vices suas, ex æquo tam major quam minor, doctus pariter et indoctus.

** I Chronicles 25:9

Egressaque est sors prima Joseph, qui erat de Asaph. Secunda Godoliæ, ipsi et filiis ejus, et fratribus ejus duodecim.

** I Chronicles 25:10

Tertia Zachur, filiis et fratribus ejus duodecim.

** I Chronicles 25:11

Quarta Isari, filiis et fratribus ejus duodecim.

** I Chronicles 25:12

Quinta Nathaniæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:13

Sexta Bocciau, filiis et fratribus ejus duodecim.

** I Chronicles 25:14

Septima Isreela, filiis et fratribus ejus duodecim.

** I Chronicles 25:15

Octava Jesaiæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:16

Nona Mathaniæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:17

Decima Semeiæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:18

Undecima Azareel, filiis et fratribus ejus duodecim.

** I Chronicles 25:19

Duodecima Hasabiæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:20

Tertiadecima Subaël, filiis et fratribus ejus duodecim.

** I Chronicles 25:21

Quartadecima Mathathiæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:22

Quintadecima Jerimoth, filiis et fratribus ejus duodecim.

** I Chronicles 25:23

Sextadecima Hananiæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:24

Septimadecima Jesbacassæ, filiis et fratribus ejus duodecim.

** I Chronicles 25:25

Octavadecima Hanani, filiis et fratribus ejus duodecim.

** I Chronicles 25:26

Nonadecima Mellothi, filiis et fratribus ejus duodecim.

** I Chronicles 25:27

Vigesima Eliatha, filiis et fratribus ejus duodecim.

** I Chronicles 25:28

Vigesima prima Othir, filiis et fratribus ejus duodecim.

** I Chronicles 25:29

Vigesima secunda Geddelthi, filiis et fratribus ejus duodecim.

** I Chronicles 25:30

Vigesima tertia Mahazioth, filiis et fratribus ejus duodecim.

** I Chronicles 25:31

Vigesima quarta Romemthiezer, filiis et fratribus ejus duodecim.   

* I Chronicles 26

** I Chronicles 26:1

Divisiones autem janitorum : de Coritis Meselemia, filius Core, de filiis Asaph.

** I Chronicles 26:2

Filii Meselemiæ : Zacharias primogenitus, Jadihel secundus, Zabadias tertius, Jathanaël quartus,

** I Chronicles 26:3

Ælam quintus, Johanan sextus, Elioënai septimus.

** I Chronicles 26:4

Filii autem Obededom : Semeias primogenitus, Jozabad secundus, Joaha tertius, Sachar quartus, Nathanaël quintus,

** I Chronicles 26:5

Ammiel sextus, Issachar septimus, Phollathi octavus : quia benedixit illi Dominus.

** I Chronicles 26:6

Semei autem filio ejus nati sunt filii, præfecti familiarum suarum : erant enim viri fortissimi.

** I Chronicles 26:7

Filii ergo Semeiæ : Othni, et Raphaël, et Obed, Elzabad, fratres ejus viri fortissimi : Eliu quoque et Samachias.

** I Chronicles 26:8

Omnes hi, de filiis Obededom : ipsi, et filii et fratres eorum, fortissimi ad ministrandum, sexaginta duo de Obededom.

** I Chronicles 26:9

Porro Meselemiæ filii, et fratres eorum robustissimi, decem et octo.

** I Chronicles 26:10

De Hosa autem, id est, de filiis Merari : Semri princeps (non enim habuerat primogenitum, et idcirco posuerat eum pater ejus in principem),

** I Chronicles 26:11

Helcias secundus, Tabelias tertius, Zacharias quartus : omnes hi filii et fratres Hosa, tredecim.

** I Chronicles 26:12

Hi divisi sunt in janitores, ut semper principes custodiarum, sicut et fratres eorum ministrarent in domo Domini.

** I Chronicles 26:13

Missæ sunt ergo sortes ex æquo, et parvis et magnis, per familias suas in unamquamque portarum.

** I Chronicles 26:14

Cecidit ergo sors orientalis, Selemiæ. Porro Zachariæ filio ejus, viro prudentissimo et erudito, sortito obtigit plaga septentrionalis.

** I Chronicles 26:15

Obededom vero et filiis ejus ad austrum : in qua parte domus erat seniorum concilium.

** I Chronicles 26:16

Sephim et Hosa ad occidentem, juxta portam, quæ ducit ad viam ascensionis : custodia contra custodiam.

** I Chronicles 26:17

Ad orientem vero Levitæ sex : et ad aquilonem, quatuor per diem : atque ad meridiem similiter in die quatuor : et ubi erat concilium bini et bini.

** I Chronicles 26:18

In cellulis quoque janitorum ad occidentem quatuor in via, binique per cellulas.

** I Chronicles 26:19

Hæ sunt divisiones janitorum filiorum Core et Merari.  

** I Chronicles 26:20

Porro Achias erat super thesauros domus Dei, et vasa sanctorum.

** I Chronicles 26:21

Filii Ledan, filii Gersonni : de Ledan principes familiarum Ledan, et Gersonni, Jehieli.

** I Chronicles 26:22

Filii Jehieli : Zathan, et Joël fratres ejus super thesauros domus Domini.

** I Chronicles 26:23

Amramitis, et Isaaritis, et Hebronitis, et Ozihelitis.

** I Chronicles 26:24

Subaël autem filius Gersom filii Moysi, præpositus thesauris.

** I Chronicles 26:25

Fratres quoque ejus Eliezer, cujus filius Rahabia, et hujus filius Isaias, et hujus filius Joram, hujus quoque filius Zechri, et hujus filius Selemith.

** I Chronicles 26:26

Ipse Selemith, et fratres ejus, super thesauros sanctorum quæ sanctificavit David rex, et principes familiarum, et tribuni, et centuriones, et duces exercitus,

** I Chronicles 26:27

de bellis et manubiis præliorum, quæ consecraverant ad instaurationem et supellectilem templi Domini.

** I Chronicles 26:28

Hæc autem universa sanctificavit Samuel videns, et Saul filius Cis, et Abner filius Ner, et Joab filius Sarviæ : omnes qui sanctificaverant ea per manum Selemith et fratrum ejus.

** I Chronicles 26:29

Isaaritis vero præerat Chonenias, et filii ejus ad opera forinsecus super Israël ad docendum et judicandum eos.

** I Chronicles 26:30

Porro de Hebronitis Hasabias, et fratres ejus viri fortissimi, mille septingenti præerant Israëli trans Jordanem contra occidentem, in cunctis operibus Domini, et in ministerium regis.

** I Chronicles 26:31

Hebronitarum autem princeps fuit Jeria secundum familias et cognationes eorum. Quadragesimo anno regni David recensiti sunt, et inventi sunt viri fortissimi in Jazer Galaad,

** I Chronicles 26:32

fratresque ejus robustioris ætatis, duo millia septingenti principes familiarum. Præposuit autem eos David rex Rubenitis, et Gadditis, et dimidiæ tribui Manasse, in omne ministerium Dei et regis.   

* I Chronicles 27

** I Chronicles 27:1

Filii autem Israël secundum numerum suum, principes familiarum, tribuni, et centuriones, et præfecti, qui ministrabant regi juxta turmas suas, ingredientes et egredientes per singulos menses in anno, viginti quatuor millibus singuli præerant.

** I Chronicles 27:2

Primæ turmæ in primo mense Jesboam præerat filius Zabdiel, et sub eo viginti quatuor millia ;

** I Chronicles 27:3

de filiis Phares, princeps cunctorum principum in exercitu mense primo.

** I Chronicles 27:4

Secundi mensis habebat turmam Dudia Ahohites, et post se alter nomine Macelloth, qui regebat partem exercitus viginti quatuor millium.

** I Chronicles 27:5

Dux quoque turmæ tertiæ in mense tertio erat Banaias filius Jojadæ sacerdos : et in divisione sua viginti quatuor millia.

** I Chronicles 27:6

Ipse est Banaias fortissimus inter triginta, et super triginta : præerat autem turmæ ipsius Amizabad filius ejus.

** I Chronicles 27:7

Quartus, mense quarto, Asahel frater Joab, et Zabadias filius ejus post eum : et in turma ejus viginti quatuor millia.

** I Chronicles 27:8

Quintus, mense quinto, princeps Samaoth Jezerites : et in turma ejus viginti quatuor millia.

** I Chronicles 27:9

Sextus, mense sexto, Hira filius Acces Thecuites : et in turma ejus viginti quatuor millia.

** I Chronicles 27:10

Septimus, mense septimo, Helles Phallonites de filiis Ephraim : et in turma ejus viginti quatuor millia.

** I Chronicles 27:11

Octavus, mense octavo, Sobochai Husathites de stirpe Zarahi : et in turma ejus viginti quatuor millia.

** I Chronicles 27:12

Nonus, mense nono, Abiezer Anathothites de filiis Jemini : et in turma ejus viginti quatuor millia.

** I Chronicles 27:13

Decimus, mense decimo, Marai, et ipse Netophathites de stirpe Zarai : et in turma ejus viginti quatuor millia.

** I Chronicles 27:14

Undecimus, mense undecimo, Banaias Pharathonites de filiis Ephraim : et in turma ejus viginti quatuor millia.

** I Chronicles 27:15

Duodecimus, mense duodecimo, Holdai Netophathites, de stirpe Gothoniel : et in turma ejus viginti quatuor millia.

** I Chronicles 27:16

Porro tribubus præerant Israël, Rubenitis, dux Eliezer filius Zechri : Simeonitis, dux Saphatias filius Maacha :

** I Chronicles 27:17

Levitis, Hasabias filius Camuel : Aaronitis, Sadoc :

** I Chronicles 27:18

Juda, Eliu frater David : Issachar, Amri filius Michaël.

** I Chronicles 27:19

Zabulonitis, Jesmaias filius Abdiæ : Nephthalitibus, Jerimoth filius Ozriel :

** I Chronicles 27:20

filiis Ephraim, Osee filius Ozaziu : dimidiæ tribui Manasse, Joël filius Phadaiæ :

** I Chronicles 27:21

et dimidiæ tribui Manasse in Galaad, Jaddo filius Zachariæ : Benjamin autem, Jasiel filius Abner :

** I Chronicles 27:22

Dan vero, Ezrihel filius Jeroham : hi principes filiorum Israël.

** I Chronicles 27:23

Noluit autem David numerare eos a viginti annis inferius : quia dixerat Dominus ut multiplicaret Israël quasi stellas cæli.

** I Chronicles 27:24

Joab filius Sarviæ cœperat numerare, nec complevit : quia super hoc ira irruerat in Israël, et idcirco numerus eorum qui fuerant recensiti, non est relatus in fastos regis David.  

** I Chronicles 27:25

Super thesauros autem regis fuit Azmoth filius Adiel : his autem thesauris, qui erant in urbibus, et in vicis, et in turribus, præsidebat Jonathan filius Oziæ.

** I Chronicles 27:26

Operi autem rustico, et agricolis qui exercebant terram, præerat Ezri filius Chelub :

** I Chronicles 27:27

vinearumque cultoribus, Semeias Romathites : cellis autem vinariis, Zabdias Aphonites.

** I Chronicles 27:28

Nam super oliveta et ficeta quæ erant in campestribus, Balanam Gederites : super apothecas autem olei, Joas.

** I Chronicles 27:29

Porro armentis quæ pascebantur in Saron, præpositus fuit Setrai Saronites : et super boves in vallibus, Saphat filius Adli :

** I Chronicles 27:30

super camelos vero, Ubil Ismahelites : et super asinos, Jadias Meronathites :

** I Chronicles 27:31

super oves quoque, Jaziz Agareus : omnes hi, principes substantiæ regis David.

** I Chronicles 27:32

Jonathan autem patruus David, consiliarius, vir prudens et litteratus : ipse et Jahiel filius Hachamoni erant cum filiis regis.

** I Chronicles 27:33

Achitophel etiam consiliarius regis, et Chusai Arachites amicus regis.

** I Chronicles 27:34

Post Achitophel fuit Jojada filius Banaiæ, et Abiathar. Princeps autem exercitus regis erat Joab.   

* I Chronicles 28

** I Chronicles 28:1

Convocavit igitur David omnes principes Israël, duces tribuum, et præpositos turmarum, qui ministrabant regi : tribunos quoque et centuriones, et qui præerant substantiæ et possessionibus regis, filiosque suos cum eunuchis, et potentes et robustissimos quosque in exercitu Jerusalem.

** I Chronicles 28:2

Cumque surrexisset rex, et stetisset, ait : Audite me, fratres mei et populus meus : cogitavi ut ædificarem domum, in qua requiesceret arca fœderis Domini, et scabellum pedum Dei nostri : et ad ædificandum, omnia præparavi.

** I Chronicles 28:3

Deus autem dixit mihi : Non ædificabis domum nomini meo, eo quod sis vir bellator, et sanguinem fuderis.

** I Chronicles 28:4

Sed elegit Dominus Deus Israël me de universa domo patris mei, ut essem rex super Israël in sempiternum : de Juda enim elegit principes : porro de domo Juda, domum patris mei, et de filiis patris mei placuit ei ut me eligeret regem super cunctum Israël.

** I Chronicles 28:5

Sed et de filiis meis (filios enim mihi multos dedit Dominus) elegit Salomonem filium meum ut sederet in throno regni Domini super Israël,

** I Chronicles 28:6

dixitque mihi : Salomon filius tuus ædificabit domum meam, et atria mea : ipsum enim elegi mihi in filium, et ego ero ei in patrem.

** I Chronicles 28:7

Et firmabo regnum ejus usque in æternum, si perseveraverit facere præcepta mea et judicia, sicut et hodie.

** I Chronicles 28:8

Nunc ergo coram universo cœtu Israël audiente Deo nostro, custodite, et perquirite cuncta mandata Domini Dei nostri : ut possideatis terram bonam, et relinquatis eam filiis vestris post vos usque in sempiternum.

** I Chronicles 28:9

Tu autem, Salomon fili mi, scito Deum patris tui, et servito ei corde perfecto, animo voluntario : omnia enim corda scrutatur Dominus, et universas mentium cogitationes intelligit. Si quæsieris eum, invenies : si autem dereliqueris eum, projiciet te in æternum.

** I Chronicles 28:10

Nunc ergo quia elegit te Dominus ut ædificares domum sanctuarii, confortare, et perfice.  

** I Chronicles 28:11

Dedit autem David Salomoni filio suo descriptionem porticus, et templi, et cellariorum, et cœnaculi, et cubiculorum in adytis, et domus propitiationis,

** I Chronicles 28:12

necnon et omnium quæ cogitaverat atriorum et exedrarum per circuitum in thesauros domus Domini, et in thesauros sanctorum,

** I Chronicles 28:13

divisionumque sacerdotalium et Leviticarum, in omnia opera domus Domini, et in universa vasa ministerii templi Domini.

** I Chronicles 28:14

Aurum in pondere per singula vasa ministerii. Argenti quoque pondus pro vasorum et operum diversitate.

** I Chronicles 28:15

Sed et in candelabra aurea, et ad lucernas eorum, aurum pro mensura uniuscujusque candelabri et lucernarum. Similiter et in candelabra argentea, et in lucernas eorum, pro diversitate mensuræ, pondus argenti tradidit.

** I Chronicles 28:16

Aurum quoque dedit in mensas propositionis pro diversitate mensarum : similiter et argentum in alias mensas argenteas.

** I Chronicles 28:17

Ad fuscinulas quoque, et phialas, et thuribula ex auro purissimo, et leunculos aureos pro qualitate mensuræ pondus distribuit in leunculum et leunculum. Similiter et in leones argenteos diversum argenti pondus separavit.

** I Chronicles 28:18

Altari autem, in quo adoletur incensum, aurum purissimum dedit : ut ex ipso fieret similitudo quadrigæ cherubim extendentium alas, et velantium arcam fœderis Domini.

** I Chronicles 28:19

Omnia, inquit, venerunt scripta manu Domini ad me, ut intelligerem universa opera exemplaris.  

** I Chronicles 28:20

Dixit quoque David Salomoni filio suo : Viriliter age, et confortare, et fac : ne timeas, et ne paveas : Dominus enim Deus meus tecum erit, et non dimittet te nec derelinquet, donec perficias omne opus ministerii domus Domini.

** I Chronicles 28:21

Ecce divisiones sacerdotum et Levitarum : in omne ministerium domus Domini assistunt tibi, et parati sunt, et noverunt tam principes quam populus facere omnia præcepta tua.   

* I Chronicles 29

** I Chronicles 29:1

Locutusque est David rex ad omnem ecclesiam : Salomonem filium meum unum elegit Deus, adhuc puerum et tenellum : opus namque grande est, neque enim homini præparatur habitatio, sed Deo.

** I Chronicles 29:2

Ego autem totis viribus meis præparavi impensas domus Dei mei. Aurum ad vasa aurea, et argentum in argentea, æs in ænea, ferrum in ferrea, ligna ad lignea : et lapides onychinos, et quasi stibinos, et diversorum colorum, omnemque pretiosum lapidem, et marmor Parium abundantissime :

** I Chronicles 29:3

et super hæc quæ obtuli in domum Dei mei de peculio meo aurum et argentum, do in templum Dei mei, exceptis his quæ præparavi in ædem sanctam.

** I Chronicles 29:4

Tria millia talenta auri de auro Ophir, et septem millia talentorum argenti probatissimi ad deaurandos parietes templi.

** I Chronicles 29:5

Et ubicumque opus est aurum de auro, et ubicumque opus est argentum de argento, opera fiant per manus artificum : et si quis sponte offert, impleat manum suam hodie, et offerat quod voluerit Domino.

** I Chronicles 29:6

Polliciti sunt itaque principes familiarum, et proceres tribuum Israël, tribuni quoque, et centuriones, et principes possessionum regis.

** I Chronicles 29:7

Dederuntque in opera domus Dei auri talenta quinque millia, et solidos decem millia : argenti talenta decem millia, et æris talenta decem et octo millia : ferri quoque centum millia talentorum.

** I Chronicles 29:8

Et apud quemcumque inventi sunt lapides, dederunt in thesauros domus Domini per manum Jahiel Gersonitis.  

** I Chronicles 29:9

Lætatusque est populus cum vota sponte promitterent, quia corde toto offerebant ea Domino : sed et David rex lætatus est gaudio magno.

** I Chronicles 29:10

Et benedixit Domino coram universa multitudine, et ait : Benedictus es, Domine Deus Israël patris nostri, ab æterno in æternum.

** I Chronicles 29:11

Tua est, Domine, magnificentia, et potentia, et gloria, atque victoria : et tibi laus : cuncta enim quæ in cælo sunt et in terra, tua sunt : tuum, Domine, regnum, et tu es super omnes principes.

** I Chronicles 29:12

Tuæ divitiæ, et tua est gloria : tu dominaris omnium. In manu tua virtus et potentia : in manu tua magnitudo, et imperium omnium.

** I Chronicles 29:13

Nunc igitur Deus noster, confitemur tibi, et laudamus nomen tuum inclytum.

** I Chronicles 29:14

Quis ego, et quis populus meus, ut possimus hæc tibi universa promittere ? Tua sunt omnia : et quæ de manu tua accepimus, dedimus tibi.

** I Chronicles 29:15

Peregrini enim sumus coram te, et advenæ, sicut omnes patres nostri. Dies nostri quasi umbra super terram, et nulla est mora.

** I Chronicles 29:16

Domine Deus noster, omnis hæc copia quam paravimus ut ædificaretur domus nomini sancto tuo, de manu tua est, et tua sunt omnia.

** I Chronicles 29:17

Scio, Deus meus, quod probes corda, et simplicitatem diligas, unde et ego in simplicitate cordis mei lætus obtuli universa hæc : et populum tuum qui hic repertus est, vidi cum ingenti gaudio tibi offerre donaria.

** I Chronicles 29:18

Domine Deus Abraham, et Isaac, et Israël patrum nostrorum, custodi in æternum hanc voluntatem cordis eorum, et semper in venerationem tui mens ista permaneat.

** I Chronicles 29:19

Salomoni quoque filio meo da cor perfectum, ut custodiat mandata tua, testimonia tua, et cæremonias tuas, et faciat universa : et ædificet ædem, cujus impensas paravi.

** I Chronicles 29:20

Præcepit autem David universæ ecclesiæ : Benedicite Domino Deo nostro. Et benedixit omnis ecclesia Domino Deo patrum suorum : et inclinaverunt se, et adoraverunt Deum, et deinde regem.

** I Chronicles 29:21

Immolaveruntque victimas Domino : et obtulerunt holocausta die sequenti, tauros mille, arietes mille, agnos mille cum libaminibus suis, et universo ritu abundantissime in omnem Israël.

** I Chronicles 29:22

Et comederunt, et biberunt coram Domino in die illo cum grandi lætitia. Et unxerunt secundo Salomonem filium David. Unxerunt autem eum Domino in principem, et Sadoc in pontificem.

** I Chronicles 29:23

Seditque Salomon super solium Domini in regem pro David patre suo, et cunctis placuit : et paruit illi omnis Israël.

** I Chronicles 29:24

Sed et universi principes, et potentes, et cuncti filii regis David dederunt manum, et subjecti fuerunt Salomoni regi.

** I Chronicles 29:25

Magnificavit ergo Dominus Salomonem super omnem Israël : et dedit illi gloriam regni, qualem nullus habuit ante eum rex Israël.

** I Chronicles 29:26

Igitur David filius Isai regnavit super universum Israël.

** I Chronicles 29:27

Et dies quibus regnavit super Israël, fuerunt quadraginta anni : in Hebron regnavit septem annis, et in Jerusalem annis triginta tribus.

** I Chronicles 29:28

Et mortuus est in senectute bona, plenus dierum, et divitiis, et gloria : et regnavit Salomon filius ejus pro eo.  

** I Chronicles 29:29

Gesta autem David regis priora et novissima scripta sunt in libro Samuelis videntis, et in libro Nathan prophetæ, atque in volumine Gad videntis :

** I Chronicles 29:30

universique regni ejus, et fortitudinis, et temporum quæ transierunt sub eo, sive in Israël, sive in cunctis regnis terrarum.    

