* I Corinthians 1

** I Corinthians 1:1

Paulus vocatus Apostolus Jesu Christi per voluntatem Dei, et Sosthenes frater,

** I Corinthians 1:2

ecclesiæ Dei, quæ est Corinthi, sanctificatis in Christo Jesu, vocatis sanctis, cum omnibus qui invocant nomen Domini nostri Jesu Christi, in omni loco ipsorum et nostro.

** I Corinthians 1:3

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** I Corinthians 1:4

Gratias ago Deo meo semper pro vobis in gratia Dei, quæ data est vobis in Christo Jesu :

** I Corinthians 1:5

quod in omnibus divites facti estis in illo, in omni verbo, et in omni scientia.

** I Corinthians 1:6

Sicut testimonium Christi confirmatum est in vobis :

** I Corinthians 1:7

ita ut nihil vobis desit in ulla gratia, exspectantibus revelationem Domini nostri Jesu Christi,

** I Corinthians 1:8

qui et confirmabit vos usque in finem sine crimine, in die adventus Domini nostri Jesu Christi.

** I Corinthians 1:9

Fidelis Deus : per quem vocati estis in societatem filii ejus Jesu Christi Domini nostri.  

** I Corinthians 1:10

Obsecro autem vos fratres per nomen Domini nostri Jesu Christi : ut idipsum dicatis omnes, et non sint in vobis schismata : sitis autem perfecti in eodem sensu, et in eadem sententia.

** I Corinthians 1:11

Significatum est enim mihi de vobis fratres mei ab iis, qui sunt Chloës, quia contentiones sunt inter vos.

** I Corinthians 1:12

Hoc autem dico, quod unusquisque vestrum dicit : Ego quidem sum Pauli : ego autem Apollo : ego vero Cephæ : ego autem Christi.

** I Corinthians 1:13

Divisus est Christus ? numquid Paulus crucifixus est pro vobis ? aut in nomine Pauli baptizati estis ?

** I Corinthians 1:14

Gratias ago Deo, quod neminem vestrum baptizavi, nisi Crispum et Caium :

** I Corinthians 1:15

ne quis dicat quod in nomine meo baptizati estis.

** I Corinthians 1:16

Baptizavi autem et Stephanæ domum : ceterum nescio si quem alium baptizaverim.

** I Corinthians 1:17

Non enim misit me Christus baptizare, sed evangelizare : non in sapientia verbi, ut non evacuetur crux Christi.  

** I Corinthians 1:18

Verbum enim crucis pereuntibus quidem stultitia est : iis autem qui salvi fiunt, id est nobis, Dei virtus est.

** I Corinthians 1:19

Scriptum est enim : Perdam sapientiam sapientium, et prudentiam prudentium reprobabo.

** I Corinthians 1:20

Ubi sapiens ? ubi scriba ? ubi conquisitor hujus sæculi ? Nonne stultam fecit Deus sapientiam hujus mundi ?

** I Corinthians 1:21

Nam quia in Dei sapientia non cognovit mundus per sapientiam Deum : placuit Deo per stultitiam prædicationis salvos facere credentes.

** I Corinthians 1:22

Quoniam et Judæi signa petunt, et Græci sapientiam quærunt :

** I Corinthians 1:23

nos autem prædicamus Christum crucifixum : Judæis quidem scandalum, gentibus autem stultitiam,

** I Corinthians 1:24

ipsis autem vocatis Judæis, atque Græcis Christum Dei virtutem, et Dei sapientiam :

** I Corinthians 1:25

quia quod stultum est Dei, sapientius est hominibus : et quod infirmum est Dei, fortius est hominibus.

** I Corinthians 1:26

Videte enim vocationem vestram, fratres, quia non multi sapientes secundum carnem, non multi potentes, non multi nobiles :

** I Corinthians 1:27

sed quæ stulta sunt mundi elegit Deus, ut confundat sapientes : et infirma mundi elegit Deus, ut confundat fortia :

** I Corinthians 1:28

et ignobilia mundi, et contemptibilia elegit Deus, et ea quæ non sunt, ut ea quæ sunt destrueret :

** I Corinthians 1:29

ut non glorietur omnis caro in conspectu ejus.

** I Corinthians 1:30

Ex ipso autem vos estis in Christo Jesu, qui factus est nobis sapientia a Deo, et justitia, et sanctificatio, et redemptio :

** I Corinthians 1:31

ut quemadmodum scriptum est : Qui gloriatur, in Domino glorietur.   

* I Corinthians 2

** I Corinthians 2:1

Et ego, cum venissem ad vos, fratres, veni non in sublimitate sermonis, aut sapientiæ, annuntians vobis testimonium Christi.

** I Corinthians 2:2

Non enim judicavi me scire aliquid inter vos, nisi Jesum Christum, et hunc crucifixum.

** I Corinthians 2:3

Et ego in infirmitate, et timore, et tremore multo fui apud vos :

** I Corinthians 2:4

et sermo meus, et prædicatio mea non in persuasibilibus humanæ sapientiæ verbis, sed in ostensione spiritus et virtutis :

** I Corinthians 2:5

ut fides vestra non sit in sapientia hominum, sed in virtute Dei.  

** I Corinthians 2:6

Sapientiam autem loquimur inter perfectos : sapientiam vero non hujus sæculi, neque principum hujus sæculi, qui destruuntur :

** I Corinthians 2:7

sed loquimur Dei sapientiam in mysterio, quæ abscondita est, quam prædestinavit Deus ante sæcula in gloriam nostram,

** I Corinthians 2:8

quam nemo principum hujus sæculi cognovit : si enim cognovissent, numquam Dominum gloriæ crucifixissent.

** I Corinthians 2:9

Sed sicut scriptum est : Quod oculus non vidit, nec auris audivit, nec in cor hominis ascendit, quæ præparavit Deus iis qui diligunt illum :

** I Corinthians 2:10

nobis autem revelavit Deus per Spiritum suum : Spiritus enim omnia scrutatur, etiam profunda Dei.

** I Corinthians 2:11

Quis enim hominum scit quæ sunt hominis, nisi spiritus hominis, qui in ipso est ? ita et quæ Dei sunt, nemo cognovit, nisi Spiritus Dei.

** I Corinthians 2:12

Nos autem non spiritum hujus mundi accepimus, sed Spiritum qui ex Deo est, ut sciamus quæ a Deo donata sunt nobis :

** I Corinthians 2:13

quæ et loquimur non in doctis humanæ sapientiæ verbis, sed in doctrina Spiritus, spiritualibus spiritualia comparantes.

** I Corinthians 2:14

Animalis autem homo non percipit ea quæ sunt Spiritus Dei : stultitia enim est illi, et non potest intelligere : quia spiritualiter examinatur.

** I Corinthians 2:15

Spiritualis autem judicat omnia : et ipse a nemine judicatur.

** I Corinthians 2:16

Quis enim cognovit sensum Domini, qui instruat eum ? nos autem sensum Christi habemus.   

* I Corinthians 3

** I Corinthians 3:1

Et ego, fratres, non potui vobis loqui quasi spiritualibus, sed quasi carnalibus. Tamquam parvulis in Christo,

** I Corinthians 3:2

lac vobis potum dedi, non escam : nondum enim poteratis : sed nec nunc quidem potestis : adhuc enim carnales estis.

** I Corinthians 3:3

Cum enim sit inter vos zelus, et contentio : nonne carnales estis, et secundum hominem ambulatis ?

** I Corinthians 3:4

Cum enim quis dicat : Ego quidem sum Pauli ; alius autem : Ego Apollo : nonne homines estis ?   Quid igitur est Apollo ? quid vero Paulus ?

** I Corinthians 3:5

ministri ejus, cui credidistis, et unicuique sicut Dominus dedit.

** I Corinthians 3:6

Ego plantavi, Apollo rigavit : sed Deus incrementum dedit.

** I Corinthians 3:7

Itaque neque qui plantat est aliquid, neque qui rigat : sed qui incrementum dat, Deus.

** I Corinthians 3:8

Qui autem plantat, et qui rigat, unum sunt. Unusquisque autem propriam mercedem accipiet, secundum suum laborem.

** I Corinthians 3:9

Dei enim sumus adjutores : Dei agricultura estis, Dei ædificatio estis.

** I Corinthians 3:10

Secundum gratiam Dei, quæ data est mihi, ut sapiens architectus fundamentum posui : alius autem superædificat. Unusquisque autem videat quomodo superædificet.

** I Corinthians 3:11

Fundamentum enim aliud nemo potest ponere præter id quod positum est, quod est Christus Jesus.

** I Corinthians 3:12

Si quis autem superædificat super fundamentum hoc, aurum, argentum, lapides pretiosos, ligna, fœnum, stipulam,

** I Corinthians 3:13

uniuscujusque opus manifestum erit : dies enim Domini declarabit, quia in igne revelabitur : et uniuscujusque opus quale sit, ignis probabit.

** I Corinthians 3:14

Si cujus opus manserit quod superædificavit, mercedem accipiet.

** I Corinthians 3:15

Si cujus opus arserit, detrimentum patietur : ipse autem salvus erit, sic tamen quasi per ignem.

** I Corinthians 3:16

Nescitis quia templum Dei estis, et Spiritus Dei habitat in vobis ?

** I Corinthians 3:17

Si quis autem templum Dei violaverit, disperdet illum Deus. Templum enim Dei sanctum est, quod estis vos.  

** I Corinthians 3:18

Nemo se seducat : si quis videtur inter vos sapiens esse in hoc sæculo, stultus fiat ut sit sapiens.

** I Corinthians 3:19

Sapientia enim hujus mundi, stultitia est apud Deum. Scriptum est enim : Comprehendam sapientes in astutia eorum.

** I Corinthians 3:20

Et iterum : Dominus novit cogitationes sapientium quoniam vanæ sunt.

** I Corinthians 3:21

Nemo itaque glorietur in hominibus.

** I Corinthians 3:22

Omnia enim vestra sunt, sive Paulus, sive Apollo, sive Cephas, sive mundus, sive vita, sive mors, sive præsentia, sive futura : omnia enim vestra sunt :

** I Corinthians 3:23

vos autem Christi : Christus autem Dei.   

* I Corinthians 4

** I Corinthians 4:1

Sic nos existimet homo ut ministros Christi, et dispensatores mysteriorum Dei.

** I Corinthians 4:2

Hic jam quæritur inter dispensatores ut fidelis quis inveniatur.

** I Corinthians 4:3

Mihi autem pro minimo est ut a vobis judicer, aut ab humano die : sed neque meipsum judico.

** I Corinthians 4:4

Nihil enim mihi conscius sum, sed non in hoc justificatus sum : qui autem judicat me, Dominus est.

** I Corinthians 4:5

Itaque nolite ante tempus judicare, quoadusque veniat Dominus : qui et illuminabit abscondita tenebrarum, et manifestabit consilia cordium : et tunc laus erit unicuique a Deo.

** I Corinthians 4:6

Hæc autem, fratres, transfiguravi in me et Apollo, propter vos : ut in nobis discatis, ne supra quam scriptum est, unus adversus alterum infletur pro alio.

** I Corinthians 4:7

Quis enim te discernit ? quid autem habes quod non accepisti ? si autem accepisti, quid gloriaris quasi non acceperis ?  

** I Corinthians 4:8

Jam saturati estis, jam divites facti estis : sine nobis regnatis : et utinam regnetis, ut et nos vobiscum regnemus.

** I Corinthians 4:9

Puto enim quod Deus nos Apostolos novissimos ostendit, tamquam morti destinatos : quia spectaculum facti sumus mundo, et angelis, et hominibus.

** I Corinthians 4:10

Nos stulti propter Christum, vos autem prudentes in Christo : nos infirmi, vos autem fortes : vos nobiles, nos autem ignobiles.

** I Corinthians 4:11

Usque in hanc horam et esurimus, et sitimus, et nudi sumus, et colaphis cædimur, et instabiles sumus,

** I Corinthians 4:12

et laboramus operantes manibus nostris : maledicimur, et benedicimus : persecutionem patimur, et sustinemus :

** I Corinthians 4:13

blasphemamur, et obsecramus : tamquam purgamenta hujus mundi facti sumus, omnium peripsema usque adhuc.  

** I Corinthians 4:14

Non ut confundam vos, hæc scribo, sed ut filios meos carissimos moneo.

** I Corinthians 4:15

Nam si decem millia pædagogorum habeatis in Christo, sed non multos patres. Nam in Christo Jesu per Evangelium ego vos genui.

** I Corinthians 4:16

Rogo ergo vos, imitatores mei estote, sicut et ego Christi.

** I Corinthians 4:17

Ideo misi ad vos Timotheum, qui est filius meus carissimus, et fidelis in Domino : qui vos commonefaciet vias meas, quæ sunt in Christo Jesu, sicut ubique in omni ecclesia doceo.

** I Corinthians 4:18

Tamquam non venturus sim ad vos, sic inflati sunt quidam.

** I Corinthians 4:19

Veniam autem ad vos cito, si Dominus voluerit : et cognoscam non sermonem eorum qui inflati sunt, sed virtutem.

** I Corinthians 4:20

Non enim in sermone est regnum Dei, sed in virtute.

** I Corinthians 4:21

Quid vultis ? in virga veniam ad vos, an in caritate, et spiritu mansuetudinis ?   

* I Corinthians 5

** I Corinthians 5:1

Omnino auditur inter vos fornicatio, et talis fornicatio, qualis nec inter gentes, ita ut uxorem patris sui aliquis habeat.

** I Corinthians 5:2

Et vos inflati estis : et non magis luctum habuistis ut tollatur de medio vestrum qui hoc opus fecit.

** I Corinthians 5:3

Ego quidem absens corpore, præsens autem spiritu, jam judicavi ut præsens eum, qui sic operatus est,

** I Corinthians 5:4

in nomine Domini nostri Jesu Christi, congregatis vobis et meo spiritu, cum virtute Domini nostri Jesu,

** I Corinthians 5:5

tradere hujusmodi Satanæ in interitum carnis, ut spiritus salvus sit in die Domini nostri Jesu Christi.  

** I Corinthians 5:6

Non est bona gloriatio vestra. Nescitis quia modicum fermentum totam massam corrumpit ?

** I Corinthians 5:7

Expurgate vetus fermentum, ut sitis nova conspersio, sicut estis azymi. Etenim Pascha nostrum immolatus est Christus.

** I Corinthians 5:8

Itaque epulemur : non in fermento veteri, neque in fermento malitiæ et nequitiæ : sed in azymis sinceritatis et veritatis.

** I Corinthians 5:9

Scripsi vobis in epistola : Ne commisceamini fornicariis :

** I Corinthians 5:10

non utique fornicariis hujus mundi, aut avaris, aut rapacibus, aut idolis servientibus : alioquin debueratis de hoc mundo exiisse.

** I Corinthians 5:11

Nunc autem scripsi vobis non commisceri : si is qui frater nominatur, est fornicator, aut avarus, aut idolis serviens, aut maledicus, aut ebriosus, aut rapax, cum ejusmodi nec cibum sumere.

** I Corinthians 5:12

Quid enim mihi de iis qui foris sunt, judicare ? nonne de iis qui intus sunt, vos judicatis ?

** I Corinthians 5:13

nam eos qui foris sunt, Deus judicabit. Auferte malum ex vobis ipsis.   

* I Corinthians 6

** I Corinthians 6:1

Audet aliquis vestrum habens negotium adversus alterum, judicari apud iniquos, et non apud sanctos ?

** I Corinthians 6:2

an nescitis quoniam sancti de hoc mundo judicabunt ? et si in vobis judicabitur mundus, indigni estis qui de minimis judicetis ?

** I Corinthians 6:3

Nescitis quoniam angelos judicabimus ? quanto magis sæcularia ?

** I Corinthians 6:4

Sæcularia igitur judicia si habueritis : contemptibiles, qui sunt in ecclesia, illos constituite ad judicandum.

** I Corinthians 6:5

Ad verecundiam vestram dico. Sic non est inter vos sapiens quisquam, qui possit judicare inter fratrem suum ?

** I Corinthians 6:6

Sed frater cum fratre judicio contendit : et hoc apud infideles ?

** I Corinthians 6:7

Jam quidem omnino delictum est in vobis, quod judicia habetis inter vos. Quare non magis injuriam accipitis ? quare non magis fraudem patimini ?

** I Corinthians 6:8

Sed vos injuriam facitis, et fraudatis : et hoc fratribus.  

** I Corinthians 6:9

An nescitis quia iniqui regnum Dei non possidebunt ? Nolite errare : neque fornicarii, neque idolis servientes, neque adulteri,

** I Corinthians 6:10

neque molles, neque masculorum concubitores, neque fures, neque avari, neque ebriosi, neque maledici, neque rapaces regnum Dei possidebunt.

** I Corinthians 6:11

Et hæc quidam fuistis : sed abluti estis, sed sanctificati estis, sed justificati estis in nomine Domini nostri Jesu Christi, et in Spiritu Dei nostri.

** I Corinthians 6:12

Omnia mihi licent, sed non omnia expediunt : omnia mihi licent, sed ego sub nullis redigar potestate.

** I Corinthians 6:13

Esca ventri, et venter escis : Deus autem et hunc et has destruet : corpus autem non fornicationi, sed Domino : et Dominus corpori.

** I Corinthians 6:14

Deus vero et Dominum suscitavit : et nos suscitabit per virtutem suam.

** I Corinthians 6:15

Nescitis quoniam corpora vestra membra sunt Christi ? Tollens ergo membra Christi, faciam membra meretricis ? Absit.

** I Corinthians 6:16

An nescitis quoniam qui adhæret meretrici, unum corpus efficitur ? Erunt enim (inquit) duo in carne una.

** I Corinthians 6:17

Qui autem adhæret Domino, unus spiritus est.

** I Corinthians 6:18

Fugite fornicationem. Omne peccatum, quodcumque fecerit homo, extra corpus est : qui autem fornicatur, in corpus suum peccat.

** I Corinthians 6:19

An nescitis quoniam membra vestra, templum sunt Spiritus Sancti, qui in vobis est, quem habetis a Deo, et non estis vestri ?

** I Corinthians 6:20

Empti enim estis pretio magno. Glorificate, et portate Deum in corpore vestro.   

* I Corinthians 7

** I Corinthians 7:1

De quibus autem scripsistis mihi : Bonum est homini mulierem non tangere :

** I Corinthians 7:2

propter fornicationem autem unusquisque suam uxorem habeat, et unaquæque suum virum habeat.

** I Corinthians 7:3

Uxori vir debitum reddat : similiter autem et uxor viro.

** I Corinthians 7:4

Mulier sui corporis potestatem non habet, sed vir. Similiter autem et vir sui corporis potestatem non habet, sed mulier.

** I Corinthians 7:5

Nolite fraudare invicem, nisi forte ex consensu ad tempus, ut vacetis orationi : et iterum revertimini in idipsum, ne tentet vos Satanas propter incontinentiam vestram.

** I Corinthians 7:6

Hoc autem dico secundum indulgentiam, non secundum imperium.

** I Corinthians 7:7

Volo enim omnes vos esse sicut meipsum : sed unusquisque proprium donum habet ex Deo : alius quidem sic, alius vero sic.

** I Corinthians 7:8

Dico autem non nuptis, et viduis : bonum est illis si sic permaneant, sicut et ego.

** I Corinthians 7:9

Quod si non se continent, nubant. Melius est enim nubere, quam uri.  

** I Corinthians 7:10

Iis autem qui matrimonio juncti sunt, præcipio non ego, sed Dominus, uxorem a viro non discedere :

** I Corinthians 7:11

quod si discesserit, manere innuptam, aut viro suo reconciliari. Et vir uxorem non dimittat.  

** I Corinthians 7:12

Nam ceteris ego dico, non Dominus. Si quis frater uxorem habet infidelem, et hæc consentit habitare cum illo, non dimittat illam.

** I Corinthians 7:13

Et si qua mulier fidelis habet virum infidelem, et hic consentit habitare cum illa, non dimittat virum :

** I Corinthians 7:14

sanctificatus est enim vir infidelis per mulierem fidelem, et sanctificata est mulier infidelis per virum fidelem : alioquin filii vestri immundi essent, nunc autem sancti sunt.

** I Corinthians 7:15

Quod si infidelis discedit, discedat : non enim servituti subjectus est frater, aut soror in hujusmodi : in pace autem vocavit nos Deus.

** I Corinthians 7:16

Unde enim scis mulier, si virum salvum facies ? aut unde scis vir, si mulierem salvam facies ?  

** I Corinthians 7:17

Nisi unicuique sicut divisit Dominus, unumquemque sicut vocavit Deus, ita ambulet, et sicut in omnibus ecclesiis doceo.

** I Corinthians 7:18

Circumcisus aliquis vocatus est ? non adducat præputium. In præputio aliquis vocatus est ? non circumcidatur.

** I Corinthians 7:19

Circumcisio nihil est, et præputium nihil est : sed observatio mandatorum Dei.

** I Corinthians 7:20

Unusquisque in qua vocatione vocatus est, in ea permaneat.

** I Corinthians 7:21

Servus vocatus es ? non sit tibi curæ : sed et si potes fieri liber, magis utere.

** I Corinthians 7:22

Qui enim in Domino vocatus est servus, libertus est Domini : similiter qui liber vocatus est, servus est Christi.

** I Corinthians 7:23

Pretio empti estis : nolite fieri servi hominum.

** I Corinthians 7:24

Unusquisque in quo vocatus est, fratres, in hoc permaneat apud Deum.  

** I Corinthians 7:25

De virginibus autem præceptum Domini non habeo : consilium autem do, tamquam misericordiam consecutus a Domino, ut sim fidelis.

** I Corinthians 7:26

Existimo ergo hoc bonum esse propter instantem necessitatem, quoniam bonum est homini sic esse.

** I Corinthians 7:27

Alligatus es uxori ? noli quærere solutionem. Solutus es ab uxore ? noli quærere uxorem.

** I Corinthians 7:28

Si autem acceperis uxorem, non peccasti. Et si nupserit virgo, non peccavit : tribulationem tamen carnis habebunt hujusmodi. Ego autem vobis parco.

** I Corinthians 7:29

Hoc itaque dico, fratres : tempus breve est : reliquum est, ut et qui habent uxores, tamquam non habentes sint :

** I Corinthians 7:30

et qui flent, tamquam non flentes : et qui gaudent, tamquam non gaudentes : et qui emunt, tamquam non possidentes :

** I Corinthians 7:31

et qui utuntur hoc mundo, tamquam non utantur : præterit enim figura hujus mundi.

** I Corinthians 7:32

Volo autem vos sine sollicitudine esse. Qui sine uxore est, sollicitus est quæ Domini sunt, quomodo placeat Deo.

** I Corinthians 7:33

Qui autem cum uxore est, sollicitus est quæ sunt mundi, quomodo placeat uxori, et divisus est.

** I Corinthians 7:34

Et mulier innupta, et virgo, cogitat quæ Domini sunt, ut sit sancta corpore, et spiritu. Quæ autem nupta est, cogitat quæ sunt mundi, quomodo placeat viro.

** I Corinthians 7:35

Porro hoc ad utilitatem vestram dico : non ut laqueum vobis injiciam, sed ad id, quod honestum est, et quod facultatem præbeat sine impedimento Dominum obsecrandi.

** I Corinthians 7:36

Si quis autem turpem se videri existimat super virgine sua, quod sit superadulta, et ita oportet fieri : quod vult faciat : non peccat, si nubat.

** I Corinthians 7:37

Nam qui statuit in corde suo firmus, non habens necessitatem, potestatem autem habens suæ voluntatis, et hoc judicavit in corde suo, servare virginem suam, bene facit.

** I Corinthians 7:38

Igitur et qui matrimonio jungit virginem suam, bene facit : et qui non jungit, melius facit.

** I Corinthians 7:39

Mulier alligata est legi quanto tempore vir ejus vivit, quod si dormierit vir ejus, liberata est : cui vult nubat, tantum in Domino.

** I Corinthians 7:40

Beatior autem erit si sic permanserit secundum meum consilium : puto autem quod et ego Spiritum Dei habeam.   

* I Corinthians 8

** I Corinthians 8:1

De iis autem quæ idolis sacrificantur, scimus quia omnes scientiam habemus. Scientia inflat, caritas vero ædificat.

** I Corinthians 8:2

Si quis autem se existimat scire aliquid, nondum cognovit quemadmodum oporteat eum scire.

** I Corinthians 8:3

Si quis autem diligit Deum, hic cognitus est ab eo.

** I Corinthians 8:4

De escis autem quæ idolis immolantur, scimus quia nihil est idolum in mundo, et quod nullus est Deus, nisi unus.

** I Corinthians 8:5

Nam etsi sunt qui dicantur dii sive in cælo, sive in terra (siquidem sunt dii multi, et domini multi) :

** I Corinthians 8:6

nobis tamen unus est Deus, Pater, ex quo omnia, et nos in illum : et unus Dominus Jesus Christus, per quem omnia, et nos per ipsum.

** I Corinthians 8:7

Sed non in omnibus est scientia. Quidam autem cum conscientia usque nunc idoli, quasi idolothytum manducant : et conscientia ipsorum cum sit infirma, polluitur.

** I Corinthians 8:8

Esca autem nos non commendat Deo. Neque enim si manducaverimus, abundabimus : neque si non manducaverimus, deficiemus.

** I Corinthians 8:9

Videte autem ne forte hæc licentia vestra offendiculum fiat infirmis.

** I Corinthians 8:10

Si enim quis viderit eum, qui habet scientiam, in idolio recumbentem : nonne conscientia ejus, cum sit infirma, ædificabitur ad manducandum idolothyta ?

** I Corinthians 8:11

Et peribit infirmus in tua scientia, frater, propter quem Christus mortuus est ?

** I Corinthians 8:12

Sic autem peccantes in fratres, et percutientes conscientiam eorum infirmam, in Christum peccatis.

** I Corinthians 8:13

Quapropter si esca scandalizat fratrem meum, non manducabo carnem in æternum, ne fratrem meum scandalizem.   

* I Corinthians 9

** I Corinthians 9:1

Non sum liber ? non sum Apostolus ? nonne Christum Jesum Dominum nostrum vidi ? nonne opus meum vos estis in Domino ?

** I Corinthians 9:2

Et si aliis non sum Apostolus, sed tamen vobis sum : nam signaculum apostolatus mei vos estis in Domino.

** I Corinthians 9:3

Mea defensio apud eos qui me interrogant, hæc est :

** I Corinthians 9:4

Numquid non habemus potestatem manducandi et bibendi ?

** I Corinthians 9:5

numquid non habemus potestatem mulierem sororem circumducendi sicut et ceteri Apostoli, et fratres Domini, et Cephas ?

** I Corinthians 9:6

aut ego solus, et Barnabas, non habemus potestatem hoc operandi ?

** I Corinthians 9:7

Quis militat suis stipendiis umquam ? quis plantat vineam, et de fructu ejus non edit ? quis pascit gregem, et de lacte gregis non manducat ?

** I Corinthians 9:8

Numquid secundum hominem hæc dico ? an et lex hæc non dicit ?

** I Corinthians 9:9

Scriptum est enim in lege Moysi : Non alligabis os bovi trituranti. Numquid de bobus cura est Deo ?

** I Corinthians 9:10

an propter nos utique hoc dicit ? Nam propter nos scripta sunt : quoniam debet in spe qui arat, arare : et qui triturat, in spe fructus percipiendi.

** I Corinthians 9:11

Si nos vobis spiritualia seminavimus, magnum est si nos carnalia vestra metamus ?

** I Corinthians 9:12

Si alii potestatis vestræ participes sunt, quare non potius nos ? Sed non usi sumus hac potestate : sed omnia sustinemus, ne quod offendiculum demus Evangelio Christi.

** I Corinthians 9:13

Nescitis quoniam qui in sacrario operantur quæ de sacrario sunt, edunt : et qui altari deserviunt, cum altari participant ?

** I Corinthians 9:14

Ita et Dominus ordinavit iis qui Evangelium annuntiant, de Evangelio vivere.

** I Corinthians 9:15

Ego autem nullo horum usus sum. Non autem scripsi hæc ut ita fiant in me : bonum est enim mihi magis mori, quam ut gloriam meam quis evacuet.

** I Corinthians 9:16

Nam si evangelizavero, non est mihi gloria : necessitas enim mihi incumbit : væ enim mihi est, si non evangelizavero.

** I Corinthians 9:17

Si enim volens hoc ago, mercedem habeo : si autem invitus, dispensatio mihi credita est.

** I Corinthians 9:18

Quæ est ergo merces mea ? ut Evangelium prædicans, sine sumptu ponam Evangelium, ut non abutar potestate mea in Evangelio.  

** I Corinthians 9:19

Nam cum liber essem ex omnibus, omnium me servum feci, ut plures lucrifacerem.

** I Corinthians 9:20

Et factus sum Judæis tamquam Judæus, ut Judæos lucrarer :

** I Corinthians 9:21

iis qui sub lege sunt, quasi sub lege essem (cum ipse non essem sub lege) ut eos qui sub lege erant, lucrifacerem : iis qui sine lege erant, tamquam sine lege essem (cum sine lege Dei non essem : sed in lege essem Christi) ut lucrifacerem eos qui sine lege erant.

** I Corinthians 9:22

Factus sum infirmis infirmus, ut infirmos lucrifacerem. Omnibus omnia factus sum, ut omnes facerem salvos.

** I Corinthians 9:23

Omnia autem facio propter Evangelium : ut particeps ejus efficiar.

** I Corinthians 9:24

Nescitis quod ii qui in stadio currunt, omnes quidem currunt, sed unus accipit bravium ? Sic currite ut comprehendatis.

** I Corinthians 9:25

Omnis autem qui in agone contendit, ab omnibus se abstinet, et illi quidem ut corruptibilem coronam accipiant : nos autem incorruptam.

** I Corinthians 9:26

Ego igitur sic curro, non quasi in incertum : sic pugno, non quasi aërem verberans :

** I Corinthians 9:27

sed castigo corpus meum, et in servitutem redigo : ne forte cum aliis prædicaverim, ipse reprobus efficiar.   

* I Corinthians 10

** I Corinthians 10:1

Nolo enim vos ignorare fratres, quoniam patres nostri omnes sub nube fuerunt, et omnes mare transierunt,

** I Corinthians 10:2

et omnes in Moyse baptizati sunt in nube, et in mari :

** I Corinthians 10:3

et omnes eamdem escam spiritalem manducaverunt,

** I Corinthians 10:4

et omnes eumdem potum spiritalem biberunt (bibebant autem de spiritali, consequente eos, petra : petra autem erat Christus) :

** I Corinthians 10:5

sed non in pluribus eorum beneplacitum est Deo : nam prostrati sunt in deserto.

** I Corinthians 10:6

Hæc autem in figura facta sunt nostri, ut non simus concupiscentes malorum, sicut et illi concupierunt.

** I Corinthians 10:7

Neque idololatræ efficiamini, sicut quidam ex ipsis : quemadmodum scriptum est : Sedit populus manducare, et bibere, et surrexerunt ludere.

** I Corinthians 10:8

Neque fornicemur, sicut quidam ex ipsis fornicati sunt, et ceciderunt una die viginti tria millia.

** I Corinthians 10:9

Neque tentemus Christum, sicut quidam eorum tentaverunt, et a serpentibus perierunt.

** I Corinthians 10:10

Neque murmuraveritis, sicut quidam eorum murmuraverunt, et perierunt ab exterminatore.

** I Corinthians 10:11

Hæc autem omnia in figura contingebant illis : scripta sunt autem ad correptionem nostram, in quos fines sæculorum devenerunt.

** I Corinthians 10:12

Itaque qui se existimat stare, videat ne cadat.

** I Corinthians 10:13

Tentatio vos non apprehendat nisi humana : fidelis autem Deus est, qui non patietur vos tentari supra id quod potestis, sed faciet etiam cum tentatione proventum ut possitis sustinere.  

** I Corinthians 10:14

Propter quod, carissimi mihi, fugite ab idolorum cultura :

** I Corinthians 10:15

ut prudentibus loquor, vos ipsi judicate quod dico.

** I Corinthians 10:16

Calix benedictionis, cui benedicimus, nonne communicatio sanguinis Christi est ? et panis quem frangimus, nonne participatio corporis Domini est ?

** I Corinthians 10:17

Quoniam unus panis, unum corpus multi sumus, omnes qui de uno pane participamus.

** I Corinthians 10:18

Videte Israël secundum carnem : nonne qui edunt hostias, participes sunt altaris ?

** I Corinthians 10:19

Quid ergo ? dico quod idolis immolatum sit aliquid ? aut quod idolum, sit aliquid ?

** I Corinthians 10:20

Sed quæ immolant gentes, dæmoniis immolant, et non Deo. Nolo autem vos socios fieri dæmoniorum :

** I Corinthians 10:21

non potestis calicem Domini bibere, et calicem dæmoniorum ; non potestis mensæ Domini participes esse, et mensæ dæmoniorum.

** I Corinthians 10:22

An æmulamur Dominum ? numquid fortiores illo sumus ? Omnia mihi licent, sed non omnia expediunt.

** I Corinthians 10:23

Omnia mihi licent, sed non omnia ædificat.  

** I Corinthians 10:24

Nemo quod suum est quærat, sed quod alterius.

** I Corinthians 10:25

Omne quod in macello venit, manducate, nihil interrogantes propter conscientiam.

** I Corinthians 10:26

Domini est terra, et plenitudo ejus.

** I Corinthians 10:27

Si quis vocat vos infidelium, et vultis ire : omne quod vobis apponitur, manducate, nihil interrogantes propter conscientiam.

** I Corinthians 10:28

Si quis autem dixerit : Hoc immolatum est idolis : nolite manducare propter illum qui indicavit, et propter conscientiam :

** I Corinthians 10:29

conscientiam autem dico non tuam, sed alterius. Ut quid enim libertas mea judicatur ab aliena conscientia ?

** I Corinthians 10:30

Si ego cum gratia participo, quid blasphemor pro eo quod gratias ago ?

** I Corinthians 10:31

Sive ergo manducatis, sive bibitis, sive aliud quid facitis : omnia in gloriam Dei facite.

** I Corinthians 10:32

Sine offensione estote Judæis, et gentibus, et ecclesiæ Dei :

** I Corinthians 10:33

sicut et ego per omnia omnibus placeo, non quærens quod mihi utile est, sed quod multis : ut salvi fiant.   

* I Corinthians 11

** I Corinthians 11:1

Imitatores mei estote, sicut et ego Christi.

** I Corinthians 11:2

Laudo autem vos fratres quod per omnia mei memores estis : et sicut tradidi vobis, præcepta mea tenetis.

** I Corinthians 11:3

Volo autem vos scire quod omnis viri caput, Christus est : caput autem mulieris, vir : caput vero Christi, Deus.

** I Corinthians 11:4

Omnis vir orans, aut prophetans velato capite, deturpat caput suum.

** I Corinthians 11:5

Omnis autem mulier orans, aut prophetans non velato capite, deturpat caput suum : unum enim est ac si decalvetur.

** I Corinthians 11:6

Nam si non velatur mulier, tondeatur. Si vero turpe est mulieri tonderi, aut decalvari, velet caput suum.

** I Corinthians 11:7

Vir quidem non debet velare caput suum : quoniam imago et gloria Dei est, mulier autem gloria viri est.

** I Corinthians 11:8

Non enim vir ex muliere est, sed mulier ex viro.

** I Corinthians 11:9

Etenim non est creatus vir propter mulierem, sed mulier propter virum.

** I Corinthians 11:10

Ideo debet mulier potestatem habere supra caput propter angelos.

** I Corinthians 11:11

Verumtamen neque vir sine muliere : neque mulier sine viro in Domino.

** I Corinthians 11:12

Nam sicut mulier de viro, ita et vir per mulierem : omnia autem ex Deo.

** I Corinthians 11:13

Vos ipsi judicate : decet mulierem non velatam orare Deum ?

** I Corinthians 11:14

Nec ipsa natura docet vos, quod vir quidem si comam nutriat, ignominia est illi :

** I Corinthians 11:15

mulier vero si comam nutriat, gloria est illi : quoniam capilli pro velamine ei dati sunt.

** I Corinthians 11:16

Si quis autem videtur contentiosus esse : nos talem consuetudinem non habemus, neque ecclesia Dei.  

** I Corinthians 11:17

Hoc autem præcipio : non laudans quod non in melius, sed in deterius convenitis.

** I Corinthians 11:18

Primum quidem convenientibus vobis in ecclesiam, audio scissuras esse inter vos, et ex parte credo.

** I Corinthians 11:19

Nam oportet et hæreses esse, ut et qui probati sunt, manifesti fiant in vobis.

** I Corinthians 11:20

Convenientibus ergo vobis in unum, jam non est Dominicam cœnam manducare.

** I Corinthians 11:21

Unusquisque enim suam cœnam præsumit ad manducandum, et alius quidem esurit, alius autem ebrius est.

** I Corinthians 11:22

Numquid domos non habetis ad manducandum, et bibendum ? aut ecclesiam Dei contemnitis, et confunditis eos qui non habent ? Quid dicam vobis ? laudo vos ? in hoc non laudo.

** I Corinthians 11:23

Ego enim accepi a Domino quod et tradidi vobis, quoniam Dominus Jesus in qua nocte tradebatur, accepit panem,

** I Corinthians 11:24

et gratias agens fregit, et dixit : Accipite, et manducate : hoc est corpus meum, quod pro vobis tradetur : hoc facite in meam commemorationem.

** I Corinthians 11:25

Similiter et calicem, postquam cœnavit, dicens : Hic calix novum testamentum est in meo sanguine : hoc facite quotiescumque bibetis, in meam commemorationem.

** I Corinthians 11:26

Quotiescumque enim manducabitis panem hunc, et calicem bibetis, mortem Domini annuntiabitis donec veniat.

** I Corinthians 11:27

Itaque quicumque manducaverit panem hunc, vel biberit calicem Domini indigne, reus erit corporis et sanguinis Domini.

** I Corinthians 11:28

Probet autem seipsum homo : et sic de pane illo edat, et de calice bibat.

** I Corinthians 11:29

Qui enim manducat et bibit indigne, judicium sibi manducat et bibit, non dijudicans corpus Domini.

** I Corinthians 11:30

Ideo inter vos multi infirmi et imbecilles, et dormiunt multi.

** I Corinthians 11:31

Quod si nosmetipsos dijudicaremus, non utique judicaremur.

** I Corinthians 11:32

Dum judicamur autem, a Domino corripimur, ut non cum hoc mundo damnemur.

** I Corinthians 11:33

Itaque fratres mei, cum convenitis ad manducandum, invicem exspectate.

** I Corinthians 11:34

Si quis esurit, domi manducet, ut non in judicium conveniatis. Cetera autem, cum venero, disponam.   

* I Corinthians 12

** I Corinthians 12:1

De spiritualibus autem, nolo vos ignorare fratres.

** I Corinthians 12:2

Scitis quoniam cum gentes essetis, ad simulacra muta prout ducebamini euntes.

** I Corinthians 12:3

Ideo notum vobis facio, quod nemo in Spiritu Dei loquens, dicit anathema Jesu. Et nemo potest dicere, Dominus Jesus, nisi in Spiritu Sancto.

** I Corinthians 12:4

Divisiones vero gratiarum sunt, idem autem Spiritus :

** I Corinthians 12:5

et divisiones ministrationum sunt, idem autem Dominus :

** I Corinthians 12:6

et divisiones operationum sunt, idem vero Deus qui operatur omnia in omnibus.

** I Corinthians 12:7

Unicuique autem datur manifestatio Spiritus ad utilitatem.

** I Corinthians 12:8

Alii quidem per Spiritum datur sermo sapientiæ : alii autem sermo scientiæ secundum eumdem Spiritum :

** I Corinthians 12:9

alteri fides in eodem Spiritu : alii gratia sanitatum in uno Spiritu :

** I Corinthians 12:10

alii operatio virtutum, alii prophetia, alii discretio spirituum, alii genera linguarum, alii interpretatio sermonum.

** I Corinthians 12:11

Hæc autem omnia operatur unus atque idem Spiritus, dividens singulis prout vult.  

** I Corinthians 12:12

Sicut enim corpus unum est, et membra habet multa, omnia autem membra corporis cum sint multa, unum tamen corpus sunt : ita et Christus.

** I Corinthians 12:13

Etenim in uno Spiritu omnes nos in unum corpus baptizati sumus, sive Judæi, sive gentiles, sive servi, sive liberi : et omnes in uno Spiritu potati sumus.

** I Corinthians 12:14

Nam et corpus non est unum membrum, sed multa.

** I Corinthians 12:15

Si dixerit pes : Quoniam non sum manus, non sum de corpore : num ideo non est de corpore ?

** I Corinthians 12:16

Et si dixerit auris : Quoniam non sum oculus, non sum de corpore : num ideo est de corpore ?

** I Corinthians 12:17

Si totum corpus oculus : ubi auditus ? Si totum auditus : ubi odoratus ?

** I Corinthians 12:18

Nunc autem posuit Deus membra, unumquodque eorum in corpore sicut voluit.

** I Corinthians 12:19

Quod si essent omnia unum membrum, ubi corpus ?

** I Corinthians 12:20

Nunc autem multa quidem membra, unum autem corpus.

** I Corinthians 12:21

Non potest autem oculus dicere manui : Opera tua non indigeo : aut iterum caput pedibus : Non estis mihi necessarii.

** I Corinthians 12:22

Sed multo magis quæ videntur membra corporis infirmiora esse, necessariora sunt :

** I Corinthians 12:23

et quæ putamus ignobiliora membra esse corporis, his honorem abundantiorem circumdamus : et quæ inhonesta sunt nostra, abundantiorem honestatem habent.

** I Corinthians 12:24

Honesta autem nostra nullius egent : sed Deus temperavit corpus, ei cui deerat, abundantiorem tribuendo honorem,

** I Corinthians 12:25

ut non sit schisma in corpore, sed idipsum pro invicem sollicita sint membra.

** I Corinthians 12:26

Et si quid patitur unum membrum, compatiuntur omnia membra : sive gloriatur unum membrum, congaudent omnia membra.  

** I Corinthians 12:27

Vos autem estis corpus Christi, et membra de membro.

** I Corinthians 12:28

Et quosdam quidem posuit Deus in ecclesia primum apostolos, secundo prophetas, exinde doctores, deinde virtutes, exinde gratias curationum, opitulationes, gubernationes, genera linguarum, interpretationes sermonum.

** I Corinthians 12:29

Numquid omnes apostoli ? numquid omnes prophetæ ? numquid omnes doctores ?

** I Corinthians 12:30

numquid omnes virtutes ? numquid omnes gratiam habent curationum ? numquid omnes linguis loquuntur ? numquid omnes interpretantur ?

** I Corinthians 12:31

Æmulamini autem charismata meliora. Et adhuc excellentiorem viam vobis demonstro.   

* I Corinthians 13

** I Corinthians 13:1

Si linguis hominum loquar, et angelorum, caritatem autem non habeam, factus sum velut æs sonans, aut cymbalum tinniens.

** I Corinthians 13:2

Et si habuero prophetiam, et noverim mysteria omnia, et omnem scientiam : et si habuero omnem fidem ita ut montes transferam, caritatem autem non habuero, nihil sum.

** I Corinthians 13:3

Et si distribuero in cibos pauperum omnes facultates meas, et si tradidero corpus meum ita ut ardeam, caritatem autem non habuero, nihil mihi prodest.  

** I Corinthians 13:4

Caritas patiens est, benigna est. Caritas non æmulatur, non agit perperam, non inflatur,

** I Corinthians 13:5

non est ambitiosa, non quærit quæ sua sunt, non irritatur, non cogitat malum,

** I Corinthians 13:6

non gaudet super iniquitate, congaudet autem veritati :

** I Corinthians 13:7

omnia suffert, omnia credit, omnia sperat, omnia sustinet.  

** I Corinthians 13:8

Caritas numquam excidit : sive prophetiæ evacuabuntur, sive linguæ cessabunt, sive scientia destruetur.

** I Corinthians 13:9

Ex parte enim cognoscimus, et ex parte prophetamus.

** I Corinthians 13:10

Cum autem venerit quod perfectum est, evacuabitur quod ex parte est.

** I Corinthians 13:11

Cum essem parvulus, loquebar ut parvulus, sapiebam ut parvulus, cogitabam ut parvulus. Quando autem factus sum vir, evacuavi quæ erant parvuli.

** I Corinthians 13:12

Videmus nunc per speculum in ænigmate : tunc autem facie ad faciem. Nunc cognosco ex parte : tunc autem cognoscam sicut et cognitus sum.

** I Corinthians 13:13

Nunc autem manent fides, spes, caritas, tria hæc : major autem horum est caritas.   

* I Corinthians 14

** I Corinthians 14:1

Sectamini caritatem, æmulamini spiritualia : magis autem ut prophetetis.

** I Corinthians 14:2

Qui enim loquitur lingua, non hominibus loquitur, sed Deo : nemo enim audit. Spiritu autem loquitur mysteria.

** I Corinthians 14:3

Nam qui prophetat, hominibus loquitur ad ædificationem, et exhortationem, et consolationem.

** I Corinthians 14:4

Qui loquitur lingua, semetipsum ædificat : qui autem prophetat, ecclesiam Dei ædificat.

** I Corinthians 14:5

Volo autem omnes vos loqui linguis : magis autem prophetare. Nam major est qui prophetat, quam qui loquitur linguis ; nisi forte interpretetur ut ecclesia ædificationem accipiat.

** I Corinthians 14:6

Nunc autem, fratres, si venero ad vos linguis loquens : quid vobis prodero, nisi vobis loquar aut in revelatione, aut in scientia, aut in prophetia, aut in doctrina ?

** I Corinthians 14:7

Tamen quæ sine anima sunt vocem dantia, sive tibia, sive cithara ; nisi distinctionem sonituum dederint, quomodo scietur id quod canitur, aut quod citharizatur ?

** I Corinthians 14:8

Etenim si incertam vocem det tuba, quis parabit se ad bellum ?

** I Corinthians 14:9

Ita et vos per linguam nisi manifestum sermonem dederitis : quomodo scietur id quod dicitur ? eritis enim in aëra loquentes.

** I Corinthians 14:10

Tam multa, ut puta genera linguarum sunt in hoc mundo : et nihil sine voce est.

** I Corinthians 14:11

Si ergo nesciero virtutem vocis, ero ei, cui loquor, barbarus : et qui loquitur, mihi barbarus.

** I Corinthians 14:12

Sic et vos, quoniam æmulatores estis spirituum, ad ædificationem ecclesiæ quærite ut abundetis.

** I Corinthians 14:13

Et ideo qui loquitur lingua, oret ut interpretetur.

** I Corinthians 14:14

Nam si orem lingua, spiritus meus orat, mens autem mea sine fructu est.

** I Corinthians 14:15

Quid ergo est ? Orabo spiritu, orabo et mente : psallam spiritu, psallam et mente.

** I Corinthians 14:16

Ceterum si benedixeris spiritu, qui supplet locum idiotæ, quomodo dicet : Amen, super tuam benedictionem ? quoniam quid dicas, nescit.

** I Corinthians 14:17

Nam tu quidem bene gratias agis, sed alter non ædificatur.

** I Corinthians 14:18

Gratias ago Deo meo, quod omnium vestrum lingua loquor.

** I Corinthians 14:19

Sed in ecclesia volo quinque verba sensu meo loqui, ut et alios instruam : quam decem millia verborum in lingua.

** I Corinthians 14:20

Fratres, nolite pueri effici sensibus, sed malitia parvuli estote : sensibus autem perfecti estote.

** I Corinthians 14:21

In lege scriptum est : Quoniam in aliis linguis et labiis aliis loquar populo huic : et nec sic exaudient me, dicit Dominus.

** I Corinthians 14:22

Itaque linguæ in signum sunt non fidelibus, sed infidelibus : prophetiæ autem non infidelibus, sed fidelibus.

** I Corinthians 14:23

Si ergo conveniat universa ecclesia in unum, et omnes linguis loquantur, intrent autem idiotæ, aut infideles : nonne dicent quod insanitis ?

** I Corinthians 14:24

Si autem omnes prophetent, intret autem quis infidelis, vel idiota, convincitur ab omnibus, dijudicatur ab omnibus :

** I Corinthians 14:25

occulta cordis ejus manifesta fiunt : et ita cadens in faciem adorabit Deum, pronuntians quod vere Deus in vobis sit.  

** I Corinthians 14:26

Quid ergo est, fratres ? Cum convenitis, unusquisque vestrum psalmum habet, doctrinam habet, apocalypsim habet, linguam habet, interpretationem habet : omnia ad ædificationem fiant.

** I Corinthians 14:27

Sive lingua quis loquitur, secundum duos, aut ut multum tres, et per partes, et unus interpretatur.

** I Corinthians 14:28

Si autem non fuerit interpres, taceat in ecclesia : sibi autem loquatur, et Deo.

** I Corinthians 14:29

Prophetæ autem duo, aut tres dicant, et ceteri dijudicent.

** I Corinthians 14:30

Quod si alii revelatum fuerit sedenti, prior taceat.

** I Corinthians 14:31

Potestis enim omnes per singulos prophetare : ut omnes discant, et omnes exhortentur :

** I Corinthians 14:32

et spiritus prophetarum prophetis subjecti sunt.

** I Corinthians 14:33

Non enim est dissensionis Deus, sed pacis : sicut et in omnibus ecclesiis sanctorum doceo.

** I Corinthians 14:34

Mulieres in ecclesiis taceant, non enim permittitur eis loqui, sed subditas esse, sicut et lex dicit.

** I Corinthians 14:35

Si quid autem volunt discere, domi viros suos interrogent. Turpe est enim mulieri loqui in ecclesia.

** I Corinthians 14:36

An a vobis verbum Dei processit ? aut in vos solos pervenit ?

** I Corinthians 14:37

Si quis videtur propheta esse, aut spiritualis, cognoscat quæ scribo vobis, quia Domini sunt mandata.

** I Corinthians 14:38

Si quis autem ignorat, ignorabitur.

** I Corinthians 14:39

Itaque fratres æmulamini prophetare : et loqui linguis nolite prohibere.

** I Corinthians 14:40

Omnia autem honeste, et secundum ordinem fiant.   

* I Corinthians 15

** I Corinthians 15:1

Notum autem vobis facio, fratres, Evangelium, quod prædicavi vobis, quod et accepistis, in quo et statis,

** I Corinthians 15:2

per quod et salvamini : qua ratione prædicaverim vobis, si tenetis, nisi frustra credidistis.

** I Corinthians 15:3

Tradidi enim vobis in primis quod et accepi : quoniam Christus mortuus est pro peccatis nostris secundum Scripturas :

** I Corinthians 15:4

et quia sepultus est, et quia resurrexit tertia die secundum Scripturas :

** I Corinthians 15:5

et quia visus est Cephæ, et post hoc undecim :

** I Corinthians 15:6

deinde visus est plus quam quingentis fratribus simul : ex quibus multi manent usque adhuc, quidam autem dormierunt :

** I Corinthians 15:7

deinde visus est Jacobo, deinde Apostolis omnibus :

** I Corinthians 15:8

novissime autem omnium tamquam abortivo, visus est et mihi.

** I Corinthians 15:9

Ego enim sum minimus Apostolorum, qui non sum dignus vocari Apostolus, quoniam persecutus sum ecclesiam Dei.

** I Corinthians 15:10

Gratia autem Dei sum id quod sum, et gratia ejus in me vacua non fuit, sed abundantius illis omnibus laboravi : non ego autem, sed gratia Dei mecum :

** I Corinthians 15:11

sive enim ego, sive illi : sic prædicamus, et sic credidistis.  

** I Corinthians 15:12

Si autem Christus prædicatur quod resurrexit a mortuis, quomodo quidam dicunt in vobis, quoniam resurrectio mortuorum non est ?

** I Corinthians 15:13

Si autem resurrectio mortuorum non est : neque Christus resurrexit.

** I Corinthians 15:14

Si autem Christus non resurrexit, inanis est ergo prædicatio nostra, inanis est et fides vestra :

** I Corinthians 15:15

invenimur autem et falsi testes Dei : quoniam testimonium diximus adversus Deum quod suscitaverit Christum, quem non suscitavit, si mortui non resurgunt.

** I Corinthians 15:16

Nam si mortui non resurgunt, neque Christus resurrexit.

** I Corinthians 15:17

Quod si Christus non resurrexit, vana est fides vestra : adhuc enim estis in peccatis vestris.

** I Corinthians 15:18

Ergo et qui dormierunt in Christo, perierunt.

** I Corinthians 15:19

Si in hac vita tantum in Christo sperantes sumus, miserabiliores sumus omnibus hominibus.  

** I Corinthians 15:20

Nunc autem Christus resurrexit a mortuis primitiæ dormientium,

** I Corinthians 15:21

quoniam quidem per hominem mors, et per hominem resurrectio mortuorum.

** I Corinthians 15:22

Et sicut in Adam omnes moriuntur, ita et in Christo omnes vivificabuntur.

** I Corinthians 15:23

Unusquisque autem in suo ordine, primitiæ Christus : deinde ii qui sunt Christi, qui in adventu ejus crediderunt.

** I Corinthians 15:24

Deinde finis : cum tradiderit regnum Deo et Patri, cum evacuaverit omnem principatum, et potestatem, et virtutem.

** I Corinthians 15:25

Oportet autem illum regnare donec ponat omnes inimicos sub pedibus ejus.

** I Corinthians 15:26

Novissima autem inimica destruetur mors : omnia enim subjecit pedibus ejus. Cum autem dicat :

** I Corinthians 15:27

Omnia subjecta sunt ei, sine dubio præter eum qui subjecit ei omnia.

** I Corinthians 15:28

Cum autem subjecta fuerint illi omnia : tunc et ipse Filius subjectus erit ei, qui subjecit sibi omnia, ut sit Deus omnia in omnibus.

** I Corinthians 15:29

Alioquin quid facient qui baptizantur pro mortuis, si omnino mortui non resurgunt ? ut quid et baptizantur pro illis ?

** I Corinthians 15:30

ut quid et nos periclitamur omni hora ?

** I Corinthians 15:31

Quotidie morior per vestram gloriam, fratres, quam habeo in Christo Jesu Domino nostro.

** I Corinthians 15:32

Si secundum hominem ad bestias pugnavi Ephesi, quid mihi prodest, si mortui non resurgunt ? Manducemus, et bibamus, cras enim moriemur.

** I Corinthians 15:33

Nolite seduci : corrumpunt mores bonos colloquia mala.

** I Corinthians 15:34

Evigilate justi, et nolite peccare : ignorantiam enim Dei quidam habent, ad reverentiam vobis loquor.  

** I Corinthians 15:35

Sed dicet aliquis : Quomodo resurgunt mortui ? qualive corpore venient ?

** I Corinthians 15:36

Insipiens, tu quod seminas non vivificatur, nisi prius moriatur :

** I Corinthians 15:37

et quod seminas, non corpus, quod futurum est, seminas, sed nudum granum, ut puta tritici, aut alicujus ceterorum.

** I Corinthians 15:38

Deus autem dat illi corpus sicut vult : ut unicuique seminum proprium corpus.

** I Corinthians 15:39

Non omnis caro, eadem caro : sed alia quidem hominum, alia vero pecorum, alia volucrum, alia autem piscium.

** I Corinthians 15:40

Et corpora cælestia, et corpora terrestria : sed alia quidem cælestium gloria, alia autem terrestrium.

** I Corinthians 15:41

Alia claritas solis, alia claritas lunæ, et alia claritas stellarum. Stella enim a stella differt in claritate :

** I Corinthians 15:42

sic et resurrectio mortuorum. Seminatur in corruptione, surget in incorruptione.

** I Corinthians 15:43

Seminatur in ignobilitate, surget in gloria : seminatur in infirmitate, surget in virtute :

** I Corinthians 15:44

seminatur corpus animale, surget corpus spiritale. Si est corpus animale, est et spiritale, sicut scriptum est :

** I Corinthians 15:45

Factus est primus homo Adam in animam viventem, novissimus Adam in spiritum vivificantem.

** I Corinthians 15:46

Sed non prius quod spiritale est, sed quod animale : deinde quod spiritale.

** I Corinthians 15:47

Primus homo de terra, terrenus : secundus homo de cælo, cælestis.

** I Corinthians 15:48

Qualis terrenus, tales et terreni : et qualis cælestis, tales et cælestes.

** I Corinthians 15:49

Igitur, sicut portavimus imaginem terreni, portemus et imaginem cælestis.  

** I Corinthians 15:50

Hoc autem dico, fratres : quia caro et sanguis regnum Dei possidere non possunt : neque corruptio incorruptelam possidebit.

** I Corinthians 15:51

Ecce mysterium vobis dico : omnes quidem resurgemus, sed non omnes immutabimur.

** I Corinthians 15:52

In momento, in ictu oculi, in novissima tuba : canet enim tuba, et mortui resurgent incorrupti : et nos immutabimur.

** I Corinthians 15:53

Oportet enim corruptibile hoc induere incorruptionem : et mortale hoc induere immortalitatem.

** I Corinthians 15:54

Cum autem mortale hoc induerit immortalitatem, tunc fiet sermo, qui scriptus est : Absorpta est mors in victoria.

** I Corinthians 15:55

Ubi est mors victoria tua ? ubi est mors stimulus tuus ?

** I Corinthians 15:56

Stimulus autem mortis peccatum est : virtus vero peccati lex.

** I Corinthians 15:57

Deo autem gratias, qui dedit nobis victoriam per Dominum nostrum Jesum Christum.

** I Corinthians 15:58

Itaque fratres mei dilecti, stabiles estote, et immobiles : abundantes in opere Domini semper, scientes quod labor vester non est inanis in Domino.   

* I Corinthians 16

** I Corinthians 16:1

De collectis autem, quæ fiunt in sanctos, sicut ordinavi ecclesiis Galatiæ, ita et vos facite.

** I Corinthians 16:2

Per unam sabbati unusquisque vestrum apud se seponat, recondens quod ei bene placuerit : ut non, cum venero, tunc collectæ fiant.

** I Corinthians 16:3

Cum autem præsens fuero, quos probaveritis per epistolas, hos mittam perferre gratiam vestram in Jerusalem.

** I Corinthians 16:4

Quod si dignum fuerit ut et ego eam, mecum ibunt.  

** I Corinthians 16:5

Veniam autem ad vos, cum Macedoniam pertransiero : nam Macedoniam pertransibo.

** I Corinthians 16:6

Apud vos autem forsitan manebo, vel etiam hiemabo : ut vos me deducatis quocumque iero.

** I Corinthians 16:7

Nolo enim vos modo in transitu videre, spero enim me aliquantulum temporis manere apud vos, si Dominus permiserit.

** I Corinthians 16:8

Permanebo autem Ephesi usque ad Pentecosten.

** I Corinthians 16:9

Ostium enim mihi apertum est magnum, et evidens : et adversarii multi.  

** I Corinthians 16:10

Si autem venerit Timotheus, videte ut sine timore sit apud vos : opus enim Domini operatur, sicut et ego.

** I Corinthians 16:11

Ne quis ergo illum spernat : deducite autem illum in pace, ut veniat ad me : exspecto enim illum cum fratribus.

** I Corinthians 16:12

De Apollo autem fratre vobis notum facio, quoniam multum rogavi eum ut veniret ad vos cum fratribus : et utique non fuit voluntas ut nunc veniret : veniet autem, cum ei vacuum fuerit.

** I Corinthians 16:13

Vigilate, state in fide, viriliter agite, et confortamini.

** I Corinthians 16:14

Omnia vestra in caritate fiant.

** I Corinthians 16:15

Obsecro autem vos fratres, nostis domum Stephanæ, et Fortunati, et Achaici : quoniam sunt primitiæ Achaiæ, et in ministerium sanctorum ordinaverunt seipsos :

** I Corinthians 16:16

ut et vos subditi sitis ejusmodi, et omni cooperanti, et laboranti.

** I Corinthians 16:17

Gaudeo autem in præsentia Stephanæ, et Fortunati, et Achaici : quoniam id, quod vobis deerat, ipsi suppleverunt :

** I Corinthians 16:18

refecerunt enim et meum spiritum, et vestrum. Cognoscite ergo qui hujusmodi sunt.  

** I Corinthians 16:19

Salutant vos ecclesiæ Asiæ. Salutant vos in Domino multum, Aquila et Priscilla cum domestica sua ecclesia : apud quos et hospitor.

** I Corinthians 16:20

Salutant vos omnes fratres. Salutate invicem in osculo sancto.

** I Corinthians 16:21

Salutatio, mea manu Pauli.

** I Corinthians 16:22

Si quis non amat Dominum nostrum Jesum Christum, sit anathema, Maran Atha.

** I Corinthians 16:23

Gratia Domini nostri Jesu Christi vobiscum.

** I Corinthians 16:24

Caritas mea cum omnibus vobis in Christo Jesu. Amen.    

