* I Kings 1

** I Kings 1:1

Et rex David senuerat, habebatque ætatis plurimos dies : cumque operiretur vestibus, non calefiebat.

** I Kings 1:2

Dixerunt ergo ei servi sui : Quæramus domino nostro regi adolescentulam virginem, et stet coram rege, et foveat eum, dormiatque in sinu suo, et calefaciat dominum nostrum regem.

** I Kings 1:3

Quæsierunt igitur adolescentulam speciosam in omnibus finibus Israël, et invenerunt Abisag Sunamitidem, et adduxerunt eam ad regem.

** I Kings 1:4

Erat autem puella pulchra nimis, dormiebatque cum rege, et ministrabat ei : rex vero non cognovit eam.  

** I Kings 1:5

Adonias autem filius Haggith elevabatur, dicens : Ego regnabo. Fecitque sibi currus et equites, et quinquaginta viros qui currerent ante eum.

** I Kings 1:6

Nec corripuit eum pater suus aliquando, dicens : Quare hoc fecisti ? Erat autem et ipse pulcher valde, secundus natu post Absalom.

** I Kings 1:7

Et sermo ei cum Joab filio Sarviæ, et cum Abiathar sacerdote, qui adjuvabant partes Adoniæ.

** I Kings 1:8

Sadoc vero sacerdos, et Banaias filius Jojadæ, et Nathan propheta, et Semei et Rei, et robur exercitus David, non erat cum Adonia.

** I Kings 1:9

Immolatis ergo Adonias arietibus et vitulis, et universis pinguibus, juxta lapidem Zoheleth, qui erat vicinus fonti Rogel, vocavit universos fratres suos filios regis, et omnes viros Juda servos regis.

** I Kings 1:10

Nathan autem prophetam, et Banaiam, et robustos quosque, et Salomonem fratrem suum non vocavit.  

** I Kings 1:11

Dixit itaque Nathan ad Bethsabee matrem Salomonis : Num audisti quod regnaverit Adonias filius Haggith, et dominus noster David hoc ignorat ?

** I Kings 1:12

Nunc ergo veni, accipe consilium a me, et salva animam tuam, filiique tui Salomonis.

** I Kings 1:13

Vade, et ingredere ad regem David, et dic ei : Nonne tu, domine mi rex, jurasti mihi ancillæ tuæ, dicens : Salomon filius tuus regnabit post me, et ipse sedebit in solio meo ? quare ergo regnat Adonias ?

** I Kings 1:14

Et adhuc ibi te loquente cum rege, ego veniam post te, et complebo sermones tuos.

** I Kings 1:15

Ingressa est itaque Bethsabee ad regem in cubiculum : rex autem senuerat nimis, et Abisag Sunamitis ministrabat ei.

** I Kings 1:16

Inclinavit se Bethsabee, et adoravit regem. Ad quam rex : Quid tibi, inquit, vis ?

** I Kings 1:17

Quæ respondens, ait : Domine mi, tu jurasti per Dominum Deum tuum ancillæ tuæ : Salomon filius tuus regnabit post me, et ipse sedebit in solio meo.

** I Kings 1:18

Et ecce nunc Adonias regnat, te, domine mi rex, ignorante.

** I Kings 1:19

Mactavit boves, et pinguia quæque, et arietes plurimos, et vocavit omnes filios regis, Abiathar quoque sacerdotem, et Joab principem militiæ : Salomonem autem servum tuum non vocavit.

** I Kings 1:20

Verumtamen, domine mi rex, in te oculi respiciunt totius Israël, ut indices eis quis sedere debeat in solio tuo, domine mi rex, post te.

** I Kings 1:21

Eritque, cum dormierit dominus meus rex cum patribus suis, erimus ego et filius meus Salomon peccatores.  

** I Kings 1:22

Adhuc illa loquente cum rege, Nathan propheta venit.

** I Kings 1:23

Et nuntiaverunt regi, dicentes : Adest Nathan propheta. Cumque introisset in conspectu regis, et adorasset eum pronus in terram,

** I Kings 1:24

dixit Nathan : Domine mi rex, tu dixisti : Adonias regnet post me, et ipse sedeat super thronum meum ?

** I Kings 1:25

Quia descendit hodie, et immolavit boves, et pinguia, et arietes plurimos, et vocavit universos filios regis et principes exercitus, Abiathar quoque sacerdotem, illisque vescentibus et bibentibus coram eo, et dicentibus : Vivat rex Adonias :

** I Kings 1:26

me servum tuum, et Sadoc sacerdotem, et Banaiam filium Jojadæ, et Salomonem famulum tuum non vocavit.

** I Kings 1:27

Numquid a domino meo rege exivit hoc verbum, et mihi non indicasti servo tuo quis sessurus esset super thronum domini mei regis post eum ?

** I Kings 1:28

Et respondit rex David, dicens : Vocate ad me Bethsabee. Quæ cum fuisset ingressa coram rege, et stetisset ante eum,

** I Kings 1:29

juravit rex, et ait : Vivit Dominus, qui eruit animam meam de omni angustia,

** I Kings 1:30

quia sicut juravi tibi per Dominum Deum Israël, dicens : Salomon filius tuus regnabit post me, et ipse sedebit super solium meum pro me : sic faciam hodie.

** I Kings 1:31

Summissoque Bethsabee in terram vultu, adoravit regem, dicens : Vivat dominus meus David in æternum.  

** I Kings 1:32

Dixit quoque rex David : Vocate mihi Sadoc sacerdotem, et Nathan prophetam, et Banaiam filium Jojadæ. Qui cum ingressi fuissent coram rege,

** I Kings 1:33

dixit ad eos : Tollite vobiscum servos domini vestri, et imponite Salomonem filium meum super mulam meam, et ducite eum in Gihon.

** I Kings 1:34

Et ungat eum ibi Sadoc sacerdos et Nathan propheta in regem super Israël : et canetis buccina, atque dicetis : Vivat rex Salomon.

** I Kings 1:35

Et ascendetis post eum, et veniet, et sedebit super solium meum, et ipse regnabit pro me : illique præcipiam ut sit dux super Israël et super Judam.

** I Kings 1:36

Et respondit Banaias filius Jojadæ regi, dicens : Amen : sic loquatur Dominus Deus domini mei regis.

** I Kings 1:37

Quomodo fuit Dominus cum domino meo rege, sic sit cum Salomone, et sublimius faciat solium ejus a solio domini mei regis David.

** I Kings 1:38

Descendit ergo Sadoc sacerdos, et Nathan propheta, et Banaias filius Jojadæ, et Cerethi, et Phelethi : et imposuerunt Salomonem super mulam regis David, et adduxerunt eum in Gihon.

** I Kings 1:39

Sumpsitque Sadoc sacerdos cornu olei de tabernaculo, et unxit Salomonem : et cecinerunt buccina, et dixit omnis populus : Vivat rex Salomon.

** I Kings 1:40

Et ascendit universa multitudo post eum, et populus canentium tibiis, et lætantium gaudio magno : et insonuit terra a clamore eorum.  

** I Kings 1:41

Audivit autem Adonias, et omnes qui invitati fuerant ab eo : jamque convivium finitum erat : sed et Joab, audita voce tubæ, ait : Quid sibi vult clamor civitatis tumultuantis ?

** I Kings 1:42

Adhuc illo loquente, Jonathas filius Abiathar sacerdotis venit : cui dixit Adonias : Ingredere, quia vir fortis es, et bona nuntians.

** I Kings 1:43

Responditque Jonathas Adoniæ : Nequaquam : dominus enim noster rex David regem constituit Salomonem :

** I Kings 1:44

misitque cum eo Sadoc sacerdotem, et Nathan prophetam, et Banaiam filium Jojadæ, et Cerethi, et Phelethi, et imposuerunt eum super mulam regis.

** I Kings 1:45

Unxeruntque eum Sadoc sacerdos et Nathan propheta regem in Gihon : et ascenderunt inde lætantes, et insonuit civitas : hæc est vox quam audistis.

** I Kings 1:46

Sed et Salomon sedet super solium regni.

** I Kings 1:47

Et ingressi servi regis benedixerunt domino nostro regi David, dicentes : Amplificet Deus nomen Salomonis super nomen tuum, et magnificet thronus ejus super thronum tuum. Et adoravit rex in lectulo suo :

** I Kings 1:48

et locutus est : Benedictus Dominus Deus Israël, qui dedit hodie sedentem in solio meo, videntibus oculis meis.  

** I Kings 1:49

Territi sunt ergo, et surrexerunt omnes qui invitati fuerant ab Adonia, et ivit unusquisque in viam suam.

** I Kings 1:50

Adonias autem timens Salomonem, surrexit, et abiit, tenuitque cornu altaris.

** I Kings 1:51

Et nuntiaverunt Salomoni, dicentes : Ecce Adonias timens regem Salomonem, tenuit cornu altaris, dicens : Juret mihi rex Salomon hodie, quod non interficiat servum suum gladio.

** I Kings 1:52

Dixitque Salomon : Si fuerit vir bonus, non cadet ne unus quidem capillus ejus in terram : sin autem malum inventum fuerit in eo, morietur.

** I Kings 1:53

Misit ergo rex Salomon, et eduxit eum ab altari : et ingressus adoravit regem Salomonem : dixitque ei Salomon : Vade in domum tuam.   

* I Kings 2

** I Kings 2:1

Appropinquaverunt autem dies David ut moreretur : præcepitque Salomoni filio suo, dicens :

** I Kings 2:2

Ego ingredior viam universæ terræ : confortare, et esto vir.

** I Kings 2:3

Et observa custodias Domini Dei tui, ut ambules in viis ejus : ut custodias cæremonias ejus, et præcepta ejus, et judicia, et testimonia, sicut scriptum est in lege Moysi : ut intelligas universa quæ facis, et quocumque te verteris :

** I Kings 2:4

ut confirmet Dominus sermones suos quos locutus est de me, dicens : Si custodierint filii tui vias suas, et ambulaverint coram me in veritate, in omni corde suo et in omni anima sua, non auferetur tibi vir de solio Israël.

** I Kings 2:5

Tu quoque nosti quæ fecerit mihi Joab filius Sarviæ, quæ fecerit duobus principibus exercitus Israël, Abner filio Ner, et Amasæ filio Jether : quos occidit, et effudit sanguinem belli in pace, et posuit cruorem prælii in balteo suo qui erat circa lumbos ejus, et in calceamento suo quod erat in pedibus ejus.

** I Kings 2:6

Facies ergo juxta sapientiam tuam, et non deduces canitiem ejus pacifice ad inferos.

** I Kings 2:7

Sed et filiis Berzellai Galaaditis reddes gratiam, eruntque comedentes in mensa tua : occurrerunt enim mihi quando fugiebam a facie Absalom fratris tui.

** I Kings 2:8

Habes quoque apud te Semei filium Gera filii Jemini de Bahurim, qui maledixit mihi maledictione pessima quando ibam ad castra : sed quia descendit mihi in occursum cum transirem Jordanem, et juravi ei per Dominum, dicens : Non te interficiam gladio :

** I Kings 2:9

tu noli pati eum esse innoxium. Vir autem sapiens es, ut scias quæ facies ei : deducesque canos ejus cum sanguine ad inferos.

** I Kings 2:10

Dormivit igitur David cum patribus suis, et sepultus est in civitate David.

** I Kings 2:11

Dies autem quibus regnavit David super Israël, quadraginta anni sunt : in Hebron regnavit septem annis ; in Jerusalem, triginta tribus.  

** I Kings 2:12

Salomon autem sedit super thronum David patris sui, et firmatum est regnum ejus nimis.

** I Kings 2:13

Et ingressus est Adonias filius Haggith ad Bethsabee matrem Salomonis. Quæ dixit ei : Pacificusne est ingressus tuus ? Qui respondit : Pacificus.

** I Kings 2:14

Addiditque : Sermo mihi est ad te. Cui ait : Loquere. Et ille :

** I Kings 2:15

Tu, inquit, nosti, quia meum erat regnum, et me præposuerat omnis Israël sibi in regem : sed translatum est regnum, et factum est fratris mei : a Domino enim constitutum est ei.

** I Kings 2:16

Nunc ergo petitionem unam precor a te : ne confundas faciem meam. Quæ dixit ad eum : Loquere.

** I Kings 2:17

Et ille ait : Precor ut dicas Salomoni regi (neque enim negare tibi quidquam potest) ut det mihi Abisag Sunamitidem uxorem.

** I Kings 2:18

Et ait Bethsabee : Bene : ego loquar pro te regi.

** I Kings 2:19

Venit ergo Bethsabee ad regem Salomonem ut loqueretur ei pro Adonia : et surrexit rex in occursum ejus, adoravitque eam, et sedit super thronum suum : positusque est thronus matri regis, quæ sedit ad dexteram ejus.

** I Kings 2:20

Dixitque ei : Petitionem unam parvulam ego deprecor a te : ne confundas faciem meam. Et dixit ei rex : Pete, mater mea : neque enim fas est ut avertam faciem tuam.

** I Kings 2:21

Quæ ait : Detur Abisag Sunamitis Adoniæ fratri tuo uxor.

** I Kings 2:22

Responditque rex Salomon, et dixit matri suæ : Quare postulas Abisag Sunamitidem Adoniæ ? postula ei et regnum : ipse est enim frater meus major me, et habet Abiathar sacerdotem, et Joab filium Sarviæ.

** I Kings 2:23

Juravit itaque rex Salomon per Dominum, dicens : Hæc faciat mihi Deus, et hæc addat, quia contra animam suam locutus est Adonias verbum hoc.

** I Kings 2:24

Et nunc vivit Dominus, qui firmavit me, et collocavit me super solium David patris mei, et qui fecit mihi domum, sicut locutus est, quia hodie occidetur Adonias.

** I Kings 2:25

Misitque rex Salomon per manum Banaiæ filii Jojadæ, qui interfecit eum, et mortuus est.

** I Kings 2:26

Abiathar quoque sacerdoti dixit rex : Vade in Anathoth ad agrum tuum : equidem vir mortis es : sed hodie te non interficiam, quia portasti arcam Domini Dei coram David patre meo, et sustinuisti laborem in omnibus in quibus laboravit pater meus.

** I Kings 2:27

Ejecit ergo Salomon Abiathar ut non esset sacerdos Domini, ut impleretur sermo Domini quem locutus est super domum Heli in Silo.  

** I Kings 2:28

Venit autem nuntius ad Joab, quod Joab declinasset post Adoniam, et post Salomonem non declinasset : fugit ergo Joab in tabernaculum Domini, et apprehendit cornu altaris.

** I Kings 2:29

Nuntiatumque est regi Salomoni quod fugisset Joab in tabernaculum Domini, et esset juxta altare : misitque Salomon Banaiam filium Jojadæ, dicens : Vade, interfice eum.

** I Kings 2:30

Et venit Banaias ad tabernaculum Domini, et dixit ei : Hæc dicit rex : Egredere. Qui ait : Non egrediar, sed hic moriar. Renuntiavit Banaias regi sermonem, dicens : Hæc locutus est Joab, et hæc respondit mihi.

** I Kings 2:31

Dixitque ei rex : Fac sicut locutus est, et interfice eum, et sepeli : et amovebis sanguinem innocentem qui effusus est a Joab, a me, et a domo patris mei.

** I Kings 2:32

Et reddet Dominus sanguinem ejus super caput ejus, quia interfecit duos viros justos, melioresque se : et occidit eos gladio, patre meo David ignorante, Abner filium Ner principem militiæ Israël, et Amasam filium Jether principem exercitus Juda :

** I Kings 2:33

et revertetur sanguis illorum in caput Joab, et in caput seminis ejus in sempiternum. David autem et semini ejus, et domui, et throno illius, sit pax usque in æternum a Domino.

** I Kings 2:34

Ascendit itaque Banaias filius Jojadæ, et aggressus eum interfecit : sepultusque est in domo sua in deserto.

** I Kings 2:35

Et constituit rex Banaiam filium Jojadæ pro eo super exercitum, et Sadoc sacerdotem posuit pro Abiathar.  

** I Kings 2:36

Misit quoque rex, et vocavit Semei : dixitque ei : Ædifica tibi domum in Jerusalem, et habita ibi : et non egredieris inde huc atque illuc.

** I Kings 2:37

Quacumque autem die egressus fueris, et transieris torrentem Cedron, scito te interficiendum : sanguis tuus erit super caput tuum.

** I Kings 2:38

Dixitque Semei regi : Bonus sermo : sicut locutus est dominus meus rex, sic faciet servus tuus. Habitavit itaque Semei in Jerusalem diebus multis.

** I Kings 2:39

Factum est autem post annos tres ut fugerent servi Semei ad Achis filium Maacha regem Geth : nuntiatumque est Semei quod servi ejus issent in Geth.

** I Kings 2:40

Et surrexit Semei, et stravit asinum suum, ivitque ad Achis in Geth ad requirendum servos suos, et adduxit eos de Geth.

** I Kings 2:41

Nuntiatum est autem Salomoni quod isset Semei in Geth de Jerusalem, et rediisset.

** I Kings 2:42

Et mittens vocavit eum, dixitque illi : Nonne testificatus sum tibi per Dominum, et prædixi tibi : Quacumque die egressus ieris huc et illuc, scito te esse moriturum : et respondisti mihi : Bonus sermo, quem audivi ?

** I Kings 2:43

quare ergo non custodisti jusjurandum Domini, et præceptum quod præceperam tibi ?

** I Kings 2:44

Dixitque rex ad Semei : Tu nosti omne malum cujus tibi conscium est cor tuum, quod fecisti David patri meo : reddidit Dominus malitiam tuam in caput tuum :

** I Kings 2:45

et rex Salomon benedictus, et thronus David erit stabilis coram Domino usque in sempiternum.

** I Kings 2:46

Jussit itaque rex Banaiæ filio Jojadæ, qui egressus, percussit eum, et mortuus est.   

* I Kings 3

** I Kings 3:1

Confirmatum est igitur regnum in manu Salomonis, et affinitate conjunctus est Pharaoni regi Ægypti : accepit namque filiam ejus, et adduxit in civitatem David, donec compleret ædificans domum suam, et domum Domini, et murum Jerusalem per circuitum.

** I Kings 3:2

Attamen populus immolabat in excelsis : non enim ædificatum erat templum nomini Domini usque in diem illum.

** I Kings 3:3

Dilexit autem Salomon Dominum, ambulans in præceptis David patris sui, excepto quod in excelsis immolabat, et accendebat thymiama.

** I Kings 3:4

Abiit itaque in Gabaon, ut immolaret ibi : illud quippe erat excelsum maximum : mille hostias in holocaustum obtulit Salomon super altare illud in Gabaon.

** I Kings 3:5

Apparuit autem Dominus Salomoni per somnium nocte, dicens : Postula quod vis ut dem tibi.

** I Kings 3:6

Et ait Salomon : Tu fecisti cum servo tuo David patre meo misericordiam magnam, sicut ambulavit in conspectu tuo in veritate et justitia, et recto corde tecum : custodisti ei misericordiam tuam grandem, et dedisti ei filium sedentem super thronum ejus, sicut est hodie.

** I Kings 3:7

Et nunc Domine Deus, tu regnare fecisti servum tuum pro David patre meo : ego autem sum puer parvulus, et ignorans egressum et introitum meum.

** I Kings 3:8

Et servus tuus in medio est populi quem elegisti, populi infiniti, qui numerari et supputari non potest præ multitudine.

** I Kings 3:9

Dabis ergo servo tuo cor docile, ut populum tuum judicare possit, et discernere inter bonum et malum. Quis enim poterit judicare populum istum, populum tuum hunc multum ?  

** I Kings 3:10

Placuit ergo sermo coram Domino, quod Salomon postulasset hujuscemodi rem.

** I Kings 3:11

Et dixit Dominus Salomoni : Quia postulasti verbum hoc, et non petisti tibi dies multos, nec divitias, aut animas inimicorum tuorum, sed postulasti tibi sapientiam ad discernendum judicium :

** I Kings 3:12

ecce feci tibi secundum sermones tuos, et dedi tibi cor sapiens et intelligens, in tantum ut nullus ante te similis tui fuerit, nec post te surrecturus sit.

** I Kings 3:13

Sed et hæc quæ non postulasti, dedi tibi : divitias scilicet, et gloriam, ut nemo fuerit similis tui in regibus cunctis retro diebus.

** I Kings 3:14

Si autem ambulaveris in viis meis, et custodieris præcepta mea et mandata mea, sicut ambulavit pater tuus, longos faciam dies tuos.

** I Kings 3:15

Igitur evigilavit Salomon, et intellexit quod esset somnium : cumque venisset Jerusalem, stetit coram arca fœderis Domini, et obtulit holocausta, et fecit victimas pacificas, et grande convivium universis famulis suis.  

** I Kings 3:16

Tunc venerunt duæ mulieres meretrices ad regem, steteruntque coram eo :

** I Kings 3:17

quarum una ait : Obsecro, mi domine : ego et mulier hæc habitabamus in domo una, et peperi apud eam in cubiculo.

** I Kings 3:18

Tertia autem die postquam ego peperi, peperit et hæc : et eramus simul, nullusque alius nobiscum in domo, exceptis nobis duabus.

** I Kings 3:19

Mortuus est autem filius mulieris hujus nocte : dormiens quippe oppressit eum.

** I Kings 3:20

Et consurgens intempestæ noctis silentio, tulit filium meum de latere meo, ancillæ tuæ dormientis, et collocavit in sinu suo : suum autem filium, qui erat mortuus, posuit in sinu meo.

** I Kings 3:21

Cumque surrexissem mane ut darem lac filio meo, apparuit mortuus : quem diligentius intuens clara luce, deprehendi non esse meum quem genueram.

** I Kings 3:22

Responditque altera mulier : Non est ita ut dicis, sed filius tuus mortuus est, meus autem vivit. E contrario illa dicebat : Mentiris : filius quippe meus vivit, et filius tuus mortuus est. Atque in hunc modum contendebant coram rege.

** I Kings 3:23

Tunc rex ait : Hæc dicit : Filius meus vivit, et filius tuus mortuus est : et ista respondit : Non, sed filius tuus mortuus est, meus autem vivit.

** I Kings 3:24

Dixit ergo rex : Afferte mihi gladium. Cumque attulissent gladium coram rege,

** I Kings 3:25

Dividite, inquit, infantem vivum in duas partes, et date dimidiam partem uni, et dimidiam partem alteri.

** I Kings 3:26

Dixit autem mulier, cujus filius erat vivus, ad regem (commota sunt quippe viscera ejus super filio suo) : Obsecro, domine, date illi infantem vivum, et nolite interficere eum. E contrario illa dicebat : Nec mihi nec tibi sit, sed dividatur.

** I Kings 3:27

Respondit rex, et ait : Date huic infantem vivum, et non occidatur : hæc est enim mater ejus.

** I Kings 3:28

Audivit itaque omnis Israël judicium quod judicasset rex, et timuerunt regem, videntes sapientiam Dei esse in eo ad faciendum judicium.   

* I Kings 4

** I Kings 4:1

Erat autem rex Salomon regnans super omnem Israël :

** I Kings 4:2

et hi principes quos habebat : Azarias filius Sadoc sacerdotis :

** I Kings 4:3

Elihoreph et Ahia filii Sisa scribæ : Josaphat filius Ahilud a commentariis :

** I Kings 4:4

Banaias filius Jojadæ super exercitum : Sadoc autem et Abiathar sacerdotes :

** I Kings 4:5

Azarias filius Nathan super eos qui assistebant regi : Zabud filius Nathan sacerdos, amicus regis :

** I Kings 4:6

et Ahisar præpositus domus : et Adoniram filius Abda super tributa.

** I Kings 4:7

Habebat autem Salomon duodecim præfectos super omnem Israël, qui præbebant annonam regi et domui ejus : per singulos enim menses in anno, singuli necessaria ministrabant.

** I Kings 4:8

Et hæc nomina eorum : Benhur in monte Ephraim.

** I Kings 4:9

Bendecar in Macces, et in Salebim, et in Bethsames, et in Elon, et in Bethanan.

** I Kings 4:10

Benhesed in Aruboth : ipsius erat Socho, et omnis terra Epher.

** I Kings 4:11

Benabinadab, cujus omnis Nephath Dor : Tapheth filiam Salomonis habebat uxorem.

** I Kings 4:12

Bana filius Ahilud regebat Thanac et Mageddo, et universam Bethsan, quæ est juxta Sarthana subter Jezrahel, a Bethsan usque Abelmehula e regione Jecmaan.

** I Kings 4:13

Bengaber in Ramoth Galaad : habebat Avothjair filii Manasse in Galaad : ipse præerat in omni regione Argob, quæ est in Basan, sexaginta civitatibus magnis atque muratis quæ habebant seras æreas.

** I Kings 4:14

Ahinadab filius Addo præerat in Manaim.

** I Kings 4:15

Achimaas in Nephthali : sed et ipse habebat Basemath filiam Salomonis in conjugio.

** I Kings 4:16

Baana filius Husi in Aser, et in Baloth.

** I Kings 4:17

Josaphat filius Pharue in Issachar.

** I Kings 4:18

Semei filius Ela in Benjamin.

** I Kings 4:19

Gaber filius Uri in terra Galaad, in terra Sehon regis Amorrhæi et Og regis Basan, super omnia quæ erant in illa terra.  

** I Kings 4:20

Juda et Israël innumerabiles, sicut arena maris in multitudine : comedentes, et bibentes, atque lætantes.

** I Kings 4:21

Salomon autem erat in ditione sua, habens omnia regna a flumine terræ Philisthiim usque ad terminum Ægypti : offerentium sibi munera, et servientium ei cunctis diebus vitæ ejus.

** I Kings 4:22

Erat autem cibus Salomonis per dies singulos triginta cori similæ, et sexaginta cori farinæ,

** I Kings 4:23

decem boves pingues, et viginti boves pascuales, et centum arietes, excepta venatione cervorum, caprearum, atque bubalorum, et avium altilium.

** I Kings 4:24

Ipse enim obtinebat omnem regionem quæ erat trans flumen, a Thaphsa usque ad Gazan, et cunctos reges illarum regionum : et habebat pacem ex omni parte in circuitu.

** I Kings 4:25

Habitabatque Juda et Israël absque timore ullo, unusquisque sub vite sua et sub ficu sua, a Dan usque Bersabee, cunctis diebus Salomonis.

** I Kings 4:26

Et habebat Salomon quadraginta millia præsepia equorum currilium, et duodecim millia equestrium.

** I Kings 4:27

Nutriebantque eos supradicti regis præfecti : sed et necessaria mensæ regis Salomonis cum ingenti cura præbebant in tempore suo.

** I Kings 4:28

Hordeum quoque, et paleas equorum et jumentorum, deferebant in locum ubi erat rex, juxta constitutum sibi.  

** I Kings 4:29

Dedit quoque Deus sapientiam Salomoni, et prudentiam multam nimis, et latitudinem cordis quasi arenam quæ est in littore maris.

** I Kings 4:30

Et præcedebat sapientia Salomonis sapientiam omnium Orientalium et Ægyptiorum,

** I Kings 4:31

et erat sapientior cunctis hominibus : sapientior Ethan Ezrahita, et Heman, et Chalcol, et Dorda filiis Mahol : et erat nominatus in universis gentibus per circuitum.

** I Kings 4:32

Locutus est quoque Salomon tria millia parabolas : et fuerunt carmina ejus quinque et mille.

** I Kings 4:33

Et disputavit super lignis a cedro quæ est in Libano, usque ad hyssopum quæ egreditur de pariete : et disseruit de jumentis, et volucribus, et reptilibus, et piscibus.

** I Kings 4:34

Et veniebant de cunctis populis ad audiendam sapientiam Salomonis, et ab universis regibus terræ qui audiebant sapientiam ejus.   

* I Kings 5

** I Kings 5:1

Misit quoque Hiram rex Tyri servos suos ad Salomonem : audivit enim quod ipsum unxissent regem pro patre ejus : quia amicus fuerat Hiram David omni tempore.

** I Kings 5:2

Misit autem Salomon ad Hiram, dicens :

** I Kings 5:3

Tu scis voluntatem David patris mei, et quia non potuerit ædificare domum nomini Domini Dei sui propter bella imminentia per circuitum, donec daret Dominus eos sub vestigio pedum ejus.

** I Kings 5:4

Nunc autem requiem dedit Dominus Deus meus mihi per circuitum, et non est satan, neque occursus malus.

** I Kings 5:5

Quam ob rem cogito ædificare templum nomini Domini Dei mei, sicut locutus est Dominus David patri meo, dicens : Filius tuus, quem dabo pro te super solium tuum, ipse ædificabit domum nomini meo.

** I Kings 5:6

Præcipe igitur ut præcidant mihi servi tui cedros de Libano, et servi mei sint cum servis tuis : mercedem autem servorum tuorum dabo tibi quamcumque petieris : scis enim quomodo non est in populo meo vir qui noverit ligna cædere sicut Sidonii.

** I Kings 5:7

Cum ergo audisset Hiram verba Salomonis, lætatus est valde, et ait : Benedictus Dominus Deus hodie, qui dedit David filium sapientissimum super populum hunc plurimum.

** I Kings 5:8

Et misit Hiram ad Salomonem, dicens : Audivi quæcumque mandasti mihi : ego faciam omnem voluntatem tuam in lignis cedrinis et abiegnis.

** I Kings 5:9

Servi mei deponent ea de Libano ad mare, et ego componam ea in ratibus in mari usque ad locum quem significaveris mihi : et applicabo ea ibi, et tu tolles ea : præbebisque necessaria mihi, ut detur cibus domui meæ.

** I Kings 5:10

Itaque Hiram dabat Salomoni ligna cedrina, et ligna abiegna, juxta omnem voluntatem ejus.

** I Kings 5:11

Salomon autem præbebat Hiram coros tritici viginti millia in cibum domui ejus, et viginti coros purissimi olei : hæc tribuebat Salomon Hiram per singulos annos.

** I Kings 5:12

Dedit quoque Dominus sapientiam Salomoni, sicut locutus est ei : et erat pax inter Hiram et Salomonem, et percusserunt ambo fœdus.  

** I Kings 5:13

Elegitque rex Salomon operarios de omni Israël, et erat indictio triginta millia virorum.

** I Kings 5:14

Mittebatque eos in Libanum, decem millia per menses singulos vicissim, ita ut duobus mensibus essent in domibus suis : et Adoniram erat super hujuscemodi indictione.

** I Kings 5:15

Fueruntque Salomoni septuaginta millia eorum qui onera portabant, et octoginta millia latomorum in monte,

** I Kings 5:16

absque præpositis qui præerant singulis operibus, numero trium millium et trecentorum, præcipientium populo et his qui faciebant opus.

** I Kings 5:17

Præcepitque rex ut tollerent lapides grandes, lapides pretiosos in fundamentum templi, et quadrarent eos :

** I Kings 5:18

quos dolaverunt cæmentarii Salomonis et cæmentarii Hiram : porro Giblii præparaverunt ligna et lapides ad ædificandam domum.   

* I Kings 6

** I Kings 6:1

Factum est ergo quadringentesimo et octogesimo anno egressionis filiorum Israël de terra Ægypti, in anno quarto, mense Zio (ipse est mensis secundus), regni Salomonis super Israël, ædificari cœpit domus Domino.

** I Kings 6:2

Domus autem quam ædificabat rex Salomon Domino, habebat sexaginta cubitos in longitudine, et viginti cubitos in latitudine, et triginta cubitos in altitudine.

** I Kings 6:3

Et porticus erat ante templum viginti cubitorum longitudinis, juxta mensuram latitudinis templi : et habebat decem cubitos latitudinis ante faciem templi.

** I Kings 6:4

Fecitque in templo fenestras obliquas.

** I Kings 6:5

Et ædificavit super parietem templi tabulata per gyrum, in parietibus domus per circuitum templi et oraculi, et fecit latera in circuitu.

** I Kings 6:6

Tabulatum quod subter erat, quinque cubitos habebat latitudinis, et medium tabulatum sex cubitorum latitudinis, et tertium tabulatum septem habens cubitos latitudinis. Trabes autem posuit in domo per circuitum forinsecus, ut non hærerent muris templi.

** I Kings 6:7

Domus autem cum ædificaretur, de lapidibus dolatis atque perfectis ædificata est : et malleus, et securis, et omne ferramentum non sunt audita in domo cum ædificaretur.

** I Kings 6:8

Ostium lateris medii in parte erat domus dextræ : et per cochleam ascendebant in medium cœnaculum, et a medio in tertium.

** I Kings 6:9

Et ædificavit domum, et consummavit eam : texit quoque domum laquearibus cedrinis.

** I Kings 6:10

Et ædificavit tabulatum super omnem domum quinque cubitis altitudinis, et operuit domum lignis cedrinis.

** I Kings 6:11

Et factus est sermo Domini ad Salomonem, dicens :

** I Kings 6:12

Domus hæc, quam ædificas, si ambulaveris in præceptis meis, et judicia mea feceris, et custodieris omnia mandata mea, gradiens per ea, firmabo sermonem meum tibi, quem locutus sum ad David patrem tuum :

** I Kings 6:13

et habitabo in medio filiorum Israël, et non derelinquam populum meum Israël.  

** I Kings 6:14

Igitur ædificavit Salomon domum, et consummavit eam.

** I Kings 6:15

Et ædificavit parietes domus intrinsecus tabulatis cedrinis : a pavimento domus usque ad summitatem parietum, et usque ad laquearia, operuit lignis cedrinis intrinsecus : et texit pavimentum domus tabulis abiegnis.

** I Kings 6:16

Ædificavitque viginti cubitorum ad posteriorem partem templi tabulata cedrina, a pavimento usque ad superiora : et fecit interiorem domum oraculi in Sanctum sanctorum.

** I Kings 6:17

Porro quadraginta cubitorum erat ipsum templum pro foribus oraculi.

** I Kings 6:18

Et cedro omnis domus intrinsecus vestiebatur, habens tornaturas et juncturas suas fabrefactas, et cælaturas eminentes : omnia cedrinis tabulis vestiebantur : nec omnino lapis apparere poterat in pariete.

** I Kings 6:19

Oraculum autem in medio domus, in interiori parte fecerat, ut poneret ibi arcam fœderis Domini.

** I Kings 6:20

Porro oraculum habebat viginti cubitos longitudinis, et viginti cubitos latitudinis, et viginti cubitos altitudinis : et operuit illud atque vestivit auro purissimo : sed et altare vestivit cedro.

** I Kings 6:21

Domum quoque ante oraculum operuit auro purissimo, et affixit laminas clavis aureis.

** I Kings 6:22

Nihilque erat in templo quod non auro tegeretur : sed et totum altare oraculi texit auro.

** I Kings 6:23

Et fecit in oraculo duos cherubim de lignis olivarum, decem cubitorum altitudinis.

** I Kings 6:24

Quinque cubitorum ala cherub una, et quinque cubitorum ala cherub altera : id est, decem cubitos habentes, a summitate alæ unius usque ad alæ alterius summitatem.

** I Kings 6:25

Decem quoque cubitorum erat cherub secundus : in mensura pari, et opus unum erat in duobus cherubim,

** I Kings 6:26

id est, altitudinem habebat unus cherub decem cubitorum, et similiter cherub secundus.

** I Kings 6:27

Posuitque cherubim in medio templi interioris : extendebant autem alas suas cherubim, et tangebat ala una parietem, et ala cherub secundi tangebat parietem alterum : alæ autem alteræ in media parte templi se invicem contingebant.

** I Kings 6:28

Texit quoque cherubim auro.

** I Kings 6:29

Et omnes parietes templi per circuitum sculpsit variis cælaturis et torno : et fecit in eis cherubim, et palmas, et picturas varias, quasi prominentes de pariete, et egredientes.

** I Kings 6:30

Sed et pavimentum domus texit auro intrinsecus et extrinsecus.

** I Kings 6:31

Et in ingressu oraculi fecit ostiola de lignis olivarum, postesque angulorum quinque.

** I Kings 6:32

Et duo ostia de lignis olivarum : et sculpsit in eis picturam cherubim, et palmarum species, et anaglypha valde prominentia : et texit ea auro, et operuit tam cherubim quam palmas, et cetera, auro.

** I Kings 6:33

Fecitque in introitu templi postes de lignis olivarum quadrangulatos,

** I Kings 6:34

et duo ostia de lignis abiegnis altrinsecus : et utrumque ostium duplex erat, et se invicem tenens aperiebatur.

** I Kings 6:35

Et sculpsit cherubim, et palmas, et cælaturas valde eminentes : operuitque omnia laminis aureis opere quadro ad regulam.

** I Kings 6:36

Et ædificavit atrium interius tribus ordinibus lapidum politorum, et uno ordine lignorum cedri.

** I Kings 6:37

Anno quarto fundata est domus Domini in mense Zio :

** I Kings 6:38

et in anno undecimo, mense Bul (ipse est mensis octavus), perfecta est domus in omni opere suo, et in universis utensilibus suis : ædificavitque eam annis septem.   

* I Kings 7

** I Kings 7:1

Domum autem suam ædificavit Salomon tredecim annis, et ad perfectum usque perduxit.

** I Kings 7:2

Ædificavit quoque domum saltus Libani centum cubitorum longitudinis, et quinquaginta cubitorum latitudinis, et triginta cubitorum altitudinis : et quatuor deambulacra inter columnas cedrinas : ligna quippe cedrina exciderat in columnas.

** I Kings 7:3

Et tabulatis cedrinis vestivit totam cameram, quæ quadraginta quinque columnis sustentabatur. Unus autem ordo habebat columnas quindecim

** I Kings 7:4

contra se invicem positas,

** I Kings 7:5

et e regione se respicientes, æquali spatio inter columnas, et super columnas quadrangulata ligna in cunctis æqualia.

** I Kings 7:6

Et porticum columnarum fecit quinquaginta cubitorum longitudinis, et triginta cubitorum latitudinis : et alteram porticum in facie majoris porticus : et columnas, et epistylia super columnas.

** I Kings 7:7

Porticum quoque solii, in qua tribunal est, fecit : et texit lignis cedrinis a pavimento usque ad summitatem.

** I Kings 7:8

Et domuncula, in qua sedebatur ad judicandum, erat in media porticu simili opere. Domum quoque fecit filiæ Pharaonis (quam uxorem duxerat Salomon) tali opere, quali et hanc porticum.

** I Kings 7:9

Omnia lapidibus pretiosis, qui ad normam quamdam atque mensuram tam intrinsecus quam extrinsecus serrati erant : a fundamento usque ad summitatem parietum, et extrinsecus usque ad atrium majus.

** I Kings 7:10

Fundamenta autem de lapidibus pretiosis, lapidibus magnis, decem sive octo cubitorum.

** I Kings 7:11

Et desuper lapides pretiosi æqualis mensuræ secti erant, similiterque de cedro.

** I Kings 7:12

Et atrium majus rotundum trium ordinum de lapidibus sectis, et unius ordinis de dolata cedro : necnon et in atrio domus Domini interiori, et in porticu domus.  

** I Kings 7:13

Misit quoque rex Salomon, et tulit Hiram de Tyro,

** I Kings 7:14

filium mulieris viduæ de tribu Nephthali, patre Tyrio, artificem ærarium, et plenum sapientia, et intelligentia, et doctrina, ad faciendum omne opus ex ære. Qui cum venisset ad regem Salomonem, fecit omne opus ejus.

** I Kings 7:15

Et finxit duas columnas æreas, decem et octo cubitorum altitudinis columnam unam : et linea duodecim cubitorum ambiebat columnam utramque.

** I Kings 7:16

Duo quoque capitella fecit, quæ ponerentur super capita columnarum, fusilia ex ære : quinque cubitorum altitudinis capitellum unum, et quinque cubitorum altitudinis capitellum alterum :

** I Kings 7:17

et quasi in modum retis, et catenarum sibi invicem miro opere contextarum. Utrumque capitellum columnarum fusile erat : septena versuum retiacula in capitello uno, et septena retiacula in capitello altero.

** I Kings 7:18

Et perfecit columnas, et duos ordines per circuitum retiaculorum singulorum, ut tegerent capitella quæ erant super summitatem, malogranatorum : eodem modo fecit et capitello secundo.

** I Kings 7:19

Capitella autem quæ erant super capita columnarum, quasi opere lilii fabricata erant in porticu quatuor cubitorum.

** I Kings 7:20

Et rursum alia capitella in summitate columnarum desuper juxta mensuram columnæ contra retiacula : malogranatorum autem ducenti ordines erant in circuitu capitelli secundi.

** I Kings 7:21

Et statuit duas columnas in porticu templi : cumque statuisset columnam dexteram, vocavit eam nomine Jachin : similiter erexit columnam secundam, et vocavit nomen ejus Booz.

** I Kings 7:22

Et super capita columnarum opus in modum lilii posuit : perfectumque est opus columnarum.

** I Kings 7:23

Fecit quoque mare fusile decem cubitorum a labio usque ad labium, rotundum in circuitu : quinque cubitorum altitudo ejus, et resticula triginta cubitorum cingebat illud per circuitum.

** I Kings 7:24

Et sculptura subter labium circuibat illud decem cubitis ambiens mare : duo ordines sculpturarum striatarum erant fusiles.

** I Kings 7:25

Et stabat super duodecim boves, e quibus tres respiciebant ad aquilonem, et tres ad occidentem, et tres ad meridiem, et tres ad orientem : et mare super eos desuper erat : quorum posteriora universa intrinsecus latitabant.

** I Kings 7:26

Grossitudo autem luteris, trium unciarum erat : labiumque ejus quasi labium calicis, et folium repandi lilii : duo millia batos capiebat.

** I Kings 7:27

Et fecit decem bases æneas, quatuor cubitorum longitudinis bases singulas, et quatuor cubitorum latitudinis, et trium cubitorum altitudinis.

** I Kings 7:28

Et ipsum opus basium, interrasile erat : et sculpturæ inter juncturas.

** I Kings 7:29

Et inter coronulas et plectas, leones et boves et cherubim, et in juncturis similiter desuper : et subter leones et boves, quasi lora ex ære dependentia.

** I Kings 7:30

Et quatuor rotæ per bases singulas, et axes ærei : et per quatuor partes quasi humeruli subter luterem fusiles, contra se invicem respectantes.

** I Kings 7:31

Os quoque luteris intrinsecus erat in capitis summitate : et quod forinsecus apparebat, unius cubiti erat totum rotundum, pariterque habebat unum cubitum et dimidium : in angulis autem columnarum variæ cælaturæ erant : et media intercolumnia, quadrata non rotunda.

** I Kings 7:32

Quatuor quoque rotæ quæ per quatuor angulos basis erant, cohærebant sibi subter basim : una rota habebat altitudinis cubitum et semis.

** I Kings 7:33

Tales autem rotæ erant quales solent in curru fieri : et axes earum, et radii, et canthi, et modioli, omnia fusilia.

** I Kings 7:34

Nam et humeruli illi quatuor per singulos angulos basis unius, ex ipsa basi fusiles et conjuncti erant.

** I Kings 7:35

In summitate autem basis erat quædam rotunditas dimidii cubiti, ita fabrefacta ut luter desuper posset imponi, habens cælaturas suas, variasque sculpturas ex semetipsa.

** I Kings 7:36

Sculpsit quoque in tabulatis illis quæ erant ex ære, et in angulis, cherubim, et leones, et palmas, quasi in similitudinem hominis stantis, ut non cælata, sed apposita per circuitum viderentur.

** I Kings 7:37

In hunc modum fecit decem bases, fusura una, et mensura, sculpturaque consimili.

** I Kings 7:38

Fecit quoque decem luteres æneos : quadraginta batos capiebat luter unus, eratque quatuor cubitorum : singulos quoque luteres per singulas, id est, decem bases, posuit.

** I Kings 7:39

Et constituit decem bases, quinque ad dexteram partem templi, et quinque ad sinistram : mare autem posuit ad dexteram partem templi contra orientem ad meridiem.

** I Kings 7:40

Fecit ergo Hiram lebetes, et scutras, et hamulas, et perfecit omne opus regis Salomonis in templo Domini.

** I Kings 7:41

Columnas duas, et funiculos capitellorum super capitella columnarum duos : et retiacula duo, ut operirent duos funiculos qui erant super capita columnarum.

** I Kings 7:42

Et malogranata quadringenta in duobus retiaculis : duos versus malogranatorum in retiaculis singulis, ad operiendos funiculos capitellorum qui erant super capita columnarum.

** I Kings 7:43

Et bases decem, et luteres decem super bases.

** I Kings 7:44

Et mare unum, et boves duodecim subter mare.

** I Kings 7:45

Et lebetes, et scutras, et hamulas, omnia vasa quæ fecit Hiram regi Salomoni in domo Domini, de auricalco erant.

** I Kings 7:46

In campestri regione Jordanis fudit ea rex in argillosa terra, inter Sochoth et Sarthan.

** I Kings 7:47

Et posuit Salomon omnia vasa : propter multitudinem autem nimiam non erat pondus æris.  

** I Kings 7:48

Fecitque Salomon omnia vasa in domo Domini : altare aureum, et mensam super quam ponerentur panes propositionis, auream :

** I Kings 7:49

et candelabra aurea, quinque ad dexteram, et quinque ad sinistram contra oraculum, ex auro puro : et quasi lilii flores, et lucernas desuper aureas : et forcipes aureos,

** I Kings 7:50

et hydrias, et fuscinulas, et phialas, et mortariola, et thuribula, de auro purissimo : et cardines ostiorum domus interioris Sancti sanctorum, et ostiorum domus templi, ex auro erant.

** I Kings 7:51

Et perfecit omne opus quod faciebat Salomon in domo Domini, et intulit quæ sanctificaverat David pater suus, argentum, et aurum, et vasa, reposuitque in thesauris domus Domini.   

* I Kings 8

** I Kings 8:1

Tunc congregati sunt omnes majores natu Israël cum principibus tribuum, et duces familiarum filiorum Israël, ad regem Salomonem in Jerusalem, ut deferrent arcam fœderis Domini de civitate David, id est, de Sion.

** I Kings 8:2

Convenitque ad regem Salomonem universus Israël in mense Ethanim, in solemni die : ipse est mensis septimus.

** I Kings 8:3

Veneruntque cuncti senes de Israël, et tulerunt arcam sacerdotes,

** I Kings 8:4

et portaverunt arcam Domini, et tabernaculum fœderis, et omnia vasa sanctuarii quæ erant in tabernaculo : et ferebant ea sacerdotes et Levitæ.

** I Kings 8:5

Rex autem Salomon, et omnis multitudo Israël quæ convenerat ad eum, gradiebatur cum illo ante arcam, et immolabant oves et boves absque æstimatione et numero.

** I Kings 8:6

Et intulerunt sacerdotes arcam fœderis Domini in locum suum, in oraculum templi, in Sanctum sanctorum, subter alas cherubim.

** I Kings 8:7

Siquidem cherubim expandebant alas super locum arcæ, et protegebant arcam, et vectes ejus desuper.

** I Kings 8:8

Cumque eminerent vectes, et apparerent summitates eorum foris sanctuarium ante oraculum, non apparebant ultra extrinsecus, qui et fuerunt ibi usque in præsentem diem.

** I Kings 8:9

In arca autem non erat aliud nisi duæ tabulæ lapideæ quas posuerat in ea Moyses in Horeb, quando pepigit Dominus fœdus cum filiis Israël, cum egrederentur de terra Ægypti.

** I Kings 8:10

Factum est autem cum exissent sacerdotes de sanctuario, nebula implevit domum Domini,

** I Kings 8:11

et non poterant sacerdotes stare et ministrare propter nebulam : impleverat enim gloria Domini domum Domini.

** I Kings 8:12

Tunc ait Salomon : Dominus dixit ut habitaret in nebula.

** I Kings 8:13

Ædificans ædificavi domum in habitaculum tuum : firmissimum solium tuum in sempiternum.

** I Kings 8:14

Convertitque rex faciem suam, et benedixit omni ecclesiæ Israël : omnia enim ecclesia Israël stabat.

** I Kings 8:15

Et ait Salomon : Benedictus Dominus Deus Israël, qui locutus est ore suo ad David patrem meum, et in manibus ejus perfecit, dicens :

** I Kings 8:16

A die qua eduxi populum meum Israël de Ægypto, non elegi civitatem de universis tribubus Israël, ut ædificaretur domus, et esset nomen meum ibi : sed elegi David ut esset super populum meum Israël.

** I Kings 8:17

Voluitque David pater meus ædificare domum nomini Domini Dei Israël :

** I Kings 8:18

et ait Dominus ad David patrem meum : Quod cogitasti in corde tuo ædificare domum nomini meo, bene fecisti, hoc ipsum mente tractans.

** I Kings 8:19

Verumtamen tu non ædificabis mihi domum, sed filius tuus, qui egredietur de renibus tuis, ipse ædificabit domum nomini meo.

** I Kings 8:20

Confirmavit Dominus sermonem suum quem locutus est : stetique pro David patre meo, et sedi super thronum Israël, sicut locutus est Dominus : et ædificavi domum nomini Domini Dei Israël.

** I Kings 8:21

Et constitui ibi locum arcæ in qua fœdus Domini est, quod percussit cum patribus nostris quando egressi sunt de terra Ægypti.  

** I Kings 8:22

Stetit autem Salomon ante altare Domini in conspectu ecclesiæ Israël, et expandit manus suas in cælum,

** I Kings 8:23

et ait : Domine Deus Israël, non est similis tui deus in cælo desuper, et super terram deorsum : qui custodis pactum et misericordiam servis tuis qui ambulant coram te in toto corde suo.

** I Kings 8:24

Qui custodisti servo tuo David patri meo quæ locutus es ei : ore locutus es, et manibus perfecisti, ut hæc dies probat.

** I Kings 8:25

Nunc igitur Domine Deus Israël, conserva famulo tuo David patri meo quæ locutus es ei, dicens : Non auferetur de te vir coram me, qui sedeat super thronum Israël : ita tamen si custodierint filii tui viam suam, ut ambulent coram me sicut tu ambulasti in conspectu meo.

** I Kings 8:26

Et nunc Domine Deus Israël, firmentur verba tua quæ locutus es servo tuo David patri meo.

** I Kings 8:27

Ergone putandum est quod vere Deus habitet super terram ? si enim cælum, et cæli cælorum, te capere non possunt, quanto magis domus hæc, quam ædificavi ?

** I Kings 8:28

Sed respice ad orationem servi tui, et ad preces ejus, Domine Deus meus : audi hymnum et orationem quam servus tuus orat coram te hodie :

** I Kings 8:29

ut sint oculi tui aperti super domum hanc nocte ac die : super domum, de qua dixisti : Erit nomen meum ibi : ut exaudias orationem quam orat in loco isto ad te servus tuus :

** I Kings 8:30

ut exaudias deprecationem servi tui et populi tui Israël, quodcumque oraverint in loco isto, et exaudies in loco habitaculi tui in cælo : et cum exaudieris, propitius eris.  

** I Kings 8:31

Si peccaverit homo in proximum suum, et habuerit aliquod juramentum quo teneatur astrictus, et venerit propter juramentum coram altari tuo in domum tuam,

** I Kings 8:32

tu exaudies in cælo : et facies, et judicabis servos tuos, condemnans impium, et reddens viam suam super caput ejus, justificansque justum, et retribuens ei secundum justitiam suam.

** I Kings 8:33

Si fugerit populus tuus Israël inimicos suos (quia peccaturus est tibi), et agentes pœnitentiam, et confitentes nomini tuo, venerint, et oraverint, et deprecati te fuerint in domo hac :

** I Kings 8:34

exaudi in cælo, et dimitte peccatum populi tui Israël, et reduces eos in terram quam dedisti patribus eorum.

** I Kings 8:35

Si clausum fuerit cælum, et non pluerit propter peccata eorum, et orantes in loco isto, pœnitentiam egerint nomini tuo, et a peccatis suis conversi fuerint propter afflictionem suam :

** I Kings 8:36

exaudi eos in cælo, et dimitte peccata servorum tuorum, et populi tui Israël : et ostende eis viam bonam per quam ambulent, et da pluviam super terram tuam, quam dedisti populo tuo in possessionem.

** I Kings 8:37

Fames si oborta fuerit in terra, aut pestilentia, aut corruptus aër, aut ærugo, aut locusta, vel rubigo, et afflixerit eum inimicus ejus portas obsidens : omnis plaga, universa infirmitas,

** I Kings 8:38

cuncta devotatio, et imprecatio quæ acciderit omni homini de populo tuo Israël : si quis cognoverit plagam cordis sui, et expanderit manus suas in domo hac,

** I Kings 8:39

tu exaudies in cælo in loco habitationis tuæ, et repropitiaberis, et facies ut des unicuique secundum omnes vias suas, sicut videris cor ejus (quia tu nosti solus cor omnium filiorum hominum),

** I Kings 8:40

ut timeant te cunctis diebus quibus vivunt super faciem terræ quam dedisti patribus nostris.  

** I Kings 8:41

Insuper et alienigena, qui non est de populo tuo Israël, cum venerit de terra longinqua propter nomen tuum (audietur enim nomen tuum magnum, et manus tua fortis, et brachium tuum

** I Kings 8:42

extentum ubique), cum venerit ergo, et oraverit in hoc loco,

** I Kings 8:43

tu exaudies in cælo, in firmamento habitaculi tui, et facies omnia pro quibus invocaverit te alienigena : ut discant universi populi terrarum nomen tuum timere, sicut populus tuus Israël, et probent quia nomen tuum invocatum est super domum hanc quam ædificavi.

** I Kings 8:44

Si egressus fuerit populus tuus ad bellum contra inimicos suos per viam, quocumque miseris eos, orabunt te contra viam civitatis quam elegisti, et contra domum quam ædificavi nomini tuo,

** I Kings 8:45

et exaudies in cælo orationes eorum et preces eorum, et facies judicium eorum.  

** I Kings 8:46

Quod si peccaverint tibi (non est enim homo qui non peccet) et iratus tradideris eos inimicis suis, et captivi ducti fuerint in terram inimicorum longe vel prope,

** I Kings 8:47

et egerint pœnitentiam in corde suo in loco captivitatis, et conversi deprecati te fuerint in captivitate sua, dicentes : Peccavimus : inique egimus, impie gessimus :

** I Kings 8:48

et reversi fuerint ad te in universo corde suo et tota anima sua in terra inimicorum suorum, ad quam captivi ducti fuerint : et oraverint te contra viam terræ suæ, quam dedisti patribus eorum, et civitatis quam elegisti, et templi quod ædificavi nomini tuo :

** I Kings 8:49

exaudies in cælo, in firmamento solii tui, orationes eorum et preces eorum, et facies judicium eorum :

** I Kings 8:50

et propitiaberis populo tuo qui peccavit tibi, et omnibus iniquitatibus eorum quibus prævaricati sunt in te : et dabis misericordiam coram eis qui eos captivos habuerint, ut misereantur eis.

** I Kings 8:51

Populus enim tuus est, et hæreditas tua, quos eduxisti de terra Ægypti, de medio fornacis ferreæ.

** I Kings 8:52

Ut sint oculi tui aperti ad deprecationem servi tui, et populi tui Israël, et exaudias eos in universis pro quibus invocaverint te.

** I Kings 8:53

Tu enim separasti eos tibi in hæreditatem de universis populis terræ, sicut locutus es per Moysen servum tuum quando eduxisti patres nostros de Ægypto, Domine Deus.  

** I Kings 8:54

Factum est autem, cum complesset Salomon orans Dominum omnem orationem et deprecationem hanc, surrexit de conspectu altaris Domini : utrumque enim genu in terram fixerat, et manus expanderat in cælum.

** I Kings 8:55

Stetit ergo, et benedixit omni ecclesiæ Israël voce magna, dicens :

** I Kings 8:56

Benedictus Dominus, qui dedit requiem populo suo Israël, juxta omnia quæ locutus est : non cecidit ne unus quidem sermo ex omnibus bonis quæ locutus est per Moysen servum suum.

** I Kings 8:57

Sit Dominus Deus noster nobiscum, sicut fuit cum patribus nostris, non derelinquens nos, neque projiciens.

** I Kings 8:58

Sed inclinet corda nostra ad se, ut ambulemus in universis viis ejus, et custodiamus mandata ejus, et cæremonias ejus, et judicia quæcumque mandavit patribus nostris.

** I Kings 8:59

Et sint sermones mei isti, quibus deprecatus sum coram Domino, appropinquantes Domino Deo nostro die ac nocte, ut faciat judicium servo suo, et populo suo Israël per singulos dies :

** I Kings 8:60

ut sciant omnes populi terræ quia Dominus ipse est Deus, et non est ultra absque eo.

** I Kings 8:61

Sit quoque cor nostrum perfectum cum Domino Deo nostro, ut ambulemus in decretis ejus, et custodiamus mandata ejus, sicut et hodie.  

** I Kings 8:62

Igitur rex, et omnis Israël cum eo, immolabant victimas coram Domino.

** I Kings 8:63

Mactavitque Salomon hostias pacificas, quas immolavit Domino, boum viginti duo millia, et ovium centum viginti millia : et dedicaverunt templum Domini rex et filii Israël.

** I Kings 8:64

In die illa sanctificavit rex medium atrii quod erat ante domum Domini : fecit quippe holocaustum ibi, et sacrificium, et adipem pacificorum : quoniam altare æreum quod erat coram Domino, minus erat, et capere non poterat holocaustum, et sacrificium, et adipem pacificorum.

** I Kings 8:65

Fecit ergo Salomon in tempore illo festivitatem celebrem, et omnis Israël cum eo, multitudo magna ab introitu Emath usque ad rivum Ægypti, coram Domino Deo nostro, septem diebus et septem diebus, id est, quatuordecim diebus.

** I Kings 8:66

Et in die octava dimisit populos : qui benedicentes regi, profecti sunt in tabernacula sua lætantes, et alacri corde super omnibus bonis quæ fecerat Dominus David servo suo, et Israël populo suo.   

* I Kings 9

** I Kings 9:1

Factum est autem cum perfecisset Salomon ædificium domus Domini, et ædificium regis, et omne quod optaverat et voluerat facere,

** I Kings 9:2

apparuit ei Dominus secundo, sicut apparuerat ei in Gabaon.

** I Kings 9:3

Dixitque Dominus ad eum : Exaudivi orationem tuam et deprecationem tuam, quam deprecatus es coram me : sanctificavi domum hanc quam ædificasti, ut ponerem nomen meum ibi in sempiternum, et erunt oculi mei et cor meum ibi cunctis diebus.

** I Kings 9:4

Tu quoque si ambulaveris coram me sicut ambulavit pater tuus, in simplicitate cordis et in æquitate, et feceris omnia quæ præcepi tibi, et legitima mea et judicia mea servaveris,

** I Kings 9:5

ponam thronum regni tui super Israël in sempiternum, sicut locutus sum David patri tuo, dicens : Non auferetur vir de genere tuo de solio Israël.

** I Kings 9:6

Si autem aversione aversi fueritis vos et filii vestri, non sequentes me, nec custodientes mandata mea et cæremonias meas quas proposui vobis, sed abieritis et colueritis deos alienos, et adoraveritis eos :

** I Kings 9:7

auferam Israël de superficie terræ quam dedi eis, et templum quod sanctificavi nomini meo, projiciam a conspectu meo : eritque Israël in proverbium, et in fabulam cunctis populis.

** I Kings 9:8

Et domus hæc erit in exemplum : omnis qui transierit per eam, stupebit, et sibilabit, et dicet : Quare fecit Dominus sic terræ huic, et domui huic ?

** I Kings 9:9

Et respondebunt : Quia dereliquerunt Dominum Deum suum, qui eduxit patres eorum de terra Ægypti, et secuti sunt deos alienos, et adoraverunt eos, et coluerunt eos : idcirco induxit Dominus super eos omne malum hoc.  

** I Kings 9:10

Expletis autem annis viginti postquam ædificaverat Salomon duas domos, id est, domum Domini, et domum regis

** I Kings 9:11

(Hiram rege Tyri præbente Salomoni ligna cedrina et abiegna, et aurum juxta omne quod opus habuerat), tunc dedit Salomon Hiram viginti oppida in terra Galilææ.

** I Kings 9:12

Et egressus est Hiram de Tyro ut videret oppida quæ dederat ei Salomon, et non placuerunt ei.

** I Kings 9:13

Et ait : Hæccine sunt civitates quas dedisti mihi, frater ? Et appellavit eas terram Chabul, usque in diem hanc.

** I Kings 9:14

Misit quoque Hiram ad regem Salomonem centum viginti talenta auri.

** I Kings 9:15

Hæc est summa expensarum quam obtulit rex Salomon ad ædificandam domum Domini et domum suam, et Mello, et murum Jerusalem, et Heser, et Mageddo, et Gazer.

** I Kings 9:16

Pharao rex Ægypti ascendit, et cepit Gazar, succenditque eam igni, et Chananæum, qui habitabat in civitate, interfecit : et dedit eam in dotem filiæ suæ uxori Salomonis.

** I Kings 9:17

Ædificavit ergo Salomon Gazer, et Bethoron inferiorem,

** I Kings 9:18

et Balaath, et Palmiram in terra solitudinis.

** I Kings 9:19

Et omnes vicos qui ad se pertinebant et erant absque muro, munivit, et civitates curruum et civitates equitum, et quodcumque ei placuit ut ædificaret in Jerusalem, et in Libano, et in omni terra potestatis suæ.

** I Kings 9:20

Universum populum qui remanserat de Amorrhæis, et Hethæis, et Pherezæis, et Hevæis, et Jebusæis, qui non sunt de filiis Israël :

** I Kings 9:21

horum filios qui remanserant in terra, quos scilicet non potuerant filii Israël exterminare, fecit Salomon tributarios usque in diem hanc.

** I Kings 9:22

De filiis autem Israël non constituit Salomon servire quemquam, sed erant viri bellatores, et ministri ejus, et principes, et duces, et præfecti curruum et equorum.

** I Kings 9:23

Erant autem principes super omnia opera Salomonis præpositi quingenti quinquaginta, qui habebant subjectum populum, et statutis operibus imperabant.

** I Kings 9:24

Filia autem Pharaonis ascendit de civitate David in domum suam, quam ædificaverat ei Salomon : tunc ædificavit Mello.

** I Kings 9:25

Offerebat quoque Salomon, tribus vicibus per annos singulos, holocausta et pacificas victimas super altare quod ædificaverat Domino, et adolebat thymiama coram Domino : perfectumque est templum.

** I Kings 9:26

Classem quoque fecit rex Salomon in Asiongaber, quæ est juxta Ailath in littore maris Rubri, in terra Idumææ.

** I Kings 9:27

Misitque Hiram in classe illa servos suos viros nauticos et gnaros maris, cum servis Salomonis.

** I Kings 9:28

Qui cum venissent in Ophir, sumptum inde aurum quadringentorum viginti talentorum, detulerunt ad regem Salomonem.   

* I Kings 10

** I Kings 10:1

Sed et regina Saba, audita fama Salomonis in nomine Domini, venit tentare eum in ænigmatibus.

** I Kings 10:2

Et ingressa Jerusalem multo cum comitatu et divitiis, camelis portantibus aromata, et aurum infinitum nimis, et gemmas pretiosas, venit ad regem Salomonem, et locuta est ei universa quæ habebat in corde suo.

** I Kings 10:3

Et docuit eam Salomon omnia verba quæ proposuerat : non fuit sermo qui regem posset latere, et non responderet ei.

** I Kings 10:4

Videns autem regina Saba omnem sapientiam Salomonis, et domum quam ædificaverat,

** I Kings 10:5

et cibos mensæ ejus, et habitacula servorum, et ordines ministrantium, vestesque eorum, et pincernas, et holocausta quæ offerebat in domo Domini : non habebat ultra spiritum.

** I Kings 10:6

Dixitque ad regem : Verus est sermo quem audivi in terra mea

** I Kings 10:7

super sermonibus tuis, et super sapientia tua : et non credebam narrantibus mihi, donec ipsa veni, et vidi oculis meis, et probavi quod media pars mihi nuntiata non fuerit : major est sapientia et opera tua, quam rumor quem audivi.

** I Kings 10:8

Beati viri tui, et beati servi tui, qui stant coram te semper, et audiunt sapientiam tuam.

** I Kings 10:9

Sit Dominus Deus tuus benedictus, cui complacuisti, et posuit te super thronum Israël, eo quod dilexerit Dominus Israël in sempiternum, et constituit te regem ut faceres judicium et justitiam.

** I Kings 10:10

Dedit ergo regi centum viginti talenta auri, et aromata multa nimis, et gemmas pretiosas : non sunt allata ultra aromata tam multa, quam ea quæ dedit regina Saba regi Salomoni.  

** I Kings 10:11

(Sed et classis Hiram, quæ portabat aurum de Ophir, attulit ex Ophir ligna thyina multa nimis, et gemmas pretiosas.

** I Kings 10:12

Fecitque rex de lignis thyinis fulcra domus Domini et domus regiæ, et citharas lyrasque cantoribus : non sunt allata hujuscemodi ligna thyina, neque visa usque in præsentem diem.)

** I Kings 10:13

Rex autem Salomon dedit reginæ Saba omnia quæ voluit et petivit ab eo, exceptis his quæ ultro obtulerat ei munere regio. Quæ reversa est, et abiit in terram suam cum servis suis.

** I Kings 10:14

Erat autem pondus auri quod afferebatur Salomoni per annos singulos, sexcentorum sexaginta sex talentorum auri,

** I Kings 10:15

excepto eo quod afferebant viri qui super vectigalia erant, et negotiatores, universique scruta vendentes, et omnes reges Arabiæ, ducesque terræ.

** I Kings 10:16

Fecit quoque rex Salomon ducenta scuta de auro purissimo : sexcentos auri siclos dedit in laminas scuti unius.

** I Kings 10:17

Et trecentas peltas ex auro probato : trecentæ minæ auri unam peltam vestiebant : posuitque eas rex in domo saltus Libani.

** I Kings 10:18

Fecit etiam rex Salomon thronum de ebore grandem : et vestivit eum auro fulvo nimis,

** I Kings 10:19

qui habebat sex gradus : et summitas throni rotunda erat in parte posteriori : et duæ manus hinc atque inde tenentes sedile : et duo leones stabant juxta manus singulas.

** I Kings 10:20

Et duodecim leunculi stantes super sex gradus hinc atque inde : non est factum tale opus in universis regnis.

** I Kings 10:21

Sed et omnia vasa quibus potabat rex Salomon, erant aurea : et universa supellex domus saltus Libani de auro purissimo : non erat argentum, nec alicujus pretii putabatur in diebus Salomonis,

** I Kings 10:22

quia classis regis per mare cum classe Hiram semel per tres annos ibat in Tharsis, deferens inde aurum, et argentum, et dentes elephantorum, et simias, et pavos.  

** I Kings 10:23

Magnificatus est ergo rex Salomon super omnes reges terræ divitiis et sapientia.

** I Kings 10:24

Et universa terra desiderabat vultum Salomonis, ut audiret sapientiam ejus, quam dederat Deus in corde ejus.

** I Kings 10:25

Et singuli deferebant ei munera, vasa argentea et aurea, vestes et arma bellica, aromata quoque, et equos et mulos per annos singulos.

** I Kings 10:26

Congregavitque Salomon currus et equites, et facti sunt ei mille quadringenti currus, et duodecim millia equitum : et disposuit eos per civitates munitas, et cum rege in Jerusalem.

** I Kings 10:27

Fecitque ut tanta esset abundantia argenti in Jerusalem, quanta et lapidum : et cedrorum præbuit multitudinem quasi sycomoros quæ nascuntur in campestribus.

** I Kings 10:28

Et educebantur equi Salomoni de Ægypto, et de Coa. Negotiatores enim regis emebant de Coa, et statuto pretio perducebant.

** I Kings 10:29

Egrediebatur autem quadriga ex Ægypto sexcentis siclis argenti, et equus centum quinquaginta. Atque in hunc modum cuncti reges Hethæorum et Syriæ equos venundabant.   

* I Kings 11

** I Kings 11:1

Rex autem Salomon adamavit mulieres alienigenas multas, filiam quoque Pharaonis, et Moabitidas, et Ammonitidas, Idumæas, et Sidonias, et Hethæas :

** I Kings 11:2

de gentibus super quibus dixit Dominus filiis Israël : Non ingrediemini ad eas, neque de illis ingredientur ad vestras : certissime enim avertent corda vestra ut sequamini deos earum. His itaque copulatus est Salomon ardentissimo amore.

** I Kings 11:3

Fueruntque ei uxores quasi reginæ septingentæ, et concubinæ trecentæ : et averterunt mulieres cor ejus.

** I Kings 11:4

Cumque jam esset senex, depravatum est cor ejus per mulieres, ut sequeretur deos alienos : nec erat cor ejus perfectum cum Domino Deo suo, sicut cor David patris ejus.

** I Kings 11:5

Sed colebat Salomon Astarthen deam Sidoniorum, et Moloch idolum Ammonitarum.

** I Kings 11:6

Fecitque Salomon quod non placuerat coram Domino, et non adimplevit ut sequeretur Dominum sicut David pater ejus.

** I Kings 11:7

Tunc ædificavit Salomon fanum Chamos idolo Moab in monte qui est contra Jerusalem, et Moloch idolo filiorum Ammon.

** I Kings 11:8

Atque in hunc modum fecit universis uxoribus suis alienigenis, quæ adolebant thura, et immolabant diis suis.

** I Kings 11:9

Igitur iratus est Dominus Salomoni, quod aversa esset mens ejus a Domino Deo Israël, qui apparuerat ei secundo,

** I Kings 11:10

et præceperat de verbo hoc ne sequeretur deos alienos : et non custodivit quæ mandavit ei Dominus.

** I Kings 11:11

Dixit itaque Dominus Salomoni : Quia habuisti hoc apud te, et non custodisti pactum meum, et præcepta mea quæ mandavi tibi, disrumpens scindam regnum tuum, et dabo illud servo tuo.

** I Kings 11:12

Verumtamen in diebus tuis non faciam propter David patrem tuum : de manu filii tui scindam illud,

** I Kings 11:13

nec totum regnum auferam, sed tribum unam dabo filio tuo propter David servum meum, et Jerusalem, quam elegi.  

** I Kings 11:14

Suscitavit autem Dominus adversarium Salomoni Adad Idumæum de semine regio, qui erat in Edom.

** I Kings 11:15

Cum enim esset David in Idumæa, et ascendisset Joab princeps militiæ ad sepeliendum eos qui fuerant interfecti, et occidisset omnem masculinum in Idumæa

** I Kings 11:16

(sex enim mensibus ibi moratus est Joab, et omnis Israël, donec interimeret omne masculinum in Idumæa),

** I Kings 11:17

fugit Adad ipse, et viri Idumæi de servis patris ejus cum eo, ut ingrederetur Ægyptum : erat autem Adad puer parvulus.

** I Kings 11:18

Cumque surrexissent de Madian, venerunt in Pharan, tuleruntque secum viros de Pharan, et introierunt Ægyptum ad Pharaonem regem Ægypti : qui dedit ei domum, et cibos constituit, et terram delegavit.

** I Kings 11:19

Et invenit Adad gratiam coram Pharaone valde, in tantum ut daret ei uxorem sororem uxoris suæ germanam Taphnes reginæ.

** I Kings 11:20

Genuitque ei soror Taphnes Genubath filium, et nutrivit eum Taphnes in domo Pharaonis : eratque Genubath habitans apud Pharaonem cum filiis ejus.

** I Kings 11:21

Cumque audisset Adad in Ægypto dormisse David cum patribus suis, et mortuum esse Joab principem militiæ, dixit Pharaoni : Dimitte me, ut vadam in terram meam.

** I Kings 11:22

Dixitque ei Pharao : Qua enim re apud me indiges, ut quæras ire ad terram tuam ? At ille respondit : Nulla : sed obsecro te ut dimittas me.  

** I Kings 11:23

Suscitavit quoque ei Deus adversarium Razon filium Eliada, qui fugerat Adarezer regem Soba dominum suum :

** I Kings 11:24

et congregavit contra eum viros, et factus est princeps latronum cum interficeret eos David : abieruntque Damascum, et habitaverunt ibi, et constituerunt eum regem in Damasco :

** I Kings 11:25

eratque adversarius Israëli cunctis diebus Salomonis : et hoc est malum Adad, et odium contra Israël : regnavitque in Syria.

** I Kings 11:26

Jeroboam quoque filius Nabat, Ephrathæus, de Sareda, servus Salomonis, cujus mater erat nomine Sarva, mulier vidua, levavit manum contra regem.

** I Kings 11:27

Et hæc est causa rebellionis adversus eum, quia Salomon ædificavit Mello, et coæquavit voraginem civitatis David patris sui.

** I Kings 11:28

Erat autem Jeroboam vir fortis et potens : vidensque Salomon adolescentem bonæ indolis et industrium, constituerat eum præfectum super tributa universæ domus Joseph.  

** I Kings 11:29

Factum est igitur in tempore illo, ut Jeroboam egrederetur de Jerusalem, et inveniret eum Ahias Silonites propheta in via, opertus pallio novo : erant autem duo tantum in agro.

** I Kings 11:30

Apprehendensque Ahias pallium suum novum quo coopertus erat, scidit in duodecim partes.

** I Kings 11:31

Et ait ad Jeroboam : Tolle tibi decem scissuras : hæc enim dicit Dominus Deus Israël : Ecce ego scindam regnum de manu Salomonis, et dabo tibi decem tribus.

** I Kings 11:32

Porro una tribus remanebit ei propter servum meum David, et Jerusalem civitatem, quam elegi ex omnibus tribubus Israël :

** I Kings 11:33

eo quod dereliquerit me, et adoraverit Astarthen deam Sidoniorum, et Chamos deum Moab, et Moloch deum filiorum Ammon : et non ambulaverit in viis meis, ut faceret justitiam coram me, et præcepta mea et judicia, sicut David pater ejus.

** I Kings 11:34

Nec auferam omne regnum de manu ejus, sed ducem ponam eum cunctis diebus vitæ suæ, propter David servum meum quem elegi, qui custodivit mandata mea et præcepta mea.

** I Kings 11:35

Auferam autem regnum de manu filii ejus, et dabo tibi decem tribus :

** I Kings 11:36

filio autem ejus dabo tribum unam, ut remaneat lucerna David servo meo cunctis diebus coram me in Jerusalem civitate, quam elegi ut esset nomen meum ibi.

** I Kings 11:37

Te autem assumam, et regnabis super omnia quæ desiderat anima tua, erisque rex super Israël.

** I Kings 11:38

Si igitur audieris omnia quæ præcepero tibi, et ambulaveris in viis meis, et feceris quod rectum est coram me, custodiens mandata mea et præcepta mea, sicut fecit David servus meus : ero tecum, et ædificabo tibi domum fidelem, quomodo ædificavi David domum : et tradam tibi Israël :

** I Kings 11:39

et affligam semen David super hoc, verumtamen non cunctis diebus.

** I Kings 11:40

Voluit ergo Salomon interficere Jeroboam : qui surrexit, et aufugit in Ægyptum ad Sesac regem Ægypti, et fuit in Ægypto usque ad mortem Salomonis.  

** I Kings 11:41

Reliquum autem verborum Salomonis, et omnia quæ fecit, et sapientia ejus, ecce universa scripta sunt in libro verborum dierum Salomonis.

** I Kings 11:42

Dies autem quos regnavit Salomon in Jerusalem super omnem Israël, quadraginta anni sunt.

** I Kings 11:43

Dormivitque Salomon cum patribus suis, et sepultus est in civitate David patris sui : regnavitque Roboam filius ejus pro eo.   

* I Kings 12

** I Kings 12:1

Venit autem Roboam in Sichem : illuc enim congregatus erat omnis Israël ad constituendum eum regem.

** I Kings 12:2

At vero Jeroboam filius Nabat, cum adhuc esset in Ægypto profugus a facie regis Salomonis, audita morte ejus, reversus est de Ægypto.

** I Kings 12:3

Miseruntque et vocaverunt eum : venit ergo Jeroboam, et omnis multitudo Israël, et locuti sunt ad Roboam, dicentes :

** I Kings 12:4

Pater tuus durissimum jugum imposuit nobis : tu itaque nunc imminue paululum de imperio patris tui durissimo, et de jugo gravissimo quod imposuit nobis, et serviemus tibi.

** I Kings 12:5

Qui ait eis : Ite usque ad tertium diem, et revertimini ad me. Cumque abiisset populus,

** I Kings 12:6

iniit consilium rex Roboam cum senioribus qui assistebant coram Salomone patre ejus cum adhuc viveret, et ait : Quod datis mihi consilium, ut respondeam populo huic ?

** I Kings 12:7

Qui dixerunt ei : Si hodie obedieris populo huic, et servieris, et petitioni eorum cesseris, locutusque fueris ad eos verba lenia, erunt tibi servi cunctis diebus.

** I Kings 12:8

Qui dereliquit consilium senum, quod dederant ei, et adhibuit adolescentes, qui nutriti fuerant cum eo, et assistebant illi,

** I Kings 12:9

dixitque ad eos : Quod mihi datis consilium, ut respondeam populo huic, qui dixerunt mihi : Levius fac jugum quod imposuit pater tuus super nos ?

** I Kings 12:10

Et dixerunt ei juvenes qui nutriti fuerant cum eo : Sic loqueris populo huic, qui locuti sunt ad te, dicentes : Pater tuus aggravavit jugum nostrum : tu releva nos. Sic loqueris ad eos : Minimus digitus meus grossior est dorso patris mei.

** I Kings 12:11

Et nunc pater meus posuit super vos jugum grave, ego autem addam super jugum vestrum : pater meus cecidit vos flagellis, ego autem cædam vos scorpionibus.

** I Kings 12:12

Venit ergo Jeroboam et omnis populus ad Roboam die tertia, sicut locutus fuerat rex, dicens : Revertimini ad me die tertia.

** I Kings 12:13

Responditque rex populo dura, derelicto consilio seniorum quod ei dederant,

** I Kings 12:14

et locutus est eis secundum consilium juvenum, dicens : Pater meus aggravavit jugum vestrum, ego autem addam jugo vestro : pater meus cecidit vos flagellis, ego autem cædam vos scorpionibus.

** I Kings 12:15

Et non acquievit rex populo : quoniam aversatus fuerat eum Dominus, ut suscitaret verbum suum quod locutus fuerat in manu Ahiæ Silonitæ, ad Jeroboam filium Nabat.  

** I Kings 12:16

Videns itaque populus quod noluisset eos audire rex, respondit ei dicens : Quæ nobis pars in David ? vel quæ hæreditas in filio Isai ? vade in tabernacula tua, Israël : nunc vide domum tuam, David. Et abiit Israël in tabernacula sua.

** I Kings 12:17

Super filios autem Israël, quicumque habitabant in civitatibus Juda, regnavit Roboam.

** I Kings 12:18

Misit ergo rex Roboam Aduram, qui erat super tributa : et lapidavit eum omnis Israël, et mortuus est. Porro rex Roboam festinus ascendit currum, et fugit in Jerusalem :

** I Kings 12:19

recessitque Israël a domo David usque in præsentem diem.

** I Kings 12:20

Factum est autem cum audisset omnis Israël quod reversus esset Jeroboam, miserunt, et vocaverunt eum congregato cœtu, et constituerunt eum regem super omnem Israël : nec secutus est quisquam domum David præter tribum Juda solam.

** I Kings 12:21

Venit autem Roboam Jerusalem, et congregavit universam domum Juda, et tribum Benjamin, centum octoginta millia electorum virorum bellatorum, ut pugnarent contra domum Israël, et reducerent regnum Roboam filio Salomonis.

** I Kings 12:22

Factus est autem sermo Domini ad Semeiam virum Dei, dicens :

** I Kings 12:23

Loquere ad Roboam filium Salomonis regem Juda, et ad omnem domum Juda, et Benjamin, et reliquos de populo, dicens :

** I Kings 12:24

Hæc dicit Dominus : Non ascendetis, neque bellabitis contra fratres vestros filios Israël : revertatur vir in domum suam : a me enim factum est verbum hoc. Audierunt sermonem Domini, et reversi sunt de itinere, sicut eis præceperat Dominus.  

** I Kings 12:25

Ædificavit autem Jeroboam Sichem in monte Ephraim, et habitavit ibi : et egressus inde ædificavit Phanuel.

** I Kings 12:26

Dixitque Jeroboam in corde suo : Nunc revertetur regnum ad domum David,

** I Kings 12:27

si ascenderit populus iste ut faciat sacrificia in domo Domini in Jerusalem : et convertetur cor populi hujus ad dominum suum Roboam regem Juda, interficientque me, et revertentur ad eum.

** I Kings 12:28

Et excogitato consilio fecit duos vitulos aureos, et dixit eis : Nolite ultra ascendere in Jerusalem : ecce dii tui Israël, qui te eduxerunt de terra Ægypti.

** I Kings 12:29

Posuitque unum in Bethel, et alterum in Dan :

** I Kings 12:30

et factum est verbum hoc in peccatum : ibat enim populus ad adorandum vitulum usque in Dan.

** I Kings 12:31

Et fecit fana in excelsis, et sacerdotes de extremis populi, qui non erant de filiis Levi.

** I Kings 12:32

Constituitque diem solemnem in mense octavo, quintadecima die mensis, in similitudinem solemnitatis quæ celebrabatur in Juda. Et ascendens altare, similiter fecit in Bethel, ut immolaret vitulis quos fabricatus fuerat : constituitque in Bethel sacerdotes excelsorum quæ fecerat.

** I Kings 12:33

Et ascendit super altare quod exstruxerat in Bethel, quintadecima die mensis octavi, quem finxerat de corde suo : et fecit solemnitatem filiis Israël, et ascendit super altare, ut adoleret incensum.   

* I Kings 13

** I Kings 13:1

Et ecce vir Dei venit de Juda in sermone Domini in Bethel, Jeroboam stante super altare, et thus jaciente.

** I Kings 13:2

Et exclamavit contra altare in sermone Domini, et ait : Altare, altare, hæc dicit Dominus : Ecce filius nascetur domui David, Josias nomine, et immolabit super te sacerdotes excelsorum, qui nunc in te thura succendunt : et ossa hominum super te incendet.

** I Kings 13:3

Deditque in illa die signum, dicens : Hoc erit signum quod locutus est Dominus : ecce altare scindetur, et effundetur cinis qui in eo est.

** I Kings 13:4

Cumque audisset rex sermonem hominis Dei quem inclamaverat contra altare in Bethel, extendit manum suam de altari, dicens : Apprehendite eum. Et exaruit manus ejus quam extenderat contra eum, nec valuit retrahere eam ad se.

** I Kings 13:5

Altare quoque scissum est, et effusus est cinis de altari, juxta signum quod prædixerat vir Dei in sermone Domini.

** I Kings 13:6

Et ait rex ad virum Dei : Deprecare faciem Domini Dei tui, et ora pro me, ut restituatur manus mea mihi. Oravitque vir Dei faciem Domini, et reversa est manus regis ad eum, et facta est sicut prius fuerat.

** I Kings 13:7

Locutus est autem rex ad virum Dei : Veni mecum domum ut prandeas, et dabo tibi munera.

** I Kings 13:8

Responditque vir Dei ad regem : Si dederis mihi mediam partem domus tuæ, non veniam tecum, nec comedam panem, neque bibam aquam in loco isto :

** I Kings 13:9

sic enim mandatum est mihi in sermone Domini præcipientis : Non comedes panem, neque bibes aquam, nec reverteris per viam qua venisti.

** I Kings 13:10

Abiit ergo per aliam viam, et non est reversus per iter quo venerat in Bethel.  

** I Kings 13:11

Prophetes autem quidam senex habitabat in Bethel : ad quem venerunt filii sui, et narraverunt ei omnia opera quæ fecerat vir Dei illa die in Bethel : et verba quæ locutus fuerat ad regem, narraverunt patri suo.

** I Kings 13:12

Et dixit eis pater eorum : Per quam viam abiit ? Ostenderunt ei filii sui viam per quam abierat vir Dei, qui venerat de Juda.

** I Kings 13:13

Et ait filiis suis : Sternite mihi asinum. Qui cum stravissent, ascendit,

** I Kings 13:14

et abiit post virum Dei, et invenit eum sedentem subtus terebinthum : et ait illi : Tune es vir Dei qui venisti de Juda ? Respondit ille : Ego sum.

** I Kings 13:15

Dixitque ad eum : Veni mecum domum, ut comedas panem.

** I Kings 13:16

Qui ait : Non possum reverti, neque venire tecum : nec comedam panem, neque bibam aquam in loco isto,

** I Kings 13:17

quia locutus est Dominus ad me in sermone Domini, dicens : Non comedes panem, et non bibes aquam ibi, nec reverteris per viam qua ieris.

** I Kings 13:18

Qui ait illi : Et ego propheta sum similis tui : et angelus locutus est mihi in sermone Domini, dicens : Reduc eum tecum in domum tuam, ut comedat panem, et bibat aquam. Fefellit eum,

** I Kings 13:19

et reduxit secum : comedit ergo panem in domo ejus, et bibit aquam.

** I Kings 13:20

Cumque sederent ad mensam, factus est sermo Domini ad prophetam qui reduxerat eum.

** I Kings 13:21

Et exclamavit ad virum Dei qui venerat de Juda, dicens : Hæc dicit Dominus : Quia non obediens fuisti ori Domini, et non custodisti mandatum quod præcepit tibi Dominus Deus tuus,

** I Kings 13:22

et reversus es, et comedisti panem, et bibisti aquam in loco in quo præcepit tibi ne comederes panem neque biberes aquam, non inferetur cadaver tuum in sepulchrum patrum tuorum.  

** I Kings 13:23

Cumque comedisset et bibisset, stravit asinum suum prophetæ quem reduxerat.

** I Kings 13:24

Qui cum abiisset, invenit eum leo in via, et occidit, et erat cadaver ejus projectum in itinere : asinus autem stabat juxta illum, et leo stabat juxta cadaver.

** I Kings 13:25

Et ecce viri transeuntes viderunt cadaver projectum in via, et leonem stantem juxta cadaver. Et venerunt, et divulgaverunt in civitate in qua prophetes ille senex habitabat.

** I Kings 13:26

Quod cum audisset propheta ille qui reduxerat eum de via, ait : Vir Dei est, qui inobediens fuit ori Domini, et tradidit eum Dominus leoni, et confregit eum, et occidit juxta verbum Domini quod locutus est ei.

** I Kings 13:27

Dixitque ad filios suos : Sternite mihi asinum. Qui cum stravissent,

** I Kings 13:28

et ille abiisset, invenit cadaver ejus projectum in via, et asinum et leonem stantes juxta cadaver : non comedit leo de cadavere, nec læsit asinum.

** I Kings 13:29

Tulit ergo prophetes cadaver viri Dei, et posuit illud super asinum, et reversus intulit in civitatem prophetæ senis ut plangeret eum.

** I Kings 13:30

Et posuit cadaver ejus in sepulchro suo, et planxerunt eum : Heu, heu mi frater !

** I Kings 13:31

Cumque planxissent eum, dixit ad filios suos : Cum mortuus fuero, sepelite me in sepulchro in quo vir Dei sepultus est : juxta ossa ejus ponite ossa mea.

** I Kings 13:32

Profecto enim veniet sermo quem prædixit in sermone Domini contra altare quod est in Bethel, et contra omnia fana excelsorum quæ sunt in urbibus Samariæ.  

** I Kings 13:33

Post verba hæc non est reversus Jeroboam de via sua pessima, sed e contrario fecit de novissimis populi sacerdotes excelsorum : quicumque volebat, implebat manum suam, et fiebat sacerdos excelsorum.

** I Kings 13:34

Et propter hanc causam peccavit domus Jeroboam, et eversa est, et deleta de superficie terræ.   

* I Kings 14

** I Kings 14:1

In tempore illo ægrotavit Abia filius Jeroboam.

** I Kings 14:2

Dixitque Jeroboam uxori suæ : Surge, et commuta habitum, ne cognoscaris quod sis uxor Jeroboam, et vade in Silo, ubi est Ahias propheta, qui locutus est mihi quod regnaturus essem super populum hunc.

** I Kings 14:3

Tolle quoque in manu tua decem panes, et crustulam, et vas mellis, et vade ad illum : ipse enim indicabit tibi quid eventurum sit puero huic.

** I Kings 14:4

Fecit ut dixerat, uxor Jeroboam : et consurgens abiit in Silo, et venit in domum Ahiæ : at ille non poterat videre, quia caligaverant oculi ejus præ senectute.

** I Kings 14:5

Dixit autem Dominus ad Ahiam : Ecce uxor Jeroboam ingreditur ut consulat te super filio suo qui ægrotat : hæc et hæc loqueris ei. Cum ergo illa intraret, et dissimularet se esse quæ erat,

** I Kings 14:6

audivit Ahias sonitum pedum ejus introëuntis per ostium, et ait : Ingredere, uxor Jeroboam : quare aliam te esse simulas ? ego autem missus sum ad te durus nuntius.

** I Kings 14:7

Vade, et dic Jeroboam : Hæc dicit Dominus Deus Israël : Quia exaltavi te de medio populi, et dedi te ducem super populum meum Israël,

** I Kings 14:8

et scidi regnum domus David, et dedi illud tibi, et non fuisti sicut servus meus David, qui custodivit mandata mea, et secutus est me in toto corde suo, faciens quod placitum esset in conspectu meo :

** I Kings 14:9

sed operatus es mala super omnes qui fuerunt ante te, et fecisti tibi deos alienos et conflatiles, ut me ad iracundiam provocares, me autem projecisti post corpus tuum :

** I Kings 14:10

idcirco ecce ego inducam mala super domum Jeroboam, et percutiam de Jeroboam mingentem ad parietem, et clausum, et novissimum in Israël : et mundabo reliquias domus Jeroboam, sicut mundari solet fimus usque ad purum.

** I Kings 14:11

Qui mortui fuerint de Jeroboam in civitate, comedent eos canes : qui autem mortui fuerint in agro, vorabunt eos aves cæli : quia Dominus locutus est.

** I Kings 14:12

Tu igitur surge, et vade in domum tuam : et in ipso introitu pedum tuorum in urbem, morietur puer,

** I Kings 14:13

et planget eum omnis Israël, et sepeliet : iste enim solus inferetur de Jeroboam in sepulchrum, quia inventus est super eo sermo bonus a Domino Deo Israël in domo Jeroboam.

** I Kings 14:14

Constituet autem sibi Dominus regem super Israël, qui percutiet domum Jeroboam in hac die, et in hoc tempore :

** I Kings 14:15

et percutiet Dominus Deus Israël, sicut moveri solet arundo in aqua : et evellet Israël de terra bona hac, quam dedit patribus eorum, et ventilabit eos trans flumen : quia fecerunt sibi lucos, ut irritarent Dominum.

** I Kings 14:16

Et tradet Dominus Israël propter peccata Jeroboam, qui peccavit, et peccare fecit Israël.

** I Kings 14:17

Surrexit itaque uxor Jeroboam, et abiit, et venit in Thersa : cumque illa ingrederetur limen domus, puer mortuus est,

** I Kings 14:18

et sepelierunt eum. Et planxit eum omnis Israël juxta sermonem Domini, quem locutus est in manu servi sui Ahiæ prophetæ.  

** I Kings 14:19

Reliqua autem verborum Jeroboam, quomodo pugnaverit, et quomodo regnaverit, ecce scripta sunt in libro verborum dierum regum Israël.

** I Kings 14:20

Dies autem quibus regnavit Jeroboam, viginti duo anni sunt : et dormivit cum patribus suis, regnavitque Nadab filius ejus pro eo.  

** I Kings 14:21

Porro Roboam filius Salomonis regnavit in Juda. Quadraginta et unius anni erat Roboam cum regnare cœpisset : decem et septem annos regnavit in Jerusalem civitate, quam elegit Dominus ut poneret nomen suum ibi, ex omnibus tribubus Israël. Nomen autem matris ejus Naama Ammanitis.

** I Kings 14:22

Et fecit Judas malum coram Domino, et irritaverunt eum super omnibus quæ fecerant patres eorum in peccatis suis quæ peccaverunt.

** I Kings 14:23

Ædificaverunt enim et ipsi sibi aras, et statuas, et lucos super omnem collem excelsum, et subter omnem arborem frondosam :

** I Kings 14:24

sed et effeminati fuerunt in terra, feceruntque omnes abominationes gentium quas attrivit Dominus ante faciem filiorum Israël.

** I Kings 14:25

In quinto autem anno regni Roboam, ascendit Sesac rex Ægypti in Jerusalem,

** I Kings 14:26

et tulit thesauros domus Domini, et thesauros regios, et universa diripuit : scuta quoque aurea, quæ fecerat Salomon :

** I Kings 14:27

pro quibus fecit rex Roboam scuta ærea, et tradidit ea in manum ducum scutariorum, et eorum qui excubabant ante ostium domus regis.

** I Kings 14:28

Cumque ingrederetur rex in domum Domini, portabant ea qui præeundi habebant officium : et postea reportabant ad armamentarium scutariorum.

** I Kings 14:29

Reliqua autem sermonum Roboam, et omnia quæ fecit, ecce scripta sunt in libro sermonum dierum regum Juda.

** I Kings 14:30

Fuitque bellum inter Roboam et Jeroboam cunctis diebus.

** I Kings 14:31

Dormivitque Roboam cum patribus suis, et sepultus est cum eis in civitate David : nomen autem matris ejus Naama Ammanitis : et regnavit Abiam filius ejus pro eo.   

* I Kings 15

** I Kings 15:1

Igitur in octavodecimo anno regni Jeroboam filii Nabat, regnavit Abiam super Judam.

** I Kings 15:2

Tribus annis regnavit in Jerusalem : nomen matris ejus Maacha filia Abessalom.

** I Kings 15:3

Ambulavitque in omnibus peccatis patris sui, quæ fecerat ante eum : nec erat cor ejus perfectum cum Domino Deo suo, sicut cor David patris ejus.

** I Kings 15:4

Sed propter David dedit ei Dominus Deus suus lucernam in Jerusalem, ut suscitaret filium ejus post eum, et statueret Jerusalem :

** I Kings 15:5

eo quod fecisset David rectum in oculis Domini, et non declinasset ab omnibus quæ præceperat ei cunctis diebus vitæ suæ, excepto sermone Uriæ Hethæi.

** I Kings 15:6

Attamen bellum fuit inter Roboam et Jeroboam omni tempore vitæ ejus.

** I Kings 15:7

Reliqua autem sermonum Abiam, et omnia quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ? Fuitque prælium inter Abiam et inter Jeroboam.

** I Kings 15:8

Et dormivit Abiam cum patribus suis, et sepelierunt eum in civitate David, regnavitque Asa filius ejus pro eo.  

** I Kings 15:9

In anno ergo vigesimo Jeroboam regis Israël regnavit Asa rex Juda,

** I Kings 15:10

et quadraginta et uno anno regnavit in Jerusalem. Nomen matris ejus Maacha filia Abessalom.

** I Kings 15:11

Et fecit Asa rectum ante conspectum Domini, sicut David pater ejus :

** I Kings 15:12

et abstulit effeminatos de terra, purgavitque universas sordes idolorum quæ fecerant patres ejus.

** I Kings 15:13

Insuper et Maacham matrem suam amovit, ne esset princeps in sacris Priapi, et in luco ejus quem consecraverat : subvertitque specum ejus, et confregit simulacrum turpissimum, et combussit in torrente Cedron :

** I Kings 15:14

excelsa autem non abstulit. Verumtamen cor Asa perfectum erat cum Domino cunctis diebus suis :

** I Kings 15:15

et intulit ea quæ sanctificaverat pater suus, et voverat, in domum Domini, argentum, et aurum, et vasa.  

** I Kings 15:16

Bellum autem erat inter Asa, et Baasa regem Israël cunctis diebus eorum.

** I Kings 15:17

Ascendit quoque Baasa rex Israël in Judam, et ædificavit Rama, ut non posset quispiam egredi vel ingredi de parte Asa regis Juda.

** I Kings 15:18

Tollens itaque Asa omne argentum et aurum quod remanserat in thesauris domus Domini, et in thesauris domus regiæ, et dedit illud in manus servorum suorum : et misit ad Benadad filium Tabremon filii Hezion, regem Syriæ, qui habitabat in Damasco, dicens :

** I Kings 15:19

Fœdus est inter me et te, et inter patrem meum et patrem tuum : ideo misi tibi munera, argentum et aurum : et peto ut venias, et irritum facias fœdus quod habes cum Baasa rege Israël, et recedat a me.

** I Kings 15:20

Acquiescens Benadad regi Asa, misit principes exercitus sui in civitates Israël, et percusserunt Ahion, et Dan, et Abeldomum Maacha, et universam Cenneroth, omnem scilicet terram Nephthali.

** I Kings 15:21

Quod cum audisset Baasa, intermisit ædificare Rama, et reversus est in Thersa.

** I Kings 15:22

Rex autem Asa nuntium misit in omnem Judam, dicens : Nemo sit excusatus. Et tulerunt lapides de Rama, et ligna ejus, quibus ædificaverat Baasa, et exstruxit de eis rex Asa Gabaa Benjamin, et Maspha.

** I Kings 15:23

Reliqua autem omnium sermonum Asa, et universæ fortitudines ejus, et cuncta quæ fecit, et civitates quas exstruxit, nonne hæc scripta sunt in libro verborum dierum regum Juda ? Verumtamen in tempore senectutis suæ doluit pedes.

** I Kings 15:24

Et dormivit cum patribus suis, et sepultus est cum eis in civitate David patris sui. Regnavitque Josaphat filius ejus pro eo.  

** I Kings 15:25

Nadab vero filius Jeroboam regnavit super Israël anno secundo Asa regis Juda : regnavitque super Israël duobus annis.

** I Kings 15:26

Et fecit quod malum est in conspectu Domini, et ambulavit in viis patris sui, et in peccatis ejus quibus peccare fecit Israël.

** I Kings 15:27

Insidiatus est autem ei Baasa filius Ahiæ de domo Issachar, et percussit eum in Gebbethon, quæ est urbs Philisthinorum : siquidem Nadab et omnis Israël obsidebant Gebbethon.

** I Kings 15:28

Interfecit ergo illum Baasa in anno tertio Asa regis Juda, et regnavit pro eo.

** I Kings 15:29

Cumque regnasset, percussit omnem domum Jeroboam : non dimisit ne unam quidem animam de semine ejus donec deleret eum, juxta verbum Domini quod locutus fuerat in manu servi sui Ahiæ Silonitis,

** I Kings 15:30

propter peccata Jeroboam, quæ peccaverat, et quibus peccare fecerat Israël : et propter delictum quo irritaverat Dominum Deum Israël.

** I Kings 15:31

Reliqua autem sermonum Nadab, et omnia quæ operatus est, nonne hæc scripta sunt in libro verborum dierum regum Israël ?

** I Kings 15:32

Fuitque bellum inter Asa, et Baasa regem Israël, cunctis diebus eorum.  

** I Kings 15:33

Anno tertio Asa regis Juda, regnavit Baasa filius Ahiæ super omnem Israël in Thersa, viginti quatuor annis.

** I Kings 15:34

Et fecit malum coram Domino, ambulavitque in via Jeroboam, et in peccatis ejus quibus peccare fecit Israël.   

* I Kings 16

** I Kings 16:1

Factus est autem sermo Domini ad Jehu filium Hanani contra Baasa, dicens :

** I Kings 16:2

Pro eo quod exaltavi te de pulvere, et posui te ducem super populum meum Israël, tu autem ambulasti in via Jeroboam, et peccare fecisti populum meum Israël, ut me irritares in peccatis eorum :

** I Kings 16:3

ecce ego demetam posteriora Baasa, et posteriora domus ejus, et faciam domum tuam sicut domum Jeroboam filii Nabat.

** I Kings 16:4

Qui mortuus fuerit de Baasa in civitate, comedent eum canes : et qui mortuus fuerit ex eo in regione, comedent eum volucres cæli.

** I Kings 16:5

Reliqua autem sermonum Baasa, et quæcumque fecit, et prælia ejus, nonne hæc scripta sunt in libro verborum dierum regum Israël ?

** I Kings 16:6

Dormivit ergo Baasa cum patribus suis, sepultusque est in Thersa : et regnavit Ela filius ejus pro eo.

** I Kings 16:7

Cum autem in manu Jehu filii Hanani prophetæ verbum Domini factum esset contra Baasa, et contra domum ejus, et contra omne malum quod fecerat coram Domino, ad irritandum eum in operibus manuum suarum, ut fieret sicut domus Jeroboam : ob hanc causam occidit eum, hoc est, Jehu filium Hanani prophetam.  

** I Kings 16:8

Anno vigesimo sexto Asa regis Juda, regnavit Ela filius Baasa super Israël in Thersa, duobus annis.

** I Kings 16:9

Et rebellavit contra eum servus suus Zambri, dux mediæ partis equitum : erat autem Ela in Thersa bibens, et temulentus in domo Arsa præfecti Thersa.

** I Kings 16:10

Irruens ergo Zambri, percussit et occidit eum, anno vigesimo septimo Asa regis Juda, et regnavit pro eo.

** I Kings 16:11

Cumque regnasset, et sedisset super solium ejus, percussit omnem domum Baasa, et non dereliquit ex ea mingentem ad parietem : et propinquos et amicos ejus.

** I Kings 16:12

Delevitque Zambri omnem domum Baasa, juxta verbum Domini quod locutus fuerat ad Baasa in manu Jehu prophetæ,

** I Kings 16:13

propter universa peccata Baasa, et peccata Ela filii ejus, qui peccaverunt, et peccare fecerunt Israël, provocantes Dominum Deum Israël in vanitatibus suis.

** I Kings 16:14

Reliqua autem sermonum Ela, et omnia quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Israël ?  

** I Kings 16:15

Anno vigesimo septimo Asa regis Juda, regnavit Zambri septem diebus in Thersa : porro exercitus obsidebat Gebbethon urbem Philisthinorum.

** I Kings 16:16

Cumque audisset rebellasse Zambri, et occidisse regem, fecit sibi regem omnis Israël Amri, qui erat princeps militiæ super Israël in die illa in castris.

** I Kings 16:17

Ascendit ergo Amri, et omnis Israël cum eo, de Gebbethon, et obsidebant Thersa.

** I Kings 16:18

Videns autem Zambri quod expugnanda esset civitas, ingressus est palatium, et succendit se cum domo regia : et mortuus est

** I Kings 16:19

in peccatis suis quæ peccaverat, faciens malum coram Domino, et ambulans in via Jeroboam, et in peccato ejus, quo fecit peccare Israël.

** I Kings 16:20

Reliqua autem sermonum Zambri, et insidiarum ejus, et tyrannidis, nonne hæc scripta sunt in libro verborum dierum regum Israël ?

** I Kings 16:21

Tunc divisus est populus Israël in duas partes : media pars populi sequebatur Thebni filium Gineth, ut constitueret eum regem : et media pars Amri.

** I Kings 16:22

Prævaluit autem populus qui erat cum Amri, populo qui sequebatur Thebni filium Gineth : mortuusque est Thebni, et regnavit Amri.  

** I Kings 16:23

Anno trigesimo primo Asa regis Juda, regnavit Amri super Israël, duodecim annis : in Thersa regnavit sex annis.

** I Kings 16:24

Emitque montem Samariæ a Somer duobus talentis argenti : et ædificavit eum, et vocavit nomen civitatis quam exstruxerat, nomine Semer domini montis, Samariam.

** I Kings 16:25

Fecit autem Amri malum in conspectu Domini, et operatus est nequiter, super omnes qui fuerunt ante eum.

** I Kings 16:26

Ambulavitque in omni via Jeroboam filii Nabat, et in peccatis ejus quibus peccare fecerat Israël, ut irritaret Dominum Deum Israël in vanitatibus suis.

** I Kings 16:27

Reliqua autem sermonum Amri, et prælia ejus quæ gessit, nonne hæc scripta sunt in libro verborum dierum regum Israël ?

** I Kings 16:28

Dormivitque Amri cum patribus suis, et sepultus est in Samaria : regnavitque Achab filius ejus pro eo.  

** I Kings 16:29

Achab vero filius Amri regnavit super Israël anno trigesimo octavo Asa regis Juda. Et regnavit Achab filius Amri super Israël in Samaria viginti et duobus annis.

** I Kings 16:30

Et fecit Achab filius Amri malum in conspectu Domini super omnes qui fuerunt ante eum.

** I Kings 16:31

Nec suffecit ei ut ambularet in peccatis Jeroboam filii Nabat : insuper duxit uxorem Jezabel filiam Ethbaal regis Sidoniorum. Et abiit, et servivit Baal, et adoravit eum.

** I Kings 16:32

Et posuit aram Baal in templo Baal, quod ædificaverat in Samaria,

** I Kings 16:33

et plantavit lucum : et addidit Achab in opere suo, irritans Dominum Deum Israël super omnes reges Israël qui fuerunt ante eum.

** I Kings 16:34

In diebus ejus ædificavit Hiel de Bethel Jericho : in Abiram primitivo suo fundavit eam, et in Segub novissimo suo posuit portas ejus, juxta verbum Domini quod locutus fuerat in manu Josue filii Nun.   

* I Kings 17

** I Kings 17:1

Et dixit Elias Thesbites de habitatoribus Galaad ad Achab : Vivit Dominus Deus Israël, in cujus conspectu sto, si erit annis his ros et pluvia, nisi juxta oris mei verba.

** I Kings 17:2

Et factum est verbum Domini ad eum, dicens :

** I Kings 17:3

Recede hinc, et vade contra orientem, et abscondere in torrente Carith, qui est contra Jordanem,

** I Kings 17:4

et ibi de torrente bibes : corvisque præcepi ut pascant te ibi.

** I Kings 17:5

Abiit ergo, et fecit juxta verbum Domini : cumque abiisset, sedit in torrente Carith, qui est contra Jordanem.

** I Kings 17:6

Corvi quoque deferebant ei panem et carnes mane, similiter panem et carnes vesperi, et bibebat de torrente.

** I Kings 17:7

Post dies autem siccatus est torrens : non enim pluerat super terram.  

** I Kings 17:8

Factus est ergo sermo Domini ad eum, dicens :

** I Kings 17:9

Surge, et vade in Sarephta Sidoniorum, et manebis ibi : præcepi enim ibi mulieri viduæ ut pascat te.

** I Kings 17:10

Surrexit, et abiit in Sarephta. Cumque venisset ad portam civitatis, apparuit ei mulier vidua colligens ligna, et vocavit eam, dixitque ei : Da mihi paululum aquæ in vase ut bibam.

** I Kings 17:11

Cumque illa pergeret ut afferret, clamavit post tergum ejus, dicens : Affer mihi, obsecro, et buccellam panis in manu tua.

** I Kings 17:12

Quæ respondit : Vivit Dominus Deus tuus, quia non habeo panem, nisi quantum pugillus capere potest farinæ in hydria, et paululum olei in lecytho : en colligo duo ligna ut ingrediar et faciam illum mihi et filio meo, ut comedamus, et moriamur.

** I Kings 17:13

Ad quam Elias ait : Noli timere, sed vade, et fac sicut dixisti : verumtamen mihi primum fac de ipsa farinula subcinericium panem parvulum, et affer ad me : tibi autem et filio tuo facies postea.

** I Kings 17:14

Hæc autem dicit Dominus Deus Israël : Hydria farinæ non deficiet, nec lecythus olei minuetur, usque ad diem in qua Dominus daturus est pluviam super faciem terræ.

** I Kings 17:15

Quæ abiit, et fecit juxta verbum Eliæ : et comedit ipse, et illa, et domus ejus : et ex illa die

** I Kings 17:16

hydria farinæ non defecit, et lecythus olei non est imminutus, juxta verbum Domini quod locutus fuerat in manu Eliæ.

** I Kings 17:17

Factum est autem post hæc, ægrotavit filius mulieris matrisfamilias, et erat languor fortissimus, ita ut non remaneret in eo halitus.

** I Kings 17:18

Dixit ergo ad Eliam : Quid mihi et tibi, vir Dei ? ingressus es ad me, ut rememorarentur iniquitates meæ, et interficeres filium meum ?

** I Kings 17:19

Et ait ad eam Elias : Da mihi filium tuum. Tulitque eum de sinu ejus, et portavit in cœnaculum ubi ipse manebat, et posuit super lectulum suum.

** I Kings 17:20

Et clamavit ad Dominum, et dixit : Domine Deus meus, etiam ne viduam apud quam ego utcumque sustentor, afflixisti ut interficeres filium ejus ?

** I Kings 17:21

Et expandit se, atque mensus est super puerum tribus vicibus, et clamavit ad Dominum, et ait : Domine Deus meus, revertatur, obsecro, anima pueri hujus in viscera ejus.

** I Kings 17:22

Et exaudivit Dominus vocem Eliæ : et reversa est anima pueri intra eum, et revixit.

** I Kings 17:23

Tulitque Elias puerum, et deposuit eum de cœnaculo in inferiorem domum, et tradidit matri suæ, et ait illi : En vivit filius tuus.

** I Kings 17:24

Dixitque mulier ad Eliam : Nunc in isto cognovi quoniam vir Dei es tu, et verbum Domini in ore tuo verum est.   

* I Kings 18

** I Kings 18:1

Post dies multos factum est verbum Domini ad Eliam, in anno tertio, dicens : Vade, et ostende te Achab, ut dem pluviam super faciem terræ.

** I Kings 18:2

Ivit ergo Elias, ut ostenderet se Achab : erat autem fames vehemens in Samaria.

** I Kings 18:3

Vocavitque Achab Abdiam dispensatorem domus suæ : Abdias autem timebat Dominum valde.

** I Kings 18:4

Nam cum interficeret Jezabel prophetas Domini, tulit ille centum prophetas, et abscondit eos quinquagenos et quinquagenos in speluncis, et pavit eos pane et aqua.

** I Kings 18:5

Dixit ergo Achab ad Abdiam : Vade in terram ad universos fontes aquarum, et in cunctas valles, si forte possimus invenire herbam, et salvare equos et mulos, et non penitus jumenta intereant.

** I Kings 18:6

Diviseruntque sibi regiones ut circuirent eas : Achab ibat per viam unam, et Abdias per viam alteram seorsum.

** I Kings 18:7

Cumque esset Abdias in via, Elias occurrit ei : qui cum cognovisset eum, cecidit super faciem suam, et ait : Num tu es, domine mi, Elias ?

** I Kings 18:8

Cui ille respondit : Ego. Vade, et dic domino tuo : Adest Elias.

** I Kings 18:9

Et ille : Quid peccavi, inquit, quoniam tradis me servum tuum in manu Achab, ut interficiat me ?

** I Kings 18:10

Vivit Dominus Deus tuus, quia non est gens aut regnum quo non miserit dominus meus te requirens : et respondentibus cunctis : Non est hic : adjuravit regna singula et gentes, eo quod minime reperireris.

** I Kings 18:11

Et nunc tu dicis mihi : Vade, et dic domino tuo : Adest Elias.

** I Kings 18:12

Cumque recessero a te, spiritus Domini asportabit te in locum quem ego ignoro : et ingressus nuntiabo Achab, et non inveniens te, interficiet me : servus autem tuus timet Dominum ab infantia sua.

** I Kings 18:13

Numquid non indicatum est tibi domino meo quid fecerim cum interficeret Jezabel prophetas Domini, quod absconderim de prophetis Domini centum viros, quinquagenos et quinquagenos, in speluncis, et paverim eos pane et aqua ?

** I Kings 18:14

et nunc tu dicis : Vade, et dic domino tuo : Adest Elias : ut interficiat me ?

** I Kings 18:15

Et dixit Elias : Vivit Dominus exercituum, ante cujus vultum sto, quia hodie apparebo ei.

** I Kings 18:16

Abiit ergo Abdias in occursum Achab, et indicavit ei : venitque Achab in occursum Eliæ.

** I Kings 18:17

Et cum vidisset eum, ait : Tune es ille, qui conturbas Israël ?

** I Kings 18:18

Et ille ait : Non ego turbavi Israël, sed tu, et domus patris tui, qui dereliquistis mandata Domini, et secuti estis Baalim.  

** I Kings 18:19

Verumtamen nunc mitte, et congrega ad me universum Israël in monte Carmeli, et prophetas Baal quadringentos quinquaginta, prophetasque lucorum quadringentos, qui comedunt de mensa Jezabel.

** I Kings 18:20

Misit Achab ad omnes filios Israël, et congregavit prophetas in monte Carmeli.

** I Kings 18:21

Accedens autem Elias ad omnem populum, ait : Usquequo claudicatis in duas partes ? si Dominus est Deus, sequimini eum : si autem Baal, sequimini illum. Et non respondit ei populus verbum.

** I Kings 18:22

Et ait rursus Elias ad populum : Ego remansi propheta Domini solus : prophetæ autem Baal quadringenti et quinquaginta viri sunt.

** I Kings 18:23

Dentur nobis duo boves, et illi eligant sibi bovem unum, et in frusta cædentes ponant super ligna, ignem autem non supponant : et ego faciam bovem alterum, et imponam super ligna, ignem autem non supponam.

** I Kings 18:24

Invocate nomina deorum vestrorum, et ego invocabo nomen Domini mei : et Deus qui exaudierit per ignem, ipse sit Deus. Respondens omnis populus ait : Optima propositio.

** I Kings 18:25

Dixit ergo Elias prophetis Baal : Eligite vobis bovem unum, et facite primi, quia vos plures estis : et invocate nomina deorum vestrorum, ignemque non supponatis.

** I Kings 18:26

Qui cum tulissent bovem quem dederat eis, fecerunt : et invocabant nomen Baal de mane usque ad meridiem, dicentes : Baal, exaudi nos. Et non erat vox, nec qui responderet : transiliebantque altare quod fecerant.

** I Kings 18:27

Cumque esset jam meridies, illudebat illis Elias, dicens : Clamate voce majore : deus enim est, et forsitan loquitur, aut in diversorio est, aut in itinere, aut certe dormit, ut excitetur.

** I Kings 18:28

Clamabant ergo voce magna, et incidebant se juxta ritum suum cultris et lanceolis, donec perfunderentur sanguine.

** I Kings 18:29

Postquam autem transiit meridies, et illis prophetantibus venerat tempus quo sacrificium offerri solet, nec audiebatur vox, nec aliquis respondebat, nec attendebat orantes,

** I Kings 18:30

dixit Elias omni populo : Venite ad me.   Et accedente ad se populo, curavit altare Domini quod destructum fuerat.

** I Kings 18:31

Et tulit duodecim lapides juxta numerum tribuum filiorum Jacob, ad quem factus est sermo Domini, dicens : Israël erit nomen tuum.

** I Kings 18:32

Et ædificavit de lapidibus altare in nomine Domini : fecitque aquæductum, quasi per duas aratiunculas in circuitu altaris,

** I Kings 18:33

et composuit ligna : divisitque per membra bovem, et posuit super ligna,

** I Kings 18:34

et ait : Implete quatuor hydrias aqua, et fundite super holocaustum et super ligna. Rursumque dixit : Etiam secundo hoc facite. Qui cum fecissent secundo, ait : Etiam tertio idipsum facite. Feceruntque tertio,

** I Kings 18:35

et currebant aquæ circum altare, et fossa aquæductus repleta est.

** I Kings 18:36

Cumque jam tempus esset ut offerretur holocaustum, accedens Elias propheta ait : Domine Deus Abraham, et Isaac, et Israël, ostende hodie quia tu es Deus Israël, et ego servus tuus, et juxta præceptum tuum feci omnia verba hæc.

** I Kings 18:37

Exaudi me, Domine, exaudi me : ut discat populus iste quia tu es Dominus Deus, et tu convertisti cor eorum iterum.

** I Kings 18:38

Cecidit autem ignis Domini, et voravit holocaustum, et ligna, et lapides, pulverem quoque, et aquam quæ erat in aquæductu lambens.

** I Kings 18:39

Quod cum vidisset omnis populus, cecidit in faciem suam, et ait : Dominus ipse est Deus, Dominus ipse est Deus.

** I Kings 18:40

Dixitque Elias ad eos : Apprehendite prophetas Baal, et ne unus quidem effugiat ex eis. Quos cum apprehendissent, duxit eos Elias ad torrentem Cison, et interfecit eos ibi.  

** I Kings 18:41

Et ait Elias ad Achab : Ascende, comede, et bibe, quia sonus multæ pluviæ est.

** I Kings 18:42

Ascendit Achab ut comederet et biberet : Elias autem ascendit in verticem Carmeli, et pronus in terram posuit faciem suam inter genua sua,

** I Kings 18:43

et dixit ad puerum suum : Ascende, et prospice contra mare. Qui cum ascendisset, et contemplatus esset, ait : Non est quidquam. Et rursum ait illi : Revertere septem vicibus.

** I Kings 18:44

In septima autem vice, ecce nubecula parva quasi vestigium hominis ascendebat de mari. Qui ait : Ascende, et dic Achab : Junge currum tuum et descende, ne occupet te pluvia.

** I Kings 18:45

Cumque se verteret huc atque illuc, ecce cæli contenebrati sunt, et nubes, et ventus, et facta est pluvia grandis. Ascendens itaque Achab, abiit in Jezrahel :

** I Kings 18:46

et manus Domini facta est super Eliam, accinctisque lumbis currebat ante Achab, donec veniret in Jezrahel.   

* I Kings 19

** I Kings 19:1

Nuntiavit autem Achab Jezabel omnia quæ fecerat Elias, et quomodo occidisset universos prophetas gladio.

** I Kings 19:2

Misitque Jezabel nuntium ad Eliam, dicens : Hæc mihi faciant dii, et hæc addant, nisi hac hora cras posuero animam tuam sicut animam unius ex illis.

** I Kings 19:3

Timuit ergo Elias, et surgens abiit quocumque eum ferebat voluntas : venitque in Bersabee Juda, et dimisit ibi puerum suum,

** I Kings 19:4

et perrexit in desertum, viam unius diei. Cumque venisset, et sederet subter unam juniperum, petivit animæ suæ ut moreretur, et ait : Sufficit mihi, Domine : tolle animam meam : neque enim melior sum quam patres mei.

** I Kings 19:5

Projecitque se, et obdormivit in umbra juniperi : et ecce angelus Domini tetigit eum, et dixit illi : Surge, et comede.

** I Kings 19:6

Respexit, et ecce ad caput suum subcinericius panis, et vas aquæ : comedit ergo, et bibit, et rursum obdormivit.

** I Kings 19:7

Reversusque est angelus Domini secundo, et tetigit eum, dixitque illi : Surge, comede : grandis enim tibi restat via.

** I Kings 19:8

Qui cum surrexisset, comedit et bibit, et ambulavit in fortitudine cibi illius quadraginta diebus et quadraginta noctibus usque ad montem Dei Horeb.  

** I Kings 19:9

Cumque venisset illuc, mansit in spelunca : et ecce sermo Domini ad eum, dixitque illi : Quid hic agis, Elia ?

** I Kings 19:10

At ille respondit : Zelo zelatus sum pro Domino Deo exercituum, quia dereliquerunt pactum tuum filii Israël : altaria tua destruxerunt, prophetas tuos occiderunt gladio, derelictus sum ego solus, et quærunt animam meam ut auferant eam.

** I Kings 19:11

Et ait ei : Egredere, et sta in monte coram Domino : et ecce Dominus transit. Et spiritus grandis et fortis subvertens montes, et conterens petras, ante Dominum : non in spiritu Dominus. Et post spiritum commotio : non in commotione Dominus.

** I Kings 19:12

Et post commotionem ignis : non in igne Dominus. Et post ignem sibilus auræ tenuis.

** I Kings 19:13

Quod cum audisset Elias, operuit vultum suum pallio, et egressus stetit in ostio speluncæ. Et ecce vox ad eum dicens : Quid hic agis, Elia ? Et ille respondit :

** I Kings 19:14

Zelo zelatus sum pro Domino Deo exercituum, quia dereliquerunt pactum tuum filii Israël : altaria tua destruxerunt, prophetas tuos occiderunt gladio, derelictus sum ego solus, et quærunt animam meam ut auferant eam.

** I Kings 19:15

Et ait Dominus ad eum : Vade, et revertere in viam tuam per desertum in Damascum : cumque perveneris illuc, unges Hazaël regem super Syriam,

** I Kings 19:16

et Jehu filium Namsi unges regem super Israël : Eliseum autem filium Saphat, qui est de Abelmehula, unges prophetam pro te.

** I Kings 19:17

Et erit : quicumque fugerit gladium Hazaël, occidet eum Jehu : et quicumque fugerit gladium Jehu, interficiet eum Eliseus.

** I Kings 19:18

Et derelinquam mihi in Israël septem millia virorum, quorum genua non sunt incurvata ante Baal, et omne os quod non adoravit eum osculans manus.  

** I Kings 19:19

Profectus ergo inde Elias, reperit Eliseum filium Saphat, arantem in duodecim jugis boum. Et ipse in duodecim jugis boum arantibus unus erat : cumque venisset Elias ad eum, misit pallium suum super illum.

** I Kings 19:20

Qui statim relictis bobus cucurrit post Eliam, et ait : Osculer, oro, patrem meum, et matrem meam, et sic sequar te. Dixitque ei : Vade, et revertere : quod enim meum erat, feci tibi.

** I Kings 19:21

Reversus autem ab eo, tulit par boum, et mactavit illud, et in aratro boum coxit carnes, et dedit populo, et comederunt : consurgensque abiit, et secutus est Eliam, et ministrabat ei.   

* I Kings 20

** I Kings 20:1

Porro Benadad rex Syriæ congregavit omnem exercitum suum, et triginta duos reges secum, et equos, et currus : et ascendens pugnabat contra Samariam, et obsidebat eam.

** I Kings 20:2

Mittensque nuntios ad Achab regem Israël in civitatem,

** I Kings 20:3

ait : Hæc dicit Benadad : Argentum tuum, et aurum tuum meum est : et uxores tuæ, et filii tui optimi, mei sunt.

** I Kings 20:4

Responditque rex Israël : Juxta verbum tuum, domine mi rex, tuus sum ego, et omnia mea.

** I Kings 20:5

Revertentesque nuntii, dixerunt : Hæc dicit Benadad, qui misit nos ad te : Argentum tuum, et aurum tuum, et uxores tuas, et filios tuos, dabis mihi.

** I Kings 20:6

Cras igitur hac eadem hora mittam servos meos ad te, et scrutabuntur domum tuam, et domum servorum tuorum : et omne quod eis placuerit, ponent in manibus suis, et auferent.

** I Kings 20:7

Vocavit autem rex Israël omnes seniores terræ, et ait : Animadvertite, et videte quoniam insidietur nobis : misit enim ad me pro uxoribus meis, et filiis, et pro argento et auro : et non abnui.

** I Kings 20:8

Dixeruntque omnes majores natu, et universus populus, ad eum : Non audias, neque acquiescas illi.

** I Kings 20:9

Respondit itaque nuntiis Benadad : Dicite domino meo regi : Omnia propter quæ misisti ad me servum tuum in initio, faciam : hanc autem rem facere non possum.

** I Kings 20:10

Reversique nuntii retulerunt ei. Qui remisit, et ait : Hæc faciant mihi dii, et hæc addant, si suffecerit pulvis Samariæ pugillis omnis populi qui sequitur me.

** I Kings 20:11

Et respondens rex Israël, ait : Dicite ei : Ne glorietur, accinctus æque ut discinctus.

** I Kings 20:12

Factum est autem cum audisset Benadad verbum istud, bibebat ipse et reges in umbraculis : et ait servis suis : Circumdate civitatem. Et circumdederunt eam.  

** I Kings 20:13

Et ecce propheta unus accedens ad Achab regem Israël, ait ei : Hæc dicit Dominus : Certe vidisti omnem multitudinem hanc nimiam ? ecce ego tradam eam in manu tua hodie, ut scias quia ego sum Dominus.

** I Kings 20:14

Et ait Achab : Per quem ? Dixitque ei : Hæc dicit Dominus : Per pedissequos principum provinciarum. Et ait : Quis incipiet præliari ? Et ille dixit : Tu.

** I Kings 20:15

Recensuit ergo pueros principum provinciarum, et reperit numerum ducentorum triginta duorum : et recensuit post eos populum, omnes filios Israël, septem millia.

** I Kings 20:16

Et egressi sunt meridie. Benadad autem bibebat temulentus in umbraculo suo, et reges triginta duo cum eo, qui ad auxilium ejus venerant.

** I Kings 20:17

Egressi sunt autem pueri principum provinciarum in prima fronte. Misit itaque Benadad : qui nuntiaverunt ei, dicentes : Viri egressi sunt de Samaria.

** I Kings 20:18

Et ille ait : Sive pro pace veniunt, apprehendite eos vivos : sive ut prælientur, vivos eos capite.

** I Kings 20:19

Egressi sunt ergo pueri principum provinciarum, ac reliquus exercitus sequebatur :

** I Kings 20:20

et percussit unusquisque virum qui contra se veniebat : fugeruntque Syri, et persecutus est eos Israël. Fugit quoque Benadad rex Syriæ in equo cum equitibus suis.

** I Kings 20:21

Necnon egressus rex Israël percussit equos et currus, et percussit Syriam plaga magna.

** I Kings 20:22

Accedens autem propheta ad regem Israël, dixit ei : Vade, et confortare, et scito, et vide quid facias : sequenti enim anno rex Syriæ ascendet contra te.  

** I Kings 20:23

Servi vero regis Syriæ dixerunt ei : Dii montium sunt dii eorum, ideo superaverunt nos : sed melius est ut pugnemus contra eos in campestribus, et obtinebimus eos.

** I Kings 20:24

Tu ergo verbum hoc fac : amove reges singulos ab exercitu tuo, et pone principes pro eis :

** I Kings 20:25

et instaura numerum militum qui ceciderunt de tuis, et equos secundum equos pristinos, et currus secundum currus quos ante habuisti : et pugnabimus contra eos in campestribus, et videbis quod obtinebimus eos. Credidit consilio eorum, et fecit ita.

** I Kings 20:26

Igitur postquam annus transierat, recensuit Benadad Syros, et ascendit in Aphec ut pugnaret contra Israël.

** I Kings 20:27

Porro filii Israël recensiti sunt, et acceptis cibariis profecti ex adverso, castraque metati sunt contra eos, quasi duo parvi greges caprarum : Syri autem repleverunt terram.

** I Kings 20:28

(Et accedens unus vir Dei, dixit ad regem Israël : Hæc dicit Dominus : Quia dixerunt Syri : Deus montium est Dominus, et non est Deus vallium : dabo omnem multitudinem hanc grandem in manu tua, et scietis quia ego sum Dominus.)

** I Kings 20:29

Dirigebantque septem diebus ex adverso hi atque illi acies, septima autem die commissum est bellum : percusseruntque filii Israël de Syris centum millia peditum in die una.

** I Kings 20:30

Fugerunt autem qui remanserant in Aphec, in civitatem : et cecidit murus super viginti septem millia hominum qui remanserant. Porro Benadad fugiens ingressus est civitatem, in cubiculum quod erat intra cubiculum.

** I Kings 20:31

Dixeruntque ei servi sui : Ecce, audivimus quod reges domus Israël clementes sint : ponamus itaque saccos in lumbis nostris, et funiculos in capitibus nostris, et egrediamur ad regem Israël : forsitan salvabit animas nostras.

** I Kings 20:32

Accinxerunt saccis lumbos suos, et posuerunt funiculos in capitibus suis, veneruntque ad regem Israël, et dixerunt ei : Servus tuus Benadad dicit : Vivat, oro te, anima mea. Et ille ait : Si adhuc vivit, frater meus est.

** I Kings 20:33

Quod acceperunt viri pro omine : et festinantes rapuerunt verbum ex ore ejus, atque dixerunt : Frater tuus Benadad. Et dixit eis : Ite, et adducite eum ad me. Egressus est ergo ad eum Benadad, et levavit eum in currum suum.

** I Kings 20:34

Qui dixit ei : Civitates quas tulit pater meus a patre tuo, reddam : et plateas fac tibi in Damasco, sicut fecit pater meus in Samaria, et ego fœderatus recedam a te. Pepigit ergo fœdus, et dimisit eum.  

** I Kings 20:35

Tunc vir quidam de filiis prophetarum dixit ad socium suum in sermone Domini : Percute me. At ille noluit percutere.

** I Kings 20:36

Cui ait : Quia noluisti audire vocem Domini, ecce recedes a me, et percutiet te leo. Cumque paululum recessisset ab eo, invenit eum leo, atque percussit.

** I Kings 20:37

Sed et alterum inveniens virum, dixit ad eum : Percute me. Qui percussit eum, et vulneravit.

** I Kings 20:38

Abiit ergo propheta, et occurrit regi in via, et mutavit aspersione pulveris os et oculos suos.

** I Kings 20:39

Cumque rex transisset, clamavit ad regem, et ait : Servus tuus egressus est ad præliandum cominus : cumque fugisset vir unus, adduxit eum quidam ad me, et ait : Custodi virum istum : qui si lapsus fuerit, erit anima tua pro anima ejus, aut talentum argenti appendes.

** I Kings 20:40

Dum autem ego turbatus huc illucque me verterem, subito non comparuit. Et ait rex Israël ad eum : Hoc est judicium tuum, quod ipse decrevisti.

** I Kings 20:41

At ille statim abstersit pulverem de facie sua, et cognovit eum rex Israël, quod esset de prophetis.

** I Kings 20:42

Qui ait ad eum : Hæc dicit Dominus : Quia dimisisti virum dignum morte de manu tua, erit anima tua pro anima ejus, et populus tuus pro populo ejus.

** I Kings 20:43

Reversus est igitur rex Israël in domum suam, audire contemnens, et furibundus venit in Samariam.   

* I Kings 21

** I Kings 21:1

Post verba autem hæc, tempore illo vinea erat Naboth Jezrahelitæ, quæ erat in Jezrahel, juxta palatium Achab regis Samariæ.

** I Kings 21:2

Locutus est ergo Achab ad Naboth, dicens : Da mihi vineam tuam, ut faciam mihi hortum olerum, quia vicina est, et prope domum meam : daboque tibi pro ea vineam meliorem, aut si commodius tibi putas, argenti pretium, quanto digna est.

** I Kings 21:3

Cui respondit Naboth : Propitius sit mihi Dominus, ne dem hæreditatem patrum meorum tibi.

** I Kings 21:4

Venit ergo Achab in domum suam indignans, et frendens super verbo quod locutus fuerat ad eum Naboth Jezrahelites, dicens : Non dabo tibi hæreditatem patrum meorum. Et projiciens se in lectulum suum, avertit faciem suam ad parietem, et non comedit panem.

** I Kings 21:5

Ingressa est autem ad eum Jezabel uxor sua, dixitque ei : Quid est hoc, unde anima tua contristata est ? et quare non comedis panem ?

** I Kings 21:6

Qui respondit ei : Locutus sum Naboth Jezrahelitæ, et dixi ei : Da mihi vineam tuam, accepta pecunia : aut, si tibi placet, dabo tibi vineam meliorem pro ea. Et ille ait : Non dabo tibi vineam meam.

** I Kings 21:7

Dixit ergo ad eum Jezabel uxor ejus : Grandis auctoritatis es, et bene regis regnum Israël. Surge, et comede panem, et æquo animo esto : ego dabo tibi vineam Naboth Jezrahelitæ.  

** I Kings 21:8

Scripsit itaque litteras ex nomine Achab, et signavit eas annulo ejus, et misit ad majores natu, et optimates, qui erant in civitate ejus, et habitabant cum Naboth.

** I Kings 21:9

Litterarum autem hæc erat sententia : Prædicate jejunium, et sedere facite Naboth inter primos populi :

** I Kings 21:10

et submittite duos viros filios Belial contra eum, et falsum testimonium dicant : Benedixit Deum et regem : et educite eum, et lapidate, sicque moriatur.

** I Kings 21:11

Fecerunt ergo cives ejus majores natu et optimates, qui habitabant cum eo in urbe, sicut præceperat eis Jezabel, et sicut scriptum erat in litteris quas miserat ad eos :

** I Kings 21:12

prædicaverunt jejunium, et sedere fecerunt Naboth inter primos populi.

** I Kings 21:13

Et adductis duobus viris filiis diaboli, fecerunt eos sedere contra eum : at illi, scilicet ut viri diabolici, dixerunt contra eum testimonium coram multitudine : Benedixit Naboth Deum et regem : quam ob rem eduxerunt eum extra civitatem, et lapidibus interfecerunt.

** I Kings 21:14

Miseruntque ad Jezabel, dicentes : Lapidatus est Naboth, et mortuus est.

** I Kings 21:15

Factum est autem, cum audisset Jezabel lapidatum Naboth et mortuum, locuta est ad Achab : Surge, et posside vineam Naboth Jezrahelitæ, qui noluit tibi acquiescere, et dare eam accepta pecunia : non enim vivit Naboth, sed mortuus est.

** I Kings 21:16

Quod cum audisset Achab, mortuum videlicet Naboth, surrexit, et descendebat in vineam Naboth Jezrahelitæ, ut possideret eam.  

** I Kings 21:17

Factus est igitur sermo Domini ad Eliam Thesbiten, dicens :

** I Kings 21:18

Surge, et descende in occursum Achab regis Israël, qui est in Samaria : ecce ad vineam Naboth descendit, ut possideat eam.

** I Kings 21:19

Et loqueris ad eum, dicens : Hæc dicit Dominus : Occidisti, insuper et possedisti. Et post hæc addes : Hæc dicit Dominus : In loco hoc, in quo linxerunt canes sanguinem Naboth, lambent quoque sanguinem tuum.

** I Kings 21:20

Et ait Achab ad Eliam : Num invenisti me inimicum tibi ? Qui dixit : Inveni, eo quod venundatus sis, ut faceres malum in conspectu Domini.

** I Kings 21:21

Ecce ego inducam super te malum, et demetam posteriora tua, et interficiam de Achab mingentem ad parietem, et clausum et ultimum in Israël.

** I Kings 21:22

Et dabo domum tuam sicut domum Jeroboam filii Nabat, et sicut domum Baasa filii Ahia : quia egisti ut me ad iracundiam provocares, et peccare fecisti Israël.

** I Kings 21:23

Sed et de Jezabel locutus est Dominus, dicens : Canes comedent Jezabel in agro Jezrahel.

** I Kings 21:24

Si mortuus fuerit Achab in civitate, comedent eum canes : si autem mortuus fuerit in agro, comedent eum volucres cæli.

** I Kings 21:25

Igitur non fuit alter talis sicut Achab, qui venundatus est ut faceret malum in conspectu Domini : concitavit enim eum Jezabel uxor sua,

** I Kings 21:26

et abominabilis factus est, in tantum ut sequeretur idola quæ fecerant Amorrhæi, quos consumpsit Dominus a facie filiorum Israël.

** I Kings 21:27

Itaque cum audisset Achab sermones istos, scidit vestimenta sua, et operuit cilicio carnem suam, jejunavitque et dormivit in sacco, et ambulavit demisso capite.

** I Kings 21:28

Et factus est sermo Domini ad Eliam Thesbiten, dicens :

** I Kings 21:29

Nonne vidisti humiliatum Achab coram me ? quia igitur humiliatus est mei causa, non inducam malum in diebus ejus, sed in diebus filii sui inferam malum domui ejus.   

* I Kings 22

** I Kings 22:1

Transierunt igitur tres anni absque bello inter Syriam et Israël.

** I Kings 22:2

In anno autem tertio, descendit Josaphat rex Juda ad regem Israël.

** I Kings 22:3

(Dixitque rex Israël ad servos suos : Ignoratis quod nostra sit Ramoth Galaad, et negligimus tollere eam de manu regis Syriæ ?)

** I Kings 22:4

Et ait ad Josaphat : Veniesne mecum ad præliandum in Ramoth Galaad ?

** I Kings 22:5

Dixitque Josaphat ad regem Israël : Sicut ego sum, ita et tu : populus meus et populus tuus unum sunt : et equites mei, equites tui. Dixitque Josaphat ad regem Israël : Quære, oro te, hodie sermonem Domini.

** I Kings 22:6

Congregavit ergo rex Israël prophetas, quadringentos circiter viros, et ait ad eos : Ire debeo in Ramoth Galaad ad bellandum, an quiescere ? Qui responderunt : Ascende, et dabit eam Dominus in manu regis.

** I Kings 22:7

Dixit autem Josaphat : Non est hic propheta Domini quispiam, ut interrogemus per eum ?

** I Kings 22:8

Et ait rex Israël ad Josaphat : Remansit vir unus per quem possumus interrogare Dominum : sed ego odi eum, quia non prophetat mihi bonum, sed malum : Michæas filius Jemla. Cui Josaphat ait : Ne loquaris ita, rex.

** I Kings 22:9

Vocavit ergo rex Israël eunuchum quemdam, et dixit ei : Festina adducere Michæam filium Jemla.  

** I Kings 22:10

Rex autem Israël, et Josaphat rex Juda, sedebant unusquisque in solio suo, vestiti cultu regio, in area juxta ostium portæ Samariæ : et universi prophetæ prophetabant in conspectu eorum.

** I Kings 22:11

Fecit quoque sibi Sedecias filius Chanaana cornua ferrea, et ait : Hæc dicit Dominus : His ventilabis Syriam, donec deleas eam.

** I Kings 22:12

Omnesque prophetæ similiter prophetabant, dicentes : Ascende in Ramoth Galaad, et vade prospere, et tradet Dominus in manus regis.

** I Kings 22:13

Nuntius vero qui ierat ut vocaret Michæam, locutus est ad eum, dicens : Ecce sermones prophetarum ore uno regi bona prædicant : sit ergo sermo tuus similis eorum, et loquere bona.

** I Kings 22:14

Cui Michæas ait : Vivit Dominus, quia quodcumque dixerit mihi Dominus, hoc loquar.

** I Kings 22:15

Venit itaque ad regem, et ait illi rex : Michæa, ire debemus in Ramoth Galaad ad præliandum, an cessare ? Cui ille respondit : Ascende, et vade prospere, et tradet eam Dominus in manus regis.

** I Kings 22:16

Dixit autem rex ad eum : Iterum atque iterum adjuro te, ut non loquaris mihi nisi quod verum est, in nomine Domini.

** I Kings 22:17

Et ille ait : Vidi cunctum Israël dispersum in montibus, quasi oves non habentes pastorem. Et ait Dominus : Non habent isti dominum : revertatur unusquisque in domum suam in pace.

** I Kings 22:18

(Dixit ergo rex Israël ad Josaphat : Numquid non dixi tibi, quia non prophetat mihi bonum, sed semper malum ?)

** I Kings 22:19

Ille vero addens, ait : Propterea audi sermonem Domini : vidi Dominum sedentem super solium suum, et omnem exercitum cæli assistentem ei a dextris et a sinistris :

** I Kings 22:20

et ait Dominus : Quis decipiet Achab regem Israël, ut ascendat, et cadat in Ramoth Galaad ? Et dixit unus verba hujuscemodi, et alius aliter.

** I Kings 22:21

Egressus est autem spiritus, et stetit coram Domino, et ait : Ego decipiam illum. Cui locutus est Dominus : In quo ?

** I Kings 22:22

Et ille ait : Egrediar, et ero spiritus mendax in ore omnium prophetarum ejus. Et dixit Dominus : Decipies, et prævalebis : egredere, et fac ita.

** I Kings 22:23

Nunc igitur ecce dedit Dominus spiritum mendacii in ore omnium prophetarum tuorum, qui hic sunt, et Dominus locutus est contra te malum.

** I Kings 22:24

Accessit autem Sedecias filius Chanaana, et percussit Michæam in maxillam, et dixit : Mene ergo dimisit spiritus Domini, et locutus est tibi ?

** I Kings 22:25

Et ait Michæas : Visurus es in die illa quando ingredieris cubiculum intra cubiculum ut abscondaris.

** I Kings 22:26

Et ait rex Israël : Tollite Michæam, et maneat apud Amon principem civitatis, et apud Joas filium Amelech,

** I Kings 22:27

et dicite eis : Hæc dicit rex : Mittite virum istum in carcerem, et sustentate eum pane tribulationis, et aqua angustiæ, donec revertar in pace.

** I Kings 22:28

Dixitque Michæas : Si reversus fueris in pace, non est locutus in me Dominus. Et ait : Audite, populi omnes.

** I Kings 22:29

Ascendit itaque rex Israël, et Josaphat rex Juda, in Ramoth Galaad.

** I Kings 22:30

Dixit itaque rex Israël ad Josaphat : Sume arma, et ingredere prælium, et induere vestibus tuis. Porro rex Israël mutavit habitum suum, et ingressus est bellum.

** I Kings 22:31

Rex autem Syriæ præceperat principibus curruum triginta duobus, dicens : Non pugnabitis contra minorem et majorem quempiam, nisi contra regem Israël solum.

** I Kings 22:32

Cum ergo vidissent principes curruum Josaphat, suspicati sunt quod ipse esset rex Israël, et impetu facto pugnabant contra eum : et exclamavit Josaphat.

** I Kings 22:33

Intellexeruntque principes curruum quod non esset rex Israël, et cessaverunt ab eo.

** I Kings 22:34

Vir autem quidam tetendit arcum, in incertum sagittam dirigens, et casu percussit regem Israël inter pulmonem et stomachum. At ille dixit aurigæ suo : Verte manum tuam, et ejice me de exercitu, quia graviter vulneratus sum.

** I Kings 22:35

Commissum est ergo prælium in die illa, et rex Israël stabat in curru suo contra Syros, et mortuus est vespere : fluebat autem sanguis plagæ in sinum currus,

** I Kings 22:36

et præco insonuit in universo exercitu antequam sol occumberet, dicens : Unusquisque revertatur in civitatem, et in terram suam.

** I Kings 22:37

Mortuus est autem rex, et perlatus est in Samariam : sepelieruntque regem in Samaria,

** I Kings 22:38

et laverunt currum ejus in piscina Samariæ : et linxerunt canes sanguinem ejus, et habenas laverunt, juxta verbum Domini quod locutus fuerat.

** I Kings 22:39

Reliqua autem sermonum Achab, et universa quæ fecit, et domus eburnea quam ædificavit, cunctarumque urbium quas exstruxit, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** I Kings 22:40

Dormivit ergo Achab cum patribus suis, et regnavit Ochozias filius ejus pro eo.  

** I Kings 22:41

Josaphat vero filius Asa regnare cœperat super Judam anno quarto Achab regis Israël.

** I Kings 22:42

Triginta quinque annorum erat cum regnare cœpisset, et viginti quinque annis regnavit in Jerusalem : nomen matris ejus Azuba filia Salai.

** I Kings 22:43

Et ambulavit in omni via Asa patris sui, et non declinavit ex ea : fecitque quod rectum erat in conspectu Domini.

** I Kings 22:44

Verumtamen excelsa non abstulit : adhuc enim populus sacrificabat, et adolebat incensum in excelsis.

** I Kings 22:45

Pacemque habuit Josaphat cum rege Israël.

** I Kings 22:46

Reliqua autem verborum Josaphat, et opera ejus quæ gessit, et prælia, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** I Kings 22:47

Sed et reliquias effeminatorum qui remanserant in diebus Asa patris ejus, abstulit de terra.

** I Kings 22:48

Nec erat tunc rex constitutus in Edom.

** I Kings 22:49

Rex vero Josaphat fecerat classes in mari, quæ navigarent in Ophir propter aurum : et ire non potuerunt, quia confractæ sunt in Asiongaber.

** I Kings 22:50

Tunc ait Ochozias filius Achab ad Josaphat : Vadant servi mei cum servis tuis in navibus. Et noluit Josaphat.

** I Kings 22:51

Dormivitque Josaphat cum patribus suis, et sepultus est cum eis in civitate David patris sui : regnavitque Joram filius ejus pro eo.  

** I Kings 22:52

Ochozias autem filius Achab regnare cœperat super Israël in Samaria, anno septimodecimo Josaphat regis Juda : regnavitque super Israël duobus annis.

** I Kings 22:53

Et fecit malum in conspectu Domini, et ambulavit in via patris sui et matris suæ, et in via Jeroboam filii Nabat, qui peccare fecit Israël.

** I Kings 22:54

Servivit quoque Baal, et adoravit eum, et irritavit Dominum Deum Israël, juxta omnia quæ fecerat pater ejus.    

