* I Peter 1

** I Peter 1:1

Petrus Apostolus Jesu Christi, electis advenis dispersionis Ponti, Galatiæ, Cappadociæ, Asiæ, et Bithyniæ,

** I Peter 1:2

secundum præscientiam Dei Patris, in sanctificationem Spiritus, in obedientiam, et aspersionem sanguinis Jesu Christi. Gratia vobis, et pax multiplicetur.  

** I Peter 1:3

Benedictus Deus et Pater Domini nostri Jesu Christi, qui secundum misericordiam suam magnam regeneravit nos in spem vivam, per resurrectionem Jesu Christi ex mortuis,

** I Peter 1:4

in hæreditatem incorruptibilem, et incontaminatam, et immarcescibilem, conservatam in cælis in vobis,

** I Peter 1:5

qui in virtute Dei custodimini per fidem in salutem, paratam revelari in tempore novissimo.

** I Peter 1:6

In quo exsultabis, modicum nunc si oportet contristari in variis tentationibus :

** I Peter 1:7

ut probatio vestræ fidei multo pretiosior auro (quod per ignem probatur) inveniatur in laudem, et gloriam, et honorem in revelatione Jesu Christi :

** I Peter 1:8

quem cum non videritis, diligitis : in quem nunc quoque non videntes creditis : credentes autem exsultabitis lætitia inenarrabili, et glorificata :

** I Peter 1:9

reportantes finem fidei vestræ, salutem animarum.

** I Peter 1:10

De qua salute exquisierunt, atque scrutati sunt prophetæ, qui de futura in vobis gratia prophetaverunt :

** I Peter 1:11

scrutantes in quod vel quale tempus significaret in eis Spiritus Christi : prænuntians eas quæ in Christo sunt passiones, et posteriores glorias :

** I Peter 1:12

quibus revelatum est quia non sibimetipsis, vobis autem ministrabant ea quæ nunc nuntiata sunt vobis per eos qui evangelizaverunt vobis, Spiritu Sancto misso de cælo, in quem desiderant angeli prospicere.  

** I Peter 1:13

Propter quod succincti lumbos mentis vestræ, sobrii, perfecte sperate in eam, quæ offertur vobis, gratiam, in revelationem Jesu Christi :

** I Peter 1:14

quasi filii obedientiæ, non configurati prioribus ignorantiæ vestræ desideriis :

** I Peter 1:15

sed secundum eum qui vocavit vos, Sanctum : et ipsi in omni conversatione sancti sitis :

** I Peter 1:16

quoniam scriptum est : Sancti eritis, quoniam ego sanctus sum.

** I Peter 1:17

Et si patrem invocatis eum, qui sine acceptione personarum judicat secundum uniuscujusque opus, in timore incolatus vestri tempore conversamini.

** I Peter 1:18

Scientes quod non corruptibilibus, auro vel argento, redempti estis de vana vestra conversatione paternæ traditionis :

** I Peter 1:19

sed pretioso sanguine quasi agni immaculati Christi, et incontaminati :

** I Peter 1:20

præcogniti quidem ante mundi constitutionem, manifestati autem novissimis temporibus propter vos,

** I Peter 1:21

qui per ipsum fideles estis in Deo, qui suscitavit eum a mortuis, et dedit ei gloriam, ut fides vestra et spes esset in Deo :

** I Peter 1:22

animas vestras castificantes in obedientia caritatis, in fraternitatis amore, simplici ex corde invicem diligite attentius :

** I Peter 1:23

renati non ex semine corruptibili, sed incorruptibili per verbum Dei vivi, et permanentis in æternum :

** I Peter 1:24

quia omnis caro ut fœnum : et omnis gloria ejus tamquam flos fœni : exaruit fœnum, et flos ejus decidit.

** I Peter 1:25

Verbum autem Domini manet in æternum : hoc est autem verbum, quod evangelizatum est in vos.   

* I Peter 2

** I Peter 2:1

Deponentes igitur omnem malitiam, et omnem dolum, et simulationes, et invidias, et omnes detractiones,

** I Peter 2:2

sicut modo geniti infantes, rationabile, sine dolo lac concupiscite : ut in eo crescatis in salutem :

** I Peter 2:3

si tamen gustastis quoniam dulcis est Dominus.

** I Peter 2:4

Ad quem accedentes lapidem vivum, ab hominibus quidem reprobatum, a Deo autem electum, et honorificatum :

** I Peter 2:5

et ipsi tamquam lapides vivi superædificamini, domus spiritualis, sacerdotium sanctum, offerre spirituales hostias, acceptabiles Deo per Jesum Christum.

** I Peter 2:6

Propter quod continet Scriptura : Ecce pono in Sion lapidem summum angularem, electum, pretiosum : et qui crediderit in eum, non confundetur.

** I Peter 2:7

Vobis igitur honor credentibus : non credentibus autem lapis, quem reprobaverunt ædificantes : hic factus est in caput anguli,

** I Peter 2:8

et lapis offensionis, et petra scandali, his qui offendunt verbo, nec credunt in quo et positi sunt.

** I Peter 2:9

Vos autem genus electum, regale sacerdotium, gens sancta, populus acquisitionis : ut virtutes annuntietis ejus qui de tenebris vos vocavit in admirabile lumen suum.

** I Peter 2:10

Qui aliquando non populus, nunc autem populus Dei : qui non consecuti misericordiam, nunc autem misericordiam consecuti.  

** I Peter 2:11

Carissimi, obsecro vos tamquam advenas et peregrinos abstinere vos a carnalibus desideriis, quæ militant adversus animam,

** I Peter 2:12

conversationem vestram inter gentes habentes bonam : ut in eo quod detrectant de vobis tamquam de malefactoribus, ex bonis operibus vos considerantes, glorificent Deum in die visitationis.

** I Peter 2:13

Subjecti igitur estote omni humanæ creaturæ propter Deum : sive regi quasi præcellenti :

** I Peter 2:14

sive ducibus tamquam ab eo missis ad vindictam malefactorum, laudem vero bonorum :

** I Peter 2:15

quia sic est voluntas Dei, ut benefacientes obmutescere faciatis imprudentium hominum ignorantiam :

** I Peter 2:16

quasi liberi, et non quasi velamen habentes malitiæ libertatem, sed sicut servi Dei.

** I Peter 2:17

Omnes honorate : fraternitatem diligite : Deum timete : regem honorificate.  

** I Peter 2:18

Servi, subditi estote in omni timore dominis, non tantum bonis et modestis, sed etiam dyscolis.

** I Peter 2:19

Hæc est enim gratia, si propter Dei conscientiam sustinet quis tristitias, patiens injuste.

** I Peter 2:20

Quæ enim est gloria, si peccantes, et colaphizati suffertis ? sed si bene facientes patienter sustinetis, hæc est gratia apud Deum.

** I Peter 2:21

In hoc enim vocati estis : quia et Christus passus est pro nobis, vobis relinquens exemplum ut sequamini vestigia ejus :

** I Peter 2:22

qui peccatum non fecit, nec inventus est dolus in ore ejus :

** I Peter 2:23

qui cum malediceretur, non maledicebat : cum pateretur, non comminabatur : tradebat autem judicanti se injuste :

** I Peter 2:24

qui peccata nostra ipse pertulit in corpore suo super lignum ; ut peccatis mortui, justitiæ vivamus : cujus livore sanati estis.

** I Peter 2:25

Eratis enim sicut oves errantes, sed conversi estis nunc ad pastorem, et episcopum animarum vestrarum.   

* I Peter 3

** I Peter 3:1

Similiter et mulieres subditæ sint viris suis : ut etsi qui non credunt verbo, per mulierem conversationem sine verbo lucrifiant :

** I Peter 3:2

considerantes in timore castam conversationem vestram.

** I Peter 3:3

Quarum non sit extrinsecus capillatura, aut circumdatio auri, aut indumenti vestimentorum cultus :

** I Peter 3:4

sed qui absconditus est cordis homo, in incorruptibilitate quieti, et modesti spiritus, qui est in conspectu Dei locuples.

** I Peter 3:5

Sic enim aliquando et sanctæ mulieres, sperantes in Deo, ornabant se, subjectæ propriis viris.

** I Peter 3:6

Sicut Sara obediebat Abrahæ, dominum eum vocans : cujus estis filiæ benefacientes, et non pertimentes ullam perturbationem.

** I Peter 3:7

Viri similiter cohabitantes secundum scientiam, quasi infirmiori vasculo muliebri impartientes honorem, tamquam et cohæredibus gratiæ vitæ : ut non impediantur orationes vestræ.  

** I Peter 3:8

In fine autem omnes unanimes, compatientes fraternitatis amatores, misericordes, modesti, humiles :

** I Peter 3:9

non reddentes malum pro malo, nec maledictum pro maledicto, sed e contrario benedicentes : quia in hoc vocati estis, ut benedictionem hæreditate possideatis.

** I Peter 3:10

Qui enim vult vitam diligere, et dies videre bonos, coërceat linguam suam a malo, et labia ejus ne loquantur dolum.

** I Peter 3:11

Declinet a malo, et faciat bonum : inquirat pacem, et sequatur eam :

** I Peter 3:12

quia oculi Domini super justos, et aures ejus in preces eorum : vultus autem Domini super facientes mala.

** I Peter 3:13

Et quis est qui vobis noceat, si boni æmulatores fueritis ?

** I Peter 3:14

Sed et si quid patimini propter justitiam, beati. Timorem autem eorum ne timueritis, et non conturbemini.

** I Peter 3:15

Dominum autem Christum sanctificate in cordibus vestris, parati semper ad satisfactionem omni poscenti vos rationem de ea, quæ in vobis est, spe.

** I Peter 3:16

Sed cum modestia, et timore, conscientiam habentes bonam : ut in eo, quod detrahunt vobis, confundantur, qui calumniantur vestram bonam in Christo conversationem.

** I Peter 3:17

Melius est enim benefacientes (si voluntas Dei velit) pati, quam malefacientes.  

** I Peter 3:18

Quia et Christus semel pro peccatis nostris mortuus est, justus pro injustis, ut nos offerret Deo, mortificatus quidem carne, vivificatus autem spiritu.

** I Peter 3:19

In quo et his, qui in carcere erant, spiritibus veniens prædicavit :

** I Peter 3:20

qui increduli fuerant aliquando, quando exspectabant Dei patientiam in diebus Noë, cum fabricaretur arca : in qua pauci, id est octo animæ, salvæ factæ sunt per aquam.

** I Peter 3:21

Quod et vos nunc similis formæ salvos fecit baptisma : non carnis depositio sordium, sed conscientiæ bonæ interrogatio in Deum per resurrectionem Jesu Christi.

** I Peter 3:22

Qui est in dextera Dei, deglutiens mortem ut vitæ æternæ hæredes efficeremur : profectus in cælum subjectis sibi angelis, et potestatibus, et virtutibus.   

* I Peter 4

** I Peter 4:1

Christo igitur passo in carne, et vos eadem cogitatione armamini : quia qui passus est in carne, desiit a peccatis :

** I Peter 4:2

ut jam non desideriis hominum, sed voluntati Dei, quod reliquum est in carne vivat temporis.

** I Peter 4:3

Sufficit enim præteritum tempus ad voluntatem gentium consummandam his qui ambulaverunt in luxuriis, desideriis, vinolentiis, comessationibus, potationibus, et illicitis idolorum cultibus.

** I Peter 4:4

In quo admirantur non concurrentibus vobis in eamdem luxuriæ confusionem, blasphemantes.

** I Peter 4:5

Qui reddent rationem ei qui paratus est judicare vivos et mortuos.

** I Peter 4:6

Propter hoc enim et mortuis evangelizatum est : ut judicentur quidem secundum homines in carne, vivant autem secundum Deum in spiritu.  

** I Peter 4:7

Omnium autem finis appropinquavit. Estote itaque prudentes, et vigilate in orationibus.

** I Peter 4:8

Ante omnia autem, mutuam in vobismetipsis caritatem continuam habentes : quia caritas operit multitudinem peccatorum.

** I Peter 4:9

Hospitales invicem sine murmuratione.

** I Peter 4:10

Unusquisque, sicut accepit gratiam, in alterutrum illam administrantes, sicut boni dispensatores multiformis gratiæ Dei.

** I Peter 4:11

Si quis loquitur, quasi sermones Dei : si quis ministrat, tamquam ex virtute, quam administrat Deus : ut in omnibus honorificetur Deus per Jesum Christum : cui est gloria et imperium in sæcula sæculorum. Amen.  

** I Peter 4:12

Carissimi, nolite peregrinari in fervore, qui ad tentationem vobis fit, quasi novi aliquid vobis contingat :

** I Peter 4:13

sed communicantes Christi passionibus gaudete, ut et in revelatione gloriæ ejus gaudeatis exsultantes.

** I Peter 4:14

Si exprobramini in nomine Christi, beati eritis : quoniam quod est honoris, gloriæ, et virtutis Dei, et qui est ejus Spiritus, super vos requiescit.

** I Peter 4:15

Nemo autem vestrum patiatur ut homicida, aut fur, aut maledicus, aut alienorum appetitor.

** I Peter 4:16

Si autem ut christianus, non erubescat : glorificet autem Deum in isto nomine :

** I Peter 4:17

quoniam tempus est ut incipiat judicium a domo Dei. Si autem primum a nobis, quis finis eorum, qui non credunt Dei Evangelio ?

** I Peter 4:18

et si justus vix salvabitur, impius et peccator ubi parebunt ?

** I Peter 4:19

Itaque et hi, qui patiuntur secundum voluntatem Dei, fideli Creatori commendent animas suas in benefactis.   

* I Peter 5

** I Peter 5:1

Seniores ergo, qui in vobis sunt, obsecro, consenior et testis Christi passionum : qui et ejus, quæ in futuro revelanda est, gloriæ communicator :

** I Peter 5:2

pascite qui in vobis est gregem Dei, providentes non coacte, sed spontanee secundum Deum : neque turpis lucri gratia, sed voluntarie :

** I Peter 5:3

neque ut dominantes in cleris, sed forma facti gregis ex animo.

** I Peter 5:4

Et cum apparuerit princeps pastorum, percipietis immarcescibilem gloriæ coronam.

** I Peter 5:5

Similiter adolescentes subditi estote senioribus.   Omnes autem invicem humilitatem insinuate, quia Deus superbis resistit, humilibus autem dat gratiam.

** I Peter 5:6

Humiliamini igitur sub potenti manu Dei, ut vos exaltet in tempore visitationis :

** I Peter 5:7

omnem sollicitudinem vestram projicientes in eum, quoniam ipsi cura est de vobis.

** I Peter 5:8

Sobrii estote, et vigilate : quia adversarius vester diabolus tamquam leo rugiens circuit, quærens quem devoret :

** I Peter 5:9

cui resistite fortes in fide : scientes eamdem passionem ei quæ in mundo est vestræ fraternitati fieri.

** I Peter 5:10

Deus autem omnis gratiæ, qui vocavit nos in æternam suam gloriam in Christo Jesu, modicum passos ipse perficiet, confirmabit, solidabitque.

** I Peter 5:11

Ipsi gloria, et imperium in sæcula sæculorum. Amen.  

** I Peter 5:12

Per Silvanum fidelem fratrem vobis, ut arbitror, breviter scripsi : obsecrans et contestans, hanc esse veram gratiam Dei, in qua statis.

** I Peter 5:13

Salutat vos ecclesia quæ est in Babylone coëlecta, et Marcus filius meus.

** I Peter 5:14

Salutate invicem in osculo sancto. Gratia vobis omnibus qui estis in Christo Jesu. Amen.    

