* I Thessalonians 1

** I Thessalonians 1:1

Paulus, et Silvanus, et Timotheus ecclesiæ Thessalonicensium in Deo Patre, et Domino Jesu Christo.

** I Thessalonians 1:2

Gratia vobis, et pax.   Gratias agimus Deo semper pro omnibus vobis, memoriam vestri facientes in orationibus nostris sine intermissione,

** I Thessalonians 1:3

memores operis fidei vestræ, et laboris, et caritatis, et sustinentiæ spei Domini nostri Jesu Christi, ante Deum et Patrem nostrum :

** I Thessalonians 1:4

scientes, fratres dilecti a Deo, electionem vestram :

** I Thessalonians 1:5

quia Evangelium nostrum non fuit ad vos in sermone tantum, sed et in virtute, et in Spiritu Sancto, et in plenitudine multa, sicut scitis quales fuerimus in vobis propter vos.

** I Thessalonians 1:6

Et vos imitatores nostri facti estis, et Domini, excipientes verbum in tribulatione multa, cum gaudio Spiritus Sancti :

** I Thessalonians 1:7

ita ut facti sitis forma omnibus credentibus in Macedonia, et in Achaia.

** I Thessalonians 1:8

A vobis enim diffamatus est sermo Domini, non solum in Macedonia, et in Achaia, sed et in omni loco fides vestra, quæ est ad Deum, profecta est ita ut non sit nobis necesse quidquam loqui.

** I Thessalonians 1:9

Ipsi enim de nobis annuntiant qualem introitum habuerimus ad vos : et quomodo conversi estis ad Deum a simulacris, servire Deo vivo, et vero,

** I Thessalonians 1:10

et exspectare Filium ejus de cælis (quem suscitavit a mortuis) Jesum, qui eripuit nos ab ira ventura.   

* I Thessalonians 2

** I Thessalonians 2:1

Nam ipsi scitis, fratres, introitum nostrum ad vos, quia non inanis fuit :

** I Thessalonians 2:2

sed ante passi, et contumeliis affecti (sicut scitis) in Philippis, fiduciam habuimus in Deo nostro, loqui ad vos Evangelium Dei in multa sollicitudine.

** I Thessalonians 2:3

Exhortatio enim nostra non de errore, neque de immunditia, neque in dolo,

** I Thessalonians 2:4

sed sicut probati sumus a Deo ut crederetur nobis Evangelium : ita loquimur non quasi hominibus placentes, sed Deo, qui probat corda nostra.

** I Thessalonians 2:5

Neque enim aliquando fuimus in sermone adulationis, sicut scitis : neque in occasione avaritiæ : Deus testis est :

** I Thessalonians 2:6

nec quærentes ab hominibus gloriam, neque a vobis, neque ab aliis.

** I Thessalonians 2:7

Cum possemus vobis oneri esse ut Christi apostoli : sed facti sumus parvuli in medio vestrum, tamquam si nutrix foveat filios suos.

** I Thessalonians 2:8

Ita desiderantes vos, cupide volebamus tradere vobis non solum Evangelium Dei, sed etiam animas nostras : quoniam carissimi nobis facti estis.

** I Thessalonians 2:9

Memores enim estis, fratres, laboris nostri, et fatigationis : nocte ac die operantes, ne quem vestrum gravaremus, prædicavimus in vobis Evangelium Dei.

** I Thessalonians 2:10

Vos testes estis, et Deus, quam sancte, et juste, et sine querela, vobis, qui credidistis, fuimus :

** I Thessalonians 2:11

sicut scitis, qualiter unumquemque vestrum (sicut pater filios suos)

** I Thessalonians 2:12

deprecantes vos, et consolantes, testificati sumus, ut ambularetis digne Deo, qui vocavit vos in suum regnum et gloriam.  

** I Thessalonians 2:13

Ideo et nos gratias agimus Deo sine intermissione : quoniam cum accepissetis a nobis verbum auditus Dei, accepistis illud, non ut verbum hominum, sed (sicut est vere) verbum Dei, qui operatur in vobis, qui credidistis :

** I Thessalonians 2:14

vos enim imitatores facti estis, fratres, ecclesiarum Dei, quæ sunt in Judæa in Christo Jesu : quia eadem passi estis et vos a contribulibus vestris, sicut et ipsi a Judæis :

** I Thessalonians 2:15

qui et Dominum occiderunt Jesum, et prophetas, et nos persecuti sunt, et Deo non placent, et omnibus hominibus adversantur,

** I Thessalonians 2:16

prohibentes nos gentibus loqui ut salvæ fiant, ut impleant peccata sua semper : pervenit enim ira Dei super illos usque in finem.

** I Thessalonians 2:17

Nos autem fratres desolati a vobis ad tempus horæ, aspectu, non corde, abundantius festinavimus faciem vestram videre cum multo desiderio :

** I Thessalonians 2:18

quoniam voluimus venire ad vos, ego quidem Paulus, et semel, et iterum : sed impedivit nos Satanas.

** I Thessalonians 2:19

Quæ est enim nostra spes aut gaudium, aut corona gloriæ ? nonne vos ante Dominum nostrum Jesum Christum estis in adventu ejus ?

** I Thessalonians 2:20

vos enim estis gloria nostra et gaudium.   

* I Thessalonians 3

** I Thessalonians 3:1

Propter quod non sustinentes amplius, placuit nobis remanere Athenis, solis :

** I Thessalonians 3:2

et misimus Timotheum fratrem nostrum, et ministrum Dei in Evangelio Christi, ad confirmandos vos, et exhortandos pro fide vestra :

** I Thessalonians 3:3

ut nemo moveatur in tribulationibus istis : ipsi enim scitis quod in hoc positi sumus.

** I Thessalonians 3:4

Nam et cum apud vos essemus, prædicebamus vobis passuros nos tribulationes, sicut et factum est, et scitis.

** I Thessalonians 3:5

Propterea et ego amplius non sustinens, misi ad cognoscendam fidem vestram : ne forte tentaverit vos is qui tentat, et inanis fiat labor noster.

** I Thessalonians 3:6

Nunc autem veniente Timotheo ad nos a vobis, et annuntiante nobis fidem et caritatem vestram, et quia memoriam nostri habetis bonam semper, desiderantes nos videre, sicut et nos quoque vos :

** I Thessalonians 3:7

ideo consolati sumus, fratres, in vobis in omni necessitate et tribulatione nostra, per fidem vestram,

** I Thessalonians 3:8

quoniam nunc vivimus, si vos statis in Domino.

** I Thessalonians 3:9

Quam enim gratiarum actionem possumus Deo retribuere pro vobis in omni gaudio, quo gaudemus propter vos ante Deum nostrum,

** I Thessalonians 3:10

nocte ac die abundantius orantes, ut videamus faciem vestram, et compleamus ea quæ desunt fidei vestræ ?

** I Thessalonians 3:11

Ipse autem Deus, et Pater noster, et Dominus noster Jesus Christus, dirigat viam nostram ad vos.

** I Thessalonians 3:12

Vos autem Dominus multiplicet, et abundare faciat caritatem vestram in invicem, et in omnes, quemadmodum et nos in vobis :

** I Thessalonians 3:13

ad confirmanda corda vestra sine querela in sanctitate, ante Deum et Patrem nostrum, in adventu Domini nostri Jesu Christi cum omnibus sanctis ejus. Amen.   

* I Thessalonians 4

** I Thessalonians 4:1

De cetero ergo, fratres, rogamus vos et obsecramus in Domino Jesu, ut quemadmodum accepistis a nobis quomodo oporteat vos ambulare, et placere Deo, sic et ambuletis ut abundetis magis.

** I Thessalonians 4:2

Scitis enim quæ præcepta dederim vobis per Dominum Jesum.

** I Thessalonians 4:3

Hæc est enim voluntas Dei, sanctificatio vestra : ut abstineatis vos a fornicatione,

** I Thessalonians 4:4

ut sciat unusquisque vestrum vas suum possidere in sanctificatione, et honore :

** I Thessalonians 4:5

non in passione desiderii, sicut et gentes, quæ ignorant Deum :

** I Thessalonians 4:6

et ne quis supergrediatur, neque circumveniat in negotio fratrem suum : quoniam vindex est Dominus de his omnibus, sicut prædiximus vobis, et testificati sumus.

** I Thessalonians 4:7

Non enim vocavit nos Deus in immunditiam, sed in sanctificationem.

** I Thessalonians 4:8

Itaque qui hæc spernit, non hominem spernit, sed Deum : qui etiam dedit Spiritum suum Sanctum in nobis.

** I Thessalonians 4:9

De caritate autem fraternitatis non necesse habemus scribere vobis : ipsi enim vos a Deo didicistis ut diligatis invicem.

** I Thessalonians 4:10

Etenim illud facitis in omnes fratres in universa Macedonia. Rogamus autem vos, fratres, ut abundetis magis,

** I Thessalonians 4:11

et operam detis ut quieti sitis, et ut vestrum negotium agatis, et operemini manibus vestris, sicut præcepimus vobis :

** I Thessalonians 4:12

et ut honeste ambuletis ad eos qui foris sunt : et nullius aliquid desideretis.

** I Thessalonians 4:13

Nolumus autem vos ignorare fratres de dormientibus, ut non contristemini sicut et ceteri, qui spem non habent.  

** I Thessalonians 4:14

Si enim credimus quod Jesus mortuus est, et resurrexit : ita et Deus eos qui dormierunt per Jesum, adducet cum eo.

** I Thessalonians 4:15

Hoc enim vobis dicimus in verbo Domini, quia nos, qui vivimus, qui residui sumus in adventum Domini, non præveniemus eos qui dormierunt.

** I Thessalonians 4:16

Quoniam ipse Dominus in jussu, et in voce archangeli, et in tuba Dei descendet de cælo : et mortui, qui in Christo sunt, resurgent primi.

** I Thessalonians 4:17

Deinde nos, qui vivimus, qui relinquimur, simul rapiemur cum illis in nubibus obviam Christo in aëra, et sic semper cum Domino erimus.

** I Thessalonians 4:18

Itaque consolamini invicem in verbis istis.   

* I Thessalonians 5

** I Thessalonians 5:1

De temporibus autem, et momentis, fratres, non indigetis ut scribamus vobis.

** I Thessalonians 5:2

Ipsi enim diligenter scitis quia dies Domini, sicut fur in nocte, ita veniet :

** I Thessalonians 5:3

cum enim dixerint : Pax et securitas : tunc repentinus eis superveniet interitus, sicut dolor in utero habenti, et non effugient.

** I Thessalonians 5:4

Vos autem, fratres, non estis in tenebris, ut vos dies illa tamquam fur comprehendat :

** I Thessalonians 5:5

omnes enim vos filii lucis estis, et filii diei : non sumus noctis, neque tenebrarum.

** I Thessalonians 5:6

Igitur non dormiamus sicut et ceteri, sed vigilemus, et sobrii simus.

** I Thessalonians 5:7

Qui enim dormiunt, nocte dormiunt : et qui ebrii sunt, nocte ebrii sunt.

** I Thessalonians 5:8

Nos autem, qui diei sumus, sobrii simus, induti loricam fidei et caritatis, et galeam spem salutis :

** I Thessalonians 5:9

quoniam non posuit nos Deus in iram, sed in acquisitionem salutis per Dominum nostrum Jesum Christum,

** I Thessalonians 5:10

qui mortuus est pro nobis : ut sive vigilemus, sive dormiamus, simul cum illo vivamus.

** I Thessalonians 5:11

Propter quod consolamini invicem, et ædificate alterutrum, sicut et facitis.  

** I Thessalonians 5:12

Rogamus autem vos, fratres, ut noveritis eos qui laborant inter vos, et præsunt vobis in Domino, et monent vos,

** I Thessalonians 5:13

ut habeatis illos abundantius in caritate propter opus illorum : pacem habete cum eis.

** I Thessalonians 5:14

Rogamus autem vos, fratres, corripite inquietos, consolamini pusillanimes, suscipite infirmos, patientes estote ad omnes.

** I Thessalonians 5:15

Videte ne quis malum pro malo alicui reddat : sed semper quod bonum est sectamini in invicem, et in omnes.

** I Thessalonians 5:16

Semper gaudete.

** I Thessalonians 5:17

Sine intermissione orate.

** I Thessalonians 5:18

In omnibus gratias agite : hæc est enim voluntas Dei in Christo Jesu in omnibus vobis.

** I Thessalonians 5:19

Spiritum nolite extinguere.

** I Thessalonians 5:20

Prophetias nolite spernere.

** I Thessalonians 5:21

Omnia autem probate : quod bonum est tenete.

** I Thessalonians 5:22

Ab omni specie mala abstinete vos.

** I Thessalonians 5:23

Ipse autem Deus pacis sanctificet vos per omnia : ut integer spiritus vester, et anima, et corpus sine querela in adventu Domini nostri Jesu Christi servetur.

** I Thessalonians 5:24

Fidelis est, qui vocavit vos : qui etiam faciet.  

** I Thessalonians 5:25

Fratres, orate pro nobis.

** I Thessalonians 5:26

Salutate fratres omnes in osculo sancto.

** I Thessalonians 5:27

Adjuro vos per Dominum ut legatur epistola hæc omnibus sanctis fratribus.

** I Thessalonians 5:28

Gratia Domini nostri Jesu Christi vobiscum. Amen.    

