* II Corinthians 1

** II Corinthians 1:1

Paulus, Apostolus Jesu Christi per voluntatem Dei, et Timotheus frater, ecclesiæ Dei, quæ est Corinthi cum omnibus sanctis, qui sunt in universa Achaia.

** II Corinthians 1:2

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** II Corinthians 1:3

Benedictus Deus et Pater Domini nostri Jesu Christi, Pater misericordiarum, et Deus totius consolationis,

** II Corinthians 1:4

qui consolatur nos in omni tribulatione nostra : ut possimus et ipsi consolari eos qui in omni pressura sunt, per exhortationem, qua exhortamur et ipsi a Deo.

** II Corinthians 1:5

Quoniam sicut abundant passiones Christi in nobis : ita et per Christum abundat consolatio nostra.

** II Corinthians 1:6

Sive autem tribulamur pro vestra exhortatione et salute, sive consolamur pro vestra consolatione, sive exhortamur pro vestra exhortatione et salute, quæ operatur tolerantiam earumdem passionum, quas et nos patimur :

** II Corinthians 1:7

ut spes nostra firma sit pro vobis : scientes quod sicut socii passionum estis, sic eritis et consolationis.

** II Corinthians 1:8

Non enim volumus ignorare vos, fratres, de tribulatione nostra, quæ facta est in Asia, quoniam supra modum gravati sumus supra virtutem, ita ut tæderet nos etiam vivere.

** II Corinthians 1:9

Sed ipsi in nobismetipsis responsum mortis habuimus, ut non simus fidentes in nobis, sed in Deo, qui suscitat mortuos :

** II Corinthians 1:10

qui de tantis periculis nos eripuit, et eruit : in quem speramus quoniam et adhuc eripiet,

** II Corinthians 1:11

adjuvantibus et vobis in oratione pro nobis : ut ex multorum personis, ejus quæ in nobis est donationis, per multos gratiæ agantur pro nobis.  

** II Corinthians 1:12

Nam gloria nostra hæc est : testimonium conscientiæ nostræ, quod in simplicitate cordis et sinceritate Dei, et non in sapientia carnali, sed in gratia Dei, conversati sumus in hoc mundo : abundantius autem ad vos.

** II Corinthians 1:13

Non enim alia scribimus vobis, quam quæ legistis, et cognovistis. Spero autem quod usque in finem cognoscetis,

** II Corinthians 1:14

sicut et cognovistis nos ex parte, quod gloria vestra sumus, sicut et vos nostra, in die Domini nostri Jesu Christi.

** II Corinthians 1:15

Et hac confidentia volui prius venire ad vos, ut secundam gratiam haberetis :

** II Corinthians 1:16

et per vos transire in Macedoniam, et iterum a Macedonia venire ad vos, et a vobis deduci in Judæam.

** II Corinthians 1:17

Cum ergo hoc voluissem, numquid levitate usus sum ? aut quæ cogito, secundum carnem cogito, ut sit apud me Est et Non ?

** II Corinthians 1:18

Fidelis autem Deus, quia sermo noster, qui fuit apud vos, non est in illo Est et Non.

** II Corinthians 1:19

Dei enim Filius Jesus Christus, qui in vobis per nos prædicatus est, per me, et Silvanum, et Timotheum, non fuit Est et Non, sed Est in illo fuit.

** II Corinthians 1:20

Quotquot enim promissiones Dei sunt, in illo Est : ideo et per ipsum Amen Deo ad gloriam nostram.

** II Corinthians 1:21

Qui autem confirmat nos vobiscum in Christo, et qui unxit nos Deus :

** II Corinthians 1:22

qui et signavit nos, et dedit pignus Spiritus in cordibus nostris.  

** II Corinthians 1:23

Ego autem testem Deum invoco in animam meam, quod parcens vobis, non veni ultra Corinthum : non quia dominamur fidei vestæ, sed adjutores sumus gaudii vestri : nam fide statis.   

** II Corinthians 1:24

nil

* II Corinthians 2

** II Corinthians 2:1

Statui autem hoc ipsum apud me, ne iterum in tristitia venirem ad vos.

** II Corinthians 2:2

Si enim ego contristo vos : et quis est, qui me lætificet, nisi qui contristatur ex me ?

** II Corinthians 2:3

Et hoc ipsum scripsi vobis, ut non cum venero, tristitiam super tristitiam habeam, de quibus oportuerat me gaudere : confidens in omnibus vobis, quia meum gaudium, omnium vestrum est.

** II Corinthians 2:4

Nam ex multa tribulatione et angustia cordis scripsi vobis per multas lacrimas : non ut contristemini, sed ut sciatis, quam caritatem habeam abundantius in vobis.  

** II Corinthians 2:5

Si quis autem contristavit, non me contristavit : sed ex parte, ut non onerem omnes vos.

** II Corinthians 2:6

Sufficit illi, qui ejusmodi est, objurgatio hæc, quæ fit a pluribus :

** II Corinthians 2:7

ita ut e contrario magis donetis, et consolemini, ne forte abundantiori tristitia absorbeatur qui ejusmodi est.

** II Corinthians 2:8

Propter quod obsecro vos, ut confirmetis in illum caritatem.

** II Corinthians 2:9

Ideo enim et scripsi, ut cognoscam experimentum vestrum, an in omnibus obedientes sitis.

** II Corinthians 2:10

Cui autem aliquid donastis, et ego : nam et ego quod donavi, si quid donavi, propter vos in persona Christi,

** II Corinthians 2:11

ut non circumveniamur a Satana : non enim ignoramus cogitationes ejus.  

** II Corinthians 2:12

Cum venissem autem Troadem propter Evangelium Christi, et ostium mihi apertum esset in Domino,

** II Corinthians 2:13

non habui requiem spiritui meo, eo quod non invenerim Titum fratrem meum, sed valefaciens eis, profectus sum in Macedoniam.

** II Corinthians 2:14

Deo autem gratias, qui semper triumphat nos in Christo Jesu, et odorem notitiæ suæ manifestat per nos in omni loco :

** II Corinthians 2:15

quia Christi bonus odor sumus Deo in iis qui salvi fiunt, et in iis qui pereunt :

** II Corinthians 2:16

aliis quidem odor mortis in mortem : aliis autem odor vitæ in vitam. Et ad hæc quis tam idoneus ?

** II Corinthians 2:17

non enim sumus sicut plurimi, adulterantes verbum Dei, sed ex sinceritate, sed sicut ex Deo, coram Deo, in Christo loquimur.   

* II Corinthians 3

** II Corinthians 3:1

Incipimus iterum nosmetipsos commendare ? aut numquid egemus (sicut quidam) commendatitiis epistolis ad vos, aut ex vobis ?

** II Corinthians 3:2

Epistola nostra vos estis, scripta in cordibus nostris, quæ scitur, et legitur ab omnibus hominibus :

** II Corinthians 3:3

manifestati quod epistola estis Christi, ministrata a nobis, et scripta non atramento, sed Spiritu Dei vivi : non in tabulis lapideis, sed in tabulis cordis carnalibus.  

** II Corinthians 3:4

Fiduciam autem talem habemus per Christum ad Deum :

** II Corinthians 3:5

non quod sufficientes simus cogitare aliquid a nobis, quasi ex nobis : sed sufficientia nostra ex Deo est :

** II Corinthians 3:6

qui et idoneos nos fecit ministros novi testamenti : non littera, sed Spiritu : littera enim occidit, Spiritus autem vivificat.

** II Corinthians 3:7

Quod si ministratio mortis litteris deformata in lapidibus fuit in gloria, ita ut non possent intendere filii Israël in faciem Moysi propter gloriam vultus ejus, quæ evacuatur :

** II Corinthians 3:8

quomodo non magis ministratio Spiritus erit in gloria ?

** II Corinthians 3:9

Nam si ministratio damnationis gloria est : multo magis abundat ministerium justitiæ in gloria.

** II Corinthians 3:10

Nam nec glorificatum est, quod claruit in hac parte, propter excellentem gloriam.

** II Corinthians 3:11

Si enim quod evacuatur, per gloriam est : multo magis quod manet, in gloria est.  

** II Corinthians 3:12

Habentes igitur talem spem, multa fiducia utimur :

** II Corinthians 3:13

et non sicut Moyses ponebat velamen super faciem suam, ut non intenderent filii Israël in faciem ejus, quod evacuatur,

** II Corinthians 3:14

sed obtusi sunt sensus eorum. Usque in hodiernum enim diem, idipsum velamen in lectione veteris testamenti manet non revelatum (quoniam in Christo evacuatur),

** II Corinthians 3:15

sed usque in hodiernum diem, cum legitur Moyses, velamen positum est super cor eorum.

** II Corinthians 3:16

Cum autem conversus fuerit ad Dominum, auferetur velamen.

** II Corinthians 3:17

Dominus autem Spiritus est : ubi autem Spiritus Domini, ibi libertas.

** II Corinthians 3:18

Nos vero omnes, revelata facie gloriam Domini speculantes, in eamdem imaginem transformamur a claritate in claritatem, tamquam a Domini Spiritu.   

* II Corinthians 4

** II Corinthians 4:1

Ideo habentes administrationem, juxta quod misericordiam consecuti sumus, non deficimus,

** II Corinthians 4:2

sed abdicamus occulta dedecoris, non ambulantes in astutia, neque adulterantes verbum Dei, sed in manifestatione veritatis commendantes nosmetipsos ad omnem conscientiam hominum coram Deo.

** II Corinthians 4:3

Quod si etiam opertum est Evangelium nostrum, in iis, qui pereunt, est opertum :

** II Corinthians 4:4

in quibus Deus hujus sæculi excæcavit mentes infidelium, ut non fulgeat illis illuminatio Evangelii gloriæ Christi, qui est imago Dei.

** II Corinthians 4:5

Non enim nosmetipsos prædicamus, sed Jesum Christum Dominum nostrum : nos autem servos vestros per Jesum :

** II Corinthians 4:6

quoniam Deus, qui dixit de tenebris lucem splendescere, ipse illuxit in cordibus nostris ad illuminationem scientiæ claritatis Dei, in facie Christi Jesu.  

** II Corinthians 4:7

Habemus autem thesaurum istum in vasis fictilibus : ut sublimitas sit virtutis Dei, et non ex nobis.

** II Corinthians 4:8

In omnibus tribulationem patimur, sed non angustiamur : aporiamur, sed non destituimur :

** II Corinthians 4:9

persecutionem patimur, sed non derelinquimur : dejicimur, sed non perimus :

** II Corinthians 4:10

semper mortificationem Jesu in corpore nostro circumferentes, ut et vita Jesu manifestetur in corporibus nostris.

** II Corinthians 4:11

Semper enim nos, qui vivimus, in mortem tradimur propter Jesum : ut et vita Jesu manifestetur in carne nostra mortali.

** II Corinthians 4:12

Ergo mors in nobis operatur, vita autem in vobis.

** II Corinthians 4:13

Habentes autem eumdem spiritum fidei, sicut scriptum est : Credidi, propter quod locutus sum : et nos credimus, propter quod et loquimur :

** II Corinthians 4:14

scientes quoniam qui suscitavit Jesum, et nos cum Jesu suscitabit, et constituet vobiscum.

** II Corinthians 4:15

Omnia enim propter vos : ut gratia abundans, per multos in gratiarum actione, abundet in gloriam Dei.

** II Corinthians 4:16

Propter quod non deficimus : sed licet is, qui foris est, noster homo corrumpatur, tamen is, qui intus est, renovatur de die in diem.

** II Corinthians 4:17

Id enim, quod in præsenti est momentaneum et leve tribulationis nostræ, supra modum in sublimitate æternum gloriæ pondus operatur in nobis,

** II Corinthians 4:18

non contemplantibus nobis quæ videntur, sed quæ non videntur. Quæ enim videntur, temporalia sunt : quæ autem non videntur, æterna sunt.   

* II Corinthians 5

** II Corinthians 5:1

Scimus enim quoniam si terrestris domus nostra hujus habitationis dissolvatur, quod ædificationem ex Deo habemus, domum non manufactam, æternam in cælis.

** II Corinthians 5:2

Nam et in hoc ingemiscimus, habitationem nostram, quæ de cælo est, superindui cupientes :

** II Corinthians 5:3

si tamen vestiti, non nudi inveniamur.

** II Corinthians 5:4

Nam et qui sumus in hoc tabernaculo, ingemiscimus gravati : eo quod nolumus expoliari, sed supervestiri, ut absorbeatur quod mortale est, a vita.

** II Corinthians 5:5

Qui autem efficit nos in hoc ipsum, Deus, qui dedit nobis pignus Spiritus.

** II Corinthians 5:6

Audentes igitur semper, scientes quoniam dum sumus in corpore, peregrinamur a Domino

** II Corinthians 5:7

(per fidem enim ambulamus, et non per speciem) :

** II Corinthians 5:8

audemus autem, et bonam voluntatem habemus magis peregrinari a corpore, et præsentes esse ad Dominum.

** II Corinthians 5:9

Et ideo contendimus, sive absentes, sive præsentes, placere illi.

** II Corinthians 5:10

Omnes enim nos manifestari oportet ante tribunal Christi, ut referat unusquisque propria corporis, prout gessit, sive bonum, sive malum.  

** II Corinthians 5:11

Scientes ergo timorem Domini, hominibus suademus, Deo autem manifesti sumus. Spero autem et in conscientiis vestris manifestos nos esse.

** II Corinthians 5:12

Non iterum commendamus nos vobis, sed occasionem damus vobis gloriandi pro nobis : ut habeatis ad eos qui in facie gloriantur, et non in corde.

** II Corinthians 5:13

Sive enim mente excedimus Deo : sive sobrii sumus, vobis.

** II Corinthians 5:14

Caritas enim Christi urget nos : æstimantes hoc, quoniam si unus pro omnibus mortuus est, ergo omnes mortui sunt :

** II Corinthians 5:15

et pro omnibus mortuus est Christus : ut, et qui vivunt, jam non sibi vivant, sed ei qui pro ipsis mortuus est et resurrexit.

** II Corinthians 5:16

Itaque nos ex hoc neminem novimus secundum carnem. Et si cognovimus secundum carnem Christum, sed nunc jam non novimus.

** II Corinthians 5:17

Si qua ergo in Christo nova creatura, vetera transierunt : ecce facta sunt omnia nova.

** II Corinthians 5:18

Omnia autem ex Deo, qui nos reconciliavit sibi per Christum : et dedit nobis ministerium reconciliationis,

** II Corinthians 5:19

quoniam quidem Deus erat in Christo mundum reconcilians sibi, non reputans illis delicta ipsorum, et posuit in nobis verbum reconciliationis.

** II Corinthians 5:20

Pro Christo ergo legatione fungimur, tamquam Deo exhortante per nos. Obsecramus pro Christo, reconciliamini Deo.

** II Corinthians 5:21

Eum, qui non noverat peccatum, pro nobis peccatum fecit, ut nos efficeremur justitia Dei in ipso.   

* II Corinthians 6

** II Corinthians 6:1

Adjuvantes autem exhortamur ne in vacuum gratiam Dei recipiatis.

** II Corinthians 6:2

Ait enim : Tempore accepto exaudivi te, et in die salutis adjuvi te. Ecce nunc tempus acceptabile, ecce nunc dies salutis.

** II Corinthians 6:3

Nemini dantes ullam offensionem, ut non vituperetur ministerium nostrum :

** II Corinthians 6:4

sed in omnibus exhibeamus nosmetipsos sicut Dei ministros in multa patientia, in tribulationibus, in necessitatibus, in angustiis,

** II Corinthians 6:5

in plagis, in carceribus, in seditionibus, in laboribus, in vigiliis, in jejuniis,

** II Corinthians 6:6

in castitate, in scientia, in longanimitate, in suavitate, in Spiritu Sancto, in caritate non ficta,

** II Corinthians 6:7

in verbo veritatis, in virtute Dei, per arma justitiæ a dextris et a sinistris,

** II Corinthians 6:8

per gloriam, et ignobilitatem, per infamiam, et bonam famam : ut seductores, et veraces, sicut qui ignoti, et cogniti :

** II Corinthians 6:9

quasi morientes, et ecce vivimus : ut castigati, et non mortificati :

** II Corinthians 6:10

quasi tristes, semper autem gaudentes : sicut egentes, multos autem locupletantes : tamquam nihil habentes, et omnia possidentes.  

** II Corinthians 6:11

Os nostrum patet ad vos, o Corinthii ; cor nostrum dilatatum est.

** II Corinthians 6:12

Non angustiamini in nobis : angustiamini autem in visceribus vestris :

** II Corinthians 6:13

eamdem autem habentes remunerationem, tamquam filiis dico, dilatamini et vos.  

** II Corinthians 6:14

Nolite jugum ducere cum infidelibus. Quæ enim participatio justitiæ cum iniquitate ? aut quæ societas luci ad tenebras ?

** II Corinthians 6:15

quæ autem conventio Christi ad Belial ? aut quæ pars fideli cum infideli ?

** II Corinthians 6:16

qui autem consensus templo Dei cum idolis ? vos enim estis templum Dei vivi, sicut dicit Deus :   Quoniam inhabitabo in illis, et inambulabo inter eos,  et ero illorum Deus, et ipsi erunt mihi populus. 

** II Corinthians 6:17

Propter quod exite de medio eorum,  et separamini, dicit Dominus,  et immundum ne tetigeritis : 

** II Corinthians 6:18

et ego recipiam vos :  et ero vobis in patrem,  et vos eritis mihi in filios et filias,  dicit Dominus omnipotens.  

* II Corinthians 7

** II Corinthians 7:1

Has ergo habentes promissiones, carissimi, mundemus nos ab omni inquinamento carnis et spiritus, perficientes sanctificationem in timore Dei.

** II Corinthians 7:2

Capite nos. Neminem læsimus, neminem corrupimus, neminem circumvenimus.

** II Corinthians 7:3

Non ad condemnationem vestram dico : prædiximus enim quod in cordibus nostris estis ad commoriendum et ad convivendum.

** II Corinthians 7:4

Multa mihi fiducia est apud vos, multa mihi gloriatio pro vobis : repletus sum consolatione ; superabundo gaudio in omni tribulatione nostra.

** II Corinthians 7:5

Nam et cum venissemus in Macedoniam, nullam requiem habuit caro nostra, sed omnem tribulationem passi sumus : foris pugnæ, intus timores.

** II Corinthians 7:6

Sed qui consolatur humiles, consolatus est nos Deus in adventu Titi.

** II Corinthians 7:7

Non solum autem in adventu ejus, sed etiam in consolatione, qua consolatus est in vobis, referens nobis vestrum desiderium, vestrum fletum, vestram æmulationem pro me, ita ut magis gauderem.  

** II Corinthians 7:8

Quoniam etsi contristavi vos in epistola, non me pœnitet : etsi pœniteret, videns quod epistola illa (etsi ad horam) vos contristavit,

** II Corinthians 7:9

nunc gaudeo : non quia contristati estis, sed quia contristati estis ad pœnitentiam. Contristati enim estis ad Deum, ut in nullo detrimentum patiamini ex nobis.

** II Corinthians 7:10

Quæ enim secundum Deum tristitia est, pœnitentiam in salutem stabilem operatur : sæculi autem tristitia mortem operatur.

** II Corinthians 7:11

Ecce enim hoc ipsum, secundum Deum contristari vos, quantam in vobis operatur sollicitudinem : sed defensionem, sed indignationem, sed timorem, sed desiderium, sed æmulationem, sed vindictam : in omnibus exhibuistis vos incontaminatos esse negotio.

** II Corinthians 7:12

Igitur, etsi scripsi vobis, non propter eum qui fecit injuriam, nec propter eum qui passus est : sed ad manifestandam sollicitudinem nostram, quam habemus pro vobis

** II Corinthians 7:13

coram Deo : ideo consolati sumus. In consolatione autem nostra, abundantius magis gavisi sumus super gaudio Titi, quia refectus est spiritus ejus ab omnibus vobis :

** II Corinthians 7:14

et si quid apud illum de vobis gloriatus sum, non sum confusus : sed sicut omnia vobis in veritate locuti sumus, ita et gloriatio nostra, quæ fuit ad Titum, veritas facta est,

** II Corinthians 7:15

et viscera ejus abundantius in vobis sunt, reminiscentis omnium vestrum obedientiam : quomodo cum timore et tremore excepistis illum.

** II Corinthians 7:16

Gaudeo quod in omnibus confido in vobis.   

* II Corinthians 8

** II Corinthians 8:1

Notam autem facimus vobis, fratres, gratiam Dei, quæ data est in ecclesiis Macedoniæ :

** II Corinthians 8:2

quod in multo experimento tribulationis abundantia gaudii ipsorum fuit, et altissima paupertas eorum, abundavit in divitias simplicitatis eorum :

** II Corinthians 8:3

quia secundum virtutem testimonium illis reddo, et supra virtutem voluntarii fuerunt,

** II Corinthians 8:4

cum multa exhortatione obsecrantes nos gratiam, et communicationem ministerii, quod fit in sanctos.

** II Corinthians 8:5

Et non sicut speravimus, sed semetipsos dederunt primum Domino, deinde nobis per voluntatem Dei,

** II Corinthians 8:6

ita ut rogaremus Titum, ut quemadmodum cœpit, ita et perficiat in vobis etiam gratiam istam.

** II Corinthians 8:7

Sed sicut in omnibus abundatis fide, et sermone, et scientia, et omni sollicitudine, insuper et caritate vestra in nos, ut et in hac gratia abundetis.

** II Corinthians 8:8

Non quasi imperans dico : sed per aliorum sollicitudinem, etiam vestræ caritatis ingenium bonum comprobans.

** II Corinthians 8:9

Scitis enim gratiam Domini nostri Jesu Christi, quoniam propter vos egenus factus est, cum esset dives, ut illius inopia vos divites essetis.

** II Corinthians 8:10

Et consilium in hoc do : hoc enim vobis utile est, qui non solum facere, sed et velle cœpistis ab anno priore :

** II Corinthians 8:11

nunc vero et facto perficite : ut quemadmodum promptus est animus voluntatis, ita sit et perficiendi ex eo quod habetis.

** II Corinthians 8:12

Si enim voluntas prompta est, secundum id quod habet, accepta est, non secundum id quod non habet.

** II Corinthians 8:13

Non enim ut aliis sit remissio, vobis autem tribulatio, sed ex æqualitate.

** II Corinthians 8:14

In præsenti tempore vestra abundantia illorum inopiam suppleat : ut et illorum abundantia vestræ inopiæ sit supplementum, ut fiat æqualitas, sicut scriptum est :

** II Corinthians 8:15

Qui multum, non abundavit : et qui modicum, non minoravit.  

** II Corinthians 8:16

Gratias autem Deo, qui dedit eamdem sollicitudinem pro vobis in corde Titi,

** II Corinthians 8:17

quoniam exhortationem quidem suscepit : sed cum sollicitior esset, sua voluntate profectus est ad vos.

** II Corinthians 8:18

Misimus etiam cum illo fratrem, cujus laus est in Evangelio per omnes ecclesias :

** II Corinthians 8:19

non solum autem, sed et ordinatus est ab ecclesiis comes peregrinationis nostræ in hanc gratiam, quæ ministratur a nobis ad Domini gloriam, et destinatam voluntatem nostram :

** II Corinthians 8:20

devitantes hoc, ne quis nos vituperet in hac plenitudine, quæ ministratur a nobis.

** II Corinthians 8:21

Providemus enim bona non solum coram Deo, sed etiam coram hominibus.

** II Corinthians 8:22

Misimus autem cum illis et fratrem nostrum, quem probavimus in multis sæpe sollicitum esse : nunc autem multo sollicitiorem, confidentia multa in vos,

** II Corinthians 8:23

sive pro Tito, qui est socius meus, et in vos adjutor, sive fratres nostri, Apostoli ecclesiarum, gloria Christi.

** II Corinthians 8:24

Ostensionem ergo, quæ est caritatis vestræ, et nostræ gloriæ pro vobis, in illos ostendite in faciem ecclesiarum.   

* II Corinthians 9

** II Corinthians 9:1

Nam de ministerio, quod fit in sanctos ex abundanti est mihi scribere vobis.

** II Corinthians 9:2

Scio enim promptum animum vestrum : pro quo de vobis glorior apud Macedones. Quoniam et Achaia parata est ab anno præterito, et vestra æmulatio provocavit plurimos.

** II Corinthians 9:3

Misi autem fratres : ut ne quod gloriamur de vobis, evacuetur in hac parte, ut (quemadmodum dixi) parati sitis :

** II Corinthians 9:4

ne cum venerint Macedones mecum, et invenerint vos imparatos, erubescamus nos (ut non dicamus vos) in hac substantia.

** II Corinthians 9:5

Necessarium ergo existimavi rogare fratres, ut præveniant ad vos, et præparent repromissam benedictionem hanc paratam esse sic, quasi benedictionem, non tamquam avaritiam.  

** II Corinthians 9:6

Hoc autem dico : qui parce seminat, parce et metet : et qui seminat in benedictionibus, de benedictionibus et metet.

** II Corinthians 9:7

Unusquisque, prout destinavit in corde suo, non ex tristitia, aut ex necessitate : hilarem enim datorem diligit Deus.

** II Corinthians 9:8

Potens est autem Deus omnem gratiam abundare facere in vobis : ut in omnibus semper omnem sufficientiam habentes, abundetis in omne opus bonum,

** II Corinthians 9:9

sicut scriptum est : Dispersit, dedit pauperibus : justitia ejus manet in sæculum sæculi.

** II Corinthians 9:10

Qui autem administrat semen seminanti : et panem ad manducandum præstabit, et multiplicabit semen vestrum, et augebit incrementa frugum justitiæ vestræ :

** II Corinthians 9:11

ut in omnibus locupletati abundetis in omnem simplicitatem, quæ operatur per nos gratiarum actionem Deo.

** II Corinthians 9:12

Quoniam ministerium hujus officii non solum supplet ea quæ desunt sanctis, sed etiam abundat per multas gratiarum actiones in Domino,

** II Corinthians 9:13

per probationem ministerii hujus, glorificantes Deum in obedientia confessionis vestræ, in Evangelium Christi, et simplicitate communicationis in illos, et in omnes,

** II Corinthians 9:14

et in ipsorum obsecratione pro vobis, desiderantium vos propter eminentem gratiam Dei in vobis.

** II Corinthians 9:15

Gratias Deo super inenarrabili dono ejus.   

* II Corinthians 10

** II Corinthians 10:1

Ipse autem ego Paulus obsecro vos per mansuetudinem et modestiam Christi, qui in facie quidem humilis sum inter vos, absens autem confido in vos.

** II Corinthians 10:2

Rogo autem vos ne præsens audeam per eam confidentiam, qua existimor audere in quosdam, qui arbitrantur nos tamquam secundum carnem ambulemus.

** II Corinthians 10:3

In carne enim ambulantes, non secundum carnem militamus.

** II Corinthians 10:4

Nam arma militiæ nostræ non carnalia sunt, sed potentia Deo ad destructionem munitionum, consilia destruentes,

** II Corinthians 10:5

et omnem altitudinem extollentem se adversus scientiam Dei, et in captivitatem redigentes omnem intellectum in obsequium Christi,

** II Corinthians 10:6

et in promptu habentes ulcisci omnem inobedientiam, cum impleta fuerit vestra obedientia.  

** II Corinthians 10:7

Quæ secundum faciem sunt, videte. Si quis confidit sibi Christi se esse, hoc cogitet iterum apud se : quia sicut ipse Christi est, ita et nos.

** II Corinthians 10:8

Nam etsi amplius aliquid gloriatus fuero de potestate nostra, quam dedit nobis Dominus in ædificationem, et non in destructionem vestram, non erubescam.

** II Corinthians 10:9

Ut autem non existimer tamquam terrere vos per epistolas :

** II Corinthians 10:10

quoniam quidem epistolæ, inquiunt, graves sunt et fortes : præsentia autem corporis infirma, et sermo contemptibilis :

** II Corinthians 10:11

hoc cogitet qui ejusmodi est, quia quales sumus verbo per epistolas absentes, tales et præsentes in facto.  

** II Corinthians 10:12

Non enim audemus inserere, aut comparare nos quibusdam, qui seipsos commendant : sed ipsi in nobis nosmetipsos metientes, et comparantes nosmetipsos nobis.

** II Corinthians 10:13

Nos autem non in immensum gloriabimur, sed secundum mensuram regulæ, qua mensus est nobis Deus, mensuram pertingendi usque ad vos.

** II Corinthians 10:14

Non enim quasi non pertingentes ad vos, superextendimus nos : usque ad vos enim pervenimus in Evangelio Christi.

** II Corinthians 10:15

Non in immensum gloriantes in alienis laboribus : spem autem habentes crescentis fidei vestræ, in vobis magnificari secundum regulam nostram in abundantiam,

** II Corinthians 10:16

etiam in illa, quæ ultra vos sunt, evangelizare, non in aliena regula in iis quæ præparata sunt gloriari.

** II Corinthians 10:17

Qui autem gloriatur, in Domino glorietur.

** II Corinthians 10:18

Non enim qui seipsum commendat, ille probatus est : sed quem Deus commendat.   

* II Corinthians 11

** II Corinthians 11:1

Utinam sustineretis modicum quid insipientiæ meæ, sed et supportare me :

** II Corinthians 11:2

æmulor enim vos Dei æmulatione. Despondi enim vos uni viro, virginem castam exhibere Christo.

** II Corinthians 11:3

Timeo autem ne sicut serpens Hevam seduxit astutia sua, ita corrumpantur sensus vestri, et excidant a simplicitate, quæ est in Christo.

** II Corinthians 11:4

Nam si is qui venit, alium Christum prædicat, quem non prædicavimus, aut alium spiritum accipitis, quem non accepistis : aut aliud Evangelium, quod non recepistis : recte pateremini.

** II Corinthians 11:5

Existimo enim nihil me minus fecisse a magnis Apostolis.

** II Corinthians 11:6

Nam etsi imperitus sermone, sed non scientia, in omnibus autem manifestati sumus vobis.  

** II Corinthians 11:7

Aut numquid peccatum feci, meipsum humilians, ut vos exaltemini ? quoniam gratis Evangelium Dei evangelizavi vobis ?

** II Corinthians 11:8

Alias ecclesias expoliavi, accipiens stipendium ad ministerium vestrum.

** II Corinthians 11:9

Et cum essem apud vos, et egerem, nulli onerosus fui : nam quod mihi deerat, suppleverunt fratres, qui venerunt a Macedonia : et in omnibus sine onere me vobis servavi, et servabo.

** II Corinthians 11:10

Est veritas Christi in me, quoniam hæc gloriatio non infringetur in me in regionibus Achaiæ.

** II Corinthians 11:11

Quare ? quia non diligo vos ? Deus scit.

** II Corinthians 11:12

Quod autem facio, et faciam : ut amputem occasionem eorum qui volunt occasionem, ut in quo gloriantur, inveniantur sicut et nos.

** II Corinthians 11:13

Nam ejusmodi pseudoapostoli sunt operarii subdoli, transfigurantes se in apostolos Christi.

** II Corinthians 11:14

Et non mirum : ipse enim Satanas transfigurat se in angelum lucis.

** II Corinthians 11:15

Non est ergo magnum, si ministri ejus transfigurentur velut ministri justitiæ : quorum finis erit secundum opera ipsorum.  

** II Corinthians 11:16

Iterum dico (ne quis me putet insipientem esse, alioquin velut insipientem accipite me, ut et ego modicum quid glorier),

** II Corinthians 11:17

quod loquor, non loquor secundum Deum, sed quasi in insipientia, in hac substantia gloriæ.

** II Corinthians 11:18

Quoniam multi gloriantur secundum carnem : et ego gloriabor.

** II Corinthians 11:19

Libenter enim suffertis insipientes, cum sitis ipsi sapientes.

** II Corinthians 11:20

Sustinetis enim si quis vos in servitutem redigit, si quis devorat, si quis accipit, si quis extollitur, si quis in faciem vos cædit.

** II Corinthians 11:21

Secundum ignobilitatem dico, quasi nos infirmi fuerimus in hac parte. In quo quis audet (in insipientia dico) audeo et ego :

** II Corinthians 11:22

Hebræi sunt, et ego : Israëlitæ sunt, et ego : semen Abrahæ sunt, et ego.  

** II Corinthians 11:23

Ministri Christi sunt (ut minus sapiens dico), plus ego : in laboribus plurimis, in carceribus abundantius, in plagis supra modum, in mortibus frequenter.

** II Corinthians 11:24

A Judæis quinquies, quadragenas, una minus, accepi.

** II Corinthians 11:25

Ter virgis cæsus sum, semel lapidatus sum : ter naufragium feci, nocte et die in profundo maris fui,

** II Corinthians 11:26

in itineribus sæpe, periculis fluminum, periculis latronum, periculis ex genere, periculis ex gentibus, periculis in civitate, periculis in solitudine, periculis in mari, periculis in falsis fratribus :

** II Corinthians 11:27

in labore et ærumna, in vigiliis multis, in fame et siti, in jejuniis multis, in frigore et nuditate,

** II Corinthians 11:28

præter illa quæ extrinsecus sunt, instantia mea quotidiana, sollicitudo omnium ecclesiarum.

** II Corinthians 11:29

Quis infirmatur, et ego non infirmor ? quis scandalizatur, et ego non uror ?

** II Corinthians 11:30

Si gloriari oportet, quæ infirmitatis meæ sunt, gloriabor.

** II Corinthians 11:31

Deus et Pater Domini nostri Jesu Christi, qui est benedictus in sæcula, scit quod non mentior.

** II Corinthians 11:32

Damasci præpositus gentis Aretæ regis custodiebat civitatem Damascenorum ut me comprehenderet :

** II Corinthians 11:33

et per fenestram in sporta dimissus sum per murum, et sic effugi manus ejus.   

* II Corinthians 12

** II Corinthians 12:1

Si gloriari oportet (non expedit quidem), veniam autem ad visiones et revelationes Domini.

** II Corinthians 12:2

Scio hominem in Christo ante annos quatuordecim, sive in corpore nescio, sive extra corpus nescio, Deus scit, raptum hujusmodi usque ad tertium cælum.

** II Corinthians 12:3

Et scio hujusmodi hominem sive in corpore, sive extra corpus nescio, Deus scit :

** II Corinthians 12:4

quoniam raptus est in paradisum : et audivit arcana verba, quæ non licet homini loqui.

** II Corinthians 12:5

Pro hujusmodi gloriabor : pro me autem nihil gloriabor nisi in infirmitatibus meis.

** II Corinthians 12:6

Nam etsi voluero gloriari, non ero insipiens : veritatem enim dicam : parco autem, ne quis me existimet supra id quod videt in me, aut aliquid audit ex me.

** II Corinthians 12:7

Et ne magnitudo revelationum extollat me, datus est mihi stimulus carnis meæ angelus Satanæ, qui me colaphizet.

** II Corinthians 12:8

Propter quod ter Dominum rogavi ut discederet a me :

** II Corinthians 12:9

et dixit mihi : Sufficit tibi gratia mea : nam virtus in infirmitate perficitur. Libenter igitur gloriabor in infirmitatibus meis, ut inhabitet in me virtus Christi.

** II Corinthians 12:10

Propter quod placeo mihi in infirmitatibus meis, in contumeliis, in necessitatibus, in persecutionibus, in angustiis pro Christo : cum enim infirmor, tunc potens sum.

** II Corinthians 12:11

Factus sum insipiens, vos me coëgistis. Ego enim a vobis debui commendari : nihil enim minus fui ab iis, qui sunt supra modum Apostoli : tametsi nihil sum :

** II Corinthians 12:12

signa tamen apostolatus mei facta sunt super vos in omni patientia, in signis, et prodigiis, et virtutibus.

** II Corinthians 12:13

Quid est enim, quod minus habuistis præ ceteris ecclesiis, nisi quod ego ipse non gravavi vos ? donate mihi hanc injuriam.  

** II Corinthians 12:14

Ecce tertio hoc paratus sum venire ad vos : et non ero gravis vobis. Non enim quæro quæ vestra sunt, sed vos. Nec enim debent filii parentibus thesaurizare, sed parentes filiis.

** II Corinthians 12:15

Ego autem libentissime impendam, et super impendar ipse pro animabus vestris : licet plus vos diligens, minus diligar.

** II Corinthians 12:16

Sed esto : ego vos non gravavi : sed cum essem astutus, dolo vos cepi.

** II Corinthians 12:17

Numquid per aliquem eorum, quod misi ad vos, circumveni vos ?

** II Corinthians 12:18

Rogavi Titum, et misi cum illo fratrem. Numquid Titus vos circumvenit ? nonne eodem spiritu ambulavimus ? nonne iisdem vestigiis ?  

** II Corinthians 12:19

Olim putatis quod excusemus nos apud vos ? coram Deo in Christo loquimur : omnia autem, carissimi, propter ædificationem vestram.

** II Corinthians 12:20

Timeo enim ne forte cum venero, non quales volo, inveniam vos : et ego inveniar a vobis, qualem non vultis : ne forte contentiones, æmulationes, animositates, dissensiones, detractiones, susurrationes, inflationes, seditiones sint inter vos :

** II Corinthians 12:21

ne iterum cum venero, humiliet me Deus apud vos, et lugeam multos ex iis qui ante peccaverunt, et non egerunt pœnitentiam super immunditia, et fornicatione, et impudicitia, quam gesserunt.   

* II Corinthians 13

** II Corinthians 13:1

Ecce tertio hoc venio ad vos : in ore duorum vel trium testium stabit omne verbum.

** II Corinthians 13:2

Prædixi, et prædico, ut præsens, et nunc absens iis qui ante peccaverunt, et ceteris omnibus, quoniam si venero iterum, non parcam.

** II Corinthians 13:3

An experimentum quæritis ejus, qui in me loquitur Christus, qui in vobis non infirmatur, sed potens est in vobis ?

** II Corinthians 13:4

Nam etsi crucifixus est ex infirmitate : sed vivit ex virtute Dei. Nam et nos infirmi sumus in illo : sed vivemus cum eo ex virtute Dei in vobis.

** II Corinthians 13:5

Vosmetipsos tentate si estis in fide : ipsi vos probate. An non cognoscitis vosmetipsos quia Christus Jesus in vobis est ? nisi forte reprobi estis.

** II Corinthians 13:6

Spero autem quod cognoscetis, quia nos non sumus reprobi.

** II Corinthians 13:7

Oramus autem Deum ut nihil mali faciatis, non ut nos probati appareamus, sed ut vos quod bonum est faciatis : nos autem ut reprobi simus.

** II Corinthians 13:8

Non enim possumus aliquid adversus veritatem, sed pro veritate.

** II Corinthians 13:9

Gaudemus enim, quoniam nos infirmi sumus, vos autem potentes estis. Hoc et oramus, vestram consummationem.

** II Corinthians 13:10

Ideo hæc absens scribo, ut non præsens durius agam secundum potestatem, quam Dominus dedit mihi in ædificationem, et non in destructionem.  

** II Corinthians 13:11

De cetero, fratres, gaudete, perfecti estote, exhortamini, idem sapite, pacem habete, et Deus pacis et dilectionis erit vobiscum.

** II Corinthians 13:12

Salutate invicem in osculo sancto. Salutant vos omnes sancti.

** II Corinthians 13:13

Gratia Domini nostri Jesu Christi, et caritas Dei, et communicatio Sancti Spiritus sit cum omnibus vobis. Amen.    

