* II John 1

** II John 1:1

Senior Electæ dominæ, et natis ejus, quos ego diligo in veritate, et non ego solus, sed et omnes qui cognoverunt veritatem,

** II John 1:2

propter veritatem, quæ permanet in nobis, et nobiscum erit in æternum.

** II John 1:3

Sit vobiscum gratia, misericordia, pax a Deo Patre, et a Christo Jesu Filio Patris in veritate, et caritate.  

** II John 1:4

Gavisus sum valde, quoniam inveni de filiis tuis ambulantes in veritate, sicut mandatum accepimus a Patre.

** II John 1:5

Et nunc rogo te domina, non tamquam mandatum novum scribens tibi, sed quod habuimus ab initio, ut diligamus alterutrum.

** II John 1:6

Et hæc est caritas, ut ambulemus secundum mandata ejus. Hoc est enim mandatum, ut quemadmodum audistis ab initio, in eo ambuletis.  

** II John 1:7

Quoniam multi seductores exierunt in mundum, qui non confitentur Jesum Christum venisse in carnem : hic est seductor, et antichristus.

** II John 1:8

Videte vosmetipsos, ne perdatis quæ operati estis : sed ut mercedem plenam accipiatis.

** II John 1:9

Omnis qui recedit, et non permanet in doctrina Christi, Deum non habet : qui permanet in doctrina, hic et Patrem et Filium habet.

** II John 1:10

Si quis venit ad vos, et hanc doctrinam non affert, nolite recipere eum in domum, nec Ave ei dixeritis.

** II John 1:11

Qui enim dicit illi Ave, communicat operibus ejus malignis.  

** II John 1:12

Plura habens vobis scribere, nolui per cartam et atramentum : spero enim me futurum apud vos, et os ad os loqui : ut gaudium vestrum plenum sit.

** II John 1:13

Salutant te filii sororis tuæ Electæ.    

