* II Kings 1

** II Kings 1:1

Prævaricatus est autem Moab in Israël, postquam mortuus est Achab.

** II Kings 1:2

Ceciditque Ochozias per cancellos cœnaculi sui, quod habebat in Samaria, et ægrotavit : misitque nuntios, dicens ad eos : Ite, consulite Beelzebub deum Accaron, utrum vivere queam de infirmitate mea hac.

** II Kings 1:3

Angelus autem Domini locutus est ad Eliam Thesbiten, dicens : Surge, et ascende in occursum nuntiorum regis Samariæ, et dices ad eos : Numquid non est Deus in Israël, ut eatis ad consulendum Beelzebub deum Accaron ?

** II Kings 1:4

Quam ob rem hæc dicit Dominus : De lectulo, super quem ascendisti, non descendes, sed morte morieris. Et abiit Elias.

** II Kings 1:5

Reversique sunt nuntii ad Ochoziam. Qui dixit eis : Quare reversi estis ?

** II Kings 1:6

At illi responderunt ei : Vir occurrit nobis, et dixit ad nos : Ite, et revertimini ad regem qui misit vos, et dicetis ei : Hæc dicit Dominus : Numquid quia non erat Deus in Israël, mittis ut consulatur Beelzebub deus Accaron ? idcirco de lectulo, super quem ascendisti, non descendes, sed morte morieris.

** II Kings 1:7

Qui dixit eis : Cujus figuræ et habitus est vir ille, qui occurrit vobis, et locutus est verba hæc ?

** II Kings 1:8

At illi dixerunt : Vir pilosus, et zona pellicea accinctus renibus. Qui ait : Elias Thesbites est.  

** II Kings 1:9

Misitque ad eum quinquagenarium principem, et quinquaginta qui erant sub eo. Qui ascendit ad eum : sedentique in vertice montis, ait : Homo Dei, rex præcepit ut descendas.

** II Kings 1:10

Respondensque Elias, dixit quinquagenario : Si homo Dei sum, descendat ignis de cælo, et devoret te, et quinquaginta tuos. Descendit itaque ignis de cælo, et devoravit eum, et quinquaginta qui erant cum eo.

** II Kings 1:11

Rursumque misit ad eum principem quinquagenarium alterum, et quinquaginta cum eo. Qui locutus est illi : Homo Dei, hæc dicit rex : Festina, descende.

** II Kings 1:12

Respondens Elias, ait : Si homo Dei ego sum, descendat ignis de cælo, et devoret te, et quinquaginta tuos. Descendit ergo ignis de cælo, et devoravit illum, et quinquaginta ejus.

** II Kings 1:13

Iterum misit principem quinquagenarium tertium, et quinquaginta qui erant cum eo. Qui cum venisset, curvavit genua contra Eliam, et precatus est eum, et ait : Homo Dei, noli despicere animam meam, et animas servorum tuorum qui mecum sunt.

** II Kings 1:14

Ecce descendit ignis de cælo, et devoravit duos principes quinquagenarios primos, et quinquagenos qui cum eis erant : sed nunc obsecro ut miserearis animæ meæ.

** II Kings 1:15

Locutus est autem angelus Domini ad Eliam, dicens : Descende cum eo : ne timeas. Surrexit igitur, et descendit cum eo ad regem,

** II Kings 1:16

et locutus est ei : Hæc dicit Dominus : Quia misisti nuntios ad consulendum Beelzebub deum Accaron, quasi non esset Deus in Israël a quo posses interrogare sermonem, ideo de lectulo super quem ascendisti, non descendes, sed morte morieris.

** II Kings 1:17

Mortuus est ergo juxta sermonem Domini quem locutus est Elias, et regnavit Joram frater ejus pro eo, anno secundo Joram filii Josaphat regis Judæ : non enim habebat filium.

** II Kings 1:18

Reliqua autem verborum Ochoziæ quæ operatus est, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?   

* II Kings 2

** II Kings 2:1

Factum est autem cum levare vellet Dominus Eliam per turbinem in cælum, ibant Elias et Eliseus de Galgalis.

** II Kings 2:2

Dixitque Elias ad Eliseum : Sede hic, quia Dominus misit me usque in Bethel. Cui ait Eliseus : Vivit Dominus, et vivit anima tua, quia non derelinquam te. Cumque descendissent Bethel,

** II Kings 2:3

egressi sunt filii prophetarum qui erant in Bethel, ad Eliseum, et dixerunt ei : Numquid nosti quia hodie Dominus tollet dominum tuum a te ? Qui respondit : Et ego novi : silete.

** II Kings 2:4

Dixit autem Elias ad Eliseum : Sede hic, quia Dominus misit me in Jericho. Et ille ait : Vivit Dominus, et vivit anima tua, quia non derelinquam te. Cumque venissent Jericho,

** II Kings 2:5

accesserunt filii prophetarum qui erant in Jericho, ad Eliseum, et dixerunt ei : Numquid nosti quia Dominus hodie tollet dominum tuum a te ? Et ait : Et ego novi : silete.

** II Kings 2:6

Dixit autem ei Elias : Sede hic, quia Dominus misit me usque ad Jordanem. Qui ait : Vivit Dominus, et vivit anima tua, quia non derelinquam te. Ierunt igitur ambo pariter,

** II Kings 2:7

et quinquaginta viri de filiis prophetarum secuti sunt eos, qui et steterunt e contra, longe : illi autem ambo stabant super Jordanem.

** II Kings 2:8

Tulitque Elias pallium suum, et involvit illud, et percussit aquas : quæ divisæ sunt in utramque partem, et transierunt ambo per siccum.

** II Kings 2:9

Cumque transissent, Elias dixit ad Eliseum : Postula quod vis ut faciam tibi, antequam tollar a te. Dixitque Eliseus : Obsecro ut fiat in me duplex spiritus tuus.

** II Kings 2:10

Qui respondit : Rem difficilem postulasti : attamen si videris me quando tollar a te, erit tibi quod petisti : si autem non videris, non erit.  

** II Kings 2:11

Cumque pergerent, et incedentes sermocinarentur, ecce currus igneus, et equi ignei diviserunt utrumque : et ascendit Elias per turbinem in cælum.

** II Kings 2:12

Eliseus autem videbat, et clamabat : Pater mi, pater mi, currus Israël, et auriga ejus. Et non vidit eum amplius : apprehenditque vestimenta sua, et scidit illa in duas partes.

** II Kings 2:13

Et levavit pallium Eliæ, quod ceciderat ei : reversusque stetit super ripam Jordanis,

** II Kings 2:14

et pallio Eliæ, quod ceciderat ei, percussit aquas, et non sunt divisæ : et dixit : Ubi est Deus Eliæ etiam nunc ? Percussitque aquas, et divisæ sunt huc atque illuc, et transiit Eliseus.

** II Kings 2:15

Videntes autem filii prophetarum qui erant in Jericho e contra, dixerunt : Requievit spiritus Eliæ super Eliseum. Et venientes in occursum ejus, adoraverunt eum proni in terram,

** II Kings 2:16

dixeruntque illi : Ecce cum servis tuis sunt quinquaginta viri fortes qui possunt ire, et quærere dominum tuum, ne forte tulerit eum spiritus Domini, et projecerit eum in unum montium, aut in unam vallium. Qui ait : Nolite mittere.

** II Kings 2:17

Coëgeruntque eum donec acquiesceret, et diceret : Mittite. Et miserunt quinquaginta viros : qui cum quæsissent tribus diebus, non invenerunt.

** II Kings 2:18

Et reversi sunt ad eum : at ille habitabat in Jericho, et dixit eis : Numquid non dixi vobis : Nolite mittere ?

** II Kings 2:19

Dixerunt quoque viri civitatis ad Eliseum : Ecce habitatio civitatis hujus optima est, sicut tu ipse, domine, perspicis : sed aquæ pessimæ sunt, et terra sterilis.

** II Kings 2:20

At ille ait : Afferte mihi vas novum, et mittite in illud sal. Quod cum attulissent,

** II Kings 2:21

egressus ad fontem aquarum misit in illum sal, et ait : Hæc dicit Dominus : Sanavi aquas has, et non erit ultra in eis mors, neque sterilitas.

** II Kings 2:22

Sanatæ sunt ergo aquæ usque in diem hanc, juxta verbum Elisei quod locutus est.

** II Kings 2:23

Ascendit autem inde in Bethel : cumque ascenderet per viam, pueri parvi egressi sunt de civitate, et illudebant ei, dicentes : Ascende calve, ascende calve.

** II Kings 2:24

Qui cum respexisset, vidit eos, et maledixit eis in nomine Domini : egressique sunt duo ursi de saltu, et laceraverunt ex eis quadraginta duos pueros.

** II Kings 2:25

Abiit autem inde in montem Carmeli, et inde reversus est in Samariam.   

* II Kings 3

** II Kings 3:1

Joram vero filius Achab regnavit super Israël in Samaria anno decimooctavo Josaphat regis Judæ : regnavitque duodecim annis.

** II Kings 3:2

Et fecit malum coram Domino, sed non sicut pater suus et mater : tulit enim statuas Baal quas fecerat pater ejus.

** II Kings 3:3

Verumtamen in peccatis Jeroboam filii Nabat, qui peccare fecit Israël, adhæsit, nec recessit ab eis.

** II Kings 3:4

Porro Mesa rex Moab nutriebat pecora multa, et solvebat regi Israël centum millia agnorum, et centum millia arietum cum velleribus suis.

** II Kings 3:5

Cumque mortuus fuisset Achab, prævaricatus est fœdus quod habebat cum rege Israël.

** II Kings 3:6

Egressus est igitur rex Joram in die illa de Samaria, et recensuit universum Israël.

** II Kings 3:7

Misitque ad Josaphat regem Juda, dicens : Rex Moab recessit a me : veni mecum contra eum ad prælium. Qui respondit : Ascendam : qui meus est, tuus est : populus meus, populus tuus, et equi mei, equi tui.

** II Kings 3:8

Dixitque : Per quam viam ascendemus ? At ille respondit : Per desertum Idumææ.

** II Kings 3:9

Perrexerunt igitur rex Israël, et rex Juda, et rex Edom, et circuierunt per viam septem dierum, nec erat aqua exercitui et jumentis quæ sequebantur eos.

** II Kings 3:10

Dixitque rex Israël : Heu ! heu ! heu ! congregavit nos Dominus tres reges ut traderet in manus Moab.

** II Kings 3:11

Et ait Josaphat : Estne hic propheta Domini, ut deprecemur Dominum per eum ? Et respondit unus de servis regis Israël : Est hic Eliseus filius Saphat, qui fundebat aquam super manus Eliæ.

** II Kings 3:12

Et ait Josaphat : Est apud eum sermo Domini. Descenditque ad eum rex Israël, et Josaphat rex Juda, et rex Edom.  

** II Kings 3:13

Dixit autem Eliseus ad regem Israël : Quid mihi et tibi est ? vade ad prophetas patris tui et matris tuæ. Et ait illi rex Israël : Quare congregavit Dominus tres reges hos ut traderet eos in manus Moab ?

** II Kings 3:14

Dixitque ad eum Eliseus : Vivit Dominus exercituum, in cujus conspectu sto, quod si non vultum Josaphat regis Judæ erubescerem, non attendissem quidem te, nec respexissem.

** II Kings 3:15

Nunc autem adducite mihi psaltem. Cumque caneret psaltes, facta est super eum manus Domini, et ait :

** II Kings 3:16

Hæc dicit Dominus : Facite alveum torrentis hujus fossas et fossas.

** II Kings 3:17

Hæc enim dicit Dominus : Non videbitis ventum, neque pluviam : et alveus iste replebitur aquis, et bibetis vos, et familiæ vestræ, et jumenta vestra.

** II Kings 3:18

Parumque est hoc in conspectu Domini : insuper tradet etiam Moab in manus vestras.

** II Kings 3:19

Et percutietis omnem civitatem munitam, et omnem urbem electam, et universum lignum fructiferum succidetis, cunctosque fontes aquarum obturabitis, et omnem agrum egregium operietis lapidibus.

** II Kings 3:20

Factum est igitur mane, quando sacrificium offerri solet, et ecce aquæ veniebant per viam Edom, et repleta est terra aquis.

** II Kings 3:21

Universi autem Moabitæ audientes quod ascendissent reges ut pugnarent adversum eos, convocaverunt omnes qui accincti erant balteo desuper, et steterunt in terminis.

** II Kings 3:22

Primoque mane surgentes, et orto jam sole ex adverso aquarum, viderunt Moabitæ e contra aquas rubras quasi sanguinem,

** II Kings 3:23

dixeruntque : Sanguis gladii est : pugnaverunt reges contra se, et cæsi sunt mutuo : nunc perge ad prædam, Moab.

** II Kings 3:24

Perrexeruntque in castra Israël : porro consurgens Israël, percussit Moab : at illi fugerunt coram eis. Venerunt igitur qui vicerant, et percusserunt Moab,

** II Kings 3:25

et civitates destruxerunt : et omnem agrum optimum, mittentes singuli lapides, repleverunt : et universos fontes aquarum obturaverunt : et omnia ligna fructifera succiderunt, ita ut muri tantum fictiles remanerent : et circumdata est civitas a fundibulariis, et magna ex parte percussa.

** II Kings 3:26

Quod cum vidisset rex Moab, prævaluisse scilicet hostes, tulit secum septingentos viros educentes gladium, ut irrumperent ad regem Edom : et non potuerunt.

** II Kings 3:27

Arripiensque filium suum primogenitum, qui regnaturus erat pro eo, obtulit holocaustum super murum : et facta est indignatio magna in Israël, statimque recesserunt ab eo, et reversi sunt in terram suam.   

* II Kings 4

** II Kings 4:1

Mulier autem quædam de uxoribus prophetarum clamabat ad Eliseum, dicens : Servus tuus vir meus mortuus est, et tu nosti quia servus tuus fuit timens Dominum : et ecce creditor venit ut tollat duos filios meos ad serviendum sibi.

** II Kings 4:2

Cui dixit Eliseus : Quid vis ut faciam tibi ? dic mihi, quid habes in domo tua ? At illa respondit : Non habeo ancilla tua quidquam in domo mea, nisi parum olei quo ungar.

** II Kings 4:3

Cui ait : Vade, pete mutuo ab omnibus vicinis tuis vasa vacua non pauca,

** II Kings 4:4

et ingredere, et claude ostium tuum cum intrinsecus fueris tu, et filii tui : et mitte inde in omnia vasa hæc, et cum plena fuerint, tolles.

** II Kings 4:5

Ivit itaque mulier, et clausit ostium super se, et super filios suos : illi offerebant vasa, et illa infundebat.

** II Kings 4:6

Cumque plena fuissent vasa, dixit ad filium suum : Affer mihi adhuc vas. Et ille respondit : Non habeo. Stetitque oleum.

** II Kings 4:7

Venit autem illa, et indicavit homini Dei. Et ille : Vade, inquit, vende oleum, et redde creditori tuo : tu autem, et filii tui vivite de reliquo.  

** II Kings 4:8

Facta est autem quædam dies, et transibat Eliseus per Sunam : erat autem ibi mulier magna, quæ tenuit eum ut comederet panem : cumque frequenter inde transiret, divertebat ad eam ut comederet panem.

** II Kings 4:9

Quæ dixit ad virum suum : Animadverto quod vir Dei sanctus est iste, qui transit per nos frequenter.

** II Kings 4:10

Faciamus ergo ei cœnaculum parvum, et ponamus ei in eo lectulum, et mensam, et sellam, et candelabrum, ut cum venerit ad nos, maneat ibi.

** II Kings 4:11

Facta est ergo dies quædam, et veniens divertit in cœnaculum, et requievit ibi.

** II Kings 4:12

Dixitque ad Giezi puerum suum : Voca Sunamitidem istam. Qui cum vocasset eam, et illa stetisset coram eo,

** II Kings 4:13

dixit ad puerum suum : Loquere ad eam : Ecce, sedule in omnibus ministrasti nobis : quid vis ut faciam tibi ? numquid habes negotium, et vis ut loquar regi, sive principi militiæ ? Quæ respondit : In medio populi mei habito.

** II Kings 4:14

Et ait : Quid ergo vult ut faciam ei ? Dixitque Giezi : Ne quæras : filium enim non habet, et vir ejus senex est.

** II Kings 4:15

Præcepit itaque ut vocaret eam : quæ cum vocata fuisset, et stetisset ante ostium,

** II Kings 4:16

dixit ad eam : In tempore isto, et in hac eadem hora, si vita comes fuerit, habebis in utero filium. At illa respondit : Noli quæso, domine mi vir Dei, noli mentiri ancillæ tuæ.

** II Kings 4:17

Et concepit mulier, et peperit filium in tempore, et in hora eadem, qua dixerat Eliseus.  

** II Kings 4:18

Crevit autem puer : et cum esset quædam dies, et egressus isset ad patrem suum, ad messores,

** II Kings 4:19

ait patri suo : Caput meum doleo, caput meum doleo. At ille dixit puero : Tolle, et duc eum ad matrem suam.

** II Kings 4:20

Qui cum tulisset, et duxisset eum ad matrem suam, posuit eum illa super genua sua usque ad meridiem, et mortuus est.

** II Kings 4:21

Ascendit autem, et collocavit eum super lectulum hominis Dei, et clausit ostium : et egressa,

** II Kings 4:22

vocavit virum suum, et ait : Mitte mecum, obsecro, unum de pueris, et asinam, ut excurram usque ad hominem Dei, et revertar.

** II Kings 4:23

Qui ait illi : Quam ob causam vadis ad eum ? hodie non sunt calendæ, neque sabbatum. Quæ respondit : Vadam.

** II Kings 4:24

Stravitque asinam, et præcepit puero : Mina, et propera : ne mihi moram facias in eundo : et hoc age quod præcipio tibi.

** II Kings 4:25

Profecta est igitur, et venit ad virum Dei in montem Carmeli : cumque vidisset eam vir Dei e contra, ait ad Giezi puerum suum : Ecce Sunamitis illa.

** II Kings 4:26

Vade ergo in occursum ejus, et dic ei : Recte ne agitur circa te, et circa virum tuum, et circa filium tuum ? Quæ respondit : Recte.

** II Kings 4:27

Cumque venisset ad virum Dei in montem, apprehendit pedes ejus : et accessit Giezi ut amoveret eam. Et ait homo Dei : Dimitte illam : anima enim ejus in amaritudine est, et Dominus celavit a me, et non indicavit mihi.

** II Kings 4:28

Quæ dixit illi : Numquid petivi filium a domino meo ? numquid non dixi tibi : Ne illudas me ?

** II Kings 4:29

Et ille ait ad Giezi : Accinge lumbos tuos, et tolle baculum meum in manu tua, et vade. Si occurrerit tibi homo, non salutes eum : et si salutaverit te quispiam, non respondeas illi : et pones baculum meum super faciem pueri.

** II Kings 4:30

Porro mater pueri ait : Vivit Dominus, et vivit anima tua, non dimittam te. Surrexit ergo, et secutus est eam.

** II Kings 4:31

Giezi autem præcesserat ante eos, et posuerat baculum super faciem pueri, et non erat vox, neque sensus : reversusque est in occursum ejus, et nuntiavit ei, dicens : Non surrexit puer.

** II Kings 4:32

Ingressus est ergo Eliseus domum, et ecce puer mortuus jacebat in lectulo ejus :

** II Kings 4:33

ingressusque clausit ostium super se et super puerum, et oravit ad Dominum.

** II Kings 4:34

Et ascendit, et incubuit super puerum : posuitque os suum super os ejus, et oculos suos super oculos ejus, et manus suas super manus ejus : et incurvavit se super eum, et calefacta est caro pueri.

** II Kings 4:35

At ille reversus, deambulavit in domo, semel huc atque illuc : et ascendit, et incubuit super eum : et oscitavit puer septies, aperuitque oculos.

** II Kings 4:36

At ille vocavit Giezi, et dixit ei : Voca Sunamitidem hanc. Quæ vocata, ingressa est ad eum. Qui ait : Tolle filium tuum.

** II Kings 4:37

Venit illa, et corruit ad pedes ejus, et adoravit super terram : tulitque filium suum, et egressa est.  

** II Kings 4:38

Et Eliseus reversus est in Galgala. Erat autem fames in terra, et filii prophetarum habitabant coram eo. Dixitque uni de pueris suis : Pone ollam grandem, et coque pulmentum filiis prophetarum.

** II Kings 4:39

Et egressus est unus in agrum ut colligeret herbas agrestes : invenitque quasi vitem silvestrem, et collegit ex ea colocynthidas agri, et implevit pallium suum, et reversus concidit in ollam pulmenti : nesciebat enim quid esset.

** II Kings 4:40

Infuderunt ergo sociis ut comederent : cumque gustassent de coctione, clamaverunt, dicentes : Mors in olla, vir Dei. Et non potuerunt comedere.

** II Kings 4:41

At ille : Afferte, inquit, farinam. Cumque tulissent, misit in ollam, et ait : Infunde turbæ, ut comedant. Et non fuit amplius quidquam amaritudinis in olla.

** II Kings 4:42

Vir autem quidam venit de Baalsalisa deferens viro Dei panes primitiarum, viginti panes hordeaceos, et frumentum novum in pera sua. At ille dixit : Da populo, ut comedat.

** II Kings 4:43

Responditque ei minister ejus : Quantum est hoc, ut apponam centum viris ? Rursum ille ait : Da populo, ut comedat : hæc enim dicit Dominus : Comedent, et supererit.

** II Kings 4:44

Posuit itaque coram eis : qui comederunt, et superfuit juxta verbum Domini.   

* II Kings 5

** II Kings 5:1

Naaman princeps militiæ regis Syriæ erat vir magnus apud dominum suum, et honoratus : per illum enim dedit Dominus salutem Syriæ : erat autem vir fortis et dives, sed leprosus.

** II Kings 5:2

Porro de Syria egressi fuerant latrunculi, et captivam duxerant de terra Israël puellam parvulam, quæ erat in obsequio uxoris Naaman :

** II Kings 5:3

quæ ait ad dominam suam : Utinam fuisset dominus meus ad prophetam qui est in Samaria, profecto curasset eum a lepra quam habet.

** II Kings 5:4

Ingressus est itaque Naaman ad dominum suum, et nuntiavit ei, dicens : Sic et sic locuta est puella de terra Israël.

** II Kings 5:5

Dixitque ei rex Syriæ : Vade, et mittam litteras ad regem Israël. Qui cum profectus esset, et tulisset secum decem talenta argenti, et sex millia aureos, et decem mutatoria vestimentorum,

** II Kings 5:6

detulit litteras ad regem Israël in hæc verba : Cum acceperis epistolam hanc, scito quod miserim ad te Naaman servum meum, ut cures eum a lepra sua.

** II Kings 5:7

Cumque legisset rex Israël litteras, scidit vestimenta sua, et ait : Numquid deus ego sum, ut occidere possim et vivificare, quia iste misit ad me ut curem hominem a lepra sua ? animadvertite, et videte quod occasiones quærat adversum me.

** II Kings 5:8

Quod cum audisset Eliseus vir Dei, scidisse videlicet regem Israël vestimenta sua, misit ad eum, dicens : Quare scidisti vestimenta tua ? veniat ad me, et sciat esse prophetam in Israël.

** II Kings 5:9

Venit ergo Naaman cum equis et curribus, et stetit ad ostium domus Elisei :

** II Kings 5:10

misitque ad eum Eliseus nuntium, dicens : Vade, et lavare septies in Jordane, et recipiet sanitatem caro tua, atque mundaberis.

** II Kings 5:11

Iratus Naaman recedebat, dicens : Putabam quod egrederetur ad me, et stans invocaret nomen Domini Dei sui, et tangeret manu sua locum lepræ, et curaret me.

** II Kings 5:12

Numquid non meliores sunt Abana et Pharphar fluvii Damasci, omnibus aquis Israël, ut laver in eis, et munder ? Cum ergo vertisset se, et abiret indignans,

** II Kings 5:13

accesserunt ad eum servi sui, et locuti sunt ei : Pater, etsi rem grandem dixisset tibi propheta, certe facere debueras : quanto magis quia nunc dixit tibi : Lavare, et mundaberis ?

** II Kings 5:14

Descendit, et lavit in Jordane septies juxta sermonem viri Dei : et restituta est caro ejus sicut caro pueri parvuli, et mundatus est.

** II Kings 5:15

Reversusque ad virum Dei cum universo comitatu suo, venit, et stetit coram eo, et ait : Vere scio quod non sit alius deus in universa terra, nisi tantum in Israël. Obsecro itaque ut accipias benedictionem a servo tuo.

** II Kings 5:16

At ille respondit : Vivit Dominus, ante quem sto, quia non accipiam. Cumque vim faceret, penitus non acquievit.

** II Kings 5:17

Dixitque Naaman : Ut vis : sed, obsecro, concede mihi servo tuo ut tollam onus duorum burdonum de terra : non enim faciet ultra servus tuus holocaustum aut victimam diis alienis, nisi Domino.

** II Kings 5:18

Hoc autem solum est, de quo depreceris Dominum pro servo tuo, quando ingredietur dominus meus templum Remmon ut adoret : et illo innitente super manum meam, si adoravero in templo Remmon, adorante eo in eodem loco, ut ignoscat mihi Dominus servo tuo pro hac re.

** II Kings 5:19

Qui dixit ei : Vade in pace. Abiit ergo ab eo electo terræ tempore.  

** II Kings 5:20

Dixitque Giezi puer viri Dei : Pepercit dominus meus Naaman Syro isti, ut non acciperet ab eo quæ attulit : vivit Dominus, quia curram post eum, et accipiam ab eo aliquid.

** II Kings 5:21

Et secutus est Giezi post tergum Naaman : quem cum vidisset ille currentem ad se, desiliit de curru in occursum ejus, et ait : Rectene sunt omnia ?

** II Kings 5:22

Et ille ait : Recte. Dominus meus misit me ad te dicens : Modo venerunt ad me duo adolescentes de monte Ephraim, ex filiis prophetarum : da eis talentum argenti, et vestes mutatorias duplices.

** II Kings 5:23

Dixitque Naaman : Melius est ut accipias duo talenta. Et coëgit eum, ligavitque duo talenta argenti in duobus saccis, et duplicia vestimenta, et imposuit duobus pueris suis, qui et portaverunt coram eo.

** II Kings 5:24

Cumque venisset jam vesperi, tulit de manu eorum, et reposuit in domo, dimisitque viros, et abierunt.

** II Kings 5:25

Ipse autem ingressus, stetit coram domino suo. Et dixit Eliseus : Unde venis, Giezi ? Qui respondit : Non ivit servus tuus quoquam.

** II Kings 5:26

At ille ait : Nonne cor meum in præsenti erat, quando reversus est homo de curru suo in occursum tui ? nunc igitur accepisti argentum, et accepisti vestes ut emas oliveta, et vineas, et oves, et boves, et servos, et ancillas.

** II Kings 5:27

Sed et lepra Naaman adhærebit tibi, et semini tuo usque in sempiternum. Et egressus est ab eo leprosus quasi nix.   

* II Kings 6

** II Kings 6:1

Dixerunt autem filii prophetarum ad Eliseum : Ecce locus in quo habitamus coram te, angustus est nobis.

** II Kings 6:2

Eamus usque ad Jordanem, et tollant singuli de silva materias singulas, ut ædificemus nobis ibi locum ad habitandum. Qui dixit : Ite.

** II Kings 6:3

Et ait unus ex illis : Veni ergo et tu cum servis tuis. Respondit : Ego veniam.

** II Kings 6:4

Et abiit cum eis. Cumque venissent ad Jordanem, cædebant ligna.

** II Kings 6:5

Accidit autem ut cum unus materiam succidisset, caderet ferrum securis in aquam : exclamavitque ille, et ait : Heu ! heu ! heu ! domine mi : et hoc ipsum mutuo acceperam.

** II Kings 6:6

Dixit autem homo Dei : Ubi cecidit ? At ille monstravit ei locum. Præcidit ergo lignum, et misit illuc : natavitque ferrum,

** II Kings 6:7

et ait : Tolle. Qui extendit manum, et tulit illud.  

** II Kings 6:8

Rex autem Syriæ pugnabat contra Israël, consiliumque iniit cum servis suis, dicens : In loco illo et illo ponamus insidias.

** II Kings 6:9

Misit itaque vir Dei ad regem Israël, dicens : Cave ne transeas in locum illum : quia ibi Syri in insidiis sunt.

** II Kings 6:10

Misit itaque rex Israël ad locum quem dixerat ei vir Dei, et præoccupavit eum, et observavit se ibi non semel neque bis.

** II Kings 6:11

Conturbatumque est cor regis Syriæ pro hac re : et convocatis servis suis, ait : Quare non indicatis mihi quis proditor mei sit apud regem Israël ?

** II Kings 6:12

Dixitque unus servorum ejus : Nequaquam, domine mi rex, sed Eliseus propheta qui est in Israël, indicat regi Israël omnia verba quæcumque locutus fueris in conclavi tuo.

** II Kings 6:13

Dixitque eis : Ite, et videte ubi sit, ut mittam, et capiam eum. Annuntiaveruntque ei, dicentes : Ecce in Dothan.

** II Kings 6:14

Misit ergo illuc equos et currus, et robur exercitus : qui cum venissent nocte, circumdederunt civitatem.

** II Kings 6:15

Consurgens autem diluculo minister viri Dei, egressus vidit exercitum in circuitu civitatis, et equos et currus : nuntiavitque ei, dicens : Heu ! heu ! heu ! domine mi : quid faciemus ?

** II Kings 6:16

At ille respondit : Noli timere : plures enim nobiscum sunt, quam cum illis.

** II Kings 6:17

Cumque orasset Eliseus, ait : Domine, aperi oculos hujus, ut videat. Et aperuit Dominus oculos pueri, et vidit : et ecce mons plenus equorum et curruum igneorum in circuitu Elisei.

** II Kings 6:18

Hostes vero descenderunt ad eum : porro Eliseus oravit ad Dominum, dicens : Percute, obsecro, gentem hanc cæcitate. Percussitque eos Dominus ne viderent, juxta verbum Elisei.

** II Kings 6:19

Dixit autem ad eos Eliseus : Non est hæc via, neque ista est civitas : sequimini me, et ostendam vobis virum quem quæritis. Duxit ergo eos in Samariam :

** II Kings 6:20

cumque ingressi fuissent in Samariam, dixit Eliseus : Domine, aperi oculos istorum, ut videant. Aperuitque Dominus oculos eorum, et viderunt se esse in medio Samariæ.

** II Kings 6:21

Dixitque rex Israël ad Eliseum, cum vidisset eos : Numquid percutiam eos, pater mi ?

** II Kings 6:22

At ille ait : Non percuties : neque enim cepisti eos gladio et arcu tuo, ut percutias : sed pone panem et aquam coram eis, ut comedant et bibant, et vadant ad dominum suum.

** II Kings 6:23

Appositaque est eis ciborum magna præparatio, et comederunt et biberunt, et dimisit eos, abieruntque ad dominum suum, et ultra non venerunt latrones Syriæ in terram Israël.  

** II Kings 6:24

Factum est autem post hæc, congregavit Benadad rex Syriæ universum exercitum suum, et ascendit, et obsidebat Samariam.

** II Kings 6:25

Factaque est fames magna in Samaria : et tamdiu obsessa est, donec venundaretur caput asini octoginta argenteis, et quarta pars cabi stercoris columbarum quinque argenteis.

** II Kings 6:26

Cumque rex Israël transiret per murum, mulier quædam exclamavit ad eum, dicens : Salva me, domine mi rex.

** II Kings 6:27

Qui ait : Non te salvat Dominus : unde te possum salvare ? de area, vel de torculari ? Dixitque ad eam rex : Quid tibi vis ? Quæ respondit :

** II Kings 6:28

Mulier ista dixit mihi : Da filium tuum, ut comedamus eum hodie, et filium meum comedemus cras.

** II Kings 6:29

Coximus ergo filium meum, et comedimus. Dixique ei die altera : Da filium tuum, ut comedamus eum. Quæ abscondit filium suum.

** II Kings 6:30

Quod cum audisset rex, scidit vestimenta sua, et transibat per murum. Viditque omnis populus cilicium quo vestitus erat ad carnem intrinsecus.

** II Kings 6:31

Et ait rex : Hæc mihi faciat Deus, et hæc addat, si steterit caput Elisei filii Saphat super ipsum hodie.

** II Kings 6:32

Eliseus autem sedebat in domo sua, et senes sedebant cum eo. Præmisit itaque virum : et antequam veniret nuntius ille, dixit ad senes : Numquid scitis quod miserit filius homicidæ hic, ut præcidatur caput meum ? videte ergo : cum venerit nuntius, claudite ostium, et non sinatis eum introire : ecce enim sonitus pedum domini ejus post eum est.

** II Kings 6:33

Adhuc illo loquente eis, apparuit nuntius qui veniebat ad eum. Et ait : Ecce, tantum malum a Domino est : quid amplius expectabo a Domino ?   

* II Kings 7

** II Kings 7:1

Dixit autem Eliseus : Audite verbum Domini : Hæc dicit Dominus : In tempore hoc cras modius similæ uno statere erit, et duo modii hordei statere uno, in porta Samariæ.

** II Kings 7:2

Respondens unus de ducibus, super cujus manum rex incumbebat, homini Dei, ait : Si Dominus fecerit etiam cataractas in cælo, numquid poterit esse quod loqueris ? Qui ait : Videbis oculis tuis, et inde non comedes.

** II Kings 7:3

Quatuor ergo viri erant leprosi juxta introitum portæ : qui dixerunt ad invicem : Quid hic esse volumus donec moriamur ?

** II Kings 7:4

sive ingredi voluerimus civitatem, fame moriemur : sive manserimus hic, moriendum nobis est : venite ergo, et transfugiamus ad castra Syriæ : si pepercerint nobis, vivemus : si autem occidere voluerint, nihilominus moriemur.

** II Kings 7:5

Surrexerunt ergo vesperi, ut venirent ad castra Syriæ. Cumque venissent ad principium castrorum Syriæ, nullum ibidem repererunt.

** II Kings 7:6

Siquidem Dominus sonitum audiri fecerat in castris Syriæ, curruum, et equorum, et exercitus plurimi : dixeruntque ad invicem : Ecce mercede conduxit adversum nos rex Israël reges Hethæorum et Ægyptiorum, et venerunt super nos.

** II Kings 7:7

Surrexerunt ergo, et fugerunt in tenebris, et dereliquerunt tentoria sua, et equos et asinos, in castris, fugeruntque animas tantum suas salvare cupientes.

** II Kings 7:8

Igitur cum venissent leprosi illi ad principium castrorum, ingressi sunt unum tabernaculum, et comederunt et biberunt : tuleruntque inde argentum, et aurum, et vestes, et abierunt, et absconderunt : et rursum reversi sunt ad aliud tabernaculum, et inde similiter auferentes absconderunt.

** II Kings 7:9

Dixeruntque ad invicem : Non recte facimus : hæc enim dies boni nuntii est. Si tacuerimus et noluerimus nuntiare usque mane, sceleris arguemur : venite, eamus, et nuntiemus in aula regis.

** II Kings 7:10

Cumque venissent ad portam civitatis, narraverunt eis, dicentes : Ivimus ad castra Syriæ, et nullum ibidem reperimus hominem, nisi equos et asinos alligatos, et fixa tentoria.

** II Kings 7:11

Ierunt ergo portarii, et nuntiaverunt in palatio regis intrinsecus.

** II Kings 7:12

Qui surrexit nocte, et ait ad servos suos : Dico vobis quid fecerint nobis Syri : sciunt quia fame laboramus, et idcirco egressi sunt de castris, et latitant in agris, dicentes : Cum egressi fuerint de civitate, capiemus eos vivos, et tunc civitatem ingredi poterimus.

** II Kings 7:13

Respondit autem unus servorum ejus : Tollamus quinque equos qui remanserunt in urbe (quia ipsi tantum sunt in universa multitudine Israël, alii enim consumpti sunt), et mittentes, explorare poterimus.

** II Kings 7:14

Adduxerunt ergo duos equos, misitque rex in castra Syrorum, dicens : Ite, et videte.

** II Kings 7:15

Qui abierunt post eos usque ad Jordanem : ecce autem omnis via plena erat vestibus et vasis quæ projecerant Syri cum turbarentur : reversique nuntii indicaverunt regi.

** II Kings 7:16

Et egressus populus diripuit castra Syriæ : factusque est modius similæ statere uno, et duo modii hordei statere uno, juxta verbum Domini.

** II Kings 7:17

Porro rex ducem illum, in cujus manu incumbebat, constituit ad portam : quem conculcavit turba in introitu portæ, et mortuus est, juxta quod locutus fuerat vir Dei, quando descenderat rex ad eum.

** II Kings 7:18

Factumque est secundum sermonem viri Dei quem dixerat regi, quando ait : Duo modii hordei statere uno erunt, et modius similæ statere uno, hoc eodem tempore cras in porta Samariæ :

** II Kings 7:19

quando responderat dux ille viro Dei, et dixerat : Etiamsi Dominus fecerit cataractas in cælo, numquid poterit fieri quod loqueris ? Et dixit ei : Videbis oculis tuis, et inde non comedes.

** II Kings 7:20

Evenit ergo ei sicut prædictum fuerat, et conculcavit eum populus in porta, et mortuus est.   

* II Kings 8

** II Kings 8:1

Eliseus autem locutus est ad mulierem cujus vivere fecerat filium, dicens : Surge, vade tu et domus tua, et peregrinare ubicumque repereris : vocavit enim Dominus famem, et veniet super terram septem annis.

** II Kings 8:2

Quæ surrexit, et fecit juxta verbum hominis Dei : et vadens cum domo sua, peregrinata est in terra Philisthiim diebus multis.

** II Kings 8:3

Cumque finiti essent anni septem, reversa est mulier de terra Philisthiim : et egressa est ut interpellaret regem pro domo sua, et pro agris suis.

** II Kings 8:4

Rex autem loquebatur cum Giezi puero viri Dei, dicens : Narra mihi omnia magnalia quæ fecit Eliseus.

** II Kings 8:5

Cumque ille narraret regi quomodo mortuum suscitasset, apparuit mulier cujus vivificaverat filium, clamans ad regem pro domo sua, et pro agris suis. Dixitque Giezi : Domine mi rex, hæc est mulier, et hic est filius ejus quem suscitavit Eliseus.

** II Kings 8:6

Et interrogavit rex mulierem : quæ narravit ei. Deditque ei rex eunuchum unum, dicens : Restitue ei omnia quæ sua sunt, et universos reditus agrorum, a die qua reliquit terram usque ad præsens.  

** II Kings 8:7

Venit quoque Eliseus Damascum, et Benadad rex Syriæ ægrotabat : nuntiaveruntque ei, dicentes : Venit vir Dei huc.

** II Kings 8:8

Et ait rex ad Hazaël : Tolle tecum munera, et vade in occursum viri Dei, et consule Dominum per eum, dicens : Si evadere potero de infirmitate mea hac ?

** II Kings 8:9

Ivit igitur Hazaël in occursum ejus, habens secum munera, et omnia bona Damasci, onera quadraginta camelorum. Cumque stetisset coram eo, ait : Filius tuus Benadad rex Syriæ misit me ad te, dicens : Si sanari potero de infirmitate mea hac ?

** II Kings 8:10

Dixitque ei Eliseus : Vade, dic ei : Sanaberis : porro ostendit mihi Dominus quia morte morietur.

** II Kings 8:11

Stetique cum eo, et conturbatus est usque ad suffusionem vultus : flevitque vir Dei.

** II Kings 8:12

Cui Hazaël ait : Quare dominus meus flet ? At ille dixit : Quia scio quæ facturus sis filiis Israël mala. Civitates eorum munitas igne succendes, et juvenes eorum interficies gladio, et parvulos eorum elides, et prægnantes divides.

** II Kings 8:13

Dixitque Hazaël : Quid enim sum servus tuus canis, ut faciam rem istam magnam ? Et ait Eliseus : Ostendit mihi Dominus te regem Syriæ fore.

** II Kings 8:14

Qui cum recessisset ab Eliseo, venit ad dominum suum. Qui ait ei : Quid dixit tibi Eliseus ? At ille respondit : Dixit mihi : Recipies sanitatem.

** II Kings 8:15

Cumque venisset dies altera, tulit stragulum, et infudit aquam, et expandit super faciem ejus : quo mortuo, regnavit Hazaël pro eo.  

** II Kings 8:16

Anno quinto Joram filii Achab regis Israël, et Josaphat regis Juda, regnavit Joram filius Josaphat rex Juda.

** II Kings 8:17

Triginta duorum annorum erat cum regnare cœpisset, et octo annis regnavit in Jerusalem.

** II Kings 8:18

Ambulavitque in viis regum Israël, sicut ambulaverat domus Achab : filia enim Achab erat uxor ejus : et fecit quod malum est in conspectu Domini.

** II Kings 8:19

Noluit autem Dominus disperdere Judam, propter David servum suum, sicut promiserat ei, ut daret illi lucernam, et filiis ejus cunctis diebus.

** II Kings 8:20

In diebus ejus recessit Edom ne esset sub Juda, et constituit sibi regem.

** II Kings 8:21

Venitque Joram Seira, et omnes currus cum eo : et surrexit nocte, percussitque Idumæos qui eum circumdederant, et principes curruum : populus autem fugit in tabernacula sua.

** II Kings 8:22

Recessit ergo Edom ne esset sub Juda, usque ad diem hanc. Tunc recessit et Lobna in tempore illo.

** II Kings 8:23

Reliqua autem sermonum Joram, et universa quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** II Kings 8:24

Et dormivit Joram cum patribus suis, sepultusque est cum eis in civitate David, et regnavit Ochozias filius ejus pro eo.  

** II Kings 8:25

Anno duodecimo Joram filii Achab regis Israël regnavit Ochozias filius Joram regis Judæ.

** II Kings 8:26

Viginti duorum annorum erat Ochozias cum regnare cœpisset, et uno anno regnavit in Jerusalem : nomen matris ejus Athalia filia Amri regis Israël.

** II Kings 8:27

Et ambulavit in viis domus Achab : et fecit quod malum est coram Domino, sicut domus Achab : gener enim domus Achab fuit.

** II Kings 8:28

Abiit quoque cum Joram filio Achab ad præliandum contra Hazaël regem Syriæ in Ramoth Galaad, et vulneraverunt Syri Joram.

** II Kings 8:29

Qui reversus est ut curaretur in Jezrahel, quia vulneraverant eum Syri in Ramoth præliantem contra Hazaël regem Syriæ. Porro Ochozias filius Joram rex Juda descendit invisere Joram filium Achab in Jezrahel, quia ægrotabat ibi.   

* II Kings 9

** II Kings 9:1

Eliseus autem prophetes vocavit unum de filiis prophetarum, et ait illi : Accinge lumbos tuos, et tolle lenticulam olei hanc in manu tua, et vade in Ramoth Galaad.

** II Kings 9:2

Cumque veneris illuc, videbis Jehu filium Josaphat filii Namsi : et ingressus suscitabis eum de medio fratrum suorum, et introduces in interius cubiculum.

** II Kings 9:3

Tenensque lenticulam olei, fundes super caput ejus, et dices : Hæc dicit Dominus : Unxi te regem super Israël. Aperiesque ostium, et fugies, et non ibi subsistes.

** II Kings 9:4

Abiit ergo adolescens puer prophetæ in Ramoth Galaad,

** II Kings 9:5

et ingressus est illuc : ecce autem principes exercitus sedebant : et ait : Verbum mihi ad te, o princeps. Dixitque Jehu : Ad quem ex omnibus nobis ? At ille dixit : Ad te, o princeps.

** II Kings 9:6

Et surrexit, et ingressus est cubiculum : at ille fudit oleum super caput ejus, et ait : Hæc dicit Dominus Deus Israël : Unxi te regem super populum Domini Israël,

** II Kings 9:7

et percuties domum Achab domini tui, et ulciscar sanguinem servorum meorum prophetarum, et sanguinem omnium servorum Domini de manu Jezabel.

** II Kings 9:8

Perdamque omnem domum Achab : et interficiam de Achab mingentem ad parietem, et clausum et novissimum in Israël.

** II Kings 9:9

Et dabo domum Achab sicut domum Jeroboam filii Nabat, et sicut domum Baasa filii Ahia.

** II Kings 9:10

Jezabel quoque comedent canes in agro Jezrahel, nec erit qui sepeliat eam. Aperuitque ostium, et fugit.

** II Kings 9:11

Jehu autem egressus est ad servos domini sui : qui dixerunt ei : Rectene sunt omnia ? quid venit insanus iste ad te ? Qui ait eis : Nostis hominem, et quid locutus sit.

** II Kings 9:12

At ille responderunt : Falsum est, sed magis narra nobis. Qui ait eis : Hæc et hæc locutus est mihi, et ait : Hæc dicit Dominus : Unxi te regem super Israël.

** II Kings 9:13

Festinaverunt itaque, et unusquisque tollens pallium suum posuerunt sub pedibus ejus in similitudinem tribunalis, et cecinerunt tuba, atque dixerunt : Regnavit Jehu.  

** II Kings 9:14

Conjuravit ergo Jehu filius Josaphat filii Namsi contra Joram : porro Joram obsederat Ramoth Galaad, ipse et omnis Israël contra Hazaël regem Syriæ :

** II Kings 9:15

et reversus fuerat ut curaretur in Jezrahel propter vulnera, quia percusserant eum Syri præliantem contra Hazaël regem Syriæ. Dixitque Jehu : Si placet vobis, nemo egrediatur profugus de civitate, ne vadat, et nuntiet in Jezrahel.

** II Kings 9:16

Et ascendit, et profectus est in Jezrahel : Joram enim ægrotabat ibi, et Ochozias rex Juda descenderat ad visitandum Joram.

** II Kings 9:17

Igitur speculator qui stabat super turrim Jezrahel, vidit globum Jehu venientis, et ait : Video ego globum. Dixitque Joram : Tolle currum, et mitte in occursum eorum, et dicat vadens : Rectene sunt omnia ?

** II Kings 9:18

Abiit ergo qui ascenderat currum, in occursum ejus, et ait : Hæc dicit rex : Pacatane sunt omnia ? Dixitque Jehu : Quid tibi et paci ? transi, et sequere me. Nuntiavit quoque speculator, dicens : Venit nuntius ad eos, et non revertitur.

** II Kings 9:19

Misit etiam currum equorum secundum : venitque ad eos, et ait : Hæc dicit rex : Numquid pax est ? Et ait Jehu : Quid tibi et paci ? transi, et sequere me.

** II Kings 9:20

Nuntiavit autem speculator, dicens : Venit usque ad eos, et non revertitur : est autem incessus quasi incessus Jehu filii Namsi, præceps enim graditur.

** II Kings 9:21

Et ait Joram : Junge currum. Junxeruntque currum ejus, et egressus est Joram rex Israël, et Ochozias rex Juda, singuli in curribus suis, egressique sunt in occursum Jehu, et invenerunt eum in agro Naboth Jezrahelitæ.

** II Kings 9:22

Cumque vidisset Joram Jehu, dixit : Pax est, Jehu ? At ille respondit : Quæ pax ? adhuc fornicationes Jezabel matris tuæ, et veneficia ejus multa, vigent.

** II Kings 9:23

Convertit autem Joram manum suam, et fugiens ait ad Ochoziam : Insidiæ, Ochozia.

** II Kings 9:24

Porro Jehu tetendit arcum manu, et percussit Joram inter scapulas : et egressa est sagitta per cor ejus, statimque corruit in curru suo.

** II Kings 9:25

Dixitque Jehu ad Badacer ducem : Tolle, projice eum in agro Naboth Jezrahelitæ : memini enim quando ego et tu sedentes in curru sequebamur Achab patrem hujus, quod Dominus onus hoc levaverit super eum, dicens :

** II Kings 9:26

Si non pro sanguine Naboth, et pro sanguine filiorum ejus, quem vidi heri, ait Dominus, reddam tibi in agro isto, dicit Dominus. Nunc ergo tolle, et projice eum in agrum juxta verbum Domini.  

** II Kings 9:27

Ochozias autem rex Juda videns hoc, fugit per viam domus horti : persecutusque est eum Jehu, et ait : Etiam hunc percutite in curru suo. Et percusserunt eum in ascensu Gaver, qui est juxta Jeblaam : qui fugit in Mageddo, et mortuus est ibi.

** II Kings 9:28

Et imposuerunt eum servi ejus super currum suum, et tulerunt in Jerusalem : sepelieruntque eum in sepulchro cum patribus suis in civitate David.  

** II Kings 9:29

Anno undecimo Joram filii Achab, regnavit Ochozias super Judam,

** II Kings 9:30

venitque Jehu in Jezrahel. Porro Jezabel, introitu ejus audito, depinxit oculos suos stibio, et ornavit caput suum, et respexit per fenestram

** II Kings 9:31

ingredientem Jehu per portam, et ait : Numquid pax potest esse Zambri, qui interfecit dominum suum ?

** II Kings 9:32

Levavitque Jehu faciem suam ad fenestram, et ait : Quæ est ista ? et inclinaverunt se ad eum duo vel tres eunuchi.

** II Kings 9:33

At ille dixit eis : Præcipitate eam deorsum : et præcipitaverunt eam, aspersusque est sanguine paries, et equorum ungulæ conculcaverunt eam.

** II Kings 9:34

Cumque introgressus esset ut comederet biberetque, ait : Ite, et videte maledictam illam, et sepelite eam : quia filia regis est.

** II Kings 9:35

Cumque issent ut sepelirent eam, non invenerunt nisi calvariam, et pedes, et summas manus.

** II Kings 9:36

Reversique nuntiaverunt ei. Et ait Jehu : Sermo Domini est, quem locutus est per servum suum Eliam Thesbiten, dicens : In agro Jezrahel comedent canes carnes Jezabel,

** II Kings 9:37

et erunt carnes Jezabel sicut stercus super faciem terræ in agro Jezrahel, ita ut prætereuntes dicant : Hæccine est illa Jezabel ?   

* II Kings 10

** II Kings 10:1

Erant autem Achab septuaginta filii in Samaria : scripsit ergo Jehu litteras, et misit in Samariam, ad optimates civitatis, et ad majores natu, et ad nutritios Achab, dicens :

** II Kings 10:2

Statim ut acceperitis litteras has, qui habetis filios domini vestri, et currus, et equos, et civitates firmas, et arma,

** II Kings 10:3

eligite meliorem, et eum qui vobis placuerit de filiis domini vestri, et eum ponite super solium patris sui, et pugnate pro domo domini vestri.

** II Kings 10:4

Timuerunt illi vehementer, et dixerunt : Ecce duo reges non potuerunt stare coram eo, et quomodo nos valebimus resistere ?

** II Kings 10:5

Miserunt ergo præpositi domus, et præfecti civitatis, et majores natu, et nutritii, ad Jehu, dicentes : Servi tui sumus : quæcumque jusseris faciemus, nec constituemus nobis regem : quæcumque tibi placent, fac.

** II Kings 10:6

Rescripsit autem eis litteras secundo, dicens : Si mei estis, et obeditis mihi, tollite capita filiorum domini vestri, et venite ad me hac eadem hora cras in Jezrahel. Porro filii regis, septuaginta viri, apud optimates civitates nutriebantur.

** II Kings 10:7

Cumque venissent litteras ad eos, tulerunt filios regis, et occiderunt septuaginta viros, et posuerunt capita eorum in cophinis, et miserunt ad eum in Jezrahel.

** II Kings 10:8

Venit autem nuntius, et indicavit ei, dicens : Attulerunt capita filiorum regis. Qui respondit : Ponite ea ad duos acervos juxta introitum portæ usque mane.

** II Kings 10:9

Cumque diluxisset, egressus est, et stans dixit ad omnem populum : Justi estis : si ego conjuravi contra dominum meum et interfeci eum, quis percussit omnes hos ?

** II Kings 10:10

videte ergo nunc quoniam non cecidit de sermonibus Domini in terram, quos locutus est Dominus super domum Achab : et Dominus fecit quod locutus est in manu servi sui Eliæ.

** II Kings 10:11

Percussit igitur Jehu omnes qui reliqui erant de domo Achab in Jezrahel, et universos optimates ejus, et notos, et sacerdotes, donec non remanerent ex eo reliquiæ.  

** II Kings 10:12

Et surrexit, et venit in Samariam : cumque venisset ad Cameram pastorum in via,

** II Kings 10:13

invenit fratres Ochoziæ regis Juda : dixitque ad eos : Quinam estis vos ? Qui responderunt : Fratres Ochoziæ sumus, et descendimus ad salutandos filios regis, et filios reginæ.

** II Kings 10:14

Qui ait : Comprehendite eos vivos. Quos cum comprehendissent vivos, jugulaverunt eos in cisterna juxta Cameram, quadraginta duos viros : et non reliquit ex eis quemquam.

** II Kings 10:15

Cumque abiisset inde, invenit Jonadab filium Rechab in occursum sibi, et benedixit ei. Et ait ad eum : Numquid est cor tuum rectum, sicut cor meum cum corde tuo ? Et ait Jonadab : Est. Si est, inquit, da manum tuam. Qui dedit ei manum suam. At ille levavit eum ad se in currum :

** II Kings 10:16

dixitque ad eum : Veni mecum, et vide zelum meum pro Domino. Et impositum in curru suo

** II Kings 10:17

duxit in Samariam. Et percussit omnes qui reliqui fuerant de Achab in Samaria usque ad unum, juxta verbum Domini quod locutus est per Eliam.  

** II Kings 10:18

Congregavit ergo Jehu omnem populum, et dixit ad eos : Achab coluit Baal parum, ego autem colam eum amplius.

** II Kings 10:19

Nunc igitur omnes prophetas Baal, et universos servos ejus, et cunctos sacerdotes ipsius vocate ad me : nullus sit qui non veniat : sacrificium enim grande est mihi Baal : quicumque defuerit, non vivet. Porro Jehu faciebat hoc insidiose, ut disperderet cultores Baal.

** II Kings 10:20

Et dixit : Sanctificate diem solemnem Baal. Vocavitque,

** II Kings 10:21

et misit in universos terminos Israël, et venerunt cuncti servi Baal : non fuit residuus ne unus quidem qui non veniret. Et ingressi sunt templum Baal : et repleta est domus Baal, a summo usque ad summum.

** II Kings 10:22

Dixitque his qui erant super vestes : Proferte vestimenta universis servis Baal. Et protulerunt eis vestes.

** II Kings 10:23

Ingressusque Jehu, et Jonadab filius Rechab, templum Baal, ait cultoribus Baal : Perquirite, et videte, ne quis forte vobiscum sit de servis Domini, sed ut sint servi Baal soli.

** II Kings 10:24

Ingressi sunt igitur ut facerent victimas et holocausta : Jehu autem præparaverat sibi foris octoginta viros, et dixerat eis : Quicumque fugerit de hominibus his, quos ego adduxero in manus vestras, anima ejus erit pro anima illius.

** II Kings 10:25

Factum est autem, cum completum esset holocaustum, præcepit Jehu militibus et ducibus suis : Ingredimini, et percutite eos : nullus evadat. Percusseruntque eos in ore gladii, et projecerunt milites et duces : et ierunt in civitatem templi Baal,

** II Kings 10:26

et protulerunt statuam de fano Baal, et combusserunt,

** II Kings 10:27

et comminuerunt eam. Destruxerunt quoque ædem Baal, et fecerunt pro ea latrinas usque in diem hanc.  

** II Kings 10:28

Delevit itaque Jehu Baal de Israël :

** II Kings 10:29

verumtamen a peccatis Jeroboam filii Nabat, qui peccare fecit Israël, non recessit, nec dereliquit vitulos aureos qui erant in Bethel et in Dan.

** II Kings 10:30

Dixit autem Dominus ad Jehu : Quia studiose egisti quod rectum erat, et placebat in oculis meis, et omnia quæ erant in corde meo fecisti contra domum Achab : filii tui usque ad quartam generationem sedebunt super thronum Israël.

** II Kings 10:31

Porro Jehu non custodivit ut ambularet in lege Domini Dei Israël in toto corde suo : non enim recessit a peccatis Jeroboam, qui peccare fecerat Israël.

** II Kings 10:32

In diebus illis cœpit Dominus tædere super Israël : percussitque eos Hazaël in universis finibus Israël,

** II Kings 10:33

a Jordane contra orientalem plagam, omnem terram Galaad, et Gad, et Ruben, et Manasse, ab Aroër, quæ est super torrentem Arnon, et Galaad, et Basan.

** II Kings 10:34

Reliqua autem verborum Jehu, et universa quæ fecit, et fortitudo ejus, nonne hæc scripta sunt in libro verborum dierum regum Israël ?

** II Kings 10:35

Et dormivit Jehu cum patribus suis, sepelieruntque eum in Samaria : et regnavit Joachaz filius ejus pro eo.

** II Kings 10:36

Dies autem quos regnavit Jehu super Israël, viginti et octo anni sunt in Samaria.   

* II Kings 11

** II Kings 11:1

Athalia vero mater Ochoziæ, videns mortuum filium suum, surrexit, et interfecit omne semen regium.

** II Kings 11:2

Tollens autem Josaba filia regis Joram, soror Ochoziæ, Joas filium Ochoziæ, furata est eum de medio filiorum regis qui interficiebantur, et nutricem ejus de triclinio : et abscondit eum a facie Athaliæ ut non interficeretur.

** II Kings 11:3

Eratque cum ea sex annis clam in domo Domini : porro Athalia regnavit super terram.  

** II Kings 11:4

Anno autem septimo misit Jojada, et assumens centuriones et milites, introduxit ad se in templum Domini, pepigitque cum eis fœdus : et adjurans eos in domo Domini, ostendit eis filium regis :

** II Kings 11:5

et præcepit illis, dicens : Iste est sermo, quem facere debetis :

** II Kings 11:6

tertia pars vestrum introëat sabbato, et observet excubias domus regis. Tertia autem pars sit ad portam Sur, et tertia pars sit ad portam quæ est post habitaculum scutariorum : et custodietis excubias domus Messa.

** II Kings 11:7

Duæ vero partes e vobis, omnes egredientes sabbato, custodiant excubias domus Domini circa regem.

** II Kings 11:8

Et vallabitis eum, habentes arma in manibus vestris : si quis autem ingressus fuerit septum templi, interficiatur : eritisque cum rege introëunte et egrediente.

** II Kings 11:9

Et fecerunt centuriones juxta omnia quæ præceperat eis Jojada sacerdos : et assumentes singuli viros suos qui ingrediebantur sabbatum, cum his qui egrediebantur sabbato, venerunt ad Jojadam sacerdotem.

** II Kings 11:10

Qui dedit eis hastas et arma regis David, quæ erant in domo Domini.

** II Kings 11:11

Et steterunt singuli habentes arma in manu sua, a parte templi dextera usque ad partem sinistram altaris et ædis, circum regem.

** II Kings 11:12

Produxitque filium regis, et posuit super eum diadema et testimonium : feceruntque eum regem, et unxerunt : et plaudentes manu, dixerunt : Vivat rex.

** II Kings 11:13

Audivit autem Athalia vocem populi currentis : et ingressa ad turbas in templum Domini,

** II Kings 11:14

vidit regem stantem super tribunal juxta morem, et cantores, et tubas prope eum, omnemque populum terræ lætantem, et canentem tubis : et scidit vestimenta sua, clamavitque : Conjuratio, conjuratio.

** II Kings 11:15

Præcepit autem Jojada centurionibus qui erant super exercitum, et ait eis : Educite eam extra septa templi, et quicumque eam secutus fuerit, feriatur gladio. Dixerat enim sacerdos : Non occidatur in templo Domini.

** II Kings 11:16

Imposueruntque ei manus, et impegerunt eam per viam introitus equorum, juxta palatium, et interfecta est ibi.

** II Kings 11:17

Pepigit ergo Jojada fœdus inter Dominum, et inter regem, et inter populum, ut esset populus Domini : et inter regem et populum.

** II Kings 11:18

Ingressusque est omnis populus terræ templum Baal, et destruxerunt aras ejus, et imagines contriverunt valide : Mathan quoque sacerdotem Baal occiderunt coram altari. Et posuit sacerdos custodias in domo Domini.

** II Kings 11:19

Tulitque centuriones, et Cerethi et Phelethi legiones, et omnem populum terræ, deduxeruntque regem de domo Domini : et venerunt per viam portæ scutariorum in palatium, et sedit super thronum regum.

** II Kings 11:20

Lætatusque est omnis populus terræ, et civitas conquievit : Athalia autem occisa est gladio in domo regis.

** II Kings 11:21

Septemque annorum erat Joas, cum regnare cœpisset.   

* II Kings 12

** II Kings 12:1

Anno septimo Jehu, regnavit Joas : et quadraginta annis regnavit in Jerusalem. Nomen matris ejus Sebia de Bersabee.

** II Kings 12:2

Fecitque Joas rectum coram Domino cunctis diebus quibus docuit eum Jojada sacerdos.

** II Kings 12:3

Verumtamen excelsa non abstulit : adhuc enim populus immolabat, et adolebat in excelsis incensum.  

** II Kings 12:4

Dixitque Joas ad sacerdotes : Omnem pecuniam sanctorum, quæ illata fuerit in templum Domini a prætereuntibus, quæ offertur pro pretio animæ, et quam sponte et arbitrio cordis sui inferunt in templum Domini :

** II Kings 12:5

accipiant illam sacerdotes juxta ordinem suum, et instaurent sartatecta domus, si quid necessarium viderint instauratione.

** II Kings 12:6

Igitur usque ad vigesimum tertium annum regis Joas, non instauraverunt sacerdotes sartatecta templi.

** II Kings 12:7

Vocavitque rex Joas Jojadam pontificem et sacerdotes, dicens eis : Quare sartatecta non instauratis templi ? nolite ergo amplius accipere pecuniam juxta ordinem vestrum, sed ad instaurationem templi reddite eam.

** II Kings 12:8

Prohibitique sunt sacerdotes ultra accipere pecuniam a populo, et instaurare sartatecta domus.

** II Kings 12:9

Et tulit Jojada pontifex gazophylacium unum, aperuitque foramen desuper, et posuit illud juxta altare ad dexteram ingredientium domum Domini : mittebantque in eo sacerdotes qui custodiebant ostia, omnem pecuniam quæ deferebatur ad templum Domini.

** II Kings 12:10

Cumque viderent nimiam pecuniam esse in gazophylacio, ascendebat scriba regis, et pontifex, effundebantque et numerabant pecuniam quæ inveniebatur in domo Domini :

** II Kings 12:11

et dabant eam juxta numerum atque mensuram in manu eorum qui præerant cæmentariis domus Domini : qui impendebant eam in fabris lignorum et in cæmentariis, iis qui operabantur in domo Domini,

** II Kings 12:12

et sartatecta faciebant : et in iis qui cædebant saxa, et ut emerent ligna, et lapides, qui excidebantur, ita ut impleretur instauratio domus Domini in universis quæ indigebant expensa ad muniendam domum.

** II Kings 12:13

Verumtamen non fiebant ex eadem pecunia hydriæ templi Domini, et fuscinulæ, et thuribula, et tubæ, et omne vas aureum et argenteum, de pecunia quæ inferebatur in templum Domini.

** II Kings 12:14

Iis enim qui faciebant opus, dabatur ut instauraretur templum Domini :

** II Kings 12:15

et non fiebat ratio iis hominibus qui accipiebant pecuniam ut distribuerent eam artificibus, sed in fide tractabant eam.

** II Kings 12:16

Pecuniam vero pro delicto, et pecuniam pro peccatis non inferebant in templum Domini, quia sacerdotum erat.  

** II Kings 12:17

Tunc ascendit Hazaël rex Syriæ, et pugnabat contra Geth, cepitque eam : et direxit faciem suam ut ascenderet in Jerusalem.

** II Kings 12:18

Quam ob rem tulit Joas rex Juda omnia sanctificata quæ consecraverant Josaphat, et Joram, et Ochozias, patres ejus reges Juda, et quæ ipse obtulerat : et universum argentum quod inveniri potuit in thesauris templi Domini et in palatio regis : misitque Hazaëli regi Syriæ, et recessit ab Jerusalem.

** II Kings 12:19

Reliqua autem sermonum Joas, et universa quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** II Kings 12:20

Surrexerunt autem servi ejus, et conjuraverunt inter se, percusseruntque Joas in domo Mello in descensu Sella.

** II Kings 12:21

Josachar namque filius Semaath, et Jozabad filius Somer servi ejus, percusserunt eum, et mortuus est : et sepelierunt eum cum patribus suis in civitate David : regnavitque Amasias filius ejus pro eo.   

* II Kings 13

** II Kings 13:1

Anno vigesimo tertio Joas filii Ochoziæ regis Juda, regnavit Joachaz filius Jehu super Israël in Samaria decem et septem annis.

** II Kings 13:2

Et fecit malum coram Domino, secutusque est peccata Jeroboam filii Nabat, qui peccare fecit Israël, et non declinavit ab eis.

** II Kings 13:3

Iratusque est furor Domini contra Israël, et tradidit eos in manu Hazaël regis Syriæ, et in manu Benadad filii Hazaël, cunctis diebus.

** II Kings 13:4

Deprecatus est autem Joachaz faciem Domini, et audivit eum Dominus : vidit enim angustiam Israël, quia attriverat eos rex Syriæ :

** II Kings 13:5

et dedit Dominus salvatorem Israëli, et liberatus est de manu regis Syriæ : habitaveruntque filii Israël in tabernaculis suis sicut heri et nudiustertius.

** II Kings 13:6

Verumtamen non recesserunt a peccatis domus Jeroboam, qui peccare fecit Israël, sed in ipsis ambulaverunt : siquidem et lucus permansit in Samaria.

** II Kings 13:7

Et non sunt derelicti Joachaz de populo nisi quinquaginta equites, et decem currus, et decem millia peditum : interfecerat enim eos rex Syriæ, et redegerat quasi pulverem in tritura areæ.

** II Kings 13:8

Reliqua autem sermonum Joachaz, et universa quæ fecit, et fortitudo ejus, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 13:9

Dormivitque Joachaz cum patribus suis, et sepelierunt eum in Samaria : regnavitque Joas filius ejus pro eo.

** II Kings 13:10

Anno trigesimo septimo Joas regis Juda, regnavit Joas filius Joachaz super Israël in Samaria sedecim annis.

** II Kings 13:11

Et fecit quod malum est in conspectu Domini : non declinavit ab omnibus peccatis Jeroboam filii Nabat, qui peccare fecit Israël, sed in ipsis ambulavit.

** II Kings 13:12

Reliqua autem sermonum Joas, et universa quæ fecit, et fortitudo ejus, quomodo pugnaverit contra Amasiam regem Juda, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 13:13

Et dormivit Joas cum patribus suis : Jeroboam autem sedit super solium ejus. Porro Joas sepultus est in Samaria cum regibus Israël.  

** II Kings 13:14

Eliseus autem ægrotabat infirmitate, qua et mortuus est : descenditque ad eum Joas rex Israël, et flebat coram eo, dicebatque : Pater mi, pater mi, currus Israël et auriga ejus.

** II Kings 13:15

Et ait illi Eliseus : Affer arcum et sagittas. Cumque attulisset ad eum arcum et sagittas,

** II Kings 13:16

dixit ad regem Israël : Pone manum tuam super arcum. Et cum posuisset ille manum suam, superposuit Eliseus manus suas manibus regis,

** II Kings 13:17

et ait : Aperi fenestram orientalem. Cumque aperuisset, dixit Eliseus : Jace sagittam. Et jecit. Et ait Eliseus : Sagitta salutis Domini, et sagitta salutis contra Syriam : percutiesque Syriam in Aphec, donec consumas eam.

** II Kings 13:18

Et ait : Tolle sagittas. Qui cum tulisset, rursum dixit ei : Percute jaculo terram. Et cum percussisset tribus vicibus, et stetisset,

** II Kings 13:19

iratus est vir Dei contra eum, et ait : Si percussisses quinquies, aut sexies, sive septies, percussisses Syriam usque ad consumptionem : nunc autem tribus vicibus percuties eam.

** II Kings 13:20

Mortuus est ergo Eliseus, et sepelierunt eum. Latrunculi autem de Moab venerunt in terram in ipso anno.

** II Kings 13:21

Quidam autem sepelientes hominem, viderunt latrunculos, et projecerunt cadaver in sepulchro Elisei. Quod cum tetigisset ossa Elisei, revixit homo, et stetit super pedes suos.  

** II Kings 13:22

Igitur Hazaël rex Syriæ afflixit Israël cunctis diebus Joachaz :

** II Kings 13:23

et misertus est Dominus eorum, et reversus est ad eos propter pactum suum, quod habebat cum Abraham, et Isaac, et Jacob : et noluit disperdere eos, neque projicere penitus usque in præsens tempus.

** II Kings 13:24

Mortuus est autem Hazaël rex Syriæ, et regnavit Benadad filius ejus pro eo.

** II Kings 13:25

Porro Joas filius Joachaz tulit urbes de manu Benadad filii Hazaël, quas tulerat de manu Joachaz patris sui jure prælii : tribus vicibus percussit eum Joas, et reddidit civitates Israël.   

* II Kings 14

** II Kings 14:1

In anno secundo Joas filii Joachaz regis Israël, regnavit Amasias filius Joas regis Juda.

** II Kings 14:2

Viginti quinque annorum erat cum regnare cœpisset : viginti autem et novem annis regnavit in Jerusalem. Nomen matris ejus Joadan de Jerusalem.

** II Kings 14:3

Et fecit rectum coram Domino, verumtamen non ut David pater ejus. Juxta omnia quæ fecit Joas pater suus, fecit :

** II Kings 14:4

nisi hoc tantum, quod excelsa non abstulit : adhuc enim populus immolabat, et adolebat incensum in excelsis.

** II Kings 14:5

Cumque obtinuisset regnum, percussit servos suos, qui interfecerant regem patrem suum :

** II Kings 14:6

filios autem eorum qui occiderant, non occidit, juxta quod scriptum est in libro legis Moysi, sicut præcepit Dominus, dicens : Non morientur patres pro filiis, neque filii morientur pro patribus : sed unusquisque in peccato suo morietur.

** II Kings 14:7

Ipse percussit Edom in valle Salinarum decem millia, et apprehendit petram in prælio, vocavitque nomen ejus Jectehel usque in præsentem diem.  

** II Kings 14:8

Tunc misit Amasias nuntios ad Joas filium Joachaz filii Jehu regis Israël, dicens : Veni, et videamus nos.

** II Kings 14:9

Remisitque Joas rex Israël ad Amasiam regem Juda, dicens : Carduus Libani misit ad cedrum quæ est in Libano, dicens : Da filiam tuam filio meo uxorem. Transieruntque bestiæ saltus quæ sunt in Libano, et conculcaverunt carduum.

** II Kings 14:10

Percutiens invaluisti super Edom, et sublevavit te cor tuum : contentus esto gloria, et sede in domo tua : quare provocas malum, ut cadas tu et Judas tecum ?

** II Kings 14:11

Et non acquievit Amasias. Ascenditque Joas rex Israël, et viderunt se, ipse et Amasias rex Juda, in Bethsames oppido Judæ.

** II Kings 14:12

Percussusque est Juda coram Israël, et fugerunt unusquisque in tabernacula sua.

** II Kings 14:13

Amasiam vero regem Juda, filium Joas filii Ochoziæ, cepit Joas rex Israël in Bethsames, et adduxit eum in Jerusalem : et interrupit murum Jerusalem, a porta Ephraim usque ad portam anguli, quadringentis cubitis.

** II Kings 14:14

Tulitque omne aurum et argentum, et universa vasa quæ inventa sunt in domo Domini et in thesauris regis, et obsides, et reversus est in Samariam.  

** II Kings 14:15

Reliqua autem verborum Joas quæ fecit, et fortitudo ejus qua pugnavit contra Amasiam regem Juda, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 14:16

Dormivitque Joas cum patribus suis, et sepultus est in Samaria cum regibus Israël, et regnavit Jeroboam filius ejus pro eo.

** II Kings 14:17

Vixit autem Amasias filius Joas rex Juda postquam mortuus est Joas filius Joachaz regis Israël, quindecim annis.

** II Kings 14:18

Reliqua autem sermonum Amasiæ, nonne hæc scripta sunt in libro sermonum dierum regum Juda ?

** II Kings 14:19

Factaque est contra eum conjuratio in Jerusalem : at ille fugit in Lachis. Miseruntque post eum in Lachis, et interfecerunt eum ibi :

** II Kings 14:20

et asportaverunt in equis, sepultusque est in Jerusalem cum patribus suis in civitate David.

** II Kings 14:21

Tulit autem universus populus Judæ Azariam annos natum sedecim, et constituerunt eum regem pro patre ejus Amasia.

** II Kings 14:22

Ipse ædificavit Ælath, et restituit eam Judæ, postquam dormivit rex cum patribus suis.  

** II Kings 14:23

Anno quintodecimo Amasiæ filii Joas regis Juda, regnavit Jeroboam filius Joas regis Israël in Samaria, quadraginta et uno anno.

** II Kings 14:24

Et fecit quod malum est coram Domino : non recessit ab omnibus peccatis Jeroboam filii Nabat, qui peccare fecit Israël.

** II Kings 14:25

Ipse restituit terminos Israël ab introitu Emath usque ad mare solitudinis, juxta sermonem Domini Dei Israël quem locutus est per servum suum Jonam filium Amathi prophetam, qui erat de Geth, quæ est in Opher.

** II Kings 14:26

Vidit enim Dominus afflictionem Israël amaram nimis, et quod consumpti essent usque ad clausos carcere et extremos, et non esset qui auxiliaretur Israëli.

** II Kings 14:27

Nec locutus est Dominus ut deleret nomen Israël de sub cælo, sed salvavit eos in manu Jeroboam filii Joas.

** II Kings 14:28

Reliqua autem sermonum Jeroboam, et universa quæ fecit, et fortitudo ejus qua præliatus est, et quomodo restituit Damascum et Emath Judæ in Israël, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 14:29

Dormivitque Jeroboam cum patribus suis regibus Israël, et regnavit Zacharias filius ejus pro eo.   

* II Kings 15

** II Kings 15:1

Anno vigesimo septimo Jeroboam regis Israël, regnavit Azarias filius Amasiæ regis Juda.

** II Kings 15:2

Sedecim annorum erat cum regnare cœpisset, et quinquaginta duobus annis regnavit in Jerusalem : nomen matris ejus Jechelia de Jerusalem.

** II Kings 15:3

Fecitque quod erat placitum coram Domino, juxta omnia quæ fecit Amasias pater ejus.

** II Kings 15:4

Verumtamen excelsa non est demolitus : adhuc populus sacrificabat, et adolebat incensum in excelsis.

** II Kings 15:5

Percussit autem Dominus regem, et fuit leprosus usque in diem mortis suæ, et habitabat in domo libera seorsum : Joatham vero filius regis gubernabat palatium, et judicabit populum terræ.

** II Kings 15:6

Reliqua autem sermonum Azariæ, et universa quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** II Kings 15:7

Et dormivit Azarias cum patribus suis : sepelieruntque eum cum majoribus suis in civitate David, et regnavit Joatham filius ejus pro eo.  

** II Kings 15:8

Anno trigesimo octavo Azariæ regis Juda, regnavit Zacharias filius Jeroboam super Israël in Samaria sex mensibus.

** II Kings 15:9

Et fecit quod malum est coram Domino, sicut fecerant patres ejus : non recessit a peccatis Jeroboam filii Nabat, qui peccare fecit Israël.

** II Kings 15:10

Conjuravit autem contra eum Sellum filius Jabes : percussitque eum palam, et interfecit, regnavitque pro eo.

** II Kings 15:11

Reliqua autem verborum Zachariæ, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 15:12

Iste est sermo Domini quem locutus est ad Jehu, dicens : Filii tui usque ad quartam generationem sedebunt super thronum Israël. Factumque est ita.  

** II Kings 15:13

Sellum filius Jabes regnavit trigesimo novo anno Azariæ regis Juda : regnavit autem uno mense in Samaria.

** II Kings 15:14

Et ascendit Manahem filius Gadi de Thersa, venitque in Samariam, et percussit Sellum filium Jabes in Samaria, et interfecit eum : regnavitque pro eo.

** II Kings 15:15

Reliqua autem verborum Sellum, et conjuratio ejus, per quam tetendit insidias, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 15:16

Tunc percussit Manahem Thapsam, et omnes qui erant in ea, et terminos ejus de Thersa : noluerant enim aperire ei : et interfecit omnes prægnantes ejus, et scidit eas.  

** II Kings 15:17

Anno trigesimo nono Azariæ regis Juda, regnavit Manahem filius Gadi super Israël decem annis in Samaria.

** II Kings 15:18

Fecitque quod erat malum coram Domino : non recessit a peccatis Jeroboam filii Nabat, qui peccare fecit Israël, cunctis diebus ejus.

** II Kings 15:19

Veniebat Phul rex Assyriorum in terram, et dabat Manahem Phul mille talenta argenti, ut esset ei in auxilium, et firmaret regnum ejus.

** II Kings 15:20

Indixitque Manahem argentum super Israël cunctis potentibus et divitibus, ut daret regi Assyriorum quinquaginta siclos argenti per singulos : reversusque est rex Assyriorum, et non est moratus in terra.

** II Kings 15:21

Reliqua autem sermonum Manahem, et universa quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?

** II Kings 15:22

Et dormivit Manahem cum patribus suis : regnavitque Phaceia filius ejus pro eo.  

** II Kings 15:23

Anno quinquagesimo Azariæ regis Juda, regnavit Phaceia filius Manahem super Israël in Samaria biennio.

** II Kings 15:24

Et fecit quod erat malum coram Domino : non recessit a peccatis Jeroboam filii Nabat, qui peccare fecit Israël.

** II Kings 15:25

Conjuravit autem adversus eum Phacee filius Romeliæ, dux ejus, et percussit eum in Samaria in turre domus regiæ, juxta Argob et juxta Arie, et cum eo quinquaginta viros de filiis Galaaditarum : et interfecit eum, regnavitque pro eo.

** II Kings 15:26

Reliqua autem sermonum Phaceia, et universa quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?  

** II Kings 15:27

Anno quinquagesimo secundo Azariæ regis Juda, regnavit Phacee filius Romeliæ super Israël in Samaria viginti annis.

** II Kings 15:28

Et fecit quod erat malum coram Domino : non recessit a peccatis Jeroboam filii Nabat, qui peccare fecit Israël.

** II Kings 15:29

In diebus Phacee regis Israël, venit Theglathphalasar rex Assur, et cepit Ajon, et Abel Domum, Maacha et Janoë, et Cedes, et Asor, et Galaad, et Galilæam, et universam terram Nephthali : et transtulit eos in Assyrios.

** II Kings 15:30

Conjuravit autem et tetendit insidias Osee filius Ela contra Phacee filium Romeliæ, et percussit eum, et interfecit : regnavitque pro eo vigesimo anno Joatham filii Oziæ.

** II Kings 15:31

Reliqua autem sermonum Phacee, et universa quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Israël ?  

** II Kings 15:32

Anno secundo Phacee filii Romeliæ regis Israël, regnavit Joatham filius Oziæ regis Juda.

** II Kings 15:33

Viginti quinque annorum erat cum regnare cœpisset, et sedecim annis regnavit in Jerusalem : nomen matris ejus Jerusa filia Sadoc.

** II Kings 15:34

Fecitque quod erat placitum coram Domino : juxta omnia quæ fecerat Ozias pater suus, operatus est.

** II Kings 15:35

Verumtamen excelsa non abstulit : adhuc populus immolabat, et adolebat incensum in excelsis. Ipse ædificavit portam domus Domini sublimissimam.

** II Kings 15:36

Reliqua autem sermonum Joatham, et universa quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** II Kings 15:37

In diebus illis cœpit Dominus mittere in Judam Rasin regem Syriæ, et Phacee filium Romeliæ.

** II Kings 15:38

Et dormivit Joatham cum patribus suis, sepultusque est cum eis in civitate David patris sui : et regnavit Achaz filius ejus pro eo.   

* II Kings 16

** II Kings 16:1

Anno decimoseptimo Phacee filii Romeliæ, regnavit Achaz filius Joatham regis Juda.

** II Kings 16:2

Viginti annorum erat Achaz cum regnare cœpisset, et sedecim annis regnavit in Jerusalem. Non fecit quod erat placitum in conspectu Domini Dei sui sicut David pater ejus,

** II Kings 16:3

sed ambulavit in via regum Israël : insuper et filium suum consecravit, transferens per ignem secundum idola gentium, quæ dissipavit Dominus coram filiis Israël.

** II Kings 16:4

Immolabat quoque victimas, et adolebat incensum in excelsis, et in collibus, et sub omni ligno frondoso.  

** II Kings 16:5

Tunc ascendit Rasin rex Syriæ, et Phacee filius Romeliæ rex Israël, in Jerusalem ad præliandum : cumque obsiderent Achaz, non valuerunt superare eum.

** II Kings 16:6

In tempore illo restituit Rasin rex Syriæ, Ailam Syriæ, et ejecit Judæos de Aila : et Idumæi venerunt in Ailam, et habitaverunt ibi usque in diem hanc.  

** II Kings 16:7

Misit autem Achaz nuntios ad Theglathphalasar regem Assyriorum, dicens : Servus tuus, et filius tuus ego sum : ascende, et salvum me fac de manu regis Syriæ, et de manu regis Israël, qui consurrexerunt adversum me.

** II Kings 16:8

Et cum collegisset argentum et aurum quod inveniri potuit in domo Domini et in thesauris regis, misit regi Assyriorum munera.

** II Kings 16:9

Qui et acquievit voluntati ejus : ascendit enim rex Assyriorum in Damascum, et vastavit eam, et transtulit habitatores ejus Cyrenen : Rasin autem interfecit.

** II Kings 16:10

Perrexitque rex Achaz in occursum Theglathphalasar regis Assyriorum in Damascum : cumque vidisset altare Damasci, misit rex Achaz ad Uriam sacerdotem exemplar ejus, et similitudinem juxta omne opus ejus.

** II Kings 16:11

Exstruxitque Urias sacerdos altare : juxta omnia quæ præceperat rex Achaz de Damasco, ita fecit sacerdos Urias donec veniret rex Achaz de Damasco.

** II Kings 16:12

Cumque venisset rex de Damasco, vidit altare, et veneratus est illud : ascenditque et immolavit holocausta et sacrificium suum,

** II Kings 16:13

et libavit libamina, et fudit sanguinem pacificorum quæ obtulerat super altare.

** II Kings 16:14

Porro altare æreum quod erat coram Domino, transtulit de facie templi, et de loco altaris, et de loco templi Domini : posuitque illud ex latere altaris ad aquilonem.

** II Kings 16:15

Præcepit quoque rex Achaz Uriæ sacerdoti, dicens : Super altare majus offer holocaustum matutinum, et sacrificium vespertinum, et holocaustum regis, et sacrificium ejus, et holocaustum universi populi terræ, et sacrificia eorum, et libamina eorum : et omnem sanguinem holocausti, et universum sanguinem victimæ super illud effundes : altare vero æreum erit paratum ad voluntatem meam.

** II Kings 16:16

Fecit igitur Urias sacerdos juxta omnia quæ præceperat rex Achaz.

** II Kings 16:17

Tulit autem rex Achaz cælatas bases, et luterem qui erat desuper : et mare deposuit de bobus æreis qui sustentabant illud, et posuit super pavimentum stratum lapide.

** II Kings 16:18

Musach quoque sabbati quod ædificaverat in templo : et ingressum regis exterius convertit in templum Domini propter regem Assyriorum.

** II Kings 16:19

Reliqua autem verborum Achaz quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Juda ?

** II Kings 16:20

Dormivitque Achaz cum patribus suis, et sepultus est cum eis in civitate David : et regnavit Ezechias filius ejus pro eo.   

* II Kings 17

** II Kings 17:1

Anno duodecimo Achaz regis Juda, regnavit Osee filius Ela in Samaria super Israël novem annis.

** II Kings 17:2

Fecitque malum coram Domino, sed non sicut reges Israël qui ante eum fuerant.

** II Kings 17:3

Contra hunc ascendit Salmanasar rex Assyriorum, et factus est ei Osee servus, reddebatque illi tributa.

** II Kings 17:4

Cumque deprehendisset rex Assyriorum Osee, quod rebellare nitens misisset nuntios ad Sua regem Ægypti ne præstaret tributa regi Assyriorum sicut singulis annis solitus erat, obsedit eum, et vinctum misit in carcerem.

** II Kings 17:5

Pervagatusque est omnem terram : et ascendens Samariam, obsedit eam tribus annis.

** II Kings 17:6

Anno autem nono Osee, cepit rex Assyriorum Samariam, et transtulit Israël in Assyrios : posuitque eos in Hala et in Habor juxta fluvium Gozan, in civitatibus Medorum.  

** II Kings 17:7

Factum est enim, cum peccassent filii Israël Domino Deo suo, qui eduxerat eos de terra Ægypti, de manu Pharaonis regis Ægypti, coluerunt deos alienos.

** II Kings 17:8

Et ambulaverunt juxta ritum gentium quas consumpserat Dominus in conspectu filiorum Israël et regum Israël, quia similiter fecerant.

** II Kings 17:9

Et offenderunt filii Israël verbis non rectis Dominum Deum suum : et ædificaverunt sibi excelsa in cunctis urbibus suis, a turre custodum usque ad civitatem munitam.

** II Kings 17:10

Feceruntque sibi statuas et lucos in omni colle sublimi, et subter omne lignum nemorosum :

** II Kings 17:11

et adolebant ibi incensum super aras in morem gentium quas transtulerat Dominus a facie eorum : feceruntque verba pessima irritantes Dominum.

** II Kings 17:12

Et coluerunt immunditias de quibus præcepit eis Dominus ne facerent verbum hoc.

** II Kings 17:13

Et testificatus est Dominus in Israël et in Juda per manum omnium prophetarum et videntium, dicens : Revertimini a viis vestris pessimis, et custodite præcepta mea et cæremonias, juxta omnem legem quam præcepi patribus vestris, et sicut misi ad vos in manu servorum meorum prophetarum.

** II Kings 17:14

Qui non audierunt, sed induraverunt cervicem suam juxta cervicem patrum suorum, qui noluerunt obedire Domino Deo suo.

** II Kings 17:15

Et abjecerunt legitima ejus, et pactum quod pepigit cum patribus eorum, et testificationes quibus contestatus est eos : secutique sunt vanitates, et vane egerunt : et secuti sunt gentes quæ erant per circuitum eorum, super quibus præceperat Dominus eis ut non facerent sicut et illæ faciebant.

** II Kings 17:16

Et dereliquerunt omnia præcepta Domini Dei sui : feceruntque sibi conflatiles duos vitulos, et lucos, et adoraverunt universam militiam cæli : servieruntque Baal,

** II Kings 17:17

et consecraverunt filios suos et filias suas per ignem : et divinationibus inserviebant, et auguriis : et tradiderunt se ut facerent malum coram Domino, ut irritarent eum.

** II Kings 17:18

Iratusque est Dominus vehementer Israëli, et abstulit eos a conspectu suo, et non remansit nisi tribus Juda tantummodo.

** II Kings 17:19

Sed nec ipse Juda custodivit mandata Domini Dei sui : verum ambulavit in erroribus Israël, quos operatus fuerat.

** II Kings 17:20

Projecitque Dominus omne semen Israël, et afflixit eos, et tradidit eos in manu diripientium, donec projiceret eos a facie sua :

** II Kings 17:21

ex eo jam tempore quo scissus est Israël a domo David, et constituerunt sibi regem Jeroboam filium Nabat : separavit enim Jeroboam Israël a Domino, et peccare eos fecit peccatum magnum.

** II Kings 17:22

Et ambulaverunt filii Israël in universis peccatis Jeroboam quæ fecerat : et non recesserunt ab eis,

** II Kings 17:23

usquequo Dominus auferret Israël a facie sua, sicut locutus fuerat in manu omnium servorum suorum prophetarum : translatusque est Israël de terra sua in Assyrios, usque in diem hanc.  

** II Kings 17:24

Adduxit autem rex Assyriorum de Babylone, et de Cutha, et de Avah, et de Emath, et de Sepharvaim : et collocavit eos in civitatibus Samariæ pro filiis Israël : qui possederunt Samariam, et habitaverunt in urbibus ejus.

** II Kings 17:25

Cumque ibi habitare cœpissent, non timebant Dominum : et immisit in eos Dominus leones, qui interficiebant eos.

** II Kings 17:26

Nuntiatumque est regi Assyriorum, et dictum : Gentes quas transtulisti, et habitare fecisti in civitatibus Samariæ, ignorant legitima Dei terræ : et immisit in eos Dominus leones, et ecce interficiunt eos, eo quod ignorent ritum Dei terræ.

** II Kings 17:27

Præcepit autem rex Assyriorum, dicens : Ducite illuc unum de sacerdotibus quos inde captivos adduxistis, et vadat, et habitet cum eis : et doceat eos legitima Dei terræ.

** II Kings 17:28

Igitur cum venisset unus de sacerdotibus his qui captivi ducti fuerant de Samaria, habitavit in Bethel, et docebat eos quomodo colerent Dominum.

** II Kings 17:29

Et unaquæque gens fabricata est deum suum : posueruntque eos in fanis excelsis quæ fecerant Samaritæ, gens et gens in urbibus suis, in quibus habitabat.

** II Kings 17:30

Viri enim Babylonii fecerunt Sochothbenoth : viri autem Cuthæi fecerunt Nergel : et viri de Emath fecerunt Asima.

** II Kings 17:31

Porro Hevæi fecerunt Nebahaz et Tharthac. Hi autem qui erant de Sepharvaim, comburebant filios suos igni, Adramelech et Anamelech diis Sepharvaim,

** II Kings 17:32

et nihilominus colebant Dominum. Fecerunt autem sibi de novissimis sacerdotes excelsorum, et ponebant eos in fanis sublimibus.

** II Kings 17:33

Et cum Dominum colerent, diis quoque suis serviebant juxta consuetudinem gentium, de quibus translati fuerant Samariam.

** II Kings 17:34

Usque in præsentem diem morem sequuntur antiquum : non timent Dominum, neque custodiunt cæremonias ejus, judicia, et legem, et mandatum, quod præceperat Dominus filiis Jacob, quem cognominavit Israël :

** II Kings 17:35

et percusserat cum eis pactum, et mandaverat eis, dicens : Nolite timere deos alienos, et non adoretis eos, neque colatis eos, et non immoletis eis :

** II Kings 17:36

sed Dominum Deum vestrum, qui eduxit vos de terra Ægypti in fortitudine magna et in brachio extento, ipsum timete, et illum adorate, et ipsi immolate.

** II Kings 17:37

Cæremonias quoque, et judicia, et legem, et mandatum, quod scripsit vobis, custodite ut faciatis cunctis diebus : et non timeatis deos alienos.

** II Kings 17:38

Et pactum quod percussit vobiscum, nolite oblivisci : nec colatis deos alienos,

** II Kings 17:39

sed Dominum Deum vestrum timete, et ipse eruet vos de manu omnium inimicorum vestrorum.

** II Kings 17:40

Illi vero non audierunt, sed juxta consuetudinem suam pristinam perpetrabant.

** II Kings 17:41

Fuerunt igitur gentes istæ timentes quidem Dominum, sed nihilominus et idolis suis servientes : nam et filii eorum, et nepotes, sicut fecerunt patres sui, ita faciunt usque in præsentem diem.   

* II Kings 18

** II Kings 18:1

Anno tertio Osee filii Ela regis Israël, regnavit Ezechias filius Achaz regis Juda.

** II Kings 18:2

Viginti quinque annorum erat cum regnare cœpisset, et viginti novem annis regnavit in Jerusalem : nomen matris ejus Abi filia Zachariæ.

** II Kings 18:3

Fecitque quod erat bonum coram Domino, juxta omnia quæ fecerat David pater ejus.

** II Kings 18:4

Ipse dissipavit excelsa, et contrivit statuas, et succidit lucos, confregitque serpentem æneum quem fecerat Moyses : siquidem usque ad illud tempus filii Israël adolebant ei incensum : vocavitque nomen ejus Nohestan.

** II Kings 18:5

In Domino Deo Israël speravit : itaque post eum non fuit similis ei de cunctis regibus Juda, sed neque in his qui ante eum fuerunt :

** II Kings 18:6

et adhæsit Domino, et non recessit a vestigiis ejus, fecitque mandata ejus, quæ præceperat Dominus Moysi.

** II Kings 18:7

Unde et erat Dominus cum eo, et in cunctis ad quæ procedebat, sapienter se agebat. Rebellavit quoque contra regem Assyriorum, et non servivit ei.

** II Kings 18:8

Ipse percussit Philisthæos usque ad Gazam, et omnes terminos eorum, a turre custodum usque ad civitatem munitam.

** II Kings 18:9

Anno quarto regis Ezechiæ, qui erat annus septimus Osee filii Ela regis Israël, ascendit Salmanasar rex Assyriorum in Samariam, et oppugnavit eam,

** II Kings 18:10

et cepit. Nam post annos tres, anno sexto Ezechiæ, id est nono anno Osee regis Israël, capta est Samaria :

** II Kings 18:11

et transtulit rex Assyriorum Israël in Assyrios, collocavitque eos in Hala et in Habor fluviis Gozan in civitatibus Medorum :

** II Kings 18:12

quia non audierunt vocem Domini Dei sui, sed prætergressi sunt pactum ejus : omnia quæ præceperat Moyses servus Domini non audierunt, neque fecerunt.  

** II Kings 18:13

Anno quartodecimo regis Ezechiæ, ascendit Sennacherib rex Assyriorum ad universas civitates Juda munitas, et cepit eas.

** II Kings 18:14

Tunc misit Ezechias rex Juda nuntios ad regem Assyriorum in Lachis, dicens : Peccavi : recede a me, et omne quod imposueris mihi, feram. Indixit itaque rex Assyriorum Ezechiæ regi Judæ trecenta talenta argenti, et triginta talenta auri.

** II Kings 18:15

Deditque Ezechias omne argentum quod repertum fuerat in domo Domini et in thesauris regis.

** II Kings 18:16

In tempore illo confregit Ezechias valvas templi Domini, et laminas auri quas ipse affixerat, et dedit eas regi Assyriorum.

** II Kings 18:17

Misit autem rex Assyriorum Tharthan, et Rabsaris, et Rabsacen de Lachis ad regem Ezechiam cum manu valida Jerusalem : qui cum ascendissent, venerunt Jerusalem, et steterunt juxta aquæductum piscinæ superioris, quæ est in via Agrifullonis.

** II Kings 18:18

Vocaveruntque regem : egressus est autem ad eos Eliacim filius Helciæ præpositus domus, et Sobna scriba, et Joahe filius Asaph a commentariis.

** II Kings 18:19

Dixitque ad eos Rabsaces : Loquimini Ezechiæ : Hæc dicit rex magnus, rex Assyriorum : Quæ est ista fiducia, qua niteris ?

** II Kings 18:20

forsitan inisti consilium, ut præpares te ad prælium. In quo confidis, ut audeas rebellare ?

** II Kings 18:21

an speras in baculo arundineo atque confracto Ægypto, super quem, si incubuerit homo, comminutus ingredietur manum ejus, et perforabit eam ? sic est Pharao rex Ægypti omnibus qui confidunt in se.

** II Kings 18:22

Quod si dixeritis mihi : In Domino Deo nostro habemus fiduciam : nonne iste est, cujus abstulit Ezechias excelsa et altaria, et præcepit Judæ et Jerusalem : Ante altare hoc adorabitis in Jerusalem ?

** II Kings 18:23

Nunc igitur transite ad dominum meum regem Assyriorum, et dabo vobis duo millia equorum, et videte an habere valeatis ascensores eorum.

** II Kings 18:24

Et quomodo potestis resistere ante unum satrapam de servis domini mei minimis ? an fiduciam habes in Ægypto propter currus et equites ?

** II Kings 18:25

Numquid sine Domini voluntate ascendi ad locum istum, ut demolirer eum ? Dominus dixit mihi : Ascende ad terram hanc, et demolire eam.

** II Kings 18:26

Dixerunt autem Eliacim filius Helciæ, et Sobna, et Joahe Rabsaci : Precamur ut loquaris nobis servis tuis syriace : siquidem intelligimus hanc linguam : et non loquaris nobis judaice, audiente populo qui est super murum.

** II Kings 18:27

Responditque eis Rabsaces, dicens : Numquid ad dominum tuum, et ad te misit me dominus meus, ut loquerer sermones hos, et non potius ad viros qui sedent super murum, ut comedant stercora sua, et bibant urinam suam vobiscum ?

** II Kings 18:28

Stetit itaque Rabsaces, et exclamavit voce magna judaice, et ait : Audite verba regis magni, regis Assyriorum.

** II Kings 18:29

Hæc dicit rex : Non vos seducat Ezechias : non enim poterit eruere vos de manu mea :

** II Kings 18:30

neque fiduciam vobis tribuat super Dominum, dicens : Eruens liberabit nos Dominus, et non tradetur civitas hæc in manu regis Assyriorum.

** II Kings 18:31

Nolite audire Ezechiam. Hæc enim dicit rex Assyriorum : Facite mecum quod vobis est utile, et egredimini ad me : et comedet unusquisque de vinea sua, et de ficu sua : et bibetis aquas de cisternis vestris,

** II Kings 18:32

donec veniam, et transferam vos in terram quæ similis est terræ vestræ, in terram fructiferam, et fertilem vini, terram panis et vinearum, terram olivarum et olei ac mellis : et vivetis, et non moriemini. Nolite audire Ezechiam, qui vos decipit, dicens : Dominus liberabit nos.

** II Kings 18:33

Numquid liberaverunt dii gentium terram suam de manu regis Assyriorum ?

** II Kings 18:34

ubi est deus Emath, et Arphad ? ubi est deus Sepharvaim, Ana, et Ava ? numquid liberaverunt Samariam de manu mea ?

** II Kings 18:35

Quinam illi sunt in universis diis terrarum, qui eruerunt regionem suam de manu mea, ut possit eruere Dominus Jerusalem de manu mea ?

** II Kings 18:36

Tacuit itaque populus, et non respondit ei quidquam : siquidem præceptum regis acceperant ut non responderent ei.

** II Kings 18:37

Venitque Eliacim filius Helciæ, præpositus domus, et Sobna scriba, et Joahe filius Asaph a commentariis ad Ezechiam scissis vestibus, et nuntiaverunt ei verba Rabsacis.   

* II Kings 19

** II Kings 19:1

Quæ cum audisset Ezechias rex, scidit vestimenta sua, et opertus est sacco, ingressusque est domum Domini.

** II Kings 19:2

Et misit Eliacim præpositum domus, et Sobnam scribam, et senes de sacerdotibus, opertos saccis, ad Isaiam prophetam filium Amos.

** II Kings 19:3

Qui dixerunt : Hæc dicit Ezechias : Dies tribulationis, et increpationis, et blasphemiæ dies iste : venerunt filii usque ad partum, et vires non habet parturiens.

** II Kings 19:4

Si forte audiat Dominus Deus tuus universa verba Rabsacis, quem misit rex Assyriorum dominus suus ut exprobraret Deum viventem et argueret verbis, quæ audivit Dominus Deus tuus : et fac orationem pro reliquiis quæ repertæ sunt.

** II Kings 19:5

Venerunt ergo servi regis Ezechiæ ad Isaiam.

** II Kings 19:6

Dixitque eis Isaias : Hæc dicetis domino vestro : Hæc dicit Dominus : Noli timere a facie sermonum quos audisti, quibus blasphemaverunt pueri regis Assyriorum me.

** II Kings 19:7

Ecce ego immittam ei spiritum, et audiet nuntium, et revertetur in terram suam, et dejiciam eum gladio in terra sua.  

** II Kings 19:8

Reversus est ergo Rabsaces, et invenit regem Assyriorum expugnantem Lobnam : audierat enim quod recessisset de Lachis.

** II Kings 19:9

Cumque audisset de Tharaca rege Æthiopiæ, dicentes : Ecce egressus est ut pugnet adversum te : et iret contra eum, misit nuntios ad Ezechiam, dicens :

** II Kings 19:10

Hæc dicite Ezechiæ regi Juda : Non te seducat Deus tuus in quo habes fiduciam, neque dicas : Non tradetur Jerusalem in manus regis Assyriorum.

** II Kings 19:11

Tu enim ipse audisti quæ fecerunt reges Assyriorum universis terris, quomodo vastaverunt eas : num ergo solus poteris liberari ?

** II Kings 19:12

Numquid liberaverunt dii gentium singulos quos vastaverunt patres mei, Gozan videlicet, et Haran, et Reseph, et filios Eden qui erant in Thelassar ?

** II Kings 19:13

ubi est rex Emath, et rex Arphad, et rex civitatis Sepharvaim, Ana, et Ava ?

** II Kings 19:14

Itaque cum accepisset Ezechias litteras de manu nuntiorum, et legisset eas, ascendit in domum Domini, et expandit eas coram Domino,

** II Kings 19:15

et oravit in conspectu ejus, dicens : Domine Deus Israël, qui sedes super cherubim, tu es Deus solus regum omnium terræ : tu fecisti cælum et terram.

** II Kings 19:16

Inclina aurem tuam, et audi : aperi, Domine, oculos tuos, et vide : audi omnia verba Sennacherib, qui misit ut exprobraret nobis Deum viventem.

** II Kings 19:17

Vere, Domine, dissipaverunt reges Assyriorum gentes, et terras omnium.

** II Kings 19:18

Et miserunt deos eorum in ignem : non enim erant dii, sed opera manuum hominum, ex ligno et lapide : et perdiderunt eos.

** II Kings 19:19

Nunc igitur Domine Deus noster, salvos nos fac de manu ejus, ut sciant omnia regna terræ quia tu es Dominus Deus solus.

** II Kings 19:20

Misit autem Isaias filius Amos ad Ezechiam, dicens : Hæc dicit Dominus Deus Israël : Quæ deprecatus es me super Sennacherib rege Assyriorum, audivi.  

** II Kings 19:21

Iste est sermo, quem locutus est Dominus de eo :   Sprevit te, et subsannavit te, virgo filia Sion :  post tergum tuum caput movit, filia Jerusalem. 

** II Kings 19:22

Cui exprobrasti, et quem blasphemasti ?  contra quem exaltasti vocem tuam, et elevasti in excelsum oculos tuos ?  Contra Sanctum Israël. 

** II Kings 19:23

Per manum servorum tuorum exprobrasti Domino, et dixisti :  In multitudine curruum meorum ascendi excelsa montium in summitate Libani,  et succidi sublimes cedros ejus, et electas abietes illius.  Et ingressus sum usque ad terminos ejus,  et saltum Carmeli ejus

** II Kings 19:24

ego succidi.  Et bibi aquas alienas, et siccavi vestigiis pedum meorum omnes aquas clausas. 

** II Kings 19:25

Numquid non audisti quid ab initio fecerim ?  ex diebus antiquis plasmavi illud, et nunc adduxi :  eruntque in ruinam collium pugnantium civitates munitæ. 

** II Kings 19:26

Et qui sedent in eis, humiles manu, contremuerunt et confusi sunt :  facti sunt velut fœnum agri, et virens herba tectorum,  quæ arefacta est antequam veniret ad maturitatem. 

** II Kings 19:27

Habitaculum tuum, et egressum tuum, et introitum tuum, et viam tuam ego præscivi,  et furorem tuum contra me. 

** II Kings 19:28

Insanisti in me, et superbia tua ascendit in aures meas :  ponam itaque circulum in naribus tuis, et camum in labiis tuis,  et reducam te in viam per quam venisti. 

** II Kings 19:29

Tibi autem, Ezechia, hoc erit signum :  comede hoc anno quæ repereris :  in secundo autem anno, quæ sponte nascuntur :  porro in tertio anno seminate et metite :  plantate vineas, et comedite fructum earum. 

** II Kings 19:30

Et quodcumque reliquum fuerit de domo Juda, mittet radicem deorsum,  et faciet fructum sursum. 

** II Kings 19:31

De Jerusalem quippe egredientur reliquiæ,  et quod salvetur de monte Sion :  zelus Domini exercituum faciet hoc. 

** II Kings 19:32

Quam ob rem hæc dicit Dominus de rege Assyriorum :  Non ingredietur urbem hanc, nec mittet in eam sagittam,  nec occupabit eam clypeus, nec circumdabit eam munitio. 

** II Kings 19:33

Per viam qua venit, revertetur :  et civitatem hanc non ingredietur, dicit Dominus. 

** II Kings 19:34

Protegamque urbem hanc, et salvabo eam propter me,  et propter David servum meum.  

** II Kings 19:35

Factum est igitur in nocte illa, venit angelus Domini, et percussit in castris Assyriorum centum octoginta quinque millia. Cumque diluculo surrexisset, vidit omnia corpora mortuorum : et recedens abiit,

** II Kings 19:36

et reversus est Sennacherib rex Assyriorum, et mansit in Ninive.

** II Kings 19:37

Cumque adoraret in templo Nesroch deum suum, Adramelech et Sarasar filii ejus percusserunt eum gladio, fugeruntque in terram Armeniorum : et regnavit Asarhaddon filius ejus pro eo.   

* II Kings 20

** II Kings 20:1

In diebus illis ægrotavit Ezechias usque ad mortem : et venit ad eum Isaias filius Amos propheta, dixitque ei : Hæc dicit Dominus Deus : Præcipe domui tuæ : morieris enim tu, et non vives.

** II Kings 20:2

Qui convertit faciem suam ad parietem, et oravit Dominum, dicens :

** II Kings 20:3

Obsecro, Domine : memento, quæso, quomodo ambulaverim coram te in veritate, et in corde perfecto, et quod placitum est coram te fecerim. Flevit itaque Ezechias fletu magno.

** II Kings 20:4

Et antequam egrederetur Isaias mediam partem atrii, factus est sermo Domini ad eum, dicens :

** II Kings 20:5

Revertere, et dic Ezechiæ duci populi mei : Hæc dicit Dominus Deus David patris tui : Audivi orationem tuam, et vidi lacrimas tuas, et ecce sanavi te : die tertio ascendes templum Domini.

** II Kings 20:6

Et addam diebus tuis quindecim annos : sed et de manu regis Assyriorum liberabo te, et civitatem hanc : et protegam urbem istam propter me, et propter David servum meum.

** II Kings 20:7

Dixitque Isaias : Afferte massam ficorum. Quam cum attulissent, et posuissent super ulcus ejus, curatus est.

** II Kings 20:8

Dixerat autem Ezechias ad Isaiam : Quod erit signum, quia Dominus me sanabit, et quia ascensurus sum die tertia templum Domini ?

** II Kings 20:9

Cui ait Isaias : Hoc erit signum a Domino quod facturus sit Dominus sermonem quem locutus est : vis ut ascendat umbra decem lineis, an ut revertatur totidem gradibus ?

** II Kings 20:10

Et ait Ezechias : Facile est umbram crescere decem lineis : nec hoc volo ut fiat, sed ut revertatur retrorsum decem gradibus.

** II Kings 20:11

Invocavit itaque Isaias propheta Dominum, et reduxit umbram per lineas quibus jam descenderat in horologio Achaz, retrorsum decem gradibus.  

** II Kings 20:12

In tempore illo misit Berodach Baladan, filius Baladan, rex Babyloniorum, litteras et munera ad Ezechiam : audierat enim quod ægrotasset Ezechias.

** II Kings 20:13

Lætatus est autem in adventu eorum Ezechias, et ostendit eis domum aromatum, et aurum et argentum, et pigmenta varia, unguenta quoque, et domum vasorum suorum, et omnia quæ habere poterat in thesauris suis. Non fuit quod non monstraret eis Ezechias in domo sua, et in omni potestate sua.

** II Kings 20:14

Venit autem Isaias propheta ad regem Ezechiam, dixitque ei : Quid dixerunt viri isti ? aut unde venerunt ad te ? Cui ait Ezechias : De terra longinqua venerunt ad me, de Babylone.

** II Kings 20:15

At ille respondit : Quid viderunt in domo tua ? Ait Ezechias : Omnia quæcumque sunt in domo mea, viderunt : nihil est quod non monstraverim eis in thesauris meis.

** II Kings 20:16

Dixit itaque Isaias Ezechiæ : Audi sermonem Domini :

** II Kings 20:17

Ecce dies venient, et auferentur omnia quæ sunt in domo tua, et quæ condiderunt patres tui usque in diem hanc, in Babylonem : non remanebit quidquam, ait Dominus.

** II Kings 20:18

Sed et de filiis tuis qui egredientur ex te, quos generabis, tollentur, et erunt eunuchi in palatio regis Babylonis.

** II Kings 20:19

Dixit Ezechias ad Isaiam : Bonus sermo Domini quem locutus es : sit pax et veritas in diebus meis.  

** II Kings 20:20

Reliqua autem sermonum Ezechiæ, et omnis fortitudo ejus, et quomodo fecerit piscinam et aquæductum, et introduxerit aquas in civitatem, nonne hæc scripta sunt in libro sermonum dierum regum Juda ?

** II Kings 20:21

Dormivitque Ezechias cum patribus suis, et regnavit Manasses filius ejus pro eo.   

* II Kings 21

** II Kings 21:1

Duodecim annorum erat Manasses cum regnare cœpisset, et quinquaginta quinque annis regnavit in Jerusalem : nomen matris ejus Haphsiba.

** II Kings 21:2

Fecitque malum in conspectu Domini, juxta idola gentium quas delevit Dominus a facie filiorum Israël.

** II Kings 21:3

Conversusque est, et ædificavit excelsa quæ dissipaverat Ezechias pater ejus : et erexit aras Baal, et fecit lucos sicut fecerat Achab rex Israël, et adoravit omnem militiam cæli, et coluit eam.

** II Kings 21:4

Exstruxitque aras in domo Domini, de qua dixit Dominus : In Jerusalem ponam nomen meum.

** II Kings 21:5

Et exstruxit altaria universæ militiæ cæli in duobus atriis templi Domini.

** II Kings 21:6

Et traduxit filium suum per ignem : et ariolatus est, et observavit auguria, et fecit pythones, et aruspices multiplicavit, ut faceret malum coram Domino, et irritaret eum.

** II Kings 21:7

Posuit quoque idolum luci quem fecerat, in templo Domini, super quod locutus est Dominus ad David, et ad Salomonem filium ejus : In templo hoc, et in Jerusalem quam elegi de cunctis tribubus Israël, ponam nomen meum in sempiternum.

** II Kings 21:8

Et ultra non faciam commoveri pedem Israël de terra quam dedi patribus eorum : si tamen custodierint opere omnia quæ præcepi eis, et universam legem quam mandavit eis servus meus Moyses.

** II Kings 21:9

Illi vero non audierunt : sed seducti sunt a Manasse, ut facerent malum super gentes quas contrivit Dominus a facie filiorum Israël.

** II Kings 21:10

Locutusque est Dominus in manu servorum suorum prophetarum, dicens :

** II Kings 21:11

Quia fecit Manasses rex Juda abominationes istas pessimas, super omnia quæ fecerunt Amorrhæi ante eum, et peccare fecit etiam Judam in immunditiis suis :

** II Kings 21:12

propterea hæc dicit Dominus Deus Israël : Ecce ego inducam mala super Jerusalem et Judam, ut quicumque audierit, tinniant ambæ aures ejus.

** II Kings 21:13

Et extendam super Jerusalem funiculum Samariæ, et pondus domus Achab : et delebo Jerusalem, sicut deleri solent tabulæ : et delens vertam, et ducam crebrius stylum super faciem ejus.

** II Kings 21:14

Dimittam vero reliquias hæreditatis meæ, et tradam eas in manus inimicorum ejus, eruntque in vastitatem, et in rapinam cunctis adversariis suis :

** II Kings 21:15

eo quod fecerint malum coram me, et perseveraverint irritantes me, ex die qua egressi sunt patres eorum ex Ægypto usque ad hanc diem.

** II Kings 21:16

Insuper et sanguinem innoxium fudit Manasses multum nimis, donec impleret Jerusalem usque ad os : absque peccatis suis quibus peccare fecit Judam, ut faceret malum coram Domino.

** II Kings 21:17

Reliqua autem sermonum Manasse, ut universa quæ fecit, et peccatum ejus quod peccavit, nonne hæc scripta sunt in libro sermonum dierum regum Juda ?

** II Kings 21:18

Dormivitque Manasses cum patribus suis, et sepultus est in horto domus suæ, in horto Oza : et regnavit Amon filius ejus pro eo.  

** II Kings 21:19

Viginti duorum annorum erat Amon cum regnare cœpisset : duobus quoque annis regnavit in Jerusalem : nomen matris ejus Messalemeth filia Harus de Jeteba.

** II Kings 21:20

Fecitque malum in conspectu Domini, sicut fecerat Manasses pater ejus.

** II Kings 21:21

Et ambulavit in omni via per quam ambulaverat pater ejus, servivitque immunditiis quibus servierat pater ejus, et adoravit eas :

** II Kings 21:22

et dereliquit Dominum Deum patrum suorum, et non ambulavit in via Domini.

** II Kings 21:23

Tetenderuntque ei insidias servi sui, et interfecerunt regem in domo sua.

** II Kings 21:24

Percussit autem populus terræ omnes qui conjuraverant contra regem Amon, et constituerunt sibi regem Josiam filium ejus pro eo.

** II Kings 21:25

Reliqua autem sermonum Amon quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Juda ?

** II Kings 21:26

Sepelieruntque eum in sepulchro suo, in horto Oza : et regnavit Josias filius ejus pro eo.   

* II Kings 22

** II Kings 22:1

Octo annorum erat Josias cum regnare cœpisset : triginta et uno anno regnavit in Jerusalem : nomen matris ejus Idida filia Hadaia de Besecath.

** II Kings 22:2

Fecitque quod placitum erat coram Domino, et ambulavit per omnes vias David patris sui : non declinavit ad dexteram, sive ad sinistram.

** II Kings 22:3

Anno autem octavodecimo regis Josiæ, misit rex Saphan filium Aslia filii Messulam scribam templi Domini, dicens ei :

** II Kings 22:4

Vade ad Helciam sacerdotem magnum, ut confletur pecunia quæ illata est in templum Domini, quam collegerunt janitores templi a populo :

** II Kings 22:5

deturque fabris per præpositos domus Domini, qui et distribuant eam his qui operantur in templo Domini, ad instauranda sartatecta templi :

** II Kings 22:6

tignariis videlicet et cæmentariis, et iis qui interrupta componunt : et ut emantur ligna, et lapides de lapicidinis, ad instaurandum templum Domini.

** II Kings 22:7

Verumtamen non supputetur eis argentum quod accipiunt, sed in potestate habeant, et in fide.  

** II Kings 22:8

Dixit autem Helcias pontifex ad Saphan scribam : Librum legis reperi in domo Domini. Deditque Helcias volumen Saphan, qui et legit illud.

** II Kings 22:9

Venit quoque Saphan scriba ad regem, et renuntiavit ei quod præceperat, et ait : Conflaverunt servi tui pecuniam quæ reperta est in domo Domini, et dederunt ut distribueretur fabris a præfectis operum templi Domini.

** II Kings 22:10

Narravit quoque Saphan scriba regi, dicens : Librum dedit mihi Helcias sacerdos. Quem cum legisset Saphan coram rege,

** II Kings 22:11

et audisset rex verba libri legis Domini, scidit vestimenta sua.

** II Kings 22:12

Et præcepit Helciæ sacerdoti, et Ahicam filio Saphan, et Achobor filio Micha, et Saphan scribæ, et Asaiæ servo regis, dicens :

** II Kings 22:13

Ite et consulite Dominum super me, et super populo, et super omni Juda, de verbis voluminis istius, quod inventum est : magna enim ira Domini succensa est contra nos, quia non audierunt patres nostri verba libri hujus, ut facerent omne quod scriptum est nobis.

** II Kings 22:14

Ierunt itaque Helcias sacerdos, et Ahicam, et Achobor, et Sapham, et Asaia, ad Holdam prophetidem, uxorem Sellum filii Thecuæ filii Araas custodis vestium, quæ habitabat in Jerusalem in Secunda : locutique sunt ad eam.

** II Kings 22:15

Et illa respondit eis : Hæc dicit Dominus Deus Israël : Dicite viro qui misit vos ad me :

** II Kings 22:16

Hæc dicit Dominus : Ecce ego adducam mala super locum istum, et super habitatores ejus, omnia verba legis quæ legit rex Juda :

** II Kings 22:17

quia dereliquerunt me, et sacrificaverunt diis alienis, irritantes me in cunctis operibus manuum suarum : et succendetur indignatio mea in loco hoc, et non extinguetur.

** II Kings 22:18

Regi autem Juda, qui misit vos ut consuleretis Dominum, sic dicetis : Hæc dicit Dominus Deus Israël : Pro eo quod audisti verba voluminis,

** II Kings 22:19

et perterritum est cor tuum, et humiliatus es coram Domino, auditis sermonibus contra locum istum et habitatores ejus, quod videlicet fierent in stuporem et in maledictum : et scidisti vestimenta tua, et flevisti coram me, et ego audivi, ait Dominus :

** II Kings 22:20

idcirco colligam te ad patres tuos, et colligeris ad sepulchrum tuum in pace, ut non videant oculi tui omnia mala quæ inducturus sum super locum istum.   

* II Kings 23

** II Kings 23:1

Et renuntiaverunt regi quod dixerat. Qui misit : et congregati sunt ad eum omnes senes Juda et Jerusalem.

** II Kings 23:2

Ascenditque rex templum Domini, et omnes viri Juda, universique qui habitabant in Jerusalem cum eo sacerdotes et prophetæ, et omnis populus a parvo usque ad magnum : legitque, cunctis audientibus, omnia verba libri fœderis, qui inventus est in domo Domini.

** II Kings 23:3

Stetitque rex super gradum : et fœdus percussit coram Domino, ut ambularent post Dominum, et custodirent præcepta ejus, et testimonia, et cæremonias in omni corde, et in tota anima, et suscitarent verba fœderis hujus, quæ scripta erant in libro illo : acquievitque populus pacto.

** II Kings 23:4

Et præcepit rex Helciæ pontifici, et sacerdotibus secundi ordinis, et janitoribus, ut projicerent de templo Domini omnia vasa quæ facta fuerant Baal, et in luco, et universæ militiæ cæli : et combussit ea foris Jerusalem in convalle Cedron, et tulit pulverem eorum in Bethel.

** II Kings 23:5

Et delevit aruspices quos posuerant reges Juda ad sacrificandum in excelsis per civitates Juda, et in circuitu Jerusalem : et eos qui adolebant incensum Baal, et soli, et lunæ, et duodecim signis, et omni militiæ cæli.

** II Kings 23:6

Et efferri fecit lucum de domo Domini foras Jerusalem in convalle Cedron, et combussit eum ibi, et redegit in pulverem, et projecit super sepulchra vulgi.

** II Kings 23:7

Destruxit quoque ædiculas effeminatorum quæ erant in domo Domini, pro quibus mulieres texebant quasi domunculas luci.

** II Kings 23:8

Congregavitque omnes sacerdotes de civitatibus Juda, et contaminavit excelsa ubi sacrificabant sacerdotes de Gabaa usque Bersabee, et destruxit aras portarum in introitu ostii Josue principis civitatis, quod erat ad sinistram portæ civitatis.

** II Kings 23:9

Verumtamen non ascendebant sacerdotes excelsorum ad altare Domini in Jerusalem : sed tantum comedebant azyma in medio fratrum suorum.

** II Kings 23:10

Contaminavit quoque Topheth, quod est in convalle filii Ennom, ut nemo consecraret filium suum aut filiam per ignem, Moloch.

** II Kings 23:11

Abstulit quoque equos quos dederant reges Juda soli in introitu templi Domini juxta exedram Nathanmelech eunuchi, qui erat in Pharurim : currus autem solis combussit igni.

** II Kings 23:12

Altaria quoque quæ erant super tecta cœnaculi Achaz, quæ fecerant reges Juda, et altaria quæ fecerat Manasses in duobus atriis templi Domini, destruxit rex, et cucurrit inde, et dispersit cinerem eorum in torrentem Cedron.

** II Kings 23:13

Excelsa quoque, quæ erant in Jerusalem ad dexteram partem montis offensionis, quæ ædificaverat Salomon rex Israël Astaroth idolo Sidoniorum, et Chamos offensioni Moab, et Melchom abominationi filiorum Ammon, polluit rex.

** II Kings 23:14

Et contrivit statuas, et succidit lucos : replevitque loca eorum ossibus mortuorum.

** II Kings 23:15

Insuper et altare quod erat in Bethel, et excelsum quod fecerat Jeroboam filius Nabat, qui peccare fecit Israël : et altare illud, et excelsum destruxit, atque combussit, et comminuit in pulverem, succenditque etiam lucum.

** II Kings 23:16

Et conversus Josias, vidit ibi sepulchra quæ erant in monte : misitque et tulit ossa de sepulchris, et combussit ea super altare, et polluit illud juxta verbum Domini quod locutus est vir Dei, qui prædixerat verba hæc.

** II Kings 23:17

Et ait : Quis est titulus ille, quem video ? Responderuntque ei cives urbis illius : Sepulchrum est hominis Dei, qui venit de Juda, et prædixit verba hæc, quæ fecisti super altare Bethel.

** II Kings 23:18

Et ait : Dimitte eum : nemo commoveat ossa ejus. Et intacta manserunt ossa illius cum ossibus prophetæ qui venerat de Samaria.

** II Kings 23:19

Insuper et omnia fana excelsorum quæ erant in civitatibus Samariæ, quæ fecerant reges Israël ad irritandum Dominum, abstulit Josias : et fecit eis secundum omnia opera quæ fecerat in Bethel.

** II Kings 23:20

Et occidit universos sacerdotes excelsorum qui erant ibi super altaria, et combussit ossa humana super ea : reversusque est Jerusalem.

** II Kings 23:21

Et præcepit omni populo, dicens : Facite Phase Domino Deo vestro, secundum quod scriptum est in libro fœderis hujus.

** II Kings 23:22

Nec enim factum est Phase tale a diebus judicum qui judicaverunt Israël, et omnium dierum regum Israël et regum Juda,

** II Kings 23:23

sicut in octavodecimo anno regis Josiæ factum est Phase istud Domino in Jerusalem.

** II Kings 23:24

Sed et pythones, et ariolos, et figuras idolorum, et immunditias, et abominationes, quæ fuerant in terra Juda et Jerusalem, abstulit Josias : ut statueret verba legis quæ scripta sunt in libro quem invenit Helcias sacerdos in templo Domini.

** II Kings 23:25

Similis illi non fuit ante eum rex, qui reverteretur ad Dominum in omni corde suo, et in tota anima sua, et in universa virtute sua juxta omnem legem Moysi : neque post eum surrexit similis illi.

** II Kings 23:26

Verumtamen non est aversus Dominus ab ira furoris sui magni quo iratus est furor ejus contra Judam propter irritationes quibus provocaverat eum Manasses.

** II Kings 23:27

Dixit itaque Dominus : Etiam Judam auferam a facie mea, sicut abstuli Israël : et projiciam civitatem hanc quam elegi Jerusalem, et domum de qua dixi : Erit nomen meum ibi.  

** II Kings 23:28

Reliqua autem sermonum Josiæ, et universa quæ fecit, nonne hæc scripta sunt in libro verborum dierum regum Juda ?

** II Kings 23:29

In diebus ejus ascendit Pharao Nechao rex Ægypti contra regem Assyriorum ad flumen Euphraten, et abiit Josias rex in occursum ejus : et occisus est in Mageddo cum vidisset eum.

** II Kings 23:30

Et portaverunt eum servi sui mortuum de Mageddo : et pertulerunt in Jerusalem, et sepelierunt eum in sepulchro suo. Tulitque populus terræ Joachaz filium Josiæ : et unxerunt eum, et constituerunt eum regem pro patre suo.  

** II Kings 23:31

Viginti trium annorum erat Joachaz cum regnare cœpisset, et tribus mensibus regnavit in Jerusalem : nomen matris ejus Amital filia Jeremiæ de Lobna.

** II Kings 23:32

Et fecit malum coram Domino, juxta omnia quæ fecerant patres ejus.

** II Kings 23:33

Vinxitque eum Pharao Nechao in Rebla, quæ est in terra Emath, ne regnaret in Jerusalem : et imposuit mulctam terræ centum talentis argenti, et talento auri.  

** II Kings 23:34

Regemque constituit Pharao Nechao Eliacim filium Josiæ pro Josia patre ejus : vertitque nomen ejus Joakim. Porro Joachaz tulit, et duxit in Ægyptum, et mortuus est ibi.

** II Kings 23:35

Argentum autem et aurum dedit Joakim Pharaoni, cum indixisset terræ per singulos, ut conferretur juxta præceptum Pharaonis : et unumquemque juxta vires suas exegit, tam argentum quam aurum, de populo terræ, ut daret Pharaoni Nechao.

** II Kings 23:36

Viginti quinque annorum erat Joakim cum regnare cœpisset, et undecim annis regnavit in Jerusalem : nomen matris ejus Zebida filia Phadaia de Ruma.

** II Kings 23:37

Et fecit malum coram Domino juxta omnia quæ fecerant patres ejus.   

* II Kings 24

** II Kings 24:1

In diebus ejus ascendit Nabuchodonosor rex Babylonis, et factus est ei Joakim servus tribus annis : et rursum rebellavit contra eum.

** II Kings 24:2

Immisitque ei Dominus latrunculos Chaldæorum, et latrunculos Syriæ, et latrunculos Moab, et latrunculos filiorum Ammon : et immisit eos in Judam ut disperderent eum, juxta verbum Domini quod locutus fuerat per servos suos prophetas.

** II Kings 24:3

Factum est autem hoc per verbum Domini contra Judam, ut auferret eum coram se propter peccata Manasse universa quæ fecit,

** II Kings 24:4

et propter sanguinem innoxium quem effudit, et implevit Jerusalem cruore innocentium : et ob hanc rem noluit Dominus propitiari.

** II Kings 24:5

Reliqua autem sermonum Joakim, et universa quæ fecit, nonne hæc scripta sunt in libro sermonum dierum regum Juda ? Et dormivit Joakim cum patribus suis :

** II Kings 24:6

et regnavit Joachin filius ejus pro eo.

** II Kings 24:7

Et ultra non addidit rex Ægypti ut egrederetur de terra sua : tulerat enim rex Babylonis, a rivo Ægypti usque ad fluvium Euphraten, omnia quæ fuerant regis Ægypti.  

** II Kings 24:8

Decem et octo annorum erat Joachin cum regnare cœpisset, et tribus mensibus regnavit in Jerusalem : nomen matris ejus Nohesta filia Elnathan de Jerusalem.

** II Kings 24:9

Et fecit malum coram Domino, juxta omnia quæ fecerat pater ejus.

** II Kings 24:10

In tempore illo ascenderunt servi Nabuchodonosor regis Babylonis in Jerusalem, et circumdata est urbs munitionibus.

** II Kings 24:11

Venitque Nabuchodonosor rex Babylonis ad civitatem cum servis suis ut oppugnarent eam.

** II Kings 24:12

Egressusque est Joachin rex Juda ad regem Babylonis, ipse et mater ejus, et servi ejus, et principes ejus, et eunuchi ejus : et suscepit eum rex Babylonis anno octavo regni sui.

** II Kings 24:13

Et protulit inde omnes thesauros domus Domini, et thesauros domus regiæ : et concidit universa vasa aurea quæ fecerat Salomon rex Israël in templo Domini juxta verbum Domini.  

** II Kings 24:14

Et transtulit omnem Jerusalem, et universos principes, et omnes fortes exercitus, decem millia, in captivitatem, et omnem artificem et clusorem : nihilque relictum est, exceptis pauperibus populi terræ.

** II Kings 24:15

Transtulit quoque Joachin in Babylonem, et matrem regis, et uxores regis, et eunuchos ejus : et judices terræ duxit in captivitatem de Jerusalem in Babylonem.

** II Kings 24:16

Et omnes viros robustos, septem millia, et artifices, et clusores mille, omnes viros fortes et bellatores : duxitque eos rex Babylonis captivos in Babylonem.

** II Kings 24:17

Et constituit Matthaniam patruum ejus pro eo : imposuitque nomen ei Sedeciam.  

** II Kings 24:18

Vigesimum et primum annum ætatis habebat Sedecias cum regnare cœpisset, et undecim annis regnavit in Jerusalem : nomen matris ejus erat Amital filia Jeremiæ de Lobna.

** II Kings 24:19

Et fecit malum coram Domino, juxta omnia quæ fecerat Joakim.

** II Kings 24:20

Irascebatur enim Dominus contra Jerusalem et contra Judam, donec projiceret eos a facie sua : recessitque Sedecias a rege Babylonis.   

* II Kings 25

** II Kings 25:1

Factum est autem anno nono regni ejus, mense decimo, decima die mensis, venit Nabuchodonosor rex Babylonis, ipse et omnis exercitus ejus, in Jerusalem, et circumdederunt eam : et exstruxerunt in circuitu ejus munitiones.

** II Kings 25:2

Et clausa est civitas atque vallata usque ad undecimum annum regis Sedeciæ,

** II Kings 25:3

nona die mensis : prævaluitque fames in civitate, nec erat panis populo terræ.

** II Kings 25:4

Et interrupta est civitas : et omnes viri bellatores nocte fugerunt per viam portæ quæ est inter duplicem murum ad hortum regis. Porro Chaldæi obsidebant in circuitu civitatem. Fugit itaque Sedecias per viam quæ ducit ad campestria solitudinis.

** II Kings 25:5

Et persecutus est exercitus Chaldæorum regem, comprehenditque eum in planitie Jericho : et omnes bellatores qui erant cum eo, dispersi sunt, et reliquerunt eum.

** II Kings 25:6

Apprehensum ergo regem duxerunt ad regem Babylonis in Reblatha : qui locutus est cum eo judicium.

** II Kings 25:7

Filios autem Sedeciæ occidit coram eo, et oculos ejus effodit, vinxitque eum catenis, et adduxit in Babylonem.  

** II Kings 25:8

Mense quinto, septima die mensis, ipse est annus nonusdecimus regis Babylonis, venit Nabuzardan princeps exercitus, servus regis Babylonis, in Jerusalem.

** II Kings 25:9

Et succendit domum Domini, et domum regis : et domos Jerusalem, omnemque domum combussit igni.

** II Kings 25:10

Et muros Jerusalem in circuitu destruxit omnis exercitus Chaldæorum, qui erat cum principe militum.

** II Kings 25:11

Reliquam autem populi partem quæ remanserat in civitate, et perfugas qui transfugerant ad regem Babylonis, et reliquum vulgus transtulit Nabuzardan princeps militiæ.

** II Kings 25:12

Et de pauperibus terræ reliquit vinitores et agricolas.

** II Kings 25:13

Columnas autem æreas quæ erant in templo Domini, et bases, et mare æreum quod erat in domo Domini, confregerunt Chaldæi, et transtulerunt æs omne in Babylonem.

** II Kings 25:14

Ollas quoque æreas, et trullas, et tridentes, et scyphos, et mortariola, et omnia vasa ærea, in quibus ministrabant, tulerunt.

** II Kings 25:15

Necnon et thuribula, et phialas : quæ aurea, aurea, et quæ argentea, argentea tulit princeps militiæ,

** II Kings 25:16

id est, columnas duas, mare unum, et bases quas fecerat Salomon in templo Domini : non erat pondus æris omnium vasorum.

** II Kings 25:17

Decem et octo cubitos altitudinis habebat columna una : et capitellum æreum super se altitudinis trium cubitorum : et retiaculum, et malogranata super capitellum columnæ, omnia ærea : similem et columna secunda habebat ornatum.

** II Kings 25:18

Tulit quoque princeps militiæ Saraiam sacerdotem primum, et Sophoniam sacerdotem secundum, et tres janitores.

** II Kings 25:19

Et de civitate eunuchum unum, qui erat præfectus super bellatores viros : et quinque viros de his qui steterant coram rege, quos reperit in civitate : et Sopher principem exercitus, qui probabat tyrones de populo terræ : et sexaginta viros e vulgo, qui inventi fuerant in civitate.

** II Kings 25:20

Quos tollens Nabuzardan princeps militum, duxit ad regem Babylonis in Reblatha.

** II Kings 25:21

Percussitque eos rex Babylonis, et interfecit eos in Reblatha in terra Emath : et translatus est Juda de terra sua.  

** II Kings 25:22

Populo autem qui relictus erat in terra Juda, quem dimiserat Nabuchodonosor rex Babylonis, præfecit Godoliam filium Ahicam filii Saphan.

** II Kings 25:23

Quod cum audissent omnes duces militum, ipsi et viri qui erant cum eis, videlicet quod constituisset rex Babylonis Godoliam, venerunt ad Godoliam in Maspha, Ismahel filius Nathaniæ, et Johanan filius Caree, et Saraia filius Thanehumeth Netophathites, et Jezonias filius Maachathi, ipsi et socii eorum.

** II Kings 25:24

Juravitque Godolias ipsis et sociis eorum, dicens : Nolite timere servire Chaldæis : manete in terra, et servite regi Babylonis, et bene erit vobis.

** II Kings 25:25

Factum est autem in mense septimo, venit Ismahel filius Nathaniæ filii Elisama de semine regio, et decem viri cum eo : percusseruntque Godoliam, qui et mortuus est : sed et Judæos et Chaldæos qui erant cum eo in Maspha.  

** II Kings 25:26

Consurgensque omnis populus a parvo usque ad magnum, et principes militum, venerunt in Ægyptum timentes Chaldæos.

** II Kings 25:27

Factum est vero in anno trigesimo septimo transmigrationis Joachin regis Juda, mense duodecimo, vigesima septima die mensis : sublevavit Evilmerodach rex Babylonis, anno quo regnare cœperat, caput Joachin regis Juda de carcere.

** II Kings 25:28

Et locutus est ei benigne, et posuit thronum ejus super thronum regum qui erant cum eo in Babylone.

** II Kings 25:29

Et mutavit vestes ejus quas habuerat in carcere, et comedebat panem semper in conspectu ejus cunctis diebus vitæ suæ.

** II Kings 25:30

Annonam quoque constituit ei sine intermissione, quæ et dabatur ei a rege per singulos dies omnibus diebus vitæ suæ.    

