* II Peter 1

** II Peter 1:1

Simon Petrus, servus et apostolus Jesu Christi, iis qui coæqualem nobiscum sortiti sunt fidem in justitia Dei nostri, et Salvatoris Jesu Christi.

** II Peter 1:2

Gratia vobis, et pax adimpleatur in cognitione Dei, et Christi Jesu Domini nostri :

** II Peter 1:3

Quomodo omnia nobis divinæ virtutis suæ, quæ ad vitam et pietatem donata sunt, per cognitionem ejus, qui vocavit nos propria gloria, et virtute,

** II Peter 1:4

per quem maxima, et pretiosa nobis promissa donavit : ut per hæc efficiamini divinæ consortes naturæ : fugientes ejus, quæ in mundo est, concupiscentiæ corruptionem.  

** II Peter 1:5

Vos autem curam omnem subinferentes, ministrate in fide vestra virtutem, in virtute autem scientiam,

** II Peter 1:6

in scientia autem abstinentiam, in abstinentia autem patientiam, in patientia autem pietatem,

** II Peter 1:7

in pietate autem amorem fraternitatis, in amore autem fraternitatis caritatem.

** II Peter 1:8

Hæc enim si vobiscum adsint, et superent, non vacuos nec sine fructu vos constituent in Domini nostri Jesu Christi cognitione.

** II Peter 1:9

Cui enim non præsto sunt hæc, cæcus est, et manu tentans, oblivionem accipiens purgationis veterum suorum delictorum.

** II Peter 1:10

Quapropter fratres, magis satagite ut per bona opera certam vestram vocationem, et electionem faciatis : hæc enim facientes, non peccabitis aliquando.

** II Peter 1:11

Sic enim abundanter ministrabitur vobis introitus in æternum regnum Domini nostri et Salvatoris Jesu Christi.  

** II Peter 1:12

Propter quod incipiam vos semper commonere de his : et quidem scientes et confirmatos vos in præsenti veritate.

** II Peter 1:13

Justum autem arbitror quamdiu sum in hoc tabernaculo, suscitare vos in commonitione :

** II Peter 1:14

certus quod velox est depositio tabernaculi mei secundum quod et Dominus noster Jesus Christus significavit mihi.

** II Peter 1:15

Dabo autem operam et frequenter habere vos post obitum meum, ut horum memoriam faciatis.  

** II Peter 1:16

Non enim doctas fabulas secuti notam fecimus vobis Domini nostri Jesu Christi virtutem et præsentiam : sed speculatores facti illius magnitudinis.

** II Peter 1:17

Accipiens enim a Deo Patre honorem et gloriam, voce delapsa ad eum hujuscemodi a magnifica gloria : Hic est Filius meus dilectus, in quo mihi complacui, ipsum audite.

** II Peter 1:18

Et hanc vocem nos audivimus de cælo allatam, cum essemus cum ipso in monte sancto.

** II Peter 1:19

Et habemus firmiorem propheticum sermonem : cui benefacitis attendentes quasi lucernæ lucenti in caliginoso loco donec dies elucescat, et lucifer oriatur in cordibus vestris :

** II Peter 1:20

hoc primum intelligentes quod omnis prophetia Scripturæ propria interpretatione non fit.

** II Peter 1:21

Non enim voluntate humana allata est aliquando prophetia : sed Spiritu Sancto inspirati, locuti sunt sancti Dei homines.   

* II Peter 2

** II Peter 2:1

Fuerunt vero et pseudoprophetæ in populo, sicut et in vobis erunt magistri mendaces, qui introducent sectas perditionis : et eum qui emit eos, Dominum negant, superducentes sibi celerem perditionem.

** II Peter 2:2

Et multi sequentur eorum luxurias, per quos via veritatis blasphemabitur :

** II Peter 2:3

et in avaritia fictis verbis de vobis negotiabuntur : quibus judicium jam olim non cessat : et perditio eorum non dormitat.

** II Peter 2:4

Si enim Deus angelis peccantibus non pepercit, sed rudentibus inferni detractos in tartarum tradidit cruciandos, in judicium reservari.

** II Peter 2:5

Et originali mundo non pepercit, sed octavum Noë justitiæ præconem custodivit, diluvium mundo impiorum inducens.

** II Peter 2:6

Et civitates Sodomorum et Gomorrhæorum in cinerem redigens, eversione damnavit : exemplum eorum, qui impie acturi sunt, ponens :

** II Peter 2:7

et justum Lot oppressum a nefandorum injuria, ac luxuriosa conversatione eripuit :

** II Peter 2:8

aspectu enim, et auditu justus erat : habitans apud eos, qui de die in diem animam justam iniquis operibus cruciabant.

** II Peter 2:9

Novit Dominus pios de tentatione eripere : iniquos vero in diem judicii reservare cruciandos.  

** II Peter 2:10

Magis autem eos, qui post carnem in concupiscentia immunditiæ ambulant, dominationemque contemnunt, audaces, sibi placentes, sectas non metuunt introducere blasphemantes :

** II Peter 2:11

ubi angeli fortitudine, et virtute cum sint majores, non portant adversum se execrabile judicium.

** II Peter 2:12

Hi vero velut irrationabilia pecora, naturaliter in captionem, et in perniciem in his quæ ignorant blasphemantes in corruptione sua peribunt,

** II Peter 2:13

percipientes mercedem injustitiæ, voluptatem existimantes diei delicias : coinquinationes, et maculæ deliciis affluentes, in conviviis suis luxuriantes vobiscum,

** II Peter 2:14

oculos habentes plenos adulterii, et incessabilis delicti. Pellicientes animas instabiles, cor exercitatum avaritia habentes, maledictionis filii :

** II Peter 2:15

derelinquentes rectam viam erraverunt, secuti viam Balaam ex Bosor, qui mercedem iniquitatis amavit :

** II Peter 2:16

correptionem vero habuit suæ vesaniæ : subjugale mutum animal, hominis voce loquens, prohibuit prophetæ insipientiam.

** II Peter 2:17

Hi sunt fontes sine aqua, et nebulæ turbinibus exagitatæ, quibus caligo tenebrarum reservatur.

** II Peter 2:18

Superba enim vanitatis loquentes, pelliciunt in desideriis carnis luxuriæ eos, qui paululum effugiunt, qui in errore conversantur :

** II Peter 2:19

libertatem illis promittentes, cum ipsi servi sint corruptionem : a quo enim quis superatus est, hujus et servus est.

** II Peter 2:20

Si enim refugientes coinquinationes mundi in cognitione Domini nostri, et Salvatoris Jesu Christi, his rursus implicati superantur : facta sunt eis posteriora deteriora prioribus.

** II Peter 2:21

Melius enim erat illis non cognoscere viam justitiæ, quam post agnitionem, retrorsum converti ab eo, quod illis traditum est, sancto mandato.

** II Peter 2:22

Contigit enim eis illud veri proverbii : Canis reversus ad suum vomitum : et, Sus lota in volutabro luti.   

* II Peter 3

** II Peter 3:1

Hanc ecce vobis, carissimi, secundam scribo epistolam, in quibus vestram excito in commonitione sinceram mentem :

** II Peter 3:2

ut memores sitis eorum, quæ prædixi, verborum, a sanctis prophetis et apostolorum vestrorum, præceptorum Domini et Salvatoris.

** II Peter 3:3

Hoc primum scientes, quod venient in novissimis diebus in deceptione illusores, juxta proprias concupiscentias ambulantes,

** II Peter 3:4

dicentes : Ubi est promissio, aut adventus ejus ? ex quo enim patres dormierunt, omnia sic perseverant ab initio creaturæ.

** II Peter 3:5

Latet enim eos hoc volentes, quod cæli erant prius, et terra de aqua, et per aquam consistens Dei verbo :

** II Peter 3:6

per quæ, ille tunc mundus aqua inundatus, periit.

** II Peter 3:7

Cæli autem, qui nunc sunt, et terra eodem verbo repositi sunt, igni reservati in diem judicii, et perditionis impiorum hominum.

** II Peter 3:8

Unum vero hoc non lateat vos, carissimi, quia unus dies apud Dominum sicut mille anni, et mille anni sicut dies unus.

** II Peter 3:9

Non tardat Dominus promissionem suam, sicut quidam existimant : sed patienter agit propter vos, nolens aliquos perire, sed omnes ad pœnitentiam reverti.

** II Peter 3:10

Adveniet autem dies Domini ut fur : in quo cæli magno impetu transient, elementa vero calore solventur, terra autem et quæ in ipsa sunt opera, exurentur.  

** II Peter 3:11

Cum igitur hæc omnia dissolvenda sunt, quales oportet vos esse in sanctis conversationibus, et pietatibus,

** II Peter 3:12

exspectantes, et properantes in adventum diei Domini, per quem cæli ardentes solventur, et elementa ignis ardore tabescent ?

** II Peter 3:13

Novos vero cælos, et novam terram secundum promissa ipsius exspectamus, in quibus justitia habitat.

** II Peter 3:14

Propter quod, carissimi, hæc exspectantes, satagite immaculati, et inviolati ei inveniri in pace :

** II Peter 3:15

et Domini nostri longanimitatem, salutem arbitremini : sicut et carissimus frater noster Paulus secundum datam sibi sapientiam scripsit vobis,

** II Peter 3:16

sicut et omnibus epistolis, loquens in eis de his in quibus sunt quædam difficilia intellectu, quæ indocti et instabiles depravant, sicut et ceteras Scripturas, ad suam ipsorum perditionem.  

** II Peter 3:17

Vos igitur fratres, præscientes custodite, ne insipientium errore traducti excidatis a propria firmitate :

** II Peter 3:18

crescite vero in gratia, et in cognitione Domini nostri, et Salvatoris Jesu Christi. Ipsi gloria et nunc, et in diem æternitatis. Amen.    

