* III John 1

** III John 1:1

Senior Gajo carissimo, quem ego diligo in veritate.

** III John 1:2

Carissime, de omnibus orationem facio prospere te ingredi, et valere sicut prospere agit anima tua.  

** III John 1:3

Gavisus sum valde venientibus fratribus, et testimonium perhibentibus veritati tuæ, sicut tu in veritate ambulas.

** III John 1:4

Majorem horum non habeo gratiam, quam ut audiam filios meos in veritate ambulare.

** III John 1:5

Carissime, fideliter facis quidquid operaris in fratres, et hoc in peregrinos,

** III John 1:6

qui testimonium reddiderunt caritati tuæ in conspectu ecclesiæ : quos, benefaciens, deduces digne Deo.

** III John 1:7

Pro nomine enim ejus profecti sunt, nihil accipientes a gentibus.

** III John 1:8

Nos ergo debemus suscipere hujusmodi, ut cooperatores simus veritatis.  

** III John 1:9

Scripsissem forsitan ecclesiæ : sed is qui amat primatum gerere in eis, Diotrephes, non recipit nos :

** III John 1:10

propter hoc si venero, commonebo ejus opera, quæ facit, verbis malignis garriens in nos : et quasi non ei ista sufficiant, neque ipse suscipit fratres : et eos qui suscipiunt, prohibet, et de ecclesia ejicit.

** III John 1:11

Carissime, noli imitari malum, sed quod bonum est. Qui benefacit, ex Deo est : qui malefacit, non vidit Deum.  

** III John 1:12

Demetrio testimonium redditur ab omnibus, et ab ipsa veritate, sed et nos testimonium perhibemus : et nosti quoniam testimonium nostrum verum est.  

** III John 1:13

Multa habui tibi scribere : sed nolui per atramentum et calamum scribere tibi.

** III John 1:14

Spero autem protinus te videre, et os ad os loquemur. Pax tibi. Salutant te amici. Saluta amicos nominatim.    

** III John 1:15

nil

