* Acts 1

** Acts 1:1

Primum quidem sermonem feci de omnibus, o Theophile, quæ cœpit Jesus facere et docere

** Acts 1:2

usque in diem qua præcipiens Apostolis per Spiritum Sanctum, quos elegit, assumptus est :

** Acts 1:3

quibus et præbuit seipsum vivum post passionem suam in multis argumentis, per dies quadraginta apparens eis, et loquens de regno Dei.  

** Acts 1:4

Et convescens, præcepit eis ab Jerosolymis ne discederent, sed exspectarent promissionem Patris, quam audistis (inquit) per os meum :

** Acts 1:5

quia Joannes quidem baptizavit aqua, vos autem baptizabimini Spiritu Sancto non post multos hos dies.

** Acts 1:6

Igitur qui convenerant, interrogabant eum, dicentes : Domine, si in tempore hoc restitues regnum Israël ?

** Acts 1:7

Dixit autem eis : Non est vestrum nosse tempora vel momenta quæ Pater posuit in sua potestate :

** Acts 1:8

sed accipietis virtutem supervenientis Spiritus Sancti in vos, et eritis mihi testes in Jerusalem, et in omni Judæa, et Samaria, et usque ad ultimum terræ.  

** Acts 1:9

Et cum hæc dixisset, videntibus illis, elevatus est : et nubes suscepit eum ab oculis eorum.

** Acts 1:10

Cumque intuerentur in cælum euntem illum, ecce duo viri astiterunt juxta illos in vestibus albis,

** Acts 1:11

qui et dixerunt : Viri Galilæi, quid statis aspicientes in cælum ? Hic Jesus, qui assumptus est a vobis in cælum, sic veniet quemadmodum vidistis eum euntem in cælum.  

** Acts 1:12

Tunc reversi sunt Jerosolymam a monte qui vocatur Oliveti, qui est juxta Jerusalem, sabbati habens iter.

** Acts 1:13

Et cum introissent in cœnaculum, ascenderunt ubi manebant Petrus, et Joannes, Jacobus, et Andreas, Philippus, et Thomas, Bartholomæus, et Matthæus, Jacobus Alphæi, et Simon Zelotes, et Judas Jacobi.

** Acts 1:14

Hi omnes erant perseverantes unanimiter in oratione cum mulieribus, et Maria matre Jesu, et fratribus ejus.  

** Acts 1:15

In diebus illis, exsurgens Petrus in medio fratrum, dixit (erat autem turba hominum simul, fere centum viginti) :

** Acts 1:16

Viri fratres, oportet impleri Scripturam quam prædixit Spiritus Sanctus per os David de Juda, qui fuit dux eorum qui comprehenderunt Jesum :

** Acts 1:17

qui connumeratus erat in nobis, et sortitus est sortem ministerii hujus.

** Acts 1:18

Et hic quidem possedit agrum de mercede iniquitatis, et suspensus crepuit medius : et diffusa sunt omnia viscera ejus.

** Acts 1:19

Et notum factum est omnibus habitantibus Jerusalem, ita ut appellaretur ager ille, lingua eorum, Haceldama, hoc est, ager sanguinis.

** Acts 1:20

Scriptum est enim in libro Psalmorum : Fiat commoratio eorum deserta, et non sit qui inhabitet in ea : et episcopatum ejus accipiat alter.

** Acts 1:21

Oportet ergo ex his viris qui nobiscum sunt congregati in omni tempore quo intravit et exivit inter nos Dominus Jesus,

** Acts 1:22

incipiens a baptismate Joannis usque in diem qua assumptus est a nobis, testem resurrectionis ejus nobiscum fieri unum ex istis.

** Acts 1:23

Et statuerunt duos, Joseph, qui vocabatur Barsabas, qui cognominatus est Justus, et Mathiam.

** Acts 1:24

Et orantes dixerunt : Tu Domine, qui corda nosti omnium, ostende quem elegeris ex his duobus unum,

** Acts 1:25

accipere locum ministerii hujus et apostolatus, de quo prævaricatus est Judas ut abiret in locum suum.

** Acts 1:26

Et dederunt sortes eis, et cecidit sors super Mathiam : et annumeratus est cum undecim Apostolis.   

* Acts 2

** Acts 2:1

Et cum complerentur dies Pentecostes, erant omnes pariter in eodem loco :

** Acts 2:2

et factus est repente de cælo sonus, tamquam advenientis spiritus vehementis, et replevit totam domum ubi erant sedentes.

** Acts 2:3

Et apparuerunt illis dispertitæ linguæ tamquam ignis, seditque supra singulos eorum :

** Acts 2:4

et repleti sunt omnes Spiritu Sancto, et cœperunt loqui variis linguis, prout Spiritus Sanctus dabat eloqui illis.

** Acts 2:5

Erant autem in Jerusalem habitantes Judæi, viri religiosi ex omni natione quæ sub cælo est.

** Acts 2:6

Facta autem hac voce, convenit multitudo, et mente confusa est, quoniam audiebat unusquisque lingua sua illos loquentes.

** Acts 2:7

Stupebant autem omnes, et mirabantur, dicentes : Nonne ecce omnes isti qui loquuntur, Galilæi sunt ?

** Acts 2:8

et quomodo nos audivimus unusquisque linguam nostram in qua nati sumus ?

** Acts 2:9

Parthi, et Medi, et Ælamitæ, et qui habitant Mespotamiam, Judæam, et Cappadociam, Pontum, et Asiam,

** Acts 2:10

Phrygiam, et Pamphyliam, Ægyptum, et partes Libyæ quæ est circa Cyrenen : et advenæ Romani,

** Acts 2:11

Judæi quoque, et Proselyti, Cretes, et Arabes : audivimus eos loquentes nostris linguis magnalia Dei.

** Acts 2:12

Stupebant autem omnes, et mirabantur ad invicem, dicentes : Quidnam vult hoc esse ?

** Acts 2:13

Alii autem irridentes dicebant : Quia musto pleni sunt isti.  

** Acts 2:14

Stans autem Petrus cum undecim, levavit vocem suam, et locutus est eis : Viri Judæi, et qui habitatis Jerusalem universi, hoc vobis notum sit, et auribus percipite verba mea.

** Acts 2:15

Non enim, sicut vos æstimatis, hi ebrii sunt, cum sit hora diei tertia :

** Acts 2:16

sed hoc est quod dictum est per prophetam Joël :  

** Acts 2:17

Et erit in novissimis diebus, dicit Dominus,  effundam de Spiritu meo super omnem carnem :  et prophetabunt filii vestri et filiæ vestræ,  et juvenes vestri visiones videbunt,  et seniores vestri somnia somniabunt. 

** Acts 2:18

Et quidem super servos meos, et super ancillas meas,  in diebus illis effundam de Spiritu meo,  et prophetabunt : 

** Acts 2:19

et dabo prodigia in cælo sursum,  et signa in terra deorsum, sanguinem, et ignem, et vaporem fumi : 

** Acts 2:20

sol convertetur in tenebras,  et luna in sanguinem,  antequam veniat dies Domini magnus et manifestus. 

** Acts 2:21

Et erit : omnis quicumque invocaverit nomen Domini, salvus erit.

** Acts 2:22

Viri Israëlitæ, audite verba hæc : Jesum Nazarenum, virum approbatum a Deo in vobis, virtutibus, et prodigiis, et signis, quæ fecit Deus per illum in medio vestri, sicut et vos scitis :

** Acts 2:23

hunc, definito consilio et præscientia Dei traditum, per manus iniquorum affligentes interemistis :

** Acts 2:24

quem Deus suscitavit, solutis doloribus inferni, juxta quod impossibile erat teneri illum ab eo.

** Acts 2:25

David enim dicit in eum :  Providebam Dominum in conspectu meo semper :  quoniam a dextris est mihi, ne commovear : 

** Acts 2:26

propter hoc lætatum est cor meum, et exsultavit lingua mea,  insuper et caro mea requiescet in spe : 

** Acts 2:27

quoniam non derelinques animam meam in inferno,  nec dabis sanctum tuum videre corruptionem. 

** Acts 2:28

Notas mihi fecisti vias vitæ :  et replebis me jucunditate cum facie tua.

** Acts 2:29

Viri fratres, liceat audenter dicere ad vos de patriarcha David, quoniam defunctus est, et sepultus : et sepulchrum ejus est apud nos usque in hodiernum diem.

** Acts 2:30

Propheta igitur cum esset, et sciret quia jurejurando jurasset illi Deus de fructu lumbi ejus sedere super sedem ejus :

** Acts 2:31

providens locutus est de resurrectione Christi, quia neque derelictus est in inferno, neque caro ejus vidit corruptionem.

** Acts 2:32

Hunc Jesum resuscitavit Deus, cujus omnes nos testes sumus.

** Acts 2:33

Dextera igitur Dei exaltatus, et promissione Spiritus Sancti accepta a Patre, effudit hunc, quem vos videtis et auditis.

** Acts 2:34

Non enim David ascendit in cælum : dixit autem ipse :  Dixit Dominus Domino meo :  Sede a dextris meis, 

** Acts 2:35

donec ponam inimicos tuos  scabellum pedum tuorum.

** Acts 2:36

Certissime sciat ergo omnis domus Israël, quia et Dominum eum et Christum fecit Deus hunc Jesum, quem vos crucifixistis.  

** Acts 2:37

His autem auditis, compuncti sunt corde, et dixerunt ad Petrum et ad reliquos Apostolos : Quid faciemus, viri fratres ?

** Acts 2:38

Petrus vero ad illos : Pœnitentiam, inquit, agite, et baptizetur unusquisque vestrum in nomine Jesu Christi in remissionem peccatorum vestrorum : et accipietis donum Spiritus Sancti.

** Acts 2:39

Vobis enim est repromissio, et filiis vestris, et omnibus qui longe sunt, quoscumque advocaverit Dominus Deus noster.

** Acts 2:40

Aliis etiam verbis plurimis testificatus est, et exhortabatur eos, dicens : Salvamini a generatione ista prava.

** Acts 2:41

Qui ergo receperunt sermonem ejus, baptizati sunt : et appositæ sunt in die illa animæ circiter tria millia.  

** Acts 2:42

Erant autem perseverantes in doctrina Apostolorum, et communicatione fractionis panis, et orationibus.

** Acts 2:43

Fiebat autem omni animæ timor : multa quoque prodigia et signa per Apostolos in Jerusalem fiebant, et metus erat magnus in universis.

** Acts 2:44

Omnes etiam qui credebant, erant pariter, et habebant omnia communia.

** Acts 2:45

Possessiones et substantias vendebant, et dividebant illa omnibus, prout cuique opus erat.

** Acts 2:46

Quotidie quoque perdurantes unanimiter in templo, et frangentes circa domos panem, sumebant cibum cum exsultatione et simplicitate cordis,

** Acts 2:47

collaudantes Deum et habentes gratiam ad omnem plebem. Dominus autem augebat qui salvi fierent quotidie in idipsum.   

* Acts 3

** Acts 3:1

Petrus autem et Joannes ascendebant in templum ad horam orationis nonam.

** Acts 3:2

Et quidam vir, qui erat claudus ex utero matris suæ, bajulabatur : quem ponebant quotidie ad portam templi, quæ dicitur Speciosa, ut peteret eleemosynam ab introëuntibus in templum.

** Acts 3:3

Is cum vidisset Petrum et Joannem incipientes introire in templum, rogabat ut eleemosynam acciperet.

** Acts 3:4

Intuens autem in eum Petrus cum Joanne, dixit : Respice in nos.

** Acts 3:5

At ille intendebat in eos, sperans se aliquid accepturum ab eis.

** Acts 3:6

Petrus autem dixit : Argentum et aurum non est mihi : quod autem habeo, hoc tibi do : in nomine Jesu Christi Nazareni surge, et ambula.

** Acts 3:7

Et apprehensa manu ejus dextera, allevavit eum, et protinus consolidatæ sunt bases ejus et plantæ.

** Acts 3:8

Et exiliens stetit, et ambulabat : et intravit cum illis in templum ambulans, et exiliens, et laudans Deum.

** Acts 3:9

Et vidit omnis populus eum ambulantem et laudantem Deum.

** Acts 3:10

Cognoscebant autem illum, quod ipse erat qui ad eleemosynam sedebat ad Speciosam portam templi : et impleti sunt stupore et extasi in eo quod contigerat illi.

** Acts 3:11

Cum teneret autem Petrum et Joannem, cucurrit omnis populus ad eos ad porticum quæ appellatur Salomonis, stupentes.  

** Acts 3:12

Videns autem Petrus, respondit ad populum : Viri Israëlitæ, quid miramini in hoc, aut nos quid intuemini, quasi nostra virtute aut potestate fecerimus hunc ambulare ?

** Acts 3:13

Deus Abraham, et Deus Isaac, et Deus Jacob, Deus patrum nostrorum glorificavit filium suum Jesum, quem vos quidem tradidistis, et negastis ante faciem Pilati, judicante illo dimitti.

** Acts 3:14

Vos autem sanctum et justum negastis, et petistis virum homicidam donari vobis :

** Acts 3:15

auctorem vero vitæ interfecistis, quem Deus suscitavit a mortuis, cujus nos testes sumus.

** Acts 3:16

Et in fide nominis ejus, hunc quem vos vidistis et nostis, confirmavit nomen ejus : et fides, quæ per eum est, dedit integram sanitatem istam in conspectu omnium vestrum.

** Acts 3:17

Et nunc, fratres, scio quia per ignorantiam fecistis, sicut et principes vestri.

** Acts 3:18

Deus autem, quæ prænuntiavit per os omnium prophetarum, pati Christum suum, sic implevit.

** Acts 3:19

Pœnitemini igitur et convertimini, ut deleantur peccata vestra :

** Acts 3:20

ut cum venerint tempora refrigerii a conspectu Domini, et miserit eum qui prædicatus est vobis, Jesum Christum,

** Acts 3:21

quem oportet quidem cælum suscipere usque in tempora restitutionis omnium quæ locutus est Deus per os sanctorum suorum a sæculo prophetarum.

** Acts 3:22

Moyses quidem dixit : Quoniam prophetam suscitabit vobis Dominus Deus vester de fratribus vestris, tamquam me : ipsum audietis juxta omnia quæcumque locutus fuerit vobis.

** Acts 3:23

Erit autem : omnis anima quæ non audierit prophetam illum, exterminabitur de plebe.

** Acts 3:24

Et omnes prophetæ, a Samuel et deinceps, qui locuti sunt, annuntiaverunt dies istos.

** Acts 3:25

Vos estis filii prophetarum, et testamenti quod disposuit Deus ad patres nostros, dicens ad Abraham : Et in semine tuo benedicentur omnes familiæ terræ.

** Acts 3:26

Vobis primum Deus suscitans filium suum, misit eum benedicentem vobis : ut convertat se unusquisque a nequitia sua.   

* Acts 4

** Acts 4:1

Loquentibus autem illis ad populum, supervenerunt sacerdotes, et magistratus templi, et sadducæi,

** Acts 4:2

dolentes quod docerent populum, et annuntiarent in Jesu resurrectionem ex mortuis :

** Acts 4:3

et injecerunt in eos manus, et posuerunt eos in custodiam in crastinum : erat enim jam vespera.

** Acts 4:4

Multi autem eorum qui audierant verbum, crediderunt : et factus est numerus virorum quinque millia.

** Acts 4:5

Factum est autem in crastinum, ut congregarentur principes eorum, et seniores, et scribæ, in Jerusalem :

** Acts 4:6

et Annas princeps sacerdotum, et Caiphas, et Joannes, et Alexander, et quotquot erant de genere sacerdotali.

** Acts 4:7

Et statuentes eos in medio, interrogabant : In qua virtute, aut in quo nomine fecistis hoc vos ?  

** Acts 4:8

Tunc repletus Spiritu Sancto Petrus, dixit ad eos : Principes populi, et seniores, audite :

** Acts 4:9

si nos hodie dijudicamur in benefacto hominis infirmi, in quo iste salvus factus est,

** Acts 4:10

notum sit omnibus vobis, et omni plebi Israël, quia in nomine Domini nostri Jesu Christi Nazareni, quem vos crucifixistis, quem Deus suscitavit a mortuis, in hoc iste astat coram vobis sanus.

** Acts 4:11

Hic est lapis qui reprobatus est a vobis ædificantibus, qui factus est in caput anguli :

** Acts 4:12

et non est in alio aliquo salus. Nec enim aliud nomen est sub cælo datum hominibus, in quo oporteat nos salvos fieri.  

** Acts 4:13

Videntes autem Petri constantiam, et Joannis, comperto quod homines essent sine litteris, et idiotæ, admirabantur, et cognoscebant eos quoniam cum Jesu fuerant :

** Acts 4:14

hominem quoque videntes stantem cum eis, qui curatus fuerat, nihil poterant contradicere.

** Acts 4:15

Jusserunt autem eos foras extra concilium secedere : et conferebant ad invicem,

** Acts 4:16

dicentes : Quid faciemus hominibus istis ? quoniam quidem notum signum factum est per eos omnibus habitantibus Jerusalem : manifestum est, et non possumus negare.

** Acts 4:17

Sed ne amplius divulgetur in populum, comminemur eis ne ultra loquantur in nomine hoc ulli hominum.

** Acts 4:18

Et vocantes eos, denuntiaverunt ne omnino loquerentur neque docerent in nomine Jesu.

** Acts 4:19

Petrus vero et Joannes respondentes, dixerunt ad eos : Si justum est in conspectu Dei vos potius audire quam Deum, judicate.

** Acts 4:20

Non enim possumus quæ vidimus et audivimus non loqui.

** Acts 4:21

At illi comminantes dimiserunt eos, non invenientes quomodo punirent eos propter populum : quia omnes clarificabant id quod factum fuerat in eo quod acciderat.

** Acts 4:22

Annorum enim erat amplius quadraginta homo, in quo factum fuerat signum istud sanitatis.  

** Acts 4:23

Dimissi autem venerunt ad suos, et annuntiaverunt eis quanta ad eos principes sacerdotum et seniores dixissent.

** Acts 4:24

Qui cum audissent, unanimiter levaverunt vocem ad Deum, et dixerunt : Domine, tu es qui fecisti cælum et terram, mare et omnia quæ in eis sunt :

** Acts 4:25

qui Spiritu Sancto per os patris nostri David pueri tui dixisti :   Quare fremuerunt gentes,  et populi meditati sunt inania ? 

** Acts 4:26

Astiterunt reges terræ,  et principes convenerunt in unum  adversus Dominum, et adversus Christum ejus.

** Acts 4:27

Convenerunt enim vere in civitate ista adversus sanctum puerum tuum Jesum, quem unxisti, Herodes et Pontius Pilatus, cum gentibus et populis Israël,

** Acts 4:28

facere quæ manus tua et consilium tuum decreverunt fieri.

** Acts 4:29

Et nunc, Domine, respice in minas eorum, et da servis tuis cum omni fiducia loqui verbum tuum,

** Acts 4:30

in eo quod manum tuam extendas ad sanitates, et signa, et prodigia fieri per nomen sancti filii tui Jesu.

** Acts 4:31

Et cum orassent, motus est locus in quo erant congregati : et repleti sunt omnes Spiritu Sancto, et loquebantur verbum Dei cum fiducia.  

** Acts 4:32

Multitudinis autem credentium erat cor unum et anima una : nec quisquam eorum quæ possidebat, aliquid suum esse dicebat, sed erant illis omnia communia.

** Acts 4:33

Et virtute magna reddebant Apostoli testimonium resurrectionis Jesu Christi Domini nostri : et gratia magna erat in omnibus illis.

** Acts 4:34

Neque enim quisquam egens erat inter illos. Quotquot enim possessores agrorum aut domorum erant, vendentes afferebant pretia eorum quæ vendebant,

** Acts 4:35

et ponebant ante pedes Apostolorum. Dividebatur autem singulis prout cuique opus erat.

** Acts 4:36

Joseph autem, qui cognominatus est Barnabas ab Apostolis (quod est interpretatum, Filius consolationis), Levites, Cyprius genere,

** Acts 4:37

cum haberet agrum, vendidit eum, et attulit pretium, et posuit ante pedes Apostolorum.   

* Acts 5

** Acts 5:1

Vir autem quidam nomine Ananias, cum Saphira uxore suo vendidit agrum,

** Acts 5:2

et fraudavit de pretio agri, conscia uxore sua : et afferens partem quamdam, ad pedes Apostolorum posuit.

** Acts 5:3

Dixit autem Petrus : Anania, cur tentavit Satanas cor tuum, mentiri te Spiritui Sancto, et fraudare de pretio agri ?

** Acts 5:4

nonne manens tibi manebat, et venundatum in tua erat potestate ? quare posuisti in corde tuo hanc rem ? non es mentitus hominibus, sed Deo.

** Acts 5:5

Audiens autem Ananias hæc verba, cecidit, et expiravit. Et factus est timor magnus super omnes qui audierunt.

** Acts 5:6

Surgentes autem juvenes amoverunt eum, et efferentes sepelierunt.

** Acts 5:7

Factum est autem quasi horarum trium spatium, et uxor ipsius, nesciens quod factum fuerat, introivit.

** Acts 5:8

Dixit autem ei Petrus : Dic mihi mulier, si tanti agrum vendidistis ? At illa dixit : Etiam tanti.

** Acts 5:9

Petrus autem ad eam : Quid utique convenit vobis tentare Spiritum Domini ? Ecce pedes eorum qui sepelierunt virum tuum ad ostium, et efferent te.

** Acts 5:10

Confestim cecidit ante pedes ejus, et expiravit. Intrantes autem juvenes invenerunt illam mortuam : et extulerunt, et sepelierunt ad virum suum.

** Acts 5:11

Et factus est timor magnus in universa ecclesia, et in omnes qui audierunt hæc.  

** Acts 5:12

Per manus autem Apostolorum fiebant signa et prodigia multa in plebe. Et erant unanimiter omnes in porticu Salomonis.

** Acts 5:13

Ceterorum autem nemo audebat se conjungere illis : sed magnificabat eos populus.

** Acts 5:14

Magis autem augebatur credentium in Domino multitudo virorum ac mulierum,

** Acts 5:15

ita ut in plateas ejicerent infirmos, et ponerent in lectulis et grabatis, ut, veniente Petro, saltem umbra illius obumbraret quemquam illorum, et liberarentur ab infirmitatibus suis.

** Acts 5:16

Concurrebat autem et multitudo vicinarum civitatum Jerusalem, afferentes ægros, et vexatos a spiritibus immundis : qui curabantur omnes.  

** Acts 5:17

Exsurgens autem princeps sacerdotum, et omnes qui cum illo erant (quæ est hæresis sadducæorum), repleti sunt zelo :

** Acts 5:18

et injecerunt manus in Apostolos, et posuerunt eos in custodia publica.

** Acts 5:19

Angelus autem Domini per noctem aperiens januas carceris, et educens eos, dixit :

** Acts 5:20

Ite, et stantes loquimini in templo plebi omnia verba vitæ hujus.

** Acts 5:21

Qui cum audissent, intraverunt diluculo in templum, et docebant. Adveniens autem princeps sacerdotum, et qui cum eo erant, convocaverunt concilium, et omnes seniores filiorum Israël : et miserunt ad carcerem ut adducerentur.

** Acts 5:22

Cum autem venissent ministri, et aperto carcere non invenissent illos, reversi nuntiaverunt,

** Acts 5:23

dicentes : Carcerem quidem invenimus clausum cum omni diligentia, et custodes stantes ante januas : aperientes autem neminem intus invenimus.

** Acts 5:24

Ut autem audierunt hos sermones magistratus templi et principes sacerdotum, ambigebant de illis quidnam fieret.

** Acts 5:25

Adveniens autem quidam, nuntiavit eis : Quia ecce viri quos posuistis in carcerem, sunt in templo, stantes et docentes populum.  

** Acts 5:26

Tunc abiit magistratus cum ministris, et adduxit illos sine vi : timebant enim populum ne lapidarentur.

** Acts 5:27

Et cum adduxissent illos, statuerunt in concilio : et interrogavit eos princeps sacerdotum,

** Acts 5:28

dicens : Præcipiendo præcepimus vobis ne doceretis in nomine isto, et ecce replestis Jerusalem doctrina vestra : et vultis inducere super nos sanguinem hominis istius.  

** Acts 5:29

Respondens autem Petrus et Apostoli, dixerunt : Obedire oportet Deo magis quam hominibus.

** Acts 5:30

Deus patrum nostrorum suscitavit Jesum, quem vos interemistis, suspendentes in ligno.

** Acts 5:31

Hunc principem et salvatorem Deus exaltavit dextera sua ad dandam pœnitentiam Israëli, et remissionem peccatorum :

** Acts 5:32

et nos sumus testes horum verborum, et Spiritus Sanctus, quem dedit Deus omnibus obedientibus sibi.

** Acts 5:33

Hæc cum audissent, dissecabantur, et cogitabant interficere illos.  

** Acts 5:34

Surgens autem quidam in concilio pharisæus, nomine Gamaliel, legis doctor, honorabilis universæ plebi, jussit foras ad breve homines fieri,

** Acts 5:35

dixitque ad illos : Viri Israëlitæ, attendite vobis super hominibus istis quid acturi sitis.

** Acts 5:36

Ante hos enim dies extitit Theodas, dicens se esse aliquem, cui consensit numerus virorum circiter quadringentorum : qui occisus est, et omnes qui credebant ei, dissipati sunt, et redacti ad nihilum.

** Acts 5:37

Post hunc extitit Judas Galilæus in diebus professionis, et avertit populum post se : et ipse periit, et omnes quotquot consenserunt ei, dispersi sunt.

** Acts 5:38

Et nunc itaque dico vobis, discedite ab hominibus istis, et sinite illos : quoniam si est ex hominibus consilium hoc aut opus, dissolvetur :

** Acts 5:39

si vero ex Deo est, non poteritis dissolvere illud, ne forte et Deo repugnare inveniamini. Consenserunt autem illi.

** Acts 5:40

Et convocantes Apostolos, cæsis denuntiaverunt ne omnino loquerentur in nomine Jesu, et dimiserunt eos.

** Acts 5:41

Et illi quidem ibant gaudentes a conspectu concilii, quoniam digni habiti sunt pro nomine Jesu contumeliam pati.

** Acts 5:42

Omni autem die non cessabant in templo et circa domos, docentes et evangelizantes Christum Jesum.   

* Acts 6

** Acts 6:1

In diebus illis, crescente numero discipulorum, factum est murmur Græcorum adversus Hebræos, eo quod despicerentur in ministerio quotidiano viduæ eorum.

** Acts 6:2

Convocantes autem duodecim multitudinem discipulorum, dixerunt : Non est æquum nos derelinquere verbum Dei, et ministrare mensis.

** Acts 6:3

Considerate ergo, fratres, viros ex vobis boni testimonii septem, plenos Spiritu Sancto et sapientia, quos constituamus super hoc opus.

** Acts 6:4

Nos vero orationi et ministerio verbi instantes erimus.

** Acts 6:5

Et placuit sermo coram omni multitudine. Et elegerunt Stephanum, virum plenum fide et Spiritu Sancto, et Philippum, et Prochorum, et Nicanorem, et Timonem, et Parmenam, et Nicolaum advenam Antiochenum.

** Acts 6:6

Hos statuerunt ante conspectum Apostolorum : et orantes imposuerunt eis manus.

** Acts 6:7

Et verbum Domini crescebat, et multiplicabatur numerus discipulorum in Jerusalem valde : multa etiam turba sacerdotum obediebat fidei.  

** Acts 6:8

Stephanus autem plenus gratia et fortitudine, faciebat prodigia et signa magna in populo.

** Acts 6:9

Surrexerunt autem quidam de synagoga quæ appellatur Libertinorum, et Cyrenensium, et Alexandrinorum, et eorum qui erant a Cilicia, et Asia, disputantes cum Stephano :

** Acts 6:10

et non poterant resistere sapientiæ, et Spiritui qui loquebatur.

** Acts 6:11

Tunc summiserunt viros, qui dicerent se audivisse eum dicentem verba blasphemiæ in Moysen et in Deum.

** Acts 6:12

Commoverunt itaque plebem, et seniores, et scribas : et concurrentes rapuerunt eum, et adduxerunt in concilium,

** Acts 6:13

et statuerunt falsos testes, qui dicerent : Homo iste non cessat loqui verba adversus locum sanctum, et legem :

** Acts 6:14

audivimus enim eum dicentem quoniam Jesus Nazarenus hic destruet locum istum, et mutabit traditiones quas tradidit nobis Moyses.

** Acts 6:15

Et intuentes eum omnes qui sedebant in concilio, viderunt faciem ejus tamquam faciem angeli.   

* Acts 7

** Acts 7:1

Dixit autem princeps sacerdotum : Si hæc ita se habent ?

** Acts 7:2

Qui ait : Viri fratres et patres, audite : Deus gloriæ apparuit patri nostro Abrahæ cum esset in Mesopotamia, priusquam moraretur in Charan,

** Acts 7:3

et dixit ad illum : Exi de terra tua, et de cognatione tua, et veni in terram quam monstravero tibi.

** Acts 7:4

Tunc exiit de terra Chaldæorum, et habitavit in Charan. Et inde, postquam mortuus est pater ejus, transtulit illum in terram istam, in qua nunc vos habitatis.

** Acts 7:5

Et non dedit illi hæreditatem in ea, nec passum pedis : sed repromisit dare illi eam in possessionem, et semini ejus post ipsum, cum non haberet filium.

** Acts 7:6

Locutus est autem ei Deus : Quia erit semen ejus accola in terra aliena, et servituti eos subjicient, et male tractabunt eos annis quadringentis :

** Acts 7:7

et gentem cui servierint, judicabo ego, dixit Dominus : et post hæc exibunt, et servient mihi in loco isto.

** Acts 7:8

Et dedit illi testamentum circumcisionis : et sic genuit Isaac, et circumcidit eum die octavo : et Isaac, Jacob : et Jacob, duodecim patriarchas.

** Acts 7:9

Et patriarchæ æmulantes, Joseph vendiderunt in Ægyptum : et erat Deus cum eo,

** Acts 7:10

et eripuit eum ex omnibus tribulationibus ejus, et dedit ei gratiam et sapientiam in conspectu pharaonis regis Ægypti : et constituit eum præpositum super Ægyptum, et super omnem domum suam.

** Acts 7:11

Venit autem fames in universam Ægyptum et Chanaan, et tribulatio magna : et non inveniebant cibos patres nostri.

** Acts 7:12

Cum audisset autem Jacob esse frumentum in Ægypto, misit patres nostros primum :

** Acts 7:13

et in secundo cognitus est Joseph a fratribus suis, et manifestatum est Pharaoni genus ejus.

** Acts 7:14

Mittens autem Joseph, accersivit Jacob patrem suum et omnem cognationem suam, in animabus septuaginta quinque.

** Acts 7:15

Et descendit Jacob in Ægyptum : et defunctus est ipse, et patres nostri.

** Acts 7:16

Et translati sunt in Sichem, et positi sunt in sepulchro, quod emit Abraham pretio argenti a filiis Hemor filii Sichem.  

** Acts 7:17

Cum autem appropinquaret tempus promissionis quam confessus erat Deus Abrahæ, crevit populus, et multiplicatus est in Ægypto,

** Acts 7:18

quoadusque surrexit alius rex in Ægypto, qui non sciebat Joseph.

** Acts 7:19

Hic circumveniens genus nostrum, afflixit patres nostros ut exponerent infantes suos, ne vivificarentur.

** Acts 7:20

Eodem tempore natus est Moyses, et fuit gratus Deo : qui nutritus est tribus mensibus in domo patris sui.

** Acts 7:21

Exposito autem illo, sustulit eum filia Pharaonis, et nutrivit eum sibi in filium.

** Acts 7:22

Et eruditus est Moyses omni sapientia Ægyptiorum, et erat potens in verbis et in operibus suis.

** Acts 7:23

Cum autem impleretur ei quadraginta annorum tempus, ascendit in cor ejus ut visitaret fratres suos filios Israël.

** Acts 7:24

Et cum vidisset quemdam injuriam patientem, vindicavit illum, et fecit ultionem ei qui injuriam sustinebat, percusso Ægyptio.

** Acts 7:25

Existimabat autem intelligere fratres, quoniam Deus per manum ipsius daret salutem illis : at illi non intellexerunt.

** Acts 7:26

Sequenti vero die apparuit illis litigantibus : et reconciliabat eos in pace, dicens : Viri, fratres estis : ut quid nocetis alterutrum ?

** Acts 7:27

Qui autem injuriam faciebat proximo, repulit eum, dicens : Quis te constituit principem et judicem super nos ?

** Acts 7:28

Numquid interficere me tu vis, quemadmodum interfecisti heri Ægyptium ?

** Acts 7:29

Fugit autem Moyses in verbo isto : et factus est advena in terra Madian, ubi generavit filios duos.

** Acts 7:30

Et expletis annis quadraginta, apparuit illi in deserto montis Sina angelus in igne flammæ rubi.

** Acts 7:31

Moyses autem videns, admiratus est visum. Et accedente illo ut consideraret, facta est ad eum vox Domini, dicens :

** Acts 7:32

Ego sum Deus patrum tuorum, Deus Abraham, Deus Isaac, et Deus Jacob. Tremefactus autem Moyses, non audebat considerare.

** Acts 7:33

Dixit autem illi Dominus : Solve calceamentum pedum tuorum : locus enim in quo stas, terra sancta est.

** Acts 7:34

Videns vidi afflictionem populi mei qui est in Ægypto, et gemitum eorum audivi, et descendi liberare eos. Et nunc veni, et mittam te in Ægyptum.

** Acts 7:35

Hunc Moysen, quem negaverunt, dicentes : Quis te constituit principem et judicem ? hunc Deus principem et redemptorem misit, cum manu angeli qui apparuit illi in rubo.

** Acts 7:36

Hic eduxit illos faciens prodigia et signa in terra Ægypti, et in rubro mari, et in deserto annis quadraginta.

** Acts 7:37

Hic est Moyses, qui dixit filiis Israël : Prophetam suscitabit vobis Deus de fratribus vestris, tamquam me : ipsum audietis.

** Acts 7:38

Hic est qui fuit in ecclesia in solitudine cum angelo, qui loquebatur ei in monte Sina, et cum patribus nostris : qui accepit verba vitæ dare nobis.

** Acts 7:39

Cui noluerunt obedire patres nostri : sed repulerunt, et aversi sunt cordibus suis in Ægyptum,

** Acts 7:40

dicentes ad Aaron : Fac nobis deos qui præcedant nos : Moyses enim hic, qui eduxit nos de terra Ægypti, nescimus quid factum sit ei.

** Acts 7:41

Et vitulum fecerunt in diebus illis, et obtulerunt hostiam simulacro, et lætabantur in operibus manuum suarum.

** Acts 7:42

Convertit autem Deus, et tradidit eos servire militiæ cæli, sicut scriptum est in libro prophetarum :   Numquid victimas et hostias obtulistis mihi  annis quadraginta in deserto, domus Israël ? 

** Acts 7:43

Et suscepistis tabernaculum Moloch,  et sidus dei vestri Rempham,  figuras quas fecistis adorare eas :  et transferam vos trans Babylonem.

** Acts 7:44

Tabernaculum testimonii fuit cum patribus nostris in deserto, sicut disposuit illis Deus loquens ad Moysen, ut faceret illud secundum formam quam viderat.

** Acts 7:45

Quod et induxerunt, suscipientes patres nostri cum Jesu in possessionem gentium quas expulit Deus a facie patrum nostrorum, usque in diebus David,

** Acts 7:46

qui invenit gratiam ante Deum, et petiit ut inveniret tabernaculum Deo Jacob.

** Acts 7:47

Salomon autem ædificavit illi domum.

** Acts 7:48

Sed non Excelsus in manufactis habitat, sicut propheta dicit : 

** Acts 7:49

Cælum mihi sedes est :  terra autem scabellum pedum meorum.  Quam domum ædificabitis mihi ? dicit Dominus :  aut quis locus requietionis meæ est ? 

** Acts 7:50

Nonne manus mea fecit hæc omnia ?

** Acts 7:51

Dura cervice, et incircumcisis cordibus et auribus, vos semper Spiritui Sancto resistitis : sicut patres vestri, ita et vos.

** Acts 7:52

Quem prophetarum non sunt persecuti patres vestri ? et occiderunt eos qui prænuntiabant de adventu Justi, cujus vos nunc proditores et homicidæ fuistis :

** Acts 7:53

qui accepistis legem in dispositione angelorum, et non custodistis.  

** Acts 7:54

Audientes autem hæc, dissecabantur cordibus suis, et stridebant dentibus in eum.

** Acts 7:55

Cum autem esset plenus Spiritu Sancto, intendens in cælum, vidit gloriam Dei, et Jesum stantem a dextris Dei. Et ait : Ecce video cælos apertos, et Filium hominis stantem a dextris Dei.

** Acts 7:56

Exclamantes autem voce magna continuerunt aures suas, et impetum fecerunt unanimiter in eum.

** Acts 7:57

Et ejicientes eum extra civitatem, lapidabant : et testes deposuerunt vestimenta sua secus pedes adolescentis qui vocabatur Saulus.

** Acts 7:58

Et lapidabant Stephanum invocantem, et dicentem : Domine Jesu, suscipe spiritum meum.

** Acts 7:59

Positis autem genibus, clamavit voce magna, dicens : Domine, ne statuas illis hoc peccatum. Et cum hoc dixisset, obdormivit in Domino. Saulus autem erat consentiens neci ejus.   

* Acts 8

** Acts 8:1

Facta est autem in illa die persecutio magna in ecclesia quæ erat Jerosolymis, et omnes dispersi sunt per regiones Judææ et Samariæ præter Apostolos.

** Acts 8:2

Curaverunt autem Stephanum viri timorati, et fecerunt planctum magnum super eum.

** Acts 8:3

Saulus autem devastabat ecclesiam per domos intrans, et trahens viros ac mulieres, tradebat in custodiam.  

** Acts 8:4

Igitur qui dispersi erant pertransibant, evangelizantes verbum Dei.

** Acts 8:5

Philippus autem descendens in civitatem Samariæ, prædicabat illis Christum.

** Acts 8:6

Intendebant autem turbæ his quæ a Philippo dicebantur, unanimiter audientes, et videntes signa quæ faciebat.

** Acts 8:7

Multi enim eorum qui habebant spiritus immundos, clamantes voce magna exibant. Multi autem paralytici et claudi curati sunt.

** Acts 8:8

Factum est ergo gaudium magnum in illa civitate.

** Acts 8:9

Vir autem quidam nomine Simon, qui ante fuerat in civitate magus, seducens gentem Samariæ, dicens se esse aliquem magnum :

** Acts 8:10

cui auscultabant omnes a minimo usque ad maximum, dicentes : Hic est virtus Dei, quæ vocatur magna.

** Acts 8:11

Attendebant autem eum : propter quod multo tempore magiis suis dementasset eos.

** Acts 8:12

Cum vero credidissent Philippo evangelizanti de regno Dei, in nomine Jesu Christi baptizabantur viri ac mulieres.

** Acts 8:13

Tunc Simon et ipse credidit : et cum baptizatus esset, adhærebat Philippo. Videns etiam signa et virtutes maximas fieri, stupens admirabatur.  

** Acts 8:14

Cum autem audissent Apostoli qui erant Jerosolymis, quod recepisset Samaria verbum Dei, miserunt ad eos Petrum et Joannem.

** Acts 8:15

Qui cum venissent, oraverunt pro ipsis ut acciperent Spiritum Sanctum :

** Acts 8:16

nondum enim in quemquam illorum venerat, sed baptizati tantum erant in nomine Domini Jesu.

** Acts 8:17

Tunc imponebant manus super illos, et accipiebant Spiritum Sanctum.

** Acts 8:18

Cum vidisset autem Simon quia per impositionem manus Apostolorum daretur Spiritus Sanctus, obtulit eis pecuniam,

** Acts 8:19

dicens : Date et mihi hanc potestatem, ut cuicumque imposuero manus, accipiat Spiritum Sanctum. Petrus autem dixit ad eum :

** Acts 8:20

Pecunia tua tecum sit in perditionem : quoniam donum Dei existimasti pecunia possideri.

** Acts 8:21

Non est tibi pars neque sors in sermone isto : cor enim tuum non est rectum coram Deo.

** Acts 8:22

Pœnitentiam itaque age ab hac nequitia tua : et roga Deum, si forte remittatur tibi hæc cogitatio cordis tui.

** Acts 8:23

In felle enim amaritudinis, et obligatione iniquitatis, video te esse.

** Acts 8:24

Respondens autem Simon, dixit : Precamini vos pro me ad Dominum, ut nihil veniat super me horum quæ dixistis.

** Acts 8:25

Et illi quidem testificati, et locuti verbum Domini, redibant Jerosolymam, et multis regionibus Samaritanorum evangelizabant.  

** Acts 8:26

Angelus autem Domini locutus est ad Philippum, dicens : Surge, et vade contra meridianum, ad viam quæ descendit ab Jerusalem in Gazam : hæc est deserta.

** Acts 8:27

Et surgens abiit. Et ecce vir Æthiops, eunuchus, potens Candacis reginæ Æthiopum, qui erat super omnes gazas ejus, venerat adorare in Jerusalem :

** Acts 8:28

et revertebatur sedens super currum suum, legensque Isaiam prophetam.

** Acts 8:29

Dixit autem Spiritus Philippo : Accede, et adjunge te ad currum istum.

** Acts 8:30

Accurrens autem Philippus, audivit eum legentem Isaiam prophetam, et dixit : Putasne intelligis quæ legis ?

** Acts 8:31

Qui ait : Et quomodo possum, si non aliquis ostenderit mihi ? Rogavitque Philippum ut ascenderet, et sederet secum.

** Acts 8:32

Locus autem Scripturæ quem legebat, erat hic :   Tamquam ovis ad occisionem ductus est :  et sicut agnus coram tondente se, sine voce,  sic non aperuit os suum. 

** Acts 8:33

In humilitate judicium ejus sublatum est.  Generationem ejus quis enarrabit ?  quoniam tolletur de terra vita ejus.

** Acts 8:34

Respondens autem eunuchus Philippo, dixit : Obsecro te, de quo propheta dicit hoc ? de se, an de alio aliquo ?

** Acts 8:35

Aperiens autem Philippus os suum, et incipiens a Scriptura ista, evangelizavit illi Jesum.

** Acts 8:36

Et dum irent per viam, venerunt ad quamdam aquam : et ait eunuchus : Ecce aqua : quid prohibet me baptizari ?

** Acts 8:37

Dixit autem Philippus : Si credis ex toto corde, licet. Et respondens ait : Credo Filium Dei esse Jesum Christum.

** Acts 8:38

Et jussit stare currum : et descenderunt uterque in aquam, Philippus et eunuchus, et baptizavit eum.

** Acts 8:39

Cum autem ascendissent de aqua, Spiritus Domini rapuit Philippum, et amplius non vidit eum eunuchus. Ibat autem per viam suam gaudens.

** Acts 8:40

Philippus autem inventus est in Azoto, et pertransiens evangelizabat civitatibus cunctis, donec veniret Cæsaream.  

* Acts 9

** Acts 9:1

Saulus autem adhuc spirans minarum et cædis in discipulos Domini, accessit ad principem sacerdotum,

** Acts 9:2

et petiit ab eo epistolas in Damascum ad synagogas : ut si quos invenisset hujus viæ viros ac mulieres, vinctos perduceret in Jerusalem.  

** Acts 9:3

Et cum iter faceret, contigit ut appropinquaret Damasco : et subito circumfulsit eum lux de cælo.

** Acts 9:4

Et cadens in terram audivit vocem dicentem sibi : Saule, Saule, quid me persequeris ?

** Acts 9:5

Qui dixit : Quis es, domine ? Et ille : Ego sum Jesus, quem tu persequeris : durum est tibi contra stimulum calcitrare.

** Acts 9:6

Et tremens ac stupens dixit : Domine, quid me vis facere ?

** Acts 9:7

Et Dominus ad eum : Surge, et ingredere civitatem, et ibi dicetur tibi quid te oporteat facere. Viri autem illi qui comitabantur cum eo, stabant stupefacti, audientes quidem vocem, neminem autem videntes.

** Acts 9:8

Surrexit autem Saulus de terra, apertisque oculis nihil videbat. Ad manus autem illum trahentes, introduxerunt Damascum.

** Acts 9:9

Et erat ibi tribus diebus non videns, et non manducavit, neque bibit.  

** Acts 9:10

Erat autem quidam discipulus Damasci, nomine Ananias : et dixit ad illum in visu Dominus : Anania. At ille ait : Ecce ego, Domine.

** Acts 9:11

Et Dominus ad eum : Surge, et vade in vicum qui vocatur Rectus : et quære in domo Judæ Saulum nomine Tarsensem : ecce enim orat.

** Acts 9:12

(Et vidit virum Ananiam nomine, introëuntem, et imponentem sibi manus ut visum recipiat.)

** Acts 9:13

Respondit autem Ananias : Domine, audivi a multis de viro hoc, quanta mala fecerit sanctis tuis in Jerusalem :

** Acts 9:14

et hic habet potestatem a principibus sacerdotum alligandi omnes qui invocant nomen tuum.

** Acts 9:15

Dixit autem ad eum Dominus : Vade, quoniam vas electionis est mihi iste, ut portet nomen meum coram gentibus, et regibus, et filiis Israël.

** Acts 9:16

Ego enim ostendam illi quanta oporteat eum pro nomine meo pati.  

** Acts 9:17

Et abiit Ananias, et introivit in domum : et imponens ei manus, dixit : Saule frater, Dominus misit me Jesus, qui apparuit tibi in via qua veniebas, ut videas, et implearis Spiritu Sancto.

** Acts 9:18

Et confestim ceciderunt ab oculis ejus tamquam squamæ, et visum recepit : et surgens baptizatus est.

** Acts 9:19

Et cum accepisset cibum, confortatus est.   Fuit autem cum discipulis qui erant Damasci per dies aliquot.

** Acts 9:20

Et continuo in synagogis prædicabat Jesum, quoniam hic est Filius Dei.

** Acts 9:21

Stupebant autem omnes qui audiebant, et dicebant : Nonne hic est qui expugnabat in Jerusalem eos qui invocabant nomen istud : et huc ad hoc venit, ut vinctos illos duceret ad principes sacerdotum ?

** Acts 9:22

Saulus autem multo magis convalescebat, et confundebat Judæos qui habitabant Damasci, affirmans quoniam hic est Christus.

** Acts 9:23

Cum autem implerentur dies multi, consilium fecerunt in unum Judæi ut eum interficerent.

** Acts 9:24

Notæ autem factæ sunt Saulo insidiæ eorum. Custodiebant autem et portas die ac nocte, ut eum interficerent.

** Acts 9:25

Accipientes autem eum discipuli nocte, per murum dimiserunt eum, submittentes in sporta.  

** Acts 9:26

Cum autem venisset in Jerusalem, tentabat se jungere discipulis, et omnes timebant eum, non credentes quod esset discipulus.

** Acts 9:27

Barnabas autem apprehensum illum duxit ad Apostolos : et narravit illis quomodo in via vidisset Dominum, et quia locutus est ei, et quomodo in Damasco fiducialiter egerit in nomine Jesu.

** Acts 9:28

Et erat cum illis intrans et exiens in Jerusalem, et fiducialiter agens in nomine Domini.

** Acts 9:29

Loquebatur quoque gentibus, et disputabat cum Græcis : illi autem quærebant occidere eum.  

** Acts 9:30

Quod cum cognovissent fratres, deduxerunt eum Cæsaream, et dimiserunt Tarsum.

** Acts 9:31

Ecclesia quidem per totam Judæam, et Galilæam, et Samariam habebat pacem, et ædificabatur ambulans in timore Domini, et consolatione Sancti Spiritus replebatur.  

** Acts 9:32

Factum est autem, ut Petrus dum pertransiret universos, deveniret ad sanctos qui habitabant Lyddæ.

** Acts 9:33

Invenit autem ibi hominem quemdam, nomine Æneam, ab annis octo jacentem in grabato, qui erat paralyticus.

** Acts 9:34

Et ait illi Petrus : Ænea, sanat te Dominus Jesus Christus : surge, et sterne tibi. Et continuo surrexit.

** Acts 9:35

Et viderunt eum omnes qui habitabant Lyddæ et Saronæ : qui conversi sunt ad Dominum.  

** Acts 9:36

In Joppe autem fuit quædam discipula, nomine Tabitha, quæ interpretata dicitur Dorcas. Hæc erat plena operibus bonis et eleemosynis quas faciebat.

** Acts 9:37

Factum est autem in diebus illis ut infirmata moreretur. Quam cum lavissent, posuerunt eam in cœnaculo.

** Acts 9:38

Cum autem prope esset Lydda ad Joppen, discipuli, audientes quia Petrus esset in ea, miserunt duos viros ad eum, rogantes : Ne pigriteris venire ad nos.

** Acts 9:39

Exsurgens autem Petrus, venit cum illis. Et cum advenisset, duxerunt illum in cœnaculum : et circumsteterunt illum omnes viduæ flentes, et ostendentes ei tunicas et vestes quas faciebat illis Dorcas.

** Acts 9:40

Ejectis autem omnibus foras, Petrus ponens genua oravit : et conversus ad corpus, dixit : Tabitha, surge. At illa aperuit oculos suos : et viso Petro, resedit.

** Acts 9:41

Dans autem illi manum, erexit eam. Et cum vocasset sanctos et viduas, assignavit eam vivam.

** Acts 9:42

Notum autem factum est per universam Joppen : et crediderunt multi in Domino.

** Acts 9:43

Factum est autem ut dies multos moraretur in Joppe, apud Simonem quemdam coriarium.   

* Acts 10

** Acts 10:1

Vir autem quidam erat in Cæsarea, nomine Cornelius, centurio cohortis quæ dicitur Italica,

** Acts 10:2

religiosus, ac timens Deum cum omni domo sua, faciens eleemosynas multas plebi, et deprecans Deum semper.

** Acts 10:3

Is vidit in visu manifeste, quasi hora diei nona, angelum Dei introëuntem ad se, et dicentem sibi : Corneli.

** Acts 10:4

At ille intuens eum, timore correptus, dixit : Quid est, domine ? Dixit autem illi : Orationes tuæ et eleemosynæ tuæ ascenderunt in memoriam in conspectu Dei.

** Acts 10:5

Et nunc mitte viros in Joppen, et accersi Simonem quemdam, qui cognominatur Petrus :

** Acts 10:6

hic hospitatur apud Simonem quemdam coriarium, cujus est domus juxta mare : hic dicet tibi quid te oporteat facere.

** Acts 10:7

Et cum discessisset angelus qui loquebatur illi, vocavit duos domesticos suos, et militem metuentem Dominum ex his qui illi parebant.

** Acts 10:8

Quibus cum narrasset omnia, misit illos in Joppen.  

** Acts 10:9

Postera autem die, iter illis facientibus, et appropinquantibus civitati, ascendit Petrus in superiora ut oraret circa horam sextam.

** Acts 10:10

Et cum esuriret, voluit gustare. Parantibus autem illis, cecidit super eum mentis excessus :

** Acts 10:11

et vidit cælum apertum, et descendens vas quoddam, velut linteum magnum, quatuor initiis submitti de cælo in terram,

** Acts 10:12

in quo erant omnia quadrupedia, et serpentia terræ, et volatilia cæli.

** Acts 10:13

Et facta est vox ad eum : Surge, Petre : occide, et manduca.

** Acts 10:14

Ait autem Petrus : Absit Domine, quia numquam manducavi omne commune et immundum.

** Acts 10:15

Et vox iterum secundo ad eum : Quod Deus purificavit, tu commune ne dixeris.

** Acts 10:16

Hoc autem factum est per ter : et statim receptum est vas in cælum.

** Acts 10:17

Et dum intra se hæsitaret Petrus quidnam esset visio quam vidisset, ecce viri qui missi erant a Cornelio, inquirentes domum Simonis astiterunt ad januam.

** Acts 10:18

Et cum vocassent, interrogabant, si Simon qui cognominatur Petrus illic haberet hospitium.

** Acts 10:19

Petro autem cogitante de visione, dixit Spiritus ei : Ecce viri tres quærunt te.

** Acts 10:20

Surge itaque, descende, et vade cum eis nihil dubitans : quia ego misi illos.

** Acts 10:21

Descendens autem Petrus ad viros, dixit : Ecce ego sum, quem quæritis : quæ causa est, propter quam venistis ?

** Acts 10:22

Qui dixerunt : Cornelius centurio, vir justus et timens Deum, et testimonium habens ab universa gente Judæorum, responsum accepit ab angelo sancto accersire te in domum suam, et audire verba abs te.

** Acts 10:23

Introducens ergo eos, recepit hospitio. Sequenti autem die, surgens profectus est cum illis, et quidam ex fratribus ab Joppe comitati sunt eum.  

** Acts 10:24

Altera autem die introivit Cæsaream. Cornelius vero exspectabat illos, convocatis cognatis suis et necessariis amicis.

** Acts 10:25

Et factum est cum introisset Petrus, obvius venit ei Cornelius, et procidens ad pedes ejus adoravit.

** Acts 10:26

Petrus vero elevavit eum, dicens : Surge : et ego ipse homo sum.

** Acts 10:27

Et loquens cum illo intravit, et invenit multos qui convenerant :

** Acts 10:28

dixitque ad illos : Vos scitis quomodo abominatum sit viro Judæo conjungi aut accedere ad alienigenam : sed mihi ostendit Deus neminem communem aut immundum dicere hominem.

** Acts 10:29

Propter quod sine dubitatione veni accersitus. Interrogo ergo, quam ob causam accersistis me ?

** Acts 10:30

Et Cornelius ait : A nudiusquarta die usque ad hanc horam, orans eram hora nona in domo mea, et ecce vir stetit ante me in veste candida, et ait :

** Acts 10:31

Corneli, exaudita est oratio tua, et eleemosynæ tuæ commemoratæ sunt in conspectu Dei.

** Acts 10:32

Mitte ergo in Joppen, et accersi Simonem qui cognominatur Petrus : hic hospitatur in domo Simonis coriarii juxta mare.

** Acts 10:33

Confestim ergo misi ad te : et tu benefecisti veniendo. Nunc ergo omnes nos in conspectu tuo adsumus audire omnia quæcumque tibi præcepta sunt a Domino.  

** Acts 10:34

Aperiens autem Petrus os suum, dixit : In veritate comperi quia non est personarum acceptor Deus ;

** Acts 10:35

sed in omni gente qui timet eum, et operatur justitiam, acceptus est illi.

** Acts 10:36

Verbum misit Deus filiis Israël, annuntians pacem per Jesum Christum (hic est omnium Dominus).

** Acts 10:37

Vos scitis quod factum est verbum per universam Judæam : incipiens enim a Galilæa post baptismum quod prædicavit Joannes,

** Acts 10:38

Jesum a Nazareth : quomodo unxit eum Deus Spiritu Sancto, et virtute, qui pertransiit benefaciendo, et sanando omnes oppressos a diabolo, quoniam Deus erat cum illo.

** Acts 10:39

Et nos testes sumus omnium quæ fecit in regione Judæorum, et Jerusalem, quem occiderunt suspendentes in ligno.

** Acts 10:40

Hunc Deus suscitavit tertia die, et dedit eum manifestum fieri,

** Acts 10:41

non omni populo, sed testibus præordinatis a Deo : nobis, qui manducavimus et bibimus cum illo postquam resurrexit a mortuis.

** Acts 10:42

Et præcepit nobis prædicare populo, et testificari, quia ipse est qui constitutus est a Deo judex vivorum et mortuorum.

** Acts 10:43

Huic omnes prophetæ testimonium perhibent remissionem peccatorum accipere per nomen ejus omnes qui credunt in eum.  

** Acts 10:44

Adhuc loquente Petro verba hæc, cecidit Spiritus Sanctus super omnes qui audiebant verbum.

** Acts 10:45

Et obstupuerunt ex circumcisione fideles qui venerant cum Petro, quia et in nationes gratia Spiritus Sancti effusa est.

** Acts 10:46

Audiebant enim illos loquentes linguis, et magnificantes Deum.

** Acts 10:47

Tunc respondit Petrus : Numquid aquam quis prohibere potest ut non baptizentur hi qui Spiritum Sanctum acceperunt sicut et nos ?

** Acts 10:48

Et jussit eos baptizari in nomine Domini Jesu Christi. Tunc rogaverunt eum ut maneret apud eos aliquot diebus.   

* Acts 11

** Acts 11:1

Audierunt autem Apostoli et fratres qui erant in Judæa, quoniam et gentes receperunt verbum Dei.

** Acts 11:2

Cum autem ascendisset Petrus Jerosolymam, disceptabant adversus illum qui erant ex circumcisione,

** Acts 11:3

dicentes : Quare introisti ad viros præputium habentes, et manducasti cum illis ?

** Acts 11:4

Incipiens autem Petrus exponebat illis ordinem, dicens :

** Acts 11:5

Ego eram in civitate Joppe orans, et vidi in excessu mentis visionem, descendens vas quoddam velut linteum magnum quatuor initiis summitti de cælo, et venit usque ad me.

** Acts 11:6

In quod intuens considerabam, et vidi quadrupedia terræ, et bestias, et reptilia, et volatilia cæli.

** Acts 11:7

Audivi autem et vocem dicentem mihi : Surge, Petre : occide, et manduca.

** Acts 11:8

Dixi autem : Nequaquam Domine : quia commune aut immundum numquam introivit in os meum.

** Acts 11:9

Respondit autem vox secundo de cælo : Quæ Deus mundavit, tu ne commune dixeris.

** Acts 11:10

Hoc autem factum est per ter : et recepta sunt omnia rursum in cælum.

** Acts 11:11

Et ecce viri tres confestim astiterunt in domo in qua eram, missi a Cæsarea ad me.

** Acts 11:12

Dixit autem Spiritus mihi ut irem cum illis, nihil hæsitans. Venerunt autem mecum et sex fratres isti, et ingressi sumus in domum viri.

** Acts 11:13

Narravit autem nobis quomodo vidisset angelum in domo sua, stantem et dicentem sibi : Mitte in Joppen, et accersi Simonem qui cognominatur Petrus,

** Acts 11:14

qui loquetur tibi verba in quibus salvus eris tu, et universa domus tua.

** Acts 11:15

Cum autem cœpissem loqui, cecidit Spiritus Sanctus super eos, sicut et in nos in initio.

** Acts 11:16

Recordatus sum autem verbi Domini, sicut dicebat : Joannes quidem baptizavit aqua, vos autem baptizabimini Spiritu Sancto.

** Acts 11:17

Si ergo eamdem gratiam dedit illis Deus, sicut et nobis qui credidimus in Dominum Jesum Christum : ego quis eram, qui possem prohibere Deum ?

** Acts 11:18

His auditis, tacuerunt : et glorificaverunt Deum, dicentes : Ergo et gentibus pœnitentiam dedit Deus ad vitam.  

** Acts 11:19

Et illi quidem qui dispersi fuerant a tribulatione quæ facta fuerat sub Stephano, perambulaverunt usque Phœnicen, et Cyprum, et Antiochiam, nemini loquentes verbum, nisi solis Judæis.

** Acts 11:20

Erant autem quidam ex eis viri Cyprii et Cyrenæi, qui cum introissent Antiochiam, loquebantur et ad Græcos, annuntiantes Dominum Jesum.

** Acts 11:21

Et erat manus Domini cum eis : multusque numerus credentium conversus est ad Dominum.

** Acts 11:22

Pervenit autem sermo ad aures ecclesiæ quæ erat Jerosolymis super istis : et miserunt Barnabam usque ad Antiochiam.

** Acts 11:23

Qui cum pervenisset, et vidisset gratiam Dei, gavisus est : et hortabatur omnes in proposito cordis permanere in Domino :

** Acts 11:24

quia erat vir bonus, et plenus Spiritu Sancto, et fide. Et apposita est multa turba Domino.  

** Acts 11:25

Profectus est autem Barnabas Tarsum, ut quæreret Saulum : quem cum invenisset, perduxit Antiochiam.

** Acts 11:26

Et annum totum conversati sunt ibi in ecclesia : et docuerunt turbam multam, ita ut cognominarentur primum Antiochiæ discipuli, christiani.

** Acts 11:27

In his autem diebus supervenerunt ab Jerosolymis prophetæ Antiochiam :

** Acts 11:28

et surgens unus ex eis nomine Agabus, significabat per spiritum famem magnam futuram in universo orbe terrarum, quæ facta est sub Claudio.

** Acts 11:29

Discipuli autem, prout quis habebat, proposuerunt singuli in ministerium mittere habitantibus in Judæa fratribus :

** Acts 11:30

quod et fecerunt, mittentes ad seniores per manus Barnabæ et Sauli.   

* Acts 12

** Acts 12:1

Eodem autem tempore misit Herodes rex manus, ut affligeret quosdam de ecclesia.

** Acts 12:2

Occidit autem Jacobum fratrem Joannis gladio.

** Acts 12:3

Videns autem quia placeret Judæis, apposuit ut apprehenderet et Petrum. Erant autem dies Azymorum.

** Acts 12:4

Quem cum apprehendisset, misit in carcerem, tradens quatuor quaternionibus militum custodiendum, volens post Pascha producere eum populo.

** Acts 12:5

Et Petrus quidem servabatur in carcere. Oratio autem fiebat sine intermissione ab ecclesia ad Deum pro eo.  

** Acts 12:6

Cum autem producturus eum esset Herodes, in ipsa nocte erat Petrus dormiens inter duos milites, vinctus catenis duabus : et custodes ante ostium custodiebant carcerem.

** Acts 12:7

Et ecce angelus Domini astitit, et lumen refulsit in habitaculo : percussoque latere Petri, excitavit eum, dicens : Surge velociter. Et ceciderunt catenæ de manibus ejus.

** Acts 12:8

Dixit autem angelus ad eum : Præcingere, et calcea te caligas tuas. Et fecit sic. Et dixit illi : Circumda tibi vestimentum tuum, et sequere me.

** Acts 12:9

Et exiens sequebatur eum, et nesciebat quia verum est, quod fiebat per angelum : existimabat autem se visum videre.

** Acts 12:10

Transeuntes autem primam et secundam custodiam, venerunt ad portam ferream, quæ ducit ad civitatem : quæ ultro aperta est eis. Et exeuntes processerunt vicum unum : et continuo discessit angelus ab eo.  

** Acts 12:11

Et Petrus ad se reversus, dixit : Nunc scio vere quia misit Dominus angelum suum, et eripuit me de manu Herodis, et de omni exspectatione plebis Judæorum.

** Acts 12:12

Consideransque venit ad domum Mariæ matris Joannis, qui cognominatus est Marcus, ubi erant multi congregati, et orantes.

** Acts 12:13

Pulsante autem eo ostium januæ, processit puella ad audiendum, nomine Rhode.

** Acts 12:14

Et ut cognovit vocem Petri, præ gaudio non aperuit januam, sed intro currens nuntiavit stare Petrum ante januam.

** Acts 12:15

At illi dixerunt ad eam : Insanis. Illa autem affirmabat sic se habere. Illi autem dicebant : Angelus ejus est.

** Acts 12:16

Petrus autem perseverabat pulsans. Cum autem aperuissent, viderunt eum, et obstupuerunt.

** Acts 12:17

Annuens autem eis manu ut tacerent, narravit quomodo Dominus eduxisset eum de carcere, dixitque : Nuntiate Jacobo et fratribus hæc. Et egressus abiit in alium locum.  

** Acts 12:18

Facta autem die, erat non parva turbatio inter milites, quidnam factum esset de Petro.

** Acts 12:19

Herodes autem cum requisisset eum et non invenisset, inquisitione facta de custodibus, jussit eos duci : descendensque a Judæa in Cæsaream, ibi commoratus est.

** Acts 12:20

Erat autem iratus Tyriis et Sidoniis. At illi unanimes venerunt ad eum, et persuaso Blasto, qui erat super cubiculum regis, postulabant pacem, eo quod alerentur regiones eorum ab illo.

** Acts 12:21

Statuto autem die Herodes vestitus veste regia sedit pro tribunali, et concionabatur ad eos.

** Acts 12:22

Populus autem acclamabat : Dei voces, et non hominis.

** Acts 12:23

Confestim autem percussit eum angelus Domini, eo quod non dedisset honorem Deo : et consumptus a vermibus, expiravit.

** Acts 12:24

Verbum autem Domini crescebat, et multiplicabatur.

** Acts 12:25

Barnabas autem et Saulus reversi sunt ab Jerosolymis expleto ministerio assumpto Joanne, qui cognominatus est Marcus.   

* Acts 13

** Acts 13:1

Erant autem in ecclesia quæ erat Antiochiæ, prophetæ et doctores, in quibus Barnabas, et Simon qui vocabatur Niger, et Lucius Cyrenensis, et Manahen, qui erat Herodis Tetrarchæ collactaneus, et Saulus.

** Acts 13:2

Ministrantibus autem illis Domino, et jejunantibus, dixit illis Spiritus Sanctus : Segregate mihi Saulum et Barnabam in opus ad quod assumpsi eos.

** Acts 13:3

Tunc jejunantes et orantes, imponentesque eis manus, dimiserunt illos.  

** Acts 13:4

Et ipsi quidem missi a Spiritu Sancto abierunt Seleuciam : et inde navigaverunt Cyprum.

** Acts 13:5

Et cum venissent Salaminam, prædicabant verbum Dei in synagogis Judæorum. Habebant autem et Joannem in ministerio.

** Acts 13:6

Et cum perambulassent universam insulam usque Paphum, invenerunt quemdam virum magum pseudoprophetam, Judæum, cui nomen erat Barjesu,

** Acts 13:7

qui erat cum proconsule Sergio Paulo viro prudente. Hic, accersitis Barnaba et Saulo, desiderabat audire verbum Dei.

** Acts 13:8

Resistebat autem illis Elymas magus (sic enim interpretatur nomen ejus), quærens avertere proconsulem a fide.

** Acts 13:9

Saulus autem, qui et Paulus, repletus Spiritu Sancto, intuens in eum,

** Acts 13:10

dixit : O plene omni dolo et omni fallacia, fili diaboli, inimice omnis justitiæ, non desinis subvertere vias Domini rectas.

** Acts 13:11

Et nunc ecce manus Domini super te, et eris cæcus, non videns solem usque ad tempus. Et confestim cecidit in eum caligo et tenebræ : et circuiens quærebat qui ei manum daret.

** Acts 13:12

Tunc proconsul cum vidisset factum, credidit admirans super doctrina Domini.  

** Acts 13:13

Et cum a Papho navigassent Paulus et qui cum eo erant, venerunt Pergen Pamphyliæ. Joannes autem discedens ab eis, reversus est Jerosolymam.

** Acts 13:14

Illi vero pertranseuntes Pergen, venerunt Antiochiam Pisidiæ : et ingressi synagogam die sabbatorum, sederunt.

** Acts 13:15

Post lectionem autem legis et prophetarum, miserunt principes synagogæ ad eos, dicentes : Viri fratres, si quis est in vobis sermo exhortationis ad plebem, dicite.  

** Acts 13:16

Surgens autem Paulus, et manu silentium indicens, ait : Viri Israëlitæ, et qui timetis Deum, audite :

** Acts 13:17

Deus plebis Israël elegit patres nostros, et plebem exaltavit cum essent incolæ in terra Ægypti, et in brachio excelso eduxit eos ex ea,

** Acts 13:18

et per quadraginta annorum tempus mores eorum sustinuit in deserto.

** Acts 13:19

Et destruens gentes septem in terra Chanaan, sorte distribuit eis terram eorum,

** Acts 13:20

quasi post quadringentos et quinquaginta annos : et post hæc dedit judices, usque ad Samuel prophetam.

** Acts 13:21

Et exinde postulaverunt regem : et dedit illis Deus Saul filium Cis, virum de tribu Benjamin, annis quadraginta :

** Acts 13:22

et amoto illo, suscitavit illis David regem : cui testimonium perhibens, dixit : Inveni David filium Jesse, virum secundum cor meum, qui faciet omnes voluntates meas.

** Acts 13:23

Hujus Deus ex semine secundum promissionem eduxit Israël salvatorem Jesum,

** Acts 13:24

prædicante Joanne ante faciem adventus ejus baptismum pœnitentiæ omni populo Israël.

** Acts 13:25

Cum impleret autem Joannes cursum suum, dicebat : Quem me arbitramini esse, non sum ego : sed ecce venit post me, cujus non sum dignus calceamenta pedum solvere.

** Acts 13:26

Viri fratres, filii generis Abraham, et qui in vobis timent Deum, vobis verbum salutis hujus missum est.

** Acts 13:27

Qui enim habitabant Jerusalem, et principes ejus hunc ignorantes, et voces prophetarum quæ per omne sabbatum leguntur, judicantes impleverunt,

** Acts 13:28

et nullam causam mortis invenientes in eo, petierunt a Pilato ut interficerent eum.

** Acts 13:29

Cumque consummassent omnia quæ de eo scripta erant, deponentes eum de ligno, posuerunt eum in monumento.

** Acts 13:30

Deus vero suscitavit eum a mortuis tertia die : qui visus est per dies multos his

** Acts 13:31

qui simul ascenderant cum eo de Galilæa in Jerusalem : qui usque nunc sunt testes ejus ad plebem.

** Acts 13:32

Et nos vobis annuntiamus eam, quæ ad patres nostros repromissio facta est :

** Acts 13:33

quoniam hanc Deus adimplevit filiis nostris resuscitans Jesum, sicut et in psalmo secundo scriptum est : Filius meus es tu, ego hodie genui te.

** Acts 13:34

Quod autem suscitavit eum a mortuis, amplius jam non reversurum in corruptionem, ita dixit : Quia dabo vobis sancta David fidelia.

** Acts 13:35

Ideoque et alias dicit : Non dabis sanctum tuum videre corruptionem.

** Acts 13:36

David enim in sua generatione cum administrasset, voluntati Dei dormivit : et appositus est ad patres suos, et vidit corruptionem.

** Acts 13:37

Quem vero Deus suscitavit a mortuis, non vidit corruptionem.

** Acts 13:38

Notum igitur sit vobis, viri fratres, quia per hunc vobis remissio peccatorum annuntiatur, et ab omnibus quibus non potuistis in lege Moysi justificari,

** Acts 13:39

in hoc omnis qui credit, justificatur.

** Acts 13:40

Videte ergo ne superveniat vobis quod dictum est in prophetis :  

** Acts 13:41

Videte contemptores, et admiramini, et disperdimini :  quia opus operor ego in diebus vestris,  opus quod non credetis, si quis enarraverit vobis.

** Acts 13:42

Exeuntibus autem illis rogabant ut sequenti sabbato loquerentur sibi verba hæc.

** Acts 13:43

Cumque dimissa esset synagoga, secuti sunt multi Judæorum, et colentium advenarum, Paulum et Barnabam : qui loquentes suadebant eis ut permanerent in gratia Dei.  

** Acts 13:44

Sequenti vero sabbato pene universa civitas convenit audire verbum Dei.

** Acts 13:45

Videntes autem turbas Judæi, repleti sunt zelo, et contradicebant his quæ a Paulo dicebantur, blasphemantes.

** Acts 13:46

Tunc constanter Paulus et Barnabas dixerunt : Vobis oportebat primum loqui verbum Dei : sed quoniam repellitis illud, et indignos vos judicatis æternæ vitæ, ecce convertimur ad gentes.

** Acts 13:47

Sic enim præcepit nobis Dominus : Posui te in lucem gentium, ut sis in salutem usque ad extremum terræ.

** Acts 13:48

Audientes autem gentes, gavisæ sunt, et glorificabant verbum Domini : et crediderunt quotquot erant præordinati ad vitam æternam.

** Acts 13:49

Disseminabatur autem verbum Domini per universam regionem.

** Acts 13:50

Judæi autem concitaverunt mulieres religiosas et honestas, et primos civitatis, et excitaverunt persecutionem in Paulum et Barnabam : et ejecerunt eos de finibus suis.

** Acts 13:51

At illi excusso pulvere pedum in eos, venerunt Iconium.

** Acts 13:52

Discipuli quoque replebantur gaudio, et Spiritu Sancto.   

* Acts 14

** Acts 14:1

Factum est autem Iconii, ut simul introirent in synagogam Judæorum, et loquerentur, ita ut crederet Judæorum et Græcorum copiosa multitudo.

** Acts 14:2

Qui vero increduli fuerunt Judæi, suscitaverunt et ad iracundiam concitaverunt animas gentium adversus fratres.

** Acts 14:3

Multo igitur tempore demorati sunt, fiducialiter agentes in Domino, testimonium perhibente verbo gratiæ suæ, dante signa et prodigia fieri per manus eorum.

** Acts 14:4

Divisa est autem multitudo civitatis : et quidam quidem erant cum Judæis, quidam vero cum Apostolis.  

** Acts 14:5

Cum autem factus esset impetus gentilium et Judæorum cum principibus suis, ut contumeliis afficerent, et lapidarent eos,

** Acts 14:6

intelligentes confugerunt ad civitates Lycaoniæ Lystram et Derben, et universam in circuitu regionem, et ibi evangelizantes erant.

** Acts 14:7

Et quidam vir Lystris infirmus pedibus sedebat, claudus ex utero matris suæ, qui numquam ambulaverat.

** Acts 14:8

Hic audivit Paulum loquentem. Qui intuitus eum, et videns quia fidem haberet ut salvus fieret,

** Acts 14:9

dixit magna voce : Surge super pedes tuos rectus. Et exilivit, et ambulabat.

** Acts 14:10

Turbæ autem cum vidissent quod fecerat Paulus, levaverunt vocem suam lycaonice, dicentes : Dii similes facti hominibus descenderunt ad nos.

** Acts 14:11

Et vocabant Barnabam Jovem, Paulum vero Mercurium : quoniam ipse erat dux verbi.

** Acts 14:12

Sacerdos quoque Jovis, qui erat ante civitatem, tauros et coronas ante januas afferens, cum populis volebat sacrificare.

** Acts 14:13

Quod ubi audierunt Apostoli, Barnabas et Paulus, conscissis tunicis suis exilierunt in turbas, clamantes

** Acts 14:14

et dicentes : Viri, quid hæc facitis ? et nos mortales sumus, similes vobis homines, annuntiantes vobis ab his vanis converti ad Deum vivum, qui fecit cælum, et terram, et mare, et omnia quæ in eis sunt :

** Acts 14:15

qui in præteritis generationibus dimisit omnes gentes ingredi vias suas.

** Acts 14:16

Et quidem non sine testimonio semetipsum reliquit benefaciens de cælo, dans pluvias et tempora fructifera, implens cibo et lætitia corda nostra.

** Acts 14:17

Et hæc dicentes, vix sedaverunt turbas ne sibi immolarent.

** Acts 14:18

Supervenerunt autem quidam ab Antiochia et Iconio Judæi : et persuasis turbis, lapidantesque Paulum, traxerunt extra civitatem, existimantes eum mortuum esse.

** Acts 14:19

Circumdantibus autem eum discipulis, surgens intravit civitatem, et postera die profectus est cum Barnaba in Derben.  

** Acts 14:20

Cumque evangelizassent civitati illi, et docuissent multos, reversi sunt Lystram, et Iconium, et Antiochiam,

** Acts 14:21

confirmantes animas discipulorum, exhortantesque ut permanerent in fide : et quoniam per multas tribulationes oportet nos intrare in regnum Dei.

** Acts 14:22

Et cum constituissent illis per singulas ecclesias presbyteros, et orassent cum jejunationibus, commendaverunt eos Domino, in quem crediderunt.

** Acts 14:23

Transeuntesque Pisidiam, venerunt in Pamphyliam,

** Acts 14:24

et loquentes verbum Domini in Perge, descenderunt in Attaliam :

** Acts 14:25

et inde navigaverunt Antiochiam, unde erant traditi gratiæ Dei in opus quod compleverunt.

** Acts 14:26

Cum autem venissent, et congregassent ecclesiam, retulerunt quanta fecisset Deus cum illis, et quia aperuisset gentibus ostium fidei.

** Acts 14:27

Morati sunt autem tempus non modicum cum discipulis.   

* Acts 15

** Acts 15:1

Et quidam descendentes de Judæa docebant fratres : Quia nisi circumcidamini secundum morem Moysi, non potestis salvari.

** Acts 15:2

Facta ergo seditione non minima Paulo et Barnabæ adversus illos, statuerunt ut ascenderent Paulus et Barnabas, et quidam alii ex aliis ad Apostolos et presbyteros in Jerusalem super hac quæstione.

** Acts 15:3

Illi ergo deducti ab ecclesia pertransibant Phœnicen et Samariam, narrantes conversionem gentium : et faciebant gaudium magnum omnibus fratribus.

** Acts 15:4

Cum autem venissent Jerosolymam, suscepti sunt ab ecclesia, et ab Apostolis et senioribus, annuntiantes quanta Deus fecisset cum illis.

** Acts 15:5

Surrexerunt autem quidam de hæresi pharisæorum, qui crediderunt, dicentes quia oportet circumcidi eos, præcipere quoque servare legem Moysi.

** Acts 15:6

Conveneruntque Apostoli et seniores videre de verbo hoc.

** Acts 15:7

Cum autem magna conquisitio fieret, surgens Petrus dixit ad eos : Viri fratres, vos scitis quoniam ab antiquis diebus Deus in nobis elegit, per os meum audire gentes verbum Evangelii et credere.

** Acts 15:8

Et qui novit corda Deus, testimonium perhibuit, dans illis Spiritum Sanctum, sicut et nobis,

** Acts 15:9

et nihil discrevit inter nos et illos, fide purificans corda eorum.

** Acts 15:10

Nunc ergo quid tentatis Deum, imponere jugum super cervices discipulorum quod neque patres nostri, neque nos portare potuimus ?

** Acts 15:11

sed per gratiam Domini Jesu Christi credimus salvari, quemadmodum et illi.

** Acts 15:12

Tacuit autem omnis multitudo : et audiebant Barnabam et Paulum narrantes quanta Deus fecisset signa et prodigia in gentibus per eos.  

** Acts 15:13

Et postquam tacuerunt, respondit Jacobus, dicens : Viri fratres, audite me.

** Acts 15:14

Simon narravit quemadmodum primum Deus visitavit sumere ex gentibus populum nomini suo.

** Acts 15:15

Et huic concordant verba prophetarum : sicut scriptum est :  

** Acts 15:16

Post hæc revertar,  et reædificabo tabernaculum David quod decidit :  et diruta ejus reædificabo,  et erigam illud : 

** Acts 15:17

ut requirant ceteri hominum Dominum,  et omnes gentes super quas invocatum est nomen meum,  dicit Dominus faciens hæc. 

** Acts 15:18

Notum a sæculo est Domino opus suum.

** Acts 15:19

Propter quod ego judico non inquietari eos qui ex gentibus convertuntur ad Deum,

** Acts 15:20

sed scribere ad eos ut abstineant se a contaminationibus simulacrorum, et fornicatione, et suffocatis, et sanguine.

** Acts 15:21

Moyses enim a temporibus antiquis habet in singulis civitatibus qui eum prædicent in synagogis, ubi per omne sabbatum legitur.  

** Acts 15:22

Tunc placuit Apostolis et senioribus cum omni ecclesia eligere viros ex eis, et mittere Antiochiam cum Paulo et Barnaba : Judam, qui cognominabatur Barsabas, et Silam, viros primos in fratribus :

** Acts 15:23

scribentes per manus eorum : Apostoli et seniores fratres, his qui sunt Antiochiæ, et Syriæ, et Ciliciæ, fratribus ex gentibus, salutem.

** Acts 15:24

Quoniam audivimus quia quidam ex nobis exeuntes, turbaverunt vos verbis, evertentes animas vestras, quibus non mandavimus,

** Acts 15:25

placuit nobis collectis in unum eligere viros, et mittere ad vos cum carissimis nostris Barnaba et Paulo,

** Acts 15:26

hominibus qui tradiderunt animas suas pro nomine Domini nostri Jesu Christi.

** Acts 15:27

Misimus ergo Judam et Silam, qui et ipsi vobis verbis referent eadem.

** Acts 15:28

Visum est enim Spiritui Sancto et nobis nihil ultra imponere vobis oneris quam hæc necessaria :

** Acts 15:29

ut abstineatis vos ab immolatis simulacrorum, et sanguine, et suffocato, et fornicatione : a quibus custodientes vos, bene agetis. Valete.

** Acts 15:30

Illi ergo dimissi, descenderunt Antiochiam : et congregata multitudine tradiderunt epistolam.

** Acts 15:31

Quam cum legissent, gavisi sunt super consolatione.

** Acts 15:32

Judas autem et Silas, et ipsi cum essent prophetæ, verbo plurimo consolati sunt fratres, et confirmaverunt.

** Acts 15:33

Facto autem ibi aliquanto tempore, dimissi sunt cum pace a fratribus ad eos qui miserant illos.

** Acts 15:34

Visum est autem Silæ ibi remanere : Judas autem solus abiit Jerusalem.  

** Acts 15:35

Paulus autem et Barnabas demorabantur Antiochiæ, docentes et evangelizantes cum aliis pluribus verbum Domini.

** Acts 15:36

Post aliquot autem dies, dixit ad Barnabam Paulus : Revertentes visitemus fratres per universas civitates in quibus prædicavimus verbum Domini, quomodo se habeant.

** Acts 15:37

Barnabas autem volebat secum assumere et Joannem, qui cognominabatur Marcus.

** Acts 15:38

Paulus autem rogabat eum (ut qui discessisset ab eis de Pamphylia, et non isset cum eis in opus) non debere recipi.

** Acts 15:39

Facta est autem dissensio, ita ut discederent ab invicem, et Barnabas quidem, assumpto Marco, navigaret Cyprum.  

** Acts 15:40

Paulus vero, electo Sila, profectus est, traditus gratiæ Dei a fratribus.

** Acts 15:41

Perambulabat autem Syriam et Ciliciam, confirmans ecclesias : præcipiens custodire præcepta Apostolorum et seniorum.   

* Acts 16

** Acts 16:1

Pervenit autem Derben et Lystram. Et ecce discipulus quidam erat ibi nomine Timotheus, filius mulieris Judææ fidelis, patre gentili.

** Acts 16:2

Huic testimonium bonum reddebant qui in Lystris erant et Iconio fratres.

** Acts 16:3

Hunc voluit Paulus secum proficisci : et assumens circumcidit eum propter Judæos qui erant in illis locis. Sciebant enim omnes quod pater ejus erat gentilis.

** Acts 16:4

Cum autem pertransirent civitates, tradebant eis custodiri dogmata quæ erant decreta ab Apostolis et senioribus qui erant Jerosolymis.

** Acts 16:5

Et ecclesiæ quidem confirmabantur fide, et abundabunt numero quotidie.

** Acts 16:6

Transeuntes autem Phrygiam et Galatiæ regionem, vetati sunt a Spiritu Sancto loqui verbum Dei in Asia.

** Acts 16:7

Cum venissent autem in Mysiam, tentabant ire in Bithyniam : et non permisit eos Spiritus Jesu.

** Acts 16:8

Cum autem pertransissent Mysiam, descenderunt Troadem :

** Acts 16:9

et visio per noctem Paulo ostensa est : vir Macedo quidam erat stans et deprecans eum, et dicens : Transiens in Macedoniam, adjuva nos.  

** Acts 16:10

Ut autem visum vidit, statim quæsivimus proficisci in Macedoniam, certi facti quod vocasset nos Deus evangelizare eis.

** Acts 16:11

Navigantes autem a Troade, recto cursu venimus Samothraciam, et sequenti die Neapolim :

** Acts 16:12

et inde Philippos, quæ est prima partis Macedoniæ civitas, colonia. Eramus autem in hac urbe diebus aliquot, conferentes.

** Acts 16:13

Die autem sabbatorum egressi sumus foras portam juxta flumen, ubi videbatur oratio esse : et sedentes loquebamur mulieribus quæ convenerant.

** Acts 16:14

Et quædam mulier nomine Lydia, purpuraria civitatis Thyatirenorum, colens Deum, audivit : cujus Dominus aperuit cor intendere his quæ dicebantur a Paulo.

** Acts 16:15

Cum autem baptizata esset, et domus ejus, deprecata est, dicens : Si judicastis me fidelem Domino esse, introite in domum meam, et manete. Et coëgit nos.

** Acts 16:16

Factum est autem euntibus nobis ad orationem, puellam quamdam habentem spiritum pythonem obviare nobis, quæ quæstum magnum præstabat dominis suis divinando.

** Acts 16:17

Hæc subsecuta Paulum et nos, clamabat dicens : Isti homines servi Dei excelsi sunt, qui annuntiant vobis viam salutis.

** Acts 16:18

Hoc autem faciebat multis diebus. Dolens autem Paulus, et conversus, spiritui dixit : Præcipio tibi in nomine Jesu Christi exire ab ea. Et exiit eadem hora.

** Acts 16:19

Videntes autem domini ejus quia exivit spes quæstus eorum, apprehendentes Paulum et Silam, perduxerunt in forum ad principes :

** Acts 16:20

et offerentes eos magistratibus, dixerunt : Hi homines conturbant civitatem nostram, cum sint Judæi :

** Acts 16:21

et annuntiant morem quem non licet nobis suscipere neque facere, cum simus Romani.  

** Acts 16:22

Et cucurrit plebs adversus eos : et magistratus, scissis tunicis eorum, jusserunt eos virgis cædi.

** Acts 16:23

Et cum multas plagas eis imposuissent, miserunt eos in carcerem, præcipientes custodi ut diligenter custodiret eos.

** Acts 16:24

Qui cum tale præceptum accepisset, misit eos in interiorem carcerem, et pedes eorum strinxit ligno.

** Acts 16:25

Media autem nocte Paulus et Silas orantes, laudabant Deum : et audiebant eos qui in custodia erant.

** Acts 16:26

Subito vero terræmotus factus est magnus, ita ut moverentur fundamenta carceris. Et statim aperta sunt omnia ostia : et universorum vincula soluta sunt.

** Acts 16:27

Expergefactus autem custos carceris, et videns januas apertas carceris, evaginato gladio volebat se interficere, æstimans fugisse vinctos.

** Acts 16:28

Clamavit autem Paulus voce magna, dicens : Nihil tibi mali feceris : universi enim hic sumus.

** Acts 16:29

Petitoque lumine, introgressus est : et tremefactus procidit Paulo et Silæ ad pedes :

** Acts 16:30

et producens eos foras, ait : Domini, quid me oportet facere, ut salvus fiam ?

** Acts 16:31

At illi dixerunt : Crede in Dominum Jesum, et salvus eris tu, et domus tua.

** Acts 16:32

Et locuti sunt ei verbum Domini cum omnibus qui erant in domo ejus.

** Acts 16:33

Et tollens eos in illa hora noctis, lavit plagas eorum : et baptizatus est ipse, et omnis domus ejus continuo.

** Acts 16:34

Cumque perduxisset eos in domum suam, apposuit eis mensam, et lætatus est cum omni domo sua credens Deo.  

** Acts 16:35

Et cum dies factus esset, miserunt magistratus lictores, dicentes : Dimitte homines illos.

** Acts 16:36

Nuntiavit autem custos carceris verba hæc Paulo : Quia miserunt magistratus ut dimittamini : nunc igitur exeuntes, ite in pace.

** Acts 16:37

Paulus autem dixit eis : Cæsos nos publice, indemnatos homines Romanos, miserunt in carcerem : et nunc occulte nos ejiciunt ? Non ita : sed veniant,

** Acts 16:38

et ipsi nos ejiciant. Nuntiaverunt autem magistratibus lictores verba hæc. Timueruntque audito quod Romani essent :

** Acts 16:39

et venientes deprecati sunt eos, et educentes rogabant ut egrederentur de urbe.

** Acts 16:40

Exeuntes autem de carcere, introierunt ad Lydiam : et visis fratribus consolati sunt eos, et profecti sunt.   

* Acts 17

** Acts 17:1

Cum autem perambulassent Amphipolim et Apolloniam, venerunt Thessalonicam, ubi erat synagoga Judæorum.

** Acts 17:2

Secundum consuetudinem autem Paulus introivit ad eos, et per sabbata tria disserebat eis de Scripturis,

** Acts 17:3

adaperiens et insinuans quia Christum oportuit pati, et resurgere a mortuis : et quia hic est Jesus Christus, quem ego annuntio vobis.

** Acts 17:4

Et quidam ex eis crediderunt et adjuncti sunt Paulo et Silæ : et de colentibus gentilibusque multitudo magna, et mulieres nobiles non paucæ.

** Acts 17:5

Zelantes autem Judæi, assumentesque de vulgo viros quosdam malos, et turba facta, concitaverunt civitatem : et assistentes domui Jasonis quærebant eos producere in populum.

** Acts 17:6

Et cum non invenissent eos, trahebant Jasonem et quosdam fratres ad principes civitatis, clamantes : Quoniam hi qui urbem concitant, et huc venerunt,

** Acts 17:7

quos suscepit Jason, et hi omnes contra decreta Cæsaris faciunt, regem alium dicentes esse, Jesum.

** Acts 17:8

Concitaverunt autem plebem et principes civitatis audientes hæc.

** Acts 17:9

Et accepta satisfactione a Jasone et a ceteris, dimiserunt eos.  

** Acts 17:10

Fratres vero confestim per noctem dimiserunt Paulum et Silam in Berœam. Qui cum venissent, in synagogam Judæorum introierunt.

** Acts 17:11

Hi autem erant nobiliores eorum qui sunt Thessalonicæ, qui susceperunt verbum cum omni aviditate, quotidie scrutantes Scripturas, si hæc ita se haberent.

** Acts 17:12

Et multi quidem crediderunt ex eis, et mulierum gentilium honestarum, et viri non pauci.

** Acts 17:13

Cum autem cognovissent in Thessalonica Judæi quia et Berœæ prædicatum est a Paulo verbum Dei, venerunt et illuc commoventes, et turbantes multitudinem.

** Acts 17:14

Statimque tunc Paulum dimiserunt fratres, ut iret usque ad mare : Silas autem et Timotheus remanserunt ibi.  

** Acts 17:15

Qui autem deducebant Paulum, perduxerunt eum usque Athenas, et accepto mandato ab eo ad Silam et Timotheum ut quam celeriter venirent ad illum, profecti sunt.

** Acts 17:16

Paulus autem cum Athenis eos exspectaret, incitabatur spiritus ejus in ipso, videns idololatriæ deditam civitatem.

** Acts 17:17

Disputabat igitur in synagoga cum Judæis et colentibus, et in foro, per omnes dies ad eos qui aderant.

** Acts 17:18

Quidam autem epicurei et stoici philosophi disserebant cum eo, et quidam dicebant : Quid vult seminiverbius hic dicere ? Alii vero : Novorum dæmoniorum videtur annuntiator esse : quia Jesum et resurrectionem annuntiabat eis.  

** Acts 17:19

Et apprehensum eum ad Areopagum duxerunt, dicentes : Possumus scire quæ est hæc nova, quæ a te dicitur, doctrina ?

** Acts 17:20

nova enim quædam infers auribus nostris : volumus ergo scire quidnam velint hæc esse.

** Acts 17:21

(Athenienses autem omnes, et advenæ hospites, ad nihil aliud vacabant nisi aut dicere aut audire aliquid novi.)

** Acts 17:22

Stans autem Paulus in medio Areopagi, ait : Viri Athenienses, per omnia quasi superstitiosiores vos video.

** Acts 17:23

Præteriens enim, et videns simulacra vestra, inveni et aram in qua scriptum erat : Ignoto Deo. Quod ergo ignorantes colitis, hoc ego annuntio vobis.

** Acts 17:24

Deus, qui fecit mundum, et omnia quæ in eo sunt, hic cæli et terræ cum sit Dominus, non in manufactis templis habitat,

** Acts 17:25

nec manibus humanis colitur indigens aliquo, cum ipse det omnibus vitam, et inspirationem, et omnia :

** Acts 17:26

fecitque ex uno omne genus hominum inhabitare super universam faciem terræ, definiens statuta tempora, et terminos habitationis eorum,

** Acts 17:27

quærere Deum si forte attrectent eum, aut inveniant, quamvis non longe sit ab unoquoque nostrum.

** Acts 17:28

In ipso enim vivimus, et movemur, et sumus : sicut et quidam vestrorum poëtarum dixerunt : Ipsius enim et genus sumus.

** Acts 17:29

Genus ergo cum simus Dei, non debemus æstimare auro, aut argento, aut lapidi, sculpturæ artis, et cogitationis hominis, divinum esse simile.

** Acts 17:30

Et tempora quidem hujus ignorantiæ despiciens Deus, nunc annuntiat hominibus ut omnes ubique pœnitentiam agant,

** Acts 17:31

eo quod statuit diem in quo judicaturus est orbem in æquitate, in viro in quo statuit, fidem præbens omnibus, suscitans eum a mortuis.

** Acts 17:32

Cum audissent autem resurrectionem mortuorum, quidam quidem irridebant, quidam vero dixerunt : Audiemus te de hoc iterum.

** Acts 17:33

Sic Paulus exivit de medio eorum.

** Acts 17:34

Quidam vero viri adhærentes ei, crediderunt : in quibus et Dionysius Areopagita, et mulier nomine Damaris, et alii cum eis.   

* Acts 18

** Acts 18:1

Post hæc egressus ab Athenis, venit Corinthum :

** Acts 18:2

et inveniens quemdam Judæum nomine Aquilam, Ponticum genere, qui nuper venerat ab Italia, et Priscillam uxorem ejus (eo quod præcepisset Claudius discedere omnes Judæos a Roma), accessit ad eos.

** Acts 18:3

Et quia ejusdem erat artis, manebat apud eos, et operabatur. (Erant autem scenofactoriæ artis.)

** Acts 18:4

Et disputabat in synagoga per omne sabbatum, interponens nomen Domini Jesu : suadebatque Judæis et Græcis.

** Acts 18:5

Cum venissent autem de Macedonia Silas et Timotheus, instabat verbo Paulus, testificans Judæis esse Christum Jesum.

** Acts 18:6

Contradicentibus autem eis, et blasphemantibus, excutiens vestimenta sua, dixit ad eos : Sanguis vester super caput vestrum : mundus ego : ex hoc ad gentes vadam.

** Acts 18:7

Et migrans inde, intravit in domum cujusdam, nomine Titi Justi, colentis Deum, cujus domus erat conjuncta synagogæ.

** Acts 18:8

Crispus autem archisynagogus credidit Domino cum omni domo sua : et multi Corinthiorum audientes credebant, et baptizabantur.

** Acts 18:9

Dixit autem Dominus nocte per visionem Paulo : Noli timere, sed loquere, et ne taceas :

** Acts 18:10

propter quod ego sum tecum, et nemo apponetur tibi ut noceat te : quoniam populus est mihi multus in hac civitate.

** Acts 18:11

Sedit autem ibi annum et sex menses, docens apud eos verbum Dei.  

** Acts 18:12

Gallione autem proconsule Achaiæ, insurrexerunt uno animo Judæi in Paulum, et adduxerunt eum ad tribunal,

** Acts 18:13

dicentes : Quia contra legem hic persuadet hominibus colere Deum.

** Acts 18:14

Incipiente autem Paulo aperire os, dixit Gallio ad Judæos : Si quidem esset iniquum aliquid aut facinus pessimum, o viri Judæi, recte vos sustinerem.

** Acts 18:15

Si vero quæstiones sunt de verbo, et nominibus, et lege vestra, vos ipsi videritis : judex ego horum nolo esse.

** Acts 18:16

Et minavit eos a tribunali.

** Acts 18:17

Apprehendentes autem omnes Sosthenem principem synagogæ, percutiebant eum ante tribunal : et nihil eorum Gallioni curæ erat.  

** Acts 18:18

Paulus vero cum adhuc sustinuisset dies multos fratribus valefaciens, navigavit in Syriam (et cum eo Priscilla et Aquila), qui sibi totonderat in Cenchris caput : habebat enim votum.

** Acts 18:19

Devenitque Ephesum, et illos ibi reliquit. Ipse vero ingressus synagogam, disputabat cum Judæis.

** Acts 18:20

Rogantibus autem eis ut ampliori tempore maneret, non consensit,

** Acts 18:21

sed valefaciens, et dicens : Iterum revertar ad vos, Deo volente : profectus est ab Epheso.

** Acts 18:22

Et descendens Cæsaream, ascendit, et salutavit ecclesiam, et descendit Antiochiam.  

** Acts 18:23

Et facto ibi aliquanto tempore profectus est, perambulans ex ordine Galaticam regionem, et Phrygiam, confirmans omnes discipulos.

** Acts 18:24

Judæus autem quidam, Apollo nomine, Alexandrinus genere, vir eloquens, devenit Ephesum, potens in scripturis.

** Acts 18:25

Hic erat edoctus viam Domini : et fervens spiritu loquebatur, et docebat diligenter ea quæ sunt Jesu, sciens tantum baptisma Joannis.

** Acts 18:26

Hic ergo cœpit fiducialiter agere in synagoga. Quem cum audissent Priscilla et Aquila, assumpserunt eum, et diligentius exposuerunt ei viam Domini.

** Acts 18:27

Cum autem vellet ire Achaiam, exhortati fratres, scripserunt discipulis ut susciperent eum. Qui cum venisset, contulit multum his qui crediderant.

** Acts 18:28

Vehementer enim Judæos revincebat publice, ostendens per Scripturas esse Christum Jesum.   

* Acts 19

** Acts 19:1

Factum est autem cum Apollo esset Corinthi, ut Paulus peragratis superioribus partibus veniret Ephesum, et inveniret quosdam discipulos :

** Acts 19:2

dixitque ad eos : Si Spiritum Sanctum accepistis credentes ? At illi dixerunt ad eum : Sed neque si Spiritus Sanctus est, audivimus.

** Acts 19:3

Ille vero ait : In quo ergo baptizati estis ? Qui dixerunt : In Joannis baptismate.

** Acts 19:4

Dixit autem Paulus : Joannes baptizavit baptismo pœnitentiæ populum, dicens in eum qui venturus esset post ipsum ut crederent, hoc est, in Jesum.

** Acts 19:5

His auditis, baptizati sunt in nomine Domini Jesu.

** Acts 19:6

Et cum imposuisset illis manus Paulus, venit Spiritus Sanctus super eos, et loquebantur linguis, et prophetabant.

** Acts 19:7

Erant autem omnes viri fere duodecim.  

** Acts 19:8

Introgressus autem synagogam, cum fiducia loquebatur per tres menses, disputans et suadens de regno Dei.

** Acts 19:9

Cum autem quidam indurarentur, et non crederent, maledicentes viam Domini coram multitudine, discedens ab eis, segregavit discipulos, quotidie disputans in schola tyranni cujusdam.

** Acts 19:10

Hoc autem factum est per biennium, ita ut omnes qui habitabant in Asia audirent verbum Domini, Judæi atque gentiles.

** Acts 19:11

Virtutesque non quaslibet faciebat Deus per manum Pauli,

** Acts 19:12

ita ut etiam super languidos deferrentur a corpore ejus sudaria et semicinctia, et recedebant ab eis languores, et spiritus nequam egrediebantur.  

** Acts 19:13

Tentaverunt autem quidam et de circumeuntibus Judæis exorcistis invocare super eos qui habebant spiritus malos nomen Domini Jesu, dicentes : Adjuro vos per Jesum, quem Paulus prædicat.

** Acts 19:14

Erant autem quidam Judæi, Scevæ principis sacerdotum septem filii, qui hoc faciebant.

** Acts 19:15

Respondens autem spiritus nequam dixit eis : Jesum novi, et Paulum scio : vos autem qui estis ?

** Acts 19:16

Et insiliens in eos homo, in quo erat dæmonium pessimum, et dominatus amborum, invaluit contra eos, ita ut nudi et vulnerati effugerent de domo illa.

** Acts 19:17

Hoc autem notum factum est omnibus Judæis, atque gentilibus qui habitabant Ephesi : et cecidit timor super omnes illos, et magnificabatur nomen Domini Jesu.

** Acts 19:18

Multique credentium veniebant, confitentes et annuntiantes actus suos.

** Acts 19:19

Multi autem ex eis, qui fuerant curiosa sectati, contulerunt libros, et combusserunt coram omnibus : et computatis pretiis illorum, invenerunt pecuniam denariorum quinquaginta millium.

** Acts 19:20

Ita fortiter crescebat verbum Dei, et confirmabatur.  

** Acts 19:21

His autem expletis, proposuit Paulus in Spiritu, transita Macedonia et Achaia, ire Jerosolymam, dicens : Quoniam postquam fuero ibi, oportet me et Romam videre.

** Acts 19:22

Mittens autem in Macedoniam duos ex ministrantibus sibi, Timotheum et Erastum, ipse remansit ad tempus in Asia.

** Acts 19:23

Facta est autem illo tempore turbatio non minima de via Domini.

** Acts 19:24

Demetrius enim quidam nomine, argentarius, faciens ædes argenteas Dianæ, præstabat artificibus non modicum quæstum :

** Acts 19:25

quos convocans, et eos qui hujusmodi erant opifices, dixit : Viri, scitis quia de hoc artificio est nobis acquisitio :

** Acts 19:26

et videtis et auditis quia non solum Ephesi, sed pene totius Asiæ, Paulus hic suadens avertit multam turbam, dicens : Quoniam non sunt dii, qui manibus fiunt.

** Acts 19:27

Non solum autem hæc periclitabitur nobis pars in redargutionem venire, sed et magnæ Dianæ templum in nihilum reputabitur, sed et destrui incipiet majestas ejus, quam tota Asia et orbis colit.

** Acts 19:28

His auditis, repleti sunt ira, et exclamaverunt dicentes : Magna Diana Ephesiorum.

** Acts 19:29

Et impleta est civitas confusione, et impetum fecerunt uno animo in theatrum, rapto Gajo et Aristarcho Macedonibus, comitibus Pauli.

** Acts 19:30

Paulo autem volente intrare in populum, non permiserunt discipuli.

** Acts 19:31

Quidam autem et de Asiæ principibus, qui erant amici ejus, miserunt ad eum rogantes ne se daret in theatrum :

** Acts 19:32

alii autem aliud clamabant. Erat enim ecclesia confusa : et plures nesciebant qua ex causa convenissent.

** Acts 19:33

De turba autem detraxerunt Alexandrum, propellentibus eum Judæis. Alexander autem manu silentio postulato, volebat reddere rationem populo.

** Acts 19:34

Quem ut cognoverunt Judæum esse, vox facta una est omnium, quasi per horas duas clamantium : Magna Diana Ephesiorum.

** Acts 19:35

Et cum sedasset scriba turbas, dixit : Viri Ephesii, quis enim est hominum, qui nesciat Ephesiorum civitatem cultricem esse magnæ Dianæ, Jovisque prolis ?

** Acts 19:36

Cum ergo his contradici non possit, oportet vos sedatos esse, et nihil temere agere.

** Acts 19:37

Adduxistis enim homines istos, neque sacrilegos, neque blasphemantes deam vestram.

** Acts 19:38

Quod si Demetrius et qui cum eo sunt artifices, habent adversus aliquem causam, conventus forenses aguntur, et proconsules sunt : accusent invicem.

** Acts 19:39

Si quid autem alterius rei quæritis, in legitima ecclesia poterit absolvi.

** Acts 19:40

Nam et periclitamur argui seditionis hodiernæ, cum nullus obnoxius sit de quo possimus reddere rationem concursus istius. Et cum hæc dixisset, dimisit ecclesiam.   

* Acts 20

** Acts 20:1

Postquam autem cessavit tumultus, vocatis Paulus discipulis, et exhortatus eos, valedixit, et profectus est ut iret in Macedoniam.

** Acts 20:2

Cum autem perambulasset partes illas, et exhortatus eos fuisset multo sermone, venit ad Græciam :

** Acts 20:3

ubi cum fecisset menses tres, factæ sunt illi insidiæ a Judæis navigaturo in Syriam : habuitque consilium ut reverteretur per Macedoniam.

** Acts 20:4

Comitatus est autem eum Sopater Pyrrhi Berœensis, Thessalonicensium vero Aristarchus, et Secundus, et Gajus Derbeus, et Timotheus : Asiani vero Tychicus et Trophimus.  

** Acts 20:5

Hi cum præcessissent, sustinuerunt nos Troade :

** Acts 20:6

nos vero navigavimus post dies azymorum a Philippis, et venimus ad eos Troadem in diebus quinque, ubi demorati sumus diebus septem.

** Acts 20:7

Una autem sabbati cum convenissemus ad frangendum panem, Paulus disputabat cum eis profecturus in crastinum, protraxitque sermonem usque in mediam noctem.

** Acts 20:8

Erant autem lampades copiosæ in cœnaculo, ubi eramus congregati.

** Acts 20:9

Sedens autem quidam adolescens nomine Eutychus super fenestram, cum mergeretur somno gravi, disputante diu Paulo, ductus somno cecidit de tertio cœnaculo deorsum, et sublatus est mortuus.

** Acts 20:10

Ad quem cum descendisset Paulus, incubuit super eum : et complexus dixit : Nolite turbari, anima enim ipsius in ipso est.

** Acts 20:11

Ascendens autem, frangensque panem, et gustans, satisque allocutus usque in lucem, sic profectus est.

** Acts 20:12

Adduxerunt autem puerum viventem, et consolati sunt non minime.  

** Acts 20:13

Nos autem ascendentes navem, navigavimus in Asson, inde suscepturi Paulum : sic enim disposuerat ipse per terram iter facturus.

** Acts 20:14

Cum autem convenisset nos in Asson, assumpto eo, venimus Mitylenen.

** Acts 20:15

Et inde navigantes, sequenti die venimus contra Chium, et alia applicuimus Samum, et sequenti die venimus Miletum.

** Acts 20:16

Proposuerat enim Paulus transnavigare Ephesum, ne qua mora illi fieret in Asia. Festinabat enim, si possibile sibi esset, ut diem Pentecostes faceret Jerosolymis.  

** Acts 20:17

A Mileto autem mittens Ephesum, vocavit majores natu ecclesiæ.

** Acts 20:18

Qui cum venissent ad eum, et simul essent, dixit eis : Vos scitis a prima die qua ingressus sum in Asiam, qualiter vobiscum per omne tempus fuerim,

** Acts 20:19

serviens Domino cum omni humilitate, et lacrimis, et tentationibus, quæ mihi acciderunt ex insidiis Judæorum :

** Acts 20:20

quomodo nihil subtraxerim utilium, quominus annuntiarem vobis et docerem vos, publice et per domos,

** Acts 20:21

testificans Judæis atque gentilibus in Deum pœnitentiam, et fidem in Dominum nostrum Jesum Christum.

** Acts 20:22

Et nunc ecce alligatus ego spiritu, vado in Jerusalem : quæ in ea ventura sint mihi, ignorans :

** Acts 20:23

nisi quod Spiritus Sanctus per omnes civitates mihi protestatur, dicens quoniam vincula et tribulationes Jerosolymis me manent.

** Acts 20:24

Sed nihil horum vereor : nec facio animam meam pretiosiorem quam me, dummodo consummem cursum meum, et ministerium verbi quod accepi a Domino Jesu, testificari Evangelium gratiæ Dei.

** Acts 20:25

Et nunc ecce ego scio quia amplius non videbitis faciem meam vos omnes, per quos transivi prædicans regnum Dei.

** Acts 20:26

Quapropter contestor vos hodierna die, quia mundus sum a sanguine omnium.

** Acts 20:27

Non enim subterfugi, quominus annuntiarem omne consilium Dei vobis.

** Acts 20:28

Attendite vobis, et universo gregi, in quo vos Spiritus Sanctus posuit episcopos regere ecclesiam Dei, quam acquisivit sanguine suo.

** Acts 20:29

Ego scio quoniam intrabunt post discessionem meam lupi rapaces in vos, non parcentes gregi.

** Acts 20:30

Et ex vobisipsis exsurgent viri loquentes perversa, ut abducant discipulos post se.

** Acts 20:31

Propter quod vigilate, memoria retinentes quoniam per triennium nocte et die non cessavi, cum lacrimis monens unumquemque vestrum.

** Acts 20:32

Et nunc commendo vos Deo, et verbo gratiæ ipsius, qui potens est ædificare, et dare hæreditatem in sanctificatis omnibus.

** Acts 20:33

Argentum, et aurum, aut vestem nullius concupivi, sicut

** Acts 20:34

ipsi scitis : quoniam ad ea quæ mihi opus erant, et his qui mecum sunt, ministraverunt manus istæ.

** Acts 20:35

Omnia ostendi vobis, quoniam sic laborantes, oportet suscipere infirmos ac meminisse verbi Domini Jesu : quoniam ipse dixit : Beatius est magis dare, quam accipere.

** Acts 20:36

Et cum hæc dixisset, positis genibus suis oravit cum omnibus illis.

** Acts 20:37

Magnus autem fletus factus est omnium : et procumbentes super collum Pauli, osculabantur eum,

** Acts 20:38

dolentes maxime in verbo quod dixerat, quoniam amplius faciem ejus non essent visuri. Et deducebant eum ad navem.   

* Acts 21

** Acts 21:1

Cum autem factum esset ut navigaremus abstracti ab eis, recto cursu venimus Coum, et sequenti die Rhodum, et inde Pataram.

** Acts 21:2

Et cum invenissemus navem transfretantem in Phœnicen, ascendentes navigavimus.

** Acts 21:3

Cum apparuissemus autem Cypro, relinquentes eam ad sinistram, navigavimus in Syriam, et venimus Tyrum : ibi enim navis expositura erat onus.

** Acts 21:4

Inventis autem discipulis, mansimus ibi diebus septem : qui Paulo dicebant per Spiritum ne ascenderet Jerosolymam.

** Acts 21:5

Et expletis diebus, profecti ibamus, deducentibus nos omnibus cum uxoribus et filiis usque foras civitatem : et positis genibus in littore, oravimus.

** Acts 21:6

Et cum valefecissemus invicem, ascendimus navem : illi autem redierunt in sua.

** Acts 21:7

Nos vero navigatione expleta a Tyro descendimus Ptolemaidam : et salutatis fratribus, mansimus die una apud illos.

** Acts 21:8

Alia autem die profecti, venimus Cæsaream. Et intrantes domum Philippi evangelistæ, qui erat unus de septem, mansimus apud eum.

** Acts 21:9

Huic autem erant quatuor filiæ virgines prophetantes.  

** Acts 21:10

Et cum moraremur per dies aliquot, supervenit quidam a Judæa propheta, nomine Agabus.

** Acts 21:11

Is cum venisset ad nos, tulit zonam Pauli : et alligans sibi pedes et manus, dixit : Hæc dicit Spiritus Sanctus : Virum, cujus est zona hæc, sic alligabunt in Jerusalem Judæi, et tradent in manus gentium.

** Acts 21:12

Quod cum audissemus, rogabamus nos, et qui loci illius erant, ne ascenderet Jerosolymam.

** Acts 21:13

Tunc respondit Paulus, et dixit : Quid facitis flentes, et affligentes cor meum ? Ego enim non solum alligari, sed et mori in Jerusalem paratus sum propter nomen Domini Jesu.

** Acts 21:14

Et cum ei suadere non possemus, quievimus, dicentes : Domini voluntas fiat.  

** Acts 21:15

Post dies autem istos, præparati ascendebamus in Jerusalem.

** Acts 21:16

Venerunt autem et ex discipulis a Cæsarea nobiscum, adducentes secum apud quem hospitaremur Mnasonem quemdam Cyprium, antiquum discipulum.

** Acts 21:17

Et cum venissemus Jerosolymam, libenter exceperunt nos fratres.  

** Acts 21:18

Sequenti autem die introibat Paulus nobiscum ad Jacobum, omnesque collecti sunt seniores.

** Acts 21:19

Quos cum salutasset, narrabat per singula quæ Deus fecisset in gentibus per ministerium ipsius.

** Acts 21:20

At illi cum audissent, magnificabant Deum, dixeruntque ei : Vides, frater, quot millia sunt in Judæis qui crediderunt, et omnes æmulatores sunt legis.

** Acts 21:21

Audierunt autem de te quia discessionem doceas a Moyse eorum qui per gentes sunt Judæorum, dicens non debere eos circumcidere filios suos, neque secundum consuetudinem ingredi.

** Acts 21:22

Quid ergo est ? utique oportet convenire multitudinem : audient enim te supervenisse.

** Acts 21:23

Hoc ergo fac quod tibi dicimus. Sunt nobis viri quatuor, votum habentes super se.

** Acts 21:24

His assumptis, sanctifica te cum illis, et impende in illis ut radant capita : et scient omnes quia quæ de te audierunt, falsa sunt, sed ambulas et ipse custodiens legem.

** Acts 21:25

De his autem qui crediderunt ex gentibus, nos scripsimus judicantes ut abstineant se ab idolis immolato, et sanguine, et suffocato, et fornicatione.

** Acts 21:26

Tunc Paulus, assumptis viris, postera die purificatus cum illis intravit in templum, annuntians expletionem dierum purificationis, donec offerretur pro unoquoque eorum oblatio.  

** Acts 21:27

Dum autem septem dies consummarentur, hi qui de Asia erant Judæi, cum vidissent eum in templo, concitaverunt omnem populum, et injecerunt ei manus, clamantes :

** Acts 21:28

Viri Israëlitæ, adjuvate : hic est homo qui adversus populum, et legem, et locum hunc, omnes ubique docens, insuper et gentiles induxit in templum, et violavit sanctum locum istum.

** Acts 21:29

Viderant enim Trophimum Ephesium in civitate cum ipso, quem æstimaverunt quoniam in templum introduxisset Paulus.

** Acts 21:30

Commotaque est civitas tota, et facta est concursio populi. Et apprehendentes Paulum, trahebant eum extra templum : et statim clausæ sunt januæ.

** Acts 21:31

Quærentibus autem eum occidere, nuntiatum est tribuno cohortis quia tota confunditur Jerusalem.

** Acts 21:32

Qui statim, assumptis militibus et centurionibus, decurrit ad illos. Qui cum vidissent tribunum et milites, cessaverunt percutere Paulum.

** Acts 21:33

Tunc accedens tribunus apprehendit eum, et jussit eum alligari catenis duabus : et interrogabat quis esset, et quid fecisset.

** Acts 21:34

Alii autem aliud clamabant in turba. Et cum non posset certum cognoscere præ tumultu, jussit duci eum in castra.

** Acts 21:35

Et cum venisset ad gradus, contigit ut portaretur a militibus propter vim populi.

** Acts 21:36

Sequebatur enim multitudo populi, clamans : Tolle eum.

** Acts 21:37

Et cum cœpisset induci in castra Paulus, dicit tribuno : Si licet mihi loqui aliquid ad te ? Qui dixit : Græce nosti ?

** Acts 21:38

nonne tu es Ægyptius, qui ante hos dies tumultum concitasti, et eduxisti in desertum quatuor millia virorum sicariorum ?

** Acts 21:39

Et dixit ad eum Paulus : Ego homo sum quidem Judæus a Tarso Ciliciæ, non ignotæ civitatis municeps. Rogo autem te, permitte mihi loqui ad populum.

** Acts 21:40

Et cum ille permisisset, Paulus stans in gradibus annuit manu ad plebem, et magno silentio facto, allocutus est lingua hebræa, dicens :   

* Acts 22

** Acts 22:1

Viri fratres, et patres, audite quam ad vos nunc reddo rationem.

** Acts 22:2

Cum audissent autem quia hebræa lingua loqueretur ad illos, magis præstiterunt silentium.

** Acts 22:3

Et dicit : Ego sum vir Judæus, natus in Tarso Ciliciæ, nutritus autem in ista civitate, secus pedes Gamaliel eruditus juxta veritatem paternæ legis, æmulator legis, sicut et vos omnes estis hodie :

** Acts 22:4

qui hanc viam persecutus sum usque ad mortem, alligans et tradens in custodias viros ac mulieres,

** Acts 22:5

sicut princeps sacerdotum mihi testimonium reddit, et omnes majores natu : a quibus et epistolas accipiens, ad fratres Damascum pergebam, ut adducerem inde vinctos in Jerusalem ut punirentur.

** Acts 22:6

Factum est autem, eunte me, et appropinquante Damasco media die, subito de cælo circumfulsit me lux copiosa :

** Acts 22:7

et decidens in terram, audivi vocem dicentem mihi : Saule, Saule, quid me persequeris ?

** Acts 22:8

Ego autem respondi : Quis es, domine ? Dixitque ad me : Ego sum Jesus Nazarenus, quem tu persequeris.

** Acts 22:9

Et qui mecum erant, lumen quidem viderunt, vocem autem non audierunt ejus qui loquebatur mecum.

** Acts 22:10

Et dixi : Quid faciam, domine ? Dominus autem dixit ad me : Surgens vade Damascum : et ibi tibi dicetur de omnibus quæ te oporteat facere.

** Acts 22:11

Et cum non viderem præ claritate luminis illius, ad manum deductus a comitibus, veni Damascum.

** Acts 22:12

Ananias autem quidam vir secundum legem, testimonium habens ab omnibus cohabitantibus Judæis,

** Acts 22:13

veniens ad me et astans, dixit mihi : Saule frater, respice. Et ego eadem hora respexi in eum.

** Acts 22:14

At ille dixit : Deus patrum nostrorum præordinavit te, ut cognosceres voluntatem ejus, et videres justum, et audires vocem ex ore ejus :

** Acts 22:15

quia eris testis illius ad omnes homines eorum quæ vidisti et audisti.

** Acts 22:16

Et nunc quid moraris ? Exsurge, et baptizare, et ablue peccata tua, invocato nomine ipsius.

** Acts 22:17

Factum est autem revertenti mihi in Jerusalem, et oranti in templo, fieri me in stupore mentis,

** Acts 22:18

et videre illum dicentem mihi : Festina, et exi velociter ex Jerusalem : quoniam non recipient testimonium tuum de me.

** Acts 22:19

Et ego dixi : Domine, ipsi sciunt quia ego eram concludens in carcerem, et cædens per synagogas eos qui credebant in te :

** Acts 22:20

et cum funderetur sanguis Stephani testis tui, ego astabam, et consentiebam, et custodiebam vestimenta interficientium illum.

** Acts 22:21

Et dixit ad me : Vade, quoniam ego in nationes longe mittam te.

** Acts 22:22

Audiebant autem eum usque ad hoc verbum, et levaverunt vocem suam, dicentes : Tolle de terra hujusmodi : non enim fas est eum vivere.  

** Acts 22:23

Vociferantibus autem eis, et projicientibus vestimenta sua, et pulverem jactantibus in aërem,

** Acts 22:24

jussit tribunus induci eum in castra, et flagellis cædi, et torqueri eum, ut sciret propter quam causam sic acclamarent ei.

** Acts 22:25

Et cum astrinxissent eum loris, dicit astanti sibi centurioni Paulus : Si hominem Romanum et indemnatum licet vobis flagellare ?

** Acts 22:26

Quo audito, centurio accessit ad tribunum, et nuntiavit ei, dicens : Quid acturus es ? hic enim homo civis Romanus est.

** Acts 22:27

Accedens autem tribunus, dixit illi : Dic mihi si tu Romanus es ? At ille dixit : Etiam.

** Acts 22:28

Et respondit tribunus : Ego multa summa civilitatem hanc consecutus sum. Et Paulus ait : Ego autem et natus sum.

** Acts 22:29

Protinus ergo discesserunt ab illo qui eum torturi erant. Tribunus quoque timuit postquam rescivit, quia civis Romanus esset, et quia alligasset eum.

** Acts 22:30

Postera autem die volens scire diligentius qua ex causa accusaretur a Judæis, solvit eum, et jussit sacerdotes convenire, et omne concilium : et producens Paulum, statuit inter illos.   

* Acts 23

** Acts 23:1

Intendens autem in concilium Paulus, ait : Viri fratres, ego omni conscientia bona conversatus sum ante Deum usque in hodiernum diem.

** Acts 23:2

Princeps autem sacerdotum Ananias præcepit astantibus sibi percutere os ejus.

** Acts 23:3

Tunc Paulus dixit ad eum : Percutiet te Deus, paries dealbate. Et tu sedens judicas me secundum legem, et contra legem jubes me percuti ?

** Acts 23:4

Et qui astabant dixerunt : Summum sacerdotem Dei maledicis.

** Acts 23:5

Dixit autem Paulus : Nesciebam, fratres, quia princeps est sacerdotum. Scriptum est enim : Principem populi tui non maledices.

** Acts 23:6

Sciens autem Paulus quia una pars esset sadducæorum, et altera pharisæorum, exclamavit in concilio : Viri fratres, ego pharisæus sum, filius pharisæorum : de spe et resurrectione mortuorum ego judicor.

** Acts 23:7

Et cum hæc dixisset, facta est dissensio inter pharisæos et sadducæos, et soluta est multitudo.

** Acts 23:8

Sadducæi enim dicunt non esse resurrectionem, neque angelum, neque spiritum : pharisæi autem utraque confitentur.

** Acts 23:9

Factus est autem clamor magnus. Et surgentes quidam pharisæorum, pugnabant, dicentes : Nihil mali invenimus in homine isto : quid si spiritus locutus est ei, aut angelus ?

** Acts 23:10

Et cum magna dissensio facta esset, timens tribunus ne discerperetur Paulus ab ipsis, jussit milites descendere, et rapere eum de medio eorum, ac deducere eum in castra.  

** Acts 23:11

Sequenti autem nocte assistens ei Dominus, ait : Constans esto : sicut enim testificatus es de me in Jerusalem, sic te oportet et Romæ testificari.

** Acts 23:12

Facta autem die collegerunt se quidam ex Judæis, et devoverunt, se dicentes neque manducaturos, neque bibituros donec occiderent Paulum.

** Acts 23:13

Erant autem plus quam quadraginta viri qui hanc conjurationem fecerant :

** Acts 23:14

qui accesserunt ad principes sacerdotum et seniores, et dixerunt : Devotione devovimus nos nihil gustaturos, donec occidamus Paulum.

** Acts 23:15

Nunc ergo vos notum facite tribuno cum concilio, ut producat illum ad vos, tamquam aliquid certius cognituri de eo. Nos vero priusquam appropiet, parati sumus interficere illum.

** Acts 23:16

Quod cum audisset filius sororis Pauli insidias, venit, et intravit in castra, nuntiavitque Paulo.

** Acts 23:17

Vocans autem Paulus ad se unum ex centurionibus, ait : Adolescentem hunc perduc ad tribunum, habet enim aliquid indicare illi.

** Acts 23:18

Et ille quidem assumens eum duxit ad tribunum, et ait : Vinctus Paulus rogavit me hunc adolescentem perducere ad te, habentem aliquid loqui tibi.

** Acts 23:19

Apprehendens autem tribunus manum illius, secessit cum eo seorsum, et interrogavit illum : Quid est quod habes indicare mihi ?

** Acts 23:20

Ille autem dixit : Judæis convenit rogare te ut crastina die producas Paulum in concilium, quasi aliquid certius inquisituri sint de illo :

** Acts 23:21

tu vero ne credideris illis : insidiantur enim ei ex eis viri amplius quam quadraginta, qui se devoverunt non manducare, neque bibere donec interficiant eum : et nunc parati sunt, exspectantes promissum tuum.

** Acts 23:22

Tribunus igitur dimisit adolescentem, præcipiens ne cui loqueretur quoniam hæc nota sibi fecisset.  

** Acts 23:23

Et vocatis duobus centurionibus, dixit illis : Parate milites ducentos ut eant usque Cæsaream, et equites septuaginta, et lancearios ducentos a tertia hora noctis,

** Acts 23:24

et jumenta præparate ut imponentes Paulum, salvum perducerent ad Felicem præsidem.

** Acts 23:25

(Timuit enim ne forte raperent eum Judæi, et occiderent, et ipse postea calumniam sustineret, tamquam accepturus pecuniam.)

** Acts 23:26

Scribens epistolam continentem hæc : Claudius Lysias optimo præsidi Felici, salutem.

** Acts 23:27

Virum hunc comprehensum a Judæis, et incipientem interfici ab eis, superveniens cum exercitu eripui, cognito quia Romanus est.

** Acts 23:28

Volensque scire causam quam objiciebant illi, deduxi eum in concilium eorum.

** Acts 23:29

Quem inveni accusari de quæstionibus legis ipsorum, nihil vero dignum morte aut vinculis habentem criminis.

** Acts 23:30

Et cum mihi perlatum esset de insidiis quas paraverant illi, misi eum ad te, denuntians et accusatoribus ut dicant apud te. Vale.

** Acts 23:31

Milites ergo secundum præceptum sibi assumentes Paulum, duxerunt per noctem in Antipatridem.

** Acts 23:32

Et postera die dimissis equitibus ut cum eo irent, reversi sunt ad castra.

** Acts 23:33

Qui cum venissent Cæsaream, et tradidissent epistolam præsidi, statuerunt ante illum et Paulum.

** Acts 23:34

Cum legisset autem, et interrogasset de qua provincia esset, et cognoscens quia de Cilicia :

** Acts 23:35

Audiam te, inquit, cum accusatores tui venerint. Jussitque in prætorio Herodis custodiri eum.   

* Acts 24

** Acts 24:1

Post quinque autem dies descendit princeps sacerdotum Ananias, cum senioribus quibusdam, et Tertullo quodam oratore, qui adierunt præsidem adversus Paulum.

** Acts 24:2

Et citato Paulo cœpit accusare Tertullus, dicens : Cum in multa pace agamus per te, et multa corrigantur per tuam providentiam,

** Acts 24:3

semper et ubique suscipimus, optime Felix, cum omni gratiarum actione.

** Acts 24:4

Ne diutius autem te protraham, oro, breviter audias nos pro tua clementia.

** Acts 24:5

Invenimus hunc hominem pestiferum, et concitantem seditiones omnibus Judæis in universo orbe, et auctorem seditionis sectæ Nazarenorum :

** Acts 24:6

qui etiam templum violare conatus est, quem et apprehensum voluimus secundum legem nostram judicare.

** Acts 24:7

Superveniens autem tribunus Lysias, cum vi magna eripuit eum de manibus nostris,

** Acts 24:8

jubens accusatores ejus ad te venire : a quo poteris ipse judicans, de omnibus istis cognoscere, de quibus nos accusamus eum.

** Acts 24:9

Adjecerunt autem et Judæi, dicentes hæc ita se habere.

** Acts 24:10

Respondit autem Paulus (annuente sibi præside dicere) : Ex multis annis te esse judicem genti huic sciens, bono animo pro me satisfaciam.

** Acts 24:11

Potes enim cognoscere quia non plus sunt mihi dies quam duodecim, ex quo ascendi adorare in Jerusalem :

** Acts 24:12

et neque in templo invenerunt me cum aliquo disputantem, aut concursum facientem turbæ, neque in synagogis, neque in civitate :

** Acts 24:13

neque probare possunt tibi de quibus nunc me accusant.

** Acts 24:14

Confiteor autem hoc tibi, quod secundum sectam quam dicunt hæresim, sic deservio Patri et Deo meo, credens omnibus quæ in lege et prophetis scripta sunt :

** Acts 24:15

spem habens in Deum, quam et hi ipsi exspectant, resurrectionem futuram justorum et iniquorum.

** Acts 24:16

In hoc et ipse studeo sine offendiculo conscientiam habere ad Deum et ad homines semper.

** Acts 24:17

Post annos autem plures eleemosynas facturus in gentem meam, veni, et oblationes, et vota,

** Acts 24:18

in quibus invenerunt me purificatum in templo : non cum turba, neque cum tumultu.

** Acts 24:19

Quidam autem ex Asia Judæi, quos oportebat apud te præsto esse, et accusare si quid haberent adversum me :

** Acts 24:20

aut hi ipsi dicant si quid invenerunt in me iniquitatis cum stem in concilio,

** Acts 24:21

nisi de una hac solummodo voce qua clamavi inter eos stans : Quoniam de resurrectione mortuorum ego judicor hodie a vobis.  

** Acts 24:22

Distulit autem illos Felix, certissime sciens de via hac, dicens : Cum tribunus Lysias descenderit, audiam vos.

** Acts 24:23

Jussitque centurioni custodire eum, et habere requiem, nec quemquam de suis prohibere ministrare ei.

** Acts 24:24

Post aliquot autem dies veniens Felix cum Drusilla uxore sua, quæ erat Judæa, vocavit Paulum, et audivit ab eo fidem quæ est in Christum Jesum.

** Acts 24:25

Disputante autem illo de justitia, et castitate, et de judicio futuro, tremefactus Felix, respondit : Quod nunc attinet, vade : tempore autem opportuno accersam te :

** Acts 24:26

simul et sperans quod pecunia ei daretur a Paulo, propter quod et frequenter accersens eum, loquebatur cum eo.

** Acts 24:27

Biennio autem expleto, accepit successorem Felix Portium Festum. Volens autem gratiam præstare Judæis Felix, reliquit Paulum vinctum.   

* Acts 25

** Acts 25:1

Festus ergo cum venisset in provinciam, post triduum ascendit Jerosolymam a Cæsarea.

** Acts 25:2

Adieruntque eum principes sacerdotum et primi Judæorum adversus Paulum : et rogabant eum,

** Acts 25:3

postulantes gratiam adversus eum, ut juberet perduci eum in Jerusalem, insidias tendentes ut interficerent eum in via.

** Acts 25:4

Festus autem respondit servari Paulum in Cæsarea : se autem maturius profecturum.

** Acts 25:5

Qui ergo in vobis, ait, potentes sunt, descendentes simul, si quod est in viro crimen, accusent eum.

** Acts 25:6

Demoratus autem inter eos dies non amplius quam octo aut decem, descendit Cæsaream, et altera die sedit pro tribunali, et jussit Paulum adduci.

** Acts 25:7

Qui cum perductus esset, circumsteterunt eum, qui ab Jerosolyma descenderant Judæi, multas et graves causas objicientes, quas non poterant probare :

** Acts 25:8

Paulo rationem reddente : Quoniam neque in legem Judæorum, neque in templum, neque in Cæsarem quidquam peccavi.

** Acts 25:9

Festus autem volens gratiam præstare Judæis, respondens Paulo, dixit : Vis Jerosolymam ascendere, et ibi de his judicari apud me ?

** Acts 25:10

Dixit autem Paulus : Ad tribunal Cæsaris sto : ibi me oportet judicari : Judæis non nocui, sicut tu melius nosti.

** Acts 25:11

Si enim nocui, aut dignum morte aliquid feci, non recuso mori : si vero nihil est eorum quæ hi accusant me, nemo potest me illis donare. Cæsarem appello.

** Acts 25:12

Tunc Festus cum concilio locutus, respondit : Cæsarem appellasti ? ad Cæsarem ibis.  

** Acts 25:13

Et cum dies aliquot transacti essent, Agrippa rex et Bernice descenderunt Cæsaream ad salutandum Festum.

** Acts 25:14

Et cum dies plures ibi demorarentur, Festus regi indicavit de Paulo, dicens : Vir quidam est derelictus a Felice vinctus,

** Acts 25:15

de quo cum essem Jerosolymis, adierunt me principes sacerdotum et seniores Judæorum, postulantes adversus illum damnationem.

** Acts 25:16

Ad quos respondi : Quia non est Romanis consuetudo damnare aliquem hominem priusquam is qui accusatur præsentes habeat accusatores, locumque defendendi accipiat ad abluenda crimina.

** Acts 25:17

Cum ergo huc convenissent sine ulla dilatione, sequenti die sedens pro tribunali, jussi adduci virum.

** Acts 25:18

De quo, cum stetissent accusatores, nullam causam deferebant, de quibus ego suspicabar malum.

** Acts 25:19

Quæstiones vero quasdam de sua superstitione habebant adversus eum, et de quodam Jesu defuncto, quem affirmabat Paulus vivere.

** Acts 25:20

Hæsitans autem ego de hujusmodi quæstione, dicebam si vellet ire Jerosolymam, et ibi judicari de istis.

** Acts 25:21

Paulo autem appellante ut servaretur ad Augusti cognitionem, jussi servari eum, donec mittam eum ad Cæsarem.

** Acts 25:22

Agrippa autem dixit ad Festum : Volebam et ipse hominem audire. Cras, inquit, audies eum.

** Acts 25:23

Altera autem die cum venisset Agrippa et Bernice cum multa ambitione, et introissent in auditorium cum tribunis et viris principalibus civitatis, jubente Festo, adductus est Paulus.

** Acts 25:24

Et dicit Festus : Agrippa rex, et omnes qui simul adestis nobiscum viri, videtis hunc de quo omnis multitudo Judæorum interpellavit me Jerosolymis, petentes et acclamantes non oportere eum vivere amplius.

** Acts 25:25

Ego vere comperi nihil dignum morte eum admisisse. Ipso autem hoc appellante ad Augustum, judicavi mittere.

** Acts 25:26

De quo quid certum scribam domino, non habeo. Propter quod produxi eum ad vos, et maxime ad te, rex Agrippa, ut interrogatione facta habeam quid scribam.

** Acts 25:27

Sine ratione enim mihi videtur mittere vinctum, et causas ejus non significare.   

* Acts 26

** Acts 26:1

Agrippa vero ad Paulum ait : Permittitur tibi loqui pro temetipso. Tunc Paulus extenta manu cœpit rationem reddere :

** Acts 26:2

De omnibus quibus accusor a Judæis, rex Agrippa, æstimo me beatum apud te cum sim defensurus me hodie,

** Acts 26:3

maxime te sciente omnia, et quæ apud Judæos sunt consuetudines et quæstiones : propter quod obsecro patienter me audias.

** Acts 26:4

Et quidem vitam meam a juventute, quæ ab initio fuit in gente mea in Jerosolymis, noverunt omnes Judæi :

** Acts 26:5

præscientes me ab initio (si velint testimonium perhibere) quoniam secundum certissimam sectam nostræ religionis vixi pharisæus.

** Acts 26:6

Et nunc, in spe quæ ad patres nostros repromissionis facta est a Deo, sto judicio subjectus :

** Acts 26:7

in quam duodecim tribus nostræ nocte ac die deservientes, sperant devenire. De qua spe accusor a Judæis, rex.

** Acts 26:8

Quid incredibile judicatur apud vos, si Deus mortuos suscitat ?

** Acts 26:9

Et ego quidem existimaveram me adversus nomen Jesu Nazareni debere multa contraria agere,

** Acts 26:10

quod et feci Jerosolymis, et multos sanctorum ego in carceribus inclusi, a principibus sacerdotum potestate accepta : et cum occiderentur, detuli sententiam.

** Acts 26:11

Et per omnes synagogas frequenter puniens eos, compellebam blasphemare : et amplius insaniens in eos, persequebar usque in exteras civitates.

** Acts 26:12

In quibus dum irem Damascum cum potestate et permissu principum sacerdotum,

** Acts 26:13

die media in via vidi, rex, de cælo supra splendorem solis circumfulsisse me lumen, et eos qui mecum simul erant.

** Acts 26:14

Omnesque nos cum decidissemus in terram, audivi vocem loquentem mihi hebraica lingua : Saule, Saule, quid me persequeris ? durum est tibi contra stimulum calcitrare.

** Acts 26:15

Ego autem dixi : Quis es, domine ? Dominus autem dixit : Ego sum Jesus, quem tu persequeris.

** Acts 26:16

Sed exsurge, et sta super pedes tuos : ad hoc enim apparui tibi, ut constituam te ministrum, et testem eorum quæ vidisti, et eorum quibus apparebo tibi,

** Acts 26:17

eripiens te de populo et gentibus, in quas nunc ego mitto te,

** Acts 26:18

aperire oculos eorum, ut convertantur a tenebris ad lucem, et de potestate Satanæ ad Deum, ut accipiant remissionem peccatorum, et sortem inter sanctos, per fidem quæ est in me.

** Acts 26:19

Unde, rex Agrippa, non fui incredulus cælesti visioni :

** Acts 26:20

sed his qui sunt Damasci primum, et Jerosolymis, et in omnem regionem Judææ, et gentibus, annuntiabam, ut pœnitentiam agerent, et converterentur ad Deum, digna pœnitentiæ opera facientes.

** Acts 26:21

Hac ex causa me Judæi, cum essem in templo, comprehensum tentabant interficere.

** Acts 26:22

Auxilio autem adjutus Dei usque in hodiernum diem, sto, testificans minori atque majori, nihil extra dicens quam ea quæ prophetæ locuti sunt futura esse, et Moyses,

** Acts 26:23

si passibilis Christus, si primus ex resurrectione mortuorum, lumen annuntiaturus est populo et gentibus.

** Acts 26:24

Hæc loquente eo, et rationem reddente, Festus magna voce dixit : Insanis, Paule : multæ te litteræ ad insaniam convertunt.

** Acts 26:25

Et Paulus : Non insanio, inquit, optime Feste, sed veritatis et sobrietatis verba loquor.

** Acts 26:26

Scit enim de his rex, ad quem et constanter loquor : latere enim eum nihil horum arbitror. Neque enim in angulo quidquam horum gestum est.

** Acts 26:27

Credis, rex Agrippa, prophetis ? Scio quia credis.

** Acts 26:28

Agrippa autem ad Paulum : In modico suades me christianum fieri.

** Acts 26:29

Et Paulus : Opto apud Deum, et in modico et in magno, non tantum te, sed etiam omnes qui audiunt hodie fieri tales, qualis et ego sum, exceptis vinculis his.

** Acts 26:30

Et exsurrexit rex, et præses, et Bernice, et qui assidebant eis.

** Acts 26:31

Et cum secessissent, loquebantur ad invicem, dicentes : Quia nihil morte aut vinculis dignum quid fecit homo iste.

** Acts 26:32

Agrippa autem Festo dixit : Dimitti poterat homo hic, si non appellasset Cæsarem.   

* Acts 27

** Acts 27:1

Ut autem judicatum est navigare eum in Italiam, et tradi Paulum cum reliquis custodiis centurioni nomine Julio cohortis Augustæ,

** Acts 27:2

ascendentes navem Adrumetinam, incipientes navigare circa Asiæ loca, sustulimus, perseverante nobiscum Aristarcho Macedone Thessalonicensi.

** Acts 27:3

Sequenti autem die devenimus Sidonem. Humane autem tractans Julius Paulum, permisit ad amicos ire, et curam sui agere.

** Acts 27:4

Et inde cum sustulissemus, subnavigavimus Cyprum, propterea quod essent venti contrarii.

** Acts 27:5

Et pelagus Ciliciæ et Pamphyliæ navigantes, venimus Lystram, quæ est Lyciæ :

** Acts 27:6

et ibi inveniens centurio navem Alexandrinam navigantem in Italiam, transposuit nos in eam.

** Acts 27:7

Et cum multis diebus tarde navigaremus, et vix devenissemus contra Gnidum, prohibente nos vento, adnavigavimus Cretæ juxta Salmonem :

** Acts 27:8

et vix juxta navigantes, venimus in locum quemdam qui vocatur Boniportus, cui juxta erat civitas Thalassa.

** Acts 27:9

Multo autem tempore peracto, et cum jam non esset tuta navigatio eo quod et jejunium jam præteriisset, consolabatur eos Paulus,

** Acts 27:10

dicens eis : Viri, video quoniam cum injuria et multo damno non solum oneris, et navis, sed etiam animarum nostrarum incipit esse navigatio.

** Acts 27:11

Centurio autem gubernatori et nauclero magis credebat, quam his quæ a Paulo dicebantur.

** Acts 27:12

Et cum aptus portus non esset ad hiemandum, plurimi statuerunt consilium navigare inde, si quomodo possent, devenientes Phœnicen hiemare, portum Cretæ respicientem ad Africum et ad Corum.

** Acts 27:13

Aspirante autem austro, æstimantes propositum se tenere, cum sustulissent de Asson, legebant Cretam.  

** Acts 27:14

Non post multum autem misit se contra ipsam ventus typhonicus, qui vocatur Euroaquilo.

** Acts 27:15

Cumque arrepta esset navis, et non posset conari in ventum, data nave flatibus, ferebamur.

** Acts 27:16

In insulam autem quamdam decurrentes, quæ vocatur Cauda, potuimus vix obtinere scapham.

** Acts 27:17

Qua sublata, adjutoriis utebantur, accingentes navem, timentes ne in Syrtim inciderent, summisso vase sic ferebantur.

** Acts 27:18

Valida autem nobis tempestate jactatis, sequenti die jactum fecerunt :

** Acts 27:19

et tertia die suis manibus armamenta navis projecerunt.

** Acts 27:20

Neque autem sole, neque sideribus apparentibus per plures dies, et tempestate non exigua imminente, jam ablata erat spes omnis salutis nostræ.

** Acts 27:21

Et cum multa jejunatio fuisset, tunc stans Paulus in medio eorum, dixit : Oportebat quidem, o viri, audito me, non tollere a Creta, lucrique facere injuriam hanc et jacturam.

** Acts 27:22

Et nunc suadeo vobis bono animo esse : amissio enim nullius animæ erit ex vobis, præterquam navis.

** Acts 27:23

Astitit enim mihi hac nocte angelus Dei, cujus sum ego, et cui deservio,

** Acts 27:24

dicens : Ne timeas, Paule : Cæsari te oportet assistere : et ecce donavit tibi Deus omnes qui navigant tecum.

** Acts 27:25

Propter quod bono animo estote, viri : credo enim Deo quia sic erit, quemadmodum dictum est mihi.

** Acts 27:26

In insulam autem quamdam oportet nos devenire.

** Acts 27:27

Sed posteaquam quartadecima nox supervenit, navigantibus nobis in Adria circa mediam noctem, suspicabantur nautæ apparere sibi aliquam regionem.

** Acts 27:28

Qui et summittentes bolidem, invenerunt passus viginti : et pusillum inde separati, invenerunt passus quindecim.

** Acts 27:29

Timentes autem ne in aspera loca incideremus, de puppi mittentes anchoras quatuor, optabant diem fieri.

** Acts 27:30

Nautis vero quærentibus fugere de navi, cum misissent scapham in mare, sub obtentu quasi inciperent a prora anchoras extendere,

** Acts 27:31

dixit Paulus centurioni et militibus : Nisi hi in navi manserint, vos salvi fieri non potestis.

** Acts 27:32

Tunc absciderunt milites funes scaphæ, et passi sunt eam excidere.

** Acts 27:33

Et cum lux inciperet fieri, rogabat Paulus omnes sumere cibum, dicens : Quartadecima die hodie exspectantes jejuni permanetis, nihil accipientes.

** Acts 27:34

Propter quod rogo vos accipere cibum pro salute vestra : quia nullius vestrum capillus de capite peribit.

** Acts 27:35

Et cum hæc dixisset, sumens panem, gratias egit Deo in conspectu omnium : et cum fregisset, cœpit manducare.

** Acts 27:36

Animæquiores autem facti omnes, et ipsi sumpserunt cibum.

** Acts 27:37

Eramus vero universæ animæ in navi ducentæ septuaginta sex.

** Acts 27:38

Et satiati cibo alleviabant navem, jactantes triticum in mare.

** Acts 27:39

Cum autem dies factus esset, terram non agnoscebant : sinum vero quemdam considerabant habentem littus, in quem cogitabant si possent ejicere navem.

** Acts 27:40

Et cum anchoras sustulissent, committebant se mari, simul laxantes juncturas gubernaculorum : et levato artemone secundum auræ flatum, tendebant ad littus.

** Acts 27:41

Et cum incidissemus in locum dithalassum, impegerunt navem : et prora quidem fixa manebat immobilis, puppis vero solvebatur a vi maris.

** Acts 27:42

Militum autem consilium fuit ut custodias occiderent, ne quis cum enatasset, effugeret.

** Acts 27:43

Centurio autem volens servare Paulum, prohibuit fieri : jussitque eos qui possent natare, emittere se primos, et evadere, et ad terram exire :

** Acts 27:44

et ceteros, alios in tabulis ferebant, quosdam super ea quæ de navi erant. Et sic factum est, ut omnes animæ evaderent ad terram.   

* Acts 28

** Acts 28:1

Et cum evasissemus, tunc cognovimus quia Melita insula vocabatur. Barbari vero præstabant non modicam humanitatem nobis.

** Acts 28:2

Accensa enim pyra, reficiebant nos omnes propter imbrem qui imminebat, et frigus.

** Acts 28:3

Cum congregasset autem Paulus sarmentorum aliquantam multitudinem, et imposuisset super ignem, vipera a calore cum processisset, invasit manum ejus.

** Acts 28:4

Ut vero viderunt barbari pendentem bestiam de manu ejus, ad invicem dicebant : Utique homicida est homo hic, qui cum evaserit de mari, ultio non sinit eum vivere.

** Acts 28:5

Et ille quidem excutiens bestiam in ignem, nihil mali passus est.

** Acts 28:6

At illi existimabant eum in tumorem convertendum, et subito casurum et mori. Diu autem illis exspectantibus, et videntibus nihil mali in eo fieri, convertentes se, dicebant eum esse deum.

** Acts 28:7

In locis autem illis erant prædia principis insulæ, nomine Publii, qui nos suscipiens, triduo benigne exhibuit.

** Acts 28:8

Contigit autem patrem Publii febribus et dysenteria vexatum jacere. Ad quem Paulus intravit : et cum orasset, et imposuisset ei manus, salvavit eum.

** Acts 28:9

Quo facto, omnes qui in insula habebant infirmitates, accedebant, et curabantur :

** Acts 28:10

qui etiam multis honoribus nos honoraverunt, et navigantibus imposuerunt quæ necessaria erant.  

** Acts 28:11

Post menses autem tres navigavimus in navi Alexandrina, quæ in insula hiemaverat, cui erat insigne Castorum.

** Acts 28:12

Et cum venissemus Syracusam, mansimus ibi triduo.

** Acts 28:13

Inde circumlegentes devenimus Rhegium : et post unum diem, flante austro, secunda die venimus Puteolos :

** Acts 28:14

ubi inventis fratribus rogati sumus manere apud eos dies septem : et sic venimus Romam.

** Acts 28:15

Et inde cum audissent fratres, occurrerunt nobis usque ad Appii forum, ac tres Tabernas. Quos cum vidisset Paulus, gratias agens Deo, accepit fiduciam.

** Acts 28:16

Cum autem venissemus Romam, permissum est Paulo manere sibimet cum custodiente se milite.  

** Acts 28:17

Post tertium autem diem convocavit primos Judæorum. Cumque convenissent, dicebat eis : Ego, viri fratres, nihil adversus plebem faciens, aut morem paternum, vinctus ab Jerosolymis traditus sum in manus Romanorum,

** Acts 28:18

qui cum interrogationem de me habuissent, voluerunt me dimittere, eo quod nulla esset causa mortis in me.

** Acts 28:19

Contradicentibus autem Judæis, coactus sum appellare Cæsarem, non quasi gentem meam habens aliquid accusare.

** Acts 28:20

Propter hanc igitur causam rogavi vos videre, et alloqui. Propter spem enim Israël catena hac circumdatus sum.

** Acts 28:21

At illi dixerunt ad eum : Nos neque litteras accepimus de te a Judæa, neque adveniens aliquis fratrum nuntiavit, aut locutus est quid de te malum.

** Acts 28:22

Rogamus autem a te audire quæ sentis : nam de secta hac notum est nobis quia ubique ei contradicitur.

** Acts 28:23

Cum constituissent autem illi diem, venerunt ad eum in hospitium plurimi, quibus exponebat testificans regnum Dei, suadensque eis de Jesu ex lege Moysi et prophetis a mane usque ad vesperam.

** Acts 28:24

Et quidam credebant his quæ dicebantur : quidam vero non credebant.

** Acts 28:25

Cumque invicem non essent consentientes, discedebant, dicente Paulo unum verbum : Quia bene Spiritus Sanctus locutus est per Isaiam prophetam ad patres nostros,

** Acts 28:26

dicens : Vade ad populum istum, et dic ad eos :   Aure audietis, et non intelligetis,  et videntes videbitis, et non perspicietis. 

** Acts 28:27

Incrassatum est enim cor populi hujus,  et auribus graviter audierunt,  et oculos suos compresserunt :  ne forte videant oculis,  et auribus audiant,  et corde intelligant, et convertantur,  et sanem eos.

** Acts 28:28

Notum ergo sit vobis, quoniam gentibus missum est hoc salutare Dei, et ipsi audient.

** Acts 28:29

Et cum hæc dixisset, exierunt ab eo Judæi, multam habentes inter se quæstionem.  

** Acts 28:30

Mansit autem biennio toto in suo conducto : et suscipiebat omnes qui ingrediebantur ad eum,

** Acts 28:31

prædicans regnum Dei, et docens quæ sunt de Domino Jesu Christo cum omni fiducia, sine prohibitione.    

