* Amos 1

** Amos 1:1

Verba Amos, qui fuit in pastoribus de Thecue, quæ vidit super Israël in diebus Oziæ, regis Juda, et in diebus Jeroboam, filii Joas, regis Israël, ante duos annos terræmotus.  

** Amos 1:2

Et dixit :   Dominus de Sion rugiet,  et de Jerusalem dabit vocem suam ;  et luxerunt speciosa pastorum,  et exsiccatus est vertex Carmeli. 

** Amos 1:3

Hæc dicit Dominus :  Super tribus sceleribus Damasci,  et super quatuor non convertam eum,  eo quod trituraverint in plaustris ferreis Galaad. 

** Amos 1:4

Et mittam ignem in domum Azaël,  et devorabit domos Benadad. 

** Amos 1:5

Et conteram vectem Damasci :  et disperdam habitatorem de campo idoli,  et tenentem sceptrum de domo voluptatis :  et transferetur populus Syriæ Cyrenen,  dicit Dominus. 

** Amos 1:6

Hæc dicit Dominus :  Super tribus sceleribus Gazæ,  et super quatuor non convertam eum,  eo quod transtulerint captivitatem perfectam,  ut concluderent eam in Idumæa. 

** Amos 1:7

Et mittam ignem in murum Gazæ,  et devorabit ædes ejus. 

** Amos 1:8

Et disperdam habitatorem de Azoto,  et tenentem sceptrum de Ascalone :  et convertam manum meam super Accaron,  et peribunt reliqui Philisthinorum,  dicit Dominus Deus. 

** Amos 1:9

Hæc dicit Dominus :  Super tribus sceleribus Tyri,  et super quatuor non convertam eum,  eo quod concluserint captivitatem perfectam in Idumæa,  et non sint recordati fœderis fratrum. 

** Amos 1:10

Et mittam ignem in murum Tyri,  et devorabit ædes ejus. 

** Amos 1:11

Hæc dicit Dominus :  Super tribus sceleribus Edom,  et super quatuor non convertam eum,  eo quod persecutus sit in gladio fratrem suum,  et violaverit misericordiam ejus,  et tenuerit ultra furorem suum,  et indignationem suam servaverit usque in finem. 

** Amos 1:12

Mittam ignem in Theman,  et devorabit ædes Bosræ. 

** Amos 1:13

Hæc dicit Dominus :  Super tribus sceleribus filiorum Ammon,  et super quatuor non convertam eum,  eo quod dissecuerit prægnantes Galaad  ad dilatandum terminum suum. 

** Amos 1:14

Et succendam ignem in muro Rabba,  et devorabit ædes ejus in ululatu in die belli,  et in turbine in die commotionis. 

** Amos 1:15

Et ibit Melchom in captivitatem,  ipse et principes ejus simul,  dicit Dominus.  

* Amos 2

** Amos 2:1

Hæc dicit Dominus :  Super tribus sceleribus Moab,  et super quatuor non convertam eum,  eo quod incenderit ossa regis Idumææ usque ad cinerem. 

** Amos 2:2

Et mittam ignem in Moab,  et devorabit ædes Carioth :  et morietur in sonitu Moab, in clangore tubæ. 

** Amos 2:3

Et disperdam judicem de medio ejus,  et omnes principes ejus interficiam cum eo,  dicit Dominus. 

** Amos 2:4

Hæc dicit Dominus :  Super tribus sceleribus Juda,  et super quatuor non convertam eum,  eo quod abjecerit legem Domini  et mandata ejus non custodierit :  deceperant enim eos idola sua,  post quæ abierant patres eorum. 

** Amos 2:5

Et mittam ignem in Juda,  et devorabit ædes Jerusalem. 

** Amos 2:6

Hæc dicit Dominus :  Super tribus sceleribus Israël,  et super quatuor non convertam eum,  pro eo quod vendiderit pro argento justum,  et pauperem pro calceamentis. 

** Amos 2:7

Qui conterunt super pulverem terræ capita pauperum,  et viam humilium declinant :  et filius ac pater ejus ierunt ad puellam,  ut violarent nomen sanctum meum. 

** Amos 2:8

Et super vestimentis pignoratis accubuerunt juxta omne altare,  et vinum damnatorum bibebant in domo Dei sui. 

** Amos 2:9

Ego autem exterminavi Amorrhæum a facie eorum,  cujus altitudo, cedrorum altitudo ejus,  et fortis ipse quasi quercus ;  et contrivi fructum ejus desuper,  et radices ejus subter. 

** Amos 2:10

Ego sum qui ascendere vos feci de terra Ægypti,  et duxi vos in deserto quadraginta annis,  ut possideretis terram Amorrhæi. 

** Amos 2:11

Et suscitavi de filiis vestris in prophetas,  et de juvenibus vestris nazaræos.  Numquid non ita est, filii Israël ? dicit Dominus. 

** Amos 2:12

Et propinabitis nazaræis vinum,  et prophetis mandabitis, dicentes :  Ne prophetetis. 

** Amos 2:13

Ecce ego stridebo subter vos,  sicut stridet plaustrum onustum fœno. 

** Amos 2:14

Et peribit fuga a veloce,  et fortis non obtinebit virtutem suam,  et robustus non salvabit animam suam : 

** Amos 2:15

et tenens arcum non stabit,  et velox pedibus suis non salvabitur,  et ascensor equi non salvabit animam suam : 

** Amos 2:16

et robustus corde inter fortes nudus fugiet in illa die,  dicit Dominus.  

* Amos 3

** Amos 3:1

Audite verbum quod locutus est Dominus super vos, filii Israël,  super omnem cognationem quam eduxi de terra Ægypti, dicens : 

** Amos 3:2

Tantummodo vos cognovi ex omnibus cognationibus terræ ;  idcirco visitabo super vos omnes iniquitates vestras. 

** Amos 3:3

Numquid ambulabunt duo pariter,  nisi convenerit eis ? 

** Amos 3:4

numquid rugiet leo in saltu,  nisi habuerit prædam ?  numquid dabit catulus leonis vocem de cubili suo,  nisi aliquid apprehenderit ? 

** Amos 3:5

numquid cadet avis in laqueum terræ  absque aucupe ?  numquid auferetur laqueus de terra  antequam quid ceperit ? 

** Amos 3:6

si clanget tuba in civitate,  et populus non expavescet ?  si erit malum in civitate,  quod Dominus non fecerit ? 

** Amos 3:7

Quia non facit Dominus Deus verbum,  nisi revelaverit secretum suum ad servos suos prophetas. 

** Amos 3:8

Leo rugiet, quis non timebit ?  Dominus Deus locutus est, quis non prophetabit ? 

** Amos 3:9

Auditum facite in ædibus Azoti,  et in ædibus terræ Ægypti,  et dicite : Congregamini super montes Samariæ,  et videte insanias multas in medio ejus,  et calumniam patientes in penetralibus ejus. 

** Amos 3:10

Et nescierunt facere rectum, dicit Dominus,  thesaurizantes iniquitatem et rapinas in ædibus suis. 

** Amos 3:11

Propterea hæc dicit Dominus Deus :  Tribulabitur et circuietur terra :  et detrahetur ex te fortitudo tua,  et diripientur ædes tuæ. 

** Amos 3:12

Hæc dicit Dominus :  Quomodo si eruat pastor de ore leonis  duo crura, aut extremum auriculæ,  sic eruentur filii Israël, qui habitant in Samaria  in plaga lectuli, et in Damasci grabato. 

** Amos 3:13

Audite, et contestamini in domo Jacob,  dicit Dominus Deus exercituum ; 

** Amos 3:14

quia in die cum visitare cœpero prævaricationes Israël,  super eum visitabo, et super altaria Bethel ;  et amputabuntur cornua altaris, et cadent in terram. 

** Amos 3:15

Et percutiam domum hiemalem cum domo æstiva,  et peribunt domus eburneæ,  et dissipabuntur ædes multæ,  dicit Dominus.  

* Amos 4

** Amos 4:1

Audite verbum hoc, vaccæ pingues,  quæ estis in monte Samariæ,  quæ calumniam facitis egenis  et confringitis pauperes ;  quæ dicitis dominis vestris : Afferte, et bibemus. 

** Amos 4:2

Juravit Dominus Deus in sancto suo,  quia ecce dies venient super vos,  et levabunt vos in contis,  et reliquias vestras in ollis ferventibus. 

** Amos 4:3

Et per aperturas exibitis altera contra alteram,  et projiciemini in Armon,  dicit Dominus. 

** Amos 4:4

Venite ad Bethel, et impie agite ;  ad Galgalam, et multiplicate prævaricationem :  et afferte mane victimas vestras,  tribus diebus decimas vestras. 

** Amos 4:5

Et sacrificate de fermentato laudem,  et vocate voluntarias oblationes, et annuntiate ;  sic enim voluistis, filii Israël,  dicit Dominus Deus. 

** Amos 4:6

Unde et ego dedi vobis stuporem dentium in cunctis urbibus vestris,  et indigentiam panum in omnibus locis vestris ;  et non estis reversi ad me,  dicit Dominus. 

** Amos 4:7

Ego quoque prohibui a vobis imbrem,  cum adhuc tres menses superessent usque ad messem :  et plui super unam civitatem,  et super alteram civitatem non plui ;  pars una compluta est,  et pars super quam non plui, aruit. 

** Amos 4:8

Et venerunt duæ et tres civitates ad unam civitatem  ut biberent aquam, et non sunt satiatæ ;  et non redistis ad me,  dicit Dominus. 

** Amos 4:9

Percussi vos in vento urente, et in aurugine :  multitudinem hortorum vestrorum et vinearum vestrarum,  oliveta vestra et ficeta vestra comedit eruca :  et non redistis ad me,  dicit Dominus. 

** Amos 4:10

Misi in vos mortem in via Ægypti ;  percussi in gladio juvenes vestros,  usque ad captivitatem equorum vestrorum,  et ascendere feci putredinem castrorum vestrorum in nares vestras :  et non redistis ad me,  dicit Dominus. 

** Amos 4:11

Subverti vos sicut subvertit Deus Sodomam et Gomorrham,  et facti estis quasi torris raptus ab incendio :  et non redistis ad me,  dicit Dominus. 

** Amos 4:12

Quapropter hæc faciam tibi, Israël :  postquam autem hæc fecero tibi,  præparare in occursum Dei tui, Israël. 

** Amos 4:13

Quia ecce formans montes,  et creans ventum,  et annuntians homini eloquium suum,  faciens matutinam nebulam,  et gradiens super excelsa terræ :  Dominus Deus exercituum nomen ejus.  

* Amos 5

** Amos 5:1

Audite verbum istud,  quod ego levo super vos planctum :  domus Israël cecidit,  et non adjiciet ut resurgat. 

** Amos 5:2

Virgo Israël projecta est in terram suam,  non est qui suscitet eam. 

** Amos 5:3

Quia hæc dicit Dominus Deus :  Urbs de qua egrediebantur mille,  relinquentur in ea centum ;  et de qua egrediebantur centum,  relinquentur in ea decem in domo Israël. 

** Amos 5:4

Quia hæc dicit Dominus domui Israël :  Quærite me, et vivetis. 

** Amos 5:5

Et nolite quærere Bethel,  et in Galgalam nolite intrare,  et in Bersabee non transibitis,  quia Galgala captiva ducetur,  et Bethel erit inutilis. 

** Amos 5:6

Quærite Dominum, et vivite  (ne forte comburatur ut ignis domus Joseph, et devorabit,  et non erit qui extinguat Bethel : 

** Amos 5:7

qui convertitis in absinthium judicium,  et justitiam in terra relinquitis) : 

** Amos 5:8

facientem Arcturum et Orionem,  et convertentem in mane tenebras,  et diem in noctem mutantem ;  qui vocat aquas maris,  et effundit eas super faciem terræ ;  Dominus nomen est ejus : 

** Amos 5:9

qui subridet vastitatem super robustum,  et depopulationem super potentem affert. 

** Amos 5:10

Odio habuerunt corripientem in porta,  et loquentem perfecte abominati sunt. 

** Amos 5:11

Idcirco, pro eo quod diripiebatis pauperem,  et prædam electam tollebatis ab eo,  domos quadro lapide ædificabitis,  et non habitabitis in eis ;  vineas plantabis amantissimas,  et non bibetis vinum earum. 

** Amos 5:12

Quia cognovi multa scelera vestra,  et fortia peccata vestra :  hostes justi, accipientes munus,  et pauperes deprimentes in porta. 

** Amos 5:13

Ideo prudens in tempore illo tacebit,  quia tempus malum est. 

** Amos 5:14

Quærite bonum, et non malum, ut vivatis ;  et erit Dominus Deus exercituum vobiscum, sicut dixistis. 

** Amos 5:15

Odite malum et diligite bonum,  et constituite in porta judicium :  si forte misereatur Dominus Deus exercituum reliquiis Joseph. 

** Amos 5:16

Propterea hæc dicit Dominus Deus exercituum, dominator :  In omnibus plateis planctus ;  et in cunctis quæ foris sunt, dicetur : Væ, væ !  et vocabunt agricolam ad luctum,  et ad planctum eos qui sciunt plangere. 

** Amos 5:17

Et in omnibus vineis erit planctus,  quia pertransibo in medio tui,  dicit Dominus. 

** Amos 5:18

Væ desiderantibus diem Domini !  ad quid eam vobis ?  Dies Domini ista, tenebræ, et non lux. 

** Amos 5:19

Quomodo si fugiat vir a facie leonis,  et occurrat ei ursus ;  et ingrediatur domum, et innitatur manu sua super parietem,  et mordeat eum coluber. 

** Amos 5:20

Numquid non tenebræ dies Domini, et non lux ;  et caligo, et non splendor in ea ? 

** Amos 5:21

Odi, et projeci festivitates vestras,  et non capiam odorem cœtuum vestrorum. 

** Amos 5:22

Quod si obtuleritis mihi holocautomata, et munera vestra,  non suscipiam ;  et vota pinguium vestrorum non respiciam. 

** Amos 5:23

Aufer a me tumultum carminum tuorum ;  et cantica lyræ tuæ non audiam. 

** Amos 5:24

Et revelabitur quasi aqua judicium,  et justitia quasi torrens fortis. 

** Amos 5:25

Numquid hostias et sacrificium obtulistis mihi  in deserto quadraginta annis, domus Israël ?

** Amos 5:26

et portastis tabernaculum Moloch vestro,  et imaginem idolorum vestrorum, sidus dei vestri,  quæ fecistis vobis. 

** Amos 5:27

Et migrare vos faciam trans Damascum, dicit Dominus :  Deus exercituum nomen ejus.  

* Amos 6

** Amos 6:1

Væ qui opulenti estis in Sion,  et confiditis in monte Samariæ :  optimates capita populorum,  ingredientes pompatice domum Israël ! 

** Amos 6:2

Transite in Chalane, et videte,  et ite inde in Emath magnam,  et descendite in Geth Palæstinorum,  et ad optima quæque regna horum :  si latior terminus eorum termino vestro est. 

** Amos 6:3

Qui separati estis in diem malum,  et appropinquatis solio iniquitatis ; 

** Amos 6:4

qui dormitis in lectis eburneis,  et lascivitis in stratis vestris ;  qui comeditis agnum de grege,  et vitulos de medio armenti ; 

** Amos 6:5

qui canitis ad vocem psalterii,  sicut David putaverunt se habere vasa cantici, 

** Amos 6:6

bibentes vinum in phialis,  et optimo unguento delibuti,  et nihil patiebantur super contritione Joseph. 

** Amos 6:7

Quapropter nunc migrabunt in capite transmigrantium,  et auferetur factio lascivientium. 

** Amos 6:8

Juravit Dominus Deus in anima sua,  dicit Dominus Deus exercituum :  Detestor ego superbiam Jacob,  et domos ejus odi,  et tradam civitatem cum habitatoribus suis. 

** Amos 6:9

Quod si reliqui fuerint decem viri in domo una,  et ipsi morientur. 

** Amos 6:10

Et tollet eum propinquus suus, et comburet eum,  ut efferat ossa de domo ;  et dicet ei, qui in penetralibus domus est :  Numquid adhuc est penes te ? 

** Amos 6:11

Et respondebit : Finis est.  Et dicet ei : Tace,  et non recorderis nominis Domini. 

** Amos 6:12

Quia ecce Dominus mandabit,  et percutiet domum majorem ruinis,  et domum minorem scissionibus. 

** Amos 6:13

Numquid currere queunt in petris equi,  aut arari potest in bubalis ?  quoniam convertistis in amaritudinem judicium,  et fructum justitiæ in absinthium. 

** Amos 6:14

Qui lætamini in nihilo ; qui dicitis :  Numquid non in fortitudine nostra assumpsimus nobis cornua ? 

** Amos 6:15

Ecce enim suscitabo super vos, domus Israël,  dicit Dominus Deus exercituum, gentem,  et conteret vos ab introitu Emath usque ad torrentem deserti.  

* Amos 7

** Amos 7:1

Hæc ostendit mihi Dominus Deus : et ecce fictor locustæ in principio germinantium serotini imbris, et ecce serotinus post tonsionem regis.

** Amos 7:2

Et factum est, cum consummasset comedere herbam terræ, dixi : Domine Deus, propitius esto, obsecro ; quis suscitabit Jacob, quia parvulus est ?

** Amos 7:3

Misertus est Dominus super hoc : Non erit, dixit Dominus.

** Amos 7:4

Hæc ostendit mihi Dominus Deus : et ecce vocabat judicium ad ignem Dominus Deus ; et devoravit abyssum multam, et comedit simul partem.

** Amos 7:5

Et dixi : Domine Deus, quiesce, obsecro ; quis suscitabit Jacob, quia parvulus est ?

** Amos 7:6

Misertus est Dominus super hoc : Sed et istud non erit, dixit Dominus Deus.

** Amos 7:7

Hæc ostendit mihi Dominus : et ecce Dominus stans super murum litum, et in manu ejus trulla cæmentarii.

** Amos 7:8

Et dixit Dominus ad me : Quid tu vides, Amos ? Et dixi : Trullam cæmentarii. Et dixit Dominus :   Ecce ego ponam trullam in medio populi mei Israël ;  non adjiciam ultra superinducere eum. 

** Amos 7:9

Et demolientur excelsa idoli,  et sanctificationes Israël desolabuntur,  et consurgam super domum Jeroboam in gladio.

** Amos 7:10

Et misit Amasias, sacerdos Bethel, ad Jeroboam, regem Israël, dicens : Rebellavit contra te Amos in medio domus Israël ; non poterit terra sustinere universos sermones ejus.

** Amos 7:11

Hæc enim dicit Amos : In gladio morietur Jeroboam, et Israël captivus migrabit de terra sua.

** Amos 7:12

Et dixit Amasias ad Amos : Qui vides, gradere : fuge in terram Juda, et comede ibi panem, et prophetabis ibi.

** Amos 7:13

Et in Bethel non adjicies ultra ut prophetes, quia sanctificatio regis est, et domus regni est.

** Amos 7:14

Responditque Amos, et dixit ad Amasiam : Non sum propheta, et non sum filius prophetæ : sed armentarius ego sum vellicans sycomoros.

** Amos 7:15

Et tulit me Dominus cum sequerer gregem, et dixit Dominus ad me : Vade, propheta ad populum meum Israël.

** Amos 7:16

Et nunc audi verbum Domini :  Tu dicis : Non prophetabis super Israël,  et non stillabis super domum idoli. 

** Amos 7:17

Propter hoc hæc dicit Dominus :  Uxor tua in civitate fornicabitur,  et filii tui et filiæ tuæ in gladio cadent,  et humus tua funiculo metietur :  et tu in terra polluta morieris,  et Israël captivus migrabit de terra sua.  

* Amos 8

** Amos 8:1

Hæc ostendit mihi Dominus Deus : et ecce uncinus pomorum.

** Amos 8:2

Et dixit : Quid tu vides, Amos ? Et dixi : Uncinum pomorum. Et dixit Dominus ad me :   Venit finis super populum meum Israël ;  non adjiciam ultra ut pertranseam eum. 

** Amos 8:3

Et stridebunt cardines templi in die illa,  dicit Dominus Deus :  multi morientur ;  in omni loco projicietur silentium. 

** Amos 8:4

Audite hoc, qui conteritis pauperem,  et deficere facitis egenos terræ, 

** Amos 8:5

dicentes : Quando transibit mensis,  et venundabimus merces ?  et sabbatum, et aperiemus frumentum,  ut imminuamus mensuram, et augeamus siclum,  et supponamus stateras dolosas, 

** Amos 8:6

ut possideamus in argento egenos et pauperes pro calceamentis,  et quisquilias frumenti vendamus ? 

** Amos 8:7

Juravit Dominus in superbiam Jacob :  Si oblitus fuero usque ad finem omnia opera eorum. 

** Amos 8:8

Numquid super isto non commovebitur terra,  et lugebit omnis habitator ejus,  et ascendet quasi fluvius universus,  et ejicicetur, et defluet, quasi rivus Ægypti ? 

** Amos 8:9

Et erit in die illa, dicit Dominus Deus :  occidet sol in meridie,  et tenebrescere faciam terram in die luminis : 

** Amos 8:10

et convertam festivitates vestras in luctum,  et omnia cantica vestra in planctum,  et inducam super omne dorsum vestrum saccum,  et super omne caput calvitium :  et ponam eam quasi luctum unigeniti,  et novissima ejus quasi diem amarum. 

** Amos 8:11

Ecce dies veniunt, dicet Dominus,  et mittam famem in terram :  non famem panis, neque sitim aquæ,  sed audiendi verbum Domini. 

** Amos 8:12

Et commovebuntur a mari usque ad mare,  et ab aquilone usque ad orientem :  circuibunt quærentes verbum Domini,  et non invenient. 

** Amos 8:13

In die illa deficient virgines pulchræ et adolescentes in siti, 

** Amos 8:14

qui jurant in delicto Samariæ,  et dicunt : Vivit Deus tuus, Dan,  et vivit via Bersabee ;  et cadent, et non resurgent ultra.  

* Amos 9

** Amos 9:1

Vidi Dominum stantem super altare, et dixit :   Percute cardinem,  et commoveantur superliminaria :  avaritia enim in capite omnium,  et novissimum eorum in gladio interficiam ;  non erit fuga eis.  Fugient, et non salvabitur ex eis qui fugerit. 

** Amos 9:2

Si descenderint usque ad infernum,  inde manus mea educet eos ;  et si ascenderint usque in cælum,  inde detraham eos. 

** Amos 9:3

Et si absconditi fuerint in vertice Carmeli,  inde scrutans auferam eos ;  et si celaverint se ab oculis meis in profundo maris,  ibi mandabo serpenti, et mordebit eos. 

** Amos 9:4

Et si abierint in captivitatem coram inimicis suis,  ibi mandabo gladio, et occidet eos :  et ponam oculos meos super eos in malum,  et non in bonum. 

** Amos 9:5

Et Dominus Deus exercituum, qui tangit terram, et tabescet,  et lugebunt omnes habitantes in ea :  et ascendet sicut rivus omnis,  et defluet sicut fluvius Ægypti. 

** Amos 9:6

Qui ædificat in cælo ascensionem suam,  et fasciculum suum super terram fundavit ;  qui vocat aquas maris,  et effundit eas super faciem terræ :  Dominus nomen ejus. 

** Amos 9:7

Numquid non ut filii Æthiopum  vos estis mihi, filii Israël ? ait Dominus.  Numquid non Israël ascendere feci de terra Ægypti,  et Palæstinos de Cappadocia,  et Syros de Cyrene ? 

** Amos 9:8

Ecce oculi Domini Dei super regnum peccans :  et conteram illud a facie terræ ;  verumtamen conterens non conteram domum Jacob,  dicit Dominus. 

** Amos 9:9

Ecce enim mandabo ego,  et concutiam in omnibus gentibus domum Israël,  sicut concutitur triticum in cribro,  et non cadet lapillus super terram. 

** Amos 9:10

In gladio morientur omnes peccatores populi mei,  qui dicunt : Non appropinquabit,  et non veniet super nos malum. 

** Amos 9:11

In die illa suscitabo tabernaculum David, quod cecidit :  et reædificabo aperturas murorum ejus,  et ea quæ corruerant instaurabo :  et reædificabo illud sicut in diebus antiquis, 

** Amos 9:12

ut possideant reliquias Idumææ, et omnes nationes :  eo quod invocatum sit nomen meum super eos,  dicit Dominus faciens hæc. 

** Amos 9:13

Ecce dies veniunt, dicit Dominus,  et comprehendet arator messorem,  et calcator uvæ mittentem semen :  et stillabunt montes dulcedinem,  et omnes colli culti erunt. 

** Amos 9:14

Et convertam captivitatem populi mei Israël ;  et ædificabunt civitates desertas, et inhabitabunt ;  et plantabunt vineas, et bibent vinum earum,  et facient hortos, et comedent fructus eorum. 

** Amos 9:15

Et plantabo eos super humum suam,  et non evellam eos ultra de terra sua, quam dedi eis,  dicit Dominus Deus tuus.    

