* Colossians 1

** Colossians 1:1

Paulus Apostolus Jesu Christi per voluntatem Dei, et Timotheus frater :

** Colossians 1:2

eis, qui sunt Colossis, sanctis, et fidelibus fratribus in Christo Jesu.

** Colossians 1:3

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.   Gratias agimus Deo, et Patri Domini nostri Jesu Christi semper pro vobis orantes :

** Colossians 1:4

audientes fidem vestram in Christo Jesu, et dilectionem quam habetis in sanctos omnes

** Colossians 1:5

propter spem, quæ reposita est vobis in cælis : quam audistis in verbo veritatis Evangelii :

** Colossians 1:6

quod pervenit ad vos, sicut et in universo mundo est, et fructificat, et crescit sicut in vobis, ex ea die, qua audistis, et cognovistis gratiam Dei in veritate,

** Colossians 1:7

sicut didicistis ab Epaphra carissimo conservo nostro, qui est fidelis pro vobis minister Christi Jesu,

** Colossians 1:8

qui etiam manifestavit nobis dilectionem vestram in spiritu.

** Colossians 1:9

Ideo et nos ex qua die audivimus, non cessamus pro vobis orantes, et postulantes ut impleamini agnitione voluntatis ejus, in omni sapientia et intellectu spiritali :

** Colossians 1:10

ut ambuletis digne Deo per omnia placentes : in omni opere bono fructificantes, et crescentes in scientia Dei :

** Colossians 1:11

in omni virtute confortati secundum potentiam claritatis ejus, in omni patientia et longanimitate cum gaudio,

** Colossians 1:12

gratias agentes Deo Patri, qui dignos nos fecit in partem sortis sanctorum in lumine :

** Colossians 1:13

qui eripuit nos de potestate tenebrarum, et transtulit in regnum filii dilectionis suæ,

** Colossians 1:14

in quo habemus redemptionem per sanguinem ejus, remissionem peccatorum :

** Colossians 1:15

qui est imago Dei invisibilis, primogenitus omnis creaturæ :

** Colossians 1:16

quoniam in ipso condita sunt universa in cælis, et in terra, visibilia, et invisibilia, sive throni, sive dominationes, sive principatus, sive potestates : omnia per ipsum et in ipso creata sunt :

** Colossians 1:17

et ipse est ante omnes, et omnia in ipso constant.  

** Colossians 1:18

Et ipse est caput corporis Ecclesiæ, qui est principium, primogenitus ex mortuis : ut sit in omnibus ipse primatum tenens :

** Colossians 1:19

quia in ipso complacuit, omnem plenitudinem inhabitare :

** Colossians 1:20

et per eum reconciliare omnia in ipsum, pacificans per sanguinem crucis ejus, sive quæ in terris, sive quæ in cælis sunt.

** Colossians 1:21

Et vos cum essetis aliquando alienati, et inimici sensu in operibus malis :

** Colossians 1:22

nunc autem reconciliavit in corpore carnis ejus per mortem, exhibere vos sanctos, et immaculatos, et irreprehensibiles coram ipso :

** Colossians 1:23

si tamen permanetis in fide fundati, et stabiles, et immobiles a spe Evangelii, quod audistis, quod prædicatum est in universa creatura, quæ sub cælo est, cujus factus sum ego Paulus minister.  

** Colossians 1:24

Qui nunc gaudeo in passionibus pro vobis, et adimpleo ea quæ desunt passionum Christi, in carne mea pro corpore ejus, quod est Ecclesia :

** Colossians 1:25

cujus factus sum ego minister secundum dispensationem Dei, quæ data est mihi in vos, ut impleam verbum Dei :

** Colossians 1:26

mysterium, quod absconditum fuit a sæculis, et generationibus, nunc autem manifestatum est sanctis ejus,

** Colossians 1:27

quibus voluit Deus notas facere divitias gloriæ sacramenti hujus in gentibus, quod est Christus, in vobis spes gloriæ,

** Colossians 1:28

quem nos annuntiamus, corripientes omnem hominem, et docentes omnem hominem, in omni sapientia, ut exhibeamus omnem hominem perfectum in Christo Jesu :

** Colossians 1:29

in quo et laboro, certando secundum operationem ejus, quam operatur in me in virtute.   

* Colossians 2

** Colossians 2:1

Volo enim vos scire qualem sollicitudinem habeam pro vobis, et pro iis qui sunt Laodiciæ, et quicumque non viderunt faciem meam in carne :

** Colossians 2:2

ut consolentur corda ipsorum, instructi in caritate, et in omnes divitias plenitudinis intellectus, in agnitionem mysterii Dei Patris et Christi Jesu :

** Colossians 2:3

in quo sunt omnes thesauri sapientiæ et scientiæ absconditi.  

** Colossians 2:4

Hoc autem dico, ut nemo vos decipiat in sublimitate sermonum.

** Colossians 2:5

Nam etsi corpore absens sum, sed spiritu vobiscum sum : gaudens, et videns ordinem vestrum, et firmamentum ejus, quæ in Christo est, fidei vestræ.

** Colossians 2:6

Sicut ergo accepistis Jesum Christum Dominum, in ipso ambulate,

** Colossians 2:7

radicati, et superædificati in ipso, et confirmati fide, sicut et didicistis, abundantes in illo in gratiarum actione.

** Colossians 2:8

Videte ne quis vos decipiat per philosophiam, et inanem fallaciam secundum traditionem hominum, secundum elementa mundi, et non secundum Christum :

** Colossians 2:9

quia in ipso inhabitat omnis plenitudo divinitatis corporaliter :

** Colossians 2:10

et estis in illo repleti, qui est caput omnis principatus et potestatis :

** Colossians 2:11

in quo et circumcisi estis circumcisione non manu facta in expoliatione corporis carnis, sed in circumcisione Christi :

** Colossians 2:12

consepulti ei in baptismo, in quo et resurrexistis per fidem operationis Dei, qui suscitavit illum a mortuis.

** Colossians 2:13

Et vos cum mortui essetis in delictis, et præputio carnis vestræ, convivificavit cum illo, donans vobis omnia delicta :

** Colossians 2:14

delens quod adversus nos erat chirographum decreti, quod erat contrarium nobis, et ipsum tulit de medio, affigens illud cruci :

** Colossians 2:15

et expolians principatus, et potestates traduxit confidenter, palam triumphans illos in semetipso.  

** Colossians 2:16

Nemo ergo vos judicet in cibo, aut in potu, aut in parte diei festi, aut neomeniæ, aut sabbatorum :

** Colossians 2:17

quæ sunt umbra futurorum : corpus autem Christi.

** Colossians 2:18

Nemo vos seducat, volens in humilitate, et religione angelorum, quæ non vidit ambulans, frustra inflatus sensu carnis suæ,

** Colossians 2:19

et non tenens caput, ex quo totum corpus per nexus, et conjunctiones subministratum, et constructum crescit in augmentum Dei.

** Colossians 2:20

Si ergo mortui estis cum Christo ab elementis hujus mundi : quid adhuc tamquam viventes in mundo decernitis ?

** Colossians 2:21

Ne tetigeritis, neque gustaveritis, neque contrectaveritis :

** Colossians 2:22

quæ sunt omnia in interitum ipso usu, secundum præcepta et doctrinas hominum :

** Colossians 2:23

quæ sunt rationem quidem habentia sapientiæ in superstitione, et humilitate, et non ad parcendum corpori, non in honore aliquo ad saturitatem carnis.   

* Colossians 3

** Colossians 3:1

Igitur, si consurrexistis cum Christo : quæ sursum sunt quærite, ubi Christus est in dextera Dei sedens :

** Colossians 3:2

quæ sursum sunt sapite, non quæ super terram.

** Colossians 3:3

Mortui enim estis, et vita vestra est abscondita cum Christo in Deo.

** Colossians 3:4

Cum Christus apparuerit, vita vestra : tunc et vos apparebitis cum ipso in gloria.

** Colossians 3:5

Mortificate ergo membra vestra, quæ sunt super terram : fornicationem, immunditiam, libidinem, concupiscentiam malam, et avaritiam, quæ est simulacrorum servitus :

** Colossians 3:6

propter quæ venit ira Dei super filios incredulitatis :

** Colossians 3:7

in quibus et vos ambulastis aliquando, cum viveretis in illis.

** Colossians 3:8

Nunc autem deponite et vos omnia : iram, indignationem, malitiam, blasphemiam, turpem sermonem de ore vestro.

** Colossians 3:9

Nolite mentiri invicem, expoliantes vos veterem hominem cum actibus suis,

** Colossians 3:10

et induentes novum eum, qui renovatur in agnitionem secundum imaginem ejus qui creavit illum :

** Colossians 3:11

ubi non est gentilis et Judæus, circumcisio et præputium, Barbarus et Scytha, servus et liber : sed omnia, et in omnibus Christus.

** Colossians 3:12

Induite vos ergo, sicut electi Dei, sancti, et dilecti, viscera misericordiæ, benignitatem, humilitatem, modestiam, patientiam :

** Colossians 3:13

supportantes invicem, et donantes vobismetipsis si quis adversus aliquem habet querelam : sicut et Dominus donavit vobis, ita et vos.

** Colossians 3:14

Super omnia autem hæc, caritatem habete, quod est vinculum perfectionis :

** Colossians 3:15

et pax Christi exsultet in cordibus vestris, in qua et vocati estis in uno corpore : et grati estote.

** Colossians 3:16

Verbum Christi habitet in vobis abundanter, in omni sapientia, docentes, et commonentes vosmetipsos, psalmis, hymnis, et canticis spiritualibus, in gratia cantantes in cordibus vestris Deo.

** Colossians 3:17

Omne, quodcumque facitis in verbo aut in opere, omnia in nomine Domini Jesu Christi, gratias agentes Deo et Patri per ipsum.  

** Colossians 3:18

Mulieres, subditæ estote viris, sicut oportet, in Domino.

** Colossians 3:19

Viri, diligite uxores vestras, et nolite amari esse ad illas.

** Colossians 3:20

Filii, obedite parentibus per omnia : hoc enim placitum est in Domino.

** Colossians 3:21

Patres, nolite ad indignationem provocare filios vestros, ut non pusillo animo fiant.

** Colossians 3:22

Servi, obedite per omnia dominis carnalibus, non ad oculum servientes, quasi hominibus placentes, sed in simplicitate cordis, timentes Deum.

** Colossians 3:23

Quodcumque facitis, ex animo operamini sicut Domino, et non hominibus :

** Colossians 3:24

scientes quod a Domino accipietis retributionem hæreditatis. Domino Christo servite.

** Colossians 3:25

Qui enim injuriam facit, recipiet id quod inique gessit : et non est personarum acceptio apud Deum.   

* Colossians 4

** Colossians 4:1

Domini, quod justum est et æquum, servis præstate : scientes quod et vos Dominum habetis in cælo.  

** Colossians 4:2

Orationi instate, vigilantes in ea in gratiarum actione :

** Colossians 4:3

orantes simul et pro nobis, ut Deus aperiat nobis ostium sermonis ad loquendum mysterium Christi (propter quod etiam vinctus sum),

** Colossians 4:4

ut manifestem illud ita ut oportet me loqui.

** Colossians 4:5

In sapientia ambulate ad eos, qui foris sunt : tempus redimentes.

** Colossians 4:6

Sermo vester semper in gratia sale sit conditus, ut sciatis quomodo oporteat vos unicuique respondere.  

** Colossians 4:7

Quæ circa me sunt, omnia vobis nota faciet Tychicus, carissimus frater, et fidelis minister, et conservus in Domino :

** Colossians 4:8

quem misi ad vos ad hoc ipsum, ut cognoscat quæ circa vos sunt, et consoletur corda vestra,

** Colossians 4:9

cum Onesimo carissimo, et fideli fratre, qui ex vobis est. Omnia, quæ hic aguntur, nota facient vobis.  

** Colossians 4:10

Salutat vos Aristarchus concaptivus meus, et Marcus consobrinus Barnabæ, de quo accepistis mandata : si venerit ad vos, excipite illum :

** Colossians 4:11

et Jesus, qui dicitur Justus : qui sunt ex circumcisione : hi soli sunt adjutores mei in regno Dei, qui mihi fuerunt solatio.

** Colossians 4:12

Salutat vos Epaphras, qui ex vobis est, servus Christi Jesu, semper sollicitus pro vobis in orationibus, ut stetis perfecti, et pleni in omni voluntate Dei.

** Colossians 4:13

Testimonium enim illi perhibeo quod habet multum laborem pro vobis, et pro iis qui sunt Laodiciæ, et qui Hierapoli.

** Colossians 4:14

Salutat vos Lucas, medicus carissimus, et Demas.

** Colossians 4:15

Salutate fratres, qui sunt Laodiciæ, et Nympham, et quæ in domo ejus est, ecclesiam.

** Colossians 4:16

Et cum lecta fuerit apud vos epistola hæc, facite ut et in Laodicensium ecclesia legatur : et eam, quæ Laodicensium est, vos legatis.

** Colossians 4:17

Et dicite Archippo : Vide ministerium, quod accepisti in Domino, ut illud impleas.

** Colossians 4:18

Salutatio, mea manu Pauli. Memores estote vinculorum meorum. Gratia vobiscum. Amen.    

