* Ecclesiastes 1

** Ecclesiastes 1:1

Verba Ecclesiastæ, filii David, regis Jerusalem.  

** Ecclesiastes 1:2

Vanitas vanitatum, dixit Ecclesiastes ;  vanitas vanitatum, et omnia vanitas. 

** Ecclesiastes 1:3

Quid habet amplius homo  de universo labore suo quo laborat sub sole ? 

** Ecclesiastes 1:4

Generatio præterit, et generatio advenit ;  terra autem in æternum stat. 

** Ecclesiastes 1:5

Oritur sol et occidit,  et ad locum suum revertitur ;  ibique renascens,

** Ecclesiastes 1:6

gyrat per meridiem, et flectitur ad aquilonem.  Lustrans universa in circuitu pergit spiritus,  et in circulos suos revertitur. 

** Ecclesiastes 1:7

Omnia flumina intrant in mare,  et mare non redundat ;  ad locum unde exeunt flumina  revertuntur ut iterum fluant. 

** Ecclesiastes 1:8

Cunctæ res difficiles ;  non potest eas homo explicare sermone.  Non saturatur oculus visu,  nec auris auditu impletur. 

** Ecclesiastes 1:9

Quid est quod fuit ? Ipsum quod futurum est.  Quid est quod factum est ? Ipsum quod faciendum est. 

** Ecclesiastes 1:10

Nihil sub sole novum,  nec valet quisquam dicere : Ecce hoc recens est :  jam enim præcessit in sæculis quæ fuerunt ante nos. 

** Ecclesiastes 1:11

Non est priorum memoria ;  sed nec eorum quidem quæ postea futura sunt  erit recordatio apud eos qui futuri sunt in novissimo. 

** Ecclesiastes 1:12

Ego Ecclesiastes fui rex Israël in Jerusalem ; 

** Ecclesiastes 1:13

et proposui in animo meo quærere et investigare sapienter  de omnibus quæ fiunt sub sole.  Hanc occupationem pessimam  dedit Deus filiis hominum, ut occuparentur in ea. 

** Ecclesiastes 1:14

Vidi cuncta quæ fiunt sub sole,  et ecce universa vanitas et afflictio spiritus. 

** Ecclesiastes 1:15

Perversi difficile corriguntur,  et stultorum infinitus est numerus. 

** Ecclesiastes 1:16

Locutus sum in corde meo, dicens :  Ecce magnus effectus sum, et præcessi omnes sapientia  qui fuerunt ante me in Jerusalem ;  et mens mea contemplata est multa sapienter, et didici. 

** Ecclesiastes 1:17

Dedique cor meum ut scirem prudentiam atque doctrinam,  erroresque et stultitiam ;  et agnovi quod in his quoque esset labor et afflictio spiritus : 

** Ecclesiastes 1:18

eo quod in multa sapientia multa sit indignatio ;  et qui addit scientiam, addit et laborem.  

* Ecclesiastes 2

** Ecclesiastes 2:1

Dixi ego in corde meo : Vadam,  et affluam deliciis, et fruar bonis ;  et vidi quod hoc quoque esset vanitas. 

** Ecclesiastes 2:2

Risum reputavi errorem,  et gaudio dixi : Quid frustra deciperis ? 

** Ecclesiastes 2:3

Cogitavi in corde meo abstrahere a vino carnem meam,  ut animam meam transferrem ad sapientiam,  devitaremque stultitiam,  donec viderem quid esset utile filiis hominum,  quo facto opus est sub sole numero dierum vitæ suæ. 

** Ecclesiastes 2:4

Magnificavi opera mea,  ædificavi mihi domos,  et plantavi vineas ; 

** Ecclesiastes 2:5

feci hortos et pomaria,  et consevi ea cuncti generis arboribus ; 

** Ecclesiastes 2:6

et exstruxi mihi piscinas aquarum,  ut irrigarem silvam lignorum germinantium. 

** Ecclesiastes 2:7

Possedi servos et ancillas,  multamque familiam habui :  armenta quoque, et magnos ovium greges,  ultra omnes qui fuerunt ante me in Jerusalem ; 

** Ecclesiastes 2:8

coacervavi mihi argentum et aurum,  et substantias regum ac provinciarum ;  feci mihi cantores et cantatrices,  et delicias filiorum hominum,  scyphos, et urceos in ministerio ad vina fundenda ; 

** Ecclesiastes 2:9

et supergressus sum opibus  omnes qui ante me fuerunt in Jerusalem :  sapientia quoque perseveravit mecum. 

** Ecclesiastes 2:10

Et omnia quæ desideraverunt oculi mei  non negavi eis,  nec prohibui cor meum quin omni voluptate frueretur,  et oblectaret se in his quæ præparaveram ;  et hanc ratus sum partem meam si uterer labore meo. 

** Ecclesiastes 2:11

Cumque me convertissem ad universa opera quæ fecerant manus meæ,  et ad labores in quibus frustra sudaveram,  vidi in omnibus vanitatem et afflictionem animi,  et nihil permanere sub sole. 

** Ecclesiastes 2:12

Transivi ad contemplandam sapientiam,  erroresque, et stultitiam.  (Quid est, inquam, homo,  ut sequi possit regem, factorem suum ?) 

** Ecclesiastes 2:13

Et vidi quod tantum præcederet sapientia stultitiam,  quantum differt lux a tenebris. 

** Ecclesiastes 2:14

Sapientis oculi in capite ejus ;  stultus in tenebris ambulat :  et didici quod unus utriusque esset interitus. 

** Ecclesiastes 2:15

Et dixi in corde meo :  Si unus et stulti et meus occasus erit,  quid mihi prodest quod majorem sapientiæ dedi operam ?  Locutusque cum mente mea,  animadverti quod hoc quoque esset vanitas. 

** Ecclesiastes 2:16

Non enim erit memoria sapientis similiter ut stulti in perpetuum,  et futura tempora oblivione cuncta pariter operient :  moritur doctus similiter ut indoctus. 

** Ecclesiastes 2:17

Et idcirco tæduit me vitæ meæ,  videntem mala universa esse sub sole,  et cuncta vanitatem et afflictionem spiritus. 

** Ecclesiastes 2:18

Rursus detestatus sum omnem industriam meam,  qua sub sole studiosissime laboravi,  habiturus hæredem post me, 

** Ecclesiastes 2:19

quem ignoro utrum sapiens an stultus futurus sit,  et dominabitur in laboribus meis,  quibus desudavi et sollicitus fui :  et est quidquam tam vanum ? 

** Ecclesiastes 2:20

Unde cessavi,  renuntiavitque cor meum ultra laborare sub sole. 

** Ecclesiastes 2:21

Nam cum alius laboret in sapientia,  et doctrina, et sollicitudine,  homini otioso quæsita dimittit ;  et hoc ergo vanitas et magnum malum. 

** Ecclesiastes 2:22

Quid enim proderit homini de universo labore suo,  et afflictione spiritus,  qua sub sole cruciatus est ? 

** Ecclesiastes 2:23

Cuncti dies ejus doloribus et ærumnis pleni sunt,  nec per noctem mente requiescit.  Et hoc nonne vanitas est ? 

** Ecclesiastes 2:24

Nonne melius est comedere et bibere,  et ostendere animæ suæ bona de laboribus suis ?  et hoc de manu Dei est. 

** Ecclesiastes 2:25

Quis ita devorabit et deliciis affluet ut ego ? 

** Ecclesiastes 2:26

Homini bono in conspectu suo  dedit Deus sapientiam, et scientiam, et lætitiam ;  peccatori autem dedit afflictionem et curam superfluam,  ut addat, et congreget,  et tradat ei qui placuit Deo ;  sed et hoc vanitas est, et cassa sollicitudo mentis.  

* Ecclesiastes 3

** Ecclesiastes 3:1

Omnia tempus habent,  et suis spatiis transeunt universa sub cælo. 

** Ecclesiastes 3:2

Tempus nascendi, et tempus moriendi ;  tempus plantandi, et tempus evellendi quod plantatum est. 

** Ecclesiastes 3:3

Tempus occidendi, et tempus sanandi ;  tempus destruendi, et tempus ædificandi. 

** Ecclesiastes 3:4

Tempus flendi, et tempus ridendi ;  tempus plangendi, et tempus saltandi. 

** Ecclesiastes 3:5

Tempus spargendi lapides, et tempus colligendi,  tempus amplexandi, et tempus longe fieri ab amplexibus. 

** Ecclesiastes 3:6

Tempus acquirendi, et tempus perdendi ;  tempus custodiendi, et tempus abjiciendi. 

** Ecclesiastes 3:7

Tempus scindendi, et tempus consuendi ;  tempus tacendi, et tempus loquendi. 

** Ecclesiastes 3:8

Tempus dilectionis, et tempus odii ;  tempus belli, et tempus pacis. 

** Ecclesiastes 3:9

Quid habet amplius homo de labore suo ? 

** Ecclesiastes 3:10

Vidi afflictionem quam dedit Deus filiis hominum,  ut distendantur in ea. 

** Ecclesiastes 3:11

Cuncta fecit bona in tempore suo,  et mundum tradidit disputationi eorum,  ut non inveniat homo opus  quod operatus est Deus ab initio usque ad finem. 

** Ecclesiastes 3:12

Et cognovi quod non esset melius nisi lætari,  et facere bene in vita sua ; 

** Ecclesiastes 3:13

omnis enim homo qui comedit et bibit,  et videt bonum de labore suo,  hoc donum Dei est. 

** Ecclesiastes 3:14

Didici quod omnia opera quæ fecit Deus perseverent in perpetuum ;  non possumus eis quidquam addere, nec auferre,  quæ fecit Deus ut timeatur. 

** Ecclesiastes 3:15

Quod factum est, ipsum permanet ;  quæ futura sunt jam fuerunt,  et Deus instaurat quod abiit. 

** Ecclesiastes 3:16

Vidi sub sole in loco judicii impietatem,  et in loco justitiæ iniquitatem : 

** Ecclesiastes 3:17

et dixi in corde meo :  Justum et impium judicabit Deus,  et tempus omnis rei tunc erit. 

** Ecclesiastes 3:18

Dixi in corde meo de filiis hominum,  ut probaret eos Deus,  et ostenderet similes esse bestiis. 

** Ecclesiastes 3:19

Idcirco unus interitus est hominis et jumentorum,  et æqua utriusque conditio.  Sicut moritur homo,  sic et illa moriuntur.  Similiter spirant omnia,  et nihil habet homo jumento amplius :  cuncta subjacent vanitati, 

** Ecclesiastes 3:20

et omnia pergunt ad unum locum.  De terra facta sunt,  et in terram pariter revertuntur. 

** Ecclesiastes 3:21

Quis novit si spiritus filiorum Adam ascendat sursum,  et si spiritus jumentorum descendat deorsum ? 

** Ecclesiastes 3:22

Et deprehendi nihil esse melius  quam lætari hominem in opere suo,  et hanc esse partem illius.  Quis enim eum adducet ut post se futura cognoscat ?  

* Ecclesiastes 4

** Ecclesiastes 4:1

Verti me ad alia, et vidi calumnias  quæ sub sole geruntur,  et lacrimas innocentium,  et neminem consolatorem,  nec posse resistere eorum violentiæ,  cunctorum auxilio destitutos, 

** Ecclesiastes 4:2

et laudavi magis mortuos quam viventes ; 

** Ecclesiastes 4:3

et feliciorem utroque judicavi  qui necdum natus est,  nec vidit mala quæ sub sole fiunt. 

** Ecclesiastes 4:4

Rursum contemplatus sum omnes labores hominum,  et industrias animadverti patere invidiæ proximi ;  et in hoc ergo vanitas et cura superflua est. 

** Ecclesiastes 4:5

Stultus complicat manus suas,  et comedit carnes suas, dicens : 

** Ecclesiastes 4:6

Melior est pugillus cum requie,  quam plena utraque manus cum labore et afflictione animi. 

** Ecclesiastes 4:7

Considerans, reperi et aliam vanitatem sub sole. 

** Ecclesiastes 4:8

Unus est, et secundum non habet,  non filium, non fratrem,  et tamen laborare non cessat,  nec satiantur oculi ejus divitiis ;  nec recogitat, dicens :  Cui laboro, et fraudo animam meam bonis ?  In hoc quoque vanitas est et afflictio pessima. 

** Ecclesiastes 4:9

Melius est ergo duos esse simul quam unum ;  habent enim emolumentum societatis suæ. 

** Ecclesiastes 4:10

Si unus ceciderit, ab altero fulcietur.  Væ soli, quia cum ceciderit, non habet sublevantem se. 

** Ecclesiastes 4:11

Et si dormierint duo, fovebuntur mutuo ;  unus quomodo calefiet ? 

** Ecclesiastes 4:12

Et si quispiam prævaluerit contra unum,  duo resistunt ei ;  funiculus triplex difficile rumpitur. 

** Ecclesiastes 4:13

Melior est puer pauper et sapiens,  rege sene et stulto,  qui nescit prævidere in posterum. 

** Ecclesiastes 4:14

Quod de carcere catenisque interdum quis egrediatur ad regnum ;  et alius, natus in regno, inopia consumatur. 

** Ecclesiastes 4:15

Vidi cunctos viventes qui ambulant sub sole  cum adolescente secundo, qui consurget pro eo. 

** Ecclesiastes 4:16

Infinitus numerus est populi  omnium qui fuerunt ante eum,  et qui postea futuri sunt non lætabuntur in eo ;  sed et hoc vanitas et afflictio spiritus. 

** Ecclesiastes 4:17

Custodi pedem tuum ingrediens domum Dei,  et appropinqua ut audias.  Multo enim melior est obedientia quam stultorum victimæ,  qui nesciunt quid faciunt mali.  

* Ecclesiastes 5

** Ecclesiastes 5:1

Ne temere quid loquaris,  neque cor tuum sit velox ad proferendum sermonem coram Deo.  Deus enim in cælo, et tu super terram ;  idcirco sint pauci sermones tui. 

** Ecclesiastes 5:2

Multas curas sequuntur somnia,  et in multis sermonibus invenietur stultitia. 

** Ecclesiastes 5:3

Si quid vovisti Deo,  ne moreris reddere :  displicet enim ei infidelis et stulta promissio,  sed quodcumque voveris redde : 

** Ecclesiastes 5:4

multoque melius est non vovere,  quam post votum promissa non reddere. 

** Ecclesiastes 5:5

Ne dederis os tuum ut peccare facias carnem tuam,  neque dicas coram angelo :  Non est providentia :  ne forte iratus Deus contra sermones tuos  dissipet cuncta opera manuum tuarum. 

** Ecclesiastes 5:6

Ubi multa sunt somnia,  plurimæ sunt vanitates, et sermones innumeri ;  tu vero Deum time. 

** Ecclesiastes 5:7

Si videris calumnias egenorum, et violenta judicia,  et subverti justitiam in provincia,  non mireris super hoc negotio :  quia excelso excelsior est alius,  et super hos quoque eminentiores sunt alii ; 

** Ecclesiastes 5:8

et insuper universæ terræ rex imperat servienti. 

** Ecclesiastes 5:9

Avarus non implebitur pecunia,  et qui amat divitias fructum non capiet ex eis ;  et hoc ergo vanitas. 

** Ecclesiastes 5:10

Ubi multæ sunt opes,  multi et qui comedunt eas.  Et quid prodest possessori,  nisi quod cernit divitias oculis suis ? 

** Ecclesiastes 5:11

Dulcis est somnus operanti,  sive parum sive multum comedat ;  saturitas autem divitis non sinit eum dormire. 

** Ecclesiastes 5:12

Est et alia infirmitas pessima quam vidi sub sole :  divitiæ conservatæ in malum domini sui. 

** Ecclesiastes 5:13

Pereunt enim in afflictione pessima :  generavit filium qui in summa egestate erit. 

** Ecclesiastes 5:14

Sicut egressus est nudus de utero matris suæ, sic revertetur,  et nihil auferet secum de labore suo. 

** Ecclesiastes 5:15

Miserabilis prorsus infirmitas :  quomodo venit, sic revertetur.  Quid ergo prodest ei quod laboravit in ventum ? 

** Ecclesiastes 5:16

cunctis diebus vitæ suæ comedit in tenebris,  et in curis multis, et in ærumna atque tristitia. 

** Ecclesiastes 5:17

Hoc itaque visum est mihi bonum,  ut comedat quis et bibat,  et fruatur lætitia ex labore suo  quo laboravit ipse sub sole,  numero dierum vitæ suæ  quos dedit ei Deus ;  et hæc est pars illius. 

** Ecclesiastes 5:18

Et omni homini cui dedit Deus divitias atque substantiam,  potestatemque ei tribuit ut comedat ex eis,  et fruatur parte sua, et lætetur de labore suo :  hoc est donum Dei. 

** Ecclesiastes 5:19

Non enim satis recordabitur dierum vitæ suæ,  eo quod Deus occupet deliciis cor ejus.  

* Ecclesiastes 6

** Ecclesiastes 6:1

Est et aliud malum quod vidi sub sole,  et quidem frequens apud homines : 

** Ecclesiastes 6:2

vir cui dedit Deus divitias,  et substantiam, et honorem,  et nihil deest animæ suæ ex omnibus quæ desiderat ;  nec tribuit ei potestatem Deus ut comedat ex eo,  sed homo extraneus vorabit illud :  hoc vanitas et miseria magna est. 

** Ecclesiastes 6:3

Si genuerit quispiam centum liberos,  et vixerit multos annos,  et plures dies ætatis habuerit,  et anima illius non utatur bonis substantiæ suæ,  sepulturaque careat :  de hoc ergo pronuntio quod melior illo sit abortivus. 

** Ecclesiastes 6:4

Frustra enim venit,  et pergit ad tenebras,  et oblivione delebitur nomen ejus. 

** Ecclesiastes 6:5

Non vidit solem,  neque cognovit distantiam boni et mali. 

** Ecclesiastes 6:6

Etiam si duobus millibus annis vixerit,  et non fuerit perfruitus bonis,  nonne ad unum locum properant omnia ? 

** Ecclesiastes 6:7

Omnis labor hominis in ore ejus ;  sed anima ejus non implebitur. 

** Ecclesiastes 6:8

Quid habet amplius sapiens a stulto ?  et quid pauper, nisi ut pergat illuc ubi est vita ? 

** Ecclesiastes 6:9

Melius est videre quod cupias,  quam desiderare quod nescias.  Sed et hoc vanitas est, et præsumptio spiritus. 

** Ecclesiastes 6:10

Qui futurus est, jam vocatum est nomen ejus ;  et scitur quod homo sit,  et non possit contra fortiorem se in judicio contendere. 

** Ecclesiastes 6:11

Verba sunt plurima,  multamque in disputando habentia vanitatem.  

* Ecclesiastes 7

** Ecclesiastes 7:1

Quid necesse est homini majora se quærere,  cum ignoret quid conducat sibi in vita sua,  numero dierum peregrinationis suæ,  et tempore quod velut umbra præterit ?  aut quis ei poterit indicare  quod post eum futurum sub sole sit ? 

** Ecclesiastes 7:2

Melius est nomen bonum quam unguenta pretiosa,  et dies mortis die nativitatis. 

** Ecclesiastes 7:3

Melius est ire ad domum luctus  quam ad domum convivii ;  in illa enim finis cunctorum admonetur hominum,  et vivens cogitat quid futurum sit. 

** Ecclesiastes 7:4

Melior est ira risu,  quia per tristitiam vultus corrigitur animus delinquentis. 

** Ecclesiastes 7:5

Cor sapientium ubi tristitia est,  et cor stultorum ubi lætitia. 

** Ecclesiastes 7:6

Melius est a sapiente corripi,  quam stultorum adulatione decipi ; 

** Ecclesiastes 7:7

quia sicut sonitus spinarum ardentium sub olla,  sic risus stulti.  Sed et hoc vanitas. 

** Ecclesiastes 7:8

Calumnia conturbat sapientem,  et perdet robur cordis illius. 

** Ecclesiastes 7:9

Melior est finis orationis quam principium.  Melior est patiens arrogante. 

** Ecclesiastes 7:10

Ne sis velox ad irascendum,  quia ira in sinu stulti requiescit. 

** Ecclesiastes 7:11

Ne dicas : Quid putas causæ est  quod priora tempora meliora fuere quam nunc sunt ?  stulta enim est hujuscemodi interrogatio. 

** Ecclesiastes 7:12

Utilior est sapientia cum divitiis,  et magis prodest videntibus solem. 

** Ecclesiastes 7:13

Sicut enim protegit sapientia, sic protegit pecunia ;  hoc autem plus habet eruditio et sapientia,  quod vitam tribuunt possessori suo. 

** Ecclesiastes 7:14

Considera opera Dei,  quod nemo possit corrigere quem ille despexerit. 

** Ecclesiastes 7:15

In die bona fruere bonis,  et malam diem præcave ;  sicut enim hanc, sic et illam fecit Deus,  ut non inveniat homo contra eum justas querimonias. 

** Ecclesiastes 7:16

Hæc quoque vidi in diebus vanitatis meæ :  justus perit in justitia sua,  et impius multo vivit tempore in malitia sua. 

** Ecclesiastes 7:17

Noli esse justus multum,  neque plus sapias quam necesse est,  ne obstupescas. 

** Ecclesiastes 7:18

Ne impie agas multum,  et noli esse stultus,  ne moriaris in tempore non tuo. 

** Ecclesiastes 7:19

Bonum est te sustentare justum :  sed et ab illo ne subtrahas manum tuam ;  quia qui timet Deum nihil negligit. 

** Ecclesiastes 7:20

Sapientia confortavit sapientem  super decem principes civitatis ; 

** Ecclesiastes 7:21

non est enim homo justus in terra  qui faciat bonum et non peccet. 

** Ecclesiastes 7:22

Sed et cunctis sermonibus qui dicuntur  ne accomodes cor tuum,  ne forte audias servum tuum maledicentem tibi ; 

** Ecclesiastes 7:23

scit enim conscientia tua  quia et tu crebro maledixisti aliis. 

** Ecclesiastes 7:24

Cuncta tentavi in sapientia.  Dixi : Sapiens efficiar :  et ipsa longius recessit a me, 

** Ecclesiastes 7:25

multo magis quam erat.  Et alta profunditas, quis inveniet eam ? 

** Ecclesiastes 7:26

Lustravi universa animo meo,  ut scirem et considerarem,  et quærerem sapientiam, et rationem,  et ut cognoscerem impietatem stulti,  et errorem imprudentium : 

** Ecclesiastes 7:27

et inveni amariorem morte mulierem,  quæ laqueus venatorum est,  et sagena cor ejus ;  vincula sunt manus illius.  Qui placet Deo effugiet illam ;  qui autem peccator est capietur ab illa. 

** Ecclesiastes 7:28

Ecce hoc inveni, dixit Ecclesiastes,  unum et alterum ut invenirem rationem, 

** Ecclesiastes 7:29

quam adhuc quærit anima mea,  et non inveni.  Virum de mille unum reperi ;  mulierem ex omnibus non inveni. 

** Ecclesiastes 7:30

Solummodo hoc inveni,  quod fecerit Deus hominem rectum,  et ipse se infinitis miscuerit quæstionibus.  Quis talis ut sapiens est ?  et quis cognovit solutionem verbi ?  

* Ecclesiastes 8

** Ecclesiastes 8:1

Sapientia hominis lucet in vultu ejus,  et potentissimus faciem illius commutabit. 

** Ecclesiastes 8:2

Ego os regis observo,  et præcepta juramenti Dei. 

** Ecclesiastes 8:3

Ne festines recedere a facie ejus,  neque permaneas in opere malo :  quia omne quod voluerit faciet. 

** Ecclesiastes 8:4

Et sermo illius potestate plenus est,  nec dicere ei quisquam potest : Quare ita facis ? 

** Ecclesiastes 8:5

Qui custodit præceptum non experietur quidquam mali.  Tempus et responsionem cor sapientis intelligit. 

** Ecclesiastes 8:6

Omni negotio tempus est, et opportunitas :  et multa hominis afflictio, 

** Ecclesiastes 8:7

quia ignorat præterita,  et futura nullo scire potest nuntio. 

** Ecclesiastes 8:8

Non est in hominis potestate prohibere spiritum,  nec habet potestatem in die mortis :  nec sinitur quiescere ingruente bello,  neque salvabit impietas impium. 

** Ecclesiastes 8:9

Omnia hæc consideravi,  et dedi cor meum in cunctis operibus quæ fiunt sub sole.  Interdum dominatur homo homini in malum suum. 

** Ecclesiastes 8:10

Vidi impios sepultos,  qui etiam cum adhuc viverent  in loco sancto erant,  et laudabantur in civitate  quasi justorum operum.  Sed et hoc vanitas est. 

** Ecclesiastes 8:11

Etenim quia non profertur cito contra malos sententia,  absque timore ullo  filii hominum perpetrant mala. 

** Ecclesiastes 8:12

Attamen peccator ex eo quod centies facit malum,  et per patientiam sustentatur ;  ego cognovi quod erit bonum timentibus Deum,  qui verentur faciem ejus. 

** Ecclesiastes 8:13

Non sit bonum impio,  nec prolongentur dies ejus,  sed quasi umbra transeant qui non timent faciem Domini. 

** Ecclesiastes 8:14

Est et alia vanitas quæ fit super terram :  sunt justi quibus mala proveniunt  quasi opera egerint impiorum :  et sunt impii qui ita securi sunt  quasi justorum facta habeant.  Sed et hoc vanissimum judico. 

** Ecclesiastes 8:15

Laudavi igitur lætitiam ;  quod non esset homini bonum sub sole,  nisi quod comederet, et biberet, atque gauderet,  et hoc solum secum auferret de labore suo,  in diebus vitæ suæ quos dedit ei Deus sub sole. 

** Ecclesiastes 8:16

Et apposui cor meum ut scirem sapientiam,  et intelligerem distentionem quæ versatur in terra.  Est homo qui diebus et noctibus somnum non capit oculis. 

** Ecclesiastes 8:17

Et intellexi quod omnium operum Dei  nullam possit homo invenire rationem  eorum quæ fiunt sub sole ;  et quanto plus laboraverit ad quærendum,  tanto minus inveniat :  etiam si dixerit sapiens se nosse, non poterit reperire.  

* Ecclesiastes 9

** Ecclesiastes 9:1

Omnia hæc tractavi in corde meo,  ut curiose intelligerem.  Sunt justi atque sapientes,  et opera eorum in manu Dei ;  et tamen nescit homo utrum amore an odio dignus sit. 

** Ecclesiastes 9:2

Sed omnia in futurum servantur incerta,  eo quod universa æque eveniant justo et impio,  bono et malo, mundo et immundo,  immolanti victimas et sacrificia contemnenti.  Sicut bonus, sic et peccator ;  ut perjurus, ita et ille qui verum dejerat. 

** Ecclesiastes 9:3

Hoc est pessimum inter omnia quæ sub sole fiunt :  quia eadem cunctis eveniunt.  Unde et corda filiorum hominum implentur malitia  et contemptu in vita sua,  et post hæc ad inferos deducentur. 

** Ecclesiastes 9:4

Nemo est qui semper vivat, et qui hujus rei habeat fiduciam ;  melior est canis vivus leone mortuo. 

** Ecclesiastes 9:5

Viventes enim sciunt se esse morituros ;  mortui vero nihil noverunt amplius,  nec habent ultra mercedem,  quia oblivioni tradita est memoria eorum. 

** Ecclesiastes 9:6

Amor quoque, et odium, et invidiæ simul perierunt ;  nec habent partem in hoc sæculo,  et in opere quod sub sole geritur. 

** Ecclesiastes 9:7

Vade ergo, et comede in lætitia panem tuum,  et bibe cum gaudio vinum tuum,  quia Deo placent opera tua. 

** Ecclesiastes 9:8

Omni tempore sint vestimenta tua candida,  et oleum de capite tuo non deficiat. 

** Ecclesiastes 9:9

Perfruere vita cum uxore quam diligis,  cunctis diebus vitæ instabilitatis tuæ,  qui dati sunt tibi sub sole omni tempore vanitatis tuæ :  hæc est enim pars in vita  et in labore tuo quo laboras sub sole. 

** Ecclesiastes 9:10

Quodcumque facere potest manus tua,  instanter operare,  quia nec opus, nec ratio, nec sapientia, nec scientia  erunt apud inferos, quo tu properas. 

** Ecclesiastes 9:11

Verti me ad aliud, et vidi sub sole  nec velocium esse cursum,  nec fortium bellum,  nec sapientium panem,  nec doctorum divitias,  nec artificum gratiam ;  sed tempus casumque in omnibus. 

** Ecclesiastes 9:12

Nescit homo finem suum ;  sed sicut pisces capiuntur hamo,  et sicut aves laqueo comprehenduntur,  sic capiuntur homines in tempore malo,  cum eis extemplo supervenerit. 

** Ecclesiastes 9:13

Hanc quoque sub sole vidi sapientiam,  et probavi maximam : 

** Ecclesiastes 9:14

civitas parva, et pauci in ea viri ;  venit contra eam rex magnus, et vallavit eam,  exstruxitque munitiones per gyrum, et perfecta est obsidio. 

** Ecclesiastes 9:15

Inventusque est in ea vir pauper et sapiens,  et liberavit urbem per sapientiam suam ;  et nullus deinceps recordatus est hominis illius pauperis. 

** Ecclesiastes 9:16

Et dicebam ego meliorem esse sapientiam fortitudine.  Quomodo ergo sapientia pauperis contempta est,  et verba ejus non sunt audita ? 

** Ecclesiastes 9:17

Verba sapientium audiuntur in silentio,  plus quam clamor principis inter stultos. 

** Ecclesiastes 9:18

Melior est sapientia quam arma bellica ;  et qui in uno peccaverit, multa bona perdet.  

* Ecclesiastes 10

** Ecclesiastes 10:1

Muscæ morientes perdunt suavitatem unguenti.  Pretiosior est sapientia et gloria,  parva et ad tempus stultitia. 

** Ecclesiastes 10:2

Cor sapientis in dextera ejus,  et cor stulti in sinistra illius. 

** Ecclesiastes 10:3

Sed et in via stultus ambulans,  cum ipse insipiens sit,  omnes stultos æstimat. 

** Ecclesiastes 10:4

Si spiritus potestatem habentis ascenderit super te,  locum tuum ne demiseris,  quia curatio faciet cessare peccata maxima. 

** Ecclesiastes 10:5

Est malum quod vidi sub sole,  quasi per errorem egrediens a facie principis : 

** Ecclesiastes 10:6

positum stultum in dignitate sublimi,  et divites sedere deorsum. 

** Ecclesiastes 10:7

Vidi servos in equis,  et principes ambulantes super terram quasi servos. 

** Ecclesiastes 10:8

Qui fodit foveam incidet in eam,  et qui dissipat sepem mordebit eum coluber. 

** Ecclesiastes 10:9

Qui transfert lapides affligetur in eis,  et qui scindit ligna vulnerabitur ab eis. 

** Ecclesiastes 10:10

Si retusum fuerit ferrum,  et hoc non ut prius, sed hebetatum fuerit,  multo labore exacuetur,  et post industriam sequetur sapientia. 

** Ecclesiastes 10:11

Si mordeat serpens in silentio,  nihil eo minus habet qui occulte detrahit. 

** Ecclesiastes 10:12

Verba oris sapientis gratia,  et labia insipientis præcipitabunt eum ; 

** Ecclesiastes 10:13

initium verborum ejus stultitia,  et novissimum oris illius error pessimus. 

** Ecclesiastes 10:14

Stultus verba multiplicat.  Ignorat homo quid ante se fuerit ;  et quid post se futurum sit, quis ei poterit indicare ? 

** Ecclesiastes 10:15

Labor stultorum affliget eos,  qui nesciunt in urbem pergere. 

** Ecclesiastes 10:16

Væ tibi, terra, cujus rex puer est,  et cujus principes mane comedunt. 

** Ecclesiastes 10:17

Beata terra cujus rex nobilis est,  et cujus principes vescuntur in tempore suo,  ad reficiendum, et non ad luxuriam. 

** Ecclesiastes 10:18

In pigritiis humiliabitur contignatio,  et in infirmitate manuum perstillabit domus. 

** Ecclesiastes 10:19

In risum faciunt panem et vinum  ut epulentur viventes ;  et pecuniæ obediunt omnia. 

** Ecclesiastes 10:20

In cogitatione tua regi ne detrahas,  et in secreto cubiculi tui ne maledixeris diviti :  quia et aves cæli portabunt vocem tuam,  et qui habet pennas annuntiabit sententiam.  

* Ecclesiastes 11

** Ecclesiastes 11:1

Mitte panem tuum super transeuntes aquas,  quia post tempora multa invenies illum. 

** Ecclesiastes 11:2

Da partem septem necnon et octo,  quia ignoras quid futurum sit mali super terram. 

** Ecclesiastes 11:3

Si repletæ fuerint nubes,  imbrem super terram effundent.  Si ceciderit lignum ad austrum aut ad aquilonem,  in quocumque loco ceciderit, ibi erit. 

** Ecclesiastes 11:4

Qui observat ventum non seminat ;  et qui considerat nubes numquam metet. 

** Ecclesiastes 11:5

Quomodo ignoras quæ sit via spiritus,  et qua ratione compingantur ossa in ventre prægnantis,  sic nescis opera Dei,  qui fabricator est omnium. 

** Ecclesiastes 11:6

Mane semina semen tuum,  et vespere ne cesset manus tua :  quia nescis quid magis oriatur, hoc aut illud ;  et si utrumque simul, melius erit. 

** Ecclesiastes 11:7

Dulce lumen,  et delectabile est oculis videre solem. 

** Ecclesiastes 11:8

Si annis multis vixerit homo,  et in his omnibus lætatus fuerit,  meminisse debet tenebrosi temporis, et dierum multorum,  qui cum venerint, vanitatis arguentur præterita. 

** Ecclesiastes 11:9

Lætare ergo, juvenis, in adolescentia tua,  et in bono sit cor tuum in diebus juventutis tuæ :  et ambula in viis cordis tui,  et in intuitu oculorum tuorum,  et scito quod pro omnibus his adducet te Deus in judicium. 

** Ecclesiastes 11:10

Aufer iram a corde tuo,  et amove malitiam a carne tua :  adolescentia enim et voluptas vana sunt.  

* Ecclesiastes 12

** Ecclesiastes 12:1

Memento Creatoris tui in diebus juventutis tuæ,  antequam veniat tempus afflictionis,  et appropinquent anni de quibus dicas :  Non mihi placent ; 

** Ecclesiastes 12:2

antequam tenebrescat sol, et lumen, et luna, et stellæ,  et revertantur nubes post pluviam ; 

** Ecclesiastes 12:3

quando commovebuntur custodes domus,  et nutabunt viri fortissimi,  et otiosæ erunt molentes in minuto numero,  et tenebrescent videntes per foramina ; 

** Ecclesiastes 12:4

et claudent ostia in platea,  in humilitate vocis molentis,  et consurgent ad vocem volucris,  et obsurdescent omnes filiæ carminis : 

** Ecclesiastes 12:5

excelsa quoque timebunt, et formidabunt in via.  Florebit amygdalus, impinguabitur locusta,  et dissipabitur capparis,  quoniam ibit homo in domum æternitatis suæ,  et circuibunt in platea plangentes. 

** Ecclesiastes 12:6

Antequam rumpatur funiculus argenteus,  et recurrat vitta aurea,  et conteratur hydria super fontem,  et confringatur rota super cisternam, 

** Ecclesiastes 12:7

et revertatur pulvis in terram suam unde erat,  et spiritus redeat ad Deum, qui dedit illum. 

** Ecclesiastes 12:8

Vanitas vanitatum, dixit Ecclesiastes,  et omnia vanitas. 

** Ecclesiastes 12:9

Cumque esset sapientissimus Ecclesiastes,  docuit populum, et enarravit quæ fecerat ;  et investigans composuit parabolas multas. 

** Ecclesiastes 12:10

Quæsivit verba utilia,  et conscripsit sermones rectissimos ac veritate plenos. 

** Ecclesiastes 12:11

Verba sapientium sicut stimuli,  et quasi clavi in altum defixi,  quæ per magistrorum consilium data sunt a pastore uno. 

** Ecclesiastes 12:12

His amplius, fili mi, ne requiras.  Faciendi plures libros nullus est finis ;  frequensque meditatio, carnis afflictio est. 

** Ecclesiastes 12:13

Finem loquendi pariter omnes audiamus.  Deum time, et mandata ejus observa :  hoc est enim omnis homo, 

** Ecclesiastes 12:14

et cuncta quæ fiunt adducet Deus in judicium  pro omni errato, sive bonum, sive malum illud sit.    

