* Ephesians 1

** Ephesians 1:1

Paulus Apostolus Jesu Christi per voluntatem Dei, omnibus sanctis qui sunt Ephesi, et fidelibus in Christo Jesu.

** Ephesians 1:2

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** Ephesians 1:3

Benedictus Deus et Pater Domini nostri Jesu Christi, qui benedixit nos in omni benedictione spirituali in cælestibus in Christo,

** Ephesians 1:4

sicut elegit nos in ipso ante mundi constitutionem, ut essemus sancti et immaculati in conspectu ejus in caritate.

** Ephesians 1:5

Qui prædestinavit nos in adoptionem filiorum per Jesum Christum in ipsum : secundum propositum voluntatis suæ,

** Ephesians 1:6

in laudem gloriæ gratiæ suæ, in qua gratificavit nos in dilecto Filio suo.

** Ephesians 1:7

In quo habemus redemptionem per sanguinem ejus, remissionem peccatorum secundum divitias gratiæ ejus,

** Ephesians 1:8

quæ superabundavit in nobis in omni sapientia et prudentia :

** Ephesians 1:9

ut notum faceret nobis sacramentum voluntatis suæ, secundum beneplacitum ejus, quod proposuit in eo,

** Ephesians 1:10

in dispensatione plenitudinis temporum, instaurare omnia in Christo, quæ in cælis et quæ in terra sunt, in ipso ;

** Ephesians 1:11

in quo etiam et nos sorte vocati sumus prædestinati secundum propositum ejus qui operatur omnia secundum consilium voluntatis suæ :

** Ephesians 1:12

ut simus in laudem gloriæ ejus nos, qui ante speravimus in Christo ;

** Ephesians 1:13

in quo et vos, cum audissetis verbum veritatis, Evangelium salutis vestræ, in quo et credentes signati estis Spiritu promissionis Sancto,

** Ephesians 1:14

qui est pignus hæreditatis nostræ, in redemptionem acquisitionis, in laudem gloriæ ipsius.  

** Ephesians 1:15

Propterea et ego audiens fidem vestram, quæ est in Domino Jesu, et dilectionem in omnes sanctos,

** Ephesians 1:16

non cesso gratias agens pro vobis, memoriam vestri faciens in orationibus meis :

** Ephesians 1:17

ut Deus, Domini nostri Jesu Christi Pater gloriæ, det vobis spiritum sapientiæ et revelationis in agnitione ejus,

** Ephesians 1:18

illuminatos oculos cordis vestri, ut sciatis quæ sit spes vocationis ejus, et quæ divitiæ gloriæ hæreditatis ejus in sanctis,

** Ephesians 1:19

et quæ sit supereminens magnitudo virtutis ejus in nos, qui credimus secundum operationem potentiæ virtutis ejus,

** Ephesians 1:20

quam operatus est in Christo, suscitans illum a mortuis, et constituens ad dexteram suam in cælestibus :

** Ephesians 1:21

supra omnem principatum, et potestatem, et virtutem, et dominationem, et omne nomen, quod nominatur non solum in hoc sæculo, sed etiam in futuro.

** Ephesians 1:22

Et omnia subjecit sub pedibus ejus : et ipsum dedit caput supra omnem ecclesiam,

** Ephesians 1:23

quæ est corpus ipsius, et plenitudo ejus, qui omnia in omnibus adimpletur.   

* Ephesians 2

** Ephesians 2:1

Et vos, cum essetis mortui delictis et peccatis vestris,

** Ephesians 2:2

in quibus aliquando ambulastis secundum sæculum mundi hujus, secundum principem potestatis aëris hujus, spiritus, qui nunc operatur in filios diffidentiæ,

** Ephesians 2:3

in quibus et nos omnes aliquando conversati sumus in desideriis carnis nostræ, facientes voluntatem carnis et cogitationum, et eramus natura filii iræ, sicut et ceteri :

** Ephesians 2:4

Deus autem, qui dives est in misericordia, propter nimiam caritatem suam, qua dilexit nos,

** Ephesians 2:5

et cum essemus mortui peccatis, convivificavit nos in Christo (cujus gratia estis salvati),

** Ephesians 2:6

et conresuscitavit, et consedere fecit in cælestibus in Christo Jesu :

** Ephesians 2:7

ut ostenderet in sæculis supervenientibus abundantes divitias gratiæ suæ, in bonitate super nos in Christo Jesu.

** Ephesians 2:8

Gratia enim estis salvati per fidem, et hoc non ex vobis : Dei enim donum est :

** Ephesians 2:9

non ex operibus, ut ne quis glorietur.

** Ephesians 2:10

Ipsius enim sumus factura, creati in Christo Jesu in operibus bonis, quæ præparavit Deus ut in illis ambulemus.  

** Ephesians 2:11

Propter quod memores estote quod aliquando vos gentes in carne, qui dicimini præputium ab ea quæ dicitur circumcisio in carne, manu facta :

** Ephesians 2:12

quia eratis illo in tempore sine Christo, alienati a conversatione Israël, et hospites testamentorum, promissionis spem non habentes, et sine Deo in hoc mundo.

** Ephesians 2:13

Nunc autem in Christo Jesu, vos, qui aliquando eratis longe, facti estis prope in sanguine Christi.

** Ephesians 2:14

Ipse enim est pax nostra, qui fecit utraque unum, et medium parietem maceriæ solvens, inimicitias in carne sua,

** Ephesians 2:15

legem mandatorum decretis evacuans, ut duos condat in semetipso in unum novum hominem, faciens pacem :

** Ephesians 2:16

et reconciliet ambos in uno corpore, Deo per crucem, interficiens inimicitias in semetipso.

** Ephesians 2:17

Et veniens evangelizavit pacem vobis, qui longe fuistis, et pacem iis, qui prope.

** Ephesians 2:18

Quoniam per ipsum habemus accessum ambo in uno Spiritu ad Patrem.

** Ephesians 2:19

Ergo jam non estis hospites, et advenæ : sed estis cives sanctorum, et domestici Dei,

** Ephesians 2:20

superædificati super fundamentum apostolorum, et prophetarum, ipso summo angulari lapide Christo Jesu :

** Ephesians 2:21

in quo omnis ædificatio constructa crescit in templum sanctum in Domino,

** Ephesians 2:22

in quo et vos coædificamini in habitaculum Dei in Spiritu.   

* Ephesians 3

** Ephesians 3:1

Hujus rei gratia, ego Paulus vinctus Christi Jesu, pro vobis gentibus,

** Ephesians 3:2

si tamen audistis dispensationem gratiæ Dei, quæ data est mihi in vobis :

** Ephesians 3:3

quoniam secundum revelationem notum mihi factum est sacramentum, sicut supra scripsi in brevi,

** Ephesians 3:4

prout potestis legentes intelligere prudentiam meam in mysterio Christi :

** Ephesians 3:5

quod aliis generationibus non est agnitum filiis hominum, sicuti nunc revelatum est sanctis apostolis ejus et prophetis in Spiritu,

** Ephesians 3:6

gentes esse cohæredes, et concorporales, et comparticipes promissionis ejus in Christo Jesu per Evangelium :

** Ephesians 3:7

cujus factus sum minister secundum donum gratiæ Dei, quæ data est mihi secundum operationem virtutis ejus.

** Ephesians 3:8

Mihi omnium sanctorum minimo data est gratia hæc, in gentibus evangelizare investigabiles divitias Christi,

** Ephesians 3:9

et illuminare omnes, quæ sit dispensatio sacramenti absconditi a sæculis in Deo, qui omnia creavit :

** Ephesians 3:10

ut innotescat principatibus et potestatibus in cælestibus per Ecclesiam, multiformis sapientia Dei,

** Ephesians 3:11

secundum præfinitionem sæculorum, quam fecit in Christo Jesu Domino nostro :

** Ephesians 3:12

in quo habemus fiduciam, et accessum in confidentia per fidem ejus.

** Ephesians 3:13

Propter quod peto ne deficiatis in tribulationibus meis pro vobis : quæ est gloria vestra.  

** Ephesians 3:14

Hujus rei gratia flecto genua mea ad Patrem Domini nostri Jesu Christi,

** Ephesians 3:15

ex quo omnis paternitas in cælis et in terra nominatur,

** Ephesians 3:16

ut det vobis secundum divitias gloriæ suæ, virtute corroborari per Spiritum ejus in interiorem hominem,

** Ephesians 3:17

Christum habitare per fidem in cordibus vestris : in caritate radicati, et fundati,

** Ephesians 3:18

ut possitis comprehendere cum omnibus sanctis, quæ sit latitudo, et longitudo, et sublimitas, et profundum :

** Ephesians 3:19

scire etiam supereminentem scientiæ caritatem Christi, ut impleamini in omnem plenitudinem Dei.

** Ephesians 3:20

Ei autem, qui potens est omnia facere superabundanter quam petimus aut intelligimus, secundum virtutem, quæ operatur in nobis :

** Ephesians 3:21

ipsi gloria in Ecclesia, et in Christo Jesu, in omnes generationes sæculi sæculorum. Amen.   

* Ephesians 4

** Ephesians 4:1

Obsecro itaque vos ego vinctus in Domino, ut digne ambuletis vocatione, qua vocati estis,

** Ephesians 4:2

cum omni humilitate, et mansuetudine, cum patientia, supportantes invicem in caritate,

** Ephesians 4:3

solliciti servare unitatem Spiritus in vinculo pacis.

** Ephesians 4:4

Unum corpus, et unus Spiritus, sicut vocati estis in una spe vocationis vestræ.

** Ephesians 4:5

Unus Dominus, una fides, unum baptisma.

** Ephesians 4:6

Unus Deus et Pater omnium, qui est super omnes, et per omnia, et in omnibus nobis.  

** Ephesians 4:7

Unicuique autem nostrum data est gratia secundum mensuram donationis Christi.

** Ephesians 4:8

Propter quod dicit : Ascendens in altum, captivam duxit captivitatem : dedit dona hominibus.

** Ephesians 4:9

Quod autem ascendit, quid est, nisi quia et descendit primum in inferiores partes terræ ?

** Ephesians 4:10

Qui descendit, ipse est et qui ascendit super omnes cælos, ut impleret omnia.

** Ephesians 4:11

Et ipse dedit quosdam quidem apostolos, quosdam autem prophetas, alios vero evangelistas, alios autem pastores et doctores,

** Ephesians 4:12

ad consummationem sanctorum in opus ministerii, in ædificationem corporis Christi :

** Ephesians 4:13

donec occurramus omnes in unitatem fidei, et agnitionis Filii Dei, in virum perfectum, in mensuram ætatis plenitudinis Christi :

** Ephesians 4:14

ut jam non simus parvuli fluctuantes, et circumferamur omni vento doctrinæ in nequitia hominum, in astutia ad circumventionem erroris.

** Ephesians 4:15

Veritatem autem facientes in caritate, crescamus in illo per omnia, qui est caput Christus :

** Ephesians 4:16

ex quo totum corpus compactum et connexum per omnem juncturam subministrationis, secundum operationem in mensuram uniuscujusque membri, augmentum corporis facit in ædificationem sui in caritate.  

** Ephesians 4:17

Hoc igitur dico, et testificor in Domino, ut jam non ambuletis, sicut et gentes ambulant in vanitate sensus sui,

** Ephesians 4:18

tenebris obscuratum habentes intellectum, alienati a vita Dei per ignorantiam, quæ est in illis, propter cæcitatem cordis ipsorum,

** Ephesians 4:19

qui desperantes, semetipsos tradiderunt impudicitiæ, in operationem immunditiæ omnis in avaritiam.

** Ephesians 4:20

Vos autem non ita didicistis Christum,

** Ephesians 4:21

si tamen illum audistis, et in ipso edocti estis, sicut est veritas in Jesu,

** Ephesians 4:22

deponere vos secundum pristinam conversationem veterem hominem, qui corrumpitur secundum desideria erroris.

** Ephesians 4:23

Renovamini autem spiritu mentis vestræ,

** Ephesians 4:24

et induite novum hominem, qui secundum Deum creatus est in justitia, et sanctitate veritatis.  

** Ephesians 4:25

Propter quod deponentes mendacium, loquimini veritatem unusquisque cum proximo suo : quoniam sumus invicem membra.

** Ephesians 4:26

Irascimini, et nolite peccare : sol non occidat super iracundiam vestram.

** Ephesians 4:27

Nolite locum dare diabolo :

** Ephesians 4:28

qui furabatur, jam non furetur : magis autem laboret, operando manibus suis, quod bonum est, ut habeat unde tribuat necessitatem patienti.

** Ephesians 4:29

Omnis sermo malus ex ore vestro non procedat : sed si quis bonus ad ædificationem fidei ut det gratiam audientibus.

** Ephesians 4:30

Et nolite contristare Spiritum Sanctum Dei : in quo signati estis in diem redemptionis.

** Ephesians 4:31

Omnis amaritudo, et ira, et indignatio, et clamor, et blasphemia tollatur a vobis cum omni malitia.

** Ephesians 4:32

Estote autem invicem benigni, misericordes, donantes invicem sicut et Deus in Christo donavit vobis.   

* Ephesians 5

** Ephesians 5:1

Estote ergo imitatores Dei, sicut filii carissimi,

** Ephesians 5:2

et ambulate in dilectione, sicut et Christus dilexit nos, et tradidit semetipsum pro nobis, oblationem et hostiam Deo in odorem suavitatis.

** Ephesians 5:3

Fornicatio autem, et omnis immunditia, aut avaritia, nec nominetur in vobis, sicut decet sanctos :

** Ephesians 5:4

aut turpitudo, aut stultiloquium, aut scurrilitas, quæ ad rem non pertinet : sed magis gratiarum actio.

** Ephesians 5:5

Hoc enim scitote intelligentes : quod omnis fornicator, aut immundus, aut avarus, quod est idolorum servitus, non habet hæreditatem in regno Christi et Dei.

** Ephesians 5:6

Nemo vos seducat inanibus verbis : propter hæc enim venit ira Dei in filios diffidentiæ.

** Ephesians 5:7

Nolite ergo effici participes eorum.  

** Ephesians 5:8

Eratis enim aliquando tenebræ : nunc autem lux in Domino. Ut filii lucis ambulate :

** Ephesians 5:9

fructus enim lucis est in omni bonitate, et justitia, et veritate :

** Ephesians 5:10

probantes quid sit beneplacitum Deo :

** Ephesians 5:11

et nolite communicare operibus infructuosis tenebrarum, magis autem redarguite.

** Ephesians 5:12

Quæ enim in occulto fiunt ab ipsis, turpe est et dicere.

** Ephesians 5:13

Omnia autem, quæ arguuntur, a lumine manifestantur : omne enim, quod manifestatur, lumen est.

** Ephesians 5:14

Propter quod dicit : Surge qui dormis, et exsurge a mortuis, et illuminabit te Christus.

** Ephesians 5:15

Videte itaque, fratres, quomodo caute ambuletis : non quasi insipientes,

** Ephesians 5:16

sed ut sapientes : redimentes tempus, quoniam dies mali sunt.

** Ephesians 5:17

Propterea nolite fieri imprudentes, sed intelligentes quæ sit voluntas Dei.

** Ephesians 5:18

Et nolite inebriari vino, in quo est luxuria, sed implemini Spiritu Sancto,

** Ephesians 5:19

loquentes vobismetipsis in psalmis, et hymnis, et canticis spiritualibus, cantantes et psallentes in cordibus vestris Domino,

** Ephesians 5:20

gratias agentes semper pro omnibus in nomine Domini nostri Jesu Christi Deo et Patri,

** Ephesians 5:21

subjecti invicem in timore Christi.  

** Ephesians 5:22

Mulieres viris suis subditæ sint, sicut Domino :

** Ephesians 5:23

quoniam vir caput est mulieris, sicut Christus caput est Ecclesiæ : ipse, salvator corporis ejus.

** Ephesians 5:24

Sed sicut Ecclesia subjecta est Christo, ita et mulieres viris suis in omnibus.

** Ephesians 5:25

Viri, diligite uxores vestras, sicut et Christus dilexit Ecclesiam, et seipsum tradidit pro ea,

** Ephesians 5:26

ut illam sanctificaret, mundans lavacro aquæ in verbo vitæ,

** Ephesians 5:27

ut exhiberet ipse sibi gloriosam Ecclesiam, non habentem maculam, aut rugam, aut aliquid hujusmodi, sed ut sit sancta et immaculata.

** Ephesians 5:28

Ita et viri debent diligere uxores suas ut corpora sua. Qui suam uxorem diligit, seipsum diligit.

** Ephesians 5:29

Nemo enim umquam carnem suam odio habuit : sed nutrit et fovet eam, sicut et Christus Ecclesiam :

** Ephesians 5:30

quia membra sumus corporis ejus, de carne ejus et de ossibus ejus.

** Ephesians 5:31

Propter hoc relinquet homo patrem et matrem suam, et adhærebit uxori suæ, et erunt duo in carne una.

** Ephesians 5:32

Sacramentum hoc magnum est, ego autem dico in Christo et in Ecclesia.

** Ephesians 5:33

Verumtamen et vos singuli, unusquisque uxorem suam sicut seipsum diligat : uxor autem timeat virum suum.   

* Ephesians 6

** Ephesians 6:1

Filii, obedite parentibus vestris in Domino : hoc enim justum est.

** Ephesians 6:2

Honora patrem tuum, et matrem tuam, quod est mandatum primum in promissione :

** Ephesians 6:3

ut bene sit tibi, et sis longævus super terram.

** Ephesians 6:4

Et vos patres, nolite ad iracundiam provocare filios vestros : sed educate illos in disciplina et correptione Domini.  

** Ephesians 6:5

Servi, obedite dominis carnalibus cum timore et tremore, in simplicitate cordis vestri, sicut Christo :

** Ephesians 6:6

non ad oculum servientes, quasi hominibus placentes, sed ut servi Christi, facientes voluntatem Dei ex animo,

** Ephesians 6:7

cum bona voluntate servientes, sicut Domino, et non hominibus :

** Ephesians 6:8

scientes quoniam unusquisque quodcumque fecerit bonum, hoc recipiet a Domino, sive servus, sive liber.

** Ephesians 6:9

Et vos domini, eadem facite illis, remittentes minas : scientes quia et illorum et vester Dominus est in cælis : et personarum acceptio non est apud eum.  

** Ephesians 6:10

De cetero, fratres, confortamini in Domino, et in potentia virtutis ejus.

** Ephesians 6:11

Induite vos armaturam Dei, ut possitis stare adversus insidias diaboli :

** Ephesians 6:12

quoniam non est nobis colluctatio adversus carnem et sanguinem, sed adversus principes, et potestates, adversus mundi rectores tenebrarum harum, contra spiritualia nequitiæ, in cælestibus.

** Ephesians 6:13

Propterea accipite armaturam Dei, ut possitis resistere in die malo, et in omnibus perfecti stare.

** Ephesians 6:14

State ergo succincti lumbos vestros in veritate, et induti loricam justitiæ,

** Ephesians 6:15

et calceati pedes in præparatione Evangelii pacis,

** Ephesians 6:16

in omnibus sumentes scutum fidei, in quo possitis omnia tela nequissimi ignea extinguere :

** Ephesians 6:17

et galeam salutis assumite, et gladium spiritus (quod est verbum Dei),

** Ephesians 6:18

per omnem orationem et obsecrationem orantes omni tempore in spiritu : et in ipso vigilantes in omni instantia et obsecratione pro omnibus sanctis :

** Ephesians 6:19

et pro me, ut detur mihi sermo in apertione oris mei cum fiducia, notum facere mysterium Evangelii :

** Ephesians 6:20

pro quo legatione fungor in catena, ita ut in ipso audeam, prout oportet me loqui.  

** Ephesians 6:21

Ut autem et vos sciatis quæ circa me sunt, quid agam, omnia vobis nota faciet Tychicus, carissimus frater, et fidelis minister in Domino :

** Ephesians 6:22

quem misi ad vos in hoc ipsum, ut cognoscatis quæ circa nos sunt, et consoletur corda vestra.

** Ephesians 6:23

Pax fratribus, et caritas cum fide a Deo Patre et Domino Jesu Christo.

** Ephesians 6:24

Gratia cum omnibus qui diligunt Dominum nostrum Jesum Christum in incorruptione. Amen.    

