* Ezra 1

** Ezra 1:1

In anno primo Cyri regis Persarum, ut compleretur verbum Domini ex ore Jeremiæ, suscitavit Dominus spiritum Cyri regis Persarum : et traduxit vocem in omni regno suo, etiam per scripturam, dicens :

** Ezra 1:2

Hæc dicit Cyrus rex Persarum : Omnia regna terræ dedit mihi Dominus Deus cæli, et ipse præcepit mihi ut ædificarem ei domum in Jerusalem, quæ est in Judæa.

** Ezra 1:3

Quis est in vobis de universo populo ejus ? Sit Deus illius cum ipso. Ascendat in Jerusalem, quæ est in Judæa, et ædificet domum Domini Dei Israël : ipse est Deus qui est in Jerusalem.

** Ezra 1:4

Et omnes reliqui in cunctis locis ubicumque habitant, adjuvent eum viri de loco suo argento et auro, et substantia, et pecoribus, excepto quod voluntarie offerunt templo Dei, quod est in Jerusalem.  

** Ezra 1:5

Et surrexerunt principes patrum de Juda et Benjamin, et sacerdotes, et Levitæ, et omnis cujus Deus suscitavit spiritum, ut ascenderent ad ædificandum templum Domini, quod erat in Jerusalem.

** Ezra 1:6

Universique qui erant in circuitu, adjuverunt manus eorum in vasis argenteis et aureis, in substantia et jumentis, in supellectili, exceptis his quæ sponte obtulerant.

** Ezra 1:7

Rex quoque Cyrus protulit vasa templi Domini, quæ tulerat Nabuchodonosor de Jerusalem, et posuerat ea in templo dei sui.

** Ezra 1:8

Protulit autem ea Cyrus rex Persarum per manum Mithridatis filii Gazabar, et annumeravit ea Sassabasar principi Juda.

** Ezra 1:9

Et hic est numerus eorum : phialæ aureæ triginta, phialæ argenteæ mille, cultri viginti novem, scyphi aurei triginta,

** Ezra 1:10

scyphi argentei secundi quadringenti decem, vasa alia mille.

** Ezra 1:11

Omnia vasa aurea et argentea quinque millia quadringenta : universa tulit Sassabasar cum his qui ascendebant de transmigratione Babylonis in Jerusalem.   

* Ezra 2

** Ezra 2:1

Hi sunt autem provinciæ filii, qui ascenderunt de captivitate, quam transtulerat Nabuchodonosor rex Babylonis in Babylonem, et reversi sunt in Jerusalem et Judam, unusquisque in civitatem suam.

** Ezra 2:2

Qui venerunt cum Zorobabel, Josue, Nehemia, Saraia, Rahelaia, Mardochai, Belsan, Mesphar, Beguai, Rehum, Baana. Numerus virorum populi Israël :

** Ezra 2:3

filii Pharos duo millia centum septuaginta duo.

** Ezra 2:4

Filii Sephatia, trecenti septuaginta duo.

** Ezra 2:5

Filii Area, septingenti septuaginta quinque.

** Ezra 2:6

Filii Phahath Moab, filiorum Josue : Joab, duo millia octingenti duodecim.

** Ezra 2:7

Filii Ælam, mille ducenti quinquaginta quatuor.

** Ezra 2:8

Filii Zethua, nongenti quadraginta quinque.

** Ezra 2:9

Filii Zachai, septingenti sexaginta.

** Ezra 2:10

Filii Bani, sexcenti quadraginta duo.

** Ezra 2:11

Filii Bebai, sexcenti viginti tres.

** Ezra 2:12

Filii Azgad, mille ducenti viginti duo.

** Ezra 2:13

Filii Adonicam, sexcenti sexaginta sex.

** Ezra 2:14

Filii Beguai, duo millia quinquaginta sex.

** Ezra 2:15

Filii Adin, quadringenti quinquaginta quatuor.

** Ezra 2:16

Filii Ather, qui erant ex Ezechia, nonaginta octo.

** Ezra 2:17

Filii Besai, trecenti viginti tres.

** Ezra 2:18

Filii Jora, centum duodecim.

** Ezra 2:19

Filii Hasum, ducenti viginti tres.

** Ezra 2:20

Filii Gebbar, nonaginta quinque.

** Ezra 2:21

Filii Bethlehem, centum viginti tres.

** Ezra 2:22

Viri Netupha, quinquaginta sex.

** Ezra 2:23

Viri Anathoth, centum viginti octo.

** Ezra 2:24

Filii Azmaveth, quadraginta duo.

** Ezra 2:25

Filii Cariathiarim, Cephira et Beroth, septingenti quadraginta tres.

** Ezra 2:26

Filii Rama et Gabaa, sexcenti viginti unus.

** Ezra 2:27

Viri Machmas, centum viginti duo.

** Ezra 2:28

Viri Bethel et Hai, ducenti viginti tres.

** Ezra 2:29

Filii Nebo, quinquaginta duo.

** Ezra 2:30

Filii Megbis, centum quinquaginta sex.

** Ezra 2:31

Filii Ælam alterius, mille ducenti quinquaginta quatuor.

** Ezra 2:32

Filii Harim, trecenti viginti.

** Ezra 2:33

Filii Lod Hadid, et Ono, septingenti viginti quinque.

** Ezra 2:34

Filii Jericho, trecenti quadraginta quinque.

** Ezra 2:35

Filii Senaa, tria millia sexcenti triginta.  

** Ezra 2:36

Sacerdotes : filii Jadaia in domo Josue, nongenti septuaginta tres.

** Ezra 2:37

Filii Emmer, mille quinquaginta duo.

** Ezra 2:38

Filii Pheshur, mille ducenti quadraginta septem.

** Ezra 2:39

Filii Harim, mille decem et septem.

** Ezra 2:40

Levitæ : filii Josue et Cedmihel filiorum Odoviæ, septuaginta quatuor.

** Ezra 2:41

Cantores : filii Asaph, centum viginti octo.

** Ezra 2:42

Filii janitorum : filii Sellum, filii Ater, filii Telmon, filii Accub, filii Hatitha, filii Sobai : universi centum triginta novem.  

** Ezra 2:43

Nathinæi : filii Siha, filii Hasupha, filii Tabbaoth,

** Ezra 2:44

filii Ceros, filii Siaa, filii Phadon,

** Ezra 2:45

filii Lebana, filii Hagaba, filii Accub,

** Ezra 2:46

filii Hagab, filii Semlai, filii Hanan,

** Ezra 2:47

filii Gaddel, filii Gaher, filii Raaia,

** Ezra 2:48

filii Rasin, filii Necoda, filii Gazam,

** Ezra 2:49

filii Aza, filii Phasea, filii Besee,

** Ezra 2:50

filii Asena, filii Munim, filii Nephusim,

** Ezra 2:51

filii Bacbuc, filii Hacupha, filii Harhur,

** Ezra 2:52

filii Besluth, filii Mahida, filii Harsa,

** Ezra 2:53

filii Bercos, filii Sisara, filii Thema,

** Ezra 2:54

filii Nasia, filii Hatipha,

** Ezra 2:55

filii servorum Salomonis, filii Sotai, filii Sophereth, filii Pharuda,

** Ezra 2:56

filii Jala, filii Dercon, filii Geddel,

** Ezra 2:57

filii Saphatia, filii Hatil, filii Phochereth, qui erant de Asebaim, filii Ami :

** Ezra 2:58

omnes Nathinæi, et filii servorum Salomonis, trecenti nonaginta duo.  

** Ezra 2:59

Et hi qui ascenderunt de Thelmala, Thelharsa, Cherub, et Adon, et Emer : et non potuerunt indicare domum patrum suorum et semen suum, utrum ex Israël essent.

** Ezra 2:60

Filii Dalaia, filii Tobia, filii Necoda, sexcenti quinquaginta duo.  

** Ezra 2:61

Et de filiis sacerdotum : filii Hobia, filii Accos, filii Berzellai, qui accepit de filiabus Berzellai Galaaditis, uxorem, et vocatus est nomine eorum :

** Ezra 2:62

hi quæsierunt scripturam genealogiæ suæ, et non invenerunt, et ejecti sunt de sacerdotio.

** Ezra 2:63

Et dixit Athersatha eis ut non comederent de Sancto sanctorum, donec surgeret sacerdos doctus atque perfectus.  

** Ezra 2:64

Omnis multitudo quasi unus, quadraginta duo millia trecenti sexaginta :

** Ezra 2:65

exceptis servis eorum, et ancillis, qui erant septem millia trecenti triginta septem : et in ipsis cantores atque cantatrices ducenti.

** Ezra 2:66

Equi eorum septingenti triginta sex, muli eorum, ducenti quadraginta quinque,

** Ezra 2:67

cameli eorum, quadringenti triginta quinque, asini eorum, sex millia septingenti viginti.

** Ezra 2:68

Et de principibus patrum, cum ingrederentur templum Domini, quod est in Jerusalem, sponte obtulerunt in domum Dei ad exstruendam eam in loco suo.

** Ezra 2:69

Secundum vires suas dederunt impensas operis, auri solidos sexaginta millia et mille, argenti mnas quinque millia, et vestes sacerdotales centum.

** Ezra 2:70

Habitaverunt ergo sacerdotes, et Levitæ, et de populo, et cantores, et janitores, et Nathinæi, in urbibus suis, universusque Israël in civitatibus suis.   

* Ezra 3

** Ezra 3:1

Jamque venerat mensis septimus, et erant filii Israël in civitatibus suis : congregatus est ergo populus quasi vir unus in Jerusalem.

** Ezra 3:2

Et surrexit Josue filius Josedec, et fratres ejus sacerdotes, et Zorobabel filius Salathiel, et fratres ejus, et ædificaverunt altare Dei Israël ut offerrent in eo holocautomata, sicut scriptum est in lege Moysi viri Dei.

** Ezra 3:3

Collocaverunt autem altare Dei super bases suas, deterrentibus eos per circuitum populis terrarum : et obtulerunt super illud holocaustum Domino mane et vespere.

** Ezra 3:4

Feceruntque solemnitatem tabernaculorum, sicut scriptum est, et holocaustum diebus singulis per ordinem secundum præceptum opus diei in die suo.

** Ezra 3:5

Et post hæc holocaustum juge, tam in calendis quam in universis solemnitatibus Domini quæ erant consecratæ, et in omnibus in quibus ultro offerebatur munus Domino.

** Ezra 3:6

A primo die mensis septimi cœperunt offerre holocaustum Domino : porro templum Dei nondum fundatum erat.

** Ezra 3:7

Dederunt autem pecunias latomis et cæmentariis : cibum quoque, et potum, et oleum Sidoniis Tyriisque, ut deferrent ligna cedrina de Libano ad mare Joppe, juxta quod præceperat Cyrus rex Persarum eis.  

** Ezra 3:8

Anno autem secundo adventus eorum ad templum Dei in Jerusalem, mense secundo, cœperunt Zorobabel filius Salathiel, et Josue filius Josedec, et reliqui de fratribus eorum sacerdotes, et Levitæ, et omnes qui venerant de captivitate in Jerusalem, et constituerunt Levitas a viginti annis et supra, ut urgerent opus Domini.

** Ezra 3:9

Stetitque Josue et filii ejus et fratres ejus, Cedmihel et filii ejus, et filii Juda, quasi vir unus, ut instarent super eos qui faciebant opus in templo Dei : filii Henadad, et filii eorum, et fratres eorum Levitæ.

** Ezra 3:10

Fundato igitur a cæmentariis templo Domini, steterunt sacerdotes in ornatu suo cum tubis, et Levitæ filii Asaph in cymbalis, ut laudarent Deum per manus David regis Israël.

** Ezra 3:11

Et concinebant in hymnis, et confessione Domino : Quoniam bonus, quoniam in æternum misericordia ejus super Israël. Omnis quoque populus vociferabatur clamore magno in laudando Dominum, eo quod fundatum esset templum Domini.

** Ezra 3:12

Plurimi etiam de sacerdotibus et Levitis, et principes patrum, et seniores, qui viderant templum prius cum fundatum esset, et hoc templum, in oculis eorum, flebant voce magna : et multi vociferantes in lætitia, elevabant vocem.

** Ezra 3:13

Nec poterat quisquam agnoscere vocem clamoris lætantium, et vocem fletus populi : commistim enim populus vociferabatur clamore magno, et vox audiebatur procul.   

* Ezra 4

** Ezra 4:1

Audierunt autem hostes Judæ et Benjamin, quia filii captivitatis ædificarent templum Domino Deo Israël :

** Ezra 4:2

et accedentes ad Zorobabel, et ad principes patrum, dixerunt eis : Ædificemus vobiscum, quia ita ut vos, quærimus Deum vestrum : ecce nos immolavimus victimas a diebus Asor Haddan regis Assur, qui adduxit nos huc.

** Ezra 4:3

Et dixit eis Zorobabel, et Josue, et reliqui principes patrum Israël : Non est vobis et nobis ut ædificemus domum Deo nostro, sed nos ipsi soli ædificabimus Domino Deo nostro, sicut præcepit nobis Cyrus rex Persarum.

** Ezra 4:4

Factum est igitur ut populus terræ impediret manus populi Judæ, et turbaret eos in ædificando.

** Ezra 4:5

Conduxerunt autem adversus eos consiliatores, ut destruerent consilium eorum omnibus diebus Cyri regis Persarum, et usque ad regnum Darii regis Persarum.  

** Ezra 4:6

In regno autem Assueri, in principio regni ejus, scripserunt accusationem adversus habitatores Judæ et Jerusalem.

** Ezra 4:7

Et in diebus Artaxerxis scripsit Beselam, Mithridates, et Thabeel, et reliqui qui erant in consilio eorum, ad Artaxerxem regem Persarum : epistola autem accusationis scripta erat syriace, et legebatur sermone syro.

** Ezra 4:8

Reum Beelteem, et Samsai scriba, scripserunt epistolam unam de Jerusalem Artaxerxi regi, hujuscemodi :

** Ezra 4:9

Reum Beelteem, et Samsai scriba, et reliqui consiliatores eorum, Dinæi, et Apharsathachæi, Terphalæi, Apharsæi, Erchuæi, Babylonii, Susanechæi, Dievi, et Ælamitæ,

** Ezra 4:10

et ceteri de gentibus, quas transtulit Asenaphar magnus et gloriosus, et habitare eas fecit in civitatibus Samariæ, et in reliquis regionibus trans flumen in pace

** Ezra 4:11

(hoc est exemplar epistolæ, quam miserunt ad eum), Artaxerxi regi, servi tui, viri qui sunt trans fluvium, salutem dicunt.

** Ezra 4:12

Notum sit regi quia Judæi, qui ascenderunt a te ad nos, venerunt in Jerusalem civitatem rebellem et pessimam, quam ædificant exstruentes muros ejus, et parietes componentes.

** Ezra 4:13

Nunc igitur notum sit regi, quia si civitas illa ædificata fuerit, et muri ejus instaurati, tributum, et vectigal, et annuos reditus non dabunt, et usque ad reges hæc noxa perveniet.

** Ezra 4:14

Nos autem memores salis, quod in palatio comedimus, et quia læsiones regis videre nefas ducimus, idcirco misimus et nuntiavimus regi,

** Ezra 4:15

ut recenseas in libris historiarum patrum tuorum, et invenies scriptum in commentariis : et scies quoniam urbs illa, urbs rebellis est, et nocens regibus et provinciis, et bella concitantur in ea ex diebus antiquis : quam ob rem et civitas ipsa destructa est.

** Ezra 4:16

Nuntiamus nos regi, quoniam si civitas illa ædificata fuerit, et muri ipsius instaurati, possessionem trans fluvium non habebis.  

** Ezra 4:17

Verbum misit rex ad Reum Beelteem, et Samsai scribam, et ad reliquos, qui erant in consilio eorum habitatores Samariæ, et ceteris trans fluvium, salutem dicens et pacem.

** Ezra 4:18

Accusatio, quam misistis ad nos, manifeste lecta est coram me,

** Ezra 4:19

et a me præceptum est : et recensuerunt, inveneruntque quoniam civitas illa a diebus antiquis adversum reges rebellat, et seditiones, et prælia concitantur in ea :

** Ezra 4:20

nam et reges fortissimi fuerunt in Jerusalem, qui et dominati sunt omni regioni quæ trans fluvium est : tributum quoque et vectigal, et reditus accipiebant.

** Ezra 4:21

Nunc ergo audite sententiam : prohibeatis viros illos, ut urbs illa non ædificetur donec si forte a me jussum fuerit.

** Ezra 4:22

Videte ne negligenter hoc impleatis, et paulatim crescat malum contra reges.  

** Ezra 4:23

Itaque exemplum edicti Artaxerxis regis lectum est coram Reum Beelteem, et Samsai scriba, et consiliariis eorum : et abierunt festini in Jerusalem ad Judæos, et prohibuerunt eos in brachio et robore.

** Ezra 4:24

Tunc intermissum est opus domus Domini in Jerusalem, et non fiebat usque ad annum secundum regni Darii regis Persarum.   

* Ezra 5

** Ezra 5:1

Prophetaverunt autem Aggæus propheta, et Zacharias filius Addo, prophetantes ad Judæos qui erant in Judæa et Jerusalem, in nomine Dei Israël.

** Ezra 5:2

Tunc surrexerunt Zorobabel filius Salathiel, et Josue filius Josedec, et cœperunt ædificare templum Dei in Jerusalem, et cum eis prophetæ Dei adjuvantes eos.

** Ezra 5:3

In ipso autem tempore venit ad eos Thathanai, qui erat dux trans flumen, et Stharbuzanai, et consiliarii eorum : sicque dixerunt eis : Quis dedit vobis consilium ut domum hanc ædificaretis, et muros ejus instauraretis ?

** Ezra 5:4

Ad quod respondimus eis, quæ essent nomina hominum auctorum ædificationis illius.

** Ezra 5:5

Oculus autem Dei eorum factus est super senes Judæorum, et non potuerunt inhibere eos. Placuitque ut res ad Darium referretur, et tunc satisfacerent adversus accusationem illam.  

** Ezra 5:6

Exemplar epistolæ, quam misit Thathanai dux regionis trans flumen, et Stharbuzanai, et consiliatores ejus Arphasachæi, qui erant trans flumen, ad Darium regem.

** Ezra 5:7

Sermo, quem miserant ei, sic scriptus erat : Dario regi pax omnis.

** Ezra 5:8

Notum sit regi, isse nos ad Judæam provinciam, ad domum Dei magni, quæ ædificatur lapide impolito, et ligna ponuntur in parietibus : opusque illud diligenter exstruitur, et crescit in manibus eorum.

** Ezra 5:9

Interrogavimus ergo senes illos, et ita diximus eis : Quis dedit vobis potestatem ut domum hanc ædificaretis, et muros hos instauraretis ?

** Ezra 5:10

Sed et nomina eorum quæsivimus ab eis, ut nuntiaremus tibi : scripsimusque nomina eorum virorum, qui sunt principes in eis.

** Ezra 5:11

Hujuscemodi autem sermonem responderunt nobis dicentes : Nos sumus servi Dei cæli et terræ, et ædificamus templum, quod erat exstructum ante hos annos multos, quodque rex Israël magnus ædificaverat, et exstruxerat.

** Ezra 5:12

Postquam autem ad iracundiam provocaverunt patres nostri Deum cæli, tradidit eos in manus Nabuchodonosor regis Babylonis Chaldæi, domum quoque hanc destruxit, et populum ejus transtulit in Babylonem.

** Ezra 5:13

Anno autem primo Cyri regis Babylonis, Cyrus rex proposuit edictum ut domus Dei hæc ædificaretur.

** Ezra 5:14

Nam et vasa templi Dei aurea et argentea, quæ Nabuchodonosor tulerat de templo, quod erat in Jerusalem, et asportaverat ea in templum Babylonis, protulit Cyrus rex de templo Babylonis, et data sunt Sassabasar vocabulo, quem et principem constituit,

** Ezra 5:15

dixitque ei : Hæc vasa tolle, et vade, et pone ea in templo, quod est in Jerusalem, et domus Dei ædificetur in loco suo.

** Ezra 5:16

Tunc itaque Sassabasar ille venit et posuit fundamenta templi Dei in Jerusalem, et ex eo tempore usque nunc ædificatur, et necdum completum est.

** Ezra 5:17

Nunc ergo si videtur regi bonum, recenseat in bibliotheca regis, quæ est in Babylone, utrumnam a Cyro rege jussum fuerit ut ædificaretur domus Dei in Jerusalem, et voluntatem regis super hac re mittat ad nos.   

* Ezra 6

** Ezra 6:1

Tunc Darius rex præcepit : et recensuerunt in bibliotheca librorum, qui erant repositi in Babylone.

** Ezra 6:2

Et inventum est in Ecbatanis, quod est castrum in Medena provincia, volumen unum : talisque scriptus erat in eo commentarius :

** Ezra 6:3

Anno primo Cyri regis, Cyrus rex decrevit ut domus Dei ædificaretur, quæ est in Jerusalem, in loco ubi immolent hostias, et ut ponant fundamenta supportantia altitudinem cubitorum sexaginta, et latitudinem cubitorum sexaginta,

** Ezra 6:4

ordines de lapidibus impolitis tres, et sic ordines de lignis novis : sumptus autem de domo regis dabuntur.

** Ezra 6:5

Sed et vasa templi Dei aurea et argentea, quæ Nabuchodonosor tulerat de templo Jerusalem, et attulerat ea in Babylonem, reddantur, et referantur in templum in Jerusalem in locum suum, quæ et posita sunt in templo Dei.

** Ezra 6:6

Nunc ergo Thathanai dux regionis, quæ est trans flumen, Stharbuzanai, et consiliarii vestri Apharsachæi, qui estis trans flumen, procul recedite ab illis,

** Ezra 6:7

et dimittite fieri templum Dei illud a duce Judæorum, et a senioribus eorum, ut domum Dei illam ædificent in loco suo.

** Ezra 6:8

Sed et a me præceptum est quid oporteat fieri a presbyteris Judæorum illis ut ædificetur domus Dei, scilicet ut de arca regis, id est, de tributis quæ dantur de regione trans flumen, studiose sumptus dentur viris illis, ne impediatur opus.

** Ezra 6:9

Quod si necesse fuerit, et vitulos, et agnos, et hædos in holocaustum Deo cæli, frumentum, sal, vinum, et oleum, secundum ritum sacerdotum, qui sunt in Jerusalem, detur eis per singulos dies, ne sit in aliquo querimonia.

** Ezra 6:10

Et offerant oblationes Deo cæli, orentque pro vita regis, et filiorum ejus.

** Ezra 6:11

A me ergo positum est decretum : ut omnis homo qui hanc mutaverit jussionem, tollatur lignum de domum ipsius, et erigatur, et configatur in eo, domus autem ejus publicetur.

** Ezra 6:12

Deus autem, qui habitare fecit nomen suum ibi, dissipet omnia regna, et populum qui extenderit manum suam ut repugnet, et dissipet domum Dei illam, quæ est in Jerusalem. Ego Darius statui decretum, quod studiose impleri volo.  

** Ezra 6:13

Igitur Thathanai dux regionis trans flumen, et Stharbuzanai, et consiliarii ejus, secundum quod præceperat Darius rex, sic diligenter executi sunt.

** Ezra 6:14

Seniores autem Judæorum ædificabant, et prosperabantur juxta prophetiam Aggæi prophetæ, et Zachariæ filii Addo : et ædificaverunt et construxerunt, jubente Deo Israël, et jubente Cyro, et Dario, et Artaxerxe regibus Persarum :

** Ezra 6:15

et compleverunt domum Dei istam, usque ad diem tertium mensis Adar, qui est annus sextus regni Darii regis.

** Ezra 6:16

Fecerunt autem filii Israël sacerdotes et Levitæ, et reliqui filiorum transmigrationis, dedicationem domus Dei in gaudio.

** Ezra 6:17

Et obtulerunt in dedicationem domus Dei, vitulos centum, arietes ducentos, agnos quadringentos, hircos caprarum pro peccato totius Israël duodecim, juxta numerum tribuum Israël.

** Ezra 6:18

Et statuerunt sacerdotes in ordinibus suis, et Levitas in vicibus suis, super opera Dei in Jerusalem, sicut scriptum est in libro Moysi.  

** Ezra 6:19

Fecerunt autem filii Israël transmigrationis Pascha, quartadecima die mensis primi.

** Ezra 6:20

Purificati enim fuerant sacerdotes et Levitæ quasi unus : omnes mundi ad immolandum Pascha universis filiis transmigrationis, et fratribus suis sacerdotibus, et sibi.

** Ezra 6:21

Et comederunt filii Israël, qui reversi fuerant de transmigratione, et omnes qui se separaverant a coinquinatione gentium terræ ad eos, ut quærerent Dominum Deum Israël.

** Ezra 6:22

Et fecerunt solemnitatem azymorum septem diebus in lætitia, quoniam lætificaverat eos Dominus, et converterat cor regis Assur ad eos, ut adjuvaret manus eorum in opere domus Domini Dei Israël.   

* Ezra 7

** Ezra 7:1

Post hæc autem verba in regno Artaxerxis regis Persarum, Esdras filius Saraiæ, filii Azariæ, filii Helciæ,

** Ezra 7:2

filii Sellum, filii Sadoc, filii Achitob,

** Ezra 7:3

filii Amariæ, filii Azariæ, filii Maraioth,

** Ezra 7:4

filii Zarahiæ, filii Ozi, filii Bocci,

** Ezra 7:5

filii Abisue, filii Phinees, filii Eleazar, filii Aaron sacerdotis ab initio.

** Ezra 7:6

Ipse Esdras ascendit de Babylone, et ipse scriba velox in lege Moysi, quam Dominus Deus dedit Israël : et dedit ei rex secundum manum Domini Dei ejus super eum, omnem petitionem ejus.

** Ezra 7:7

Et ascenderunt de filiis Israël, et de filiis sacerdotum, et de filiis Levitarum, et de cantoribus, et de janitoribus, et de Nathinæis, in Jerusalem, anno septimo Artaxerxis regis.

** Ezra 7:8

Et venerunt in Jerusalem mense quinto, ipse est annus septimus regis.

** Ezra 7:9

Quia in primo die mensis primi cœpit ascendere de Babylone, et in primo die mensis quinti venit in Jerusalem, juxta manum Dei sui bonam super se.

** Ezra 7:10

Esdras enim paravit cor suum, ut investigaret legem Domini, et faceret et doceret in Israël præceptum et judicium.  

** Ezra 7:11

Hoc est autem exemplar epistolæ edicti, quod dedit rex Artaxerxes Esdræ sacerdoti, scribæ erudito in sermonibus et præceptis Domini, et cæremoniis ejus in Israël.

** Ezra 7:12

Artaxerxes rex regum Esdræ sacerdoti scribæ legis Dei cæli doctissimo, salutem.

** Ezra 7:13

A me decretum est, ut cuicumque placuerit in regno meo de populo Israël, et de sacerdotibus ejus, et de Levitis, ire in Jerusalem, tecum vadat.

** Ezra 7:14

A facie enim regis, et septem consiliatorum ejus, missus es, ut visites Judæam et Jerusalem in lege Dei tui, quæ est in manu tua :

** Ezra 7:15

et ut feras argentum et aurum quod rex, et consiliatores ejus, sponte obtulerunt Deo Israël, cujus in Jerusalem tabernaculum est.

** Ezra 7:16

Et omne argentum et aurum quodcumque inveneris in universa provincia Babylonis, et populus offerre voluerit, et de sacerdotibus quæ sponte obtulerint domui Dei sui, quæ est in Jerusalem,

** Ezra 7:17

libere accipe, et studiose eme de hac pecunia vitulos, arietes, agnos, et sacrificia, et libamina eorum, et offer ea super altare templi Dei vestri, quod est in Jerusalem.

** Ezra 7:18

Sed et si quid tibi et fratribus tuis placuerit de reliquo argento et auro ut faciatis, juxta voluntatem Dei vestri facite.

** Ezra 7:19

Vasa quoque, quæ dantur tibi in ministerium domus Dei tui, trade in conspectu Dei in Jerusalem.

** Ezra 7:20

Sed et cetera, quibus opus fuerit in domum Dei tui, quantumcumque necesse est ut expendas, dabitur de thesauro, et de fisco regis,

** Ezra 7:21

et a me. Ego Artaxerxes rex, statui atque decrevi omnibus custodibus arcæ publicæ, qui sunt trans flumen, ut quodcumque petierit a vobis Esdras sacerdos, scriba legis Dei cæli, absque mora detis,

** Ezra 7:22

usque ad argenti talenta centum, et usque ad frumenti coros centum, et usque ad vini batos centum, et usque ad batos olei centum, sal vero absque mensura.

** Ezra 7:23

Omne quod ad ritum Dei cæli pertinet, tribuatur diligenter in domo Dei cæli : ne forte irascatur contra regnum regis, et filiorum ejus.

** Ezra 7:24

Vobis quoque notum facimus de universis sacerdotibus, et Levitis, et cantoribus, et janitoribus, Nathinæis, et ministris domus Dei hujus, ut vectigal, et tributum, et annonas non habeatis potestatem imponendi super eos.

** Ezra 7:25

Tu autem Esdra, secundum sapientiam Dei tui, quæ est in manu tua, constitue judices et præsides, ut judicent omni populo qui est trans flumen, his videlicet qui noverunt legem Dei tui : sed et imperitos docete libere.

** Ezra 7:26

Et omnis qui non fecerit legem Dei tui, et legem regis, diligenter, judicium erit de eo sive in mortem, sive in exilium, sive in condemnationem substantiæ ejus, vel certe in carcerem.  

** Ezra 7:27

Benedictus Dominus Deus patrum nostrorum, qui dedit hoc in corde regis ut glorificaret domum Domini quæ est in Jerusalem,

** Ezra 7:28

et in me inclinavit misericordiam suam coram rege et consiliatoribus ejus, et universis principibus regis potentibus : et ego confortatus manu Domini Dei mei, quæ erat in me, congregavi de Israël principes qui ascenderent mecum.   

* Ezra 8

** Ezra 8:1

Hi sunt ergo principes familiarum, et genealogia eorum, qui ascenderunt mecum in regno Artaxerxis regis de Babylone.

** Ezra 8:2

De filiis Phinees, Gersom. De filiis Ithamar, Daniel. De filiis David, Hattus.

** Ezra 8:3

De filiis Secheniæ, filiis Pharos, Zacharias : et cum eo numerati sunt viri centum quinquaginta.

** Ezra 8:4

De filiis Phahath Moab, Elioënai filius Zarehe, et cum eo ducenti viri.

** Ezra 8:5

De filiis Secheniæ, filius Ezechiel, et cum eo trecenti viri.

** Ezra 8:6

De filiis Adan, Abed filius Jonathan, et cum eo quinquaginta viri.

** Ezra 8:7

De filiis Alam, Isaias filius Athaliæ, et cum eo septuaginta viri.

** Ezra 8:8

De filiis Saphatiæ, Zebedia filius Michaël, et cum eo octoginta viri.

** Ezra 8:9

De filiis Joab, Obedia filius Jahiel, et cum eo ducenti decem et octo viri.

** Ezra 8:10

De filiis Selomith, filius Josphiæ, et cum eo centum sexaginta viri.

** Ezra 8:11

De filiis Bebai, Zacharias filius Bebai, et cum eo viginti octo viri.

** Ezra 8:12

De filiis Azgad, Johanan filius Eccetan, et cum eo centum et decem viri.

** Ezra 8:13

De filiis Adonicam, qui erant novissimi : et hæc nomina eorum : Elipheleth, et Jehiel, et Samaias, et cum eis sexaginta viri.

** Ezra 8:14

De filii Begui, Uthai et Zachur, et cum eis septuaginta viri.  

** Ezra 8:15

Congregavi autem eos ad fluvium qui decurrit ad Ahava, et mansimus ibi tribus diebus : quæsivique in populo et in sacerdotibus de filiis Levi, et non inveni ibi.

** Ezra 8:16

Itaque misi Eliezer, et Ariel, et Semeiam, et Elnathan, et Jarib, et alterum Elnathan, et Nathan, et Zachariam, et Mosollam principes : et Jojarib, et Elnathan sapientes.

** Ezra 8:17

Et misi eos ad Eddo, qui est primus in Chasphiæ loco, et posui in ore eorum verba, quæ loquerentur ad Eddo, et fratres ejus Nathinæos in loco Chasphiæ, ut adducerent nobis ministros domus Dei nostri.

** Ezra 8:18

Et adduxerunt nobis per manum Dei nostri bonam super nos, virum doctissimum de filiis Moholi filii Levi, filii Israël, et Sarabiam et filios ejus et fratres ejus decem et octo,

** Ezra 8:19

et Hasabiam, et cum eo Isaiam de filiis Merari, fratresque ejus, et filios ejus viginti :

** Ezra 8:20

et de Nathinæis, quos dederat David et principes ad ministeria Levitarum, Nathinæos ducentos viginti : omnes hi suis nominibus vocabantur.

** Ezra 8:21

Et prædicavi ibi jejunium juxta fluvium Ahava, ut affligeremur coram Domino Deo nostro, et peteremus ab eo viam rectam nobis et filiis nostris, universæque substantiæ nostræ.

** Ezra 8:22

Erubui enim petere a rege auxilium et equites, qui defenderent nos ab inimico in via : quia dixeramus regi : Manus Dei nostri est super omnes qui quærunt eum in bonitate : et imperium ejus, et fortitudo ejus, et furor, super omnes qui derelinquunt eum.

** Ezra 8:23

Jejunavimus autem, et rogavimus Deum nostrum per hoc : et evenit nobis prospere.

** Ezra 8:24

Et separavi de principibus sacerdotum duodecim, Sarabiam, et Hasabiam, et cum eis de fratribus eorum decem :

** Ezra 8:25

appendique eis argentum et aurum, et vasa consecrata domus Dei nostri, quæ obtulerat rex et consiliatores ejus, et principes ejus, universusque Israël eorum qui inventi fuerant :

** Ezra 8:26

et appendi in manibus eorum argenti talenta sexcenta quinquaginta, et vasa argentea centum, auri centum talenta :

** Ezra 8:27

et crateres aureos viginti, qui habebant solidos millenos, et vasa æris fulgentis optimi duo, pulchra ut aurum.

** Ezra 8:28

Et dixi eis : Vos sancti Domini, et vasa sancta, et argentum et aurum, quod sponte oblatum est Domino Deo patrum nostrorum :

** Ezra 8:29

vigilate et custodite, donec appendatis coram principibus sacerdotum, et Levitarum, et ducibus familiarum Israël in Jerusalem, in thesaurum domus Domini.

** Ezra 8:30

Susceperunt autem sacerdotes et Levitæ pondus argenti, et auri, et vasorum, ut deferrent Jerusalem in domum Dei nostri.

** Ezra 8:31

Promovimus ergo a flumine Ahava duodecimo die mensis primi ut pergeremus Jerusalem : et manus Dei nostri fuit super nos, et liberavit nos de manu inimici et insidiatoris in via.  

** Ezra 8:32

Et venimus Jerusalem, et mansimus ibi tribus diebus.

** Ezra 8:33

Die autem quarta appensum est argentum, et aurum, et vasa in domo Dei nostri per manum Meremoth filii Uriæ sacerdotis, et cum eo Eleazar filius Phinees, cumque eis Jozabed filius Josue, et Noadaia filius Bennoi Levitæ,

** Ezra 8:34

juxta numerum et pondus omnium : descriptumque est omne pondus in tempore illo.

** Ezra 8:35

Sed et qui venerant de captivitate filii transmigrationis, obtulerunt holocautomata Deo Israël, vitulos duodecim pro omni populo Israël, arietes nonaginta sex, agnos septuaginta septem, hircos pro peccato duodecim : omnia in holocaustum Domino.

** Ezra 8:36

Dederunt autem edicta regis satrapis qui erant de conspectu regis, et ducibus trans flumen, et elevaverunt populum et domum Dei.   

* Ezra 9

** Ezra 9:1

Postquam autem hæc completa sunt, accesserunt ad me principes, dicentes : Non est separatus populus Israël, sacerdotes et Levitæ, a populis terrarum et abominationibus eorum : Chananæi videlicet, et Hethæi, et Pherezæi, et Jebusæi, et Ammonitarum, et Moabitarum, et Ægyptiorum, et Amorrhæorum :

** Ezra 9:2

tulerunt enim de filiabus eorum sibi et filiis suis, et commiscuerunt semen sanctum cum populis terrarum : manus etiam principum et magistratuum fuit in transgressione hac prima.

** Ezra 9:3

Cumque audissem sermonem istum, scidi pallium meum et tunicam, et evelli capillos capitis mei et barbæ, et sedi mœrens.

** Ezra 9:4

Convenerunt autem ad me omnes qui timebant verbum Dei Israël, pro transgressione eorum qui de captivitate venerant, et ego sedebam tristis usque ad sacrificium vespertinum :

** Ezra 9:5

et in sacrificio vespertino, surrexi de afflictione mea, et scisso pallio et tunica, curvavi genua mea, et expandi manus meas ad Dominum Deum meum.  

** Ezra 9:6

Et dixi : Deus meus, confundor et erubesco levare faciem meam ad te : quoniam iniquitates nostræ multiplicatæ sunt super caput nostrum, et delicta nostra creverunt usque ad cælum,

** Ezra 9:7

a diebus patrum nostrorum : sed et nos ipsi peccavimus graviter usque ad diem hanc, et in iniquitatibus nostris traditi sumus ipsi, et reges nostri, et sacerdotes nostri, in manum regum terrarum, et in gladium, et in captivitatem, et in rapinam, et in confusionem vultus, sicut et die hac.

** Ezra 9:8

Et nunc quasi parum et ad momentum facta est deprecatio nostra apud Dominum Deum nostrum, ut dimitterentur nobis reliquiæ, et daretur nobis paxillus in loco sancto ejus, et illuminaret oculos nostros Deus noster, et daret nobis vitam modicam in servitute nostra :

** Ezra 9:9

quia servi sumus, et in servitute nostra non dereliquit nos Deus noster, sed inclinavit super nos misericordiam coram rege Persarum, ut daret nobis vitam, et sublimaret domum Dei nostri, et exstrueret solitudines ejus, et daret nobis sepem in Juda et Jerusalem.  

** Ezra 9:10

Et nunc quid dicemus, Deus noster, post hæc ? Quia dereliquimus mandata tua,

** Ezra 9:11

quæ præcepisti in manu servorum tuorum prophetarum, dicens : Terra, ad quam vos ingredimini ut possideatis eam, terra immunda est juxta immunditiam populorum, ceterarumque terrarum, abominationibus eorum qui repleverunt eam ab ore usque ad os in coinquinatione sua.

** Ezra 9:12

Nunc ergo filias vestras ne detis filiis eorum, et filias eorum ne accipiatis filiis vestris, et non quæratis pacem eorum et prosperitatem eorum usque in æternum : ut confortemini, et comedatis quæ bona sunt terræ, et hæredes habeatis filios vestros usque in sæculum.

** Ezra 9:13

Et post omnia quæ venerunt super nos in operibus nostris pessimis, et in delicto nostro magno, quia tu, Deus noster, liberasti nos de iniquitate nostra, et dedisti nobis salutem sicut est hodie,

** Ezra 9:14

ut non converteremur, et irrita faceremus mandata tua, neque matrimonia jungeremus cum populis abominationum istarum. Numquid iratus es nobis usque ad consummationem, ne dimitteres nobis reliquias ad salutem ?

** Ezra 9:15

Domine Deus Israël, justus es tu : quoniam derelicti sumus, qui salvaremur sicut die hac. Ecce coram te sumus in delicto nostro : non enim stari potest coram te super hoc.   

* Ezra 10

** Ezra 10:1

Sic ergo orante Esdra, et implorante eo et flente, et jacente ante templum Dei, collectus est ad eum de Israël cœtus grandis nimis virorum et mulierum et puerorum, et flevit populus fletu multo.

** Ezra 10:2

Et respondit Sechenias filius Jehiel de filiis Ælam, et dixit Esdræ : Nos prævaricati sumus in Deum nostrum, et duximus uxores alienigenas de populis terræ : et nunc, si est pœnitentia in Israël super hoc,

** Ezra 10:3

percutiamus fœdus cum Domino Deo nostro, ut projiciamus universas uxores, et eos qui de his nati sunt, juxta voluntatem Domini, et eorum qui timent præceptum Domini Dei nostri : secundum legem fiat.

** Ezra 10:4

Surge, tuum est decernere, nosque erimus tecum : confortare, et fac.

** Ezra 10:5

Surrexit ergo Esdras, et adjuravit principes sacerdotum et Levitarum, et omnem Israël, ut facerent secundum verbum hoc : et juraverunt.

** Ezra 10:6

Et surrexit Esdras ante domum Dei, et abiit ad cubiculum Johanan filii Eliasib, et ingressus est illuc : panem non comedit, et aquam non bibit : lugebat enim transgressionem eorum, qui venerant de captivitate.

** Ezra 10:7

Et missa est vox in Juda et in Jerusalem omnibus filiis transmigrationis, ut congregarentur in Jerusalem :

** Ezra 10:8

et omnis qui non venerit in tribus diebus juxta consilium principum et seniorum, auferetur universa substantia ejus, et ipse abjicietur de cœtu transmigrationis.

** Ezra 10:9

Convenerunt igitur omnes viri Juda et Benjamin in Jerusalem tribus diebus : ipse est mensis nonus, vigesimo die mensis : et sedit omnis populus in platea domus Dei, trementes pro peccato, et pluviis.  

** Ezra 10:10

Et surrexit Esdras sacerdos, et dixit ad eos : Vos transgressi estis, et duxistis uxores alienigenas, ut adderetis super delictum Israël.

** Ezra 10:11

Et nunc date confessionem Domino Deo patrum vestrorum, et facite placitum ejus, et separamini a populis terræ, et ab uxoribus alienigenis.

** Ezra 10:12

Et respondit universa multitudo, dixitque voce magna : Juxta verbum tuum ad nos, sic fiat.

** Ezra 10:13

Verumtamen quia populus multus est, et tempus pluviæ, et non sustinemus stare foris, et opus non est diei unius vel duorum (vehementer quippe peccavimus in sermone isto),

** Ezra 10:14

constituantur principes in universa multitudine : et omnes in civitatibus nostris qui duxerunt uxores alienigenas veniant in temporibus statutis, et cum his seniores per civitatem et civitatem, et judices ejus, donec avertatur ira Dei nostri a nobis super peccato hoc.

** Ezra 10:15

Igitur Jonathan filius Azahel, et Jaasia filius Thecue, steterunt super hoc, et Messollam et Sebethai Levites adjuverunt eos :

** Ezra 10:16

feceruntque sic filii transmigrationis. Et abierunt Esdras sacerdos, et viri principes familiarum, in domos patrum suorum, et omnes per nomina sua, et sederunt in die primo mensis decimi ut quærerent rem.

** Ezra 10:17

Et consummati sunt omnes viri, qui duxerant uxores alienigenas, usque ad diem primam mensis primi.  

** Ezra 10:18

Et inventi sunt de filiis sacerdotum qui duxerant uxores alienigenas. De filiis Josue filii Josedec, et fratres ejus, Maasia, et Eliezer, et Jarib, et Godolia.

** Ezra 10:19

Et dederunt manus suas ut ejicerent uxores suas, et pro delicto suo arietem de ovibus offerrent.

** Ezra 10:20

Et de filiis Emmer, Hanani, et Zebedia.

** Ezra 10:21

Et de filiis Harim, Maasia, et Elia, et Semeia, et Jehiel, et Ozias.

** Ezra 10:22

Et de filiis Pheshur, Elioënai, Maasia, Ismaël, Nathanaël, Jozabed, et Elasa.

** Ezra 10:23

Et de filiis Levitarum, Jozabed, et Semei, et Celaia, ipse est Calita, Phataia, Juda, et Eliezer.

** Ezra 10:24

Et de cantoribus, Eliasib. Et de janitoribus, Sellum, et Telem, et Uri.

** Ezra 10:25

Et ex Israël, de filiis Pharos, Remeia, et Jesia, et Melchia, et Miamin, et Eliezer, et Melchia, et Banea.

** Ezra 10:26

Et de filiis Ælam, Mathania, Zacharias, et Jehiel, et Abdi, et Jerimoth, et Elia.

** Ezra 10:27

Et de filiis Zethua, Elioënai, Eliasib, Mathania, et Jerimuth, et Zabad, et Aziza.

** Ezra 10:28

Et de filiis Bebai, Johanan, Hanania, Zabbai, Athalai.

** Ezra 10:29

Et de filiis Bani, Mosollam, et Melluch, et Adaia, Jasub, et Saal, et Ramoth.

** Ezra 10:30

Et de filiis Phahath Moab, Edna, et Chalal, Banaias, et Maasias, Mathanias, Beseleel, Bennui, et Manasse.

** Ezra 10:31

Et de filiis Herem, Eliezer, Josue, Melchias, Semeias, Simeon,

** Ezra 10:32

Benjamin, Maloch, Samarias.

** Ezra 10:33

Et de filiis Hasom, Mathanai, Mathatha, Zabad, Eliphelet, Jermai, Manasse, Semei.

** Ezra 10:34

De filiis Bani, Maadi, Amram, et Vel,

** Ezra 10:35

Baneas, et Badaias, Cheliau,

** Ezra 10:36

Vania, Marimuth, et Eliasib,

** Ezra 10:37

Mathanias, Mathanai, et Jasi,

** Ezra 10:38

et Bani, et Bennui, Semei,

** Ezra 10:39

et Salmias, et Nathan, et Adaias,

** Ezra 10:40

et Mechnedebai, Sisai, Sarai,

** Ezra 10:41

Ezrel, et Selemiau, Semeria,

** Ezra 10:42

Sellum, Amaria, Joseph.

** Ezra 10:43

De filiis Nebo, Jehiel, Mathathias, Zabad, Zabina, Jeddu, et Joël, et Banaia.

** Ezra 10:44

Omnes hi acceperant uxores alienigenas, et fuerunt ex eis mulieres, quæ pepererant filios.    

