* Genesis 1

** Genesis 1:1

In principio creavit Deus cælum et terram.

** Genesis 1:2

Terra autem erat inanis et vacua, et tenebræ erant super faciem abyssi : et spiritus Dei ferebatur super aquas.

** Genesis 1:3

Dixitque Deus : Fiat lux. Et facta est lux.

** Genesis 1:4

Et vidit Deus lucem quod esset bona : et divisit lucem a tenebris.

** Genesis 1:5

Appellavitque lucem Diem, et tenebras Noctem : factumque est vespere et mane, dies unus.

** Genesis 1:6

Dixit quoque Deus : Fiat firmamentum in medio aquarum : et dividat aquas ab aquis.

** Genesis 1:7

Et fecit Deus firmamentum, divisitque aquas, quæ erant sub firmamento, ab his, quæ erant super firmamentum. Et factum est ita.

** Genesis 1:8

Vocavitque Deus firmamentum, Cælum : et factum est vespere et mane, dies secundus.

** Genesis 1:9

Dixit vero Deus : Congregentur aquæ, quæ sub cælo sunt, in locum unum : et appareat arida. Et factum est ita.

** Genesis 1:10

Et vocavit Deus aridam Terram, congregationesque aquarum appellavit Maria. Et vidit Deus quod esset bonum.

** Genesis 1:11

Et ait : Germinet terra herbam virentem, et facientem semen, et lignum pomiferum faciens fructum juxta genus suum, cujus semen in semetipso sit super terram. Et factum est ita.

** Genesis 1:12

Et protulit terra herbam virentem, et facientem semen juxta genus suum, lignumque faciens fructum, et habens unumquodque sementem secundum speciem suam. Et vidit Deus quod esset bonum.

** Genesis 1:13

Et factum est vespere et mane, dies tertius.

** Genesis 1:14

Dixit autem Deus : Fiant luminaria in firmamento cæli, et dividant diem ac noctem, et sint in signa et tempora, et dies et annos :

** Genesis 1:15

ut luceant in firmamento cæli, et illuminent terram. Et factum est ita.

** Genesis 1:16

Fecitque Deus duo luminaria magna : luminare majus, ut præesset diei : et luminare minus, ut præesset nocti : et stellas.

** Genesis 1:17

Et posuit eas in firmamento cæli, ut lucerent super terram,

** Genesis 1:18

et præessent diei ac nocti, et dividerent lucem ac tenebras. Et vidit Deus quod esset bonum.

** Genesis 1:19

Et factum est vespere et mane, dies quartus.

** Genesis 1:20

Dixit etiam Deus : Producant aquæ reptile animæ viventis, et volatile super terram sub firmamento cæli.

** Genesis 1:21

Creavitque Deus cete grandia, et omnem animam viventem atque motabilem, quam produxerant aquæ in species suas, et omne volatile secundum genus suum. Et vidit Deus quod esset bonum.

** Genesis 1:22

Benedixitque eis, dicens : Crescite, et multiplicamini, et replete aquas maris : avesque multiplicentur super terram.

** Genesis 1:23

Et factum est vespere et mane, dies quintus.

** Genesis 1:24

Dixit quoque Deus : Producat terra animam viventem in genere suo, jumenta, et reptilia, et bestias terræ secundum species suas. Factumque est ita.

** Genesis 1:25

Et fecit Deus bestias terræ juxta species suas, et jumenta, et omne reptile terræ in genere suo.   Et vidit Deus quod esset bonum,

** Genesis 1:26

et ait : Faciamus hominem ad imaginem et similitudinem nostram : et præsit piscibus maris, et volatilibus cæli, et bestiis, universæque terræ, omnique reptili, quod movetur in terra.

** Genesis 1:27

Et creavit Deus hominem ad imaginem suam : ad imaginem Dei creavit illum, masculum et feminam creavit eos.

** Genesis 1:28

Benedixitque illis Deus, et ait : Crescite et multiplicamini, et replete terram, et subjicite eam, et dominamini piscibus maris, et volatilibus cæli, et universis animantibus, quæ moventur super terram.

** Genesis 1:29

Dixitque Deus : Ecce dedi vobis omnem herbam afferentem semen super terram, et universa ligna quæ habent in semetipsis sementem generis sui, ut sint vobis in escam :

** Genesis 1:30

et cunctis animantibus terræ, omnique volucri cæli, et universis quæ moventur in terra, et in quibus est anima vivens, ut habeant ad vescendum. Et factum est ita.

** Genesis 1:31

Viditque Deus cuncta quæ fecerat, et erant valde bona. Et factum est vespere et mane, dies sextus.   

* Genesis 2

** Genesis 2:1

Igitur perfecti sunt cæli et terra, et omnis ornatus eorum.

** Genesis 2:2

Complevitque Deus die septimo opus suum quod fecerat : et requievit die septimo ab universo opere quod patrarat.

** Genesis 2:3

Et benedixit diei septimo, et sanctificavit illum, quia in ipso cessaverat ab omni opere suo quod creavit Deus ut faceret.  

** Genesis 2:4

Istæ sunt generationes cæli et terræ, quando creata sunt, in die quo fecit Dominus Deus cælum et terram,

** Genesis 2:5

et omne virgultum agri antequam oriretur in terra, omnemque herbam regionis priusquam germinaret : non enim pluerat Dominus Deus super terram, et homo non erat qui operaretur terram :

** Genesis 2:6

sed fons ascendebat e terra, irrigans universam superficiem terræ.

** Genesis 2:7

Formavit igitur Dominus Deus hominem de limo terræ, et inspiravit in faciem ejus spiraculum vitæ, et factus est homo in animam viventem.

** Genesis 2:8

Plantaverat autem Dominus Deus paradisum voluptatis a principio, in quo posuit hominem quem formaverat.

** Genesis 2:9

Produxitque Dominus Deus de humo omne lignum pulchrum visu, et ad vescendum suave lignum etiam vitæ in medio paradisi, lignumque scientiæ boni et mali.

** Genesis 2:10

Et fluvius egrediebatur de loco voluptatis ad irrigandum paradisum, qui inde dividitur in quatuor capita.

** Genesis 2:11

Nomen uni Phison : ipse est qui circuit omnem terram Hevilath, ubi nascitur aurum :

** Genesis 2:12

et aurum terræ illius optimum est ; ibi invenitur bdellium, et lapis onychinus.

** Genesis 2:13

Et nomen fluvii secundi Gehon ; ipse est qui circumit omnem terram Æthiopiæ.

** Genesis 2:14

Nomen vero fluminis tertii, Tigris : ipse vadit contra Assyrios. Fluvius autem quartus, ipse est Euphrates.

** Genesis 2:15

Tulit ergo Dominus Deus hominem, et posuit eum in paradiso voluptatis, ut operaretur, et custodiret illum :

** Genesis 2:16

præcepitque ei, dicens : Ex omni ligno paradisi comede ;

** Genesis 2:17

de ligno autem scientiæ boni et mali ne comedas : in quocumque enim die comederis ex eo, morte morieris.

** Genesis 2:18

Dixit quoque Dominus Deus : Non est bonum esse hominem solum : faciamus ei adjutorium simile sibi.

** Genesis 2:19

Formatis igitur Dominus Deus de humo cunctis animantibus terræ, et universis volatilibus cæli, adduxit ea ad Adam, ut videret quid vocaret ea : omne enim quod vocavit Adam animæ viventis, ipsum est nomen ejus.

** Genesis 2:20

Appellavitque Adam nominibus suis cuncta animantia, et universa volatilia cæli, et omnes bestias terræ : Adæ vero non inveniebatur adjutor similis ejus.

** Genesis 2:21

Immisit ergo Dominus Deus soporem in Adam : cumque obdormisset, tulit unam de costis ejus, et replevit carnem pro ea.

** Genesis 2:22

Et ædificavit Dominus Deus costam, quam tulerat de Adam, in mulierem : et adduxit eam ad Adam.

** Genesis 2:23

Dixitque Adam : Hoc nunc os ex ossibus meis, et caro de carne mea : hæc vocabitur Virago, quoniam de viro sumpta est.

** Genesis 2:24

Quam ob rem relinquet homo patrem suum, et matrem, et adhærebit uxori suæ : et erunt duo in carne una.

** Genesis 2:25

Erat autem uterque nudus, Adam scilicet et uxor ejus : et non erubescebant.   

* Genesis 3

** Genesis 3:1

Sed et serpens erat callidior cunctis animantibus terræ quæ fecerat Dominus Deus. Qui dixit ad mulierem : Cur præcepit vobis Deus ut non comederetis de omni ligno paradisi ?

** Genesis 3:2

Cui respondit mulier : De fructu lignorum, quæ sunt in paradiso, vescimur :

** Genesis 3:3

de fructu vero ligni quod est in medio paradisi, præcepit nobis Deus ne comederemus, et ne tangeremus illud, ne forte moriamur.

** Genesis 3:4

Dixit autem serpens ad mulierem : Nequaquam morte moriemini.

** Genesis 3:5

Scit enim Deus quod in quocumque die comederitis ex eo, aperientur oculi vestri, et eritis sicut dii, scientes bonum et malum.

** Genesis 3:6

Vidit igitur mulier quod bonum esset lignum ad vescendum, et pulchrum oculis, aspectuque delectabile : et tulit de fructu illius, et comedit : deditque viro suo, qui comedit.

** Genesis 3:7

Et aperti sunt oculi amborum ; cumque cognovissent se esse nudos, consuerunt folia ficus, et fecerunt sibi perizomata.

** Genesis 3:8

Et cum audissent vocem Domini Dei deambulantis in paradiso ad auram post meridiem, abscondit se Adam et uxor ejus a facie Domini Dei in medio ligni paradisi.

** Genesis 3:9

Vocavitque Dominus Deus Adam, et dixit ei : Ubi es ?

** Genesis 3:10

Qui ait : Vocem tuam audivi in paradiso, et timui, eo quod nudus essem, et abscondi me.

** Genesis 3:11

Cui dixit : Quis enim indicavit tibi quod nudus esses, nisi quod ex ligno de quo præceperam tibi ne comederes, comedisti ?

** Genesis 3:12

Dixitque Adam : Mulier, quam dedisti mihi sociam, dedit mihi de ligno, et comedi.

** Genesis 3:13

Et dixit Dominus Deus ad mulierem : Quare hoc fecisti ? Quæ respondit : Serpens decepit me, et comedi.  

** Genesis 3:14

Et ait Dominus Deus ad serpentem :   Quia fecisti hoc,  maledictus es inter omnia animantia, et bestias terræ :  super pectus tuum gradieris, et terram comedes cunctis diebus vitæ tuæ. 

** Genesis 3:15

Inimicitias ponam inter te et mulierem,  et semen tuum et semen illius :  ipsa conteret caput tuum,  et tu insidiaberis calcaneo ejus.

** Genesis 3:16

Mulieri quoque dixit : Multiplicabo ærumnas tuas, et conceptus tuos : in dolore paries filios, et sub viri potestate eris, et ipse dominabitur tui.

** Genesis 3:17

Adæ vero dixit : Quia audisti vocem uxoris tuæ, et comedisti de ligno, ex quo præceperam tibi ne comederes, maledicta terra in opere tuo : in laboribus comedes ex ea cunctis diebus vitæ tuæ.

** Genesis 3:18

Spinas et tribulos germinabit tibi, et comedes herbam terræ.

** Genesis 3:19

In sudore vultus tui vesceris pane, donec revertaris in terram de qua sumptus es : quia pulvis es et in pulverem reverteris.

** Genesis 3:20

Et vocavit Adam nomen uxoris suæ, Heva : eo quod mater esset cunctorum viventium.

** Genesis 3:21

Fecit quoque Dominus Deus Adæ et uxori ejus tunicas pelliceas, et induit eos :

** Genesis 3:22

et ait : Ecce Adam quasi unus ex nobis factus est, sciens bonum et malum : nunc ergo ne forte mittat manum suam, et sumat etiam de ligno vitæ, et comedat, et vivat in æternum.

** Genesis 3:23

Et emisit eum Dominus Deus de paradiso voluptatis, ut operaretur terram de qua sumptus est.

** Genesis 3:24

Ejecitque Adam : et collocavit ante paradisum voluptatis cherubim, et flammeum gladium, atque versatilem, ad custodiendam viam ligni vitæ.  

* Genesis 4

** Genesis 4:1

Adam vero cognovit uxorem suam Hevam, quæ concepit et peperit Cain, dicens : Possedi hominem per Deum.

** Genesis 4:2

Rursumque peperit fratrem ejus Abel. Fuit autem Abel pastor ovium, et Cain agricola.

** Genesis 4:3

Factum est autem post multos dies ut offerret Cain de fructibus terræ munera Domino.

** Genesis 4:4

Abel quoque obtulit de primogenitis gregis sui, et de adipibus eorum : et respexit Dominus ad Abel, et ad munera ejus.

** Genesis 4:5

Ad Cain vero, et ad munera illius non respexit : iratusque est Cain vehementer, et concidit vultus ejus.

** Genesis 4:6

Dixitque Dominus ad eum : Quare iratus es ? et cur concidit facies tua ?

** Genesis 4:7

nonne si bene egeris, recipies : sin autem male, statim in foribus peccatum aderit ? sed sub te erit appetitus ejus, et tu dominaberis illius.

** Genesis 4:8

Dixitque Cain ad Abel fratrem suum : Egrediamur foras. Cumque essent in agro, consurrexit Cain adversus fratrem suum Abel, et interfecit eum.

** Genesis 4:9

Et ait Dominus ad Cain : Ubi est Abel frater tuus ? Qui respondit : Nescio : num custos fratris mei sum ego ?

** Genesis 4:10

Dixitque ad eum : Quid fecisti ? vox sanguinis fratris tui clamat ad me de terra.

** Genesis 4:11

Nunc igitur maledictus eris super terram, quæ aperuit os suum, et suscepit sanguinem fratris tui de manu tua.

** Genesis 4:12

Cum operatus fueris eam, non dabit tibi fructus suos : vagus et profugus eris super terram.

** Genesis 4:13

Dixitque Cain ad Dominum : Major est iniquitas mea, quam ut veniam merear.

** Genesis 4:14

Ecce ejicis me hodie a facie terræ, et a facie tua abscondar, et ero vagus et profugus in terra : omnis igitur qui invenerit me, occidet me.

** Genesis 4:15

Dixitque ei Dominus : Nequaquam ita fiet : sed omnis qui occiderit Cain, septuplum punietur. Posuitque Dominus Cain signum, ut non interficeret eum omnis qui invenisset eum.

** Genesis 4:16

Egressusque Cain a facie Domini, habitavit profugus in terra ad orientalem plagam Eden.  

** Genesis 4:17

Cognovit autem Cain uxorem suam, quæ concepit, et peperit Henoch : et ædificavit civitatem, vocavitque nomen ejus ex nomine filii sui, Henoch.

** Genesis 4:18

Porro Henoch genuit Irad, et Irad genuit Maviaël, et Maviaël genuit Mathusaël, et Mathusaël genuit Lamech.

** Genesis 4:19

Qui accepit duas uxores, nomen uni Ada, et nomen alteri Sella.

** Genesis 4:20

Genuitque Ada Jabel, qui fuit pater habitantium in tentoriis, atque pastorum.

** Genesis 4:21

Et nomen fratris ejus Jubal : ipse fuit pater canentium cithara et organo.

** Genesis 4:22

Sella quoque genuit Tubalcain, qui fuit malleator et faber in cuncta opera æris et ferri. Soror vero Tubalcain, Noëma.

** Genesis 4:23

Dixitque Lamech uxoribus suis Adæ et Sellæ :   Audite vocem meam, uxores Lamech ;  auscultate sermonem meum :  quoniam occidi virum in vulnus meum,  et adolescentulum in livorem meum. 

** Genesis 4:24

Septuplum ultio dabitur de Cain :  de Lamech vero septuagies septies.  

** Genesis 4:25

Cognovit quoque adhuc Adam uxorem suam : et peperit filium, vocavitque nomen ejus Seth, dicens : Posuit mihi Deus semen aliud pro Abel, quem occidit Cain.

** Genesis 4:26

Sed et Seth natus est filius, quem vocavit Enos : iste cœpit invocare nomen Domini.   

* Genesis 5

** Genesis 5:1

Hic est liber generationis Adam. In die qua creavit Deus hominem, ad similitudinem Dei fecit illum.

** Genesis 5:2

Masculum et feminam creavit eos, et benedixit illis : et vocavit nomen eorum Adam, in die quo creati sunt.

** Genesis 5:3

Vixit autem Adam centum triginta annis : et genuit ad imaginem et similitudinem suam, vocavitque nomen ejus Seth.

** Genesis 5:4

Et facti sunt dies Adam, postquam genuit Seth, octingenti anni : genuitque filios et filias.

** Genesis 5:5

Et factum est omne tempus quod vixit Adam, anni nongenti triginta, et mortuus est.

** Genesis 5:6

Vixit quoque Seth centum quinque annis, et genuit Enos.

** Genesis 5:7

Vixitque Seth, postquam genuit Enos, octingentis septem annis, genuitque filios et filias.

** Genesis 5:8

Et facti sunt omnes dies Seth nongentorum duodecim annorum, et mortuus est.

** Genesis 5:9

Vixit vero Enos nonaginta annis, et genuit Cainan.

** Genesis 5:10

Post cujus ortum vixit octingentis quindecim annis, et genuit filios et filias.

** Genesis 5:11

Factique sunt omnes dies Enos nongenti quinque anni, et mortuus est.

** Genesis 5:12

Vixit quoque Cainan septuaginta annis, et genuit Malaleel.

** Genesis 5:13

Et vixit Cainan, postquam genuit Malaleel, octingentis quadraginta annis, genuitque filios et filias.

** Genesis 5:14

Et facti sunt omnes dies Cainan nongenti decem anni, et mortuus est.

** Genesis 5:15

Vixit autem Malaleel sexaginta quinque annis, et genuit Jared.

** Genesis 5:16

Et vixit Malaleel, postquam genuit Jared, octingentis triginta annis, et genuit filios et filias.

** Genesis 5:17

Et facti sunt omnes dies Malaleel octingenti nonaginta quinque anni, et mortuus est.

** Genesis 5:18

Vixitque Jared centum sexaginta duobus annis, et genuit Henoch.

** Genesis 5:19

Et vixit Jared, postquam genuit Henoch, octingentis annis, et genuit filios et filias.

** Genesis 5:20

Et facti sunt omnes dies Jared nongenti sexaginta duo anni, et mortuus est.

** Genesis 5:21

Porro Henoch vixit sexaginta quinque annis, et genuit Mathusalam.

** Genesis 5:22

Et ambulavit Henoch cum Deo : et vixit, postquam genuit Mathusalam, trecentis annis, et genuit filios et filias.

** Genesis 5:23

Et facti sunt omnes dies Henoch trecenti sexaginta quinque anni.

** Genesis 5:24

Ambulavitque cum Deo, et non apparuit : quia tulit eum Deus.

** Genesis 5:25

Vixit quoque Mathusala centum octoginta septem annis, et genuit Lamech.

** Genesis 5:26

Et vixit Mathusala, postquam genuit Lamech, septingentis octoginta duobus annis, et genuit filios et filias.

** Genesis 5:27

Et facti sunt omnes dies Mathusala nongenti sexaginta novem anni, et mortuus est.

** Genesis 5:28

Vixit autem Lamech centum octoginta duobus annis, et genuit filium :

** Genesis 5:29

vocavitque nomen ejus Noë, dicens : Iste consolabitur nos ab operibus et laboribus manuum nostrarum in terra, cui maledixit Dominus.

** Genesis 5:30

Vixitque Lamech, postquam genuit Noë, quingentis nonaginta quinque annis, et genuit filios et filias.

** Genesis 5:31

Et facti sunt omnes dies Lamech septingenti septuaginta septem anni, et mortuus est. Noë vero cum quingentorum esset annorum, genuit Sem, Cham et Japheth.   

* Genesis 6

** Genesis 6:1

Cumque cœpissent homines multiplicari super terram, et filias procreassent,

** Genesis 6:2

videntes filii Dei filias hominum quod essent pulchræ, acceperunt sibi uxores ex omnibus, quas elegerant.

** Genesis 6:3

Dixitque Deus : Non permanebit spiritus meus in homine in æternum, quia caro est : eruntque dies illius centum viginti annorum.

** Genesis 6:4

Gigantes autem erant super terram in diebus illis : postquam enim ingressi sunt filii Dei ad filias hominum, illæque genuerunt, isti sunt potentes a sæculo viri famosi.

** Genesis 6:5

Videns autem Deus quod multa malitia hominum esset in terra, et cuncta cogitatio cordis intenta esset ad malum omni tempore,

** Genesis 6:6

pœnituit eum quod hominum fecisset in terra. Et tactus dolore cordis intrinsecus,

** Genesis 6:7

Delebo, inquit, hominem, quem creavi, a facie terræ, ab homine usque ad animantia, a reptili usque ad volucres cæli : pœnitet enim me fecisse eos.  

** Genesis 6:8

Noë vero invenit gratiam coram Domino.

** Genesis 6:9

Hæ sunt generationes Noë : Noë vir justus atque perfectus fuit in generationibus suis ; cum Deo ambulavit.

** Genesis 6:10

Et genuit tres filios, Sem, Cham et Japheth.

** Genesis 6:11

Corrupta est autem terra coram Deo, et repleta est iniquitate.

** Genesis 6:12

Cumque vidisset Deus terram esse corruptam (omnis quippe caro corruperat viam suam super terram),

** Genesis 6:13

dixit ad Noë : Finis universæ carnis venit coram me : repleta est terra iniquitate a facie eorum, et ego disperdam eos cum terra.

** Genesis 6:14

Fac tibi arcam de lignis lævigatis ; mansiunculas in arca facies, et bitumine linies intrinsecus et extrinsecus.

** Genesis 6:15

Et sic facies eam : trecentorum cubitorum erit longitudo arcæ, quinquaginta cubitorum latitudo, et triginta cubitorum altitudo illius.

** Genesis 6:16

Fenestram in arca facies, et in cubito consummabis summitatem ejus : ostium autem arcæ pones ex latere ; deorsum, cœnacula et tristega facies in ea.  

** Genesis 6:17

Ecce ego adducam aquas diluvii super terram, ut interficiam omnem carnem, in qua spiritus vitæ est subter cælum : universa quæ in terra sunt, consumentur.

** Genesis 6:18

Ponamque fœdus meum tecum : et ingredieris arcam tu et filii tui, uxor tua, et uxores filiorum tuorum tecum.

** Genesis 6:19

Et ex cunctis animantibus universæ carnis bina induces in arcam, ut vivant tecum : masculini sexus et feminini.

** Genesis 6:20

De volucribus juxta genus suum, et de jumentis in genere suo, et ex omni reptili terræ secundum genus suum : bina de omnibus ingredientur tecum, ut possint vivere.

** Genesis 6:21

Tolles igitur tecum ex omnibus escis, quæ mandi possunt, et comportabis apud te : et erunt tam tibi, quam illis in cibum.

** Genesis 6:22

Fecit igitur Noë omnia quæ præceperat illi Deus.  

* Genesis 7

** Genesis 7:1

Dixitque Dominus ad eum : Ingredere tu et omnis domus tua in arcam : te enim vidi justum coram me in generatione hac.

** Genesis 7:2

Ex omnibus animantibus mundis tolle septena et septena, masculum et feminam : de animantibus vero immundis duo et duo, masculum et feminam.

** Genesis 7:3

Sed et de volatilibus cæli septena et septena, masculum et feminam : ut salvetur semen super faciem universæ terræ.

** Genesis 7:4

Adhuc enim, et post dies septem ego pluam super terram quadraginta diebus et quadraginta noctibus : et delebo omnem substantiam, quam feci, de superficie terræ.

** Genesis 7:5

Fecit ergo Noë omnia quæ mandaverat ei Dominus.

** Genesis 7:6

Eratque sexcentorum annorum quando diluvii aquæ inundaverunt super terram.

** Genesis 7:7

Et ingressus est Noë et filii ejus, uxor ejus et uxores filiorum ejus cum eo in arcam propter aquas diluvii.

** Genesis 7:8

De animantibus quoque mundis et immundis, et de volucribus, et ex omni quod movetur super terram,

** Genesis 7:9

duo et duo ingressa sunt ad Noë in arcam, masculus et femina, sicut præceperat Dominus Noë.

** Genesis 7:10

Cumque transissent septem dies, aquæ diluvii inundaverunt super terram.

** Genesis 7:11

Anno sexcentesimo vitæ Noë, mense secundo, septimodecimo die mensis, rupti sunt omnes fontes abyssi magnæ, et cataractæ cæli apertæ sunt :

** Genesis 7:12

et facta est pluvia super terram quadraginta diebus et quadraginta noctibus.

** Genesis 7:13

In articulo diei illius ingressus est Noë, et Sem, et Cham, et Japheth filii ejus ; uxor illius, et tres uxores filiorum ejus cum eis in arcam :

** Genesis 7:14

ipsi et omne animal secundum genus suum, universaque jumenta in genere suo, et omne quod movetur super terram in genere suo, cunctumque volatile secundum genus suum, universæ aves, omnesque volucres,

** Genesis 7:15

ingressæ sunt ad Noë in arcam, bina et bina ex omni carne, in qua erat spiritus vitæ.

** Genesis 7:16

Et quæ ingressa sunt, masculus et femina ex omni carne introierunt, sicut præceperat ei Deus : et inclusit eum Dominus deforis.  

** Genesis 7:17

Factumque est diluvium quadraginta diebus super terram : et multiplicatæ sunt aquæ, et elevaverunt arcam in sublime a terra.

** Genesis 7:18

Vehementer enim inundaverunt, et omnia repleverunt in superficie terræ : porro arca ferebatur super aquas.

** Genesis 7:19

Et aquæ prævaluerunt nimis super terram : opertique sunt omnes montes excelsi sub universo cælo.

** Genesis 7:20

Quindecim cubitis altior fuit aqua super montes, quos operuerat.

** Genesis 7:21

Consumptaque est omnis caro quæ movebatur super terram, volucrum, animantium, bestiarum, omniumque reptilium, quæ reptant super terram : universi homines,

** Genesis 7:22

et cuncta, in quibus spiraculum vitæ est in terra, mortua sunt.

** Genesis 7:23

Et delevit omnem substantiam quæ erat super terram, ab homine usque ad pecus, tam reptile quam volucres cæli : et deleta sunt de terra. Remansit autem solus Noë, et qui cum eo erant in arca.

** Genesis 7:24

Obtinueruntque aquæ terram centum quinquaginta diebus.   

* Genesis 8

** Genesis 8:1

Recordatus autem Deus Noë, cunctorumque animantium, et omnium jumentorum, quæ erant cum eo in arca, adduxit spiritum super terram, et imminutæ sunt aquæ.

** Genesis 8:2

Et clausi sunt fontes abyssi, et cataractæ cæli : et prohibitæ sunt pluviæ de cælo.

** Genesis 8:3

Reversæque sunt aquæ de terra euntes et redeuntes : et cœperunt minui post centum quinquaginta dies.

** Genesis 8:4

Requievitque arca mense septimo, vigesimo septimo die mensis, super montes Armeniæ.

** Genesis 8:5

At vero aquæ ibant et decrescebant usque ad decimum mensem : decimo enim mense, primo die mensis, apparuerunt cacumina montium.

** Genesis 8:6

Cumque transissent quadraginta dies, aperiens Noë fenestram arcæ, quam fecerat, dimisit corvum,

** Genesis 8:7

qui egrediebatur, et non revertebatur, donec siccarentur aquæ super terram.

** Genesis 8:8

Emisit quoque columbam post eum, ut videret si jam cessassent aquæ super faciem terræ.

** Genesis 8:9

Quæ cum non invenisset ubi requiesceret pes ejus, reversa est ad eum in arcam : aquæ enim erant super universam terram : extenditque manum, et apprehensam intulit in arcam.

** Genesis 8:10

Expectatis autem ultra septem diebus aliis, rursum dimisit columbam ex arca.

** Genesis 8:11

At illa venit ad eum ad vesperam, portans ramum olivæ virentibus foliis in ore suo : intellexit ergo Noë quod cessassent aquæ super terram.

** Genesis 8:12

Expectavitque nihilominus septem alios dies : et emisit columbam, quæ non est reversa ultra ad eum.

** Genesis 8:13

Igitur sexcentesimo primo anno, primo mense, prima die mensis, imminutæ sunt aquæ super terram : et aperiens Noë tectum arcæ, aspexit, viditque quod exsiccata esset superficies terræ.

** Genesis 8:14

Mense secundo, septimo et vigesimo die mensis arefacta est terra.  

** Genesis 8:15

Locutus est autem Deus ad Noë, dicens :

** Genesis 8:16

Egredere de arca, tu et uxor tua, filii tui et uxores filiorum tuorum tecum.

** Genesis 8:17

Cuncta animantia, quæ sunt apud te, ex omni carne, tam in volatilibus quam in bestiis et universis reptilibus, quæ reptant super terram, educ tecum, et ingredimini super terram : crescite et multiplicamini super eam.

** Genesis 8:18

Egressus est ergo Noë, et filii ejus : uxor illius, et uxores filiorum ejus cum eo.

** Genesis 8:19

Sed et omnia animantia, jumenta, et reptilia quæ reptant super terram, secundum genus suum, egressa sunt de arca.

** Genesis 8:20

Ædificavit autem Noë altare Domino : et tollens de cunctis pecoribus et volucribus mundis, obtulit holocausta super altare.

** Genesis 8:21

Odoratusque est Dominus odorem suavitatis, et ait : Nequaquam ultra maledicam terræ propter homines : sensus enim et cogitatio humani cordis in malum prona sunt ab adolescentia sua : non igitur ultra percutiam omnem animam viventem sicut feci.

** Genesis 8:22

Cunctis diebus terræ, sementis et messis, frigus et æstus, æstas et hiems, nox et dies non requiescent.   

* Genesis 9

** Genesis 9:1

Benedixitque Deus Noë et filiis ejus. Et dixit ad eos : Crescite, et multiplicamini, et replete terram.

** Genesis 9:2

Et terror vester ac tremor sit super cuncta animalia terræ, et super omnes volucres cæli, cum universis quæ moventur super terram : omnes pisces maris manui vestræ traditi sunt.

** Genesis 9:3

Et omne, quod movetur et vivit, erit vobis in cibum : quasi olera virentia tradidi vobis omnia.

** Genesis 9:4

Excepto, quod carnem cum sanguine non comedetis.

** Genesis 9:5

Sanguinem enim animarum vestrarum requiram de manu cunctarum bestiarum : et de manu hominis, de manu viri, et fratris ejus requiram animam hominis.

** Genesis 9:6

Quicumque effuderit humanum sanguinem, fundetur sanguis illius : ad imaginem quippe Dei factus est homo.

** Genesis 9:7

Vos autem crescite et multiplicamini, et ingredimini super terram, et implete eam.  

** Genesis 9:8

Hæc quoque dixit Deus ad Noë, et ad filios ejus cum eo :

** Genesis 9:9

Ecce ego statuam pactum meum vobiscum, et cum semine vestro post vos :

** Genesis 9:10

et ad omnem animam viventem, quæ est vobiscum, tam in volucribus quam in jumentis et pecudibus terræ cunctis, quæ egressa sunt de arca, et universis bestiis terræ.

** Genesis 9:11

Statuam pactum meum vobiscum, et nequaquam ultra interficietur omnis caro aquis diluvii, neque erit deinceps diluvium dissipans terram.

** Genesis 9:12

Dixitque Deus : Hoc signum fœderis quod do inter me et vos, et ad omnem animam viventem, quæ est vobiscum in generationes sempiternas :

** Genesis 9:13

arcum meum ponam in nubibus, et erit signum fœderis inter me et inter terram.

** Genesis 9:14

Cumque obduxero nubibus cælum, apparebit arcus meus in nubibus :

** Genesis 9:15

et recordabor fœderis mei vobiscum, et cum omni anima vivente quæ carnem vegetat : et non erunt ultra aquæ diluvii ad delendum universam carnem.

** Genesis 9:16

Eritque arcus in nubibus, et videbo illum, et recordabor fœderis sempiterni quod pactum est inter Deum et omnem animam viventem universæ carnis quæ est super terram.

** Genesis 9:17

Dixitque Deus ad Noë : Hoc erit signum fœderis, quod constitui inter me et omnem carnem super terram.  

** Genesis 9:18

Erant ergo filii Noë, qui egressi sunt de arca, Sem, Cham et Japheth : porro Cham ipse est pater Chanaan.

** Genesis 9:19

Tres isti filii sunt Noë : et ab his disseminatum est omne genus hominum super universam terram.

** Genesis 9:20

Cœpitque Noë vir agricola exercere terram, et plantavit vineam.

** Genesis 9:21

Bibensque vinum inebriatus est, et nudatus in tabernaculo suo.

** Genesis 9:22

Quod cum vidisset Cham, pater Chanaan, verenda scilicet patris sui esse nudata, nuntiavit duobus fratribus suis foras.

** Genesis 9:23

At vero Sem et Japheth pallium imposuerunt humeris suis, et incedentes retrorsum, operuerunt verenda patris sui : faciesque eorum aversæ erant, et patris virilia non viderunt.

** Genesis 9:24

Evigilans autem Noë ex vino, cum didicisset quæ fecerat ei filius suus minor,

** Genesis 9:25

ait :   Maledictus Chanaan,  servus servorum erit fratribus suis.

** Genesis 9:26

Dixitque :  Benedictus Dominus Deus Sem,  sit Chanaan servus ejus. 

** Genesis 9:27

Dilatet Deus Japheth, et habitet in tabernaculis Sem,  sitque Chanaan servus ejus.

** Genesis 9:28

Vixit autem Noë post diluvium trecentis quinquaginta annis.

** Genesis 9:29

Et impleti sunt omnes dies ejus nongentorum quinquaginta annorum : et mortuus est.  

* Genesis 10

** Genesis 10:1

Hæ sunt generationes filiorum Noë, Sem, Cham et Japheth : natique sunt eis filii post diluvium.

** Genesis 10:2

Filii Japheth : Gomer, et Magog, et Madai, et Javan, et Thubal, et Mosoch, et Thiras.

** Genesis 10:3

Porro filii Gomer : Ascenez et Riphath et Thogorma.

** Genesis 10:4

Filii autem Javan : Elisa et Tharsis, Cetthim et Dodanim.

** Genesis 10:5

Ab his divisæ sunt insulæ gentium in regionibus suis, unusquisque secundum linguam suam et familias suas in nationibus suis.  

** Genesis 10:6

Filii autem Cham : Chus, et Mesraim, et Phuth, et Chanaan.

** Genesis 10:7

Filii Chus : Saba, et Hevila, et Sabatha, et Regma, et Sabatacha. Filii Regma : Saba et Dadan.

** Genesis 10:8

Porro Chus genuit Nemrod : ipse cœpit esse potens in terra,

** Genesis 10:9

et erat robustus venator coram Domino. Ob hoc exivit proverbium : Quasi Nemrod robustus venator coram Domino.

** Genesis 10:10

Fuit autem principium regni ejus Babylon, et Arach et Achad, et Chalanne, in terra Sennaar.

** Genesis 10:11

De terra illa egressus est Assur, et ædificavit Niniven, et plateas civitatis, et Chale.

** Genesis 10:12

Resen quoque inter Niniven et Chale : hæc est civitas magna.

** Genesis 10:13

At vero Mesraim genuit Ludim, et Anamim et Laabim, Nephthuim,

** Genesis 10:14

et Phetrusim, et Chasluim : de quibus egressi sunt Philisthiim et Caphtorim.

** Genesis 10:15

Chanaan autem genuit Sidonem primogenitum suum. Hethæum,

** Genesis 10:16

et Jebusæum, et Amorrhæum, Gergesæum,

** Genesis 10:17

Hevæum, et Aracæum : Sinæum,

** Genesis 10:18

et Aradium, Samaræum, et Amathæum : et post hæc disseminati sunt populi Chananæorum.

** Genesis 10:19

Factique sunt termini Chanaan venientibus a Sidone Geraram usque Gazam, donec ingrediaris Sodomam et Gomorrham, et Adamam, et Seboim usque Lesa.

** Genesis 10:20

Hi sunt filii Cham in cognationibus, et linguis, et generationibus, terrisque et gentibus suis.  

** Genesis 10:21

De Sem quoque nati sunt, patre omnium filiorum Heber, fratre Japheth majore.

** Genesis 10:22

Filii Sem : Ælam, et Assur, et Arphaxad, et Lud, et Aram.

** Genesis 10:23

Filii Aram : Us, et Hul, et Gether, et Mes.

** Genesis 10:24

At vero Arphaxad genuit Sale, de quo ortus est Heber.

** Genesis 10:25

Natique sunt Heber filii duo : nomen uni Phaleg, eo quod in diebus ejus divisa sit terra : et nomen fratris ejus Jectan.

** Genesis 10:26

Qui Jectan genuit Elmodad, et Saleph, et Asarmoth, Jare,

** Genesis 10:27

et Aduram, et Uzal, et Decla,

** Genesis 10:28

et Ebal, et Abimaël, Saba,

** Genesis 10:29

et Ophir, et Hevila, et Jobab : omnes isti, filii Jectan.

** Genesis 10:30

Et facta est habitatio eorum de Messa pergentibus usque Sephar montem orientalem.

** Genesis 10:31

Isti filii Sem secundum cognationes, et linguas, et regiones in gentibus suis.

** Genesis 10:32

Hæ familiæ Noë juxta populos et nationes suas. Ab his divisæ sunt gentes in terra post diluvium.   

* Genesis 11

** Genesis 11:1

Erat autem terra labii unius, et sermonum eorumdem.

** Genesis 11:2

Cumque proficiscerentur de oriente, invenerunt campum in terra Sennaar, et habitaverunt in eo.

** Genesis 11:3

Dixitque alter ad proximum suum : Venite, faciamus lateres, et coquamus eos igni. Habueruntque lateres pro saxis, et bitumen pro cæmento :

** Genesis 11:4

et dixerunt : Venite, faciamus nobis civitatem et turrim, cujus culmen pertingat ad cælum : et celebremus nomen nostrum antequam dividamur in universas terras.

** Genesis 11:5

Descendit autem Dominus ut videret civitatem et turrim, quam ædificabant filii Adam,

** Genesis 11:6

et dixit : Ecce, unus est populus, et unum labium omnibus : cœperuntque hoc facere, nec desistent a cogitationibus suis, donec eas opere compleant.

** Genesis 11:7

Venite igitur, descendamus, et confundamus ibi linguam eorum, ut non audiat unusquisque vocem proximi sui.

** Genesis 11:8

Atque ita divisit eos Dominus ex illo loco in universas terras, et cessaverunt ædificare civitatem.

** Genesis 11:9

Et idcirco vocatum est nomen ejus Babel, quia ibi confusum est labium universæ terræ : et inde dispersit eos Dominus super faciem cunctarum regionum.  

** Genesis 11:10

Hæ sunt generationes Sem : Sem erat centum annorum quando genuit Arphaxad, biennio post diluvium.

** Genesis 11:11

Vixitque Sem, postquam genuit Arphaxad, quingentis annis : et genuit filios et filias.

** Genesis 11:12

Porro Arphaxad vixit triginta quinque annis, et genuit Sale.

** Genesis 11:13

Vixitque Arphaxad, postquam genuit Sale, trecentis tribus annis : et genuit filios et filias.

** Genesis 11:14

Sale quoque vixit triginta annis, et genuit Heber.

** Genesis 11:15

Vixitque Sale, postquam genuit Heber, quadringentis tribus annis : et genuit filios et filias.

** Genesis 11:16

Vixit autem Heber triginta quatuor annis, et genuit Phaleg.

** Genesis 11:17

Et vixit Heber postquam genuit Phaleg, quadringentis triginta annis : et genuit filios et filias.

** Genesis 11:18

Vixit quoque Phaleg triginta annis, et genuit Reu.

** Genesis 11:19

Vixitque Phaleg, postquam genuit Reu, ducentis novem annis : et genuit filios et filias.

** Genesis 11:20

Vixit autem Reu triginta duobus annis, et genuit Sarug.

** Genesis 11:21

Vixit quoque Reu, postquam genuit Sarug, ducentis septem annis : et genuit filios et filias.

** Genesis 11:22

Vixit vero Sarug triginta annis, et genuit Nachor.

** Genesis 11:23

Vixitque Sarug, postquam genuit Nachor, ducentis annis : et genuit filios et filias.

** Genesis 11:24

Vixit autem Nachor viginti novem annis, et genuit Thare.

** Genesis 11:25

Vixitque Nachor, postquam genuit Thare, centum decem et novem annis : et genuit filios et filias.

** Genesis 11:26

Vixitque Thare septuaginta annis, et genuit Abram, et Nachor, et Aran.  

** Genesis 11:27

Hæ sunt autem generationes Thare : Thare genuit Abram, Nachor et Aran. Porro Aran genuit Lot.

** Genesis 11:28

Mortuusque est Aran ante Thare patrem suum, in terra nativitatis suæ, in Ur Chaldæorum.

** Genesis 11:29

Duxerunt autem Abram et Nachor uxores : nomen uxoris Abram, Sarai : et nomen uxoris Nachor, Melcha filia Aran, patris Melchæ, et patris Jeschæ.

** Genesis 11:30

Erat autem Sarai sterilis, nec habebat liberos.

** Genesis 11:31

Tulit itaque Thare Abram filium suum, et Lot filium Aran, filium filii sui, et Sarai nurum suam, uxorem Abram filii sui, et eduxit eos de Ur Chaldæorum, ut irent in terram Chanaan : veneruntque usque Haran, et habitaverunt ibi.

** Genesis 11:32

Et facti sunt dies Thare ducentorum quinque annorum, et mortuus est in Haran.   

* Genesis 12

** Genesis 12:1

Dixit autem Dominus ad Abram : Egredere de terra tua, et de cognatione tua, et de domo patris tui, et veni in terram quam monstrabo tibi.

** Genesis 12:2

Faciamque te in gentem magnam, et benedicam tibi, et magnificabo nomen tuum, erisque benedictus.

** Genesis 12:3

Benedicam benedicentibus tibi, et maledicam maledicentibus tibi, atque in te benedicentur universæ cognationes terræ.

** Genesis 12:4

Egressus est itaque Abram sicut præceperat ei Dominus, et ivit cum eo Lot : septuaginta quinque annorum erat Abram cum egrederetur de Haran.

** Genesis 12:5

Tulitque Sarai uxorem suam, et Lot filium fratris sui, universamque substantiam quam possederant, et animas quas fecerant in Haran : et egressi sunt ut irent in terram Chanaan. Cumque venissent in eam,

** Genesis 12:6

pertransivit Abram terram usque ad locum Sichem, usque ad convallem illustrem : Chananæus autem tunc erat in terra.

** Genesis 12:7

Apparuit autem Dominus Abram, et dixit ei : Semini tuo dabo terram hanc. Qui ædificavit ibi altare Domino, qui apparuerat ei.

** Genesis 12:8

Et inde transgrediens ad montem, qui erat contra orientem Bethel, tetendit ibi tabernaculum suum, ab occidente habens Bethel, et ab oriente Hai : ædificavit quoque ibi altare Domino, et invocavit nomen ejus.

** Genesis 12:9

Perrexitque Abram vadens, et ultra progrediens ad meridiem.  

** Genesis 12:10

Facta est autem fames in terra : descenditque Abram in Ægyptum, ut peregrinaretur ibi : prævaluerat enim fames in terra.

** Genesis 12:11

Cumque prope esset ut ingrederetur Ægyptum, dixit Sarai uxori suæ : Novi quod pulchra sis mulier :

** Genesis 12:12

et quod cum viderint te Ægyptii, dicturi sunt : Uxor ipsius est : et interficient me, et te reservabunt.

** Genesis 12:13

Dic ergo, obsecro te, quod soror mea sis : ut bene sit mihi propter te, et vivat anima mea ob gratiam tui.

** Genesis 12:14

Cum itaque ingressus esset Abram Ægyptum, viderunt Ægyptii mulierem quod esset pulchra nimis.

** Genesis 12:15

Et nuntiaverunt principes Pharaoni, et laudaverunt eam apud illum : et sublata est mulier in domum Pharaonis.

** Genesis 12:16

Abram vero bene usi sunt propter illam : fueruntque ei oves et boves et asini, et servi et famulæ, et asinæ et cameli.

** Genesis 12:17

Flagellavit autem Dominus Pharaonem plagis maximis, et domum ejus, propter Sarai uxorem Abram.

** Genesis 12:18

Vocavitque Pharao Abram, et dixit ei : Quidnam est hoc quod fecisti mihi ? quare non indicasti quod uxor tua esset ?

** Genesis 12:19

quam ob causam dixisti esse sororem tuam, ut tollerem eam mihi in uxorem ? Nunc igitur ecce conjux tua, accipe eam, et vade.

** Genesis 12:20

Præcepitque Pharao super Abram viris : et deduxerunt eum, et uxorem illius, et omnia quæ habebat.   

* Genesis 13

** Genesis 13:1

Ascendit ergo Abram de Ægypto, ipse et uxor ejus, et omnia quæ habebat, et Lot cum eo, ad australem plagam.

** Genesis 13:2

Erat autem dives valde in possessione auri et argenti.

** Genesis 13:3

Reversusque est per iter, quo venerat, a meridie in Bethel, usque ad locum ubi prius fixerat tabernaculum inter Bethel et Hai,

** Genesis 13:4

in loco altaris quod fecerat prius : et invocavit ibi nomen Domini.

** Genesis 13:5

Sed et Lot qui erat cum Abram, fuerunt greges ovium, et armenta, et tabernacula.

** Genesis 13:6

Nec poterat eos capere terra, ut habitarent simul : erat quippe substantia eorum multa, et nequibant habitare communiter.

** Genesis 13:7

Unde et facta est rixa inter pastores gregum Abram et Lot. Eo autem tempore Chananæus et Pherezæus habitabant in terra illa.

** Genesis 13:8

Dixit ergo Abram ad Lot : Ne quæso sit jurgium inter me et te, et inter pastores meos et pastores tuos : fratres enim sumus.

** Genesis 13:9

Ecce universa terra coram te est : recede a me, obsecro : si ad sinistram ieris, ego dexteram tenebo : si tu dexteram elegeris, ego ad sinistram pergam.

** Genesis 13:10

Elevatis itaque Lot oculis, vidit omnem circa regionem Jordanis, quæ universa irrigabatur antequam subverteret Dominus Sodomam et Gomorrham, sicut paradisus Domini, et sicut Ægyptus venientibus in Segor.

** Genesis 13:11

Elegitque sibi Lot regionem circa Jordanem, et recessit ab oriente : divisique sunt alterutrum a fratre suo.

** Genesis 13:12

Abram habitavit in terra Chanaan ; Lot vero moratus est in oppidis, quæ erant circa Jordanem, et habitavit in Sodomis.

** Genesis 13:13

Homines autem Sodomitæ pessimi erant, et peccatores coram Domino nimis.  

** Genesis 13:14

Dixitque Dominus ad Abram, postquam divisus est ab eo Lot : Leva oculos tuos et vide a loco, in quo nunc es, ad aquilonem et meridiem, ad orientem et occidentem.

** Genesis 13:15

Omnem terram, quam conspicis, tibi dabo, et semini tuo usque in sempiternum.

** Genesis 13:16

Faciamque semen tuum sicut pulverem terræ : si quis potest hominum numerare pulverem terræ, semen quoque tuum numerare poterit.

** Genesis 13:17

Surge, et perambula terram in longitudine et in latitudine sua : quia tibi daturus sum eam.

** Genesis 13:18

Movens igitur tabernaculum suum Abram, venit, et habitavit juxta convallem Mambre, quæ est in Hebron : ædificavitque ibi altare Domino.   

* Genesis 14

** Genesis 14:1

Factum est autem in illo tempore, ut Amraphel rex Sennaar, et Arioch rex Ponti, et Chodorlahomor rex Elamitarum, et Thadal rex gentium

** Genesis 14:2

inirent bellum contra Bara regem Sodomorum, et contra Bersa regem Gomorrhæ, et contra Sennaab regem Adamæ, et contra Semeber regem Seboim, contraque regem Balæ, ipsa est Segor.

** Genesis 14:3

Omnes hi convenerunt in vallem Silvestrem, quæ nunc est mare salis.

** Genesis 14:4

Duodecim enim annis servierunt Chodorlahomor, et tertiodecimo anno recesserunt ab eo.

** Genesis 14:5

Igitur quartodecimo anno venit Chodorlahomor, et reges qui erant cum eo : percusseruntque Raphaim in Astarothcarnaim, et Zuzim cum eis, et Emim in Save Cariathaim,

** Genesis 14:6

et Chorræos in montibus Seir, usque ad Campestria Pharan, quæ est in solitudine.

** Genesis 14:7

Reversique sunt, et venerunt ad fontem Misphat, ipsa est Cades : et percusserunt omnem regionem Amalecitarum, et Amorrhæum, qui habitabat in Asasonthamar.

** Genesis 14:8

Et egressi sunt rex Sodomorum, et rex Gomorrhæ, rexque Adamæ, et rex Seboim, necnon et rex Balæ, quæ est Segor : et direxerunt aciem contra eos in valle Silvestri :

** Genesis 14:9

scilicet adversus Chodorlahomor regem Elamitarum, et Thadal regem Gentium, et Amraphel regem Sennaar, et Arioch regem Ponti : quatuor reges adversus quinque.

** Genesis 14:10

Vallis autem Silvestris habebat puteos multos bituminis. Itaque rex Sodomorum, et Gomorrhæ, terga verterunt, cecideruntque ibi : et qui remanserant, fugerunt ad montem.

** Genesis 14:11

Tulerunt autem omnem substantiam Sodomorum et Gomorrhæ, et universa quæ ad cibum pertinent, et abierunt :

** Genesis 14:12

necnon et Lot, et substantiam ejus, filium fratris Abram, qui habitabat in Sodomis.  

** Genesis 14:13

Et ecce unus, qui evaserat, nuntiavit Abram Hebræo, qui habitabat in convalle Mambre Amorrhæi, fratris Escol, et fratris Aner : hi enim pepigerant fœdus cum Abram.

** Genesis 14:14

Quod cum audisset Abram, captum videlicet Lot fratrem suum, numeravit expeditos vernaculos suos trecentos decem et octo : et persecutus est usque Dan.

** Genesis 14:15

Et divisis sociis, irruit super eos nocte : percussitque eos, et persecutus est eos usque Hoba, quæ est ad lævam Damasci.

** Genesis 14:16

Reduxitque omnem substantiam, et Lot fratrem suum cum substantia illius, mulieres quoque et populum.

** Genesis 14:17

Egressus est autem rex Sodomorum in occursum ejus postquam reversus est a cæde Chodorlahomor, et regum qui cum eo erant in valle Save, quæ est vallis regis.  

** Genesis 14:18

At vero Melchisedech rex Salem, proferens panem et vinum, erat enim sacerdos Dei altissimi,

** Genesis 14:19

benedixit ei, et ait : Benedictus Abram Deo excelso, qui creavit cælum et terram :

** Genesis 14:20

et benedictus Deus excelsus, quo protegente, hostes in manibus tuis sunt. Et dedit ei decimas ex omnibus.

** Genesis 14:21

Dixit autem rex Sodomorum ad Abram : Da mihi animas, cetera tolle tibi.

** Genesis 14:22

Qui respondit ei : Levo manum meam ad Dominum Deum excelsum possessorem cæli et terræ,

** Genesis 14:23

quod a filo subtegminis usque ad corigiam caligæ, non accipiam ex omnibus quæ tua sunt, ne dicas : Ego ditavi Abram :

** Genesis 14:24

exceptis his, quæ comederunt juvenes, et partibus virorum, qui venerunt mecum, Aner, Escol et Mambre : isti accipient partes suas.   

* Genesis 15

** Genesis 15:1

His itaque transactis, factus est sermo Domini ad Abram per visionem dicens : Noli timere, Abram : ego protector tuus sum, et merces tua magna nimis.

** Genesis 15:2

Dixitque Abram : Domine Deus, quid dabis mihi ? ego vadam absque liberis, et filius procuratoris domus meæ iste Damascus Eliezer.

** Genesis 15:3

Addiditque Abram : Mihi autem non dedisti semen, et ecce vernaculus meus, hæres meus erit.

** Genesis 15:4

Statimque sermo Domini factus est ad eum, dicens : Non erit hic hæres tuus, sed qui egredietur de utero tuo, ipsum habebis hæredem.

** Genesis 15:5

Eduxitque eum foras, et ait illi : Suspice cælum, et numera stellas, si potes. Et dixit ei : Sic erit semen tuum.

** Genesis 15:6

Credidit Abram Deo, et reputatum est illi ad justitiam.

** Genesis 15:7

Dixitque ad eum : Ego Dominus qui eduxi te de Ur Chaldæorum ut darem tibi terram istam, et possideres eam.

** Genesis 15:8

At ille ait : Domine Deus, unde scire possum quod possessurus sim eam ?

** Genesis 15:9

Et respondens Dominus : Sume, inquit, mihi vaccam triennem, et capram trimam, et arietem annorum trium, turturem quoque et columbam.

** Genesis 15:10

Qui tollens universa hæc, divisit ea per medium, et utrasque partes contra se altrinsecus posuit ; aves autem non divisit.

** Genesis 15:11

Descenderuntque volucres super cadavera, et abigebat eas Abram.

** Genesis 15:12

Cumque sol occumberet, sopor irruit super Abram, et horror magnus et tenebrosus invasit eum.

** Genesis 15:13

Dictumque est ad eum : Scito prænoscens quod peregrinum futurum sit semen tuum in terra non sua, et subjicient eos servituti, et affligent quadringentis annis.

** Genesis 15:14

Verumtamen gentem, cui servituri sunt, ego judicabo : et post hæc egredientur cum magna substantia.

** Genesis 15:15

Tu autem ibis ad patres tuos in pace, sepultus in senectute bona.

** Genesis 15:16

Generatione autem quarta revertentur huc : necdum enim completæ sunt iniquitates Amorrhæorum usque ad præsens tempus.

** Genesis 15:17

Cum ergo occubuisset sol, facta est caligo tenebrosa, et apparuit clibanus fumans, et lampas ignis transiens inter divisiones illas.

** Genesis 15:18

In illo die pepigit Dominus fœdus cum Abram, dicens : Semini tuo dabo terram hanc a fluvio Ægypti usque ad fluvium magnum Euphraten,

** Genesis 15:19

Cinæos, et Cenezæos, Cedmonæos,

** Genesis 15:20

et Hethæos, et Pherezæos, Raphaim quoque,

** Genesis 15:21

et Amorrhæos, et Chananæos, et Gergesæos, et Jebusæos.   

* Genesis 16

** Genesis 16:1

Igitur Sarai, uxor Abram, non genuerat liberos : sed habens ancillam ægyptiam nomine Agar,

** Genesis 16:2

dixit marito suo : Ecce, conclusit me Dominus, ne parerem. Ingredere ad ancillam meam, si forte saltem ex illa suscipiam filios. Cumque ille acquiesceret deprecanti,

** Genesis 16:3

tulit Agar ægyptiam ancillam suam post annos decem quam habitare cœperant in terra Chanaan : et dedit eam viro suo uxorem.

** Genesis 16:4

Qui ingressus est ad eam. At illa concepisse se videns, despexit dominam suam.

** Genesis 16:5

Dixitque Sarai ad Abram : Inique agis contra me : ego dedi ancillam meam in sinum tuum, quæ videns quod conceperit, despectui me habet : judicet Dominus inter me et te.

** Genesis 16:6

Cui respondens Abram : Ecce, ait, ancilla tua in manu tua est, utere ea ut libet. Affligente igitur eam Sarai, fugam iniit.

** Genesis 16:7

Cumque invenisset eam angelus Domini juxta fontem aquæ in solitudine, qui est in via Sur in deserto,

** Genesis 16:8

dixit ad illam : Agar ancilla Sarai, unde venis ? et quo vadis ? Quæ respondit : A facie Sarai dominæ meæ ego fugio.

** Genesis 16:9

Dixitque ei angelus Domini : Revertere ad dominam tuam, et humiliare sub manu illius.

** Genesis 16:10

Et rursum : Multiplicans, inquit, multiplicabo semen tuum, et non numerabitur præ multitudine.

** Genesis 16:11

Ac deinceps : Ecce, ait, concepisti, et paries filium : vocabisque nomen ejus Ismaël, eo quod audierit Dominus afflictionem tuam.

** Genesis 16:12

Hic erit ferus homo : manus ejus contra omnes, et manus omnium contra eum : et e regione universorum fratrum suorum figet tabernacula.

** Genesis 16:13

Vocavit autem nomen Domini qui loquebatur ad eam : Tu Deus qui vidisti me. Dixit enim : Profecto hic vidi posteriora videntis me.

** Genesis 16:14

Propterea appellavit puteum illum Puteum viventis et videntis me. Ipse est inter Cades et Barad.

** Genesis 16:15

Peperitque Agar Abræ filium : qui vocavit nomen ejus Ismaël.

** Genesis 16:16

Octoginta et sex annorum erat Abram quando peperit ei Agar Ismaëlem.   

* Genesis 17

** Genesis 17:1

Postquam vero nonaginta et novem annorum esse cœperat, apparuit ei Dominus, dixitque ad eum : Ego Deus omnipotens : ambula coram me, et esto perfectus.

** Genesis 17:2

Ponamque fœdus meum inter me et te, et multiplicabo te vehementer nimis.

** Genesis 17:3

Cecidit Abram pronus in faciem.

** Genesis 17:4

Dixitque ei Deus : Ego sum, et pactum meum tecum, erisque pater multarum gentium.

** Genesis 17:5

Nec ultra vocabitur nomen tuum Abram, sed appellaberis Abraham : quia patrem multarum gentium constitui te.

** Genesis 17:6

Faciamque te crescere vehementissime, et ponam te in gentibus, regesque ex te egredientur.

** Genesis 17:7

Et statuam pactum meum inter me et te, et inter semen tuum post te in generationibus suis, fœdere sempiterno : ut sim Deus tuus, et seminis tui post te.

** Genesis 17:8

Daboque tibi et semini tuo terram peregrinationis tuæ, omnem terram Chanaan in possessionem æternam, eroque Deus eorum.  

** Genesis 17:9

Dixit iterum Deus ad Abraham : Et tu ergo custodies pactum meum, et semen tuum post te in generationibus suis.

** Genesis 17:10

Hoc est pactum meum quod observabitis inter me et vos, et semen tuum post te : circumcidetur ex vobis omne masculinum :

** Genesis 17:11

et circumcidetis carnem præputii vestri, ut sit in signum fœderis inter me et vos.

** Genesis 17:12

Infans octo dierum circumcidetur in vobis, omne masculinum in generationibus vestris : tam vernaculus, quam emptitius circumcidetur, et quicumque non fuerit de stirpe vestra :

** Genesis 17:13

eritque pactum meum in carne vestra in fœdus æternum.

** Genesis 17:14

Masculus, cujus præputii caro circumcisa non fuerit, delebitur anima illa de populo suo : quia pactum meum irritum fecit.  

** Genesis 17:15

Dixit quoque Deus ad Abraham : Sarai uxorem tuam non vocabis Sarai, sed Saram.

** Genesis 17:16

Et benedicam ei, et ex illa dabo tibi filium cui benedicturus sum : eritque in nationes, et reges populorum orientur ex eo.

** Genesis 17:17

Cecidit Abraham in faciem suam, et risit, dicens in corde suo : Putasne centenario nascetur filius ? et Sara nonagenaria pariet ?

** Genesis 17:18

Dixitque ad Deum : Utinam Ismaël vivat coram te.

** Genesis 17:19

Et ait Deus ad Abraham : Sara uxor tua pariet tibi filium, vocabisque nomen ejus Isaac, et constituam pactum meum illi in fœdus sempiternum, et semini ejus post eum.

** Genesis 17:20

Super Ismaël quoque exaudivi te : ecce, benedicam ei, et augebo, et multiplicabo eum valde : duodecim duces generabit, et faciam illum in gentem magnam.

** Genesis 17:21

Pactum vero meum statuam ad Isaac, quem pariet tibi Sara tempore isto in anno altero.

** Genesis 17:22

Cumque finitus esset sermo loquentis cum eo, ascendit Deus ab Abraham.  

** Genesis 17:23

Tulit autem Abraham Ismaël filium suum, et omnes vernaculos domus suæ, universosque quos emerat, cunctos mares ex omnibus viris domus suæ : et circumcidit carnem præputii eorum statim in ipsa die, sicut præceperat ei Deus.

** Genesis 17:24

Abraham nonaginta et novem erat annorum quando circumcidit carnem præputii sui.

** Genesis 17:25

Et Ismaël filius tredecim annos impleverat tempore circumcisionis suæ.

** Genesis 17:26

Eadem die circumcisus est Abraham et Ismaël filius ejus :

** Genesis 17:27

et omnes viri domus illius, tam vernaculi, quam emptitii et alienigenæ pariter circumcisi sunt.   

* Genesis 18

** Genesis 18:1

Apparuit autem ei Dominus in convalle Mambre sedenti in ostio tabernaculi sui in ipso fervore diei.

** Genesis 18:2

Cumque elevasset oculos, apparuerunt ei tres viri stantes prope eum : quos cum vidisset, cucurrit in occursum eorum de ostio tabernaculi, et adoravit in terram.

** Genesis 18:3

Et dixit : Domine, si inveni gratiam in oculis tuis, ne transeas servum tuum :

** Genesis 18:4

sed afferam pauxillum aquæ, et lavate pedes vestros, et requiescite sub arbore.

** Genesis 18:5

Ponamque buccellam panis, et confortate cor vestrum : postea transibitis : idcirco enim declinastis ad servum vestrum. Qui dixerunt : Fac ut locutus es.

** Genesis 18:6

Festinavit Abraham in tabernaculum ad Saram, dixitque ei : Accelera, tria sata similæ commisce, et fac subcinericios panes.

** Genesis 18:7

Ipse vero ad armentum cucurrit, et tulit inde vitulum tenerrimum et optimum, deditque puero : qui festinavit et coxit illum.

** Genesis 18:8

Tulit quoque butyrum et lac, et vitulum quem coxerat, et posuit coram eis : ipse vero stabat juxta eos sub arbore.  

** Genesis 18:9

Cumque comedissent, dixerunt ad eum : Ubi est Sara uxor tua ? Ille respondit : Ecce in tabernaculo est.

** Genesis 18:10

Cui dixit : Revertens veniam ad te tempore isto, vita comite, et habebit filium Sara uxor tua. Quo audito, Sara risit post ostium tabernaculi.

** Genesis 18:11

Erant autem ambo senes, provectæque ætatis, et desierant Saræ fieri muliebria.

** Genesis 18:12

Quæ risit occulte dicens : Postquam consenui, et dominus meus vetulus est, voluptati operam dabo ?

** Genesis 18:13

Dixit autem Dominus ad Abraham : Quare risit Sara, dicens : Num vere paritura sum anus ?

** Genesis 18:14

Numquid Deo quidquam est difficile ? juxta condictum revertar ad te hoc eodem tempore, vita comite, et habebit Sara filium.

** Genesis 18:15

Negavit Sara, dicens : Non risi, timore perterrita. Dominus autem : Non est, inquit, ita : sed risisti.  

** Genesis 18:16

Cum ergo surrexissent inde viri, direxerunt oculos contra Sodomam : et Abraham simul gradiebatur, deducens eos.

** Genesis 18:17

Dixitque Dominus : Num celare potero Abraham quæ gesturus sum :

** Genesis 18:18

cum futurus sit in gentem magnam, ac robustissimam, et benedicendæ sint in illo omnes nationes terræ ?

** Genesis 18:19

Scio enim quod præcepturus sit filiis suis, et domui suæ post se ut custodiant viam Domini, et faciant judicium et justitiam : ut adducat Dominus propter Abraham omnia quæ locutus est ad eum.

** Genesis 18:20

Dixit itaque Dominus : Clamor Sodomorum et Gomorrhæ multiplicatus est, et peccatum eorum aggravatum est nimis.

** Genesis 18:21

Descendam, et videbo utrum clamorem qui venit ad me, opere compleverint ; an non est ita, ut sciam.

** Genesis 18:22

Converteruntque se inde, et abierunt Sodomam : Abraham vero adhuc stabat coram Domino.

** Genesis 18:23

Et appropinquans ait : Numquid perdes justum cum impio ?

** Genesis 18:24

si fuerint quinquaginta justi in civitate, peribunt simul ? et non parces loco illi propter quinquaginta justos, si fuerint in eo ?

** Genesis 18:25

Absit a te ut rem hanc facias, et occidas justum cum impio, fiatque justus sicut impius, non est hoc tuum : qui judicas omnem terram, nequaquam facies judicium hoc.

** Genesis 18:26

Dixitque Dominus ad eum : Si invenero Sodomis quinquaginta justos in medio civitatis, dimittam omni loco propter eos.

** Genesis 18:27

Respondensque Abraham, ait : Quia semel cœpi, loquar ad Dominum meum, cum sim pulvis et cinis.

** Genesis 18:28

Quid si minus quinquaginta justis quinque fuerint ? delebis, propter quadraginta quinque, universam urbem ? Et ait : Non delebo, si invenero ibi quadraginta quinque.

** Genesis 18:29

Rursumque locutus est ad eum : Sin autem quadraginta ibi inventi fuerint, quid facies ? Ait : Non percutiam propter quadraginta.

** Genesis 18:30

Ne quæso, inquit, indigneris, Domine, si loquar : quid si ibi inventi fuerint triginta ? Respondit : Non faciam, si invenero ibi triginta.

** Genesis 18:31

Quia semel, ait, cœpi loquar ad Dominum meum : quid si ibi inventi fuerint viginti ? Ait : Non interficiam propter viginti.

** Genesis 18:32

Obsecro, inquit, ne irascaris, Domine, si loquar adhuc semel : quid si inventi fuerint ibi decem ? Et dixit : Non delebo propter decem.

** Genesis 18:33

Abiitque Dominus, postquam cessavit loqui ad Abraham : et ille reversus est in locum suum.   

* Genesis 19

** Genesis 19:1

Veneruntque duo angeli Sodomam vespere, et sedente Lot in foribus civitatis. Qui cum vidisset eos, surrexit, et ivit obviam eis : adoravitque pronus in terram,

** Genesis 19:2

et dixit : Obsecro, domini, declinate in domum pueri vestri, et manete ibi : lavate pedes vestros, et mane proficiscemini in viam vestram. Qui dixerunt : Minime, sed in platea manebimus.

** Genesis 19:3

Compulit illos oppido ut diverterent ad eum : ingressisque domum illius fecit convivium, et coxit azyma, et comederunt.

** Genesis 19:4

Prius autem quam irent cubitum, viri civitatis vallaverunt domum a puero usque ad senem, omnis populus simul.

** Genesis 19:5

Vocaveruntque Lot, et dixerunt ei : Ubi sunt viri qui introierunt ad te nocte ? educ illos huc, ut cognoscamus eos.

** Genesis 19:6

Egressus ad eos Lot, post tergum occludens ostium, ait :

** Genesis 19:7

Nolite, quæso, fratres mei, nolite malum hoc facere.

** Genesis 19:8

Habeo duas filias, quæ necdum cognoverunt virum : educam eas ad vos, et abutimini eis sicut vobis placuerit, dummodo viris istis nihil mali faciatis, quia ingressi sunt sub umbra culminis mei.

** Genesis 19:9

At illi dixerunt : Recede illuc. Et rursus : Ingressus es, inquiunt, ut advena ; numquid ut judices ? te ergo ipsum magis quam hos affligemus. Vimque faciebant Lot vehementissime : jamque prope erat ut effringerent fores.

** Genesis 19:10

Et ecce miserunt manum viri, et introduxerunt ad se Lot, clauseruntque ostium :

** Genesis 19:11

et eos, qui foris erant, percusserunt cæcitate a minimo usque ad maximum, ita ut ostium invenire non possent.

** Genesis 19:12

Dixerunt autem ad Lot : Habes hic quempiam tuorum ? generum, aut filios, aut filias, omnes, qui tui sunt, educ de urbe hac :

** Genesis 19:13

delebimus enim locum istum, eo quod increverit clamor eorum coram Domino, qui misit nos ut perdamus illos.

** Genesis 19:14

Egressus itaque Lot, locutus est ad generos suos qui accepturi erant filias ejus, et dixit : Surgite, egredimini de loco isto : quia delebit Dominus civitatem hanc. Et visus est eis quasi ludens loqui.  

** Genesis 19:15

Cumque esset mane, cogebant eum angeli, dicentes : Surge, tolle uxorem tuam, et duas filias quas habes : ne et tu pariter pereas in scelere civitatis.

** Genesis 19:16

Dissimulante illo, apprehenderunt manum ejus, et manum uxoris, ac duarum filiarum ejus, eo quod parceret Dominus illi.

** Genesis 19:17

Eduxeruntque eum, et posuerunt extra civitatem : ibique locuti sunt ad eum, dicentes : Salva animam tuam : noli respicere post tergum, nec stes in omni circa regione : sed in monte salvum te fac, ne et tu simul pereas.

** Genesis 19:18

Dixitque Lot ad eos : Quæso, domine mi,

** Genesis 19:19

quia invenit servus tuus gratiam coram te, et magnificasti misericordiam tuam quam fecisti mecum, ut salvares animam meam, nec possum in monte salvari, ne forte apprehendat me malum, et moriar :

** Genesis 19:20

est civitas hæc juxta, ad quam possum fugere, parva, et salvabor in ea : numquid non modica est, et vivet anima mea ?

** Genesis 19:21

Dixitque ad eum : Ecce etiam in hoc suscepi preces tuas, ut non subvertam urbem pro qua locutus es.

** Genesis 19:22

Festina, et salvare ibi : quia non potero facere quidquam donec ingrediaris illuc. Idcirco vocatum est nomen urbis illius Segor.

** Genesis 19:23

Sol egressus est super terram, et Lot ingressus est Segor.

** Genesis 19:24

Igitur Dominus pluit super Sodomam et Gomorrham sulphur et ignem a Domino de cælo :

** Genesis 19:25

et subvertit civitates has, et omnem circa regionem, universos habitatores urbium, et cuncta terræ virentia.

** Genesis 19:26

Respiciensque uxor ejus post se, versa est in statuam salis.

** Genesis 19:27

Abraham autem consurgens mane, ubi steterat prius cum Domino,

** Genesis 19:28

intuitus est Sodomam et Gomorrham, et universam terram regionis illius : viditque ascendentem favillam de terra quasi fornacis fumum.

** Genesis 19:29

Cum enim subverteret Deus civitates regionis illius, recordatus Abrahæ, liberavit Lot de subversione urbium in quibus habitaverat.  

** Genesis 19:30

Ascenditque Lot de Segor, et mansit in monte, duæ quoque filiæ ejus cum eo (timuerat enim manere in Segor) et mansit in spelunca ipse, et duæ filiæ ejus cum eo.

** Genesis 19:31

Dixitque major ad minorem : Pater noster senex est, et nullus virorum remansit in terra, qui possit ingredi ad nos juxta morem universæ terræ.

** Genesis 19:32

Veni, inebriemus eum vino, dormiamusque cum eo, ut servare possimus ex patre nostro semen.

** Genesis 19:33

Dederunt itaque patri suo bibere vinum nocte illa. Et ingressa est major, dormivitque cum patre ; at ille non sensit, nec quando accubuit filia, nec quando surrexit.

** Genesis 19:34

Altera quoque die dixit major ad minorem : Ecce dormivi heri cum patre meo, demus ei bibere vinum etiam hac nocte, et dormies cum eo, ut salvemus semen de patre nostro.

** Genesis 19:35

Dederunt etiam et illa nocte patri suo bibere vinum, ingressaque minor filia, dormivit cum eo : et ne tunc quidem sensit quando concubuerit, vel quando illa surrexerit.

** Genesis 19:36

Conceperunt ergo duæ filiæ Lot de patre suo.

** Genesis 19:37

Peperitque major filium, et vocavit nomen ejus Moab : ipse est pater Moabitarum usque in præsentem diem.

** Genesis 19:38

Minor quoque peperit filium, et vocavit nomen ejus Ammon, id est, Filius populi mei : ipse est pater Ammonitarum usque hodie.   

* Genesis 20

** Genesis 20:1

Profectus inde Abraham in terram australem, habitavit inter Cades et Sur : et peregrinatus est in Geraris.

** Genesis 20:2

Dixitque de Sara uxore suo : Soror mea est. Misit ergo Abimelech rex Geraræ, et tulit eam.

** Genesis 20:3

Venit autem Deus ad Abimelech per somnium nocte, et ait illi : En morieris propter mulierem quam tulisti : habet enim virum.

** Genesis 20:4

Abimelech vero non tetigerat eam, et ait : Domine, num gentem ignorantem et justam interficies ?

** Genesis 20:5

nonne ipse dixit mihi : Soror mea est : et ipsa ait : Frater meus est ? In simplicitate cordis mei, et munditia manuum mearum feci hoc.

** Genesis 20:6

Dixitque ad eum Deus : Et ego scio quod simplici corde feceris : et ideo custodivi te ne peccares in me, et non dimisi ut tangeres eam.

** Genesis 20:7

Nunc ergo redde viro suo uxorem, quia propheta est : et orabit pro te, et vives : si autem nolueris reddere, scito quod morte morieris tu, et omnia quæ tua sunt.

** Genesis 20:8

Statimque de nocte consurgens Abimelech, vocavit omnes servos suos : et locutus est universa verba hæc in auribus eorum, timueruntque omnes viri valde.

** Genesis 20:9

Vocavit autem Abimelech etiam Abraham, et dixit ei : Quid fecisti nobis ? quid peccavimus in te, quia induxisti super me et super regnum meum peccatum grande ? quæ non debuisti facere, fecisti nobis.

** Genesis 20:10

Rursumque expostulans, ait : Quid vidisti, ut hoc faceres ?

** Genesis 20:11

Respondit Abraham : Cogitavi mecum, dicens : Forsitan non est timor Dei in loco isto : et interficient me propter uxorem meam :

** Genesis 20:12

alias autem et vere soror mea est, filia patris mei, et non filia matris meæ, et duxi eam in uxorem.

** Genesis 20:13

Postquam autem eduxit me Deus de domo patris mei, dixi ad eam : Hanc misericordiam facies mecum : in omni loco, ad quem ingrediemur, dices quod frater tuus sim.

** Genesis 20:14

Tulit igitur Abimelech oves et boves, et servos et ancillas, et dedit Abraham : reddiditque illi Saram uxorem suam,

** Genesis 20:15

et ait : Terra coram vobis est, ubicumque tibi placuerit habita.

** Genesis 20:16

Saræ autem dixit : Ecce mille argenteos dedi fratri tuo, hoc erit tibi in velamen oculorum ad omnes qui tecum sunt, et quocumque perrexeris : mementoque te deprehensam.

** Genesis 20:17

Orante autem Abraham, sanavit Deus Abimelech et uxorem, ancillasque ejus, et pepererunt :

** Genesis 20:18

concluserat enim Dominus omnem vulvam domus Abimelech propter Saram uxorem Abrahæ.   

* Genesis 21

** Genesis 21:1

Visitavit autem Dominus Saram, sicut promiserat : et implevit quæ locutus est.

** Genesis 21:2

Concepitque et peperit filium in senectute sua, tempore quo prædixerat ei Deus.

** Genesis 21:3

Vocavitque Abraham nomen filii sui, quem genuit ei Sara, Isaac :

** Genesis 21:4

et circumcidit eum octavo die, sicut præceperat ei Deus,

** Genesis 21:5

cum centum esset annorum : hac quippe ætate patris, natus est Isaac.

** Genesis 21:6

Dixitque Sara : Risum fecit mihi Deus : quicumque audierit, corridebit mihi.

** Genesis 21:7

Rursumque ait : Quis auditurus crederet Abraham quod Sara lactaret filium, quem peperit ei jam seni ?

** Genesis 21:8

Crevit igitur puer, et ablactatus est : fecitque Abraham grande convivium in die ablactationis ejus.  

** Genesis 21:9

Cumque vidisset Sara filium Agar Ægyptiæ ludentem cum Isaac filio suo, dixit ad Abraham :

** Genesis 21:10

Ejice ancillam hanc, et filium ejus : non enim erit hæres filius ancillæ cum filio meo Isaac.

** Genesis 21:11

Dure accepit hoc Abraham pro filio suo.

** Genesis 21:12

Cui dixit Deus : Non tibi videatur asperum super puero, et super ancilla tua : omnia quæ dixerit tibi Sara, audi vocem ejus : quia in Isaac vocabitur tibi semen.

** Genesis 21:13

Sed et filium ancillæ faciam in gentem magnam, quia semen tuum est.

** Genesis 21:14

Surrexit itaque Abraham mane, et tollens panem et utrem aquæ, imposuit scapulæ ejus, tradiditque puerum, et dimisit eam. Quæ cum abiisset, errabat in solitudine Bersabee.

** Genesis 21:15

Cumque consumpta esset aqua in utre, abjecit puerum subter unam arborum, quæ ibi erant.

** Genesis 21:16

Et abiit, seditque e regione procul quantum potest arcus jacere : dixit enim : Non videbo morientem puerum : et sedens contra, levavit vocem suam et flevit.

** Genesis 21:17

Exaudivit autem Deus vocem pueri : vocavitque angelus Dei Agar de cælo, dicens : Quid agis Agar ? noli timere : exaudivit enim Deus vocem pueri de loco in quo est.

** Genesis 21:18

Surge, tolle puerum, et tene manum illius : quia in gentem magnam faciam eum.

** Genesis 21:19

Aperuitque oculos ejus Deus : quæ videns puteum aquæ, abiit, et implevit utrem, deditque puero bibere.

** Genesis 21:20

Et fuit cum eo : qui crevit, et moratus est in solitudine, factusque est juvenis sagittarius.

** Genesis 21:21

Habitavitque in deserto Pharan, et accepit illi mater sua uxorem de terra Ægypti.  

** Genesis 21:22

Eodem tempore dixit Abimelech, et Phicol princeps exercitus ejus, ad Abraham : Deus tecum est in universis quæ agis.

** Genesis 21:23

Jura ergo per Deum, ne noceas mihi, et posteris meis, stirpique meæ : sed juxta misericordiam, quam feci tibi, facies mihi, et terræ in qua versatus es advena.

** Genesis 21:24

Dixitque Abraham : Ego jurabo.

** Genesis 21:25

Et increpavit Abimelech propter puteum aquæ quem vi abstulerunt servi ejus.

** Genesis 21:26

Responditque Abimelech : Nescivi quis fecerit hanc rem : sed et tu non indicasti mihi, et ego non audivi præter hodie.

** Genesis 21:27

Tulit itaque Abraham oves et boves, et dedit Abimelech : percusseruntque ambo fœdus.

** Genesis 21:28

Et statuit Abraham septem agnas gregis seorsum.

** Genesis 21:29

Cui dixit Abimelech : Quid sibi volunt septem agnæ istæ, quas stare fecisti seorsum ?

** Genesis 21:30

At ille : Septem, inquit, agnas accipies de manu mea : ut sint mihi in testimonium, quoniam ego fodi puteum istum.

** Genesis 21:31

Idcirco vocatus est locus ille Bersabee : quia ibi uterque juravit.

** Genesis 21:32

Et inierunt fœdus pro puteo juramenti.

** Genesis 21:33

Surrexit autem Abimelech, et Phicol princeps exercitus ejus, reversique sunt in terram Palæstinorum. Abraham vero plantavit nemus in Bersabee, et invocavit ibi nomen Domini Dei æterni.

** Genesis 21:34

Et fuit colonus terræ Palæstinorum diebus multis.   

* Genesis 22

** Genesis 22:1

Quæ postquam gesta sunt, tentavit Deus Abraham, et dixit ad eum : Abraham, Abraham. At ille respondit : Adsum.

** Genesis 22:2

Ait illi : Tolle filium tuum unigenitum, quem diligis, Isaac, et vade in terram visionis, atque ibi offeres eum in holocaustum super unum montium quem monstravero tibi.

** Genesis 22:3

Igitur Abraham de nocte consurgens, stravit asinum suum, ducens secum duos juvenes, et Isaac filium suum : cumque concidisset ligna in holocaustum, abiit ad locum quem præceperat ei Deus.

** Genesis 22:4

Die autem tertio, elevatis oculis, vidit locum procul :

** Genesis 22:5

dixitque ad pueros suos : Expectate hic cum asino : ego et puer illuc usque properantes, postquam adoraverimus, revertemur ad vos.

** Genesis 22:6

Tulit quoque ligna holocausti, et imposuit super Isaac filium suum : ipse vero portabat in manibus ignem et gladium. Cumque duo pergerent simul,

** Genesis 22:7

dixit Isaac patri suo : Pater mi. At ille respondit : Quid vis, fili ? Ecce, inquit, ignis et ligna : ubi est victima holocausti ?

** Genesis 22:8

Dixit autem Abraham : Deus providebit sibi victimam holocausti, fili mi. Pergebant ergo pariter.

** Genesis 22:9

Et venerunt ad locum quem ostenderat ei Deus, in quo ædificavit altare, et desuper ligna composuit ; cumque alligasset Isaac filium suum, posuit eum in altare super struem lignorum.

** Genesis 22:10

Extenditque manum, et arripuit gladium, ut immolaret filium suum.

** Genesis 22:11

Et ecce angelus Domini de cælo clamavit, dicens : Abraham, Abraham. Qui respondit : Adsum.

** Genesis 22:12

Dixitque ei : Non extendas manum tuam super puerum, neque facias illi quidquam : nunc cognovi quod times Deum, et non pepercisti unigenito filio tuo propter me.

** Genesis 22:13

Levavit Abraham oculos suos, viditque post tergum arietem inter vepres hærentem cornibus, quem assumens obtulit holocaustum pro filio.

** Genesis 22:14

Appellavitque nomen loci illius, Dominus videt. Unde usque hodie dicitur : In monte Dominus videbit.  

** Genesis 22:15

Vocavit autem angelus Domini Abraham secundo de cælo, dicens :

** Genesis 22:16

Per memetipsum juravi, dicit Dominus : quia fecisti hanc rem, et non pepercisti filio tuo unigenito propter me :

** Genesis 22:17

benedicam tibi, et multiplicabo semen tuum sicut stellas cæli, et velut arenam quæ est in littore maris : possidebit semen tuum portas inimicorum suorum,

** Genesis 22:18

et benedicentur in semine tuo omnes gentes terræ, quia obedisti voci meæ.

** Genesis 22:19

Reversus est Abraham ad pueros suos, abieruntque Bersabee simul, et habitavit ibi.  

** Genesis 22:20

His ita gestis, nuntiatum est Abrahæ quod Melcha quoque genuisset filios Nachor fratri suo :

** Genesis 22:21

Hus primogenitum, et Buz fratrem ejus, et Camuel patrem Syrorum,

** Genesis 22:22

et Cased, et Azau, Pheldas quoque et Jedlaph,

** Genesis 22:23

ac Bathuel, de quo nata est Rebecca : octo istos genuit Melcha, Nachor fratri Abrahæ.

** Genesis 22:24

Concubina vero illius, nomine Roma, peperit Tabee, et Gaham, et Thahas, et Maacha.   

* Genesis 23

** Genesis 23:1

Vixit autem Sara centum viginti septem annis.

** Genesis 23:2

Et mortua est in civitate Arbee, quæ est Hebron, in terra Chanaan : venitque Abraham ut plangeret et fleret eam.

** Genesis 23:3

Cumque surrexisset ab officio funeris, locutus est ad filios Heth, dicens :

** Genesis 23:4

Advena sum et peregrinus apud vos : date mihi jus sepulchri vobiscum, ut sepeliam mortuum meum.

** Genesis 23:5

Responderunt filii Heth, dicentes :

** Genesis 23:6

Audi nos, domine : princeps Dei es apud nos : in electis sepulchris nostris sepeli mortuum tuum, nullusque te prohibere poterit quin in monumento ejus sepelias mortuum tuum.

** Genesis 23:7

Surrexit Abraham, et adoravit populum terræ, filios videlicet Heth :

** Genesis 23:8

dixitque ad eos : Si placet animæ vestræ ut sepeliam mortuum meum, audite me, et intercedite pro me apud Ephron filium Seor :

** Genesis 23:9

ut det mihi speluncam duplicem, quam habet in extrema parte agri sui : pecunia digna tradat eam mihi coram vobis in possessionem sepulchri.

** Genesis 23:10

Habitabat autem Ephron in medio filiorum Heth. Responditque Ephron ad Abraham, cunctis audientibus qui ingrediebantur portam civitatis illius, dicens :

** Genesis 23:11

Nequaquam ita fiat, domine mi, sed tu magis ausculta quod loquor. Agrum trado tibi, et speluncam quæ in eo est, præsentibus filiis populi mei ; sepeli mortuum tuum.

** Genesis 23:12

Adoravit Abraham coram populo terræ.

** Genesis 23:13

Et locutus est ad Ephron circumstante plebe : Quæso ut audias me : dabo pecuniam pro agro : suscipe eam, et sic sepeliam mortuum meum in eo.

** Genesis 23:14

Responditque Ephron :

** Genesis 23:15

Domine mi, audi me : terra, quam postulas, quadringentis siclis argenti valet : istud est pretium inter me et te : sed quantum est hoc ? sepeli mortuum tuum.

** Genesis 23:16

Quod cum audisset Abraham, appendit pecuniam, quam Ephron postulaverat, audientibus filiis Heth, quadringentos siclos argenti probatæ monetæ publicæ.

** Genesis 23:17

Confirmatusque est ager quondam Ephronis, in quo erat spelunca duplex, respiciens Mambre, tam ipse, quam spelunca, et omnes arbores ejus in cunctis terminis ejus per circuitum,

** Genesis 23:18

Abrahæ in possessionem, videntibus filiis Heth, et cunctis qui intrabant portam civitatis illius.

** Genesis 23:19

Atque ita sepelivit Abraham Saram uxorem suam in spelunca agri duplici, quæ respiciebat Mambre. Hæc est Hebron in terra Chanaan.

** Genesis 23:20

Et confirmatus est ager, et antrum quod erat in eo, Abrahæ in possessionem monumenti a filiis Heth.   

* Genesis 24

** Genesis 24:1

Erat autem Abraham senex, dierumque multorum : et Dominus in cunctis benedixerat ei.

** Genesis 24:2

Dixitque ad servum seniorem domus suæ, qui præerat omnibus quæ habebat : Pone manum tuam subter femur meum,

** Genesis 24:3

ut adjurem te per Dominum Deum cæli et terræ, ut non accipias uxorem filio meo de filiabus Chananæorum, inter quos habito :

** Genesis 24:4

sed ad terram et cognationem meam proficiscaris et inde accipias uxorem filio meo Isaac.

** Genesis 24:5

Respondit servus : Si noluerit mulier venire mecum in terram hanc, numquid reducere debeo filium tuum ad locum, de quo egressus es ?

** Genesis 24:6

Dixitque Abraham : Cave nequando reducas filium meum illuc.

** Genesis 24:7

Dominus Deus cæli, qui tulit me de domo patris mei, et de terra nativitatis meæ, qui locutus est mihi, et juravit mihi, dicens : Semini tuo dabo terram hanc : ipse mittet angelum suum coram te, et accipies inde uxorem filio meo :

** Genesis 24:8

sin autem mulier noluerit sequi te, non teneberis juramento : filium meum tantum ne reducas illuc.

** Genesis 24:9

Posuit ergo servus manum sub femore Abraham domini sui, et juravit illi super sermone hoc.

** Genesis 24:10

Tulitque decem camelos de grege domini sui, et abiit, ex omnibus bonis ejus portans secum, profectusque perrexit in Mesopotamiam ad urbem Nachor.

** Genesis 24:11

Cumque camelos fecisset accumbere extra oppidum juxta puteum aquæ vespere, tempore quo solent mulieres egredi ad hauriendam aquam, dixit :

** Genesis 24:12

Domine Deus domini mei Abraham, occurre, obsecro, mihi hodie, et fac misericordiam cum domino meo Abraham.

** Genesis 24:13

Ecce ego sto prope fontem aquæ, et filiæ habitatorum hujus civitatis egredientur ad hauriendam aquam.

** Genesis 24:14

Igitur puella, cui ego dixero : Inclina hydriam tuam ut bibam : et illa responderit : Bibe, quin et camelis tuis dabo potum : ipsa est quam præparasti servo tuo Isaac : et per hoc intelligam quod feceris misericordiam cum domino meo.

** Genesis 24:15

Necdum intra se verba compleverat, et ecce Rebecca egrediebatur, filia Bathuel, filii Melchæ uxoris Nachor fratris Abraham, habens hydriam in scapula sua :

** Genesis 24:16

puella decora nimis, virgoque pulcherrima, et incognita viro : descenderat autem ad fontem, et impleverat hydriam, ac revertebatur.

** Genesis 24:17

Occurritque ei servus, et ait : Pauxillum aquæ mihi ad bibendum præbe de hydria tua.

** Genesis 24:18

Quæ respondit : Bibe, domine mi : celeriterque deposuit hydriam super ulnam suam, et dedit ei potum.

** Genesis 24:19

Cumque ille bibisset, adjecit : Quin et camelis tuis hauriam aquam, donec cuncti bibant.

** Genesis 24:20

Effundensque hydriam in canalibus, recurrit ad puteum ut hauriret aquam : et haustam omnibus camelis dedit.

** Genesis 24:21

Ipse autem contemplabatur eam tacitus, scire volens utrum prosperum iter suum fecisset Dominus, an non.

** Genesis 24:22

Postquam autem biberunt cameli, protulit vir inaures aureas, appendentes siclos duos, et armillas totidem pondo siclorum decem.

** Genesis 24:23

Dixitque ad eam : Cujus es filia ? indica mihi, est in domo patris tui locus ad manendum ?

** Genesis 24:24

Quæ respondit : Filia sum Bathuelis, filii Melchæ, quem peperit ipsi Nachor.

** Genesis 24:25

Et addidit, dicens : Palearum quoque et fœni plurimum est apud nos, et locus spatiosus ad manendum.

** Genesis 24:26

Inclinavit se homo, et adoravit Dominum,

** Genesis 24:27

dicens : Benedictus Dominus Deus domini mei Abraham, qui non abstulit misericordiam et veritatem suam a domino meo, et recto itinere me perduxit in domum fratris domini mei.  

** Genesis 24:28

Cucurrit itaque puella, et nuntiavit in domum matris suæ omnia quæ audierat.

** Genesis 24:29

Habebat autem Rebecca fratrem nomine Laban, qui festinus egressus est ad hominem, ubi erat fons.

** Genesis 24:30

Cumque vidisset inaures et armillas in manibus sororis suæ, et audisset cuncta verba referentis : Hæc locutus est mihi homo : venit ad virum qui stabat juxta camelos, et prope fontem aquæ :

** Genesis 24:31

dixitque ad eum : Ingredere, benedicte Domini : cur foris stas ? præparavi domum, et locum camelis.

** Genesis 24:32

Et introduxit eum in hospitium : ac destravit camelos, deditque paleas et fœnum, et aquam ad lavandos pedes ejus, et virorum qui venerant cum eo.

** Genesis 24:33

Et appositus est in conspectu ejus panis. Qui ait : Non comedam, donec loquar sermones meos. Respondit ei : Loquere.

** Genesis 24:34

At ille : Servus, inquit, Abraham sum :

** Genesis 24:35

et Dominus benedixit domino meo valde, magnificatusque est : et dedit ei oves et boves, argentum et aurum, servos et ancillas, camelos et asinos.

** Genesis 24:36

Et peperit Sara uxor domini mei filium domino meo in senectute sua, deditque illi omnia quæ habuerat.

** Genesis 24:37

Et adjuravit me dominus meus, dicens : Non accipies uxorem filio meo de filiabus Chananæorum, in quorum terra habito :

** Genesis 24:38

sed ad domum patris mei perges, et de cognatione mea accipies uxorem filio meo.

** Genesis 24:39

Ego vero respondi domino meo : Quid si noluerit venire mecum mulier ?

** Genesis 24:40

Dominus, ait, in cujus conspectu ambulo, mittet angelum suum tecum, et diriget viam tuam : accipiesque uxorem filio meo de cognatione mea, et de domo patris mei.

** Genesis 24:41

Innocens eris a maledictione mea, cum veneris ad propinquos meos, et non dederint tibi.

** Genesis 24:42

Veni ergo hodie ad fontem aquæ, et dixi : Domine Deus domini mei Abraham, si direxisti viam meam, in qua nunc ambulo,

** Genesis 24:43

ecce sto juxta fontem aquæ, et virgo, quæ egredietur ad hauriendam aquam, audierit a me : Da mihi pauxillum aquæ ad bibendum ex hydria tua :

** Genesis 24:44

et dixerit mihi : Et tu bibe, et camelis tuis hauriam : ipsa est mulier, quam præparavit Dominus filio domini mei.

** Genesis 24:45

Dumque hæc tacitus mecum volverem, apparuit Rebecca veniens cum hydria, quam portabat in scapula : descenditque ad fontem, et hausit aquam. Et aio ad eam : Da mihi paululum bibere.

** Genesis 24:46

Quæ festinans deposuit hydriam de humero, et dixit mihi : Et tu bibe, et camelis tuis tribuam potum. Bibi, et adaquavit camelos.

** Genesis 24:47

Interrogavique eam, et dixi : Cujus es filia ? Quæ respondit : Filia Bathuelis sum, filii Nachor, quem peperit ei Melcha. Suspendi itaque inaures ad ornandam faciem ejus, et armillas posui in manibus ejus.

** Genesis 24:48

Pronusque adoravi Dominum, benedicens Domino Deo domini mei Abraham, qui perduxit me recto itinere, ut sumerem filiam fratris domini mei filio ejus.

** Genesis 24:49

Quam ob rem si facitis misericordiam et veritatem cum domino meo, indicate mihi : sin autem aliud placet, et hoc dicite mihi, ut vadam ad dextram, sive ad sinistram.  

** Genesis 24:50

Responderuntque Laban et Bathuel : A Domino egressus est sermo : non possumus extra placitum ejus quidquam aliud loqui tecum.

** Genesis 24:51

En Rebecca coram te est, tolle eam, et proficiscere, et sit uxor filii domini tui, sicut locutus est Dominus.

** Genesis 24:52

Quod cum audisset puer Abraham, procidens adoravit in terram Dominum.

** Genesis 24:53

Prolatisque vasis argenteis, et aureis, ac vestibus, dedit ea Rebeccæ pro munere : fratribus quoque ejus et matri dona obtulit.

** Genesis 24:54

Inito convivio, vescentes pariter et bibentes manserunt ibi. Surgens autem mane, locutus est puer : Dimitte me, ut vadam ad dominum meum.

** Genesis 24:55

Responderuntque fratres ejus et mater : Maneat puella saltem decem dies apud nos, et postea proficiscetur.

** Genesis 24:56

Nolite, ait, me retinere, quia Dominus direxit viam meam : dimittite me ut pergam ad dominum meum.

** Genesis 24:57

Et dixerunt : Vocemus puellam, et quæramus ipsius voluntatem.

** Genesis 24:58

Cumque vocata venisset, sciscitati sunt : Vis ire cum homine isto ? Quæ ait : Vadam.

** Genesis 24:59

Dimiserunt ergo eam, et nutricem illius, servumque Abraham, et comites ejus,

** Genesis 24:60

imprecantes prospera sorori suæ, atque dicentes : Soror nostra es, crescas in mille millia, et possideat semen tuum portas inimicorum suorum.

** Genesis 24:61

Igitur Rebecca et puellæ illius, ascensis camelis, secutæ sunt virum : qui festinus revertebatur ad dominum suum.

** Genesis 24:62

Eo autem tempore deambulabat Isaac per viam quæ ducit ad puteum, cujus nomen est Viventis et videntis : habitabat enim in terra australi :

** Genesis 24:63

et egressus fuerat ad meditandum in agro, inclinata jam die : cumque elevasset oculos, vidit camelos venientes procul.

** Genesis 24:64

Rebecca quoque, conspecto Isaac, descendit de camelo,

** Genesis 24:65

et ait ad puerum : Quis est ille homo qui venit per agrum in occursum nobis ? Dixitque ei : Ipse est dominus meus. At illa tollens cito pallium, operuit se.

** Genesis 24:66

Servus autem cuncta, quæ gesserat, narravit Isaac.

** Genesis 24:67

Qui introduxit eam in tabernaculum Saræ matris suæ, et accepit eam uxorem : et in tantum dilexit eam, ut dolorem, qui ex morte matris ejus acciderat, temperaret.   

* Genesis 25

** Genesis 25:1

Abraham vero aliam duxit uxorem nomine Ceturam :

** Genesis 25:2

quæ peperit ei Zamran et Jecsan, et Madan, et Madian, et Jesboc, et Sue.

** Genesis 25:3

Jecsan quoque genuit Saba et Dadan. Filii Dadan fuerunt Assurim, et Latusim, et Loomin.

** Genesis 25:4

At vero ex Madian ortus est Epha, et Opher, et Henoch, et Abida, et Eldaa : omnes hi filii Ceturæ.

** Genesis 25:5

Deditque Abraham cuncta quæ possederat, Isaac :

** Genesis 25:6

filiis autem concubinarum largitus est munera, et separavit eos ab Isaac filio suo, dum adhuc ipse viveret, ad plagam orientalem.

** Genesis 25:7

Fuerunt autem dies vitæ Abrahæ, centum septuaginta quinque anni.

** Genesis 25:8

Et deficiens mortuus est in senectute bona, provectæque ætatis et plenus dierum : congregatusque est ad populum suum.

** Genesis 25:9

Et sepelierunt eum Isaac et Ismaël filii sui in spelunca duplici, quæ sita est in agro Ephron filii Seor Hethæi, e regione Mambre,

** Genesis 25:10

quem emerat a filiis Heth : ibi sepultus est ipse, et Sara uxor ejus.

** Genesis 25:11

Et post obitum illius benedixit Deus Isaac filio ejus, qui habitabat juxta puteum nomine Viventis et videntis.  

** Genesis 25:12

Hæ sunt generationes Ismaël filii Abrahæ, quem peperit ei Agar Ægyptia, famula Saræ : et

** Genesis 25:13

hæc nomina filiorum ejus in vocabulis et generationibus suis. Primogenitus Ismaëlis Nabaioth, deinde Cedar, et Adbeel, et Mabsam,

** Genesis 25:14

Masma quoque, et Duma, et Massa,

** Genesis 25:15

Hadar, et Thema, et Jethur, et Naphis, et Cedma.

** Genesis 25:16

Isti sunt filii Ismaëlis : et hæc nomina per castella et oppida eorum, duodecim principes tribuum suarum.

** Genesis 25:17

Et facti sunt anni vitæ Ismaëlis centum triginta septem, deficiensque mortuus est, et appositus ad populum suum.

** Genesis 25:18

Habitavit autem ab Hevila usque Sur, quæ respicit Ægyptum introëuntibus Assyrios ; coram cunctis fratribus suis obiit.  

** Genesis 25:19

Hæ quoque sunt generationes Isaac filii Abraham : Abraham genuit Isaac :

** Genesis 25:20

qui cum quadraginta esset annorum, duxit uxorem Rebeccam filiam Bathuelis Syri de Mesopotamia, sororem Laban.

** Genesis 25:21

Deprecatusque est Isaac Dominum pro uxore sua, eo quod esset sterilis : qui exaudivit eum, et dedit conceptum Rebeccæ.

** Genesis 25:22

Sed collidebantur in utero ejus parvuli ; quæ ait : Si sic mihi futurum erat, quid necesse fuit concipere ? perrexitque ut consuleret Dominum.

** Genesis 25:23

Qui respondens ait :   Duæ gentes sunt in utero tuo,  et duo populi ex ventre tuo dividentur,  populusque populum superabit,  et major serviet minori.

** Genesis 25:24

Jam tempus pariendi advenerat, et ecce gemini in utero ejus reperti sunt.

** Genesis 25:25

Qui prior egressus est, rufus erat, et totus in morem pellis hispidus : vocatumque est nomen ejus Esau. Protinus alter egrediens, plantam fratris tenebat manu : et idcirco appellavit eum Jacob.

** Genesis 25:26

Sexagenarius erat Isaac quando nati sunt ei parvuli.

** Genesis 25:27

Quibus adultis, factus est Esau vir gnarus venandi, et homo agricola : Jacob autem vir simplex habitabat in tabernaculis.

** Genesis 25:28

Isaac amabat Esau, eo quod de venationibus illius vesceretur : et Rebecca diligebat Jacob.

** Genesis 25:29

Coxit autem Jacob pulmentum : ad quem cum venisset Esau de agro lassus,

** Genesis 25:30

ait : Da mihi de coctione hac rufa, quia oppido lassus sum. Quam ob causam vocatum est nomen ejus Edom.

** Genesis 25:31

Cui dixit Jacob : Vende mihi primogenita tua.

** Genesis 25:32

Ille respondit : En morior, quid mihi proderunt primogenita ?

** Genesis 25:33

Ait Jacob : Jura ergo mihi. Juravit ei Esau et vendidit primogenita.

** Genesis 25:34

Et sic, accepto pane et lentis edulio, comedit et bibit, et abiit, parvipendens quod primogenita vendidisset.  

* Genesis 26

** Genesis 26:1

Orta autem fame super terram post eam sterilitatem, quæ acciderat in diebus Abraham, abiit Isaac ad Abimelech regem Palæstinorum in Gerara.

** Genesis 26:2

Apparuitque ei Dominus, et ait : Ne descendas in Ægyptum, sed quiesce in terra quam dixero tibi,

** Genesis 26:3

et peregrinare in ea : eroque tecum, et benedicam tibi : tibi enim et semini tuo dabo universas regiones has, complens juramentum quod spopondi Abraham patri tuo.

** Genesis 26:4

Et multiplicabo semen tuum sicut stellas cæli : daboque posteris tuis universas regiones has : et benedicentur in semine tuo omnes gentes terræ,

** Genesis 26:5

eo quod obedierit Abraham voci meæ, et custodierit præcepta et mandata mea, et cæremonias legesque servaverit.

** Genesis 26:6

Mansit itaque Isaac in Geraris.  

** Genesis 26:7

Qui cum interrogaretur a viris loci illius super uxore sua, respondit : Soror mea est : timuerat enim confiteri quod sibi esset sociata conjugio, reputans ne forte interficerent eum propter illius pulchritudinem.

** Genesis 26:8

Cumque pertransissent dies plurimi, et ibidem moraretur, prospiciens Abimelech rex Palæstinorum per fenestram, vidit eum jocantem cum Rebecca uxore sua.

** Genesis 26:9

Et accersito eo, ait : Perspicuum est quod uxor tua sit : cur mentitus es eam sororem tuam esse ? Respondit : Timui ne morerer propter eam.

** Genesis 26:10

Dixitque Abimelech : Quare imposuisti nobis ? potuit coire quispiam de populo cum uxore tua, et induxeras super nos grande peccatum. Præcepitque omni populo, dicens :

** Genesis 26:11

Qui tetigerit hominis hujus uxorem, morte morietur.  

** Genesis 26:12

Sevit autem Isaac in terra illa, et invenit in ipso anno centuplum : benedixitque ei Dominus.

** Genesis 26:13

Et locupletatus est homo, et ibat proficiens atque succrescens, donec magnus vehementer effectus est :

** Genesis 26:14

habuit quoque possessiones ovium et armentorum, et familiæ plurimum. Ob hoc invidentes ei Palæstini,

** Genesis 26:15

omnes puteos, quos foderant servi patris illius Abraham, illo tempore obstruxerunt, implentes humo :

** Genesis 26:16

in tantum, ut ipse Abimelech diceret ad Isaac : Recede a nobis, quoniam potentior nobis factus es valde.

** Genesis 26:17

Et ille discedens, ut veniret ad torrentem Geraræ, habitaretque ibi,

** Genesis 26:18

rursum fodit alios puteos, quos foderant servi patris sui Abraham, et quos, illo mortuo, olim obstruxerant Philisthiim : appellavitque eos eisdem nominibus quibus ante pater vocaverat.

** Genesis 26:19

Foderuntque in torrente, et repererunt aquam vivam.

** Genesis 26:20

Sed et ibi jurgium fuit pastorum Geraræ adversus pastores Isaac, dicentium : Nostra est aqua, quam ob rem nomen putei ex eo, quod acciderat, vocavit Calumniam.

** Genesis 26:21

Foderunt autem et alium : et pro illo quoque rixati sunt, appellavitque eum Inimicitias.

** Genesis 26:22

Profectus inde fodit alium puteum, pro quo non contenderunt : itaque vocavit nomen ejus Latitudo, dicens : Nunc dilatavit nos Dominus, et fecit crescere super terram.  

** Genesis 26:23

Ascendit autem ex illo loco in Bersabee,

** Genesis 26:24

ubi apparuit ei Dominus in ipsa nocte, dicens : Ego sum Deus Abraham patris tui : noli timere, quia ego tecum sum : benedicam tibi, et multiplicabo semen tuum propter servum meum Abraham.

** Genesis 26:25

Itaque ædificavit ibi altare : et invocato nomine Domini, extendit tabernaculum, præcepitque servis suis ut foderent puteum.

** Genesis 26:26

Ad quem locum cum venissent de Geraris Abimelech, et Ochozath amicus illius, et Phicol dux militum,

** Genesis 26:27

locutus est eis Isaac : Quid venistis ad me, hominem quem odistis, et expulistis a vobis ?

** Genesis 26:28

Qui responderunt : Vidimus tecum esse Dominum, et idcirco nos diximus : Sit juramentum inter nos, et ineamus fœdus,

** Genesis 26:29

ut non facias nobis quidquam mali, sicut et nos nihil tuorum attigimus, nec fecimus quod te læderet : sed cum pace dimisimus auctum benedictione Domini.

** Genesis 26:30

Fecit ergo eis convivium, et post cibum et potum

** Genesis 26:31

surgentes mane, juraverunt sibi mutuo : dimisitque eos Isaac pacifice in locum suum.

** Genesis 26:32

Ecce autem venerunt in ipso die servi Isaac annuntiantes ei de puteo, quem foderant, atque dicentes : Invenimus aquam.

** Genesis 26:33

Unde appellavit eum Abundantiam : et nomen urbi impositum est Bersabee, usque in præsentem diem.

** Genesis 26:34

Esau vero quadragenarius duxit uxores, Judith filiam Beeri Hethæi, et Basemath filiam Elon ejusdem loci :

** Genesis 26:35

quæ ambæ offenderant animum Isaac et Rebeccæ.   

* Genesis 27

** Genesis 27:1

Senuit autem Isaac, et caligaverunt oculi ejus, et videre non poterat : vocavitque Esau filium suum majorem, et dixit ei : Fili mi ? Qui respondit : Adsum.

** Genesis 27:2

Cui pater : Vides, inquit, quod senuerim, et ignorem diem mortis meæ.

** Genesis 27:3

Sume arma tua, pharetram, et arcum, et egredere foras : cumque venatu aliquid apprehenderis,

** Genesis 27:4

fac mihi inde pulmentum sicut velle me nosti, et affer ut comedam : et benedicat tibi anima mea antequam moriar.

** Genesis 27:5

Quod cum audisset Rebecca, et ille abiisset in agrum ut jussionem patris impleret,

** Genesis 27:6

dixit filio suo Jacob : Audivi patrem tuum loquentem cum Esau fratre tuo, et dicentem ei :

** Genesis 27:7

Affer mihi de venatione tua, et fac cibos ut comedam, et benedicam tibi coram Domino antequam moriar.

** Genesis 27:8

Nunc ergo, fili mi, acquiesce consiliis meis :

** Genesis 27:9

et pergens ad gregem, affer mihi duos hædos optimos, ut faciam ex eis escas patri tuo, quibus libenter vescitur :

** Genesis 27:10

quas cum intuleris, et comederit, benedicat tibi priusquam moriatur.

** Genesis 27:11

Cui ille respondit : Nosti quod Esau frater meus homo pilosus sit, et ego lenis :

** Genesis 27:12

si attrectaverit me pater meus, et senserit, timeo ne putet me sibi voluisse illudere, et inducam super me maledictionem pro benedictione.

** Genesis 27:13

Ad quem mater : In me sit, ait, ista maledictio, fili mi : tantum audi vocem meam, et pergens, affer quæ dixi.

** Genesis 27:14

Abiit, et attulit, deditque matri. Paravit illa cibos, sicut velle noverat patrem illius.

** Genesis 27:15

Et vestibus Esau valde bonis, quas apud se habebat domi, induit eum :

** Genesis 27:16

pelliculasque hædorum circumdedit manibus, et colli nuda protexit :

** Genesis 27:17

deditque pulmentum, et panes, quos coxerat, tradidit.

** Genesis 27:18

Quibus illatis, dixit : Pater mi ? At ille respondit : Audio. Quis es tu, fili mi ?

** Genesis 27:19

Dixitque Jacob : Ego sum primogenitus tuus Esau : feci sicut præcepisti mihi : surge, sede, et comede de venatione mea, ut benedicat mihi anima tua.

** Genesis 27:20

Rursumque Isaac ad filium suum : Quomodo, inquit, tam cito invenire potuisti, fili mi ? Qui respondit : Voluntas Dei fuit ut cito occurreret mihi quod volebam.

** Genesis 27:21

Dixitque Isaac : Accede huc, ut tangam te, fili mi, et probem utrum tu sis filius meus Esau, an non.

** Genesis 27:22

Accessit ille ad patrem, et palpato eo, dixit Isaac : Vox quidem, vox Jacob est : sed manus, manus sunt Esau.

** Genesis 27:23

Et non cognovit eum, quia pilosæ manus similitudinem majoris expresserant. Benedicens ergo illi,

** Genesis 27:24

ait : Tu es filius meus Esau ? Respondit : Ego sum.

** Genesis 27:25

At ille : Affer mihi, inquit, cibos de venatione tua, fili mi, ut benedicat tibi anima mea. Quos cum oblatos comedisset, obtulit ei etiam vinum. Quo hausto,

** Genesis 27:26

dixit ad eum : Accede ad me, et da mihi osculum, fili mi.

** Genesis 27:27

Accessit, et osculatus est eum. Statimque ut sensit vestimentorum illius fragrantiam, benedicens illi, ait :   Ecce odor filii mei  sicut odor agri pleni,  cui benedixit Dominus. 

** Genesis 27:28

Det tibi Deus de rore cæli  et de pinguedine terræ  abundantiam frumenti et vini. 

** Genesis 27:29

Et serviant tibi populi,  et adorent te tribus :  esto dominus fratrum tuorum,  et incurventur ante te filii matris tuæ :  qui maledixerit tibi, sit ille maledictus,  et qui benedixerit tibi, benedictionibus repleatur.  

** Genesis 27:30

Vix Isaac sermonem impleverat, et egresso Jacob foras, venit Esau,

** Genesis 27:31

coctosque de venatione cibos intulit patri, dicens : Surge, pater mi, et comede de venatione filii tui, ut benedicat mihi anima tua.

** Genesis 27:32

Dixitque illi Isaac : Quis enim es tu ? Qui respondit : Ego sum filius tuus primogenitus Esau.

** Genesis 27:33

Expavit Isaac stupore vehementi : et ultra quam credi potest admirans, ait : Quis igitur ille est qui dudum captam venationem attulit mihi, et comedi ex omnibus priusquam tu venires ; benedixique ei, et erit benedictus ?

** Genesis 27:34

Auditis Esau sermonibus patris, irrugiit clamore magno : et consternatus, ait : Benedic etiam et mihi, pater mi.

** Genesis 27:35

Qui ait : Venit germanus tuus fraudulenter, et accepit benedictionem tuam.

** Genesis 27:36

At ille subjunxit : Juste vocatum est nomen ejus Jacob : supplantavit enim me en altera vice : primogenita mea ante tulit, et nunc secundo surripuit benedictionem meam. Rursumque ad patrem : Numquid non reservasti, ait, et mihi benedictionem ?

** Genesis 27:37

Respondit Isaac : Dominum tuum illum constitui, et omnes fratres ejus servituti illius subjugavi ; frumento et vino stabilivi eum : et tibi post hæc, fili mi, ultra quid faciam ?

** Genesis 27:38

Cui Esau : Num unam, inquit, tantum benedictionem habes, pater ? mihi quoque obsecro ut benedicas. Cumque ejulatu magno fleret,

** Genesis 27:39

motus Isaac, dixit ad eum :   In pinguedine terræ,  et in rore cæli desuper,

** Genesis 27:40

erit benedictio tua.  Vives in gladio, et fratri tuo servies :  tempusque veniet, cum excutias et solvas jugum ejus de cervicibus tuis.  

** Genesis 27:41

Oderat ergo semper Esau Jacob pro benedictione qua benedixerat ei pater : dixitque in corde suo : Venient dies luctus patris mei, et occidam Jacob fratrem meum.

** Genesis 27:42

Nuntiata sunt hæc Rebeccæ : quæ mittens et vocans Jacob filium suum, dixit ad eum : Ecce Esau frater tuus minatur ut occidat te.

** Genesis 27:43

Nunc ergo, fili mi, audi vocem meam, et consurgens fuge ad Laban fratrem meum in Haran :

** Genesis 27:44

habitabisque cum eo dies paucos, donec requiescat furor fratris tui,

** Genesis 27:45

et cesset indignatio ejus, obliviscaturque eorum quæ fecisti in eum : postea mittam, et adducam te inde huc : cur utroque orbabor filio in uno die ?

** Genesis 27:46

Dixitque Rebecca ad Isaac : Tædet me vitæ meæ propter filias Heth : si acceperit Jacob uxorem de stirpe hujus terræ, nolo vivere.   

* Genesis 28

** Genesis 28:1

Vocavit itaque Isaac Jacob, et benedixit eum, præcepitque ei dicens : Noli accipere conjugem de genere Chanaan :

** Genesis 28:2

sed vade, et proficiscere in Mesopotamiam Syriæ, ad domum Bathuel patris matris tuæ, et accipe tibi inde uxorem de filiabus Laban avunculi tui.

** Genesis 28:3

Deus autem omnipotens benedicat tibi, et crescere te faciat, atque multiplicet, ut sis in turbas populorum.

** Genesis 28:4

Et det tibi benedictiones Abrahæ, et semini tuo post te : ut possideas terram peregrinationis tuæ, quam pollicitus est avo tuo.

** Genesis 28:5

Cumque dimisisset eum Isaac, profectus venit in Mesopotamiam Syriæ ad Laban filium Bathuel Syri, fratrem Rebeccæ matris suæ.

** Genesis 28:6

Videns autem Esau quod benedixisset pater suus Jacob, et misisset eum in Mesopotamiam Syriæ, ut inde uxorem duceret ; et quod post benedictionem præcepisset ei, dicens : Non accipies uxorem de filiabus Chanaan :

** Genesis 28:7

quodque obediens Jacob parentibus suis isset in Syriam :

** Genesis 28:8

probans quoque quod non libenter aspiceret filias Chanaan pater suus :

** Genesis 28:9

ivit ad Ismaëlem, et duxit uxorem absque iis, quas prius habebat, Maheleth filiam Ismaël filii Abraham, sororem Nabaioth.  

** Genesis 28:10

Igitur egressus Jacob de Bersabee, pergebat Haran.

** Genesis 28:11

Cumque venisset ad quemdam locum, et vellet in eo requiescere post solis occubitum, tulit de lapidibus qui jacebant, et supponens capiti suo, dormivit in eodem loco.

** Genesis 28:12

Viditque in somnis scalam stantem super terram, et cacumen illius tangens cælum : angelos quoque Dei ascendentes et descendentes per eam,

** Genesis 28:13

et Dominum innixum scalæ dicentem sibi : Ego sum Dominus Deus Abraham patris tui, et Deus Isaac : terram, in qua dormis, tibi dabo et semini tuo.

** Genesis 28:14

Eritque semen tuum quasi pulvis terræ : dilataberis ad occidentem, et orientem, et septentrionem, et meridiem : et benedicentur in te et in semine tuo cunctæ tribus terræ.

** Genesis 28:15

Et ero custos tuus quocumque perrexeris, et reducam te in terram hanc : nec dimittam nisi complevero universa quæ dixi.

** Genesis 28:16

Cumque evigilasset Jacob de somno, ait : Vere Dominus est in loco isto, et ego nesciebam.

** Genesis 28:17

Pavensque, Quam terribilis est, inquit, locus iste ! non est hic aliud nisi domus Dei, et porta cæli.

** Genesis 28:18

Surgens ergo Jacob mane, tulit lapidem quem supposuerat capiti suo, et erexit in titulum, fundens oleum desuper.

** Genesis 28:19

Appellavitque nomen urbis Bethel, quæ prius Luza vocabatur.

** Genesis 28:20

Vovit etiam votum, dicens : Si fuerit Deus mecum, et custodierit me in via, per quam ego ambulo, et dederit mihi panem ad vescendum, et vestimentum ad induendum,

** Genesis 28:21

reversusque fuero prospere ad domum patris mei : erit mihi Dominus in Deum,

** Genesis 28:22

et lapis iste, quem erexi in titulum, vocabitur Domus Dei : cunctorumque quæ dederis mihi, decimas offeram tibi.   

* Genesis 29

** Genesis 29:1

Profectus ergo Jacob venit in terram orientalem.

** Genesis 29:2

Et vidit puteum in agro, tres quoque greges ovium accubantes juxta eum : nam ex illo adaquabantur pecora, et os ejus grandi lapide claudebatur.

** Genesis 29:3

Morisque erat ut cunctis ovibus congregatis devolverent lapidem, et refectis gregibus rursum super os putei ponerent.

** Genesis 29:4

Dixitque ad pastores : Fratres, unde estis ? Qui responderunt : De Haran.

** Genesis 29:5

Quos interrogans, Numquid, ait, nostis Laban filium Nachor ? Dixerunt : Novimus.

** Genesis 29:6

Sanusne est ? inquit. Valet, inquiunt : et ecce Rachel filia ejus venit cum grege suo.

** Genesis 29:7

Dixitque Jacob : Adhuc multum diei superest, nec est tempus ut reducantur ad caulas greges : date ante potum ovibus, et sic eas ad pastum reducite.

** Genesis 29:8

Qui responderunt : Non possumus, donec omnia pecora congregentur, et amoveamus lapidem de ore putei, ut adaquemus greges.

** Genesis 29:9

Adhuc loquebantur, et ecce Rachel veniebat cum ovibus patris sui : nam gregem ipsa pascebat.

** Genesis 29:10

Quam cum vidisset Jacob, et sciret consobrinam suam, ovesque Laban avunculi sui, amovit lapidem quo puteus claudebatur.

** Genesis 29:11

Et adaquato grege, osculatus est eam : et elevata voce flevit,

** Genesis 29:12

et indicavit ei quod frater esset patris sui, et filius Rebeccæ : at illa festinans nuntiavit patri suo.

** Genesis 29:13

Qui cum audisset venisse Jacob filium sororis suæ, cucurrit obviam ei : complexusque eum, et in oscula ruens, duxit in domum suam. Auditis autem causis itineris,

** Genesis 29:14

respondit : Os meum es, et caro mea. Et postquam impleti sunt dies mensis unius,

** Genesis 29:15

dixit ei : Num quia frater meus es, gratis servies mihi ? dic quid mercedis accipias.  

** Genesis 29:16

Habebat vero duas filias : nomen majoris Lia, minor vero appellabatur Rachel.

** Genesis 29:17

Sed Lia lippis erat oculis : Rachel decora facie, et venusto aspectu.

** Genesis 29:18

Quam diligens Jacob, ait : Serviam tibi pro Rachel filia tua minore, septem annis.

** Genesis 29:19

Respondit Laban : Melius est ut tibi eam dem quam alteri viro : mane apud me.

** Genesis 29:20

Servivit ergo Jacob pro Rachel septem annis : et videbantur illi pauci dies præ amoris magnitudine.

** Genesis 29:21

Dixitque ad Laban : Da mihi uxorem meam : quia jam tempus impletum est, ut ingrediar ad illam.

** Genesis 29:22

Qui vocatis multis amicorum turbis ad convivium, fecit nuptias.

** Genesis 29:23

Et vespere Liam filiam suam introduxit ad eum,

** Genesis 29:24

dans ancillam filiæ, Zelpham nomine. Ad quam cum ex more Jacob fuisset ingressus, facto mane vidit Liam :

** Genesis 29:25

et dixit ad socerum suum : Quid est quod facere voluisti ? nonne pro Rachel servivi tibi ? quare imposuisti mihi ?

** Genesis 29:26

Respondit Laban : Non est in loco nostro consuetudinis, ut minores ante tradamus ad nuptias.

** Genesis 29:27

Imple hebdomadam dierum hujus copulæ : et hanc quoque dabo tibi pro opere quo serviturus es mihi septem annis aliis.

** Genesis 29:28

Acquievit placito : et hebdomada transacta, Rachel duxit uxorem :

** Genesis 29:29

cui pater servam Balam tradiderat.

** Genesis 29:30

Tandemque potitus optatis nuptiis, amorem sequentis priori prætulit, serviens apud eum septem annis aliis.  

** Genesis 29:31

Videns autem Dominus quod despiceret Liam, aperuit vulvam ejus, sorore sterili permanente.

** Genesis 29:32

Quæ conceptum genuit filium, vocavitque nomen ejus Ruben, dicens : Vidit Dominus humilitatem meam : nunc amabit me vir meus.

** Genesis 29:33

Rursumque concepit et peperit filium, et ait : Quoniam audivit me Dominus haberi contemptui, dedit etiam istum mihi ; vocavitque nomen ejus Simeon.

** Genesis 29:34

Concepitque tertio, et genuit alium filium : dixitque : Nunc quoque copulabitur mihi maritus meus : eo quod pepererim ei tres filios : et idcirco appellavit nomen ejus Levi.

** Genesis 29:35

Quarto concepit, et peperit filium, et ait : Modo confitebor Domino, et ob hoc vocavit eum Judam : cessavitque parere.   

* Genesis 30

** Genesis 30:1

Cernens autem Rachel quod infecunda esset, invidit sorori suæ, et ait marito suo : Da mihi liberos, alioquin moriar.

** Genesis 30:2

Cui iratus respondit Jacob : Num pro Deo ego sum, qui privavit te fructu ventris tui ?

** Genesis 30:3

At illa : Habeo, inquit, famulam Balam : ingredere ad illam, ut pariat super genua mea, et habeam ex illa filios.

** Genesis 30:4

Deditque illi Balam in conjugium : quæ,

** Genesis 30:5

ingresso ad se viro, concepit, et peperit filium.

** Genesis 30:6

Dixitque Rachel : Judicavit mihi Dominus, et exaudivit vocem meam, dans mihi filium, et idcirco appellavit nomen ejus Dan.

** Genesis 30:7

Rursumque Bala concipiens, peperit alterum,

** Genesis 30:8

pro quo ait Rachel : Comparavit me Deus cum sorore mea, et invalui : vocavitque eum Nephthali.

** Genesis 30:9

Sentiens Lia quod parere desiisset, Zelpham ancillam suam marito tradidit.

** Genesis 30:10

Qua post conceptum edente filium,

** Genesis 30:11

dixit : Feliciter, et idcirco vocavit nomen ejus Gad.

** Genesis 30:12

Peperit quoque Zelpha alterum.

** Genesis 30:13

Dixitque Lia : Hoc pro beatitudine mea : beatam quippe me dicent mulieres : propterea appellavit eum Aser.

** Genesis 30:14

Egressus autem Ruben tempore messis triticeæ in agrum, reperit mandragoras, quas matri Liæ detulit. Dixitque Rachel : Da mihi partem de mandragoris filii tui.

** Genesis 30:15

Illa respondit : Parumne tibi videtur quod præripueris maritum mihi, nisi etiam mandragoras filii mei tuleris ? Ait Rachel : Dormiat tecum hac nocte pro mandragoris filii tui.

** Genesis 30:16

Redeuntique ad vesperam Jacob de agro, egressa est in occursum ejus Lia, et Ad me, inquit, intrabis : quia mercede conduxi te pro mandragoris filii mei. Dormivitque cum ea nocte illa.

** Genesis 30:17

Et exaudivit Deus preces ejus, concepitque et peperit filium quintum,

** Genesis 30:18

et ait : Dedit Deus mercedem mihi, quia dedi ancillam meam viro meo : appellavitque nomen ejus Issachar.

** Genesis 30:19

Rursum Lia concipiens, peperit sextum filium,

** Genesis 30:20

et ait : Dotavit me Deus dote bona : etiam hac vice mecum erit maritus meus, eo quod genuerim ei sex filios : et idcirco appellavit nomen ejus Zabulon.

** Genesis 30:21

Post quem peperit filiam, nomine Dinam.

** Genesis 30:22

Recordatus quoque Dominus Rachelis, exaudivit eam, et aperuit vulvam ejus.

** Genesis 30:23

Quæ concepit, et peperit filium, dicens : Abstulit Deus opprobrium meum.

** Genesis 30:24

Et vocavit nomen ejus Joseph, dicens : Addat mihi Dominus filium alterum.

** Genesis 30:25

Nato autem Joseph, dixit Jacob socero suo : Dimitte me ut revertar in patriam, et ad terram meam.

** Genesis 30:26

Da mihi uxores, et liberos meos, pro quibus servivi tibi, ut abeam : tu nosti servitutem qua servivi tibi.  

** Genesis 30:27

Ait illi Laban : Inveniam gratiam in conspectu tuo, experimento didici, quia benedixerit mihi Deus propter te :

** Genesis 30:28

constitue mercedem tuam quam dem tibi.

** Genesis 30:29

At ille respondit : Tu nosti quomodo servierim tibi, et quanta in manibus meis fuerit possessio tua.

** Genesis 30:30

Modicum habuisti antequam venirem ad te, et nunc dives effectus es : benedixitque tibi Dominus ad introitum meum. Justum est igitur ut aliquando provideam etiam domui meæ.

** Genesis 30:31

Dixitque Laban : Quid tibi dabo ? At ille ait : Nihil volo : sed si feceris quod postulo, iterum pascam, et custodiam pecora tua.

** Genesis 30:32

Gyra omnes greges tuos, et separa cunctas oves varias, et sparso vellere ; quodcumque furvum, et maculosum, variumque fuerit, tam in ovibus quam in capris, erit merces mea.

** Genesis 30:33

Respondebitque mihi cras justitia mea, quando placiti tempus advenerit coram te : et omnia quæ non fuerint varia, et maculosa, et furva, tam in ovibus quam in capris, furti me arguent.

** Genesis 30:34

Dixitque Laban : Gratum habeo quod petis.

** Genesis 30:35

Et separavit in die illa capras, et oves, et hircos, et arietes varios, atque maculosos : cunctum autem gregem unicolorem, id est albi et nigri velleris, tradidit in manu filiorum suorum.

** Genesis 30:36

Et posuit spatium itineris trium dierum inter se et generum, qui pascebat reliquos greges ejus.

** Genesis 30:37

Tollens ergo Jacob virgas populeas virides, et amygdalinas, et ex platanis, ex parte decorticavit eas : detractisque corticibus, in his, quæ spoliata fuerant, candor apparuit : illa vero quæ integra fuerant, viridia permanserunt : atque in hunc modum color effectus est varius.

** Genesis 30:38

Posuitque eas in canalibus, ubi effundebatur aqua : ut cum venissent greges ad bibendum, ante oculos haberent virgas, et in aspectu earum conciperent.

** Genesis 30:39

Factumque est ut in ipso calore coitus, oves intuerentur virgas, et parerent maculosa, et varia, et diverso colore respersa.

** Genesis 30:40

Divisitque gregem Jacob, et posuit virgas in canalibus ante oculos arietum : erant autem alba et nigra quæque, Laban ; cetera vero, Jacob, separatis inter se gregibus.

** Genesis 30:41

Igitur quando primo tempore ascendebantur oves, ponebat Jacob virgas in canalibus aquarum ante oculos arietum et ovium, ut in earum contemplatione conciperent :

** Genesis 30:42

quando vero serotina admissura erat, et conceptus extremus, non ponebat eas. Factaque sunt ea quæ erant serotina, Laban : et quæ primi temporis, Jacob.

** Genesis 30:43

Ditatusque est homo ultra modum, et habuit greges multos, ancillas et servos, camelos et asinos.   

* Genesis 31

** Genesis 31:1

Postquam autem audivit verba filiorum Laban dicentium : Tulit Jacob omnia quæ fuerunt patris nostri, et de illius facultate ditatus, factus est inclytus :

** Genesis 31:2

animadvertit quoque faciem Laban, quod non esset erga se sicut heri et nudiustertius,

** Genesis 31:3

maxime dicente sibi Domino : Revertere in terram patrum tuorum, et ad generationem tuam, eroque tecum.

** Genesis 31:4

Misit, et vocavit Rachel et Liam in agrum, ubi pascebat greges,

** Genesis 31:5

dixitque eis : Video faciem patris vestri quod non sit erga me sicut heri et nudiustertius : Deus autem patris mei fuit mecum.

** Genesis 31:6

Et ipsæ nostis quod totis viribus meis servierim patri vestro.

** Genesis 31:7

Sed et pater vester circumvenit me et mutavit mercedem meam decem vicibus : et tamen non dimisit eum Deus ut noceret mihi.

** Genesis 31:8

Si quando dixit : Variæ erunt mercedes tuæ : pariebant omnes oves varios fœtus ; quando vero e contrario, ait : Alba quæque accipies pro mercede : omnes greges alba pepererunt.

** Genesis 31:9

Tulitque Deus substantiam patris vestri, et dedit mihi.

** Genesis 31:10

Postquam enim conceptus ovium tempus advenerat, levavi oculos meos, et vidi in somnis ascendentes mares super feminas, varios et maculosos, et diversorum colorum.

** Genesis 31:11

Dixitque angelus Dei ad me in somnis : Jacob ? Et ego respondi : Adsum.

** Genesis 31:12

Qui ait : Leva oculos tuos, et vide universos masculos ascendentes super feminas, varios, maculosos, atque respersos. Vidi enim omnia quæ fecit tibi Laban.

** Genesis 31:13

Ego sum Deus Bethel, ubi unxisti lapidem, et votum vovisti mihi. Nunc ergo surge, et egredere de terra hac, revertens in terram nativitatis tuæ.

** Genesis 31:14

Responderuntque Rachel et Lia : Numquid habemus residui quidquam in facultatibus et hæreditate domus patris nostri ?

** Genesis 31:15

nonne quasi alienas reputavit nos, et vendidit, comeditque pretium nostrum ?

** Genesis 31:16

Sed Deus tulit opes patris nostri, et eas tradidit nobis, ac filiis nostris : unde omnia quæ præcepit tibi Deus, fac.

** Genesis 31:17

Surrexit itaque Jacob, et impositis liberis ac conjugibus suis super camelos, abiit.

** Genesis 31:18

Tulitque omnem substantiam suam, et greges, et quidquid in Mesopotamia acquisierat, pergens ad Isaac patrem suum in terram Chanaan.  

** Genesis 31:19

Eo tempore ierat Laban ad tondendas oves, et Rachel furata est idola patris sui.

** Genesis 31:20

Noluitque Jacob confiteri socero suo quod fugeret.

** Genesis 31:21

Cumque abiisset tam ipse quam omnia quæ juris sui erant, et amne transmisso pergeret contra montem Galaad,

** Genesis 31:22

nuntiatum est Laban die tertio quod fugeret Jacob.

** Genesis 31:23

Qui, assumptis fratribus suis, persecutus est eum diebus septem : et comprehendit eum in monte Galaad.

** Genesis 31:24

Viditque in somnis dicentem sibi Deum : Cave ne quidquam aspere loquaris contra Jacob.

** Genesis 31:25

Jamque Jacob extenderat in monte tabernaculum : cumque ille consecutus fuisset eum cum fratribus suis, in eodem monte Galaad fixit tentorium.

** Genesis 31:26

Et dixit ad Jacob : Quare ita egisti, ut clam me abigeres filias meas quasi captivas gladio ?

** Genesis 31:27

cur ignorante me fugere voluisti, nec indicare mihi, ut prosequerer te cum gaudio, et canticis, et tympanis, et citharis ?

** Genesis 31:28

Non es passus ut oscularer filios meos et filias : stulte operatus es : et nunc quidem

** Genesis 31:29

valet manus mea reddere tibi malum : sed Deus patris vestri heri dixit mihi : Cave ne loquaris contra Jacob quidquam durius.

** Genesis 31:30

Esto, ad tuos ire cupiebas, et desiderio erat tibi domus patris tui : cur furatus es deos meos ?

** Genesis 31:31

Respondit Jacob : Quod inscio te profectus sum, timui ne violenter auferres filias tuas.

** Genesis 31:32

Quod autem furti me arguis : apud quemcumque inveneris deos tuos, necetur coram fratribus nostris : scrutare, quidquid tuorum apud me inveneris, et aufer. Hæc dicens, ignorabat quod Rachel furata esset idola.

** Genesis 31:33

Ingressus itaque Laban tabernaculum Jacob, et Liæ, et utriusque famulæ, non invenit. Cumque intrasset tentorium Rachelis,

** Genesis 31:34

illa festinans abscondit idola subter stramenta cameli, et sedit desuper : scrutantique omne tentorium, et nihil invenienti,

** Genesis 31:35

ait : Ne irascatur dominus meus quod coram te assurgere nequeo : quia juxta consuetudinem feminarum nunc accidit mihi : sic delusa sollicitudo quærentis est.

** Genesis 31:36

Tumensque Jacob, cum jurgio ait : Quam ob culpam meam, et ob quod peccatum meum sic exarsisti post me,

** Genesis 31:37

et scrutatus es omnem supellectilem meam ? quid invenisti de cuncta substantia domus tuæ ? pone hic coram fratribus meis, et fratribus tuis, et judicent inter me et te.

** Genesis 31:38

Idcirco viginti annis fui tecum ? oves tuæ et capræ steriles non fuerunt, arietes gregis tui non comedi :

** Genesis 31:39

nec captum a bestia ostendi tibi, ego damnum omne reddebam : quidquid furto peribat, a me exigebas :

** Genesis 31:40

die noctuque æstu urebar, et gelu, fugiebatque somnus ab oculis meis.

** Genesis 31:41

Sicque per viginti annos in domo tua servivi tibi, quatuordecim pro filiabus, et sex pro gregibus tuis : immutasti quoque mercedem meam decem vicibus.

** Genesis 31:42

Nisi Deus patris mei Abraham, et timor Isaac affuisset mihi, forsitan modo nudum me dimisisses : afflictionem meam et laborem manuum mearum respexit Deus, et arguit te heri.  

** Genesis 31:43

Respondit ei Laban : Filiæ meæ et filii, et greges tui, et omnia quæ cernis, mea sunt : quid possum facere filiis et nepotibus meis ?

** Genesis 31:44

Veni ergo, et ineamus fœdus, ut sit in testimonium inter me et te.

** Genesis 31:45

Tulit itaque Jacob lapidem, et erexit illum in titulum :

** Genesis 31:46

dixitque fratribus suis : Afferte lapides. Qui congregantes fecerunt tumulum, comederuntque super eum :

** Genesis 31:47

quem vocavit Laban Tumulum testis : et Jacob, Acervum testimonii, uterque juxta proprietatem linguæ suæ.

** Genesis 31:48

Dixitque Laban : Tumulus iste erit testis inter me et te hodie, et idcirco appellatum est nomen ejus Galaad, id est, Tumulus testis.

** Genesis 31:49

Intueatur et judicet Dominus inter nos quando recesserimus a nobis,

** Genesis 31:50

si afflixeris filias meas, et si introduxeris alias uxores super eas : nullus sermonis nostri testis est absque Deo, qui præsens respicit.

** Genesis 31:51

Dixitque rursus ad Jacob : En tumulus hic, et lapis quem erexi inter me et te,

** Genesis 31:52

testis erit : tumulus, inquam, iste et lapis sint in testimonium, si aut ego transiero illum pergens ad te, aut tu præterieris, malum mihi cogitans.

** Genesis 31:53

Deus Abraham, et Deus Nachor, judicet inter nos, Deus patris eorum. Juravit ergo Jacob per timorem patris sui Isaac :

** Genesis 31:54

immolatisque victimis in monte, vocavit fratres suos ut ederent panem. Qui cum comedissent, manserunt ibi :

** Genesis 31:55

Laban vero de nocte consurgens, osculatus est filios, et filias suas, et benedixit illis : reversusque est in locum suum.   

* Genesis 32

** Genesis 32:1

Jacob quoque abiit itinere quo cœperat : fueruntque ei obviam angeli Dei.

** Genesis 32:2

Quos cum vidisset, ait : Castra Dei sunt hæc : et appellavit nomen loci illius Mahanaim, id est, Castra.

** Genesis 32:3

Misit autem et nuntios ante se ad Esau fratrem suum in terram Seir, in regionem Edom :

** Genesis 32:4

præcepitque eis, dicens : Sic loquimini domino meo Esau : Hæc dicit frater tuus Jacob : Apud Laban peregrinatus sum, et fui usque in præsentem diem.

** Genesis 32:5

Habeo boves, et asinos, et oves, et servos, et ancillas : mittoque nunc legationem ad dominum meum, ut inveniam gratiam in conspectu tuo.

** Genesis 32:6

Reversique sunt nuntii ad Jacob, dicentes : Venimus ad Esau fratrem tuum, et ecce properat tibi in occursum cum quadringentis viris.

** Genesis 32:7

Timuit Jacob valde : et perterritus divisit populum qui secum erat, greges quoque et oves, et boves, et camelos, in duas turmas,

** Genesis 32:8

dicens : Si venerit Esau ad unam turmam, et percusserit eam, alia turma, quæ relicta est, salvabitur.

** Genesis 32:9

Dixitque Jacob : Deus patris mei Abraham, et Deus patris mei Isaac : Domine qui dixisti mihi : Revertere in terram tuam, et in locum nativitatis tuæ, et benefaciam tibi :

** Genesis 32:10

minor sum cunctis miserationibus tuis, et veritate tua quam explevisti servo tuo. In baculo meo transivi Jordanem istum : et nunc cum duabus turmis regredior.

** Genesis 32:11

Erue me de manu fratris mei Esau, quia valde eum timeo : ne forte veniens percutiat matrem cum filiis.

** Genesis 32:12

Tu locutus es quod benefaceres mihi, et dilatares semen meum sicut arenam maris, quæ præ multitudine numerari non potest.

** Genesis 32:13

Cumque dormisset ibi nocte illa, separavit de his quæ habebat, munera Esau fratri suo,

** Genesis 32:14

capras ducentas, hircos viginti, oves ducentas, et arietes viginti,

** Genesis 32:15

camelos fœtas cum pullis suis triginta, vaccas quadraginta, et tauros viginti, asinas viginti et pullos earum decem.

** Genesis 32:16

Et misit per manus servorum suorum singulos seorsum greges, dixitque pueris suis : Antecedite me, et sit spatium inter gregem et gregem.

** Genesis 32:17

Et præcepit priori, dicens : Si obvium habueris fratrem meum Esau, et interrogaverit te : Cujus es ? aut, Quo vadis ? aut, Cujus sunt ista quæ sequeris ?

** Genesis 32:18

respondebis : Servi tui Jacob, munera misit domino meo Esau, ipse quoque post nos venit.

** Genesis 32:19

Similiter dedit mandata secundo, et tertio, et cunctis qui sequebantur greges, dicens : Iisdem verbis loquimini ad Esau cum inveneritis eum.

** Genesis 32:20

Et addetis : Ipse quoque servus tuus Jacob iter nostrum insequitur. Dixit enim : Placabo illum muneribus quæ præcedunt, et postea videbo illum : forsitan propitiabitur mihi.

** Genesis 32:21

Præcesserunt itaque munera ante eum, ipse vero mansit nocte illa in castris.  

** Genesis 32:22

Cumque mature surrexisset, tulit duas uxores suas, et totidem famulas cum undecim filiis, et transivit vadum Jaboc.

** Genesis 32:23

Traductisque omnibus quæ ad se pertinebant,

** Genesis 32:24

mansit solus : et ecce vir luctabatur cum eo usque mane.

** Genesis 32:25

Qui cum videret quod eum superare non posset, tetigit nervum femoris ejus, et statim emarcuit.

** Genesis 32:26

Dixitque ad eum : Dimitte me : jam enim ascendit aurora. Respondit : Non dimittam te, nisi benedixeris mihi.

** Genesis 32:27

Ait ergo : Quod nomen est tibi ? Respondit : Jacob.

** Genesis 32:28

At ille : Nequaquam, inquit, Jacob appellabitur nomen tuum, sed Israël : quoniam si contra Deum fortis fuisti, quanto magis contra homines prævalebis ?

** Genesis 32:29

Interrogavit eum Jacob : Dic mihi, quo appellaris nomine ? Respondit : Cur quæris nomen meum ? Et benedixit ei in eodem loco.

** Genesis 32:30

Vocavitque Jacob nomen loci illius Phanuel, dicens : Vidi Deum facie ad faciem, et salva facta est anima mea.

** Genesis 32:31

Ortusque est ei statim sol, postquam transgressus est Phanuel : ipse vero claudicabat pede.

** Genesis 32:32

Quam ob causam non comedunt nervum filii Israël, qui emarcuit in femore Jacob, usque in præsentem diem : eo quod tetigerit nervum femoris ejus, et obstupuerit.   

* Genesis 33

** Genesis 33:1

Elevans autem Jacob oculos suos, vidit venientem Esau, et cum eo quadringentos viros : divisitque filios Liæ et Rachel, ambarumque famularum :

** Genesis 33:2

et posuit utramque ancillam, et liberos earum, in principio : Liam vero, et filios ejus, in secundo loco : Rachel autem et Joseph novissimos.

** Genesis 33:3

Et ipse progrediens adoravit pronus in terram septies, donec appropinquaret frater ejus.

** Genesis 33:4

Currens itaque Esau obviam fratri suo, amplexatus est eum : stringensque collum ejus, et osculans flevit.

** Genesis 33:5

Levatisque oculis, vidit mulieres et parvulos earum, et ait : Quid sibi volunt isti ? et si ad te pertinent ? Respondit : Parvuli sunt quos donavit mihi Deus servo tuo.

** Genesis 33:6

Et appropinquantes ancillæ et filii earum, incurvati sunt.

** Genesis 33:7

Accessit quoque Lia cum pueris suis : et cum similiter adorassent, extremi Joseph et Rachel adoraverunt.

** Genesis 33:8

Dixitque Esau : Quænam sunt istæ turmæ quas obviam habui ? Respondit : Ut invenirem gratiam coram domino meo.

** Genesis 33:9

At ille ait : Habeo plurima, frater mi, sint tua tibi.

** Genesis 33:10

Dixitque Jacob : Noli ita, obsecro : sed si inveni gratiam in oculis tuis, accipe munusculum de manibus meis. Sic enim vidi faciem tuam, quasi viderim vultum Dei : esto mihi propitius,

** Genesis 33:11

et suscipe benedictionem quam attuli tibi, et quam donavit mihi Deus tribuens omnia. Vix fratre compellente, suscipiens,

** Genesis 33:12

ait : Gradiamur simul, eroque socius itineris tui.

** Genesis 33:13

Dixitque Jacob : Nosti, domine mi, quod parvulos habeam teneros, et oves, et boves fœtas mecum : quas si plus in ambulando fecero laborare, morientur una die cuncti greges.

** Genesis 33:14

Præcedat dominus meus ante servum suum : et ego sequar paulatim vestigia ejus, sicut videro parvulos meos posse, donec veniam ad dominum meum in Seir.

** Genesis 33:15

Respondit Esau : Oro te, ut de populo qui mecum est, saltem socii remaneant viæ tuæ. Non est, inquit, necesse : hoc uno tantum indigeo, ut inveniam gratiam in conspectu tuo, domine mi.

** Genesis 33:16

Reversus est itaque illo die Esau itinere quo venerat in Seir.

** Genesis 33:17

Et Jacob venit in Socoth : ubi ædificata domo et fixis tentoriis appellavit nomen loci illius Socoth, id est, Tabernacula.

** Genesis 33:18

Transivitque in Salem urbem Sichimorum, quæ est in terra Chanaan, postquam reversus est de Mesopotamia Syriæ : et habitavit juxta oppidum.

** Genesis 33:19

Emitque partem agri, in qua fixerat tabernacula, a filiis Hemor patris Sichem centum agnis.

** Genesis 33:20

Et erecto ibi altari, invocavit super illud fortissimum Deum Israël.   

* Genesis 34

** Genesis 34:1

Egressa est autem Dina filia Liæ ut videret mulieres regionis illius.

** Genesis 34:2

Quam cum vidisset Sichem filius Hemor Hevæi, princeps terræ illius, adamavit eam : et rapuit, et dormivit cum illa, vi opprimens virginem.

** Genesis 34:3

Et conglutinata est anima ejus cum ea, tristemque delinivit blanditiis.

** Genesis 34:4

Et pergens ad Hemor patrem suum : Accipe, inquit, mihi puellam hanc conjugem.

** Genesis 34:5

Quod cum audisset Jacob absentibus filiis, et in pastu pecorum occupatis, siluit donec redirent.  

** Genesis 34:6

Egresso autem Hemor patre Sichem ut loqueretur ad Jacob,

** Genesis 34:7

ecce filii ejus veniebant de agro : auditoque quod acciderat, irati sunt valde, eo quod fœdam rem operatus esset in Israël et, violata filia Jacob, rem illicitam perpetrasset.

** Genesis 34:8

Locutus est itaque Hemor ad eos : Sichem filii mei adhæsit anima filiæ vestræ : date eam illi uxorem :

** Genesis 34:9

et jungamus vicissim connubia : filias vestras tradite nobis, et filias nostras accipite,

** Genesis 34:10

et habitate nobiscum : terra in potestate vestra est : exercete, negotiamini, et possidete eam.

** Genesis 34:11

Sed et Sichem ad patrem et ad fratres ejus ait : Inveniam gratiam coram vobis : et quæcumque statueritis, dabo :

** Genesis 34:12

augete dotem, et munera postulate, et libenter tribuam quod petieritis : tantum date mihi puellam hanc uxorem.

** Genesis 34:13

Responderunt filii Jacob Sichem et patri ejus in dolo, sævientes ob stuprum sororis :

** Genesis 34:14

Non possumus facere quod petitis, nec dare sororem nostram homini incircumciso : quod illicitum et nefarium est apud nos.

** Genesis 34:15

Sed in hoc valebimus fœderari, si volueritis esse similes nostri, et circumcidatur in vobis omne masculini sexus ;

** Genesis 34:16

tunc dabimus et accipiemus mutuo filias vestras ac nostras : et habitabimus vobiscum, erimusque unus populus.

** Genesis 34:17

Si autem circumcidi nolueritis, tollemus filiam nostram, et recedemus.

** Genesis 34:18

Placuit oblatio eorum Hemor, et Sichem filio ejus,

** Genesis 34:19

nec distulit adolescens quin statim quod petebatur expleret : amabat enim puellam valde, et ipse erat inclytus in omni domo patris sui.

** Genesis 34:20

Ingressique portam urbis, locuti sunt ad populum :

** Genesis 34:21

Viri isti pacifici sunt, et volunt habitare nobiscum : negotientur in terra, et exerceant eam, quæ spatiosa et lata cultoribus indiget : filias eorum accipiemus uxores, et nostras illis dabimus.

** Genesis 34:22

Unum est quo differtur tantum bonum : si circumcidamus masculos nostros, ritum gentis imitantes.

** Genesis 34:23

Et substantia eorum, et pecora, et cuncta quæ possident, nostra erunt : tantum in hoc acquiescamus, et habitantes simul, unum efficiemus populum.

** Genesis 34:24

Assensique sunt omnes, circumcisis cunctis maribus.  

** Genesis 34:25

Et ecce, die tertio, quando gravissimus vulnerum dolor est : arreptis duo filii Jacob, Simeon et Levi fratres Dinæ, gladiis, ingressi sunt urbem confidenter : interfectisque omnibus masculis,

** Genesis 34:26

Hemor et Sichem pariter necaverunt, tollentes Dinam de domo Sichem sororem suam.

** Genesis 34:27

Quibus egressis, irruerunt super occisos ceteri filii Jacob : et depopulati sunt urbem in ultionem stupri.

** Genesis 34:28

Oves eorum, et armenta, et asinos, cunctaque vastantes quæ in domibus et in agris erant,

** Genesis 34:29

parvulos quoque eorum et uxores duxerunt captivas.

** Genesis 34:30

Quibus patratis audacter, Jacob dixit ad Simeon et Levi : Turbastis me, et odiosum fecistis me Chananæis, et Pherezæis habitatoribus terræ hujus : nos pauci sumus ; illi congregati percutient me, et delebor ego, et domus mea.

** Genesis 34:31

Responderunt : Numquid ut scorto abuti debuere sorore nostra ?   

* Genesis 35

** Genesis 35:1

Interea locutus est Deus ad Jacob : Surge, et ascende Bethel, et habita ibi, facque altare Deo qui apparuit tibi quando fugiebas Esau fratrem tuum.

** Genesis 35:2

Jacob vero convocata omni domo sua, ait : Abjicite deos alienos qui in medio vestri sunt, et mundamini, ac mutate vestimenta vestra.

** Genesis 35:3

Surgite, et ascendamus in Bethel, ut faciamus ibi altare Deo : qui exaudivit me in die tribulationis meæ, et socius fuit itineris mei.

** Genesis 35:4

Dederunt ergo ei omnes deos alienos quos habebant, et inaures quæ erant in auribus eorum : at ille infodit ea subter terebinthum, quæ est post urbem Sichem.

** Genesis 35:5

Cumque profecti essent, terror Dei invasit omnes per circuitum civitates, et non sunt ausi persequi recedentes.

** Genesis 35:6

Venit igitur Jacob Luzam, quæ est in terra Chanaan, cognomento Bethel : ipse et omnis populus cum eo.

** Genesis 35:7

Ædificavitque ibi altare, et appellavit nomen loci illius, Domus Dei : ibi enim apparuit ei Deus cum fugeret fratrem suum.

** Genesis 35:8

Eodem tempore mortua est Debora nutrix Rebeccæ, et sepulta est ad radices Bethel subter quercum : vocatumque est nomen loci illius, Quercus fletus.

** Genesis 35:9

Apparuit autem iterum Deus Jacob postquam reversus est de Mesopotamia Syriæ, benedixitque ei

** Genesis 35:10

dicens : Non vocaberis ultra Jacob, sed Israël erit nomen tuum. Et appellavit eum Israël,

** Genesis 35:11

dixitque ei : Ego Deus omnipotens : cresce, et multiplicare : gentes et populi nationum ex te erunt, reges de lumbis tuis egredientur,

** Genesis 35:12

terramque quam dedi Abraham et Isaac, dabo tibi et semini tuo post te.

** Genesis 35:13

Et recessit ab eo.

** Genesis 35:14

Ille vero erexit titulum lapideum in loco quo locutus fuerat ei Deus : libans super eum libamina, et effundens oleum :

** Genesis 35:15

vocansque nomen loci illius Bethel.  

** Genesis 35:16

Egressus autem inde, venit verno tempore ad terram quæ ducit Ephratam : in qua cum parturiret Rachel,

** Genesis 35:17

ob difficultatem partus periclitari cœpit. Dixitque ei obstetrix : Noli timere, quia et hunc habebis filium.

** Genesis 35:18

Egrediente autem anima præ dolore, et imminente jam morte, vocavit nomen filii sui Benomi, id est, Filius doloris mei : pater vero appellavit eum Benjamin, id est, Filius dextræ.

** Genesis 35:19

Mortua est ergo Rachel, et sepulta est in via quæ ducit Ephratam, hæc est Bethlehem.

** Genesis 35:20

Erexitque Jacob titulum super sepulchrum ejus : hic est titulus monumenti Rachel, usque in præsentem diem.

** Genesis 35:21

Egressus inde, fixit tabernaculum trans Turrem gregis.

** Genesis 35:22

Cumque habitaret in illa regione, abiit Ruben, et dormivit cum Bala concubina patris sui : quod illum minime latuit. Erant autem filii Jacob duodecim.

** Genesis 35:23

Filii Liæ : primogenitus Ruben, et Simeon, et Levi, et Judas, et Issachar, et Zabulon.

** Genesis 35:24

Filii Rachel : Joseph et Benjamin.

** Genesis 35:25

Filii Balæ ancillæ Rachelis : Dan et Nephthali.

** Genesis 35:26

Filii Zelphæ ancillæ Liæ : Gad et Aser : hi sunt filii Jacob, qui nati sunt ei in Mesopotamia Syriæ.  

** Genesis 35:27

Venit etiam ad Isaac patrem suum in Mambre, civitatem Arbee, hæc est Hebron, in qua peregrinatus est Abraham et Isaac.

** Genesis 35:28

Et completi sunt dies Isaac centum octoginta annorum.

** Genesis 35:29

Consumptusque ætate mortuus est : et appositus est populo suo senex et plenus dierum : et sepelierunt eum Esau et Jacob filii sui.   

* Genesis 36

** Genesis 36:1

Hæ sunt autem generationes Esau, ipse est Edom.

** Genesis 36:2

Esau accepit uxores de filiabus Chanaan : Ada filiam Elon Hethæi, et Oolibama filiam Anæ filiæ Sebeon Hevæi :

** Genesis 36:3

Basemath quoque filiam Ismaël sororem Nabaioth.

** Genesis 36:4

Peperit autem Ada Eliphaz : Basemath genuit Rahuel :

** Genesis 36:5

Oolibama genuit Jehus et Ihelon et Core. Hi filii Esau qui nati sunt ei in terra Chanaan.

** Genesis 36:6

Tulit autem Esau uxores suas et filios et filias, et omnem animam domus suæ, et substantiam, et pecora, et cuncta quæ habere poterat in terra Chanaan : et abiit in alteram regionem, recessitque a fratre suo Jacob.

** Genesis 36:7

Divites enim erant valde, et simul habitare non poterant : nec sustinebat eos terra peregrinationis eorum præ multitudine gregum.

** Genesis 36:8

Habitavitque Esau in monte Seir, ipse est Edom.

** Genesis 36:9

Hæ autem sunt generationes Esau patris Edom in monte Seir,

** Genesis 36:10

et hæc nomina filiorum ejus : Eliphaz filius Ada uxoris Esau : Rahuel quoque filius Basemath uxoris ejus.

** Genesis 36:11

Fueruntque Eliphaz filii : Theman, Omar, Sepho, et Gatham, et Cenez.

** Genesis 36:12

Erat autem Thamna concubina Eliphaz filii Esau : quæ peperit ei Amalech. Hi sunt filii Ada uxoris Esau.

** Genesis 36:13

Filii autem Rahuel : Nahath et Zara, Samma et Meza : hi filii Basemath uxoris Esau.

** Genesis 36:14

Isti quoque erant filii Oolibama filiæ Anæ filiæ Sebeon, uxoris Esau, quos genuit ei, Jehus et Ihelon et Core.

** Genesis 36:15

Hi duces filiorum Esau : filii Eliphaz primogeniti Esau : dux Theman, dux Omra, dux Sepho, dux Cenez,

** Genesis 36:16

dux Core, dux Gathan, dux Amalech. Hi filii Eliphaz in terra Edom, et hi filii Ada.

** Genesis 36:17

Hi quoque filii Rahuel filii Esau : dux Nahath, dux Zara, dux Samma, dux Meza : hi autem duces Rahuel in terra Edom : isti filii Basemath uxoris Esau.

** Genesis 36:18

Hi autem filii Oolibama uxoris Esau : dux Jehus, dux Ihelon, dux Core : hi duces Oolibama filiæ Anæ uxoris Esau.

** Genesis 36:19

Isti sunt filii Esau, et hi duces eorum : ipse est Edom.

** Genesis 36:20

Isti sunt filii Seir Horræi, habitatores terræ : Lotan, et Sobal, et Sebeon, et Ana,

** Genesis 36:21

et Dison, et Eser, et Disan : hi duces Horræi, filii Seir in terra Edom.

** Genesis 36:22

Facti sunt autem filii Lotan : Hori et Heman. Erat autem soror Lotan, Thamna.

** Genesis 36:23

Et isti filii Sobal : Alvan et Manahat et Ebal, et Sepho et Onam.

** Genesis 36:24

Et hi filii Sebeon : Aja et Ana. Iste est Ana qui invenit aquas calidas in solitudine, cum pasceret asinos Sebeon patris sui :

** Genesis 36:25

habuitque filium Dison, et filiam Oolibama.

** Genesis 36:26

Et isti filii Dison : Hamdan, et Eseban, et Jethram, et Charan.

** Genesis 36:27

Hi quoque filii Eser : Balaan, et Zavan, et Acan.

** Genesis 36:28

Habuit autem filios Disan : Hus et Aram.

** Genesis 36:29

Hi duces Horræorum : dux Lotan, dux Sobal, dux Sebeon, dux Ana,

** Genesis 36:30

dux Dison, dux Eser, dux Disan : isti duces Horræorum qui imperaverunt in terra Seir.

** Genesis 36:31

Reges autem qui regnaverunt in terra Edom antequam haberent regem filii Israël, fuerunt hi :

** Genesis 36:32

Bela filius Beor, nomenque urbis ejus Denaba.

** Genesis 36:33

Mortuus est autem Bela, et regnavit pro eo Jobab filius Zaræ de Bosra.

** Genesis 36:34

Cumque mortuus esset Jobab, regnavit pro eo Husam de terra Themanorum.

** Genesis 36:35

Hoc quoque mortuo, regnavit pro eo Adad filius Badad, qui percussit Madian in regione Moab : et nomen urbis ejus Avith.

** Genesis 36:36

Cumque mortuus esset Adad, regnavit pro eo Semla de Masreca.

** Genesis 36:37

Hoc quoque mortuo regnavit pro eo Saul de fluvio Rohoboth.

** Genesis 36:38

Cumque et hic obiisset, successit in regnum Balanan filius Achobor.

** Genesis 36:39

Isto quoque mortuo regnavit pro eo Adar, nomenque urbis ejus Phau : et appellabatur uxor ejus Meetabel, filia Matred filiæ Mezaab.

** Genesis 36:40

Hæc ergo nomina ducum Esau in cognationibus, et locis, et vocabulis suis : dux Thamna, dux Alva, dux Jetheth,

** Genesis 36:41

dux Oolibama, dux Ela, dux Phinon,

** Genesis 36:42

dux Cenez, dux Theman, dux Mabsar,

** Genesis 36:43

dux Magdiel, dux Hiram : hi duces Edom habitantes in terra imperii sui, ipse est Esau pater Idumæorum.   

* Genesis 37

** Genesis 37:1

Habitavit autem Jacob in terra Chanaan, in qua pater suus peregrinatus est.

** Genesis 37:2

Et hæ sunt generationes ejus : Joseph cum sedecim esset annorum, pascebat gregem cum fratribus suis adhuc puer : et erat cum filiis Balæ et Zelphæ uxorum patris sui : accusavitque fratres suos apud patrem crimine pessimo.

** Genesis 37:3

Israël autem diligebat Joseph super omnes filios suos, eo quod in senectute genuisset eum : fecitque ei tunicam polymitam.

** Genesis 37:4

Videntes autem fratres ejus quod a patre plus cunctis filiis amaretur, oderant eum, nec poterant ei quidquam pacifice loqui.

** Genesis 37:5

Accidit quoque ut visum somnium referret fratribus suis : quæ causa majoris odii seminarium fuit.

** Genesis 37:6

Dixitque ad eos : Audite somnium meum quod vidi :

** Genesis 37:7

putabam nos ligare manipulos in agro : et quasi consurgere manipulum meum, et stare, vestrosque manipulos circumstantes adorare manipulum meum.

** Genesis 37:8

Responderunt fratres ejus : Numquid rex noster eris ? aut subjiciemur ditioni tuæ ? Hæc ergo causa somniorum atque sermonum, invidiæ et odii fomitem ministravit.

** Genesis 37:9

Aliud quoque vidit somnium, quod narrans fratribus, ait : Vidi per somnium, quasi solem, et lunam, et stellas undecim adorare me.

** Genesis 37:10

Quod cum patri suo, et fratribus retulisset, increpavit eum pater suus, et dixit : Quid sibi vult hoc somnium quod vidisti ? num ego et mater tua, et fratres tui adorabimus te super terram ?

** Genesis 37:11

Invidebant ei igitur fratres sui : pater vero rem tacitus considerabat.  

** Genesis 37:12

Cumque fratres illius in pascendis gregibus patris morarentur in Sichem,

** Genesis 37:13

dixit ad eum Israël : Fratres tui pascunt oves in Sichimis : veni, mittam te ad eos. Quo respondente,

** Genesis 37:14

Præsto sum, ait ei : Vade, et vide si cuncta prospera sint erga fratres tuos, et pecora : et renuntia mihi quid agatur. Missus de valle Hebron, venit in Sichem :

** Genesis 37:15

invenitque eum vir errantem in agro, et interrogavit quid quæreret.

** Genesis 37:16

At ille respondit : Fratres meos quæro : indica mihi ubi pascant greges.

** Genesis 37:17

Dixitque ei vir : Recesserunt de loco isto : audivi autem eos dicentes : Eamus in Dothain. Perrexit ergo Joseph post fratres suos, et invenit eos in Dothain.

** Genesis 37:18

Qui cum vidissent eum procul, antequam accederet ad eos, cogitaverunt illum occidere :

** Genesis 37:19

et mutuo loquebantur : Ecce somniator venit :

** Genesis 37:20

venite, occidamus eum, et mittamus in cisternam veterem : dicemusque : Fera pessima devoravit eum : et tunc apparebit quid illi prosint somnia sua.

** Genesis 37:21

Audiens autem hoc Ruben, nitebatur liberare eum de manibus eorum, et dicebat :

** Genesis 37:22

Non interficiatis animam ejus, nec effundatis sanguinem : sed projicite eum in cisternam hanc, quæ est in solitudine, manusque vestras servate innoxias : hoc autem dicebat, volens eripere eum de manibus eorum, et reddere patri suo.

** Genesis 37:23

Confestim igitur ut pervenit ad fratres suos, nudaverunt eum tunica talari et polymita :

** Genesis 37:24

miseruntque eum in cisternam veterem, quæ non habebat aquam.

** Genesis 37:25

Et sedentes ut comederent panem, viderunt Ismaëlitas viatores venire de Galaad, et camelos eorum portantes aromata, et resinam, et stacten in Ægyptum.

** Genesis 37:26

Dixit ergo Judas fratribus suis : Quid nobis prodest si occiderimus fratrem nostrum, et celaverimus sanguinem ipsius ?

** Genesis 37:27

melius est ut venundetur Ismaëlitis, et manus nostræ non polluantur : frater enim et caro nostra est. Acquieverunt fratres sermonibus illius.

** Genesis 37:28

Et prætereuntibus Madianitis negotiatoribus, extrahentes eum de cisterna, vendiderunt eum Ismaëlitis, viginti argenteis : qui duxerunt eum in Ægyptum.

** Genesis 37:29

Reversusque Ruben ad cisternam, non invenit puerum :

** Genesis 37:30

et scissis vestibus pergens ad fratres suos, ait : Puer non comparet, et ego quo ibo ?

** Genesis 37:31

Tulerunt autem tunicam ejus, et in sanguine hædi, quem occiderant, tinxerunt :

** Genesis 37:32

mittentes qui ferrent ad patrem, et dicerent : Hanc invenimus : vide utrum tunica filii tui sit, an non.

** Genesis 37:33

Quam cum agnovisset pater, ait : Tunica filii mei est : fera pessima comedit eum, bestia devoravit Joseph.

** Genesis 37:34

Scissisque vestibus, indutus est cilicio, lugens filium suum multo tempore.

** Genesis 37:35

Congregatis autem cunctis liberis ejus ut lenirent dolorem patris, noluit consolationem accipere, sed ait : Descendam ad filium meum lugens in infernum. Et illo perseverante in fletu,

** Genesis 37:36

Madianitæ vendiderunt Joseph in Ægypto Putiphari eunucho Pharaonis, magistro militum.   

* Genesis 38

** Genesis 38:1

Eodem tempore, descendens Judas a fratribus suis, divertit ad virum Odollamitem, nomine Hiram.

** Genesis 38:2

Viditque ibi filiam hominis Chananæi, vocabulo Sue : et accepta uxore, ingressus est ad eam.

** Genesis 38:3

Quæ concepit, et peperit filium, et vocavit nomen ejus Her.

** Genesis 38:4

Rursumque concepto fœtu, natum filium vocavit Onan.

** Genesis 38:5

Tertium quoque peperit : quem appellavit Sela ; quo nato, parere ultra cessavit.

** Genesis 38:6

Dedit autem Judas uxorem primogenito suo Her, nomine Thamar.

** Genesis 38:7

Fuit quoque Her primogenitus Judæ nequam in conspectu Domini : et ab eo occisus est.

** Genesis 38:8

Dixit ergo Judas ad Onan filium suum : Ingredere uxorem fratris tui, et sociare illi, ut suscites semen fratri tuo.

** Genesis 38:9

Ille sciens non sibi nasci filios, introiens ad uxorem fratris sui, semen fundebat in terram, ne liberi fratris nomine nascerentur.

** Genesis 38:10

Et idcirco percussit eum Dominus, quod rem detestabilem faceret.

** Genesis 38:11

Quam ob rem dixit Judas Thamar nurui suæ : Esto vidua in domo patris tui, donec crescat Sela filius meus : timebat enim ne et ipse moreretur, sicut fratres ejus. Quæ abiit, et habitavit in domo patris sui.

** Genesis 38:12

Evolutis autem multis diebus, mortua est filia Sue uxor Judæ : qui, post luctum consolatione suscepta, ascendebat ad tonsores ovium suarum, ipse et Hiras opilio gregis Odollamites, in Thamnas.

** Genesis 38:13

Nuntiatumque est Thamar quod socer illius ascenderet in Thamnas ad tondendas oves.

** Genesis 38:14

Quæ, depositis viduitatis vestibus, assumpsit theristrum : et mutato habitu, sedit in bivio itineris, quod ducit Thamnam : eo quod crevisset Sela, et non eum accepisset maritum.

** Genesis 38:15

Quam cum vidisset Judas, suspicatus est esse meretricem : operuerat enim vultum suum, ne agnosceretur.

** Genesis 38:16

Ingrediensque ad eam, ait : Dimitte me ut coëam tecum : nesciebat enim quod nurus sua esset. Qua respondente : Quid dabis mihi ut fruaris concubitu meo ?

** Genesis 38:17

dixit : Mittam tibi hædum de gregibus. Rursumque illa dicente : Patiar quod vis, si dederis mihi arrhabonem, donec mittas quod polliceris.

** Genesis 38:18

Ait Judas : Quid tibi vis pro arrhabone dari ? Respondit : Annulum tuum, et armillam, et baculum quem manu tenes. Ad unum igitur coitum mulier concepit,

** Genesis 38:19

et surgens abiit : depositoque habitu quem sumpserat, induta est viduitatis vestibus.

** Genesis 38:20

Misit autem Judas hædum per pastorem suum Odollamitem, ut reciperet pignus quod dederat mulieri : qui cum non invenisset eam,

** Genesis 38:21

interrogavit homines loci illius : Ubi est mulier quæ sedebat in bivio ? Respondentibus cunctis : Non fuit in loco ista meretrix.

** Genesis 38:22

Reversus est ad Judam, et dixit ei : Non inveni eam : sed et homines loci illius dixerunt mihi, numquam sedisse ibi scortum.

** Genesis 38:23

Ait Judas : Habeat sibi, certe mendacii arguere nos non potest, ego misi hædum quem promiseram : et tu non invenisti eam.

** Genesis 38:24

Ecce autem post tres menses nuntiaverunt Judæ, dicentes : Fornicata est Thamar nurus tua, et videtur uterus illius intumescere. Dixitque Judas : Producite eam ut comburatur.

** Genesis 38:25

Quæ cum duceretur ad pœnam, misit ad socerum suum, dicens : De viro, cujus hæc sunt, concepi : cognosce cujus sit annulus, et armilla, et baculus.

** Genesis 38:26

Qui, agnitis muneribus, ait : Justior me est : quia non tradidi eam Sela filio meo. Attamen ultra non cognovit eam.

** Genesis 38:27

Instante autem partu, apparuerunt gemini in utero : atque in ipsa effusione infantium unus protulit manum, in qua obstetrix ligavit coccinum, dicens :

** Genesis 38:28

Iste egredietur prior.

** Genesis 38:29

Illo vero retrahente manum, egressus est alter : dixitque mulier : Quare divisa est propter te maceria ? et ob hanc causam, vocavit nomen ejus Phares.

** Genesis 38:30

Postea egressus est frater ejus, in cujus manu erat coccinum : quem appellavit Zara.   

* Genesis 39

** Genesis 39:1

Igitur Joseph ductus est in Ægyptum, emitque eum Putiphar eunuchus Pharaonis, princeps exercitus, vir ægyptius, de manu Ismaëlitarum, a quibus perductus erat.

** Genesis 39:2

Fuitque Dominus cum eo, et erat vir in cunctis prospere agens : habitavitque in domo domini sui,

** Genesis 39:3

qui optime noverat Dominum esse cum eo, et omnia, quæ gerebat, ab eo dirigi in manu illius.

** Genesis 39:4

Invenitque Joseph gratiam coram domino suo, et ministrabat ei : a quo præpositus omnibus gubernabat creditam sibi domum, et universa quæ ei tradita fuerant :

** Genesis 39:5

benedixitque Dominus domui Ægyptii propter Joseph, et multiplicavit tam in ædibus quam in agris cunctam ejus substantiam :

** Genesis 39:6

nec quidquam aliud noverat, nisi panem quo vescebatur. Erat autem Joseph pulchra facie, et decorus aspectu.

** Genesis 39:7

Post multos itaque dies injecit domina sua oculos suos in Joseph, et ait : Dormi mecum.

** Genesis 39:8

Qui nequaquam acquiescens operi nefario, dixit ad eam : Ecce dominus meus, omnibus mihi traditis, ignorat quid habeat in domo sua :

** Genesis 39:9

nec quidquam est quod non in mea sit potestate, vel non tradiderit mihi, præter te, quæ uxor ejus es : quomodo ergo possum hoc malum facere, et peccare in Deum meum ?

** Genesis 39:10

Hujuscemodi verbis per singulos dies, et mulier molesta erat adolescenti : et ille recusabat stuprum.

** Genesis 39:11

Accidit autem quadam die ut intraret Joseph domum, et operis quippiam absque arbitris faceret :

** Genesis 39:12

et illa, apprehensa lacinia vestimenti ejus, diceret : Dormi mecum. Qui relicto in manu ejus pallio fugit, et egressus est foras.

** Genesis 39:13

Cumque vidisset mulier vestem in manibus suis, et se esse contemptam,

** Genesis 39:14

vocavit ad se homines domus suæ, et ait ad eos : En introduxit virum hebræum, ut illuderet nobis : ingressus est ad me, ut coiret mecum : cumque ego succlamassem,

** Genesis 39:15

et audisset vocem meam, reliquit pallium quod tenebam, et fugit foras.

** Genesis 39:16

In argumentum ergo fidei retentum pallium ostendit marito revertenti domum,

** Genesis 39:17

et ait : Ingressus est ad me servus hebræus quem adduxisti, ut illuderet mihi :

** Genesis 39:18

cumque audisset me clamare, reliquit pallium quod tenebam, et fugit foras.

** Genesis 39:19

His auditis dominus, et nimium credulus verbis conjugis, iratus est valde :

** Genesis 39:20

tradiditque Joseph in carcerem, ubi vincti regis custodiebantur, et erat ibi clausus.  

** Genesis 39:21

Fuit autem Dominus cum Joseph, et misertus illius dedit ei gratiam in conspectu principis carceris.

** Genesis 39:22

Qui tradidit in manu illius universos vinctos qui in custodia tenebantur : et quidquid fiebat, sub ipso erat.

** Genesis 39:23

Nec noverat aliquid, cunctis ei creditis : Dominus enim erat cum illo, et omnia opera ejus dirigebat.   

* Genesis 40

** Genesis 40:1

His ita gestis, accidit ut peccarent duo eunuchi, pincerna regis Ægypti, et pistor, domino suo.

** Genesis 40:2

Iratusque contra eos Pharao (nam alter pincernis præerat, alter pistoribus),

** Genesis 40:3

misit eos in carcerem principis militum, in quo erat vinctus et Joseph.

** Genesis 40:4

At custos carceris tradidit eos Joseph, qui et ministrabat eis : aliquantulum temporis fluxerat, et illi in custodia tenebantur.

** Genesis 40:5

Videruntque ambo somnium nocte una, juxta interpretationem congruam sibi :

** Genesis 40:6

ad quos cum introisset Joseph mane, et vidisset eos tristes,

** Genesis 40:7

sciscitatus est eos, dicens : Cur tristior est hodie solito facies vestra ?

** Genesis 40:8

Qui responderunt : Somnium vidimus, et non est qui interpretetur nobis. Dixitque ad eos Joseph : Numquid non Dei est interpretatio ? referte mihi quid videritis.

** Genesis 40:9

Narravit prior, præpositus pincernarum, somnium suum : Videbam coram me vitem,

** Genesis 40:10

in qua erant tres propagines, crescere paulatim in gemmas, et post flores uvas maturescere :

** Genesis 40:11

calicemque Pharaonis in manu mea : tuli ergo uvas, et expressi in calicem quem tenebam, et tradidi poculum Pharaoni.

** Genesis 40:12

Respondit Joseph : Hæc est interpretatio somnii : tres propagines, tres adhuc dies sunt :

** Genesis 40:13

post quos recordabitur Pharao ministerii tui, et restituet te in gradum pristinum : dabisque ei calicem juxta officium tuum, sicut ante facere consueveras.

** Genesis 40:14

Tantum memento mei, cum bene tibi fuerit, et facias mecum misericordiam : ut suggeras Pharaoni ut educat me de isto carcere :

** Genesis 40:15

quia furto sublatus sum de terra Hebræorum, et hic innocens in lacum missus sum.

** Genesis 40:16

Videns pistorum magister quod prudenter somnium dissolvisset, ait : Et ego vidi somnium : quod tria canistra farinæ haberem super caput meum :

** Genesis 40:17

et in uno canistro quod erat excelsius, portare me omnes cibos qui fiunt arte pistoria, avesque comedere ex eo.

** Genesis 40:18

Respondit Joseph : Hæc est interpretatio somnii : tria canistra, tres adhuc dies sunt :

** Genesis 40:19

post quos auferet Pharao caput tuum, ac suspendet te in cruce, et lacerabunt volucres carnes tuas.

** Genesis 40:20

Exinde dies tertius natalitius Pharaonis erat : qui faciens grande convivium pueris suis, recordatus est inter epulas magistri pincernarum, et pistorum principis.

** Genesis 40:21

Restituitque alterum in locum suum, ut porrigeret ei poculum :

** Genesis 40:22

alterum suspendit in patibulo, ut conjectoris veritas probaretur.

** Genesis 40:23

Et tamen succedentibus prosperis, præpositus pincernarum oblitus est interpretis sui.   

* Genesis 41

** Genesis 41:1

Post duos annos vidit Pharao somnium. Putabat se stare super fluvium,

** Genesis 41:2

de quo ascendebant septem boves, pulchræ et crassæ nimis : et pascebantur in locis palustribus.

** Genesis 41:3

Aliæ quoque septem emergebant de flumine, fœdæ confectæque macie : et pascebantur in ipsa amnis ripa in locis virentibus :

** Genesis 41:4

devoraveruntque eas, quarum mira species et habitudo corporum erat. Expergefactus Pharao,

** Genesis 41:5

rursum dormivit, et vidit alterum somnium : septem spicæ pullulabant in culmo uno plenæ atque formosæ :

** Genesis 41:6

aliæ quoque totidem spicæ tenues, et percussæ uredine oriebantur,

** Genesis 41:7

devorantes omnium priorum pulchritudinem. Evigilans Pharao post quietem,

** Genesis 41:8

et facto mane, pavore perterritus, misit ad omnes conjectores Ægypti, cunctosque sapientes, et accersitis narravit somnium, nec erat qui interpretaretur.

** Genesis 41:9

Tunc demum reminiscens pincernarum magister, ait : Confiteor peccatum meum :

** Genesis 41:10

iratus rex servis suis, me et magistrum pistorum retrudi jussit in carcerem principis militum :

** Genesis 41:11

ubi una nocte uterque vidimus somnium præsagum futurorum.

** Genesis 41:12

Erat ibi puer hebræus, ejusdem ducis militum famulus : cui narrantes somnia,

** Genesis 41:13

audivimus quidquid postea rei probavit eventus ; ego enim redditus sum officio meo, et ille suspensus est in cruce.

** Genesis 41:14

Protinus ad regis imperium eductum de carcere Joseph totonderunt : ac veste mutata obtulerunt ei.

** Genesis 41:15

Cui ille ait : Vidi somnia, nec est qui edisserat : quæ audivi te sapientissime conjicere.

** Genesis 41:16

Respondit Joseph : Absque me Deus respondebit prospera Pharaoni.

** Genesis 41:17

Narravit ergo Pharao quod viderat : Putabam me stare super ripam fluminis,

** Genesis 41:18

et septem boves de amne conscendere, pulchras nimis, et obesis carnibus : quæ in pastu paludis virecta carpebant.

** Genesis 41:19

Et ecce, has sequebantur aliæ septem boves, in tantum deformes et macilentæ, ut numquam tales in terra Ægypti viderim :

** Genesis 41:20

quæ, devoratis et consumptis prioribus,

** Genesis 41:21

nullum saturitatis dedere vestigium : sed simili macie et squalore torpebant. Evigilans, rursus sopore depressus,

** Genesis 41:22

vidi somnium. Septem spicæ pullulabant in culmo uno plenæ atque pulcherrimæ.

** Genesis 41:23

Aliæ quoque septem tenues et percussæ uredine, oriebantur e stipula :

** Genesis 41:24

quæ priorum pulchritudinem devoraverunt. Narravi conjectoribus somnium, et nemo est qui edisserat.

** Genesis 41:25

Respondit Joseph : Somnium regis unum est : quæ facturus est Deus, ostendit Pharaoni.

** Genesis 41:26

Septem boves pulchræ, et septem spicæ plenæ, septem ubertatis anni sunt : eamdemque vim somnii comprehendunt.

** Genesis 41:27

Septem quoque boves tenues atque macilentæ, quæ ascenderunt post eas, et septem spicæ tenues, et vento urente percussæ, septem anni venturæ sunt famis.

** Genesis 41:28

Qui hoc ordine complebuntur :

** Genesis 41:29

ecce septem anni venient fertilitatis magnæ in universa terra Ægypti,

** Genesis 41:30

quos sequentur septem anni alii tantæ sterilitatis, ut oblivioni tradatur cuncta retro abundantia : consumptura est enim fames omnem terram,

** Genesis 41:31

et ubertatis magnitudinem perditura est inopiæ magnitudo.

** Genesis 41:32

Quod autem vidisti secundo ad eamdem rem pertinens somnium : firmitatis indicium est, eo quod fiat sermo Dei, et velocius impleatur.

** Genesis 41:33

Nunc ergo provideat rex virum sapientem et industrium, et præficiat eum terræ Ægypti :

** Genesis 41:34

qui constituat præpositos per cunctas regiones : et quintam partem fructuum per septem annos fertilitatis,

** Genesis 41:35

qui jam nunc futuri sunt, congreget in horrea : et omne frumentum sub Pharaonis potestate condatur, serveturque in urbibus.

** Genesis 41:36

Et præparetur futuræ septem annorum fami, quæ oppressura est Ægyptum, et non consumetur terra inopia.

** Genesis 41:37

Placuit Pharaoni consilium et cunctis ministris ejus :

** Genesis 41:38

locutusque est ad eos : Num invenire poterimus talem virum, qui spiritu Dei plenus sit ?

** Genesis 41:39

Dixit ergo ad Joseph : Quia ostendit tibi Deus omnia quæ locutus es, numquid sapientiorem et consimilem tui invenire potero ?  

** Genesis 41:40

Tu eris super domum meam, et ad tui oris imperium cunctus populus obediet : uno tantum regni solio te præcedam.

** Genesis 41:41

Dixitque rursus Pharao ad Joseph : Ecce, constitui te super universam terram Ægypti.

** Genesis 41:42

Tulitque annulum de manu sua, et dedit eum in manu ejus : vestivitque eum stola byssina, et collo torquem auream circumposuit.

** Genesis 41:43

Fecitque eum ascendere super currum suum secundum, clamante præcone, ut omnes coram eo genu flecterent, et præpositum esse scirent universæ terræ Ægypti.

** Genesis 41:44

Dixit quoque rex ad Joseph : Ego sum Pharao : absque tuo imperio non movebit quisquam manum aut pedem in omni terra Ægypti.

** Genesis 41:45

Vertitque nomen ejus, et vocavit eum, lingua ægyptiaca, Salvatorem mundi. Deditque illi uxorem Aseneth filiam Putiphare sacerdotis Heliopoleos. Egressus est itaque Joseph ad terram Ægypti

** Genesis 41:46

(triginta autem annorum erat quando stetit in conspectu regis Pharaonis), et circuivit omnes regiones Ægypti.

** Genesis 41:47

Venitque fertilitas septem annorum : et in manipulos redactæ segetes congregatæ sunt in horrea Ægypti.

** Genesis 41:48

Omnis etiam frugum abundantia in singulis urbibus condita est.

** Genesis 41:49

Tantaque fuit abundantia tritici, ut arenæ maris coæquaretur, et copia mensuram excederet.

** Genesis 41:50

Nati sunt autem Joseph filii duo antequam veniret fames : quos peperit ei Aseneth filia Putiphare sacerdotis Heliopoleos.

** Genesis 41:51

Vocavitque nomen primogeniti Manasses, dicens : Oblivisci me fecit Deus omnium laborum meorum, et domus patris mei.

** Genesis 41:52

Nomen quoque secundi appellavit Ephraim, dicens : Crescere me fecit Deus in terra paupertatis meæ.

** Genesis 41:53

Igitur transactis septem ubertatis annis, qui fuerant in Ægypto,

** Genesis 41:54

cœperunt venire septem anni inopiæ, quos prædixerat Joseph : et in universo orbe fames prævaluit, in cuncta autem terra Ægypti panis erat.

** Genesis 41:55

Qua esuriente, clamavit populus ad Pharaonem, alimenta petens. Quibus ille respondit : Ite ad Joseph : et quidquid ipse vobis dixerit, facite.

** Genesis 41:56

Crescebat autem quotidie fames in omni terra : aperuitque Joseph universa horrea, et vendebat Ægyptiis : nam et illos oppresserat fames.

** Genesis 41:57

Omnesque provinciæ veniebant in Ægyptum, ut emerent escas, et malum inopiæ temperarent.   

* Genesis 42

** Genesis 42:1

Audiens autem Jacob quod alimenta venderentur in Ægypto, dixit filiis suis : Quare negligitis ?

** Genesis 42:2

audivi quod triticum venundetur in Ægypto : descendite, et emite nobis necessaria, ut possimus vivere, et non consumamur inopia.

** Genesis 42:3

Descendentes igitur fratres Joseph decem, ut emerent frumenta in Ægypto,

** Genesis 42:4

Benjamin domi retento a Jacob, qui dixerat fratribus ejus : Ne forte in itinere quidquam patiatur mali :

** Genesis 42:5

ingressi sunt terram Ægypti cum aliis qui pergebant ad emendum. Erat autem fames in terra Chanaan.

** Genesis 42:6

Et Joseph erat princeps in terra Ægypti, atque ad ejus nutum frumenta populis vendebantur. Cumque adorassent eum fratres sui,

** Genesis 42:7

et agnovisset eos, quasi ad alienos durius loquebatur, interrogans eos : Unde venistis ? Qui responderunt : De terra Chanaan, ut emamus victui necessaria.

** Genesis 42:8

Et tamen fratres ipse cognoscens, non est cognitus ab eis.

** Genesis 42:9

Recordatusque somniorum, quæ aliquando viderat, ait ad eos : Exploratores estis : ut videatis infirmiora terræ venistis.

** Genesis 42:10

Qui dixerunt : Non est ita, domine, sed servi tui venerunt ut emerent cibos.

** Genesis 42:11

Omnes filii unius viri sumus : pacifici venimus, nec quidquam famuli tui machinantur mali.

** Genesis 42:12

Quibus ille respondit : Aliter est : immunita terræ hujus considerare venistis.

** Genesis 42:13

At illi : Duodecim, inquiunt, servi tui, fratres sumus, filii viri unius in terra Chanaan : minimus cum patre nostro est, alius non est super.

** Genesis 42:14

Hoc est, ait, quod locutus sum : exploratores estis.

** Genesis 42:15

Jam nunc experimentum vestri capiam : per salutem Pharaonis non egrediemini hinc, donec veniat frater vester minimus.

** Genesis 42:16

Mittite ex vobis unum, et adducat eum : vos autem eritis in vinculis, donec probentur quæ dixistis utrum vera an falsa sint : alioquin per salutem Pharaonis exploratores estis.

** Genesis 42:17

Tradidit ergo illos custodiæ tribus diebus.

** Genesis 42:18

Die autem tertio eductis de carcere, ait : Facite quæ dixi, et vivetis : Deum enim timeo.

** Genesis 42:19

Si pacifici estis, frater vester unus ligetur in carcere : vos autem abite, et ferte frumenta quæ emistis, in domos vestras,

** Genesis 42:20

et fratrem vestrum minimum ad me adducite, ut possim vestros probare sermones, et non moriamini. Fecerunt ut dixerat,

** Genesis 42:21

et locuti sunt ad invicem : Merito hæc patimur, quia peccavimus in fratrem nostrum, videntes angustiam animæ illius, dum deprecaretur nos, et non audivimus : idcirco venit super nos ista tribulatio.

** Genesis 42:22

E quibus unus Ruben, ait : Numquid non dixi vobis : Nolite peccare in puerum : et non audistis me ? en sanguis ejus exquiritur.

** Genesis 42:23

Nesciebant autem quod intelligeret Joseph, eo quod per interpretem loqueretur ad eos.

** Genesis 42:24

Avertitque se parumper, et flevit : et reversus locutus est ad eos.  

** Genesis 42:25

Tollensque Simeon, et ligans illis præsentibus, jussit ministris ut implerent eorum saccos tritico, et reponerent pecunias singulorum in sacculis suis, datis supra cibariis in viam : qui fecerunt ita.

** Genesis 42:26

At illi portantes frumenta in asinis suis, profecti sunt.

** Genesis 42:27

Apertoque unus sacco, ut daret jumento pabulum in diversorio, contemplatus pecuniam in ore sacculi,

** Genesis 42:28

dixit fratribus suis : Reddita est mihi pecunia, en habetur in sacco. Et obstupefacti, turbatique, mutuo dixerunt : Quidnam est hoc quod fecit nobis Deus ?

** Genesis 42:29

Veneruntque ad Jacob patrem suum in terram Chanaan, et narraverunt ei omnia quæ accidissent sibi, dicentes :

** Genesis 42:30

Locutus est nobis dominus terræ dure, et putavit nos exploratores esse provinciæ.

** Genesis 42:31

Cui respondimus : Pacifici sumus, nec ullas molimur insidias.

** Genesis 42:32

Duodecim fratres uno patre geniti sumus : unus non est super, minimus cum patre nostro est in terra Chanaan.

** Genesis 42:33

Qui ait nobis : Sic probabo quod pacifici sitis : fratrem vestrum unum dimittite apud me, et cibaria domibus vestris necessaria sumite, et abite,

** Genesis 42:34

fratremque vestrum minimum adducite ad me, ut sciam quod non sitis exploratores : et istum, qui tenetur in vinculis, recipere possitis : ac deinceps quæ vultis, emendi habeatis licentiam.

** Genesis 42:35

His dictis, cum frumenta effunderent, singuli repererunt in ore saccorum ligatas pecunias, exterritisque simul omnibus,

** Genesis 42:36

dixit pater Jacob : Absque liberis me esse fecistis : Joseph non est super, Simeon tenetur in vinculis, et Benjamin auferetis : in me hæc omnia mala reciderunt.

** Genesis 42:37

Cui respondit Ruben : Duos filios meos interfice, si non reduxero illum tibi : trade illum in manu mea, et ego eum tibi restituam.

** Genesis 42:38

At ille : Non descendet, inquit, filius meus vobiscum : frater ejus mortuus est, et ipse solus remansit : si quid ei adversi acciderit in terra ad quam pergitis, deducetis canos meos cum dolore ad inferos.   

* Genesis 43

** Genesis 43:1

Interim fames omnem terram vehementer premebat.

** Genesis 43:2

Consumptisque cibis quos ex Ægypto detulerant, dixit Jacob ad filios suos : Revertimini, et emite nobis pauxillum escarum.

** Genesis 43:3

Respondit Judas : Denuntiavit nobis vir ille sub attestatione jurisjurandi, dicens : Non videbitis faciem meam, nisi fratrem vestrum minimum adduxeritis vobiscum.

** Genesis 43:4

Si ergo vis eum mittere nobiscum, pergemus pariter, et ememus tibi necessaria :

** Genesis 43:5

sin autem non vis, non ibimus : vir enim, ut sæpe diximus, denuntiavit nobis, dicens : Non videbitis faciem meam absque fratre vestro minimo.

** Genesis 43:6

Dixit eis Israël : In meam hoc fecistis miseriam, ut indicaretis ei et alium habere vos fratrem.

** Genesis 43:7

At illi responderunt : Interrogavit nos homo per ordinem nostram progeniem : si pater viveret : si haberemus fratrem : et nos respondimus ei consequenter juxta id quod fuerat sciscitatus : numquid scire poteramus quod dicturus esset : Adducite fratrem vestrum vobiscum ?

** Genesis 43:8

Judas quoque dixit patri suo : Mitte puerum mecum, ut proficiscamur, et possimus vivere : ne moriamur nos et parvuli nostri.

** Genesis 43:9

Ego suscipio puerum : de manu mea require illum : nisi reduxero, et reddidero eum tibi, ero peccati reus in te omni tempore.

** Genesis 43:10

Si non intercessisset dilatio, jam vice alter venissemus.

** Genesis 43:11

Igitur Israël pater eorum dixit ad eos : Si sic necesse est, facite quod vultis : sumite de optimis terræ fructibus in vasis vestris, et deferte viro munera, modicum resinæ, et mellis, et storacis, stactes, et terebinthi, et amygdalarum.

** Genesis 43:12

Pecuniam quoque duplicem ferte vobiscum : et illam, quam invenistis in sacculis, reportate, ne forte errore factum sit :

** Genesis 43:13

sed et fratrem vestrum tollite, et ite ad virum.

** Genesis 43:14

Deus autem meus omnipotens faciat vobis eum placabilem : et remittat vobiscum fratrem vestrum quem tenet, et hunc Benjamin : ego autem quasi orbatus absque liberis ero.  

** Genesis 43:15

Tulerunt ergo viri munera, et pecuniam duplicem, et Benjamin : descenderuntque in Ægyptum, et steterunt coram Joseph.

** Genesis 43:16

Quos cum ille vidisset et Benjamin simul, præcepit dispensatori domus suæ, dicens : Introduc viros domum, et occide victimas, et instrue convivium : quoniam mecum sunt comesturi meridie.

** Genesis 43:17

Fecit ille quod sibi fuerat imperatum, et introduxit viros domum.

** Genesis 43:18

Ibique exterriti, dixerunt mutuo : Propter pecuniam, quam retulimus prius in saccis nostris, introducti sumus : ut devolvat in nos calumniam, et violenter subjiciat servituti et nos, et asinos nostros.

** Genesis 43:19

Quam ob rem in ipsis foribus accedentes ad dispensatorem domus,

** Genesis 43:20

locuti sunt : Oramus, domine, ut audias nos. Jam ante descendimus ut emeremus escas :

** Genesis 43:21

quibus emptis, cum venissemus ad diversorium, aperuimus saccos nostros, et invenimus pecuniam in ore saccorum : quam nunc eodem pondere reportavimus.

** Genesis 43:22

Sed et aliud attulimus argentum, ut emamus quæ nobis necessaria sunt : non est in nostra conscientia quis posuerit eam in marsupiis nostris.

** Genesis 43:23

At ille respondit : Pax vobiscum, nolite timere : Deus vester, et Deus patris vestri, dedit vobis thesauros in saccis vestris : nam pecuniam, quam dedistis mihi, probatam ego habeo. Eduxitque ad eos Simeon.

** Genesis 43:24

Et introductis domum, attulit aquam, et laverunt pedes suos, deditque pabulum asinis eorum.

** Genesis 43:25

Illi vero parabant munera, donec ingrederetur Joseph meridie : audierant enim quod ibi comesturi essent panem.

** Genesis 43:26

Igitur ingressus est Joseph domum suam, obtuleruntque ei munera, tenentes in manibus suis : et adoraverunt proni in terram.

** Genesis 43:27

At ille, clementer resalutatis eis, interrogavit eos, dicens : Salvusne est pater vester senex, de quo dixeratis mihi ? adhuc vivit ?

** Genesis 43:28

Qui responderunt : Sospes est servus tuus pater noster, adhuc vivit. Et incurvati, adoraverunt eum.

** Genesis 43:29

Attollens autem Joseph oculos, vidit Benjamin fratrem suum uterinum, et ait : Iste est frater vester parvulus, de quo dixeratis mihi ? Et rursum : Deus, inquit, misereatur tui, fili mi.

** Genesis 43:30

Festinavitque, quia commota fuerant viscera ejus super fratre suo, et erumpebant lacrimæ : et introiens cubiculum flevit.

** Genesis 43:31

Rursumque lota facie egressus, continuit se, et ait : Ponite panes.

** Genesis 43:32

Quibus appositis, seorsum Joseph, et seorsum fratribus, Ægyptiis quoque qui vescebantur simul, seorsum (illicitum est enim Ægyptiis comedere cum Hebræis, et profanum putant hujuscemodi convivium)

** Genesis 43:33

sederunt coram eo, primogenitus juxta primogenita sua, et minimus juxta ætatem suam. Et mirabantur nimis,

** Genesis 43:34

sumptis partibus quas ab eo acceperant : majorque pars venit Benjamin, ita ut quinque partibus excederet. Biberuntque et inebriati sunt cum eo.   

* Genesis 44

** Genesis 44:1

Præcepit autem Joseph dispensatori domus suæ, dicens : Imple saccos eorum frumento, quantum possunt capere : et pone pecuniam singulorum in summitate sacci.

** Genesis 44:2

Scyphum autem meum argenteum, et pretium quod dedit tritici, pone in ore sacci junioris. Factumque est ita.

** Genesis 44:3

Et orto mane, dimissi sunt cum asinis suis.

** Genesis 44:4

Jamque urbem exierant, et processerant paululum : tunc Joseph accersito dispensatore domus, Surge, inquit, et persequere viros : et apprehensis dicito : Quare reddidistis malum pro bono ?

** Genesis 44:5

scyphus, quem furati estis, ipse est in quo bibit dominus meus, et in quo augurari solet : pessimam rem fecistis.

** Genesis 44:6

Fecit ille ut jusserat : et apprehensis per ordinem locutus est.

** Genesis 44:7

Qui responderunt : Quare sic loquitur dominus noster, ut servi tui tantum flagitii commiserint ?

** Genesis 44:8

pecuniam, quam invenimus in summitate saccorum, reportavimus ad te de terra Chanaan : et quomodo consequens est ut furati simus de domo domini tui aurum vel argentum ?

** Genesis 44:9

apud quemcumque fuerit inventum servorum tuorum quod quæris, moriatur, et nos erimus servi domini nostri.

** Genesis 44:10

Qui dixit eis : Fiat juxta vestram sententiam : apud quemcumque fuerit inventum, ipse sit servus meus, vos autem eritis innoxii.

** Genesis 44:11

Itaque festinato deponentes in terram saccos, aperuerunt singuli.

** Genesis 44:12

Quos scrutatus, incipiens a majore usque ad minimum, invenit scyphum in sacco Benjamin.

** Genesis 44:13

At illi, scissis vestibus, oneratisque rursum asinis, reversi sunt in oppidum.

** Genesis 44:14

Primusque Judas cum fratribus ingressus est ad Joseph (necdum enim de loco abierat) omnesque ante eum pariter in terram corruerunt.

** Genesis 44:15

Quibus ille ait : Cur sic agere voluistis ? an ignoratis quod non sit similis mei in augurandi scientia ?

** Genesis 44:16

Cui Judas : Quid respondebimus, inquit, domino meo ? vel quid loquemur, aut juste poterimus obtendere ? Deus invenit iniquitatem servorum tuorum : en omnes servi sumus domini mei, et nos, et apud quem inventus est scyphus.

** Genesis 44:17

Respondit Joseph : Absit a me ut sic agam : qui furatus est scyphum, ipse sit servus meus : vos autem abite liberi ad patrem vestrum.

** Genesis 44:18

Accedens autem propius Judas, confidenter ait : Oro, domine mi, loquatur servus tuus verbum in auribus tuis, et ne irascaris famulo tuo : tu es enim post Pharaonem

** Genesis 44:19

dominus meus. Interrogasti prius servos tuos : Habetis patrem aut fratrem ?

** Genesis 44:20

et nos respondimus tibi domino meo : Est nobis pater senex, et puer parvulus, qui in senectute illius natus est : cujus uterinus frater mortuus est : et ipsum solum habet mater sua, pater vero tenere diligit eum.

** Genesis 44:21

Dixistique servis tuis : Adducite eum ad me, et ponam oculos meos super illum.

** Genesis 44:22

Suggessimus domino meo : Non potest puer relinquere patrem suum : si enim illum dimiserit, morietur.

** Genesis 44:23

Et dixisti servis tuis : Nisi venerit frater vester minimus vobiscum, non videbitis amplius faciem meam.

** Genesis 44:24

Cum ergo ascendissemus ad famulum tuum patrem nostrum, narravimus ei omnia quæ locutus est dominus meus.

** Genesis 44:25

Et dixit pater noster : Revertimini, et emite nobis parum tritici.

** Genesis 44:26

Cui diximus : Ire non possumus : si frater noster minimus descenderit nobiscum, proficiscemur simul : alioquin illo absente, non audemus videre faciem viri.

** Genesis 44:27

Ad quæ ille respondit : Vos scitis quod duos genuerit mihi uxor mea.

** Genesis 44:28

Egressus est unus, et dixistis : Bestia devoravit eum : et hucusque non comparet.

** Genesis 44:29

Si tuleritis et istum, et aliquid ei in via contigerit, deducetis canos meos cum mœrore ad inferos.

** Genesis 44:30

Igitur si intravero ad servum tuum patrem nostrum, et puer defuerit (cum anima illius ex hujus anima pendeat),

** Genesis 44:31

videritque eum non esse nobiscum, morietur, et deducent famuli tui canos ejus cum dolore ad inferos.

** Genesis 44:32

Ego proprie servus tuus sim qui in meam hunc recepi fidem, et spopondi dicens : Nisi reduxero eum, peccati reus ero in patrem meum omni tempore.

** Genesis 44:33

Manebo itaque servus tuus pro puero in ministerio domini mei, et puer ascendat cum fratribus suis.

** Genesis 44:34

Non enim possum redire ad patrem meum, absente puero : ne calamitatis, quæ oppressura est patrem meum, testis assistam.   

* Genesis 45

** Genesis 45:1

Non se poterat ultra cohibere Joseph multis coram astantibus : unde præcepit ut egrederentur cuncti foras, et nullus interesset alienus agnitioni mutuæ.

** Genesis 45:2

Elevavitque vocem cum fletu, quam audierunt Ægyptii, omnisque domus Pharaonis.

** Genesis 45:3

Et dixit fratribus suis : Ego sum Joseph : adhuc pater meus vivit ? Non poterant respondere fratres nimio terrore perterriti.

** Genesis 45:4

Ad quos ille clementer : Accedite, inquit, ad me. Et cum accessissent prope : Ego sum, ait, Joseph, frater vester, quem vendidistis in Ægyptum.

** Genesis 45:5

Nolite pavere, neque vobis durum esse videatur quod vendidistis me in his regionibus : pro salute enim vestra misit me Deus ante vos in Ægyptum.

** Genesis 45:6

Biennium est enim quod cœpit fames esse in terra : et adhuc quinque anni restant, quibus nec arari poterit, nec meti.

** Genesis 45:7

Præmisitque me Deus ut reservemini super terram, et escas ad vivendum habere possitis.

** Genesis 45:8

Non vestro consilio, sed Dei voluntate huc missus sum : qui fecit me quasi patrem Pharaonis, et dominum universæ domus ejus, ac principem in omni terra Ægypti.

** Genesis 45:9

Festinate, et ascendite ad patrem meum, et dicetis ei : Hæc mandat filius tuus Joseph : Deus fecit me dominum universæ terræ Ægypti : descende ad me, ne moreris,

** Genesis 45:10

et habitabis in terra Gessen : erisque juxta me tu, et filii tui, et filii filiorum tuorum, oves tuæ, et armenta tua, et universa quæ possides :

** Genesis 45:11

ibique te pascam (adhuc enim quinque anni residui sunt famis) ne et tu pereas, et domus tua, et omnia quæ possides.

** Genesis 45:12

En oculi vestri, et oculi fratris mei Benjamin, vident quod os meum loquatur ad vos.

** Genesis 45:13

Nuntiate patri meo universam gloriam meam, et cuncta quæ vidistis in Ægypto : festinate, et adducite eum ad me.

** Genesis 45:14

Cumque amplexatus recidisset in collum Benjamin fratris sui, flevit : illo quoque similiter flente super collum ejus.

** Genesis 45:15

Osculatusque est Joseph omnes fratres suos, et ploravit super singulos : post quæ ausi sunt loqui ad eum.

** Genesis 45:16

Auditumque est, et celebri sermone vulgatum in aula regis : Venerunt fratres Joseph : et gavisus est Pharao, atque omnis familia ejus.

** Genesis 45:17

Dixitque ad Joseph ut imperaret fratribus suis, dicens : Onerantes jumenta, ite in terram Chanaan,

** Genesis 45:18

et tollite inde patrem vestrum et cognationem, et venite ad me : et ego dabo vobis omnia bona Ægypti, ut comedatis medullam terræ.

** Genesis 45:19

Præcipe etiam ut tollant plaustra de terra Ægypti, ad subvectionem parvulorum suorum ac conjugum : et dicito : Tollite patrem vestrum, et properate quantocius venientes.

** Genesis 45:20

Nec dimittatis quidquam de supellectili vestra : quia omnes opes Ægypti vestræ erunt.  

** Genesis 45:21

Feceruntque filii Israël ut eis mandatum fuerat. Quibus dedit Joseph plaustra, secundum Pharaonis imperium, et cibaria in itinere.

** Genesis 45:22

Singulis quoque proferri jussit binas stolas : Benjamin vero dedit trecentos argenteos cum quinque stolis optimis :

** Genesis 45:23

tantumdem pecuniæ et vestium mittens patri suo, addens et asinos decem, qui subveherent ex omnibus divitiis Ægypti, et totidem asinas, triticum in itinere, panesque portantes.

** Genesis 45:24

Dimisit ergo fratres suos, et proficiscentibus ait : Ne irascamini in via.

** Genesis 45:25

Qui ascendentes ex Ægypto, venerunt in terram Chanaan ad patrem suum Jacob.

** Genesis 45:26

Et nuntiaverunt ei, dicentes : Joseph filius tuus vivit : et ipse dominatur in omni terra Ægypti. Quo audito Jacob, quasi de gravi somno evigilans, tamen non credebat eis.

** Genesis 45:27

Illi e contra referebant omnem ordinem rei. Cumque vidisset plaustra et universa quæ miserat, revixit spiritus ejus,

** Genesis 45:28

et ait : Sufficit mihi si adhuc Joseph filius meus vivit : vadam, et videbo illum antequam moriar.   

* Genesis 46

** Genesis 46:1

Profectusque Israël cum omnibus quæ habebat, venit ad Puteum juramenti : et mactatis ibi victimis Deo patris sui Isaac,

** Genesis 46:2

audivit eum per visionem noctis vocantem se, et dicentem sibi : Jacob, Jacob. Cui respondit : Ecce adsum.

** Genesis 46:3

Ait illi Deus : Ego sum fortissimus Deus patris tui : noli timere, descende in Ægyptum, quia in gentem magnam faciam te ibi.

** Genesis 46:4

Ego descendam tecum illuc, et ego inde adducam te revertentem : Joseph quoque ponet manus suas super oculos tuos.

** Genesis 46:5

Surrexit autem Jacob a Puteo juramenti : tuleruntque eum filii cum parvulis et uxoribus suis in plaustris quæ miserat Pharao ad portandum senem,

** Genesis 46:6

et omnia quæ possederat in terra Chanaan : venitque in Ægyptum cum omni semine suo,

** Genesis 46:7

filii ejus, et nepotes, filiæ, et cuncta simul progenies.

** Genesis 46:8

Hæc sunt autem nomina filiorum Israël, qui ingressi sunt in Ægyptum, ipse cum liberis suis. Primogenitus Ruben.

** Genesis 46:9

Filii Ruben : Henoch et Phallu et Hesron et Charmi.

** Genesis 46:10

Filii Simeon : Jamuel et Jamin et Ahod, et Jachin et Sohar, et Saul filius Chanaanitidis.

** Genesis 46:11

Filii Levi : Gerson et Caath et Merari.

** Genesis 46:12

Filii Juda : Her et Onan et Sela et Phares et Zara ; mortui sunt autem Her et Onan in terra Chanaan. Natique sunt filii Phares : Hesron et Hamul.

** Genesis 46:13

Filii Issachar : Thola et Phua et Job et Semron.

** Genesis 46:14

Filii Zabulon : Sared et Elon et Jahelel.

** Genesis 46:15

Hi filii Liæ quos genuit in Mesopotamia Syriæ cum Dina filia sua : omnes animæ filiorum ejus et filiarum, triginta tres.

** Genesis 46:16

Filii Gad : Sephion et Haggi et Suni et Esebon et Heri et Arodi et Areli.

** Genesis 46:17

Filii Aser : Jamne et Jesua et Jessui et Beria, Sara quoque soror eorum. Filii Beria : Heber et Melchiel.

** Genesis 46:18

Hi filii Zelphæ, quam dedit Laban Liæ filiæ suæ : et hos genuit Jacob sedecim animas.

** Genesis 46:19

Filii Rachel uxoris Jacob : Joseph et Benjamin.

** Genesis 46:20

Natique sunt Joseph filii in terra Ægypti, quos genuit ei Aseneth filia Putiphare sacerdotis Heliopoleos : Manasses et Ephraim.

** Genesis 46:21

Filii Benjamin : Bela et Bechor et Asbel et Gera et Naaman et Echi et Ros et Mophim et Ophim et Ared.

** Genesis 46:22

Hi filii Rachel quos genuit Jacob : omnes animæ, quatuordecim.

** Genesis 46:23

Filii Dan : Husim.

** Genesis 46:24

Filii Nephthali : Jasiel et Guni et Jeser et Sallem.

** Genesis 46:25

Hi filii Balæ, quam dedit Laban Racheli filiæ suæ : et hos genuit Jacob : omnes animæ, septem.

** Genesis 46:26

Cunctæ animæ, quæ ingressæ sunt cum Jacob in Ægyptum, et egressæ sunt de femore illius, absque uxoribus filiorum ejus, sexaginta sex.

** Genesis 46:27

Filii autem Joseph, qui nati sunt ei in terra Ægypti, animæ duæ. Omnes animæ domus Jacob, quæ ingressæ sunt in Ægyptum, fuere septuaginta.  

** Genesis 46:28

Misit autem Judam ante se ad Joseph, ut nuntiaret ei, et occurreret in Gessen.

** Genesis 46:29

Quo cum pervenisset, juncto Joseph curro suo, ascendit obviam patri suo ad eumdem locum : vidensque eum, irruit super collum ejus, et inter amplexus flevit.

** Genesis 46:30

Dixitque pater ad Joseph : Jam lætus moriar, quia vidi faciem tuam, et superstitem te relinquo.

** Genesis 46:31

At ille locutus est ad fratres suos, et ad omnem domum patris sui : Ascendam, et nuntiabo Pharaoni, dicamque ei : Fratres mei, et domus patris mei, qui erant in terra Chanaan, venerunt ad me :

** Genesis 46:32

et sunt viri pastores ovium, curamque habent alendorum gregum : pecora sua, et armenta, et omnia quæ habere potuerunt, adduxerunt secum.

** Genesis 46:33

Cumque vocaverit vos, et dixerit : Quod est opus vestrum ?

** Genesis 46:34

respondebitis : Viri pastores sumus servi tui, ab infantia nostra usque in præsens, et nos et patres nostri. Hæc autem dicetis, ut habitare possitis in terra Gessen : quia detestantur Ægyptii omnes pastores ovium.   

* Genesis 47

** Genesis 47:1

Ingressus ergo Joseph nuntiavit Pharaoni, dicens : Pater meus et fratres, oves eorum et armenta, et cuncta quæ possident, venerunt de terra Chanaan : et ecce consistunt in terra Gessen.

** Genesis 47:2

Extremos quoque fratrum suorum quinque viros constituit coram rege :

** Genesis 47:3

quos ille interrogavit : Quid habetis operis ? Responderunt : Pastores ovium sumus servi tui, et nos et patres nostri.

** Genesis 47:4

Ad peregrinandum in terra tua venimus : quoniam non est herba gregibus servorum tuorum, ingravescente fame in terra Chanaan : petimusque ut esse nos jubeas servos tuos in terra Gessen.

** Genesis 47:5

Dixit itaque rex ad Joseph : Pater tuus et fratres tui venerunt ad te.

** Genesis 47:6

Terra Ægypti in conspectu tuo est : in optimo loco fac eos habitare, et trade eis terram Gessen. Quod si nosti in eis esse viros industrios, constitue illos magistros pecorum meorum.

** Genesis 47:7

Post hæc introduxit Joseph patrem suum ad regem, et statuit eum coram eo : qui benedicens illi,

** Genesis 47:8

et interrogatus ab eo : Quot sunt dies annorum vitæ tuæ ?

** Genesis 47:9

respondit : Dies peregrinationis meæ centum triginta annorum sunt, parvi et mali, et non pervenerunt usque ad dies patrum meorum quibus peregrinati sunt.

** Genesis 47:10

Et benedicto rege, egressus est foras.

** Genesis 47:11

Joseph vero patri et fratribus suis dedit possessionem in Ægypto in optimo terræ loco, Ramesses, ut præceperat Pharao.

** Genesis 47:12

Et alebat eos, omnemque domum patris sui, præbens cibaria singulis.  

** Genesis 47:13

In toto enim orbe panis deerat, et oppresserat fames terram, maxime Ægypti et Chanaan.

** Genesis 47:14

E quibus omnem pecuniam congregavit pro venditione frumenti, et intulit eam in ærarium regis.

** Genesis 47:15

Cumque defecisset emptoribus pretium, venit cuncta Ægyptus ad Joseph, dicens : Da nobis panes : quare morimur coram te, deficiente pecunia ?

** Genesis 47:16

Quibus ille respondit : Adducite pecora vestra, et dabo vobis pro eis cibos, si pretium non habetis.

** Genesis 47:17

Quæ cum adduxissent, dedit eis alimenta pro equis, et ovibus, et bobus, et asinis : sustentavitque eos illo anno pro commutatione pecorum.

** Genesis 47:18

Venerunt quoque anno secundo, et dixerunt ei : Non celabimus dominum nostrum quod deficiente pecunia, pecora simul defecerunt : nec clam te est, quod absque corporibus et terra nihil habeamus.

** Genesis 47:19

Cur ergo moriemur te vidente ? et nos et terra nostra tui erimus : eme nos in servitutem regiam, et præbe semina, ne pereunte cultore redigatur terra in solitudinem.

** Genesis 47:20

Emit igitur Joseph omnem terram Ægypti, vendentibus singulis possessiones suas præ magnitudine famis. Subjecitque eam Pharaoni,

** Genesis 47:21

et cunctos populos ejus a novissimis terminis Ægypti usque ad extremos fines ejus,

** Genesis 47:22

præter terram sacerdotum, quæ a rege tradita fuerat eis : quibus et statuta cibaria ex horreis publicis præbebantur, et idcirco non sunt compulsi vendere possessiones suas.

** Genesis 47:23

Dixit ergo Joseph ad populos : En ut cernitis, et vos et terram vestram Pharao possidet : accipite semina, et serite agros,

** Genesis 47:24

ut fruges habere possitis. Quintam partem regi dabitis : quatuor reliquas permitto vobis in sementem, et in cibum familiis et liberis vestris.

** Genesis 47:25

Qui responderunt : Salus nostra in manu tua est : respiciat nos tantum dominus noster, et læti serviemus regi.

** Genesis 47:26

Ex eo tempore usque in præsentem diem, in universa terra Ægypti regibus quinta pars solvitur, et factum est quasi in legem, absque terra sacerdotali, quæ libera ab hac conditione fuit.  

** Genesis 47:27

Habitavit ergo Israël in Ægypto, id est, in terra Gessen, et possedit eam : auctusque est, et multiplicatus nimis.

** Genesis 47:28

Et vixit in ea decem et septem annis : factique sunt omnes dies vitæ illius, centum quadraginta septem annorum.

** Genesis 47:29

Cumque appropinquare cerneret diem mortis suæ, vocavit filium suum Joseph, et dixit ad eum : Si inveni gratiam in conspectu tuo, pone manum tuam sub femore meo : et facies mihi misericordiam et veritatem, ut non sepelias me in Ægypto :

** Genesis 47:30

sed dormiam cum patribus meis, et auferas me de terra hac, condasque in sepulchro majorum meorum. Cui respondit Joseph : Ego faciam quod jussisti.

** Genesis 47:31

Et ille : Jura ergo, inquit, mihi. Quo jurante, adoravit Israël Deum, conversus ad lectuli caput.   

* Genesis 48

** Genesis 48:1

His ita transactis, nuntiatum est Joseph quod ægrotaret pater suus : qui, assumptis duobus filiis Manasse et Ephraim, ire perrexit.

** Genesis 48:2

Dictumque est seni : Ecce filius tuus Joseph venit ad te. Qui confortatus sedit in lectulo.

** Genesis 48:3

Et ingresso ad se ait : Deus omnipotens apparuit mihi in Luza, quæ est in terra Chanaan : benedixitque mihi,

** Genesis 48:4

et ait : Ego te augebo et multiplicabo, et faciam te in turbas populorum : daboque tibi terram hanc, et semini tuo post te in possessionem sempiternam.

** Genesis 48:5

Duo ergo filii tui, qui nati sunt tibi in terra Ægypti antequam huc venirem ad te, mei erunt : Ephraim et Manasses, sicut Ruben et Simeon reputabuntur mihi.

** Genesis 48:6

Reliquos autem quos genueris post eos, tui erunt, et nomine fratrum suorum vocabuntur in possessionibus suis.

** Genesis 48:7

Mihi enim, quando veniebam de Mesopotamia, mortua est Rachel in terra Chanaan in ipso itinere, eratque vernum tempus : et ingrediebar Ephratam, et sepelivi eam juxta viam Ephratæ, quæ alio nomine appellatur Bethlehem.

** Genesis 48:8

Videns autem filios ejus dixit ad eum : Qui sunt isti ?

** Genesis 48:9

Respondit : Filii mei sunt, quos donavit mihi Deus in hoc loco. Adduc, inquit, eos ad me, ut benedicam illis.

** Genesis 48:10

Oculi enim Israël caligabant præ nimia senectute, et clare videre non poterat. Applicitosque ad se, deosculatus et circumplexus eos,

** Genesis 48:11

dixit ad filium suum : Non sum fraudatus aspectu tuo : insuper ostendit mihi Deus semen tuum.

** Genesis 48:12

Cumque tulisset eos Joseph de gremio patris, adoravit pronus in terram.

** Genesis 48:13

Et posuit Ephraim ad dexteram suam, id est, ad sinistram Israël : Manassen vero in sinistra sua, ad dexteram scilicet patris, applicuitque ambos ad eum.

** Genesis 48:14

Qui extendens manum dexteram, posuit super caput Ephraim minoris fratris : sinistram autem super caput Manasse qui major natu erat, commutans manus.

** Genesis 48:15

Benedixitque Jacob filiis Joseph, et ait : Deus, in cujus conspectu ambulaverunt patres mei Abraham, et Isaac ; Deus qui pascit me ab adolescentia mea usque in præsentem diem :

** Genesis 48:16

angelus, qui eruit me de cunctis malis, benedicat pueris istis : et invocetur super eos nomen meum, nomina quoque patrum meorum Abraham et Isaac, et crescant in multitudinem super terram.

** Genesis 48:17

Videns autem Joseph quod posuisset pater suus dexteram manum super caput Ephraim, graviter accepit : et apprehensam manum patris levare conatus est de capite Ephraim, et transferre super caput Manasse.

** Genesis 48:18

Dixitque ad patrem : Non ita convenit, pater : quia hic est primogenitus, pone dexteram tuam super caput ejus.

** Genesis 48:19

Qui renuens, ait : Scio, fili mi, scio : et iste quidem erit in populos, et multiplicabitur : sed frater ejus minor, major erit illo : et semen illius crescet in gentes.

** Genesis 48:20

Benedixitque eis in tempore illo, dicens : In te benedicetur Israël, atque dicetur : Faciat tibi Deus sicut Ephraim, et sicut Manasse. Constituitque Ephraim ante Manassen.

** Genesis 48:21

Et ait ad Joseph filium suum : En ego morior, et erit Deus vobiscum, reducetque vos ad terram patrum vestrorum.

** Genesis 48:22

Do tibi partem unam extra fratres tuos, quam tuli de manu Amorrhæi in gladio et arcu meo.   

* Genesis 49

** Genesis 49:1

Vocavit autem Jacob filios suos, et ait eis : Congregamini, ut annuntiem quæ ventura sunt vobis in diebus novissimis.  

** Genesis 49:2

Congregamini, et audite, filii Jacob,  audite Israël patrem vestrum : 

** Genesis 49:3

Ruben, primogenitus meus,  tu fortitudo mea, et principium doloris mei ;  prior in donis, major in imperio. 

** Genesis 49:4

Effusus es sicut aqua, non crescas : quia ascendisti cubile patris tui,  et maculasti stratum ejus. 

** Genesis 49:5

Simeon et Levi fratres  vasa iniquitatis bellantia. 

** Genesis 49:6

In consilium eorum non veniat anima mea,  et in cœtu illorum non sit gloria mea :  quia in furore suo occiderunt virum,  et in voluntate sua suffoderunt murum. 

** Genesis 49:7

Maledictus furor eorum, quia pertinax :  et indignatio eorum, quia dura :  dividam eos in Jacob,  et dispergam eos in Israël. 

** Genesis 49:8

Juda, te laudabunt fratres tui :  manus tua in cervicibus inimicorum tuorum,  adorabunt te filii patris tui. 

** Genesis 49:9

Catulus leonis Juda :  ad prædam, fili mi, ascendisti :  requiescens accubuisti ut leo,  et quasi leæna : quis suscitabit eum ? 

** Genesis 49:10

Non auferetur sceptrum de Juda,  et dux de femore ejus,  donec veniat qui mittendus est,  et ipse erit expectatio gentium. 

** Genesis 49:11

Ligans ad vineam pullum suum,  et ad vitem, o fili mi, asinam suam,  lavabit in vino stolam suam  et in sanguine uvæ pallium suum. 

** Genesis 49:12

Pulchriores sunt oculi ejus vino,  et dentes ejus lacte candidiores. 

** Genesis 49:13

Zabulon in littore maris habitabit,  et in statione navium  pertingens usque ad Sidonem. 

** Genesis 49:14

Issachar asinus fortis  accubans inter terminos. 

** Genesis 49:15

Vidit requiem, quod esset bona  et terram, quod optima :  et supposuit humerum suum ad portandum,  factusque est tributis serviens. 

** Genesis 49:16

Dan judicabit populum suum  sicut et alia tribus in Israël. 

** Genesis 49:17

Fiat Dan coluber in via,  cerastes in semita,  mordens ungulas equi,  ut cadat ascensor ejus retro. 

** Genesis 49:18

Salutare tuum expectabo, Domine. 

** Genesis 49:19

Gad, accinctus præliabitur ante eum :  et ipse accingetur retrorsum. 

** Genesis 49:20

Aser, pinguis panis ejus,  et præbebit delicias regibus. 

** Genesis 49:21

Nephthali, cervus emissus,  et dans eloquia pulchritudinis. 

** Genesis 49:22

Filius accrescens Joseph, filius accrescens et decorus aspectu :  filiæ discurrerunt super murum. 

** Genesis 49:23

Sed exasperaverunt eum et jurgati sunt,  invideruntque illi habentes jacula. 

** Genesis 49:24

Sedit in forti arcus ejus,  et dissoluta sunt vincula brachiorum et manuum illius  per manus potentis Jacob :  inde pastor egressus est, lapis Israël. 

** Genesis 49:25

Deus patris tui erit adjutor tuus,  et omnipotens benedicet tibi  benedictionibus cæli desuper, benedictionibus abyssi jacentis deorsum,  benedictionibus uberum et vulvæ. 

** Genesis 49:26

Benedictiones patris tui confortatæ sunt benedictionibus patrum ejus,  donec veniret desiderium collium æternorum :  fiant in capite Joseph,  et in vertice Nazaræi inter fratres suos. 

** Genesis 49:27

Benjamin lupus rapax,  mane comedat prædam,  et vespere dividet spolia.

** Genesis 49:28

Omnes hi in tribubus Israël duodecim : hæc locutus est eis pater suus, benedixitque singulis benedictionibus propriis.  

** Genesis 49:29

Et præcepit eis, dicens : Ego congregor ad populum meum : sepelite me cum patribus meis in spelunca duplici quæ est in agro Ephron Hethæi,

** Genesis 49:30

contra Mambre in terra Chanaan, quam emit Abraham cum agro ab Ephron Hethæo in possessionem sepulchri.

** Genesis 49:31

Ibi sepelierunt eum, et Saram uxorem ejus : ibi sepultus est Isaac cum Rebecca conjuge sua : ibi et Lia condita jacet.

** Genesis 49:32

Finitisque mandatis quibus filios instruebat, collegit pedes suos super lectulum, et obiit : appositusque est ad populum suum.   

* Genesis 50

** Genesis 50:1

Quod cernens Joseph, ruit super faciem patris, flens et deosculans eum.

** Genesis 50:2

Præcepitque servis suis medicis ut aromatibus condirent patrem.

** Genesis 50:3

Quibus jussa explentibus, transierunt quadraginta dies : iste quippe mos erat cadaverum conditorum : flevitque eum Ægyptus septuaginta diebus.

** Genesis 50:4

Et expleto planctus tempore, locutus est Joseph ad familiam Pharaonis : Si inveni gratiam in conspectu vestro, loquimini in auribus Pharaonis :

** Genesis 50:5

eo quod pater meus adjuraverit me dicens : En morior : in sepulchro meo, quod fodi mihi in terra Chanaan, sepelies me. Ascendam igitur, et sepeliam patrem meum, ac revertar.

** Genesis 50:6

Dixitque ei Pharao : Ascende, et sepeli patrem tuum sicut adjuratus es.

** Genesis 50:7

Quo ascendente, ierunt cum eo omnes senes domus Pharaonis, cunctique majores natu terræ Ægypti :

** Genesis 50:8

domus Joseph cum fratribus suis, absque parvulis, et gregibus atque armentis, quæ dereliquerant in terra Gessen.

** Genesis 50:9

Habuit quoque in comitatu currus et equites : et facta est turba non modica.

** Genesis 50:10

Veneruntque ad Aream Atad, quæ sita est trans Jordanem : ubi celebrantes exequias planctu magno atque vehementi impleverunt septem dies.

** Genesis 50:11

Quod cum vidissent habitatores terræ Chanaan, dixerunt : Planctus magnus est iste Ægyptiis. Et idcirco vocatum est nomen loci illius, Planctus Ægypti.

** Genesis 50:12

Fecerunt ergo filii Jacob sicut præceperat eis :

** Genesis 50:13

et portantes eum in terram Chanaan, sepelierunt eum in spelunca duplici, quam emerat Abraham cum agro in possessionem sepulchri ab Ephron Hethæo, contra faciem Mambre.

** Genesis 50:14

Reversusque est Joseph in Ægyptum cum fratribus suis, et omni comitatu, sepulto patre.  

** Genesis 50:15

Quo mortuo, timentes fratres ejus, et mutuo colloquentes : Ne forte memor sit injuriæ quam passus est, et reddat nobis omne malum quod fecimus,

** Genesis 50:16

mandaverunt ei dicentes : Pater tuus præcepit nobis antequam moreretur,

** Genesis 50:17

ut hæc tibi verbis illius diceremus : Obsecro ut obliviscaris sceleris fratrum tuorum, et peccati atque malitiæ quam exercuerunt in te : nos quoque oramus ut servis Dei patris tui dimittas iniquitatem hanc. Quibus auditis flevit Joseph.

** Genesis 50:18

Veneruntque ad eum fratres sui : et proni adorantes in terram, dixerunt : Servi tui sumus.

** Genesis 50:19

Quibus ille respondit : Nolite timere : num Dei possumus resistere voluntati ?

** Genesis 50:20

Vos cogitastis de me malum : sed Deus vertit illud in bonum, ut exaltaret me, sicut in præsentiarum cernitis, et salvos faceret multos populos.

** Genesis 50:21

Nolite timere : ego pascam vos et parvulos vestros : consolatusque est eos, et blande ac leniter est locutus.

** Genesis 50:22

Et habitavit in Ægypto cum omni domo patris sui : vixitque centum decem annis. Et vidit Ephraim filios usque ad tertiam generationem. Filii quoque Machir filii Manasse nati sunt in genibus Joseph.

** Genesis 50:23

Quibus transactis, locutus est fratribus suis : Post mortem meam Deus visitabit vos, et ascendere vos faciet de terra ista ad terram quam juravit Abraham, Isaac et Jacob.

** Genesis 50:24

Cumque adjurasset eos atque dixisset : Deus visitabit vos, asportate ossa mea vobiscum de loco isto :

** Genesis 50:25

mortuus est, expletis centum decem vitæ suæ annis. Et conditus aromatibus, repositus est in loculo in Ægypto.    

