* Habakkuk 1

** Habakkuk 1:1

Onus quod vidit Habacuc propheta.  

** Habakkuk 1:2

Usquequo, Domine, clamabo,  et non exaudies ?  vociferabor ad te, vim patiens,  et non salvabis ? 

** Habakkuk 1:3

Quare ostendisti mihi iniquitatem et laborem,  videre prædam et injustitiam contra me ?  Et factum est judicium, et contradictio potentior. 

** Habakkuk 1:4

Propter hoc lacerata est lex,  et non pervenit usque ad finem judicium ;  quia impius prævalet adversus justum,  propterea egreditur judicium perversum. 

** Habakkuk 1:5

Aspicite in gentibus, et videte ;  admiramini, et obstupescite :  quia opus factum est in diebus vestris,  quod nemo credet cum narrabitur. 

** Habakkuk 1:6

Quia ecce ego suscitabo Chaldæos,  gentem amaram et velocem,  ambulantem super latitudinem terræ,  ut possideat tabernacula non sua. 

** Habakkuk 1:7

Horribilis et terribilis est :  ex semetipsa judicium et onus ejus egredietur. 

** Habakkuk 1:8

Leviores pardis equi ejus,  et velociores lupis vespertinis :  et diffundentur equites ejus :  equites namque ejus de longe venient ;  volabunt quasi aquila festinans ad comedendum. 

** Habakkuk 1:9

Omnes ad prædam venient,  facies eorum ventus urens ;  et congregabit quasi arenam captivitatem. 

** Habakkuk 1:10

Et ipse de regibus triumphabit,  et tyranni ridiculi ejus erunt ;  ipse super omnem munitionem ridebit,  et comportabit aggerem, et capiet eam. 

** Habakkuk 1:11

Tunc mutabitur spiritus, et pertransibit, et corruet :  hæc est fortitudo ejus dei sui. 

** Habakkuk 1:12

Numquid non tu a principio,  Domine, Deus meus, sancte meus,  et non moriemur ?  Domine, in judicium posuisti eum,  et fortem, ut corriperes, fundasti eum. 

** Habakkuk 1:13

Mundi sunt oculi tui, ne videas malum,  et respicere ad iniquitatem non poteris.  Quare respicis super iniqua agentes,  et taces devorante impio justiorem se ? 

** Habakkuk 1:14

Et facies homines quasi pisces maris,  et quasi reptile non habens principem. 

** Habakkuk 1:15

Totum in hamo sublevavit,  traxit illud in sagena sua,  et congregavit in rete suum.  Super hoc lætabitur, et exsultabit. 

** Habakkuk 1:16

Propterea immolabit sagenæ suæ,  et sacrificabit reti suo,  quia in ipsis incrassata est pars ejus,  et cibus ejus electus. 

** Habakkuk 1:17

Propter hoc ergo expandit sagenam suam,  et semper interficere gentes non parcet.  

* Habakkuk 2

** Habakkuk 2:1

Super custodiam meam stabo,  et figam gradum super munitionem :  et contemplabor ut videam quid dicatur mihi,  et quid respondeam ad arguentem me.  

** Habakkuk 2:2

Et respondit mihi Dominus, et dixit :   Scribe visum, et explana eum super tabulas,  ut percurrat qui legerit eum. 

** Habakkuk 2:3

Quia adhuc visus procul ;  et apparebit in finem, et non mentietur :  si moram fecerit, exspecta illum,  quia veniens veniet, et non tardabit. 

** Habakkuk 2:4

Ecce qui incredulus est, non erit recta anima ejus in semetipso ;  justus autem in fide sua vivet. 

** Habakkuk 2:5

Et quomodo vinum potantem decipit,  sic erit vir superbus, et non decorabitur :  qui dilatavit quasi infernus animam suam,  et ipse quasi mors, et non adimpletur :  et congregabit ad se omnes gentes,  et coacervabit ad se omnes populos. 

** Habakkuk 2:6

Numquid non omnes isti super eum parabolam sument,  et loquelam ænigmatum ejus, et dicetur :  Væ ei qui multiplicat non sua ?  usquequo et aggravat contra se densum lutum ? 

** Habakkuk 2:7

Numquid non repente consurgent qui mordeant te,  et suscitabuntur lacerantes te,  et eris in rapinam eis ? 

** Habakkuk 2:8

Quia tu spoliasti gentes multas,  spoliabunt te omnes qui reliqui fuerint de populis,  propter sanguinem hominis,  et iniquitatem terræ, civitatis, et omnium habitantium in ea. 

** Habakkuk 2:9

Væ qui congregat avaritiam malam domui suæ,  ut sit in excelso nidus ejus,  et liberari se putat de manu mali ! 

** Habakkuk 2:10

Cogitasti confusionem domui tuæ ;  concidisti populos multos,  et peccavit anima tua. 

** Habakkuk 2:11

Quia lapis de pariete clamabit,  et lignum, quod inter juncturas ædificiorum est, respondebit. 

** Habakkuk 2:12

Væ qui ædificat civitatem in sanguinibus,  et præparat urbem in iniquitate ! 

** Habakkuk 2:13

Numquid non hæc sunt a Domino exercituum ?  laborabunt enim populi in multo igne,  et gentes in vacuum, et deficient. 

** Habakkuk 2:14

Quia replebitur terra, ut cognoscant gloriam Domini,  quasi aquæ operientes mare. 

** Habakkuk 2:15

Væ qui potum dat amico suo mittens fel suum,  et inebrians ut aspiciat nuditatem ejus ! 

** Habakkuk 2:16

Repletus es ignominia pro gloria ;  bibe tu quoque, et consopire.  Circumdabit te calix dexteræ Domini,  et vomitus ignominiæ super gloriam tuam. 

** Habakkuk 2:17

Quia iniquitas Libani operiet te,  et vastitas animalium deterrebit eos  de sanguinibus hominum,  et iniquitate terræ, et civitatis, et omnium habitantium in ea. 

** Habakkuk 2:18

Quid prodest sculptile, quia sculpsit illud fictor suus,  conflatile, et imaginem falsam ?  quia speravit in figmento fictor ejus, ut faceret simulacra muta. 

** Habakkuk 2:19

Væ qui dicit ligno : Expergiscere ;  Surge, lapidi tacenti !  Numquid ipse docere poterit ?  ecce iste coopertus est auro et argento,  et omnis spiritus non est in visceribus ejus. 

** Habakkuk 2:20

Dominus autem in templo sancto suo :  sileat a facie ejus omnis terra !  

* Habakkuk 3

** Habakkuk 3:1

Oratio Habacuc prophetæ, pro ignorantiis.  

** Habakkuk 3:2

Domine, audivi auditionem tuam, et timui.  Domine, opus tuum, in medio annorum vivifica illud ;  in medio annorum notum facies :  cum iratus fueris, misericordiæ recordaberis. 

** Habakkuk 3:3

Deus ab austro veniet,  et Sanctus de monte Pharan :  operuit cælos gloria ejus,  et laudis ejus plena est terra. 

** Habakkuk 3:4

Splendor ejus ut lux erit,  cornua in manibus ejus :  ibi abscondita est fortitudo ejus. 

** Habakkuk 3:5

Ante faciem ejus ibit mors,  et egredietur diabolus ante pedes ejus. 

** Habakkuk 3:6

Stetit, et mensus est terram ;  aspexit, et dissolvit gentes,  et contriti sunt montes sæculi :  incurvati sunt colles mundi ab itineribus æternitatis ejus. 

** Habakkuk 3:7

Pro iniquitate vidi tentoria Æthiopiæ ;  turbabuntur pelles terræ Madian. 

** Habakkuk 3:8

Numquid in fluminibus iratus es, Domine ?  aut in fluminibus furor tuus ?  vel in mari indignatio tua ?  Qui ascendes super equos tuos, et quadrigæ tuæ salvatio. 

** Habakkuk 3:9

Suscitans suscitabis arcum tuum,  juramenta tribubus quæ locutus es ;  fluvios scindes terræ. 

** Habakkuk 3:10

Viderunt te, et doluerunt montes ;  gurges aquarum transiit :  dedit abyssus vocem suam ;  altitudo manus suas levavit. 

** Habakkuk 3:11

Sol et luna steterunt in habitaculo suo :  in luce sagittarum tuarum ibunt,  in splendore fulgurantis hastæ tuæ. 

** Habakkuk 3:12

In fremitu conculcabis terram ;  in furore obstupefacies gentes. 

** Habakkuk 3:13

Egressus es in salutem populi tui,  in salutem cum christo tuo :  percussisti caput de domo impii,  denudasti fundamentum ejus usque ad collum. 

** Habakkuk 3:14

Maledixisti sceptris ejus,  capiti bellatorum ejus,  venientibus ut turbo ad dispergendum me :  exsultatio eorum, sicut ejus qui devorat pauperem in abscondito. 

** Habakkuk 3:15

Viam fecisti in mari equis tuis,  in luto aquarum multarum. 

** Habakkuk 3:16

Audivi, et conturbatus est venter meus ;  a voce contremuerunt labia mea.  Ingrediatur putredo in ossibus meis,  et subter me scateat :  ut requiescam in die tribulationis,  ut ascendam ad populum accinctum nostrum. 

** Habakkuk 3:17

Ficus enim non florebit,  et non erit germen in vineis ;  mentietur opus olivæ,  et arva non afferent cibum :  abscindetur de ovili pecus,  et non erit armentum in præsepibus. 

** Habakkuk 3:18

Ego autem in Domino gaudebo ;  et exsultabo in Deo Jesu meo. 

** Habakkuk 3:19

Deus Dominus fortitudo mea,  et ponet pedes meos quasi cervorum :  et super excelsa mea deducet me  victor in psalmis canentem.    

