* Hebrews 1

** Hebrews 1:1

Multifariam, multisque modis olim Deus loquens patribus in prophetis :

** Hebrews 1:2

novissime, diebus istis locutus est nobis in Filio, quem constituit hæredem universorum, per quem fecit et sæcula :

** Hebrews 1:3

qui cum sit splendor gloriæ, et figura substantiæ ejus, portansque omnia verbo virtutis suæ, purgationem peccatorum faciens, sedet ad dexteram majestatis in excelsis :

** Hebrews 1:4

tanto melior angelis effectus, quanto differentius præ illis nomen hæreditavit.

** Hebrews 1:5

Cui enim dixit aliquando angelorum : Filius meus es tu, ego hodie genui te ? Et rursum : Ego ero illi in patrem, et ipse erit mihi in filium ?

** Hebrews 1:6

Et cum iterum introducit primogenitum in orbem terræ, dicit : Et adorent eum omnes angeli Dei.

** Hebrews 1:7

Et ad angelos quidem dicit : Qui facit angelos suos spiritus, et ministros suos flammam ignis.

** Hebrews 1:8

Ad Filium autem : Thronus tuus Deus in sæculum sæculi : virga æquitatis, virga regni tui.

** Hebrews 1:9

Dilexisti justitiam, et odisti iniquitatem : propterea unxit te Deus, Deus tuus, oleo exultationis præ participibus tuis.

** Hebrews 1:10

Et : Tu in principio, Domine, terram fundasti : et opera manuum tuarum sunt cæli.

** Hebrews 1:11

Ipsi peribunt, tu autem permanebis, et omnes ut vestimentum veterascent :

** Hebrews 1:12

et velut amictum mutabis eos, et mutabuntur : tu autem idem ipse es, et anni tui non deficient.

** Hebrews 1:13

Ad quem autem angelorum dixit aliquando : Sede a dextris meis, quoadusque ponam inimicos tuos scabellum pedum tuorum ?

** Hebrews 1:14

Nonne omnes sunt administratorii spiritus, in ministerium missi propter eos, qui hæreditatem capient salutis ?   

* Hebrews 2

** Hebrews 2:1

Propterea abundantius oportet observare nos ea quæ audivimus, ne forte pereffluamus.

** Hebrews 2:2

Si enim qui per angelos dictus est sermo, factus est firmus, et omnis prævaricatio, et inobedientia accepit justam mercedis retributionem :

** Hebrews 2:3

quomodo nos effugiemus si tantam neglexerimus salutem ? quæ cum initium accepisset enarrari per Dominum ab eis, qui audierunt, in nos confirmata est,

** Hebrews 2:4

contestante Deo signis et portentis, et variis virtutibus, et Spiritus Sancti distributionibus secundum suam voluntatem.

** Hebrews 2:5

Non enim angelis subjecit Deus orbem terræ futurum, de quo loquimur.

** Hebrews 2:6

Testatus est autem in quodam loco quis, dicens : Quid est homo quod memor es ejus, aut filius hominis quoniam visitas eum ?

** Hebrews 2:7

Minuisti eum paulo minus ab angelis : gloria et honore coronasti eum : et constituisti eum super opera manuum tuarum.

** Hebrews 2:8

Omnia subjecisti sub pedibus ejus. In eo enim quod omnia ei subjecit, nihil dimisit non subjectum ei. Nunc autem necdum videmus omnia subjecta ei.

** Hebrews 2:9

Eum autem, qui modico quam angeli minoratus est, videmus Jesum propter passionem mortis, gloria et honore coronatum : ut, gratia Dei, pro omnibus gustaret mortem.  

** Hebrews 2:10

Decebat enim eum, propter quem omnia, et per quem omnia, qui multos filios in gloriam adduxerat, auctorem salutis eorum per passionem consummare.

** Hebrews 2:11

Qui enim sanctificat, et qui sanctificantur, ex uno omnes. Propter quam causam non confunditur fratres eos vocare, dicens :

** Hebrews 2:12

Nuntiabo nomen tuum fratribus meis : in medio ecclesiæ laudabo te.

** Hebrews 2:13

Et iterum : Ego ero fidens in eum. Et iterum : Ecce ego, et pueri mei, quos dedit mihi Deus.

** Hebrews 2:14

Quia ergo pueri communicaverunt carni, et sanguini, et ipse similiter participavit eisdem : ut per mortem destrueret eum qui habebat mortis imperium, id est, diabolum :

** Hebrews 2:15

et liberaret eos qui timore mortis per totam vitam obnoxii erant servituti.

** Hebrews 2:16

Nusquam enim angelos apprehendit, sed semen Abrahæ apprehendit.

** Hebrews 2:17

Unde debuit per omnia fratribus similari, ut misericors fieret, et fidelis pontifex ad Deum, ut repropitiaret delicta populi.

** Hebrews 2:18

In eo enim, in quo passus est ipse et tentatus, potens est et eis, qui tentantur, auxiliari.   

* Hebrews 3

** Hebrews 3:1

Unde, fratres sancti, vocationis cælestis participes, considerate Apostolum, et pontificem confessionis nostræ Jesum :

** Hebrews 3:2

qui fidelis est ei, qui fecit illum, sicut et Moyses in omni domo ejus.

** Hebrews 3:3

Amplioris enim gloriæ iste præ Moyse dignus est habitus, quanto ampliorem honorem habet domus, qui fabricavit illam.

** Hebrews 3:4

Omnis namque domus fabricatur ab aliquo : qui autem omnia creavit, Deus est.

** Hebrews 3:5

Et Moyses quidem fidelis erat in tota domo ejus tamquam famulus, in testimonium eorum, quæ dicenda erant :

** Hebrews 3:6

Christus vero tamquam filius in domo sua : quæ domus sumus nos, si fiduciam, et gloriam spei usque ad finem, firmam retineamus.  

** Hebrews 3:7

Quapropter sicut dicit Spiritus Sanctus : Hodie si vocem ejus audieritis,

** Hebrews 3:8

nolite obdurare corda vestra, sicut in exacerbatione secundum diem tentationis in deserto,

** Hebrews 3:9

ubi tentaverunt me patres vestri : probaverunt, et viderunt opera mea

** Hebrews 3:10

quadraginta annis : propter quod infensus fui generationi huic, et dixi : Semper errant corde. Ipsi autem non cognoverunt vias meas,

** Hebrews 3:11

sicut juravi in ira mea : Si introibunt in requiem meam.

** Hebrews 3:12

Videte fratres, ne forte sit in aliquo vestrum cor malum incredulitatis, discedendi a Deo vivo :

** Hebrews 3:13

sed adhortamini vosmetipsos per singulos dies, donec hodie cognominatur, ut non obduretur quis ex vobis fallacia peccati.

** Hebrews 3:14

Participes enim Christi effecti sumus, si tamen initium substantiæ ejus usque ad finem firmum retineamus.

** Hebrews 3:15

Dum dicitur : Hodie si vocem ejus audieritis, nolite obdurare corda vestra, quemadmodum in illa exacerbatione.

** Hebrews 3:16

Quidam enim audientes exacerbaverunt : sed non universi qui profecti sunt ex Ægypto per Moysen.

** Hebrews 3:17

Quibus autem infensus est quadraginta annis ? nonne illis qui peccaverunt, quorum cadavera prostrata sunt in deserto ?

** Hebrews 3:18

Quibus autem juravit non introire in requiem ipsius, nisi illis qui increduli fuerunt ?

** Hebrews 3:19

Et videmus, quia non potuerunt introire propter incredulitatem.   

* Hebrews 4

** Hebrews 4:1

Timeamus ergo ne forte relicta pollicitatione introëundi in requiem ejus, existimetur aliquis ex vobis deesse.

** Hebrews 4:2

Etenim et nobis nuntiatum est, quemadmodum et illis : sed non profuit illis sermo auditus, non admistus fidei ex iis quæ audierunt.

** Hebrews 4:3

Ingrediemur enim in requiem, qui credidimus : quemadmodum dixit : Sicut juravi in ira mea : Si introibunt in requiem meam : et quidem operibus ab institutione mundi perfectis.

** Hebrews 4:4

Dixit enim in quodam loco de die septima sic : Et requievit Deus die septima ab omnibus operibus suis.

** Hebrews 4:5

Et in isto rursum : Si introibunt in requiem meam.

** Hebrews 4:6

Quoniam ergo superest introire quosdam in illam, et ii, quibus prioribus annuntiatum est, non introierunt propter incredulitatem :

** Hebrews 4:7

iterum terminat diem quemdam, Hodie, in David dicendo, post tantum temporis, sicut supra dictum est : Hodie si vocem ejus audieritis, nolite obdurare corda vestra.

** Hebrews 4:8

Nam si eis Jesus requiem præstitisset, numquam de alia loqueretur, posthac, die.

** Hebrews 4:9

Itaque relinquitur sabbatismus populo Dei.

** Hebrews 4:10

Qui enim ingressus est in requiem ejus, etiam ipse requievit ab operibus suis, sicut a suis Deus.

** Hebrews 4:11

Festinemus ergo ingredi in illam requiem : ut ne in idipsum quis incidat incredulitatis exemplum.

** Hebrews 4:12

Vivus est enim sermo Dei, et efficax et penetrabilior omni gladio ancipiti : et pertingens usque ad divisionem animæ ac spiritus : compagum quoque ac medullarum, et discretor cogitationum et intentionum cordis.

** Hebrews 4:13

Et non est ulla creatura invisibilis in conspectu ejus : omnia autem nuda et aperta sunt oculis ejus, ad quem nobis sermo.  

** Hebrews 4:14

Habentes ergo pontificem magnum qui penetravit cælos, Jesum Filium Dei, teneamus confessionem.

** Hebrews 4:15

Non enim habemus pontificem qui non possit compati infirmitatibus nostris : tentatum autem per omnia pro similitudine absque peccato.

** Hebrews 4:16

Adeamus ergo cum fiducia ad thronum gratiæ : ut misericordiam consequamur, et gratiam inveniamus in auxilio opportuno.   

* Hebrews 5

** Hebrews 5:1

Omnis namque pontifex ex hominibus assumptus, pro hominibus constituitur in iis quæ sunt ad Deum, ut offerat dona, et sacrificia pro peccatis :

** Hebrews 5:2

qui condolere possit iis qui ignorant et errant : quoniam et ipse circumdatus est infirmitate :

** Hebrews 5:3

et propterea debet, quemadmodum pro populo, ita etiam et pro semetipso offerre pro peccatis.

** Hebrews 5:4

Nec quisquam sumit sibi honorem, sed qui vocatur a Deo, tamquam Aaron.

** Hebrews 5:5

Sic et Christus non semetipsum clarificavit ut pontifex fieret : sed qui locutus est ad eum : Filius meus es tu, ego hodie genui te.

** Hebrews 5:6

Quemadmodum et in alio loco dicit : Tu es sacerdos in æternum, secundum ordinem Melchisedech.

** Hebrews 5:7

Qui in diebus carnis suæ preces, supplicationesque ad eum qui possit illum salvum facere a morte cum clamore valido, et lacrimis offerens, exauditus est pro sua reverentia.

** Hebrews 5:8

Et quidem cum esset Filius Dei, didicit ex iis, quæ passus est, obedientiam :

** Hebrews 5:9

et consummatus, factus est omnibus obtemperantibus sibi, causa salutis æternæ,

** Hebrews 5:10

appellatus a Deo pontifex juxta ordinem Melchisedech.  

** Hebrews 5:11

De quo nobis grandis sermo, et ininterpretabilis ad dicendum : quoniam imbecilles facti estis ad audiendum.

** Hebrews 5:12

Etenim cum deberetis magistri esse propter tempus, rursum indigetis ut vos doceamini quæ sint elementa exordii sermonum Dei : et facti estis quibus lacte opus sit, non solido cibo.

** Hebrews 5:13

Omnis enim, qui lactis est particeps, expers est sermonis justitiæ : parvulus enim est.

** Hebrews 5:14

Perfectorum autem est solidus cibus : eorum, qui pro consuetudine exercitatos habent sensus ad discretionem boni ac mali.   

* Hebrews 6

** Hebrews 6:1

Quapropter intermittentes inchoationis Christi sermonem, ad perfectiora feramur, non rursum jacientes fundamentum pœnitentiæ ab operibus mortuis, et fidei ad Deum,

** Hebrews 6:2

baptismatum doctrinæ, impositionis quoque manuum, ac resurrectionis mortuorum, et judicii æterni.

** Hebrews 6:3

Et hoc faciemus, si quidem permiserit Deus.  

** Hebrews 6:4

Impossibile est enim eos qui semel sunt illuminati, gustaverunt etiam donum cæleste, et participes facti sunt Spiritus Sancti,

** Hebrews 6:5

gustaverunt nihilominus bonum Dei verbum, virtutesque sæculi venturi,

** Hebrews 6:6

et prolapsi sunt ; rursus renovari ad pœnitentiam, rursum crucifigentes sibimetipsis Filium Dei, et ostentui habentes.

** Hebrews 6:7

Terra enim sæpe venientem super se bibens imbrem, et generans herbam opportunam illis, a quibus colitur, accipit benedictionem a Deo :

** Hebrews 6:8

proferens autem spinas ac tribulos, reproba est, et maledicto proxima : cujus consummatio in combustionem.  

** Hebrews 6:9

Confidimus autem de vobis dilectissimi meliora, et viciniora saluti : tametsi ita loquimur.

** Hebrews 6:10

Non enim injustus Deus, ut obliviscatur operis vestri, et dilectionis, quam ostendistis in nomine ipsius, qui ministrastis sanctis, et ministratis.

** Hebrews 6:11

Cupimus autem unumquemque vestrum eamdem ostentare sollicitudinem ad expletionem spei usque in finem :

** Hebrews 6:12

ut non segnes efficiamini, verum imitatores eorum, qui fide, et patientia hæreditabunt promissiones.

** Hebrews 6:13

Abrahæ namque promittens Deus, quoniam neminem habuit, per quem juraret, majorem, juravit per semetipsum,

** Hebrews 6:14

dicens : Nisi benedicens benedicam te, et multiplicans multiplicabo te.

** Hebrews 6:15

Et sic longanimiter ferens, adeptus est repromissionem.

** Hebrews 6:16

Homines enim per majorem sui jurant : et omnis controversiæ eorum finis, ad confirmationem, est juramentum.

** Hebrews 6:17

In quo abundantius volens Deus ostendere pollicitationis hæredibus, immobilitatem consilii sui, interposuit jusjurandum :

** Hebrews 6:18

ut per duas res immobiles, quibus impossibile est mentiri Deum, fortissimum solatium habeamus, qui confugimus ad tenendam propositam spem,

** Hebrews 6:19

quam sicut anchoram habemus animæ tutam ac firmam, et incedentem usque ad interiora velaminis,

** Hebrews 6:20

ubi præcursor pro nobis introivit Jesus, secundum ordinem Melchisedech pontifex factus in æternum.   

* Hebrews 7

** Hebrews 7:1

Hic enim Melchisedech, rex Salem, sacerdos Dei summi, qui obviavit Abrahæ regresso a cæde regum, et benedixit ei :

** Hebrews 7:2

cui et decimas omnium divisit Abraham : primum quidem qui interpretatur rex justitiæ : deinde autem et rex Salem, quod est, rex pacis,

** Hebrews 7:3

sine patre, sine matre, sine genealogia, neque initium dierum, neque finem vitæ habens, assimilatus autem Filio Dei, manet sacerdos in perpetuum.  

** Hebrews 7:4

Intuemini autem quantus sit hic, cui et decimas dedit de præcipuis Abraham patriarcha.

** Hebrews 7:5

Et quidem de filiis Levi sacerdotium accipientes, mandatum habent decimas sumere a populo secundum legem, id est, a fratribus suis : quamquam et ipsi exierint de lumbis Abrahæ.

** Hebrews 7:6

Cujus autem generatio non annumeratur in eis, decimas sumpsit ab Abraham, et hunc, qui habebat repromissiones, benedixit.

** Hebrews 7:7

Sine ulla autem contradictione, quod minus est, a meliore benedicitur.

** Hebrews 7:8

Et hic quidem, decimas morientes homines accipiunt : ibi autem contestatur, quia vivit.

** Hebrews 7:9

Et (ut ita dictum sit) per Abraham, et Levi, qui decimas accepit, decimatus est :

** Hebrews 7:10

adhuc enim in lumbis patris erat, quando obviavit ei Melchisedech.  

** Hebrews 7:11

Si ergo consummatio per sacerdotium Leviticum erat (populus enim sub ipso legem accepit) quid adhuc necessarium fuit secundum ordinem Melchisedech, alium surgere sacerdotem, et non secundum ordinem Aaron dici ?

** Hebrews 7:12

Translato enim sacerdotio, necesse est ut et legis translatio fiat.

** Hebrews 7:13

In quo enim hæc dicuntur, de alia tribu est, de qua nullus altari præsto fuit.

** Hebrews 7:14

Manifestum est enim quod ex Juda ortus sit Dominus noster : in qua tribu nihil de sacerdotibus Moyses locutus est.

** Hebrews 7:15

Et amplius adhuc manifestum est : si secundum similitudinem Melchisedech exsurgat alius sacerdos,

** Hebrews 7:16

qui non secundum legem mandati carnalis factus est, sed secundum virtutem vitæ insolubilis.

** Hebrews 7:17

Contestatur enim : Quoniam tu es sacerdos in æternum, secundum ordinem Melchisedech.

** Hebrews 7:18

Reprobatio quidem fit præcedentis mandati, propter infirmitatem ejus, et inutilitatem :

** Hebrews 7:19

nihil enim ad perfectum adduxit lex : introductio vero melioris spei, per quam proximamus ad Deum.

** Hebrews 7:20

Et quantum est non sine jurejurando (alii quidem sine jurejurando sacerdotes facti sunt,

** Hebrews 7:21

hic autem cum jurejurando per eum, qui dixit ad illum : Juravit Dominus, et non pœnitebit eum : tu es sacerdos in æternum) :

** Hebrews 7:22

in tantum melioris testamenti sponsor factus est Jesus.

** Hebrews 7:23

Et alii quidem plures facti sunt sacerdotes, idcirco quod morte prohiberentur permanere :

** Hebrews 7:24

hic autem eo quod maneat in æternum, sempiternum habet sacerdotium.

** Hebrews 7:25

Unde et salvare in perpetuum potest accedentes per semetipsum ad Deum : semper vivens ad interpellandum pro nobis.

** Hebrews 7:26

Talis enim decebat ut nobis esset pontifex, sanctus, innocens, impollutus, segregatus a peccatoribus, et excelsior cælis factus :

** Hebrews 7:27

qui non habet necessitatem quotidie, quemadmodum sacerdotes, prius pro suis delictis hostias offerre, deinde pro populi : hoc enim fecit semel, seipsum offerendo.

** Hebrews 7:28

Lex enim homines constituit sacerdotes infirmitatem habentes : sermo autem jurisjurandi, qui post legem est, Filium in æternum perfectum.   

* Hebrews 8

** Hebrews 8:1

Capitulum autem super ea quæ dicuntur : Talem habemus pontificem, qui consedit in dextera sedis magnitudinis in cælis,

** Hebrews 8:2

sanctorum minister, et tabernaculi veri, quod fixit Dominus, et non homo.

** Hebrews 8:3

Omnis enim pontifex ad offerendum munera, et hostias constituitur : unde necesse est et hunc habere aliquid, quod offerat.

** Hebrews 8:4

Si ergo esset super terram, nec esset sacerdos : cum essent qui offerent secundum legem munera,

** Hebrews 8:5

qui exemplari, et umbræ deserviunt cælestium. Sicut responsum est Moysi, cum consummaret tabernaculum : Vide (inquit) omnia facito secundum exemplar, quod tibi ostensum est in monte.

** Hebrews 8:6

Nunc autem melius sortitus est ministerium, quanto et melioris testamenti mediator est, quod in melioribus repromissionibus sancitum est.

** Hebrews 8:7

Nam si illud prius culpa vacasset, non utique secundi locus inquireretur.

** Hebrews 8:8

Vituperans enim eos dicit : Ecce dies venient, dicit Dominus : et consummabo super domum Israël, et super domum Juda, testamentum novum,

** Hebrews 8:9

non secundum testamentum quod feci patribus eorum in die qua apprehendi manum eorum ut educerem illos de terra Ægypti : quoniam ipsi non permanserunt in testamento meo : et ego neglexi eos, dicit Dominus.

** Hebrews 8:10

Quia hoc est testamentum quod disponam domui Israël post dies illos, dicit Dominus : dando leges meas in mentem eorum, et in corde eorum superscribam eas : et ero eis in Deum, et ipsi erunt mihi in populum :

** Hebrews 8:11

et non docebit unusquisque proximum suum, et unusquisque fratrem suum, dicens : Cognosce Dominum : quoniam omnes scient me a minore usque ad majorem eorum :

** Hebrews 8:12

quia propitius ero iniquitatibus eorum, et peccatorum eorum jam non memorabor.

** Hebrews 8:13

Dicendo autem novum : veteravit prius. Quod autem antiquatur, et senescit, prope interitum est.   

* Hebrews 9

** Hebrews 9:1

Habuit quidem et prius justificationes culturæ, et Sanctum sæculare.

** Hebrews 9:2

Tabernaculum enim factum est primum, in quo erant candelabra, et mensa, et propositio panum, quæ dicitur Sancta.

** Hebrews 9:3

Post velamentum autem secundum, tabernaculum, quod dicitur Sancta sanctorum :

** Hebrews 9:4

aureum habens thuribulum, et arcam testamenti circumtectam ex omni parte auro, in qua urna aurea habens manna, et virga Aaron, quæ fronduerat, et tabulæ testamenti,

** Hebrews 9:5

superque eam erant cherubim gloriæ obumbrantia propitiatorium : de quibus non est modo dicendum per singula.

** Hebrews 9:6

His vero ita compositis, in priori quidem tabernaculo semper introibant sacerdotes, sacrificiorum officia consummantes :

** Hebrews 9:7

in secundo autem semel in anno solus pontifex non sine sanguine, quem offert pro sua et populi ignorantia :

** Hebrews 9:8

hoc significante Spiritu Sancto, nondum propalatam esse sanctorum viam, adhuc priore tabernaculo habente statum :

** Hebrews 9:9

quæ parabola est temporis instantis : juxta quam munera, et hostiæ offeruntur, quæ non possunt juxta conscientiam perfectum facere servientem, solummodo in cibis, et in potibus,

** Hebrews 9:10

et variis baptismatibus, et justitiis carnis usque ad tempus correctionis impositis.  

** Hebrews 9:11

Christus autem assistens pontifex futurorum bonorum, per amplius et perfectius tabernaculum, non manufactum, id est, non hujus creationis :

** Hebrews 9:12

neque per sanguinem hircorum aut vitulorum, sed per proprium sanguinem introivit semel in Sancta, æterna redemptione inventa.

** Hebrews 9:13

Si enim sanguis hircorum et taurorum, et cinis vitulæ aspersus inquinatos sanctificat ad emundationem carnis :

** Hebrews 9:14

quanto magis sanguis Christi, qui per Spiritum Sanctum semetipsum obtulit immaculatum Deo, emundabit conscientiam nostram ab operibus mortuis, ad serviendum Deo viventi ?  

** Hebrews 9:15

Et ideo novi testamenti mediator est : ut morte intercedente, in redemptionem earum prævaricationum, quæ erant sub priori testamento, repromissionem accipiant qui vocati sunt æternæ hæreditatis.

** Hebrews 9:16

Ubi enim testamentum est, mors necesse est intercedat testatoris.

** Hebrews 9:17

Testamentum enim in mortuis confirmatum est : alioquin nondum valet, dum vivit qui testatus est.

** Hebrews 9:18

Unde nec primum quidem sine sanguine dedicatum est.

** Hebrews 9:19

Lecto enim omni mandato legis a Moyse universo populo, accipiens sanguinem vitulorum et hircorum cum aqua, et lana coccinea, et hyssopo, ipsum quoque librum, et omnem populum aspersit,

** Hebrews 9:20

dicens : Hic sanguis testamenti, quod mandavit ad vos Deus.

** Hebrews 9:21

Etiam tabernaculum et omnia vasa ministerii sanguine similiter aspersit.

** Hebrews 9:22

Et omnia pene in sanguine secundum legem mundantur : et sine sanguinis effusione non fit remissio.

** Hebrews 9:23

Necesse est ergo exemplaria quidem cælestium his mundari : ipsa autem cælestia melioribus hostiis quam istis.

** Hebrews 9:24

Non enim in manufacta Sancta Jesus introivit exemplaria verorum : sed in ipsum cælum, ut appareat nunc vultui Dei pro nobis :

** Hebrews 9:25

neque ut sæpe offerat semetipsum, quemadmodum pontifex intrat in Sancta per singulos annos in sanguine alieno :

** Hebrews 9:26

alioquin oportebat eum frequenter pati ab origine mundi : nunc autem semel in consummatione sæculorum, ad destitutionem peccati, per hostiam suam apparuit.

** Hebrews 9:27

Et quemadmodum statutum est hominibus semel mori, post hoc autem judicium :

** Hebrews 9:28

sic et Christus semel oblatus est ad multorum exhaurienda peccata : secundo sine peccato apparebit exspectantibus se, in salutem.   

* Hebrews 10

** Hebrews 10:1

Umbram enim habens lex futurorum bonorum, non ipsam imaginem rerum : per singulos annos, eisdem ipsis hostiis quas offerunt indesinenter, numquam potest accedentes perfectos facere :

** Hebrews 10:2

alioquin cessassent offerri : ideo quod nullam haberent ultra conscientiam peccati, cultores semel mundati :

** Hebrews 10:3

sed in ipsis commemoratio peccatorum per singulos annos fit.

** Hebrews 10:4

Impossibile enim est sanguine taurorum et hircorum auferri peccata.

** Hebrews 10:5

Ideo ingrediens mundum dicit : Hostiam et oblationem noluisti : corpus autem aptasti mihi :

** Hebrews 10:6

holocautomata pro peccato non tibi placuerunt.

** Hebrews 10:7

Tunc dixi : Ecce venio : in capite libri scriptum est de me : Ut faciam, Deus, voluntatem tuam.

** Hebrews 10:8

Superius dicens : Quia hostias, et oblationes, et holocautomata pro peccato noluisti, nec placita sunt tibi, quæ secundum legem offeruntur,

** Hebrews 10:9

tunc dixi : Ecce venio, ut faciam, Deus, voluntatem tuam : aufert primum, ut sequens statuat.

** Hebrews 10:10

In qua voluntate sanctificati sumus per oblationem corporis Jesu Christi semel.

** Hebrews 10:11

Et omnis quidem sacerdos præsto est quotidie ministrans, et easdem sæpe offerens hostias, quæ numquam possunt auferre peccata :

** Hebrews 10:12

hic autem unam pro peccatis offerens hostiam, in sempiternum sedet in dextera Dei,

** Hebrews 10:13

de cetero exspectans donec ponantur inimici ejus scabellum pedum ejus.

** Hebrews 10:14

Una enim oblatione, consummavit in sempiternum sanctificatos.

** Hebrews 10:15

Contestatur autem nos et Spiritus Sanctus. Postquam enim dixit :

** Hebrews 10:16

Hoc autem testamentum, quod testabor ad illos post dies illos, dicit Dominus, dando leges meas in cordibus eorum, et in mentibus eorum superscribam eas :

** Hebrews 10:17

et peccatorum, et iniquitatum eorum jam non recordabor amplius.

** Hebrews 10:18

Ubi autem horum remissio : jam non est oblatio pro peccato.  

** Hebrews 10:19

Habentes itaque, fratres, fiduciam in introitu sanctorum in sanguine Christi,

** Hebrews 10:20

quam initiavit nobis viam novam, et viventem per velamen, id est, carnem suam,

** Hebrews 10:21

et sacerdotem magnum super domum Dei :

** Hebrews 10:22

accedamus cum vero corde in plenitudine fidei, aspersi corda a conscientia mala, et abluti corpus aqua munda,

** Hebrews 10:23

teneamus spei nostræ confessionem indeclinabilem (fidelis enim est qui repromisit),

** Hebrews 10:24

et consideremus invicem in provocationem caritatis, et bonorum operum :

** Hebrews 10:25

non deserentes collectionem nostram, sicut consuetudinis est quibusdam, sed consolantes, et tanto magis quanto videritis appropinquantem diem.

** Hebrews 10:26

Voluntarie enim peccantibus nobis post acceptam notitiam veritatis, jam non relinquitur pro peccatis hostia,

** Hebrews 10:27

terribilis autem quædam exspectatio judicii, et ignis æmulatio, quæ consumptura est adversarios.

** Hebrews 10:28

Irritam quis faciens legem Moysi, sine ulla miseratione duobus vel tribus testibus moritur :

** Hebrews 10:29

quanto magis putatis deteriora mereri supplicia qui Filium Dei conculcaverit, et sanguinem testamenti pollutum duxerit, in quo sanctificatus est, et spiritui gratiæ contumeliam fecerit ?

** Hebrews 10:30

Scimus enim qui dixit : Mihi vindicta, et ego retribuam. Et iterum : Quia judicabit Dominus populum suum.

** Hebrews 10:31

Horrendum est incidere in manus Dei viventis.

** Hebrews 10:32

Rememoramini autem pristinos dies, in quibus illuminati, magnum certamen sustinuistis passionum :

** Hebrews 10:33

et in altero quidem opprobriis et tribulationibus spectaculum facti : in altero autem socii taliter conversantium effecti.

** Hebrews 10:34

Nam et vinctis compassi estis, et rapinam bonorum vestrorum cum gaudio suscepistis, cognoscentes vos habere meliorem et manentem substantiam.

** Hebrews 10:35

Nolite itaque amittere confidentiam vestram, quæ magnam habet remunerationem.

** Hebrews 10:36

Patientia enim vobis necessaria est : ut voluntatem Dei facientes, reportetis promissionem.

** Hebrews 10:37

Adhuc enim modicum aliquantulum, qui venturus est, veniet, et non tardabit.

** Hebrews 10:38

Justus autem meus ex fide vivit : quod si subtraxerit se, non placebit animæ meæ.

** Hebrews 10:39

Nos autem non sumus subtractionis filii in perditionem, sed fidei in acquisitionem animæ.   

* Hebrews 11

** Hebrews 11:1

Est autem fides sperandarum substantia rerum, argumentum non apparentium.

** Hebrews 11:2

In hac enim testimonium consecuti sunt senes.

** Hebrews 11:3

Fide intelligimus aptata esse sæcula verbo Dei : ut ex invisibilibus visibilia fierent.  

** Hebrews 11:4

Fide plurimam hostiam Abel, quam Cain, obtulit Deo, per quam testimonium consecutus est esse justus, testimonium perhibente muneribus ejus Deo, et per illam defunctus adhuc loquitur.

** Hebrews 11:5

Fide Henoch translatus est ne videret mortem, et non inveniebatur, quia transtulit illum Deus : ante translationem enim testimonium habuit placuisse Deo.

** Hebrews 11:6

Sine fide autem impossibile est placere Deo. Credere enim oportet accedentem ad Deum quia est, et inquirentibus se remunerator sit.

** Hebrews 11:7

Fide Noë responso accepto de iis quæ adhuc non videbantur, metuens aptavit arcam in salutem domus suæ, per quam damnavit mundum : et justitiæ, quæ per fidem est, hæres est institutus.  

** Hebrews 11:8

Fide qui vocatur Abraham obedivit in locum exire, quem accepturus erat in hæreditatem : et exiit, nesciens quo iret.

** Hebrews 11:9

Fide demoratus est in terra repromissionis, tamquam in aliena, in casulis habitando cum Isaac et Jacob cohæredibus repromissionis ejusdem.

** Hebrews 11:10

Exspectabat enim fundamenta habentem civitatem : cujus artifex et conditor Deus.

** Hebrews 11:11

Fide et ipsa Sara sterilis virtutem in conceptionem seminis accepit, etiam præter tempus ætatis : quoniam fidelem credidit esse eum qui repromiserat.

** Hebrews 11:12

Propter quod et ab uno orti sunt (et hoc emortuo) tamquam sidera cæli in multitudinem, et sicut arena, quæ est ad oram maris, innumerabilis.

** Hebrews 11:13

Juxta fidem defuncti sunt omnes isti, non acceptis repromissionibus, sed a longe eas aspicientes, et salutantes, et confitentes quia peregrini et hospites sunt super terram.

** Hebrews 11:14

Qui enim hæc dicunt, significant se patriam inquirere.

** Hebrews 11:15

Et si quidem ipsius meminissent de qua exierunt, habebant utique tempus revertendi :

** Hebrews 11:16

nunc autem meliorem appetunt, id est, cælestem. Ideo non confunditur Deus vocari Deus eorum : paravit enim illis civitatem.

** Hebrews 11:17

Fide obtulit Abraham Isaac, cum tentaretur, et unigenitum offerebat, qui susceperat repromissiones :

** Hebrews 11:18

ad quem dictum est : Quia in Isaac vocabitur tibi semen :

** Hebrews 11:19

arbitrans quia et a mortuis suscitare potens est Deus : unde eum et in parabolam accepit.

** Hebrews 11:20

Fide et de futuris benedixit Isaac Jacob et Esau.

** Hebrews 11:21

Fide Jacob, moriens, singulos filiorum Joseph benedixit : et adoravit fastigium virgæ ejus.

** Hebrews 11:22

Fide Joseph, moriens, de profectione filiorum Israël memoratus est, et de ossibus suis mandavit.  

** Hebrews 11:23

Fide Moyses, natus, occultatus est mensibus tribus a parentibus suis, eo quod vidissent elegantem infantem, et non timuerunt regis edictum.

** Hebrews 11:24

Fide Moyses grandis factus negavit se esse filium filiæ Pharaonis,

** Hebrews 11:25

magis eligens affligi cum populo Dei, quam temporalis peccati habere jucunditatem,

** Hebrews 11:26

majores divitias æstimans thesauro Ægyptiorum, improperium Christi : aspiciebat enim in remunerationem.

** Hebrews 11:27

Fide reliquit Ægyptum, non veritus animositatem regis : invisibilem enim tamquam videns sustinuit.

** Hebrews 11:28

Fide celebravit Pascha, et sanguinis effusionem : ne qui vastabat primitiva, tangeret eos.

** Hebrews 11:29

Fide transierunt mare Rubrum tamquam per aridam terram : quod experti Ægyptii, devorati sunt.  

** Hebrews 11:30

Fide muri Jericho corruerunt, circuitu dierum septem.

** Hebrews 11:31

Fide Rahab meretrix non periit cum incredulis, excipiens exploratores cum pace.

** Hebrews 11:32

Et quid adhuc dicam ? deficiet enim me tempus enarrantem de Gedeon, Barac, Samson, Jephte, David, Samuel, et prophetis :

** Hebrews 11:33

qui per fidem vicerunt regna, operati sunt justitiam, adepti sunt repromissiones, obturaverunt ora leonum,

** Hebrews 11:34

extinxerunt impetum ignis, effugerunt aciem gladii, convaluerunt de infirmitate, fortes facti sunt in bello, castra verterunt exterorum :

** Hebrews 11:35

acceperunt mulieres de resurrectione mortuos suos : alii autem distenti sunt non suscipientes redemptionem ut meliorem invenirent resurrectionem.

** Hebrews 11:36

Alii vero ludibria, et verbera experti, insuper et vincula, et carceres :

** Hebrews 11:37

lapidati sunt, secti sunt, tentati sunt, in occisione gladii mortui sunt, circuierunt in melotis, in pellibus caprinis, egentes, angustiati, afflicti :

** Hebrews 11:38

quibus dignus non erat mundus : in solitudinibus errantes, in montibus, in speluncis, et in cavernis terræ.

** Hebrews 11:39

Et hi omnes testimonio fidei probati, non acceperunt repromissionem,

** Hebrews 11:40

Deo pro nobis melius aliquid providente, ut non sine nobis consummarentur.   

* Hebrews 12

** Hebrews 12:1

Ideoque et nos tantam habentes impositam nubem testium, deponentes omne pondus, et circumstans nos peccatum, per patientiam curramus ad propositum nobis certamen :

** Hebrews 12:2

aspicientes in auctorem fidei, et consummatorem Jesum, qui proposito sibi gaudio sustinuit crucem, confusione contempta, atque in dextera sedis Dei sedet.

** Hebrews 12:3

Recogitate enim eum qui talem sustinuit a peccatoribus adversum semetipsum contradictionem : ut ne fatigemini, animis vestris deficientes.

** Hebrews 12:4

Nondum enim usque ad sanguinem restitistis, adversus peccatum repugnantes :

** Hebrews 12:5

et obliti estis consolationis, quæ vobis tamquam filiis loquitur, dicens : Fili mi, noli negligere disciplinam Domini : neque fatigeris dum ab eo argueris.

** Hebrews 12:6

Quem enim diligit Dominus, castigat : flagellat autem omnem filium, quem recipit.

** Hebrews 12:7

In disciplina perseverate. Tamquam filiis vobis offert se Deus : quis enim filius, quem non corripit pater ?

** Hebrews 12:8

quod si extra disciplinam estis, cujus participes facti sunt omnes : ergo adulteri, et non filii estis.

** Hebrews 12:9

Deinde patres quidem carnis nostræ, eruditores habuimus, et reverebamur eos, non multo magis obtemperabimus Patri spirituum, et vivemus ?

** Hebrews 12:10

Et illi quidem in tempore paucorum dierum, secundum voluntatem suam erudiebant nos : hic autem ad id quod utile est in recipiendo sanctificationem ejus.

** Hebrews 12:11

Omnis autem disciplina in præsenti quidem videtur non esse gaudii, sed mœroris : postea autem fructum pacatissimum exercitatis per eam, reddet justitiæ.

** Hebrews 12:12

Propter quod remissas manus, et soluta genua erigite,

** Hebrews 12:13

et gressus rectos facite pedibus vestris : ut non claudicans quis erret, magis autem sanetur.  

** Hebrews 12:14

Pacem sequimini cum omnibus, et sanctimoniam, sine qua nemo videbit Deum :

** Hebrews 12:15

contemplantes nequis desit gratiæ Dei : ne qua radix amaritudinis sursum germinans impediat, et per illam inquinentur multi.

** Hebrews 12:16

Ne quis fornicator, aut profanus ut Esau : qui propter unam escam vendidit primitiva sua :

** Hebrews 12:17

scitote enim quoniam et postea cupiens hæreditare benedictionem, reprobatus est : non enim invenit pœnitentiæ locum, quamquam cum lacrimis inquisisset eam.

** Hebrews 12:18

Non enim accessistis ad tractabilem montem, et accensibilem ignem, et turbinem, et caliginem, et procellam,

** Hebrews 12:19

et tubæ sonum, et vocem verborum, quam qui audierunt, excusaverunt se, ne eis fieret verbum.

** Hebrews 12:20

Non enim portabant quod dicebatur : Et si bestia tetigerit montem, lapidabitur.

** Hebrews 12:21

Et ita terribile erat quod videbatur. Moyses dixit : Exterritus sum, et tremebundus.

** Hebrews 12:22

Sed accessistis ad Sion montem, et civitatem Dei viventis, Jerusalem cælestem, et multorum millium angelorum frequentiam,

** Hebrews 12:23

et ecclesiam primitivorum, qui conscripti sunt in cælis, et judicem omnium Deum, et spiritus justorum perfectorum,

** Hebrews 12:24

et testamenti novi mediatorem Jesum, et sanguinis aspersionem melius loquentem quam Abel.

** Hebrews 12:25

Videte ne recusetis loquentem. Si enim illi non effugerunt, recusantes eum, qui super terram loquebatur : multo magis nos, qui de cælis loquentem nobis avertimus.

** Hebrews 12:26

Cujus vox movit terram tunc : nunc autem repromittit, dicens : Adhuc semel, et ego movebo non solum terram, sed et cælum.

** Hebrews 12:27

Quod autem, Adhuc semel, dicit : declarat mobilium translationem tamquam factorum, ut maneant ea quæ sunt immobilia.

** Hebrews 12:28

Itaque regnum immobile suscipientes, habemus gratiam : per quam serviamus placentes Deo, cum metu et reverentia.

** Hebrews 12:29

Etenim Deus noster ignis consumens est.   

* Hebrews 13

** Hebrews 13:1

Caritas fraternitatis maneat in vobis,

** Hebrews 13:2

et hospitalitatem nolite oblivisci : per hanc enim latuerunt quidam, angelis hospitio receptis.

** Hebrews 13:3

Mementote vinctorum, tamquam simul vincti : et laborantium, tamquam et ipsi in corpore morantes.

** Hebrews 13:4

Honorabile connubium in omnibus, et thorus immaculatus. Fornicatores enim, et adulteros judicabit Deus.

** Hebrews 13:5

Sint mores sine avaritia, contenti præsentibus : ipse enim dixit : Non te deseram, neque derelinquam :

** Hebrews 13:6

ita ut confidenter dicamus : Dominus mihi adjutor : non timebo quid faciat mihi homo.

** Hebrews 13:7

Mementote præpositorum vestrorum, qui vobis locuti sunt verbum Dei : quorum intuentes exitum conversationis, imitamini fidem.

** Hebrews 13:8

Jesus Christus heri, et hodie : ipse et in sæcula.

** Hebrews 13:9

Doctrinis variis et peregrinis nolite abduci. Optimum est enim gratia stabilire cor, non escis : quæ non profuerunt ambulantibus in eis.

** Hebrews 13:10

Habemus altare, de quo edere non habent potestatem, qui tabernaculo deserviunt.

** Hebrews 13:11

Quorum enim animalium infertur sanguis pro peccato in Sancta per pontificem, horum corpora cremantur extra castra.

** Hebrews 13:12

Propter quod et Jesus, ut sanctificaret per suum sanguinem populum, extra portam passus est.

** Hebrews 13:13

Exeamus igitur ad eum extra castra, improperium ejus portantes.

** Hebrews 13:14

Non enim habemus hic manentem civitatem, sed futuram inquirimus.

** Hebrews 13:15

Per ipsum ergo offeramus hostiam laudis semper Deo, id est, fructum labiorum confitentium nomini ejus.

** Hebrews 13:16

Beneficentiæ autem et communionis nolite oblivisci : talibus enim hostiis promeretur Deus.

** Hebrews 13:17

Obedite præpositis vestris, et subjacete eis. Ipsi enim pervigilant quasi rationem pro animabus vestris reddituri, ut cum gaudio hoc faciant, et non gementes : hoc enim non expedit vobis.  

** Hebrews 13:18

Orate pro nobis : confidimus enim quia bonam conscientiam habemus in omnibus bene volentes conversari.

** Hebrews 13:19

Amplius autem deprecor vos hoc facere, quo celerius restituar vobis.

** Hebrews 13:20

Deus autem pacis, qui eduxit de mortuis pastorem magnum ovium, in sanguine testamenti æterni, Dominum nostrum Jesum Christum,

** Hebrews 13:21

aptet vos in omni bono, ut faciatis ejus voluntatem : faciens in vobis quod placeat coram se per Jesum Christum : cui est gloria in sæcula sæculorum. Amen.

** Hebrews 13:22

Rogo autem vos fratres, ut sufferatis verbum solatii. Etenim perpaucis scripsi vobis.

** Hebrews 13:23

Cognoscite fratrem nostrum Timotheum dimissum : cum quo (si celerius venerit) videbo vos.

** Hebrews 13:24

Salutate omnes præpositos vestros, et omnes sanctos. Salutant vos de Italia fratres.

** Hebrews 13:25

Gratia cum omnibus vobis. Amen.    

