* Hosea 1

** Hosea 1:1

Verbum Domini, quod factum est ad Osee, filium Beeri, in diebus Oziæ, Joathan, Achaz, Ezechiæ, regum Juda ; et in diebus Jeroboam, filii Joas, regis Israël.  

** Hosea 1:2

Principium loquendi Domino in Osee. Et dixit Dominus ad Osee : Vade, sume tibi uxorem fornicationum, et fac tibi filios fornicationum, quia fornicans fornicabitur terra a Domino.

** Hosea 1:3

Et abiit, et accepit Gomer, filiam Debelaim : et concepit, et peperit ei filium.

** Hosea 1:4

Et dixit Dominus ad eum : Voca nomen ejus Jezrahel, quoniam adhuc modicum, et visitabo sanguinem Jezrahel super domum Jehu, et quiescere faciam regnum domus Israël.

** Hosea 1:5

Et in illa die conteram arcum Israël in valle Jezrahel.

** Hosea 1:6

Et concepit adhuc, et peperit filiam. Et dixit ei : Voca nomen ejus, Absque misericordia, quia non addam ultra misereri domui Israël, sed oblivione obliviscar eorum.

** Hosea 1:7

Et domui Juda miserebor, et salvabo eos in Domino Deo suo ; et non salvabo eos in arcu et gladio, et in bello, et in equis, et in equitibus.

** Hosea 1:8

Et ablactavit eam quæ erat Absque misericordia. Et concepit, et peperit filium.

** Hosea 1:9

Et dixit : Voca nomen ejus, Non populus meus, quia vos non populus meus, et ego non ero vester.

** Hosea 1:10

Et erit numerus filiorum Israël quasi arena maris, quæ sine mensura est, et non numerabitur. Et erit in loco ubi dicetur eis : Non populus meus vos : dicetur eis : Filii Dei viventis.

** Hosea 1:11

Et congregabuntur filii Juda et filii Israël pariter ; et ponent sibimet caput unum, et ascendent de terra, quia magnus dies Jezrahel.   

* Hosea 2

** Hosea 2:1

Dicite fratribus vestris : Populus meus ; et sorori vestræ : Misericordiam consecuta.  

** Hosea 2:2

Judicate matrem vestram, judicate,  quoniam ipsa non uxor mea,  et ego non vir ejus.  Auferat fornicationes suas a facie sua,  et adulteria sua de medio uberum suorum ; 

** Hosea 2:3

ne forte expoliem eam nudam,  et statuam eam secundum diem nativitatis suæ,  et ponam eam quasi solitudinem,  et statuam eam velut terram inviam,  et interficiam eam siti. 

** Hosea 2:4

Et filiorum illius non miserebor,  quoniam filii fornicationum sunt. 

** Hosea 2:5

Quia fornicata est mater eorum,  confusa est quæ concepit eos ;  quia dixit : Vadam post amatores meos,  qui dant panes mihi, et aquas meas,  lanam meam, et linum meum,  oleum meum, et potum meum. 

** Hosea 2:6

Propter hoc ecce ego sepiam viam tuam spinis,  et sepiam eam maceria, et semitas suas non inveniet. 

** Hosea 2:7

Et sequetur amatores suos, et non apprehendet eos ;  et quæret eos, et non inveniet :  et dicet : Vadam, et revertar ad virum meum priorem,  quia bene mihi erat tunc magis quam nunc. 

** Hosea 2:8

Et hæc nescivit, quia ego dedi ei frumentum, et vinum, et oleum,  et argentum multiplicavi ei, et aurum,  quæ fecerunt Baal. 

** Hosea 2:9

Idcirco convertar, et sumam frumentum meum in tempore suo,  et vinum meum in tempore suo.  Et liberabo lanam meam et linum meum,  quæ operiebant ignominiam ejus. 

** Hosea 2:10

Et nunc revelabo stultitiam ejus in oculis amatorum ejus ;  et vir non eruet eam de manu mea ; 

** Hosea 2:11

et cessare faciam omne gaudium ejus,  solemnitatem ejus, neomeniam ejus, sabbatum ejus,  et omnia festa tempora ejus. 

** Hosea 2:12

Et corrumpam vineam ejus, et ficum ejus,  de quibus dixit : Mercedes hæ meæ sunt,  quas dederunt mihi amatores mei ;  et ponam eam in saltum,  et comedet eam bestia agri. 

** Hosea 2:13

Et visitabo super eam dies Baalim,  quibus accendebat incensum,  et ornabatur in aure sua, et monili suo.  Et ibat post amatores suos,  et mei obliviscebatur, dicit Dominus. 

** Hosea 2:14

Propter hoc ecce ego lactabo eam,  et ducam eam in solitudinem,  et loquar ad cor ejus. 

** Hosea 2:15

Et dabo ei vinitores ejus ex eodem loco,  et vallem Achor, ad aperiendam spem ;  et canet ibi juxta dies juventutis suæ,  et juxta dies ascensionis suæ de terra Ægypti. 

** Hosea 2:16

Et erit in die illa, ait Dominus :  vocabit me, Vir meus,  et non vocabit me ultra Baali. 

** Hosea 2:17

Et auferam nomina Baalim de ore ejus,  et non recordabitur ultra nominis eorum. 

** Hosea 2:18

Et percutiam cum eis fœdus in die illa, cum bestia agri,  et cum volucre cæli, et cum reptili terræ ;  et arcum, et gladium, et bellum conteram de terra,  et dormire eos faciam fiducialiter. 

** Hosea 2:19

Et sponsabo te mihi in sempiternum ;  et sponsabo te mihi in justitia, et judicio,  et in misericordia, et in miserationibus. 

** Hosea 2:20

Et sponsabo te mihi in fide ;  et scies quia ego Dominus. 

** Hosea 2:21

Et erit in die illa :  exaudiam, dicit Dominus, exaudiam cælos,  et illi exaudient terram. 

** Hosea 2:22

Et terra exaudiet triticum, et vinum, et oleum,  et hæc exaudient Jezrahel. 

** Hosea 2:23

Et seminabo eam mihi in terra,  et miserebor ejus quæ fuit Absque misericordia. 

** Hosea 2:24

Et dicam Non populo meo : Populus meus es tu ;  et ipse dicet : Deus meus es tu.  

* Hosea 3

** Hosea 3:1

Et dixit Dominus ad me : Adhuc vade, et dilige mulierem dilectam amico et adulteram, sicut diligit Dominus filios Israël, et ipsi respiciunt ad deos alienos, et diligunt vinacia uvarum.

** Hosea 3:2

Et fodi eam mihi quindecim argenteis, et coro hordei, et dimidio coro hordæi.

** Hosea 3:3

Et dixi ad eam : Dies multos exspectabis me ; non fornicaberis, et non eris viro ; sed et ego exspectabo te.

** Hosea 3:4

Quia dies multos sedebunt filii Israël sine rege, et sine principe, et sine sacrificio, et sine altari, et sine ephod, et sine theraphim.

** Hosea 3:5

Et post hæc revertentur filii Israël, et quærent Dominum Deum suum, et David regem suum : et pavebunt ad Dominum, et ad bonum ejus, in novissimo dierum.  

* Hosea 4

** Hosea 4:1

Audite verbum Domini, filii Israël,  quia judicium Domino cum habitatoribus terræ :  non est enim veritas, et non est misericordia,  et non est scientia Dei in terra. 

** Hosea 4:2

Maledictum, et mendacium,  et homicidium, et furtum, et adulterium inundaverunt,  et sanguis sanguinem tetigit. 

** Hosea 4:3

Propter hoc lugebit terra,  et infirmabitur omnis qui habitat in ea,  in bestia agri, et in volucre cæli ;  sed et pisces maris congregabuntur. 

** Hosea 4:4

Verumtamen unusquisque non judicet,  et non arguatur vir :  populus enim tuus sicut hi qui contradicunt sacerdoti. 

** Hosea 4:5

Et corrues hodie,  et corruet etiam propheta tecum.  Nocte tacere feci matrem tuam. 

** Hosea 4:6

Conticuit populus meus,  eo quod non habuerit scientiam :  quia tu scientiam repulisti,  repellam te, ne sacerdotio fungaris mihi ;  et oblita es legis Dei tui,  obliviscar filiorum tuorum et ego. 

** Hosea 4:7

Secundum multitudinem eorum sic peccaverunt mihi :  gloriam eorum in ignominiam commutabo. 

** Hosea 4:8

Peccata populi mei comedent,  et ad iniquitatem eorum sublevabunt animas eorum. 

** Hosea 4:9

Et erit sicut populus, sic sacerdos ;  et visitabo super eum vias ejus,  et cogitationes ejus reddam ei. 

** Hosea 4:10

Et comedent, et non saturabuntur ;  fornicati sunt, et non cessaverunt :  quoniam Dominum dereliquerunt in non custodiendo. 

** Hosea 4:11

Fornicatio, et vinum, et ebrietas auferunt cor. 

** Hosea 4:12

Populus meus in ligno suo interrogavit,  et baculus ejus annuntiavit ei ;  spiritus enim fornicationum decepit eos,  et fornicati sunt a Deo suo. 

** Hosea 4:13

Super capita montium sacrificabant,  et super colles ascendebant thymiama ;  subtus quercum, et populum, et terebinthum,  quia bona erat umbra ejus ;  ideo fornicabuntur filiæ vestræ,  et sponsæ vestræ adulteræ erunt. 

** Hosea 4:14

Non visitabo super filias vestras cum fuerint fornicatæ,  et super sponsas vestras cum adulteraverint,  quoniam ipsi cum meretricibus conversabantur,  et cum effeminatis sacrificabant ;  et populus non intelligens vapulabit. 

** Hosea 4:15

Si fornicaris tu, Israël,  non delinquat saltem Juda ;  et nolite ingredi in Galgala,  et ne ascenderitis in Bethaven,  neque juraveritis : Vivit Dominus ! 

** Hosea 4:16

Quoniam sicut vacca lasciviens declinavit Israël ;  nunc pascet eos Dominus, quasi agnum in latitudine. 

** Hosea 4:17

Particeps idolorum Ephraim : dimitte eum. 

** Hosea 4:18

Separatum est convivium eorum ;  fornicatione fornicati sunt :  dilexerunt afferre ignominiam protectores ejus. 

** Hosea 4:19

Ligavit eum spiritus in alis suis,  et confundentur a sacrificiis suis.  

* Hosea 5

** Hosea 5:1

Audite hoc, sacerdotes,  et attendite, domus Israël,  et domus regis, auscultate :  quia vobis judicium est,  quoniam laqueus facti estis speculationi,  et rete expansum super Thabor. 

** Hosea 5:2

Et victimas declinastis in profundum ;  et ego eruditor omnium eorum. 

** Hosea 5:3

Ego scio Ephraim,  et Israël non est absconditus a me :  quia nunc fornicatus est Ephraim ;  contaminatus est Israël. 

** Hosea 5:4

Non dabunt cogitationes suas ut revertantur ad Deum suum,  quia spiritus fornicationum in medio eorum,  et Dominum non cognoverunt. 

** Hosea 5:5

Et respondebit arrogantia Israël in facie ejus,  et Israël et Ephraim ruent in iniquitate sua :  ruet etiam Judas cum eis. 

** Hosea 5:6

In gregibus suis et in armentis suis vadent ad quærendum Dominum,  et non invenient :  ablatus est ab eis. 

** Hosea 5:7

In Dominum prævaricati sunt,  quia filios alienos genuerunt :  nunc devorabit eos mensis, cum partibus suis. 

** Hosea 5:8

Clangite buccina in Gabaa,  tuba in Rama ;  ululate in Bethaven,  post tergum tuum, Benjamin. 

** Hosea 5:9

Ephraim in desolatione erit in die correptionis ;  in tribubus Israël ostendi fidem. 

** Hosea 5:10

Facti sunt principes Juda quasi assumentes terminum ;  super eos effundam quasi aquam iram meam. 

** Hosea 5:11

Calumniam patiens est Ephraim, fractus judicio,  quoniam cœpit abire post sordes. 

** Hosea 5:12

Et ego quasi tinea Ephraim,  et quasi putredo domui Juda. 

** Hosea 5:13

Et vidit Ephraim languorem suum,  et Juda vinculum suum ;  et abiit Ephraim ad Assur,  et misit ad regem ultorem :  et ipse non poterit sanare vos,  nec solvere poterit a vobis vinculum. 

** Hosea 5:14

Quoniam ego quasi leæna Ephraim,  et quasi catulus leonis domui Juda.  Ego, ego capiam, et vadam ;  tollam, et non est qui eruat. 

** Hosea 5:15

Vadens revertar ad locum meum,  donec deficiatis, et quæratis faciem meam.  

* Hosea 6

** Hosea 6:1

In tribulatione sua mane consurgent ad me :  Venite, et revertamur ad Dominum, 

** Hosea 6:2

quia ipse cepit, et sanabit nos ;  percutiet, et curabit nos. 

** Hosea 6:3

Vivificabit nos post duos dies ;  in die tertia suscitabit nos,  et vivemus in conspectu ejus.  Sciemus, sequemurque ut cognoscamus Dominum :  quasi diluculum præparatus est egressus ejus,  et veniet quasi imber nobis temporaneus et serotinus terræ. 

** Hosea 6:4

Quid faciam tibi, Ephraim ?  quid faciam tibi, Juda ?  misericordia vestra quasi nubes matutina,  et quasi ros mane pertransiens. 

** Hosea 6:5

Propter hoc dolavi in prophetis ;  occidi eos in verbis oris mei :  et judicia tua quasi lux egredientur. 

** Hosea 6:6

Quia misericordiam volui, et non sacrificium ;  et scientiam Dei plus quam holocausta. 

** Hosea 6:7

Ipsi autem sicut Adam transgressi sunt pactum :  ibi prævaricati sunt in me. 

** Hosea 6:8

Galaad civitas operantium idolum,  supplantata sanguine. 

** Hosea 6:9

Et quasi fauces virorum latronum,  particeps sacerdotum, in via interficientium pergentes de Sichem :  quia scelus operati sunt. 

** Hosea 6:10

In domo Israël vidi horrendum :  ibi fornicationes Ephraim,  contaminatus est Israël. 

** Hosea 6:11

Sed et Juda, pone messem tibi,  cum convertero captivitatem populi mei.  

* Hosea 7

** Hosea 7:1

Cum sanare vellem Israël,  revelata est iniquitas Ephraim,  et malitia Samariæ,  quia operati sunt mendacium ;  et fur ingressus est spolians,  latrunculus foris. 

** Hosea 7:2

Et ne forte dicant in cordibus suis,  omnem malitiam eorum me recordatum,  nunc circumdederunt eos adinventiones suæ :  coram facie mea factæ sunt. 

** Hosea 7:3

In malitia sua lætificaverunt regem,  et in mendaciis suis principes. 

** Hosea 7:4

Omnes adulterantes,  quasi clibanus succensus a coquente ;  quievit paululum civitas a commistione fermenti,  donec fermentaretur totum. 

** Hosea 7:5

Dies regis nostri : cœperunt principes furere a vino ;  extendit manum suam cum illusoribus. 

** Hosea 7:6

Quia applicuerunt quasi clibanum cor suum,  cum insidiaretur eis ;  tota nocte dormivit coquens eos :  mane ipse succensus quasi ignis flammæ. 

** Hosea 7:7

Omnes calefacti sunt quasi clibanus,  et devoraverunt judices suos :  omnes reges eorum ceciderunt ;  non est qui clamat in eis ad me. 

** Hosea 7:8

Ephraim in populis ipse commiscebatur ;  Ephraim factus est subcinericius panis, qui non reversatur. 

** Hosea 7:9

Comederunt alieni robur ejus, et ipse nescivit ;  sed et cani effusi sunt in eo, et ipse ignoravit. 

** Hosea 7:10

Et humiliabitur superbia Israël in facie ejus ;  nec reversi sunt ad Dominum Deum suum,  et non quæsierunt eum in omnibus his. 

** Hosea 7:11

Et factus est Ephraim quasi columba seducta non habens cor.  Ægyptum invocabant ; ad Assyrios abierunt. 

** Hosea 7:12

Et cum profecti fuerint,  expandam super eos rete meum :  quasi volucrem cæli detraham eos ;  cædam eos secundum auditionem cœtus eorum. 

** Hosea 7:13

Væ eis, quoniam recesserunt a me !  vastabuntur, quia prævaricati sunt in me,  et ego redemi eos,  et ipsi locuti sunt contra me mendacia. 

** Hosea 7:14

Et non clamaverunt ad me in corde suo,  sed ululabant in cubilibus suis :  super triticum et vinum ruminabant ;  recesserunt a me. 

** Hosea 7:15

Et ego erudivi eos, et confortavi brachia eorum,  et in me cogitaverunt malitiam. 

** Hosea 7:16

Reversi sunt ut essent absque jugo ;  facti sunt quasi arcus dolosus :  cadent in gladio principes eorum, a furore linguæ suæ.  Ista subsannatio eorum in terra Ægypti.  

* Hosea 8

** Hosea 8:1

In gutture tuo sit tuba  quasi aquila super domum Domini,  pro eo quod transgressi sunt fœdus meum,  et legem meam prævaricati sunt. 

** Hosea 8:2

Me invocabunt : Deus meus,  cognovimus te Israël. 

** Hosea 8:3

Projecit Israël bonum :  inimicus persequetur eum. 

** Hosea 8:4

Ipsi regnaverunt, et non ex me ;  principes exstiterunt, et non cognovi :  argentum suum et aurum suum fecerunt sibi idola,  ut interirent. 

** Hosea 8:5

Projectus est vitulus tuus, Samaria ;  iratus est furor meus in eos.  Usquequo non poterunt emundari ? 

** Hosea 8:6

Quia ex Israël et ipse est :  artifex fecit illum, et non est deus ;  quoniam in aranearum telas erit vitulus Samariæ. 

** Hosea 8:7

Quia ventum seminabunt,  et turbinem metent :  culmus stans non est in eo ;  germen non faciet farinam :  quod etsi fecerit, alieni comedent eam. 

** Hosea 8:8

Devoratus est Israël ;  nunc factus est in nationibus quasi vas immundum. 

** Hosea 8:9

Quia ipsi ascenderunt ad Assur,  onager solitarius sibi ;  Ephraim munera dederunt amatoribus. 

** Hosea 8:10

Sed et cum mercede conduxerint nationes,  nunc congregabo eos,  et quiescent paulisper ab onere regis et principum. 

** Hosea 8:11

Quia multiplicavit Ephraim altaria ad peccandum ;  factæ sunt ei aræ in delictum. 

** Hosea 8:12

Scribam ei multiplices leges meas,  quæ velut alienæ computatæ sunt. 

** Hosea 8:13

Hostias offerent,  immolabunt carnes et comedent,  et Dominus non suscipiet eas :  nunc recordabitur iniquitatis eorum,  et visitabit peccata eorum :  ipsi in Ægyptum convertentur. 

** Hosea 8:14

Et oblitus est Israël factoris sui,  et ædificavit delubra ;  et Judas multiplicavit urbes munitas ;  et mittam ignem in civitates ejus,  et devorabit ædes illius.  

* Hosea 9

** Hosea 9:1

Noli lætari, Israël ;  noli exsultare sicut populi :  quia fornicatus es a Deo tuo ;  dilexisti mercedem super omnes areas tritici. 

** Hosea 9:2

Area et torcular non pascet eos,  et vinum mentietur eis : 

** Hosea 9:3

non habitabunt in terra Domini.  Reversus est Ephraim in Ægyptum,  et in Assyriis pollutum comedit. 

** Hosea 9:4

Non libabunt Domino vinum,  et non placebunt ei.  Sacrificia eorum quasi panis lugentium ;  omnes qui comedent eum, contaminabuntur :  quia panis eorum animæ ipsorum :  non intrabit in domum Domini. 

** Hosea 9:5

Quid facietis in die solemni,  in die festivitatis Domini ? 

** Hosea 9:6

Ecce enim profecti sunt a vastitate :  Ægyptus congregabit eos ;  Memphis sepeliet eos :  desiderabile argentum eorum urtica hæreditabit,  lappa in tabernaculis eorum. 

** Hosea 9:7

Venerunt dies visitationis,  venerunt dies retributionis.  Scitote, Israël,  stultum prophetam,  insanum virum spiritualem,  propter multitudinem iniquitatis tuæ,  et multitudinem amentiæ. 

** Hosea 9:8

Speculator Ephraim cum Deo meo,  propheta laqueus ruinæ factus est super omnes vias ejus ;  insania in domo Dei ejus. 

** Hosea 9:9

Profunde peccaverunt, sicut in diebus Gabaa.  Recordabitur iniquitatis eorum,  et visitabit peccata eorum. 

** Hosea 9:10

Quasi uvas in deserto inveni Israël,  quasi prima poma ficulneæ in cacumine ejus vidi patres eorum :  ipsi autem intraverunt ad Beelphegor,  et abalienati sunt in confusionem,  et facti sunt abominabiles sicut ea quæ dilexerunt. 

** Hosea 9:11

Ephraim quasi avis avolavit ;  gloria eorum a partu, et ab utero, et a conceptu. 

** Hosea 9:12

Quod etsi enutrierint filios suos,  absque liberis eos faciam in hominibus ;  sed et væ eis cum recessero ab eis ! 

** Hosea 9:13

Ephraim, ut vidi, Tyrus erat fundata in pulchritudine ;  et Ephraim educet ad interfectorem filios suos. 

** Hosea 9:14

Da eis, Domine. Quid dabis eis ?  da eis vulvam sine liberis, et ubera arentia. 

** Hosea 9:15

Omnes nequitiæ eorum in Galgal,  quia ibi exosos habui eos.  Propter malitiam adinventionum eorum,  de domo mea ejiciam eos ;  non addam ut diligam eos :  omnes principes eorum recedentes. 

** Hosea 9:16

Percussus est Ephraim ;  radix eorum exsiccata est :  fructum nequaquam facient,  quod etsi genuerint,  interficiam amantissima uteri eorum. 

** Hosea 9:17

Abjiciet eos Deus meus, quia non audierunt eum,  et erunt vagi in nationibus.  

* Hosea 10

** Hosea 10:1

Vitis frondosa Israël,  fructus adæquatus est ei :  secundum multitudinem fructus sui multiplicavit altaria,  juxta ubertatem terræ suæ exuberavit simulacris. 

** Hosea 10:2

Divisum est cor eorum, nunc interibunt ;  ipse confringet simulacra eorum,  depopulabitur aras eorum. 

** Hosea 10:3

Quia nunc dicent : Non est rex nobis,  non enim timemus Dominum ;  et rex quid faciet nobis ? 

** Hosea 10:4

Loquimini verba visionis inutilis, et ferietis fœdus ;  et germinabit quasi amaritudo judicium super sulcos agri. 

** Hosea 10:5

Vaccas Bethaven coluerunt habitatores Samariæ ;  quia luxit super eum populus ejus,  et æditui ejus super eum exsultaverunt  in gloria ejus, quia migravit ab eo. 

** Hosea 10:6

Siquidem et ipse in Assur delatus est,  munus regi ultori.  Confusio Ephraim capiet,  et confundetur Israël in voluntate sua. 

** Hosea 10:7

Transire fecit Samaria regem suum  quasi spumam super faciem aquæ. 

** Hosea 10:8

Et disperdentur excelsa idoli, peccatum Israël ;  lappa et tribulus ascendet super aras eorum :  et dicent montibus : Operite nos,  et collibus : Cadite super nos. 

** Hosea 10:9

Ex diebus Gabaa peccavit Israël ;  ibi steterunt.  Non comprehendet eos in Gabaa  prælium super filios iniquitatis. 

** Hosea 10:10

Juxta desiderium meum corripiam eos :  congregabuntur super eos populi,  cum corripientur propter duas iniquitates suas. 

** Hosea 10:11

Ephraim vitula docta diligere trituram,  et ego transivi super pulchritudinem colli ejus :  ascendam super Ephraim,  arabit Judas ;  confringet sibi sulcos Jacob. 

** Hosea 10:12

Seminate vobis in justitia,  et metite in ore misericordiæ.  Innovate vobis novale ;  tempus autem requirendi Dominum,  cum venerit qui docebit vos justitiam. 

** Hosea 10:13

Arastis impietatem,  iniquitatem messuistis :  comedistis frugem mendacii,  quia confisus es in viis tuis,  in multitudine fortium tuorum. 

** Hosea 10:14

Consurget tumultus in populo tuo ;  et omnes munitiones tuæ vastabuntur,  sicut vastatus est Salmana a domo ejus qui judicavit Baal  in die prælii, matre super filios allisa. 

** Hosea 10:15

Sic fecit vobis Bethel,  a facie malitiæ nequitiarum vestrarum.  

* Hosea 11

** Hosea 11:1

Sicut mane transiit, pertransiit rex Israël.  Quia puer Israël, et dilexi eum ;  et ex Ægypto vocavi filium meum. 

** Hosea 11:2

Vocaverunt eos, sic abierunt a facie eorum ;  Baalim immolabant, et simulacris sacrificabant. 

** Hosea 11:3

Et ego quasi nutritius Ephraim :  portabam eos in brachiis meis,  et nescierunt quod curarem eos. 

** Hosea 11:4

In funiculis Adam traham eos,  in vinculis caritatis ;  et ero eis quasi exaltans jugum super maxillas eorum,  et declinavi ad eum ut vesceretur. 

** Hosea 11:5

Non revertetur in terram Ægypti, et Assur ipse rex ejus,  quoniam noluerunt converti. 

** Hosea 11:6

Cœpit gladius in civitatibus ejus,  et consumet electos ejus,  et comedet capita eorum. 

** Hosea 11:7

Et populus meus pendebit ad reditum meum ;  jugum autem imponetur eis simul, quod non auferetur. 

** Hosea 11:8

Quomodo dabo te, Ephraim ?  protegam te, Israël ?  Quomodo dabo te sicut Adama,  ponam te ut Seboim ?  Conversum est in me cor meum,  pariter conturbata est pœnitudo mea. 

** Hosea 11:9

Non faciam furorem iræ meæ ;  non convertar ut disperdam Ephraim,  quoniam Deus ego, et non homo ;  in medio tui sanctus,  et non ingrediar civitatem. 

** Hosea 11:10

Post Dominum ambulabunt ;  quasi leo rugiet,  quia ipse rugiet,  et formidabunt filii maris. 

** Hosea 11:11

Et avolabunt quasi avis ex Ægypto,  et quasi columba de terra Assyriorum :  et collocabo eos in domibus suis, dicit Dominus. 

** Hosea 11:12

Circumdedit me in negatione Ephraim,  et in dolo domus Israël ;  Judas autem testis descendit cum Deo,  et cum sanctis fidelis.  

* Hosea 12

** Hosea 12:1

Ephraim pascit ventum,  et sequitur æstum ;  tota die mendacium et vastitatem multiplicat :  et fœdus cum Assyriis iniit,  et oleum in Ægyptum ferebat. 

** Hosea 12:2

Judicium ergo Domini cum Juda,  et visitatio super Jacob :  juxta vias ejus, et juxta adinventiones ejus reddet ei. 

** Hosea 12:3

In utero supplantavit fratrem suum,  et in fortitudine sua directus est cum angelo. 

** Hosea 12:4

Et invaluit ad angelum, et confortatus est ;  flevit, et rogavit eum.  In Bethel invenit eum,  et ibi locutus est nobiscum. 

** Hosea 12:5

Et Dominus Deus exercituum,  Dominus memoriale ejus. 

** Hosea 12:6

Et tu ad Deum tuum converteris ;  misericordiam et judicium custodi,  et spera in Deo tuo semper. 

** Hosea 12:7

Chanaan, in manu ejus statera dolosa,  calumniam dilexit. 

** Hosea 12:8

Et dixit Ephraim : Verumtamen dives effectus sum ;  inveni idolum mihi :  omnes labores mei non invenient mihi iniquitatem quam peccavi. 

** Hosea 12:9

Et ego Dominus Deus tuus ex terra Ægypti :  adhuc sedere te faciam in tabernaculis, sicut in diebus festivitatis. 

** Hosea 12:10

Et locutus sum super prophetas,  et ego visionem multiplicavi,  et in manu prophetarum assimilatus sum. 

** Hosea 12:11

Si Galaad idolum, ergo frustra erant in Galgal bobus immolantes ;  nam et altaria eorum quasi acervi super sulcos agri. 

** Hosea 12:12

Fugit Jacob in regionem Syriæ,  et servivit Israël in uxorem,  et in uxorem servavit. 

** Hosea 12:13

In propheta autem eduxit Dominus Israël de Ægypto,  et in propheta servatus est. 

** Hosea 12:14

Ad iracundiam me provocavit Ephraim in amaritudinibus suis :  et sanguis ejus super eum veniet,  et opprobrium ejus restituet ei Dominus suus.  

* Hosea 13

** Hosea 13:1

Loquente Ephraim, horror invasit Israël ;  et deliquit in Baal, et mortuus est. 

** Hosea 13:2

Et nunc addiderunt ad peccandum ;  feceruntque sibi conflatile de argento suo  quasi similitudinem idolorum :  factura artificum totum est :  his ipsi dicunt : Immolate homines, vitulos adorantes. 

** Hosea 13:3

Idcirco erunt quasi nubes matutina,  et sicut ros matutinus præteriens ;  sicut pulvis turbine raptus ex area,  et sicut fumus de fumario. 

** Hosea 13:4

Ego autem Dominus Deus tuus, ex terra Ægypti ;  et Deum absque me nescies,  et salvator non est præter me. 

** Hosea 13:5

Ego cognovi te in deserto,  in terra solitudinis. 

** Hosea 13:6

Juxta pascua sua adimpleti sunt et saturati sunt ;  et levaverunt cor suum, et obliti sunt mei. 

** Hosea 13:7

Et ego ero eis quasi leæna,  sicut pardus in via Assyriorum. 

** Hosea 13:8

Occurram eis quasi ursa raptis catulis,  et dirumpam interiora jecoris eorum,  et consumam eos ibi quasi leo :  bestia agri scindet eos. 

** Hosea 13:9

Perditio tua, Israël : tantummodo in me auxilium tuum. 

** Hosea 13:10

Ubi est rex tuus ?  maxime nunc salvet te in omnibus urbibus tuis ;  et judices tui, de quibus dixisti :  Da mihi regem et principes. 

** Hosea 13:11

Dabo tibi regem in furore meo,  et auferam in indignatione mea. 

** Hosea 13:12

Colligata est iniquitas Ephraim ;  absconditum peccatum ejus. 

** Hosea 13:13

Dolores parturientis venient ei :  ipse filius non sapiens :  nunc enim non stabit in contritione filiorum. 

** Hosea 13:14

De manu mortis liberabo eos ;  de morte redimam eos.  Ero mors tua, o mors !  morsus tuus ero, inferne !  consolatio abscondita est ab oculis meis. 

** Hosea 13:15

Quia ipse inter fratres dividet :  adducet urentem ventum Dominus de deserto ascendentem,  et siccabit venas ejus,  et desolabit fontem ejus :  et ipse diripiet thesaurum omnis vasis desiderabilis.  

* Hosea 14

** Hosea 14:1

Pereat Samaria, quoniam ad amaritudinem concitavit Deum suum !  in gladio pereant,  parvuli eorum elidantur,  et fœtæ ejus discindantur ! 

** Hosea 14:2

Convertere, Israël, ad Dominum Deum tuum,  quoniam corruisti in iniquitate tua. 

** Hosea 14:3

Tollite vobiscum verba,  et convertimini ad Dominum ; et dicite ei :  Omnem aufer iniquitatem, accipe bonum,  et reddemus vitulos labiorum nostrorum. 

** Hosea 14:4

Assur non salvabit nos :  super equum non ascendemus,  nec dicemus ultra, Dii nostri opera manuum nostrarum :  quia ejus, qui in te est, misereberis pupilli. 

** Hosea 14:5

Sanabo contritiones eorum ;  diligam eos spontanee :  quia aversus est furor meus ab eis. 

** Hosea 14:6

Ero quasi ros ;  Israël germinabit sicut lilium,  et erumpet radix ejus ut Libani. 

** Hosea 14:7

Ibunt rami ejus,  et erit quasi oliva gloria ejus,  et odor ejus ut Libani. 

** Hosea 14:8

Convertentur sedentes in umbra ejus ;  vivent tritico, et germinabunt quasi vinea ;  memoriale ejus sicut vinum Libani. 

** Hosea 14:9

Ephraim, quid mihi ultra idola ?  Ego exaudiam, et dirigam eum ego ut abietem virentem ;  ex me fructus tuus inventus est. 

** Hosea 14:10

Quis sapiens, et intelliget ista ? intelligens, et sciet hæc ?  quia rectæ viæ Domini,  et justi ambulabunt in eis ;  prævaricatores vero corruent in eis.    

