* James 1

** James 1:1

Jacobus, Dei et Domini nostri Jesu Christi servus, duodecim tribubus, quæ sunt in dispersione, salutem.  

** James 1:2

Omne gaudium existimate fratres mei, cum in tentationes varias incideritis :

** James 1:3

scientes quod probatio fidei vestræ patientiam operatur.

** James 1:4

Patientia autem opus perfectum habet : ut sitis perfecti et integri in nullo deficientes.

** James 1:5

Si quis autem vestrum indiget sapientia, postulet a Deo, qui dat omnibus affluenter, et non improperat : et dabitur ei.

** James 1:6

Postulet autem in fide nihil hæsitans : qui enim hæsitat, similis est fluctui maris, qui a vento movetur et circumfertur :

** James 1:7

non ergo æstimet homo ille quod accipiat aliquid a Domino.

** James 1:8

Vir duplex animo inconstans est in omnibus viis suis.

** James 1:9

Glorietur autem frater humilis in exaltatione sua :

** James 1:10

dives autem in humilitate sua, quoniam sicut flos fœni transibit ;

** James 1:11

exortus est enim sol cum ardore, et arefecit fœnum, et flos ejus decidit, et decor vultus ejus deperiit : ita et dives in itineribus suis marcescet.

** James 1:12

Beatus vir qui suffert tentationem : quoniam cum probatus fuerit, accipiet coronam vitæ, quam repromisit Deus diligentibus se.

** James 1:13

Nemo cum tentatur, dicat quoniam a Deo tentatur : Deus enim intentator malorum est : ipse autem neminem tentat.

** James 1:14

Unusquisque vero tentatur a concupiscentia sua abstractus, et illectus.

** James 1:15

Deinde concupiscentia cum conceperit, parit peccatum : peccatum vero cum consummatum fuerit, generat mortem.

** James 1:16

Nolite itaque errare, fratres mei dilectissimi.

** James 1:17

Omne datum optimum, et omne donum perfectum desursum est, descendens a Patre luminum, apud quem non est transmutatio, nec vicissitudinis obumbratio.

** James 1:18

Voluntarie enim genuit nos verbo veritatis, ut simus initium aliquod creaturæ ejus.  

** James 1:19

Scitis, fratres mei dilectissimi. Sit autem omnis homo velox ad audiendum : tardus autem ad loquendum, et tardus ad iram.

** James 1:20

Ira enim viri justitiam Dei non operatur.

** James 1:21

Propter quod abjicientes omnem immunditiam, et abundantiam malitiæ, in mansuetudine suscipite insitum verbum, quod potest salvare animas vestras.

** James 1:22

Estote autem factores verbi, et non auditores tantum : fallentes vosmetipsos.

** James 1:23

Quia si quis auditor est verbi, et non factor, hic comparabitur viro consideranti vultum nativitatis suæ in speculo :

** James 1:24

consideravit enim se, et abiit, et statim oblitus est qualis fuerit.

** James 1:25

Qui autem perspexerit in legem perfectam libertatis, et permanserit in ea, non auditor obliviosus factus, sed factor operis : hic beatus in facto suo erit.

** James 1:26

Si quis autem putat se religiosum esse, non refrenans linguam suam, sed seducens cor suum, hujus vana est religio.

** James 1:27

Religio munda et immaculata apud Deum et Patrem, hæc est : visitare pupillos et viduas in tribulatione eorum, et immaculatum se custodire ab hoc sæculo.   

* James 2

** James 2:1

Fratres mei, nolite in personarum acceptione habere fidem Domini nostri Jesu Christi gloriæ.

** James 2:2

Etenim si introierit in conventum vestrum vir aureum annulum habens in veste candida, introierit autem et pauper in sordido habitu,

** James 2:3

et intendatis in eum qui indutus est veste præclara, et dixeritis ei : Tu sede hic bene : pauperi autem dicatis : Tu sta illic ; aut sede sub scabello pedum meorum :

** James 2:4

nonne judicatis apud vosmetipsos, et facti estis judices cogitationum iniquarum ?

** James 2:5

Audite, fratres mei dilectissimi : nonne Deus elegit pauperes in hoc mundo, divites in fide, et hæredes regni, quod repromisit Deus diligentibus se ?

** James 2:6

vos autem exhonorastis pauperem. Nonne divites per potentiam opprimunt vos, et ipsi trahunt vos ad judicia ?

** James 2:7

nonne ipsi blasphemant bonum nomen, quod invocatum est super vos ?

** James 2:8

Si tamen legem perficitis regalem secundum Scripturas : Diliges proximum tuum sicut teipsum : bene facitis :

** James 2:9

si autem personas accipitis, peccatum operamini, redarguti a lege quasi transgressores.

** James 2:10

Quicumque autem totam legem servaverit, offendat autem in uno, factus est omnium reus.

** James 2:11

Qui enim dixit : Non mœchaberis, dixit et : Non occides. Quod si non mœchaberis, occides autem, factus es transgressor legis.

** James 2:12

Sic loquimini, et sic facite sicut per legem libertatis incipientes judicari.

** James 2:13

Judicium enim sine misericordia illi qui non fecit misericordiam : superexaltat autem misericordia judicium.  

** James 2:14

Quid proderit, fratres mei, si fidem quis dicat se habere, opera autem non habeat ? numquid poterit fides salvare eum ?

** James 2:15

Si autem frater et soror nudi sint, et indigeant victu quotidiano,

** James 2:16

dicat autem aliquis ex vobis illis : Ite in pace, calefacimini et saturamini : non dederitis autem eis quæ necessaria sunt corpori, quid proderit ?

** James 2:17

Sic et fides, si non habeat opera, mortua est in semetipsa.

** James 2:18

Sed dicet quis : Tu fidem habes, et ego opera habeo : ostende mihi fidem tuam sine operibus : et ego ostendam tibi ex operibus fidem meam.

** James 2:19

Tu credis quoniam unus est Deus : bene facis : et dæmones credunt, et contremiscunt.

** James 2:20

Vis autem scire, o homo inanis, quoniam fides sine operibus mortua est ?

** James 2:21

Abraham pater noster nonne ex operibus justificatus est, offerens Isaac filium suum super altare ?

** James 2:22

Vides quoniam fides cooperabatur operibus illius : et ex operibus fides consummata est ?

** James 2:23

Et suppleta est Scriptura, dicens : Credidit Abraham Deo, et reputatum est illi ad justitiam, et amicus Dei appellatus est.

** James 2:24

Videtis quoniam ex operibus justificatur homo, et non ex fide tantum ?

** James 2:25

Similiter et Rahab meretrix, nonne ex operibus justificata est, suscipiens nuntios, et alia via ejiciens ?

** James 2:26

Sicut enim corpus sine spiritu mortuum est, ita et fides sine operibus mortua est.   

* James 3

** James 3:1

Nolite plures magistri fieri fratres mei, scientes quoniam majus judicium sumitis.

** James 3:2

In multis enim offendimus omnes. Si quis in verbo non offendit, hic perfectus est vir : potest etiam freno circumducere totum corpus.

** James 3:3

Si autem equis frena in ora mittimus ad consentiendum nobis, et omne corpus illorum circumferimus.

** James 3:4

Ecce et naves, cum magnæ sint, et a ventis validis minentur, circumferuntur a modico gubernaculo ubi impetus dirigentis voluerit.

** James 3:5

Ita et lingua modicum quidem membrum est, et magna exaltat. Ecce quantus ignis quam magnam silvam incendit !

** James 3:6

Et lingua ignis est, universitas iniquitatis. Lingua constituitur in membris nostris, quæ maculat totum corpus, et inflammat rotam nativitatis nostræ inflammata a gehenna.

** James 3:7

Omnis enim natura bestiarum, et volucrum, et serpentium, et ceterorum domantur, et domita sunt a natura humana :

** James 3:8

linguam autem nullus hominum domare potest : inquietum malum, plena veneno mortifero.

** James 3:9

In ipsa benedicimus Deum et Patrem : et in ipsa maledicimus homines, qui ad similitudinem Dei facti sunt.

** James 3:10

Ex ipso ore procedit benedictio et maledictio. Non oportet, fratres mei, hæc ita fieri.

** James 3:11

Numquid fons de eodem foramine emanat dulcem et amaram aquam ?

** James 3:12

Numquid potest, fratres mei, ficus uvas facere, aut vitis ficus ? Sic neque salsa dulcem potest facere aquam.  

** James 3:13

Quis sapiens et disciplinatus inter vos ? Ostendat ex bona conversatione operationem suam in mansuetudine sapientiæ.

** James 3:14

Quod si zelum amarum habetis, et contentiones sint in cordibus vestris : nolite gloriari, et mendaces esse adversus veritatem :

** James 3:15

non est enim ista sapientia desursum descendens : sed terrena, animalis, diabolica.

** James 3:16

Ubi enim zelus et contentio, ibi inconstantia et omne opus pravum.

** James 3:17

Quæ autem desursum est sapientia, primum quidem pudica est, deinde pacifica, modesta, suadibilis, bonis consentiens, plena misericordia et fructibus bonis, non judicans, sine simulatione.

** James 3:18

Fructus autem justitiæ, in pace seminatur, facientibus pacem.   

* James 4

** James 4:1

Unde bella et lites in vobis ? nonne hinc : ex concupiscentiis vestris, quæ militant in membris vestris ?

** James 4:2

concupiscitis, et non habetis : occiditis, et zelatis : et non potestis adipisci : litigatis, et belligeratis, et non habetis, propter quod non postulatis.

** James 4:3

Petitis, et non accipitis : eo quod male petatis : ut in concupiscentiis vestris insumatis.

** James 4:4

Adulteri, nescitis quia amicitia hujus mundi inimica est Dei ? quicumque ergo voluerit amicus esse sæculi hujus, inimicus Dei constituitur.

** James 4:5

An putatis quia inaniter Scriptura dicat : Ad invidiam concupiscit spiritus qui habitat in vobis ?

** James 4:6

majorem autem dat gratiam. Propter quod dicit : Deus superbis resistit, humilibus autem dat gratiam.

** James 4:7

Subditi ergo estote Deo, resistite autem diabolo, et fugiet a vobis.

** James 4:8

Appropinquate Deo, et appropinquabit vobis. Emundate manus, peccatores : et purificate corda, duplices animo.

** James 4:9

Miseri estote, et lugete, et plorate : risus vester in luctum convertatur, et gaudium in mœrorem.

** James 4:10

Humiliamini in conspectu Domini, et exaltabit vos.

** James 4:11

Nolite detrahere alterutrum fratres. Qui detrahit fratri, aut qui judicat fratrem suum, detrahit legi, et judicat legem. Si autem judicas legem, non es factor legis, sed judex.

** James 4:12

Unus est legislator et judex, qui potest perdere et liberare.  

** James 4:13

Tu autem quis es, qui judicas proximum ? Ecce nunc qui dicitis : Hodie, aut crastino ibimus in illam civitatem, et faciemus ibi quidem annum, et mercabimur, et lucrum faciemus :

** James 4:14

qui ignoratis quid erit in crastino.

** James 4:15

Quæ est enim vita vestra ? vapor est ad modicum parens, et deinceps exterminabitur ; pro eo ut dicatis : Si Dominus voluerit. Et : Si vixerimus, faciemus hoc, aut illud.

** James 4:16

Nunc autem exsultatis in superbiis vestris. Omnis exsultatio talis, maligna est.

** James 4:17

Scienti igitur bonum facere, et non facienti, peccatum est illi.   

* James 5

** James 5:1

Agite nunc divites, plorate ululantes in miseriis vestris, quæ advenient vobis.

** James 5:2

Divitiæ vestræ putrefactæ sunt, et vestimenta vestra a tineis comesta sunt.

** James 5:3

Aurum et argentum vestrum æruginavit : et ærugo eorum in testimonium vobis erit, et manducabit carnes vestras sicut ignis. Thesaurizastis vobis iram in novissimis diebus.

** James 5:4

Ecce merces operariorum, qui messuerunt regiones vestras, quæ fraudata est a vobis, clamat : et clamor eorum in aures Domini sabbaoth introivit.

** James 5:5

Epulati estis super terram, et in luxuriis enutristis corda vestra in die occisionis.

** James 5:6

Addixistis, et occidistis justum, et non restitit vobis.  

** James 5:7

Patientes igitur estote, fratres, usque ad adventum Domini. Ecce agricola exspectat pretiosum fructum terræ, patienter ferens donec accipiat temporaneum et serotinum.

** James 5:8

Patientes igitur estote et vos, et confirmate corda vestra : quoniam adventus Domini appropinquavit.

** James 5:9

Nolite ingemiscere, fratres, in alterutrum, ut non judicemini. Ecce judex ante januam assistit.

** James 5:10

Exemplum accipite, fratres, exitus mali, laboris, et patientiæ, prophetas qui locuti sunt in nomine Domini.

** James 5:11

Ecce beatificamus eos qui sustinuerunt. Sufferentiam Job audistis, et finem Domini vidistis, quoniam misericors Dominus est, et miserator.  

** James 5:12

Ante omnia autem, fratres mei, nolite jurare, neque per cælum, neque per terram, neque aliud quodcumque juramentum. Sit autem sermo vester : Est, est : Non, non : ut non sub judicio decidatis.  

** James 5:13

Tristatur aliquis vestrum ? oret. Æquo animo est ? psallat.

** James 5:14

Infirmatur quis in vobis ? inducat presbyteros ecclesiæ, et orent super eum, ungentes eum oleo in nomine Domini :

** James 5:15

et oratio fidei salvabit infirmum, et alleviabit eum Dominus : et si in peccatis sit, remittentur ei.

** James 5:16

Confitemini ergo alterutrum peccata vestra, et orate pro invicem ut salvemini : multum enim valet deprecatio justi assidua.

** James 5:17

Elias homo erat similis nobis passibilis : et oratione oravit ut non plueret super terram, et non pluit annos tres, et menses sex.

** James 5:18

Et rursum oravit : et cælum dedit pluviam, et terra dedit fructum suum.  

** James 5:19

Fratres mei, si quis ex vobis erraverit a veritate, et converterit quis eum :

** James 5:20

scire debet quoniam qui converti fecerit peccatorem ab errore viæ suæ, salvabit animam ejus a morte, et operiet multitudinem peccatorum.    

