* John 1

** John 1:1

In principio erat Verbum,  et Verbum erat apud Deum,  et Deus erat Verbum. 

** John 1:2

Hoc erat in principio apud Deum. 

** John 1:3

Omnia per ipsum facta sunt :  et sine ipso factum est nihil, quod factum est. 

** John 1:4

In ipso vita erat,  et vita erat lux hominum : 

** John 1:5

et lux in tenebris lucet,  et tenebræ eam non comprehenderunt. 

** John 1:6

Fuit homo  missus a Deo,  cui nomen erat Joannes. 

** John 1:7

Hic venit in testimonium  ut testimonium perhiberet de lumine,  ut omnes crederent per illum. 

** John 1:8

Non erat ille lux,  sed ut testimonium perhiberet de lumine. 

** John 1:9

Erat lux vera,  quæ illuminat omnem hominem  venientem in hunc mundum. 

** John 1:10

In mundo erat,  et mundus per ipsum factus est,  et mundus eum non cognovit. 

** John 1:11

In propria venit,  et sui eum non receperunt. 

** John 1:12

Quotquot autem receperunt eum,  dedit eis potestatem filios Dei fieri,  his qui credunt in nomine ejus : 

** John 1:13

qui non ex sanguinibus,  neque ex voluntate carnis,  neque ex voluntate viri,  sed ex Deo nati sunt. 

** John 1:14

Et Verbum caro factum est,  et habitavit in nobis :  et vidimus gloriam ejus,  gloriam quasi unigeniti a Patre  plenum gratiæ et veritatis. 

** John 1:15

Joannes testimonium perhibet de ipso,  et clamat dicens :  Hic erat quem dixi :  Qui post me venturus est,  ante me factus est :  quia prior me erat. 

** John 1:16

Et de plenitudine ejus  nos omnes accepimus, et gratiam pro gratia : 

** John 1:17

quia lex per Moysen data est,  gratia et veritas per Jesum Christum facta est. 

** John 1:18

Deum nemo vidit umquam :  unigenitus Filius, qui est in sinu Patris,  ipse enarravit.  

** John 1:19

Et hoc est testimonium Joannis, quando miserunt Judæi ab Jerosolymis sacerdotes et Levitas ad eum ut interrogarent eum : Tu quis es ?

** John 1:20

Et confessus est, et non negavit, et confessus est : Quia non sum ego Christus.

** John 1:21

Et interrogaverunt eum : Quid ergo ? Elias es tu ? Et dixit : Non sum. Propheta es tu ? Et respondit : Non.

** John 1:22

Dixerunt ergo ei : Quis es ut responsum demus his qui miserunt nos ? quid dicis de teipso ?

** John 1:23

Ait : Ego vox clamantis in deserto : Dirigite viam Domini, sicut dixit Isaias propheta.

** John 1:24

Et qui missi fuerant, erant ex pharisæis.

** John 1:25

Et interrogaverunt eum, et dixerunt ei : Quid ergo baptizas, si tu non es Christus, neque Elias, neque propheta ?

** John 1:26

Respondit eis Joannes, dicens : Ego baptizo in aqua : medius autem vestrum stetit, quem vos nescitis.

** John 1:27

Ipse est qui post me venturus est, qui ante me factus est : cujus ego non sum dignus ut solvam ejus corrigiam calceamenti.

** John 1:28

Hæc in Bethania facta sunt trans Jordanem, ubi erat Joannes baptizans.  

** John 1:29

Altera die vidit Joannes Jesum venientem ad se, et ait : Ecce agnus Dei, ecce qui tollit peccatum mundi.

** John 1:30

Hic est de quo dixi : Post me venit vir qui ante me factus est : quia prior me erat :

** John 1:31

et ego nesciebam eum, sed ut manifestetur in Israël, propterea veni ego in aqua baptizans.

** John 1:32

Et testimonium perhibuit Joannes, dicens : Quia vidi Spiritum descendentem quasi columbam de cælo, et mansit super eum.

** John 1:33

Et ego nesciebam eum : sed qui misit me baptizare in aqua, ille mihi dixit : Super quem videris Spiritum descendentem, et manentem super eum, hic est qui baptizat in Spiritu Sancto.

** John 1:34

Et ego vidi : et testimonium perhibui quia hic est Filius Dei.  

** John 1:35

Altera die iterum stabat Joannes, et ex discipulis ejus duo.

** John 1:36

Et respiciens Jesum ambulantem, dicit : Ecce agnus Dei.

** John 1:37

Et audierunt eum duo discipuli loquentem, et secuti sunt Jesum.

** John 1:38

Conversus autem Jesus, et videns eos sequentes se, dicit eis : Quid quæritis ? Qui dixerunt ei : Rabbi (quod dicitur interpretatum Magister), ubi habitas ?

** John 1:39

Dicit eis : Venite et videte. Venerunt, et viderunt ubi maneret, et apud eum manserunt die illo : hora autem erat quasi decima.

** John 1:40

Erat autem Andreas, frater Simonis Petri, unus ex duobus qui audierant a Joanne, et secuti fuerant eum.

** John 1:41

Invenit hic primum fratrem suum Simonem, et dicit ei : Invenimus Messiam (quod est interpretatum Christus).

** John 1:42

Et adduxit eum ad Jesum. Intuitus autem eum Jesus, dixit : Tu es Simon, filius Jona ; tu vocaberis Cephas, quod interpretatur Petrus.

** John 1:43

In crastinum voluit exire in Galilæam, et invenit Philippum. Et dicit ei Jesus : Sequere me.

** John 1:44

Erat autem Philippus a Bethsaida, civitate Andreæ et Petri.

** John 1:45

Invenit Philippus Nathanaël, et dicit ei : Quem scripsit Moyses in lege, et prophetæ, invenimus Jesum filium Joseph a Nazareth.

** John 1:46

Et dixit ei Nathanaël : A Nazareth potest aliquid boni esse ? Dicit ei Philippus : Veni et vide.

** John 1:47

Vidit Jesus Nathanaël venientem ad se, et dicit de eo : Ecce vere Israëlita, in quo dolus non est.

** John 1:48

Dicit ei Nathanaël : Unde me nosti ? Respondit Jesus, et dixit ei : Priusquam te Philippus vocavit, cum esses sub ficu, vidi te.

** John 1:49

Respondit ei Nathanaël, et ait : Rabbi, tu es Filius Dei, tu es rex Israël.

** John 1:50

Respondit Jesus, et dixit ei : Quia dixi tibi : Vidi te sub ficu, credis ; majus his videbis.

** John 1:51

Et dicit ei : Amen, amen dico vobis, videbitis cælum apertum, et angelos Dei ascendentes, et descendentes supra Filium hominis.   

* John 2

** John 2:1

Et die tertia nuptiæ factæ sunt in Cana Galilææ, et erat mater Jesu ibi.

** John 2:2

Vocatus est autem et Jesus, et discipuli ejus, ad nuptias.

** John 2:3

Et deficiente vino, dicit mater Jesu ad eum : Vinum non habent.

** John 2:4

Et dicit ei Jesus : Quid mihi et tibi est, mulier ? nondum venit hora mea.

** John 2:5

Dicit mater ejus ministris : Quodcumque dixerit vobis, facite.

** John 2:6

Erant autem ibi lapideæ hydriæ sex positæ secundum purificationem Judæorum, capientes singulæ metretas binas vel ternas.

** John 2:7

Dicit eis Jesus : Implete hydrias aqua. Et impleverunt eas usque ad summum.

** John 2:8

Et dicit eis Jesus : Haurite nunc, et ferte architriclino. Et tulerunt.

** John 2:9

Ut autem gustavit architriclinus aquam vinum factam, et non sciebat unde esset, ministri autem sciebant, qui hauserant aquam : vocat sponsum architriclinus,

** John 2:10

et dicit ei : Omnis homo primum bonum vinum ponit et cum inebriati fuerint, tunc id, quod deterius est. Tu autem servasti bonum vinum usque adhuc.

** John 2:11

Hoc fecit initium signorum Jesus in Cana Galilææ ; et manifestavit gloriam suam, et crediderunt in eum discipuli ejus.

** John 2:12

Post hoc descendit Capharnaum ipse, et mater ejus, et fratres ejus, et discipuli ejus : et ibi manserunt non multis diebus.  

** John 2:13

Et prope erat Pascha Judæorum, et ascendit Jesus Jerosolymam :

** John 2:14

et invenit in templo vendentes boves, et oves, et columbas, et numularios sedentes.

** John 2:15

Et cum fecisset quasi flagellum de funiculis, omnes ejecit de templo, oves quoque, et boves, et numulariorum effudit æs, et mensas subvertit.

** John 2:16

Et his qui columbas vendebant, dixit : Auferte ista hinc, et nolite facere domum patris mei, domum negotiationis.

** John 2:17

Recordati sunt vero discipuli ejus quia scriptum est : Zelus domus tuæ comedit me.

** John 2:18

Responderunt ergo Judæi, et dixerunt ei : Quod signum ostendis nobis, quia hæc facis ?

** John 2:19

Respondit Jesus, et dixit eis : Solvite templum hoc, et in tribus diebus excitabo illud.

** John 2:20

Dixerunt ergo Judæi : Quadraginta et sex annis ædificatum est templum hoc, et tu in tribus diebus excitabis illud ?

** John 2:21

Ille autem dicebat de templo corporis sui.

** John 2:22

Cum ergo resurrexisset a mortuis, recordati sunt discipuli ejus, quia hoc dicebat, et crediderunt scripturæ et sermoni quem dixit Jesus.

** John 2:23

Cum autem esset Jerosolymis in Pascha in die festo, multi crediderunt in nomine ejus, videntes signa ejus, quæ faciebat.

** John 2:24

Ipse autem Jesus non credebat semetipsum eis, eo quod ipse nosset omnes,

** John 2:25

et quia opus ei non erat ut quis testimonium perhiberet de homine : ipse enim sciebat quid esset in homine.   

* John 3

** John 3:1

Erat autem homo ex pharisæis, Nicodemus nomine, princeps Judæorum.

** John 3:2

Hic venit ad Jesum nocte, et dixit ei : Rabbi, scimus quia a Deo venisti magister, nemo enim potest hæc signa facere, quæ tu facis, nisi fuerit Deus cum eo.

** John 3:3

Respondit Jesus, et dixit ei : Amen, amen dico tibi, nisi quis renatus fuerit denuo, non potest videre regnum Dei.

** John 3:4

Dicit ad eum Nicodemus : Quomodo potest homo nasci, cum sit senex ? numquid potest in ventrem matris suæ iterato introire et renasci ?

** John 3:5

Respondit Jesus : Amen, amen dico tibi, nisi quis renatus fuerit ex aqua, et Spiritu Sancto, non potest introire in regnum Dei.

** John 3:6

Quod natum est ex carne, caro est : et quod natum est ex spiritu, spiritus est.

** John 3:7

Non mireris quia dixi tibi : oportet vos nasci denuo.

** John 3:8

Spiritus ubi vult spirat, et vocem ejus audis, sed nescis unde veniat, aut quo vadat : sic est omnis qui natus est ex spiritu.

** John 3:9

Respondit Nicodemus, et dixit ei : Quomodo possunt hæc fieri ?

** John 3:10

Respondit Jesus, et dixit ei : Tu es magister in Israël, et hæc ignoras ?

** John 3:11

Amen, amen dico tibi, quia quod scimus loquimur, et quod vidimus testamur, et testimonium nostrum non accipitis.

** John 3:12

Si terrena dixi vobis, et non creditis : quomodo, si dixero vobis cælestia, credetis ?

** John 3:13

Et nemo ascendit in cælum, nisi qui descendit de cælo, Filius hominis, qui est in cælo.

** John 3:14

Et sicut Moyses exaltavit serpentem in deserto, ita exaltari oportet Filium hominis :

** John 3:15

ut omnis qui credit in ipsum, non pereat, sed habeat vitam æternam.

** John 3:16

Sic enim Deus dilexit mundum, ut Filium suum unigenitum daret : ut omnis qui credit in eum, non pereat, sed habeat vitam æternam.

** John 3:17

Non enim misit Deus Filium suum in mundum, ut judicet mundum, sed ut salvetur mundus per ipsum.

** John 3:18

Qui credit in eum, non judicatur ; qui autem non credit, jam judicatus est : quia non credit in nomine unigeniti Filii Dei.

** John 3:19

Hoc est autem judicium : quia lux venit in mundum, et dilexerunt homines magis tenebras quam lucem : erant enim eorum mala opera.

** John 3:20

Omnis enim qui male agit, odit lucem, et non venit ad lucem, ut non arguantur opera ejus :

** John 3:21

qui autem facit veritatem, venit ad lucem, ut manifestentur opera ejus, quia in Deo sunt facta.  

** John 3:22

Post hæc venit Jesus et discipuli ejus in terram Judæam : et illic demorabatur cum eis, et baptizabat.

** John 3:23

Erat autem et Joannes baptizans, in Ænnon, juxta Salim : quia aquæ multæ erant illic, et veniebant et baptizabantur.

** John 3:24

Nondum enim missus fuerat Joannes in carcerem.

** John 3:25

Facta est autem quæstio ex discipulis Joannis cum Judæis de purificatione.

** John 3:26

Et venerunt ad Joannem, et dixerunt ei : Rabbi, qui erat tecum trans Jordanem, cui tu testimonium perhibuisti, ecce hic baptizat, et omnes veniunt ad eum.

** John 3:27

Respondit Joannes, et dixit : Non potest homo accipere quidquam, nisi fuerit ei datum de cælo.

** John 3:28

Ipsi vos mihi testimonium perhibetis, quod dixerim : Non sum ego Christus : sed quia missus sum ante illum.

** John 3:29

Qui habet sponsam, sponsus est : amicus autem sponsi, qui stat, et audit eum, gaudio gaudet propter vocem sponsi. Hoc ergo gaudium meum impletum est.

** John 3:30

Illum oportet crescere, me autem minui.

** John 3:31

Qui desursum venit, super omnes est. Qui est de terra, de terra est, et de terra loquitur. Qui de cælo venit, super omnes est.

** John 3:32

Et quod vidit, et audivit, hoc testatur : et testimonium ejus nemo accipit.

** John 3:33

Qui accepit ejus testimonium signavit, quia Deus verax est.

** John 3:34

Quem enim misit Deus, verba Dei loquitur : non enim ad mensuram dat Deus spiritum.

** John 3:35

Pater diligit Filium et omnia dedit in manu ejus.

** John 3:36

Qui credit in Filium, habet vitam æternam ; qui autem incredulus est Filio, non videbit vitam, sed ira Dei manet super eum.   

* John 4

** John 4:1

Ut ergo cognovit Jesus quia audierunt pharisæi quod Jesus plures discipulos facit, et baptizat, quam Joannes

** John 4:2

(quamquam Jesus non baptizaret, sed discipuli ejus),

** John 4:3

reliquit Judæam, et abiit iterum in Galilæam.

** John 4:4

Oportebat autem eum transire per Samariam.  

** John 4:5

Venit ergo in civitatem Samariæ, quæ dicitur Sichar, juxta prædium quod dedit Jacob Joseph filio suo.

** John 4:6

Erat autem ibi fons Jacob. Jesus ergo fatigatus ex itinere, sedebat sic supra fontem. Hora erat quasi sexta.

** John 4:7

Venit mulier de Samaria haurire aquam. Dicit ei Jesus : Da mihi bibere.

** John 4:8

(Discipuli enim ejus abierant in civitatem ut cibos emerent.)

** John 4:9

Dicit ergo ei mulier illa Samaritana : Quomodo tu, Judæus cum sis, bibere a me poscis, quæ sum mulier Samaritana ? non enim coutuntur Judæi Samaritanis.

** John 4:10

Respondit Jesus, et dixit ei : Si scires donum Dei, et quis est qui dicit tibi : Da mihi bibere, tu forsitan petisses ab eo, et dedisset tibi aquam vivam.

** John 4:11

Dicit ei mulier : Domine, neque in quo haurias habes, et puteus altus est : unde ergo habes aquam vivam ?

** John 4:12

Numquid tu major es patre nostro Jacob, qui dedit nobis puteum, et ipse ex eo bibit, et filii ejus, et pecora ejus ?

** John 4:13

Respondit Jesus, et dixit ei : Omnis qui bibit ex aqua hac, sitiet iterum ; qui autem biberit ex aqua quam ego dabo ei, non sitiet in æternum :

** John 4:14

sed aqua quam ego dabo ei, fiet in eo fons aquæ salientis in vitam æternam.

** John 4:15

Dicit ad eum mulier : Domine, da mihi hanc aquam, ut non sitiam, neque veniam huc haurire.

** John 4:16

Dicit ei Jesus : Vade, voca virum tuum, et veni huc.

** John 4:17

Respondit mulier, et dixit : Non habeo virum. Dicit ei Jesus : Bene dixisti, quia non habeo virum ;

** John 4:18

quinque enim viros habuisti, et nunc, quem habes, non est tuus vir : hoc vere dixisti.

** John 4:19

Dicit ei mulier : Domine, video quia propheta es tu.

** John 4:20

Patres nostri in monte hoc adoraverunt, et vos dicitis, quia Jerosolymis est locus ubi adorare oportet.

** John 4:21

Dicit ei Jesus : Mulier, crede mihi, quia venit hora, quando neque in monte hoc, neque in Jerosolymis adorabitis Patrem.

** John 4:22

Vos adoratis quod nescitis : nos adoramus quod scimus, quia salus ex Judæis est.

** John 4:23

Sed venit hora, et nunc est, quando veri adoratores adorabunt Patrem in spiritu et veritate. Nam et Pater tales quærit, qui adorent eum.

** John 4:24

Spiritus est Deus : et eos qui adorant eum, in spiritu et veritate oportet adorare.

** John 4:25

Dicit ei mulier : Scio quia Messias venit (qui dicitur Christus) : cum ergo venerit ille, nobis annuntiabit omnia.

** John 4:26

Dicit ei Jesus : Ego sum, qui loquor tecum.

** John 4:27

Et continuo venerunt discipuli ejus, et mirabantur quia cum muliere loquebatur. Nemo tamen dixit : Quid quæris ? aut, Quid loqueris cum ea ?

** John 4:28

Reliquit ergo hydriam suam mulier, et abiit in civitatem, et dicit illis hominibus :

** John 4:29

Venite, et videte hominem qui dixit mihi omnia quæcumque feci : numquid ipse est Christus ?

** John 4:30

Exierunt ergo de civitate et veniebant ad eum.

** John 4:31

Interea rogabant eum discipuli, dicentes : Rabbi, manduca.

** John 4:32

Ille autem dicit eis : Ego cibum habeo manducare, quem vos nescitis.

** John 4:33

Dicebant ergo discipuli ad invicem : Numquid aliquis attulit ei manducare ?

** John 4:34

Dicit eis Jesus : Meus cibus est ut faciam voluntatem ejus qui misit me, ut perficiam opus ejus.

** John 4:35

Nonne vos dicitis quod adhuc quatuor menses sunt, et messis venit ? Ecce dico vobis : levate oculos vestros, et videte regiones, quia albæ sunt jam ad messem.

** John 4:36

Et qui metit, mercedem accipit, et congregat fructum in vitam æternam : ut et qui seminat, simul gaudeat, et qui metit.

** John 4:37

In hoc enim est verbum verum : quia alius est qui seminat, et alius est qui metit.

** John 4:38

Ego misi vos metere quod vos non laborastis : alii laboraverunt, et vos in labores eorum introistis.

** John 4:39

Ex civitate autem illa multi crediderunt in eum Samaritanorum, propter verbum mulieris testimonium perhibentis : Quia dixit mihi omnia quæcumque feci.

** John 4:40

Cum venissent ergo ad illum Samaritani, rogaverunt eum ut ibi maneret. Et mansit ibi duos dies.

** John 4:41

Et multo plures crediderunt in eum propter sermonem ejus.

** John 4:42

Et mulieri dicebant : Quia jam non propter tuam loquelam credimus : ipsi enim audivimus, et scimus quia hic est vere Salvator mundi.  

** John 4:43

Post duos autem dies exiit inde, et abiit in Galilæam.

** John 4:44

Ipse enim Jesus testimonium perhibuit, quia propheta in sua patria honorem non habet.

** John 4:45

Cum ergo venisset in Galilæam, exceperunt eum Galilæi, cum omnia vidissent quæ fecerat Jerosolymis in die festo : et ipsi enim venerant ad diem festum.

** John 4:46

Venit ergo iterum in Cana Galilææ, ubi fecit aquam vinum. Et erat quidam regulus, cujus filius infirmabatur Capharnaum.

** John 4:47

Hic cum audisset quia Jesus adveniret a Judæa in Galilæam, abiit ad eum, et rogabat eum ut descenderet, et sanaret filium ejus : incipiebat enim mori.

** John 4:48

Dixit ergo Jesus ad eum : Nisi signa et prodigia videritis, non creditis.

** John 4:49

Dicit ad eum regulus : Domine, descende priusquam moriatur filius meus.

** John 4:50

Dicit ei Jesus : Vade, filius tuus vivit. Credidit homo sermoni quem dixit ei Jesus, et ibat.

** John 4:51

Jam autem eo descendente, servi occurrerunt ei, et nuntiaverunt dicentes, quia filius ejus viveret.

** John 4:52

Interrogabat ergo horam ab eis in qua melius habuerit. Et dixerunt ei : Quia heri hora septima reliquit eum febris.

** John 4:53

Cognovit ergo pater, quia illa hora erat in qua dixit ei Jesus : Filius tuus vivit ; et credidit ipse et domus ejus tota.

** John 4:54

Hoc iterum secundum signum fecit Jesus, cum venisset a Judæa in Galilæam.   

* John 5

** John 5:1

Post hæc erat dies festus Judæorum, et ascendit Jesus Jerosolymam.

** John 5:2

Est autem Jerosolymis probatica piscina, quæ cognominatur hebraice Bethsaida, quinque porticus habens.

** John 5:3

In his jacebat multitudo magna languentium, cæcorum, claudorum, aridorum, exspectantium aquæ motum.

** John 5:4

Angelus autem Domini descendebat secundum tempus in piscinam, et movebatur aqua. Et qui prior descendisset in piscinam post motionem aquæ, sanus fiebat a quacumque detinebatur infirmitate.

** John 5:5

Erat autem quidam homo ibi triginta et octo annos habens in infirmitate sua.

** John 5:6

Hunc autem cum vidisset Jesus jacentem, et cognovisset quia jam multum tempus haberet, dicit ei : Vis sanus fieri ?

** John 5:7

Respondit ei languidus : Domine, hominem non habeo, ut, cum turbata fuerit aqua, mittat me in piscinam : dum venio enim ego, alius ante me descendit.

** John 5:8

Dicit ei Jesus : Surge, tolle grabatum tuum et ambula.

** John 5:9

Et statim sanus factus est homo ille : et sustulit grabatum suum, et ambulabat. Erat autem sabbatum in die illo.  

** John 5:10

Dicebant ergo Judæi illi qui sanatus fuerat : Sabbatum est, non licet tibi tollere grabatum tuum.

** John 5:11

Respondit eis : Qui me sanum fecit, ille mihi dixit : Tolle grabatum tuum et ambula.

** John 5:12

Interrogaverunt ergo eum : Quis est ille homo qui dixit tibi : Tolle grabatum tuum et ambula ?

** John 5:13

Is autem qui sanus fuerat effectus, nesciebat quis esset. Jesus enim declinavit a turba constituta in loco.

** John 5:14

Postea invenit eum Jesus in templo, et dixit illi : Ecce sanus factus es ; jam noli peccare, ne deterius tibi aliquid contingat.

** John 5:15

Abiit ille homo, et nuntiavit Judæis quia Jesus esset, qui fecit eum sanum.

** John 5:16

Propterea persequebantur Judæi Jesum, quia hæc faciebat in sabbato.

** John 5:17

Jesus autem respondit eis : Pater meus usque modo operatur, et ego operor.

** John 5:18

Propterea ergo magis quærebant eum Judæi interficere : quia non solum solvebat sabbatum, sed et patrem suum dicebat Deum, æqualem se faciens Deo.   Respondit itaque Jesus, et dixit eis :

** John 5:19

Amen, amen dico vobis : non potest Filius a se facere quidquam, nisi quod viderit Patrem facientem : quæcumque enim ille fecerit, hæc et Filius similiter facit.

** John 5:20

Pater enim diligit Filium, et omnia demonstrat ei quæ ipse facit : et majora his demonstrabit ei opera, ut vos miremini.

** John 5:21

Sicut enim Pater suscitat mortuos, et vivificat, sic et Filius, quos vult, vivificat.

** John 5:22

Neque enim Pater judicat quemquam : sed omne judicium dedit Filio,

** John 5:23

ut omnes honorificent Filium, sicut honorificant Patrem ; qui non honorificat Filium, non honorificat Patrem, qui misit illum.

** John 5:24

Amen, amen dico vobis, quia qui verbum meum audit, et credit ei qui misit me, habet vitam æternam, et in judicium non venit, sed transiit a morte in vitam.

** John 5:25

Amen, amen dico vobis, quia venit hora, et nunc est, quando mortui audient vocem Filii Dei : et qui audierint, vivent.

** John 5:26

Sicut enim Pater habet vitam in semetipso, sic dedit et Filio habere vitam in semetipso :

** John 5:27

et potestatem dedit ei judicium facere, quia Filius hominis est.

** John 5:28

Nolite mirari hoc, quia venit hora in qua omnes qui in monumentis sunt audient vocem Filii Dei :

** John 5:29

et procedent qui bona fecerunt, in resurrectionem vitæ ; qui vero mala egerunt, in resurrectionem judicii.

** John 5:30

Non possum ego a meipso facere quidquam. Sicut audio, judico : et judicium meum justum est, quia non quæro voluntatem meam, sed voluntatem ejus qui misit me.  

** John 5:31

Si ego testimonium perhibeo de meipso, testimonium meum non est verum.

** John 5:32

Alius est qui testimonium perhibet de me : et scio quia verum est testimonium, quod perhibet de me.

** John 5:33

Vos misistis ad Joannem, et testimonium perhibuit veritati.

** John 5:34

Ego autem non ab homine testimonium accipio : sed hæc dico ut vos salvi sitis.

** John 5:35

Ille erat lucerna ardens et lucens : vos autem voluistis ad horam exsultare in luce ejus.

** John 5:36

Ego autem habeo testimonium majus Joanne. Opera enim quæ dedit mihi Pater ut perficiam ea : ipsa opera, quæ ego facio, testimonium perhibent de me, quia Pater misit me :

** John 5:37

et qui misit me Pater, ipse testimonium perhibuit de me : neque vocem ejus umquam audistis, neque speciem ejus vidistis :

** John 5:38

et verbum ejus non habetis in vobis manens : quia quem misit ille, huic vos non creditis.

** John 5:39

Scrutamini Scripturas, quia vos putatis in ipsis vitam æternam habere : et illæ sunt quæ testimonium perhibent de me :

** John 5:40

et non vultis venire ad me ut vitam habeatis.

** John 5:41

Claritatem ab hominibus non accipio.

** John 5:42

Sed cognovi vos, quia dilectionem Dei non habetis in vobis.

** John 5:43

Ego veni in nomine Patris mei, et non accipitis me ; si alius venerit in nomine suo, illum accipietis.

** John 5:44

Quomodo vos potestis credere, qui gloriam ab invicem accipitis, et gloriam quæ a solo Deo est, non quæritis ?

** John 5:45

Nolite putare quia ego accusaturus sim vos apud Patrem : est qui accusat vos Moyses, in quo vos speratis.

** John 5:46

Si enim crederetis Moysi, crederetis forsitan et mihi : de me enim ille scripsit.

** John 5:47

Si autem illius litteris non creditis, quomodo verbis meis credetis ?   

* John 6

** John 6:1

Post hæc abiit Jesus trans mare Galilææ, quod est Tiberiadis :

** John 6:2

et sequebatur eum multitudo magna, quia videbant signa quæ faciebat super his qui infirmabantur.

** John 6:3

Subiit ergo in montem Jesus et ibi sedebat cum discipulis suis.

** John 6:4

Erat autem proximum Pascha dies festus Judæorum.

** John 6:5

Cum sublevasset ergo oculos Jesus, et vidisset quia multitudo maxima venit ad eum, dixit ad Philippum : Unde ememus panes, ut manducent hi ?

** John 6:6

Hoc autem dicebat tentans eum : ipse enim sciebat quid esset facturus.

** John 6:7

Respondit ei Philippus : Ducentorum denariorum panes non sufficiunt eis, ut unusquisque modicum quid accipiat.

** John 6:8

Dicit ei unus ex discipulis ejus, Andreas, frater Simonis Petri :

** John 6:9

Est puer unus hic qui habet quinque panes hordeaceos et duos pisces : sed hæc quid sunt inter tantos ?

** John 6:10

Dixit ergo Jesus : Facite homines discumbere. Erat autem fœnum multum in loco. Discubuerunt ergo viri, numero quasi quinque millia.

** John 6:11

Accepit ergo Jesus panes : et cum gratias egisset, distribuit discumbentibus : similiter et ex piscibus quantum volebant.

** John 6:12

Ut autem impleti sunt, dixit discipulis suis : Colligite quæ superaverunt fragmenta, ne pereant.

** John 6:13

Collegerunt ergo, et impleverunt duodecim cophinos fragmentorum ex quinque panibus hordeaceis, quæ superfuerunt his qui manducaverant.

** John 6:14

Illi ergo homines cum vidissent quod Jesus fecerat signum, dicebant : Quia hic est vere propheta, qui venturus est in mundum.

** John 6:15

Jesus ergo cum cognovisset quia venturi essent ut raperent eum, et facerent eum regem, fugit iterum in montem ipse solus.  

** John 6:16

Ut autem sero factum est, descenderunt discipuli ejus ad mare.

** John 6:17

Et cum ascendissent navim, venerunt trans mare in Capharnaum : et tenebræ jam factæ erant et non venerat ad eos Jesus.

** John 6:18

Mare autem, vento magno flante, exsurgebat.

** John 6:19

Cum remigassent ergo quasi stadia viginti quinque aut triginta, vident Jesum ambulantem supra mare, et proximum navi fieri, et timuerunt.

** John 6:20

Ille autem dicit eis : Ego sum, nolite timere.

** John 6:21

Voluerunt ergo accipere eum in navim et statim navis fuit ad terram, in quam ibant.

** John 6:22

Altera die, turba, quæ stabat trans mare, vidit quia navicula alia non erat ibi nisi una, et quia non introisset cum discipulis suis Jesus in navim, sed soli discipuli ejus abiissent :

** John 6:23

aliæ vero supervenerunt naves a Tiberiade juxta locum ubi manducaverant panem, gratias agente Domino.

** John 6:24

Cum ergo vidisset turba quia Jesus non esset ibi, neque discipuli ejus, ascenderunt in naviculas, et venerunt Capharnaum quærentes Jesum.  

** John 6:25

Et cum invenissent eum trans mare, dixerunt ei : Rabbi, quando huc venisti ?

** John 6:26

Respondit eis Jesus, et dixit : Amen, amen dico vobis : quæritis me non quia vidistis signa, sed quia manducastis ex panibus et saturati estis.

** John 6:27

Operamini non cibum, qui perit, sed qui permanet in vitam æternam, quem Filius hominis dabit vobis. Hunc enim Pater signavit Deus.

** John 6:28

Dixerunt ergo ad eum : Quid faciemus ut operemur opera Dei ?

** John 6:29

Respondit Jesus, et dixit eis : Hoc est opus Dei, ut credatis in eum quem misit ille.

** John 6:30

Dixerunt ergo ei : Quod ergo tu facis signum ut videamus et credamus tibi ? quid operaris ?

** John 6:31

Patres nostri manducaverunt manna in deserto, sicut scriptum est : Panem de cælo dedit eis manducare.

** John 6:32

Dixit ergo eis Jesus : Amen, amen dico vobis : non Moyses dedit vobis panem de cælo, sed Pater meus dat vobis panem de cælo verum.

** John 6:33

Panis enim Dei est, qui de cælo descendit, et dat vitam mundo.

** John 6:34

Dixerunt ergo ad eum : Domine, semper da nobis panem hunc.

** John 6:35

Dixit autem eis Jesus : Ego sum panis vitæ : qui venit ad me, non esuriet, et qui credit in me, non sitiet umquam.

** John 6:36

Sed dixi vobis quia et vidistis me, et non creditis.

** John 6:37

Omne quod dat mihi Pater, ad me veniet : et eum qui venit ad me, non ejiciam foras :

** John 6:38

quia descendi de cælo, non ut faciam voluntatem meam, sed voluntatem ejus qui misit me.

** John 6:39

Hæc est autem voluntas ejus qui misit me, Patris : ut omne quod dedit mihi, non perdam ex eo, sed resuscitem illud in novissimo die.

** John 6:40

Hæc est autem voluntas Patris mei, qui misit me : ut omnis qui videt Filium et credit in eum, habeat vitam æternam, et ego resuscitabo eum in novissimo die.

** John 6:41

Murmurabant ergo Judæi de illo, quia dixisset : Ego sum panis vivus, qui de cælo descendi,

** John 6:42

et dicebant : Nonne hic est Jesus filius Joseph, cujus nos novimus patrem et matrem ? quomodo ergo dicit hic : Quia de cælo descendi ?

** John 6:43

Respondit ergo Jesus, et dixit eis : Nolite murmurare in invicem :

** John 6:44

nemo potest venire ad me, nisi Pater, qui misit me, traxerit eum ; et ego resuscitabo eum in novissimo die.

** John 6:45

Est scriptum in prophetis : Et erunt omnes docibiles Dei. Omnis qui audivit a Patre, et didicit, venit ad me.

** John 6:46

Non quia Patrem vidit quisquam, nisi is, qui est a Deo, hic vidit Patrem.

** John 6:47

Amen, amen dico vobis : qui credit in me, habet vitam æternam.  

** John 6:48

Ego sum panis vitæ.

** John 6:49

Patres vestri manducaverunt manna in deserto, et mortui sunt.

** John 6:50

Hic est panis de cælo descendens : ut si quis ex ipso manducaverit, non moriatur.

** John 6:51

Ego sum panis vivus, qui de cælo descendi.

** John 6:52

Si quis manducaverit ex hoc pane, vivet in æternum : et panis quem ego dabo, caro mea est pro mundi vita.

** John 6:53

Litigabant ergo Judæi ad invicem, dicentes : Quomodo potest hic nobis carnem suam dare ad manducandum ?

** John 6:54

Dixit ergo eis Jesus : Amen, amen dico vobis : nisi manducaveritis carnem Filii hominis, et biberitis ejus sanguinem, non habebitis vitam in vobis.

** John 6:55

Qui manducat meam carnem, et bibit meum sanguinem, habet vitam æternam : et ego resuscitabo eum in novissimo die.

** John 6:56

Caro enim mea vere est cibus : et sanguis meus, vere est potus ;

** John 6:57

qui manducat meam carnem et bibit meum sanguinem, in me manet, et ego in illo.

** John 6:58

Sicut misit me vivens Pater, et ego vivo propter Patrem : et qui manducat me, et ipse vivet propter me.

** John 6:59

Hic est panis qui de cælo descendit. Non sicut manducaverunt patres vestri manna, et mortui sunt. Qui manducat hunc panem, vivet in æternum.  

** John 6:60

Hæc dixit in synagoga docens, in Capharnaum.

** John 6:61

Multi ergo audientes ex discipulis ejus, dixerunt : Durus est hic sermo, et quis potest eum audire ?

** John 6:62

Sciens autem Jesus apud semetipsum quia murmurarent de hoc discipuli ejus, dixit eis : Hoc vos scandalizat ?

** John 6:63

si ergo videritis Filium hominis ascendentem ubi erat prius ?

** John 6:64

Spiritus est qui vivificat : caro non prodest quidquam : verba quæ ego locutus sum vobis, spiritus et vita sunt.

** John 6:65

Sed sunt quidam ex vobis qui non credunt. Sciebat enim ab initio Jesus qui essent non credentes, et quis traditurus esset eum.

** John 6:66

Et dicebat : Propterea dixi vobis, quia nemo potest venire ad me, nisi fuerit ei datum a Patre meo.

** John 6:67

Ex hoc multi discipulorum ejus abierunt retro : et jam non cum illo ambulabant.

** John 6:68

Dixit ergo Jesus ad duodecim : Numquid et vos vultis abire ?

** John 6:69

Respondit ergo ei Simon Petrus : Domine, ad quem ibimus ? verba vitæ æternæ habes :

** John 6:70

et nos credidimus, et cognovimus quia tu es Christus Filius Dei.

** John 6:71

Respondit eis Jesus : Nonne ego vos duodecim elegi : et ex vobis unus diabolus est ?

** John 6:72

Dicebat autem Judam Simonis Iscariotem : hic enim erat traditurus eum, cum esset unus ex duodecim.   

* John 7

** John 7:1

Post hæc autem ambulabat Jesus in Galilæam : non enim volebat in Judæam ambulare, quia quærebant eum Judæi interficere.

** John 7:2

Erat autem in proximo dies festus Judæorum, Scenopegia.

** John 7:3

Dixerunt autem ad eum fratres ejus : Transi hinc, et vade in Judæam, ut et discipuli tui videant opera tua, quæ facis.

** John 7:4

Nemo quippe in occulto quid facit, et quærit ipse in palam esse : si hæc facis, manifesta teipsum mundo.

** John 7:5

Neque enim fratres ejus credebant in eum.

** John 7:6

Dicit ergo eis Jesus : Tempus meum nondum advenit : tempus autem vestrum semper est paratum.

** John 7:7

Non potest mundus odisse vos : me autem odit, quia ego testimonium perhibeo de illo quod opera ejus mala sunt.

** John 7:8

Vos ascendite ad diem festum hunc, ego autem non ascendo ad diem festum istum : quia meum tempus nondum impletum est.

** John 7:9

Hæc cum dixisset, ipse mansit in Galilæa.  

** John 7:10

Ut autem ascenderunt fratres ejus, tunc et ipse ascendit ad diem festum non manifeste, sed quasi in occulto.

** John 7:11

Judæi ergo quærebant eum in die festo, et dicebant : Ubi est ille ?

** John 7:12

Et murmur multum erat in turba de eo. Quidam enim dicebant : Quia bonus est. Alii autem dicebant : Non, sed seducit turbas.

** John 7:13

Nemo tamen palam loquebatur de illo propter metum Judæorum.  

** John 7:14

Jam autem die festo mediante, ascendit Jesus in templum, et docebat.

** John 7:15

Et mirabantur Judæi, dicentes : Quomodo hic litteras scit, cum non didicerit ?

** John 7:16

Respondit eis Jesus, et dixit : Mea doctrina non est mea, sed ejus qui misit me.

** John 7:17

Si quis voluerit voluntatem ejus facere, cognoscet de doctrina, utrum ex Deo sit, an ego a meipso loquar.

** John 7:18

Qui a semetipso loquitur, gloriam propriam quærit ; qui autem quærit gloriam ejus qui misit eum, hic verax est, et injustitia in illo non est.

** John 7:19

Nonne Moyses dedit vobis legem : et nemo ex vobis facit legem ?

** John 7:20

Quid me quæritis interficere ? Respondit turba, et dixit : Dæmonium habes : quis te quærit interficere ?

** John 7:21

Respondit Jesus et dixit eis : Unum opus feci, et omnes miramini :

** John 7:22

propterea Moyses dedit vobis circumcisionem (non quia ex Moyse est, sed ex patribus), et in sabbato circumciditis hominem.

** John 7:23

Si circumcisionem accipit homo in sabbato, ut non solvatur lex Moysi : mihi indignamini quia totum hominem sanum feci in sabbato ?

** John 7:24

Nolite judicare secundum faciem, sed justum judicium judicate.  

** John 7:25

Dicebant ergo quidam ex Jerosolymis : Nonne hic est, quem quærunt interficere ?

** John 7:26

et ecce palam loquitur, et nihil ei dicunt. Numquid vere cognoverunt principes quia hic est Christus ?

** John 7:27

Sed hunc scimus unde sit : Christus autem cum venerit, nemo scit unde sit.

** John 7:28

Clamabat ergo Jesus in templo docens, et dicens : Et me scitis, et unde sim scitis : et a meipso non veni, sed est verus qui misit me, quem vos nescitis.

** John 7:29

Ego scio eum : quia ab ipso sum, et ipse me misit.

** John 7:30

Quærebant ergo eum apprehendere : et nemo misit in illum manus, quia nondum venerat hora ejus.

** John 7:31

De turba autem multi crediderunt in eum, et dicebant : Christus cum venerit, numquid plura signa faciet quam quæ hic facit ?

** John 7:32

Audierunt pharisæi turbam murmurantem de illo hæc : et miserunt principes et pharisæi ministros ut apprehenderent eum.

** John 7:33

Dixit ergo eis Jesus : Adhuc modicum tempus vobiscum sum : et vado ad eum qui me misit.

** John 7:34

Quæretis me, et non invenietis : et ubi ego sum, vos non potestis venire.

** John 7:35

Dixerunt ergo Judæi ad semetipsos : Quo hic iturus est, quia non inveniemus eum ? numquid in dispersionem gentium iturus est, et docturus gentes ?

** John 7:36

quis est hic sermo, quem dixit : Quæretis me, et non invenietis : et ubi sum ego, vos non potestis venire ?  

** John 7:37

In novissimo autem die magno festivitatis stabat Jesus, et clamabat dicens : Si quis sitit, veniat ad me et bibat.

** John 7:38

Qui credit in me, sicut dicit Scriptura, flumina de ventre ejus fluent aquæ vivæ.

** John 7:39

Hoc autem dixit de Spiritu, quem accepturi erant credentes in eum : nondum enim erat Spiritus datus, quia Jesus nondum erat glorificatus.  

** John 7:40

Ex illa ergo turba cum audissent hos sermones ejus, dicebant : Hic est vere propheta.

** John 7:41

Alii dicebant : Hic est Christus. Quidam autem dicebant : Numquid a Galilæa venit Christus ?

** John 7:42

nonne Scriptura dicit : Quia ex semine David, et de Bethlehem castello, ubi erat David, venit Christus ?

** John 7:43

Dissensio itaque facta est in turba propter eum.

** John 7:44

Quidam autem ex ipsis volebant apprehendere eum : sed nemo misit super eum manus.

** John 7:45

Venerunt ergo ministri ad pontifices et pharisæos. Et dixerunt eis illi : Quare non adduxistis illum ?

** John 7:46

Responderunt ministri : Numquam sic locutus est homo, sicut hic homo.

** John 7:47

Responderunt ergo eis pharisæi : Numquid et vos seducti estis ?

** John 7:48

numquid ex principibus aliquis credidit in eum, aut ex pharisæis ?

** John 7:49

sed turba hæc, quæ non novit legem, maledicti sunt.

** John 7:50

Dixit Nicodemus ad eos, ille qui venit ad eum nocte, qui unus erat ex ipsis :

** John 7:51

Numquid lex nostra judicat hominem, nisi prius audierit ab ipso, et cognoverit quid faciat ?

** John 7:52

Responderunt, et dixerunt ei : Numquid et tu Galilæus es ? scrutare Scripturas, et vide quia a Galilæa propheta non surgit.

** John 7:53

Et reversi sunt unusquisque in domum suam.   

* John 8

** John 8:1

Jesus autem perrexit in montem Oliveti :

** John 8:2

et diluculo iterum venit in templum, et omnis populus venit ad eum, et sedens docebat eos.

** John 8:3

Adducunt autem scribæ et pharisæi mulierem in adulterio deprehensam : et statuerunt eam in medio,

** John 8:4

et dixerunt ei : Magister, hæc mulier modo deprehensa est in adulterio.

** John 8:5

In lege autem Moyses mandavit nobis hujusmodi lapidare. Tu ergo quid dicis ?

** John 8:6

Hoc autem dicebant tentantes eum, ut possent accusare eum. Jesus autem inclinans se deorsum, digito scribebat in terra.

** John 8:7

Cum ergo perseverarent interrogantes eum, erexit se, et dixit eis : Qui sine peccato est vestrum, primus in illam lapidem mittat.

** John 8:8

Et iterum se inclinans, scribebat in terra.

** John 8:9

Audientes autem unus post unum exibant, incipientes a senioribus : et remansit solus Jesus, et mulier in medio stans.

** John 8:10

Erigens autem se Jesus, dixit ei : Mulier, ubi sunt qui te accusabant ? nemo te condemnavit ?

** John 8:11

Quæ dixit : Nemo, Domine. Dixit autem Jesus : Nec ego te condemnabo : vade, et jam amplius noli peccare.  

** John 8:12

Iterum ergo locutus est eis Jesus, dicens : Ego sum lux mundi : qui sequitur me, non ambulat in tenebris, sed habebit lumen vitæ.

** John 8:13

Dixerunt ergo ei pharisæi : Tu de teipso testimonium perhibes ; testimonium tuum non est verum.

** John 8:14

Respondit Jesus, et dixit eis : Et si ego testimonium perhibeo de meipso, verum est testimonium meum : quia scio unde veni et quo vado ; vos autem nescitis unde venio aut quo vado.

** John 8:15

Vos secundum carnem judicatis : ego non judico quemquam ;

** John 8:16

et si judico ego, judicium meum verum est, quia solus non sum : sed ego et qui misit me, Pater.

** John 8:17

Et in lege vestra scriptum est, quia duorum hominum testimonium verum est.

** John 8:18

Ego sum qui testimonium perhibeo de meipso, et testimonium perhibet de me qui misit me, Pater.

** John 8:19

Dicebant ergo ei : Ubi est Pater tuus ? Respondit Jesus : Neque me scitis, neque Patrem meum : si me sciretis, forsitan et Patrem meum sciretis.

** John 8:20

Hæc verba locutus est Jesus in gazophylacio, docens in templo : et nemo apprehendit eum, quia necdum venerat hora ejus.  

** John 8:21

Dixit ergo iterum eis Jesus : Ego vado, et quæretis me, et in peccato vestro moriemini. Quo ego vado, vos non potestis venire.

** John 8:22

Dicebant ergo Judæi : Numquid interficiet semetipsum, quia dixit : Quo ego vado, vos non potestis venire ?

** John 8:23

Et dicebat eis : Vos de deorsum estis, ego de supernis sum. Vos de mundo hoc estis, ego non sum de hoc mundo.

** John 8:24

Dixi ergo vobis quia moriemini in peccatis vestris : si enim non credideritis quia ego sum, moriemini in peccato vestro.

** John 8:25

Dicebant ergo ei : Tu quis es ? Dixit eis Jesus : Principium, qui et loquor vobis.

** John 8:26

Multa habeo de vobis loqui, et judicare ; sed qui me misit, verax est ; et ego quæ audivi ab eo, hæc loquor in mundo.

** John 8:27

Et non cognoverunt quia Patrem ejus dicebat Deum.

** John 8:28

Dixit ergo eis Jesus : Cum exaltaveritis Filium hominis, tunc cognoscetis quia ego sum, et a meipso facio nihil, sed sicut docuit me Pater, hæc loquor :

** John 8:29

et qui me misit, mecum est, et non reliquit me solum : quia ego quæ placita sunt ei, facio semper.

** John 8:30

Hæc illo loquente, multi crediderunt in eum.

** John 8:31

Dicebat ergo Jesus ad eos, qui crediderunt ei, Judæos : Si vos manseritis in sermone meo, vere discipuli mei eritis,

** John 8:32

et cognoscetis veritatem, et veritas liberabit vos.

** John 8:33

Responderunt ei : Semen Abrahæ sumus, et nemini servivimus umquam : quomodo tu dicis : Liberi eritis ?

** John 8:34

Respondit eis Jesus : Amen, amen dico vobis : quia omnis qui facit peccatum, servus est peccati.

** John 8:35

Servus autem non manet in domo in æternum : filius autem manet in æternum.

** John 8:36

Si ergo vos filius liberaverit, vere liberi eritis.

** John 8:37

Scio quia filii Abrahæ estis : sed quæritis me interficere, quia sermo meus non capit in vobis.

** John 8:38

Ego quod vidi apud Patrem meum, loquor : et vos quæ vidistis apud patrem vestrum, facitis.

** John 8:39

Responderunt, et dixerunt ei : Pater noster Abraham est. Dicit eis Jesus : Si filii Abrahæ estis, opera Abrahæ facite.

** John 8:40

Nunc autem quæritis me interficere, hominem, qui veritatem vobis locutus sum, quam audivi a Deo : hoc Abraham non fecit.

** John 8:41

Vos facitis opera patris vestri. Dixerunt itaque ei : Nos ex fornicatione non sumus nati : unum patrem habemus Deum.

** John 8:42

Dixit ergo eis Jesus : Si Deus pater vester esset, diligeretis utique et me ; ego enim ex Deo processi, et veni : neque enim a meipso veni, sed ille me misit.

** John 8:43

Quare loquelam meam non cognoscitis ? Quia non potestis audire sermonem meum.

** John 8:44

Vos ex patre diabolo estis : et desideria patris vestri vultis facere. Ille homicida erat ab initio, et in veritate non stetit : quia non est veritas in eo : cum loquitur mendacium, ex propriis loquitur, quia mendax est, et pater ejus.

** John 8:45

Ego autem si veritatem dico, non creditis mihi.

** John 8:46

Quis ex vobis arguet me de peccato ? si veritatem dico vobis, quare non creditis mihi ?

** John 8:47

Qui ex Deo est, verba Dei audit. Propterea vos non auditis, quia ex Deo non estis.  

** John 8:48

Responderunt ergo Judæi, et dixerunt ei : Nonne bene dicimus nos quia Samaritanus es tu, et dæmonium habes ?

** John 8:49

Respondit Jesus : Ego dæmonium non habeo : sed honorifico Patrem meum, et vos inhonorastis me.

** John 8:50

Ego autem non quæro gloriam meam : est qui quærat, et judicet.

** John 8:51

Amen, amen dico vobis : si quis sermonem meum servaverit, mortem non videbit in æternum.

** John 8:52

Dixerunt ergo Judæi : Nunc cognovimus quia dæmonium habes. Abraham mortuus est, et prophetæ ; et tu dicis : Si quis sermonem meum servaverit, non gustabit mortem in æternum.

** John 8:53

Numquid tu major es patre nostro Abraham, qui mortuus est ? et prophetæ mortui sunt. Quem teipsum facis ?

** John 8:54

Respondit Jesus : Si ego glorifico meipsum, gloria mea nihil est : est Pater meus, qui glorificat me, quem vos dicitis quia Deus vester est,

** John 8:55

et non cognovistis eum : ego autem novi eum. Et si dixero quia non scio eum, ero similis vobis, mendax. Sed scio eum, et sermonem ejus servo.

** John 8:56

Abraham pater vester exsultavit ut videret diem meum : vidit, et gavisus est.

** John 8:57

Dixerunt ergo Judæi ad eum : Quinquaginta annos nondum habes, et Abraham vidisti ?

** John 8:58

Dixit eis Jesus : Amen, amen dico vobis, antequam Abraham fieret, ego sum.

** John 8:59

Tulerunt ergo lapides, ut jacerent in eum : Jesus autem abscondit se, et exivit de templo.   

* John 9

** John 9:1

Et præteriens Jesus vidit hominem cæcum a nativitate :

** John 9:2

et interrogaverunt eum discipuli ejus : Rabbi, quis peccavit, hic, aut parentes ejus, ut cæcus nasceretur ?

** John 9:3

Respondit Jesus : Neque hic peccavit, neque parentes ejus : sed ut manifestentur opera Dei in illo.

** John 9:4

Me oportet operari opera ejus qui misit me, donec dies est : venit nox, quando nemo potest operari :

** John 9:5

quamdiu sum in mundo, lux sum mundi.

** John 9:6

Hæc cum dixisset, exspuit in terram, et fecit lutum ex sputo, et linivit lutum super oculos ejus,

** John 9:7

et dixit ei : Vade, lava in natatoria Siloë (quod interpretatur Missus). Abiit ergo, et lavit, et venit videns.

** John 9:8

Itaque vicini, et qui viderant eum prius quia mendicus erat, dicebant : Nonne hic est qui sedebat, et mendicabat ? Alii dicebant : Quia hic est.

** John 9:9

Alii autem : Nequaquam, sed similis est ei. Ille vero dicebat : Quia ego sum.

** John 9:10

Dicebant ergo ei : Quomodo aperti sunt tibi oculi ?

** John 9:11

Respondit : Ille homo qui dicitur Jesus, lutum fecit : et unxit oculos meos, et dixit mihi : Vade ad natatoria Siloë, et lava. Et abii, et lavi, et video.

** John 9:12

Et dixerunt ei : Ubi est ille ? Ait : Nescio.  

** John 9:13

Adducunt eum ad pharisæos, qui cæcus fuerat.

** John 9:14

Erat autem sabbatum quando lutum fecit Jesus, et aperuit oculos ejus.

** John 9:15

Iterum ergo interrogabant eum pharisæi quomodo vidisset. Ille autem dixit eis : Lutum mihi posuit super oculos, et lavi, et video.

** John 9:16

Dicebant ergo ex pharisæis quidam : Non est hic homo a Deo, qui sabbatum non custodit. Alii autem dicebant : Quomodo potest homo peccator hæc signa facere ? Et schisma erat inter eos.

** John 9:17

Dicunt ergo cæco iterum : Tu quid dicis de illo qui aperuit oculos tuos ? Ille autem dixit : Quia propheta est.

** John 9:18

Non crediderunt ergo Judæi de illo, quia cæcus fuisset et vidisset, donec vocaverunt parentes ejus, qui viderat :

** John 9:19

et interrogaverunt eos, dicentes : Hic est filius vester, quem vos dicitis quia cæcus natus est ? quomodo ergo nunc videt ?

** John 9:20

Responderunt eis parentes ejus, et dixerunt : Scimus quia hic est filius noster, et quia cæcus natus est :

** John 9:21

quomodo autem nunc videat, nescimus : aut quis ejus aperuit oculos, nos nescimus ; ipsum interrogate : ætatem habet, ipse de se loquatur.

** John 9:22

Hæc dixerunt parentes ejus, quoniam timebant Judæos : jam enim conspiraverunt Judæi, ut si quis eum confiteretur esse Christum, extra synagogam fieret.

** John 9:23

Propterea parentes ejus dixerunt : Quia ætatem habet, ipsum interrogate.

** John 9:24

Vocaverunt ergo rursum hominem qui fuerat cæcus, et dixerunt ei : Da gloriam Deo : nos scimus quia hic homo peccator est.

** John 9:25

Dixit ergo eis ille : Si peccator est, nescio ; unum scio, quia cæcus cum essem, modo video.

** John 9:26

Dixerunt ergo illi : Quid fecit tibi ? quomodo aperuit tibi oculos ?

** John 9:27

Respondit eis : Dixi vobis jam, et audistis : quod iterum vultis audire ? numquid et vos vultis discipuli ejus fieri ?

** John 9:28

Maledixerunt ergo ei, et dixerunt : Tu discipulus illius sis : nos autem Moysi discipuli sumus.

** John 9:29

Nos scimus quia Moysi locutus est Deus ; hunc autem nescimus unde sit.

** John 9:30

Respondit ille homo, et dixit eis : In hoc enim mirabile est quia vos nescitis unde sit, et aperuit meos oculos :

** John 9:31

scimus autem quia peccatores Deus non audit : sed si quis Dei cultor est, et voluntatem ejus facit, hunc exaudit.

** John 9:32

A sæculo non est auditum quia quis aperuit oculos cæci nati.

** John 9:33

Nisi esset hic a Deo, non poterat facere quidquam.

** John 9:34

Responderunt, et dixerunt ei : In peccatis natus es totus, et tu doces nos ? Et ejecerunt eum foras.  

** John 9:35

Audivit Jesus quia ejecerunt eum foras : et cum invenisset eum, dixit ei : Tu credis in Filium Dei ?

** John 9:36

Respondit ille, et dixit : Quis est, Domine, ut credam in eum ?

** John 9:37

Et dixit ei Jesus : Et vidisti eum, et qui loquitur tecum, ipse est.

** John 9:38

At ille ait : Credo, Domine. Et procidens adoravit eum.

** John 9:39

Et dixit Jesus : In judicium ego in hunc mundum veni : ut qui non vident videant, et qui vident cæci fiant.

** John 9:40

Et audierunt quidam ex pharisæis qui cum ipso erant, et dixerunt ei : Numquid et nos cæci sumus ?

** John 9:41

Dixit eis Jesus : Si cæci essetis, non haberetis peccatum. Nunc vero dicitis, Quia videmus : peccatum vestrum manet.   

* John 10

** John 10:1

Amen, amen dico vobis : qui non intrat per ostium in ovile ovium, sed ascendit aliunde, ille fur est et latro.

** John 10:2

Qui autem intrat per ostium, pastor est ovium.

** John 10:3

Huic ostiarius aperit, et oves vocem ejus audiunt, et proprias oves vocat nominatim, et educit eas.

** John 10:4

Et cum proprias oves emiserit, ante eas vadit : et oves illum sequuntur, quia sciunt vocem ejus.

** John 10:5

Alienum autem non sequuntur, sed fugiunt ab eo : quia non noverunt vocem alienorum.

** John 10:6

Hoc proverbium dixit eis Jesus : illi autem non cognoverunt quid loqueretur eis.

** John 10:7

Dixit ergo eis iterum Jesus : Amen, amen dico vobis, quia ego sum ostium ovium.

** John 10:8

Omnes quotquot venerunt, fures sunt, et latrones, et non audierunt eos oves.

** John 10:9

Ego sum ostium. Per me si quis introierit, salvabitur : et ingredietur, et egredietur, et pascua inveniet.

** John 10:10

Fur non venit nisi ut furetur, et mactet, et perdat. Ego veni ut vitam habeant, et abundantius habeant.

** John 10:11

Ego sum pastor bonus. Bonus pastor animam suam dat pro ovibus suis.

** John 10:12

Mercenarius autem, et qui non est pastor, cujus non sunt oves propriæ, videt lupum venientem, et dimittit oves, et fugit : et lupus rapit, et dispergit oves ;

** John 10:13

mercenarius autem fugit, quia mercenarius est, et non pertinet ad eum de ovibus.

** John 10:14

Ego sum pastor bonus : et cognosco meas, et cognoscunt me meæ.

** John 10:15

Sicut novit me Pater, et ego agnosco Patrem : et animam meam pono pro ovibus meis.

** John 10:16

Et alias oves habeo, quæ non sunt ex hoc ovili : et illas oportet me adducere, et vocem meam audient, et fiet unum ovile et unus pastor.

** John 10:17

Propterea me diligit Pater : quia ego pono animam meam, ut iterum sumam eam.

** John 10:18

Nemo tollit eam a me : sed ego pono eam a meipso, et potestatem habeo ponendi eam, et potestatem habeo iterum sumendi eam. Hoc mandatum accepi a Patre meo.  

** John 10:19

Dissensio iterum facta est inter Judæos propter sermones hos.

** John 10:20

Dicebant autem multi ex ipsis : Dæmonium habet, et insanit : quid eum auditis ?

** John 10:21

Alii dicebant : Hæc verba non sunt dæmonium habentis : numquid dæmonium potest cæcorum oculos aperire ?  

** John 10:22

Facta sunt autem Encænia in Jerosolymis, et hiems erat.

** John 10:23

Et ambulabat Jesus in templo, in porticu Salomonis.

** John 10:24

Circumdederunt ergo eum Judæi, et dicebant ei : Quousque animam nostram tollis ? si tu es Christus, dic nobis palam.

** John 10:25

Respondit eis Jesus : Loquor vobis, et non creditis : opera quæ ego facio in nomine Patris mei, hæc testimonium perhibent de me :

** John 10:26

sed vos non creditis, quia non estis ex ovibus meis.

** John 10:27

Oves meæ vocem meam audiunt, et ego cognosco eas, et sequuntur me :

** John 10:28

et ego vitam æternam do eis, et non peribunt in æternum, et non rapiet eas quisquam de manu mea.

** John 10:29

Pater meus quod dedit mihi, majus omnibus est : et nemo potest rapere de manu Patris mei.

** John 10:30

Ego et Pater unum sumus.  

** John 10:31

Sustulerunt ergo lapides Judæi, ut lapidarent eum.

** John 10:32

Respondit eis Jesus : Multa bona opera ostendi vobis ex Patre meo : propter quod eorum opus me lapidatis ?

** John 10:33

Responderunt ei Judæi : De bono opere non lapidamus te, sed de blasphemia ; et quia tu homo cum sis, facis teipsum Deum.

** John 10:34

Respondit eis Jesus : Nonne scriptum est in lege vestra, Quia ego dixi : Dii estis ?

** John 10:35

Si illos dixit deos, ad quos sermo Dei factus est, et non potest solvi Scriptura :

** John 10:36

quem Pater sanctificavit, et misit in mundum vos dicitis : Quia blasphemas, quia dixi : Filius Dei sum ?

** John 10:37

Si non facio opera Patris mei, nolite credere mihi.

** John 10:38

Si autem facio : etsi mihi non vultis credere, operibus credite, ut cognoscatis, et credatis quia Pater in me est, et ego in Patre.

** John 10:39

Quærebant ergo eum apprehendere : et exivit de manibus eorum.

** John 10:40

Et abiit iterum trans Jordanem, in eum locum ubi erat Joannes baptizans primum, et mansit illic ;

** John 10:41

et multi venerunt ad eum, et dicebant : Quia Joannes quidem signum fecit nullum.

** John 10:42

Omnia autem quæcumque dixit Joannes de hoc, vera erant. Et multi crediderunt in eum.   

* John 11

** John 11:1

Erat autem quidam languens Lazarus a Bethania, de castello Mariæ et Marthæ sororis ejus.

** John 11:2

(Maria autem erat quæ unxit Dominum unguento, et extersit pedes ejus capillis suis : cujus frater Lazarus infirmabatur.)

** John 11:3

Miserunt ergo sorores ejus ad eum dicentes : Domine, ecce quem amas infirmatur.

** John 11:4

Audiens autem Jesus dixit eis : Infirmitas hæc non est ad mortem, sed pro gloria Dei, ut glorificetur Filius Dei per eam.

** John 11:5

Diligebat autem Jesus Martham, et sororem ejus Mariam, et Lazarum.

** John 11:6

Ut ergo audivit quia infirmabatur, tunc quidem mansit in eodem loco duobus diebus ;

** John 11:7

deinde post hæc dixit discipulis suis : Eamus in Judæam iterum.

** John 11:8

Dicunt ei discipuli : Rabbi, nunc quærebant te Judæi lapidare, et iterum vadis illuc ?

** John 11:9

Respondit Jesus : Nonne duodecim sunt horæ diei ? Si quis ambulaverit in die, non offendit, quia lucem hujus mundi videt :

** John 11:10

si autem ambulaverit in nocte, offendit, quia lux non est in eo.

** John 11:11

Hæc ait, et post hæc dixit eis : Lazarus amicus noster dormit : sed vado ut a somno excitem eum.

** John 11:12

Dixerunt ergo discipuli ejus : Domine, si dormit, salvus erit.

** John 11:13

Dixerat autem Jesus de morte ejus : illi autem putaverunt quia de dormitione somni diceret.

** John 11:14

Tunc ergo Jesus dixit eis manifeste : Lazarus mortuus est :

** John 11:15

et gaudeo propter vos, ut credatis, quoniam non eram ibi, sed eamus ad eum.

** John 11:16

Dixit ergo Thomas, qui dicitur Didymus, ad condiscipulos : Eamus et nos, ut moriamur cum eo.

** John 11:17

Venit itaque Jesus : et invenit eum quatuor dies jam in monumento habentem.

** John 11:18

(Erat autem Bethania juxta Jerosolymam quasi stadiis quindecim.)

** John 11:19

Multi autem ex Judæis venerant ad Martham et Mariam, ut consolarentur eas de fratre suo.

** John 11:20

Martha ergo ut audivit quia Jesus venit, occurrit illi : Maria autem domi sedebat.

** John 11:21

Dixit ergo Martha ad Jesum : Domine, si fuisses hic, frater meus non fuisset mortuus :

** John 11:22

sed et nunc scio quia quæcumque poposceris a Deo, dabit tibi Deus.

** John 11:23

Dicit illi Jesus : Resurget frater tuus.

** John 11:24

Dicit ei Martha : Scio quia resurget in resurrectione in novissimo die.

** John 11:25

Dixit ei Jesus : Ego sum resurrectio et vita : qui credit in me, etiam si mortuus fuerit, vivet :

** John 11:26

et omnis qui vivit et credit in me, non morietur in æternum. Credis hoc ?

** John 11:27

Ait illi : Utique Domine, ego credidi quia tu es Christus, Filius Dei vivi, qui in hunc mundum venisti.

** John 11:28

Et cum hæc dixisset, abiit, et vocavit Mariam sororem suam silentio, dicens : Magister adest, et vocat te.

** John 11:29

Illa ut audivit, surgit cito, et venit ad eum ;

** John 11:30

nondum enim venerat Jesus in castellum : sed erat adhuc in illo loco, ubi occurrerat ei Martha.

** John 11:31

Judæi ergo, qui erant cum ea in domo, et consolabantur eam, cum vidissent Mariam quia cito surrexit, et exiit, secuti sunt eam dicentes : Quia vadit ad monumentum, ut ploret ibi.

** John 11:32

Maria ergo, cum venisset ubi erat Jesus, videns eum, cecidit ad pedes ejus, et dicit ei : Domine, si fuisses hic, non esset mortuus frater meus.

** John 11:33

Jesus ergo, ut vidit eam plorantem, et Judæos, qui venerant cum ea, plorantes, infremuit spiritu, et turbavit seipsum,

** John 11:34

et dixit : Ubi posuistis eum ? Dicunt ei : Domine, veni, et vide.

** John 11:35

Et lacrimatus est Jesus.

** John 11:36

Dixerunt ergo Judæi : Ecce quomodo amabat eum.

** John 11:37

Quidam autem ex ipsis dixerunt : Non poterat hic, qui aperuit oculos cæci nati, facere ut hic non moreretur ?

** John 11:38

Jesus ergo rursum fremens in semetipso, venit ad monumentum. Erat autem spelunca, et lapis superpositus erat ei.

** John 11:39

Ait Jesus : Tollite lapidem. Dicit ei Martha, soror ejus qui mortuus fuerat : Domine, jam fœtet, quatriduanus est enim.

** John 11:40

Dicit ei Jesus : Nonne dixi tibi quoniam si credideris, videbis gloriam Dei ?

** John 11:41

Tulerunt ergo lapidem : Jesus autem, elevatis sursum oculis, dixit : Pater, gratias ago tibi quoniam audisti me.

** John 11:42

Ego autem sciebam quia semper me audis, sed propter populum qui circumstat, dixi : ut credant quia tu me misisti.

** John 11:43

Hæc cum dixisset, voce magna clamavit : Lazare, veni foras.

** John 11:44

Et statim prodiit qui fuerat mortuus, ligatus pedes, et manus institis, et facies illius sudario erat ligata. Dixit eis Jesus : Solvite eum et sinite abire.

** John 11:45

Multi ergo ex Judæis, qui venerant ad Mariam, et Martham, et viderant quæ fecit Jesus, crediderunt in eum.

** John 11:46

Quidam autem ex ipsis abierunt ad pharisæos, et dixerunt eis quæ fecit Jesus.  

** John 11:47

Collegerunt ergo pontifices et pharisæi concilium, et dicebant : Quid facimus, quia hic homo multa signa facit ?

** John 11:48

Si dimittimus eum sic, omnes credent in eum, et venient Romani, et tollent nostrum locum, et gentem.

** John 11:49

Unus autem ex ipsis, Caiphas nomine, cum esset pontifex anni illius, dixit eis : Vos nescitis quidquam,

** John 11:50

nec cogitatis quia expedit vobis ut unus moriatur homo pro populo, et non tota gens pereat.

** John 11:51

Hoc autem a semetipso non dixit : sed cum esset pontifex anni illius, prophetavit, quod Jesus moriturus erat pro gente,

** John 11:52

et non tantum pro gente, sed ut filios Dei, qui erant dispersi, congregaret in unum.

** John 11:53

Ab illo ergo die cogitaverunt ut interficerent eum.  

** John 11:54

Jesus ergo jam non in palam ambulabat apud Judæos, sed abiit in regionem juxta desertum, in civitatem quæ dicitur Ephrem, et ibi morabatur cum discipulis suis.

** John 11:55

Proximum autem erat Pascha Judæorum, et ascenderunt multi Jerosolymam de regione ante Pascha, ut sanctificarent seipsos.

** John 11:56

Quærebant ergo Jesum, et colloquebantur ad invicem, in templo stantes : Quid putatis, quia non venit ad diem festum ? Dederant autem pontifices et pharisæi mandatum ut si quis cognoverit ubi sit, indicet, ut apprehendant eum.   

** John 11:57

nil

* John 12

** John 12:1

Jesus ergo ante sex dies Paschæ venit Bethaniam, ubi Lazarus fuerat mortuus, quem suscitavit Jesus.

** John 12:2

Fecerunt autem ei cœnam ibi, et Martha ministrabat, Lazarus vero unus erat ex discumbentibus cum eo.

** John 12:3

Maria ergo accepit libram unguenti nardi pistici pretiosi, et unxit pedes Jesu, et extersit pedes ejus capillis suis : et domus impleta est ex odore unguenti.

** John 12:4

Dixit ergo unus ex discipulis ejus, Judas Iscariotes, qui erat eum traditurus :

** John 12:5

Quare hoc unguentum non veniit trecentis denariis, et datum est egenis ?

** John 12:6

Dixit autem hoc, non quia de egenis pertinebat ad eum, sed quia fur erat, et loculos habens, ea quæ mittebantur, portabat.

** John 12:7

Dixit ergo Jesus : Sinite illam ut in diem sepulturæ meæ servet illud.

** John 12:8

Pauperes enim semper habetis vobiscum : me autem non semper habetis.

** John 12:9

Cognovit ergo turba multa ex Judæis quia illic est, et venerunt, non propter Jesum tantum, sed ut Lazarum viderent, quem suscitavit a mortuis.  

** John 12:10

Cogitaverunt autem principes sacerdotum ut et Lazarum interficerent :

** John 12:11

quia multi propter illum abibant ex Judæis, et credebant in Jesum.

** John 12:12

In crastinum autem, turba multa quæ venerat ad diem festum, cum audissent quia venit Jesus Jerosolymam,

** John 12:13

acceperunt ramos palmarum, et processerunt obviam ei, et clamabant : Hosanna, benedictus qui venit in nomine Domini, rex Israël.

** John 12:14

Et invenit Jesus asellum, et sedit super eum, sicut scriptum est :

** John 12:15

Noli timere, filia Sion : ecce rex tuus venit sedens super pullum asinæ.

** John 12:16

Hæc non cognoverunt discipuli ejus primum : sed quando glorificatus est Jesus, tunc recordati sunt quia hæc erant scripta de eo, et hæc fecerunt ei.

** John 12:17

Testimonium ergo perhibebat turba, quæ erat cum eo quando Lazarum vocavit de monumento, et suscitavit eum a mortuis.

** John 12:18

Propterea et obviam venit ei turba : quia audierunt fecisse hoc signum.

** John 12:19

Pharisæi ergo dixerunt ad semetipsos : Videtis quia nihil proficimus ? ecce mundus totus post eum abiit.  

** John 12:20

Erant autem quidam gentiles, ex his qui ascenderant ut adorarent in die festo.

** John 12:21

Hi ergo accesserunt ad Philippum, qui erat a Bethsaida Galilææ, et rogabant eum, dicentes : Domine, volumus Jesum videre.

** John 12:22

Venit Philippus, et dicit Andreæ ; Andreas rursum et Philippus dixerunt Jesu.

** John 12:23

Jesus autem respondit eis, dicens : Venit hora, ut clarificetur Filius hominis.

** John 12:24

Amen, amen dico vobis, nisi granum frumenti cadens in terram, mortuum fuerit,

** John 12:25

ipsum solum manet : si autem mortuum fuerit, multum fructum affert. Qui amat animam suam, perdet eam ; et qui odit animam suam in hoc mundo, in vitam æternam custodit eam.

** John 12:26

Si quis mihi ministrat, me sequatur, et ubi sum ego, illic et minister meus erit. Si quis mihi ministraverit, honorificabit eum Pater meus.

** John 12:27

Nunc anima mea turbata est. Et quid dicam ? Pater, salvifica me ex hac hora. Sed propterea veni in horam hanc :

** John 12:28

Pater, clarifica nomen tuum. Venit ergo vox de cælo : Et clarificavi, et iterum clarificabo.

** John 12:29

Turba ergo, quæ stabat, et audierat, dicebat tonitruum esse factum. Alii dicebant : Angelus ei locutus est.

** John 12:30

Respondit Jesus, et dixit : Non propter me hæc vox venit, sed propter vos.

** John 12:31

Nunc judicium est mundi : nunc princeps hujus mundi ejicietur foras.

** John 12:32

Et ego, si exaltatus fuero a terra, omnia traham ad meipsum.

** John 12:33

(Hoc autem dicebat, significans qua morte esset moriturus.)  

** John 12:34

Respondit ei turba : Nos audivimus ex lege, quia Christus manet in æternum : et quomodo tu dicis : Oportet exaltari Filium hominis ? quis est iste Filius hominis ?

** John 12:35

Dixit ergo eis Jesus : Adhuc modicum, lumen in vobis est. Ambulate dum lucem habetis, ut non vos tenebræ comprehendant ; et qui ambulat in tenebris, nescit quo vadat.

** John 12:36

Dum lucem habetis, credite in lucem, ut filii lucis sitis. Hæc locutus est Jesus, et abiit et abscondit se ab eis.  

** John 12:37

Cum autem tanta signa fecisset coram eis, non credebant in eum ;

** John 12:38

ut sermo Isaiæ prophetæ impleretur, quem dixit :   Domine, quis credidit auditui nostro ?  et brachium Domini cui revelatum est ?

** John 12:39

Propterea non poterant credere, quia iterum dixit Isaias : 

** John 12:40

Excæcavit oculos eorum, et induravit cor eorum  ut non videant oculis, et non intelligant corde,  et convertantur, et sanem eos.

** John 12:41

Hæc dixit Isaias, quando vidit gloriam ejus, et locutus est de eo.  

** John 12:42

Verumtamen et ex principibus multi crediderunt in eum : sed propter pharisæos non confitebantur, ut e synagoga non ejicerentur.

** John 12:43

Dilexerunt enim gloriam hominum magis quam gloriam Dei.

** John 12:44

Jesus autem clamavit, et dixit : Qui credit in me, non credit in me, sed in eum qui misit me.

** John 12:45

Et qui videt me, videt eum qui misit me.

** John 12:46

Ego lux in mundum veni, ut omnis qui credit in me, in tenebris non maneat.

** John 12:47

Et si quis audierit verba mea, et non custodierit, ego non judico eum ; non enim veni ut judicem mundum, sed ut salvificem mundum.

** John 12:48

Qui spernit me et non accipit verba mea, habet qui judicet eum. Sermo quem locutus sum, ille judicabit eum in novissimo die.

** John 12:49

Quia ego ex meipso non sum locutus, sed qui misit me, Pater, ipse mihi mandatum dedit quid dicam et quid loquar.

** John 12:50

Et scio quia mandatum ejus vita æterna est : quæ ergo ego loquor, sicut dixit mihi Pater, sic loquor.   

* John 13

** John 13:1

Ante diem festum Paschæ, sciens Jesus quia venit hora ejus ut transeat ex hoc mundo ad Patrem : cum dilexisset suos, qui erant in mundo, in finem dilexit eos.

** John 13:2

Et cœna facta, cum diabolus jam misisset in cor ut traderet eum Judas Simonis Iscariotæ :

** John 13:3

sciens quia omnia dedit ei Pater in manus, et quia a Deo exivit, et ad Deum vadit :

** John 13:4

surgit a cœna, et ponit vestimenta sua, et cum accepisset linteum, præcinxit se.

** John 13:5

Deinde mittit aquam in pelvim, et cœpit lavare pedes discipulorum, et extergere linteo, quo erat præcinctus.

** John 13:6

Venit ergo ad Simonem Petrum. Et dicit ei Petrus : Domine, tu mihi lavas pedes ?

** John 13:7

Respondit Jesus, et dixit ei : Quod ego facio, tu nescis modo : scies autem postea.

** John 13:8

Dicit ei Petrus : Non lavabis mihi pedes in æternum. Respondit ei Jesus : Si non lavero te, non habebis partem mecum.

** John 13:9

Dicit ei Simon Petrus : Domine, non tantum pedes meos, sed et manus, et caput.

** John 13:10

Dicit ei Jesus : Qui lotus est, non indiget nisi ut pedes lavet, sed est mundus totus. Et vos mundi estis, sed non omnes.

** John 13:11

Sciebat enim quisnam esset qui traderet eum ; propterea dixit : Non estis mundi omnes.

** John 13:12

Postquam ergo lavit pedes eorum, et accepit vestimenta sua, cum recubuisset iterum, dixit eis : Scitis quid fecerim vobis ?

** John 13:13

Vos vocatis me Magister et Domine, et bene dicitis : sum etenim.

** John 13:14

Si ergo ego lavi pedes vestros, Dominus et Magister, et vos debetis alter alterius lavare pedes.

** John 13:15

Exemplum enim dedi vobis, ut quemadmodum ego feci vobis, ita et vos faciatis.

** John 13:16

Amen, amen dico vobis : non est servus major domino suo : neque apostolus major est eo qui misit illum.

** John 13:17

Si hæc scitis, beati eritis si feceritis ea.

** John 13:18

Non de omnibus vobis dico : ego scio quos elegerim ; sed ut adimpleatur Scriptura : Qui manducat mecum panem, levabit contra me calcaneum suum.

** John 13:19

Amodo dico vobis, priusquam fiat : ut cum factum fuerit, credatis quia ego sum.

** John 13:20

Amen, amen dico vobis : qui accipit si quem misero, me accipit ; qui autem me accipit, accipit eum qui me misit.  

** John 13:21

Cum hæc dixisset Jesus, turbatus est spiritu : et protestatus est, et dixit : Amen, amen dico vobis, quia unus ex vobis tradet me.

** John 13:22

Aspiciebant ergo ad invicem discipuli, hæsitantes de quo diceret.

** John 13:23

Erat ergo recumbens unus ex discipulis ejus in sinu Jesu, quem diligebat Jesus.

** John 13:24

Innuit ergo huic Simon Petrus, et dixit ei : Quis est, de quo dicit ?

** John 13:25

Itaque cum recubuisset ille supra pectus Jesu, dicit ei : Domine, quis est ?

** John 13:26

Respondit Jesus : Ille est cui ego intinctum panem porrexero. Et cum intinxisset panem, dedit Judæ Simonis Iscariotæ.

** John 13:27

Et post buccellam, introivit in eum Satanas. Et dixit ei Jesus : Quod facis, fac citius.

** John 13:28

Hoc autem nemo scivit discumbentium ad quid dixerit ei.

** John 13:29

Quidam enim putabant, quia loculos habebat Judas, quod dixisset ei Jesus : Eme ea quæ opus sunt nobis ad diem festum : aut egenis ut aliquid daret.

** John 13:30

Cum ergo accepisset ille buccellam, exivit continuo. Erat autem nox.  

** John 13:31

Cum ergo exisset, dixit Jesus : Nunc clarificatus est Filius hominis, et Deus clarificatus est in eo.

** John 13:32

Si Deus clarificatus est in eo, et Deus clarificabit eum in semetipso : et continuo clarificabit eum.

** John 13:33

Filioli, adhuc modicum vobiscum sum. Quæretis me ; et sicut dixi Judæis, quo ego vado, vos non potestis venire : et vobis dico modo.

** John 13:34

Mandatum novum do vobis : ut diligatis invicem : sicut dilexi vos, ut et vos diligatis invicem.

** John 13:35

In hoc cognoscent omnes quia discipuli mei estis, si dilectionem habueritis ad invicem.  

** John 13:36

Dicit ei Simon Petrus : Domine, quo vadis ? Respondit Jesus : Quo ego vado non potes me modo sequi : sequeris autem postea.

** John 13:37

Dicit ei Petrus : Quare non possum te sequi modo ? animam meam pro te ponam.

** John 13:38

Respondit ei Jesus : Animam tuam pro me pones ? amen, amen dico tibi : non cantabit gallus, donec ter me neges.   

* John 14

** John 14:1

Non turbetur cor vestrum. Creditis in Deum, et in me credite.

** John 14:2

In domo Patris mei mansiones multæ sunt ; si quominus dixissem vobis : quia vado parare vobis locum.

** John 14:3

Et si abiero, et præparavero vobis locum, iterum venio, et accipiam vos ad meipsum : ut ubi sum ego, et vos sitis.

** John 14:4

Et quo ego vado scitis, et viam scitis.

** John 14:5

Dicit ei Thomas : Domine, nescimus quo vadis : et quomodo possumus viam scire ?

** John 14:6

Dicit ei Jesus : Ego sum via, et veritas, et vita. Nemo venit ad Patrem, nisi per me.

** John 14:7

Si cognovissetis me, et Patrem meum utique cognovissetis : et amodo cognoscetis eum, et vidistis eum.

** John 14:8

Dicit ei Philippus : Domine, ostende nobis Patrem, et sufficit nobis.

** John 14:9

Dicit ei Jesus : Tanto tempore vobiscum sum, et non cognovistis me ? Philippe, qui videt me, videt et Patrem. Quomodo tu dicis : Ostende nobis Patrem ?

** John 14:10

Non creditis quia ego in Patre, et Pater in me est ? Verba quæ ego loquor vobis, a meipso non loquor. Pater autem in me manens, ipse fecit opera.

** John 14:11

Non creditis quia ego in Patre, et Pater in me est ?

** John 14:12

alioquin propter opera ipsa credite. Amen, amen dico vobis, qui credit in me, opera quæ ego facio, et ipse faciet, et majora horum faciet : quia ego ad Patrem vado.

** John 14:13

Et quodcumque petieritis Patrem in nomine meo, hoc faciam : ut glorificetur Pater in Filio.

** John 14:14

Si quid petieritis me in nomine meo, hoc faciam.  

** John 14:15

Si diligitis me, mandata mea servate :

** John 14:16

et ego rogabo Patrem, et alium Paraclitum dabit vobis, ut maneat vobiscum in æternum,

** John 14:17

Spiritum veritatis, quem mundus non potest accipere, quia non videt eum, nec scit eum : vos autem cognoscetis eum, quia apud vos manebit, et in vobis erit.

** John 14:18

Non relinquam vos orphanos : veniam ad vos.

** John 14:19

Adhuc modicum, et mundus me jam non videt. Vos autem videtis me : quia ego vivo, et vos vivetis.

** John 14:20

In illo die vos cognoscetis quia ego sum in Patre meo, et vos in me, et ego in vobis.

** John 14:21

Qui habet mandata mea, et servat ea : ille est qui diligit me. Qui autem diligit me, diligetur a Patre meo : et ego diligam eum, et manifestabo ei meipsum.

** John 14:22

Dicit ei Judas, non ille Iscariotes : Domine, quid factum est, quia manifestaturus es nobis teipsum, et non mundo ?

** John 14:23

Respondit Jesus, et dixit ei : Si quis diligit me, sermonem meum servabit, et Pater meus diliget eum, et ad eum veniemus, et mansionem apud eum faciemus ;

** John 14:24

qui non diligit me, sermones meos non servat. Et sermonem, quem audistis, non est meus : sed ejus qui misit me, Patris.

** John 14:25

Hæc locutus sum vobis apud vos manens.

** John 14:26

Paraclitus autem Spiritus Sanctus, quem mittet Pater in nomine meo, ille vos docebit omnia, et suggeret vobis omnia quæcumque dixero vobis.  

** John 14:27

Pacem relinquo vobis, pacem meam do vobis : non quomodo mundus dat, ego do vobis. Non turbetur cor vestrum, neque formidet.

** John 14:28

Audistis quia ego dixi vobis : Vado, et venio ad vos. Si diligeretis me, gauderetis utique, quia vado ad Patrem : quia Pater major me est.

** John 14:29

Et nunc dixi vobis priusquam fiat : ut cum factum fuerit, credatis.

** John 14:30

Jam non multa loquar vobiscum : venit enim princeps mundi hujus, et in me non habet quidquam.

** John 14:31

Sed ut cognoscat mundus quia diligo Patrem, et sicut mandatum dedit mihi Pater, sic facio. Surgite, eamus hinc.   

* John 15

** John 15:1

Ego sum vitis vera, et Pater meus agricola est.

** John 15:2

Omnem palmitem in me non ferentem fructum, tollet eum, et omnem qui fert fructum, purgabit eum, ut fructum plus afferat.

** John 15:3

Jam vos mundi estis propter sermonem quem locutus sum vobis.

** John 15:4

Manete in me, et ego in vobis. Sicut palmes non potest ferre fructum a semetipso, nisi manserit in vite, sic nec vos, nisi in me manseritis.

** John 15:5

Ego sum vitis, vos palmites : qui manet in me, et ego in eo, hic fert fructum multum, quia sine me nihil potestis facere.

** John 15:6

Si quis in me non manserit, mittetur foras sicut palmes, et arescet, et colligent eum, et in ignem mittent, et ardet.

** John 15:7

Si manseritis in me, et verba mea in vobis manserint, quodcumque volueritis petetis, et fiet vobis.

** John 15:8

In hoc clarificatus est Pater meus, ut fructum plurimum afferatis, et efficiamini mei discipuli.  

** John 15:9

Sicut dilexit me Pater, et ego dilexi vos. Manete in dilectione mea.

** John 15:10

Si præcepta mea servaveritis, manebitis in dilectione mea, sicut et ego Patris mei præcepta servavi, et maneo in ejus dilectione.

** John 15:11

Hæc locutus sum vobis : ut gaudium meum in vobis sit, et gaudium vestrum impleatur.

** John 15:12

Hoc est præceptum meum, ut diligatis invicem, sicut dilexi vos.

** John 15:13

Majorem hac dilectionem nemo habet, ut animam suam ponat quis pro amicis suis.

** John 15:14

Vos amici mei estis, si feceritis quæ ego præcipio vobis.

** John 15:15

Jam non dicam vos servos : quia servus nescit quid faciat dominus ejus. Vos autem dixi amicos : quia omnia quæcumque audivi a Patre meo, nota feci vobis.

** John 15:16

Non vos me elegistis, sed ego elegi vos, et posui vos ut eatis, et fructum afferatis, et fructus vester maneat : ut quodcumque petieritis Patrem in nomine meo, det vobis.

** John 15:17

Hæc mando vobis : ut diligatis invicem.  

** John 15:18

Si mundus vos odit, scitote quia me priorem vobis odio habuit.

** John 15:19

Si de mundo fuissetis, mundus quod suum erat diligeret : quia vero de mundo non estis, sed ego elegi vos de mundo, propterea odit vos mundus.

** John 15:20

Mementote sermonis mei, quem ego dixi vobis : non est servus major domino suo. Si me persecuti sunt, et vos persequentur ; si sermonem meum servaverunt, et vestrum servabunt.

** John 15:21

Sed hæc omnia facient vobis propter nomen meum : quia nesciunt eum qui misit me.

** John 15:22

Si non venissem, et locutus fuissem eis, peccatum non haberent : nunc autem excusationem non habent de peccato suo.

** John 15:23

Qui me odit, et Patrem meum odit.

** John 15:24

Si opera non fecissem in eis quæ nemo alius fecit, peccatum non haberent : nunc autem et viderunt, et oderunt et me, et Patrem meum.

** John 15:25

Sed ut adimpleatur sermo, qui in lege eorum scriptus est : Quia odio habuerunt me gratis.

** John 15:26

Cum autem venerit Paraclitus, quem ego mittam vobis a Patre, Spiritum veritatis, qui a Patre procedit, ille testimonium perhibebit de me ;

** John 15:27

et vos testimonium perhibebitis, quia ab initio mecum estis.   

* John 16

** John 16:1

Hæc locutus sum vobis, ut non scandalizemini.

** John 16:2

Absque synagogis facient vos : sed venit hora, ut omnis qui interficit vos arbitretur obsequium se præstare Deo.

** John 16:3

Et hæc facient vobis, quia non noverunt Patrem, neque me.

** John 16:4

Sed hæc locutus sum vobis, ut cum venerit hora eorum, reminiscamini quia ego dixi vobis.  

** John 16:5

Hæc autem vobis ab initio non dixi, quia vobiscum eram. Et nunc vado ad eum qui misit me ; et nemo ex vobis interrogat me : Quo vadis ?

** John 16:6

sed quia hæc locutus sum vobis, tristitia implevit cor vestrum.

** John 16:7

Sed ego veritatem dico vobis : expedit vobis ut ego vadam : si enim non abiero, Paraclitus non veniet ad vos ; si autem abiero, mittam eum ad vos.

** John 16:8

Et cum venerit ille, arguet mundum de peccato, et de justitia, et de judicio.

** John 16:9

De peccato quidem, quia non crediderunt in me.

** John 16:10

De justitia vero, quia ad Patrem vado, et jam non videbitis me.

** John 16:11

De judicio autem, quia princeps hujus mundi jam judicatus est.

** John 16:12

Adhuc multa habeo vobis dicere, sed non potestis portare modo.

** John 16:13

Cum autem venerit ille Spiritus veritatis, docebit vos omnem veritatem : non enim loquetur a semetipso, sed quæcumque audiet loquetur, et quæ ventura sunt annuntiabit vobis.

** John 16:14

Ille me clarificabit, quia de meo accipiet, et annuntiabit vobis.

** John 16:15

Omnia quæcumque habet Pater, mea sunt. Propterea dixi : quia de meo accipiet, et annuntiabit vobis.  

** John 16:16

Modicum, et jam non videbitis me ; et iterum modicum, et videbitis me : quia vado ad Patrem.

** John 16:17

Dixerunt ergo ex discipulis ejus ad invicem : Quid est hoc quod dicit nobis : Modicum, et non videbitis me ; et iterum modicum, et videbitis me, et quia vado ad Patrem ?

** John 16:18

Dicebant ergo : Quid est hoc quod dicit : Modicum ? nescimus quid loquitur.

** John 16:19

Cognovit autem Jesus, quia volebant eum interrogare, et dixit eis : De hoc quæritis inter vos quia dixi : Modicum, et non videbitis me ; et iterum modicum, et videbitis me.

** John 16:20

Amen, amen dico vobis : quia plorabitis, et flebitis vos, mundus autem gaudebit ; vos autem contristabimini, sed tristitia vestra vertetur in gaudium.

** John 16:21

Mulier cum parit, tristitiam habet, quia venit hora ejus ; cum autem pepererit puerum, jam non meminit pressuræ propter gaudium, quia natus est homo in mundum.

** John 16:22

Et vos igitur nunc quidem tristitiam habetis, iterum autem videbo vos, et gaudebit cor vestrum : et gaudium vestrum nemo tollet a vobis.

** John 16:23

Et in illo die me non rogabitis quidquam. Amen, amen dico vobis : si quid petieritis Patrem in nomine meo, dabit vobis.

** John 16:24

Usque modo non petistis quidquam in nomine meo : petite, et accipietis, ut gaudium vestrum sit plenum.  

** John 16:25

Hæc in proverbiis locutus sum vobis. Venit hora cum jam non in proverbiis loquar vobis, sed palam de Patre annuntiabo vobis :

** John 16:26

in illo die in nomine meo petetis : et non dico vobis quia ego rogabo Patrem de vobis :

** John 16:27

ipse enim Pater amat vos, quia vos me amastis, et credidistis, quia ego a Deo exivi.

** John 16:28

Exivi a Patre, et veni in mundum : iterum relinquo mundum, et vado ad Patrem.

** John 16:29

Dicunt ei discipuli ejus : Ecce nunc palam loqueris, et proverbium nullum dicis :

** John 16:30

nunc scimus quia scis omnia, et non opus est tibi ut quis te interroget : in hoc credimus quia a Deo existi.

** John 16:31

Respondit eis Jesus : Modo creditis ?

** John 16:32

ecce venit hora, et jam venit, ut dispergamini unusquisque in propria, et me solum relinquatis : et non sum solus, quia Pater mecum est.

** John 16:33

Hæc locutus sum vobis, ut in me pacem habeatis. In mundo pressuram habebitis : sed confidite, ego vici mundum.   

* John 17

** John 17:1

Hæc locutus est Jesus : et sublevatis oculis in cælum, dixit : Pater, venit hora : clarifica Filium tuum, ut Filius tuus clarificet te :

** John 17:2

sicut dedisti ei potestatem omnis carnis, ut omne, quod dedisti ei, det eis vitam æternam.

** John 17:3

Hæc est autem vita æterna : ut cognoscant te, solum Deum verum, et quem misisti Jesum Christum.

** John 17:4

Ego te clarificavi super terram : opus consummavi, quod dedisti mihi ut faciam :

** John 17:5

et nunc clarifica me tu, Pater, apud temetipsum, claritate quam habui, priusquam mundus esset, apud te.  

** John 17:6

Manifestavi nomen tuum hominibus, quos dedisti mihi de mundo : tui erant, et mihi eos dedisti : et sermonem tuum servaverunt.

** John 17:7

Nunc cognoverunt quia omnia quæ dedisti mihi, abs te sunt :

** John 17:8

quia verba quæ dedisti mihi, dedi eis : et ipsi acceperunt, et cognoverunt vere quia a te exivi, et crediderunt quia tu me misisti.

** John 17:9

Ego pro eis rogo ; non pro mundo rogo, sed pro his quos dedisti mihi : quia tui sunt :

** John 17:10

et mea omnia tua sunt, et tua mea sunt : et clarificatus sum in eis.

** John 17:11

Et jam non sum in mundo, et hi in mundo sunt, et ego ad te venio. Pater sancte, serva eos in nomine tuo, quos dedisti mihi : ut sint unum, sicut et nos.

** John 17:12

Cum essem cum eis, ego servabam eos in nomine tuo. Quos dedisti mihi, custodivi : et nemo ex eis periit, nisi filius perditionis, ut Scriptura impleatur.

** John 17:13

Nunc autem ad te venio : et hæc loquor in mundo, ut habeant gaudium meum impletum in semetipsis.

** John 17:14

Ego dedi eis sermonem tuum, et mundus eos odio habuit, quia non sunt de mundo, sicut et ego non sum de mundo.

** John 17:15

Non rogo ut tollas eos de mundo, sed ut serves eos a malo.

** John 17:16

De mundo non sunt, sicut et ego non sum de mundo.

** John 17:17

Sanctifica eos in veritate. Sermo tuus veritas est.

** John 17:18

Sicut tu me misisti in mundum, et ego misi eos in mundum :

** John 17:19

et pro eis ego sanctifico meipsum : ut sint et ipsi sanctificati in veritate.  

** John 17:20

Non pro eis autem rogo tantum, sed et pro eis qui credituri sunt per verbum eorum in me :

** John 17:21

ut omnes unum sint, sicut tu Pater in me, et ego in te, ut et ipsi in nobis unum sint : ut credat mundus, quia tu me misisti.

** John 17:22

Et ego claritatem, quam dedisti mihi, dedi eis : ut sint unum, sicut et nos unum sumus.

** John 17:23

Ego in eis, et tu in me : ut sint consummati in unum : et cognoscat mundus quia tu me misisti, et dilexisti eos, sicut et me dilexisti.

** John 17:24

Pater, quos dedisti mihi, volo ut ubi sum ego, et illi sint mecum : ut videant claritatem meam, quam dedisti mihi : quia dilexisti me ante constitutionem mundi.

** John 17:25

Pater juste, mundus te non cognovit, ego autem te cognovi : et hi cognoverunt, quia tu me misisti.

** John 17:26

Et notum feci eis nomen tuum, et notum faciam : ut dilectio, qua dilexisti me, in ipsis sit, et ego in ipsis.   

* John 18

** John 18:1

Hæc cum dixisset Jesus, egressus est cum discipulis suis trans torrentem Cedron, ubi erat hortus, in quem introivit ipse, et discipuli ejus.

** John 18:2

Sciebat autem et Judas, qui tradebat eum, locum : quia frequenter Jesus convenerat illuc cum discipulis suis.

** John 18:3

Judas ergo cum accepisset cohortem, et a pontificibus et pharisæis ministros, venit illuc cum laternis, et facibus, et armis.

** John 18:4

Jesus itaque sciens omnia quæ ventura erant super eum, processit, et dixit eis : Quem quæritis ?

** John 18:5

Responderunt ei : Jesum Nazarenum. Dicit eis Jesus : Ego sum. Stabat autem et Judas, qui tradebat eum, cum ipsis.

** John 18:6

Ut ergo dixit eis : Ego sum : abierunt retrorsum, et ceciderunt in terram.

** John 18:7

Iterum ergo interrogavit eos : Quem quæritis ? Illi autem dixerunt : Jesum Nazarenum.

** John 18:8

Respondit Jesus : Dixi vobis, quia ego sum : si ergo me quæritis, sinite hos abire.

** John 18:9

Ut impleretur sermo, quem dixit : Quia quos dedisti mihi, non perdidi ex eis quemquam.

** John 18:10

Simon ergo Petrus habens gladium eduxit eum : et percussit pontificis servum, et abscidit auriculam ejus dexteram. Erat autem nomen servo Malchus.

** John 18:11

Dixit ergo Jesus Petro : Mitte gladium tuum in vaginam. Calicem, quem dedit mihi Pater, non bibam illum ?

** John 18:12

Cohors ergo, et tribunus, et ministri Judæorum comprehenderunt Jesum, et ligaverunt eum.  

** John 18:13

Et adduxerunt eum ad Annam primum : erat enim socer Caiphæ, qui erat pontifex anni illius.

** John 18:14

Erat autem Caiphas, qui consilium dederat Judæis : Quia expedit unum hominem mori pro populo.  

** John 18:15

Sequebatur autem Jesum Simon Petrus, et alius discipulus. Discipulus autem ille erat notus pontifici, et introivit cum Jesu in atrium pontificis.

** John 18:16

Petrus autem stabat ad ostium foris. Exivit ergo discipulus alius, qui erat notus pontifici, et dixit ostiariæ : et introduxit Petrum.

** John 18:17

Dicit ergo Petro ancilla ostiaria : Numquid et tu ex discipulis es hominis istius ? Dicit ille : Non sum.

** John 18:18

Stabant autem servi et ministri ad prunas, quia frigus erat, et calefaciebant se : erat autem cum eis et Petrus stans, et calefaciens se.  

** John 18:19

Pontifex ergo interrogavit Jesum de discipulis suis, et de doctrina ejus.

** John 18:20

Respondit ei Jesus : Ego palam locutus sum mundo : ego semper docui in synagoga, et in templo, quo omnes Judæi conveniunt, et in occulto locutus sum nihil.

** John 18:21

Quid me interrogas ? interroga eos qui audierunt quid locutus sim ipsis : ecce hi sciunt quæ dixerim ego.

** John 18:22

Hæc autem cum dixisset, unus assistens ministrorum dedit alapam Jesu, dicens : Sic respondes pontifici ?

** John 18:23

Respondit ei Jesus : Si male locutus sum, testimonium perhibe de malo : si autem bene, quid me cædis ?

** John 18:24

Et misit eum Annas ligatum ad Caipham pontificem.  

** John 18:25

Erat autem Simon Petrus stans, et calefaciens se. Dixerunt ergo ei : Numquid et tu ex discipulis ejus es ? Negavit ille, et dixit : Non sum.

** John 18:26

Dicit ei unus ex servis pontificis, cognatus ejus, cujus abscidit Petrus auriculam : Nonne ego te vidi in horto cum illo ?

** John 18:27

Iterum ergo negavit Petrus : et statim gallus cantavit.  

** John 18:28

Adducunt ergo Jesum a Caipha in prætorium. Erat autem mane : et ipsi non introierunt in prætorium, ut non contaminarentur, sed ut manducarent Pascha.

** John 18:29

Exivit ergo Pilatus ad eos foras, et dixit : Quam accusationem affertis adversus hominem hunc ?

** John 18:30

Responderunt, et dixerunt ei : Si non esset hic malefactor, non tibi tradidissemus eum.

** John 18:31

Dixit ergo eis Pilatus : Accipite eum vos, et secundum legem vestram judicate eum. Dixerunt ergo ei Judæi : Nobis non licet interficere quemquam.

** John 18:32

Ut sermo Jesu impleretur, quem dixit, significans qua morte esset moriturus.

** John 18:33

Introivit ergo iterum in prætorium Pilatus : et vocavit Jesum, et dixit ei : Tu es rex Judæorum ?

** John 18:34

Respondit Jesus : A temetipso hoc dicis, an alii dixerunt tibi de me ?

** John 18:35

Respondit Pilatus : Numquid ego Judæus sum ? gens tua et pontifices tradiderunt te mihi : quid fecisti ?

** John 18:36

Respondit Jesus : Regnum meum non est de hoc mundo. Si ex hoc mundo esset regnum meum, ministri mei utique decertarent ut non traderer Judæis : nunc autem regnum meum non est hinc.

** John 18:37

Dixit itaque ei Pilatus : Ergo rex es tu ? Respondit Jesus : Tu dicis quia rex sum ego. Ego in hoc natus sum, et ad hoc veni in mundum, ut testimonium perhibeam veritati : omnis qui est ex veritate, audit vocem meam.

** John 18:38

Dicit ei Pilatus : Quid est veritas ? Et cum hoc dixisset, iterum exivit ad Judæos, et dicit eis : Ego nullam invenio in eo causam.

** John 18:39

Est autem consuetudo vobis ut unum dimittam vobis in Pascha : vultis ergo dimittam vobis regem Judæorum ?

** John 18:40

Clamaverunt ergo rursum omnes, dicentes : Non hunc, sed Barabbam. Erat autem Barabbas latro.   

* John 19

** John 19:1

Tunc ergo apprehendit Pilatus Jesum, et flagellavit.

** John 19:2

Et milites plectentes coronam de spinis, imposuerunt capiti ejus : et veste purpurea circumdederunt eum.

** John 19:3

Et veniebant ad eum, et dicebant : Ave, rex Judæorum : et dabant ei alapas.

** John 19:4

Exivit ergo iterum Pilatus foras, et dicit eis : Ecce adduco vobis eum foras, ut cognoscatis quia nullam invenio in eo causam.

** John 19:5

(Exivit ergo Jesus portans coronam spineam, et purpureum vestimentum.) Et dicit eis : Ecce homo.

** John 19:6

Cum ergo vidissent eum pontifices et ministri, clamabant, dicentes : Crucifige, crucifige eum. Dicit eis Pilatus : Accipite eum vos, et crucifigite : ego enim non invenio in eo causam.  

** John 19:7

Responderunt ei Judæi : Nos legem habemus, et secundum legem debet mori, quia Filium Dei se fecit.

** John 19:8

Cum ergo audisset Pilatus hunc sermonem, magis timuit.

** John 19:9

Et ingressus est prætorium iterum : et dixit ad Jesum : Unde es tu ? Jesus autem responsum non dedit ei.

** John 19:10

Dicit ergo ei Pilatus : Mihi non loqueris ? nescis quia potestatem habeo crucifigere te, et potestatem habeo dimittere te ?

** John 19:11

Respondit Jesus : Non haberes potestatem adversum me ullam, nisi tibi datum esset desuper. Propterea qui me tradidit tibi, majus peccatum habet.

** John 19:12

Et exinde quærebat Pilatus dimittere eum. Judæi autem clamabant dicentes : Si hunc dimittis, non es amicus Cæsaris. Omnis enim qui se regem facit, contradicit Cæsari.  

** John 19:13

Pilatus autem cum audisset hos sermones, adduxit foras Jesum : et sedit pro tribunali, in loco qui dicitur Lithostrotos, hebraice autem Gabbatha.

** John 19:14

Erat autem parasceve Paschæ, hora quasi sexta, et dicit Judæis : Ecce rex vester.

** John 19:15

Illi autem clamabant : Tolle, tolle, crucifige eum. Dicit eis Pilatus : Regem vestrum crucifigam ? Responderunt pontifices : Non habemus regem, nisi Cæsarem.

** John 19:16

Tunc ergo tradidit eis illum ut crucifigeretur. Susceperunt autem Jesum, et eduxerunt.  

** John 19:17

Et bajulans sibi crucem exivit in eum, qui dicitur Calvariæ locum, hebraice autem Golgotha :

** John 19:18

ubi crucifixerunt eum, et cum eo alios duos hinc et hinc, medium autem Jesum.

** John 19:19

Scripsit autem et titulum Pilatus, et posuit super crucem. Erat autem scriptum : Jesus Nazarenus, Rex Judæorum.

** John 19:20

Hunc ergo titulum multi Judæorum legerunt : quia prope civitatem erat locus, ubi crucifixus est Jesus, et erat scriptum hebraice, græce, et latine.

** John 19:21

Dicebant ergo Pilato pontifices Judæorum : Noli scribere : Rex Judæorum : sed quia ipse dixit : Rex sum Judæorum.

** John 19:22

Respondit Pilatus : Quod scripsi, scripsi.

** John 19:23

Milites ergo cum crucifixissent eum, acceperunt vestimenta ejus (et fecerunt quatuor partes, unicuique militi partem) et tunicam. Erat autem tunica inconsutilis, desuper contexta per totum.

** John 19:24

Dixerunt ergo ad invicem : Non scindamus eam, sed sortiamur de illa cujus sit. Ut Scriptura impleretur, dicens : Partiti sunt vestimenta mea sibi : et in vestem meam miserunt sortem. Et milites quidem hæc fecerunt.  

** John 19:25

Stabant autem juxta crucem Jesu mater ejus, et soror matris ejus, Maria Cleophæ, et Maria Magdalene.

** John 19:26

Cum vidisset ergo Jesus matrem, et discipulum stantem, quem diligebat, dicit matri suæ : Mulier, ecce filius tuus.

** John 19:27

Deinde dicit discipulo : Ecce mater tua. Et ex illa hora accepit eam discipulus in sua.

** John 19:28

Postea sciens Jesus quia omnia consummata sunt, ut consummaretur Scriptura, dixit : Sitio.

** John 19:29

Vas ergo erat positum aceto plenum. Illi autem spongiam plenam aceto, hyssopo circumponentes, obtulerunt ori ejus.

** John 19:30

Cum ergo accepisset Jesus acetum, dixit : Consummatum est. Et inclinato capite tradidit spiritum.  

** John 19:31

Judæi ergo (quoniam parasceve erat) ut non remanerent in cruce corpora sabbato (erat enim magnus dies ille sabbati), rogaverunt Pilatum ut frangerentur eorum crura, et tollerentur.

** John 19:32

Venerunt ergo milites : et primi quidem fregerunt crura, et alterius, qui crucifixus est cum eo.

** John 19:33

Ad Jesum autem cum venissent, ut viderunt eum jam mortuum, non fregerunt ejus crura,

** John 19:34

sed unus militum lancea latus ejus aperuit, et continuo exivit sanguis et aqua.

** John 19:35

Et qui vidit, testimonium perhibuit : et verum est testimonium ejus. Et ille scit quia vera dicit : ut et vos credatis.

** John 19:36

Facta sunt enim hæc ut Scriptura impleretur : Os non comminuetis ex eo.

** John 19:37

Et iterum alia Scriptura dicit : Videbunt in quem transfixerunt.  

** John 19:38

Post hæc autem rogavit Pilatum Joseph ab Arimathæa (eo quod esset discipulus Jesu, occultus autem propter metum Judæorum), ut tolleret corpus Jesu. Et permisit Pilatus. Venit ergo, et tulit corpus Jesu.

** John 19:39

Venit autem et Nicodemus, qui venerat ad Jesum nocte primum, ferens mixturam myrrhæ et aloës, quasi libras centum.

** John 19:40

Acceperunt ergo corpus Jesu, et ligaverunt illud linteis cum aromatibus, sicut mos est Judæis sepelire.

** John 19:41

Erat autem in loco, ubi crucifixus est, hortus : et in horto monumentum novum, in quo nondum quisquam positus erat.

** John 19:42

Ibi ergo propter parasceven Judæorum, quia juxta erat monumentum, posuerunt Jesum.   

* John 20

** John 20:1

Una autem sabbati, Maria Magdalene venit mane, cum adhuc tenebræ essent, ad monumentum : et vidit lapidem sublatum a monumento.

** John 20:2

Cucurrit ergo, et venit ad Simonem Petrum, et ad alium discipulum, quem amabat Jesus, et dicit illis : Tulerunt Dominum de monumento, et nescimus ubi posuerunt eum.  

** John 20:3

Exiit ergo Petrus, et ille alius discipulus, et venerunt ad monumentum.

** John 20:4

Currebant autem duo simul, et ille alius discipulus præcucurrit citius Petro, et venit primus ad monumentum.

** John 20:5

Et cum se inclinasset, vidit posita linteamina : non tamen introivit.

** John 20:6

Venit ergo Simon Petrus sequens eum, et introivit in monumentum, et vidit linteamina posita,

** John 20:7

et sudarium, quod fuerat super caput ejus, non cum linteaminibus positum, sed separatim involutum in unum locum.

** John 20:8

Tunc ergo introivit et ille discipulus qui venerat primus ad monumentum : et vidit, et credidit :

** John 20:9

nondum enim sciebant Scripturam, quia oportebat eum a mortuis resurgere.

** John 20:10

Abierunt ergo iterum discipuli ad semetipsos.  

** John 20:11

Maria autem stabat ad monumentum foris, plorans. Dum ergo fleret, inclinavit se, et prospexit in monumentum :

** John 20:12

et vidit duos angelos in albis sedentes, unum ad caput, et unum ad pedes, ubi positum fuerat corpus Jesu.

** John 20:13

Dicunt ei illi : Mulier, quid ploras ? Dicit eis : Quia tulerunt Dominum meum : et nescio ubi posuerunt eum.

** John 20:14

Hæc cum dixisset, conversa est retrorsum, et vidit Jesum stantem : et non sciebat quia Jesus est.

** John 20:15

Dicit ei Jesus : Mulier, quid ploras ? quem quæris ? Illa existimans quia hortulanus esset, dicit ei : Domine, si tu sustulisti eum, dicito mihi ubi posuisti eum, et ego eum tollam.

** John 20:16

Dicit ei Jesus : Maria. Conversa illa, dicit ei : Rabboni (quod dicitur Magister).

** John 20:17

Dicit ei Jesus : Noli me tangere, nondum enim ascendi ad Patrem meum : vade autem ad fratres meos, et dic eis : Ascendo ad Patrem meum, et Patrem vestrum, Deum meum, et Deum vestrum.

** John 20:18

Venit Maria Magdalene annuntians discipulis : Quia vidi Dominum, et hæc dixit mihi.  

** John 20:19

Cum ergo sero esset die illo, una sabbatorum, et fores essent clausæ, ubi erant discipuli congregati propter metum Judæorum : venit Jesus, et stetit in medio, et dixit eis : Pax vobis.

** John 20:20

Et cum hoc dixisset, ostendit eis manus et latus. Gavisi sunt ergo discipuli, viso Domino.

** John 20:21

Dixit ergo eis iterum : Pax vobis. Sicut misit me Pater, et ego mitto vos.

** John 20:22

Hæc cum dixisset, insufflavit, et dixit eis : Accipite Spiritum Sanctum :

** John 20:23

quorum remiseritis peccata, remittuntur eis : et quorum retinueritis, retenta sunt.

** John 20:24

Thomas autem unus ex duodecim, qui dicitur Didymus, non erat cum eis quando venit Jesus.

** John 20:25

Dixerunt ergo ei alii discipuli : Vidimus Dominum. Ille autem dixit eis : Nisi videro in manibus ejus fixuram clavorum, et mittam digitum meum in locum clavorum, et mittam manum meam in latus ejus, non credam.  

** John 20:26

Et post dies octo, iterum erant discipuli ejus intus, et Thomas cum eis. Venit Jesus januis clausis, et stetit in medio, et dixit : Pax vobis.

** John 20:27

Deinde dicit Thomæ : Infer digitum tuum huc, et vide manus meas, et affer manum tuam, et mitte in latus meum : et noli esse incredulus, sed fidelis.

** John 20:28

Respondit Thomas, et dixit ei : Dominus meus et Deus meus.

** John 20:29

Dixit ei Jesus : Quia vidisti me, Thoma, credidisti : beati qui non viderunt, et crediderunt.

** John 20:30

Multa quidem et alia signa fecit Jesus in conspectu discipulorum suorum, quæ non sunt scripta in libro hoc.

** John 20:31

Hæc autem scripta sunt ut credatis, quia Jesus est Christus Filius Dei : et ut credentes, vitam habeatis in nomine ejus.   

* John 21

** John 21:1

Postea manifestavit se iterum Jesus discipulis ad mare Tiberiadis. Manifestavit autem sic :

** John 21:2

erant simul Simon Petrus, et Thomas, qui dicitur Didymus, et Nathanaël, qui erat a Cana Galilææ, et filii Zebedæi, et alii ex discipulis ejus duo.

** John 21:3

Dicit eis Simon Petrus : Vado piscari. Dicunt ei : Venimus et nos tecum. Et exierunt, et ascenderunt in navim : et illa nocte nihil prendiderunt.

** John 21:4

Mane autem facto stetit Jesus in littore : non tamen cognoverunt discipuli quia Jesus est.

** John 21:5

Dixit ergo eis Jesus : Pueri, numquid pulmentarium habetis ? Responderunt ei : Non.

** John 21:6

Dicit eis : Mittite in dexteram navigii rete, et invenietis. Miserunt ergo : et jam non valebant illud trahere præ multitudine piscium.

** John 21:7

Dixit ergo discipulus ille, quem diligebat Jesus, Petro : Dominus est. Simon Petrus cum audisset quia Dominus est, tunica succinxit se (erat enim nudus) et misit se in mare.

** John 21:8

Alii autem discipuli navigio venerunt (non enim longe erant a terra, sed quasi cubitis ducentis), trahentes rete piscium.

** John 21:9

Ut ergo descenderunt in terram, viderunt prunas positas, et piscem superpositum, et panem.

** John 21:10

Dicit eis Jesus : Afferte de piscibus, quos prendidistis nunc.

** John 21:11

Ascendit Simon Petrus et traxit rete in terram, plenum magnis piscibus centum quinquaginta tribus. Et cum tanti essent, non est scissum rete.

** John 21:12

Dicit eis Jesus : Venite, prandete. Et nemo audebat discumbentium interrogare eum : Tu quis es ? scientes, quia Dominus est.

** John 21:13

Et venit Jesus, et accipit panem, et dat eis, et piscem similiter.

** John 21:14

Hoc jam tertio manifestatus est Jesus discipulis suis cum resurrexisset a mortuis.  

** John 21:15

Cum ergo prandissent, dicit Simoni Petro Jesus : Simon Joannis, diligis me plus his ? Dicit ei : Etiam Domine, tu scis quia amo te. Dicit ei : Pasce agnos meos.

** John 21:16

Dicit ei iterum : Simon Joannis, diligis me ? Ait illi : Etiam Domine, tu scis quia amo te. Dicit ei : Pasce agnos meos.

** John 21:17

Dicit ei tertio : Simon Joannis, amas me ? Contristatus est Petrus, quia dixit ei tertio : Amas me ? et dixit ei : Domine, tu omnia nosti, tu scis quia amo te. Dixit ei : Pasce oves meas.

** John 21:18

Amen, amen dico tibi : cum esses junior, cingebas te, et ambulabas ubi volebas : cum autem senueris, extendes manus tuas, et alius te cinget, et ducet quo tu non vis.

** John 21:19

Hoc autem dixit significans qua morte clarificaturus esset Deum. Et cum hoc dixisset, dicit ei : Sequere me.  

** John 21:20

Conversus Petrus vidit illum discipulum, quem diligebat Jesus, sequentem, qui et recubuit in cœna super pectus ejus, et dixit : Domine, quis est qui tradet te ?

** John 21:21

Hunc ergo cum vidisset Petrus, dixit Jesu : Domine, hic autem quid ?

** John 21:22

Dicit ei Jesus : Sic eum volo manere donec veniam, quid ad te ? tu me sequere.

** John 21:23

Exiit ergo sermo iste inter fratres quia discipulus ille non moritur. Et non dixit ei Jesus : Non moritur, sed : Sic eum volo manere donec veniam, quid ad te ?

** John 21:24

Hic est discipulus ille qui testimonium perhibet de his, et scripsit hæc : et scimus quia verum est testimonium ejus.

** John 21:25

Sunt autem et alia multa quæ fecit Jesus : quæ si scribantur per singula, nec ipsum arbitror mundum capere posse eos, qui scribendi sunt, libros.    

