* Joshua 1

** Joshua 1:1

Et factum est post mortem Moysi servi Domini, ut loqueretur Dominus ad Josue filium Nun, ministrum Moysi, et diceret ei :

** Joshua 1:2

Moyses servus meus mortuus est : surge, et transi Jordanem istum tu, et omnis populus tecum, in terram quam ego dabo filiis Israël.

** Joshua 1:3

Omnem locum, quem calcaverit vestigium pedis vestri, vobis tradam, sicut locutus sum Moysi.

** Joshua 1:4

A deserto et Libano usque ad fluvium magnum Euphraten, omnis terra Hethæorum usque ad mare magnum contra solis occasum erit terminus vester.

** Joshua 1:5

Nullus poterit vobis resistere cunctis diebus vitæ tuæ : sicut fui cum Moyse, ita ero tecum : non dimittam, nec derelinquam te.

** Joshua 1:6

Confortare, et esto robustus : tu enim sorte divides populo huic terram, pro qua juravi patribus suis, ut traderem eam illis.

** Joshua 1:7

Confortare igitur, et esto robustus valde, ut custodias, et facias omnem legem, quam præcepit tibi Moyses servus meus : ne declines ab ea ad dexteram vel ad sinistram, ut intelligas cuncta quæ agis.

** Joshua 1:8

Non recedat volumen legis hujus ab ore tuo : sed meditaberis in eo diebus ac noctibus, ut custodias et facias omnia quæ scripta sunt in eo : tunc diriges viam tuam, et intelliges eam.

** Joshua 1:9

Ecce præcipio tibi : confortare, et esto robustus. Noli metuere, et noli timere : quoniam tecum est Dominus Deus tuus in omnibus ad quæcumque perrexeris.  

** Joshua 1:10

Præcepitque Josue principibus populi, dicens : Transite per medium castrorum, et imperate populo, ac dicite :

** Joshua 1:11

Præparate vobis cibaria : quoniam post diem tertium transibitis Jordanem, et intrabitis ad possidendam terram quam Dominus Deus vester daturus est vobis.

** Joshua 1:12

Rubenitis quoque et Gaditis, et dimidiæ tribui Manasse, ait :

** Joshua 1:13

Mementote sermonis, quem præcepit vobis Moyses famulus Domini, dicens : Dominus Deus vester dedit vobis requiem, et omnem terram.

** Joshua 1:14

Uxores vestræ, et filii, ac jumenta manebunt in terra, quam tradidit vobis Moyses trans Jordanem : vos autem transite armati ante fratres vestros, omnes fortes manu, et pugnate pro eis,

** Joshua 1:15

donec det Dominus requiem fratribus vestris sicut et vobis dedit, et possideant ipsi quoque terram quam Dominus Deus vester daturus est eis : et sic revertimini in terram possessionis vestræ, et habitabitis in ea, quam vobis dedit Moyses famulus Domini trans Jordanem contra solis ortum.  

** Joshua 1:16

Responderuntque ad Josue, atque dixerunt : Omnia quæ præcepisti nobis, faciemus : et quocumque miseris, ibimus.

** Joshua 1:17

Sicut obedivimus in cunctis Moysi, ita obediemus et tibi : tantum sit Dominus Deus tuus tecum, sicut fuit cum Moyse.

** Joshua 1:18

Qui contradixerit ori tuo, et non obedierit cunctis sermonibus, quos præceperis ei, moriatur. Tu tantum confortare, et viriliter age.   

* Joshua 2

** Joshua 2:1

Misit igitur Josue filius Nun de Setim duos viros exploratores in abscondito : et dixit eis : Ite, et considerate terram, urbemque Jericho. Qui pergentes ingressi sunt domum mulieris meretricis, nomine Rahab, et quieverunt apud eam.

** Joshua 2:2

Nuntiatumque est regi Jericho, et dictum : Ecce viri ingressi sunt huc per noctem de filiis Israël, ut explorarent terram.

** Joshua 2:3

Misitque rex Jericho ad Rahab, dicens : Educ viros, qui venerunt ad te, et ingressi sunt domum tuam : exploratores quippe sunt, et omnem terram considerare venerunt.

** Joshua 2:4

Tollensque mulier viros, abscondit, et ait : Fateor, venerunt ad me, sed nesciebam unde essent :

** Joshua 2:5

cumque porta clauderetur in tenebris, et illi pariter exierunt ; nescio quo abierunt : persequimini cito, et comprehendetis eos.

** Joshua 2:6

Ipsa autem fecit ascendere viros in solarium domus suæ, operuitque eos stipula lini, quæ ibi erat.

** Joshua 2:7

Hi autem, qui missi fuerant, secuti sunt eos per viam, quæ ducit ad vadum Jordanis : illisque egressis statim porta clausa est.  

** Joshua 2:8

Necdum obdormierant qui latebant, et ecce mulier ascendit ad eos, et ait :

** Joshua 2:9

Novi quod Dominus tradiderit vobis terram : etenim irruit in nos terror vester, et elanguerunt omnes habitatores terræ.

** Joshua 2:10

Audivimus quod siccaverit Dominus aquas maris Rubri ad vestrum introitum, quando egressi estis ex Ægypto : et quæ feceritis duobus Amorrhæorum regibus, qui erant trans Jordanem, Sehon et Og, quos interfecistis.

** Joshua 2:11

Et hæc audientes pertimuimus, et elanguit cor nostrum, nec remansit in nobis spiritus ad introitum vestrum : Dominus enim Deus vester ipse est Deus in cælo sursum et in terra deorsum.

** Joshua 2:12

Nunc ergo jurate mihi per Dominum, ut quomodo ego misericordiam feci vobiscum, ita et vos faciatis cum domo patris mei : detisque mihi verum signum,

** Joshua 2:13

ut salvetis patrem meum et matrem, et fratres ac sorores meas, et omnia quæ illorum sunt, et eruatis animas nostras a morte.

** Joshua 2:14

Qui responderunt ei : Anima nostra sit pro vobis in mortem, si tamen non prodideris nos : cumque tradiderit nobis Dominus terram, faciemus in te misericordiam et veritatem.

** Joshua 2:15

Demisit ergo eos per funem de fenestra : domus enim ejus hærebat muro.

** Joshua 2:16

Dixitque ad eos : Ad montana conscendite, ne forte occurrant vobis revertentes : ibique latitate tribus diebus, donec redeant, et sic ibitis per viam vestram.

** Joshua 2:17

Qui dixerunt ad eam : Innoxii erimus a juramento hoc, quo adjurasti nos :

** Joshua 2:18

si ingredientibus nobis terram, signum fuerit funiculus iste coccineus, et ligaveris eum in fenestra, per quam demisisti nos : et patrem tuum ac matrem, fratresque et omnem cognationem tuam congregaveris in domum tuam.

** Joshua 2:19

Qui ostium domus tuæ egressus fuerit, sanguis ipsius erit in caput ejus, et nos erimus alieni. Cunctorum autem sanguis, qui tecum in domo fuerint, redundabit in caput nostrum, si eos aliquis tetigerit.

** Joshua 2:20

Quod si nos prodere volueris, et sermonem istum proferre in medium, erimus mundi ab hoc juramento, quo adjurasti nos.

** Joshua 2:21

Et illa respondit : Sicut locuti estis, ita fiat : dimittensque eos ut pergerent, appendit funiculum coccineum in fenestra.  

** Joshua 2:22

Illi vero ambulantes pervenerunt ad montana, et manserunt ibi tres dies, donec reverterentur qui fuerant persecuti : quærentes enim per omnem viam, non repererunt eos.

** Joshua 2:23

Quibus urbem ingressis, reversi sunt, et descenderunt exploratores de monte : et, transmisso Jordane, venerunt ad Josue filium Nun, narraveruntque ei omnia quæ acciderant sibi,

** Joshua 2:24

atque dixerunt : Tradidit Dominus omnem terram hanc in manus nostras, et timore prostrati sunt cuncti habitatores ejus.   

* Joshua 3

** Joshua 3:1

Igitur Josue de nocte consurgens movit castra : egredientesque de Setim, venerunt ad Jordanem ipse et omnes filii Israël, et morati sunt ibi tres dies.

** Joshua 3:2

Quibus evolutis transierunt præcones per castrorum medium,

** Joshua 3:3

et clamare cœperunt : Quando videritis arcam fœderis Domini Dei vestri, et sacerdotes stirpis Leviticæ portantes eam, vos quoque consurgite, et sequimini præcedentes :

** Joshua 3:4

sitque inter vos et arcam spatium cubitorum duum millium : ut procul videre possitis, et nosse per quam viam ingrediamini : quia prius non ambulastis per eam : et cavete ne appropinquetis ad arcam.

** Joshua 3:5

Dixitque Josue ad populum : Sanctificamini : cras enim faciet Dominus inter vos mirabilia.

** Joshua 3:6

Et ait ad sacerdotes : Tollite arcam fœderis, et præcedite populum. Qui jussa complentes, tulerunt, et ambulaverunt ante eos.

** Joshua 3:7

Dixitque Dominus ad Josue : Hodie incipiam exaltare te coram omni Israël : ut sciant quod sicut cum Moyse fui, ita et tecum sim.

** Joshua 3:8

Tu autem præcipe sacerdotibus, qui portant arcam fœderis, et dic eis : Cum ingressi fueritis partem aquæ Jordanis, state in ea.

** Joshua 3:9

Dixitque Josue ad filios Israël : Accedite huc, et audite verbum Domini Dei vestri.

** Joshua 3:10

Et rursum : In hoc, inquit, scietis quod Dominus Deus vivens in medio vestri est, et disperdet in conspectu vestro Chananæum et Hethæum, Hevæum et Pherezæum, Gergesæum quoque et Jebusæum, et Amorrhæum.

** Joshua 3:11

Ecce arca fœderis Domini omnis terræ antecedet vos per Jordanem.

** Joshua 3:12

Parate duodecim viros de tribubus Israël, singulos per singulas tribus.

** Joshua 3:13

Et cum posuerint vestigia pedum suorum sacerdotes qui portant arcam Domini Dei universæ terræ in aquis Jordanis, aquæ quæ inferiores sunt, decurrent atque deficient : quæ autem desuper veniunt, in una mole consistent.  

** Joshua 3:14

Igitur egressus est populus de tabernaculis suis, ut transiret Jordanem : et sacerdotes, qui portabant arcam fœderis, pergebant ante eum.

** Joshua 3:15

Ingressisque eis Jordanem, et pedibus eorum in parte aquæ tinctis (Jordanis autem ripas alvei sui tempore messis impleverat),

** Joshua 3:16

steterunt aquæ descendentes in loco uno, et ad instar montis intumescentes apparebant procul, ab urbe quæ vocatur Adom usque ad locum Sarthan : quæ autem inferiores erant, in mare Solitudinis (quod nunc vocatur Mortuum) descenderunt, usquequo omnino deficerent.

** Joshua 3:17

Populus autem incedebat contra Jericho : et sacerdotes qui portabant arcam fœderis Domini, stabant super siccam humum in medio Jordanis accincti, omnisque populus per arentem alveum transibat.   

* Joshua 4

** Joshua 4:1

Quibus transgressis, dixit Dominus ad Josue :

** Joshua 4:2

Elige duodecim viros singulos per singulas tribus :

** Joshua 4:3

et præcipe eis ut tollant de medio Jordanis alveo, ubi steterunt pedes sacerdotum, duodecim durissimos lapides, quos ponetis in loco castrorum, ubi fixeritis hac nocte tentoria.

** Joshua 4:4

Vocavitque Josue duodecim viros, quos elegerat de filiis Israël, singulos de singulis tribubus,

** Joshua 4:5

et ait ad eos : Ite ante arcam Domini Dei vestri ad Jordanis medium, et portate inde singuli singulos lapides in humeris vestris, juxta numerum filiorum Israël,

** Joshua 4:6

ut sit signum inter vos : et quando interrogaverint vos filii vestri cras, dicentes : Quid sibi volunt isti lapides ?

** Joshua 4:7

respondebitis eis : Defecerunt aquæ Jordanis ante arcam fœderis Domini, cum transiret eum : idcirco positi sunt lapides isti in monimentum filiorum Israël usque in æternum.

** Joshua 4:8

Fecerunt ergo filii Israël sicut præcepit eis Josue, portantes de medio Jordanis alveo duodecim lapides, ut Dominus ei imperarat, juxta numerum filiorum Israël, usque ad locum in quo castrametati sunt, ibique posuerunt eos.

** Joshua 4:9

Alios quoque duodecim lapides posuit Josue in medio Jordanis alveo, ubi steterunt sacerdotes qui portabant arcam fœderis : et sunt ibi usque in præsentem diem.  

** Joshua 4:10

Sacerdotes autem qui portabant arcam, stabant in Jordanis medio, donec omnia complerentur, quæ Josue, ut loqueretur ad populum, præceperat Dominus, et dixerat ei Moyses. Festinavitque populus, et transiit.

** Joshua 4:11

Cumque transissent omnes, transivit et arca Domini, sacerdotesque pergebant ante populum.

** Joshua 4:12

Filii quoque Ruben, et Gad, et dimidia tribus Manasse, armati præcedebant filios Israël, sicut eis præceperat Moyses :

** Joshua 4:13

et quadraginta pugnatorum millia per turmas, et cuneos, incedebant per plana atque campestria urbis Jericho.

** Joshua 4:14

In die illo magnificavit Dominus Josue coram omni Israël, ut timerent eum, sicut timuerant Moysen, dum adviveret.

** Joshua 4:15

Dixitque ad eum :

** Joshua 4:16

Præcipe sacerdotibus, qui portant arcam fœderis, ut ascendant de Jordane.

** Joshua 4:17

Qui præcepit eis, dicens : Ascendite de Jordane.

** Joshua 4:18

Cumque ascendissent portantes arcam fœderis Domini, et siccam humum calcare cœpissent, reversæ sunt aquæ in alveum suum, et fluebant sicut ante consueverant.  

** Joshua 4:19

Populus autem ascendit de Jordane decimo die mensis primi, et castrametati sunt in Galgalis contra orientalem plagam urbis Jericho.

** Joshua 4:20

Duodecim quoque lapides, quos de Jordanis alveo sumpserant, posuit Josue in Galgalis,

** Joshua 4:21

et dixit ad filios Israël : Quando interrogaverint filii vestri cras patres suos, et dixerint eis : Quid sibi volunt lapides isti ?

** Joshua 4:22

docebitis eos, atque dicetis : Per arentem alveum transivit Israël Jordanem istum,

** Joshua 4:23

siccante Domino Deo vestro aquas ejus in conspectu vestro, donec transiretis,

** Joshua 4:24

sicut fecerat prius in mari Rubro, quod siccavit donec transiremus :

** Joshua 4:25

ut discant omnes terrarum populi fortissimam Domini manum, ut et vos timeatis Dominum Deum vestrum omni tempore.   

* Joshua 5

** Joshua 5:1

Postquam ergo audierunt omnes reges Amorrhæorum, qui habitabant trans Jordanem ad occidentalem plagam, et cuncti reges Chanaan, qui propinqua possidebant magni maris loca, quod siccasset Dominus fluenta Jordanis coram filiis Israël donec transirent, dissolutum est cor eorum, et non remansit in eis spiritus, timentium introitum filiorum Israël.  

** Joshua 5:2

Eo tempore ait Dominus ad Josue : Fac tibi cultros lapideos, et circumcide secundo filios Israël.

** Joshua 5:3

Fecit quod jusserat Dominus, et circumcidit filios Israël in colle præputiorum.

** Joshua 5:4

Hæc autem causa est secundæ circumcisionis : omnis populus, qui egressus est de Ægypto generis masculini, universi bellatores viri, mortui sunt in deserto per longissimos viæ circuitus,

** Joshua 5:5

qui omnes circumcisi erant. Populus autem qui natus est in deserto,

** Joshua 5:6

per quadraginta annos itineris latissimæ solitudinis incircumcisus fuit : donec consumerentur qui non audierant vocem Domini, et quibus ante juraverat ut non ostenderet eis terram lacte et melle manantem.

** Joshua 5:7

Horum filii in locum successerunt patrum, et circumcisi sunt a Josue : quia sicut nati fuerant, in præputio erant, nec eos in via aliquis circumciderat.

** Joshua 5:8

Postquam autem omnes circumcisi sunt, manserunt in eodem castrorum loco, donec sanarentur.

** Joshua 5:9

Dixitque Dominus ad Josue : Hodie abstuli opprobrium Ægypti a vobis. Vocatumque est nomen loci illius Galgala, usque in præsentem diem.  

** Joshua 5:10

Manseruntque filii Israël in Galgalis, et fecerunt Phase quartadecima die mensis ad vesperum in campestribus Jericho :

** Joshua 5:11

et comederunt de frugibus terræ die altero, azymos panes, et polentam ejusdem anni.

** Joshua 5:12

Defecitque manna postquam comederunt de frugibus terræ, nec usi sunt ultra cibo illo filii Israël, sed comederunt de frugibus præsentis anni terræ Chanaan.  

** Joshua 5:13

Cum autem esset Josue in agro urbis Jericho, levavit oculos, et vidit virum stantem contra se, evaginatum tenentem gladium : perrexitque ad eum, et ait : Noster es, an adversariorum ?

** Joshua 5:14

Qui respondit : Nequaquam : sed sum princeps exercitus Domini, et nunc venio.

** Joshua 5:15

Cecidit Josue pronus in terram, et adorans ait : Quid dominus meus loquitur ad servum suum ?

** Joshua 5:16

Solve, inquit, calceamentum tuum de pedibus tuis : locus enim, in quo stas, sanctus est. Fecitque Josue ut sibi fuerat imperatum.   

* Joshua 6

** Joshua 6:1

Jericho autem clausa erat atque munita, timore filiorum Israël, et nullus egredi audebat aut ingredi.

** Joshua 6:2

Dixitque Dominus ad Josue : Ecce dedi in manu tua Jericho, et regem ejus, omnesque fortes viros.

** Joshua 6:3

Circuite urbem cuncti bellatores semel per diem : sic facietis sex diebus.

** Joshua 6:4

Septimo autem die, sacerdotes tollant septem buccinas, quarum usus est in jubilæo, et præcedant arcam fœderis : septiesque circuibitis civitatem, et sacerdotes clangent buccinis.

** Joshua 6:5

Cumque insonuerit vox tubæ longior atque concisior, et in auribus vestris increpuerit, conclamabit omnis populus vociferatione maxima, et muri funditus corruent civitatis, ingredienturque singuli per locum contra quem steterint.

** Joshua 6:6

Vocavit ergo Josue filius Nun sacerdotes, et dixit ad eos : Tollite arcam fœderis : et septem alii sacerdotes tollant septem jubilæorum buccinas, et incedant ante arcam Domini.

** Joshua 6:7

Ad populum quoque ait : Ite, et circuite civitatem, armati, præcedentes arcam Domini.  

** Joshua 6:8

Cumque Josue verba finisset, et septem sacerdotes septem buccinis clangerent ante arcam fœderis Domini,

** Joshua 6:9

omnisque præcederet armatus exercitus, reliquum vulgus arcam sequebatur, ac buccinis omnia concrepabant.

** Joshua 6:10

Præceperat autem Josue populo, dicens : Non clamabitis, nec audietur vox vestra, neque ullus sermo ex ore vestro egredietur, donec veniat dies in quo dicam vobis : Clamate, et vociferamini.

** Joshua 6:11

Circuivit ergo arca Domini civitatem semel per diem, et reversa in castra mansit ibi.

** Joshua 6:12

Igitur Josue de nocte consurgente, tulerunt sacerdotes arcam Domini,

** Joshua 6:13

et septem ex eis septem buccinas, quarum in jubilæo usus est : præcedebantque arcam Domini ambulantes atque clangentes : et armatus populus ibat ante eos, vulgus autem reliquum sequebatur arcam, et buccinis personabat.

** Joshua 6:14

Circuieruntque civitatem secundo die semel, et reversi sunt in castra. Sic fecerunt sex diebus.  

** Joshua 6:15

Dies autem septimo, diluculo consurgentes, circuierunt urbem, sicut dispositum erat, septies.

** Joshua 6:16

Cumque septimo circuitu clangerent buccinis sacerdotes, dixit Josue ad omnem Israël : Vociferamini : tradidit enim vobis Dominus civitatem.

** Joshua 6:17

Sitque civitas hæc anathema, et omnia quæ in ea sunt, Domino : sola Rahab meretrix vivat, cum universis qui cum ea in domo sunt : abscondit enim nuntios quos direximus.

** Joshua 6:18

Vos autem cavete ne de his, quæ præcepta sunt, quippiam contingatis, et sitis prævaricationis rei, et omnia castra Israël sub peccato sint atque turbentur.

** Joshua 6:19

Quidquid autem auri et argenti fuerit, et vasorum æneorum ac ferri, Domino consecretur, repositum in thesauris ejus.

** Joshua 6:20

Igitur omni populo vociferante, et clangentibus tubis, postquam in aures multitudinis vox sonitusque increpuit, muri illico corruerunt : et ascendit unusquisque per locum qui contra se erat : ceperuntque civitatem,

** Joshua 6:21

et interfecerunt omnia quæ erant in ea, a viro usque ad mulierem, ab infante usque ad senem. Boves quoque et oves et asinos in ore gladii percusserunt.  

** Joshua 6:22

Duobus autem viris, qui exploratores missi fuerant, dixit Josue : Ingredimini domum mulieris meretricis, et producite eam, et omnia quæ illius sunt, sicut illi juramento firmastis.

** Joshua 6:23

Ingressique juvenes eduxerunt Rahab, et parentes ejus, fratres quoque, et cunctam supellectilem ac cognationem illius, et extra castra Israël manere fecerunt.

** Joshua 6:24

Urbem autem, et omnia quæ erant in ea, succenderunt, absque auro et argento, et vasis æneis, ac ferro, quæ in ærarium Domini consecrarunt.

** Joshua 6:25

Rahab vero meretricem, et domum patris ejus, et omnia quæ habebat, fecit Josue vivere, et habitaverunt in medio Israël, usque in præsentem diem : eo quod absconderit nuntios, quos miserat ut explorarent Jericho. In tempore illo, imprecatus est Josue, dicens :

** Joshua 6:26

Maledictus vir coram Domino, qui suscitaverit et ædificaverit civitatem Jericho. In primogenito suo fundamenta illius jaciat, et in novissimo liberorum ponat portas ejus.

** Joshua 6:27

Fuit ergo Dominus cum Josue, et nomen ejus vulgatum est in omni terra.   

* Joshua 7

** Joshua 7:1

Filii autem Israël prævaricati sunt mandatum, et usurpaverunt de anathemate. Nam Achan filius Charmi filii Zabdi filii Zare de tribu Juda tulit aliquid de anathemate : iratusque est Dominus contra filios Israël.

** Joshua 7:2

Cumque mitteret Josue de Jericho viros contra Hai, quæ est juxta Bethaven, ad orientalem plagam oppidi Bethel, dixit eis : Ascendite, et explorate terram. Qui præcepta complentes exploraverunt Hai.

** Joshua 7:3

Et reversi dixerunt ei : Non ascendat omnis populus, sed duo vel tria millia virorum pergant, et deleant civitatem : quare omnis populus frustra vexabitur contra hostes paucissimos ?

** Joshua 7:4

Ascenderunt ergo tria millia pugnatorum. Qui statim terga vertentes,

** Joshua 7:5

percussi sunt a viris urbis Hai, et corruerunt ex eis triginta sex homines : persecutique sunt eos adversarii de porta usque ad Sabarim, et ceciderunt per prona fugientes : pertimuitque cor populi, et instar aquæ liquefactum est.  

** Joshua 7:6

Josue vero scidit vestimenta sua, et pronus cecidit in terram coram arca Domini usque ad vesperam, tam ipse quam omnes senes Israël : miseruntque pulverem super capita sua,

** Joshua 7:7

et dixit Josue : Heu Domine Deus, quid voluisti traducere populum istum Jordanem fluvium, ut traderes nos in manus Amorrhæi, et perderes ? utinam ut cœpimus, mansissemus trans Jordanem.

** Joshua 7:8

Mi Domine Deus, quid dicam, videns Israëlem hostibus suis terga vertentem ?

** Joshua 7:9

Audient Chananæi, et omnes habitatores terræ, et pariter conglobati circumdabunt nos, atque delebunt nomen nostrum de terra : et quid facies magno nomini tuo ?  

** Joshua 7:10

Dixitque Dominus ad Josue : Surge : cur jaces pronus in terra ?

** Joshua 7:11

Peccavit Israël, et prævaricatus est pactum meum : tuleruntque de anathemate, et furati sunt atque mentiti, et absconderunt inter vasa sua.

** Joshua 7:12

Nec poterit Israël stare ante hostes suos, eosque fugiet : quia pollutus est anathemate. Non ero ultra vobiscum, donec conteratis eum qui hujus sceleris reus est.

** Joshua 7:13

Surge, sanctifica populum, et dic eis : Sanctificamini in crastinum : hæc enim dicit Dominus Deus Israël : Anathema in medio tui est, Israël : non poteris stare coram hostibus tuis, donec deleatur ex te qui hoc contaminatus est scelere.

** Joshua 7:14

Accedetisque mane singuli per tribus vestras : et quamcumque tribum sors invenerit, accedet per cognationes suas, et cognatio per domos, domusque per viros.

** Joshua 7:15

Et quicumque ille in hoc facinore fuerit deprehensus, comburetur igni cum omni substantia sua : quoniam prævaricatus est pactum Domini, et fecit nefas in Israël.  

** Joshua 7:16

Surgens itaque Josue mane, applicuit Israël per tribus suas, et inventa est tribus Juda.

** Joshua 7:17

Quæ cum juxta familias suas esset oblata, inventa est familia Zare. Illam quoque per domos offerens, reperit Zabdi :

** Joshua 7:18

cujus domum in singulos dividens viros, invenit Achan filium Charmi filii Zabdi filii Zare de tribu Juda.

** Joshua 7:19

Et ait Josue ad Achan : Fili mi, da gloriam Domino Deo Israël, et confitere, atque indica mihi quid feceris, ne abscondas.

** Joshua 7:20

Responditque Achan Josue, et dixit ei : Vere ego peccavi Domino Deo Israël, et sic et sic feci.

** Joshua 7:21

Vidi enim inter spolia pallium coccineum valde bonum, et ducentos siclos argenti, regulamque auream quinquaginta siclorum : et concupiscens abstuli, et abscondi in terra contra medium tabernaculi mei, argentumque fossa humo operui.

** Joshua 7:22

Misit ergo Josue ministros : qui currentes ad tabernaculum illius, repererunt cuncta abscondita in eodem loco, et argentum simul.

** Joshua 7:23

Auferentesque de tentorio, tulerunt ea ad Josue, et ad omnes filios Israël, projeceruntque ante Dominum.

** Joshua 7:24

Tollens itaque Josue Achan filium Zare, argentumque et pallium, et auream regulam, filios quoque et filias ejus, boves et asinos et oves, ipsumque tabernaculum, et cunctam supellectilem (et omnis Israël cum eo), duxerunt eos ad vallem Achor :

** Joshua 7:25

ubi dixit Josue : Quia turbasti nos, exturbet te Dominus in die hac. Lapidavitque eum omnis Israël : et cuncta quæ illius erant, igne consumpta sunt.

** Joshua 7:26

Congregaveruntque super eum acervum magnum lapidum, qui permanet usque in præsentem diem. Et aversus est furor Domini ab eis. Vocatumque est nomen loci illius, vallis Achor, usque hodie.   

* Joshua 8

** Joshua 8:1

Dixit autem Dominus ad Josue : Ne timeas, neque formides : tolle tecum omnem multitudinem pugnatorum, et consurgens ascende in oppidum Hai. Ecce tradidi in manu tua regem ejus et populum, urbemque et terram.

** Joshua 8:2

Faciesque urbi Hai, et regi ejus, sicut fecisti Jericho, et regi illius : prædam vero, et omnia animantia diripietis vobis : pone insidias urbi post eam.

** Joshua 8:3

Surrexitque Josue, et omnis exercitus bellatorum cum eo, ut ascenderent in Hai : et electa triginta millia virorum fortium misit nocte,

** Joshua 8:4

præcepitque eis, dicens : Ponite insidias post civitatem, nec longius recedatis : et eritis omnes parati.

** Joshua 8:5

Ego autem, et reliqua multitudo, quæ mecum est, accedemus ex adverso contra urbem. Cumque exierint contra nos, sicut ante fecimus, fugiemus, et terga vertemus,

** Joshua 8:6

donec persequentes ab urbe longius protrahantur : putabunt enim nos fugere sicut prius.

** Joshua 8:7

Nobis ergo fugientibus, et illis persequentibus, consurgetis de insidiis, et vastabitis civitatem : tradetque eam Dominus Deus vester in manus vestras.

** Joshua 8:8

Cumque ceperitis, succendite eam, et sic omnia facietis, ut jussi.  

** Joshua 8:9

Dimisitque eos, et perrexerunt ad locum insidiarum, sederuntque inter Bethel et Hai, ad occidentalem plagam urbis Hai : Josue autem nocte illa in medio mansit populi,

** Joshua 8:10

surgensque diluculo recensuit socios, et ascendit cum senioribus in fronte exercitus, vallatus auxilio pugnatorum.

** Joshua 8:11

Cumque venissent et ascendissent ex adverso civitatis, steterunt ad septentrionalem urbis plagam, inter quam et eos erat vallis media.

** Joshua 8:12

Quinque autem millia viros elegerat, et posuerat in insidiis inter Bethel et Hai ex occidentali parte ejusdem civitatis :

** Joshua 8:13

omnis vero reliquus exercitus ad aquilonem aciem dirigebat, ita ut novissimi illius multitudinis occidentalem plagam urbis attingerent. Abiit ergo Josue nocte illa, et stetit in vallis medio.  

** Joshua 8:14

Quod cum vidisset rex Hai, festinavit mane, et egressus est cum omni exercitu civitatis, direxitque aciem contra desertum, ignorans quod post tergum laterent insidiæ.

** Joshua 8:15

Josue vero et omnis Israël cesserunt loco, simulantes metum, et fugientes per solitudinis viam.

** Joshua 8:16

At illi vociferantes pariter, et se mutuo cohortantes, persecuti sunt eos. Cumque recessissent a civitate,

** Joshua 8:17

et ne unus quidem in urbe Hai et Bethel remansisset qui non persequeretur Israël (sicut eruperant aperta oppida relinquentes),

** Joshua 8:18

dixit Dominus ad Josue : Leva clypeum, qui in manu tua est, contra urbem Hai, quoniam tibi tradam eam.

** Joshua 8:19

Cumque elevasset clypeum ex adverso civitatis, insidiæ, quæ latebant, surrexerunt confestim : et pergentes ad civitatem, ceperunt, et succenderunt eam.

** Joshua 8:20

Viri autem civitatis, qui persequebantur Josue, respicientes et videntes fumum urbis ad cælum usque conscendere, non potuerunt ultra huc illucque diffugere : præsertim cum hi qui simulaverant fugam, et tendebant ad solitudinem, contra persequentes fortissime restitissent.

** Joshua 8:21

Vidensque Josue et omnis Israël quod capta esset civitas, et fumus urbis ascenderet, reversus percussit viros Hai.

** Joshua 8:22

Siquidem et illi qui ceperant et succenderant civitatem, egressi ex urbe contra suos, medios hostium ferire cœperunt. Cum ergo ex utraque parte adversarii cæderentur, ita ut nullus de tanta multitudine salvaretur,

** Joshua 8:23

regem quoque urbis Hai apprehenderunt viventem, et obtulerunt Josue.  

** Joshua 8:24

Igitur omnibus interfectis, qui Israëlem ad deserta tendentem fuerant persecuti, et in eodem loco gladio corruentibus, reversi filii Israël percusserunt civitatem.

** Joshua 8:25

Erant autem qui in eodem die conciderant a viro usque ad mulierem, duodecim millia hominum, omnes urbis Hai.

** Joshua 8:26

Josue vero non contraxit manum, quam in sublime porrexerat, tenens clypeum donec interficerentur omnes habitatores Hai.

** Joshua 8:27

Jumenta autem et prædam civitatis diviserunt sibi filii Israël, sicut præceperat Dominus Josue.

** Joshua 8:28

Qui succendit urbem, et fecit eam tumulum sempiternum :

** Joshua 8:29

regem quoque ejus suspendit in patibulo usque ad vesperam et solis occasum. Præcepitque Josue, et deposuerunt cadaver ejus de cruce : projeceruntque in ipso introitu civitatis, congesto super eum magno acervo lapidum, qui permanet usque in præsentem diem.  

** Joshua 8:30

Tunc ædificavit Josue altare Domino Deo Israël in monte Hebal,

** Joshua 8:31

sicut præceperat Moyses famulus Domini filiis Israël, et scriptum est in volumine legis Moysi : altare vero de lapidibus impolitis, quos ferrum non tetigit : et obtulit super eo holocausta Domino, immolavitque pacificas victimas.

** Joshua 8:32

Et scripsit super lapides Deuteronomium legis Moysi, quod ille digesserat coram filiis Israël.

** Joshua 8:33

Omnis autem populus, et majores natu, ducesque ac judices, stabant ex utraque parte arcæ, in conspectu sacerdotum qui portabant arcam fœderis Domini, ut advena, ita et indigena. Media pars eorum juxta montem Garizim, et media juxta montem Hebal, sicut præceperat Moyses famulus Domini. Et primum quidem benedixit populo Israël.

** Joshua 8:34

Post hæc legit omnia verba benedictionis et maledictionis, et cuncta quæ scripta erant in legis volumine.

** Joshua 8:35

Nihil ex his quæ Moyses jusserat, reliquit intactum, sed universa replicavit coram omni multitudine Israël, mulieribus ac parvulis, et advenis qui inter eos morabantur.   

* Joshua 9

** Joshua 9:1

Quibus auditis, cuncti reges trans Jordanem, qui versabantur in montanis et campestribus, in maritimis ac littore magni maris, hi quoque qui habitabant juxta Libanum, Hethæus et Amorrhæus, Chananæus, Pherezæus, et Hevæus, et Jebusæus,

** Joshua 9:2

congregati sunt pariter, ut pugnarent contra Josue et Israël uno animo, eademque sententia.  

** Joshua 9:3

At hi qui habitabant in Gabaon, audientes cuncta quæ fecerat Josue Jericho, et Hai,

** Joshua 9:4

et callide cogitantes, tulerunt sibi cibaria, saccos veteres asinis imponentes, et utres vinarios scissos atque consutos,

** Joshua 9:5

calceamentaque perantiqua quæ ad indicium vetustatis pittaciis consuta erant, induti veteribus vestimentis : panes quoque, quos portabant ob viaticum, duri erant, et in frustra comminuti :

** Joshua 9:6

perrexeruntque ad Josue, qui tunc morabatur in castris Galgalæ, et dixerunt ei, atque simul omni Israëli : De terra longinqua venimus, pacem vobiscum facere cupientes. Responderuntque viri Israël ad eos, atque dixerunt :

** Joshua 9:7

Ne forte in terra, quæ nobis sorte debetur, habitetis, et non possimus fœdus inire vobiscum.

** Joshua 9:8

At illi ad Josue : Servi, inquiunt, tui sumus. Quibus Josue ait : Quinam estis vos ? et unde venistis ?

** Joshua 9:9

Responderunt : De terra longinqua valde venerunt servi tui in nomine Domini Dei tui. Audivimus enim famam potentiæ ejus, cuncta quæ fecit in Ægypto,

** Joshua 9:10

et duobus regibus Amorrhæorum qui fuerunt trans Jordanem, Sehon regi Hesebon, et Og regi Basan, qui erat in Astaroth :

** Joshua 9:11

dixeruntque nobis seniores, et omnes habitatores terræ nostræ : Tollite in manibus cibaria ob longissimam viam, et occurrite eis, et dicite : Servi vestri sumus : fœdus inite nobiscum.

** Joshua 9:12

En panes quando egressi sumus de domibus nostris, ut veniremus ad vos, calidos sumpsimus ; nunc sicci facti sunt, et vetustate nimia comminuti.

** Joshua 9:13

Utres vini novos implevimus ; nunc rupti sunt et soluti. Vestes et calceamenta quibus induimur, et quæ habemus in pedibus, ob longitudinem longioris viæ trita sunt, et pene consumpta.

** Joshua 9:14

Susceperunt igitur de cibariis eorum, et os Domini non interrogaverunt.

** Joshua 9:15

Fecitque Josue cum eis pacem, et inito fœdere pollicitus est quod non occiderentur : principes quoque multitudinis juraverunt eis.  

** Joshua 9:16

Post dies autem tres initi fœderis, audierunt quod in vicino habitarent, et inter eos futuri essent.

** Joshua 9:17

Moveruntque castra filii Israël, et venerunt in civitates eorum die tertio, quarum hæc vocabula sunt : Gabaon, et Caphira, et Beroth, et Cariathiarim.

** Joshua 9:18

Et non percusserunt eos, eo quod jurassent eis principes multitudinis in nomine Domini Dei Israël. Murmuravit itaque omne vulgus contra principes.

** Joshua 9:19

Qui responderunt eis : Juravimus illis in nomine Domini Dei Israël, et idcirco non possumus eos contingere.

** Joshua 9:20

Sed hoc faciemus eis : reserventur quidem ut vivant, ne contra nos ira Domini concitetur, si pejeraverimus :

** Joshua 9:21

sed sic vivant, ut in usus universæ multitudinis ligna cædant, aquasque comportent. Quibus hæc loquentibus,

** Joshua 9:22

vocavit Gabaonitas Josue, et dixit eis : Cur nos decipere fraude voluistis, ut diceretis : Procul valde habitamus a vobis, cum in medio nostri sitis ?

** Joshua 9:23

itaque sub maledictione eritis, et non deficiet de stirpe vestra ligna cædens, aquasque comportans in domum Dei mei.

** Joshua 9:24

Qui responderunt : Nuntiatum est nobis servis tuis, quod promisisset Dominus Deus tuus Moysi servo suo ut traderet vobis omnem terram, et disperderet cunctos habitatores ejus. Timuimus igitur valde, et providimus animabus nostris, vestro terrore compulsi, et hoc consilium inivimus.

** Joshua 9:25

Nunc autem in manu tua sumus : quod tibi bonum et rectum videtur, fac nobis.

** Joshua 9:26

Fecit ergo Josue ut dixerat, et liberavit eos de manu filiorum Israël, ut non occiderentur.

** Joshua 9:27

Decrevitque in illo die eos esse in ministerio cuncti populi, et altaris Domini, cædentes ligna, et aquas comportantes, usque in præsens tempus, in loco quem Dominus elegisset.   

* Joshua 10

** Joshua 10:1

Quæ cum audisset Adonisedec rex Jerusalem, quod scilicet cepisset Josue Hai, et subvertisset eam (sicut enim fecerat Jericho et regi ejus, sic fecit Hai et regi illius), et quod transfugissent Gabaonitæ ad Israël, et essent fœderati eorum,

** Joshua 10:2

timuit valde. Urbs enim magna erat Gabaon, et una civitatum regalium, et major oppido Hai, omnesque bellatores ejus fortissimi.

** Joshua 10:3

Misit ergo Adonisedec rex Jerusalem ad Oham regem Hebron, et ad Pharam regem Jerimoth, ad Japhia quoque regem Lachis, et ad Dabir regem Eglon, dicens :

** Joshua 10:4

Ad me ascendite, et ferte præsidium, ut expugnemus Gabaon, quare transfugerit ad Josue, et ad filios Israël.

** Joshua 10:5

Congregati igitur ascenderunt quinque reges Amorrhæorum : rex Jerusalem, rex Hebron, rex Jerimoth, rex Lachis, rex Eglon, simul cum exercitibus suis : et castrametati sunt circa Gabaon, oppugnantes eam.  

** Joshua 10:6

Habitatores autem Gabaon urbis obsessæ miserunt ad Josue, qui tunc morabatur in castris apud Galgalam, et dixerunt ei : Ne retrahas manus tuas ab auxilio servorum tuorum : ascende cito, et libera nos, ferque præsidium : convenerunt enim adversum nos omnes reges Amorrhæorum, qui habitant in montanis.

** Joshua 10:7

Ascenditque Josue de Galgalis, et omnis exercitus bellatorum cum eo, viri fortissimi.

** Joshua 10:8

Dixitque Dominus ad Josue : Ne timeas eos : in manus enim tuas tradidi illos : nullus ex eis tibi resistere poterit.

** Joshua 10:9

Irruit itaque Josue super eos repente, tota nocte ascendens de Galgalis.

** Joshua 10:10

Et conturbavit eos Dominus a facie Israël : contrivitque plaga magna in Gabaon, ac persecutus est eos per viam ascensus Bethoron, et percussit usque Azeca et Maceda.

** Joshua 10:11

Cumque fugerent filios Israël, et essent in descensu Bethoron, Dominus misit super eos lapides magnos de cælo usque ad Azeca : et mortui sunt multo plures lapidibus grandinis, quam quos gladio percusserant filii Israël.

** Joshua 10:12

Tunc locutus est Josue Domino, in die qua tradidit Amorrhæum in conspectu filiorum Israël, dixitque coram eis :   Sol, contra Gabaon ne movearis,  et luna contra vallem Ajalon. 

** Joshua 10:13

Steteruntque sol et luna,  donec ulcisceretur se gens de inimicis suis. Nonne scriptum est hoc in libro justorum ? Stetit itaque sol in medio cæli, et non festinavit occumbere spatio unius diei.

** Joshua 10:14

Non fuit antea nec postea tam longa dies, obediente Domino voci hominis, et pugnante pro Israël.

** Joshua 10:15

Reversusque est Josue cum omni Israël in castra Galgalæ.  

** Joshua 10:16

Fugerant enim quinque reges et se absconderant in spelunca urbis Maceda.

** Joshua 10:17

Nuntiatumque est Josue quod inventi essent quinque reges latentes in spelunca urbis Maceda.

** Joshua 10:18

Qui præcepit sociis, et ait : Volvite saxa ingentia ad os speluncæ, et ponite viros industrios, qui clausos custodiant :

** Joshua 10:19

vos autem nolite stare, sed persequimini hostes, et extremos quosque fugientium cædite : nec dimittatis eos urbium suarum intrare præsidia, quos tradidit Dominus Deus in manus vestras.

** Joshua 10:20

Cæsis ergo adversariis plaga magna, et usque ad internecionem pene consumptis, hi qui Israël effugere potuerunt, ingressi sunt civitates munitas.

** Joshua 10:21

Reversusque est omnis exercitus ad Josue in Maceda, ubi tunc erant castra, sani et integro numero : nullusque contra filios Israël mutire ausus est.

** Joshua 10:22

Præcepitque Josue, dicens : Aperite os speluncæ, et producite ad me quinque reges, qui in ea latitant.

** Joshua 10:23

Feceruntque ministri ut sibi fuerat imperatum : et eduxerunt ad eum quinque reges de spelunca, regem Jerusalem, regem Hebron, regem Jerimoth, regem Lachis, regem Eglon.

** Joshua 10:24

Cumque educti essent ad eum, vocavit omnes viros Israël, et ait ad principes exercitus qui secum erant : Ite, et ponite pedes super colla regum istorum. Qui cum perrexissent, et subjectorum colla pedibus calcarent,

** Joshua 10:25

rursum ait ad eos : Nolite timere, nec paveatis : confortamini, et estote robusti : sic enim faciet Dominus cunctis hostibus vestris, adversum quos dimicatis.

** Joshua 10:26

Percussitque Josue, et interfecit eos, atque suspendit super quinque stipites : fueruntque suspensi usque ad vesperum.

** Joshua 10:27

Cumque occumberet sol, præcepit sociis ut deponerent eos de patibulis. Qui depositos projecerunt in speluncam in qua latuerant, et posuerunt super os ejus saxa ingentia, quæ permanent usque in præsens.  

** Joshua 10:28

Eodem quoque die, Macedam cepit Josue, et percussit eam in ore gladii, regemque illius interfecit, et omnes habitatores ejus : non dimisit in ea saltem parvas reliquias. Fecitque regi Maceda sicut fecerat regi Jericho.

** Joshua 10:29

Transivit autem cum omni Israël de Maceda in Lebna, et pugnabat contra eam :

** Joshua 10:30

quam tradidit Dominus cum rege suo in manus Israël : percusseruntque urbem in ore gladii, et omnes habitatores ejus : non dimiserunt in ea ullas reliquias. Feceruntque regi Lebna sicut fecerant regi Jericho.

** Joshua 10:31

De Lebna transivit in Lachis cum omni Israël : et exercitu per gyrum disposito, oppugnabat eam.

** Joshua 10:32

Tradiditque Dominus Lachis in manus Israël, et cepit eam die altero, atque percussit in ore gladii, omnemque animam quæ fuerat in ea, sicut fecerat Lebna.

** Joshua 10:33

Eo tempore ascendit Horam rex Gazer, ut auxiliaretur Lachis : quem percussit Josue cum omni populo ejus usque ad internecionem.

** Joshua 10:34

Transivitque de Lachis in Eglon, et circumdedit,

** Joshua 10:35

atque expugnavit eam eadem die : percussitque in ore gladii omnes animas quæ erant in ea, juxta omnia quæ fecerat Lachis.

** Joshua 10:36

Ascendit quoque cum omni Israël de Eglon in Hebron, et pugnavit contra eam :

** Joshua 10:37

cepit eam, et percussit in ore gladii, regem quoque ejus, et omnia oppida regionis illius, universasque animas quæ in ea fuerant commoratæ : non reliquit in ea ullas reliquias : sicut fecerat Eglon, sic fecit et Hebron, cuncta quæ in ea reperit consumens gladio.

** Joshua 10:38

Inde reversus in Dabir,

** Joshua 10:39

cepit eam atque vastavit : regem quoque ejus atque omnia per circuitum oppida percussit in ore gladii : non dimisit in ea ullas reliquias : sicut fecerat Hebron et Lebna et regibus earum, sic fecit Dabir et regi illius.

** Joshua 10:40

Percussit itaque Josue omnem terram montanam et meridianam atque campestrem, et Asedoth, cum regibus suis : non dimisit in ea ullas reliquias, sed omne quod spirare poterat interfecit, sicut præceperat ei Dominus Deus Israël,

** Joshua 10:41

a Cadesbarne usque Gazam. Omnem terram Gosen usque Gabaon,

** Joshua 10:42

universosque reges, et regiones eorum uno impetu cepit atque vastavit : Dominus enim Deus Israël pugnavit pro eo.

** Joshua 10:43

Reversusque est cum omni Israël ad locum castrorum in Galgala.   

* Joshua 11

** Joshua 11:1

Quæ cum audisset Jabin rex Asor, misit ad Jobab regem Madon, et ad regem Semeron, atque ad regem Achsaph :

** Joshua 11:2

ad reges quoque aquilonis, qui habitabant in montanis et in planitie contra meridiem Ceneroth, in campestribus quoque et in regionibus Dor juxta mare :

** Joshua 11:3

Chananæum quoque ab oriente et occidente, et Amorrhæum atque Hethæum ac Pherezæum et Jebusæum in montanis : Hevæum quoque qui habitabat ad radices Hermon in terra Maspha.

** Joshua 11:4

Egressique sunt omnes cum turmis suis, populus multus nimis sicut arena quæ est in littore maris, equi quoque et currus immensæ multitudinis.

** Joshua 11:5

Conveneruntque omnes reges isti in unum ad aquas Merom, ut pugnarent contra Israël.  

** Joshua 11:6

Dixitque Dominus ad Josue : Ne timeas eos : cras enim hac eadem hora ego tradam omnes istos vulnerandos in conspectu Israël : equos eorum subnervabis, et currus igne combures.

** Joshua 11:7

Venitque Josue, et omnis exercitus cum eo, adversus illos ad aquas Merom subito, et irruerunt super eos,

** Joshua 11:8

tradiditque illos Dominus in manus Israël. Qui percusserunt eos, et persecuti sunt usque ad Sidonem magnam, et aquas Maserephoth, campumque Masphe, qui est ad orientalem illius partem. Ita percussit omnes, ut nullas dimitteret ex eis reliquias :

** Joshua 11:9

fecitque sicut præceperat ei Dominus : equos eorum subnervavit, currusque combussit igni.

** Joshua 11:10

Reversusque statim cepit Asor, et regem ejus percussit gladio. Asor enim antiquitus inter omnia regna hæc principatum tenebat.

** Joshua 11:11

Percussitque omnes animas quæ ibidem morabantur : non dimisit in ea ullas reliquias, sed usque ad internecionem universa vastavit, ipsamque urbem peremit incendio.

** Joshua 11:12

Et omnes per circuitum civitates, regesque earum, cepit, percussit atque delevit, sicut præceperat ei Moyses famulus Domini.

** Joshua 11:13

Absque urbibus, quæ erant in collibus et in tumulis sitæ, ceteras succendit Israël : unam tantum Asor munitissimam flamma consumpsit.

** Joshua 11:14

Omnemque prædam istarum urbium ac jumenta diviserunt sibi filii Israël, cunctis hominibus interfectis.

** Joshua 11:15

Sicut præceperat Dominus Moysi servo suo, ita præcepit Moyses Josue, et ille universa complevit : non præteriit de universis mandatis, nec unum quidem verbum quod jusserat Dominus Moysi.

** Joshua 11:16

Cepit itaque Josue omnem terram montanam et meridianam, terramque Gosen, et planitiem, et occidentalem plagam, montemque Israël, et campestria ejus,

** Joshua 11:17

et partem montis, quæ ascendit Seir usque Baalgad, per planitiem Libani subter montem Hermon : omnes reges eorum cepit, percussit, et occidit.

** Joshua 11:18

Multo tempore pugnavit Josue contra reges istos.

** Joshua 11:19

Non fuit civitas quæ se traderet filiis Israël, præter Hevæum, qui habitabat in Gabaon : omnes enim bellando cepit.

** Joshua 11:20

Domini enim sententia fuerat, ut indurarentur corda eorum, et pugnarent contra Israël, et caderent, et non mererentur ullam clementiam, ac perirent, sicut præceperat Dominus Moysi.

** Joshua 11:21

In illo tempore venit Josue, et interfecit Enacim de montanis, Hebron, et Dabir, et Anab, et de omni monte Juda et Israël, urbesque eorum delevit.

** Joshua 11:22

Non reliquit ullum de stirpe Enacim, in terra filiorum Israël : absque civitatibus Gaza, et Geth, et Azoto, in quibus solis relicti sunt.

** Joshua 11:23

Cepit ergo Josue omnem terram, sicut locutus est Dominus ad Moysen, et tradidit eam in possessionem filiis Israël secundum partes et tribus suas : quievitque terra a præliis.   

* Joshua 12

** Joshua 12:1

Hi sunt reges, quos percusserunt filii Israël, et possederunt terram eorum trans Jordanem ad solis ortum, a torrente Arnon usque ad montem Hermon, et omnem orientalem plagam, quæ respicit solitudinem.

** Joshua 12:2

Sehon rex Amorrhæorum, qui habitavit in Hesebon, dominatus est ab Aroër, quæ sita est super ripam torrentis Arnon, et mediæ partis in valle, dimidiæque Galaad, usque ad torrentem Jaboc, qui est terminus filiorum Ammon.

** Joshua 12:3

Et a solitudine usque ad mare Ceneroth contra orientem, et usque ad mare deserti, quod est mare salsissimum, ad orientalem plagam per viam quæ ducit Bethsimoth : et ab australi parte, quæ subjacet Asedoth, Phasga.

** Joshua 12:4

Terminus Og regis Basan, de reliquiis Raphaim, qui habitavit in Astaroth, et in Edrai, et dominatus est in monte Hermon, et in Salecha, atque in universa Basan, usque ad terminos

** Joshua 12:5

Gessuri, et Machati, et dimidiæ partis Galaad : terminos Sehon regis Hesebon.

** Joshua 12:6

Moyses famulus Domini et filii Israël percusserunt eos, tradiditque terram eorum Moyses in possessionem Rubenitis, et Gaditis, et dimidiæ tribui Manasse.

** Joshua 12:7

Hi sunt reges terræ, quos percussit Josue et filii Israël trans Jordanem ad occidentalem plagam, a Baalgad in campo Libani, usque ad montem cujus pars ascendit in Seir : tradiditque eam Josue in possessionem tribubus Israël, singulis partes suas,

** Joshua 12:8

tam in montanis quam in planis atque campestribus. In Asedoth, et in solitudine, ac in meridie, Hethæus fuit et Amorrhæus, Chananæus, et Pherezæus, Hevæus et Jebusæus.

** Joshua 12:9

Rex Jericho unus : rex Hai, quæ est ex latere Bethel, unus :

** Joshua 12:10

rex Jerusalem unus, rex Hebron unus,

** Joshua 12:11

rex Jerimoth unus, rex Lachis unus,

** Joshua 12:12

rex Eglon unus, rex Gazer unus,

** Joshua 12:13

rex Dabir unus, rex Gader unus,

** Joshua 12:14

rex Herma unus, rex Hered unus,

** Joshua 12:15

rex Lebna unus, rex Odullam unus,

** Joshua 12:16

rex Maceda unus, rex Bethel unus,

** Joshua 12:17

rex Taphua unus, rex Opher unus,

** Joshua 12:18

rex Aphec unus, rex Saron unus,

** Joshua 12:19

rex Madon unus, rex Asor unus,

** Joshua 12:20

rex Semeron unus, rex Achsaph unus,

** Joshua 12:21

rex Thenac unus, rex Mageddo unus,

** Joshua 12:22

rex Cades unus, rex Jachanan Carmeli unus,

** Joshua 12:23

rex Dor et provinciæ Dor unus, rex gentium Galgal unus,

** Joshua 12:24

rex Thersa unus : omnes reges triginta unus.   

* Joshua 13

** Joshua 13:1

Josue senex provectæque ætatis erat, et dixit Dominus ad eum : Senuisti, et longævus es, terraque latissima derelicta est, quæ necdum sorte divisa est :

** Joshua 13:2

omnis videlicet Galilæa, Philisthiim, et universa Gessuri.

** Joshua 13:3

A fluvio turbido, qui irrigat Ægyptum, usque ad terminos Accaron contra aquilonem : terra Chanaan, quæ in quinque regulos Philisthiim dividitur, Gazæos, et Azotios, Ascalonitas, Gethæos, et Accaronitas.

** Joshua 13:4

Ad meridiem vero sunt Hevæi, omnis terra Chanaan, et Maara Sidoniorum, usque Apheca et terminos Amorrhæi,

** Joshua 13:5

ejusque confinia. Libani quoque regio contra orientem, a Baalgad sub monte Hermon, donec ingrediaris Emath ;

** Joshua 13:6

omnium qui habitant in monte a Libano usque ad aquas Maserephoth, universique Sidonii. Ego sum qui delebo eos a facie filiorum Israël. Veniat ergo in partem hæreditatis Israël, sicut præcepi tibi.

** Joshua 13:7

Et nunc divide terram in possessionem novem tribubus, et dimidiæ tribui Manasse,

** Joshua 13:8

cum qua Ruben et Gad possederunt terram, quam tradidit eis Moyses famulus Domini trans fluenta Jordanis, ad orientalem plagam.

** Joshua 13:9

Ab Aroër, quæ sita est in ripa torrentis Arnon, et in vallis medio, universaque campestria Medaba, usque Dibon,

** Joshua 13:10

et cunctas civitates Sehon regis Amorrhæi, qui regnavit in Hesebon, usque ad terminos filiorum Ammon,

** Joshua 13:11

et Galaad, ac terminum Gessuri et Machati, et omnem montem Hermon, et universam Basan, usque ad Salecha,

** Joshua 13:12

omne regnum Og in Basan, qui regnavit in Astaroth et Edrai, ipse fuit de reliquiis Raphaim : percussitque eos Moyses, atque delevit.

** Joshua 13:13

Nolueruntque disperdere filii Israël Gessuri et Machati : et habitaverunt in medio Israël usque in præsentem diem.

** Joshua 13:14

Tribui autem Levi non dedit possessionem : sed sacrificia et victimæ Domini Dei Israël, ipsa est ejus hæreditas, sicut locutus est illi.  

** Joshua 13:15

Dedit ergo Moyses possessionem tribui filiorum Ruben juxta cognationes suas.

** Joshua 13:16

Fuitque terminus eorum ab Aroër, quæ sita est in ripa torrentis Arnon, et in valle ejusdem torrentis media : universam planitiem, quæ ducit Medaba,

** Joshua 13:17

et Hesebon, cunctosque viculos earum, qui sunt in campestribus : Dibon quoque et Bamothbaal, et oppidum Baalmaon,

** Joshua 13:18

et Jassa, et Cedimoth, et Mephaath,

** Joshua 13:19

et Cariathaim, et Sabama, et Sarathasar in monte convallis.

** Joshua 13:20

Bethphogor et Asedoth, Phasga et Bethiesimoth,

** Joshua 13:21

et omnes urbes campestres, universaque regna Sehon regis Amorrhæi, qui regnavit in Hesebon, quem percussit Moyses cum principibus Madian : Hevæum, et Recem, et Sur, et Hur, et Rebe duces Sehon habitatores terræ.

** Joshua 13:22

Et Balaam filium Beor ariolum occiderunt filii Israël gladio cum ceteris interfectis.

** Joshua 13:23

Factusque est terminus filiorum Ruben Jordanis fluvius. Hæc est possessio Rubenitarum per cognationes suas urbium et viculorum.  

** Joshua 13:24

Deditque Moyses tribui Gad et filiis ejus per cognationes suas possessionem, cujus hæc divisio est.

** Joshua 13:25

Terminus Jaser, et omnes civitates Galaad, et dimidiam partem terræ filiorum Ammon, usque ad Aroër, quæ est contra Rabba,

** Joshua 13:26

et ab Hesebon usque Ramoth, Masphe et Betonim : et a Manaim usque ad terminos Dabir.

** Joshua 13:27

In valle quoque Betharan, et Bethnemra, et Socoth, et Saphon reliquam partem regni Sehon regis Hesebon : hujus quoque finis, Jordanis est, usque ad extremam partem maris Cenereth trans Jordanem ad orientalem plagam.

** Joshua 13:28

Hæc est possessio filiorum Gad per familias suas, civitates et villæ earum.  

** Joshua 13:29

Dedit et dimidiæ tribui Manasse, filiisque ejus juxta cognationes suas, possessionem,

** Joshua 13:30

cujus hoc principium est : a Manaim universam Basan, et cuncta regna Og regis Basan, omnesque vicos Jair, qui sunt in Basan, sexaginta oppida :

** Joshua 13:31

et dimidiam partem Galaad, et Astaroth, et Edrai, urbes regni Og in Basan : filiis Machir, filii Manasse, dimidiæ parti filiorum Machir juxta cognationes suas.

** Joshua 13:32

Hanc possessionem divisit Moyses in campestribus Moab trans Jordanem contra Jericho ad orientalem plagam.

** Joshua 13:33

Tribui autem Levi non dedit possessionem : quoniam Dominus Deus Israël ipse est possessio ejus, ut locutus est illi.   

* Joshua 14

** Joshua 14:1

Hoc est quod possederunt filii Israël in terra Chanaan, quam dederunt eis Eleazar sacerdos, et Josue filius Nun, et principes familiarum per tribus Israël :

** Joshua 14:2

sorte omnia dividentes, sicut præceperat Dominus in manu Moysi, novem tribubus, et dimidiæ tribui.

** Joshua 14:3

Duabus enim tribubus, et dimidiæ, dederat Moyses trans Jordanem possessionem : absque Levitis, qui nihil terræ acceperunt inter fratres suos :

** Joshua 14:4

sed in eorum successerunt locum filii Joseph in duas divisi tribus, Manasse et Ephraim : nec acceperunt Levitæ aliam in terra partem, nisi urbes ad habitandum, et suburbana earum ad alenda jumenta et pecora sua.

** Joshua 14:5

Sicut præceperat Dominus Moysi, ita fecerunt filii Israël, et diviserunt terram.  

** Joshua 14:6

Accesserunt itaque filii Juda ad Josue in Galgala, locutusque est ad eum Caleb filius Jephone Cenezæus : Nosti quid locutus sit Dominus ad Moysen hominem Dei de me et te in Cadesbarne.

** Joshua 14:7

Quadraginta annorum eram quando misit me Moyses famulus Domini de Cadesbarne, ut considerarem terram, nuntiavique ei quod mihi verum videbatur.

** Joshua 14:8

Fratres autem mei, qui ascenderant mecum, dissolverunt cor populi : et nihilominus ego secutus sum Dominum Deum meum.

** Joshua 14:9

Juravitque Moyses in die illo, dicens : Terra, quam calcavit pes tuus, erit possessio tua, et filiorum tuorum in æternum : quia secutus es Dominum Deum meum.

** Joshua 14:10

Concessit ergo Dominus vitam mihi, sicut pollicitus est, usque in præsentem diem. Quadraginta et quinque anni sunt, ex quo locutus est Dominus verbum istud ad Moysen, quando ambulabat Israël per solitudinem : hodie octoginta quinque annorum sum,

** Joshua 14:11

sic valens ut eo valebam tempore quando ad explorandum missus sum : illius in me temporis fortitudo usque hodie perseverat, tam ad bellandum quam ad gradiendum.

** Joshua 14:12

Da ergo mihi montem istum, quem pollicitus est Dominus, te quoque audiente, in quo Enacim sunt, et urbes magnæ atque munitæ : si forte sit Dominus mecum, et potuero delere eos, sicut promisit mihi.

** Joshua 14:13

Benedixitque ei Josue, et tradidit ei Hebron in possessionem :

** Joshua 14:14

atque ex eo fuit Hebron Caleb filio Jephone Cenezæo usque in præsentem diem, quia secutus est Dominum Deum Israël.

** Joshua 14:15

Nomen Hebron ante vocabatur Cariath Arbe : Adam maximus ibi inter Enacim situs est : et terra cessavit a præliis.   

* Joshua 15

** Joshua 15:1

Igitur sors filiorum Judæ per cognationes suas ista fuit : a termino Edom, desertum Sin, contra meridiem, et usque ad extremam partem australis plagæ.

** Joshua 15:2

Initium ejus a summitate maris salsissimi, et a lingua ejus, quæ respicit meridiem.

** Joshua 15:3

Egrediturque contra ascensum Scorpionis, et pertransit in Sina : ascenditque in Cadesbarne, et pervenit in Esron, ascendens ad Addar, et circuiens Carcaa,

** Joshua 15:4

atque inde pertransiens in Asemona, et perveniens ad torrentem Ægypti : eruntque termini ejus mare magnum. Hic erit finis meridianæ plagæ.

** Joshua 15:5

Ab oriente vero erit initium, mare salsissimum usque ad extrema Jordanis : et ea quæ respiciunt ad aquilonem, a lingua maris usque ad eumdem Jordanis fluvium.

** Joshua 15:6

Ascenditque terminus in Beth Hagla, et transit ab aquilone in Beth Araba, ascendens ad lapidem Boën filii Ruben :

** Joshua 15:7

et tendens usque ad terminos Debera de valle Achor, contra aquilonem respiciens Galgala, quæ est ex adverso ascensionis Adommim, ab australi parte torrentis : transitque aquas, quæ vocantur fons solis : et erunt exitus ejus ad fontem Rogel.

** Joshua 15:8

Ascenditque per convallem filii Ennom ex latere Jebusæi ad meridiem, hæc est Jerusalem : et inde se erigens ad verticem montis, qui est contra Geennom ad occidentem in summitate vallis Raphaim contra aquilonem :

** Joshua 15:9

pertransitque a vertice montis usque ad fontem aquæ Nephtoa : et pervenit usque ad vicos montis Ephron : inclinaturque in Baala, quæ est Cariathiarim, id est, urbs silvarum.

** Joshua 15:10

Et circuit de Baala contra occidentem, usque ad montem Seir : transitque juxta latus montis Jarim ad aquilonem in Cheslon : et descendit in Bethsames, transitque in Thamna.

** Joshua 15:11

Et pervenit contra aquilonem partis Accaron ex latere : inclinaturque Sechrona, et transit montem Baala : pervenitque in Jebneel, et magni maris contra occidentem fine concluditur.

** Joshua 15:12

Hi sunt termini filiorum Juda per circuitum in cognationibus suis.  

** Joshua 15:13

Caleb vero filio Jephone dedit partem in medio filiorum Juda, sicut præceperat ei Dominus : Cariath Arbe patris Enac, ipsa est Hebron.

** Joshua 15:14

Delevitque ex ea Caleb tres filios Enac, Sesai et Ahiman et Tholmai de stirpe Enac.

** Joshua 15:15

Atque inde conscendens venit ad habitatores Dabir, quæ prius vocabatur Cariath Sepher, id est, civitas litterarum.

** Joshua 15:16

Dixitque Caleb : Qui percusserit Cariath Sepher, et ceperit eam, dabo ei Axam filiam meam uxorem.

** Joshua 15:17

Cepitque eam Othoniel filius Cenez frater Caleb junior : deditque ei Axam filiam suam uxorem.

** Joshua 15:18

Quæ, cum pergerent simul, suasa est a viro suo ut peteret a patre suo agrum. Suspiravitque ut sedebat in asino : cui Caleb : Quid habes ? inquit.

** Joshua 15:19

At illa respondit : Da mihi benedictionem : terram australem et arentem dedisti mihi ; junge et irriguam. Dedit itaque ei Caleb irriguum superius et inferius.  

** Joshua 15:20

Hæc est possessio tribus filiorum Juda per cognationes suas.

** Joshua 15:21

Erantque civitates ab extremis partibus filiorum Juda juxta terminos Edom a meridie : Cabseel et Eder et Jagur,

** Joshua 15:22

et Cyna et Dimona et Adada,

** Joshua 15:23

et Cades et Asor et Jethnam,

** Joshua 15:24

Ziph et Telem et Baloth,

** Joshua 15:25

Asor nova et Carioth, Hesron, hæc est Asor ;

** Joshua 15:26

Amam, Sama, et Molada,

** Joshua 15:27

et Asergadda et Hassemon et Bethphelet,

** Joshua 15:28

et Hasersual et Bersabee et Baziothia,

** Joshua 15:29

et Baala et Jim et Esem,

** Joshua 15:30

et Eltholad et Cesil et Harma,

** Joshua 15:31

et Siceleg et Medemena et Sensenna,

** Joshua 15:32

Lebaoth et Selim et Aën et Remon. Omnes civitates viginti novem, et villæ earum.

** Joshua 15:33

In campestribus vero : Estaol et Sarea et Asena,

** Joshua 15:34

et Zanoë et Ængannim et Taphua et Enaim,

** Joshua 15:35

et Jerimoth et Adullam, Socho et Azeca,

** Joshua 15:36

et Saraim et Adithaim et Gedera et Gederothaim : urbes quatuordecim, et villæ earum.

** Joshua 15:37

Sanan et Hadassa et Magdalgad,

** Joshua 15:38

Delean et Masepha et Jecthel,

** Joshua 15:39

Lachis et Bascath et Eglon,

** Joshua 15:40

Chebbon et Leheman et Cethlis,

** Joshua 15:41

et Gideroth et Bethdagon et Naama et Maceda : civitates sedecim, et villæ earum.

** Joshua 15:42

Labana et Ether et Asan,

** Joshua 15:43

Jephtha et Esna et Nesib,

** Joshua 15:44

et Ceila et Achzib et Maresa : civitates novem, et villæ earum.

** Joshua 15:45

Accaron cum vicis et villulis suis.

** Joshua 15:46

Ab Accaron usque ad mare : omnia quæ vergunt ad Azotum et viculos ejus.

** Joshua 15:47

Azotus cum vicis et villulis suis. Gaza cum vicis et villulis suis, usque ad torrentem Ægypti, et mare magnum terminus ejus.

** Joshua 15:48

Et in monte : Samir et Jether et Socoth

** Joshua 15:49

et Danna et Cariathsenna, hæc est Dabir :

** Joshua 15:50

Anab et Istemo et Anim,

** Joshua 15:51

Gosen et Olon et Gilo : civitates undecim et villæ earum.

** Joshua 15:52

Arab et Ruma et Esaan,

** Joshua 15:53

et Janum et Beththaphua et Apheca,

** Joshua 15:54

Athmatha, et Cariath Arbe, hæc est Hebron, et Sior : civitates novem, et villæ earum.

** Joshua 15:55

Maon et Carmel et Ziph et Jota,

** Joshua 15:56

Jezraël et Jucadam et Zanoë,

** Joshua 15:57

Accain, Gabaa et Thamna : civitates decem et villæ earum.

** Joshua 15:58

Halhul, et Besur, et Gedor,

** Joshua 15:59

Mareth, et Bethanoth, et Eltecon : civitates sex et villæ earum.

** Joshua 15:60

Cariathbaal, hæc est Cariathiarim urbs silvarum, et Arebba : civitates duæ, et villæ earum.

** Joshua 15:61

In deserto Betharaba, Meddin, et Sachacha,

** Joshua 15:62

et Nebsan, et civitas salis, et Engaddi : civitates sex, et villæ earum.

** Joshua 15:63

Jebusæum autem habitatorem Jerusalem non potuerunt filii Juda delere : habitavitque Jebusæus cum filiis Juda in Jerusalem usque in præsentem diem.   

* Joshua 16

** Joshua 16:1

Cecidit quoque sors filiorum Joseph ab Jordane contra Jericho et aquas ejus ab oriente : solitudo quæ ascendit de Jericho ad montem Bethel :

** Joshua 16:2

et egreditur de Bethel Luza : transitque terminum Archi, Ataroth :

** Joshua 16:3

et descendit ad occidentem juxta terminum Jephleti, usque ad terminos Beth-horon inferioris, et Gazer : finiunturque regiones ejus mari magno :

** Joshua 16:4

possederuntque filii Joseph, Manasses et Ephraim.  

** Joshua 16:5

Et factus est terminus filiorum Ephraim per cognationes suas : et possessio eorum contra orientem Ataroth Addar usque Beth-horon superiorem.

** Joshua 16:6

Egrediunturque confinia in mare : Machmethath vero aquilonem respicit, et circuit terminos contra orientem in Thanathselo : et pertransit ab oriente Janoë.

** Joshua 16:7

Descenditque de Janoë in Ataroth et Naaratha : et pervenit in Jericho, egrediturque ad Jordanem.

** Joshua 16:8

De Taphua pertransit contra mare in vallem arundineti, suntque egressus ejus in mare salsissimum. Hæc est possessio tribus filiorum Ephraim per familias suas.

** Joshua 16:9

Urbesque separatæ sunt filiis Ephraim in medio possessionis filiorum Manasse, et villæ earum.

** Joshua 16:10

Et non interfecerunt filii Ephraim Chananæum, qui habitabat in Gazer : habitavitque Chananæus in medio Ephraim usque in diem hanc tributarius.   

* Joshua 17

** Joshua 17:1

Cecidit autem sors tribui Manasse (ipse enim est primogenitus Joseph) : Machir primogenito Manasse patri Galaad, qui fuit vir pugnator, habuitque possessionem Galaad et Basan :

** Joshua 17:2

et reliquis filiorum Manasse juxta familias suas, filiis Abiezer, et filiis Helec, et filiis Esriel, et filiis Sechem, et filiis Hepher, et filiis Semida. Isti sunt filii Manasse filii Joseph, mares, per cognationes suas.  

** Joshua 17:3

Salphaad vero filio Hepher filii Galaad filii Machir filii Manasse non erant filii, sed solæ filiæ : quarum ista sunt nomina : Maala et Noa et Hegla et Melcha et Thersa.

** Joshua 17:4

Veneruntque in conspectu Eleazari sacerdotis, et Josue filii Nun, et principum, dicentes : Dominus præcepit per manum Moysi, ut daretur nobis possessio in medio fratrum nostrorum. Deditque eis juxta imperium Domini possessionem in medio fratrum patris earum.

** Joshua 17:5

Et ceciderunt funiculi Manasse, decem, absque terra Galaad et Basan trans Jordanem.

** Joshua 17:6

Filiæ enim Manasse possederunt hæreditatem in medio filiorum ejus. Terra autem Galaad cecidit in sortem filiorum Manasse qui reliqui erant.

** Joshua 17:7

Fuitque terminus Manasse ab Aser, Machmethath quæ respicit Sichem : et egreditur ad dexteram juxta habitatores fontis Taphuæ.

** Joshua 17:8

Etenim in sorte Manasse ceciderat terra Taphuæ, quæ est juxta terminos Manasse filiorum Ephraim.

** Joshua 17:9

Descenditque terminus vallis arundineti in meridiem torrentis civitatum Ephraim, quæ in medio sunt urbium Manasse : terminus Manasse ab aquilone torrentis, et exitus ejus pergit ad mare :

** Joshua 17:10

ita ut possessio Ephraim sit ab austro, et ab aquilone Manasse, et utramque claudat mare, et conjungantur sibi in tribu Aser ab aquilone, et in tribu Issachar ab oriente.

** Joshua 17:11

Fuitque hæreditas Manasse in Issachar et in Aser, Bethsan et viculi ejus, et Jeblaam cum viculis suis, et habitatores Dor cum oppidis suis, habitatores quoque Endor cum viculis suis : similiterque habitatores Thenac cum viculis suis, et habitatores Mageddo cum viculis suis, et tertia pars urbis Nopheth.

** Joshua 17:12

Nec potuerunt filii Manasse has civitates subvertere, sed cœpit Chananæus habitare in terra sua.

** Joshua 17:13

Postquam autem convaluerunt filii Israël, subjecerunt Chananæos, et fecerunt sibi tributarios, nec interfecerunt eos.  

** Joshua 17:14

Locutique sunt filii Joseph ad Josue, et dixerunt : Quare dedisti mihi possessionem sortis et funiculi unius, cum sim tantæ multitudinis, et benedixerit mihi Dominus ?

** Joshua 17:15

Ad quos Josue ait : Si populus multus es, ascende in silvam, et succide tibi spatia in terra Pherezæi et Raphaim : quia angusta est tibi possessio montis Ephraim.

** Joshua 17:16

Cui responderunt filii Joseph : Non poterimus ad montana conscendere, cum ferreis curribus utantur Chananæi, qui habitant in terra campestri, in qua sitæ sunt Bethsan cum viculis suis, et Jezraël mediam possidens vallem.

** Joshua 17:17

Dixitque Josue ad domum Joseph, Ephraim et Manasse : Populus multus es, et magnæ fortitudinis : non habebis sortem unam,

** Joshua 17:18

sed transibis ad montem, et succides tibi, atque purgabis ad habitandum spatia : et poteris ultra procedere cum subverteris Chananæum, quem dicis ferreos habere currus, et esse fortissimum.   

* Joshua 18

** Joshua 18:1

Congregatique sunt omnes filii Israël in Silo, ibique fixerunt tabernaculum testimonii, et fuit eis terra subjecta.

** Joshua 18:2

Remanserant autem filiorum Israël septem tribus, quæ necdum acceperant possessiones suas.

** Joshua 18:3

Ad quos Josue ait : Usquequo marcetis ignavia, et non intratis ad possidendam terram, quam Dominus Deus patrum vestrorum dedit vobis ?

** Joshua 18:4

Eligite de singulis tribubus ternos viros, ut mittam eos, et pergant atque circumeant terram, et describant eam juxta numerum uniuscujusque multitudinis : referantque ad me quod descripserint.

** Joshua 18:5

Dividite vobis terram in septem partes : Judas sit in terminis suis ab australi plaga, et domus Joseph ab aquilone.

** Joshua 18:6

Mediam inter hos terram in septem partes describite : et huc venietis ad me, ut coram Domino Deo vestro mittam vobis hic sortem :

** Joshua 18:7

quia non est inter vos pars Levitarum, sed sacerdotium Domini est eorum hæreditas. Gad autem et Ruben, et dimidia tribus Manasse, jam acceperant possessiones suas trans Jordanem ad orientalem plagam, quas dedit eis Moyses famulus Domini.

** Joshua 18:8

Cumque surrexissent viri, ut pergerent ad describendam terram, præcepit eis Josue, dicens : Circuite terram, et describite eam, ac revertimini ad me : ut hic coram Domino, in Silo, mittam vobis sortem.

** Joshua 18:9

Itaque perrexerunt : et lustrantes eam, in septem partes diviserunt, scribentes in volumine. Reversique sunt ad Josue in castra Silo.

** Joshua 18:10

Qui misit sortes coram Domino in Silo, divisitque terram filiis Israël in septem partes.  

** Joshua 18:11

Et ascendit sors prima filiorum Benjamin per familias suas, ut possiderent terram inter filios Juda et filios Joseph.

** Joshua 18:12

Fuitque terminus eorum contra aquilonem a Jordane : pergens juxta latus Jericho septentrionalis plagæ, et inde contra occidentem ad montana conscendens et perveniens ad solitudinem Bethaven,

** Joshua 18:13

atque pertransiens juxta Luzam ad meridiem, ipsa est Bethel : descenditque in Ataroth Addar, in montem qui est ad meridiem Beth-horon inferioris :

** Joshua 18:14

et inclinatur circuiens contra mare ad meridiem montis qui respicit Beth-horon contra Africum : suntque exitus ejus in Cariath-baal, quæ vocatur et Cariathiarim, urbem filiorum Juda. Hæc est plaga contra mare, ad occidentem.

** Joshua 18:15

A meridie autem ex parte Cariathiarim egreditur terminus contra mare, et pervenit usque ad fontem aquarum Nephtoa.

** Joshua 18:16

Descenditque in partem montis, qui respicit vallem filiorum Ennom : et est contra septentrionalem plagam in extrema parte vallis Raphaim. Descenditque in Geennom (id est, vallem Ennom) juxta latus Jebusæi ad austrum : et pervenit ad fontem Rogel,

** Joshua 18:17

transiens ad aquilonem, et egrediens ad Ensemes, id est, fontem solis :

** Joshua 18:18

et pertransit usque ad tumulos, qui sunt e regione ascensus Adommim : descenditque ad Abenboën, id est, lapidem Boën filii Ruben : et pertransit ex latere aquilonis ad campestria : descenditque in planitiem,

** Joshua 18:19

et prætergreditur contra aquilonem Beth Hagla : suntque exitus ejus contra linguam maris salsissimi ab aquilone in fine Jordanis ad australem plagam :

** Joshua 18:20

qui est terminus illius ab oriente. Hæc est possessio filiorum Benjamin per terminos suos in circuitu, et familias suas.  

** Joshua 18:21

Fueruntque civitates ejus, Jericho et Beth Hagla et vallis Casis,

** Joshua 18:22

Beth Araba et Samaraim et Bethel

** Joshua 18:23

et Avim et Aphara et Ophera,

** Joshua 18:24

villa Emona et Ophni et Gabee : civitates duodecim, et villæ earum.

** Joshua 18:25

Gabaon et Rama et Beroth,

** Joshua 18:26

et Mesphe et Caphara, et Amosa

** Joshua 18:27

et Recem, Jarephel et Tharela,

** Joshua 18:28

et Sela, Eleph, et Jebus, quæ est Jerusalem, Gabaath et Cariath : civitates quatuordecim, et villæ earum. Hæc est possessio filiorum Benjamin juxta familias suas.   

* Joshua 19

** Joshua 19:1

Et egressa est sors secunda filiorum Simeon per cognationes suas : fuitque hæreditas

** Joshua 19:2

eorum in medio possessionis filiorum Juda : Bersabee et Sabee et Molada

** Joshua 19:3

et Hasersual, Bala et Asem

** Joshua 19:4

et Eltholad, Bethul et Harma

** Joshua 19:5

et Siceleg et Bethmarchaboth et Hasersusa

** Joshua 19:6

et Bethlebaoth et Sarohen : civitates tredecim, et villæ earum.

** Joshua 19:7

Ain et Remmon et Athar et Asan : civitates quatuor, et villæ earum :

** Joshua 19:8

omnes viculi per circuitum urbium istarum usque ad Baalath Beer Ramath contra australem plagam. Hæc est hæreditas filiorum Simeon juxta cognationes suas,

** Joshua 19:9

in possessione et funiculo filiorum Juda : quia major erat, et idcirco filii Simeon possederunt in medio hæreditatis eorum.  

** Joshua 19:10

Ceciditque sors tertia filiorum Zabulon per cognationes suas : factus est terminus possessionis eorum usque Sarid.

** Joshua 19:11

Ascenditque de mari et Merala, et pervenit in Debbaseth, usque ad torrentem qui est contra Jeconam.

** Joshua 19:12

Et revertitur de Sared contra orientem in fines Ceseleththabor : et egreditur ad Dabereth, ascenditque contra Japhie.

** Joshua 19:13

Et inde pertransit usque ad orientalem plagam Gethepher et Thacasin : et egreditur in Remmon, Amthar et Noa.

** Joshua 19:14

Et circuit ad aquilonem Hanathon : suntque egressus ejus vallis Jephthaël,

** Joshua 19:15

et Cateth et Naalol et Semeron et Jerala et Bethlehem : civitates duodecim, et villæ earum.

** Joshua 19:16

Hæc est hæreditas tribus filiorum Zabulon per cognationes suas, urbes et viculi earum.  

** Joshua 19:17

Issachar egressa est sors quarta per cognationes suas :

** Joshua 19:18

fuitque ejus hæreditas Jezraël et Casaloth et Sunem

** Joshua 19:19

et Hapharaim et Seon, et Anaharath

** Joshua 19:20

et Rabboth et Cesion, Abes,

** Joshua 19:21

et Rameth, et Engannim, et Enhadda et Bethpheses.

** Joshua 19:22

Et pervenit terminus ejus usque Thabor et Sehesima et Bethsames, eruntque exitus ejus Jordanis : civitates sedecim, et villæ earum.

** Joshua 19:23

Hæc est possessio filiorum Issachar per cognationes suas, urbes et viculi earum.  

** Joshua 19:24

Ceciditque sors quinta tribui filiorum Aser per cognationes suas :

** Joshua 19:25

fuitque terminus eorum Halcath et Chali et Beten et Axaph

** Joshua 19:26

et Elmelech et Amaad et Messal : et pervenit usque ad Carmelum maris et Sihor et Labanath,

** Joshua 19:27

ac revertitur contra orientem Bethdagon : et pertransit usque Zabulon et vallem Jephthaël contra aquilonem in Bethemec et Nehiel. Egrediturque ad lævam Cabul,

** Joshua 19:28

et Abran et Rohob et Hamon et Cana, usque ad Sidonem magnam.

** Joshua 19:29

Revertiturque in Horma usque ad civitatem munitissimam Tyrum, et usque Hosa : eruntque exitus ejus in mare de funiculo Achziba :

** Joshua 19:30

et Amma et Aphec et Rohob : civitates viginti duæ, et villæ earum.

** Joshua 19:31

Hæc est possessio filiorum Aser per cognationes suas, urbesque et viculi earum.  

** Joshua 19:32

Filiorum Nephthali sexta sors cecidit per familias suas :

** Joshua 19:33

et cœpit terminus de Heleph et Elon in Saananim, et Adami, quæ est Neceb, et Jebnaël usque Lecum : et egressus eorum usque ad Jordanem :

** Joshua 19:34

revertiturque terminus contra occidentem in Azanotthabor, atque inde egreditur in Hucuca, et pertransit in Zabulon contra meridiem, et in Aser contra occidentem, et in Juda ad Jordanem contra ortum solis :

** Joshua 19:35

civitates munitissimæ, Assedim, Ser, et Emath, et Reccath et Cenereth,

** Joshua 19:36

et Edema et Arama, Asor

** Joshua 19:37

et Cedes et Edrai, Enhasor,

** Joshua 19:38

et Jeron et Magdalel, Horem et Bethanath et Bethsames : civitates decem et novem, et villæ earum.

** Joshua 19:39

Hæc est possessio tribus filiorum Nephthali per cognationes suas, urbes et viculi earum.  

** Joshua 19:40

Tribui filiorum Dan per familias suas egressa est sors septima :

** Joshua 19:41

et fuit terminus possessionis ejus Sara et Esthaol, et Hirsemes, id est, civitas solis.

** Joshua 19:42

Selebin et Ajalon et Jethela,

** Joshua 19:43

Elon et Themna et Acron,

** Joshua 19:44

Elthece, Gebbethon et Balaath,

** Joshua 19:45

et Jud et Bane et Barach et Gethremmon :

** Joshua 19:46

et Mejarcon et Arecon, cum termino qui respicit Joppen,

** Joshua 19:47

et ipso fine concluditur. Ascenderuntque filii Dan, et pugnaverunt contra Lesem, ceperuntque eam : et percusserunt eam in ore gladii, et possederunt, et habitaverunt in ea, vocantes nomen ejus Lesem Dan, ex nomine Dan patris sui.

** Joshua 19:48

Hæc est possessio tribus filiorum Dan, per cognationes suas, urbes et viculi earum.  

** Joshua 19:49

Cumque complesset sorte dividere terram singulis per tribus suas, dederunt filii Israël possessionem Josue filio Nun in medio sui,

** Joshua 19:50

juxta præceptum Domini, urbem quam postulavit Thamnath Saraa in monte Ephraim : et ædificavit civitatem, habitavitque in ea.

** Joshua 19:51

Hæ sunt possessiones, quas sorte diviserunt Eleazar sacerdos, et Josue filius Nun, et principes familiarum ac tribuum filiorum Israël in Silo, coram Domino ad ostium tabernaculi testimonii : partitique sunt terram.   

* Joshua 20

** Joshua 20:1

Et locutus est Dominus ad Josue, dicens : Loquere filiis Israël, et dic eis :

** Joshua 20:2

Separate urbes fugitivorum, de quibus locutus sum ad vos per manum Moysi :

** Joshua 20:3

ut confugiat ad eas quicumque animam percusserit nescius, et possit evadere iram proximi, qui ultor est sanguinis :

** Joshua 20:4

cum ad unam harum confugerit civitatum, stabit ante portam civitatis, et loquetur senioribus urbis illius ea quæ se comprobent innocentem : sicque suscipient eum, et dabunt ei locum ad habitandum.

** Joshua 20:5

Cumque ultor sanguinis eum fuerit persecutus, non tradent in manus ejus : quia ignorans percussit proximum ejus, nec ante biduum triduumve ejus probatur inimicus.

** Joshua 20:6

Et habitabit in civitate illa, donec stet ante judicium, causam reddens facti sui, et moriatur sacerdos magnus, qui fuerit in illo tempore : tunc revertetur homicida, et ingredietur civitatem et domum suam de qua fugerat.

** Joshua 20:7

Decreveruntque Cedes in Galilæa montis Nephthali, et Sichem in monte Ephraim, et Cariatharbe, ipsa est Hebron in monte Juda.

** Joshua 20:8

Et trans Jordanem contra orientalem plagam Jericho, statuerunt Bosor, quæ sita est in campestri solitudine de tribu Ruben, et Ramoth in Galaad de tribu Gad, et Gaulon in Basan de tribu Manasse.

** Joshua 20:9

Hæ civitates constitutæ sunt cunctis filiis Israël, et advenis qui habitabant inter eos, ut fugeret ad eas qui animam nescius percussisset, et non moreretur in manu proximi, effusum sanguinem vindicare cupientis, donec staret ante populum expositurus causam suam.   

* Joshua 21

** Joshua 21:1

Accesseruntque principes familiarum Levi ad Eleazarum sacerdotem, et Josue filium Nun, et ad duces cognationum per singulas tribus filiorum Israël :

** Joshua 21:2

locutique sunt ad eos in Silo terræ Chanaan, atque dixerunt : Dominus præcepit per manum Moysi, ut darentur nobis urbes ad habitandum, et suburbana earum ad alenda jumenta.

** Joshua 21:3

Dederuntque filii Israël de possessionibus suis juxta imperium Domini, civitates et suburbana earum.

** Joshua 21:4

Egressaque est sors in familiam Caath filiorum Aaron sacerdotis, de tribubus Juda, et Simeon, et Benjamin, civitates tredecim :

** Joshua 21:5

et reliquis filiorum Caath, id est Levitis, qui superfuerant, de tribubus Ephraim, et Dan, et dimidia tribu Manasse, civitates decem.

** Joshua 21:6

Porro filii Gerson egressa est sors, ut acciperent de tribubus Issachar et Aser et Nephthali, dimidiaque tribu Manasse in Basan, civitates numero tredecim.

** Joshua 21:7

Et filiis Merari per cognationes suas de tribubus Ruben et Gad et Zabulon urbes duodecim.

** Joshua 21:8

Dederuntque filii Israël Levitis civitates et suburbana earum, sicut præcepit Dominus per manum Moysi, singulis sorte tribuentes.

** Joshua 21:9

De tribubus filiorum Juda et Simeon dedit Josue civitates, quarum ista sunt nomina,

** Joshua 21:10

filiis Aaron per familias Caath Levitici generis (prima enim sors illis egressa est),

** Joshua 21:11

Cariatharbe patris Enac, quæ vocatur Hebron, in monte Juda, et suburbana ejus per circuitum.

** Joshua 21:12

Agros vero et villas ejus dederat Caleb filio Jephone ad possidendum.

** Joshua 21:13

Dedit ergo filiis Aaron sacerdotis Hebron confugii civitatem, ac suburbana ejus : et Lobnam cum suburbanis suis :

** Joshua 21:14

et Jether, et Esthemo,

** Joshua 21:15

et Holon, et Dabir,

** Joshua 21:16

et Ain, et Jeta, et Bethsames, cum suburbanis suis : civitates novem de tribubus, ut dictum est, duabus.

** Joshua 21:17

De tribu autem filiorum Benjamin, Gabaon, et Gabæ,

** Joshua 21:18

et Anathoth et Almon, cum suburbanis suis : civitates quatuor.

** Joshua 21:19

Omnes simul civitates filiorum Aaron sacerdotis, tredecim, cum suburbanis suis.

** Joshua 21:20

Reliquis vero per familias filiorum Caath Levitici generis, hæc est data possessio.

** Joshua 21:21

De tribu Ephraim urbes confugii, Sichem cum suburbanis suis in monte Ephraim, et Gazer

** Joshua 21:22

et Cibsaim et Beth-horon, cum suburbanis suis, civitates quatuor.

** Joshua 21:23

De tribu quoque Dan, Eltheco et Gabathon,

** Joshua 21:24

et Ajalon et Gethremmon, cum suburbanis suis, civitates quatuor.

** Joshua 21:25

Porro de dimidia tribu Manasse, Thanach et Gethremmon, cum suburbanis suis, civitates duæ.

** Joshua 21:26

Omnes civitates decem, et suburbana earum, datæ sunt filiis Caath inferioris gradus.

** Joshua 21:27

Filiis quoque Gerson Levitici generis dedit de dimidia tribu Manasse confugii civitates, Gaulon in Basan, et Bosram, cum suburbanis suis, civitates duas.

** Joshua 21:28

Porro de tribu Issachar, Cesion, et Dabereth,

** Joshua 21:29

et Jaramoth, et Engannim, cum suburbanis suis, civitates quatuor.

** Joshua 21:30

De tribu autem Aser, Masal et Abdon,

** Joshua 21:31

et Helcath, et Rohob, cum suburbanis suis, civitates quatuor.

** Joshua 21:32

De tribu quoque Nephthali civitates confugii, Cedes in Galilæa, et Hammoth Dor, et Carthan, cum suburbanis suis, civitates tres.

** Joshua 21:33

Omnes urbes familiarum Gerson, tredecim, cum suburbanis suis.

** Joshua 21:34

Filiis autem Merari Levitis inferioris gradus per familias suas data est de tribu Zabulon, Jecnam, et Cartha

** Joshua 21:35

et Damna et Naalol, civitates quatuor cum suburbanis suis.

** Joshua 21:36

De tribu Ruben ultra Jordanem contra Jericho civitates refugii, Bosor in solitudine, Misor et Jaser et Jethson et Mephaath, civitates quatuor cum suburbanis suis.

** Joshua 21:37

De tribu Gad civitates confugii, Ramoth in Galaad, et Manaim et Hesebon et Jazer, civitates quatuor cum suburbanis suis.

** Joshua 21:38

Omnes urbes filiorum Merari per familias et cognationes suas, duodecim.

** Joshua 21:39

Itaque civitates universæ Levitarum in medio possessionis filiorum Israël fuerunt quadraginta octo

** Joshua 21:40

cum suburbanis suis, singulæ per familias distributæ.  

** Joshua 21:41

Deditque Dominus Deus Israëli omnem terram, quam traditurum se patribus eorum juraverat : et possederunt illam, atque habitaverunt in ea.

** Joshua 21:42

Dataque est ab eo pax in omnes per circuitum nationes : nullusque eis hostium resistere ausus est, sed cuncti in eorum ditionem redacti sunt.

** Joshua 21:43

Ne unum quidem verbum, quod illis præstiturum se esse promiserat, irritum fuit, sed rebus expleta sunt omnia.   

* Joshua 22

** Joshua 22:1

Eodem tempore vocavit Josue Rubenitas, et Gaditas, et dimidiam tribum Manasse,

** Joshua 22:2

dixitque ad eos : Fecistis omnia quæ præcepit vobis Moyses famulus Domini : mihi quoque in omnibus obedistis,

** Joshua 22:3

nec reliquistis fratres vestros longo tempore, usque in præsentem diem, custodientes imperium Domini Dei vestri.

** Joshua 22:4

Quia igitur dedit Dominus Deus vester fratribus vestris quietem et pacem, sicut pollicitus est : revertimini, et ite in tabernacula vestra, et in terram possessionis, quam tradidit vobis Moyses famulus Domini trans Jordanem :

** Joshua 22:5

ita dumtaxat ut custodiatis attente, et opere compleatis mandatum et legem quam præcepit vobis Moyses famulus Domini, ut diligatis Dominum Deum vestrum, et ambuletis in omnibus viis ejus, et observetis mandata illius, adhæreatisque ei, ac serviatis in omni corde, et in omni anima vestra.

** Joshua 22:6

Benedixitque eis Josue, et dimisit eos. Qui reversi sunt in tabernacula sua.

** Joshua 22:7

Dimidiæ autem tribui Manasse possessionem Moyses dederat in Basan : et idcirco mediæ, quæ superfuit, dedit Josue sortem inter ceteros fratres suos trans Jordanem ad occidentalem plagam. Cumque dimitteret eos in tabernacula sua, et benedixisset eis,

** Joshua 22:8

dixit ad eos : In multa substantia atque divitiis revertimini ad sedes vestras, cum argento et auro, ære ac ferro, et veste multiplici : dividite prædam hostium cum fratribus vestris.  

** Joshua 22:9

Reversique sunt, et abierunt filii Ruben, et filii Gad, et dimidia tribus Manasse, a filiis Israël de Silo, quæ sita est in Chanaan, ut intrarent Galaad terram possessionis suæ, quam obtinuerant juxta imperium Domini in manu Moysi.

** Joshua 22:10

Cumque venissent ad tumulos Jordanis in terram Chanaan, ædificaverunt juxta Jordanem altare infinitæ magnitudinis.

** Joshua 22:11

Quod cum audissent filii Israël, et ad eos certi nuntii detulissent, ædificasse filios Ruben, et Gad, et dimidiæ tribus Manasse, altare in terra Chanaan, super Jordanis tumulos, contra filios Israël :

** Joshua 22:12

convenerunt omnes in Silo, ut ascenderent, et dimicarent contra eos.

** Joshua 22:13

Et interim miserunt ad illos in terram Galaad Phinees filium Eleazari sacerdotis,

** Joshua 22:14

et decem principes cum eo, singulos de singulis tribubus.

** Joshua 22:15

Qui venerunt ad filios Ruben, et Gad, et dimidiæ tribus Manasse in terram Galaad, dixeruntque ad eos :

** Joshua 22:16

Hæc mandat omnis populus Domini : Quæ est ista transgressio ? cur reliquistis Dominum Deum Israël, ædificantes altare sacrilegum, et a cultu illius recedentes ?

** Joshua 22:17

an parum vobis est quod peccastis in Beelphegor, et usque in præsentem diem macula hujus sceleris in nobis permanet, multique de populo corruerunt ?

** Joshua 22:18

Et vos hodie reliquistis Dominum, et cras in universum Israël ira ejus desæviet.

** Joshua 22:19

Quod si putatis immundam esse terram possessionis vestræ, transite ad terram, in qua tabernaculum Domini est, et habitate inter nos : tantum ut a Domino et a nostro consortio non recedatis, ædificato altari præter altare Domini Dei nostri.

** Joshua 22:20

Nonne Achan filius Zare præteriit mandatum Domini, et super omnem populum Israël ira ejus incubuit ? et ille erat unus homo, atque utinam solum periisset in scelere suo.  

** Joshua 22:21

Responderuntque filii Ruben et Gad, et dimidia tribus Manasse, principibus legationis Israël :

** Joshua 22:22

Fortissimus Deus Dominus, fortissimus Deus Dominus, ipse novit, et Israël simul intelliget : si prævaricationis animo hoc altare construximus, non custodiat nos, sed puniat nos in præsenti :

** Joshua 22:23

et si ea mente fecimus ut holocausta, et sacrificium, et pacificas victimas super eo imponeremus, ipse quærat et judicet :

** Joshua 22:24

et non ea magis cogitatione atque tractatu, ut diceremus : Cras dicent filii vestri filiis nostris : Quid vobis et Domino Deo Israël ?

** Joshua 22:25

terminum posuit Dominus inter nos et vos, o filii Ruben, et filii Gad, Jordanem fluvium, et idcirco partem non habetis in Domino : et per hanc occasionem avertent filii vestri filios nostros a timore Domini. Putavimus itaque melius,

** Joshua 22:26

et diximus : Exstruamus nobis altare, non in holocausta, neque ad victimas offerendas,

** Joshua 22:27

sed in testimonium inter nos et vos, et sobolem nostram vestramque progeniem, ut serviamus Domino, et juris nostri sit offerre et holocausta, et victimas, et pacificas hostias : et nequaquam dicant cras filii vestri filiis nostris : Non est vobis pars in Domino.

** Joshua 22:28

Quod si voluerint dicere, respondebunt eis : Ecce altare Domini, quod fecerunt patres nostri, non in holocausta, neque in sacrificium, sed in testimonium nostrum ac vestrum.

** Joshua 22:29

Absit a nobis hoc scelus, ut recedamus a Domino, et ejus vestigia relinquamus, exstructo altari ad holocausta, et sacrificia, et victimas offerendas, præter altare Domini Dei nostri, quod exstructum est ante tabernaculum ejus.  

** Joshua 22:30

Quibus auditis, Phinees sacerdos, et principes legationis Israël, qui erant cum eo, placati sunt : et verba filiorum Ruben, et Gad, et dimidiæ tribus Manasse, libentissime susceperunt.

** Joshua 22:31

Dixitque Phinees filius Eleazari sacerdos ad eos : Nunc scimus quod nobiscum sit Dominus, quoniam alieni estis a prævaricatione hac, et liberastis filios Israël de manu Domini.

** Joshua 22:32

Reversusque est cum principibus a filiis Ruben et Gad de terra Galaad, finium Chanaan, ad filios Israël, et retulit eis.

** Joshua 22:33

Placuitque sermo cunctis audientibus. Et laudaverunt Deum filii Israël, et nequaquam ultra dixerunt, ut ascenderent contra eos, atque pugnarent, et delerent terram possessionis eorum.

** Joshua 22:34

Vocaveruntque filii Ruben, et filii Gad, altare quod exstruxerant, Testimonium nostrum, quod Dominus ipse sit Deus.   

* Joshua 23

** Joshua 23:1

Evoluto autem multo tempore, postquam pacem dederat Dominus Israëli, subjectis in gyro nationibus universis, et Josue jam longævo, et persenilis ætatis,

** Joshua 23:2

vocavit Josue omnem Israëlem, majoresque natu, et principes ac duces, et magistros, dixitque ad eos : Ego senui, et progressioris ætatis sum :

** Joshua 23:3

vosque cernitis omnia, quæ fecerit Dominus Deus vester cunctis per circuitum nationibus, quomodo pro vobis ipse pugnaverit :

** Joshua 23:4

et nunc quia vobis sorte divisit omnem terram, ab orientali parte Jordanis usque ad mare magnum, multæque adhuc supersunt nationes :

** Joshua 23:5

Dominus Deus vester disperdet eas et auferet a facie vestra, et possidebitis terram, sicut vobis pollicitus est.

** Joshua 23:6

Tantum confortamini, et estote solliciti, ut custodiatis cuncta quæ scripta sunt in volumine legis Moysi : et non declinetis ab eis neque ad dexteram neque ad sinistram :

** Joshua 23:7

ne postquam intraveritis ad gentes quæ inter vos futuræ sunt, juretis in nomine deorum earum, et serviatis eis, et adoretis illos :

** Joshua 23:8

sed adhæreatis Domino Deo vestro : quod fecistis usque in diem hanc.

** Joshua 23:9

Et tunc auferet Dominus Deus in conspectu vestro gentes magnas et robustissimas, et nullus vobis resistere poterit.

** Joshua 23:10

Unus e vobis persequetur hostium mille viros : quia Dominus Deus vester pro vobis ipse pugnabit, sicut pollicitus est.

** Joshua 23:11

Hoc tantum diligentissime præcavete : ut diligatis Dominum Deum vestrum.

** Joshua 23:12

Quod si volueritis gentium harum, quæ inter vos habitant, erroribus adhærere, et cum eis miscere connubia, atque amicitias copulare :

** Joshua 23:13

jam nunc scitote quod Dominus Deus vester non eas deleat ante faciem vestram, sed sint vobis in foveam ac laqueum, et offendiculum ex latere vestro, et sudes in oculis vestris, donec vos auferat atque disperdat de terra hac optima, quam tradidit vobis.

** Joshua 23:14

En ego hodie ingredior viam universæ terræ, et toto animo cognoscetis quod de omnibus verbis, quæ se Dominus præstiturum vobis esse pollicitus est, unum non præterierit incassum.

** Joshua 23:15

Sicut ergo implevit opere quod promisit, et prospera cuncta venerunt : sic adducet super vos quidquid malorum comminatus est, donec vos auferat atque disperdat de terra hac optima, quam tradidit vobis,

** Joshua 23:16

eo quod præterieritis pactum Domini Dei vestri, quod pepigit vobiscum, et servieritis diis alienis, et adoraveritis eos : cito atque velociter consurget in vos furor Domini, et auferemini ab hac terra optima, quam tradidit vobis.   

* Joshua 24

** Joshua 24:1

Congregavitque Josue omnes tribus Israël in Sichem, et vocavit majores natu, ac principes, et judices, et magistros : steteruntque in conspectu Domini,

** Joshua 24:2

et ad populum sic locutus est : Hæc dicit Dominus Deus Israël : Trans fluvium habitaverunt patres vestri ab initio, Thare pater Abraham et Nachor : servieruntque diis alienis.

** Joshua 24:3

Tuli ergo patrem vestrum Abraham de Mesopotamiæ finibus, et adduxi eum in terram Chanaan, multiplicavique semen ejus,

** Joshua 24:4

et dedi ei Isaac : illique rursum dedi Jacob et Esau. E quibus, Esau dedi montem Seir ad possidendum : Jacob vero et filii ejus descenderunt in Ægyptum.

** Joshua 24:5

Misique Moysen et Aaron, et percussi Ægyptum multis signis atque portentis.

** Joshua 24:6

Eduxique vos et patres vestros de Ægypto, et venistis ad mare : persecutique sunt Ægyptii patres vestros cum curribus et equitatu, usque ad mare Rubrum.

** Joshua 24:7

Clamaverunt autem ad Dominum filii Israël : qui posuit tenebras inter vos et Ægyptios, et adduxit super eos mare, et operuit eos. Viderunt oculi vestri cuncta quæ in Ægypto fecerim, et habitastis in solitudine multo tempore :

** Joshua 24:8

et introduxi vos in terram Amorrhæi, qui habitabat trans Jordanem. Cumque pugnarent contra vos, tradidi eos in manus vestras, et possedistis terram eorum, atque interfecistis eos.

** Joshua 24:9

Surrexit autem Balac filius Sephor rex Moab, et pugnavit contra Israëlem. Misitque et vocavit Balaam filium Beor, ut malediceret vobis :

** Joshua 24:10

et ego nolui audire eum, sed e contrario per illum benedixi vobis, et liberavi vos de manu ejus.

** Joshua 24:11

Transistisque Jordanem, et venistis ad Jericho. Pugnaveruntque contra vos viri civitatis ejus, Amorrhæus et Pherezæus, et Chananæus, et Hethæus, et Gergezæus, et Hevæus, et Jebusæus : et tradidi illos in manus vestras.

** Joshua 24:12

Misique ante vos crabrones : et ejeci eos de locis suis, duos reges Amorrhæorum, non in gladio nec in arcu tuo.

** Joshua 24:13

Dedique vobis terram, in qua non laborastis, et urbes quas non ædificastis, ut habitaretis in eis : vineas, et oliveta, quæ non plantastis.

** Joshua 24:14

Nunc ergo timete Dominum, et servite ei perfecto corde atque verissimo : et auferte deos quibus servierunt patres vestri in Mesopotamia et in Ægypto, ac servite Domino.

** Joshua 24:15

Sin autem malum vobis videtur ut Domino serviatis, optio vobis datur : eligite hodie quod placet, cui servire potissimum debeatis : utrum diis, quibus servierunt patres vestri in Mesopotamia, an diis Amorrhæorum, in quorum terra habitatis : ego autem et domus mea serviemus Domino.  

** Joshua 24:16

Responditque populus, et ait : Absit a nobis ut relinquamus Dominum, et serviamus diis alienis.

** Joshua 24:17

Dominus Deus noster, ipse eduxit nos et patres nostros de terra Ægypti, de domo servitutis : fecitque videntibus nobis signa ingentia, et custodivit nos in omni via per quam ambulavimus, et in cunctis populis per quos transivimus.

** Joshua 24:18

Et ejecit universas gentes, Amorrhæum habitatorem terræ quam nos intravimus. Serviemus igitur Domino, quia ipse est Deus noster.

** Joshua 24:19

Dixitque Josue ad populum : Non poteritis servire Domino : Deus enim sanctus et fortis æmulator est, nec ignoscet sceleribus vestris atque peccatis.

** Joshua 24:20

Si dimiseritis Dominum, et servieritis diis alienis, convertet se, et affliget vos atque subvertet, postquam vobis præstiterit bona.

** Joshua 24:21

Dixitque populus ad Josue : Nequaquam ita ut loqueris erit, sed Domino serviemus.

** Joshua 24:22

Et Josue ad populum : Testes, inquit, vos estis, quia ipsi elegeritis vobis Dominum ut serviatis ei. Responderuntque : Testes.

** Joshua 24:23

Nunc ergo, ait, auferte deos alienos de medio vestri, et inclinate corda vestra ad Dominum Deum Israël.

** Joshua 24:24

Dixitque populus ad Josue : Domino Deo nostro serviemus, et obedientes erimus præceptis ejus.  

** Joshua 24:25

Percussit ergo Josue in die illo fœdus, et proposuit populo præcepta atque judicia in Sichem.

** Joshua 24:26

Scripsit quoque omnia verba hæc in volumine legis Domini : et tulit lapidem pergrandem, posuitque eum subter quercum, quæ erat in sanctuario Domini :

** Joshua 24:27

et dixit ad omnem populum : En lapis iste erit vobis in testimonium, quod audierit omnia verba Domini, quæ locutus est vobis : ne forte postea negare velitis, et mentiri Domino Deo vestro.

** Joshua 24:28

Dimisitque populum, singulos in possessionem suam.  

** Joshua 24:29

Et post hæc mortuus est Josue filius Nun servus Domini, centum et decem annorum :

** Joshua 24:30

sepelieruntque eum in finibus possessionis suæ in Thamnathsare, quæ est sita in monte Ephraim, a septentrionali parte montis Gaas.

** Joshua 24:31

Servivitque Israël Domino cunctis diebus Josue et seniorum, qui longo vixerunt tempore post Josue, et qui noverunt omnia opera Domini quæ fecerat in Israël.  

** Joshua 24:32

Ossa quoque Joseph, quæ tulerant filii Israël de Ægypto, sepelierunt in Sichem, in parte agri quem emerat Jacob a filiis Hemor patris Sichem, centum novellis ovibus, et fuit in possessionem filiorum Joseph.

** Joshua 24:33

Eleazar quoque filius Aaron mortuus est : et sepelierunt eum in Gabaath Phinees filii ejus, quæ data est ei in monte Ephraim.    

