* Jude 1

** Jude 1:1

Judas Jesu Christi servus, frater autem Jacobi, his qui sunt in Deo Patre dilectis, et Christo Jesu conservatis, et vocatis.

** Jude 1:2

Misericordia vobis, et pax, et caritas adimpleatur.  

** Jude 1:3

Carissimi, omnem sollicitudinem faciens scribendi vobis de communi vestra salute, necesse habui scribere vobis : deprecans supercertari semel traditæ sanctis fidei.

** Jude 1:4

Subintroierunt enim quidam homines (qui olim præscripti sunt in hoc judicium) impii, Dei nostri gratiam transferentes in luxuriam, et solum Dominatorem, et Dominum nostrum Jesum Christum negantes.  

** Jude 1:5

Commonere autem vos volo, scientes semel omnia, quoniam Jesus populum de terra Ægypti salvans, secundo eos, qui non crediderunt, perdidit :

** Jude 1:6

angelos vero, qui non servaverunt suum principatum, sed dereliquerunt suum domicilium, in judicium magni diei, vinculis æternis sub caligine reservavit.

** Jude 1:7

Sicut Sodoma, et Gomorrha, et finitimæ civitates simili modo exfornicatæ, et abeuntes post carnem alteram, factæ sunt exemplum, ignis æterni pœnam sustinentes.

** Jude 1:8

Similiter et hi carnem quidem maculant, dominationem autem spernunt, majestatem autem blasphemant.

** Jude 1:9

Cum Michaël Archangelus cum diabolo disputans altercaretur de Moysi corpore, non est ausus judicium inferre blasphemiæ : sed dixit : Imperet tibi Dominus.

** Jude 1:10

Hi autem quæcumque quidem ignorant, blasphemant : quæcumque autem naturaliter, tamquam muta animalia, norunt, in his corrumpuntur.

** Jude 1:11

Væ illis, quia in via Cain abierunt, et errore Balaam mercede effusi sunt, et in contradictione Core perierunt !  

** Jude 1:12

Hi sunt in epulis suis maculæ, convivantes sine timore, semetipsos pascentes, nubes sine aqua, quæ a ventis circumferentur, arbores autumnales, infructuosæ, bis mortuæ, eradicatæ,

** Jude 1:13

fluctus feri maris, despumantes suas confusiones, sidera errantia : quibus procella tenebrarum servata est in æternum.

** Jude 1:14

Prophetavit autem et de his septimus ab Adam Enoch, dicens : Ecce venit Dominus in sanctis millibus suis

** Jude 1:15

facere judicium contra omnes, et arguere omnes impios de omnibus operibus impietatis eorum, quibus impie egerunt, et de omnibus duris, quæ locuti sunt contra Deum peccatores impii.

** Jude 1:16

Hi sunt murmuratores querulosi, secundum desideria sua ambulantes, et os eorum loquitur superba, mirantes personas quæstus causa.

** Jude 1:17

Vos autem carissimi, memores estote verborum, quæ prædicta sunt ab apostolis Domini nostri Jesu Christi,

** Jude 1:18

qui dicebant vobis, quoniam in novissimo tempore venient illusores, secundum desideria sua ambulantes in impietatibus.

** Jude 1:19

Hi sunt, qui segregant semetipsos, animales, Spiritum non habentes.  

** Jude 1:20

Vos autem carissimi superædificantes vosmetipsos sanctissimæ vestræ fidei, in Spiritu Sancto orantes,

** Jude 1:21

vosmetipsos in dilectione Dei servate, exspectantes misericordiam Domini nostri Jesu Christi in vitam æternam.

** Jude 1:22

Et hos quidem arguite judicatos :

** Jude 1:23

illos vero salvate, de igne rapientes. Aliis autem miseremini in timore : odientes et eam, quæ carnalis est, maculatam tunicam.

** Jude 1:24

Ei autem qui potens est vos conservare sine peccato et constituere ante conspectum gloriæ suæ immaculatos in exsultatione in adventu Domini nostri Jesu Christi,

** Jude 1:25

soli Deo Salvatori nostro, per Jesum Christum Dominum nostrum, gloria et magnificentia, imperium et potestas ante omne sæculum, et nunc, et in omnia sæcula sæculorum. Amen.    

