* Judith 1

** Judith 1:1

Arphaxad itaque, rex Medorum, subjugaverat multas gentes imperio suo, et ipse ædificavit civitatem potentissimam, quam appellavit Ecbatanis,

** Judith 1:2

ex lapidibus quadratis et sectis : fecit muros ejus in altitudinem cubitorum septuaginta, et in latitudinem cubitorum triginta : turres vero ejus posuit in altitudinem cubitorum centum.

** Judith 1:3

Per quadrum vero earum latus utrumque vicenorum pedum spatio tendebatur, posuitque portas ejus in altitudinem turrium :

** Judith 1:4

et gloriabatur quasi potens in potentia exercitus sui, et in gloria quadrigarum suarum.  

** Judith 1:5

Anno igitur duodecimo regni sui, Nabuchodonosor rex Assyriorum, qui regnabat in Ninive civitate magna, pugnavit contra Arphaxad, et obtinuit eum

** Judith 1:6

in campo magno qui appellatur Ragau, circa Euphraten, et Tigrin, et Jadason, in campo Erioch regis Elicorum.

** Judith 1:7

Tunc exaltatum est regnum Nabuchodonosor, et cor ejus elevatum est : et misit ad omnes qui habitabant in Cilicia, et Damasco, et Libano,

** Judith 1:8

et ad gentes quæ sunt in Carmelo et Cedar, et inhabitantes Galilæam in campo magno Esdrelon,

** Judith 1:9

et ad omnes qui erant in Samaria, et trans flumen Jordanem usque ad Jerusalem, et omnem terram Jesse quousque perveniatur ad terminos Æthiopiæ.

** Judith 1:10

Ad hos omnes misit nuntios Nabuchodonosor rex Assyriorum :

** Judith 1:11

qui omnes uno animo contradixerunt, et remiserunt eos vacuos, et sine honore abjecerunt.

** Judith 1:12

Tunc indignatus Nabuchodonosor rex adversus omnem terram illam, juravit per thronum et regnum suum quod defenderet se de omnibus regionibus his.   

* Judith 2

** Judith 2:1

Anno tertiodecimo Nabuchodonosor regis, vigesima et secunda die mensis primi, factum est verbum in domo Nabuchodonosor regis Assyriorum ut defenderet se.

** Judith 2:2

Vocavitque omnes majores natu, omnesque duces et bellatores suos, et habuit cum eis mysterium consilii sui :

** Judith 2:3

dixitque cogitationem suam in eo esse, ut omnem terram suo subjugaret imperio.

** Judith 2:4

Quod dictum cum placuisset omnibus, vocavit Nabuchodonosor rex Holofernem principem militiæ suæ,

** Judith 2:5

et dixit ei : Egredere adversus omne regnum occidentis, et contra eos præcipue, qui contempserunt imperium meum.

** Judith 2:6

Non parcet oculus tuus ulli regno, omnemque urbem munitam subjugabis mihi.

** Judith 2:7

Tunc Holofernes vocavit duces et magistratus virtutis Assyriorum, et dinumeravit viros in expeditionem sicut præcepit ei rex, centum viginti millia peditum pugnatorum, et equitum sagittariorum duodecim millia.

** Judith 2:8

Omnemque expeditionem suam fecit præire in multitudine innumerabilium camelorum, cum his quæ exercitibus sufficerent copiose, boum quoque armenta, gregesque ovium, quorum non erat numerus.

** Judith 2:9

Frumentum ex omni Syria in transitu suo parari constituit.

** Judith 2:10

Aurum vero et argentum de domo regis assumpsit multum nimis.

** Judith 2:11

Et profectus est ipse, et omnis exercitus cum quadrigis, et equitibus, et sagittariis : qui cooperuerunt faciem terræ sicut locustæ.

** Judith 2:12

Cumque pertransisset fines Assyriorum, venit ad magnos montes Ange, qui sunt a sinistro Ciliciæ : ascenditque omnia castella eorum, et obtinuit omnem munitionem.

** Judith 2:13

Effregit autem civitatem opinatissimam Melothi, prædavitque omnes filios Tharsis et filios Ismaël qui erant contra faciem deserti, et ad austrum terræ Cellon.

** Judith 2:14

Et transivit Euphraten, et venit in Mesopotamiam : et fregit omnes civitates excelsas quæ erant ibi, a torrente Mambre usquequo perveniatur ad mare :

** Judith 2:15

et occupavit terminos ejus, a Cilicia usque ad fines Japheth qui sunt ad austrum.

** Judith 2:16

Abduxitque omnes filios Madian, et prædavit omnem locupletationem eorum, omnesque resistentes sibi occidit in ore gladii.

** Judith 2:17

Et post hæc descendit in campos Damasci in diebus messis, et succendit omnia sata, omnesque arbores, et vineas fecit incidi :

** Judith 2:18

et cecidit timor illius super omnes inhabitantes terram.   

* Judith 3

** Judith 3:1

Tunc miserunt legatos suos universarum urbium ac provinciarum reges ac principes, Syriæ scilicet Mesopotamiæ, et Syriæ Sobal, et Libyæ, atque Ciliciæ : qui venientes ad Holofernem, dixerunt :

** Judith 3:2

Desinat indignatio tua circa nos : melius est enim ut viventes serviamus Nabuchodonosor regi magno, et subditi simus tibi, quam morientes cum interitu nostro ipsi servitutis nostræ damna patiamur.

** Judith 3:3

Omnis civitas nostra, omnisque possessio, omnes montes, et colles, et campi, et armenta boum, gregesque ovium, et caprarum, equorumque et camelorum, et universæ facultates nostræ atque familiæ, in conspectu tuo sunt :

** Judith 3:4

sint omnia nostra sub lege tua.

** Judith 3:5

Nos, et filii nostri, servi tui sumus.

** Judith 3:6

Veni nobis pacificus dominus, et utere servitio nostro, sicut placuerit tibi.

** Judith 3:7

Tunc descendit de montibus cum equitibus in virtute magna, et obtinuit omnem civitatem, et omnem inhabitantem terram.

** Judith 3:8

De universis autem urbibus assumpsit sibi auxiliarios viros fortes, et electos ad bellum.

** Judith 3:9

Tantusque metus provinciis illis incubuit, ut universarum urbium habitatores principes et honorati simul cum populis exirent obviam venienti,

** Judith 3:10

excipientes eum cum coronis et lampadibus, ducentes choros in tympanis et tibiis.

** Judith 3:11

Nec ista tamen facientes, ferocitatem ejus pectoris mitigare potuerunt :

** Judith 3:12

nam et civitates eorum destruxit, et lucos eorum excidit.

** Judith 3:13

Præceperat enim illi Nabuchodonosor rex, ut omnes deos terræ exterminaret, videlicet ut ipse solus diceretur deus ab his nationibus quæ potuissent Holofernis potentia subjugari.

** Judith 3:14

Pertransiens autem Syriam Sobal, et omnem Apameam, omnemque Mesopotamiam, venit ad Idumæos in terram Gabaa,

** Judith 3:15

accepitque civitates eorum, et sedit ibi per triginta dies, in quibus diebus adunari præcepit universum exercitum virtutis suæ.   

* Judith 4

** Judith 4:1

Tunc audientes hæc filii Israël qui habitabant in terra Juda, timuerunt valde a facie ejus.

** Judith 4:2

Tremor et horror invasit sensus eorum, ne hoc faceret Jerusalem et templo Domini, quod fecerat ceteris civitatibus et templis earum.

** Judith 4:3

Et miserunt in omnem Samariam per circuitum usque Jericho, et præoccupaverunt omnes vertices montium :

** Judith 4:4

et muris circumdederunt vicos suos, et congregaverunt frumenta in præparationem pugnæ.

** Judith 4:5

Sacerdos etiam Eliachim scripsit ad universos qui erant contra Esdrelon, quæ est contra faciem campi magni juxta Dothain, et universos per quos viæ transitus esse poterat,

** Judith 4:6

ut obtinerent ascensus montium, per quos via esse poterat ad Jerusalem, et illic custodirent ubi angustum iter esse poterat inter montes.

** Judith 4:7

Et fecerunt filii Israël secundum quod constituerat eis sacerdos Domini Eliachim.

** Judith 4:8

Et clamavit omnis populus ad Dominum instantia magna, et humiliaverunt animas suas in jejuniis et orationibus, ipsi et mulieres eorum.

** Judith 4:9

Et induerunt se sacerdotes ciliciis, et infantes prostraverunt contra faciem templi Domini, et altare Domini operuerunt cilicio :

** Judith 4:10

et clamaverunt ad Dominum Deum Israël unanimiter ne darentur in prædam infantes eorum, et uxores eorum in divisionem, et civitates eorum in exterminium, et sancta eorum in pollutionem, et fierent opprobrium gentibus.

** Judith 4:11

Tunc Eliachim sacerdos Domini magnus circuivit omnem Israël, allocutusque est eos,

** Judith 4:12

dicens : Scitote quoniam exaudiet Dominus preces vestras, si manentes permanseritis in jejuniis et orationibus in conspectu Domini.

** Judith 4:13

Memores estote Moysi servi Domini, qui Amalec confidentem in virtute sua, et in potentia sua, et in exercitu suo, et in clypeis suis, et in curribus suis, et in equitibus suis, non ferro pugnando, sed precibus sanctis orando dejecit :

** Judith 4:14

sic erunt universi hostes Israël, si perseveraveritis in hoc opere quod cœpistis.

** Judith 4:15

Ad hanc igitur exhortationem ejus deprecantes Dominum, permanebant in conspectu Domini,

** Judith 4:16

ita ut etiam hi qui offerebant Domino holocausta, præcincti ciliciis offerrent sacrificia Domino, et erat cinis super capita eorum.

** Judith 4:17

Et ex toto corde suo omnes orabant Deum, ut visitaret populum suum Israël.   

* Judith 5

** Judith 5:1

Nuntiatumque est Holoferni principi militiæ Assyriorum, quod filii Israël præpararent se ad resistendum, ac montium itinera conclusissent :

** Judith 5:2

et furore nimio exarsit in iracundia magna, vocavitque omnes principes Moab et duces Ammon,

** Judith 5:3

et dixit eis : Dicite mihi quis sit populus iste, qui montana obsidet : aut quæ, et quales, et quantæ sint civitates eorum : quæ etiam sit virtus eorum, aut quæ sit multitudo eorum, vel quis rex militiæ illorum :

** Judith 5:4

et quare præ omnibus qui habitant in oriente, isti contempserunt nos, et non exierunt obviam nobis ut susciperent nos cum pace ?  

** Judith 5:5

Tunc Achior dux omnium filiorum Ammon respondens, ait : Si digneris audire, domine mi, dicam veritatem in conspectu tuo de populo isto qui in montanis habitat, et non egredietur verbum falsum ex ore meo.

** Judith 5:6

Populus iste ex progenie Chaldæorum est.

** Judith 5:7

Hic primum in Mesopotamia habitavit, quoniam noluerunt sequi deos patrum suorum, qui erant in terra Chaldæorum.

** Judith 5:8

Deserentes itaque cæremonias patrum suorum, quæ in multitudine deorum erant,

** Judith 5:9

unum Deum cæli coluerunt, qui et præcepit eis ut exirent inde et habitarent in Charan. Cumque operuisset omnem terram fames, descenderunt in Ægyptum, illicque per quadringentos annos sic multiplicati sunt, ut dinumerari eorum non posset exercitus.

** Judith 5:10

Cumque gravaret eos rex Ægypti, atque in ædificationibus urbium suarum in luto et latere subjugasset eos, clamaverunt ad Dominum suum, et percussit totam terram Ægypti plagis variis.

** Judith 5:11

Cumque ejecissent eos Ægyptii a se, et cessasset plaga ab eis, et iterum eos vellent capere, et ad suum servitium revocare,

** Judith 5:12

fugientibus his, Deus cæli mare aperuit, ita ut hinc inde aquæ quasi murus solidarentur, et isti pede sicco fundum maris perambulando transirent.

** Judith 5:13

In quo loco dum innumerabilis exercitus Ægyptiorum eos persequeretur, ita aquis coopertus est, ut non remaneret vel unus, qui factum posteris nuntiaret.

** Judith 5:14

Egressi vero mare Rubrum, deserta Sina montis occupaverunt, in quibus numquam homo habitare potuit, vel filius hominis requievit.

** Judith 5:15

Illic fontes amari obdulcati sunt eis ad bibendum, et per annos quadraginta annonam de cælo consecuti sunt.

** Judith 5:16

Ubicumque ingressi sunt sine arcu et sagitta, et absque scuto et gladio, Deus eorum pugnavit pro eis, et vicit.

** Judith 5:17

Et non fuit qui insultaret populo isti, nisi quando recessit a cultu Domini Dei sui.

** Judith 5:18

Quotiescumque autem præter ipsum Deum suum, alterum coluerunt, dati sunt in prædam, et in gladium, et in opprobrium.

** Judith 5:19

Quotiescumque autem pœnituerunt se recessisse a cultura Dei sui, dedit eis Deus cæli virtutem resistendi.

** Judith 5:20

Denique Chananæum regem, et Jebusæum, et Pherezæum, et Hethæum, et Hevæum, et Amorrhæum, et omnes potentes in Hesebon prostraverunt, et terras eorum et civitates eorum ipsi possederunt :

** Judith 5:21

et usque dum non peccarent in conspectu Dei sui, erant cum illis bona : Deus enim illorum odit iniquitatem.

** Judith 5:22

Nam et ante hos annos cum recessissent a via quam dederat illis Deus ut ambularent in ea, exterminati sunt præliis a multis nationibus, et plurimi eorum captivi abducti sunt in terram non suam.

** Judith 5:23

Nuper autem reversi ad Dominum Deum suum, ex dispersione qua dispersi fuerant, adunati sunt, et ascenderunt montana hæc omnia, et iterum possident Jerusalem, ubi sunt sancta eorum.

** Judith 5:24

Nunc ergo mi domine, perquire si est aliqua iniquitas eorum in conspectu Dei eorum : ascendamus ad illos, quoniam tradens tradet illos Deus eorum tibi, et subjugati erunt sub jugo potentiæ tuæ.

** Judith 5:25

Si vero non est offensio populi hujus coram Deo suo, non poterimus resistere illis, quoniam Deus eorum defendet illos : et erimus in opprobrium universæ terræ.  

** Judith 5:26

Et factum est, cum cessasset loqui Achior verba hæc, irati sunt omnes magnates Holofernis, et cogitabant interficere eum, dicentes ad alterutrum :

** Judith 5:27

Quis est iste, qui filios Israël posse dicat resistere regi Nabuchodonosor et exercitibus ejus, homines inermes, et sine virtute, et sine peritia artis pugnæ ?

** Judith 5:28

Ut ergo agnoscat Achior quoniam fallit nos, ascendamus in montana : et cum capti fuerint potentes eorum, tunc cum eisdem gladio transverberabitur :

** Judith 5:29

ut sciat omnis gens quoniam Nabuchodonosor deus terræ est, et præter ipsum alius non est.   

* Judith 6

** Judith 6:1

Factum est autem cum cessassent loqui, indignatus Holofernes vehementer, dixit ad Achior :

** Judith 6:2

Quoniam prophetasti nobis, dicens quod gens Israël defendatur a Deo suo, ut ostendam tibi quoniam non est deus nisi Nabuchodonosor,

** Judith 6:3

cum percusserimus eos omnes, sicut hominem unum, tunc et ipse cum illis Assyriorum gladio interibis, et omnis Israël tecum perditione disperiet :

** Judith 6:4

et probabis quoniam Nabuchodonosor dominus sit universæ terræ : tuncque gladius militiæ meæ transiet per latera tua, et confixus cades inter vulneratos Israël, et non respirabis ultra, donec extermineris cum illis.

** Judith 6:5

Porro autem si prophetiam tuam veram existimas, non concidat vultus tuus : et pallor qui faciem tuam obtinet abscedat a te, si verba mea hæc putas impleri non posse.

** Judith 6:6

Ut autem noveris quia simul cum illis hæc experieris, ecce ex hac hora illorum populo sociaberis, ut, dum dignas mei gladii pœnas exceperint, ipse simul ultioni subjaceas.

** Judith 6:7

Tunc Holofernes præcepit servis suis ut comprehenderent Achior, et perducerent eum in Bethuliam, et traderent eum in manus filiorum Israël.

** Judith 6:8

Et accipientes eum servi Holofernis, profecti sunt per campestria : sed cum appropinquassent ad montana, exierunt contra eos fundibularii.

** Judith 6:9

Illi autem divertentes a latere montis, ligaverunt Achior ad arborem manibus et pedibus, et sic vinctum restibus dimiserunt eum, et reversi sunt ad dominum suum.

** Judith 6:10

Porro filii Israël descendentes de Bethulia, venerunt ad eum : quem solventes, duxerunt ad Bethuliam, atque in medium populi illum statuentes, percunctati sunt quid rerum esset quod illum vinctum Assyrii reliquissent.  

** Judith 6:11

In diebus illis erant illic principes Ozias filius Micha de tribu Simeon, et Charmi, qui et Gothoniel.

** Judith 6:12

In medio itaque seniorum, et in conspectu omnium, Achior dixit omnia quæ locutus ipse fuerat ab Holoferne interrogatus : et qualiter populus Holofernis voluisset propter hoc verbum interficere eum,

** Judith 6:13

et quemadmodum ipse Holofernes iratus jusserit eum Israëlitis hac de causa tradi, ut dum vicerit filios Israël, tunc et ipsum Achior diversis jubeat interire suppliciis, propter hoc quod dixisset : Deus cæli defensor eorum est.

** Judith 6:14

Cumque Achior universa hæc exposuisset, omnis populus cecidit in faciem, adorantes Dominum, et communi lamentatione et fletu unanimes preces suas Domino effuderunt,

** Judith 6:15

dicentes : Domine Deus cæli et terræ, intuere superbiam eorum, et respice ad nostram humilitatem, et faciem sanctorum tuorum attende, et ostende quoniam non derelinquis præsumentes de te : et præsumentes de se, et de sua virtute gloriantes, humilias.

** Judith 6:16

Finito itaque fletu, et per totam diem oratione populorum completa, consolati sunt Achior,

** Judith 6:17

dicentes : Deus patrum nostrorum, cujus tu virtutem prædicasti, ipse tibi hanc dabit vicissitudinem, ut eorum magis tu interitum videas.

** Judith 6:18

Cum vero Dominus Deus noster dederit hanc libertatem servis suis, sit et tecum Deus in medio nostri : ut sicut placuerit tibi, ita cum tuis omnibus converseris nobiscum.

** Judith 6:19

Tunc Ozias, finito consilio, suscepit eum in domum suam, et fecit ei cœnam magnam.

** Judith 6:20

Et vocatis omnibus presbyteris, simul expleto jejunio refecerunt.

** Judith 6:21

Postea vero convocatus est omnis populus, et per totam noctem intra ecclesiam oraverunt, petentes auxilium a Deo Israël.   

* Judith 7

** Judith 7:1

Holofernes autem altera die præcepit exercitibus suis ut ascenderent contra Bethuliam.

** Judith 7:2

Erant autem pedites bellatorum centum viginti millia, et equites viginti duo millia, præter præparationes virorum illorum quos occupaverat captivitas, et abducti fuerant de provinciis et urbibus universæ juventutis.

** Judith 7:3

Omnes paraverunt se pariter ad pugnam contra filios Israël, et venerunt per crepidinem montis usque ad apicem, qui respicit super Dothain, a loco qui dicitur Belma usque ad Chelmon, qui est contra Esdrelon.

** Judith 7:4

Filii autem Israël, ut viderunt multitudinem illorum, prostraverunt se super terram, mittentes cinerem super capita sua, unanimes orantes ut Deus Israël misericordiam suam ostenderet super populum suum.

** Judith 7:5

Et assumentes arma sua bellica, sederunt per loca quæ ad angusti itineris tramitem dirigunt inter montosa, et erant custodientes ea tota die et nocte.  

** Judith 7:6

Porro Holofernes, dum circuit per gyrum, reperit quod fons qui influebat, aquæductum illorum a parte australi extra civitatem dirigeret : et incidi præcepit aquæductum illorum.

** Judith 7:7

Erant tamen non longe a muris fontes, ex quibus furtim videbantur haurire aquam ad refocillandum potius quam ad potandum.

** Judith 7:8

Sed filii Ammon et Moab accesserunt ad Holofernem, dicentes : Filii Israël non in lancea nec in sagitta confidunt, sed montes defendunt illos, et muniunt illos colles in præcipitio constituti.

** Judith 7:9

Ut ergo sine congressione pugnæ possis superare eos, pone custodes fontium, ut non hauriant aquam ex eis, et sine gladio interficies eos, vel certe fatigati tradent civitatem suam, quam putant in montibus positam superari non posse.

** Judith 7:10

Et placuerunt verba hæc coram Holoferne et coram satellitibus ejus, et constituit per gyrum centenarios per singulos fontes.

** Judith 7:11

Cumque ista custodia per dies viginti fuisset expleta, defecerunt cisternæ et collectiones aquarum omnibus habitantibus Bethuliam, ita ut non esset intra civitatem unde satiarentur vel una die, quoniam ad mensuram dabatur populis aqua quotidie.  

** Judith 7:12

Tunc ad Oziam congregati omnes viri feminæque, juvenes et parvuli, omnes simul una voce

** Judith 7:13

dixerunt : Judicet Deus inter nos et te, quoniam fecisti in nos mala, nolens loqui pacifice cum Assyriis, et propter hoc vendidit nos Deus in manibus eorum.

** Judith 7:14

Et ideo non est qui adjuvet, cum prosternamur ante oculos eorum in siti, et perditione magna.

** Judith 7:15

Et nunc congregate universos qui in civitate sunt, ut sponte tradamus nos omnes populo Holofernis.

** Judith 7:16

Melius est enim ut captivi benedicamus Dominum viventes, quam moriamur, et simus opprobrium omni carni, cum viderimus uxores nostras et infantes nostros mori ante oculos nostros.

** Judith 7:17

Contestamur hodie cælum et terram, et Deum patrum nostrorum, qui ulciscitur nos secundum peccata nostra, ut jam tradatis civitatem in manu militiæ Holofernis, et sit finis noster brevis in ore gladii, qui longior efficitur in ariditate sitis.

** Judith 7:18

Et cum hæc dixissent, factus est fletus et ululatus magnus in ecclesia ab omnibus, et per multas horas una voce clamaverunt ad Deum, dicentes :

** Judith 7:19

Peccavimus cum patribus nostris : injuste egimus, iniquitatem fecimus.

** Judith 7:20

Tu, quia pius es, miserere nostri, aut in tuo flagello vindica iniquitates nostras, et noli tradere confitentes te populo qui ignorat te,

** Judith 7:21

ut non dicant inter gentes : Ubi est Deus eorum ?

** Judith 7:22

Et cum fatigati ex his clamoribus et his fletibus lassati siluissent,

** Judith 7:23

exsurgens Ozias infusus lacrimis, dixit : Æquo animo estote, fratres, et hos quinque dies expectemus a Domino misericordiam.

** Judith 7:24

Forsitan enim indignationem suam abscindet, et dabit gloriam nomini suo.

** Judith 7:25

Si autem transactis quinque diebus non venerit adjutorium, faciemus hæc verba quæ locuti estis.   

* Judith 8

** Judith 8:1

Et factum est cum audisset hæc verba Judith vidua, quæ erat filia Merari filii Idox filii Joseph filii Oziæ filii Elai filii Jamnor filii Gedeon filii Raphaim filii Achitob filii Melchiæ filii Enan filii Nathaniæ filii Salathiel filii Simeon filii Ruben,

** Judith 8:2

et vir ejus fuit Manasses, qui mortuus est in diebus messis hordeaceæ :

** Judith 8:3

instabat enim super alligantes manipulos in campo, et venit æstus super caput ejus, et mortuus est in Bethulia civitate sua, et sepultus est illic cum patribus suis.

** Judith 8:4

Erat autem Judith relicta ejus vidua jam annis tribus et mensibus sex.

** Judith 8:5

Et in superioribus domus suæ fecit sibi secretum cubiculum, in quo cum puellis suis clausa morabatur,

** Judith 8:6

et habens super lumbos suos cilicium, jejunabat omnibus diebus vitæ suæ, præter sabbata et neomenias et festa domus Israël.

** Judith 8:7

Erat autem eleganti aspectu nimis, cui vir suus reliquerat divitias multas, et familiam copiosam, ac possessiones armentis boum, et gregibus ovium plenas.

** Judith 8:8

Et erat hæc in omnibus famosissima, quoniam timebat Dominum valde, nec erat qui loqueretur de illa verbum malum.  

** Judith 8:9

Hæc itaque cum audisset quoniam Ozias promisisset quod transacto quinto die traderet civitatem, misit ad presbyteros Chabri et Charmi.

** Judith 8:10

Et venerunt ad illam, et dixit illis : Quod est hoc verbum, in quo consensit Ozias, ut tradat civitatem Assyriis si intra quinque dies non venerit vobis adjutorium ?

** Judith 8:11

et qui estis vos, qui tentatis Dominum ?

** Judith 8:12

non est iste sermo qui misericordiam provocet, sed potius qui iram excitet, et furorem accendat.

** Judith 8:13

Posuistis vos tempus miserationis Domini, et in arbitrium vestrum, diem constituistis ei.

** Judith 8:14

Sed quia patiens Dominus est, in hoc ipso pœniteamus, et indulgentiam ejus fusis lacrimis postulemus :

** Judith 8:15

non enim quasi homo sic Deus comminabitur, neque sicut filius hominis ad iracundiam inflammabitur.

** Judith 8:16

Et ideo humiliemus illi animas nostras, et in spiritu constituti humiliato, servientes illi

** Judith 8:17

dicamus flentes Domino, ut secundum voluntatem suam sic faciat nobiscum misericordiam suam : ut sicut conturbatum est cor nostrum in superbia eorum, ita etiam de nostra humilitate gloriemur :

** Judith 8:18

quoniam non sumus secuti peccata patrum nostrorum, qui dereliquerunt Deum suum, et adoraverunt deos alienos,

** Judith 8:19

pro quo scelere dati sunt in gladium, et in rapinam, et in confusionem inimicis suis : nos autem alterum deum nescimus præter ipsum.

** Judith 8:20

Expectemus humiles consolationem ejus, et exquiret sanguinem nostrum de afflictionibus inimicorum nostrorum, et humiliabit omnes gentes, quæcumque insurgunt contra nos, et faciet illas sine honore Dominus Deus noster.

** Judith 8:21

Et nunc fratres, quoniam vos estis presbyteri in populo Dei, et ex vobis pendet anima illorum, ad eloquium vestrum corda eorum erigite, ut memores sint quia tentati sunt patres nostri, ut probarentur si vere colerent Deum suum.

** Judith 8:22

Memores esse debent quomodo pater noster Abraham tentatus est, et per multas tribulationes probatus, Dei amicus effectus est.

** Judith 8:23

Sic Isaac, sic Jacob, sic Moyses, et omnes qui placuerunt Deo, per multas tribulationes transierunt fideles.

** Judith 8:24

Illi autem qui tentationes non susceperunt cum timore Domini, et impatientiam suam et improperium murmurationis suæ contra Dominum protulerunt,

** Judith 8:25

exterminati sunt ab exterminatore, et a serpentibus perierunt.

** Judith 8:26

Et nos ergo non ulciscamur nos pro his quæ patimur,

** Judith 8:27

sed reputantes peccatis nostris hæc ipsa supplicia minora esse flagella Domini, quibus quasi servi corripimur ad emendationem, et non ad perditionem nostram evenisse credamus.  

** Judith 8:28

Et dixerunt illi Ozias et presbyteri : Omnia quæ locuta es, vera sunt, et non est in sermonibus tuis ulla reprehensio.

** Judith 8:29

Nunc ergo ora pro nobis, quoniam mulier sancta es, et timens Deum.

** Judith 8:30

Et dixit illis Judith : Sicut quod potui loqui, Dei esse cognoscitis,

** Judith 8:31

ita quod facere disposui, probate si ex Deo est, et orate ut firmum faciat Deus consilium meum.

** Judith 8:32

Stabitis vos ad portam nocte ista, et ego exeam cum abra mea : et orate, ut sicut dixistis, in diebus quinque respiciat Dominus populum suum Israël.

** Judith 8:33

Vos autem nolo ut scrutemini actum meum, et usque dum renuntiem vobis, nihil aliud fiat, nisi oratio pro me ad Dominum Deum nostrum.

** Judith 8:34

Et dixit ad eam Ozias princeps Juda : Vade in pace, et Dominus sit tecum in ultionem inimicorum nostrorum. Et revertentes abierunt.   

* Judith 9

** Judith 9:1

Quibus ascendentibus, Judith ingressa est oratorium suum : et induens se cilicio, posuit cinerem super caput suum : et prosternens se Domino, clamabat ad Dominum, dicens :

** Judith 9:2

Domine Deus patris mei Simeon, qui dedisti illi gladium in defensionem alienigenarum, qui violatores extiterunt in coinquinatione sua, et denudaverunt femur virginis in confusionem :

** Judith 9:3

et dedisti mulieres illorum in prædam, et filias illorum in captivitatem : et omnem prædam in divisionem servis tuis, qui zelaverunt zelum tuum : subveni, quæso te, Domine Deus meus, mihi viduæ.

** Judith 9:4

Tu enim fecisti priora, et illa post illa cogitasti : et hoc factum est quod ipse voluisti.

** Judith 9:5

Omnes enim viæ tuæ paratæ sunt, et tua judicia in tua providentia posuisti.

** Judith 9:6

Respice castra Assyriorum nunc, sicut tunc castra Ægyptiorum videre dignatus es, quando post servos tuos armati currebant, confidentes in quadrigis, et in equitatu suo, et in multitudine bellatorum.

** Judith 9:7

Sed aspexisti super castra eorum, et tenebræ fatigaverunt eos.

** Judith 9:8

Tenuit pedes eorum abyssus, et aquæ operuerunt eos.

** Judith 9:9

Sic fiant et isti, Domine, qui confidunt in multitudine sua, et in curribus suis, et in contis, et in scutis, et in sagittis suis, et in lanceis gloriantur,

** Judith 9:10

et nesciunt quia tu ipse es Deus noster, qui conteris bella ab initio, et Dominus nomen est tibi.

** Judith 9:11

Erige brachium tuum sicut ab initio, et allide virtutem illorum in virtute tua : cadat virtus eorum in iracundia tua, qui promittunt se violare sancta tua, et polluere tabernaculum nominis tui, et dejicere gladio suo cornu altaris tui.

** Judith 9:12

Fac, Domine, ut gladio proprio ejus superbia amputetur :

** Judith 9:13

capiatur laqueo oculorum suorum in me, et percuties eum ex labiis caritatis meæ.

** Judith 9:14

Da mihi in animo constantiam ut contemnam illum, et virtutem, ut evertam illum.

** Judith 9:15

Erit enim hoc memoriale nominis tui, cum manus feminæ dejecerit eum.

** Judith 9:16

Non enim in multitudine est virtus tua, Domine, neque in equorum viribus voluntas tua est, nec superbi ab initio placuerunt tibi : sed humilium et mansuetorum semper tibi placuit deprecatio.

** Judith 9:17

Deus cælorum, creator aquarum, et Dominus totius creaturæ, exaudi me miseram deprecantem, et de tua misericordia præsumentem.

** Judith 9:18

Memento, Domine, testamenti tui, et da verbum in ore meo, et in corde meo consilium corrobora, ut domus tua in sanctificatione tua permaneat :

** Judith 9:19

et omnes gentes agnoscant quia tu es Deus, et non est alius præter te.   

* Judith 10

** Judith 10:1

Factum est autem, cum cessasset clamare ad Dominum, surrexit de loco in quo jacuerat prostrata ad Dominum.

** Judith 10:2

Vocavitque abram suam, et descendens in domum suam, abstulit a se cilicium, et exuit se vestimentis viduitatis suæ,

** Judith 10:3

et lavit corpus suum, et unxit se myro optimo, et discriminavit crinem capitis sui, et imposuit mitram super caput suum, et induit se vestimentis jucunditatis suæ, induitque sandalia pedibus suis, assumpsitque dextraliola, et lilia, et inaures, et annulos, et omnibus ornamentis suis ornavit se.

** Judith 10:4

Cui etiam Dominus contulit splendorem : quoniam omnis ista compositio non ex libidine, sed ex virtute pendebat : et ideo Dominus hanc in illam pulchritudinem ampliavit, ut incomparabili decore omnium oculis appareret.

** Judith 10:5

Imposuit itaque abræ suæ ascoperam vini, et vas olei, et polentam, et palathas, et panes, et caseum, et profecta est.

** Judith 10:6

Cumque venissent ad portam civitatis, invenerunt expectantem Oziam et presbyteros civitatis.

** Judith 10:7

Qui cum vidissent eam, stupentes mirati sunt nimis pulchritudinem ejus.

** Judith 10:8

Nihil tamen interrogantes eam, dimiserunt transire, dicentes : Deus patrum nostrorum det tibi gratiam, et omne consilium tui cordis sua virtute corroboret, ut glorietur super te Jerusalem, et sit nomen tuum in numero sanctorum et justorum.

** Judith 10:9

Et dixerunt hi qui illic erant omnes una voce : Fiat, fiat.

** Judith 10:10

Judith vero orans Dominum, transivit per portas, ipsa et abra ejus.  

** Judith 10:11

Factum est autem cum descenderet montem, circa ortum diei, occurrerunt ei exploratores Assyriorum, et tenuerunt eam, dicentes : Unde venis ? aut quo vadis ?

** Judith 10:12

Quæ respondit : Filia sum Hebræorum, ideo ego fugi a facie eorum, quoniam futurum agnovi quod dentur vobis in deprædationem, pro eo quod contemnentes vos, noluerunt ultro tradere seipsos ut invenirent misericordiam in conspectu vestro.

** Judith 10:13

Hac de causa cogitavi mecum, dicens : Vadam ad faciem principis Holofernis, ut indicem illi secreta illorum, et ostendam illi quo aditu possit obtinere eos, ita ut non cadat vir unus de exercitu ejus.

** Judith 10:14

Et cum audissent viri illi verba ejus, considerabant faciem ejus, et erat in oculis eorum stupor, quoniam pulchritudinem ejus mirabantur nimis.

** Judith 10:15

Et dixerunt ad eam : Conservasti animam tuam, eo quod tale reperisti consilium, ut descenderes ad dominum nostrum.

** Judith 10:16

Hoc autem scias, quoniam cum steteris in conspectu ejus, bene tibi faciet, et eris gratissima in corde ejus. Duxeruntque illam ad tabernaculum Holofernis, annuntiantes eam.

** Judith 10:17

Cumque intrasset ante faciem ejus, statim captus est in suis oculis Holofernes.

** Judith 10:18

Dixeruntque ad eum satellites ejus : Quis contemnat populum Hebræorum, qui tam decoras mulieres habent, ut non pro his merito pugnare contra eos debeamus ?  

** Judith 10:19

Videns itaque Judith Holofernem sedentem in conopeo, quod erat ex purpura, et auro, et smaragdo, et lapidibus pretiosis intextum,

** Judith 10:20

et cum in faciem ejus intendisset, adoravit eum, prosternens se super terram. Et elevaverunt eam servi Holofernis, jubente domino suo.   

* Judith 11

** Judith 11:1

Tunc Holofernes dixit ei : Æquo animo esto, et noli pavere in corde tuo : quoniam ego numquam nocui viro qui voluit servire Nabuchodonosor regi :

** Judith 11:2

populus autem tuus, si non contempsisset me, non levassem lanceam meam super eum.

** Judith 11:3

Nunc autem dic mihi, qua ex causa recessisti ab illis, et placuit tibi ut venires ad nos ?

** Judith 11:4

Et dixit illi Judith : Sume verba ancillæ tuæ, quoniam si secutus fueris verba ancillæ tuæ, perfectam rem faciet Dominus tecum.

** Judith 11:5

Vivit enim Nabuchodonosor rex terræ, et vivit virtus ejus, quæ est in te ad correptionem omnium animarum errantium : quoniam non solum homines serviunt illi per te, sed et bestiæ agri obtemperant illi.

** Judith 11:6

Nuntiatur enim animi tui industria universis gentibus, et indicatum est omni sæculo quoniam tu solus bonus et potens es in omni regno ejus : et disciplina tua omnibus provinciis prædicatur.

** Judith 11:7

Nec hoc latet, quod locutus est Achior, nec illud ignoratur, quod ei jusseris evenire.

** Judith 11:8

Constat enim Deum nostrum sic peccatis offensum, ut mandaverit per prophetas suos ad populum quod tradat eum pro peccatis suis.

** Judith 11:9

Et quoniam sciunt se offendisse Deum suum filii Israël, tremor tuus super ipsos est.

** Judith 11:10

Insuper etiam fames invasit eos, et ab ariditate aquæ jam inter mortuos computantur.

** Judith 11:11

Denique hoc ordinant, ut interficient pecora sua, et bibant sanguinem eorum :

** Judith 11:12

et sancta Domini Dei sui, quæ præcepit Deus non contingi, in frumento, vino, et oleo, hæc cogitaverunt impendere, et volunt consumere quæ nec manibus deberent contingere : ergo quoniam hæc faciunt, certum est quod in perditionem dabuntur.

** Judith 11:13

Quod ego ancilla tua cognoscens, fugi ab illis, et misit me Dominus hæc ipsa nuntiare tibi.

** Judith 11:14

Ego enim ancilla tua Deum colo, etiam nunc apud te : et exiet ancilla tua, et orabo Deum,

** Judith 11:15

et dicet mihi quando eis reddat peccatum suum, et veniens nuntiabo tibi, ita ut ego adducam te per mediam Jerusalem, et habebis omnem populum Israël, sicut oves quibus non est pastor, et non latrabit vel unus canis contra te :

** Judith 11:16

quoniam hæc mihi dicta sunt per providentiam Dei,

** Judith 11:17

et quoniam iratus est illis Deus, hæc ipsa missa sum nuntiare tibi.

** Judith 11:18

Placuerunt autem omnia verba hæc coram Holoferne, et coram pueris ejus, et mirabantur sapientiam ejus, et dicebant alter ad alterum :

** Judith 11:19

Non est talis mulier super terram in aspectu, in pulchritudine, et in sensu verborum.

** Judith 11:20

Et dixit ad illam Holofernes : Benefecit Deus, qui misit te ante populum, ut des illum tu in manibus nostris :

** Judith 11:21

et quoniam bona est promissio tua, si fecerit mihi hoc Deus tuus, erit et Deus meus, et tu in domo Nabuchodonosor magna eris, et nomen tuum nominabitur in universa terra.   

* Judith 12

** Judith 12:1

Tunc jussit eam introire ubi repositi erant thesauri ejus, et jussit illic manere eam, et constituit quid daretur illi de convivio suo.

** Judith 12:2

Cui respondit Judith, et dixit : Nunc non potero manducare ex his quæ mihi præcipis tribui, ne veniat super me offensio : ex his autem quæ mihi detuli, manducabo.

** Judith 12:3

Cui Holofernes ait : Si defecerint tibi ista, quæ tecum detulisti, quid faciemus tibi ?

** Judith 12:4

Et dixit Judith : Vivit anima tua, domine meus, quoniam non expendet omnia hæc ancilla tua, donec faciat Deus in manu mea hæc quæ cogitavi. Et induxerunt illam servi ejus in tabernaculum quod præceperat.

** Judith 12:5

Et petiit dum introiret, ut daretur ei copia nocte et ante lucem egrediendi foras ad orationem, et deprecandi Dominum.

** Judith 12:6

Et præcepit cubiculariis suis ut sicut placeret illi, exiret et introiret ad adorandum Deum suum per triduum :

** Judith 12:7

et exibat noctibus in vallem Bethuliæ, et baptizabat se in fonte aquæ.

** Judith 12:8

Et ut ascendebat, orabat Dominum Deum Israël ut dirigeret viam ejus ad liberationem populi sui.

** Judith 12:9

Et introiens, munda manebat in tabernaculo usque dum acciperet escam suam in vespere.

** Judith 12:10

Et factum est, in quarto die Holofernes fecit cœnam servis suis, et dixit ad Vagao eunuchum suum : Vade, et suade Hebræam illam ut sponte consentiat habitare mecum.

** Judith 12:11

Fœdum est enim apud Assyrios, si femina irrideat virum agendo ut immunis ab eo transeat.  

** Judith 12:12

Tunc introivit Vagao ad Judith, et dixit : Non vereatur bona puella introire ad dominum meum, ut honorificetur ante faciem ejus, ut manducet cum eo, et bibat vinum in jucunditate.

** Judith 12:13

Cui Judith respondit : Quæ ego sum, ut contradicam domino meo ?

** Judith 12:14

omne quod erit ante oculos ejus bonum et optimum, faciam. Quidquid autem illi placuerit, hoc mihi erit optimum omnibus diebus vitæ meæ.

** Judith 12:15

Et surrexit, et ornavit se vestimento suo, et ingressa stetit ante faciem ejus.

** Judith 12:16

Cor autem Holofernes concussum est : erat enim ardens in concupiscentia ejus.

** Judith 12:17

Et dixit ad eam Holofernes : Bibe nunc, et accumbe in jucunditate, quoniam invenisti gratiam coram me.

** Judith 12:18

Et dixit Judith : Bibam, domine, quoniam magnificata est anima mea hodie præ omnibus diebus meis.

** Judith 12:19

Et accepit, et manducavit et bibit coram ipso ea quæ paraverat illi ancilla ejus.

** Judith 12:20

Et jucundus factus est Holofernes ad eam, bibitque vinum multum nimis, quantum numquam biberat in vita sua.   

* Judith 13

** Judith 13:1

Ut autem sero factum est, festinaverunt servi illius ad hospitia sua, et conclusit Vagao ostia cubiculi, et abiit.

** Judith 13:2

Erant autem omnes fatigati a vino,

** Judith 13:3

eratque Judith sola in cubiculo.

** Judith 13:4

Porro Holofernes jacebat in lecto, nimia ebrietate sopitus.

** Judith 13:5

Dixitque Judith puellæ suæ ut staret foris ante cubiculum, et observaret.

** Judith 13:6

Stetitque Judith ante lectum, orans cum lacrimis, et labiorum motu in silentio,

** Judith 13:7

dicens : Confirma me, Domine Deus Israël, et respice in hac hora ad opera manuum mearum, ut, sicut promisisti, Jerusalem civitatem tuam erigas : et hoc quod credens per te posse fieri cogitavi, perficiam.

** Judith 13:8

Et cum hæc dixisset, accessit ad columnam quæ erat ad caput lectuli ejus, et pugionem ejus, qui in ea ligatus pendebat, exsolvit.

** Judith 13:9

Cumque evaginasset illum, apprehendit comam capitis ejus, et ait : Confirma me, Domine Deus, in hac hora.

** Judith 13:10

Et percussit bis in cervicem ejus, et abscidit caput ejus, et abstulit conopeum ejus a columnis, et evolvit corpus ejus truncum.

** Judith 13:11

Et post pusillum exivit, et tradidit caput Holofernis ancillæ suæ, et jussit ut mitteret illud in peram suam.

** Judith 13:12

Et exierunt duæ, secundum consuetudinem suam, quasi ad orationem, et transierunt castra, et gyrantes vallem, venerunt ad portam civitatis.

** Judith 13:13

Et dixit Judith a longe custodibus murorum : Aperite portas, quoniam nobiscum est Deus, qui fecit virtutem in Israël.  

** Judith 13:14

Et factum est cum audissent viri vocem ejus, vocaverunt presbyteros civitatis.

** Judith 13:15

Et concurrerunt ad eam omnes, a minimo usque ad maximum : quoniam sperabant eam jam non esse venturam.

** Judith 13:16

Et accendentes luminaria, congyraverunt circa eam universi : illa autem ascendens in eminentiorem locum, jussit fieri silentium. Cumque omnes tacuissent,

** Judith 13:17

dixit Judith : Laudate Dominum Deum nostrum, qui non deseruit sperantes in se,

** Judith 13:18

et in me ancilla sua adimplevit misericordiam suam, quam promisit domui Israël : et interfecit in manu mea hostem populi sui hac nocte.

** Judith 13:19

Et proferens de pera caput Holofernis, ostendit illis, dicens : Ecce caput Holofernis principis militiæ Assyriorum, et ecce conopeum illius, in quo recumbebat in ebrietate sua, ubi per manum feminæ percussit illum Dominus Deus noster.

** Judith 13:20

Vivit autem ipse Dominus, quoniam custodivit me angelus ejus et hinc euntem, et ibi commorantem, et inde huc revertentem, et non permisit me Dominus ancillam suam coinquinari, sed sine pollutione peccati revocavit me vobis gaudentem in victoria sua, in evasione mea, et in liberatione vestra.

** Judith 13:21

Confitemini illi omnes, quoniam bonus, quoniam in sæculum misericordia ejus.

** Judith 13:22

Universi autem adorantes Dominum, dixerunt ad eam : Benedixit te Dominus in virtute sua, quia per te ad nihilum redegit inimicos nostros.

** Judith 13:23

Porro Ozias princeps populi Israël dixit ad eam : Benedicta es tu, filia, a Domino Deo excelso præ omnibus mulieribus super terram.

** Judith 13:24

Benedictus Dominus, qui creavit cælum et terram, qui te direxit in vulnera capitis principis inimicorum nostrorum :

** Judith 13:25

quia hodie nomen tuum ita magnificavit, ut non recedat laus tua de ore hominum qui memores fuerint virtutis Domini in æternum, pro quibus non pepercisti animæ tuæ propter angustias et tribulationem generis tui, sed subvenisti ruinæ ante conspectum Dei nostri.

** Judith 13:26

Et dixit omnis populus : Fiat, fiat.  

** Judith 13:27

Porro Achior vocatus venit, et dixit ei Judith : Deus Israël, cui tu testimonium dedisti quod ulciscatur se de inimicis suis, ipse caput omnium incredulorum incidit hac nocte in manu mea.

** Judith 13:28

Et ut probes quia ita est, ecce caput Holofernis, qui in contemptu superbiæ suæ Deum Israël contempsit, et tibi interitum minabatur, dicens : Cum captus fuerit populus Israël, gladio perforari præcipiam latera tua.

** Judith 13:29

Videns autem Achior caput Holofernis, angustiatus præ pavore cecidit in faciem suam super terram, et æstuavit anima ejus.

** Judith 13:30

Postea vero quam resumpto spiritu recreatus est, procidit ad pedes ejus, et adoravit eam, et dixit :

** Judith 13:31

Benedicta tu a Deo tuo in omni tabernaculo Jacob, quoniam in omni gente quæ audierit nomen tuum, magnificabitur super te Deus Israël.   

* Judith 14

** Judith 14:1

Dixit autem Judith ad omnem populum : Audite me, fratres : suspendite caput hoc super muros nostros :

** Judith 14:2

et erit, cum exierit sol, accipiat unusquisque arma sua, et exite cum impetu, non ut descendatis deorsum, sed quasi impetum facientes.

** Judith 14:3

Tunc exploratores necesse erit ut fugiant ad principem suum excitandum ad pugnam.

** Judith 14:4

Cumque duces eorum cucurrerint ad tabernaculum Holofernis, et invenerint eum truncum in suo sanguine volutatum, decidet super eos timor.

** Judith 14:5

Cumque cognoveritis fugere eos, ite post illos securi, quoniam Dominus conteret eos sub pedibus vestris.

** Judith 14:6

Tunc Achior, videns virtutem quam fecit Deus Israël, relicto gentilitatis ritu, credidit Deo, et circumcidit carnem præputii sui, et appositus est ad populum Israël, et omnis successio generis ejus usque in hodiernum diem.  

** Judith 14:7

Mox autem ut ortus est dies, suspenderunt super muros caput Holofernis, accepitque unusquisque vir arma sua, et egressi sunt cum grandi strepitu et ululatu.

** Judith 14:8

Quod videntes exploratores, ad tabernaculum Holofernis cucurrerunt.

** Judith 14:9

Porro hi qui in tabernaculo erant, venientes, et ante ingressum cubiculi perstrepentes, excitandi gratia, inquietudinem arte moliebantur, ut non ab excitantibus, sed a sonantibus Holofernes evigilaret.

** Judith 14:10

Nullus enim audebat cubiculum virtutis Assyriorum pulsando aut intrando aperire.

** Judith 14:11

Sed cum venissent ejus duces ac tribuni, et universi majores exercitus regis Assyriorum, dixerunt cubiculariis :

** Judith 14:12

Intrate, et excitate illum, quoniam egressi mures de cavernis suis, ausi sunt provocare nos ad prælium.

** Judith 14:13

Tunc ingressus Vagao cubiculum ejus, stetit ante cortinam, et plausum fecit manibus suis : suspicabatur enim illum cum Judith dormire.

** Judith 14:14

Sed cum nullum motum jacentis sensu aurium caperet, accessit proximans ad cortinam, et elevans eam, vidensque cadaver absque capite Holofernis in suo sanguine tabefactum jacere super terram, exclamavit voce magna cum fletu, et scidit vestimenta sua.

** Judith 14:15

Et ingressus tabernaculum Judith, non invenit eam, et exiliit foras ad populum,

** Judith 14:16

et dixit : Una mulier hebræa fecit confusionem in domo regis Nabuchodonosor : ecce enim Holofernes jacet in terra, et caput ejus non est in illo.

** Judith 14:17

Quod cum audissent principes virtutis Assyriorum, sciderunt omnes vestimenta sua, et intolerabilis timor et tremor cecidit super eos, et turbati sunt animi eorum valde.

** Judith 14:18

Et factus est clamor incomparabilis in medio castrorum eorum.   

* Judith 15

** Judith 15:1

Cumque omnis exercitus decollatum Holofernem audisset, fugit mens et consilium ab eis, et solo tremore et metu agitati, fugæ præsidium sumunt,

** Judith 15:2

ita ut nullus loqueretur cum proximo suo, sed inclinato capite, relictis omnibus, evadere festinabant Hebræos, quos armatos super se venire audiebant, fugientes per vias camporum et semitas collium.

** Judith 15:3

Videntes itaque filii Israël fugientes, secuti sunt illos. Descenderuntque clangentes tubis, et ululantes post ipsos.

** Judith 15:4

Et quoniam Assyrii non adunati, in fugam ibant præcipites : filii autem Israël uno agmine persequentes debilitabant omnes quos invenire potuissent.

** Judith 15:5

Misit itaque Ozias nuntios per omnes civitates et regiones Israël.

** Judith 15:6

Omnis itaque regio, omnisque urbs electam juventutem armatam misit post eos, et persecuti sunt eos in ore gladii, quousque pervenirent ad extremitatem finium suorum.

** Judith 15:7

Reliqui autem qui erant in Bethulia, ingressi sunt castra Assyriorum, et prædam quam fugientes Assyrii reliquerant, abstulerunt, et onustati sunt valde.

** Judith 15:8

Hi vero qui victores reversi sunt ad Bethuliam, omnia quæ erant illorum attulerunt secum, ita ut non esset numerus in pecoribus et jumentis et universis mobilibus eorum, ut a minimo usque ad maximum omnes divites fierent de prædationibus eorum.  

** Judith 15:9

Joacim autem summus pontifex de Jerusalem venit in Bethuliam cum universis presbyteris suis ut videret Judith.

** Judith 15:10

Quæ cum exisset ad illum, benedixerunt eam omnes una voce, dicentes : Tu gloria Jerusalem ; tu lætitia Israël ; tu honorificentia populi nostri :

** Judith 15:11

quia fecisti viriliter, et confortatum est cor tuum, eo quod castitatem amaveris, et post virum tuum, alterum nescieris : ideo et manus Domini confortavit te, et ideo eris benedicta in æternum.

** Judith 15:12

Et dixit omnis populus : Fiat, fiat.

** Judith 15:13

Per dies autem triginta, vix collecta sunt spolia Assyriorum a populo Israël.

** Judith 15:14

Porro autem universa quæ Holofernis peculiaria fuisse probata sunt, dederunt Judith in auro, et argento, et vestibus, et gemmis, et omni supellectili : et tradita sunt omnia illi a populo.

** Judith 15:15

Et omnes populi gaudebant cum mulieribus, et virginibus, et juvenibus, in organis et citharis.   

* Judith 16

** Judith 16:1

Tunc cantavit canticum hoc Domino Judith, dicens :  

** Judith 16:2

Incipite Domino in tympanis ;  cantate Domino in cymbalis ;  modulamini illi psalmum novum :  exaltate, et invocate nomen ejus. 

** Judith 16:3

Dominus conterens bella,  Dominus nomen est illi. 

** Judith 16:4

Qui posuit castra sua in medio populi sui,  ut eriperet nos de manu omnium inimicorum nostrorum. 

** Judith 16:5

Venit Assur ex montibus ab aquilone  in multitudine fortitudinis suæ :  cujus multitudo obturavit torrentes,  et equi eorum cooperuerunt valles. 

** Judith 16:6

Dixit se incensurum fines meos,  et juvenes meos occisurum gladio ;  infantes meos dare in prædam,  et virgines in captivitatem. 

** Judith 16:7

Dominus autem omnipotens nocuit eum,  et tradidit eum in manus feminæ, et confodit eum. 

** Judith 16:8

Non enim cecidit potens eorum a juvenibus,  nec filii Titan percusserunt eum,  nec excelsi gigantes opposuerunt se illi :  sed Judith filia Merari in specie faciei suæ dissolvit eum. 

** Judith 16:9

Exuit enim se vestimento viduitatis,  et induit se vestimento lætitiæ  in exultatione filiorum Israël. 

** Judith 16:10

Unxit faciem suam unguento,  et colligavit cincinnos suos mitra ;  accepit stolam novam ad decipiendum illum. 

** Judith 16:11

Sandalia ejus rapuerunt oculos ejus ;  pulchritudo ejus captivam fecit animam ejus :  amputavit pugione cervicem ejus. 

** Judith 16:12

Horruerunt Persæ constantiam ejus,  et Medi audaciam ejus. 

** Judith 16:13

Tunc ululaverunt castra Assyriorum,  quando apparuerunt humiles mei, arescentes in siti. 

** Judith 16:14

Filii puellarum compunxerunt eos,  et sicut pueros fugientes occiderunt eos :  perierunt in prælio a facie Domini Dei mei. 

** Judith 16:15

Hymnum cantemus Domino ;  hymnum novum cantemus Deo nostro. 

** Judith 16:16

Adonai Domine, magnus es tu,  et præclarus in virtute tua :  et quem superare nemo potest. 

** Judith 16:17

Tibi serviat omnis creatura tua,  quia dixisti, et facta sunt ;  misisti spiritum tuum, et creata sunt :  et non est qui resistat voci tuæ. 

** Judith 16:18

Montes a fundamentis movebuntur cum aquis ;  petræ, sicut cera, liquescent ante faciem tuam. 

** Judith 16:19

Qui autem timent te,  magni erunt apud te per omnia. 

** Judith 16:20

Væ genti insurgenti super genus meum :  Dominus enim omnipotens vindicabit in eis ;  in die judicii visitabit illos. 

** Judith 16:21

Dabit enim ignem et vermes in carnes eorum,  ut urantur et sentiant usque in sempiternum.  

** Judith 16:22

Et factum est post hæc, omnis populus post victoriam venit in Jerusalem adorare Dominum : et mox ut purificati sunt, obtulerunt omnes holocausta, et vota, et repromissiones suas.

** Judith 16:23

Porro Judith universa vasa bellica Holofernis, quæ dedit illi populus, et conopeum quod ipsa sustulerat de cubili ipsius, obtulit in anathema oblivionis.

** Judith 16:24

Erat autem populus jucundus secundum faciem sanctorum : et per tres menses gaudium hujus victoriæ celebratum est cum Judith.

** Judith 16:25

Post dies autem illos, unusquisque rediit in domum suam : et Judith magna facta est in Bethulia, et præclarior erat universæ terræ Israël.

** Judith 16:26

Erat enim virtuti castitas adjuncta, ita ut non cognosceret virum omnibus diebus vitæ suæ, ex quo defunctus est Manasses vir ejus.

** Judith 16:27

Erat autem, diebus festis, procedens cum magna gloria.

** Judith 16:28

Mansit autem in domo viri sui annos centum quinque, et dimisit abram suam liberam : et defuncta est ac sepulta cum viro suo in Bethulia.

** Judith 16:29

Luxitque illam omnis populus diebus septem.

** Judith 16:30

In omni autem spatio vitæ ejus non fuit qui perturbaret Israël, et post mortem ejus annis multis.

** Judith 16:31

Dies autem victoriæ hujus festivitatis ab Hebræis in numero sanctorum dierum accipitur, et colitur a Judæis ex illo tempore usque in præsentem diem.    

