* Lamentations 1

** Lamentations 1:1

Quomodo sedet sola  civitas plena populo !  Facta est quasi vidua  domina gentium ;  princeps provinciarum  facta est sub tributo.  

** Lamentations 1:2

Plorans ploravit in nocte,  et lacrimæ ejus in maxillis ejus :  non est qui consoletur eam  ex omnibus caris ejus ;  omnes amici ejus spreverunt eam,  et facti sunt ei inimici.  

** Lamentations 1:3

Migravit Judas propter afflictionem,  et multitudinem servitutis ;  habitavit inter gentes,  nec invenit requiem :  omnes persecutores ejus apprehenderunt eam  inter angustias.  

** Lamentations 1:4

Viæ Sion lugent, eo quod non sint  qui veniant ad solemnitatem :  omnes portæ ejus destructæ,  sacerdotes ejus gementes ;  virgines ejus squalidæ,  et ipsa oppressa amaritudine.  

** Lamentations 1:5

Facti sunt hostes ejus in capite ;  inimici ejus locupletati sunt :  quia Dominus locutus est super eam  propter multitudinem iniquitatum ejus.  Parvuli ejus ducti sunt in captivitatem  ante faciem tribulantis.  

** Lamentations 1:6

Et egressus est a filia Sion  omnis decor ejus ;  facti sunt principes ejus velut arietes  non invenientes pascua,  et abierunt absque fortitudine  ante faciem subsequentis.  

** Lamentations 1:7

Recordata est Jerusalem dierum afflictionis suæ,  et prævaricationis,  omnium desiderabilium suorum,  quæ habuerat a diebus antiquis,  cum caderet populus ejus in manu hostili,  et non esset auxiliator :  viderunt eam hostes,  et deriserunt sabbata ejus.  

** Lamentations 1:8

Peccatum peccavit Jerusalem,  propterea instabilis facta est ;  omnes qui glorificabant eam spreverunt illam,  quia viderunt ignominiam ejus :  ipsa autem gemens  conversa est retrorsum.  

** Lamentations 1:9

Sordes ejus in pedibus ejus,  nec recordata est finis sui ;  deposita est vehementer,  non habens consolatorem.  Vide, Domine, afflictionem meam,  quoniam erectus est inimicus.  

** Lamentations 1:10

Manum suam misit hostis  ad omnia desiderabilia ejus,  quia vidit gentes  ingressas sanctuarium suum,  de quibus præceperas  ne intrarent in ecclesiam tuam.  

** Lamentations 1:11

Omnis populus ejus gemens,  et quærens panem ;  dederunt pretiosa quæque pro cibo  ad refocillandam animam.  Vide, Domine, et considera  quoniam facta sum vilis !  

** Lamentations 1:12

O vos omnes qui transitis per viam,  attendite, et videte  si est dolor sicut dolor meus !  quoniam vindemiavit me,  ut locutus est Dominus,  in die iræ furoris sui.  

** Lamentations 1:13

De excelso misit ignem in ossibus meis,  et erudivit me :  expandit rete pedibus meis,  convertit me retrorsum ;  posuit me desolatam,  tota die mœrore confectam.  

** Lamentations 1:14

Vigilavit jugum iniquitatum mearum ;  in manu ejus convolutæ sunt,  et impositæ collo meo.  Infirmata est virtus mea :  dedit me Dominus in manu  de qua non potero surgere.  

** Lamentations 1:15

Abstulit omnes magnificos meos Dominus  de medio mei ;  vocavit adversum me tempus  ut contereret electos meos.  Torcular calcavit Dominus  virgini filiæ Juda.  

** Lamentations 1:16

Idcirco ego plorans,  et oculus meus deducens aquas,  quia longe factus est a me consolator,  convertens animam meam.  Facti sunt filii mei perditi,  quoniam invaluit inimicus.  

** Lamentations 1:17

Expandit Sion manus suas ;  non est qui consoletur eam.  Mandavit Dominus adversum Jacob  in circuitu ejus hostes ejus ;  facta est Jerusalem  quasi polluta menstruis inter eos.  

** Lamentations 1:18

Justus est Dominus,  quia os ejus ad iracundiam provocavi.  Audite, obsecro, universi populi,  et videte dolorem meum :  virgines meæ et juvenes mei abierunt  in captivitatem.  

** Lamentations 1:19

Vocavi amicos meos,  et ipsi deceperunt me ;  sacerdotes mei et senes mei  in urbe consumpti sunt,  quia quæsierunt cibum sibi  ut refocillarent animam suam.  

** Lamentations 1:20

Vide, Domine, quoniam tribulor :  conturbatus est venter meus,  subversum est cor meum in memetipsa,  quoniam amaritudine plena sum.  Foris interfecit gladius,  et domi mors similis est.  

** Lamentations 1:21

Audierunt quia ingemisco ego,  et non est qui consoletur me ;  omnes inimici mei audierunt malum meum,  lætati sunt quoniam tu fecisti :  adduxisti diem consolationis,  et fient similes mei.  

** Lamentations 1:22

Ingrediatur omne malum eorum coram te :  et vindemia eos, sicut vindemiasti me  propter omnes iniquitates meas :  multi enim gemitus mei,  et cor meum mœrens.  

* Lamentations 2

** Lamentations 2:1

Quomodo obtexit caligine in furore suo  Dominus filiam Sion ;  projecit de cælo in terram  inclytam Israël,  et non est recordatus scabelli pedum suorum  in die furoris sui !  

** Lamentations 2:2

Præcipitavit Dominus, nec pepercit  omnia speciosa Jacob :  destruxit in furore suo  munitiones virginis Juda,  et dejecit in terram ;  polluit regnum et principes ejus.  

** Lamentations 2:3

Confregit in ira furoris sui  omne cornu Israël ;  avertit retrorsum dexteram suam  a facie inimici,  et succendit in Jacob quasi ignem  flammæ devorantis in gyro.  

** Lamentations 2:4

Tetendit arcum suum quasi inimicus,  firmavit dexteram suam quasi hostis,  et occidit omne quod pulchrum erat visu  in tabernaculo filiæ Sion ;  effudit quasi ignem  indignationem suam.  

** Lamentations 2:5

Factus est Dominus velut inimicus,  præcipitavit Israël :  præcipitavit omnia mœnia ejus,  dissipavit munitiones ejus,  et replevit in filia Juda  humiliatum et humiliatam.  

** Lamentations 2:6

Et dissipavit quasi hortum tentorium suum ;  demolitus est tabernaculum suum.  Oblivioni tradidit Dominus in Sion  festivitatem et sabbatum ;  et in opprobrium, et in indignationem furoris sui,  regem et sacerdotem.  

** Lamentations 2:7

Repulit Dominus altare suum ;  maledixit sanctificationi suæ :  tradidit in manu inimici  muros turrium ejus.  Vocem dederunt in domo Domini  sicut in die solemni.  

** Lamentations 2:8

Cogitavit Dominus dissipare  murum filiæ Sion ;  tetendit funiculum suum,  et non avertit manum suam a perditione :  luxitque antemurale,  et murus pariter dissipatus est.  

** Lamentations 2:9

Defixæ sunt in terra portæ ejus,  perdidit et contrivit vectes ejus ;  regem ejus et principes ejus in gentibus :  non est lex,  et prophetæ ejus non invenerunt  visionem a Domino.  

** Lamentations 2:10

Sederunt in terra, conticuerunt  senes filiæ Sion ;  consperserunt cinere capita sua,  accincti sunt ciliciis :  abjecerunt in terram capita sua  virgines Jerusalem.  

** Lamentations 2:11

Defecerunt præ lacrimis oculi mei,  conturbata sunt viscera mea ;  effusum est in terra jecur meum  super contritione filiæ populi mei,  cum deficeret parvulus et lactens  in plateis oppidi.  

** Lamentations 2:12

Matribus suis dixerunt :  Ubi est triticum et vinum ?  cum deficerent quasi vulnerati  in plateis civitatis,  cum exhalarent animas suas  in sinu matrum suarum.  

** Lamentations 2:13

Cui comparabo te, vel cui assimilabo te,  filia Jerusalem ?  cui exæquabo te, et consolabor te,  virgo, filia Sion ?  magna est enim velut mare contritio tua :  quis medebitur tui ?  

** Lamentations 2:14

Prophetæ tui viderunt tibi  falsa et stulta ;  nec aperiebant iniquitatem tuam,  ut te ad pœnitentiam provocarent ;  viderunt autem tibi assumptiones falsas,  et ejectiones.  

** Lamentations 2:15

Plauserunt super te manibus  omnes transeuntes per viam ;  sibilaverunt et moverunt caput suum  super filiam Jerusalem :  Hæccine est urbs, dicentes, perfecti decoris,  gaudium universæ terræ ?  

** Lamentations 2:16

Aperuerunt super te os suum  omnes inimici tui :  sibilaverunt, et fremuerunt dentibus,  et dixerunt : Devorabimus :  en ista est dies quam exspectabamus ;  invenimus, vidimus.  

** Lamentations 2:17

Fecit Dominus quæ cogitavit ;  complevit sermonem suum,  quem præceperat a diebus antiquis :  destruxit, et non pepercit,  et lætificavit super te inimicum,  et exaltavit cornu hostium tuorum.  

** Lamentations 2:18

Clamavit cor eorum ad Dominum  super muros filiæ Sion :  Deduc quasi torrentem lacrimas  per diem et noctem ;  non des requiem tibi,  neque taceat pupilla oculi tui.  

** Lamentations 2:19

Consurge, lauda in nocte,  in principio vigiliarum ;  effunde sicut aquam cor tuum  ante conspectum Domini :  leva ad eum manus tuas  pro anima parvulorum tuorum,  qui defecerunt in fame  in capite omnium compitorum.  

** Lamentations 2:20

Vide, Domine, et considera  quem vindemiaveris ita.  Ergone comedent mulieres fructum suum,  parvulos ad mensuram palmæ ?  si occiditur in sanctuario Domini  sacerdos et propheta ?  

** Lamentations 2:21

Jacuerunt in terra foris  puer et senex ;  virgines meæ et juvenes mei  ceciderunt in gladio :  interfecisti in die furoris tui,  percussisti, nec misertus es.  

** Lamentations 2:22

Vocasti quasi ad diem solemnem,  qui terrerent me de circuitu ;  et non fuit in die furoris Domini qui effugeret,  et relinqueretur :  quos educavi et enutrivi,  inimicus meus consumpsit eos.  

* Lamentations 3

** Lamentations 3:1

Ego vir videns paupertatem meam  in virga indignationis ejus. 

** Lamentations 3:2

Me minavit, et adduxit in tenebras,  et non in lucem. 

** Lamentations 3:3

Tantum in me vertit et convertit  manum suam tota die.  

** Lamentations 3:4

Vetustam fecit pellem meam et carnem meam ;  contrivit ossa mea. 

** Lamentations 3:5

Ædificavit in gyro meo, et circumdedit me  felle et labore. 

** Lamentations 3:6

In tenebrosis collocavit me,  quasi mortuos sempiternos.  

** Lamentations 3:7

Circumædificavit adversum me, ut non egrediar ;  aggravavit compedem meum. 

** Lamentations 3:8

Sed et cum clamavero, et rogavero,  exclusit orationem meam. 

** Lamentations 3:9

Conclusit vias meas lapidibus quadris ;  semitas meas subvertit.  

** Lamentations 3:10

Ursus insidians factus est mihi,  leo in absconditis. 

** Lamentations 3:11

Semitas meas subvertit, et confregit me ;  posuit me desolatam. 

** Lamentations 3:12

Tetendit arcum suum, et posuit me  quasi signum ad sagittam.  

** Lamentations 3:13

Misit in renibus meis  filias pharetræ suæ. 

** Lamentations 3:14

Factus sum in derisum omni populo meo,  canticum eorum tota die. 

** Lamentations 3:15

Replevit me amaritudinibus ;  inebriavit me absinthio.  

** Lamentations 3:16

Et fregit ad numerum dentes meos ;  cibavit me cinere. 

** Lamentations 3:17

Et repulsa est a pace anima mea ;  oblitus sum bonorum. 

** Lamentations 3:18

Et dixi : Periit finis meus,  et spes mea a Domino.  

** Lamentations 3:19

Recordare paupertatis, et transgressionis meæ,  absinthii et fellis. 

** Lamentations 3:20

Memoria memor ero, et tabescet  in me anima mea. 

** Lamentations 3:21

Hæc recolens in corde meo,  ideo sperabo.  

** Lamentations 3:22

Misericordiæ Domini, quia non sumus consumpti ;  quia non defecerunt miserationes ejus. 

** Lamentations 3:23

Novi diluculo,  multa est fides tua. 

** Lamentations 3:24

Pars mea Dominus, dixit anima mea ;  propterea exspectabo eum.  

** Lamentations 3:25

Bonus est Dominus sperantibus in eum,  animæ quærenti illum. 

** Lamentations 3:26

Bonum est præstolari cum silentio  salutare Dei. 

** Lamentations 3:27

Bonum est viro cum portaverit jugum  ab adolescentia sua.  

** Lamentations 3:28

Sedebit solitarius, et tacebit,  quia levavit super se. 

** Lamentations 3:29

Ponet in pulvere os suum,  si forte sit spes. 

** Lamentations 3:30

Dabit percutienti se maxillam :  saturabitur opprobriis.  

** Lamentations 3:31

Quia non repellet  in sempiternum Dominus. 

** Lamentations 3:32

Quia si abjecit, et miserebitur,  secundum multitudinem misericordiarum suarum. 

** Lamentations 3:33

Non enim humiliavit ex corde suo  et abjecit filios hominum.  

** Lamentations 3:34

Ut conteret sub pedibus suis  omnes vinctos terræ. 

** Lamentations 3:35

Ut declinaret judicium viri  in conspectu vultus Altissimi. 

** Lamentations 3:36

Ut perverteret hominem in judicio suo ;  Dominus ignoravit.  

** Lamentations 3:37

Quis est iste qui dixit ut fieret,  Domino non jubente ? 

** Lamentations 3:38

Ex ore Altissimi non egredientur  nec mala nec bona ? 

** Lamentations 3:39

Quid murmuravit homo vivens,  vir pro peccatis suis ?  

** Lamentations 3:40

Scrutemur vias nostras, et quæramus,  et revertamur ad Dominum. 

** Lamentations 3:41

Levemus corda nostra cum manibus  ad Dominum in cælos. 

** Lamentations 3:42

Nos inique egimus, et ad iracundiam provocavimus ;  idcirco tu inexorabilis es.  

** Lamentations 3:43

Operuisti in furore, et percussisti nos ;  occidisti, nec pepercisti. 

** Lamentations 3:44

Opposuisti nubem tibi,  ne transeat oratio. 

** Lamentations 3:45

Eradicationem et abjectionem posuisti me  in medio populorum.  

** Lamentations 3:46

Aperuerunt super nos os suum  omnes inimici. 

** Lamentations 3:47

Formido et laqueus facta est nobis  vaticinatio, et contritio. 

** Lamentations 3:48

Divisiones aquarum deduxit oculus meus,  in contritione filiæ populi mei.  

** Lamentations 3:49

Oculus meus afflictus est, nec tacuit,  eo quod non esset requies. 

** Lamentations 3:50

Donec respiceret et videret  Dominus de cælis. 

** Lamentations 3:51

Oculus meus deprædatus est animam meam  in cunctis filiabus urbis meæ.  

** Lamentations 3:52

Venatione ceperunt me quasi avem  inimici mei gratis. 

** Lamentations 3:53

Lapsa est in lacum vita mea,  et posuerunt lapidem super me. 

** Lamentations 3:54

Inundaverunt aquæ super caput meum ;  dixi : Perii.  

** Lamentations 3:55

Invocavi nomen tuum, Domine,  de lacu novissimo. 

** Lamentations 3:56

Vocem meam audisti ; ne avertas aurem tuam  a singultu meo et clamoribus. 

** Lamentations 3:57

Appropinquasti in die quando invocavi te ;  dixisti : Ne timeas.  

** Lamentations 3:58

Judicasti, Domine, causam animæ meæ,  redemptor vitæ meæ. 

** Lamentations 3:59

Vidisti, Domine, iniquitatem illorum adversum me :  judica judicium meum. 

** Lamentations 3:60

Vidisti omnem furorem,  universas cogitationes eorum adversum me.  

** Lamentations 3:61

Audisti opprobrium eorum, Domine,  omnes cogitationes eorum adversum me. 

** Lamentations 3:62

Labia insurgentium mihi, et meditationes eorum  adversum me tota die. 

** Lamentations 3:63

Sessionem eorum et resurrectionem eorum vide ;  ego sum psalmus eorum.  

** Lamentations 3:64

Redes eis vicem, Domine,  juxta opera manuum suarum. 

** Lamentations 3:65

Dabis eis scutum cordis,  laborem tuum. 

** Lamentations 3:66

Persequeris in furore, et conteres eos  sub cælis, Domine.  

* Lamentations 4

** Lamentations 4:1

Quomodo obscuratum est aurum,  mutatus est color optimus !  dispersi sunt lapides sanctuarii  in capite omnium platearum !  

** Lamentations 4:2

Filii Sion inclyti,  et amicti auro primo :  quomodo reputati sunt in vasa testea,  opus manuum figuli !  

** Lamentations 4:3

Sed et lamiæ nudaverunt mammam,  lactaverunt catulos suos :  filia populi mei crudelis  quasi struthio in deserto.  

** Lamentations 4:4

Adhæsit lingua lactentis  ad palatum ejus in siti ;  parvuli petierunt panem,  et non erat qui frangeret eis.  

** Lamentations 4:5

Qui vescebantur voluptuose,  interierunt in viis ;  qui nutriebantur in croceis,  amplexati sunt stercora.  

** Lamentations 4:6

Et major effecta est iniquitas filiæ populi mei  peccato Sodomorum,  quæ subversa est in momento,  et non ceperunt in ea manus.  

** Lamentations 4:7

Candidiores Nazaræi ejus nive,  nitidiores lacte,  rubicundiores ebore antiquo,  sapphiro pulchriores.  

** Lamentations 4:8

Denigrata est super carbones facies eorum  et non sunt cogniti in plateis ;  adhæsit cutis eorum ossibus :  aruit, et facta est quasi lignum.  

** Lamentations 4:9

Melius fuit occisis gladio  quam interfectis fame,  quoniam isti extabuerunt consumpti  a sterilitate terræ.  

** Lamentations 4:10

Manus mulierum misericordium  coxerunt filios suos ;  facti sunt cibus earum  in contritione filiæ populi mei.  

** Lamentations 4:11

Complevit Dominus furorem suum,  effudit iram indignationis suæ :  et succendit ignem in Sion,  et devoravit fundamenta ejus.  

** Lamentations 4:12

Non crediderunt reges terræ,  et universi habitatores orbis,  quoniam ingrederetur hostis et inimicus  per portas Jerusalem.  

** Lamentations 4:13

Propter peccata prophetarum ejus,  et iniquitates sacerdotum ejus,  qui effuderunt in medio ejus  sanguinem justorum.  

** Lamentations 4:14

Erraverunt cæci in plateis,  polluti sunt in sanguine ;  cumque non possent,  tenuerunt lacinias suas.  

** Lamentations 4:15

Recedite polluti, clamaverunt eis ;  recedite, abite, nolite tangere :  jurgati quippe sunt, et commoti dixerunt inter gentes :  Non addet ultra ut habitet in eis.  

** Lamentations 4:16

Facies Domini divisit eos,  non addet ut respiciat eos ;  facies sacerdotum non erubuerunt,  neque senum miserti sunt.  

** Lamentations 4:17

Cum adhuc subsisteremus, defecerunt oculi nostri  ad auxilium nostrum vanum ;  cum respiceremus attenti ad gentem  quæ salvare non poterat.  

** Lamentations 4:18

Lubricaverunt vestigia nostra  in itinere platearum nostrarum ;  appropinquavit finis noster, completi sunt dies nostri,  quia venit finis noster.  

** Lamentations 4:19

Velociores fuerunt persecutores nostri  aquilis cæli ;  super montes persecuti sunt nos,  in deserto insidiati sunt nobis.  

** Lamentations 4:20

Spiritus oris nostri, christus Dominus,  captus est in peccatis nostris,  cui diximus : In umbra tua  vivemus in gentibus.  

** Lamentations 4:21

Gaude et lætare, filia Edom,  quæ habitas in terra Hus !  ad te quoque perveniet calix : inebriaberis,  atque nudaberis.  

** Lamentations 4:22

Completa est iniquitas tua, filia Sion :  non addet ultra ut transmigret te.  Visitavit iniquitatem tuam, filia Edom ;  discooperuit peccata tua.  

* Lamentations 5

** Lamentations 5:1

Recordare, Domine, quid acciderit nobis ;  intuere et respice opprobrium nostrum. 

** Lamentations 5:2

Hæreditas nostra versa est ad alienos,  domus nostræ ad extraneos. 

** Lamentations 5:3

Pupilli facti sumus absque patre,  matres nostræ quasi viduæ. 

** Lamentations 5:4

Aquam nostram pecunia bibimus ;  ligna nostra pretio comparavimus. 

** Lamentations 5:5

Cervicibus nostris minabamur,  lassis non dabatur requies. 

** Lamentations 5:6

Ægypto dedimus manum et Assyriis,  ut saturaremur pane. 

** Lamentations 5:7

Patres nostri peccaverunt, et non sunt :  et nos iniquitates eorum portavimus. 

** Lamentations 5:8

Servi dominati sunt nostri :  non fuit qui redimeret de manu eorum. 

** Lamentations 5:9

In animabus nostris afferebamus panem nobis,  a facie gladii in deserto. 

** Lamentations 5:10

Pellis nostra quasi clibanus exusta est,  a facie tempestatum famis. 

** Lamentations 5:11

Mulieres in Sion humiliaverunt,  et virgines in civitatibus Juda. 

** Lamentations 5:12

Principes manu suspensi sunt ;  facies senum non erubuerunt. 

** Lamentations 5:13

Adolescentibus impudice abusi sunt,  et pueri in ligno corruerunt. 

** Lamentations 5:14

Senes defecerunt de portis,  juvenes de choro psallentium. 

** Lamentations 5:15

Defecit gaudium cordis nostri ;  versus est in luctum chorus noster. 

** Lamentations 5:16

Cecidit corona capitis nostri :  væ nobis, quia peccavimus ! 

** Lamentations 5:17

Propterea mœstum factum est cor nostrum ;  ideo contenebrati sunt oculi nostri, 

** Lamentations 5:18

propter montem Sion quia disperiit ;  vulpes ambulaverunt in eo. 

** Lamentations 5:19

Tu autem, Domine, in æternum permanebis,  solium tuum in generationem et generationem. 

** Lamentations 5:20

Quare in perpetuum oblivisceris nostri,  derelinques nos in longitudine dierum ? 

** Lamentations 5:21

Converte nos, Domine, ad te, et convertemur ;  innova dies nostros, sicut a principio. 

** Lamentations 5:22

Sed projiciens repulisti nos :  iratus es contra nos vehementer.    

