* Leviticus 1

** Leviticus 1:1

Vocavit autem Moysen, et locutus est ei Dominus de tabernaculo testimonii, dicens :

** Leviticus 1:2

Loquere filiis Israël, et dices ad eos : Homo, qui obtulerit ex vobis hostiam Domino de pecoribus, id est, de bobus et ovibus offerens victimas,

** Leviticus 1:3

si holocaustum fuerit ejus oblatio, ac de armento : masculum immaculatum offeret ad ostium tabernaculi testimonii, ad placandum sibi Dominum :

** Leviticus 1:4

ponetque manum super caput hostiæ, et acceptabilis erit, atque in expiationem ejus proficiens.

** Leviticus 1:5

Immolabitque vitulum coram Domino, et offerent filii Aaron sacerdotes sanguinem ejus, fundentes per altaris circuitum, quod est ante ostium tabernaculi :

** Leviticus 1:6

detractaque pelle hostiæ, artus in frusta concident.

** Leviticus 1:7

Et subjicient in altari ignem, strue lignorum ante composita :

** Leviticus 1:8

et membra quæ sunt cæsa, desuper ordinantes, caput videlicet, et cuncta quæ adhærent jecori,

** Leviticus 1:9

intestinis et pedibus lotis aqua : adolebitque ea sacerdos super altare in holocaustum et suavem odorem Domino.

** Leviticus 1:10

Quod si de pecoribus oblatio est, de ovibus sive de capris holocaustum, masculum absque macula offeret :

** Leviticus 1:11

immolabitque ad latus altaris, quod respicit ad aquilonem, coram Domino : sanguinem vero illius fundent super altare filii Aaron per circuitum :

** Leviticus 1:12

dividentque membra, caput, et omnia quæ adhærent jecori, et ponent super ligna, quibus subjiciendus est ignis :

** Leviticus 1:13

intestina vero et pedes lavabunt aqua. Et oblata omnia adolebit sacerdos super altare in holocaustum et odorem suavissimum Domino.

** Leviticus 1:14

Si autem de avibus, holocausti oblatio fuerit Domino, de turturibus, aut pullis columbæ,

** Leviticus 1:15

offeret eam sacerdos ad altare : et retorto ad collum capite, ac rupto vulneris loco, decurrere faciet sanguinem super crepidinem altaris :

** Leviticus 1:16

vesiculam vero gutturis, et plumas projiciet prope altare ad orientalem plagam, in loco in quo cineres effundi solent,

** Leviticus 1:17

confringetque ascellas ejus, et non secabit, neque ferro dividet eam, et adolebit super altare, lignis igne supposito. Holocaustum est et oblatio suavissimi odoris Domino.   

* Leviticus 2

** Leviticus 2:1

Anima cum obtulerit oblationem sacrificii Domino, simila erit ejus oblatio ; fundetque super eam oleum, et ponet thus,

** Leviticus 2:2

ac deferet ad filios Aaron sacerdotes : quorum unus tollet pugillum plenum similæ et olei, ac totum thus, et ponet memoriale super altare in odorem suavissimum Domino.

** Leviticus 2:3

Quod autem reliquum fuerit de sacrificio, erit Aaron et filiorum ejus, Sanctum sanctorum de oblationibus Domini.

** Leviticus 2:4

Cum autem obtuleris sacrificium coctum in clibano : de simila, panes scilicet absque fermento, conspersos oleo, et lagana azyma oleo lita.

** Leviticus 2:5

Si oblatio tua fuerit de sartagine, similæ conspersæ oleo et absque fermento,

** Leviticus 2:6

divides eam minutatim, et fundes super eam oleum.

** Leviticus 2:7

Sin autem de craticula fuerit sacrificium, æque simila oleo conspergetur :

** Leviticus 2:8

quam offerens Domino, trades manibus sacerdotis.

** Leviticus 2:9

Qui cum obtulerit eam, tollet memoriale de sacrificio, et adolebit super altare in odorem suavitatis Domino :

** Leviticus 2:10

quidquid autem reliquum est, erit Aaron, et filiorum ejus, Sanctum sanctorum de oblationibus Domini.

** Leviticus 2:11

Omnis oblatio quæ offeretur Domino, absque fermento fiet, nec quidquam fermenti ac mellis adolebitur in sacrificio Domino.

** Leviticus 2:12

Primitias tantum eorum offeretis ac munera : super altare vero non imponentur in odorem suavitatis.

** Leviticus 2:13

Quidquid obtuleris sacrificii, sale condies, nec auferes sal fœderis Dei tui de sacrificio tuo : in omni oblatione tua offeres sal.

** Leviticus 2:14

Si autem obtuleris munus primarum frugum tuarum Domino de spicis adhuc virentibus, torrebis igni, et confringes in morem farris, et sic offeres primitias tuas Domino,

** Leviticus 2:15

fundens supra oleum, et thus imponens, quia oblatio Domini est :

** Leviticus 2:16

de qua adolebit sacerdos in memoriam muneris partem farris fracti, et olei, ac totum thus.   

* Leviticus 3

** Leviticus 3:1

Quod si hostia pacificorum fuerit ejus oblatio, et de bobus voluerit offerre, marem sive feminam, immaculata offeret coram Domino.

** Leviticus 3:2

Ponetque manum super caput victimæ suæ, quæ immolabitur in introitu tabernaculi testimonii, fundentque filii Aaron sacerdotes sanguinem per altaris circuitum.

** Leviticus 3:3

Et offerent de hostia pacificorum in oblationem Domino, adipem qui operit vitalia, et quidquid pinguedinis est intrinsecus :

** Leviticus 3:4

duos renes cum adipe quo teguntur ilia, et reticulum jecoris cum renunculis.

** Leviticus 3:5

Adolebuntque ea super altare in holocaustum, lignis igne supposito, in oblationem suavissimi odoris Domino.

** Leviticus 3:6

Si vero de ovibus fuerit ejus oblatio et pacificorum hostia, sive masculum obtulerit, sive feminam, immaculata erunt.

** Leviticus 3:7

Si agnum obtulerit coram Domino,

** Leviticus 3:8

ponet manum suam super caput victimæ suæ : quæ immolabitur in vestibulo tabernaculi testimonii : fundentque filii Aaron sanguinem ejus per circuitum altaris.

** Leviticus 3:9

Et offerent de pacificorum hostia sacrificium Domino : adipem et caudam totam

** Leviticus 3:10

cum renibus, et pinguedinem quæ operit ventrem atque universa vitalia, et utrumque renunculum cum adipe qui est juxta ilia, reticulumque jecoris cum renunculis.

** Leviticus 3:11

Et adolebit ea sacerdos super altare in pabulum ignis et oblationis Domini.

** Leviticus 3:12

Si capra fuerit ejus oblatio, et obtulerit eam Domino,

** Leviticus 3:13

ponet manum suam super caput ejus : immolabitque eam in introitu tabernaculi testimonii, et fundent filii Aaron sanguinem ejus per altaris circuitum.

** Leviticus 3:14

Tollentque ex ea in pastum ignis dominici, adipem qui operit ventrem, et qui tegit universa vitalia :

** Leviticus 3:15

duos renunculos cum reticulo, quod est super eos juxta ilia, et arvinam jecoris cum renunculis :

** Leviticus 3:16

adolebitque ea super altare sacerdos in alimoniam ignis, et suavissimi odoris. Omnis adeps, Domini erit

** Leviticus 3:17

jure perpetuo in generationibus, et cunctis habitaculis vestris : nec sanguinem nec adipem omnino comedetis.   

* Leviticus 4

** Leviticus 4:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 4:2

Loquere filiis Israël : Anima, quæ peccaverit per ignorantiam, et de universis mandatis Domini, quæ præcepit ut non fierent, quippiam fecerit :

** Leviticus 4:3

si sacerdos, qui unctus est, peccaverit, delinquere faciens populum, offeret pro peccato suo vitulum immaculatum Domino :

** Leviticus 4:4

et adducet illum ad ostium tabernaculi testimonii coram Domino, ponetque manum super caput ejus, et immolabit eum Domino.

** Leviticus 4:5

Hauriet quoque de sanguine vituli, inferens illum in tabernaculum testimonii.

** Leviticus 4:6

Cumque intinxerit digitum in sanguine, asperget eo septies coram Domino contra velum sanctuarii.

** Leviticus 4:7

Ponetque de eodem sanguine super cornua altaris thymiamatis gratissimi Domino, quod est in tabernaculo testimonii : omnem autem reliquum sanguinem fundet in basim altaris holocausti in introitu tabernaculi.

** Leviticus 4:8

Et adipem vituli auferet pro peccato, tam eum qui vitalia operit quam omnia quæ intrinsecus sunt :

** Leviticus 4:9

duos renunculos et reticulum quod est super eos juxta ilia, et adipem jecoris cum renunculis,

** Leviticus 4:10

sicut aufertur de vitulo hostiæ pacificorum : et adolebit ea super altare holocausti.

** Leviticus 4:11

Pellem vero et omnes carnes, cum capite et pedibus et intestinis et fimo,

** Leviticus 4:12

et reliquo corpore, efferet extra castra in locum mundum, ubi cineres effundi solent : incendetque ea super lignorum struem, quæ in loco effusorum cinerum cremabuntur.  

** Leviticus 4:13

Quod si omnis turba Israël ignoraverit, et per imperitiam fecerit quod contra mandatum Domini est,

** Leviticus 4:14

et postea intellexerit peccatum suum, offeret pro peccato suo vitulum, adducetque eum ad ostium tabernaculi.

** Leviticus 4:15

Et ponent seniores populi manus super caput ejus coram Domino. Immolatoque vitulo in conspectu Domini,

** Leviticus 4:16

inferet sacerdos, qui unctus est, de sanguine ejus in tabernaculum testimonii,

** Leviticus 4:17

tincto digito aspergens septies contra velum.

** Leviticus 4:18

Ponetque de eodem sanguine in cornibus altaris, quod est coram Domino in tabernaculo testimonii : reliquum autem sanguinem fundet juxta basim altaris holocaustorum, quod est in ostio tabernaculi testimonii.

** Leviticus 4:19

Omnemque ejus adipem tollet, et adolebit super altare :

** Leviticus 4:20

sic faciens et de hoc vitulo quomodo fecit et prius : et rogante pro eis sacerdote, propitius erit eis Dominus.

** Leviticus 4:21

Ipsum autem vitulum efferet extra castra, atque comburet sicut et priorem vitulum : quia est pro peccato multitudinis.  

** Leviticus 4:22

Si peccaverit princeps, et fecerit unum e pluribus per ignorantiam, quod Domini lege prohibetur :

** Leviticus 4:23

et postea intellexerit peccatum suum, offeret hostiam Domino, hircum de capris immaculatum.

** Leviticus 4:24

Ponetque manum suam super caput ejus : cumque immolaverit eum loco ubi solet mactari holocaustum coram Domino, quia pro peccato est,

** Leviticus 4:25

tinget sacerdos digitum in sanguine hostiæ pro peccato, tangens cornua altaris holocausti, et reliquum fundens ad basim ejus.

** Leviticus 4:26

Adipem vero adolebit supra, sicut in victimis pacificorum fieri solet : rogabitque pro eo sacerdos, et pro peccato ejus, et dimittetur ei.  

** Leviticus 4:27

Quod si peccaverit anima per ignorantiam, de populo terræ, ut faciat quidquam de his, quæ Domini lege prohibentur, atque delinquat,

** Leviticus 4:28

et cognoverit peccatum suum, offeret capram immaculatam.

** Leviticus 4:29

Ponetque manum super caput hostiæ quæ pro peccato est, et immolabit eam in loco holocausti.

** Leviticus 4:30

Tolletque sacerdos de sanguine in digito suo : et tangens cornua altaris holocausti, reliquum fundet ad basim ejus.

** Leviticus 4:31

Omnem autem adipem auferens, sicut auferri solet de victimis pacificorum, adolebit super altare in odorem suavitatis Domino : rogabitque pro eo, et dimittetur ei.

** Leviticus 4:32

Sin autem de pecoribus obtulerit victimam pro peccato, ovem scilicet immaculatam :

** Leviticus 4:33

ponet manum super caput ejus, et immolabit eam in loco ubi solent cædi holocaustorum hostiæ.

** Leviticus 4:34

Sumetque sacerdos de sanguine ejus digito suo, et tangens cornua altaris holocausti, reliquum fundet ad basim ejus.

** Leviticus 4:35

Omnem quoque adipem auferens, sicut auferri solet adeps arietis, qui immolatur pro pacificis, cremabit super altare in incensum Domini : rogabitque pro eo, et pro peccato ejus, et dimittetur ei.   

* Leviticus 5

** Leviticus 5:1

Si peccaverit anima, et audierit vocem jurantis, testisque fuerit quod aut ipse vidit, aut conscius est : nisi indicaverit, portabit iniquitatem suam.

** Leviticus 5:2

Anima quæ tetigerit aliquid immundum, sive quod occisum a bestia est, aut per se mortuum, aut quodlibet aliud reptile : et oblita fuerit immunditiæ suæ, rea est, et deliquit :

** Leviticus 5:3

et si tetigerit quidquam de immunditia hominis juxta omnem impuritatem, qua pollui solet, oblitaque cognoverit postea, subjacebit delicto.  

** Leviticus 5:4

Anima, quæ juraverit, et protulerit labiis suis, ut vel male quid faceret, vel bene, et idipsum juramento et sermone firmaverit, oblitaque postea intellexerit delictum suum,

** Leviticus 5:5

agat pœnitentiam pro peccato,

** Leviticus 5:6

et offerat de gregibus agnam sive capram, orabitque pro ea sacerdos et pro peccato ejus.

** Leviticus 5:7

Sin autem non potuerit offerre pecus, offerat duos turtures, vel duos pullos columbarum Domino, unum pro peccato, et alterum in holocaustum,

** Leviticus 5:8

dabitque eos sacerdoti : qui primum offerens pro peccato, retorquebit caput ejus ad pennulas, ita ut collo hæreat, et non penitus abrumpatur.

** Leviticus 5:9

Et asperget de sanguine ejus parietem altaris ; quidquid autem reliquum fuerit, faciet distillare ad fundamentum ejus, quia pro peccato est.

** Leviticus 5:10

Alterum vero adolebit in holocaustum, ut fieri solet : rogabitque pro eo sacerdos et pro peccato ejus, et dimittetur ei.

** Leviticus 5:11

Quod si non quiverit manus ejus duos offerre turtures, aut duos pullos columbarum, offeret pro peccato suo similæ partem ephi decimam : non mittet in eam oleum, nec thuris aliquid imponet, quia pro peccato est.

** Leviticus 5:12

Tradetque eam sacerdoti : qui plenum ex ea pugillum hauriens, cremabit super altare in monimentum ejus qui obtulerit,

** Leviticus 5:13

rogans pro illo et expians : reliquam vero partem ipse habebit in munere.  

** Leviticus 5:14

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 5:15

Anima si prævaricans cæremonias, per errorem, in his quæ Domino sunt sanctificata, peccaverit, offeret pro delicto suo arietem immaculatum de gregibus, qui emi potest duobus siclis, juxta pondus sanctuarii :

** Leviticus 5:16

ipsumque quod intulit damni restituet, et quintam partem ponet supra, tradens sacerdoti, qui rogabit pro eo offerens arietem, et dimittetur ei.

** Leviticus 5:17

Anima si peccaverit per ignorantiam, feceritque unum ex his quæ Domini lege prohibentur, et peccati rea intellexerit iniquitatem suam,

** Leviticus 5:18

offeret arietem immaculatum de gregibus sacerdoti, juxta mensuram æstimationemque peccati : qui orabit pro eo, quia nesciens fecerit : et dimittetur ei,

** Leviticus 5:19

quia per errorem deliquit in Dominum.   

* Leviticus 6

** Leviticus 6:1

Locutus est Dominus ad Moysen, dicens :

** Leviticus 6:2

Anima quæ peccaverit, et contempto Domino, negaverit proximo suo depositum quod fidei ejus creditum fuerat, vel vi aliquid extorserit, aut calumniam fecerit,

** Leviticus 6:3

sive rem perditam invenerit, et inficians insuper pejeraverit, et quodlibet aliud ex pluribus fecerit, in quibus solent peccare homines,

** Leviticus 6:4

convicta delicti,

** Leviticus 6:5

reddet omnia, quæ per fraudem voluit obtinere, integra, et quintam insuper partem domino cui damnum intulerat.

** Leviticus 6:6

Pro peccato autem suo offeret arietem immaculatum de grege, et dabit eum sacerdoti, juxta æstimationem mensuramque delicti :

** Leviticus 6:7

qui rogabit pro eo coram Domino, et dimittetur illi pro singulis quæ faciendo peccavit.  

** Leviticus 6:8

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 6:9

Præcipe Aaron et filiis ejus : Hæc est lex holocausti : cremabitur in altari tota nocte usque mane : ignis ex eodem altari erit.

** Leviticus 6:10

Vestietur tunica sacerdos et feminalibus lineis : tolletque cineres, quos vorans ignis exussit, et ponens juxta altare,

** Leviticus 6:11

spoliabitur prioribus vestimentis, indutusque aliis, efferret eos extra castra, et in loco mundissimo usque ad favillam consumi faciet.

** Leviticus 6:12

Ignis autem in altari semper ardebit, quem nutriet sacerdos subjiciens ligna mane per singulos dies, et imposito holocausto, desuper adolebit adipes pacificorum.

** Leviticus 6:13

Ignis est iste perpetuus, qui numquam deficiet in altari.

** Leviticus 6:14

Hæc est lex sacrificii et libamentorum, quæ offerent filii Aaron coram Domino, et coram altari.

** Leviticus 6:15

Tollet sacerdos pugillum similæ, quæ conspersa est oleo, et totum thus, quod super similam positum est : adolebitque illud in altari in monimentum odoris suavissimi Domino :

** Leviticus 6:16

reliquam autem partem similæ comedet Aaron cum filiis suis, absque fermento : et comedet in loco sancto atrii tabernaculi.

** Leviticus 6:17

Ideo autem non fermentabitur, quia pars ejus in Domini offertur incensum. Sanctum sanctorum erit, sicut pro peccato atque delicto.

** Leviticus 6:18

Mares tantum stirpis Aaron comedent illud. Legitimum ac sempiternum erit in generationibus vestris de sacrificiis Domini : omnis qui tetigerit illa, sanctificabitur.

** Leviticus 6:19

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 6:20

Hæc est oblatio Aaron, et filiorum ejus, quam offerre debent Domino in die unctionis suæ. Decimam partem ephi offerent similæ in sacrificio sempiterno, medium ejus mane, et medium ejus vespere :

** Leviticus 6:21

quæ in sartagine oleo conspersa frigetur. Offeret autem eam calidam in odorem suavissimum Domino

** Leviticus 6:22

sacerdos, qui jure patri successerit, et tota cremabitur in altari.

** Leviticus 6:23

Omne enim sacrificium sacerdotum igne consumetur, nec quisquam comedet ex eo.  

** Leviticus 6:24

Locutus est autem Dominus ad Moysen, dicens :

** Leviticus 6:25

Loquere Aaron et filiis ejus : Ista est lex hostiæ pro peccato : in loco ubi offertur holocaustum, immolabitur coram Domino. Sanctum sanctorum est.

** Leviticus 6:26

Sacerdos, qui offert, comedet eam in loco sancto, in atrio tabernaculi.

** Leviticus 6:27

Quidquid tetigerit carnes ejus, sanctificabitur. Si de sanguine illius vestis fuerit aspersa, lavabitur in loco sancto.

** Leviticus 6:28

Vas autem fictile, in quo cocta est, confringetur ; quod si vas æneum fuerit, defricabitur, et lavabitur aqua.

** Leviticus 6:29

Omnis masculus de genere sacerdotali vescetur de carnibus ejus, quia Sanctum sanctorum est.

** Leviticus 6:30

Hostia enim quæ cæditur pro peccato, cujus sanguis infertur in tabernaculum testimonii ad expiandum in sanctuario, non comedetur, sed comburetur igni.   

* Leviticus 7

** Leviticus 7:1

Hæc quoque lex hostiæ pro delicto, Sancta sanctorum est :

** Leviticus 7:2

idcirco ubi immolabitur holocaustum, mactabitur et victima pro delicto : sanguis ejus per gyrum altaris fundetur.

** Leviticus 7:3

Offerent ex ea caudam et adipem qui operit vitalia :

** Leviticus 7:4

duos renunculos, et pinguedinem quæ juxta ilia est, reticulumque jecoris cum renunculis.

** Leviticus 7:5

Et adolebit ea sacerdos super altare : incensum est Domini pro delicto.

** Leviticus 7:6

Omnis masculus de sacerdotali genere, in loco sancto vescetur his carnibus, quia Sanctum sanctorum est.

** Leviticus 7:7

Sicut pro peccato offertur hostia, ita et pro delicto : utriusque hostiæ lex una erit : ad sacerdotem, qui eam obtulerit, pertinebit.

** Leviticus 7:8

Sacerdos qui offert holocausti victimam, habebit pellem ejus.

** Leviticus 7:9

Et omne sacrificium similæ, quod coquitur in clibano, et quidquid in craticula, vel in sartagine præparatur, ejus erit sacerdotis a quo offertur :

** Leviticus 7:10

sive oleo conspersa, sive arida fuerint, cunctis filiis Aaron mensura æqua per singulos dividetur.  

** Leviticus 7:11

Hæc est lex hostiæ pacificorum quæ offertur Domino.

** Leviticus 7:12

Si pro gratiarum actione oblatio fuerit, offerent panes absque fermento conspersos oleo, et lagana azyma uncta oleo, coctamque similam, et collyridas olei admistione conspersas :

** Leviticus 7:13

panes quoque fermentatos cum hostia gratiarum, quæ immolatur pro pacificis :

** Leviticus 7:14

ex quibus unus pro primitiis offeretur Domino, et erit sacerdotis qui fundet hostiæ sanguinem,

** Leviticus 7:15

cujus carnes eadem comedentur die, nec remanebit ex eis quidquam usque mane.

** Leviticus 7:16

Si voto, vel sponte quispiam obtulerit hostiam, eadem similiter edetur die : sed et si quid in crastinum remanserit, vesci licitum est :

** Leviticus 7:17

quidquid autem tertius invenerit dies, ignis absumet.

** Leviticus 7:18

Si quis de carnibus victimæ pacificorum die tertio comederit, irrita fiet oblatio, nec proderit offerenti : quin potius quæcumque anima tali se edulio contaminaverit, prævaricationis rea erit.

** Leviticus 7:19

Caro, quæ aliquid tetigerit immundum, non comedetur, sed comburetur igni : qui fuerit mundus, vescetur ex ea.

** Leviticus 7:20

Anima polluta quæ ederit de carnibus hostiæ pacificorum, quæ oblata est Domino, peribit de populis suis.

** Leviticus 7:21

Et quæ tetigerit immunditiam hominis, vel jumenti, sive omnis rei quæ polluere potest, et comederit de hujuscemodi carnibus, interibit de populis suis.  

** Leviticus 7:22

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 7:23

Loquere filiis Israël : Adipem ovis, et bovis, et capræ non comedetis.

** Leviticus 7:24

Adipem cadaveris morticini, et ejus animalis, quod a bestia captum est, habebitis in varios usus.

** Leviticus 7:25

Si quis adipem, qui offerri debet in incensum Domini, comederit, peribit de populo suo.

** Leviticus 7:26

Sanguinem quoque omnis animalis non sumetis in cibo, tam de avibus quam de pecoribus.

** Leviticus 7:27

Omnis anima, quæ ederit sanguinem, peribit de populis suis.  

** Leviticus 7:28

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 7:29

Loquere filiis Israël, dicens : Qui offert victimam pacificorum Domino, offerat simul et sacrificium, id est, libamenta ejus.

** Leviticus 7:30

Tenebit manibus adipem hostiæ, et pectusculum : cumque ambo oblata Domino consecraverit, tradet sacerdoti,

** Leviticus 7:31

qui adolebit adipem super altare, pectusculum autem erit Aaron et filiorum ejus.

** Leviticus 7:32

Armus quoque dexter de pacificorum hostiis cedet in primitias sacerdotis.

** Leviticus 7:33

Qui obtulerit sanguinem et adipem filiorum Aaron, ipse habebit et armum dextrum in portione sua.

** Leviticus 7:34

Pectusculum enim elevationis, et armum separationis, tuli a filiis Israël de hostiis eorum pacificis, et dedi Aaron sacerdoti, et filiis ejus, lege perpetua, ab omni populo Israël.

** Leviticus 7:35

Hæc est unctio Aaron et filiorum ejus in cæremoniis Domini die qua obtulit eos Moyses, ut sacerdotio fungerentur,

** Leviticus 7:36

et quæ præcepit eis dari Dominus a filiis Israël religione perpetua in generationibus suis.

** Leviticus 7:37

Ista est lex holocausti, et sacrificii pro peccato atque delicto, et pro consecratione et pacificorum victimis,

** Leviticus 7:38

quam constituit Dominus Moysi in monte Sinai, quando mandabit filiis Israël ut offerrent oblationes suas Domino in deserto Sinai.   

* Leviticus 8

** Leviticus 8:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 8:2

Tolle Aaron cum filiis suis, vestes eorum, et unctionis oleum, vitulum pro peccato, duos arietes, canistrum cum azymis :

** Leviticus 8:3

et congregabis omnem cœtum ad ostium tabernaculi.

** Leviticus 8:4

Fecit Moyses ut Dominus imperaverat. Congregataque omni turba ante fores tabernaculi,

** Leviticus 8:5

ait : Iste est sermo, quem jussit Dominus fieri.

** Leviticus 8:6

Statimque obtulit Aaron et filios ejus. Cumque lavisset eos,

** Leviticus 8:7

vestivit pontificem subucula linea, accingens eum balteo, et induens eum tunica hyacinthina, et desuper humerale imposuit,

** Leviticus 8:8

quod astringens cingulo aptavit rationali, in quo erat Doctrina et Veritas.

** Leviticus 8:9

Cidari quoque texit caput : et super eam, contra frontem, posuit laminam auream consecratam in sanctificatione, sicut præceperat ei Dominus.

** Leviticus 8:10

Tulit et unctionis oleum, quo linivit tabernaculum cum omni supellectili sua.

** Leviticus 8:11

Cumque sanctificans aspersisset altare septem vicibus, unxit illud, et omnia vasa ejus, labrumque cum basi sua sanctificavit oleo.

** Leviticus 8:12

Quod fundens super caput Aaron, unxit eum, et consecravit :

** Leviticus 8:13

filios quoque ejus oblatos vestivit tunicis lineis, et cinxit balteis, imposuitque mitras, ut jusserat Dominus.  

** Leviticus 8:14

Obtulit et vitulum pro peccato : cumque super caput ejus posuisset Aaron et filii ejus manus suas,

** Leviticus 8:15

immolavit eum, hauriens sanguinem, et tincto digito, tetigit cornua altaris per gyrum : quo expiato et sanctificato, fudit reliquum sanguinem ad fundamenta ejus.

** Leviticus 8:16

Adipem vero qui erat super vitalia, et reticulum jecoris, duosque renunculos, cum arvinulis suis, adolevit super altare :

** Leviticus 8:17

vitulum cum pelle, et carnibus, et fimo, cremans extra castra, sicut præceperat Dominus.

** Leviticus 8:18

Obtulit et arietem in holocaustum : super cujus caput cum imposuissent Aaron et filii ejus manus suas,

** Leviticus 8:19

immolavit eum, et fudit sanguinem ejus per circuitum altaris.

** Leviticus 8:20

Ipsumque arietem in frusta concidens, caput ejus, et artus, et adipem adolevit igni,

** Leviticus 8:21

lotis prius intestinis et pedibus : totumque simul arietem incendit super altare, eo quod esset holocaustum suavissimi odoris Domino, sicut præceperat ei.

** Leviticus 8:22

Obtulit et arietem secundum in consecratione sacerdotum, posueruntque super caput ejus Aaron et filii ejus manus suas :

** Leviticus 8:23

quem cum immolasset Moyses, sumens de sanguine ejus, tetigit extremum auriculæ dextræ Aaron, et pollicem manus ejus dextræ, similiter et pedis.

** Leviticus 8:24

Obtulit et filios Aaron : cumque de sanguine arietis immolati tetigisset extremum auriculæ singulorum dextræ, et pollices manus ac pedis dextri, reliquum fudit super altare per circuitum :

** Leviticus 8:25

adipem vero, et caudam, omnemque pinguedinem quæ operit intestina, reticulumque jecoris, et duos renes cum adipibus suis et armo dextro separavit.  

** Leviticus 8:26

Tollens autem de canistro azymorum, quod erat coram Domino, panem absque fermento, et collyridam conspersam oleo, laganumque, posuit super adipes, et armum dextrum,

** Leviticus 8:27

tradens simul omnia Aaron et filiis ejus. Qui postquam levaverunt ea coram Domino,

** Leviticus 8:28

rursum suscepta de manibus eorum, adolevit super altare holocausti, eo quod consecrationis esset oblatio, in odorem suavitatis, sacrificii Domino.

** Leviticus 8:29

Tulitque pectusculum, elevans illud coram Domino, de ariete consecrationis in partem suam, sicut præceperat ei Dominus.  

** Leviticus 8:30

Assumensque unguentum, et sanguinem qui erat in altari, aspersit super Aaron et vestimenta ejus, et super filios illius ac vestes eorum.

** Leviticus 8:31

Cumque sanctificasset eos in vestitu suo, præcepit eis, dicens : Coquite carnes ante fores tabernaculi, et ibi comedite eas ; panes quoque consecrationis edite, qui positi sunt in canistro, sicut præcepit mihi Dominus, dicens : Aaron et filii ejus comedent eos :

** Leviticus 8:32

quidquid autem reliquum fuerit de carne et panibus, ignis absumet.

** Leviticus 8:33

De ostio quoque tabernaculi non exibitis septem diebus, usque ad diem quo complebitur tempus consecrationis vestræ ; septem enim diebus finitur consecratio :

** Leviticus 8:34

sicut et impræsentiarum factum est, ut ritus sacrificii compleretur.

** Leviticus 8:35

Die ac nocte manebitis in tabernaculo observantes custodias Domini, ne moriamini : sic enim mihi præceptum est.

** Leviticus 8:36

Feceruntque Aaron et filii ejus cuncta quæ locutus est Dominus per manum Moysi.   

* Leviticus 9

** Leviticus 9:1

Facto autem octavo die, vocavit Moyses Aaron, et filios ejus, ac majores natu Israël, dixitque ad Aaron :

** Leviticus 9:2

Tolle de armento vitulum pro peccato, et arietem in holocaustum, utrumque immaculatum, et offer illos coram Domino.

** Leviticus 9:3

Et ad filios Israël loqueris : Tollite hircum pro peccato, et vitulum, atque agnum, anniculos, et sine macula in holocaustum,

** Leviticus 9:4

bovem et arietem pro pacificis : et immolate eos coram Domino, in sacrificio singulorum similam conspersam oleo offerentes : hodie enim Dominus apparebit vobis.

** Leviticus 9:5

Tulerunt ergo cuncta quæ jusserat Moyses ad ostium tabernaculi : ubi cum omnis multitudo astaret,

** Leviticus 9:6

ait Moyses : Iste est sermo, quem præcepit Dominus : facite, et apparebit vobis gloria ejus.

** Leviticus 9:7

Et dixit ad Aaron : Accede ad altare, et immola pro peccato tuo : offer holocaustum, et deprecare pro te et pro populo : cumque mactaveris hostiam populi, ora pro eo, sicut præcepit Dominus.  

** Leviticus 9:8

Statimque Aaron accedens ad altare, immolavit vitulum pro peccato suo :

** Leviticus 9:9

cujus sanguinem obtulerunt ei filii sui : in quo tingens digitum, tetigit cornua altaris, et fudit residuum ad basim ejus.

** Leviticus 9:10

Adipemque, et renunculos, ac reticulum jecoris, quæ sunt pro peccato, adolevit super altare, sicut præceperat Dominus Moysi :

** Leviticus 9:11

carnes vero et pellem ejus extra castra combussit igni.

** Leviticus 9:12

Immolavit et holocausti victimam : obtuleruntque ei filii sui sanguinem ejus, quem fudit per altaris circuitum.

** Leviticus 9:13

Ipsam etiam hostiam in frusta concisam, cum capite et membris singulis obtulerunt ; quæ omnia super altare cremavit igni,

** Leviticus 9:14

lotis aqua prius intestinis et pedibus.  

** Leviticus 9:15

Et pro peccato populi offerens, mactavit hircum : expiatoque altari,

** Leviticus 9:16

fecit holocaustum,

** Leviticus 9:17

addens in sacrificio libamenta, quæ pariter offeruntur, et adolens ea super altare, absque cæremoniis holocausti matutini.

** Leviticus 9:18

Immolavit et bovem atque arietem, hostias pacificas populi : obtuleruntque ei filii sui sanguinem, quem fudit super altare in circuitum.

** Leviticus 9:19

Adipem autem bovis, et caudam arietis, renunculosque cum adipibus suis, et reticulum jecoris,

** Leviticus 9:20

posuerunt super pectora : cumque cremati essent adipes super altare,

** Leviticus 9:21

pectora eorum, et armos dextros separavit Aaron, elevans coram Domino, sicut præceperat Moyses.  

** Leviticus 9:22

Et extendens manus ad populum, benedixit ei. Sicque completis hostiis pro peccato, et holocaustis, et pacificis, descendit.

** Leviticus 9:23

Ingressi autem Moyses et Aaron in tabernaculum testimonii, et deinceps egressi, benedixerunt populo. Apparuitque gloria Domini omni multitudini :

** Leviticus 9:24

et ecce egressus ignis a Domino, devoravit holocaustum, et adipes qui erant super altare. Quod cum vidissent turbæ, laudaverunt Dominum, ruentes in facies suas.   

* Leviticus 10

** Leviticus 10:1

Arreptisque Nadab et Abiu filii Aaron thuribulis, posuerunt ignem, et incensum desuper, offerentes coram Domino ignem alienum : quod eis præceptum non erat.

** Leviticus 10:2

Egressusque ignis a Domino, devoravit eos, et mortui sunt coram Domino.

** Leviticus 10:3

Dixitque Moyses ad Aaron : Hoc est quod locutus est Dominus : Sanctificabor in iis qui appropinquant mihi, et in conspectu omnis populi glorificabor. Quod audiens tacuit Aaron.

** Leviticus 10:4

Vocatis autem Moyses Misaële et Elisaphan filiis Oziel, patrui Aaron, ait ad eos : Ite, et tollite fratres vestros de conspectu sanctuarii, et asportate extra castra.

** Leviticus 10:5

Confestimque pergentes, tulerunt eos sicut jacebant, vestitos lineis tunicis, et ejecerunt foras, ut sibi fuerat imperatum.

** Leviticus 10:6

Locutusque est Moyses ad Aaron, et ad Eleazar, et Ithamar, filios ejus : Capita vestra nolite nudare, et vestimenta nolite scindere, ne forte moriamini, et super omnem cœtum oriatur indignatio. Fratres vestri, et omnis domus Israël, plangant incendium quod Dominus suscitavit :

** Leviticus 10:7

vos autem non egrediemini fores tabernaculi, alioquin peribitis : oleum quippe sanctæ unctionis est super vos. Qui fecerunt omnia juxta præceptum Moysi.

** Leviticus 10:8

Dixit quoque Dominus ad Aaron :

** Leviticus 10:9

Vinum, et omne quod inebriare potest, non bibetis tu et filii tui, quando intratis in tabernaculum testimonii, ne moriamini : quia præceptum sempiternum est in generationes vestras :

** Leviticus 10:10

et ut habeatis scientiam discernendi inter sanctum et profanum, inter pollutum et mundum ;

** Leviticus 10:11

doceatisque filios Israël omnia legitima mea quæ locutus est Dominus ad eos per manum Moysi.  

** Leviticus 10:12

Locutusque est Moyses ad Aaron, et ad Eleazar, et Ithamar, filios ejus, qui erant residui : Tollite sacrificium, quod remansit de oblatione Domini, et comedite illud absque fermento juxta altare, quia Sanctum sanctorum est.

** Leviticus 10:13

Comedetis autem in loco sancto : quod datum est tibi et filiis tuis de oblationibus Domini, sicut præceptum est mihi.

** Leviticus 10:14

Pectusculum quoque quod oblatum est, et armum qui separatus est, edetis in loco mundissimo tu et filii tui, et filiæ tuæ tecum : tibi enim ac liberis tuis reposita sunt de hostiis salutaribus filiorum Israël :

** Leviticus 10:15

eo quod armum et pectus, et adipes qui cremantur in altari, elevaverunt coram Domino, et pertineant ad te, et ad filios tuos, lege perpetua, sicut præcepit Dominus.

** Leviticus 10:16

Inter hæc, hircum, qui oblatus fuerat pro peccato, cum quæreret Moyses, exustum reperit : iratusque contra Eleazar et Ithamar filios Aaron, qui remanserant, ait :

** Leviticus 10:17

Cur non comedistis hostiam pro peccato in loco sancto, quæ Sancta sanctorum est, et data vobis ut portetis iniquitatem multitudinis, et rogetis pro ea in conspectu Domini,

** Leviticus 10:18

præsertim cum de sanguine illius non sit illatum intra sancta, et comedere debueritis eam in Sanctuario, sicut præceptum est mihi ?

** Leviticus 10:19

Respondit Aaron : Oblata est hodie victima pro peccato, et holocaustum coram Domino : mihi autem accidit quod vides ; quomodo potui comedere eam, aut placere Domino in cæremoniis mente lugubri ?

** Leviticus 10:20

Quod cum audisset Moyses, recepit satisfactionem.   

* Leviticus 11

** Leviticus 11:1

Locutusque est Dominus ad Moysen et Aaron, dicens :

** Leviticus 11:2

Dicite filiis Israël : Hæc sunt animalia quæ comedere debetis de cunctis animantibus terræ :

** Leviticus 11:3

omne quod habet divisam ungulam, et ruminat in pecoribus, comedetis.

** Leviticus 11:4

Quidquid autem ruminat quidem, et habet ungulam, sed non dividit eam, sicut camelus et cetera, non comedetis illud, et inter immunda reputabitis.

** Leviticus 11:5

Chœrogryllus qui ruminat, ungulamque non dividit, immundus est.

** Leviticus 11:6

Lepus quoque : nam et ipse ruminat, sed ungulam non dividit.

** Leviticus 11:7

Et sus : qui cum ungulam dividat, non ruminat.

** Leviticus 11:8

Horum carnibus non vescemini, nec cadavera contingetis, quia immunda sunt vobis.  

** Leviticus 11:9

Hæc sunt quæ gignuntur in aquis, et vesci licitum est : omne quod habet pinnulas et squamas, tam in mari quam in fluminibus et stagnis, comedetis.

** Leviticus 11:10

Quidquid autem pinnulas et squamas non habet, eorum quæ in aquis moventur et vivunt, abominabile vobis,

** Leviticus 11:11

execrandumque erit : carnes eorum non comedetis, et morticina vitabitis.

** Leviticus 11:12

Cuncta quæ non habent pinnulas et squamas in aquis, polluta erunt.  

** Leviticus 11:13

Hæc sunt quæ de avibus comedere non debetis, et vitanda sunt vobis : aquilam, et gryphem, et haliæetum,

** Leviticus 11:14

et milvum ac vulturem juxta genus suum,

** Leviticus 11:15

et omne corvini generis in similitudinem suam,

** Leviticus 11:16

struthionem, et noctuam, et larum, et accipitrem juxta genus suum :

** Leviticus 11:17

bubonem, et mergulum, et ibin,

** Leviticus 11:18

et cygnum, et onocrotalum, et porphyrionem,

** Leviticus 11:19

herodionem, et charadrion juxta genus suum, upupam quoque, et vespertilionem.  

** Leviticus 11:20

Omne de volucribus quod graditur super quatuor pedes, abominabile erit vobis.

** Leviticus 11:21

Quidquid autem ambulat quidem super quatuor pedes, sed habet longiora retro crura, per quæ salit super terram,

** Leviticus 11:22

comedere debetis, ut est bruchus in genere suo, et attacus atque ophiomachus, ac locusta, singula juxta genus suum.

** Leviticus 11:23

Quidquid autem ex volucribus quatuor tantum habet pedes, execrabile erit vobis :

** Leviticus 11:24

et quicumque morticina eorum tetigerit, polluetur, et erit immundus usque ad vesperum :

** Leviticus 11:25

et si necesse fuerit ut portet quippiam horum mortuum, lavabit vestimenta sua, et immundus erit usque ad occasum solis.

** Leviticus 11:26

Omne animal quod habet quidem ungulam, sed non dividit eam, nec ruminat, immundum erit : et qui tetigerit illud, contaminabitur.

** Leviticus 11:27

Quod ambulat super manus ex cunctis animantibus, quæ incedunt quadrupedia, immundum erit : qui tetigerit morticina eorum, polluetur usque ad vesperum.

** Leviticus 11:28

Et qui portaverit hujuscemodi cadavera, lavabit vestimenta sua, et immundus erit usque ad vesperum : quia omnia hæc immunda sunt vobis.

** Leviticus 11:29

Hæc quoque inter polluta reputabuntur de his quæ moventur in terra, mustela et mus et crocodilus, singula juxta genus suum,

** Leviticus 11:30

mygale, et chamæleon, et stellio, et lacerta, et talpa.  

** Leviticus 11:31

Omnia hæc immunda sunt. Qui tetigerit morticina eorum, immundus erit usque ad vesperum :

** Leviticus 11:32

et super quod ceciderit quidquam de morticinis eorum, polluetur, tam vas ligneum et vestimentum, quam pelles et cilicia : et in quocumque fit opus, tingentur aqua, et polluta erunt usque ad vesperum, et sic postea mundabuntur.

** Leviticus 11:33

Vas autem fictile, in quod horum quidquam intro cecidit, polluetur, et idcirco frangendum est.

** Leviticus 11:34

Omnis cibus, quem comedetis, si fusa fuerit super eum aqua, immundus erit : et omne liquens quod bibitur de universo vase, immundum erit.

** Leviticus 11:35

Et quidquid de morticinis hujuscemodi ceciderit super illud, immundum erit : sive clibani, sive chytropodes, destruentur, et immundi erunt.

** Leviticus 11:36

Fontes vero et cisternæ, et omnis aquarum congregatio munda erit. Qui morticinum eorum tetigerit, polluetur.

** Leviticus 11:37

Si ceciderit super sementem, non polluet eam.

** Leviticus 11:38

Si autem quispiam aqua sementem perfuderit, et postea morticinis tacta fuerit, illico polluetur.

** Leviticus 11:39

Si mortuum fuerit animal, quod licet vobis comedere, qui cadaver ejus tetigerit, immundus erit usque ad vesperum :

** Leviticus 11:40

et qui comederit ex eo quippiam, sive portaverit, lavabit vestimenta sua, et immundus erit usque ad vesperum.

** Leviticus 11:41

Omne quod reptat super terram, abominabile erit, nec assumetur in cibum.

** Leviticus 11:42

Quidquid super pectus quadrupes graditur, et multos habet pedes, sive per humum trahitur, non comedetis, quia abominabile est.

** Leviticus 11:43

Nolite contaminare animas vestras, nec tangatis quidquam eorum, ne immundi sitis.

** Leviticus 11:44

Ego enim sum Dominus Deus vester : sancti estote, quia ego sanctus sum. Ne polluatis animas vestras in omni reptili quod movetur super terram.

** Leviticus 11:45

Ego enim sum Dominus, qui eduxi vos de terra Ægypti, ut essem vobis in Deum. Sancti eritis, quia ego sanctus sum.

** Leviticus 11:46

Ista est lex animantium ac volucrum, et omnis animæ viventis, quæ movetur in aqua, et reptat in terra,

** Leviticus 11:47

ut differentias noveritis mundi et immundi, et sciatis quid comedere et quid respuere debeatis.   

* Leviticus 12

** Leviticus 12:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 12:2

Loquere filiis Israël, et dices ad eos : Mulier, si suscepto semine pepererit masculum, immunda erit septem diebus juxta dies separationis menstruæ.

** Leviticus 12:3

Et die octavo circumcidetur infantulus :

** Leviticus 12:4

ipsa vero triginta tribus diebus manebit in sanguine purificationis suæ. Omne sanctum non tanget, nec ingredietur in sanctuarium, donec impleantur dies purificationis suæ.

** Leviticus 12:5

Sin autem feminam pepererit, immunda erit duabus hebdomadibus juxta ritum fluxus menstrui, et sexaginta sex diebus manebit in sanguine purificationis suæ.

** Leviticus 12:6

Cumque expleti fuerint dies purificationis suæ, pro filio sive pro filia, deferet agnum anniculum in holocaustum, et pullum columbæ sive turturem pro peccato, ad ostium tabernaculi testimonii, et tradet sacerdoti,

** Leviticus 12:7

qui offeret illa coram Domino, et orabit pro ea, et sic mundabitur a profluvio sanguinis sui : ista est lex parientis masculum aut feminam.

** Leviticus 12:8

Quod si non invenerit manus ejus, nec potuerit offerre agnum, sumet duos turtures vel duos pullos columbarum, unum in holocaustum, et alterum pro peccato : orabitque pro ea sacerdos, et sic mundabitur.   

* Leviticus 13

** Leviticus 13:1

Locutusque est Dominus ad Moysen, et Aaron, dicens :

** Leviticus 13:2

Homo, in cujus cute et carne ortus fuerit diversus color, sive pustula, aut quasi lucens quippiam, id est, plaga lepræ, adducetur ad Aaron sacerdotem, vel ad unum quemlibet filiorum ejus.

** Leviticus 13:3

Qui cum viderit lepram in cute, et pilos in album mutatos colorem, ipsamque speciem lepræ humiliorem cute et carne reliqua : plaga lepræ est, et ad arbitrium ejus separabitur.  

** Leviticus 13:4

Sin autem lucens candor fuerit in cute, nec humilior carne reliqua, et pili coloris pristini, recludet eum sacerdos septem diebus :

** Leviticus 13:5

et considerabit die septimo : et si quidem lepra ultra non creverit, nec transierit in cute priores terminos, rursum recludet eum septem diebus aliis.

** Leviticus 13:6

Et die septimo contemplabitur : si obscurior fuerit lepra, et non creverit in cute, mundabit eum, quia scabies est : lavabitque homo vestimenta sua, et mundus erit.

** Leviticus 13:7

Quod si postquam a sacerdote visus est, et redditus munditiæ, iterum lepra creverit : adducetur ad eum,

** Leviticus 13:8

et immunditiæ condemnabitur.  

** Leviticus 13:9

Plaga lepræ si fuerit in homine, adducetur ad sacerdotem,

** Leviticus 13:10

et videbit eum. Cumque color albus in cute fuerit, et capillorum mutaverit aspectum, ipsa quoque caro viva apparuerit :

** Leviticus 13:11

lepra vetustissima judicabitur, atque inolita cuti. Contaminabit itaque eum sacerdos, et non recludet, quia perspicuæ immunditiæ est.

** Leviticus 13:12

Sin autem effloruerit discurrens lepra in cute, et operuerit omnem cutem a capite usque ad pedes, quidquid sub aspectum oculorum cadit,

** Leviticus 13:13

considerabit eum sacerdos, et teneri lepra mundissima judicabit : eo quod omnis in candorem versa sit, et idcirco homo mundus erit.

** Leviticus 13:14

Quando vero caro vivens in eo apparuerit,

** Leviticus 13:15

tunc sacerdotis judicio polluetur, et inter immundos reputabitur : caro enim viva, si lepra aspergitur, immunda est.

** Leviticus 13:16

Quod si rursum versa fuerit in alborem, et totum hominem operuerit,

** Leviticus 13:17

considerabit eum sacerdos, et mundum esse decernet.  

** Leviticus 13:18

Caro autem et cutis in qua ulcus natum est, et sanatum,

** Leviticus 13:19

et in loco ulceris cicatrix alba apparuerit, sive subrufa, adducetur homo ad sacerdotem.

** Leviticus 13:20

Qui cum viderit locum lepræ humiliorem carne reliqua, et pilos versos in candorem, contaminabit eum : plaga enim lepræ orta est in ulcere.

** Leviticus 13:21

Quod si pilus coloris est pristini, et cicatrix subobscura, et vicina carne non est humilior, recludet eum septem diebus :

** Leviticus 13:22

et si quidem creverit, adjudicabit eum lepræ ;

** Leviticus 13:23

sin autem steterit in loco suo, ulceris est cicatrix, et homo mundus erit.  

** Leviticus 13:24

Caro autem et cutis, quam ignis exusserit, et sanata albam sive rufam habuerit cicatricem,

** Leviticus 13:25

considerabit eam sacerdos : et ecce versa est in alborem, et locus ejus reliqua cute est humilior, contaminabit eum, quia plaga lepræ in cicatrice orta est.

** Leviticus 13:26

Quod si pilorum color non fuerit immutatus, nec humilior plaga carne reliqua, et ipsa lepræ species fuerit subobscura, recludet eum septem diebus,

** Leviticus 13:27

et die septimo contemplabitur : si creverit in cute lepra, contaminabit eum.

** Leviticus 13:28

Sin autem in loco suo candor steterit non satis clarus, plaga combustionis est, et idcirco mundabitur, quia cicatrix est combusturæ.  

** Leviticus 13:29

Vir, sive mulier, in cujus capite vel barba germinaverit lepra, videbit eos sacerdos.

** Leviticus 13:30

Et si quidem humilior fuerit locus carne reliqua, et capillus flavus, solitoque subtilior, contaminabit eos, quia lepra capitis ac barbæ est.

** Leviticus 13:31

Sin autem viderit locum maculæ æqualem vicinæ carni, et capillum nigrum : recludet eum septem diebus,

** Leviticus 13:32

et die septimo intuebitur. Si non creverit macula, et capillus sui coloris est, et locus plagæ carni reliquæ æqualis :

** Leviticus 13:33

radetur homo absque loco maculæ, et includetur septem diebus aliis.

** Leviticus 13:34

Si die septimo visa fuerit stetisse plaga in loco suo, nec humilior carne reliqua, mundabit eum : lotisque vestibus suis, mundus erit.

** Leviticus 13:35

Sin autem post emundationem rursus creverit macula in cute,

** Leviticus 13:36

non quæret amplius utrum capillus in flavum colorem sit immutatus, quia aperte immundus est.

** Leviticus 13:37

Porro si steterit macula, et capilli nigri fuerint, noverit hominem sanatum esse, et confidenter eum pronuntiet mundum.  

** Leviticus 13:38

Vir, sive mulier, in cujus cute candor apparuerit,

** Leviticus 13:39

intuebitur eos sacerdos. Si deprehenderit subobscurum alborem lucere in cute, sciat non esse lepram, sed maculam coloris candidi, et hominem mundum.  

** Leviticus 13:40

Vir, de cujus capite capilli fluunt, calvus et mundus est :

** Leviticus 13:41

et si a fronte ceciderint pili, recalvaster et mundus est.

** Leviticus 13:42

Sin autem in calvitio sive in recalvatione albus vel rufus color fuerit exortus,

** Leviticus 13:43

et hoc sacerdos viderit, condemnabit eum haud dubiæ lepræ, quæ orta est in calvitio.

** Leviticus 13:44

Quicumque ergo maculatus fuerit lepra, et separatus est ad arbitrium sacerdotis,

** Leviticus 13:45

habebit vestimenta dissuta, caput nudum, os veste contectum, contaminatum ac sordidum se clamabit.

** Leviticus 13:46

Omni tempore quo leprosus est et immundus, solus habitabit extra castra.  

** Leviticus 13:47

Vestis lanea sive linea, quæ lepram habuerit,

** Leviticus 13:48

in stamine atque subtegmine, aut certe pellis, vel quidquid ex pelle confectum est,

** Leviticus 13:49

si alba vel rufa macula fuerit infecta, lepra reputabitur, ostendeturque sacerdoti :

** Leviticus 13:50

qui consideratam recludet septem diebus :

** Leviticus 13:51

et die septimo rursus aspiciens, si deprehenderit crevisse, lepra perseverans est : pollutum judicabit vestimentum, et omne in quo fuerit inventa :

** Leviticus 13:52

et idcirco comburetur flammis.

** Leviticus 13:53

Quod si eam viderit non crevisse,

** Leviticus 13:54

præcipiet, et lavabunt id in quo lepra est, recludetque illud septem diebus aliis.

** Leviticus 13:55

Et cum viderit faciem quidem pristinam non reversam, nec tamen crevisse lepram, immundum judicabit, et igne comburet, eo quod infusa sit in superficie vestimenti, vel per totum, lepra.

** Leviticus 13:56

Sin autem obscurior fuerit locus lepræ, postquam vestis est lota, abrumpet eum, et a solido dividet.

** Leviticus 13:57

Quod si ultra apparuerit in his locis, quæ prius immaculata erant, lepra volatilis et vaga, debet igne comburi.

** Leviticus 13:58

Si cessaverit, lavabit aqua ea, quæ pura sunt, secundo, et munda erunt.

** Leviticus 13:59

Ista est lex lepræ vestimenti lanei et linei, staminis, atque subtegminis, omnisque supellectilis pelliceæ, quomodo mundari debeat, vel contaminari.   

* Leviticus 14

** Leviticus 14:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 14:2

Hic est ritus leprosi, quando mundandus est. Adducetur ad sacerdotem :

** Leviticus 14:3

qui egressus de castris, cum invenerit lepram esse mundatam,

** Leviticus 14:4

præcipiet ei, qui purificatur, ut offerat duos passeres vivos pro se, quibus vesci licitum est, et lignum cedrinum, vermiculumque et hyssopum.

** Leviticus 14:5

Et unum ex passeribus immolari jubebit in vase fictili super aquas viventes :

** Leviticus 14:6

alium autem vivum cum ligno cedrino, et cocco et hyssopo, tinget in sanguine passeris immolati,

** Leviticus 14:7

quo asperget illum, qui mundandus est, septies, ut jure purgetur : et dimittet passerem vivum, ut in agrum avolet.

** Leviticus 14:8

Cumque laverit homo vestimenta sua, radet omnes pilos corporis, et lavabitur aqua : purificatusque ingredietur castra, ita dumtaxat ut maneat extra tabernaculum suum septem diebus,

** Leviticus 14:9

et die septimo radet capillos capitis, barbamque et supercilia, ac totius corporis pilos. Et lotis rursum vestibus et corpore,

** Leviticus 14:10

die octavo assumet duos agnos immaculatos, et ovem anniculam absque macula, et tres decimas similæ in sacrificium, quæ conspersa sit oleo, et seorsum olei sextarium.

** Leviticus 14:11

Cumque sacerdos purificans hominem, statuerit eum, et hæc omnia coram Domino in ostio tabernaculi testimonii,

** Leviticus 14:12

tollet agnum et offeret eum pro delicto, oleique sextarium : et oblatis ante Dominum omnibus,

** Leviticus 14:13

immolabit agnum, ubi solet immolari hostia pro peccato, et holocaustum, id est, in loco sancto. Sicut enim pro peccato, ita et pro delicto ad sacerdotem pertinet hostia : Sancta sanctorum est.

** Leviticus 14:14

Assumensque sacerdos de sanguine hostiæ, quæ immolata est pro delicto, ponet super extremum auriculæ dextræ ejus qui mundatur, et super pollices manus dextræ et pedis :

** Leviticus 14:15

et de olei sextario mittet in manum suam sinistram,

** Leviticus 14:16

tingetque digitum dextrum in eo, et asperget coram Domino septies.

** Leviticus 14:17

Quod autem reliquum est olei in læva manu, fundet super extremum auriculæ dextræ ejus qui mundatur, et super pollices manus ac pedis dextri, et super sanguinem qui effusus est pro delicto,

** Leviticus 14:18

et super caput ejus.

** Leviticus 14:19

Rogabitque pro eo coram Domino, et faciet sacrificium pro peccato : tunc immolabit holocaustum,

** Leviticus 14:20

et ponet illud in altari cum libamentis suis, et homo rite mundabitur.  

** Leviticus 14:21

Quod si pauper est, et non potest manus ejus invenire quæ dicta sunt pro delicto, assumet agnum ad oblationem, ut roget pro eo sacerdos, decimamque partem similæ conspersæ oleo in sacrificium, et olei sextarium,

** Leviticus 14:22

duosque turtures sive duos pullos columbæ, quorum unus sit pro peccato, et alter in holocaustum :

** Leviticus 14:23

offeretque ea die octavo purificationis suæ sacerdoti, ad ostium tabernaculi testimonii coram Domino.

** Leviticus 14:24

Qui suscipiens agnum pro delicto et sextarium olei, levabit simul :

** Leviticus 14:25

immolatoque agno, de sanguine ejus ponet super extremum auriculæ dextræ illius qui mundatur, et super pollices manus ejus ac pedis dextri :

** Leviticus 14:26

olei vero partem mittet in manum suam sinistram,

** Leviticus 14:27

in quo tingens digitum dextræ manus asperget septies coram Domino :

** Leviticus 14:28

tangetque extremum dextræ auriculæ illius qui mundatur, et pollices manus ac pedis dextri, in loco sanguinis qui effusus est pro delicto :

** Leviticus 14:29

reliquam autem partem olei, quæ est in sinistra manu, mittet super caput purificati, ut placet pro eo Dominum :

** Leviticus 14:30

et turturem sive pullum columbæ offeret,

** Leviticus 14:31

unum pro delicto, et alterum in holocaustum cum libamentis suis.

** Leviticus 14:32

Hoc est sacrificium leprosi, qui habere non potest omnia in emundationem sui.  

** Leviticus 14:33

Locutusque est Dominus ad Moysen et Aaron, dicens :

** Leviticus 14:34

Cum ingressi fueritis terram Chanaan, quam ego dabo vobis in possessionem, si fuerit plaga lepræ in ædibus,

** Leviticus 14:35

ibit cujus est domus, nuntians sacerdoti, et dicet : Quasi plaga lepræ videtur mihi esse in domo mea.

** Leviticus 14:36

At ille præcipiet ut efferant universa de domo, priusquam ingrediatur eam, et videat utrum leprosa sit, ne immunda fiant omnia quæ in domo sunt. Intrabitque postea ut consideret lepram domus :

** Leviticus 14:37

et cum viderit in parietibus illius quasi valliculas pallore sive rubore deformes, et humiliores superficie reliqua,

** Leviticus 14:38

egredietur ostium domus, et statim claudet illam septem diebus.

** Leviticus 14:39

Reversusque die septimo, considerabit eam : si invenerit crevisse lepram,

** Leviticus 14:40

jubebit erui lapides in quibus lepra est, et projici eos extra civitatem in locum immundum :

** Leviticus 14:41

domum autem ipsam radi intrinsecus per circuitum, et spargi pulverem rasuræ extra urbem in locum immundum,

** Leviticus 14:42

lapidesque alios reponi pro his qui ablati fuerint, et luto alio liniri domum.

** Leviticus 14:43

Sin autem postquam eruti sunt lapides, et pulvis erasus, et alia terra lita,

** Leviticus 14:44

ingressus sacerdos viderit reversam lepram, et parietes respersos maculis, lepra est perseverans, et immunda domus :

** Leviticus 14:45

quam statim destruent, et lapides ejus ac ligna, atque universum pulverem projicient extra oppidum in locum immundum.

** Leviticus 14:46

Qui intraverit domum quando clausa est, immundus erit usque ad vesperum :

** Leviticus 14:47

et qui dormierit in ea, et comederit quippiam, lavabit vestimenta sua.  

** Leviticus 14:48

Quod si introiens sacerdos viderit lepram non crevisse in domo, postquam denuo lita fuerit, purificabit eam reddita sanitate :

** Leviticus 14:49

et in purificationem ejus sumet duos passeres, lignumque cedrinum, et vermiculum atque hyssopum :

** Leviticus 14:50

et immolato uno passere in vase fictili super aquas vivas,

** Leviticus 14:51

tollet lignum cedrinum, et hyssopum, et coccum, et passerem vivum, et tinget omnia in sanguine passeris immolati, atque in aquis viventibus, et asperget domum septies,

** Leviticus 14:52

purificabitque eam tam in sanguine passeris quam in aquis viventibus, et in passere vivo, lignoque cedrino et hyssopo atque vermiculo.

** Leviticus 14:53

Cumque dimiserit passerem avolare in agrum libere, orabit pro domo, et jure mundabitur.

** Leviticus 14:54

Ista est lex omnis lepræ et percussuræ,

** Leviticus 14:55

lepræ vestium et domorum,

** Leviticus 14:56

cicatricis et erumpentium papularum, lucentis maculæ, et in varias species, coloribus immutatis,

** Leviticus 14:57

ut possit sciri quo tempore mundum quid, vel immundum sit.   

* Leviticus 15

** Leviticus 15:1

Locutusque est Dominus ad Moysen et Aaron, dicens :

** Leviticus 15:2

Loquimini filiis Israël, et dicite eis : Vir, qui patitur fluxum seminis, immundus erit.

** Leviticus 15:3

Et tunc judicabitur huic vitio subjacere, cum per singula momenta adhæserit carni ejus, atque concreverit fœdus humor.

** Leviticus 15:4

Omne stratum, in quo dormierit, immundum erit, et ubicumque sederit.

** Leviticus 15:5

Si quis hominum tetigerit lectum ejus, lavabit vestimenta sua, et ipse lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:6

Si sederit ubi ille sederat, et ipse lavabit vestimenta sua : et lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:7

Qui tetigerit carnem ejus, lavabit vestimenta sua : et ipse lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:8

Si salivam hujuscemodi homo jecerit super eum qui mundus est, lavabit vestimenta sua : et lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:9

Sagma, super quo sederit, immundum erit :

** Leviticus 15:10

et quidquid sub eo fuerit, qui fluxum seminis patitur, pollutum erit usque ad vesperum. Qui portaverit horum aliquid, lavabit vestimenta sua : et ipse lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:11

Omnis, quem tetigerit qui talis est, non lotis ante manibus, lavabit vestimenta sua, et lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:12

Vas fictile quod tetigerit confringetur : vas autem ligneum lavabitur aqua.  

** Leviticus 15:13

Si sanatus fuerit qui hujuscemodi sustinet passionem, numerabit septem dies post emundationem sui, et lotis vestibus et toto corpore in aquis viventibus, erit mundus.

** Leviticus 15:14

Die autem octavo sumet duos turtures, aut duos pullos columbæ, et veniet in conspectum Domini ad ostium tabernaculi testimonii, dabitque eos sacerdoti :

** Leviticus 15:15

qui faciet unum pro peccato et alterum in holocaustum : rogabitque pro eo coram Domino, ut emundetur a fluxi seminis sui.

** Leviticus 15:16

Vir de quo egreditur semen coitus, lavabit aqua omne corpus suum : et immundus erit usque ad vesperum.

** Leviticus 15:17

Vestem et pellem, quam habuerit, lavabit aqua, et immunda erit usque ad vesperum.

** Leviticus 15:18

Mulier, cum qua coierit, lavabitur aqua, et immunda erit usque ad vesperum.  

** Leviticus 15:19

Mulier, quæ redeunte mense patitur fluxum sanguinis, septem diebus separabitur.

** Leviticus 15:20

Omnis qui tetigerit eam, immundus erit usque ad vesperum :

** Leviticus 15:21

et in quo dormierit vel sederit diebus separationis suæ, polluetur.

** Leviticus 15:22

Qui tetigerit lectum ejus, lavabit vestimenta sua : et ipse lotus aqua, immundus erit usque ad vesperum.

** Leviticus 15:23

Omne vas, super quo illa sederit, quisquis attigerit, lavabit vestimenta sua : et ipse lotus aqua, pollutus erit usque ad vesperum.

** Leviticus 15:24

Si coierit cum ea vir tempore sanguinis menstrualis, immundus erit septem diebus : et omne stratum, in quo dormierit, polluetur.

** Leviticus 15:25

Mulier, quæ patitur multis diebus fluxum sanguinis non in tempore menstruali, vel quæ post menstruum sanguinem fluere non cessat, quamdiu subjacet huic passioni, immunda erit quasi sit in tempore menstruo.

** Leviticus 15:26

Omne stratum, in quo dormierit, et vas in quo sederit, pollutum erit.

** Leviticus 15:27

Quicumque tetigerit ea, lavabit vestimenta sua : et ipse lotus aqua, immundus erit usque ad vesperam.

** Leviticus 15:28

Si steterit sanguis, et fluere cessaverit, numerabit septem dies purificationis suæ :

** Leviticus 15:29

et die octavo offeret pro se sacerdoti duos turtures, aut duos pullos columbarum, ad ostium tabernaculi testimonii :

** Leviticus 15:30

qui unum faciet pro peccato, et alterum in holocaustum, rogabitque pro ea coram Domino, et pro fluxu immunditiæ ejus.

** Leviticus 15:31

Docebitis ergo filios Israël ut caveant immunditiam, et non moriantur in sordibus suis, cum polluerint tabernaculum meum quod est inter eos.

** Leviticus 15:32

Ista est lex ejus, qui patitur fluxum seminis, et qui polluitur coitu,

** Leviticus 15:33

et quæ menstruis temporibus separatur, vel quæ jugi fluit sanguine, et hominis qui dormierit cum ea.   

* Leviticus 16

** Leviticus 16:1

Locutusque est Dominus ad Moysen post mortem duorum filiorum Aaron, quando offerentes ignem alienum interfecti sunt :

** Leviticus 16:2

et præcepit ei, dicens : Loquere ad Aaron fratrem tuum, ne omni tempore ingrediatur sanctuarium, quod est intra velum coram propitiatorio quo tegitur arca, ut non moriatur (quia in nube apparebo super oraculum),

** Leviticus 16:3

nisi hæc ante fecerit : vitulum pro peccato offeret, et arietem in holocaustum.

** Leviticus 16:4

Tunica linea vestietur, feminalibus lineis verenda celabit : accingetur zona linea, cidarim lineam imponet capiti : hæc enim vestimenta sunt sancta : quibus cunctis, cum lotus fuerit, induetur.

** Leviticus 16:5

Suscipietque ab universa multitudine filiorum Israël duos hircos pro peccato, et unum arietem in holocaustum.

** Leviticus 16:6

Cumque obtulerit vitulum, et oraverit pro se et pro domo sua,

** Leviticus 16:7

duos hircos stare faciet coram Domino in ostio tabernaculi testimonii :

** Leviticus 16:8

mittensque super utrumque sortem, unam Domino, alteram capro emissario :

** Leviticus 16:9

cujus exierit sors Domino, offeret illum pro peccato :

** Leviticus 16:10

cujus autem in caprum emissarium, statuet eum vivum coram Domino, ut fundat preces super eo, et emittat eum in solitudinem.  

** Leviticus 16:11

His rite celebratis, offeret vitulum, et rogans pro se, et pro domo sua, immolabit eum :

** Leviticus 16:12

assumptoque thuribulo, quod de prunis altaris impleverit, et hauriens manu compositum thymiama in incensum, ultra velum intrabit in sancta :

** Leviticus 16:13

ut, positis super ignem aromatibus, nebula eorum et vapor operiat oraculum quod est supra testimonium, et non moriatur.

** Leviticus 16:14

Tollet quoque de sanguine vituli, et asperget digito septies contra propitiatorium ad orientem.  

** Leviticus 16:15

Cumque mactaverit hircum pro peccato populi, inferet sanguinem ejus intra velum, sicut præceptum est de sanguine vituli, ut aspergat e regione oraculi,

** Leviticus 16:16

et expiet sanctuarium ab immunditiis filiorum Israël, et a prævaricationibus eorum, cunctisque peccatis. Juxta hunc ritum faciet tabernaculo testimonii, quod fixum est inter eos, in medio sordium habitationis eorum.

** Leviticus 16:17

Nullus hominum sit in tabernaculo, quando pontifex sanctuarium ingreditur, ut roget pro se, et pro domo sua, et pro universo cœtu Israël, donec egrediatur.

** Leviticus 16:18

Cum autem exierit ad altare quod coram Domino est, oret pro se, et sumptum sanguinem vituli atque hirci fundat super cornua ejus per gyrum :

** Leviticus 16:19

aspergensque digito septies, expiet, et sanctificet illud ab immunditiis filiorum Israël.  

** Leviticus 16:20

Postquam emundaverit sanctuarium, et tabernaculum, et altare, tunc offerat hircum viventem :

** Leviticus 16:21

et posita utraque manu super caput ejus, confiteatur omnes iniquitates filiorum Israël, et universa delicta atque peccata eorum : quæ imprecans capiti ejus, emittet illum per hominem paratum, in desertum.

** Leviticus 16:22

Cumque portaverit hircus omnes iniquitates eorum in terram solitariam, et dimissus fuerit in deserto,

** Leviticus 16:23

revertetur Aaron in tabernaculum testimonii, et depositis vestibus, quibus prius indutus erat, cum intraret sanctuarium, relictisque ibi,

** Leviticus 16:24

lavabit carnem suam in loco sancto, indueturque vestibus suis. Et postquam egressus obtulerit holocaustum suum, ac plebis, rogabit tam pro se quam pro populo :

** Leviticus 16:25

et adipem, qui oblatus est pro peccatis, adolebit super altare.

** Leviticus 16:26

Ille vero, qui dimiserit caprum emissarium, lavabit vestimenta sua, et corpus aqua, et sic ingredietur in castra.

** Leviticus 16:27

Vitulum autem, et hircum, qui pro peccato fuerant immolati, et quorum sanguis illatus est in sanctuarium, ut expiatio compleretur, asportabunt foras castra, et comburent igni tam pelles quam carnes eorum, ac fimum :

** Leviticus 16:28

et quicumque combusserit ea, lavabit vestimenta sua et carnem aqua, et sic ingredietur in castra.  

** Leviticus 16:29

Eritque vobis hoc legitimum sempiternum : mense septimo, decima die mensis, affligetis animas vestras, nullumque opus facietis, sive indigena, sive advena qui peregrinatur inter vos.

** Leviticus 16:30

In hac die expiatio erit vestri, atque mundatio ab omnibus peccatis vestris : coram Domino mundabimini.

** Leviticus 16:31

Sabbatum enim requietionis est, et affligetis animas vestras religione perpetua.

** Leviticus 16:32

Expiabit autem sacerdos, qui unctus fuerit, et cujus manus initiatæ sunt ut sacerdotio fungatur pro patre suo : indueturque stola linea et vestibus sanctis,

** Leviticus 16:33

et expiabit sanctuarium et tabernaculum testimonii atque altare, sacerdotes quoque et universum populum.

** Leviticus 16:34

Eritque vobis hoc legitimum sempiternum, ut oretis pro filiis Israël, et pro cunctis peccatis eorum semel in anno. Fecit igitur sicut præceperat Dominus Moysi.   

* Leviticus 17

** Leviticus 17:1

Et locutus est Dominus ad Moysen, dicens :

** Leviticus 17:2

Loquere Aaron et filiis ejus, et cunctis filiis Israël, dicens ad eos : Iste est sermo quem mandavit Dominus, dicens :

** Leviticus 17:3

Homo quilibet de domo Israël, si occiderit bovem aut ovem, sive capram, in castris vel extra castra,

** Leviticus 17:4

et non obtulerit ad ostium tabernaculi oblationem Domino, sanguinis reus erit : quasi si sanguinem fuderit, sic peribit de medio populi sui.

** Leviticus 17:5

Ideo sacerdoti offerre debent filii Israël hostias suas, quas occident in agro, ut sanctificentur Domino ante ostium tabernaculi testimonii, et immolent eas hostias pacificas Domino.

** Leviticus 17:6

Fundetque sacerdos sanguinem super altare Domini ad ostium tabernaculi testimonii, et adolebit adipem in odorem suavitatis Domino :

** Leviticus 17:7

et nequaquam ultra immolabunt hostias suas dæmonibus, cum quibus fornicati sunt. Legitimum sempiternum erit illis et posteris eorum.

** Leviticus 17:8

Et ad ipsos dices : Homo de domo Israël, et de advenis qui peregrinantur apud vos, qui obtulerit holocaustum sive victimam,

** Leviticus 17:9

et ad ostium tabernaculi testimonii non adduxerit eam, ut offeratur Domino, interibit de populo suo.  

** Leviticus 17:10

Homo quilibet de domo Israël et de advenis qui peregrinantur inter eos, si comederit sanguinem, obfirmabo faciem meam contra animam illius, et disperdam eam de populo suo,

** Leviticus 17:11

quia anima carnis in sanguine est : et ego dedi illum vobis, ut super altare in eo expietis pro animabus vestris, et sanguis pro animæ piaculo sit.

** Leviticus 17:12

Idcirco dixi filiis Israël : Omnis anima ex vobis non comedet sanguinem, nec ex advenis qui peregrinantur apud vos.

** Leviticus 17:13

Homo quicumque de filiis Israël, et de advenis qui peregrinantur apud vos, si venatione atque aucupio ceperit feram, vel avem, quibus vesci licitum est, fundat sanguinem ejus, et operiat illum terra.

** Leviticus 17:14

Anima enim omnis carnis in sanguine est : unde dixi filiis Israël : Sanguinem universæ carnis non comedetis, quia anima carnis in sanguine est : et quicumque comederit illum, interibit.

** Leviticus 17:15

Anima, quæ comederit morticinum, vel captum a bestia, tam de indigenis, quam de advenis, lavabit vestimenta sua et semetipsum aqua, et contaminatus erit usque ad vesperum : et hoc ordine mundus fiet.

** Leviticus 17:16

Quod si non laverit vestimenta sua et corpus, portabit iniquitatem suam.   

* Leviticus 18

** Leviticus 18:1

Locutus est Dominus ad Moysen, dicens :

** Leviticus 18:2

Loquere filiis Israël, et dices ad eos : Ego Dominus Deus vester :

** Leviticus 18:3

juxta consuetudinem terræ Ægypti, in qua habitastis, non facietis : et juxta morem regionis Chanaan, ad quam ego introducturus sum vos, non agetis, nec in legitimis eorum ambulabitis.

** Leviticus 18:4

Facietis judicia mea, et præcepta mea servabitis, et ambulabitis in eis. Ego Dominus Deus vester.

** Leviticus 18:5

Custodite leges meas atque judicia, quæ faciens homo, vivet in eis. Ego Dominus.

** Leviticus 18:6

Omnis homo ad proximam sanguinis sui non accedet, ut revelet turpitudinem ejus. Ego Dominus.

** Leviticus 18:7

Turpitudinem patris tui et turpitudinem matris tuæ non discooperies : mater tua est : non revelabis turpitudinem ejus.

** Leviticus 18:8

Turpitudinem uxoris patris tui non discooperies : turpitudo enim patris tui est.

** Leviticus 18:9

Turpitudinem sororis tuæ ex patre sive ex matre, quæ domi vel foris genita est, non revelabis.

** Leviticus 18:10

Turpitudinem filiæ filii tui vel neptis ex filia non revelabis : quia turpitudo tua est.

** Leviticus 18:11

Turpitudinem filiæ uxoris patris tui, quam peperit patri tuo, et est soror tua, non revelabis.

** Leviticus 18:12

Turpitudinem sororis patris tui non discooperies : quia caro est patris tui.

** Leviticus 18:13

Turpitudinem sororis matris tuæ non revelabis, eo quod caro sit matris tuæ.

** Leviticus 18:14

Turpitudinem patrui tui non revelabis, nec accedes ad uxorem ejus, quæ tibi affinitate conjungitur.

** Leviticus 18:15

Turpitudinem nurus tuæ non revelabis, quia uxor filii tui est : nec discooperies ignominiam ejus.

** Leviticus 18:16

Turpitudinem uxoris fratris tui non revelabis : quia turpitudo fratris tui est.

** Leviticus 18:17

Turpitudinem uxoris tuæ et filiæ ejus non revelabis. Filiam filii ejus, et filiam filiæ illius non sumes, ut reveles ignominiam ejus : quia caro illius sunt, et talis coitus incestus est.

** Leviticus 18:18

Sororem uxoris tuæ in pellicatum illius non accipies, nec revelabis turpitudinem ejus adhuc illa vivente.  

** Leviticus 18:19

Ad mulierem quæ patitur menstrua non accedes, nec revelabis fœditatem ejus.

** Leviticus 18:20

Cum uxore proximi tui non coibis, nec seminis commistione maculaberis.

** Leviticus 18:21

De semine tuo non dabis ut consecretur idolo Moloch, nec pollues nomen Dei tui. Ego Dominus.

** Leviticus 18:22

Cum masculo non commiscearis coitu femineo, quia abominatio est.

** Leviticus 18:23

Cum omni pecore non coibis, nec maculaberis cum eo. Mulier non succumbet jumento, nec miscebitur ei, quia scelus est.

** Leviticus 18:24

Nec polluamini in omnibus his quibus contaminatæ sunt universæ gentes, quas ego ejiciam ante conspectum vestrum,

** Leviticus 18:25

et quibus polluta est terra : cujus ego scelera visitabo, ut evomat habitatores suos.

** Leviticus 18:26

Custodite legitima mea atque judicia, et non faciatis ex omnibus abominationibus istis, tam indigena quam colonus qui peregrinantur apud vos.

** Leviticus 18:27

Omnes enim execrationes istas fecerunt accolæ terræ qui fuerunt ante vos, et polluerunt eam.

** Leviticus 18:28

Cavete ergo ne et vos similiter evomat, cum paria feceritis, sicut evomuit gentem, quæ fuit ante vos.

** Leviticus 18:29

Omnis anima, quæ fecerit de abominationibus his quippiam, peribit de medio populi sui.

** Leviticus 18:30

Custodite mandata mea. Nolite facere quæ fecerunt hi qui fuerunt ante vos, et ne polluamini in eis. Ego Dominus Deus vester.   

* Leviticus 19

** Leviticus 19:1

Locutus est Dominus ad Moysen, dicens :

** Leviticus 19:2

Loquere ad omnem cœtum filiorum Israël, et dices ad eos : Sancti estote, quia ego sanctus sum, Dominus Deus vester.

** Leviticus 19:3

Unusquisque patrem suum, et matrem suam timeat. Sabbata mea custodite. Ego Dominus Deus vester.

** Leviticus 19:4

Nolite converti ad idola, nec deos conflatiles faciatis vobis. Ego Dominus Deus vester.

** Leviticus 19:5

Si immolaveritis hostiam pacificorum Domino, ut sit placabilis,

** Leviticus 19:6

eo die quo fuerit immolata, comedetis eam, et die altero : quidquid autem residuum fuerit in diem tertium, igne comburetis.

** Leviticus 19:7

Si quis post biduum comederit ex ea, profanus erit, et impietatis reus :

** Leviticus 19:8

portabitque iniquitatem suam, quia sanctum Domini polluit, et peribit anima illa de populo suo.  

** Leviticus 19:9

Cumque messueris segetes terræ tuæ, non tondebis usque ad solum superficiem terræ, nec remanentes spicas colliges,

** Leviticus 19:10

neque in vinea tua racemos et grana decidentia congregabis : sed pauperibus et peregrinis carpenda dimittes. Ego Dominus Deus vester.

** Leviticus 19:11

Non facietis furtum. Non mentiemini, nec decipiet unusquisque proximum suum.

** Leviticus 19:12

Non perjurabis in nomine meo, nec pollues nomen Dei tui. Ego Dominus.

** Leviticus 19:13

Non facies calumniam proximo tuo nec vi opprimes eum. Non morabitur opus mercenarii tui apud te usque mane.

** Leviticus 19:14

Non maledices surdo, nec coram cæco pones offendiculum : sed timebis Dominum Deum tuum, quia ego sum Dominus.

** Leviticus 19:15

Non facies quod iniquum est, nec injuste judicabis. Non consideres personam pauperis, nec honores vultum potentis. Juste judica proximo tuo.

** Leviticus 19:16

Non eris criminator, nec susurro in populo. Non stabis contra sanguinem proximi tui. Ego Dominus.

** Leviticus 19:17

Non oderis fratrem tuum in corde tuo, sed publice argue eum, ne habeas super illo peccatum.

** Leviticus 19:18

Non quæras ultionem, nec memor eris injuriæ civium tuorum. Diliges amicum tuum sicut teipsum. Ego Dominus.  

** Leviticus 19:19

Leges meas custodite. Jumentum tuum non facies coire cum alterius generis animantibus. Agrum tuum non seres diverso semine. Veste, quæ ex duobus texta est, non indueris.

** Leviticus 19:20

Homo, si dormierit cum muliere coitu seminis, quæ sit ancilla etiam nubilis, et tamen pretio non redempta, nec libertate donata : vapulabunt ambo, et non morientur, quia non fuit libera.

** Leviticus 19:21

Pro delicto autem suo offeret Domino ad ostium tabernaculi testimonii arietem :

** Leviticus 19:22

orabitque pro eo sacerdos, et pro peccato ejus coram Domino, et repropitiabitur ei, dimitteturque peccatum.

** Leviticus 19:23

Quando ingressi fueritis terram, et plantaveritis in ea ligna pomifera, auferetis præputia eorum : poma, quæ germinant, immunda erunt vobis, nec edetis ex eis.

** Leviticus 19:24

Quarto autem anno omnis fructus eorum sanctificabitur, laudabilis Domino.

** Leviticus 19:25

Quinto autem anno comedetis fructus, congregantes poma, quæ proferunt. Ego Dominus Deus vester.

** Leviticus 19:26

Non comedetis cum sanguine. Non augurabimini, nec observabitis somnia.

** Leviticus 19:27

Neque in rotundum attondebitis comam, nec radetis barbam.

** Leviticus 19:28

Et super mortuo non incidetis carnem vestram, neque figuras aliquas aut stigmata facietis vobis. Ego Dominus.

** Leviticus 19:29

Ne prostituas filiam tuam, ne contaminetur terra et impleatur piaculo.

** Leviticus 19:30

Sabbata mea custodite, et sanctuarium meum metuite. Ego Dominus.

** Leviticus 19:31

Non declinetis ad magos, nec ab ariolis aliquid sciscitemini, ut polluamini per eos. Ego Dominus Deus vester.

** Leviticus 19:32

Coram cano capite consurge, et honora personam senis : et time Dominum Deum tuum. Ego sum Dominus.  

** Leviticus 19:33

Si habitaverit advena in terra vestra, et moratus fuerit inter vos, non exprobretis ei :

** Leviticus 19:34

sed sit inter vos quasi indigena, et diligetis eum quasi vosmetipsos : fuistis enim et vos advenæ in terra Ægypti. Ego Dominus Deus vester.  

** Leviticus 19:35

Nolite facere iniquum aliquid in judicio, in regula, in pondere, in mensura.

** Leviticus 19:36

Statera justa, et æqua sint pondera, justus modius, æquusque sextarius. Ego Dominus Deus vester, qui eduxi vos de terra Ægypti.

** Leviticus 19:37

Custodite omnia præcepta mea, et universa judicia, et facite ea. Ego Dominus.   

* Leviticus 20

** Leviticus 20:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 20:2

Hæc loqueris filiis Israël : Homo de filiis Israël, et de advenis qui habitant in Israël, si quis dederit de semine suo idolo Moloch, morte moriatur : populus terræ lapidabit eum.

** Leviticus 20:3

Et ego ponam faciem meam contra illum : succidamque eum de medio populi sui, eo quod dederit de semine suo Moloch, et contaminaverit sanctuarium meum, ac polluerit nomen sanctum meum.

** Leviticus 20:4

Quod si negligens populus terræ, et quasi parvipendens imperium meum, dimiserit hominem qui dedit de semine suo Moloch, nec voluerit eum occidere :

** Leviticus 20:5

ponam faciem meam super hominem illum, et super cognationem ejus, succidamque et ipsum, et omnes qui consenserunt ei ut fornicarentur cum Moloch, de medio populi sui.

** Leviticus 20:6

Anima, quæ declinaverit ad magos et ariolos, et fornicata fuerit cum eis, ponam faciem meam contra eam, et interficiam illam de medio populi sui.

** Leviticus 20:7

Sanctificamini et estote sancti, quia ego sum Dominus Deus vester.

** Leviticus 20:8

Custodite præcepta mea, et facite ea : ego Dominus qui sanctifico vos.

** Leviticus 20:9

Qui maledixerit patri suo, aut matri, morte moriatur : patri matrique maledixit : sanguis ejus sit super eum.  

** Leviticus 20:10

Si mœchatus quis fuerit cum uxore alterius, et adulterium perpetraverit cum conjuge proximi sui, morte moriantur et mœchus et adultera.

** Leviticus 20:11

Qui dormierit cum noverca sua, et revelaverit ignominiam patris sui, morte moriantur ambo : sanguis eorum sit super eos.

** Leviticus 20:12

Si quis dormierit cum nuru sua, uterque moriatur, quia scelus operati sunt : sanguis eorum sit super eos.

** Leviticus 20:13

Qui dormierit cum masculo coitu femineo, uterque operatus est nefas : morte moriantur : sit sanguis eorum super eos.

** Leviticus 20:14

Qui supra uxorem filiam, duxerit matrem ejus, scelus operatus est : vivus ardebit cum eis, nec permanebit tantum nefas in medio vestri.

** Leviticus 20:15

Qui cum jumento et pecore coierit, morte moriatur : pecus quoque occidite.

** Leviticus 20:16

Mulier, quæ succubuerit cuilibet jumento, simul interficietur cum eo : sanguis eorum sit super eos.

** Leviticus 20:17

Qui acceperit sororem suam filiam patris sui, vel filiam matris suæ, et viderit turpitudinem ejus, illaque conspexerit fratris ignominiam, nefariam rem operati sunt : occidentur in conspectu populi sui, eo quod turpitudinem suam mutuo revelaverint, et portabunt iniquitatem suam.

** Leviticus 20:18

Qui coierit cum muliere in fluxu menstruo, et revelaverit turpitudinem ejus, ipsaque aperuerit fontem sanguinis sui, interficientur ambo de medio populi sui.

** Leviticus 20:19

Turpitudinem materteræ et amitæ tuæ non discooperies : qui hoc fecerit, ignominiam carnis suæ nudavit ; portabunt ambo iniquitatem suam.

** Leviticus 20:20

Qui coierit cum uxore patrui vel avunculi sui, et revelaverit ignominiam cognationis suæ, portabunt ambo peccatum suum : absque liberis morientur.

** Leviticus 20:21

Qui duxerit uxorem fratris sui, rem facit illicitam : turpitudinem fratris sui revelavit : absque liberis erunt.  

** Leviticus 20:22

Custodite leges meas, atque judicia, et facite ea : ne et vos evomat terra quam intraturi estis et habitaturi.

** Leviticus 20:23

Nolite ambulare in legitimis nationum, quas ego expulsurus sum ante vos. Omnia enim hæc fecerunt, et abominatus sum eas.

** Leviticus 20:24

Vobis autem loquor. Possidete terram eorum, quam dabo vobis in hæreditatem, terram fluentem lacte et melle. Ego Dominus Deus vester, qui separavi vos a ceteris populis.

** Leviticus 20:25

Separate ergo et vos jumentum mundum ab immundo, et avem mundam ab immunda : ne polluatis animas vestras in pecore, et avibus, et cunctis quæ moventur in terra, et quæ vobis ostendi esse polluta.

** Leviticus 20:26

Eritis mihi sancti, quia sanctus sum ego Dominus, et separavi vos a ceteris populis, ut essetis mei.

** Leviticus 20:27

Vir, sive mulier, in quibus pythonicus, vel divinationis fuerit spiritus, morte moriantur : lapidibus obruent eos : sanguis eorum sit super illos.   

* Leviticus 21

** Leviticus 21:1

Dixit quoque Dominus ad Moysen : Loquere ad sacerdotes filios Aaron, et dices ad eos : Ne contaminetur sacerdos in mortibus civium suorum,

** Leviticus 21:2

nisi tantum in consanguineis, ac propinquis, id est, super patre et matre, et filio, et filia, fratre quoque,

** Leviticus 21:3

et sorore virgine quæ non est nupta viro :

** Leviticus 21:4

sed nec in principe populi sui contaminabitur.

** Leviticus 21:5

Non radent caput, nec barbam, neque in carnibus suis facient incisuras.

** Leviticus 21:6

Sancti erunt Deo suo, et non polluent nomen ejus : incensum enim Domini, et panes Dei sui offerunt, et ideo sancti erunt.

** Leviticus 21:7

Scortum et vile prostibulum non ducent uxorem, nec eam quæ repudiata est a marito : quia consecrati sunt Deo suo,

** Leviticus 21:8

et panes propositionis offerunt. Sint ergo sancti, quia et ego sanctus sum, Dominus qui sanctifico eos.

** Leviticus 21:9

Sacerdotis filia si deprehensa fuerit in stupro, et violaverit nomen patris sui, flammis exuretur.  

** Leviticus 21:10

Pontifex, id est, sacerdos maximus inter fratres suos, super cujus caput fusum est unctionis oleum, et cujus manus in sacerdotio consecratæ sunt, vestitusque est sanctis vestibus, caput suum non discooperiet, vestimenta non scindet :

** Leviticus 21:11

et ad omnem mortuum non ingredietur omnino : super patre quoque suo et matre non contaminabitur.

** Leviticus 21:12

Nec egredietur de sanctis, ne polluat sanctuarium Domini, quia oleum sanctæ unctionis Dei sui super eum est. Ego Dominus.

** Leviticus 21:13

Virginem ducet uxorem :

** Leviticus 21:14

viduam autem et repudiatam, et sordidam, atque meretricem non accipiet, sed puellam de populo suo :

** Leviticus 21:15

ne commisceat stirpem generis sui vulgo gentis suæ : quia ego Dominus, qui sanctifico eum.

** Leviticus 21:16

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 21:17

Loquere ad Aaron : Homo de semine tuo per familias qui habuerit maculam, non offeret panes Deo suo,

** Leviticus 21:18

nec accedet ad ministerium ejus : si cæcus fuerit, si claudus, si parvo vel grandi, vel torto naso,

** Leviticus 21:19

si fracto pede, si manu,

** Leviticus 21:20

si gibbus, si lippus, si albuginem habens in oculo, si jugem scabiem, si impetiginem in corpore, vel herniosus.

** Leviticus 21:21

Omnis qui habuerit maculam de semine Aaron sacerdotis, non accedet offerre hostias Domino, nec panes Deo suo :

** Leviticus 21:22

vescetur tamen panibus qui offeruntur in sanctuario,

** Leviticus 21:23

ita dumtaxat, ut intra velum non ingrediatur, nec accedat ad altare, quia maculam habet, et contaminare non debet sanctuarium meum. Ego Dominus qui sanctifico eos.

** Leviticus 21:24

Locutus est ergo Moyses ad Aaron, et ad filios ejus, et ad omnem Israël cuncta quæ fuerant sibi imperata.   

* Leviticus 22

** Leviticus 22:1

Locutus quoque est Dominus ad Moysen, dicens :

** Leviticus 22:2

Loquere ad Aaron et ad filios ejus, ut caveant ab his quæ consecrata sunt filiorum Israël, et non contaminent nomen sanctificatorum mihi, quæ ipsi offerunt. Ego Dominus.

** Leviticus 22:3

Dic ad eos, et ad posteros eorum : Omnis homo qui accesserit de stirpe vestra ad ea quæ consecrata sunt, et quæ obtulerunt filii Israël Domino, in quo est immunditia, peribit coram Domino. Ego sum Dominus.

** Leviticus 22:4

Homo de semine Aaron, qui fuerit leprosus, aut patiens fluxum seminis, non vescetur de his quæ sanctificata sunt mihi, donec sanetur. Qui tetigerit immundum super mortuo, et ex quo egreditur semen quasi coitus,

** Leviticus 22:5

et qui tangit reptile, et quodlibet immundum cujus tactus est sordidus,

** Leviticus 22:6

immundus erit usque ad vesperum, et non vescetur his quæ sanctificata sunt : sed cum laverit carnem suam aqua,

** Leviticus 22:7

et occubuerit sol, tunc mundatus vescetur de sanctificatis, quia cibus illius est.

** Leviticus 22:8

Morticinum et captum a bestia non comedent, nec polluentur in eis. Ego sum Dominus.

** Leviticus 22:9

Custodiant præcepta mea, ut non subjaceant peccato, et moriantur in sanctuario, cum polluerint illud. Ego Dominus qui sanctifico eos.

** Leviticus 22:10

Omnis alienigena non comedet de sanctificatis ; inquilinus sacerdotis et mercenarius non vescentur ex eis.

** Leviticus 22:11

Quem autem sacerdos emerit, et qui vernaculus domus ejus fuerit, his comedent ex eis.

** Leviticus 22:12

Si filia sacerdotis cuilibet ex populo nupta fuerit, de his quæ sanctificata sunt, et de primitiis non vescetur.

** Leviticus 22:13

Sin autem vidua, vel repudiata, et absque liberis reversa fuerit ad domum patris sui : sicut puella consueverat, aletur cibis patris sui. Omnis alienigena comedendi ex eis non habet potestatem.

** Leviticus 22:14

Qui comederit de sanctificatis per ignorantiam, addet quintam partem cum eo quod comedit, et dabit sacerdoti in sanctuarium.

** Leviticus 22:15

Nec contaminabunt sanctificata filiorum Israël, quæ offerunt Domino :

** Leviticus 22:16

ne forte sustineant iniquitatem delicti sui, cum sanctificata comederint. Ego Dominus qui sanctifico eos.  

** Leviticus 22:17

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 22:18

Loquere ad Aaron et filios ejus, et ad omnes filios Israël, dicesque ad eos : Homo de domo Israël, et de advenis qui habitant apud vos, qui obtulerit oblationem suam, vel vota solvens, vel sponte offerens, quidquid illud obtulerit in holocaustum Domini,

** Leviticus 22:19

ut offeratur per vos, masculus immaculatus erit ex bobus, et ovibus, et ex capris :

** Leviticus 22:20

si maculam habuerit, non offeretis, neque erit acceptabile.

** Leviticus 22:21

Homo qui obtulerit victimam pacificorum Domino, vel vota solvens, vel sponte offerens, tam de bobus quam de ovibus, immaculatum offeret ut acceptabile sit : omnis macula non erit in eo.

** Leviticus 22:22

Si cæcum fuerit, si fractum, si cicatricem habens, si papulas, aut scabiem, aut impetiginem : non offeretis ea Domino, nec adolebitis ex eis super altare Domini.

** Leviticus 22:23

Bovem et ovem, aure et cauda amputatis, voluntarie offerre potes, votum autem ex eis solvi non potest.

** Leviticus 22:24

Omne animal, quod vel contritis, vel tusis, vel sectis ablatisque testiculis est, non offeretis Domino, et in terra vestra hoc omnino ne faciatis.

** Leviticus 22:25

De manu alienigenæ non offeretis panes Deo vestro, et quidquid aliud dare voluerit, quia corrupta, et maculata sunt omnia : non suscipietis ea.

** Leviticus 22:26

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 22:27

Bos, ovis et capra, cum genita fuerint, septem diebus erunt sub ubere matris suæ : die autem octavo, et deinceps, offerri poterunt Domino.

** Leviticus 22:28

Sive illa bos, sive ovis, non immolabuntur una die cum fœtibus suis.

** Leviticus 22:29

Si immolaveritis hostiam pro gratiarum actione Domino, ut possit esse placabilis,

** Leviticus 22:30

eodem die comedetis eam : non remanebit quidquam in mane alterius diei. Ego Dominus.

** Leviticus 22:31

Custodite mandata mea, et facite ea. Ego Dominus.

** Leviticus 22:32

Ne polluatis nomen meum sanctum, ut sanctificer in medio filiorum Israël. Ego Dominus qui sanctifico vos,

** Leviticus 22:33

et eduxi de terra Ægypti, ut essem vobis in Deum. Ego Dominus.   

* Leviticus 23

** Leviticus 23:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 23:2

Loquere filiis Israël, et dices ad eos : Hæ sunt feriæ Domini, quas vocabitis sanctas.

** Leviticus 23:3

Sex diebus facietis opus : dies septimus, quia sabbati requies est, vocabitur sanctus : omne opus non facietis in eo : sabbatum Domini est in cunctis habitationibus vestris.

** Leviticus 23:4

Hæ sunt ergo feriæ Domini sanctæ, quas celebrare debetis temporibus suis.  

** Leviticus 23:5

Mense primo, quartadecima die mensis ad vesperum, Phase Domini est :

** Leviticus 23:6

et quintadecima die mensis hujus, solemnitas azymorum Domini est. Septem diebus azyma comedetis.

** Leviticus 23:7

Dies primus erit vobis celeberrimus, sanctusque : omne opus servile non facietis in eo,

** Leviticus 23:8

sed offeretis sacrificium in igne Domino septem diebus. Dies autem septimus erit celebrior et sanctior : nullumque servile opus facietis in eo.

** Leviticus 23:9

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 23:10

Loquere filiis Israël, et dices ad eos : Cum ingressi fueritis terram, quam ego dabo vobis, et messueritis segetem, feretis manipulos spicarum, primitias messis vestræ, ad sacerdotem :

** Leviticus 23:11

qui elevabit fasciculum coram Domino, ut acceptabile sit pro vobis, altero die sabbati, et sanctificabit illum.

** Leviticus 23:12

Atque in eodem die quo manipulus consecratur, cædetur agnus immaculatus anniculus in holocaustum Domini.

** Leviticus 23:13

Et libamenta offerentur cum eo, duæ decimæ similæ conspersæ oleo in incensum Domini, odoremque suavissimum : liba quoque vini, quarta pars hin.

** Leviticus 23:14

Panem, et polentam, et pultes non comedetis ex segete, usque ad diem qua offeretis ex ea Deo vestro. Præceptum est sempiternum in generationibus, cunctisque habitaculis vestris.  

** Leviticus 23:15

Numerabitis ergo ab altero die sabbati, in quo obtulistis manipulum primitiarum, septem hebdomadas plenas,

** Leviticus 23:16

usque ad alteram diem expletionis hebdomadæ septimæ, id est, quinquaginta dies : et sic offeretis sacrificium novum Domino

** Leviticus 23:17

ex omnibus habitaculis vestris, panes primitiarum duos de duabus decimis similæ fermentatæ, quos coquetis in primitias Domini.

** Leviticus 23:18

Offeretisque cum panibus septem agnos immaculatos anniculos, et vitulum de armento unum, et arietes duos, et erunt in holocaustum cum libamentis suis, in odorem suavissimum Domini.

** Leviticus 23:19

Facietis et hircum pro peccato, duosque agnos anniculos hostias pacificorum.

** Leviticus 23:20

Cumque elevaverit eos sacerdos cum panibus primitiarum coram Domino, cedent in usum ejus.

** Leviticus 23:21

Et vocabitis hunc diem celeberrimum, atque sanctissimum : omne opus servile non facietis in eo. Legitimum sempiternum erit in cunctis habitaculis, et generationibus vestris.

** Leviticus 23:22

Postquam autem messueritis segetem terræ vestræ, nec secabitis eam usque ad solum, nec remanentes spicas colligetis : sed pauperibus et peregrinis dimittetis eas. Ego sum Dominus Deus vester.  

** Leviticus 23:23

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 23:24

Loquere filiis Israël : Mense septimo, prima die mensis, erit vobis sabbatum, memoriale, clangentibus tubis, et vocabitur sanctum :

** Leviticus 23:25

omne opus servile non facietis in eo, et offeretis holocaustum Domino.  

** Leviticus 23:26

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 23:27

Decimo die mensis hujus septimi, dies expiationum erit celeberrimus, et vocabitur sanctus : affligetisque animas vestras in eo, et offeretis holocaustum Domino.

** Leviticus 23:28

Omne opus servile non facietis in tempore diei hujus : quia dies propitiationis est, ut propitietur vobis Dominus Deus vester.

** Leviticus 23:29

Omnis anima, quæ afflicta non fuerit die hac, peribit de populis suis :

** Leviticus 23:30

et quæ operis quippiam fecerit, delebo eam de populo suo.

** Leviticus 23:31

Nihil ergo operis facietis in eo : legitimum sempiternum erit vobis in cunctis generationibus, et habitationibus vestris.

** Leviticus 23:32

Sabbatum requietionis est, et affligetis animas vestras die nono mensis : a vespera usque ad vesperam celebrabitis sabbata vestra.  

** Leviticus 23:33

Et locutus est Dominus ad Moysen, dicens :

** Leviticus 23:34

Loquere filiis Israël : A quintodecimo die mensis hujus septimi, erunt feriæ tabernaculorum septem diebus Domino.

** Leviticus 23:35

Dies primus vocabitur celeberrimus atque sanctissimus : omne opus servile non facietis in eo.

** Leviticus 23:36

Et septem diebus offeretis holocausta Domino. Dies quoque octavus erit celeberrimus, atque sanctissimus, et offeretis holocaustum Domino : est enim cœtus atque collectæ : omne opus servile non facietis in eo.

** Leviticus 23:37

Hæ sunt feriæ Domini, quas vocabitis celeberrimas atque sanctissimas, offeretisque in eis oblationes Domino, holocausta et libamenta juxta ritum uniuscujusque diei :

** Leviticus 23:38

exceptis sabbatis Domini, donisque vestris, et quæ offeretis ex voto, vel quæ sponte tribuetis Domino.

** Leviticus 23:39

A quintodecimo ergo die mensis septimi, quando congregaveritis omnes fructus terræ vestræ, celebrabitis ferias Domini septem diebus : die primo et die octavo erit sabbatum, id est, requies.

** Leviticus 23:40

Sumetisque vobis die primo fructus arboris pulcherrimæ, spatulasque palmarum, et ramos ligni densarum frondium, et salices de torrente, et lætabimini coram Domino Deo vestro.

** Leviticus 23:41

Celebrabitisque solemnitatem ejus septem diebus per annum : legitimum sempiternum erit in generationibus vestris. Mense septimo festa celebrabitis,

** Leviticus 23:42

et habitabitis in umbraculis septem diebus : omnis, qui de genere est Israël, manebit in tabernaculis,

** Leviticus 23:43

ut discant posteri vestri quod in tabernaculis habitare fecerim filios Israël, cum educerem eos de terra Ægypti. Ego Dominus Deus vester.

** Leviticus 23:44

Locutusque est Moyses super solemnitatibus Domini ad filios Israël.   

* Leviticus 24

** Leviticus 24:1

Et locutus est Dominus ad Moysen, dicens :

** Leviticus 24:2

Præcipe filiis Israël, ut afferant tibi oleum de olivis purissimum, ac lucidum, ad concinnandas lucernas jugiter,

** Leviticus 24:3

extra velum testimonii in tabernaculo fœderis. Ponetque eas Aaron a vespere usque ad mane coram Domino, cultu rituque perpetuo in generationibus vestris.

** Leviticus 24:4

Super candelabrum mundissimum ponentur semper in conspectu Domini.

** Leviticus 24:5

Accipies quoque similam, et coques ex ea duodecim panes, qui singuli habebunt duas decimas :

** Leviticus 24:6

quorum senos altrinsecus super mensam purissimam coram Domino statues :

** Leviticus 24:7

et pones super eos thus lucidissimum, ut sit panis in monimentum oblationis Domini.

** Leviticus 24:8

Per singula sabbata mutabuntur coram Domino suscepti a filiis Israël fœdere sempiterno :

** Leviticus 24:9

eruntque Aaron et filiorum ejus, ut comedant eos in loco sancto : quia Sanctum sanctorum est de sacrificiis Domini jure perpetuo.  

** Leviticus 24:10

Ecce autem egressus filius mulieris Israëlitidis, quem pepererat de viro ægyptio inter filios Israël, jurgatus est in castris cum viro Israëlita.

** Leviticus 24:11

Cumque blasphemasset nomen, et maledixisset ei, adductus est ad Moysen. (Vocabatur autem mater ejus Salumith, filia Dabri de tribu Dan.)

** Leviticus 24:12

Miseruntque eum in carcerem, donec nossent quid juberet Dominus.

** Leviticus 24:13

Qui locutus est ad Moysen,

** Leviticus 24:14

dicens : Educ blasphemum extra castra, et ponant omnes qui audierunt, manus suas super caput ejus, et lapidet eum populus universus.

** Leviticus 24:15

Et ad filios Israël loqueris : Homo, qui maledixerit Deo suo, portabit peccatum suum ;

** Leviticus 24:16

et qui blasphemaverit nomen Domini, morte moriatur : lapidibus opprimet eum omnis multitudo, sive ille civis, sive peregrinus fuerit. Qui blasphemaverit nomen Domini, morte moriatur.  

** Leviticus 24:17

Qui percusserit, et occiderit hominem, morte moriatur.

** Leviticus 24:18

Qui percusserit animal, reddet vicarium, id est, animam pro anima.

** Leviticus 24:19

Qui irrogaverit maculam cuilibet civium suorum, sicut fecit, sic fiet ei :

** Leviticus 24:20

fracturam pro fractura, oculum pro oculo, dentem pro dente restituet : qualem inflixerit maculam, talem sustinere cogetur.

** Leviticus 24:21

Qui percusserit jumentum, reddet aliud. Qui percusserit hominem, punietur.

** Leviticus 24:22

Æquum judicium sit inter vos, sive peregrinus, sive civis peccaverit : quia ego sum Dominus Deus vester.

** Leviticus 24:23

Locutusque est Moyses ad filios Israël : et eduxerunt eum, qui blasphemaverat, extra castra, ac lapidibus oppresserunt. Feceruntque filii Israël sicut præceperat Dominus Moysi.   

* Leviticus 25

** Leviticus 25:1

Locutusque est Dominus ad Moysen in monte Sinai, dicens :

** Leviticus 25:2

Loquere filiis Israël, et dices ad eos : Quando ingressi fueritis terram quam ego dabo vobis, sabbatizes sabbatum Domino.

** Leviticus 25:3

Sex annis seres agrum tuum, et sex annis putabis vineam tuam, colligesque fructus ejus :

** Leviticus 25:4

septimo autem anno sabbatum erit terræ, requietionis Domini : agrum non seres, et vineam non putabis.

** Leviticus 25:5

Quæ sponte gignet humus, non metes : et uvas primitiarum tuarum non colliges quasi vindemiam : annus enim requietionis terræ est :

** Leviticus 25:6

sed erunt vobis in cibum, tibi et servo tuo, ancillæ et mercenario tuo, et advenæ qui peregrinantur apud te :

** Leviticus 25:7

jumentis tuis et pecoribus, omnia quæ nascuntur præbebunt cibum.  

** Leviticus 25:8

Numerabis quoque tibi septem hebdomadas annorum, id est, septies septem, quæ simul faciunt annos quadraginta novem :

** Leviticus 25:9

et clanges buccina mense septimo, decima die mensis, propitiationis tempore, in universa terra vestra.

** Leviticus 25:10

Sanctificabisque annum quinquagesimum, et vocabis remissionem cunctis habitatoribus terræ tuæ : ipse est enim jubilæus. Revertetur homo ad possessionem suam, et unusquisque rediet ad familiam pristinam :

** Leviticus 25:11

quia jubilæus est, et quinquagesimus annus. Non seretis neque metetis sponte in agro nascentia, et primitias vindemiæ non colligetis,

** Leviticus 25:12

ob sanctificationem jubilæi : sed statim oblata comedetis.  

** Leviticus 25:13

Anno jubilæi, redient omnes ad possessiones suas.

** Leviticus 25:14

Quando vendes quippiam civi tuo, vel emes ab eo, ne contristes fratrem tuum, sed juxta numerum annorum jubilæi emes ab eo,

** Leviticus 25:15

et juxta supputationem frugum vendet tibi.

** Leviticus 25:16

Quanto plures anni remanserint post jubilæum, tanto crescet et pretium : et quanto minus temporis numeraveris, tanto minoris et emptio constabit : tempus enim frugum vendet tibi.

** Leviticus 25:17

Nolite affligere contribules vestros, sed timeat unusquisque Deum suum, quia ego Dominus Deus vester.

** Leviticus 25:18

Facite præcepta mea, et judicia custodite, et implete ea : ut habitare possitis in terra absque ullo pavore,

** Leviticus 25:19

et gignat vobis humus fructus suos, quibus vescamini usque ad saturitatem, nullius impetum formidantes.

** Leviticus 25:20

Quod si dixeritis : Quid comedemus anno septimo, si non severimus, neque collegerimus fruges nostras ?

** Leviticus 25:21

dabo benedictionem meam vobis anno sexto, et faciet fructus trium annorum :

** Leviticus 25:22

seretisque anno octavo, et comedetis veteres fruges usque ad nonum annum : donec nova nascantur, edetis vetera.

** Leviticus 25:23

Terra quoque non vendetur in perpetuum, quia mea est, et vos advenæ et coloni mei estis :

** Leviticus 25:24

unde cuncta regio possessionis vestræ sub redemptionis conditione vendetur.

** Leviticus 25:25

Si attenuatus frater tuus vendiderit possessiunculam suam, et voluerit propinquus ejus, potest redimere quod ille vendiderat.

** Leviticus 25:26

Sin autem non habuerit proximum, et ipse pretium ad redimendum potuerit invenire,

** Leviticus 25:27

computabuntur fructus ex eo tempore quo vendidit : et quod reliquum est, reddet emptori, sicque recipiet possessionem suam.

** Leviticus 25:28

Quod si non invenerit manus ejus ut reddat pretium, habebit emptor quod emerat, usque ad annum jubilæum. In ipso enim omnis venditio redibit ad dominum et ad possessorem pristinum.

** Leviticus 25:29

Qui vendiderit domum intra urbis muros, habebit licentiam redimendi, donec unus impleatur annus.

** Leviticus 25:30

Si non redemerit, et anni circulus fuerit evolutus, emptor possidebit eam, et posteri ejus in perpetuum, et redimi non poterit, etiam in jubilæo.

** Leviticus 25:31

Sin autem in villa domus, quæ muros non habet, agrorum jure vendetur : si ante redempta non fuerit, in jubilæo revertetur ad dominum.

** Leviticus 25:32

Ædes Levitarum quæ in urbibus sunt, semper possunt redimi :

** Leviticus 25:33

si redemptæ non fuerint, in jubilæo revertentur ad dominos, quia domus urbium Levitarum pro possessionibus sunt inter filios Israël.

** Leviticus 25:34

Suburbana autem eorum non veneant, quia possessio sempiterna est.  

** Leviticus 25:35

Si attenuatus fuerit frater tuus, et infirmus manu, et susceperis eum quasi advenam et peregrinum, et vixerit tecum,

** Leviticus 25:36

ne accipias usuras ab eo, nec amplius quam dedisti : time Deum tuum, ut vivere possit frater tuus apud te.

** Leviticus 25:37

Pecuniam tuam non dabis ei ad usuram, et frugum superabundantiam non exiges.

** Leviticus 25:38

Ego Dominus Deus vester, qui eduxi vos de terra Ægypti, ut darem vobis terram Chanaan, et essem vester Deus.  

** Leviticus 25:39

Si paupertate compulsus vendiderit se tibi frater tuus, non eum opprimes servitute famulorum,

** Leviticus 25:40

sed quasi mercenarius et colonus erit : usque ad annum jubilæum operabitur apud te,

** Leviticus 25:41

et postea egredietur cum liberis suis, et revertetur ad cognationem, ad possessionem patrum suorum.

** Leviticus 25:42

Mei enim servi sunt, et ego eduxi eos de terra Ægypti : non veneant conditione servorum :

** Leviticus 25:43

ne affligas eum per potentiam, sed metuito Deum tuum.

** Leviticus 25:44

Servus et ancilla sint vobis de nationibus quæ in circuitu vestro sunt :

** Leviticus 25:45

et de advenis qui peregrinantur apud vos, vel qui ex his nati fuerint in terra vestra, hos habebitis famulos :

** Leviticus 25:46

et hæreditario jure transmittetis ad posteros, ac possidebitis in æternum : fratres autem vestros filios Israël ne opprimatis per potentiam.

** Leviticus 25:47

Si invaluerit apud vos manus advenæ atque peregrini, et attenuatus frater tuus vendiderit se ei, aut cuiquam de stirpe ejus :

** Leviticus 25:48

post venditionem potest redimi. Qui voluerit ex fratribus suis, redimet eum,

** Leviticus 25:49

et patruus, et patruelis, et consanguineus, et affinis. Sin autem et ipse potuerit, redimet se,

** Leviticus 25:50

supputatis dumtaxat annis a tempore venditionis suæ usque ad annum jubilæum : et pecunia, qua venditus fuerat, juxta annorum numerum, et rationem mercenarii supputata.

** Leviticus 25:51

Si plures fuerint anni qui remanent usque ad jubilæum, secundum hos reddet et pretium :

** Leviticus 25:52

si pauci, ponet rationem cum eo juxta annorum numerum, et reddet emptori quod reliquum est annorum,

** Leviticus 25:53

quibus ante servivit mercedibus imputatis : non affliget eum violenter in conspectu tuo.

** Leviticus 25:54

Quod si per hæc redimi non potuerit, anno jubilæo egredietur cum liberis suis.

** Leviticus 25:55

Mei enim sunt servi filii Israël, quos eduxi de terra Ægypti.   

* Leviticus 26

** Leviticus 26:1

Ego Dominus Deus vester : non facietis vobis idolum, et sculptile, nec titulos erigetis, nec insignem lapidem ponetis in terra vestra, ut adoretis eum. Ego enim sum Dominus Deus vester.

** Leviticus 26:2

Custodite sabbata mea, et pavete ad sanctuarium meum. Ego Dominus.

** Leviticus 26:3

Si in præceptis meis ambulaveritis, et mandata mea custodieritis, et feceritis ea, dabo vobis pluvias temporibus suis,

** Leviticus 26:4

et terra gignet germen suum, et pomis arbores replebuntur.

** Leviticus 26:5

Apprehendet messium tritura vindemiam, et vindemia occupabit sementem : et comedetis panem vestrum in saturitate, et absque pavore habitabitis in terra vestra.

** Leviticus 26:6

Dabo pacem in finibus vestris : dormietis, et non erit qui exterreat. Auferam malas bestias, et gladius non transibit terminos vestros.

** Leviticus 26:7

Persequemini inimicos vestros, et corruent coram vobis.

** Leviticus 26:8

Persequentur quinque de vestris centum alienos, et centum de vobis decem millia : cadent inimici vestri gladio in conspectu vestro.

** Leviticus 26:9

Respiciam vos, et crescere faciam : multiplicabimini, et firmabo pactum meum vobiscum.

** Leviticus 26:10

Comedetis vetustissima veterum, et vetera novis supervenientibus projicietis.

** Leviticus 26:11

Ponam tabernaculum meum in medio vestri, et non abjiciet vos anima mea.

** Leviticus 26:12

Ambulabo inter vos, et ero Deus vester, vosque eritis populus meus.

** Leviticus 26:13

Ego Dominus Deus vester, qui eduxi vos de terra Ægyptiorum, ne serviretis eis : et qui confregi catenas cervicum vestrarum, ut incederetis erecti.  

** Leviticus 26:14

Quod si non audieritis me, nec feceritis omnia mandata mea,

** Leviticus 26:15

si spreveritis leges meas, et judicia mea contempseritis, ut non faciatis ea quæ a me constituta sunt, et ad irritum perducatis pactum meum :

** Leviticus 26:16

ego quoque hæc faciam vobis : visitabo vos velociter in egestate, et ardore, qui conficiat oculos vestros, et consumat animas vestras. Frustra seretis sementem, quæ ab hostibus devorabitur.

** Leviticus 26:17

Ponam faciem meam contra vos, et corruetis coram hostibus vestris, et subjiciemini his qui oderunt vos : fugietis, nemine persequente.

** Leviticus 26:18

Sin autem nec sic obedieritis mihi, addam correptiones vestras septuplum propter peccata vestra,

** Leviticus 26:19

et conteram superbiam duritiæ vestræ. Daboque vobis cælum desuper sicut ferrum, et terram æneam.

** Leviticus 26:20

Consumetur incassum labor vester, non proferet terra germen, nec arbores poma præbebunt.

** Leviticus 26:21

Si ambulaveritis ex adverso mihi, nec volueritis audire me, addam plagas vestras in septuplum propter peccata vestra :

** Leviticus 26:22

immittamque in vos bestias agri, quæ consumant vos, et pecora vestra, et ad paucitatem cuncta redigant, desertæque fiant viæ vestræ.

** Leviticus 26:23

Quod si nec sic volueritis recipere disciplinam, sed ambulaveritis ex adverso mihi :

** Leviticus 26:24

ego quoque contra vos adversus incedam, et percutiam vos septies propter peccata vestra,

** Leviticus 26:25

inducamque super vos gladium ultorem fœderis mei. Cumque confugeritis in urbes, mittam pestilentiam in medio vestri, et trademini in manibus hostium,

** Leviticus 26:26

postquam confregero baculum panis vestri : ita ut decem mulieres in uno clibano coquant panes, et reddant eos ad pondus : et comedetis, et non saturabimini.  

** Leviticus 26:27

Sin autem nec per hæc audieritis me, sed ambulaveritis contra me :

** Leviticus 26:28

et ego incedam adversus vos in furore contrario, et corripiam vos septem plagis propter peccata vestra :

** Leviticus 26:29

ita ut comedatis carnes filiorum vestrorum et filiarum vestrarum.

** Leviticus 26:30

Destruam excelsa vestra, et simulacra confringam. Cadetis inter ruinas idolorum vestrorum, et abominabitur vos anima mea,

** Leviticus 26:31

in tantum ut urbes vestras redigam in solitudinem, et deserta faciam sanctuaria vestra, nec recipiam ultra odorem suavissimum.

** Leviticus 26:32

Disperdamque terram vestram, et stupebunt super ea inimici vestri, cum habitatores illius fuerint.

** Leviticus 26:33

Vos autem dispergam in gentes, et evaginabo post vos gladium, eritque terra vestra deserta, et civitates vestræ dirutæ.

** Leviticus 26:34

Tunc placebunt terræ sabbata sua cunctis diebus solitudinis suæ : quando fueritis

** Leviticus 26:35

in terra hostili, sabbatizabit, et requiescet in sabbatis solitudinis suæ, eo quod non requieverit in sabbatis vestris quando habitabatis in ea.

** Leviticus 26:36

Et qui de vobis remanserint, dabo pavorem in cordibus eorum in regionibus hostium, terrebit eos sonitus folii volantis, et ita fugient quasi gladium : cadent, nullo persequente,

** Leviticus 26:37

et corruent singuli super fratres suos, quasi bella fugientes, nemo vestrum inimicis audebit resistere.

** Leviticus 26:38

Peribitis inter gentes, et hostilis vos terra consumet.

** Leviticus 26:39

Quod si et de iis aliqui remanserint, tabescent in iniquitatibus suis, in terra inimicorum suorum, et propter peccata patrum suorum et sua affligentur :

** Leviticus 26:40

donec confiteantur iniquitates suas, et majorum suorum, quibus prævaricati sunt in me, et ambulaverunt ex adverso mihi.

** Leviticus 26:41

Ambulabo igitur et ego contra eos, et inducam illos in terram hostilem, donec erubescat incircumcisa mens eorum : tunc orabunt pro impietatibus suis.  

** Leviticus 26:42

Et recordabor fœderis mei, quod pepigi cum Jacob, et Isaac, et Abraham. Terræ quoque memor ero :

** Leviticus 26:43

quæ cum relicta fuerit ab eis, complacebit sibi in sabbatis suis, patiens solitudinem propter illos. Ipsi vero rogabunt pro peccatis suis, eo quod abjecerint judicia mea, et leges meas despexerint.

** Leviticus 26:44

Et tamen etiam cum essent in terra hostili, non penitus abjeci eos, neque sic despexi ut consumerentur, et irritum facerent pactum meum cum eis. Ego enim sum Dominus Deus eorum,

** Leviticus 26:45

et recordabor fœderis mei pristini, quando eduxi eos de terra Ægypti in conspectu gentium, ut essem Deus eorum. Ego Dominus.   Hæc sunt judicia atque præcepta et leges quas dedit Dominus inter se et filios Israël in monte Sinai per manum Moysi.   

* Leviticus 27

** Leviticus 27:1

Locutusque est Dominus ad Moysen, dicens :

** Leviticus 27:2

Loquere filiis Israël, et dices ad eos : Homo qui votum fecerit, et spoponderit Deo animam suam, sub æstimatione dabit pretium.

** Leviticus 27:3

Si fuerit masculus a vigesimo anno usque ad sexagesimum annum, dabit quinquaginta siclos argenti ad mensuram sanctuarii :

** Leviticus 27:4

si mulier, triginta.

** Leviticus 27:5

A quinto autem anno usque ad vigesimum, masculus dabit viginti siclos : femina, decem.

** Leviticus 27:6

Ab uno mense usque ad annum quintum, pro masculo dabuntur quinque sicli : pro femina, tres.

** Leviticus 27:7

Sexagenarius et ultra masculus dabit quindecim siclos : femina, decem.

** Leviticus 27:8

Si pauper fuerit, et æstimationem reddere non valebit, stabit coram sacerdote : et quantum ille æstimaverit, et viderit eum posse reddere, tantum dabit.  

** Leviticus 27:9

Animal autem, quod immolari potest Domino, si quis voverit, sanctum erit,

** Leviticus 27:10

et mutari non poterit, id est, nec melius malo, nec pejus bono : quod si mutaverit, et ipsum quod mutatum est, et illud pro quo mutatum est, consecratum erit Domino.

** Leviticus 27:11

Animal immundum, quod immolari Domino non potest, si quis voverit, adducetur ante sacerdotem :

** Leviticus 27:12

qui judicans utrum bonum an malum sit, statuet pretium.

** Leviticus 27:13

Quod si dare voluerit is qui offert, addet supra æstimationem quintam partem.  

** Leviticus 27:14

Homo si voverit domum suam, et sanctificaverit Domino, considerabit eam sacerdos utrum bona an mala sit, et juxta pretium, quod ab eo fuerit constitutum, venundabitur :

** Leviticus 27:15

sin autem ille qui voverat, voluerit redimere eam, dabit quintam partem æstimationis supra, et habebit domum.

** Leviticus 27:16

Quod si agrum possessionis suæ voverit, et consecraverit Domino, juxta mensuram sementis æstimabitur pretium : si triginta modiis hordei seritur terra, quinquaginta siclis venundetur argenti.

** Leviticus 27:17

Si statim ab anno incipientis jubilæi voverit agrum, quanto valere potest, tanto æstimabitur.

** Leviticus 27:18

Sin autem post aliquantum temporis, supputabit sacerdos pecuniam juxta annorum, qui reliqui sunt, numerum usque ad jubilæum, et detrahetur ex pretio.

** Leviticus 27:19

Quod si voluerit redimere agrum ille qui voverat, addet quintam partem æstimatæ pecuniæ, et possidebit eum.

** Leviticus 27:20

Sin autem noluerit redimere, sed alteri cuilibet fuerit venundatus, ultra eum qui voverat redimere non poterit.

** Leviticus 27:21

Quia cum jubilæi venerit dies, sanctificatus erit Domino, et possessio consecrata ad jus pertinet sacerdotum.

** Leviticus 27:22

Si ager emptus est, et non de possessione majorum sanctificatus fuerit Domino,

** Leviticus 27:23

supputabit sacerdos juxta annorum numerum usque ad jubilæum, pretium : et dabit ille qui voverat eum, Domino.

** Leviticus 27:24

In jubilæo autem revertetur ad priorem dominum, qui vendiderat eum, et habuerat in sorte possessionis suæ.

** Leviticus 27:25

Omnis æstimatio siclo sanctuarii ponderabitur. Siclus viginti obolos habet.  

** Leviticus 27:26

Primogenita, quæ ad Dominum pertinent, nemo sanctificare poterit et vovere : sive bos, sive ovis fuerit, Domini sunt.

** Leviticus 27:27

Quod si immundum est animal, redimet qui obtulit, juxta æstimationem tuam, et addet quintam partem pretii : si redimere noluerit, vendetur alteri quantocumque a te fuerit æstimatum.

** Leviticus 27:28

Omne quod Domino consecratur, sive homo fuerit, sive animal, sive ager, non vendetur, nec redimi poterit. Quidquid semel fuerit consecratum, Sanctum sanctorum erit Domino :

** Leviticus 27:29

et omnis consecratio, quæ offertur ab homine, non redimetur, sed morte morietur.  

** Leviticus 27:30

Omnes decimæ terræ, sive de frugibus, sive de pomis arborum, Domini sunt, et illi sanctificantur.

** Leviticus 27:31

Si quis autem voluerit redimere decimas suas, addet quintam partem earum.

** Leviticus 27:32

Omnium decimarum bovis et ovis et capræ, quæ sub pastoris virga transeunt, quidquid decimum venerit, sanctificabitur Domino.

** Leviticus 27:33

Non eligetur nec bonum nec malum, nec altero commutabitur, si quis mutaverit : et quod mutatum est, et pro quo mutatum est, sanctificabitur Domino, et non redimetur.  

** Leviticus 27:34

Hæc sunt præcepta, quæ mandavit Dominus Moysi ad filios Israël in monte Sinai.    

