* Luke 1

** Luke 1:1

Quoniam quidem multi conati sunt ordinare narrationem, quæ in nobis completæ sunt, rerum :

** Luke 1:2

sicut tradiderunt nobis, qui ab initio ipsi viderunt, et ministri fuerunt sermonis :

** Luke 1:3

visum est et mihi, assecuto omnia a principio diligenter, ex ordine tibi scribere, optime Theophile,

** Luke 1:4

ut cognoscas eorum verborum, de quibus eruditus es, veritatem.  

** Luke 1:5

Fuit in diebus Herodis, regis Judææ, sacerdos quidam nomine Zacharias de vice Abia, et uxor illius de filiabus Aaron, et nomen ejus Elisabeth.

** Luke 1:6

Erant autem justi ambo ante Deum, incedentes in omnibus mandatis et justificationibus Domini sine querela.

** Luke 1:7

Et non erat illis filius, eo quod esset Elisabeth sterilis, et ambo processissent in diebus suis.

** Luke 1:8

Factum est autem, cum sacerdotio fungeretur in ordine vicis suæ ante Deum,

** Luke 1:9

secundum consuetudinem sacerdotii, sorte exiit ut incensum poneret, ingressus in templum Domini :

** Luke 1:10

et omnis multitudo populi erat orans foris hora incensi.

** Luke 1:11

Apparuit autem illi angelus Domini, stans a dextris altaris incensi.

** Luke 1:12

Et Zacharias turbatus est videns, et timor irruit super eum.

** Luke 1:13

Ait autem ad illum angelus : Ne timeas, Zacharia, quoniam exaudita est deprecatio tua : et uxor tua Elisabeth pariet tibi filium, et vocabis nomen ejus Joannem :

** Luke 1:14

et erit gaudium tibi, et exsultatio, et multi in nativitate ejus gaudebunt :

** Luke 1:15

erit enim magnus coram Domino : et vinum et siceram non bibet, et Spiritu Sancto replebitur adhuc ex utero matris suæ :

** Luke 1:16

et multos filiorum Israël convertet ad Dominum Deum ipsorum :

** Luke 1:17

et ipse præcedet ante illum in spiritu et virtute Eliæ : ut convertat corda patrum in filios, et incredulos ad prudentiam justorum, parare Domino plebem perfectam.

** Luke 1:18

Et dixit Zacharias ad angelum : Unde hoc sciam ? ego enim sum senex, et uxor mea processit in diebus suis.

** Luke 1:19

Et respondens angelus dixit ei : Ego sum Gabriel, qui asto ante Deum : et missus sum loqui ad te, et hæc tibi evangelizare.

** Luke 1:20

Et ecce eris tacens, et non poteris loqui usque in diem quo hæc fiant, pro eo quod non credidisti verbis meis, quæ implebuntur in tempore suo.

** Luke 1:21

Et erat plebs exspectans Zachariam : et mirabantur quod tardaret ipse in templo.

** Luke 1:22

Egressus autem non poterat loqui ad illos, et cognoverunt quod visionem vidisset in templo. Et ipse erat innuens illis, et permansit mutus.

** Luke 1:23

Et factum est, ut impleti sunt dies officii ejus, abiit in domum suam :

** Luke 1:24

post hos autem dies concepit Elisabeth uxor ejus, et occultabat se mensibus quinque, dicens :

** Luke 1:25

Quia sic fecit mihi Dominus in diebus, quibus respexit auferre opprobrium meum inter homines.  

** Luke 1:26

In mense autem sexto, missus est angelus Gabriel a Deo in civitatem Galilææ, cui nomen Nazareth,

** Luke 1:27

ad virginem desponsatam viro, cui nomen erat Joseph, de domo David : et nomen virginis Maria.

** Luke 1:28

Et ingressus angelus ad eam dixit : Ave gratia plena : Dominus tecum : benedicta tu in mulieribus.

** Luke 1:29

Quæ cum audisset, turbata est in sermone ejus, et cogitabat qualis esset ista salutatio.

** Luke 1:30

Et ait angelus ei : Ne timeas, Maria : invenisti enim gratiam apud Deum.

** Luke 1:31

Ecce concipies in utero, et paries filium, et vocabis nomen ejus Jesum :

** Luke 1:32

hic erit magnus, et Filius Altissimi vocabitur, et dabit illi Dominus Deus sedem David patris ejus : et regnabit in domo Jacob in æternum,

** Luke 1:33

et regni ejus non erit finis.

** Luke 1:34

Dixit autem Maria ad angelum : Quomodo fiet istud, quoniam virum non cognosco ?

** Luke 1:35

Et respondens angelus dixit ei : Spiritus Sanctus superveniet in te, et virtus Altissimi obumbrabit tibi. Ideoque et quod nascetur ex te sanctum, vocabitur Filius Dei.

** Luke 1:36

Et ecce Elisabeth cognata tua, et ipsa concepit filium in senectute sua : et hic mensis sextus est illi, quæ vocatur sterilis :

** Luke 1:37

quia non erit impossibile apud Deum omne verbum.

** Luke 1:38

Dixit autem Maria : Ecce ancilla Domini : fiat mihi secundum verbum tuum. Et discessit ab illa angelus.  

** Luke 1:39

Exsurgens autem Maria in diebus illis, abiit in montana cum festinatione, in civitatem Juda :

** Luke 1:40

et intravit in domum Zachariæ, et salutavit Elisabeth.

** Luke 1:41

Et factum est, ut audivit salutationem Mariæ Elisabeth, exsultavit infans in utero ejus : et repleta est Spiritu Sancto Elisabeth :

** Luke 1:42

et exclamavit voce magna, et dixit : Benedicta tu inter mulieres, et benedictus fructus ventris tui.

** Luke 1:43

Et unde hoc mihi, ut veniat mater Domini mei ad me ?

** Luke 1:44

Ecce enim ut facta est vox salutationis tuæ in auribus meis, exsultavit in gaudio infans in utero meo.

** Luke 1:45

Et beata, quæ credidisti, quoniam perficientur ea, quæ dicta sunt tibi a Domino.

** Luke 1:46

Et ait Maria :   Magnificat anima mea Dominum : 

** Luke 1:47

et exsultavit spiritus meus in Deo salutari meo. 

** Luke 1:48

Quia respexit humilitatem ancillæ suæ :  ecce enim ex hoc beatam me dicent omnes generationes, 

** Luke 1:49

quia fecit mihi magna qui potens est :  et sanctum nomen ejus, 

** Luke 1:50

et misericordia ejus a progenie in progenies  timentibus eum. 

** Luke 1:51

Fecit potentiam in brachio suo :  dispersit superbos mente cordis sui. 

** Luke 1:52

Deposuit potentes de sede,  et exaltavit humiles. 

** Luke 1:53

Esurientes implevit bonis :  et divites dimisit inanes. 

** Luke 1:54

Suscepit Israël puerum suum,  recordatus misericordiæ suæ : 

** Luke 1:55

sicut locutus est ad patres nostros,  Abraham et semini ejus in sæcula.

** Luke 1:56

Mansit autem Maria cum illa quasi mensibus tribus : et reversa est in domum suam.  

** Luke 1:57

Elisabeth autem impletum est tempus pariendi, et peperit filium.

** Luke 1:58

Et audierunt vicini et cognati ejus quia magnificavit Dominus misericordiam suam cum illa, et congratulabantur ei.

** Luke 1:59

Et factum est in die octavo, venerunt circumcidere puerum, et vocabant eum nomine patris sui Zachariam.

** Luke 1:60

Et respondens mater ejus, dixit : Nequaquam, sed vocabitur Joannes.

** Luke 1:61

Et dixerunt ad illam : Quia nemo est in cognatione tua, qui vocetur hoc nomine.

** Luke 1:62

Innuebant autem patri ejus, quem vellet vocari eum.

** Luke 1:63

Et postulans pugillarem scripsit, dicens : Joannes est nomen ejus. Et mirati sunt universi.

** Luke 1:64

Apertum est autem illico os ejus, et lingua ejus, et loquebatur benedicens Deum.

** Luke 1:65

Et factus est timor super omnes vicinos eorum : et super omnia montana Judææ divulgabantur omnia verba hæc :

** Luke 1:66

et posuerunt omnes qui audierant in corde suo, dicentes : Quis, putas, puer iste erit ? etenim manus Domini erat cum illo.

** Luke 1:67

Et Zacharias pater ejus repletus est Spiritu Sancto : et prophetavit, dicens :  

** Luke 1:68

Benedictus Dominus Deus Israël,  quia visitavit, et fecit redemptionem plebis suæ : 

** Luke 1:69

et erexit cornu salutis nobis  in domo David pueri sui, 

** Luke 1:70

sicut locutus est per os sanctorum,  qui a sæculo sunt, prophetarum ejus : 

** Luke 1:71

salutem ex inimicis nostris,  et de manu omnium qui oderunt nos : 

** Luke 1:72

ad faciendam misericordiam cum patribus nostris :  et memorari testamenti sui sancti : 

** Luke 1:73

jusjurandum, quod juravit ad Abraham patrem nostrum,  daturum se nobis 

** Luke 1:74

ut sine timore, de manu inimicorum nostrorum liberati,  serviamus illi 

** Luke 1:75

in sanctitate et justitia coram ipso,  omnibus diebus nostris. 

** Luke 1:76

Et tu puer, propheta Altissimi vocaberis :  præibis enim ante faciem Domini parare vias ejus, 

** Luke 1:77

ad dandam scientiam salutis plebi ejus  in remissionem peccatorum eorum 

** Luke 1:78

per viscera misericordiæ Dei nostri,  in quibus visitavit nos, oriens ex alto : 

** Luke 1:79

illuminare his qui in tenebris et in umbra mortis sedent :  ad dirigendos pedes nostros in viam pacis.

** Luke 1:80

Puer autem crescebat, et confortabatur spiritu : et erat in desertis usque in diem ostensionis suæ ad Israël.  

* Luke 2

** Luke 2:1

Factum est autem in diebus illis, exiit edictum a Cæsare Augusto ut describeretur universus orbis.

** Luke 2:2

Hæc descriptio prima facta est a præside Syriæ Cyrino :

** Luke 2:3

et ibant omnes ut profiterentur singuli in suam civitatem.

** Luke 2:4

Ascendit autem et Joseph a Galilæa de civitate Nazareth in Judæam, in civitatem David, quæ vocatur Bethlehem : eo quod esset de domo et familia David,

** Luke 2:5

ut profiteretur cum Maria desponsata sibi uxore prægnante.

** Luke 2:6

Factum est autem, cum essent ibi, impleti sunt dies ut pareret.

** Luke 2:7

Et peperit filium suum primogenitum, et pannis eum involvit, et reclinavit eum in præsepio : quia non erat eis locus in diversorio.

** Luke 2:8

Et pastores erant in regione eadem vigilantes, et custodientes vigilias noctis super gregem suum.

** Luke 2:9

Et ecce angelus Domini stetit juxta illos, et claritas Dei circumfulsit illos, et timuerunt timore magno.

** Luke 2:10

Et dixit illis angelus : Nolite timere : ecce enim evangelizo vobis gaudium magnum, quod erit omni populo :

** Luke 2:11

quia natus est vobis hodie Salvator, qui est Christus Dominus, in civitate David.

** Luke 2:12

Et hoc vobis signum : invenietis infantem pannis involutum, et positum in præsepio.

** Luke 2:13

Et subito facta est cum angelo multitudo militiæ cælestis laudantium Deum, et dicentium :  

** Luke 2:14

Gloria in altissimis Deo,  et in terra pax hominibus bonæ voluntatis.

** Luke 2:15

Et factum est, ut discesserunt ab eis angeli in cælum : pastores loquebantur ad invicem : Transeamus usque Bethlehem, et videamus hoc verbum, quod factum est, quod Dominus ostendit nobis.

** Luke 2:16

Et venerunt festinantes : et invenerunt Mariam, et Joseph, et infantem positum in præsepio.

** Luke 2:17

Videntes autem cognoverunt de verbo, quod dictum erat illis de puero hoc.

** Luke 2:18

Et omnes qui audierunt, mirati sunt : et de his quæ dicta erant a pastoribus ad ipsos.

** Luke 2:19

Maria autem conservabat omnia verba hæc, conferens in corde suo.

** Luke 2:20

Et reversi sunt pastores glorificantes et laudantes Deum in omnibus quæ audierant et viderant, sicut dictum est ad illos.  

** Luke 2:21

Et postquam consummati sunt dies octo, ut circumcideretur puer, vocatum est nomen ejus Jesus, quod vocatum est ab angelo priusquam in utero conciperetur.

** Luke 2:22

Et postquam impleti sunt dies purgationis ejus secundum legem Moysi, tulerunt illum in Jerusalem, ut sisterent eum Domino,

** Luke 2:23

sicut scriptum est in lege Domini : Quia omne masculinum adaperiens vulvam, sanctum Domino vocabitur :

** Luke 2:24

et ut darent hostiam secundum quod dictum est in lege Domini, par turturum, aut duos pullos columbarum.

** Luke 2:25

Et ecce homo erat in Jerusalem, cui nomen Simeon, et homo iste justus, et timoratus, exspectans consolationem Israël : et Spiritus Sanctus erat in eo.

** Luke 2:26

Et responsum acceperat a Spiritu Sancto, non visurum se mortem, nisi prius videret Christum Domini.

** Luke 2:27

Et venit in spiritu in templum. Et cum inducerent puerum Jesum parentes ejus, ut facerent secundum consuetudinem legis pro eo,

** Luke 2:28

et ipse accepit eum in ulnas suas : et benedixit Deum, et dixit :  

** Luke 2:29

Nunc dimittis servum tuum Domine,  secundum verbum tuum in pace : 

** Luke 2:30

quia viderunt oculi mei salutare tuum, 

** Luke 2:31

quod parasti ante faciem omnium populorum : 

** Luke 2:32

lumen ad revelationem gentium,  et gloriam plebis tuæ Israël.

** Luke 2:33

Et erat pater ejus et mater mirantes super his quæ dicebantur de illo.

** Luke 2:34

Et benedixit illis Simeon, et dixit ad Mariam matrem ejus : Ecce positus est hic in ruinam et in resurrectionem multorum in Israël, et in signum cui contradicetur :

** Luke 2:35

et tuam ipsius animam pertransibit gladius ut revelentur ex multis cordibus cogitationes.

** Luke 2:36

Et erat Anna prophetissa, filia Phanuel, de tribu Aser : hæc processerat in diebus multis, et vixerat cum viro suo annis septem a virginitate sua.

** Luke 2:37

Et hæc vidua usque ad annos octoginta quatuor : quæ non discedebat de templo, jejuniis et obsecrationibus serviens nocte ac die.

** Luke 2:38

Et hæc, ipsa hora superveniens, confitebatur Domino : et loquebatur de illo omnibus, qui exspectabant redemptionem Israël.

** Luke 2:39

Et ut perfecerunt omnia secundum legem Domini, reversi sunt in Galilæam in civitatem suam Nazareth.  

** Luke 2:40

Puer autem crescebat, et confortabatur plenus sapientia : et gratia Dei erat in illo.

** Luke 2:41

Et ibant parentes ejus per omnes annos in Jerusalem, in die solemni Paschæ.

** Luke 2:42

Et cum factus esset annorum duodecim, ascendentibus illis Jerosolymam secundum consuetudinem diei festi,

** Luke 2:43

consummatisque diebus, cum redirent, remansit puer Jesus in Jerusalem, et non cognoverunt parentes ejus.

** Luke 2:44

Existimantes autem illum esse in comitatu, venerunt iter diei, et requirebant eum inter cognatos et notos.

** Luke 2:45

Et non invenientes, regressi sunt in Jerusalem, requirentes eum.

** Luke 2:46

Et factum est, post triduum invenerunt illum in templo sedentem in medio doctorum, audientem illos, et interrogantem eos.

** Luke 2:47

Stupebant autem omnes qui eum audiebant, super prudentia et responsis ejus.

** Luke 2:48

Et videntes admirati sunt. Et dixit mater ejus ad illum : Fili, quid fecisti nobis sic ? ecce pater tuus et ego dolentes quærebamus te.

** Luke 2:49

Et ait ad illos : Quid est quod me quærebatis ? nesciebatis quia in his quæ Patris mei sunt, oportet me esse ?

** Luke 2:50

Et ipsi non intellexerunt verbum quod locutus est ad eos.

** Luke 2:51

Et descendit cum eis, et venit Nazareth : et erat subditus illis. Et mater ejus conservabat omnia verba hæc in corde suo.

** Luke 2:52

Et Jesus proficiebat sapientia, et ætate, et gratia apud Deum et homines.   

* Luke 3

** Luke 3:1

Anno autem quintodecimo imperii Tiberii Cæsaris, procurante Pontio Pilato Judæam, tetrarcha autem Galilææ Herode, Philippo autem fratre ejus tetrarcha Iturææ, et Trachonitidis regionis, et Lysania Abilinæ tetrarcha,

** Luke 3:2

sub principibus sacerdotum Anna et Caipha : factum est verbum Domini super Joannem, Zachariæ filium, in deserto.

** Luke 3:3

Et venit in omnem regionem Jordanis, prædicans baptismum pœnitentiæ in remissionem peccatorum,

** Luke 3:4

sicut scriptum est in libro sermonum Isaiæ prophetæ :   Vox clamantis in deserto :  Parate viam Domini ; rectas facite semitas ejus : 

** Luke 3:5

omnis vallis implebitur,  et omnis mons, et collis humiliabitur :  et erunt prava in directa, et aspera in vias planas : 

** Luke 3:6

et videbit omnis caro salutare Dei.

** Luke 3:7

Dicebat ergo ad turbas quæ exibant ut baptizarentur ab ipso : Genimina viperarum, quis ostendit vobis fugere a ventura ira ?

** Luke 3:8

Facite ergo fructus dignos pœnitentiæ, et ne cœperitis dicere : Patrem habemus Abraham. Dico enim vobis quia potens est Deus de lapidibus istis suscitare filios Abrahæ.

** Luke 3:9

Jam enim securis ad radicem arborum posita est. Omnis ergo arbor non faciens fructum bonum, excidetur, et in ignem mittetur.

** Luke 3:10

Et interrogabant eum turbæ, dicentes : Quid ergo faciemus ?

** Luke 3:11

Respondens autem dicebat illis : Qui habet duas tunicas, det non habenti : et qui habet escas, similiter faciat.

** Luke 3:12

Venerunt autem et publicani ut baptizarentur, et dixerunt ad illum : Magister, quid faciemus ?

** Luke 3:13

At ille dixit ad eos : Nihil amplius, quam quod constitutum est vobis, faciatis.

** Luke 3:14

Interrogabant autem eum et milites, dicentes : Quid faciemus et nos ? Et ait illis : Neminem concutiatis, neque calumniam faciatis : et contenti estote stipendiis vestris.

** Luke 3:15

Existimante autem populo, et cogitantibus omnibus in cordibus suis de Joanne, ne forte ipse esset Christus,

** Luke 3:16

respondit Joannes, dicens omnibus : Ego quidem aqua baptizo vos : veniet autem fortior me, cujus non sum dignus solvere corrigiam calceamentorum ejus : ipse vos baptizabit in Spiritu Sancto et igni :

** Luke 3:17

cujus ventilabrum in manu ejus, et purgabit aream suam, et congregabit triticum in horreum suum, paleas autem comburet igni inextinguibili.

** Luke 3:18

Multa quidem et alia exhortans evangelizabat populo.  

** Luke 3:19

Herodes autem tetrarcha cum corriperetur ab illo de Herodiade uxore fratris sui, et de omnibus malis quæ fecit Herodes,

** Luke 3:20

adjecit et hoc super omnia, et inclusit Joannem in carcere.  

** Luke 3:21

Factum est autem cum baptizaretur omnis populus, et Jesu baptizato, et orante, apertum est cælum :

** Luke 3:22

et descendit Spiritus Sanctus corporali specie sicut columba in ipsum : et vox de cælo facta est : Tu es filius meus dilectus, in te complacui mihi.

** Luke 3:23

Et ipse Jesus erat incipiens quasi annorum triginta, ut putabatur, filius Joseph, qui fuit Heli, qui fuit Mathat,

** Luke 3:24

qui fuit Levi, qui fuit Melchi, qui fuit Janne, qui fuit Joseph,

** Luke 3:25

qui fuit Mathathiæ, qui fuit Amos, qui fuit Nahum, qui fuit Hesli, qui fuit Nagge,

** Luke 3:26

qui fuit Mahath, qui fuit Mathathiæ, qui fuit Semei, qui fuit Joseph, qui fuit Juda,

** Luke 3:27

qui fuit Joanna, qui fuit Resa, qui fuit Zorobabel, qui fuit Salathiel, qui fuit Neri,

** Luke 3:28

qui fuit Melchi, qui fuit Addi, qui fuit Cosan, qui fuit Elmadan, qui fuit Her,

** Luke 3:29

qui fuit Jesu, qui fuit Eliezer, qui fuit Jorim, qui fuit Mathat, qui fuit Levi,

** Luke 3:30

qui fuit Simeon, qui fuit Juda, qui fuit Joseph, qui fuit Jona, qui fuit Eliakim,

** Luke 3:31

qui fuit Melea, qui fuit Menna, qui fuit Mathatha, qui fuit Natham, qui fuit David,

** Luke 3:32

qui fuit Jesse, qui fuit Obed, qui fuit Booz, qui fuit Salmon, qui fuit Naasson,

** Luke 3:33

qui fuit Aminadab, qui fuit Aram, qui fuit Esron, qui fuit Phares, qui fuit Judæ,

** Luke 3:34

qui fuit Jacob, qui fuit Isaac, qui fuit Abrahæ, qui fuit Thare, qui fuit Nachor,

** Luke 3:35

qui fuit Sarug, qui fuit Ragau, qui fuit Phaleg, qui fuit Heber, qui fuit Sale,

** Luke 3:36

qui fuit Cainan, qui fuit Arphaxad, qui fuit Sem, qui fuit Noë, qui fuit Lamech,

** Luke 3:37

qui fuit Methusale, qui fuit Henoch, qui fuit Jared, qui fuit Malaleel, qui fuit Cainan,

** Luke 3:38

qui fuit Henos, qui fuit Seth, qui fuit Adam, qui fuit Dei.   

* Luke 4

** Luke 4:1

Jesus autem plenus Spiritu Sancto regressus est a Jordane : et agebatur a Spiritu in desertum

** Luke 4:2

diebus quadraginta, et tentabatur a diabolo. Et nihil manducavit in diebus illis : et consummatis illis esuriit.

** Luke 4:3

Dixit autem illi diabolus : Si Filius Dei es, dic lapidi huic ut panis fiat.

** Luke 4:4

Et respondit ad illum Jesus : Scriptum est : Quia non in solo pane vivit homo, sed in omni verbo Dei.

** Luke 4:5

Et duxit illum diabolus in montem excelsum, et ostendit illi omnia regna orbis terræ in momento temporis,

** Luke 4:6

et ait illi : Tibi dabo potestatem hanc universam, et gloriam illorum : quia mihi tradita sunt, et cui volo do illa.

** Luke 4:7

Tu ergo si adoraveris coram me, erunt tua omnia.

** Luke 4:8

Et respondens Jesus, dixit illi : Scriptum est : Dominum Deum tuum adorabis, et illi soli servies.

** Luke 4:9

Et duxit illum in Jerusalem, et statuit eum super pinnam templi, et dixit illi : Si Filius Dei es, mitte te hinc deorsum.

** Luke 4:10

Scriptum est enim quod angelis suis mandavit de te, ut conservent te :

** Luke 4:11

et quia in manibus tollent te, ne forte offendas ad lapidem pedem tuum.

** Luke 4:12

Et respondens Jesus, ait illi : Dictum est : Non tentabis Dominum Deum tuum.

** Luke 4:13

Et consummata omni tentatione, diabolus recessit ab illo, usque ad tempus.  

** Luke 4:14

Et regressus est Jesus in virtute Spiritus in Galilæam, et fama exiit per universam regionem de illo.

** Luke 4:15

Et ipse docebat in synagogis eorum, et magnificabatur ab omnibus.

** Luke 4:16

Et venit Nazareth, ubi erat nutritus, et intravit secundum consuetudinem suam die sabbati in synagogam, et surrexit legere.

** Luke 4:17

Et traditus est illi liber Isaiæ prophetæ. Et ut revolvit librum, invenit locum ubi scriptum erat :

** Luke 4:18

Spiritus Domini super me : propter quod unxit me, evangelizare pauperibus misit me, sanare contritos corde,

** Luke 4:19

prædicare captivis remissionem, et cæcis visum, dimittere confractos in remissionem, prædicare annum Domini acceptum et diem retributionis.

** Luke 4:20

Et cum plicuisset librum, reddit ministro, et sedit. Et omnium in synagoga oculi erant intendentes in eum.

** Luke 4:21

Cœpit autem dicere ad illos : Quia hodie impleta est hæc scriptura in auribus vestris.

** Luke 4:22

Et omnes testimonium illi dabant : et mirabantur in verbis gratiæ, quæ procedebant de ore ipsius, et dicebant : Nonne hic est filius Joseph ?

** Luke 4:23

Et ait illis : Utique dicetis mihi hanc similitudinem : Medice cura teipsum : quanta audivimus facta in Capharnaum, fac et hic in patria tua.

** Luke 4:24

Ait autem : Amen dico vobis, quia nemo propheta acceptus est in patria sua.

** Luke 4:25

In veritate dico vobis, multæ viduæ erant in diebus Eliæ in Israël, quando clausum est cælum annis tribus et mensibus sex, cum facta esset fames magna in omni terra :

** Luke 4:26

et ad nullam illarum missus est Elias, nisi in Sarepta Sidoniæ, ad mulierem viduam.

** Luke 4:27

Et multi leprosi erant in Israël sub Eliseo propheta : et nemo eorum mundatus est nisi Naaman Syrus.

** Luke 4:28

Et repleti sunt omnes in synagoga ira, hæc audientes.

** Luke 4:29

Et surrexerunt, et ejecerunt illum extra civitatem : et duxerunt illum usque ad supercilium montis, super quem civitas illorum erat ædificata, ut præcipitarent eum.

** Luke 4:30

Ipse autem transiens per medium illorum, ibat.  

** Luke 4:31

Et descendit in Capharnaum civitatem Galilææ, ibique docebat illos sabbatis.

** Luke 4:32

Et stupebant in doctrina ejus, quia in potestate erat sermo ipsius.

** Luke 4:33

Et in synagoga erat homo habens dæmonium immundum, et exclamavit voce magna,

** Luke 4:34

dicens : Sine, quid nobis et tibi, Jesu Nazarene ? venisti perdere nos ? scio te quis sis, Sanctus Dei.

** Luke 4:35

Et increpavit illum Jesus, dicens : Obmutesce, et exi ab eo. Et cum projecisset illum dæmonium in medium, exiit ab illo, nihilque illum nocuit.

** Luke 4:36

Et factus est pavor in omnibus, et colloquebantur ad invicem, dicentes : Quod est hoc verbum, quia in potestate et virtute imperat immundis spiritibus, et exeunt ?

** Luke 4:37

Et divulgabatur fama de illo in omnem locum regionis.  

** Luke 4:38

Surgens autem Jesus de synagoga, introivit in domum Simonis. Socrus autem Simonis tenebatur magnis febribus : et rogaverunt illum pro ea.

** Luke 4:39

Et stans super illam imperavit febri : et dimisit illam. Et continuo surgens, ministrabat illis.

** Luke 4:40

Cum autem sol occidisset, omnes qui habebant infirmos variis languoribus, ducebant illos ad eum. At ille singulis manus imponens, curabat eos.

** Luke 4:41

Exibant autem dæmonia a multis clamantia, et dicentia : Quia tu es Filius Dei : et increpans non sinebat ea loqui : quia sciebant ipsum esse Christum.  

** Luke 4:42

Facta autem die egressus ibat in desertum locum, et turbæ requirebant eum, et venerunt usque ad ipsum : et detinebant illum ne discederet ab eis.

** Luke 4:43

Quibus ille ait : Quia et aliis civitatibus oportet me evangelizare regnum Dei : quia ideo missus sum.

** Luke 4:44

Et erat prædicans in synagogis Galilææ.   

* Luke 5

** Luke 5:1

Factum est autem, cum turbæ irruerunt in eum ut audirent verbum Dei, et ipse stabat secus stagnum Genesareth.

** Luke 5:2

Et vidit duas naves stantes secus stagnum : piscatores autem descenderant, et lavabant retia.

** Luke 5:3

Ascendens autem in unam navim, quæ erat Simonis, rogavit eum a terra reducere pusillum. Et sedens docebat de navicula turbas.  

** Luke 5:4

Ut cessavit autem loqui, dixit ad Simonem : Duc in altum, et laxate retia vestra in capturam.

** Luke 5:5

Et respondens Simon, dixit illi : Præceptor, per totam noctem laborantes nihil cepimus : in verbo autem tuo laxabo rete.

** Luke 5:6

Et cum hoc fecissent, concluserunt piscium multitudinem copiosam : rumpebatur autem rete eorum.

** Luke 5:7

Et annuerunt sociis, qui erant in alia navi, ut venirent, et adjuvarent eos. Et venerunt, et impleverunt ambas naviculas, ita ut pene mergerentur.

** Luke 5:8

Quod cum videret Simon Petrus, procidit ad genua Jesu, dicens : Exi a me, quia homo peccator sum, Domine.

** Luke 5:9

Stupor enim circumdederat eum, et omnes qui cum illo erant, in captura piscium, quam ceperant :

** Luke 5:10

similiter autem Jacobum et Joannem, filios Zebedæi, qui erant socii Simonis. Et ait ad Simonem Jesus : Noli timere : ex hoc jam homines eris capiens.

** Luke 5:11

Et subductis ad terram navibus, relictis omnibus, secuti sunt eum.  

** Luke 5:12

Et factum est, cum esset in una civitatum, et ecce vir plenus lepra, et videns Jesum, et procidens in faciem, rogavit eum, dicens : Domine, si vis, potes me mundare.

** Luke 5:13

Et extendens manum, tetigit eum dicens : Volo : mundare. Et confestim lepra discessit ab illo.

** Luke 5:14

Et ipse præcepit illi ut nemini diceret : sed, Vade, ostende te sacerdoti, et offer pro emundatione tua, sicut præcepit Moyses, in testimonium illis.

** Luke 5:15

Perambulabat autem magis sermo de illo : et conveniebant turbæ multæ ut audirent, et curarentur ab infirmitatibus suis.

** Luke 5:16

Ipse autem secedebat in desertum, et orabat.  

** Luke 5:17

Et factum est in una dierum, et ipse sedebat docens. Et erant pharisæi sedentes, et legis doctores, qui venerant ex omni castello Galilææ, et Judææ, et Jerusalem : et virtus Domini erat ad sanandum eos.

** Luke 5:18

Et ecce viri portantes in lecto hominem, qui erat paralyticus : et quærebant eum inferre, et ponere ante eum.

** Luke 5:19

Et non invenientes qua parte illum inferrent præ turba, ascenderunt supra tectum, et per tegulas summiserunt eum cum lecto in medium ante Jesum.

** Luke 5:20

Quorum fidem ut vidit, dixit : Homo, remittuntur tibi peccata tua.

** Luke 5:21

Et cœperunt cogitare scribæ et pharisæi, dicentes : Quis est hic, qui loquitur blasphemias ? quis potest dimittere peccata, nisi solus Deus ?

** Luke 5:22

Ut cognovit autem Jesus cogitationes eorum, respondens, dixit ad illos : Quid cogitatis in cordibus vestris ?

** Luke 5:23

Quid est facilius dicere : Dimittuntur tibi peccata : an dicere : Surge, et ambula ?

** Luke 5:24

Ut autem sciatis quia Filius hominis habet potestatem in terra dimittendi peccata, (ait paralytico) tibi dico, surge, tolle lectum tuum, et vade in domum tuam.

** Luke 5:25

Et confestim consurgens coram illis, tulit lectum in quo jacebat : et abiit in domum suam, magnificans Deum.

** Luke 5:26

Et stupor apprehendit omnes, et magnificabant Deum. Et repleti sunt timore, dicentes : Quia vidimus mirabilia hodie.  

** Luke 5:27

Et post hæc exiit, et vidit publicanum nomine Levi, sedentem ad telonium, et ait illi : Sequere me.

** Luke 5:28

Et relictis omnibus, surgens secutus est eum.

** Luke 5:29

Et fecit ei convivium magnum Levi in domo sua : et erat turba multa publicanorum, et aliorum qui cum illis erant discumbentes.

** Luke 5:30

Et murmurabant pharisæi et scribæ eorum, dicentes ad discipulos ejus : Quare cum publicanis et peccatoribus manducatis et bibitis ?

** Luke 5:31

Et respondens Jesus, dixit ad illos : Non egent qui sani sunt medico, sed qui male habent.

** Luke 5:32

Non veni vocare justos, sed peccatores ad pœnitentiam.  

** Luke 5:33

At illi dixerunt ad eum : Quare discipuli Joannis jejunant frequenter, et obsecrationes faciunt, similiter et pharisæorum : tui autem edunt et bibunt ?

** Luke 5:34

Quibus ipse ait : Numquid potestis filios sponsi, dum cum illis est sponsus, facere jejunare ?

** Luke 5:35

Venient autem dies, cum ablatus fuerit ab illis sponsus : tunc jejunabunt in illis diebus.

** Luke 5:36

Dicebat autem et similitudinem ad illos : Quia nemo commissuram a novo vestimento immittit in vestimentum vetus : alioquin et novum rumpit, et veteri non convenit commissura a novo.

** Luke 5:37

Et nemo mittit vinum novum in utres veteres : alioquin rumpet vinum novum utres, et ipsum effundetur, et utres peribunt :

** Luke 5:38

sed vinum novum in utres novos mittendum est, et utraque conservantur.

** Luke 5:39

Et nemo bibens vetus, statim vult novum : dicit enim : Vetus melius est.   

* Luke 6

** Luke 6:1

Factum est autem in sabbato secundo, primo, cum transiret per sata, vellebant discipuli ejus spicas, et manducabant confricantes manibus.

** Luke 6:2

Quidam autem pharisæorum, dicebant illis : Quid facitis quod non licet in sabbatis ?

** Luke 6:3

Et respondens Jesus ad eos, dixit : Nec hoc legistis quod fecit David, cum esurisset ipse, et qui cum illo erant ?

** Luke 6:4

quomodo intravit in domum Dei, et panes propositionis sumpsit, et manducavit, et dedit his qui cum ipso erant : quos non licet manducare nisi tantum sacerdotibus ?

** Luke 6:5

Et dicebat illis : Quia dominus est Filius hominis etiam sabbati.  

** Luke 6:6

Factum est autem in alio sabbato, ut intraret in synagogam, et doceret. Et erat ibi homo, et manus ejus dextra erat arida.

** Luke 6:7

Observabant autem scribæ et pharisæi si in sabbato curaret, ut invenirent unde accusarent eum.

** Luke 6:8

Ipse vero sciebat cogitationes eorum : et ait homini qui habebat manum aridam : Surge, et sta in medium. Et surgens stetit.

** Luke 6:9

Ait autem ad illos Jesus : Interrogo vos si licet sabbatis benefacere, an male : animam salvam facere, an perdere ?

** Luke 6:10

Et circumspectis omnibus dixit homini : Extende manum tuam. Et extendit : et restituta est manus ejus.

** Luke 6:11

Ipsi autem repleti sunt insipientia, et colloquebantur ad invicem, quidnam facerent Jesu.  

** Luke 6:12

Factum est autem in illis diebus, exiit in montem orare, et erat pernoctans in oratione Dei.

** Luke 6:13

Et cum dies factus esset, vocavit discipulos suos : et elegit duodecim ex ipsis (quos et apostolos nominavit) :

** Luke 6:14

Simonem, quem cognominavit Petrum, et Andream fratrem ejus, Jacobum, et Joannem, Philippum, et Bartholomæum,

** Luke 6:15

Matthæum, et Thomam, Jacobum Alphæi, et Simonem, qui vocatur Zelotes,

** Luke 6:16

et Judam Jacobi, et Judam Iscariotem, qui fuit proditor.

** Luke 6:17

Et descendens cum illis, stetit in loco campestri, et turba discipulorum ejus, et multitudo copiosa plebis ab omni Judæa, et Jerusalem, et maritima, et Tyri, et Sidonis,

** Luke 6:18

qui venerant ut audirent eum, et sanarentur a languoribus suis. Et qui vexabantur a spiritibus immundis, curabantur.

** Luke 6:19

Et omnis turba quærebat eum tangere : quia virtus de illo exibat, et sanabat omnes.  

** Luke 6:20

Et ipse elevatis oculis in discipulis suis, dicebat : Beati pauperes, quia vestrum est regnum Dei.

** Luke 6:21

Beati qui nunc esuritis, quia saturabimini. Beati qui nunc fletis, quia ridebitis.

** Luke 6:22

Beati eritis cum vos oderint homines, et cum separaverint vos, et exprobraverint, et ejicerint nomen vestrum tamquam malum propter Filium hominis.

** Luke 6:23

Gaudete in illa die, et exsultate : ecce enim merces vestra multa est in cælo : secundum hæc enim faciebant prophetis patres eorum.

** Luke 6:24

Verumtamen væ vobis divitibus, quia habetis consolationem vestram.

** Luke 6:25

Væ vobis, qui saturati estis : quia esurietis. Væ vobis, qui ridetis nunc : quia lugebitis et flebitis.

** Luke 6:26

Væ cum benedixerint vobis homines : secundum hæc enim faciebant pseudoprophetis patres eorum.  

** Luke 6:27

Sed vobis dico, qui auditis : diligite inimicos vestros, benefacite his qui oderunt vos.

** Luke 6:28

Benedicite maledicentibus vobis, et orate pro calumniantibus vos.

** Luke 6:29

Et qui te percutit in maxillam, præbe et alteram. Et ab eo qui aufert tibi vestimentum, etiam tunicam noli prohibere.

** Luke 6:30

Omni autem petenti te, tribue : et qui aufert quæ tua sunt, ne repetas.

** Luke 6:31

Et prout vultis ut faciant vobis homines, et vos facite illis similiter.

** Luke 6:32

Et si diligitis eos qui vos diligunt, quæ vobis est gratia ? nam et peccatores diligentes se diligunt.

** Luke 6:33

Et si benefeceritis his qui vobis benefaciunt, quæ vobis est gratia ? siquidem et peccatores hoc faciunt.

** Luke 6:34

Et si mutuum dederitis his a quibus speratis recipere, quæ gratia est vobis ? nam et peccatores peccatoribus fœnerantur, ut recipiant æqualia.

** Luke 6:35

Verumtamen diligite inimicos vestros : benefacite, et mutuum date, nihil inde sperantes : et erit merces vestra multa, et eritis filii Altissimi, quia ipse benignus est super ingratos et malos.

** Luke 6:36

Estote ergo misericordes sicut et Pater vester misericors est.  

** Luke 6:37

Nolite judicare, et non judicabimini : nolite condemnare, et non condemnabimini. Dimittite, et dimittemini.

** Luke 6:38

Date, et dabitur vobis : mensuram bonam, et confertam, et coagitatam, et supereffluentem dabunt in sinum vestrum. Eadem quippe mensura, qua mensi fueritis, remetietur vobis.

** Luke 6:39

Dicebat autem illis et similitudinem : Numquid potest cæcus cæcum ducere ? nonne ambo in foveam cadunt ?

** Luke 6:40

Non est discipulus super magistrum : perfectus autem omnis erit, si sit sicut magister ejus.

** Luke 6:41

Quid autem vides festucam in oculo fratris tui, trabem autem, quæ in oculo tuo est, non consideras ?

** Luke 6:42

aut quomodo potes dicere fratri tuo : Frater, sine ejiciam festucam de oculo tuo : ipse in oculo tuo trabem non videns ? Hypocrita, ejice primum trabem de oculo tuo : et tunc perspicies ut educas festucam de oculo fratris tui.

** Luke 6:43

Non est enim arbor bona, quæ facit fructus malos : neque arbor mala, faciens fructum bonum.

** Luke 6:44

Unaquæque enim arbor de fructu suo cognoscitur. Neque enim de spinis colligunt ficus : neque de rubo vindemiant uvam.

** Luke 6:45

Bonus homo de bono thesauro cordis sui profert bonum : et malus homo de malo thesauro profert malum. Ex abundantia enim cordis os loquitur.

** Luke 6:46

Quid autem vocatis me Domine, Domine : et non facitis quæ dico ?  

** Luke 6:47

Omnis qui venit ad me, et audit sermones meos, et facit eos, ostendam vobis cui similis sit :

** Luke 6:48

similis est homini ædificanti domum, qui fodit in altum, et posuit fundamentum super petram : inundatione autem facta, illisum est flumen domui illi, et non potuit eam movere : fundata enim erat super petram.

** Luke 6:49

Qui autem audit, et non facit, similis est homini ædificanti domum suam super terram sine fundamento : in quam illisus est fluvius, et continuo cecidit : et facta est ruina domus illius magna.   

* Luke 7

** Luke 7:1

Cum autem implesset omnia verba sua in aures plebis, intravit Capharnaum.

** Luke 7:2

Centurionis autem cujusdam servus male habens, erat moriturus : qui illi erat pretiosus.

** Luke 7:3

Et cum audisset de Jesu, misit ad eum seniores Judæorum, rogans eum ut veniret et salvaret servum ejus.

** Luke 7:4

At illi cum venissent ad Jesum, rogabant eum sollicite, dicentes ei : Quia dignus est ut hoc illi præstes :

** Luke 7:5

diligit enim gentem nostram, et synagogam ipse ædificavit nobis.

** Luke 7:6

Jesus autem ibat cum illis. Et cum jam non longe esset a domo, misit ad eum centurio amicos, dicens : Domine, noli vexari : non enim sum dignus ut sub tectum meum intres :

** Luke 7:7

propter quod et meipsum non sum dignum arbitratus ut venirem ad te : sed dic verbo, et sanabitur puer meus.

** Luke 7:8

Nam et ego homo sum sub potestate constitutus, habens sub me milites : et dico huic, Vade, et vadit : et alii, Veni, et venit : et servo meo, Fac hoc, et facit.

** Luke 7:9

Quo audito Jesus miratus est : et conversus sequentibus se turbis, dixit : Amen dico vobis, nec in Israël tantam fidem inveni.

** Luke 7:10

Et reversi, qui missi fuerant, domum, invenerunt servum, qui languerat, sanum.  

** Luke 7:11

Et factum est : deinceps ibat in civitatem quæ vocatur Naim : et ibant cum eo discipuli ejus et turba copiosa.

** Luke 7:12

Cum autem appropinquaret portæ civitatis, ecce defunctus efferebatur filius unicus matris suæ : et hæc vidua erat : et turba civitatis multa cum illa.

** Luke 7:13

Quam cum vidisset Dominus, misericordia motus super eam, dixit illi : Noli flere.

** Luke 7:14

Et accessit, et tetigit loculum. (Hi autem qui portabant, steterunt.) Et ait : Adolescens, tibi dico, surge.

** Luke 7:15

Et resedit qui erat mortuus, et cœpit loqui. Et dedit illum matri suæ.

** Luke 7:16

Accepit autem omnes timor : et magnificabant Deum, dicentes : Quia propheta magnus surrexit in nobis : et quia Deus visitavit plebem suam.

** Luke 7:17

Et exiit hic sermo in universam Judæam de eo, et in omnem circa regionem.  

** Luke 7:18

Et nuntiaverunt Joanni discipuli ejus de omnibus his.

** Luke 7:19

Et convocavit duos de discipulis suis Joannes, et misit ad Jesum, dicens : Tu es qui venturus es, an alium exspectamus ?

** Luke 7:20

Cum autem venissent ad eum viri, dixerunt : Joannes Baptista misit nos ad te dicens : Tu es qui venturus es, an alium exspectamus ?

** Luke 7:21

(In ipsa autem hora multos curavit a languoribus, et plagis, et spiritibus malis, et cæcis multis donavit visum.)

** Luke 7:22

Et respondens, dixit illis : Euntes renuntiate Joanni quæ audistis et vidistis : quia cæci vident, claudi ambulant, leprosi mundantur, surdi audiunt, mortui resurgunt, pauperes evangelizantur :

** Luke 7:23

et beatus est quicumque non fuerit scandalizatus in me.  

** Luke 7:24

Et cum discessissent nuntii Joannis, cœpit de Joanne dicere ad turbas : Quid existis in desertum videre ? arundinem vento agitatam ?

** Luke 7:25

Sed quid existis videre ? hominem mollibus vestibus indutum ? Ecce qui in veste pretiosa sunt et deliciis, in domibus regum sunt.

** Luke 7:26

Sed quid existis videre ? prophetam ? Utique dico vobis, et plus quam prophetam :

** Luke 7:27

hic est, de quo scriptum est : Ecce mitto angelum meum ante faciem tuam, qui præparabit viam tuam ante te.

** Luke 7:28

Dico enim vobis : major inter natos mulierum propheta Joanne Baptista nemo est : qui autem minor est in regno Dei, major est illo.  

** Luke 7:29

Et omnis populus audiens et publicani, justificaverunt Deum, baptizati baptismo Joannis.

** Luke 7:30

Pharisæi autem et legisperiti consilium Dei spreverunt in semetipsos, non baptizati ab eo.

** Luke 7:31

Ait autem Dominus : Cui ergo similes dicam homines generationis hujus ? et cui similes sunt ?

** Luke 7:32

Similes sunt pueris sedentibus in foro, et loquentibus ad invicem, et dicentibus : Cantavimus vobis tibiis, et non saltastis : lamentavimus, et non plorastis.

** Luke 7:33

Venit enim Joannes Baptista, neque manducans panem, neque bibens vinum, et dicitis : Dæmonium habet.

** Luke 7:34

Venit Filius hominis manducans, et bibens, et dicitis : Ecce homo devorator, et bibens vinum, amicus publicanorum et peccatorum.

** Luke 7:35

Et justificata est sapientia ab omnibus filiis suis.  

** Luke 7:36

Rogabat autem illum quidam de pharisæis ut manducaret cum illo. Et ingressus domum pharisæi discubuit.

** Luke 7:37

Et ecce mulier, quæ erat in civitate peccatrix, ut cognovit quod accubuisset in domo pharisæi, attulit alabastrum unguenti :

** Luke 7:38

et stans retro secus pedes ejus, lacrimis cœpit rigare pedes ejus, et capillis capitis sui tergebat, et osculabatur pedes ejus, et unguento ungebat.

** Luke 7:39

Videns autem pharisæus, qui vocaverat eum, ait intra se dicens : Hic si esset propheta, sciret utique quæ et qualis est mulier, quæ tangit eum : quia peccatrix est.

** Luke 7:40

Et respondens Jesus, dixit ad illum : Simon, habeo tibi aliquid dicere. At ille ait : Magister, dic.

** Luke 7:41

Duo debitores erant cuidam fœneratori : unus debebat denarios quingentos, et alius quinquaginta.

** Luke 7:42

Non habentibus illis unde redderent, donavit utrisque. Quis ergo eum plus diligit ?

** Luke 7:43

Respondens Simon dixit : Æstimo quia is cui plus donavit. At ille dixit ei : Recte judicasti.

** Luke 7:44

Et conversus ad mulierem, dixit Simoni : Vides hanc mulierem ? Intravi in domum tuam, aquam pedibus meis non dedisti : hæc autem lacrimis rigavit pedes meos, et capillis suis tersit.

** Luke 7:45

Osculum mihi non dedisti : hæc autem ex quo intravit, non cessavit osculari pedes meos.

** Luke 7:46

Oleo caput meum non unxisti : hæc autem unguento unxit pedes meos.

** Luke 7:47

Propter quod dico tibi : remittuntur ei peccata multa, quoniam dilexit multum. Cui autem minus dimittitur, minus diligit.

** Luke 7:48

Dixit autem ad illam : Remittuntur tibi peccata.

** Luke 7:49

Et cœperunt qui simul accumbebant, dicere intra se : Quis est hic qui etiam peccata dimittit ?

** Luke 7:50

Dixit autem ad mulierem : Fides tua te salvam fecit : vade in pace.   

* Luke 8

** Luke 8:1

Et factum est deinceps, et ipse iter faciebat per civitates, et castella prædicans, et evangelizans regnum Dei : et duodecim cum illo,

** Luke 8:2

et mulieres aliquæ, quæ erant curatæ a spiritibus malignis et infirmantibus : Maria, quæ vocatur Magdalene, de qua septem dæmonia exierant,

** Luke 8:3

et Joanna uxor Chusæ procuratoris Herodis, et Susanna, et aliæ multæ, quæ ministrabant ei de facultatibus suis.  

** Luke 8:4

Cum autem turba plurima convenirent, et de civitatibus properarent ad eum, dixit per similitudinem :

** Luke 8:5

Exiit qui seminat, seminare semen suum. Et dum seminat, aliud cecidit secus viam, et conculcatum est, et volucres cæli comederunt illud.

** Luke 8:6

Et aliud cecidit supra petram : et natum aruit, quia non habebat humorem.

** Luke 8:7

Et aliud cecidit inter spinas, et simul exortæ spinæ suffocaverunt illud.

** Luke 8:8

Et aliud cecidit in terram bonam : et ortum fecit fructum centuplum. Hæc dicens clamabat : Qui habet aures audiendi, audiat.  

** Luke 8:9

Interrogabant autem eum discipuli ejus, quæ esset hæc parabola.

** Luke 8:10

Quibus ipse dixit : Vobis datum est nosse mysterium regni Dei, ceteris autem in parabolis : ut videntes non videant, et audientes non intelligant.  

** Luke 8:11

Est autem hæc parabola : Semen est verbum Dei.

** Luke 8:12

Qui autem secus viam, hi sunt qui audiunt : deinde venit diabolus, et tollit verbum de corde eorum, ne credentes salvi fiant.

** Luke 8:13

Nam qui supra petram, qui cum audierint, cum gaudio suscipiunt verbum : et hi radices non habent : qui ad tempus credunt, et in tempore tentationis recedunt.

** Luke 8:14

Quod autem in spinas cecidit : hi sunt qui audierunt, et a sollicitudinibus, et divitiis, et voluptatibus vitæ euntes, suffocantur, et non referunt fructum.

** Luke 8:15

Quod autem in bonam terram : hi sunt qui in corde bono et optimo audientes verbum retinent, et fructum afferunt in patientia.  

** Luke 8:16

Nemo autem lucernam accendens, operit eam vase, aut subtus lectum ponit : sed supra candelabrum ponit, ut intrantes videant lumen.

** Luke 8:17

Non est enim occultum, quod non manifestetur : nec absconditum, quod non cognoscatur, et in palam veniat.

** Luke 8:18

Videte ergo quomodo audiatis ? Qui enim habet, dabitur illi : et quicumque non habet, etiam quod putat se habere, auferetur ab illo.  

** Luke 8:19

Venerunt autem ad illum mater et fratres ejus, et non poterant adire eum præ turba.

** Luke 8:20

Et nuntiatum est illi : Mater tua et fratres tui stant foris, volentes te videre.

** Luke 8:21

Qui respondens, dixit ad eos : Mater mea et fratres mei hi sunt, qui verbum Dei audiunt et faciunt.  

** Luke 8:22

Factum est autem in una dierum : et ipse ascendit in naviculam, et discipuli ejus, et ait ad illos : Transfretemus trans stagnum. Et ascenderunt.

** Luke 8:23

Et navigantibus illis, obdormivit, et descendit procella venti in stagnum, et complebantur, et periclitabantur.

** Luke 8:24

Accedentes autem suscitaverunt eum, dicentes : Præceptor, perimus. At ille surgens, increpavit ventum, et tempestatem aquæ, et cessavit : et facta est tranquillitas.

** Luke 8:25

Dixit autem illis : Ubi est fides vestra ? Qui timentes, mirati sunt ad invicem, dicentes : Quis putas hic est, quia et ventis, et mari imperat, et obediunt ei ?  

** Luke 8:26

Et navigaverunt ad regionem Gerasenorum, quæ est contra Galilæam.

** Luke 8:27

Et cum egressus esset ad terram, occurrit illi vir quidam, qui habebat dæmonium jam temporibus multis, et vestimento non induebatur, neque in domo manebat, sed in monumentis.

** Luke 8:28

Is, ut vidit Jesum, procidit ante illum : et exclamans voce magna, dixit : Quid mihi et tibi est, Jesu Fili Dei Altissimi ? obsecro te, ne me torqueas.

** Luke 8:29

Præcipiebat enim spiritui immundo ut exiret ab homine. Multis enim temporibus arripiebat illum, et vinciebatur catenis, et compedibus custoditus. Et ruptis vinculis agebatur a dæmonio in deserta.

** Luke 8:30

Interrogavit autem illum Jesus, dicens : Quod tibi nomen est ? At ille dixit : Legio : quia intraverant dæmonia multa in eum.

** Luke 8:31

Et rogabant illum ne imperaret illis ut in abyssum irent.

** Luke 8:32

Erat autem ibi grex porcorum multorum pascentium in monte : et rogabant eum, ut permitteret eis in illos ingredi. Et permisit illis.

** Luke 8:33

Exierunt ergo dæmonia ab homine, et intraverunt in porcos : et impetu abiit grex per præceps in stagnum, et suffocatus est.

** Luke 8:34

Quod ut viderunt factum qui pascebant, fugerunt, et nuntiaverunt in civitatem et in villas.

** Luke 8:35

Exierunt autem videre quod factum est, et venerunt ad Jesum, et invenerunt hominem sedentem, a quo dæmonia exierant, vestitum ac sana mente, ad pedes ejus, et timuerunt.

** Luke 8:36

Nuntiaverunt autem illis et qui viderant, quomodo sanus factus esset a legione :

** Luke 8:37

et rogaverunt illum omnis multitudo regionis Gerasenorum ut discederet ab ipsis : quia magno timore tenebantur. Ipse autem ascendens navim, reversus est.

** Luke 8:38

Et rogabat illum vir, a quo dæmonia exierant, ut cum eo esset. Dimisit autem eum Jesus, dicens :

** Luke 8:39

Redi in domum tuam, et narra quanta tibi fecit Deus. Et abiit per universam civitatem, prædicans quanta illi fecisset Jesus.  

** Luke 8:40

Factum est autem cum rediisset Jesus, excepit illum turba : erunt enim omnes exspectantes eum.

** Luke 8:41

Et ecce venit vir, cui nomen Jairus, et ipse princeps synagogæ erat : et cecidit ad pedes Jesu, rogans eum ut intraret in domum ejus,

** Luke 8:42

quia unica filia erat ei fere annorum duodecim, et hæc moriebatur. Et contigit, dum iret, a turba comprimebatur.

** Luke 8:43

Et mulier quædam erat in fluxu sanguinis ab annis duodecim, quæ in medicos erogaverat omnem substantiam suam, nec ab ullo potuit curari :

** Luke 8:44

accessit retro, et tetigit fimbriam vestimenti ejus : et confestim stetit fluxus sanguinis ejus.

** Luke 8:45

Et ait Jesus : Quis est, qui me tetigit ? Negantibus autem omnibus, dixit Petrus, et qui cum illo erant : Præceptor, turbæ te comprimunt, et affligunt, et dicis : Quis me tetigit ?

** Luke 8:46

Et dicit Jesus : Tetigit me aliquis : nam ego novi virtutem de me exiisse.

** Luke 8:47

Videns autem mulier, quia non latuit, tremens venit, et procidit ante pedes ejus : et ob quam causam tetigerit eum, indicavit coram omni populo : et quemadmodum confestim sanata sit.

** Luke 8:48

At ipse dixit ei : Filia, fides tua salvam te fecit : vade in pace.

** Luke 8:49

Adhuc illo loquente, venit quidam ad principem synagogæ, dicens ei : Quia mortua est filia tua, noli vexare illum.

** Luke 8:50

Jesus autem, audito hoc verbo, respondit patri puellæ : Noli timere, crede tantum, et salva erit.

** Luke 8:51

Et cum venisset domum, non permisit intrare secum quemquam, nisi Petrum, et Jacobum, et Joannem, et patrem, et matrem puellæ.

** Luke 8:52

Flebant autem omnes, et plangebant illam. At ille dixit : Nolite flere : non est mortua puella, sed dormit.

** Luke 8:53

Et deridebant eum, scientes quod mortua esset.

** Luke 8:54

Ipse autem tenens manum ejus clamavit, dicens : Puella, surge.

** Luke 8:55

Et reversus est spiritus ejus, et surrexit continuo. Et jussit illi dari manducare.

** Luke 8:56

Et stupuerunt parentes ejus, quibus præcepit ne alicui dicerent quod factum erat.   

* Luke 9

** Luke 9:1

Convocatis autem duodecim Apostolis, dedit illis virtutem et potestatem super omnia dæmonia, et ut languores curarent.

** Luke 9:2

Et misit illos prædicare regnum Dei, et sanare infirmos.

** Luke 9:3

Et ait ad illos : Nihil tuleritis in via, neque virgam, neque peram, neque panem, neque pecuniam, neque duas tunicas habeatis.

** Luke 9:4

Et in quamcumque domum intraveritis, ibi manete, et inde ne exeatis.

** Luke 9:5

Et quicumque non receperint vos : exeuntes de civitate illa, etiam pulverem pedum vestrorum excutite in testimonium supra illos.

** Luke 9:6

Egressi autem circuibant per castella evangelizantes, et curantes ubique.  

** Luke 9:7

Audivit autem Herodes tetrarcha omnia quæ fiebant ab eo, et hæsitabat eo quod diceretur

** Luke 9:8

a quibusdam : Quia Joannes surrexit a mortuis : a quibusdam vero : Quia Elias apparuit : ab aliis autem : Quia propheta unus de antiquis surrexit.

** Luke 9:9

Et ait Herodes : Joannem ego decollavi : quis est autem iste, de quo ego talia audio ? Et quærebat videre eum.  

** Luke 9:10

Et reversi Apostoli, narraverunt illi quæcumque fecerunt : et assumptis illis secessit seorsum in locum desertum, qui est Bethsaidæ.

** Luke 9:11

Quod cum cognovissent turbæ, secutæ sunt illum : et excepit eos, et loquebatur illis de regno Dei, et eos, qui cura indigebant, sanabat.

** Luke 9:12

Dies autem cœperat declinare, et accedentes duodecim dixerunt illi : Dimitte turbas, ut euntes in castella villasque quæ circa sunt, divertant, et inveniant escas : quia hic in loco deserto sumus.

** Luke 9:13

Ait autem ad illos : Vos date illis manducare. At illi dixerunt : Non sunt nobis plus quam quinque panes et duo pisces : nisi forte nos eamus, et emamus in omnem hanc turbam escas.

** Luke 9:14

Erant autem fere viri quinque millia. Ait autem ad discipulos suos : Facite illos discumbere per convivia quinquagenos.

** Luke 9:15

Et ita fecerunt : et discumbere fecerunt omnes.

** Luke 9:16

Acceptis autem quinque panibus et duobus piscibus, respexit in cælum, et benedixit illis : et fregit, et distribuit discipulis suis, ut ponerent ante turbas.

** Luke 9:17

Et manducaverunt omnes, et saturati sunt. Et sublatum est quod superfuit illis, fragmentorum cophini duodecim.  

** Luke 9:18

Et factum est cum solus esset orans, erant cum illo et discipuli : et interrogavit illos, dicens : Quem me dicunt esse turbæ ?

** Luke 9:19

At illi responderunt, et dixerunt : Joannem Baptistam, alii autem Eliam, alii vero quia unus propheta de prioribus surrexit.

** Luke 9:20

Dixit autem illis : Vos autem quem me esse dicitis ? Respondens Simon Petrus, dixit : Christum Dei.

** Luke 9:21

At ille increpans illos, præcepit ne cui dicerent hoc,

** Luke 9:22

dicens : Quia oportet Filium hominis multa pati, et reprobari a senioribus, et principibus sacerdotum, et scribis, et occidi, et tertia die resurgere.  

** Luke 9:23

Dicebat autem ad omnes : Si quis vult post me venire, abneget semetipsum, et tollat crucem suam quotidie, et sequatur me.

** Luke 9:24

Qui enim voluerit animam suam salvam facere, perdet illam : nam qui perdiderit animam suam propter me, salvam faciet illam.

** Luke 9:25

Quid enim proficit homo, si lucretur universum mundum, se autem ipsum perdat, et detrimentum sui faciat ?

** Luke 9:26

Nam qui me erubuerit, et meos sermones : hunc Filius hominis erubescet cum venerit in majestate sua, et Patris, et sanctorum angelorum.

** Luke 9:27

Dico autem vobis vere : sunt aliqui hic stantes, qui non gustabunt mortem donec videant regnum Dei.  

** Luke 9:28

Factum est autem post hæc verba fere dies octo, et assumpsit Petrum, et Jacobum, et Joannem, et ascendit in montem ut oraret.

** Luke 9:29

Et facta est, dum oraret, species vultus ejus altera : et vestitus ejus albus et refulgens.

** Luke 9:30

Et ecce duo viri loquebantur cum illo. Erant autem Moyses et Elias,

** Luke 9:31

visi in majestate : et dicebant excessum ejus, quem completurus erat in Jerusalem.

** Luke 9:32

Petrus vero, et qui cum illo erant, gravati erant somno. Et evigilantes viderunt majestatem ejus, et duos viros qui stabant cum illo.

** Luke 9:33

Et factum est cum discederent ab illo, ait Petrus ad Jesum : Præceptor, bonum est nos hic esse : et faciamus tria tabernacula, unum tibi, et unum Moysi, et unum Eliæ : nesciens quid diceret.

** Luke 9:34

Hæc autem illo loquente, facta est nubes, et obumbravit eos : et timuerunt, intrantibus illis in nubem.

** Luke 9:35

Et vox facta est de nube, dicens : Hic est Filius meus dilectus, ipsum audite.

** Luke 9:36

Et dum fieret vox, inventus est Jesus solus. Et ipsi tacuerunt, et nemini dixerunt in illis diebus quidquam ex his quæ viderant.  

** Luke 9:37

Factum est autem in sequenti die, descendentibus illis de monte, occurrit illis turba multa.

** Luke 9:38

Et ecce vir de turba exclamavit, dicens : Magister, obsecro te, respice in filium meum quia unicus est mihi :

** Luke 9:39

et ecce spiritus apprehendit eum, et subito clamat, et elidit, et dissipat eum cum spuma, et vix discedit dilanians eum :

** Luke 9:40

et rogavi discipulos tuos ut ejicerent illum, et non potuerunt.

** Luke 9:41

Respondens autem Jesus, dixit : O generatio infidelis, et perversa, usquequo ero apud vos, et patiar vos ? adduc huc filium tuum.

** Luke 9:42

Et cum accederet, elisit illum dæmonium, et dissipavit.

** Luke 9:43

Et increpavit Jesus spiritum immundum, et sanavit puerum, et reddidit illum patri ejus.  

** Luke 9:44

Stupebant autem omnes in magnitudine Dei : omnibusque mirantibus in omnibus quæ faciebat, dixit ad discipulos suos : Ponite vos in cordibus vestris sermones istos : Filius enim hominis futurum est ut tradatur in manus hominum.

** Luke 9:45

At illi ignorabant verbum istud, et erat velatum ante eos ut non sentirent illud : et timebant eum interrogare de hoc verbo.  

** Luke 9:46

Intravit autem cogitatio in eos quis eorum major esset.

** Luke 9:47

At Jesus videns cogitationes cordis illorum, apprehendit puerum, et statuit illum secus se,

** Luke 9:48

et ait illis : Quicumque susceperit puerum istum in nomine meo, me recipit : et quicumque me receperit, recipit eum qui me misit. Nam qui minor est inter vos omnes, hic major est.  

** Luke 9:49

Respondens autem Joannes dixit : Præceptor, vidimus quemdam in nomine tuo ejicientem dæmonia, et prohibuimus eum : quia non sequitur nobiscum.

** Luke 9:50

Et ait ad illum Jesus : Nolite prohibere : qui enim non est adversum vos, pro vobis est.  

** Luke 9:51

Factum est autem dum complerentur dies assumptionis ejus, et ipse faciem suam firmavit ut iret in Jerusalem.

** Luke 9:52

Et misit nuntios ante conspectum suum : et euntes intraverunt in civitatem Samaritanorum ut parerent illi.

** Luke 9:53

Et non receperunt eum, quia facies ejus erat euntis in Jerusalem.

** Luke 9:54

Cum vidissent autem discipuli ejus Jacobus et Joannes, dixerunt : Domine, vis dicimus ut ignis descendat de cælo, et consumat illos ?

** Luke 9:55

Et conversus increpavit illos, dicens : Nescitis cujus spiritus estis.

** Luke 9:56

Filius hominis non venit animas perdere, sed salvare. Et abierunt in aliud castellum.  

** Luke 9:57

Factum est autem : ambulantibus illis in via, dixit quidam ad illum : Sequar te quocumque ieris.

** Luke 9:58

Dixit illi Jesus : Vulpes foveas habent, et volucres cæli nidos : Filius autem hominis non habet ubi caput reclinet.

** Luke 9:59

Ait autem ad alterum : Sequere me : ille autem dixit : Domine, permitte mihi primum ire, et sepelire patrem meum.

** Luke 9:60

Dixitque ei Jesus : Sine ut mortui sepeliant mortuos suos : tu autem vade, et annuntia regnum Dei.

** Luke 9:61

Et ait alter : Sequar te Domine, sed permitte mihi primum renuntiare his quæ domi sunt.

** Luke 9:62

Ait ad illum Jesus : Nemo mittens manum suam ad aratrum, et respiciens retro, aptus est regno Dei.   

* Luke 10

** Luke 10:1

Post hæc autem designavit Dominus et alios septuaginta duos : et misit illos binos ante faciem suam in omnem civitatem et locum, quo erat ipse venturus.

** Luke 10:2

Et dicebat illis : Messis quidem multa, operarii autem pauci. Rogate ergo dominum messis ut mittat operarios in messem suam.

** Luke 10:3

Ite : ecce ego mitto vos sicut agnos inter lupos.

** Luke 10:4

Nolite portare sacculum, neque peram, neque calceamenta, et neminem per viam salutaveritis.

** Luke 10:5

In quamcumque domum intraveritis, primum dicite : Pax huic domui :

** Luke 10:6

et si ibi fuerit filius pacis, requiescet super illum pax vestra : sin autem, ad vos revertetur.

** Luke 10:7

In eadem autem domo manete, edentes et bibentes quæ apud illos sunt : dignus est enim operarius mercede sua. Nolite transire de domo in domum.

** Luke 10:8

Et in quamcumque civitatem intraveritis, et susceperint vos, manducate quæ apponuntur vobis :

** Luke 10:9

et curate infirmos, qui in illa sunt, et dicite illis : Appropinquavit in vos regnum Dei.

** Luke 10:10

In quamcumque autem civitatem intraveritis, et non susceperint vos, exeuntes in plateas ejus, dicite :

** Luke 10:11

Etiam pulverem, qui adhæsit nobis de civitate vestra, extergimus in vos : tamen hoc scitote, quia appropinquavit regnum Dei.

** Luke 10:12

Dico vobis, quia Sodomis in die illa remissius erit, quam illi civitati.  

** Luke 10:13

Væ tibi Corozain ! væ tibi Bethsaida ! quia si in Tyro et Sidone factæ fuissent virtutes quæ factæ sunt in vobis, olim in cilicio et cinere sedentes pœniterent.

** Luke 10:14

Verumtamen Tyro et Sidoni remissius erit in judicio, quam vobis.

** Luke 10:15

Et tu Capharnaum, usque ad cælum exaltata, usque ad infernum demergeris.

** Luke 10:16

Qui vos audit, me audit : et qui vos spernit, me spernit. Qui autem me spernit, spernit eum qui misit me.  

** Luke 10:17

Reversi sunt autem septuaginta duo cum gaudio, dicentes : Domine, etiam dæmonia subjiciuntur nobis in nomine tuo.

** Luke 10:18

Et ait illis : Videbam Satanam sicut fulgor de cælo cadentem.

** Luke 10:19

Ecce dedi vobis potestatem calcandi supra serpentes, et scorpiones, et super omnem virtutem inimici : et nihil vobis nocebit.

** Luke 10:20

Verumtamen in hoc nolite gaudere quia spiritus vobis subjiciuntur : gaudete autem, quod nomina vestra scripta sunt in cælis.  

** Luke 10:21

In ipsa hora exsultavit Spiritu Sancto, et dixit : Confiteor tibi Pater, Domine cæli et terræ, quod abscondisti hæc a sapientibus et prudentibus, et revelasti ea parvulis. Etiam Pater : quoniam sic placuit ante te.

** Luke 10:22

Omnia mihi tradita sunt a Patre meo. Et nemo scit quis sit Filius, nisi Pater : et quis sit Pater, nisi Filius, et cui voluerit Filius revelare.

** Luke 10:23

Et conversus ad discipulos suos, dixit : Beati oculi qui vident quæ vos videtis.

** Luke 10:24

Dico enim vobis quod multi prophetæ et reges voluerunt videre quæ vos videtis, et non viderunt : et audire quæ auditis, et non audierunt.  

** Luke 10:25

Et ecce quidam legisperitus surrexit tentans illum, et dicens : Magister, quid faciendo vitam æternam possidebo ?

** Luke 10:26

At ille dixit ad eum : In lege quid scriptum est ? quomodo legis ?

** Luke 10:27

Ille respondens dixit : Diliges Dominum Deum tuum ex toto corde tuo, et ex tota anima tua, et ex omnibus virtutibus tuis, et ex omni mente tua : et proximum tuum sicut teipsum.

** Luke 10:28

Dixitque illi : Recte respondisti : hoc fac, et vives.  

** Luke 10:29

Ille autem volens justificare seipsum, dixit ad Jesum : Et quis est meus proximus ?

** Luke 10:30

Suscipiens autem Jesus, dixit : Homo quidam descendebat ab Jerusalem in Jericho, et incidit in latrones, qui etiam despoliaverunt eum : et plagis impositis abierunt semivivo relicto.

** Luke 10:31

Accidit autem ut sacerdos quidam descenderet eadem via : et viso illo præterivit.

** Luke 10:32

Similiter et Levita, cum esset secus locum, et videret eum, pertransiit.

** Luke 10:33

Samaritanus autem quidam iter faciens, venit secus eum : et videns eum, misericordia motus est.

** Luke 10:34

Et appropians alligavit vulnera ejus, infundens oleum et vinum : et imponens illum in jumentum suum, duxit in stabulum, et curam ejus egit.

** Luke 10:35

Et altera die protulit duos denarios, et dedit stabulario, et ait : Curam illius habe : et quodcumque supererogaveris, ego cum rediero reddam tibi.

** Luke 10:36

Quis horum trium videtur tibi proximus fuisse illi, qui incidit in latrones ?

** Luke 10:37

At ille dixit : Qui fecit misericordiam in illum. Et ait illi Jesus : Vade, et tu fac similiter.  

** Luke 10:38

Factum est autem, dum irent, et ipse intravit in quoddam castellum : et mulier quædam, Martha nomine, excepit illum in domum suam,

** Luke 10:39

et huic erat soror nomine Maria, quæ etiam sedens secus pedes Domini, audiebat verbum illius.

** Luke 10:40

Martha autem satagebat circa frequens ministerium : quæ stetit, et ait : Domine, non est tibi curæ quod soror mea reliquit me solam ministrare ? dic ergo illi ut me adjuvet.

** Luke 10:41

Et respondens dixit illi Dominus : Martha, Martha, sollicita es, et turbaris erga plurima,

** Luke 10:42

porro unum est necessarium. Maria optimam partem elegit, quæ non auferetur ab ea.   

* Luke 11

** Luke 11:1

Et factum est : cum esset in quodam loco orans, ut cessavit, dixit unus ex discipulis ejus ad eum : Domine, doce nos orare, sicut docuit et Joannes discipulos suos.

** Luke 11:2

Et ait illis : Cum oratis, dicite : Pater, sanctificetur nomen tuum. Adveniat regnum tuum.

** Luke 11:3

Panem nostrum quotidianum da nobis hodie.

** Luke 11:4

Et dimitte nobis peccata nostra, siquidem et ipsi dimittimus omni debenti nobis. Et ne nos inducas in tentationem.  

** Luke 11:5

Et ait ad illos : Quis vestrum habebit amicum, et ibit ad illum media nocte, et dicet illi : Amice, commoda mihi tres panes,

** Luke 11:6

quoniam amicus meus venit de via ad me, et non habeo quod ponam ante illum,

** Luke 11:7

et ille de intus respondens dicat : Noli mihi molestus esse, jam ostium clausum est, et pueri mei mecum sunt in cubili : non possum surgere, et dare tibi.

** Luke 11:8

Et si ille perseveraverit pulsans : dico vobis, etsi non dabit illi surgens eo quod amicus ejus sit, propter improbitatem tamen ejus surget, et dabit illi quotquot habet necessarios.

** Luke 11:9

Et ego dico vobis : Petite, et dabitur vobis ; quærite, et invenietis ; pulsate, et aperietur vobis.

** Luke 11:10

Omnis enim qui petit, accipit : et qui quærit, invenit : et pulsanti aperietur.

** Luke 11:11

Quis autem ex vobis patrem petit panem, numquid lapidem dabit illi ? aut piscem, numquid pro pisce serpentem dabit illi ?

** Luke 11:12

aut si petierit ovum, numquid porriget illi scorpionem ?

** Luke 11:13

Si ergo vos, cum sitis mali, nostis bona data dare filiis vestris : quanto magis Pater vester de cælo dabit spiritum bonum petentibus se ?  

** Luke 11:14

Et erat ejiciens dæmonium, et illud erat mutum. Et cum ejecisset dæmonium, locutus est mutus, et admiratæ sunt turbæ.

** Luke 11:15

Quidam autem ex eis dixerunt : In Beelzebub principe dæmoniorum ejicit dæmonia.

** Luke 11:16

Et alii tentantes, signum de cælo quærebant ab eo.

** Luke 11:17

Ipse autem ut vidit cogitationes eorum, dixit eis : Omne regnum in seipsum divisum desolabitur, et domus supra domum cadet.

** Luke 11:18

Si autem et Satanas in seipsum divisus est, quomodo stabit regnum ejus ? quia dicitis in Beelzebub me ejicere dæmonia.

** Luke 11:19

Si autem ego in Beelzebub ejicio dæmonia : filii vestri in quo ejiciunt ? ideo ipsi judices vestri erunt.

** Luke 11:20

Porro si in digito Dei ejicio dæmonia : profecto pervenit in vos regnum Dei.

** Luke 11:21

Cum fortis armatus custodit atrium suum, in pace sunt ea quæ possidet.

** Luke 11:22

Si autem fortior eo superveniens vicerit eum, universa arma ejus auferet, in quibus confidebat, et spolia ejus distribuet.

** Luke 11:23

Qui non est mecum, contra me est : et qui non colligit mecum, dispergit.

** Luke 11:24

Cum immundus spiritus exierit de homine, ambulat per loca inaquosa, quærens requiem : et non inveniens dicit : Revertar in domum meam unde exivi.

** Luke 11:25

Et cum venerit, invenit eam scopis mundatam, et ornatam.

** Luke 11:26

Tunc vadit, et assumit septem alios spiritus secum, nequiores se, et ingressi habitant ibi. Et fiunt novissima hominis illius pejora prioribus.  

** Luke 11:27

Factum est autem, cum hæc diceret : extollens vocem quædam mulier de turba dixit illi : Beatus venter qui te portavit, et ubera quæ suxisti.

** Luke 11:28

At ille dixit : Quinimmo beati, qui audiunt verbum Dei et custodiunt illud.  

** Luke 11:29

Turbis autem concurrentibus cœpit dicere : Generatio hæc, generatio nequam est : signum quærit, et signum non dabitur ei, nisi signum Jonæ prophetæ.

** Luke 11:30

Nam sicut fuit Jonas signum Ninivitis, ita erit et Filius hominis generationi isti.

** Luke 11:31

Regina austri surget in judicio cum viris generationis hujus, et condemnabit illos : quia venit a finibus terræ audire sapientiam Salomonis : et ecce plus quam Salomon hic.

** Luke 11:32

Viri Ninivitæ surgent in judicio cum generatione hac, et condemnabunt illam : quia pœnitentiam egerunt ad prædicationem Jonæ, et ecce plus quam Jonas hic.  

** Luke 11:33

Nemo lucernam accendit, et in abscondito ponit, neque sub modio : sed supra candelabrum, ut qui ingrediuntur, lumen videant.

** Luke 11:34

Lucerna corporis tui est oculus tuus. Si oculus tuus fuerit simplex, totum corpus tuum lucidum erit : si autem nequam fuerit, etiam corpus tuum tenebrosum erit.

** Luke 11:35

Vide ergo ne lumen quod in te est, tenebræ sint.

** Luke 11:36

Si ergo corpus tuum totum lucidum fuerit, non habens aliquam partem tenebrarum, erit lucidum totum, et sicut lucerna fulgoris illuminabit te.

** Luke 11:37

Et cum loqueretur, rogavit illum quidam pharisæus ut pranderet apud se. Et ingressus recubuit.  

** Luke 11:38

Pharisæus autem cœpit intra se reputans dicere, quare non baptizatus esset ante prandium.

** Luke 11:39

Et ait Dominus ad illum : Nunc vos pharisæi, quod deforis est calicis et catini, mundatis : quod autem intus est vestrum, plenum est rapina et iniquitate.

** Luke 11:40

Stulti ! nonne qui fecit quod deforis est, etiam id quod deintus est fecit ?

** Luke 11:41

Verumtamen quod superest, date eleemosynam : et ecce omnia munda sunt vobis.

** Luke 11:42

Sed væ vobis, pharisæis, quia decimatis mentham, et rutam, et omne olus, et præteritis judicium et caritatem Dei : hæc autem oportuit facere, et illa non omittere.

** Luke 11:43

Væ vobis, pharisæis, quia diligitis primas cathedras in synagogis, et salutationes in foro.

** Luke 11:44

Væ vobis, quia estis ut monumenta, quæ non apparent, et homines ambulantes supra, nesciunt.

** Luke 11:45

Respondens autem quidam ex legisperitis, ait illi : Magister, hæc dicens etiam contumeliam nobis facis.

** Luke 11:46

At ille ait : Et vobis legisperitis væ : quia oneratis homines oneribus, quæ portare non possunt, et ipsi uno digito vestro non tangitis sarcinas.

** Luke 11:47

Væ vobis, qui ædificatis monumenta prophetarum : patres autem vestri occiderunt illos.

** Luke 11:48

Profecto testificamini quod consentitis operibus patrum vestrorum : quoniam ipsi quidem eos occiderunt, vos autem ædificatis eorum sepulchra.

** Luke 11:49

Propterea et sapientia Dei dixit : Mittam ad illos prophetas, et apostolos, et ex illis occident, et persequentur :

** Luke 11:50

ut inquiratur sanguis omnium prophetarum, qui effusus est a constitutione mundi a generatione ista,

** Luke 11:51

a sanguine Abel, usque ad sanguinem Zachariæ, qui periit inter altare et ædem. Ita dico vobis, requiretur ab hac generatione.

** Luke 11:52

Væ vobis, legisperitis, quia tulistis clavem scientiæ : ipsi non introistis, et eos qui introibant, prohibuistis.

** Luke 11:53

Cum autem hæc ad illos diceret, cœperunt pharisæi et legisperiti graviter insistere, et os ejus opprimere de multis,

** Luke 11:54

insidiantes ei, et quærentes aliquid capere de ore ejus, ut accusarent eum.   

* Luke 12

** Luke 12:1

Multis autem turbis circumstantibus, ita ut se invicem conculcarent, cœpit dicere ad discipulos suos : Attendite a fermento pharisæorum, quod est hypocrisis.

** Luke 12:2

Nihil autem opertum est, quod non reveletur : neque absconditum, quod non sciatur.

** Luke 12:3

Quoniam quæ in tenebris dixistis, in lumine dicentur : et quod in aurem locuti estis in cubiculis, prædicabitur in tectis.  

** Luke 12:4

Dico autem vobis amicis meis : Ne terreamini ab his qui occidunt corpus, et post hæc non habent amplius quid faciant.

** Luke 12:5

Ostendam autem vobis quem timeatis : timete eum qui, postquam occiderit, habet potestatem mittere in gehennam : ita dico vobis, hunc timete.

** Luke 12:6

Nonne quinque passeres veneunt dipondio, et unus ex illis non est in oblivione coram Deo ?

** Luke 12:7

sed et capilli capitis vestri omnes numerati sunt. Nolite ergo timere : multis passeribus pluris estis vos.  

** Luke 12:8

Dico autem vobis : Omnis quicumque confessus fuerit me coram hominibus, et Filius hominis confitebitur illum coram angelis Dei :

** Luke 12:9

qui autem negaverit me coram hominibus, negabitur coram angelis Dei.

** Luke 12:10

Et omnis qui dicit verbum in Filium hominis, remittetur illi : ei autem qui in Spiritum Sanctum blasphemaverit, non remittetur.

** Luke 12:11

Cum autem inducent vos in synagogas, et ad magistratus, et potestates, nolite solliciti esse qualiter, aut quid respondeatis, aut quid dicatis.

** Luke 12:12

Spiritus enim Sanctus docebit vos in ipsa hora quid oporteat vos dicere.

** Luke 12:13

Ait autem ei quidam de turba : Magister, dic fratri meo ut dividat mecum hæreditatem.

** Luke 12:14

At ille dixit illi : Homo, quis me constituit judicem, aut divisorem super vos ?  

** Luke 12:15

Dixitque ad illos : Videte, et cavete ab omni avaritia : quia non in abundantia cujusquam vita ejus est ex his quæ possidet.

** Luke 12:16

Dixit autem similitudinem ad illos, dicens : Hominis cujusdam divitis uberes fructus ager attulit :

** Luke 12:17

et cogitabat intra se dicens : Quid faciam, quia non habeo quo congregem fructus meos ?

** Luke 12:18

Et dixit : Hoc faciam : destruam horrea mea, et majora faciam : et illuc congregabo omnia quæ nata sunt mihi, et bona mea,

** Luke 12:19

et dicam animæ meæ : Anima, habes multa bona posita in annos plurimos : requiesce, comede, bibe, epulare.

** Luke 12:20

Dixit autem illi Deus : Stulte, hac nocte animam tuam repetunt a te : quæ autem parasti, cujus erunt ?

** Luke 12:21

Sic est qui sibi thesaurizat, et non est in Deum dives.  

** Luke 12:22

Dixitque ad discipulos suos : Ideo dico vobis, nolite solliciti esse animæ vestræ quid manducetis, neque corpori quid induamini.

** Luke 12:23

Anima plus est quam esca, et corpus plus quam vestimentum.

** Luke 12:24

Considerate corvos, quia non seminant, neque metunt, quibus non est cellarium, neque horreum, et Deus pascit illos. Quanto magis vos pluris estis illis ?

** Luke 12:25

Quis autem vestrum cogitando potest adjicere ad staturam suam cubitum unum ?

** Luke 12:26

Si ergo neque quod minimum est potestis, quid de ceteris solliciti estis ?

** Luke 12:27

Considerate lilia quomodo crescunt : non laborant, neque nent : dico autem vobis, nec Salomon in omni gloria sua vestiebatur sicut unum ex istis.

** Luke 12:28

Si autem fœnum, quod hodie est in agro, et cras in clibanum mittitur, Deus sic vestit : quanto magis vos pusillæ fidei ?

** Luke 12:29

Et vos nolite quærere quid manducetis, aut quid bibatis : et nolite in sublime tolli :

** Luke 12:30

hæc enim omnia gentes mundi quærunt. Pater autem vester scit quoniam his indigetis.

** Luke 12:31

Verumtamen quærite primum regnum Dei, et justitiam ejus : et hæc omnia adjicientur vobis.

** Luke 12:32

Nolite timere pusillus grex, quia complacuit Patri vestro dare vobis regnum.

** Luke 12:33

Vendite quæ possidetis, et date eleemosynam. Facite vobis sacculos, qui non veterascunt, thesaurum non deficientem in cælis : quo fur non appropriat, neque tinea corrumpit.

** Luke 12:34

Ubi enim thesaurus vester est, ibi et cor vestrum erit.  

** Luke 12:35

Sint lumbi vestri præcincti, et lucernæ ardentes in manibus vestris,

** Luke 12:36

et vos similes hominibus exspectantibus dominum suum quando revertatur a nuptiis : ut, cum venerit et pulsaverit, confestim aperiant ei.

** Luke 12:37

Beati servi illi quos, cum venerit dominus, invenerit vigilantes : amen dico vobis, quod præcinget se, et faciet illos discumbere, et transiens ministrabit illis.

** Luke 12:38

Et si venerit in secunda vigilia, et si in tertia vigilia venerit, et ita invenerit, beati sunt servi illi.

** Luke 12:39

Hoc autem scitote, quoniam si sciret paterfamilias, qua hora fur veniret, vigilaret utique, et non sineret perfodi domum suam.

** Luke 12:40

Et vos estote parati : quia qua hora non putatis, Filius hominis veniet.

** Luke 12:41

Ait autem ei Petrus : Domine, ad nos dicis hanc parabolam, an et ad omnes ?

** Luke 12:42

Dixit autem Dominus : Quis, putas, est fidelis dispensator, et prudens, quem constituit dominus supra familiam suam, ut det illis in tempore tritici mensuram ?

** Luke 12:43

Beatus ille servus quem, cum venerit dominus, invenerit ita facientem.

** Luke 12:44

Vere dico vobis, quoniam supra omnia quæ possidet, constituet illum.

** Luke 12:45

Quod si dixerit servus ille in corde suo : Moram facit dominus meus venire : et cœperit percutere servos, et ancillas, et edere, et bibere, et inebriari :

** Luke 12:46

veniet dominus servi illius in die qua non sperat, et hora qua nescit, et dividet eum, partemque ejus cum infidelibus ponet.

** Luke 12:47

Ille autem servus qui cognovit voluntatem domini sui, et non præparavit, et non facit secundum voluntatem ejus, vapulabit multis :

** Luke 12:48

qui autem non cognovit, et fecit digna plagis, vapulabit paucis. Omni autem cui multum datum est, multum quæretur ab eo : et cui commendaverunt multum, plus petent ab eo.  

** Luke 12:49

Ignem veni mittere in terram, et quid volo nisi ut accendatur ?

** Luke 12:50

Baptismo autem habeo baptizari : et quomodo coarctor usque dum perficiatur ?

** Luke 12:51

Putatis quia pacem veni dare in terram ? non, dico vobis, sed separationem :

** Luke 12:52

erunt enim ex hoc quinque in domo una divisi, tres in duos, et duo in tres

** Luke 12:53

dividentur : pater in filium, et filius in patrem suum, mater in filiam, et filia in matrem, socrus in nurum suam, et nurus in socrum suam.  

** Luke 12:54

Dicebat autem et ad turbas : Cum videritis nubem orientem ab occasu, statim dicitis : Nimbus venit : et ita fit.

** Luke 12:55

Et cum austrum flantem, dicitis : Quia æstus erit : et fit.

** Luke 12:56

Hypocritæ ! faciem cæli et terræ nostis probare : hoc autem tempus quomodo non probatis ?

** Luke 12:57

quid autem et a vobis ipsis non judicatis quod justum est ?  

** Luke 12:58

Cum autem vadis cum adversario tuo ad principem, in via da operam liberari ab illo, ne forte trahat te ad judicem, et judex tradat te exactori, et exactor mittat te in carcerem.

** Luke 12:59

Dico tibi, non exies inde, donec etiam novissimum minutum reddas.   

* Luke 13

** Luke 13:1

Aderant autem quidam ipso in tempore, nuntiantes illi de Galilæis, quorum sanguinem Pilatus miscuit cum sacrificiis eorum.

** Luke 13:2

Et respondens dixit illis : Putatis quod hi Galilæi præ omnibus Galilæis peccatores fuerint, quia talia passi sunt ?

** Luke 13:3

Non, dico vobis : sed nisi pœnitentiam habueritis, omnes similiter peribitis.

** Luke 13:4

Sicut illi decem et octo, supra quos cecidit turris in Siloë, et occidit eos : putatis quia et ipsi debitores fuerint præter omnes homines habitantes in Jerusalem ?

** Luke 13:5

Non, dico vobis : sed si pœnitentiam non egeritis, omnes similiter peribitis.  

** Luke 13:6

Dicebat autem et hanc similitudinem : Arborem fici habebat quidam plantatam in vinea sua, et venit quærens fructum in illa, et non invenit.

** Luke 13:7

Dixit autem ad cultorem vineæ : Ecce anni tres sunt ex quo venio quærens fructum in ficulnea hac, et non invenio : succide ergo illam : ut quid etiam terram occupat ?

** Luke 13:8

At ille respondens, dicit illi : Domine dimitte illam et hoc anno, usque dum fodiam circa illam, et mittam stercora,

** Luke 13:9

et siquidem fecerit fructum : sin autem, in futurum succides eam.  

** Luke 13:10

Erat autem docens in synagoga eorum sabbatis.

** Luke 13:11

Et ecce mulier, quæ habebat spiritum infirmitatis annis decem et octo : et erat inclinata, nec omnino poterat sursum respicere.

** Luke 13:12

Quam cum videret Jesus, vocavit eam ad se, et ait illi : Mulier, dimissa es ab infirmitate tua.

** Luke 13:13

Et imposuit illi manus, et confestim erecta est, et glorificabat Deum.

** Luke 13:14

Respondens autem archisynagogus, indignans quia sabbato curasset Jesus, dicebat turbæ : Sex dies sunt in quibus oportet operari : in his ergo venite, et curamini, et non in die sabbati.

** Luke 13:15

Respondens autem ad illum Dominus, dixit : Hypocritæ, unusquisque vestrum sabbato non solvit bovem suum, aut asinum a præsepio, et ducit adaquare ?

** Luke 13:16

Hanc autem filiam Abrahæ, quam alligavit Satanas, ecce decem et octo annis, non oportuit solvi a vinculo isto die sabbati ?

** Luke 13:17

Et cum hæc diceret, erubescebant omnes adversarii ejus : et omnis populus gaudebat in universis, quæ gloriose fiebant ab eo.  

** Luke 13:18

Dicebat ergo : Cui simile est regnum Dei, et cui simile æstimabo illud ?

** Luke 13:19

Simile est grano sinapis, quod acceptum homo misit in hortum suum, et crevit, et factum est in arborem magnam : et volucres cæli requieverunt in ramis ejus.

** Luke 13:20

Et iterum dixit : Cui simile æstimabo regnum Dei ?

** Luke 13:21

Simile est fermento, quod acceptum mulier abscondit in farinæ sata tria, donec fermentaretur totum.  

** Luke 13:22

Et ibat per civitates et castella, docens, et iter faciens in Jerusalem.

** Luke 13:23

Ait autem illi quidam : Domine, si pauci sunt, qui salvantur ? Ipse autem dixit ad illos :

** Luke 13:24

Contendite intrare per angustam portam : quia multi, dico vobis, quærent intrare, et non poterunt.

** Luke 13:25

Cum autem intraverit paterfamilias, et clauserit ostium, incipietis foris stare, et pulsare ostium, dicentes : Domine, aperi nobis : et respondens dicet vobis : Nescio vos unde sitis :

** Luke 13:26

tunc incipietis dicere : Manducavimus coram te, et bibimus, et in plateis nostris docuisti.

** Luke 13:27

Et dicet vobis : Nescio vos unde sitis : discedite a me omnes operarii iniquitatis.

** Luke 13:28

Ibi erit fletus et stridor dentium : cum videritis Abraham, et Isaac, et Jacob, et omnes prophetas in regno Dei, vos autem expelli foras.

** Luke 13:29

Et venient ab oriente, et occidente, et aquilone, et austro, et accumbent in regno Dei.

** Luke 13:30

Et ecce sunt novissimi qui erunt primi, et sunt primi qui erunt novissimi.  

** Luke 13:31

In ipsa die accesserunt quidam pharisæorum, dicentes illi : Exi, et vade hinc : quia Herodes vult te occidere.

** Luke 13:32

Et ait illis : Ite, et dicite vulpi illi : Ecce ejicio dæmonia, et sanitates perficio hodie, et cras, et tertia die consummor.

** Luke 13:33

Verumtamen oportet me hodie et cras et sequenti die ambulare : quia non capit prophetam perire extra Jerusalem.

** Luke 13:34

Jerusalem, Jerusalem, quæ occidis prophetas, et lapidas eos qui mittuntur ad te, quoties volui congregare filios tuos quemadmodum avis nidum suum sub pennis, et noluisti ?

** Luke 13:35

Ecce relinquetur vobis domus vestra deserta. Dico autem vobis, quia non videbitis me donec veniat cum dicetis : Benedictus qui venit in nomine Domini.   

* Luke 14

** Luke 14:1

Et factum est cum intraret Jesus in domum cujusdam principis pharisæorum sabbato manducare panem, et ipsi observabant eum.

** Luke 14:2

Et ecce homo quidam hydropicus erat ante illum.

** Luke 14:3

Et respondens Jesus dixit ad legisperitos et pharisæos, dicens : Si licet sabbato curare ?

** Luke 14:4

At illi tacuerunt. Ipse vero apprehensum sanavit eum, ac dimisit.

** Luke 14:5

Et respondens ad illos dixit : Cujus vestrum asinus, aut bos in puteum cadet, et non continuo extrahet illum die sabbati ?

** Luke 14:6

Et non poterant ad hæc respondere illi.  

** Luke 14:7

Dicebat autem et ad invitatos parabolam, intendens quomodo primos accubitus eligerent, dicens ad illos :

** Luke 14:8

Cum invitatus fueris ad nuptias, non discumbas in primo loco, ne forte honoratior te sit invitatus ab illo.

** Luke 14:9

Et veniens is, qui te et illum vocavit, dicat tibi : Da huic locum : et tunc incipias cum rubore novissimum locum tenere.

** Luke 14:10

Sed cum vocatus fueris, vade, recumbe in novissimo loco : ut, cum venerit qui te invitavit, dicat tibi : Amice, ascende superius. Tunc erit tibi gloria coram simul discumbentibus :

** Luke 14:11

quia omnis, qui se exaltat, humiliabitur : et qui se humiliat, exaltabitur.  

** Luke 14:12

Dicebat autem et ei, qui invitaverat : Cum facis prandium, aut cœnam, noli vocare amicos tuos, neque fratres tuos, neque cognatos, neque vicinos divites : ne forte te et ipsi reinvitent, et fiat tibi retributio ;

** Luke 14:13

sed cum facis convivium, voca pauperes, debiles, claudos, et cæcos :

** Luke 14:14

et beatus eris, quia non habent retribuere tibi : retribuetur enim tibi in resurrectione justorum.  

** Luke 14:15

Hæc cum audisset quidam de simul discumbentibus, dixit illi : Beatus qui manducabit panem in regno Dei.

** Luke 14:16

At ipse dixit ei : Homo quidam fecit cœnam magnam, et vocavit multos.

** Luke 14:17

Et misit servum suum hora cœnæ dicere invitatis ut venirent, quia jam parata sunt omnia.

** Luke 14:18

Et cœperunt simul omnes excusare. Primus dixit ei : Villam emi, et necesse habeo exire, et videre illam : rogo te, habe me excusatum.

** Luke 14:19

Et alter dixit : Juga boum emi quinque, et eo probare illa : rogo te, habe me excusatum.

** Luke 14:20

Et alius dixit : Uxorem duxi, et ideo non possum venire.

** Luke 14:21

Et reversus servus nuntiavit hæc domino suo. Tunc iratus paterfamilias, dixit servo suo : Exi cito in plateas et vicos civitatis : et pauperes, ac debiles, et cæcos, et claudos introduc huc.

** Luke 14:22

Et ait servus : Domine, factum est ut imperasti, et adhuc locus est.

** Luke 14:23

Et ait dominus servo : Exi in vias, et sæpes : et compelle intrare, ut impleatur domus mea.

** Luke 14:24

Dico autem vobis quod nemo virorum illorum qui vocati sunt, gustabit cœnam meam.  

** Luke 14:25

Ibant autem turbæ multæ cum eo : et conversus dixit ad illos :

** Luke 14:26

Si quis venit ad me, et non odit patrem suum, et matrem, et uxorem, et filios, et fratres, et sorores, adhuc autem et animam suam, non potest meus esse discipulus.

** Luke 14:27

Et qui non bajulat crucem suam, et venit post me, non potest meus esse discipulus.

** Luke 14:28

Quis enim ex vobis volens turrim ædificare, non prius sedens computat sumptus, qui necessarii sunt, si habeat ad perficiendum,

** Luke 14:29

ne, posteaquam posuerit fundamentum, et non potuerit perficere, omnes qui vident, incipiant illudere ei,

** Luke 14:30

dicentes : Quia hic homo cœpit ædificare, et non potuit consummare ?

** Luke 14:31

Aut quis rex iturus committere bellum adversus alium regem, non sedens prius cogitat, si possit cum decem millibus occurrere ei, qui cum viginti millibus venit ad se ?

** Luke 14:32

Alioquin adhuc illo longe agente, legationem mittens rogat ea quæ pacis sunt.

** Luke 14:33

Sic ergo omnis ex vobis, qui non renuntiat omnibus quæ possidet, non potest meus esse discipulus.

** Luke 14:34

Bonum est sal : si autem sal evanuerit, in quo condietur ?

** Luke 14:35

Neque in terram, neque in sterquilinium utile est, sed foras mittetur. Qui habet aures audiendi, audiat.   

* Luke 15

** Luke 15:1

Erant autem appropinquantes ei publicani, et peccatores ut audirent illum.

** Luke 15:2

Et murmurabant pharisæi, et scribæ, dicentes : Quia hic peccatores recipit, et manducat cum illis.

** Luke 15:3

Et ait ad illos parabolam istam dicens :

** Luke 15:4

Quis ex vobis homo, qui habet centum oves, et si perdiderit unam ex illis, nonne dimittit nonaginta novem in deserto, et vadit ad illam quæ perierat, donec inveniat eam ?

** Luke 15:5

Et cum invenerit eam, imponit in humeros suos gaudens :

** Luke 15:6

et veniens domum convocat amicos et vicinos, dicens illis : Congratulamini mihi, quia inveni ovem meam, quæ perierat.

** Luke 15:7

Dico vobis quod ita gaudium erit in cælo super uno peccatore pœnitentiam agente, quam super nonaginta novem justis, qui non indigent pœnitentia.  

** Luke 15:8

Aut quæ mulier habens drachmas decem, si perdiderit drachmam unam, nonne accendit lucernam, et everrit domum, et quærit diligenter, donec inveniat ?

** Luke 15:9

Et cum invenerit convocat amicas et vicinas, dicens : Congratulamini mihi, quia inveni drachmam quam perdideram.

** Luke 15:10

Ita, dico vobis, gaudium erit coram angelis Dei super uno peccatore pœnitentiam agente.  

** Luke 15:11

Ait autem : Homo quidam habuit duos filios :

** Luke 15:12

et dixit adolescentior ex illis patri : Pater, da mihi portionem substantiæ, quæ me contingit. Et divisit illis substantiam.

** Luke 15:13

Et non post multos dies, congregatis omnibus, adolescentior filius peregre profectus est in regionem longinquam, et ibi dissipavit substantiam suam vivendo luxuriose.

** Luke 15:14

Et postquam omnia consummasset, facta est fames valida in regione illa, et ipse cœpit egere.

** Luke 15:15

Et abiit, et adhæsit uni civium regionis illius : et misit illum in villam suam ut pasceret porcos.

** Luke 15:16

Et cupiebat implere ventrem suum de siliquis, quas porci manducabant : et nemo illi dabat.

** Luke 15:17

In se autem reversus, dixit : Quanti mercenarii in domo patris mei abundant panibus, ego autem hic fame pereo !

** Luke 15:18

surgam, et ibo ad patrem meum, et dicam ei : Pater, peccavi in cælum, et coram te :

** Luke 15:19

jam non sum dignus vocari filius tuus : fac me sicut unum de mercenariis tuis.

** Luke 15:20

Et surgens venit ad patrem suum. Cum autem adhuc longe esset, vidit illum pater ipsius, et misericordia motus est, et accurrens cecidit super collum ejus, et osculatus est eum.

** Luke 15:21

Dixitque ei filius : Pater, peccavi in cælum, et coram te : jam non sum dignus vocari filius tuus.

** Luke 15:22

Dixit autem pater ad servos suos : Cito proferte stolam primam, et induite illum, et date annulum in manum ejus, et calceamenta in pedes ejus :

** Luke 15:23

et adducite vitulum saginatum, et occidite, et manducemus, et epulemur :

** Luke 15:24

quia hic filius meus mortuus erat, et revixit : perierat, et inventus est. Et cœperunt epulari.

** Luke 15:25

Erat autem filius ejus senior in agro : et cum veniret, et appropinquaret domui, audivit symphoniam et chorum :

** Luke 15:26

et vocavit unum de servis, et interrogavit quid hæc essent.

** Luke 15:27

Isque dixit illi : Frater tuus venit, et occidit pater tuus vitulum saginatum, quia salvum illum recepit.

** Luke 15:28

Indignatus est autem, et nolebat introire. Pater ergo illius egressus, cœpit rogare illum.

** Luke 15:29

At ille respondens, dixit patri suo : Ecce tot annis servio tibi, et numquam mandatum tuum præterivi : et numquam dedisti mihi hædum ut cum amicis meis epularer.

** Luke 15:30

Sed postquam filius tuus hic, qui devoravit substantiam suam cum meretricibus, venit, occidisti illi vitulum saginatum.

** Luke 15:31

At ipse dixit illi : Fili, tu semper mecum es, et omnia mea tua sunt :

** Luke 15:32

epulari autem, et gaudere oportebat, quia frater tuus hic mortuus erat, et revixit ; perierat, et inventus est.   

* Luke 16

** Luke 16:1

Dicebat autem et ad discipulos suos : Homo quidam erat dives, qui habebat villicum : et hic diffamatus est apud illum quasi dissipasset bona ipsius.

** Luke 16:2

Et vocavit illum, et ait illi : Quid hoc audio de te ? redde rationem villicationis tuæ : jam enim non poteris villicare.

** Luke 16:3

Ait autem villicus intra se : Quid faciam, quia dominus meus aufert a me villicationem ? Fodere non valeo, mendicare erubesco.

** Luke 16:4

Scio quid faciam, ut, cum amotus fuero a villicatione, recipiant me in domos suas.

** Luke 16:5

Convocatis itaque singulis debitoribus domini sui, dicebat primo : Quantum debes domino meo ?

** Luke 16:6

At ille dixit : Centum cados olei. Dixitque illi : Accipe cautionem tuam : et sede cito, scribe quinquaginta.

** Luke 16:7

Deinde alii dixit : Tu vero quantum debes ? Qui ait : Centum coros tritici. Ait illi : Accipe litteras tuas, et scribe octoginta.

** Luke 16:8

Et laudavit dominus villicum iniquitatis, quia prudenter fecisset : quia filii hujus sæculi prudentiores filiis lucis in generatione sua sunt.

** Luke 16:9

Et ego vobis dico : facite vobis amicos de mammona iniquitatis : ut, cum defeceritis, recipiant vos in æterna tabernacula.

** Luke 16:10

Qui fidelis est in minimo, et in majori fidelis est : et qui in modico iniquus est, et in majori iniquus est.

** Luke 16:11

Si ergo in iniquo mammona fideles non fuistis quod verum est, quis credet vobis ?

** Luke 16:12

Et si in alieno fideles non fuistis, quod vestrum est, quis dabit vobis ?

** Luke 16:13

Nemo servus potest duobus dominis servire : aut enim unum odiet, et alterum diliget : aut uni adhærebit, et alterum contemnet. Non potestis Deo servire et mammonæ.  

** Luke 16:14

Audiebant autem omnia hæc pharisæi, qui erant avari : et deridebant illum.

** Luke 16:15

Et ait illis : Vos estis qui justificatis vos coram hominibus : Deus autem novit corda vestra : quia quod hominibus altum est, abominatio est ante Deum.

** Luke 16:16

Lex et prophetæ usque ad Joannem : ex eo regnum Dei evangelizatur, et omnis in illud vim facit.

** Luke 16:17

Facilius est autem cælum et terram præterire, quam de lege unum apicem cadere.

** Luke 16:18

Omnis qui dimittit uxorem suam et alteram ducit, mœchatur : et qui dimissam a viro ducit, mœchatur.  

** Luke 16:19

Homo quidam erat dives, qui induebatur purpura et bysso, et epulabatur quotidie splendide.

** Luke 16:20

Et erat quidam mendicus, nomine Lazarus, qui jacebat ad januam ejus, ulceribus plenus,

** Luke 16:21

cupiens saturari de micis quæ cadebant de mensa divitis, et nemo illi dabat : sed et canes veniebant, et lingebant ulcera ejus.

** Luke 16:22

Factum est autem ut moreretur mendicus, et portaretur ab angelis in sinum Abrahæ. Mortuus est autem et dives, et sepultus est in inferno.

** Luke 16:23

Elevans autem oculos suos, cum esset in tormentis, vidit Abraham a longe, et Lazarum in sinu ejus :

** Luke 16:24

et ipse clamans dixit : Pater Abraham, miserere mei, et mitte Lazarum ut intingat extremum digiti sui in aquam, ut refrigeret linguam meam, quia crucior in hac flamma.

** Luke 16:25

Et dixit illi Abraham : Fili, recordare quia recepisti bona in vita tua, et Lazarus similiter mala : nunc autem hic consolatur, tu vero cruciaris :

** Luke 16:26

et in his omnibus inter nos et vos chaos magnum firmatum est : ut hi qui volunt hinc transire ad vos, non possint, neque inde huc transmeare.

** Luke 16:27

Et ait : Rogo ergo te, pater, ut mittas eum in domum patris mei :

** Luke 16:28

habeo enim quinque fratres : ut testetur illis, ne et ipsi veniant in hunc locum tormentorum.

** Luke 16:29

Et ait illi Abraham : Habent Moysen et prophetas : audiant illos.

** Luke 16:30

At ille dixit : Non, pater Abraham : sed si quis ex mortuis ierit ad eos, pœnitentiam agent.

** Luke 16:31

Ait autem illi : Si Moysen et prophetas non audiunt, neque si quis ex mortuis resurrexerit, credent.   

* Luke 17

** Luke 17:1

Et ait ad discipulos suos : Impossibile est ut non veniant scandala : væ autem illi per quem veniunt.

** Luke 17:2

Utilius est illi si lapis molaris imponatur circa collum ejus, et projiciatur in mare quam ut scandalizet unum de pusillis istis.

** Luke 17:3

Attendite vobis : Si peccaverit in te frater tuus, increpa illum : et si pœnitentiam egerit, dimitte illi.

** Luke 17:4

Et si septies in die peccaverit in te, et septies in die conversus fuerit ad te, dicens : Pœnitet me, dimitte illi.

** Luke 17:5

Et dixerunt apostoli Domino : Adauge nobis fidem.

** Luke 17:6

Dixit autem Dominus : Si habueritis fidem sicut granum sinapis, dicetis huic arbori moro : Eradicare, et transplantare in mare, et obediet vobis.

** Luke 17:7

Quis autem vestrum habens servum arantem aut pascentem, qui regresso de agro dicat illi : Statim transi, recumbe :

** Luke 17:8

et non dicat ei : Para quod cœnem, et præcinge te, et ministra mihi donec manducem, et bibam, et post hæc tu manducabis, et bibes ?

** Luke 17:9

Numquid gratiam habet servo illi, quia fecit quæ ei imperaverat ?

** Luke 17:10

non puto. Sic et vos cum feceritis omnia quæ præcepta sunt vobis, dicite : Servi inutiles sumus : quod debuimus facere, fecimus.  

** Luke 17:11

Et factum est, dum iret in Jerusalem, transibat per mediam Samariam et Galilæam.

** Luke 17:12

Et cum ingrederetur quoddam castellum, occurrerunt ei decem viri leprosi, qui steterunt a longe :

** Luke 17:13

et levaverunt vocem, dicentes : Jesu præceptor, miserere nostri.

** Luke 17:14

Quos ut vidit, dixit : Ite, ostendite vos sacerdotibus. Et factum est, dum irent, mundati sunt.

** Luke 17:15

Unus autem ex illis, ut vidit quia mundatus est, regressus est, cum magna voce magnificans Deum,

** Luke 17:16

et cecidit in faciem ante pedes ejus, gratias agens : et hic erat Samaritanus.

** Luke 17:17

Respondens autem Jesus, dixit : Nonne decem mundati sunt ? et novem ubi sunt ?

** Luke 17:18

Non est inventus qui rediret, et daret gloriam Deo, nisi hic alienigena.

** Luke 17:19

Et ait illi : Surge, vade : quia fides tua te salvum fecit.  

** Luke 17:20

Interrogatus autem a pharisæis : Quando venit regnum Dei ? respondens eis, dixit : Non venit regnum Dei cum observatione :

** Luke 17:21

neque dicent : Ecce hic, aut ecce illic. Ecce enim regnum Dei intra vos est.

** Luke 17:22

Et ait ad discipulos suos : Venient dies quando desideretis videre unum diem Filii hominis, et non videbitis.

** Luke 17:23

Et dicent vobis : Ecce hic, et ecce illic. Nolite ire, neque sectemini :

** Luke 17:24

nam, sicut fulgur coruscans de sub cælo in ea quæ sub cælo sunt, fulget : ita erit Filius hominis in die sua.

** Luke 17:25

Primum autem oportet illum multa pati, et reprobari a generatione hac.

** Luke 17:26

Et sicut factum est in diebus Noë, ita erit et in diebus Filii hominis :

** Luke 17:27

edebant et bibebant : uxores ducebant et dabantur ad nuptias, usque in diem, qua intravit Noë in arcam : et venit diluvium, et perdidit omnes.

** Luke 17:28

Similiter sicut factum est in diebus Lot : edebant et bibebant, emebant et vendebant, plantabant et ædificabant :

** Luke 17:29

qua die autem exiit Lot a Sodomis, pluit ignem et sulphur de cælo, et omnes perdidit :

** Luke 17:30

secundum hæc erit qua die Filius hominis revelabitur.

** Luke 17:31

In illa hora, qui fuerit in tecto, et vasa ejus in domo, ne descendat tollere illa : et qui in agro, similiter non redeat retro.

** Luke 17:32

Memores estote uxoris Lot.

** Luke 17:33

Quicumque quæsierit animam suam salvam facere, perdet illam : et quicumque perdiderit illam, vivificabit eam.

** Luke 17:34

Dico vobis : In illa nocte erunt duo in lecto uno : unus assumetur, et alter relinquetur :

** Luke 17:35

duæ erunt molentes in unum : una assumetur, et altera relinquetur : duo in agro : unus assumetur, et alter relinquetur.

** Luke 17:36

Respondentes dicunt illi : Ubi Domine ?

** Luke 17:37

Qui dixit illis : Ubicumque fuerit corpus, illuc congregabuntur et aquilæ.   

* Luke 18

** Luke 18:1

Dicebat autem et parabolam ad illos, quoniam oportet semper orare et non deficere,

** Luke 18:2

dicens : Judex quidam erat in quadam civitate, qui Deum non timebat, et hominem non reverebatur.

** Luke 18:3

Vidua autem quædam erat in civitate illa, et veniebat ad eum, dicens : Vindica me de adversario meo.

** Luke 18:4

Et nolebat per multum tempus. Post hæc autem dixit intra se : Etsi Deum non timeo, nec hominem revereor :

** Luke 18:5

tamen quia molesta est mihi hæc vidua, vindicabo illam, ne in novissimo veniens sugillet me.

** Luke 18:6

Ait autem Dominus : Audite quid judex iniquitatis dicit :

** Luke 18:7

Deus autem non faciet vindictam electorum suorum clamantium ad se die ac nocte, et patientiam habebit in illis ?

** Luke 18:8

Dico vobis quia cito faciet vindictam illorum. Verumtamen Filius hominis veniens, putas, inveniet fidem in terra ?  

** Luke 18:9

Dixit autem et ad quosdam qui in se confidebant tamquam justi, et aspernabantur ceteros, parabolam istam :

** Luke 18:10

Duo homines ascenderunt in templum ut orarent : unus pharisæus et alter publicanus.

** Luke 18:11

Pharisæus stans, hæc apud se orabat : Deus, gratias ago tibi, quia non sum sicut ceteri hominum : raptores, injusti, adulteri, velut etiam hic publicanus :

** Luke 18:12

jejuno bis in sabbato, decimas do omnium quæ possideo.

** Luke 18:13

Et publicanus a longe stans, nolebat nec oculos ad cælum levare : sed percutiebat pectus suum, dicens : Deus propitius esto mihi peccatori.

** Luke 18:14

Dico vobis, descendit hic justificatus in domum suam ab illo : quia omnis qui se exaltat, humiliabitur, et qui se humiliat, exaltabitur.  

** Luke 18:15

Afferebant autem ad illum et infantes, ut eos tangeret. Quod cum viderent discipuli, increpabant illos.

** Luke 18:16

Jesus autem convocans illos, dixit : Sinite pueros venire ad me, et nolite vetare eos : talium est enim regnum Dei.

** Luke 18:17

Amen dico vobis, quicumque non acceperit regnum Dei sicut puer, non intrabit in illud.  

** Luke 18:18

Et interrogavit eum quidam princeps, dicens : Magister bone, quid faciens vitam æternam possidebo ?

** Luke 18:19

Dixit autem ei Jesus : Quid me dicis bonum ? nemo bonus nisi solus Deus.

** Luke 18:20

Mandata nosti : non occides ; non mœchaberis ; non furtum facies ; non falsum testimonium dices ; honora patrem tuum et matrem.

** Luke 18:21

Qui ait : Hæc omnia custodivi a juventute mea.

** Luke 18:22

Quo audito, Jesus ait ei : Adhuc unum tibi deest : omnia quæcumque habes vende, et da pauperibus, et habebis thesaurum in cælo : et veni, sequere me.

** Luke 18:23

His ille auditis, contristatus est : quia dives erat valde.

** Luke 18:24

Videns autem Jesus illum tristem factum, dixit : Quam difficile, qui pecunias habent, in regnum Dei intrabunt !

** Luke 18:25

facilius est enim camelum per foramen acus transire quam divitem intrare in regnum Dei.

** Luke 18:26

Et dixerunt qui audiebant : Et quis potest salvus fieri ?

** Luke 18:27

Ait illis : Quæ impossibilia sunt apud homines, possibilia sunt apud Deum.

** Luke 18:28

Ait autem Petrus : Ecce nos dimisimus omnia et secuti sumus te.

** Luke 18:29

Qui dixit eis : Amen dico vobis, nemo est qui reliquit domum, aut parentes, aut fratres, aut uxorem, aut filios propter regnum Dei,

** Luke 18:30

et non recipiat multo plura in hoc tempore, et in sæculo venturo vitam æternam.  

** Luke 18:31

Assumpsit autem Jesus duodecim, et ait illis : Ecce ascendimus Jerosolymam, et consummabuntur omnia quæ scripta sunt per prophetas de Filio hominis :

** Luke 18:32

tradetur enim gentibus, et illudetur, et flagellabitur, et conspuetur :

** Luke 18:33

et postquam flagellaverint, occident eum, et tertia die resurget.

** Luke 18:34

Et ipsi nihil horum intellexerunt, et erat verbum istud absconditum ab eis, et non intelligebant quæ dicebantur.  

** Luke 18:35

Factum est autem, cum appropinquaret Jericho, cæcus quidam sedebat secus viam, mendicans.

** Luke 18:36

Et cum audiret turbam prætereuntem, interrogabat quid hoc esset.

** Luke 18:37

Dixerunt autem ei quod Jesus Nazarenus transiret.

** Luke 18:38

Et clamavit, dicens : Jesu, fili David, miserere mei.

** Luke 18:39

Et qui præibant, increpabant eum ut taceret. Ipse vero multo magis clamabat : Fili David, miserere mei.

** Luke 18:40

Stans autem Jesus jussit illum adduci ad se. Et cum appropinquasset, interrogavit illum,

** Luke 18:41

dicens : Quid tibi vis faciam ? At ille dixit : Domine, ut videam.

** Luke 18:42

Et Jesus dixit illi : Respice, fides tua te salvum fecit.

** Luke 18:43

Et confestim vidit, et sequebatur illum magnificans Deum. Et omnis plebs ut vidit, dedit laudem Deo.   

* Luke 19

** Luke 19:1

Et ingressus perambulabat Jericho.

** Luke 19:2

Et ecce vir nomine Zachæus : et hic princeps erat publicanorum, et ipse dives :

** Luke 19:3

et quærebat videre Jesum, quis esset : et non poterat præ turba, quia statura pusillus erat.

** Luke 19:4

Et præcurrens ascendit in arborem sycomorum ut videret eum : quia inde erat transiturus.

** Luke 19:5

Et cum venisset ad locum, suspiciens Jesus vidit illum, et dixit ad eum : Zachæe, festinans descende : quia hodie in domo tua oportet me manere.

** Luke 19:6

Et festinans descendit, et excepit illum gaudens.

** Luke 19:7

Et cum viderent omnes, murmurabant, dicentes quod ad hominem peccatorem divertisset.

** Luke 19:8

Stans autem Zachæus, dixit ad Dominum : Ecce dimidium bonorum meorum, Domine, do pauperibus : et si quid aliquem defraudavi, reddo quadruplum.

** Luke 19:9

Ait Jesus ad eum : Quia hodie salus domui huic facta est : eo quod et ipse filius sit Abrahæ.

** Luke 19:10

Venit enim Filius hominis quærere, et salvum facere quod perierat.  

** Luke 19:11

Hæc illis audientibus adjiciens, dixit parabolam, eo quod esset prope Jerusalem : et quia existimarent quod confestim regnum Dei manifestaretur.

** Luke 19:12

Dixit ergo : Homo quidam nobilis abiit in regionem longinquam accipere sibi regnum, et reverti.

** Luke 19:13

Vocatis autem decem servis suis, dedit eis decem mnas, et ait ad illos : Negotiamini dum venio.

** Luke 19:14

Cives autem ejus oderant eum : et miserunt legationem post illum, dicentes : Nolumus hunc regnare super nos.

** Luke 19:15

Et factum est ut rediret accepto regno : et jussit vocari servos, quibus dedit pecuniam, ut sciret quantum quisque negotiatus esset.

** Luke 19:16

Venit autem primus dicens : Domine, mna tua decem mnas acquisivit.

** Luke 19:17

Et ait illi : Euge bone serve, quia in modico fuisti fidelis, eris potestatem habens super decem civitates.

** Luke 19:18

Et alter venit, dicens : Domine, mna tua fecit quinque mnas.

** Luke 19:19

Et huic ait : Et tu esto super quinque civitates.

** Luke 19:20

Et alter venit, dicens : Domine, ecce mna tua, quam habui repositam in sudario :

** Luke 19:21

timui enim te, quia homo austerus es : tollis quod non posuisti, et metis quod non seminasti.

** Luke 19:22

Dicit ei : De ore tuo te judico, serve nequam. Sciebas quod ego homo austerus sum, tollens quod non posui, et metens quod non seminavi :

** Luke 19:23

et quare non dedisti pecuniam meam ad mensam, ut ego veniens cum usuris utique exegissem illam ?

** Luke 19:24

Et astantibus dixit : Auferte ab illo mnam, et date illi qui decem mnas habet.

** Luke 19:25

Et dixerunt ei : Domine, habet decem mnas.

** Luke 19:26

Dico autem vobis, quia omni habenti dabitur, et abundabit : ab eo autem qui non habet, et quod habet auferetur ab eo.

** Luke 19:27

Verumtamen inimicos meos illos, qui noluerunt me regnare super se, adducite huc : et interficite ante me.

** Luke 19:28

Et his dictis, præcedebat ascendens Jerosolymam.  

** Luke 19:29

Et factum est, cum appropinquasset ad Bethphage et Bethaniam, ad montem qui vocatur Oliveti, misit duos discipulos suos,

** Luke 19:30

dicens : Ite in castellum quod contra est : in quod introëuntes, invenietis pullum asinæ alligatum, cui nemo umquam hominum sedit : solvite illum, et adducite.

** Luke 19:31

Et si quis vos interrogaverit : Quare solvitis ? sic dicetis ei : Quia Dominus operam ejus desiderat.

** Luke 19:32

Abierunt autem qui missi erant : et invenerunt, sicut dixit illis, stantem pullum.

** Luke 19:33

Solventibus autem illis pullum, dixerunt domini ejus ad illos : Quid solvitis pullum ?

** Luke 19:34

At illi dixerunt : Quia Dominus eum necessarium habet.

** Luke 19:35

Et duxerunt illum ad Jesum. Et jactantes vestimenta sua supra pullum, imposuerunt Jesum.

** Luke 19:36

Eunte autem illo, substernebant vestimenta sua in via :

** Luke 19:37

et cum appropinquaret jam ad descensum montis Oliveti, cœperunt omnes turbæ discipulorum gaudentes laudare Deum voce magna super omnibus, quas viderant, virtutibus,

** Luke 19:38

dicentes : Benedictus, qui venit rex in nomine Domini : pax in cælo, et gloria in excelsis.

** Luke 19:39

Et quidam pharisæorum de turbis dixerunt ad illum : Magister, increpa discipulos tuos.

** Luke 19:40

Quibus ipse ait : Dico vobis, quia si hi tacuerint, lapides clamabunt.  

** Luke 19:41

Et ut appropinquavit, videns civitatem flevit super illam, dicens :

** Luke 19:42

Quia si cognovisses et tu, et quidem in hac die tua, quæ ad pacem tibi : nunc autem abscondita sunt ab oculis tuis.

** Luke 19:43

Quia venient dies in te : et circumdabunt te inimici tui vallo, et circumdabunt te : et coangustabunt te undique :

** Luke 19:44

et ad terram prosternent te, et filios tuos, qui in te sunt, et non relinquent in te lapidem super lapidem : eo quod non cognoveris tempus visitationis tuæ.

** Luke 19:45

Et ingressus in templum, cœpit ejicere vendentes in illo, et ementes,

** Luke 19:46

dicens illis : Scriptum est : Quia domus mea domus orationis est : vos autem fecistis illam speluncam latronum.

** Luke 19:47

Et erat docens quotidie in templo. Principes autem sacerdotum, et scribæ, et princeps plebis quærebant illum perdere :

** Luke 19:48

et non inveniebant quid facerent illi. Omnis enim populus suspensus erat, audiens illum.   

* Luke 20

** Luke 20:1

Et factum est in una dierum, docente illo populum in templo, et evangelizante, convenerunt principes sacerdotum, et scribæ cum senioribus,

** Luke 20:2

et aiunt dicentes ad illum : Dic nobis in qua potestate hæc facis ? aut quis est qui dedit tibi hanc potestatem ?

** Luke 20:3

Respondens autem Jesus, dixit ad illos : Interrogabo vos et ego unum verbum. Respondete mihi :

** Luke 20:4

baptismus Joannis de cælo erat, an ex hominibus ?

** Luke 20:5

At illi cogitabant intra se, dicentes : Quia si dixerimus : De cælo, dicet : Quare ergo non credidistis illi ?

** Luke 20:6

Si autem dixerimus : Ex hominibus, plebs universa lapidabit nos : certi sunt enim Joannem prophetam esse.

** Luke 20:7

Et responderunt se nescire unde esset.

** Luke 20:8

Et Jesus ait illis : Neque ego dico vobis in qua potestate hæc facio.  

** Luke 20:9

Cœpit autem dicere ad plebem parabolam hanc : Homo plantavit vineam, et locavit eam colonis : et ipse peregre fuit multis temporibus.

** Luke 20:10

Et in tempore misit ad cultores servum, ut de fructu vineæ darent illi. Qui cæsum dimiserunt eum inanem.

** Luke 20:11

Et addidit alterum servum mittere. Illi autem hunc quoque cædentes, et afficientes contumelia, dimiserunt inanem.

** Luke 20:12

Et addidit tertium mittere : qui et illum vulnerantes ejecerunt.

** Luke 20:13

Dixit autem dominus vineæ : Quid faciam ? Mittam filium meum dilectum : forsitan, cum hunc viderint, verebuntur.

** Luke 20:14

Quem cum vidissent coloni, cogitaverunt intra se, dicentes : Hic est hæres, occidamus illum, ut nostra fiat hæreditas.

** Luke 20:15

Et ejectum illum extra vineam, occiderunt. Quid ergo faciet illis dominus vineæ ?

** Luke 20:16

veniet, et perdet colonos istos, et dabit vineam aliis. Quo audito, dixerunt illi : Absit.

** Luke 20:17

Ille autem aspiciens eos, ait : Quid est ergo hoc quod scriptum est : Lapidem quem reprobaverunt ædificantes, hic factus est in caput anguli ?

** Luke 20:18

Omnis qui ceciderit super illum lapidem, conquassabitur : super quem autem ceciderit, comminuet illum.  

** Luke 20:19

Et quærebant principes sacerdotum et scribæ mittere in illum manus illa hora, et timuerunt populum : cognoverunt enim quod ad ipsos dixerit similitudinem hanc.

** Luke 20:20

Et observantes miserunt insidiatores, qui se justos simularent, ut caperent eum in sermone, ut traderent illum principatui, et potestati præsidis.

** Luke 20:21

Et interrogaverunt eum, dicentes : Magister, scimus quia recte dicis et doces : et non accipis personam, sed viam Dei in veritate doces.

** Luke 20:22

Licet nobis tributum dare Cæsari, an non ?

** Luke 20:23

Considerans autem dolum illorum, dixit ad eos : Quid me tentatis ?

** Luke 20:24

ostendite mihi denarium. Cujus habet imaginem et inscriptionem ? Respondentes dixerunt ei : Cæsaris.

** Luke 20:25

Et ait illis : Reddite ergo quæ sunt Cæsaris, Cæsari : et quæ sunt Dei, Deo.

** Luke 20:26

Et non potuerunt verbum ejus reprehendere coram plebe : et mirati in responso ejus, tacuerunt.  

** Luke 20:27

Accesserunt autem quidam sadducæorum, qui negant esse resurrectionem, et interrogaverunt eum,

** Luke 20:28

dicentes : Magister, Moyses scripsit nobis : Si frater alicujus mortuus fuerit habens uxorem, et hic sine liberis fuerit, ut accipiat eam frater ejus uxorem, et suscitet semen fratri suo.

** Luke 20:29

Septem ergo fratres erant : et primus accepit uxorem, et mortuus est sine filiis.

** Luke 20:30

Et sequens accepit illam, et ipse mortuus est sine filio.

** Luke 20:31

Et tertius accepit illam. Similiter et omnes septem, et non reliquerunt semen, et mortui sunt.

** Luke 20:32

Novissime omnium mortua est et mulier.

** Luke 20:33

In resurrectione ergo, cujus eorum erit uxor ? siquidem septem habuerunt eam uxorem.

** Luke 20:34

Et ait illis Jesus : Filii hujus sæculi nubunt, et traduntur ad nuptias :

** Luke 20:35

illi vero qui digni habebuntur sæculo illo, et resurrectione ex mortuis, neque nubent, neque ducent uxores :

** Luke 20:36

neque enim ultra mori potuerunt : æquales enim angelis sunt, et filii sunt Dei, cum sint filii resurrectionis.

** Luke 20:37

Quia vero resurgant mortui, et Moyses ostendit secus rubum, sicut dicit Dominum, Deum Abraham, et Deum Isaac, et Deum Jacob.

** Luke 20:38

Deus autem non est mortuorum, sed vivorum : omnes enim vivunt ei.

** Luke 20:39

Respondentes autem quidam scribarum, dixerunt ei : Magister, bene dixisti.

** Luke 20:40

Et amplius non audebant eum quidquam interrogare.  

** Luke 20:41

Dixit autem ad illos : Quomodo dicunt Christum filium esse David ?

** Luke 20:42

et ipse David dicit in libro Psalmorum : Dixit Dominus Domino meo : sede a dextris meis,

** Luke 20:43

donec ponam inimicos tuos scabellum pedum tuorum.

** Luke 20:44

David ergo Dominum illum vocat : et quomodo filius ejus est ?

** Luke 20:45

Audiente autem omni populo, dixit discipulis suis :

** Luke 20:46

Attendite a scribis, qui volunt ambulare in stolis, et amant salutationes in foro, et primas cathedras in synagogis, et primos discubitus in conviviis,

** Luke 20:47

qui devorant domos viduarum, simulantes longam orationem : hi accipient damnationem majorem.   

* Luke 21

** Luke 21:1

Respiciens autem, vidit eos qui mittebant munera sua in gazophylacium, divites.

** Luke 21:2

Vidit autem et quamdam viduam pauperculam mittentem æra minuta duo.

** Luke 21:3

Et dixit : Vere dico vobis, quia vidua hæc pauper plus quam omnes misit.

** Luke 21:4

Nam omnes hi ex abundanti sibi miserunt in munera Dei : hæc autem ex eo quod deest illi, omnem victum suum quem habuit, misit.  

** Luke 21:5

Et quibusdam dicentibus de templo quod bonis lapidibus et donis ornatum esset, dixit :

** Luke 21:6

Hæc quæ videtis, venient dies in quibus non relinquetur lapis super lapidem, qui non destruatur.

** Luke 21:7

Interrogaverunt autem illum, dicentes : Præceptor, quando hæc erunt, et quod signum cum fieri incipient ?

** Luke 21:8

Qui dixit : Videte ne seducamini : multi enim venient in nomine meo, dicentes quia ego sum : et tempus appropinquavit : nolite ergo ire post eos.

** Luke 21:9

Cum autem audieritis prælia et seditiones, nolite terreri : oportet primum hæc fieri, sed nondum statim finis.

** Luke 21:10

Tunc dicebat illis : Surget gens contra gentem, et regnum adversus regnum.

** Luke 21:11

Et terræmotus magni erunt per loca, et pestilentiæ, et fames, terroresque de cælo, et signa magna erunt.  

** Luke 21:12

Sed ante hæc omnia injicient vobis manus suas, et persequentur tradentes in synagogas et custodias, trahentes ad reges et præsides propter nomen meum :

** Luke 21:13

continget autem vobis in testimonium.

** Luke 21:14

Ponite ergo in cordibus vestris non præmeditari quemadmodum respondeatis :

** Luke 21:15

ego enim dabo vobis os et sapientiam, cui non poterunt resistere et contradicere omnes adversarii vestri.

** Luke 21:16

Trademini autem a parentibus, et fratribus, et cognatis, et amicis, et morte afficient ex vobis :

** Luke 21:17

et eritis odio omnibus propter nomen meum :

** Luke 21:18

et capillus de capite vestro non peribit.

** Luke 21:19

In patientia vestra possidebitis animas vestras.  

** Luke 21:20

Cum autem videritis circumdari ab exercitu Jerusalem, tunc scitote quia appropinquavit desolatio ejus :

** Luke 21:21

tunc qui in Judæa sunt, fugiant ad montes, et qui in medio ejus, discedant : et qui in regionibus, non intrent in eam,

** Luke 21:22

quia dies ultionis hi sunt, ut impleantur omnia quæ scripta sunt.

** Luke 21:23

Væ autem prægnantibus et nutrientibus in illis diebus ! erit enim pressura magna super terram, et ira populo huic.

** Luke 21:24

Et cadent in ore gladii, et captivi ducentur in omnes gentes, et Jerusalem calcabitur a gentibus, donec impleantur tempora nationum.  

** Luke 21:25

Et erunt signa in sole, et luna, et stellis, et in terris pressura gentium præ confusione sonitus maris, et fluctuum :

** Luke 21:26

arescentibus hominibus præ timore, et exspectatione, quæ supervenient universo orbi : nam virtutes cælorum movebuntur :

** Luke 21:27

et tunc videbunt Filium hominis venientem in nube cum potestate magna et majestate.  

** Luke 21:28

His autem fieri incipientibus, respicite, et levate capita vestra : quoniam appropinquat redemptio vestra.

** Luke 21:29

Et dixit illis similitudinem : Videte ficulneam, et omnes arbores :

** Luke 21:30

cum producunt jam ex se fructum, scitis quoniam prope est æstas.

** Luke 21:31

Ita et vos cum videritis hæc fieri, scitote quoniam prope est regnum Dei.

** Luke 21:32

Amen dico vobis, quia non præteribit generatio hæc, donec omnia fiant.

** Luke 21:33

Cælum et terra transibunt : verba autem mea non transibunt.  

** Luke 21:34

Attendite autem vobis, ne forte graventur corda vestra in crapula, et ebrietate, et curis hujus vitæ, et superveniat in vos repentina dies illa :

** Luke 21:35

tamquam laqueus enim superveniet in omnes qui sedent super faciem omnis terræ.

** Luke 21:36

Vigilate itaque, omni tempore orantes, ut digni habeamini fugere ista omnia quæ futura sunt, et stare ante Filium hominis.  

** Luke 21:37

Erat autem diebus docens in templo : noctibus vero exiens, morabatur in monte qui vocatur Oliveti.

** Luke 21:38

Et omnis populus manicabat ad eum in templo audire eum.   

* Luke 22

** Luke 22:1

Appropinquabat autem dies festus azymorum, qui dicitur Pascha :

** Luke 22:2

et quærebant principes sacerdotum, et scribæ, quomodo Jesum interficerent : timebant vero plebem.

** Luke 22:3

Intravit autem Satanas in Judam, qui cognominabatur Iscariotes, unum de duodecim :

** Luke 22:4

et abiit, et locutus est cum principibus sacerdotum, et magistratibus, quemadmodum illum traderet eis.

** Luke 22:5

Et gavisi sunt, et pacti sunt pecuniam illi dare.

** Luke 22:6

Et spopondit, et quærebat opportunitatem ut traderet illum sine turbis.  

** Luke 22:7

Venit autem dies azymorum, in qua necesse erat occidi pascha.

** Luke 22:8

Et misit Petrum et Joannem, dicens : Euntes parate nobis pascha, ut manducemus.

** Luke 22:9

At illi dixerunt : Ubi vis paremus ?

** Luke 22:10

Et dixit ad eos : Ecce introëuntibus vobis in civitatem occurret vobis homo quidam amphoram aquæ portans : sequimini eum in domum, in quam intrat,

** Luke 22:11

et dicetis patrifamilias domus : Dicit tibi Magister : Ubi est diversorium, ubi pascha cum discipulis meis manducem ?

** Luke 22:12

Et ipse ostendet vobis cœnaculum magnum stratum, et ibi parate.

** Luke 22:13

Euntes autem invenerunt sicut dixit illis, et paraverunt pascha.

** Luke 22:14

Et cum facta esset hora, discubuit, et duodecim apostoli cum eo.

** Luke 22:15

Et ait illis : Desiderio desideravi hoc pascha manducare vobiscum, antequam patiar.

** Luke 22:16

Dico enim vobis, quia ex hoc non manducabo illud, donec impleatur in regno Dei.

** Luke 22:17

Et accepto calice gratias egit, et dixit : Accipite, et dividite inter vos.

** Luke 22:18

Dico enim vobis quod non bibam de generatione vitis donec regnum Dei veniat.  

** Luke 22:19

Et accepto pane gratias egit, et fregit, et dedit eis, dicens : Hoc est corpus meum, quod pro vobis datur : hoc facite in meam commemorationem.

** Luke 22:20

Similiter et calicem, postquam cœnavit, dicens : Hic est calix novum testamentum in sanguine meo, qui pro vobis fundetur.

** Luke 22:21

Verumtamen ecce manus tradentis me, mecum est in mensa.

** Luke 22:22

Et quidem Filius hominis, secundum quod definitum est, vadit : verumtamen væ homini illi per quem tradetur.

** Luke 22:23

Et ipsi cœperunt quærere inter se quis esset ex eis qui hoc facturus esset.  

** Luke 22:24

Facta est autem et contentio inter eos, quis eorum videretur esse major.

** Luke 22:25

Dixit autem eis : Reges gentium dominantur eorum : et qui potestatem habent super eos, benefici vocantur.

** Luke 22:26

Vos autem non sic : sed qui major est in vobis, fiat sicut minor : et qui præcessor est, sicut ministrator.

** Luke 22:27

Nam quis major est, qui recumbit, an qui ministrat ? nonne qui recumbit ? Ego autem in medio vestrum sum, sicut qui ministrat :

** Luke 22:28

vos autem estis, qui permansistis mecum in tentationibus meis.

** Luke 22:29

Et ego dispono vobis sicut disposuit mihi Pater meus regnum,

** Luke 22:30

ut edatis et bibatis super mensam meam in regno meo, et sedeatis super thronos judicantes duodecim tribus Israël.  

** Luke 22:31

Ait autem Dominus : Simon, Simon, ecce Satanas expetivit vos ut cribraret sicut triticum :

** Luke 22:32

ego autem rogavi pro te ut non deficiat fides tua : et tu aliquando conversus, confirma fratres tuos.

** Luke 22:33

Qui dixit ei : Domine, tecum paratus sum et in carcerem et in mortem ire.

** Luke 22:34

At ille dixit : Dico tibi, Petre, non cantabit hodie gallus, donec ter abneges nosse me. Et dixit eis :

** Luke 22:35

Quando misi vos sine sacculo, et pera, et calceamentis, numquid aliquid defuit vobis ?

** Luke 22:36

At illi dixerunt : Nihil. Dixit ergo eis : Sed nunc qui habet sacculum, tollat ; similiter et peram : et qui non habet, vendat tunicam suam et emat gladium.

** Luke 22:37

Dico enim vobis, quoniam adhuc hoc quod scriptum est, oportet impleri in me : Et cum iniquis deputatus est. Etenim ea quæ sunt de me finem habent.

** Luke 22:38

At illi dixerunt : Domine, ecce duo gladii hic. At ille dixit eis : Satis est.  

** Luke 22:39

Et egressus ibat secundum consuetudinem in monte Olivarum. Secuti sunt autem illum et discipuli.

** Luke 22:40

Et cum pervenisset ad locum, dixit illis : Orate ne intretis in tentationem.

** Luke 22:41

Et ipse avulsus est ab eis quantum jactus est lapidis : et positis genibus orabat,

** Luke 22:42

dicens : Pater, si vis, transfer calicem istum a me : verumtamen non mea voluntas, sed tua fiat.

** Luke 22:43

Apparuit autem illi angelus de cælo, confortans eum. Et factus in agonia, prolixius orabat.

** Luke 22:44

Et factus est sudor ejus sicut guttæ sanguinis decurrentis in terram.

** Luke 22:45

Et cum surrexisset ab oratione et venisset ad discipulos suos, invenit eos dormientes præ tristitia.

** Luke 22:46

Et ait illis : Quid dormitis ? surgite, orate, ne intretis in tentationem.  

** Luke 22:47

Adhuc eo loquente, ecce turba : et qui vocabatur Judas, unus de duodecim, antecedebat eos, et appropinquavit Jesu ut oscularetur eum.

** Luke 22:48

Jesus autem dixit illi : Juda, osculo Filium hominis tradis ?

** Luke 22:49

Videntes autem hi qui circa ipsum erant, quod futurum erat, dixerunt ei : Domine, si percutimus in gladio ?

** Luke 22:50

Et percussit unus ex illis servum principis sacerdotum, et amputavit auriculam ejus dexteram.

** Luke 22:51

Respondens autem Jesus, ait : Sinite usque huc. Et cum tetigisset auriculam ejus, sanavit eum.

** Luke 22:52

Dixit autem Jesus ad eos qui venerant ad se principes sacerdotum, et magistratus templi, et seniores : Quasi ad latronem existis cum gladiis et fustibus ?

** Luke 22:53

Cum quotidie vobiscum fuerim in templo, non extendistis manus in me : sed hæc est hora vestra, et potestas tenebrarum.

** Luke 22:54

Comprehendentes autem eum, duxerunt ad domum principis sacerdotum : Petrus vero sequebatur a longe.  

** Luke 22:55

Accenso autem igne in medio atrii et circumsedentibus illis, erat Petrus in medio eorum.

** Luke 22:56

Quem cum vidisset ancilla quædam sedentem ad lumen, et eum fuisset intuita, dixit : Et hic cum illo erat.

** Luke 22:57

At ille negavit eum, dicens : Mulier, non novi illum.

** Luke 22:58

Et post pusillum alius videns eum, dixit : Et tu de illis es. Petrus vero ait : O homo, non sum.

** Luke 22:59

Et intervallo facto quasi horæ unius, alius quidam affirmabat, dicens : Vere et hic cum illo erat : nam et Galilæus est.

** Luke 22:60

Et ait Petrus : Homo, nescio quid dicis. Et continuo, adhuc illo loquente, cantavit gallus.

** Luke 22:61

Et conversus Dominus respexit Petrum, et recordatus est Petrus verbi Domini, sicut dixerat : Quia priusquam gallus cantet, ter me negabis.

** Luke 22:62

Et egressus foras Petrus flevit amare.  

** Luke 22:63

Et viri qui tenebant illum, illudebant ei, cædentes.

** Luke 22:64

Et velaverunt eum, et percutiebant faciem ejus : et interrogabant eum, dicentes : Prophetiza, quis est, qui te percussit ?

** Luke 22:65

Et alia multa blasphemantes dicebant in eum.  

** Luke 22:66

Et ut factus est dies, convenerunt seniores plebis, et principes sacerdotum, et scribæ, et duxerunt illum in concilium suum, dicentes : Si tu es Christus, dic nobis.

** Luke 22:67

Et ait illis : Si vobis dixero, non credetis mihi :

** Luke 22:68

si autem et interrogavero, non respondebitis mihi, neque dimittetis.

** Luke 22:69

Ex hoc autem erit Filius hominis sedens a dextris virtutis Dei.

** Luke 22:70

Dixerunt autem omnes : Tu ergo es Filius Dei ? Qui ait : Vos dicitis, quia ego sum.

** Luke 22:71

At illi dixerunt : Quid adhuc desideramus testimonium ? ipsi enim audivimus de ore ejus.   

* Luke 23

** Luke 23:1

Et surgens omnis multitudo eorum, duxerunt illum ad Pilatum.

** Luke 23:2

Cœperunt autem illum accusare, dicentes : Hunc invenimus subvertentem gentem nostram, et prohibentem tributa dare Cæsari, et dicentem se Christum regem esse.

** Luke 23:3

Pilatus autem interrogavit eum, dicens : Tu es rex Judæorum ? At ille respondens ait : Tu dicis.

** Luke 23:4

Ait autem Pilatus ad principes sacerdotum et turbas : Nihil invenio causæ in hoc homine.

** Luke 23:5

At illi invalescebant, dicentes : Commovet populum docens per universam Judæam, incipiens a Galilæa usque huc.

** Luke 23:6

Pilatus autem audiens Galilæam, interrogavit si homo Galilæus esset.

** Luke 23:7

Et ut cognovit quod de Herodis potestate esset, remisit eum ad Herodem, qui et ipse Jerosolymis erat illis diebus.  

** Luke 23:8

Herodes autem viso Jesu, gavisus est valde. Erat enim cupiens ex multo tempore videre eum, eo quod audierat multa de eo, et sperabat signum aliquod videre ab eo fieri.

** Luke 23:9

Interrogabat autem eum multis sermonibus. At ipse nihil illi respondebat.

** Luke 23:10

Stabant autem principes sacerdotum et scribæ constanter accusantes eum.

** Luke 23:11

Sprevit autem illum Herodes cum exercitu suo : et illusit indutum veste alba, et remisit ad Pilatum.

** Luke 23:12

Et facti sunt amici Herodes et Pilatus in ipsa die : nam antea inimici erant ad invicem.  

** Luke 23:13

Pilatus autem, convocatis principibus sacerdotum, et magistratibus, et plebe,

** Luke 23:14

dixit ad illos : Obtulistis mihi hunc hominem, quasi avertentem populum, et ecce ego coram vobis interrogans, nullam causam inveni in homine isto ex his in quibus eum accusatis.

** Luke 23:15

Sed neque Herodes : nam remisi vos ad illum, et ecce nihil dignum morte actum est ei.

** Luke 23:16

Emendatum ergo illum dimittam.

** Luke 23:17

Necesse autem habebat dimittere eis per diem festum unum.

** Luke 23:18

Exclamavit autem simul universa turba, dicens : Tolle hunc, et dimitte nobis Barabbam :

** Luke 23:19

qui erat propter seditionem quamdam factam in civitate et homicidium missus in carcerem.

** Luke 23:20

Iterum autem Pilatus locutus est ad eos, volens dimittere Jesum.

** Luke 23:21

At illi succlamabant, dicentes : Crucifige, crucifige eum.

** Luke 23:22

Ille autem tertio dixit ad illos : Quid enim mali fecit iste ? nullam causam mortis invenio in eo : corripiam ergo illum et dimittam.

** Luke 23:23

At illi instabant vocibus magnis postulantes ut crucifigeretur : et invalescebant voces eorum.  

** Luke 23:24

Et Pilatus adjudicavit fieri petitionem eorum.

** Luke 23:25

Dimisit autem illis eum qui propter homicidium et seditionem missus fuerat in carcerem, quem petebant : Jesum vero tradidit voluntati eorum.

** Luke 23:26

Et cum ducerent eum, apprehenderunt Simonem quemdam Cyrenensem venientem de villa : et imposuerunt illi crucem portare post Jesum.

** Luke 23:27

Sequebatur autem illum multa turba populi et mulierum, quæ plangebant et lamentabantur eum.

** Luke 23:28

Conversus autem ad illas Jesus, dixit : Filiæ Jerusalem, nolite flere super me, sed super vos ipsas flete et super filios vestros.

** Luke 23:29

Quoniam ecce venient dies in quibus dicent : Beatæ steriles, et ventres qui non genuerunt, et ubera quæ non lactaverunt.

** Luke 23:30

Tunc incipient dicere montibus : Cadite super nos ; et collibus : Operite nos.

** Luke 23:31

Quia si in viridi ligno hæc faciunt, in arido quid fiet ?

** Luke 23:32

Ducebantur autem et alii duo nequam cum eo, ut interficerentur.  

** Luke 23:33

Et postquam venerunt in locum qui vocatur Calvariæ, ibi crucifixerunt eum : et latrones, unum a dextris, et alterum a sinistris.

** Luke 23:34

Jesus autem dicebat : Pater, dimitte illis : non enim sciunt quid faciunt. Dividentes vero vestimenta ejus, miserunt sortes.

** Luke 23:35

Et stabat populus spectans, et deridebant eum principes cum eis, dicentes : Alios salvos fecit, se salvum faciat, si hic est Christus Dei electus.

** Luke 23:36

Illudebant autem ei et milites accedentes, et acetum offerentes ei,

** Luke 23:37

et dicentes : Si tu es rex Judæorum, salvum te fac.

** Luke 23:38

Erat autem et superscriptio scripta super eum litteris græcis, et latinis, et hebraicis : Hic est rex Judæorum.

** Luke 23:39

Unus autem de his, qui pendebant, latronibus, blasphemabat eum, dicens : Si tu es Christus, salvum fac temetipsum et nos.

** Luke 23:40

Respondens autem alter increpabat eum, dicens : Neque tu times Deum, quod in eadem damnatione es.

** Luke 23:41

Et nos quidem juste, nam digna factis recipimus : hic vero nihil mali gessit.

** Luke 23:42

Et dicebat ad Jesum : Domine, memento mei cum veneris in regnum tuum.

** Luke 23:43

Et dixit illi Jesus : Amen dico tibi : hodie mecum eris in paradiso.  

** Luke 23:44

Erat autem fere hora sexta, et tenebræ factæ sunt in universam terram usque ad horam nonam.

** Luke 23:45

Et obscuratus est sol, et velum templi scissum est medium.

** Luke 23:46

Et clamans voce magna Jesus ait : Pater, in manus tuas commendo spiritum meum. Et hæc dicens, expiravit.

** Luke 23:47

Videns autem centurio quod factum fuerat, glorificavit Deum, dicens : Vere hic homo justus erat.

** Luke 23:48

Et omnis turba eorum, qui simul aderant ad spectaculum istud, et videbant quæ fiebant, percutientes pectora sua revertebantur.

** Luke 23:49

Stabant autem omnes noti ejus a longe, et mulieres, quæ secutæ eum erant a Galilæa, hæc videntes.  

** Luke 23:50

Et ecce vir nomine Joseph, qui erat decurio, vir bonus et justus :

** Luke 23:51

hic non consenserat consilio, et actibus eorum : ab Arimathæa civitate Judææ, qui exspectabat et ipse regnum Dei :

** Luke 23:52

hic accessit ad Pilatum et petiit corpus Jesu :

** Luke 23:53

et depositum involvit sindone, et posuit eum in monumento exciso, in quo nondum quisquam positus fuerat.

** Luke 23:54

Et dies erat parasceves, et sabbatum illucescebat.

** Luke 23:55

Subsecutæ autem mulieres, quæ cum eo venerant de Galilæa, viderunt monumentum, et quemadmodum positum erat corpus ejus.

** Luke 23:56

Et revertentes paraverunt aromata, et unguenta : et sabbato quidem siluerunt secundum mandatum.   

* Luke 24

** Luke 24:1

Una autem sabbati valde diluculo venerunt ad monumentum, portantes quæ paraverant aromata :

** Luke 24:2

et invenerunt lapidem revolutum a monumento.

** Luke 24:3

Et ingressæ non invenerunt corpus Domini Jesu.

** Luke 24:4

Et factum est, dum mente consternatæ essent de isto, ecce duo viri steterunt secus illas in veste fulgenti.

** Luke 24:5

Cum timerent autem, et declinarent vultum in terram, dixerunt ad illas : Quid quæritis viventem cum mortuis ?

** Luke 24:6

non est hic, sed surrexit : recordamini qualiter locutus est vobis, cum adhuc in Galilæa esset,

** Luke 24:7

dicens : Quia oportet Filium hominis tradi in manus hominum peccatorum, et crucifigi, et die tertia resurgere.

** Luke 24:8

Et recordatæ sunt verborum ejus.

** Luke 24:9

Et regressæ a monumento nuntiaverunt hæc omnia illis undecim, et ceteris omnibus.

** Luke 24:10

Erat autem Maria Magdalene, et Joanna, et Maria Jacobi, et ceteræ quæ cum eis erant, quæ dicebant ad apostolos hæc.

** Luke 24:11

Et visa sunt ante illos sicut deliramentum verba ista, et non crediderunt illis.

** Luke 24:12

Petrus autem surgens cucurrit ad monumentum : et procumbens vidit linteamina sola posita, et abiit secum mirans quod factum fuerat.  

** Luke 24:13

Et ecce duo ex illis ibant ipsa die in castellum, quod erat in spatio stadiorum sexaginta ab Jerusalem, nomine Emmaus.

** Luke 24:14

Et ipsi loquebantur ad invicem de his omnibus quæ acciderant.

** Luke 24:15

Et factum est, dum fabularentur, et secum quærerent : et ipse Jesus appropinquans ibat cum illis :

** Luke 24:16

oculi autem illorum tenebantur ne eum agnoscerent.

** Luke 24:17

Et ait ad illos : Qui sunt hi sermones, quos confertis ad invicem ambulantes, et estis tristes ?

** Luke 24:18

Et respondens unus, cui nomen Cleophas, dixit ei : Tu solus peregrinus es in Jerusalem, et non cognovisti quæ facta sunt in illa his diebus ?

** Luke 24:19

Quibus ille dixit : Quæ ? Et dixerunt : De Jesu Nazareno, qui fuit vir propheta, potens in opere et sermone coram Deo et omni populo :

** Luke 24:20

et quomodo eum tradiderunt summi sacerdotes et principes nostri in damnationem mortis, et crucifixerunt eum :

** Luke 24:21

nos autem sperabamus quia ipse esset redempturus Israël : et nunc super hæc omnia, tertia dies est hodie quod hæc facta sunt.

** Luke 24:22

Sed et mulieres quædam ex nostris terruerunt nos, quæ ante lucem fuerunt ad monumentum,

** Luke 24:23

et non invento corpore ejus, venerunt, dicentes se etiam visionem angelorum vidisse, qui dicunt eum vivere.

** Luke 24:24

Et abierunt quidam ex nostris ad monumentum : et ita invenerunt sicut mulieres dixerunt, ipsum vero non invenerunt.

** Luke 24:25

Et ipse dixit ad eos : O stulti, et tardi corde ad credendum in omnibus quæ locuti sunt prophetæ !

** Luke 24:26

Nonne hæc oportuit pati Christum, et ita intrare in gloriam suam ?

** Luke 24:27

Et incipiens a Moyse, et omnibus prophetis, interpretabatur illis in omnibus scripturis quæ de ipso erant.

** Luke 24:28

Et appropinquaverunt castello quo ibant : et ipse se finxit longius ire.

** Luke 24:29

Et coëgerunt illum, dicentes : Mane nobiscum, quoniam advesperascit, et inclinata est jam dies. Et intravit cum illis.

** Luke 24:30

Et factum est, dum recumberet cum eis, accepit panem, et benedixit, ac fregit, et porrigebat illis.

** Luke 24:31

Et aperti sunt oculi eorum, et cognoverunt eum : et ipse evanuit ex oculis eorum.

** Luke 24:32

Et dixerunt ad invicem : Nonne cor nostrum ardens erat in nobis dum loqueretur in via, et aperiret nobis Scripturas ?

** Luke 24:33

Et surgentes eadem hora regressi sunt in Jerusalem : et invenerunt congregatos undecim, et eos qui cum illis erant,

** Luke 24:34

dicentes : Quod surrexit Dominus vere, et apparuit Simoni.

** Luke 24:35

Et ipsi narrabant quæ gesta erant in via, et quomodo cognoverunt eum in fractione panis.  

** Luke 24:36

Dum autem hæc loquuntur, stetit Jesus in medio eorum, et dicit eis : Pax vobis : ego sum, nolite timere.

** Luke 24:37

Conturbati vero et conterriti, existimabant se spiritum videre.

** Luke 24:38

Et dixit eis : Quid turbati estis, et cogitationes ascendunt in corda vestra ?

** Luke 24:39

videte manus meas, et pedes, quia ego ipse sum ; palpate et videte, quia spiritus carnem et ossa non habet, sicut me videtis habere.

** Luke 24:40

Et cum hoc dixisset, ostendit eis manus et pedes.

** Luke 24:41

Adhuc autem illis non credentibus, et mirantibus præ gaudio, dixit : Habetis hic aliquid quod manducetur ?

** Luke 24:42

At illi obtulerunt ei partem piscis assi et favum mellis.

** Luke 24:43

Et cum manducasset coram eis, sumens reliquias dedit eis.  

** Luke 24:44

Et dixit ad eos : Hæc sunt verba quæ locutus sum ad vos cum adhuc essem vobiscum, quoniam necesse est impleri omnia quæ scripta sunt in lege Moysi, et prophetis, et Psalmis de me.

** Luke 24:45

Tunc aperuit illis sensum ut intelligerent Scripturas,

** Luke 24:46

et dixit eis : Quoniam sic scriptum est, et sic oportebat Christum pati, et resurgere a mortuis tertia die :

** Luke 24:47

et prædicari in nomine ejus pœnitentiam, et remissionem peccatorum in omnes gentes, incipientibus ab Jerosolyma.

** Luke 24:48

Vos autem testes estis horum.

** Luke 24:49

Et ego mitto promissum Patris mei in vos ; vos autem sedete in civitate, quoadusque induamini virtute ex alto.  

** Luke 24:50

Eduxit autem eos foras in Bethaniam, et elevatis manibus suis benedixit eis.

** Luke 24:51

Et factum est, dum benediceret illis, recessit ab eis, et ferebatur in cælum.

** Luke 24:52

Et ipsi adorantes regressi sunt in Jerusalem cum gaudio magno :

** Luke 24:53

et erant semper in templo, laudantes et benedicentes Deum. Amen.    

