* Mark 1

** Mark 1:1

Initium Evangelii Jesu Christi, Filii Dei.

** Mark 1:2

Sicut scriptum est in Isaia propheta :   Ecce ego mitto angelum meum ante faciem tuam,  qui præparabit viam tuam ante te. 

** Mark 1:3

Vox clamantis in deserto :  Parate viam Domini, rectas facite semitas ejus.

** Mark 1:4

Fuit Joannes in deserto baptizans, et prædicans baptismum pœnitentiæ in remissionem peccatorum.

** Mark 1:5

Et egrediebatur ad eum omnis Judææ regio, et Jerosolymitæ universi, et baptizabantur ab illo in Jordanis flumine, confitentes peccata sua.

** Mark 1:6

Et erat Joannes vestitus pilis cameli, et zona pellicea circa lumbos ejus, et locustas et mel silvestre edebat.

** Mark 1:7

Et prædicabat dicens : Venit fortior me post me, cujus non sum dignus procumbens solvere corrigiam calceamentorum ejus.

** Mark 1:8

Ego baptizavi vos aqua, ille vero baptizabit vos Spiritu Sancto.  

** Mark 1:9

Et factum est : in diebus illis venit Jesus a Nazareth Galilææ : et baptizatus est a Joanne in Jordane.

** Mark 1:10

Et statim ascendens de aqua, vidit cælos apertos, et Spiritum tamquam columbam descendentem, et manentem in ipso.

** Mark 1:11

Et vox facta est de cælis : Tu es Filius meus dilectus, in te complacui.  

** Mark 1:12

Et statim Spiritus expulit eum in desertum.

** Mark 1:13

Et erat in deserto quadraginta diebus, et quadraginta noctibus : et tentabatur a Satana : eratque cum bestiis, et angeli ministrabant illi.  

** Mark 1:14

Postquam autem traditus est Joannes, venit Jesus in Galilæam, prædicans Evangelium regni Dei,

** Mark 1:15

et dicens : Quoniam impletum est tempus, et appropinquavit regnum Dei : pœnitemini, et credite Evangelio.

** Mark 1:16

Et præteriens secus mare Galilææ, vidit Simonem, et Andream fratrem ejus, mittentes retia in mare (erant enim piscatores),

** Mark 1:17

et dixit eis Jesus : Venite post me, et faciam vos fieri piscatores hominum.

** Mark 1:18

Et protinus relictis retibus, secuti sunt eum.

** Mark 1:19

Et progressus inde pusillum, vidit Jacobum Zebedæi, et Joannem fratrem ejus, et ipsos componentes retia in navi :

** Mark 1:20

et statim vocavit illos. Et relicto patre suo Zebedæo in navi cum mercenariis, secuti sunt eum.  

** Mark 1:21

Et ingrediuntur Capharnaum : et statim sabbatis ingressus in synagogam, docebat eos.

** Mark 1:22

Et stupebant super doctrina ejus : erat enim docens eos quasi potestatem habens, et non sicut scribæ.

** Mark 1:23

Et erat in synagoga eorum homo in spiritu immundo : et exclamavit,

** Mark 1:24

dicens : Quid nobis et tibi, Jesu Nazarene ? venisti perdere nos ? scio qui sis, Sanctus Dei.

** Mark 1:25

Et comminatus est ei Jesus, dicens : Obmutesce, et exi de homine.

** Mark 1:26

Et discerpens eum spiritus immundus, et exclamans voce magna, exiit ab eo.

** Mark 1:27

Et mirati sunt omnes, ita ut conquirerent inter se dicentes : Quidnam est hoc ? quænam doctrina hæc nova ? quia in potestate etiam spiritibus immundis imperat, et obediunt ei.

** Mark 1:28

Et processit rumor ejus statim in omnem regionem Galilææ.  

** Mark 1:29

Et protinus egredientes de synagoga, venerunt in domum Simonis et Andreæ, cum Jacobo et Joanne.

** Mark 1:30

Decumbebat autem socrus Simonis febricitans : et statim dicunt ei de illa.

** Mark 1:31

Et accedens elevavit eam, apprehensa manu ejus : et continuo dimisit eam febris, et ministrabat eis.  

** Mark 1:32

Vespere autem facto cum occidisset sol, afferebant ad eum omnes male habentes, et dæmonia habentes :

** Mark 1:33

et erat omnis civitas congregata ad januam.

** Mark 1:34

Et curavit multos, qui vexabantur variis languoribus, et dæmonia multa ejiciebat, et non sinebat ea loqui, quoniam sciebant eum.  

** Mark 1:35

Et diluculo valde surgens, egressus abiit in desertum locum, ibique orabat.

** Mark 1:36

Et prosecutus est eum Simon, et qui cum illo erant.

** Mark 1:37

Et cum invenissent eum, dixerunt ei : Quia omnes quærunt te.

** Mark 1:38

Et ait illis : Eamus in proximos vicos, et civitates, ut et ibi prædicem : ad hoc enim veni.

** Mark 1:39

Et erat prædicans in synagogis eorum, et in omni Galilæa, et dæmonia ejiciens.  

** Mark 1:40

Et venit ad eum leprosus deprecans eum : et genu flexo dixit ei : Si vis, potes me mundare.

** Mark 1:41

Jesus autem misertus ejus, extendit manum suam : et tangens eum, ait illi : Volo : mundare.

** Mark 1:42

Et cum dixisset, statim discessit ab eo lepra, et mundatus est.

** Mark 1:43

Et comminatus est ei, statimque ejecit illum,

** Mark 1:44

et dicit ei : Vide nemini dixeris : sed vade, ostende te principi sacerdotum, et offer pro emundatione tua, quæ præcepit Moyses in testimonium illis.

** Mark 1:45

At ille egressus cœpit prædicare, et diffamare sermonem, ita ut jam non posset manifeste introire in civitatem, sed foris in desertis locis esset, et conveniebant ad eum undique.   

* Mark 2

** Mark 2:1

Et iterum intravit Capharnaum post dies,

** Mark 2:2

et auditum est quod in domo esset, et convenerunt multi, ita ut non caperet neque ad januam, et loquebatur eis verbum.

** Mark 2:3

Et venerunt ad eum ferentes paralyticum, qui a quatuor portabatur.

** Mark 2:4

Et cum non possent offerre eum illi præ turba, nudaverunt tectum ubi erat : et patefacientes submiserunt grabatum in quo paralyticus jacebat.

** Mark 2:5

Cum autem vidisset Jesus fidem illorum, ait paralytico : Fili, dimittuntur tibi peccata tua.

** Mark 2:6

Erant autem illic quidam de scribis sedentes, et cogitantes in cordibus suis :

** Mark 2:7

Quid hic sic loquitur ? blasphemat. Quis potest dimittere peccata, nisi solus Deus ?

** Mark 2:8

Quo statim cognito Jesus spiritu suo, quia sic cogitarent intra se, dicit illis : Quid ista cogitatis in cordibus vestris ?

** Mark 2:9

Quid est facilius dicere paralytico : Dimittuntur tibi peccata : an dicere : Surge, tolle grabatum tuum, et ambula ?

** Mark 2:10

Ut autem sciatis quia Filius hominis habet potestatem in terra dimittendi peccata (ait paralytico),

** Mark 2:11

tibi dico : Surge, tolle grabatum tuum, et vade in domum tuam.

** Mark 2:12

Et statim surrexit ille : et, sublato grabato, abiit coram omnibus, ita ut mirarentur omnes, et honorificent Deum, dicentes : Quia numquam sic vidimus.  

** Mark 2:13

Et egressus est rursus ad mare, omnisque turba veniebat ad eum, et docebat eos.

** Mark 2:14

Et cum præteriret, vidit Levi Alphæi sedentem ad telonium, et ait illi : Sequere me. Et surgens secutus est eum.

** Mark 2:15

Et factum est, cum accumberet in domo illius, multi publicani et peccatores simul discumbebant cum Jesu et discipulis ejus : erant enim multi, qui et sequebantur eum.

** Mark 2:16

Et scribæ et pharisæi videntes quia manducaret cum publicanis et peccatoribus, dicebant discipulis ejus : Quare cum publicanis et peccatoribus manducat et bibit Magister vester ?

** Mark 2:17

Hoc audito Jesus ait illis : Non necesse habent sani medico, sed qui male habent : non enim veni vocare justos, sed peccatores.

** Mark 2:18

Et erant discipuli Joannis et pharisæi jejunantes : et veniunt, et dicunt illi : Quare discipuli Joannis et pharisæorum jejunant, tui autem discipuli non jejunant ?

** Mark 2:19

Et ait illis Jesus : Numquid possunt filii nuptiarum, quamdiu sponsus cum illis est, jejunare ? Quanto tempore habent secum sponsum, non possunt jejunare.

** Mark 2:20

Venient autem dies cum auferetur ab eis sponsus : et tunc jejunabunt in illis diebus.

** Mark 2:21

Nemo assumentum panni rudis assuit vestimento veteri : alioquin aufert supplementum novum a veteri, et major scissura fit.

** Mark 2:22

Et nemo mittit vinum novum in utres veteres : alioquin dirumpet vinum utres, et vinum effundetur, et utres peribunt : sed vinum novum in utres novos mitti debet.  

** Mark 2:23

Et factum est iterum cum Dominus sabbatis ambularet per sata, et discipuli ejus cœperunt progredi, et vellere spicas.

** Mark 2:24

Pharisæi autem dicebant ei : Ecce, quid faciunt sabbatis quod non licet ?

** Mark 2:25

Et ait illis : Numquam legistis quid fecerit David, quando necessitatem habuit, et esuriit ipse, et qui cum eo erant ?

** Mark 2:26

quomodo introivit in domum Dei sub Abiathar principe sacerdotum, et panes propositionis manducavit, quos non licebat manducare, nisi sacerdotibus, et dedit eis qui cum eo erant ?

** Mark 2:27

Et dicebat eis : Sabbatum propter hominem factum est, et non homo propter sabbatum.

** Mark 2:28

Itaque Dominus est Filius hominis, etiam sabbati.   

* Mark 3

** Mark 3:1

Et introivit iterum in synagogam : et erat ibi homo habens manum aridam.

** Mark 3:2

Et observabant eum, si sabbatis curaret, ut accusarent illum.

** Mark 3:3

Et ait homini habenti manum aridam : Surge in medium.

** Mark 3:4

Et dicit eis : Licet sabbatis benefacere, an male ? animam salvam facere, an perdere ? At illi tacebant.

** Mark 3:5

Et circumspiciens eos cum ira, contristatus super cæcitate cordis eorum, dicit homini : Extende manum tuam. Et extendit, et restituta est manus illi.

** Mark 3:6

Exeuntes autem pharisæi, statim cum Herodianis consilium faciebant adversus eum quomodo eum perderent.  

** Mark 3:7

Jesus autem cum discipulis suis secessit ad mare : et multa turba a Galilæa et Judæa secuta est eum,

** Mark 3:8

et ab Jerosolymis, et ab Idumæa, et trans Jordanem : et qui circa Tyrum et Sidonem multitudo magna, audientes quæ faciebat, venerunt ad eum.

** Mark 3:9

Et dicit discipulis suis ut navicula sibi deserviret propter turbam, ne comprimerent eum :

** Mark 3:10

multos enim sanabat, ita ut irruerent in eum ut illum tangerent, quotquot habebant plagas.

** Mark 3:11

Et spiritus immundi, cum illum videbant, procidebant ei : et clamabant, dicentes :

** Mark 3:12

Tu es Filius Dei. Et vehementer comminabatur eis ne manifestarent illum.  

** Mark 3:13

Et ascendens in montem vocavit ad se quos voluit ipse : et venerunt ad eum.

** Mark 3:14

Et fecit ut essent duodecim cum illo : et ut mitteret eos prædicare.

** Mark 3:15

Et dedit illis potestatem curandi infirmitates et ejiciendi dæmonia.

** Mark 3:16

Et imposuit Simoni nomen Petrus :

** Mark 3:17

et Jacobum Zebedæi, et Joannem fratrem Jacobi, et imposuit eis nomina Boanerges, quod est, Filii tonitrui :

** Mark 3:18

et Andream, et Philippum, et Bartholomæum, et Matthæum, et Thomam, et Jacobum Alphæi, et Thaddæum, et Simonem Cananæum,

** Mark 3:19

et Judam Iscariotem, qui et tradidit illum.  

** Mark 3:20

Et veniunt ad domum : et convenit iterum turba, ita ut non possent neque panem manducare.

** Mark 3:21

Et cum audissent sui, exierunt tenere eum : dicebant enim : Quoniam in furorem versus est.

** Mark 3:22

Et scribæ, qui ab Jerosolymis descenderant, dicebant : Quoniam Beelzebub habet, et quia in principe dæmoniorum ejicit dæmonia.  

** Mark 3:23

Et convocatis eis in parabolis dicebat illis : Quomodo potest Satanas Satanam ejicere ?

** Mark 3:24

Et si regnum in se dividatur, non potest regnum illud stare.

** Mark 3:25

Et si domus super semetipsam dispertiatur, non potest domus illa stare.

** Mark 3:26

Et si Satanas consurrexerit in semetipsum, dispertitus est, et non poterit stare, sed finem habet.

** Mark 3:27

Nemo potest vasa fortis ingressus in domum diripere, nisi prius fortem alliget, et tunc domum ejus diripiet.

** Mark 3:28

Amen dico vobis, quoniam omnia dimittentur filiis hominum peccata, et blasphemiæ quibus blasphemaverint :

** Mark 3:29

qui autem blasphemaverit in Spiritum Sanctum, non habebit remissionem in æternum, sed reus erit æterni delicti.

** Mark 3:30

Quoniam dicebant : Spiritum immundum habet.  

** Mark 3:31

Et veniunt mater ejus et fratres : et foris stantes miserunt ad eum vocantes eum,

** Mark 3:32

et sedebat circa eum turba : et dicunt ei : Ecce mater tua et fratres tui foris quærunt te.

** Mark 3:33

Et respondens eis, ait : Quæ est mater mea et fratres mei ?

** Mark 3:34

Et circumspiciens eos, qui in circuitu ejus sedebant, ait : Ecce mater mea et fratres mei.

** Mark 3:35

Qui enim fecerit voluntatem Dei, hic frater meus, et soror mea, et mater est.   

* Mark 4

** Mark 4:1

Et iterum cœpit docere ad mare : et congregata est ad eum turba multa, ita ut navim ascendens sederet in mari, et omnis turba circa mare super terram erat :

** Mark 4:2

et docebat eos in parabolis multa, et dicebat illis in doctrina sua :

** Mark 4:3

Audite : ecce exiit seminans ad seminandum.

** Mark 4:4

Et dum seminat, aliud cecidit circa viam, et venerunt volucres cæli, et comederunt illud.

** Mark 4:5

Aliud vero cecidit super petrosa, ubi non habuit terram multam : et statim exortum est, quoniam non habebat altitudinem terræ :

** Mark 4:6

et quando exortus est sol, exæstuavit : et eo quod non habebat radicem, exaruit.

** Mark 4:7

Et aliud cecidit in spinas : et ascenderunt spinæ, et suffocaverunt illud, et fructum non dedit.

** Mark 4:8

Et aliud cecidit in terram bonam : et dabat fructum ascendentem et crescentem, et afferebat unum triginta, unum sexaginta, et unum centum.

** Mark 4:9

Et dicebat : Qui habet aures audiendi, audiat.

** Mark 4:10

Et cum esset singularis, interrogaverunt eum hi qui cum eo erant duodecim, parabolam.

** Mark 4:11

Et dicebat eis : Vobis datum est nosse mysterium regni Dei : illis autem, qui foris sunt, in parabolis omnia fiunt :

** Mark 4:12

ut videntes videant, et non videant : et audientes audiant, et non intelligant : nequando convertantur, et dimittantur eis peccata.  

** Mark 4:13

Et ait illis : Nescitis parabolam hanc ? Et quomodo omnes parabolas cognoscetis ?

** Mark 4:14

Qui seminat, verbum seminat.

** Mark 4:15

Hi autem sunt, qui circa viam, ubi seminatur verbum, et cum audierint, confestim venit Satanas, et aufert verbum, quod seminatum est in cordibus eorum.

** Mark 4:16

Et hi sunt similiter, qui super petrosa seminantur : qui cum audierint verbum, statim cum gaudio accipiunt illud :

** Mark 4:17

et non habent radicem in se, sed temporales sunt : deinde orta tribulatione et persecutione propter verbum, confestim scandalizantur.

** Mark 4:18

Et alii sunt qui in spinas seminantur : hi sunt qui verbum audiunt,

** Mark 4:19

et ærumnæ sæculi, et deceptio divitiarum, et circa reliqua concupiscentiæ introëuntes suffocant verbum, et sine fructu efficitur.

** Mark 4:20

Et hi sunt qui super terram bonam seminati sunt, qui audiunt verbum, et suscipiunt, et fructificant, unum triginta, unum sexaginta, et unum centum.  

** Mark 4:21

Et dicebat illis : Numquid venit lucerna ut sub modio ponatur, aut sub lecto ? nonne ut super candelabrum ponatur ?

** Mark 4:22

Non est enim aliquid absconditum, quod non manifestetur : nec factum est occultum, sed ut in palam veniat.

** Mark 4:23

Si quis habet aures audiendi, audiat.

** Mark 4:24

Et dicebat illis : Videte quid audiatis. In qua mensura mensi fueritis, remetietur vobis, et adjicietur vobis.

** Mark 4:25

Qui enim habet, dabitur illi : et qui non habet, etiam quod habet auferetur ab eo.  

** Mark 4:26

Et dicebat : Sic est regnum Dei, quemadmodum si homo jaciat sementem in terram,

** Mark 4:27

et dormiat, et exsurgat nocte et die, et semen germinet, et increscat dum nescit ille.

** Mark 4:28

Ultro enim terra fructificat, primum herbam, deinde spicam, deinde plenum frumentum in spica.

** Mark 4:29

Et cum produxerit fructus, statim mittit falcem, quoniam adest messis.

** Mark 4:30

Et dicebat : Cui assimilabimus regnum Dei ? aut cui parabolæ comparabimus illud ?

** Mark 4:31

Sicut granum sinapis, quod cum seminatum fuerit in terra, minus est omnibus seminibus, quæ sunt in terra :

** Mark 4:32

et cum seminatum fuerit, ascendit, et fit majus omnibus oleribus, et facit ramos magnos, ita ut possint sub umbra ejus aves cæli habitare.

** Mark 4:33

Et talibus multis parabolis loquebatur eis verbum, prout poterant audire :

** Mark 4:34

sine parabola autem non loquebatur eis : seorsum autem discipulis suis disserebat omnia.  

** Mark 4:35

Et ait illis in illa die, cum sero esset factum : Transeamus contra.

** Mark 4:36

Et dimittentes turbam, assumunt eum ita ut erat in navi : et aliæ naves erant cum illo.

** Mark 4:37

Et facta est procella magna venti, et fluctus mittebat in navim, ita ut impleretur navis.

** Mark 4:38

Et erat ipse in puppi super cervical dormiens : et excitant eum, et dicunt illi : Magister, non ad te pertinet, quia perimus ?

** Mark 4:39

Et exsurgens comminatus est vento, et dixit mari : Tace, obmutesce. Et cessavit ventus : et facta est tranquillitas magna.

** Mark 4:40

Et ait illis : Quid timidi estis ? necdum habetis fidem ? et timuerunt timore magno, et dicebant ad alterutrum : Quis, putas, est iste, quia et ventus et mare obediunt ei ?   

* Mark 5

** Mark 5:1

Et venerunt trans fretum maris in regionem Gerasenorum.

** Mark 5:2

Et exeunti ei de navi, statim occurrit de monumentis homo in spiritu immundo,

** Mark 5:3

qui domicilium habebat in monumentis, et neque catenis jam quisquam poterat eum ligare :

** Mark 5:4

quoniam sæpe compedibus et catenis vinctus, dirupisset catenas, et compedes comminuisset, et nemo poterat eum domare :

** Mark 5:5

et semper die ac nocte in monumentis, et in montibus erat, clamans, et concidens se lapidibus.

** Mark 5:6

Videns autem Jesum a longe, cucurrit, et adoravit eum :

** Mark 5:7

et clamans voce magna dixit : Quid mihi et tibi, Jesu Fili Dei altissimi ? adjuro te per Deum, ne me torqueas.

** Mark 5:8

Dicebat enim illi : Exi spiritus immunde ab homine.

** Mark 5:9

Et interrogabat eum : Quod tibi nomen est ? Et dicit ei : Legio mihi nomen est, quia multi sumus.

** Mark 5:10

Et deprecabatur eum multum, ne se expelleret extra regionem.

** Mark 5:11

Erat autem ibi circa montem grex porcorum magnus, pascens.

** Mark 5:12

Et deprecabantur eum spiritus, dicentes : Mitte nos in porcos ut in eos introëamus.

** Mark 5:13

Et concessit eis statim Jesus. Et exeuntes spiritus immundi introierunt in porcos : et magno impetu grex præcipitatus est in mare ad duo millia, et suffocati sunt in mari.

** Mark 5:14

Qui autem pascebant eos, fugerunt, et nuntiaverunt in civitatem et in agros. Et egressi sunt videre quid esset factum :

** Mark 5:15

et veniunt ad Jesum : et vident illum qui a dæmonio vexabatur, sedentem, vestitum, et sanæ mentis, et timuerunt.

** Mark 5:16

Et narraverunt illis, qui viderant, qualiter factum esset ei qui dæmonium habuerat, et de porcis.

** Mark 5:17

Et rogare cœperunt eum ut discederet de finibus eorum.

** Mark 5:18

Cumque ascenderet navim, cœpit illum deprecari, qui a dæmonio vexatus fuerat, ut esset cum illo,

** Mark 5:19

et non admisit eum, sed ait illi : Vade in domum tuam ad tuos, et annuntia illis quanta tibi Dominus fecerit, et misertus sit tui.

** Mark 5:20

Et abiit, et cœpit prædicare in Decapoli, quanta sibi fecisset Jesus : et omnes mirabantur.

** Mark 5:21

Et cum transcendisset Jesus in navi rursum trans fretum, convenit turba multa ad eum, et erat circa mare.  

** Mark 5:22

Et venit quidam de archisynagogis nomine Jairus, et videns eum procidit ad pedes ejus,

** Mark 5:23

et deprecabatur eum multum, dicens : Quoniam filia mea in extremis est, veni, impone manum super eam, ut salva sit, et vivat.

** Mark 5:24

Et abiit cum illo, et sequebatur eum turba multa, et comprimebant eum.

** Mark 5:25

Et mulier, quæ erat in profluvio sanguinis annis duodecim,

** Mark 5:26

et fuerat multa perpessa a compluribus medicis : et erogaverat omnia sua, nec quidquam profecerat, sed magis deterius habebat :

** Mark 5:27

cum audisset de Jesu, venit in turba retro, et tetigit vestimentum ejus :

** Mark 5:28

dicebat enim : Quia si vel vestimentum ejus tetigero, salva ero.

** Mark 5:29

Et confestim siccatus est fons sanguinis ejus : et sensit corpore quia sanata esset a plaga.

** Mark 5:30

Et statim Jesus in semetipso cognoscens virtutem quæ exierat de illo, conversus ad turbam, aiebat : Quis tetigit vestimenta mea ?

** Mark 5:31

Et dicebant ei discipuli sui : Vides turbam comprimentem te, et dicis : Quis me tetigit ?

** Mark 5:32

Et circumspiciebat videre eam, quæ hoc fecerat.

** Mark 5:33

Mulier vero timens et tremens, sciens quod factum esset in se, venit et procidit ante eum, et dixit ei omnem veritatem.

** Mark 5:34

Ille autem dixit ei : Filia, fides tua te salvam fecit : vade in pace, et esto sana a plaga tua.

** Mark 5:35

Adhuc eo loquente, veniunt ab archisynagogo, dicentes : Quia filia tua mortua est : quid ultra vexas magistrum ?

** Mark 5:36

Jesus autem audito verbo quod dicebatur, ait archisynagogo : Noli timere : tantummodo crede.

** Mark 5:37

Et non admisit quemquam se sequi nisi Petrum, et Jacobum, et Joannem fratrem Jacobi.

** Mark 5:38

Et veniunt in domum archisynagogi, et videt tumultum, et flentes, et ejulantes multum.

** Mark 5:39

Et ingressus, ait illis : Quid turbamini, et ploratis ? puella non est mortua, sed dormit.

** Mark 5:40

Et irridebant eum. Ipse vero ejectis omnibus assumit patrem, et matrem puellæ, et qui secum erant, et ingreditur ubi puella erat jacens.

** Mark 5:41

Et tenens manum puellæ, ait illi : Talitha cumi, quod est interpretatum : Puella (tibi dico), surge.

** Mark 5:42

Et confestim surrexit puella, et ambulabat : erat autem annorum duodecim : et obstupuerunt stupore magno.

** Mark 5:43

Et præcepit illis vehementer ut nemo id sciret : et dixit dari illi manducare.   

* Mark 6

** Mark 6:1

Et egressus inde, abiit in patriam suam : et sequebantur eum discipuli sui :

** Mark 6:2

et facto sabbato cœpit in synagoga docere : et multi audientes admirabantur in doctrina ejus, dicentes : Unde huic hæc omnia ? et quæ est sapientia, quæ data est illi, et virtutes tales, quæ per manus ejus efficiuntur ?

** Mark 6:3

Nonne hic est faber, filius Mariæ, frater Jacobi, et Joseph, et Judæ, et Simonis ? nonne et sorores ejus hic nobiscum sunt ? Et scandalizabantur in illo.

** Mark 6:4

Et dicebat illis Jesus : Quia non est propheta sine honore nisi in patria sua, et in domo sua, et in cognatione sua.

** Mark 6:5

Et non poterat ibi virtutem ullam facere, nisi paucos infirmos impositis manibus curavit :

** Mark 6:6

et mirabatur propter incredulitatem eorum, et circuibat castella in circuitu docens.  

** Mark 6:7

Et vocavit duodecim : et cœpit eos mittere binos, et dabat illis potestatem spirituum immundorum.

** Mark 6:8

Et præcepit eis ne quid tollerent in via, nisi virgam tantum : non peram, non panem, neque in zona æs,

** Mark 6:9

sed calceatos sandaliis, et ne induerentur duabus tunicis.

** Mark 6:10

Et dicebat eis : Quocumque introieritis in domum, illic manete donec exeatis inde :

** Mark 6:11

et quicumque non receperint vos, nec audierint vos, exeuntes inde, excutite pulverem de pedibus vestris in testimonium illis.

** Mark 6:12

Et exeuntes prædicabant ut pœnitentiam agerent :

** Mark 6:13

et dæmonia multa ejiciebant, et ungebant oleo multos ægros, et sanabant.  

** Mark 6:14

Et audivit rex Herodes (manifestum enim factum est nomen ejus), et dicebat : Quia Joannes Baptista resurrexit a mortuis : et propterea virtutes operantur in illo.

** Mark 6:15

Alii autem dicebant : Quia Elias est ; alii vero dicebant : Quia propheta est, quasi unus ex prophetis.

** Mark 6:16

Quo audito Herodes ait : Quem ego decollavi Joannem, hic a mortuis resurrexit.

** Mark 6:17

Ipse enim Herodes misit, ac tenuit Joannem, et vinxit eum in carcere propter Herodiadem uxorem Philippi fratris sui, quia duxerat eam.

** Mark 6:18

Dicebat enim Joannes Herodi : Non licet tibi habere uxorem fratris tui.

** Mark 6:19

Herodias autem insidiabatur illi : et volebat occidere eum, nec poterat.

** Mark 6:20

Herodes enim metuebat Joannem, sciens eum virum justum et sanctum : et custodiebat eum, et audito eo multa faciebat, et libenter eum audiebat.

** Mark 6:21

Et cum dies opportunus accidisset, Herodes natalis sui cœnam fecit principibus, et tribunis, et primis Galilææ :

** Mark 6:22

cumque introisset filia ipsius Herodiadis, et saltasset, et placuisset Herodi, simulque recumbentibus, rex ait puellæ : Pete a me quod vis, et dabo tibi :

** Mark 6:23

et juravit illi : Quia quidquid petieris dabo tibi, licet dimidium regni mei.

** Mark 6:24

Quæ cum exisset, dixit matri suæ : Quid petam ? At illa dixit : Caput Joannis Baptistæ.

** Mark 6:25

Cumque introisset statim cum festinatione ad regem, petivit dicens : Volo ut protinus des mihi in disco caput Joannis Baptistæ.

** Mark 6:26

Et contristatus est rex : propter jusjurandum, et propter simul discumbentes, noluit eam contristare :

** Mark 6:27

sed misso spiculatore præcepit afferri caput ejus in disco. Et decollavit eum in carcere,

** Mark 6:28

et attulit caput ejus in disco : et dedit illud puellæ, et puella dedit matri suæ.

** Mark 6:29

Quo audito, discipuli ejus venerunt, et tulerunt corpus ejus : et posuerunt illud in monumento.  

** Mark 6:30

Et convenientes Apostoli ad Jesum, renuntiaverunt ei omnia quæ egerant, et docuerant.

** Mark 6:31

Et ait illis : Venite seorsum in desertum locum, et requiescite pusillum. Erant enim qui veniebant et redibant multi : et nec spatium manducandi habebant.

** Mark 6:32

Et ascendentes in navim, abierunt in desertum locum seorsum.

** Mark 6:33

Et viderunt eos abeuntes, et cognoverunt multi : et pedestres de omnibus civitatibus concurrerunt illuc, et prævenerunt eos.

** Mark 6:34

Et exiens vidit turbam multam Jesus : et misertus est super eos, quia erant sicut oves non habentes pastorem, et cœpit docere multa.

** Mark 6:35

Et cum jam hora multa fieret, accesserunt discipuli ejus, dicentes : Desertus est locus hic, et jam hora præteriit :

** Mark 6:36

dimitte illos, ut euntes in proximas villas et vicos, emant sibi cibos, quos manducent.

** Mark 6:37

Et respondens ait illis : Date illis vos manducare. Et dixerunt ei : Euntes emamus ducentis denariis panes, et dabimus illis manducare.

** Mark 6:38

Et dicit eis : Quot panes habetis ? ite, et videte. Et cum cognovissent, dicunt : Quinque, et duos pisces.

** Mark 6:39

Et præcepit illis ut accumbere facerent omnes secundum contubernia super viride fœnum.

** Mark 6:40

Et discubuerunt in partes per centenos et quinquagenos.

** Mark 6:41

Et acceptis quinque panibus et duobus piscibus, intuens in cælum, benedixit, et fregit panes, et dedit discipulis suis, ut ponerent ante eos : et duos pisces divisit omnibus.

** Mark 6:42

Et manducaverunt omnes, et saturati sunt.

** Mark 6:43

Et sustulerunt reliquias, fragmentorum duodecim cophinos plenos, et de piscibus.

** Mark 6:44

Erant autem qui manducaverunt quinque millia virorum.  

** Mark 6:45

Et statim coëgit discipulos suos ascendere navim, ut præcederent eum trans fretum ad Bethsaidam, dum ipse dimitteret populum.

** Mark 6:46

Et cum dimisisset eos, abiit in montem orare.

** Mark 6:47

Et cum sero esset, erat navis in medio mari et ipse solus in terra.

** Mark 6:48

Et videns eos laborantes in remigando (erat enim ventus contrarius eis) et circa quartam vigiliam noctis venit ad eos ambulans supra mare : et volebat præterire eos.

** Mark 6:49

At illi ut viderunt eum ambulantem supra mare, putaverunt phantasma esse, et exclamaverunt.

** Mark 6:50

Omnes enim viderunt eum, et conturbati sunt. Et statim locutus est cum eis, et dixit eis : Confidite, ego sum : nolite timere.

** Mark 6:51

Et ascendit ad illos in navim, et cessavit ventus. Et plus magis intra se stupebant :

** Mark 6:52

non enim intellexerunt de panibus : erat enim cor eorum obcæcatum.

** Mark 6:53

Et cum transfretassent, venerunt in terram Genesareth, et applicuerunt.

** Mark 6:54

Cumque egressi essent de navi, continuo cognoverunt eum :

** Mark 6:55

et percurrentes universam regionem illam, cœperunt in grabatis eos, qui se male habebant, circumferre, ubi audiebant eum esse.

** Mark 6:56

Et quocumque introibat, in vicos, vel in villas aut civitates, in plateis ponebant infirmos, et deprecabantur eum, ut vel fimbriam vestimenti ejus tangerent, et quotquot tangebant eum, salvi fiebant.   

* Mark 7

** Mark 7:1

Et conveniunt ad eum pharisæi, et quidam de scribis, venientes ab Jerosolymis.

** Mark 7:2

Et cum vidissent quosdam ex discipulis ejus communibus manibus, id est non lotis, manducare panes, vituperaverunt.

** Mark 7:3

Pharisæi enim, et omnes Judæi, nisi crebro laverint manus, non manducant, tenentes traditionem seniorum :

** Mark 7:4

et a foro nisi baptizentur, non comedunt : et alia multa sunt, quæ tradita sunt illis servare, baptismata calicum, et urceorum, et æramentorum, et lectorum :

** Mark 7:5

et interrogabant eum pharisæi et scribæ : Quare discipuli tui non ambulant juxta traditionem seniorum, sed communibus manibus manducant panem ?

** Mark 7:6

At ille respondens, dixit eis : Bene prophetavit Isaias de vobis hypocritis, sicut scriptum est :   Populus hic labiis me honorat,  cor autem eorum longe est a me : 

** Mark 7:7

in vanum autem me colunt,  docentes doctrinas, et præcepta hominum.

** Mark 7:8

Relinquentes enim mandatum Dei, tenetis traditionem hominum, baptismata urceorum et calicum : et alia similia his facitis multa.

** Mark 7:9

Et dicebat illis : Bene irritum facitis præceptum Dei, ut traditionem vestram servetis.

** Mark 7:10

Moyses enim dixit : Honora patrem tuum, et matrem tuam. Et : Qui maledixerit patri, vel matri, morte moriatur.

** Mark 7:11

Vos autem dicitis : Si dixerit homo patri, aut matri, Corban (quod est donum) quodcumque ex me, tibi profuerit :

** Mark 7:12

et ultra non dimittitis eum quidquam facere patri suo, aut matri,

** Mark 7:13

rescindentes verbum Dei per traditionem vestram, quam tradidistis : et similia hujusmodi multa facitis.  

** Mark 7:14

Et advocans iterum turbam, dicebat illis : Audite me omnes, et intelligite.

** Mark 7:15

Nihil est extra hominem introiens in eum, quod possit eum coinquinare, sed quæ de homine procedunt illa sunt quæ communicant hominem.

** Mark 7:16

Si quis habet aures audiendi, audiat.

** Mark 7:17

Et cum introisset in domum a turba, interrogabant eum discipuli ejus parabolam.

** Mark 7:18

Et ait illis : Sic et vos imprudentes estis ? Non intelligitis quia omne extrinsecus introiens in hominem, non potest eum communicare :

** Mark 7:19

quia non intrat in cor ejus, sed in ventrum vadit, et in secessum exit, purgans omnes escas ?

** Mark 7:20

Dicebat autem, quoniam quæ de homine exeunt, illa communicant hominem.

** Mark 7:21

Ab intus enim de corde hominum malæ cogitationes procedunt, adulteria, fornicationes, homicidia,

** Mark 7:22

furta, avaritiæ, nequitiæ, dolus, impudicitiæ, oculus malus, blasphemia, superbia, stultitia.

** Mark 7:23

Omnia hæc mala ab intus procedunt, et communicant hominem.  

** Mark 7:24

Et inde surgens abiit in fines Tyri et Sidonis : et ingressus domum, neminem voluit scire, et non potuit latere.

** Mark 7:25

Mulier enim statim ut audivit de eo, cujus filia habebat spiritum immundum, intravit, et procidit ad pedes ejus.

** Mark 7:26

Erat enim mulier gentilis, Syrophœnissa genere. Et rogabat eum ut dæmonium ejiceret de filia ejus.

** Mark 7:27

Qui dixit illi : Sine prius saturari filios : non est enim bonum sumere panem filiorum, et mittere canibus.

** Mark 7:28

At illa respondit, et dixit illi : Utique Domine, nam et catelli comedunt sub mensa de micis puerorum.

** Mark 7:29

Et ait illi : Propter hunc sermonem vade : exiit dæmonium a filia tua.

** Mark 7:30

Et cum abiisset domum suam, invenit puellam jacentem supra lectum, et dæmonium exiisse.  

** Mark 7:31

Et iterum exiens de finibus Tyri, venit per Sidonem ad mare Galilææ inter medios fines Decapoleos.

** Mark 7:32

Et adducunt ei surdum, et mutum, et deprecabantur eum, ut imponat illi manum.

** Mark 7:33

Et apprehendens eum de turba seorsum, misit digitos suos in auriculas ejus : et exspuens, tetigit linguam ejus :

** Mark 7:34

et suspiciens in cælum, ingemuit, et ait illi : Ephphetha, quod est, Adaperire.

** Mark 7:35

Et statim apertæ sunt aures ejus, et solutum est vinculum linguæ ejus, et loquebatur recte.

** Mark 7:36

Et præcepit illis ne cui dicerent. Quanto autem eis præcipiebat, tanto magis plus prædicabant :

** Mark 7:37

et eo amplius admirabantur, dicentes : Bene omnia fecit : et surdos fecit audire, et mutos loqui.   

* Mark 8

** Mark 8:1

In diebus illis iterum cum turba multa esset, nec haberent quod manducarent, convocatis discipulis, ait illis :

** Mark 8:2

Misereor super turbam : quia ecce jam triduo sustinent me, nec habent quod manducent :

** Mark 8:3

et si dimisero eos jejunos in domum suam, deficient in via : quidam enim ex eis de longe venerunt.

** Mark 8:4

Et responderunt ei discipuli sui : Unde illos quis poterit saturare panibus in solitudine ?

** Mark 8:5

Et interrogavit eos : Quot panes habetis ? Qui dixerunt : Septem.

** Mark 8:6

Et præcepit turbæ discumbere super terram. Et accipiens septem panes, gratias agens fregit, et dabat discipulis suis ut apponerent, et apposuerunt turbæ.

** Mark 8:7

Et habebant pisciculos paucos : et ipsos benedixit, et jussit apponi.

** Mark 8:8

Et manducaverunt, et saturati sunt, et sustulerunt quod superaverat de fragmentis, septem sportas.

** Mark 8:9

Erant autem qui manducaverunt, quasi quatuor millia : et dimisit eos.  

** Mark 8:10

Et statim ascendens navim cum discipulis suis, venit in partes Dalmanutha.

** Mark 8:11

Et exierunt pharisæi, et cœperunt conquirere cum eo, quærentes ab illo signum de cælo, tentantes eum.

** Mark 8:12

Et ingemiscens spiritu, ait : Quid generatio ista signum quærit ? Amen dico vobis, si dabitur generationi isti signum.

** Mark 8:13

Et dimittens eos, ascendit iterum navim et abiit trans fretum.  

** Mark 8:14

Et obliti sunt panes sumere : et nisi unum panem non habebant secum in navi.

** Mark 8:15

Et præcipiebat eis, dicens : Videte, et cavete a fermento pharisæorum, et fermento Herodis.

** Mark 8:16

Et cogitabant ad alterutrum, dicentes : quia panes non habemus.

** Mark 8:17

Quo cognito, ait illis Jesus : Quid cogitatis, quia panes non habetis ? nondum cognoscetis nec intelligitis ? adhuc cæcatum habetis cor vestrum ?

** Mark 8:18

oculos habentes non videtis ? et aures habentes non auditis ? nec recordamini,

** Mark 8:19

quando quinque panes fregi in quinque millia : quot cophinos fragmentorum plenos sustulistis ? Dicunt ei : Duodecim.

** Mark 8:20

Quando et septem panes in quatuor millia : quot sportas fragmentorum tulistis ? Et dicunt ei : Septem.

** Mark 8:21

Et dicebat eis : Quomodo nondum intelligitis ?  

** Mark 8:22

Et veniunt Bethsaidam, et adducunt ei cæcum, et rogabant eum ut illum tangeret.

** Mark 8:23

Et apprehensa manu cæci, eduxit eum extra vicum : et exspuens in oculos ejus impositis manibus suis, interrogavit eum si quid videret.

** Mark 8:24

Et aspiciens, ait : Video homines velut arbores ambulantes.

** Mark 8:25

Deinde iterum imposuit manus super oculos ejus : et cœpit videre : et restitutus est ita ut clare videret omnia.

** Mark 8:26

Et misit illum in domum suam, dicens : Vade in domum tuam : et si in vicum introieris, nemini dixeris.  

** Mark 8:27

Et egressus est Jesus, et discipuli ejus in castella Cæsareæ Philippi : et in via interrogabat discipulos suos, dicens eis : Quem me dicunt esse homines ?

** Mark 8:28

Qui responderunt illi, dicentes : Joannem Baptistam, alii Eliam, alii vero quasi unum de prophetis.

** Mark 8:29

Tunc dicit illis : Vos vero quem me esse dicitis ? Respondens Petrus, ait ei : Tu es Christus.

** Mark 8:30

Et comminatus est eis, ne cui dicerent de illo.  

** Mark 8:31

Et cœpit docere eos quoniam oportet Filium hominis pati multa, et reprobari a senioribus, et a summis sacerdotibus et scribis, et occidi : et post tres dies resurgere.

** Mark 8:32

Et palam verbum loquebatur. Et apprehendens eum Petrus, cœpit increpare eum.

** Mark 8:33

Qui conversus, et videns discipulos suos, comminatus est Petro, dicens : Vade retro me Satana, quoniam non sapis quæ Dei sunt, sed quæ sunt hominum.  

** Mark 8:34

Et convocata turba cum discipulis suis, dixit eis : Si quis vult me sequi, deneget semetipsum : et tollat crucem suam, et sequatur me.

** Mark 8:35

Qui enim voluerit animam suam salvam facere, perdet eam : qui autem perdiderit animam suam propter me, et Evangelium, salvam faciet eam.

** Mark 8:36

Quid enim proderit homini, si lucretur mundum totum et detrimentum animæ suæ faciat ?

** Mark 8:37

Aut quid dabit homo commutationis pro anima sua ?

** Mark 8:38

Qui enim me confusus fuerit, et verba mea in generatione ista adultera et peccatrice, et Filius hominis confundetur eum, cum venerit in gloria Patris sui cum angelis sanctis.

** Mark 8:39

Et dicebat illis : Amen dico vobis, quia sunt quidam de hic stantibus, qui non gustabunt mortem donec videant regnum Dei veniens in virtute.   

* Mark 9

** Mark 9:1

Et post dies sex assumit Jesus Petrum, et Jacobum, et Joannem, et ducit illos in montem excelsum seorsum solos, et transfiguratus est coram ipsis.

** Mark 9:2

Et vestimenta ejus facta sunt splendentia, et candida nimis velut nix, qualia fullo non potest super terram candida facere.

** Mark 9:3

Et apparuit illis Elias cum Moyse : et erant loquentes cum Jesu.

** Mark 9:4

Et respondens Petrus, ait Jesu : Rabbi, bonum est nos hic esse : et faciamus tria tabernacula, tibi unum, et Moysi unum, et Eliæ unum.

** Mark 9:5

Non enim sciebat quid diceret : erant enim timore exterriti.

** Mark 9:6

Et facta est nubes obumbrans eos : et venit vox de nube, dicens : Hic est Filius meus carissimus : audite illum.

** Mark 9:7

Et statim circumspicientes, neminem amplius viderunt, nisi Jesum tantum secum.

** Mark 9:8

Et descendentibus illis de monte, præcepit illis ne cuiquam quæ vidissent, narrarent : nisi cum Filius hominis a mortuis resurrexerit.

** Mark 9:9

Et verbum continuerunt apud se : conquirentes quid esset, cum a mortuis resurrexerit.

** Mark 9:10

Et interrogabant eum, dicentes : Quid ergo dicunt pharisæi et scribæ, quia Eliam oportet venire primum ?

** Mark 9:11

Qui respondens, ait illis : Elias cum venerit primo, restituet omnia : et quomodo scriptum est in Filium hominis, ut multa patiatur et contemnatur.

** Mark 9:12

Sed dico vobis quia et Elias venit (et fecerunt illi quæcumque voluerunt) sicut scriptum est de eo.  

** Mark 9:13

Et veniens ad discipulos suos, vidit turbam magnam circa eos, et scribas conquirentes cum illis.

** Mark 9:14

Et confestim omnis populus videns Jesum, stupefactus est, et expaverunt, et accurrentes salutabant eum.

** Mark 9:15

Et interrogavit eos : Quid inter vos conquiritis ?

** Mark 9:16

Et respondens unus de turba, dixit : Magister, attuli filium meum ad te habentem spiritum mutum :

** Mark 9:17

qui ubicumque eum apprehenderit, allidit illum, et spumat, et stridet dentibus, et arescit : et dixi discipulis tuis ut ejicerent illum, et non potuerunt.

** Mark 9:18

Qui respondens eis, dixit : O generatio incredula, quamdiu apud vos ero ? quamdiu vos patiar ? afferte illum ad me.

** Mark 9:19

Et attulerunt eum. Et cum vidisset eum, statim spiritus conturbavit illum : et elisus in terram, volutabatur spumans.

** Mark 9:20

Et interrogavit patrem ejus : Quantum temporis est ex quo ei hoc accidit ? At ille ait : Ab infantia :

** Mark 9:21

et frequenter eum in ignem, et in aquas misit ut eum perderet : sed si quid potes, adjuva nos, misertus nostri.

** Mark 9:22

Jesus autem ait illi : Si potes credere, omnia possibilia sunt credenti.

** Mark 9:23

Et continuo exclamans pater pueri, cum lacrimis aiebat : Credo, Domine ; adjuva incredulitatem meam.

** Mark 9:24

Et cum videret Jesus concurrentem turbam, comminatus est spiritui immundo, dicens illi : Surde et mute spiritus, ego præcipio tibi, exi ab eo : et amplius ne introëas in eum.

** Mark 9:25

Et exclamans, et multum discerpens eum, exiit ab eo, et factus est sicut mortuus, ita ut multi dicerent : Quia mortuus est.

** Mark 9:26

Jesus autem tenens manum ejus elevavit eum, et surrexit.

** Mark 9:27

Et cum introisset in domum, discipuli ejus secreto interrogabant eum : Quare nos non potuimus ejicere eum ?

** Mark 9:28

Et dixit illis : Hoc genus in nullo potest exire, nisi in oratione et jejunio.

** Mark 9:29

Et inde profecti prætergrediebantur Galilæam : nec volebat quemquam scire.  

** Mark 9:30

Docebat autem discipulos suos, et dicebat illis : Quoniam Filius hominis tradetur in manus hominum, et occident eum, et occisus tertia die resurget.

** Mark 9:31

At illi ignorabant verbum : et timebant interrogare eum.  

** Mark 9:32

Et venerunt Capharnaum. Qui cum domi essent, interrogabat eos : Quid in via tractabatis ?

** Mark 9:33

At illi tacebant : siquidem in via inter se disputaverunt : quis eorum major esset.

** Mark 9:34

Et residens vocavit duodecim, et ait illis : Si quis vult primus esse, erit omnium novissimus, et omnium minister.

** Mark 9:35

Et accipiens puerum, statuit eum in medio eorum : quem cum complexus esset, ait illis :

** Mark 9:36

Quisquis unum ex hujusmodi pueris receperit in nomine meo, me recipit : et quicumque me susceperit, non me suscipit, sed eum qui misit me.  

** Mark 9:37

Respondit illi Joannes, dicens : Magister, vidimus quemdam in nomine tuo ejicientem dæmonia, qui non sequitur nos, et prohibuimus eum.

** Mark 9:38

Jesus autem ait : Nolite prohibere eum : nemo est enim qui faciat virtutem in nomine meo, et possit cito male loqui de me :

** Mark 9:39

qui enim non est adversum vos, pro vobis est.

** Mark 9:40

Quisquis enim potum dederit vobis calicem aquæ in nomine meo, quia Christi estis : amen dico vobis, non perdet mercedem suam.  

** Mark 9:41

Et quisquis scandalizaverit unum ex his pusillis credentibus in me : bonum est ei magis si circumdaretur mola asinaria collo ejus, et in mare mitteretur.

** Mark 9:42

Et si scandalizaverit te manus tua, abscide illam : bonum est tibi debilem introire in vitam, quam duas manus habentem ire in gehennam, in ignem inextinguibilem,

** Mark 9:43

ubi vermis eorum non moritur, et ignis non extinguitur.

** Mark 9:44

Et si pes tuus te scandalizat, amputa illum : bonum est tibi claudum introire in vitam æternam, quam duos pedes habentem mitti in gehennam ignis inextinguibilis,

** Mark 9:45

ubi vermis eorum non moritur, et ignis non extinguitur.

** Mark 9:46

Quod si oculus tuus scandalizat te, ejice eum : bonum est tibi luscum introire in regnum Dei, quam duos oculos habentem mitti in gehennam ignis,

** Mark 9:47

ubi vermis eorum non moritur, et ignis non extinguitur.

** Mark 9:48

Omnis enim igne salietur, et omnis victima sale salietur.

** Mark 9:49

Bonum est sal : quod si sal insulsum fuerit, in quo illud condietis ? Habete in vobis sal, et pacem habete inter vos.   

* Mark 10

** Mark 10:1

Et inde exsurgens venit in fines Judææ ultra Jordanem : et conveniunt iterum turbæ ad eum : et sicut consueverat, iterum docebat illos.

** Mark 10:2

Et accedentes pharisæi interrogabant eum : Si licet viro uxorem dimittere : tentantes eum.

** Mark 10:3

At ille respondens, dixit eis : Quid vobis præcepit Moyses ?

** Mark 10:4

Qui dixerunt : Moyses permisit libellum repudii scribere, et dimittere.

** Mark 10:5

Quibus respondens Jesus, ait : Ad duritiam cordis vestri scripsit vobis præceptum istud :

** Mark 10:6

ab initio autem creaturæ masculum et feminam fecit eos Deus.

** Mark 10:7

Propter hoc relinquet homo patrem suum et matrem, et adhærebit ad uxorem suam :

** Mark 10:8

et erunt duo in carne una. Itaque jam non sunt duo, sed una caro.

** Mark 10:9

Quod ergo Deus conjunxit, homo non separet.

** Mark 10:10

Et in domo iterum discipuli ejus de eodem interrogaverunt eum.

** Mark 10:11

Et ait illis : Quicumque dimiserit uxorem suam, et aliam duxerit, adulterium committit super eam.

** Mark 10:12

Et si uxor dimiserit virum suum, et alii nupserit, mœchatur.  

** Mark 10:13

Et offerebant illi parvulos ut tangeret illos. Discipuli autem comminabantur offerentibus.

** Mark 10:14

Quos cum videret Jesus, indigne tulit, et ait illis : Sinite parvulos venire ad me, et ne prohibueritis eos : talium enim est regnum Dei.

** Mark 10:15

Amen dico vobis : Quisquis non receperit regnum Dei velut parvulus, non intrabit in illud.

** Mark 10:16

Et complexans eos, et imponens manus super illos, benedicebat eos.  

** Mark 10:17

Et cum egressus esset in viam, procurrens quidam genu flexo ante eum, rogabat eum : Magister bone, quid faciam ut vitam æternam percipiam ?

** Mark 10:18

Jesus autem dixit ei : Quid me dicis bonum ? nemo bonus, nisi unus Deus.

** Mark 10:19

Præcepta nosti : ne adulteres, ne occidas, ne fureris, ne falsum testimonium dixeris, ne fraudem feceris, honora patrem tuum et matrem.

** Mark 10:20

At ille respondens, ait illi : Magister, hæc omnia observavi a juventute mea.

** Mark 10:21

Jesus autem intuitus eum, dilexit eum, et dixit ei : Unum tibi deest : vade, quæcumque habes vende, et da pauperibus, et habebis thesaurum in cælo : et veni, sequere me.

** Mark 10:22

Qui contristatus in verbo, abiit mœrens : erat enim habens multas possessiones.

** Mark 10:23

Et circumspiciens Jesus, ait discipulis suis : Quam difficile qui pecunias habent, in regnum Dei introibunt !

** Mark 10:24

Discipuli autem obstupescebant in verbis ejus. At Jesus rursus respondens ait illis : Filioli, quam difficile est, confidentes in pecuniis, in regnum Dei introire !

** Mark 10:25

Facilius est camelum per foramen acus transire, quam divitem intrare in regnum Dei.

** Mark 10:26

Qui magis admirabantur, dicentes ad semetipsos : Et quis potest salvus fieri ?

** Mark 10:27

Et intuens illos Jesus, ait : Apud homines impossibile est, sed non apud Deum : omnia enim possibilia sunt apud Deum.  

** Mark 10:28

Et cœpit ei Petrus dicere : Ecce nos dimisimus omnia, et secuti sumus te.

** Mark 10:29

Respondens Jesus, ait : Amen dico vobis : Nemo est qui reliquerit domum, aut fratres, aut sorores, aut patrem, aut matrem, aut filios, aut agros propter me et propter Evangelium,

** Mark 10:30

qui non accipiat centies tantum, nunc in tempore hoc : domos, et fratres, et sorores, et matres, et filios, et agros, cum persecutionibus, et in sæculo futuro vitam æternam.

** Mark 10:31

Multi autem erunt primi novissimi, et novissimi primi.  

** Mark 10:32

Erant autem in via ascendentes Jerosolymam : et præcedebat illos Jesus, et stupebant : et sequentes timebant. Et assumens iterum duodecim, cœpit illis dicere quæ essent ei eventura.

** Mark 10:33

Quia ecce ascendimus Jerosolymam, et Filius hominis tradetur principibus sacerdotum, et scribis, et senioribus, et damnabunt eum morte, et tradent eum gentibus :

** Mark 10:34

et illudent ei, et conspuent eum, et flagellabunt eum, et interficient eum : et tertia die resurget.  

** Mark 10:35

Et accedunt ad eum Jacobus et Joannes filii Zebedæi, dicentes : Magister, volumus ut quodcumque petierimus, facias nobis.

** Mark 10:36

At ille dixit eis : Quid vultis ut faciam vobis ?

** Mark 10:37

Et dixerunt : Da nobis ut unus ad dexteram tuam, et alius ad sinistram tuam sedeamus in gloria tua.

** Mark 10:38

Jesus autem ait eis : Nescitis quid petatis : potestis bibere calicem, quem ego bibo, aut baptismo, quo ego baptizor, baptizari ?

** Mark 10:39

At illi dixerunt ei : Possumus. Jesus autem ait eis : Calicem quidem, quem ego bibo, bibetis ; et baptismo, quo ego baptizor, baptizabimini :

** Mark 10:40

sedere autem ad dexteram meam, vel ad sinistram, non est meum dare vobis, sed quibus paratum est.

** Mark 10:41

Et audientes decem, cœperunt indignari de Jacobo et Joanne.

** Mark 10:42

Jesus autem vocans eos, ait illis : Scitis quia hi, qui videntur principari gentibus, dominantur eis : et principes eorum potestatem habent ipsorum.

** Mark 10:43

Non ita est autem in vobis, sed quicumque voluerit fieri major, erit vester minister :

** Mark 10:44

et quicumque voluerit in vobis primus esse, erit omnium servus.

** Mark 10:45

Nam et Filius hominis non venit ut ministraretur ei, sed ut ministraret, et daret animam suam redemptionem pro multis.  

** Mark 10:46

Et veniunt Jericho : et proficiscente eo de Jericho, et discipulis ejus, et plurima multitudine, filius Timæi Bartimæus cæcus, sedebat juxta viam mendicans.

** Mark 10:47

Qui cum audisset quia Jesus Nazarenus est, cœpit clamare, et dicere : Jesu fili David, miserere mei.

** Mark 10:48

Et comminabantur ei multi ut taceret. At ille multo magis clamabat : Fili David, miserere mei.

** Mark 10:49

Et stans Jesus præcepit illum vocari. Et vocant cæcum, dicentes ei : Animæquior esto : surge, vocat te.

** Mark 10:50

Qui projecto vestimento suo exiliens, venit ad eum.

** Mark 10:51

Et respondens Jesus dixit illi : Quid tibi vis faciam ? Cæcus autem dixit ei : Rabboni, ut videam.

** Mark 10:52

Jesus autem ait illi : Vade, fides tua te salvum fecit. Et confestim vidit, et sequebatur eum in via.   

* Mark 11

** Mark 11:1

Et cum appropinquarent Jerosolymæ et Bethaniæ ad montem Olivarum, mittit duos ex discipulis suis,

** Mark 11:2

et ait illis : Ite in castellum, quod contra vos est, et statim introëuntes illuc, invenietis pullum ligatum, super quem nemo adhuc hominum sedit : solvite illum, et adducite.

** Mark 11:3

Et si quis vobis dixerit : Quid facitis ? dicite, quia Domino necessarius est : et continuo illum dimittet huc.

** Mark 11:4

Et abeuntes invenerunt pullum ligatum ante januam foris in bivio : et solvunt eum.

** Mark 11:5

Et quidam de illic stantibus dicebant illis : Quid facitis solventes pullum ?

** Mark 11:6

Qui dixerunt eis sicut præceperat illis Jesus, et dimiserunt eis.

** Mark 11:7

Et duxerunt pullum ad Jesum : et imponunt illi vestimenta sua, et sedit super eum.

** Mark 11:8

Multi autem vestimenta sua straverunt in via : alii autem frondes cædebant de arboribus, et sternebant in via.

** Mark 11:9

Et qui præibant, et qui sequebantur, clamabant, dicentes : Hosanna : benedictus qui venit in nomine Domini :

** Mark 11:10

benedictum quod venit regnum patris nostri David : hosanna in excelsis.

** Mark 11:11

Et introivit Jerosolymam in templum : et circumspectis omnibus, cum jam vespera esset hora, exiit in Bethaniam cum duodecim.  

** Mark 11:12

Et alia die cum exirent a Bethania, esuriit.

** Mark 11:13

Cumque vidisset a longe ficum habentem folia, venit si quid forte inveniret in ea : et cum venisset ad eam, nihil invenit præter folia : non enim erat tempus ficorum.

** Mark 11:14

Et respondens dixit ei : Jam non amplius in æternum ex te fructum quisquam manducet. Et audiebant discipuli ejus.  

** Mark 11:15

Et veniunt in Jerosolymam. Et cum introisset in templum, cœpit ejicere vendentes et ementes in templo : et mensas numulariorum, et cathedras vendentium columbas evertit :

** Mark 11:16

et non sinebat ut quisquam transferret vas per templum :

** Mark 11:17

et docebat, dicens eis : Nonne scriptum est : Quia domus mea, domus orationis vocabitur omnibus gentibus ? vos autem fecistis eam speluncam latronum.

** Mark 11:18

Quo audito principes sacerdotum et scribæ, quærebant quomodo eum perderent : timebant enim eum, quoniam universa turba admirabatur super doctrina ejus.

** Mark 11:19

Et cum vespera facta esset, egrediebatur de civitate.  

** Mark 11:20

Et cum mane transirent, viderunt ficum aridam factam a radicibus.

** Mark 11:21

Et recordatus Petrus, dixit ei : Rabbi, ecce ficus, cui maledixisti, aruit.

** Mark 11:22

Et respondens Jesus ait illis : Habete fidem Dei.

** Mark 11:23

Amen dico vobis, quia quicumque dixerit huic monti : Tollere, et mittere in mare, et non hæsitaverit in corde suo, sed crediderit, quia quodcumque dixerit fiat, fiet ei.

** Mark 11:24

Propterea dico vobis, omnia quæcumque orantes petitis, credite quia accipietis, et evenient vobis.

** Mark 11:25

Et cum stabitis ad orandum, dimittite si quid habetis adversus aliquem : ut et Pater vester, qui in cælis est, dimittat vobis peccata vestra.

** Mark 11:26

Quod si vos non dimiseritis : nec Pater vester, qui in cælis est, dimittet vobis peccata vestra.  

** Mark 11:27

Et veniunt rursus Jerosolymam. Et cum ambularet in templo, accedunt ad eum summi sacerdotes, et scribæ, et seniores :

** Mark 11:28

et dicunt ei : In qua potestate hæc facis ? et quis dedit tibi hanc potestatem ut ista facias ?

** Mark 11:29

Jesus autem respondens, ait illis : Interrogabo vos et ego unum verbum, et respondete mihi : et dicam vobis in qua potestate hæc faciam.

** Mark 11:30

Baptismus Joannis, de cælo erat, an ex hominibus ? Respondete mihi.

** Mark 11:31

At illi cogitabant secum, dicentes : Si dixerimus : De cælo, dicet : Quare ergo non credidistis ei ?

** Mark 11:32

Si dixerimus : Ex hominibus, timemus populum : omnes enim habebant Joannem quia vere propheta esset.

** Mark 11:33

Et respondentes dicunt Jesu : Nescimus. Et respondens Jesus ait illis : Neque ego dico vobis in qua potestate hæc faciam.   

* Mark 12

** Mark 12:1

Et cœpit illis in parabolis loqui : Vineam pastinavit homo, et circumdedit sepem, et fodit lacum, et ædificavit turrim, et locavit eam agricolis, et peregre profectus est.

** Mark 12:2

Et misit ad agricolas in tempore servum ut ab agricolis acciperet de fructu vineæ.

** Mark 12:3

Qui apprehensum eum ceciderunt, et dimiserunt vacuum.

** Mark 12:4

Et iterum misit ad illos alium servum : et illum in capite vulneraverunt, et contumeliis affecerunt.

** Mark 12:5

Et rursum alium misit, et illum occiderunt : et plures alios : quosdam cædentes, alios vero occidentes.

** Mark 12:6

Adhuc ergo unum habens filium carissimum, et illum misit ad eos novissimum, dicens : Quia reverebuntur filium meum.

** Mark 12:7

Coloni autem dixerunt ad invicem : Hic est hæres : venite, occidamus eum : et nostra erit hæreditas.

** Mark 12:8

Et apprehendentes eum, occiderunt : et ejecerunt extra vineam.

** Mark 12:9

Quid ergo faciet dominus vineæ ? Veniet, et perdet colonos, et dabit vineam aliis.

** Mark 12:10

Nec scripturam hanc legistis : Lapidem quem reprobaverunt ædificantes, hic factus est in caput anguli :

** Mark 12:11

a Domino factum est istud, et est mirabile in oculis nostris ?

** Mark 12:12

Et quærebant eum tenere : et timuerunt turbam : cognoverunt enim quoniam ad eos parabolam hanc dixerit. Et relicto eo abierunt.  

** Mark 12:13

Et mittunt ad eum quosdam ex pharisæis, et herodianis, ut eum caperent in verbo.

** Mark 12:14

Qui venientes dicunt ei : Magister, scimus quia verax es, et non curas quemquam : nec enim vides in faciem hominum, sed in veritate viam Dei doces. Licet dari tributum Cæsari, an non dabimus ?

** Mark 12:15

Qui sciens versutiam illorum, ait illis : Quid me tentatis ? afferte mihi denarium ut videam.

** Mark 12:16

At illi attulerunt ei. Et ait illis : Cujus est imago hæc, et inscriptio ? Dicunt ei : Cæsaris.

** Mark 12:17

Respondens autem Jesus dixit illis : Reddite igitur quæ sunt Cæsaris, Cæsari : et quæ sunt Dei, Deo. Et mirabantur super eo.  

** Mark 12:18

Et venerunt ad eum sadducæi, qui dicunt resurrectionem non esse : et interrogabant eum, dicentes :

** Mark 12:19

Magister, Moyses nobis scripsit, ut si cujus frater mortuus fuerit, et dimiserit uxorem, et filios non reliquerit, accipiat frater ejus uxorem ipsius, et resuscitet semen fratri suo.

** Mark 12:20

Septem ergo fratres erant : et primus accepit uxorem, et mortuus est non relicto semine.

** Mark 12:21

Et secundus accepit eam, et mortuus est : et nec iste reliquit semen. Et tertius similiter.

** Mark 12:22

Et acceperunt eam similiter septem : et non reliquerunt semen. Novissima omnium defuncta est et mulier.

** Mark 12:23

In resurrectione ergo cum resurrexerint, cujus de his erit uxor ? septem enim habuerunt eam uxorem.

** Mark 12:24

Et respondens Jesus, ait illis : Nonne ideo erratis, non scientes Scripturas, neque virtutem Dei ?

** Mark 12:25

Cum enim a mortuis resurrexerint, neque nubent, neque nubentur, sed sunt sicut angeli in cælis.

** Mark 12:26

De mortuis autem quod resurgant, non legistis in libro Moysi, super rubum, quomodo dixerit illi Deus, inquiens : Ego sum Deus Abraham, et Deus Isaac, et Deus Jacob ?

** Mark 12:27

Non est Deus mortuorum, sed vivorum. Vos ergo multum erratis.  

** Mark 12:28

Et accessit unus de scribis, qui audierat illos conquirentes, et videns quoniam bene illis responderit, interrogavit eum quod esset primum omnium mandatum.

** Mark 12:29

Jesus autem respondit ei : Quia primum omnium mandatum est : Audi Israël, Dominus Deus tuus, Deus unus est :

** Mark 12:30

et diliges Dominum Deum tuum ex toto corde tuo, et ex tota anima tua, et ex tota mente tua, et ex tota virtute tua. Hoc est primum mandatum.

** Mark 12:31

Secundum autem simile est illi : Diliges proximum tuum tamquam teipsum. Majus horum aliud mandatum non est.

** Mark 12:32

Et ait illi scriba : Bene, Magister, in veritate dixisti, quia unus est Deus, et non est alius præter eum.

** Mark 12:33

Et ut diligatur ex toto corde, et ex toto intellectu, et ex tota anima, et ex tota fortitudine, et diligere proximum tamquam seipsum, majus est omnibus holocautomatibus, et sacrificiis.

** Mark 12:34

Jesus autem videns quod sapienter respondisset, dixit illi : Non es longe a regno Dei. Et nemo jam audebat eum interrogare.  

** Mark 12:35

Et respondens Jesus dicebat, docens in templo : Quomodo dicunt scribæ Christum filium esse David ?

** Mark 12:36

Ipse enim David dicit in Spiritu Sancto : Dixit Dominus Domino meo : Sede a dextris meis, donec ponam inimicos tuos scabellum pedum tuorum.

** Mark 12:37

Ipse ergo David dicit eum Dominum, et unde est filius ejus ? Et multa turba eum libenter audivit.

** Mark 12:38

Et dicebat eis in doctrina sua : Cavete a scribis, qui volunt in stolis ambulare, et salutari in foro,

** Mark 12:39

et in primis cathedris sedere in synagogis, et primos discubitus in cœnis :

** Mark 12:40

qui devorant domos viduarum sub obtentu prolixæ orationis : hi accipient prolixius judicium.  

** Mark 12:41

Et sedens Jesus contra gazophylacium, aspiciebat quomodo turba jactaret æs in gazophylacium, et multi divites jactabant multa.

** Mark 12:42

Cum venisset autem vidua una pauper, misit duo minuta, quod est quadrans,

** Mark 12:43

et convocans discipulos suos, ait illis : Amen dico vobis, quoniam vidua hæc pauper plus omnibus misit, qui miserunt in gazophylacium.

** Mark 12:44

Omnes enim ex eo, quod abundabat illis, miserunt : hæc vero de penuria sua omnia quæ habuit misit totum victum suum.   

* Mark 13

** Mark 13:1

Et cum egrederetur de templo, ait illi unus ex discipulis suis : Magister, aspice quales lapides, et quales structuræ.

** Mark 13:2

Et respondens Jesus, ait illi : Vides has omnes magnas ædificationes ? Non relinquetur lapis super lapidem, qui non destruatur.  

** Mark 13:3

Et cum sederet in monte Olivarum contra templum, interrogabant eum separatim Petrus, et Jacobus, et Joannes, et Andreas :

** Mark 13:4

Dic nobis, quando ista fient ? et quod signum erit, quando hæc omnia incipient consummari ?

** Mark 13:5

Et respondens Jesus cœpit dicere illis : Videte ne quis vos seducat :

** Mark 13:6

multi enim venient in nomine meo, dicentes quia ego sum : et multos seducent.

** Mark 13:7

Cum audieritis autem bella, et opiniones bellorum, ne timueritis : oportet enim hæc fieri : sed nondum finis.

** Mark 13:8

Exsurget enim gens contra gentem, et regnum super regnum, et erunt terræmotus per loca, et fames. Initium dolorum hæc.  

** Mark 13:9

Videte autem vosmetipsos. Tradent enim vos in consiliis, et in synagogis vapulabitis, et ante præsides et reges stabitis propter me, in testimonium illis.

** Mark 13:10

Et in omnes gentes primum oportet prædicari Evangelium.

** Mark 13:11

Et cum duxerint vos tradentes, nolite præcogitare quid loquamini : sed quod datum vobis fuerit in illa hora, id loquimini : non enim vos estis loquentes, sed Spiritus Sanctus.

** Mark 13:12

Tradet autem frater fratrem in mortem, et pater filium : et consurgent filii in parentes, et morte afficient eos.

** Mark 13:13

Et eritis odio omnibus propter nomen meum. Qui autem sustinuerit in finem, hic salvus erit.  

** Mark 13:14

Cum autem videritis abominationem desolationis stantem, ubi non debet, qui legit, intelligat : tunc qui in Judæa sunt, fugiant in montes :

** Mark 13:15

et qui super tectum, ne descendat in domum, nec introëat ut tollat quid de domo sua :

** Mark 13:16

et qui in agro erit, non revertatur retro tollere vestimentum suum.

** Mark 13:17

Væ autem prægnantibus et nutrientibus in illis diebus.  

** Mark 13:18

Orate vero ut hieme non fiant.

** Mark 13:19

Erunt enim dies illi tribulationes tales quales non fuerunt ab initio creaturæ, quam condidit Deus usque nunc, neque fient.

** Mark 13:20

Et nisi breviasset Dominus dies, non fuisset salva omnis caro : sed propter electos, quos elegit, breviavit dies.

** Mark 13:21

Et tunc si quis vobis dixerit : Ecce hic est Christus, ecce illic, ne credideritis.

** Mark 13:22

Exsurgent enim pseudochristi et pseudoprophetæ, et dabunt signa et portenta ad seducendos, si fieri potest, etiam electos.

** Mark 13:23

Vos ergo videte : ecce prædixi vobis omnia.  

** Mark 13:24

Sed in illis diebus, post tribulationem illam, sol contenebrabitur, et luna non dabit splendorem suum :

** Mark 13:25

et stellæ cæli erunt decidentes, et virtutes, quæ in cælis sunt, movebuntur.

** Mark 13:26

Et tunc videbunt Filium hominis venientem in nubibus cum virtute multa et gloria.

** Mark 13:27

Et tunc mittet angelos suos, et congregabit electos suos a quatuor ventis, a summo terræ usque ad summum cæli.  

** Mark 13:28

A ficu autem discite parabolam. Cum jam ramus ejus tener fuerit, et nata fuerint folia, cognoscitis quia in proximo sit æstas :

** Mark 13:29

sic et vos cum videritis hæc fieri, scitote quod in proximo sit, in ostiis.

** Mark 13:30

Amen dico vobis, quoniam non transibit generatio hæc, donec omnia ista fiant.

** Mark 13:31

Cælum et terra transibunt, verba autem mea non transibunt.  

** Mark 13:32

De die autem illo vel hora nemo scit, neque angeli in cælo, neque Filius, nisi Pater.

** Mark 13:33

Videte, vigilate, et orate : nescitis enim quando tempus sit.

** Mark 13:34

Sicut homo qui peregre profectus reliquit domum suam, et dedit servis suis potestatem cujusque operis, et janitori præcepit ut vigilet,

** Mark 13:35

vigilate ergo (nescitis enim quando dominus domus veniat : sero, an media nocte, an galli cantu, an mane),

** Mark 13:36

ne, cum venerit repente, inveniat vos dormientes.

** Mark 13:37

Quod autem vobis dico, omnibus dico : Vigilate.   

* Mark 14

** Mark 14:1

Erat autem Pascha et azyma post biduum : et quærebant summi sacerdotes et scribæ quomodo eum dolo tenerent, et occiderent.

** Mark 14:2

Dicebant autem : Non in die festo, ne forte tumultus fieret in populo.  

** Mark 14:3

Et cum esset Bethaniæ in domo Simonis leprosi, et recumberet, venit mulier habens alabastrum unguenti nardi spicati pretiosi : et fracto alabastro, effudit super caput ejus.

** Mark 14:4

Erant autem quidam indigne ferentes intra semetipsos, et dicentes : Ut quid perditio ista unguenti facta est ?

** Mark 14:5

poterat enim unguentum istud venundari plus quam trecentis denariis, et dari pauperibus. Et fremebant in eam.

** Mark 14:6

Jesus autem dixit : Sinite eam, quid illi molesti estis ? Bonum opus operata est in me :

** Mark 14:7

semper enim pauperes habetis vobiscum : et cum volueritis, potestis illis benefacere : me autem non semper habetis.

** Mark 14:8

Quod habuit hæc, fecit : prævenit ungere corpus meum in sepulturam.

** Mark 14:9

Amen dico vobis : Ubicumque prædicatum fuerit Evangelium istud in universo mundo, et quod fecit hæc, narrabitur in memoriam ejus.  

** Mark 14:10

Et Judas Iscariotes, unus de duodecim, abiit ad summos sacerdotes, ut proderet eum illis.

** Mark 14:11

Qui audientes gavisi sunt : et promiserunt ei pecuniam se daturos. Et quærebat quomodo illum opportune traderet.  

** Mark 14:12

Et primo die azymorum quando Pascha immolabant, dicunt ei discipuli : Quo vis eamus, et paremus tibi ut manduces Pascha ?

** Mark 14:13

Et mittit duos ex discipulis suis, et dicit eis : Ite in civitatem, et occurret vobis homo lagenam aquæ bajulans : sequimini eum,

** Mark 14:14

et quocumque introierit, dicite domino domus, quia magister dicit : Ubi est refectio mea, ubi Pascha cum discipulis meis manducem ?

** Mark 14:15

Et ipse vobis demonstrabit cœnaculum grande, stratum : et illic parate nobis.

** Mark 14:16

Et abierunt discipuli ejus, et venerunt in civitatem : et invenerunt sicut dixerat illis, et paraverunt Pascha.

** Mark 14:17

Vespere autem facto, venit cum duodecim.

** Mark 14:18

Et discumbentibus eis, et manducantibus, ait Jesus : Amen dico vobis, quia unus ex vobis tradet me, qui manducat mecum.

** Mark 14:19

At illi cœperunt contristari, et dicere ei singulatim : Numquid ego ?

** Mark 14:20

Qui ait illis : Unus ex duodecim, qui intingit mecum manum in catino.

** Mark 14:21

Et Filius quidem hominis vadit sicut scriptum est de eo : væ autem homini illi per quem Filius hominis tradetur ! bonum erat ei, si non esset natus homo ille.  

** Mark 14:22

Et manducantibus illis, accepit Jesus panem : et benedicens fregit, et dedit eis, et ait : Sumite, hoc est corpus meum.

** Mark 14:23

Et accepto calice, gratias agens dedit eis : et biberunt ex illo omnes.

** Mark 14:24

Et ait illis : Hic est sanguis meus novi testamenti, qui pro multis effundetur.

** Mark 14:25

Amen dico vobis, quia jam non bibam de hoc genimine vitis usque in diem illum, cum illud bibam novum in regno Dei.  

** Mark 14:26

Et hymno dicto exierunt in montem Olivarum.

** Mark 14:27

Et ait eis Jesus : Omnes scandalizabimini in me in nocte ista : quia scriptum est : Percutiam pastorem, et dispergentur oves.

** Mark 14:28

Sed postquam resurrexero, præcedam vos in Galilæam.

** Mark 14:29

Petrus autem ait illi : Et si omnes scandalizati fuerint in te, sed non ego.

** Mark 14:30

Et ait illi Jesus : Amen dico tibi, quia tu hodie in nocte hac, priusquam gallus vocem bis dederit, ter me es negaturus.

** Mark 14:31

At ille amplius loquebatur : Et si oportuerit me simul commori tibi, non te negabo. Similiter autem et omnes dicebant.  

** Mark 14:32

Et veniunt in prædium, cui nomen Gethsemani. Et ait discipulis suis : Sedete hic donec orem.

** Mark 14:33

Et assumit Petrum, et Jacobum, et Joannem secum : et cœpit pavere et tædere.

** Mark 14:34

Et ait illis : Tristis est anima mea usque ad mortem : sustinete hic, et vigilate.

** Mark 14:35

Et cum processisset paululum, procidit super terram, et orabat ut, si fieri posset, transiret ab eo hora.

** Mark 14:36

Et dixit : Abba pater, omnia tibi possibilia sunt : transfer calicem hunc a me : sed non quod ego volo, sed quod tu.

** Mark 14:37

Et venit, et invenit eos dormientes. Et ait Petro : Simon, dormis ? non potuisti una hora vigilare ?

** Mark 14:38

vigilate et orate, ut non intretis in tentationem. Spiritus quidem promptus est, caro vero infirma.

** Mark 14:39

Et iterum abiens oravit, eumdem sermonem dicens.

** Mark 14:40

Et reversus, denuo invenit eos dormientes (erant enim oculi eorum gravati), et ignorabant quid responderent ei.

** Mark 14:41

Et venit tertio, et ait illis : Dormite jam, et requiescite. Sufficit : venit hora : ecce Filius hominis tradetur in manus peccatorum.

** Mark 14:42

Surgite, eamus : ecce qui me tradet, prope est.  

** Mark 14:43

Et, adhuc eo loquente, venit Judas Iscariotes unus de duodecim, et cum eo turba multa cum gladiis et lignis, a summis sacerdotibus, et scribis, et senioribus.

** Mark 14:44

Dederat autem traditor ejus signum eis, dicens : Quemcumque osculatus fuero, ipse est, tenete eum, et ducite caute.

** Mark 14:45

Et cum venisset, statim accedens ad eum, ait : Ave Rabbi : et osculatus est eum.

** Mark 14:46

At illi manus injecerunt in eum, et tenuerunt eum.

** Mark 14:47

Unus autem quidam de circumstantibus educens gladium, percussit servum summi sacerdotis, et amputavit illi auriculam.

** Mark 14:48

Et respondens Jesus, ait illis : Tamquam ad latronem existis cum gladiis et lignis comprehendere me ?

** Mark 14:49

quotidie eram apud vos in templo docens, et non me tenuistis. Sed ut impleantur Scripturæ.

** Mark 14:50

Tunc discipuli ejus relinquentes eum, omnes fugerunt.

** Mark 14:51

Adolescens autem quidam sequebatur eum amictus sindone super nudo : et tenuerunt eum.

** Mark 14:52

At ille rejecta sindone, nudus profugit ab eis.  

** Mark 14:53

Et adduxerunt Jesum ad summum sacerdotem : et convenerunt omnes sacerdotes, et scribæ, et seniores.

** Mark 14:54

Petrus autem a longe secutus est eum usque intro in atrium summi sacerdotis : et sedebat cum ministris ad ignem, et calefaciebat se.

** Mark 14:55

Summi vero sacerdotes et omne concilium quærebant adversus Jesum testimonium ut eum morti traderent : nec inveniebant.

** Mark 14:56

Multi enim testimonium falsum dicebant adversus eum : et convenientia testimonia non erant.

** Mark 14:57

Et quidam surgentes, falsum testimonium ferebant adversus eum, dicentes :

** Mark 14:58

Quoniam nos audivimus eum dicentem : Ego dissolvam templum hoc manu factum, et per triduum aliud non manu factum ædificabo.

** Mark 14:59

Et non erat conveniens testimonium illorum.

** Mark 14:60

Et exsurgens summus sacerdos in medium, interrogavit Jesum, dicens : Non respondes quidquam ad ea quæ tibi objiciuntur ab his ?

** Mark 14:61

Ille autem tacebat, et nihil respondit. Rursum summus sacerdos interrogabat eum, et dixit ei : Tu es Christus Filius Dei benedicti ?

** Mark 14:62

Jesus autem dixit illi : Ego sum : et videbitis Filium hominis sedentem a dextris virtutis Dei, et venientem cum nubibus cæli.

** Mark 14:63

Summus autem sacerdos scindens vestimenta sua, ait : Quid adhuc desideramus testes ?

** Mark 14:64

Audistis blasphemiam : quid vobis videtur ? Qui omnes condemnaverunt eum esse reum mortis.

** Mark 14:65

Et cœperunt quidam conspuere eum, et velare faciem ejus, et colaphis eum cædere, et dicere ei : Prophetiza : et ministri alapis eum cædebant.  

** Mark 14:66

Et cum esset Petrus in atrio deorsum, venit una ex ancillis summi sacerdotis :

** Mark 14:67

et cum vidisset Petrum calefacientem se, aspiciens illum, ait : Et tu cum Jesu Nazareno eras.

** Mark 14:68

At ille negavit, dicens : Neque scio, neque novi quid dicas. Et exiit foras ante atrium, et gallus cantavit.

** Mark 14:69

Rursus autem cum vidisset illum ancilla, cœpit dicere circumstantibus : Quia hic ex illis est.

** Mark 14:70

At ille iterum negavit. Et post pusillum rursus qui astabant, dicebant Petro : Vere ex illis es : nam et Galilæus es.

** Mark 14:71

Ille autem cœpit anathematizare et jurare : Quia nescio hominem istum, quem dicitis.

** Mark 14:72

Et statim gallus iterum cantavit. Et recordatus est Petrus verbi quod dixerat ei Jesus : Priusquam gallus cantet bis, ter me negabis. Et cœpit flere.   

* Mark 15

** Mark 15:1

Et confestim mane consilium facientes summi sacerdotes cum senioribus, et scribis, et universo concilio, vincientes Jesum, duxerunt, et tradiderunt Pilato.

** Mark 15:2

Et interrogavit eum Pilatus : Tu es rex Judæorum ? At ille respondens, ait illi : Tu dicis.

** Mark 15:3

Et accusabant eum summi sacerdotes in multis.

** Mark 15:4

Pilatus autem rursum interrogavit eum, dicens : Non respondes quidquam ? vide in quantis te accusant.

** Mark 15:5

Jesus autem amplius nihil respondit, ita ut miraretur Pilatus.

** Mark 15:6

Per diem autem festum solebat dimittere illis unum ex vinctis, quemcumque petissent.

** Mark 15:7

Erat autem qui dicebatur Barrabas, qui cum seditiosis erat vinctus, qui in seditione fecerat homicidium.

** Mark 15:8

Et cum ascendisset turba, cœpit rogare, sicut semper faciebat illis.

** Mark 15:9

Pilatus autem respondit eis, et dixit : Vultis dimittam vobis regem Judæorum ?

** Mark 15:10

Sciebat enim quod per invidiam tradidissent eum summi sacerdotes.

** Mark 15:11

Pontifices autem concitaverunt turbam, ut magis Barabbam dimitteret eis.

** Mark 15:12

Pilatus autem iterum respondens, ait illis : Quid ergo vultis faciam regi Judæorum ?

** Mark 15:13

At illi iterum clamaverunt : Crucifige eum.

** Mark 15:14

Pilatus vero dicebat illis : Quid enim mali fecit ? At illi magis clamabant : Crucifige eum.

** Mark 15:15

Pilatus autem volens populo satisfacere, dimisit illis Barabbam, et tradidit Jesum flagellis cæsum, ut crucifigeretur.  

** Mark 15:16

Milites autem duxerunt eum in atrium prætorii, et convocant totam cohortem,

** Mark 15:17

et induunt eum purpura, et imponunt ei plectentes spineam coronam.

** Mark 15:18

Et cœperunt salutare eum : Ave rex Judæorum.

** Mark 15:19

Et percutiebant caput ejus arundine : et conspuebant eum, et ponentes genua, adorabant eum.

** Mark 15:20

Et postquam illuserunt ei, exuerunt illum purpura, et induerunt eum vestimentis suis : et educunt illum ut crucifigerent eum.  

** Mark 15:21

Et angariaverunt prætereuntem quempiam, Simonem Cyrenæum venientem de villa, patrem Alexandri et Rufi, ut tolleret crucem ejus.

** Mark 15:22

Et perducunt illum in Golgotha locum : quod est interpretatum Calvariæ locus.

** Mark 15:23

Et dabant ei bibere myrrhatum vinum : et non accepit.

** Mark 15:24

Et crucifigentes eum, diviserunt vestimenta ejus, mittentes sortem super eis, quis quid tolleret.

** Mark 15:25

Erat autem hora tertia : et crucifixerunt eum.

** Mark 15:26

Et erat titulus causæ ejus inscriptus : Rex Judæorum.

** Mark 15:27

Et cum eo crucifigunt duos latrones : unum a dextris, et alium a sinistris ejus.

** Mark 15:28

Et impleta est Scriptura, quæ dicit : Et cum iniquis reputatus est.

** Mark 15:29

Et prætereuntes blasphemabant eum, moventes capita sua, et dicentes : Vah ! qui destruis templum Dei, et in tribus diebus reædificas,

** Mark 15:30

salvum fac temetipsum descendens de cruce.

** Mark 15:31

Similiter et summi sacerdotes illudentes, ad alterutrum cum scribis dicebant : Alios salvos fecit ; seipsum non potest salvum facere.

** Mark 15:32

Christus rex Israël descendat nunc de cruce, ut videamus, et credamus. Et qui cum eo crucifixi erant, convitiabantur ei.  

** Mark 15:33

Et facta hora sexta, tenebræ factæ sunt per totam terram usque in horam nonam.

** Mark 15:34

Et hora nona exclamavit Jesus voce magna, dicens : Eloi, eloi, lamma sabacthani ? quod est interpretatum : Deus meus, Deus meus, ut quid dereliquisti me ?

** Mark 15:35

Et quidam de circumstantibus audientes, dicebant : Ecce Eliam vocat.

** Mark 15:36

Currens autem unus, et implens spongiam aceto, circumponensque calamo, potum dabat ei, dicens : Sinite, videamus si veniat Elias ad deponendum eum.

** Mark 15:37

Jesus autem emissa voce magna expiravit.  

** Mark 15:38

Et velum templi scissum est in duo, a summo usque deorsum.

** Mark 15:39

Videns autem centurio, qui ex adverso stabat, quia sic clamans expirasset, ait : Vere hic homo Filius Dei erat.  

** Mark 15:40

Erant autem et mulieres de longe aspicientes : inter quas erat Maria Magdalene, et Maria Jacobi minoris, et Joseph mater, et Salome :

** Mark 15:41

et cum esset in Galilæa, sequebantur eum, et ministrabant ei, et aliæ multæ, quæ simul cum eo ascenderant Jerosolymam.

** Mark 15:42

Et cum jam sero esset factum (quia erat parasceve, quod est ante sabbatum),

** Mark 15:43

venit Joseph ab Arimathæa nobilis decurio, qui et ipse erat exspectans regnum Dei, et audacter introivit ad Pilatum, et petiit corpus Jesu.

** Mark 15:44

Pilatus autem mirabatur si jam obiisset. Et accersito centurione, interrogavit eum si jam mortuus esset.

** Mark 15:45

Et cum cognovisset a centurione, donavit corpus Joseph.

** Mark 15:46

Joseph autem mercatus sindonem, et deponens eum involvit sindone, et posuit eum in monumento quod erat excisum de petra, et advolvit lapidem ad ostium monumenti.

** Mark 15:47

Maria autem Magdalene et Maria Joseph aspiciebant ubi poneretur.   

* Mark 16

** Mark 16:1

Et cum transisset sabbatum, Maria Magdalene, et Maria Jacobi, et Salome emerunt aromata ut venientes ungerent Jesum.

** Mark 16:2

Et valde mane una sabbatorum, veniunt ad monumentum, orto jam sole.

** Mark 16:3

Et dicebant ad invicem : Quis revolvet nobis lapidem ab ostio monumenti ?

** Mark 16:4

Et respicientes viderunt revolutum lapidem. Erat quippe magnus valde.

** Mark 16:5

Et introëuntes in monumentum viderunt juvenem sedentem in dextris, coopertum stola candida, et obstupuerunt.

** Mark 16:6

Qui dicit illis : Nolite expavescere : Jesum quæritis Nazarenum, crucifixum : surrexit, non est hic, ecce locus ubi posuerunt eum.

** Mark 16:7

Sed ite, dicite discipulis ejus, et Petro, quia præcedit vos in Galilæam : ibi eum videbitis, sicut dixit vobis.

** Mark 16:8

At illæ exeuntes, fugerunt de monumento : invaserat enim eas tremor et pavor : et nemini quidquam dixerunt : timebant enim.  

** Mark 16:9

Surgens autem mane prima sabbati, apparuit primo Mariæ Magdalene, de qua ejecerat septem dæmonia.

** Mark 16:10

Illa vadens nuntiavit his, qui cum eo fuerant, lugentibus et flentibus.

** Mark 16:11

Et illi audientes quia viveret, et visus esset ab ea, non crediderunt.  

** Mark 16:12

Post hæc autem duobus ex his ambulantibus ostensus est in alia effigie, euntibus in villam :

** Mark 16:13

et illi euntes nuntiaverunt ceteris : nec illis crediderunt.

** Mark 16:14

Novissime recumbentibus illis undecim apparuit : et exprobravit incredulitatem eorum et duritiam cordis : quia iis, qui viderant eum resurrexisse, non crediderunt.

** Mark 16:15

Et dixit eis : Euntes in mundum universum prædicate Evangelium omni creaturæ.

** Mark 16:16

Qui crediderit, et baptizatus fuerit, salvus erit : qui vero non crediderit, condemnabitur.

** Mark 16:17

Signa autem eos qui crediderint, hæc sequentur : in nomine meo dæmonia ejicient : linguis loquentur novis :

** Mark 16:18

serpentes tollent : et si mortiferum quid biberint, non eis nocebit : super ægros manus imponent, et bene habebunt.  

** Mark 16:19

Et Dominus quidem Jesus postquam locutus est eis, assumptus est in cælum, et sedet a dextris Dei.

** Mark 16:20

Illi autem profecti prædicaverunt ubique, Domino cooperante, et sermonem confirmante, sequentibus signis.    

