* Matthew 1

** Matthew 1:1

Liber generationis Jesu Christi filii David, filii Abraham.

** Matthew 1:2

Abraham genuit Isaac. Isaac autem genuit Jacob. Jacob autem genuit Judam, et fratres ejus.

** Matthew 1:3

Judas autem genuit Phares, et Zaram de Thamar. Phares autem genuit Esron. Esron autem genuit Aram.

** Matthew 1:4

Aram autem genuit Aminadab. Aminadab autem genuit Naasson. Naasson autem genuit Salmon.

** Matthew 1:5

Salmon autem genuit Booz de Rahab. Booz autem genuit Obed ex Ruth. Obed autem genuit Jesse. Jesse autem genuit David regem.

** Matthew 1:6

David autem rex genuit Salomonem ex ea quæ fuit Uriæ.

** Matthew 1:7

Salomon autem genuit Roboam. Roboam autem genuit Abiam. Abias autem genuit Asa.

** Matthew 1:8

Asa autem genuit Josophat. Josophat autem genuit Joram. Joram autem genuit Oziam.

** Matthew 1:9

Ozias autem genuit Joatham. Joatham autem genuit Achaz. Achaz autem genuit Ezechiam.

** Matthew 1:10

Ezechias autem genuit Manassen. Manasses autem genuit Amon. Amon autem genuit Josiam.

** Matthew 1:11

Josias autem genuit Jechoniam, et fratres ejus in transmigratione Babylonis.

** Matthew 1:12

Et post transmigrationem Babylonis : Jechonias genuit Salathiel. Salathiel autem genuit Zorobabel.

** Matthew 1:13

Zorobabel autem genuit Abiud. Abiud autem genuit Eliacim. Eliacim autem genuit Azor.

** Matthew 1:14

Azor autem genuit Sadoc. Sadoc autem genuit Achim. Achim autem genuit Eliud.

** Matthew 1:15

Eliud autem genuit Eleazar. Eleazar autem genuit Mathan. Mathan autem genuit Jacob.

** Matthew 1:16

Jacob autem genuit Joseph virum Mariæ, de qua natus est Jesus, qui vocatur Christus.

** Matthew 1:17

Omnes itaque generationes ab Abraham usque ad David, generationes quatuordecim : et a David usque ad transmigrationem Babylonis, generationes quatuordecim : et a transmigratione Babylonis usque ad Christum, generationes quatuordecim.  

** Matthew 1:18

Christi autem generatio sic erat : cum esset desponsata mater ejus Maria Joseph, antequam convenirent inventa est in utero habens de Spiritu Sancto.

** Matthew 1:19

Joseph autem vir ejus cum esset justus, et nollet eam traducere, voluit occulte dimittere eam.

** Matthew 1:20

Hæc autem eo cogitante, ecce angelus Domini apparuit in somnis ei, dicens : Joseph, fili David, noli timere accipere Mariam conjugem tuam : quod enim in ea natum est, de Spiritu Sancto est.

** Matthew 1:21

Pariet autem filium : et vocabis nomen ejus Jesum : ipse enim salvum faciet populum suum a peccatis eorum.

** Matthew 1:22

Hoc autem totum factum est, ut adimpleretur quod dictum est a Domino per prophetam dicentem :

** Matthew 1:23

Ecce virgo in utero habebit, et pariet filium : et vocabunt nomen ejus Emmanuel, quod est interpretatum Nobiscum Deus.

** Matthew 1:24

Exsurgens autem Joseph a somno, fecit sicut præcepit ei angelus Domini, et accepit conjugem suam.

** Matthew 1:25

Et non cognoscebat eam donec peperit filium suum primogenitum : et vocavit nomen ejus Jesum.   

* Matthew 2

** Matthew 2:1

Cum ergo natus esset Jesus in Bethlehem Juda in diebus Herodis regis, ecce magi ab oriente venerunt Jerosolymam,

** Matthew 2:2

dicentes : Ubi est qui natus est rex Judæorum ? vidimus enim stellam ejus in oriente, et venimus adorare eum.

** Matthew 2:3

Audiens autem Herodes rex, turbatus est, et omnis Jerosolyma cum illo.

** Matthew 2:4

Et congregans omnes principes sacerdotum, et scribas populi, sciscitabatur ab eis ubi Christus nasceretur.

** Matthew 2:5

At illi dixerunt : In Bethlehem Judæ : sic enim scriptum est per prophetam :  

** Matthew 2:6

Et tu Bethlehem terra Juda,  nequaquam minima es  in principibus Juda :  ex te enim exiet dux, qui regat populum meum Israël.

** Matthew 2:7

Tunc Herodes clam vocatis magis diligenter didicit ab eis tempus stellæ, quæ apparuit eis :

** Matthew 2:8

et mittens illos in Bethlehem, dixit : Ite, et interrogate diligenter de puero : et cum inveneritis, renuntiate mihi, ut et ego veniens adorem eum.

** Matthew 2:9

Qui cum audissent regem, abierunt, et ecce stella, quam viderant in oriente, antecedebat eos, usque dum veniens staret supra, ubi erat puer.

** Matthew 2:10

Videntes autem stellam gavisi sunt gaudio magno valde.

** Matthew 2:11

Et intrantes domum, invenerunt puerum cum Maria matre ejus, et procidentes adoraverunt eum : et apertis thesauris suis obtulerunt ei munera, aurum, thus, et myrrham.

** Matthew 2:12

Et responso accepto in somnis ne redirent ad Herodem, per aliam viam reversi sunt in regionem suam.  

** Matthew 2:13

Qui cum recessissent, ecce angelus Domini apparuit in somnis Joseph, dicens : Surge, et accipe puerum, et matrem ejus, et fuge in Ægyptum, et esto ibi usque dum dicam tibi. Futurum est enim ut Herodes quærat puerum ad perdendum eum.

** Matthew 2:14

Qui consurgens accepit puerum et matrem ejus nocte, et secessit in Ægyptum :

** Matthew 2:15

et erat ibi usque ad obitum Herodis : ut adimpleretur quod dictum est a Domino per prophetam dicentem : Ex Ægypto vocavi filium meum.

** Matthew 2:16

Tunc Herodes videns quoniam illusus esset a magis, iratus est valde, et mittens occidit omnes pueros, qui erant in Bethlehem, et in omnibus finibus ejus, a bimatu et infra secundum tempus, quod exquisierat a magis.

** Matthew 2:17

Tunc adimpletum est quod dictum est per Jeremiam prophetam dicentem :  

** Matthew 2:18

Vox in Rama audita est  ploratus, et ululatus multus :  Rachel plorans filios suos,  et noluit consolari, quia non sunt.  

** Matthew 2:19

Defuncto autem Herode, ecce angelus Domini apparuit in somnis Joseph in Ægypto,

** Matthew 2:20

dicens : Surge, et accipe puerum, et matrem ejus, et vade in terram Israël : defuncti sunt enim qui quærebant animam pueri.

** Matthew 2:21

Qui consurgens, accepit puerum, et matrem ejus, et venit in terram Israël.

** Matthew 2:22

Audiens autem quod Archelaus regnaret in Judæa pro Herode patre suo, timuit illo ire : et admonitus in somnis, secessit in partes Galilææ.

** Matthew 2:23

Et veniens habitavit in civitate quæ vocatur Nazareth : ut adimpleretur quod dictum est per prophetas : Quoniam Nazaræus vocabitur.   

* Matthew 3

** Matthew 3:1

In diebus autem illis venit Joannes Baptista prædicans in deserto Judææ,

** Matthew 3:2

et dicens : Pœnitentiam agite : appropinquavit enim regnum cælorum.

** Matthew 3:3

Hic est enim, qui dictus est per Isaiam prophetam dicentem :   Vox clamantis in deserto :  Parate viam Domini ;  rectas facite semitas ejus.

** Matthew 3:4

Ipse autem Joannes habebat vestimentum de pilis camelorum, et zonam pelliceam circa lumbos suos : esca autem ejus erat locustæ, et mel silvestre.

** Matthew 3:5

Tunc exibat ad eum Jerosolyma, et omnis Judæa, et omnis regio circa Jordanem ;

** Matthew 3:6

et baptizabantur ab eo in Jordane, confitentes peccata sua.

** Matthew 3:7

Videns autem multos pharisæorum, et sadducæorum, venientes ad baptismum suum, dixit eis : Progenies viperarum, quis demonstravit vobis fugere a ventura ira ?

** Matthew 3:8

Facite ergo fructum dignum pœnitentiæ.

** Matthew 3:9

Et ne velitis dicere intra vos : Patrem habemus Abraham. Dico enim vobis quoniam potens est Deus de lapidibus istis suscitare filios Abrahæ.

** Matthew 3:10

Jam enim securis ad radicem arborum posita est. Omnis ergo arbor, quæ non facit fructum bonum, excidetur, et in ignem mittetur.

** Matthew 3:11

Ego quidem baptizo vos in aqua in pœnitentiam : qui autem post me venturus est, fortior me est, cujus non sum dignus calceamenta portare : ipse vos baptizabit in Spiritu Sancto, et igni.

** Matthew 3:12

Cujus ventilabrum in manu sua : et permundabit aream suam : et congregabit triticum suum in horreum, paleas autem comburet igni inextinguibili.  

** Matthew 3:13

Tunc venit Jesus a Galilæa in Jordanem ad Joannem, ut baptizaretur ab eo.

** Matthew 3:14

Joannes autem prohibebat eum, dicens : Ego a te debeo baptizari, et tu venis ad me ?

** Matthew 3:15

Respondens autem Jesus, dixit ei : Sine modo : sic enim decet nos implere omnem justitiam. Tunc dimisit eum.

** Matthew 3:16

Baptizatus autem Jesus, confestim ascendit de aqua, et ecce aperti sunt ei cæli : et vidit Spiritum Dei descendentem sicut columbam, et venientem super se.

** Matthew 3:17

Et ecce vox de cælis dicens : Hic est Filius meus dilectus, in quo mihi complacui.   

* Matthew 4

** Matthew 4:1

Tunc Jesus ductus est in desertum a Spiritu, ut tentaretur a diabolo.

** Matthew 4:2

Et cum jejunasset quadraginta diebus, et quadraginta noctibus, postea esuriit.

** Matthew 4:3

Et accedens tentator dixit ei : Si Filius Dei es, dic ut lapides isti panes fiant.

** Matthew 4:4

Qui respondens dixit : Scriptum est : Non in solo pane vivit homo, sed in omni verbo, quod procedit de ore Dei.

** Matthew 4:5

Tunc assumpsit eum diabolus in sanctam civitatem, et statuit eum super pinnaculum templi,

** Matthew 4:6

et dixit ei : Si Filius Dei es, mitte te deorsum. Scriptum est enim : Quia angelis suis mandavit de te, et in manibus tollent te, ne forte offendas ad lapidem pedem tuum.

** Matthew 4:7

Ait illi Jesus : Rursum scriptum est : Non tentabis Dominum Deum tuum.

** Matthew 4:8

Iterum assumpsit eum diabolus in montem excelsum valde : et ostendit ei omnia regna mundi, et gloriam eorum,

** Matthew 4:9

et dixit ei : Hæc omnia tibi dabo, si cadens adoraveris me.

** Matthew 4:10

Tunc dicit ei Jesus : Vade Satana : Scriptum est enim : Dominum Deum tuum adorabis, et illi soli servies.

** Matthew 4:11

Tunc reliquit eum diabolus : et ecce angeli accesserunt, et ministrabant ei.  

** Matthew 4:12

Cum autem audisset Jesus quod Joannes traditus esset, secessit in Galilæam :

** Matthew 4:13

et, relicta civitate Nazareth, venit, et habitavit in Capharnaum maritima, in finibus Zabulon et Nephthalim :

** Matthew 4:14

ut adimpleretur quod dictum est per Isaiam prophetam :  

** Matthew 4:15

Terra Zabulon, et terra Nephthalim,  via maris trans Jordanem,  Galilæa gentium : 

** Matthew 4:16

populus, qui sedebat in tenebris,  vidit lucem magnam :  et sedentibus in regione umbræ mortis,  lux orta est eis.

** Matthew 4:17

Exinde cœpit Jesus prædicare, et dicere : Pœnitentiam agite : appropinquavit enim regnum cælorum.  

** Matthew 4:18

Ambulans autem Jesus juxta mare Galilææ, vidit duos fratres, Simonem, qui vocatur Petrus, et Andream fratrem ejus, mittentes rete in mare (erant enim piscatores),

** Matthew 4:19

et ait illis : Venite post me, et faciam vos fieri piscatores hominum.

** Matthew 4:20

At illi continuo relictis retibus secuti sunt eum.

** Matthew 4:21

Et procedens inde, vidit alios duos fratres, Jacobum Zebedæi, et Joannem fratrem ejus, in navi cum Zebedæo patre eorum, reficientes retia sua : et vocavit eos.

** Matthew 4:22

Illi autem statim relictis retibus et patre, secuti sunt eum.

** Matthew 4:23

Et circuibat Jesus totam Galilæam, docens in synagogis eorum, et prædicans Evangelium regni : et sanans omnem languorem, et omnem infirmitatem in populo.

** Matthew 4:24

Et abiit opinio ejus in totam Syriam, et obtulerunt ei omnes male habentes, variis languoribus, et tormentis comprehensos, et qui dæmonia habebant, et lunaticos, et paralyticos, et curavit eos :

** Matthew 4:25

et secutæ sunt eum turbæ multæ de Galilæa, et Decapoli, et de Jerosolymis, et de Judæa, et de trans Jordanem.   

* Matthew 5

** Matthew 5:1

Videns autem Jesus turbas, ascendit in montem, et cum sedisset, accesserunt ad eum discipuli ejus,

** Matthew 5:2

et aperiens os suum docebat eos dicens :

** Matthew 5:3

Beati pauperes spiritu : quoniam ipsorum est regnum cælorum.

** Matthew 5:4

Beati mites : quoniam ipsi possidebunt terram.

** Matthew 5:5

Beati qui lugent : quoniam ipsi consolabuntur.

** Matthew 5:6

Beati qui esuriunt et sitiunt justitiam : quoniam ipsi saturabuntur.

** Matthew 5:7

Beati misericordes : quoniam ipsi misericordiam consequentur.

** Matthew 5:8

Beati mundo corde : quoniam ipsi Deum videbunt.

** Matthew 5:9

Beati pacifici : quoniam filii Dei vocabuntur.

** Matthew 5:10

Beati qui persecutionem patiuntur propter justitiam : quoniam ipsorum est regnum cælorum.

** Matthew 5:11

Beati estis cum maledixerint vobis, et persecuti vos fuerint, et dixerint omne malum adversum vos mentientes, propter me :

** Matthew 5:12

gaudete, et exsultate, quoniam merces vestra copiosa est in cælis. Sic enim persecuti sunt prophetas, qui fuerunt ante vos.  

** Matthew 5:13

Vos estis sal terræ. Quod si sal evanuerit, in quo salietur ? ad nihilum valet ultra, nisi ut mittatur foras, et conculcetur ab hominibus.

** Matthew 5:14

Vos estis lux mundi. Non potest civitas abscondi supra montem posita,

** Matthew 5:15

neque accendunt lucernam, et ponunt eam sub modio, sed super candelabrum, ut luceat omnibus qui in domo sunt.

** Matthew 5:16

Sic luceat lux vestra coram hominibus : ut videant opera vestra bona, et glorificent Patrem vestrum, qui in cælis est.  

** Matthew 5:17

Nolite putare quoniam veni solvere legem aut prophetas : non veni solvere, sed adimplere.

** Matthew 5:18

Amen quippe dico vobis, donec transeat cælum et terra, jota unum aut unus apex non præteribit a lege, donec omnia fiant.

** Matthew 5:19

Qui ergo solverit unum de mandatis istis minimis, et docuerit sic homines, minimus vocabitur in regno cælorum : qui autem fecerit et docuerit, hic magnus vocabitur in regno cælorum.

** Matthew 5:20

Dico enim vobis, quia nisi abundaverit justitia vestra plus quam scribarum et pharisæorum, non intrabitis in regnum cælorum.  

** Matthew 5:21

Audistis quia dictum est antiquis : Non occides : qui autem occiderit, reus erit judicio.

** Matthew 5:22

Ego autem dico vobis : quia omnis qui irascitur fratri suo, reus erit judicio. Qui autem dixerit fratri suo, raca : reus erit concilio. Qui autem dixerit, fatue : reus erit gehennæ ignis.

** Matthew 5:23

Si ergo offers munus tuum ad altare, et ibi recordatus fueris quia frater tuus habet aliquid adversum te :

** Matthew 5:24

relinque ibi munus tuum ante altare, et vade prius reconciliari fratri tuo : et tunc veniens offeres munus tuum.

** Matthew 5:25

Esto consentiens adversario tuo cito dum es in via cum eo : ne forte tradat te adversarius judici, et judex tradat te ministro : et in carcerem mittaris.

** Matthew 5:26

Amen dico tibi, non exies inde, donec reddas novissimum quadrantem.  

** Matthew 5:27

Audistis quia dictum est antiquis : Non mœchaberis.

** Matthew 5:28

Ego autem dico vobis : quia omnis qui viderit mulierem ad concupiscendum eam, jam mœchatus est eam in corde suo.

** Matthew 5:29

Quod si oculus tuus dexter scandalizat te, erue eum, et projice abs te : expedit enim tibi ut pereat unum membrorum tuorum, quam totum corpus tuum mittatur in gehennam.

** Matthew 5:30

Et si dextra manus tua scandalizat te, abscide eam, et projice abs te : expedit enim tibi ut pereat unum membrorum tuorum, quam totum corpus tuum eat in gehennam.

** Matthew 5:31

Dictum est autem : Quicumque dimiserit uxorem suam, det ei libellum repudii.

** Matthew 5:32

Ego autem dico vobis : quia omnis qui dimiserit uxorem suam, excepta fornicationis causa, facit eam mœchari : et qui dimissam duxerit, adulterat.  

** Matthew 5:33

Iterum audistis quia dictum est antiquis : Non perjurabis : reddes autem Domino juramenta tua.

** Matthew 5:34

Ego autem dico vobis, non jurare omnino, neque per cælum, quia thronus Dei est :

** Matthew 5:35

neque per terram, quia scabellum est pedum ejus : neque per Jerosolymam, quia civitas est magni regis :

** Matthew 5:36

neque per caput tuum juraveris, quia non potes unum capillum album facere, aut nigrum.

** Matthew 5:37

Sit autem sermo vester, est, est : non, non : quod autem his abundantius est, a malo est.  

** Matthew 5:38

Audistis quia dictum est : Oculum pro oculo, et dentem pro dente.

** Matthew 5:39

Ego autem dico vobis, non resistere malo : sed si quis te percusserit in dexteram maxillam tuam, præbe illi et alteram :

** Matthew 5:40

et ei, qui vult tecum judicio contendere, et tunicam tuam tollere, dimitte ei et pallium :

** Matthew 5:41

et quicumque te angariaverit mille passus, vade cum illo et alia duo.

** Matthew 5:42

Qui petit a te, da ei : et volenti mutuari a te, ne avertaris.  

** Matthew 5:43

Audistis quia dictum est : Diliges proximum tuum, et odio habebis inimicum tuum.

** Matthew 5:44

Ego autem dico vobis : diligite inimicos vestros, benefacite his qui oderunt vos, et orate pro persequentibus et calumniantibus vos :

** Matthew 5:45

ut sitis filii Patris vestri, qui in cælis est : qui solem suum oriri facit super bonos et malos : et pluit super justos et injustos.

** Matthew 5:46

Si enim diligitis eos qui vos diligunt, quam mercedem habebitis ? nonne et publicani hoc faciunt ?

** Matthew 5:47

Et si salutaveritis fratres vestros tantum, quid amplius facitis ? nonne et ethnici hoc faciunt ?

** Matthew 5:48

Estote ergo vos perfecti, sicut et Pater vester cælestis perfectus est.   

* Matthew 6

** Matthew 6:1

Attendite ne justitiam vestram faciatis coram hominibus, ut videamini ab eis : alioquin mercedem non habebitis apud Patrem vestrum qui in cælis est.

** Matthew 6:2

Cum ergo facis eleemosynam, noli tuba canere ante te, sicut hypocritæ faciunt in synagogis, et in vicis, ut honorificentur ab hominibus. Amen dico vobis, receperunt mercedem suam.

** Matthew 6:3

Te autem faciente eleemosynam, nesciat sinistra tua quid faciat dextera tua :

** Matthew 6:4

ut sit eleemosyna tua in abscondito, et Pater tuus, qui videt in abscondito, reddet tibi.  

** Matthew 6:5

Et cum oratis, non eritis sicut hypocritæ qui amant in synagogis et in angulis platearum stantes orare, ut videantur ab hominibus : amen dico vobis, receperunt mercedem suam.

** Matthew 6:6

Tu autem cum oraveris, intra in cubiculum tuum, et clauso ostio, ora Patrem tuum in abscondito : et Pater tuus, qui videt in abscondito, reddet tibi.

** Matthew 6:7

Orantes autem, nolite multum loqui, sicut ethnici, putant enim quod in multiloquio suo exaudiantur.

** Matthew 6:8

Nolite ergo assimilari eis : scit enim Pater vester, quid opus sit vobis, antequam petatis eum.

** Matthew 6:9

Sic ergo vos orabitis :   Pater noster, qui es in cælis,  sanctificetur nomen tuum. 

** Matthew 6:10

Adveniat regnum tuum ;  fiat voluntas tua, sicut in cælo et in terra. 

** Matthew 6:11

Panem nostrum supersubstantialem da nobis hodie, 

** Matthew 6:12

et dimitte nobis debita nostra,  sicut et nos dimittimus debitoribus nostris. 

** Matthew 6:13

Et ne nos inducas in tentationem,  sed libera nos a malo. Amen.

** Matthew 6:14

Si enim dimiseritis hominibus peccata eorum : dimittet et vobis Pater vester cælestis delicta vestra.

** Matthew 6:15

Si autem non dimiseritis hominibus : nec Pater vester dimittet vobis peccata vestra.  

** Matthew 6:16

Cum autem jejunatis, nolite fieri sicut hypocritæ, tristes. Exterminant enim facies suas, ut appareant hominibus jejunantes. Amen dico vobis, quia receperunt mercedem suam.

** Matthew 6:17

Tu autem, cum jejunas, unge caput tuum, et faciem tuam lava,

** Matthew 6:18

ne videaris hominibus jejunans, sed Patri tuo, qui est in abscondito : et Pater tuus, qui videt in abscondito, reddet tibi.  

** Matthew 6:19

Nolite thesaurizare vobis thesauros in terra : ubi ærugo, et tinea demolitur : et ubi fures effodiunt, et furantur.

** Matthew 6:20

Thesaurizate autem vobis thesauros in cælo, ubi neque ærugo, neque tinea demolitur, et ubi fures non effodiunt, nec furantur.

** Matthew 6:21

Ubi enim est thesaurus tuus, ibi est et cor tuum.

** Matthew 6:22

Lucerna corporis tui est oculus tuus. Si oculus tuus fuerit simplex, totum corpus tuum lucidum erit.

** Matthew 6:23

Si autem oculus tuus fuerit nequam, totum corpus tuum tenebrosum erit. Si ergo lumen, quod in te est, tenebræ sunt : ipsæ tenebræ quantæ erunt ?

** Matthew 6:24

Nemo potest duobus dominis servire : aut enim unum odio habebit, et alterum diliget : aut unum sustinebit, et alterum contemnet. Non potestis Deo servire et mammonæ.

** Matthew 6:25

Ideo dico vobis, ne solliciti sitis animæ vestræ quid manducetis, neque corpori vestro quid induamini. Nonne anima plus est quam esca, et corpus plus quam vestimentum ?

** Matthew 6:26

Respicite volatilia cæli, quoniam non serunt, neque metunt, neque congregant in horrea : et Pater vester cælestis pascit illa. Nonne vos magis pluris estis illis ?

** Matthew 6:27

Quis autem vestrum cogitans potest adjicere ad staturam suam cubitum unum ?

** Matthew 6:28

Et de vestimento quid solliciti estis ? Considerate lilia agri quomodo crescunt : non laborant, neque nent.

** Matthew 6:29

Dico autem vobis, quoniam nec Salomon in omni gloria sua coopertus est sicut unum ex istis.

** Matthew 6:30

Si autem fœnum agri, quod hodie est, et cras in clibanum mittitur, Deus sic vestit, quanto magis vos modicæ fidei ?

** Matthew 6:31

Nolite ergo solliciti esse, dicentes : Quid manducabimus, aut quid bibemus, aut quo operiemur ?

** Matthew 6:32

hæc enim omnia gentes inquirunt. Scit enim Pater vester, quia his omnibus indigetis.

** Matthew 6:33

Quærite ergo primum regnum Dei, et justitiam ejus : et hæc omnia adjicientur vobis.

** Matthew 6:34

Nolite ergo solliciti esse in crastinum. Crastinus enim dies sollicitus erit sibi ipsi : sufficit diei malitia sua.   

* Matthew 7

** Matthew 7:1

Nolite judicare, ut non judicemini.

** Matthew 7:2

In quo enim judicio judicaveritis, judicabimini : et in qua mensura mensi fueritis, remetietur vobis.

** Matthew 7:3

Quid autem vides festucam in oculo fratris tui, et trabem in oculo tuo non vides ?

** Matthew 7:4

aut quomodo dicis fratri tuo : Sine ejiciam festucam de oculo tuo, et ecce trabs est in oculo tuo ?

** Matthew 7:5

Hypocrita, ejice primum trabem de oculo tuo, et tunc videbis ejicere festucam de oculo fratris tui.

** Matthew 7:6

Nolite dare sanctum canibus : neque mittatis margaritas vestras ante porcos, ne forte conculcent eas pedibus suis, et conversi dirumpant vos.  

** Matthew 7:7

Petite, et dabitur vobis : quærite, et invenietis : pulsate, et aperietur vobis.

** Matthew 7:8

Omnis enim qui petit, accipit : et qui quærit, invenit : et pulsanti aperietur.

** Matthew 7:9

Aut quis est ex vobis homo, quem si petierit filius suus panem, numquid lapidem porriget ei ?

** Matthew 7:10

aut si piscem petierit, numquid serpentem porriget ei ?

** Matthew 7:11

Si ergo vos, cum sitis mali, nostis bona data dare filiis vestris : quanto magis Pater vester, qui in cælis est, dabit bona petentibus se ?  

** Matthew 7:12

Omnia ergo quæcumque vultis ut faciant vobis homines, et vos facite illis. Hæc est enim lex, et prophetæ.

** Matthew 7:13

Intrate per angustam portam : quia lata porta, et spatiosa via est, quæ ducit ad perditionem, et multi sunt qui intrant per eam.

** Matthew 7:14

Quam angusta porta, et arcta via est, quæ ducit ad vitam : et pauci sunt qui inveniunt eam !  

** Matthew 7:15

Attendite a falsis prophetis, qui veniunt ad vos in vestimentis ovium, intrinsecus autem sunt lupi rapaces :

** Matthew 7:16

a fructibus eorum cognoscetis eos. Numquid colligunt de spinis uvas, aut de tribulis ficus ?

** Matthew 7:17

Sic omnis arbor bona fructus bonos facit : mala autem arbor malos fructus facit.

** Matthew 7:18

Non potest arbor bona malos fructus facere : neque arbor mala bonos fructus facere.

** Matthew 7:19

Omnis arbor, quæ non facit fructum bonum, excidetur, et in ignem mittetur.

** Matthew 7:20

Igitur ex fructibus eorum cognoscetis eos.  

** Matthew 7:21

Non omnis qui dicit mihi, Domine, Domine, intrabit in regnum cælorum : sed qui facit voluntatem Patris mei, qui in cælis est, ipse intrabit in regnum cælorum.

** Matthew 7:22

Multi dicent mihi in illa die : Domine, Domine, nonne in nomine tuo prophetavimus, et in nomine tuo dæmonia ejecimus, et in nomine tuo virtutes multas fecimus ?

** Matthew 7:23

Et tunc confitebor illis : Quia numquam novi vos : discedite a me, qui operamini iniquitatem.

** Matthew 7:24

Omnis ergo qui audit verba mea hæc, et facit ea, assimilabitur viro sapienti, qui ædificavit domum suam supra petram,

** Matthew 7:25

et descendit pluvia, et venerunt flumina, et flaverunt venti, et irruerunt in domum illam, et non cecidit : fundata enim erat super petram.

** Matthew 7:26

Et omnis qui audit verba mea hæc, et non facit ea, similis erit viro stulto, qui ædificavit domum suam super arenam :

** Matthew 7:27

et descendit pluvia, et venerunt flumina, et flaverunt venti, et irruerunt in domum illam, et cecidit, et fuit ruina illius magna.

** Matthew 7:28

Et factum est : cum consummasset Jesus verba hæc, admirabantur turbæ super doctrina ejus.

** Matthew 7:29

Erat enim docens eos sicut potestatem habens, et non sicut scribæ eorum, et pharisæi.   

* Matthew 8

** Matthew 8:1

Cum autem descendisset de monte, secutæ sunt eum turbæ multæ :

** Matthew 8:2

et ecce leprosus veniens, adorabat eum, dicens : Domine, si vis, potes me mundare.

** Matthew 8:3

Et extendens Jesus manum, tetigit eum, dicens : Volo : mundare. Et confestim mundata est lepra ejus.

** Matthew 8:4

Et ait illi Jesus : Vide, nemini dixeris : sed vade, ostende te sacerdoti, et offer munus, quod præcepit Moyses, in testimonium illis.  

** Matthew 8:5

Cum autem introisset Capharnaum, accessit ad eum centurio, rogans eum,

** Matthew 8:6

et dicens : Domine, puer meus jacet in domo paralyticus, et male torquetur.

** Matthew 8:7

Et ait illi Jesus : Ego veniam, et curabo eum.

** Matthew 8:8

Et respondens centurio, ait : Domine, non sum dignus ut intres sub tectum meum : sed tantum dic verbo, et sanabitur puer meus.

** Matthew 8:9

Nam et ego homo sum sub potestate constitutus, habens sub me milites, et dico huic : Vade, et vadit : et alii : Veni, et venit : et servo meo : Fac hoc, et facit.

** Matthew 8:10

Audiens autem Jesus miratus est, et sequentibus se dixit : Amen dico vobis, non inveni tantam fidem in Israël.

** Matthew 8:11

Dico autem vobis, quod multi ab oriente et occidente venient, et recumbent cum Abraham, et Isaac, et Jacob in regno cælorum :

** Matthew 8:12

filii autem regni ejicientur in tenebras exteriores : ibi erit fletus et stridor dentium.

** Matthew 8:13

Et dixit Jesus centurioni : Vade, et sicut credidisti, fiat tibi. Et sanatus est puer in illa hora.  

** Matthew 8:14

Et cum venisset Jesus in domum Petri, vidit socrum ejus jacentem, et febricitantem :

** Matthew 8:15

et tetigit manum ejus, et dimisit eam febris, et surrexit, et ministrabat eis.  

** Matthew 8:16

Vespere autem facto, obtulerunt ei multos dæmonia habentes : et ejiciebat spiritus verbo, et omnes male habentes curavit :

** Matthew 8:17

ut adimpleretur quod dictum est per Isaiam prophetam, dicentem :   Ipse infirmitates nostras accepit :  et ægrotationes nostras portavit.

** Matthew 8:18

Videns autem Jesus turbas multas circum se, jussit ire trans fretum.  

** Matthew 8:19

Et accedens unus scriba, ait illi : Magister, sequar te, quocumque ieris.

** Matthew 8:20

Et dicit ei Jesus : Vulpes foveas habent, et volucres cæli nidos ; Filius autem hominis non habet ubi caput reclinet.

** Matthew 8:21

Alius autem de discipulis ejus ait illi : Domine, permitte me primum ire, et sepelire patrem meum.

** Matthew 8:22

Jesus autem ait illi : Sequere me, et dimitte mortuos sepelire mortuos suos.  

** Matthew 8:23

Et ascendente eo in naviculam, secuti sunt eum discipuli ejus :

** Matthew 8:24

et ecce motus magnus factus est in mari, ita ut navicula operiretur fluctibus : ipse vero dormiebat.

** Matthew 8:25

Et accesserunt ad eum discipuli ejus, et suscitaverunt eum, dicentes : Domine, salva nos : perimus.

** Matthew 8:26

Et dicit eis Jesus : Quid timidi estis, modicæ fidei ? Tunc surgens imperavit ventis, et mari, et facta est tranquillitas magna.

** Matthew 8:27

Porro homines mirati sunt, dicentes : Qualis est hic, quia venti et mare obediunt ei ?  

** Matthew 8:28

Et cum venisset trans fretum in regionem Gerasenorum, occurrerunt ei duo habentes dæmonia, de monumentis exeuntes, sævi nimis, ita ut nemo posset transire per viam illam.

** Matthew 8:29

Et ecce clamaverunt, dicentes : Quid nobis et tibi, Jesu fili Dei ? Venisti huc ante tempus torquere nos ?

** Matthew 8:30

Erat autem non longe ab illis grex multorum porcorum pascens.

** Matthew 8:31

Dæmones autem rogabant eum, dicentes : Si ejicis nos hinc, mitte nos in gregem porcorum.

** Matthew 8:32

Et ait illis : Ite. At illi exeuntes abierunt in porcos, et ecce impetu abiit totus grex per præceps in mare : et mortui sunt in aquis.

** Matthew 8:33

Pastores autem fugerunt : et venientes in civitatem, nuntiaverunt omnia, et de eis qui dæmonia habuerant.

** Matthew 8:34

Et ecce tota civitas exiit obviam Jesu : et viso eo, rogabant ut transiret a finibus eorum.   

* Matthew 9

** Matthew 9:1

Et ascendens in naviculam, transfretavit, et venit in civitatem suam.

** Matthew 9:2

Et ecce offerebant ei paralyticum jacentem in lecto. Et videns Jesus fidem illorum, dixit paralytico : Confide fili, remittuntur tibi peccata tua.

** Matthew 9:3

Et ecce quidam de scribis dixerunt intra se : Hic blasphemat.

** Matthew 9:4

Et cum vidisset Jesus cogitationes eorum, dixit : Ut quid cogitatis mala in cordibus vestris ?

** Matthew 9:5

Quid est facilius dicere : Dimittuntur tibi peccata tua : an dicere : Surge, et ambula ?

** Matthew 9:6

Ut autem sciatis, quia Filius hominis habet potestatem in terra dimittendi peccata, tunc ait paralytico : Surge, tolle lectum tuum, et vade in domum tuam.

** Matthew 9:7

Et surrexit, et abiit in domum suam.

** Matthew 9:8

Videntes autem turbæ timuerunt, et glorificaverunt Deum, qui dedit potestatem talem hominibus.  

** Matthew 9:9

Et, cum transiret inde Jesus, vidit hominem sedentem in telonio, Matthæum nomine. Et ait illi : Sequere me. Et surgens, secutus est eum.

** Matthew 9:10

Et factum est, discumbente eo in domo, ecce multi publicani et peccatores venientes, discumbebant cum Jesu, et discipulis ejus.

** Matthew 9:11

Et videntes pharisæi, dicebant discipulis ejus : Quare cum publicanis et peccatoribus manducat magister vester ?

** Matthew 9:12

At Jesus audiens, ait : Non est opus valentibus medicus, sed male habentibus.

** Matthew 9:13

Euntes autem discite quid est : Misericordiam volo, et non sacrificium. Non enim veni vocare justos, sed peccatores.

** Matthew 9:14

Tunc accesserunt ad eum discipuli Joannis, dicentes : Quare nos, et pharisæi, jejunamus frequenter : discipuli autem tui non jejunant ?

** Matthew 9:15

Et ait illis Jesus : Numquid possunt filii sponsi lugere, quamdiu cum illis est sponsus ? Venient autem dies cum auferetur ab eis sponsus : et tunc jejunabunt.

** Matthew 9:16

Nemo autem immittit commissuram panni rudis in vestimentum vetus : tollit enim plenitudinem ejus a vestimento, et pejor scissura fit.

** Matthew 9:17

Neque mittunt vinum novum in utres veteres : alioquin rumpuntur utres, et vinum effunditur, et utres pereunt. Sed vinum novum in utres novos mittunt : et ambo conservantur.  

** Matthew 9:18

Hæc illo loquente ad eos, ecce princeps unus accessit, et adorabat eum, dicens : Domine, filia mea modo defuncta est : sed veni, impone manum tuam super eam, et vivet.

** Matthew 9:19

Et surgens Jesus, sequebatur eum, et discipuli ejus.

** Matthew 9:20

Et ecce mulier, quæ sanguinis fluxum patiebatur duodecim annis, accessit retro, et tetigit fimbriam vestimenti ejus.

** Matthew 9:21

Dicebat enim intra se : Si tetigero tantum vestimentum ejus, salva ero.

** Matthew 9:22

At Jesus conversus, et videns eam, dixit : Confide, filia, fides tua te salvam fecit. Et salva facta est mulier ex illa hora.  

** Matthew 9:23

Et cum venisset Jesus in domum principis, et vidisset tibicines et turbam tumultuantem, dicebat :

** Matthew 9:24

Recedite : non est enim mortua puella, sed dormit. Et deridebant eum.

** Matthew 9:25

Et cum ejecta esset turba, intravit : et tenuit manum ejus, et surrexit puella.

** Matthew 9:26

Et exiit fama hæc in universam terram illam.  

** Matthew 9:27

Et transeunte inde Jesu, secuti sunt eum duo cæci, clamantes, et dicentes : Miserere nostri, fili David.

** Matthew 9:28

Cum autem venisset domum, accesserunt ad eum cæci. Et dicit eis Jesus : Creditis quia hoc possum facere vobis ? Dicunt ei : Utique, Domine.

** Matthew 9:29

Tunc tetigit oculos eorum, dicens : Secundum fidem vestram, fiat vobis.

** Matthew 9:30

Et aperti sunt oculi eorum : et comminatus est illis Jesus, dicens : Videte ne quis sciat.

** Matthew 9:31

Illi autem exeuntes, diffamaverunt eum in tota terra illa.  

** Matthew 9:32

Egressis autem illis, ecce obtulerunt ei hominem mutum, dæmonium habentem.

** Matthew 9:33

Et ejecto dæmonio, locutus est mutus, et miratæ sunt turbæ, dicentes : Numquam apparuit sic in Israël.

** Matthew 9:34

Pharisæi autem dicebant : In principe dæmoniorum ejicit dæmones.  

** Matthew 9:35

Et circuibat Jesus omnes civitates, et castella, docens in synagogis eorum, et prædicans Evangelium regni, et curans omnem languorem, et omnem infirmitatem.

** Matthew 9:36

Videns autem turbas, misertus est eis : quia erant vexati, et jacentes sicut oves non habentes pastorem.

** Matthew 9:37

Tunc dicit discipulis suis : Messis quidem multa, operarii autem pauci.

** Matthew 9:38

Rogate ergo Dominum messis, ut mittat operarios in messem suam.   

* Matthew 10

** Matthew 10:1

Et convocatis duodecim discipulis suis, dedit illis potestatem spirituum immundorum, ut ejicerent eos, et curarent omnem languorem, et omnem infirmitatem.

** Matthew 10:2

Duodecim autem Apostolorum nomina sunt hæc. Primus, Simon, qui dicitur Petrus : et Andreas frater ejus,

** Matthew 10:3

Jacobus Zebedæi, et Joannes frater ejus, Philippus, et Bartholomæus, Thomas, et Matthæus publicanus, Jacobus Alphæi, et Thaddæus,

** Matthew 10:4

Simon Chananæus, et Judas Iscariotes, qui et tradidit eum.  

** Matthew 10:5

Hos duodecim misit Jesus, præcipiens eis, dicens : In viam gentium ne abieritis, et in civitates Samaritanorum ne intraveritis :

** Matthew 10:6

sed potius ite ad oves quæ perierunt domus Israël.

** Matthew 10:7

Euntes autem prædicate, dicentes : Quia appropinquavit regnum cælorum.

** Matthew 10:8

Infirmos curate, mortuos suscitate, leprosos mundate, dæmones ejicite : gratis accepistis, gratis date.

** Matthew 10:9

Nolite possidere aurum, neque argentum, neque pecuniam in zonis vestris :

** Matthew 10:10

non peram in via, neque duas tunicas, neque calceamenta, neque virgam : dignus enim est operarius cibo suo.

** Matthew 10:11

In quamcumque autem civitatem aut castellum intraveritis, interrogate, quis in ea dignus sit : et ibi manete donec exeatis.

** Matthew 10:12

Intrantes autem in domum, salutate eam, dicentes : Pax huic domui.

** Matthew 10:13

Et siquidem fuerit domus illa digna, veniet pax vestra super eam : si autem non fuerit digna, pax vestra revertetur ad vos.

** Matthew 10:14

Et quicumque non receperit vos, neque audierit sermones vestros : exeuntes foras de domo, vel civitate, excutite pulverem de pedibus vestris.

** Matthew 10:15

Amen dico vobis : Tolerabilius erit terræ Sodomorum et Gomorrhæorum in die judicii, quam illi civitati.  

** Matthew 10:16

Ecce ego mitto vos sicut oves in medio luporum. Estote ergo prudentes sicut serpentes, et simplices sicut columbæ.

** Matthew 10:17

Cavete autem ab hominibus. Tradent enim vos in conciliis, et in synagogis suis flagellabunt vos :

** Matthew 10:18

et ad præsides, et ad reges ducemini propter me in testimonium illis, et gentibus.

** Matthew 10:19

Cum autem tradent vos, nolite cogitare quomodo, aut quid loquamini : dabitur enim vobis in illa hora, quid loquamini :

** Matthew 10:20

non enim vos estis qui loquimini, sed Spiritus Patris vestri, qui loquitur in vobis.

** Matthew 10:21

Tradet autem frater fratrem in mortem, et pater filium : et insurgent filii in parentes, et morte eos afficient :

** Matthew 10:22

et eritis odio omnibus propter nomen meum : qui autem perseveraverit usque in finem, hic salvus erit.  

** Matthew 10:23

Cum autem persequentur vos in civitate ista, fugite in aliam. Amen dico vobis, non consummabitis civitates Israël, donec veniat Filius hominis.

** Matthew 10:24

Non est discipulus super magistrum, nec servus super dominum suum :

** Matthew 10:25

sufficit discipulo ut sit sicut magister ejus, et servo, sicut dominus ejus. Si patremfamilias Beelzebub vocaverunt, quanto magis domesticos ejus ?

** Matthew 10:26

Ne ergo timueritis eos. Nihil enim est opertum, quod non revelabitur : et occultum, quod non scietur.

** Matthew 10:27

Quod dico vobis in tenebris, dicite in lumine : et quod in aure auditis, prædicate super tecta.

** Matthew 10:28

Et nolite timere eos qui occidunt corpus, animam autem non possunt occidere : sed potius timete eum, qui potest et animam et corpus perdere in gehennam.

** Matthew 10:29

Nonne duo passeres asse veneunt ? et unus ex illis non cadet super terram sine Patre vestro.

** Matthew 10:30

Vestri autem capilli capitis omnes numerati sunt.

** Matthew 10:31

Nolite ergo timere : multis passeribus meliores estis vos.

** Matthew 10:32

Omnis ergo qui confitebitur me coram hominibus, confitebor et ego eum coram Patre meo, qui in cælis est.

** Matthew 10:33

Qui autem negaverit me coram hominibus, negabo et ego eum coram Patre meo, qui in cælis est.

** Matthew 10:34

Nolite arbitrari quia pacem venerim mittere in terram : non veni pacem mittere, sed gladium :

** Matthew 10:35

veni enim separare hominem adversus patrem suum, et filiam adversus matrem suam, et nurum adversus socrum suam :

** Matthew 10:36

et inimici hominis, domestici ejus.

** Matthew 10:37

Qui amat patrem aut matrem plus quam me, non est me dignus : et qui amat filium aut filiam super me, non est me dignus.

** Matthew 10:38

Et qui non accipit crucem suam, et sequitur me, non est me dignus.

** Matthew 10:39

Qui invenit animam suam, perdet illam : et qui perdiderit animam suam propter me, inveniet eam.

** Matthew 10:40

Qui recipit vos, me recipit : et qui me recipit, recipit eum qui me misit.

** Matthew 10:41

Qui recipit prophetam in nomine prophetæ, mercedem prophetæ accipiet : et qui recipit justum in nomine justi, mercedem justi accipiet.

** Matthew 10:42

Et quicumque potum dederit uni ex minimis istis calicem aquæ frigidæ tantum in nomine discipuli : amen dico vobis, non perdet mercedem suam.   

* Matthew 11

** Matthew 11:1

Et factum est, cum consummasset Jesus, præcipiens duodecim discipulis suis, transiit inde ut doceret, et prædicaret in civitatibus eorum.  

** Matthew 11:2

Joannes autem cum audisset in vinculis opera Christi, mittens duos de discipulis suis,

** Matthew 11:3

ait illi : Tu es, qui venturus es, an alium exspectamus ?

** Matthew 11:4

Et respondens Jesus ait illis : Euntes renuntiate Joanni quæ audistis, et vidistis.

** Matthew 11:5

Cæci vident, claudi ambulant, leprosi mundantur, surdi audiunt, mortui resurgunt, pauperes evangelizantur :

** Matthew 11:6

et beatus est, qui non fuerit scandalizatus in me.  

** Matthew 11:7

Illis autem abeuntibus, cœpit Jesus dicere ad turbas de Joanne : Quid existis in desertum videre ? arundinem vento agitatam ?

** Matthew 11:8

Sed quid existis videre ? hominem mollibus vestitum ? Ecce qui mollibus vestiuntur, in domibus regum sunt.

** Matthew 11:9

Sed quid existis videre ? prophetam ? Etiam dico vobis, et plus quam prophetam.

** Matthew 11:10

Hic est enim de quo scriptum est : Ecce ego mitto angelum meum ante faciem tuam, qui præparabit viam tuam ante te.

** Matthew 11:11

Amen dico vobis, non surrexit inter natos mulierum major Joanne Baptista : qui autem minor est in regno cælorum, major est illo.

** Matthew 11:12

A diebus autem Joannis Baptistæ usque nunc, regnum cælorum vim patitur, et violenti rapiunt illud.

** Matthew 11:13

Omnes enim prophetæ et lex usque ad Joannem prophetaverunt :

** Matthew 11:14

et si vultis recipere, ipse est Elias, qui venturus est.

** Matthew 11:15

Qui habet aures audiendi, audiat.  

** Matthew 11:16

Cui autem similem æstimabo generationem istam ? Similis est pueris sedentibus in foro : qui clamantes coæqualibus

** Matthew 11:17

dicunt : Cecinimus vobis, et non saltastis : lamentavimus, et non planxistis.

** Matthew 11:18

Venit enim Joannes neque manducans, neque bibens, et dicunt : Dæmonium habet.

** Matthew 11:19

Venit Filius hominis manducans, et bibens, et dicunt : Ecce homo vorax, et potator vini, publicanorum et peccatorum amicus. Et justificata est sapientia a filiis suis.  

** Matthew 11:20

Tunc cœpit exprobrare civitatibus, in quibus factæ sunt plurimæ virtutes ejus, quia non egissent pœnitentiam :

** Matthew 11:21

Væ tibi Corozain, væ tibi Bethsaida : quia, si in Tyro et Sidone factæ essent virtutes quæ factæ sunt in vobis, olim in cilicio et cinere pœnitentiam egissent.

** Matthew 11:22

Verumtamen dico vobis : Tyro et Sidoni remissius erit in die judicii, quam vobis.

** Matthew 11:23

Et tu Capharnaum, numquid usque in cælum exaltaberis ? usque in infernum descendes, quia si in Sodomis factæ fuissent virtutes quæ factæ sunt in te, forte mansissent usque in hanc diem.

** Matthew 11:24

Verumtamen dico vobis, quia terræ Sodomorum remissius erit in die judicii, quam tibi.  

** Matthew 11:25

In illo tempore respondens Jesus dixit : Confiteor tibi, Pater, Domine cæli et terræ, quia abscondisti hæc a sapientibus, et prudentibus, et revelasti ea parvulis.

** Matthew 11:26

Ita Pater : quoniam sic fuit placitum ante te.

** Matthew 11:27

Omnia mihi tradita sunt a Patre meo. Et nemo novit Filium, nisi Pater : neque Patrem quis novit, nisi Filius, et cui voluerit Filius revelare.

** Matthew 11:28

Venite ad me omnes qui laboratis, et onerati estis, et ego reficiam vos.

** Matthew 11:29

Tollite jugum meum super vos, et discite a me, quia mitis sum, et humilis corde : et invenietis requiem animabus vestris.

** Matthew 11:30

Jugum enim meum suave est, et onus meum leve.   

* Matthew 12

** Matthew 12:1

In illo tempore abiit Jesus per sata sabbato : discipuli autem ejus esurientes cœperunt vellere spicas, et manducare.

** Matthew 12:2

Pharisæi autem videntes, dixerunt ei : Ecce discipuli tui faciunt quod non licet facere sabbatis.

** Matthew 12:3

At ille dixit eis : Non legistis quid fecerit David, quando esuriit, et qui cum eo erant :

** Matthew 12:4

quomodo intravit in domum Dei, et panes propositionis comedit, quos non licebat ei edere, neque his qui cum eo erant, nisi solis sacerdotibus ?

** Matthew 12:5

aut non legistis in lege quia sabbatis sacerdotes in templo sabbatum violant, et sine crimine sunt ?

** Matthew 12:6

Dico autem vobis, quia templo major est hic.

** Matthew 12:7

Si autem sciretis, quid est : Misericordiam volo, et non sacrificium : numquam condemnassetis innocentes :

** Matthew 12:8

dominus enim est Filius hominis etiam sabbati.  

** Matthew 12:9

Et cum inde transisset, venit in synagogam eorum.

** Matthew 12:10

Et ecce homo manum habens aridam, et interrogabant eum, dicentes : Si licet sabbatis curare ? ut accusarent eum.

** Matthew 12:11

Ipse autem dixit illis : Quis erit ex vobis homo, qui habeat ovem unam, et si ceciderit hæc sabbatis in foveam, nonne tenebit et levabit eam ?

** Matthew 12:12

Quanto magis melior est homo ove ? itaque licet sabbatis benefacere.

** Matthew 12:13

Tunc ait homini : Extende manum tuam. Et extendit, et restituta est sanitati sicut altera.

** Matthew 12:14

Exeuntes autem pharisæi, consilium faciebant adversus eum, quomodo perderent eum.

** Matthew 12:15

Jesus autem sciens recessit inde : et secuti sunt eum multi, et curavit eos omnes :

** Matthew 12:16

et præcepit eis ne manifestum eum facerent.

** Matthew 12:17

Ut adimpleretur quod dictum est per Isaiam prophetam, dicentem :  

** Matthew 12:18

Ecce puer meus, quem elegi, dilectus meus,  in quo bene complacuit animæ meæ.  Ponam spiritum meum super eum,  et judicium gentibus nuntiabit. 

** Matthew 12:19

Non contendet, neque clamabit,  neque audiet aliquis in plateis vocem ejus : 

** Matthew 12:20

arundinem quassatam non confringet,  et linum fumigans non extinguet,  donec ejiciat ad victoriam judicium : 

** Matthew 12:21

et in nomine ejus gentes sperabunt.  

** Matthew 12:22

Tunc oblatus est ei dæmonium habens, cæcus, et mutus, et curavit eum ita ut loqueretur, et videret.

** Matthew 12:23

Et stupebant omnes turbæ, et dicebant : Numquid hic est filius David ?

** Matthew 12:24

Pharisæi autem audientes, dixerunt : Hic non ejicit dæmones nisi in Beelzebub principe dæmoniorum.

** Matthew 12:25

Jesus autem sciens cogitationes eorum, dixit eis : Omne regnum divisum contra se desolabitur : et omnis civitas vel domus divisa contra se, non stabit.

** Matthew 12:26

Et si Satanas Satanam ejicit, adversus se divisus est : quomodo ergo stabit regnum ejus ?

** Matthew 12:27

Et si ego in Beelzebub ejicio dæmones, filii vestri in quo ejiciunt ? ideo ipsi judices vestri erunt.

** Matthew 12:28

Si autem ego in Spiritu Dei ejicio dæmones, igitur pervenit in vos regnum Dei.

** Matthew 12:29

Aut quomodo potest quisquam intrare in domum fortis, et vasa ejus diripere, nisi prius alligaverit fortem ? et tunc domum illius diripiet.

** Matthew 12:30

Qui non est mecum, contra me est ; et qui non congregat mecum, spargit.

** Matthew 12:31

Ideo dico vobis : Omne peccatum et blasphemia remittetur hominibus, Spiritus autem blasphemia non remittetur.

** Matthew 12:32

Et quicumque dixerit verbum contra Filium hominis, remittetur ei : qui autem dixerit contra Spiritum Sanctum, non remittetur ei, neque in hoc sæculo, neque in futuro.

** Matthew 12:33

Aut facite arborem bonam, et fructum ejus bonum : aut facite arborem malam, et fructum ejus malum : siquidem ex fructu arbor agnoscitur.

** Matthew 12:34

Progenies viperarum, quomodo potestis bona loqui, cum sitis mali ? ex abundantia enim cordis os loquitur.

** Matthew 12:35

Bonus homo de bono thesauro profert bona : et malus homo de malo thesauro profert mala.

** Matthew 12:36

Dico autem vobis quoniam omne verbum otiosum, quod locuti fuerint homines, reddent rationem de eo in die judicii.

** Matthew 12:37

Ex verbis enim tuis justificaberis et ex verbis tuis condemnaberis.  

** Matthew 12:38

Tunc responderunt ei quidam de scribis et pharisæis, dicentes : Magister, volumus a te signum videre.

** Matthew 12:39

Qui respondens ait illis : Generatio mala et adultera signum quærit : et signum non dabitur ei, nisi signum Jonæ prophetæ.

** Matthew 12:40

Sicut enim fuit Jonas in ventre ceti tribus diebus, et tribus noctibus, sic erit Filius hominis in corde terræ tribus diebus et tribus noctibus.

** Matthew 12:41

Viri Ninivitæ surgent in judicio cum generatione ista, et condemnabunt eam : quia pœnitentiam egerunt in prædicatione Jonæ, et ecce plus quam Jonas hic.

** Matthew 12:42

Regina austri surget in judicio cum generatione ista, et condemnabit eam : quia venit a finibus terræ audire sapientiam Salomonis, et ecce plus quam Salomon hic.

** Matthew 12:43

Cum autem immundus spiritus exierit ab homine, ambulat per loca arida, quærens requiem, et non invenit.

** Matthew 12:44

Tunc dicit : Revertar in domum meam, unde exivi. Et veniens invenit eam vacantem, scopis mundatam, et ornatam.

** Matthew 12:45

Tunc vadit, et assumit septem alios spiritus secum nequiores se, et intrantes habitant ibi : et fiunt novissima hominis illius pejora prioribus. Sic erit et generationi huic pessimæ.  

** Matthew 12:46

Adhuc eo loquente ad turbas, ecce mater ejus et fratres stabant foris, quærentes loqui ei.

** Matthew 12:47

Dixit autem ei quidam : Ecce mater tua, et fratres tui foris stant quærentes te.

** Matthew 12:48

At ipse respondens dicenti sibi, ait : Quæ est mater mea, et qui sunt fratres mei ?

** Matthew 12:49

Et extendens manum in discipulos suos, dixit : Ecce mater mea, et fratres mei.

** Matthew 12:50

Quicumque enim fecerit voluntatem Patris mei, qui in cælis est, ipse meus frater, et soror, et mater est.   

* Matthew 13

** Matthew 13:1

In illo die exiens Jesus de domo, sedebat secus mare.

** Matthew 13:2

Et congregatæ sunt ad eum turbæ multæ, ita ut naviculam ascendens sederet : et omnis turba stabat in littore,

** Matthew 13:3

et locutus est eis multa in parabolis, dicens : Ecce exiit qui seminat, seminare.

** Matthew 13:4

Et dum seminat, quædam ceciderunt secus viam, et venerunt volucres cæli, et comederunt ea.

** Matthew 13:5

Alia autem ceciderunt in petrosa, ubi non habebant terram multam : et continuo exorta sunt, quia non habebant altitudinem terræ :

** Matthew 13:6

sole autem orto æstuaverunt ; et quia non habebant radicem, aruerunt.

** Matthew 13:7

Alia autem ceciderunt in spinas : et creverunt spinæ, et suffocaverunt ea.

** Matthew 13:8

Alia autem ceciderunt in terram bonam : et dabant fructum, aliud centesimum, aliud sexagesimum, aliud trigesimum.

** Matthew 13:9

Qui habet aures audiendi, audiat.  

** Matthew 13:10

Et accedentes discipuli dixerunt ei : Quare in parabolis loqueris eis ?

** Matthew 13:11

Qui respondens, ait illis : Quia vobis datum est nosse mysteria regni cælorum : illis autem non est datum.

** Matthew 13:12

Qui enim habet, dabitur ei, et abundabit : qui autem non habet, et quod habet auferetur ab eo.

** Matthew 13:13

Ideo in parabolis loquor eis : quia videntes non vident, et audientes non audiunt, neque intelligunt.

** Matthew 13:14

Et adimpletur in eis prophetia Isaiæ, dicentis :   Auditu audietis, et non intelligetis :  et videntes videbitis, et non videbitis. 

** Matthew 13:15

Incrassatum est enim cor populi hujus,  et auribus graviter audierunt,  et oculos suos clauserunt :  nequando videant oculis, et auribus audiant,  et corde intelligant, et convertantur,  et sanem eos.

** Matthew 13:16

Vestri autem beati oculi quia vident, et aures vestræ quia audiunt.

** Matthew 13:17

Amen quippe dico vobis, quia multi prophetæ et justi cupierunt videre quæ videtis, et non viderunt : et audire quæ auditis, et non audierunt.  

** Matthew 13:18

Vos ergo audite parabolam seminantis.

** Matthew 13:19

Omnis qui audit verbum regni, et non intelligit, venit malus, et rapit quod seminatum est in corde ejus : hic est qui secus viam seminatus est.

** Matthew 13:20

Qui autem super petrosa seminatus est, hic est qui verbum audit, et continuo cum gaudio accipit illud :

** Matthew 13:21

non habet autem in se radicem, sed est temporalis : facta autem tribulatione et persecutione propter verbum, continuo scandalizatur.

** Matthew 13:22

Qui autem seminatus est in spinis, hic est qui verbum audit, et sollicitudo sæculi istius, et fallacia divitiarum suffocat verbum, et sine fructu efficitur.

** Matthew 13:23

Qui vero in terram bonam seminatus est, hic est qui audit verbum, et intelligit, et fructum affert, et facit aliud quidem centesimum, aliud autem sexagesimum, aliud vero trigesimum.  

** Matthew 13:24

Aliam parabolam proposuit illis, dicens : Simile factum est regnum cælorum homini, qui seminavit bonum semen in agro suo :

** Matthew 13:25

cum autem dormirent homines, venit inimicus ejus, et superseminavit zizania in medio tritici, et abiit.

** Matthew 13:26

Cum autem crevisset herba, et fructum fecisset, tunc apparuerunt et zizania.

** Matthew 13:27

Accedentes autem servi patrisfamilias, dixerunt ei : Domine, nonne bonum semen seminasti in agro tuo ? unde ergo habet zizania ?

** Matthew 13:28

Et ait illis : Inimicus homo hoc fecit. Servi autem dixerunt ei : Vis, imus, et colligimus ea ?

** Matthew 13:29

Et ait : Non : ne forte colligentes zizania, eradicetis simul cum eis et triticum.

** Matthew 13:30

Sinite utraque crescere usque ad messem, et in tempore messis dicam messoribus : Colligite primum zizania, et alligate ea in fasciculos ad comburendum : triticum autem congregate in horreum meum.  

** Matthew 13:31

Aliam parabolam proposuit eis dicens : Simile est regnum cælorum grano sinapis, quod accipiens homo seminavit in agro suo :

** Matthew 13:32

quod minimum quidem est omnibus seminibus : cum autem creverit, majus est omnibus oleribus, et fit arbor, ita ut volucres cæli veniant, et habitent in ramis ejus.

** Matthew 13:33

Aliam parabolam locutus est eis : Simile est regnum cælorum fermento, quod acceptum mulier abscondit in farinæ satis tribus, donec fermentatum est totum.

** Matthew 13:34

Hæc omnia locutus est Jesus in parabolis ad turbas : et sine parabolis non loquebatur eis :

** Matthew 13:35

ut impleretur quod dictum erat per prophetam dicentem : Aperiam in parabolis os meum ; eructabo abscondita a constitutione mundi.  

** Matthew 13:36

Tunc, dimissis turbis, venit in domum : et accesserunt ad eum discipuli ejus, dicentes : Edissere nobis parabolam zizaniorum agri.

** Matthew 13:37

Qui respondens ait illis : Qui seminat bonum semen, est Filius hominis.

** Matthew 13:38

Ager autem est mundus. Bonum vero semen, hi sunt filii regni. Zizania autem, filii sunt nequam.

** Matthew 13:39

Inimicus autem, qui seminavit ea, est diabolus. Messis vero, consummatio sæculi est. Messores autem, angeli sunt.

** Matthew 13:40

Sicut ergo colliguntur zizania, et igni comburuntur : sic erit in consummatione sæculi.

** Matthew 13:41

Mittet Filius hominis angelos suos, et colligent de regno ejus omnia scandala, et eos qui faciunt iniquitatem :

** Matthew 13:42

et mittent eos in caminum ignis. Ibi erit fletus et stridor dentium.

** Matthew 13:43

Tunc justi fulgebunt sicut sol in regno Patris eorum. Qui habet aures audiendi, audiat.  

** Matthew 13:44

Simile est regnum cælorum thesauro abscondito in agro : quem qui invenit homo, abscondit, et præ gaudio illius vadit, et vendit universa quæ habet, et emit agrum illum.

** Matthew 13:45

Iterum simile est regnum cælorum homini negotiatori, quærenti bonas margaritas.

** Matthew 13:46

Inventa autem una pretiosa margarita, abiit, et vendidit omnia quæ habuit, et emit eam.  

** Matthew 13:47

Iterum simile est regnum cælorum sagenæ missæ in mare, et ex omni genere piscium congreganti.

** Matthew 13:48

Quam, cum impleta esset, educentes, et secus littus sedentes, elegerunt bonos in vasa, malos autem foras miserunt.

** Matthew 13:49

Sic erit in consummatione sæculi : exibunt angeli, et separabunt malos de medio justorum,

** Matthew 13:50

et mittent eos in caminum ignis : ibi erit fletus, et stridor dentium.

** Matthew 13:51

Intellexistis hæc omnia ? Dicunt ei : Etiam.

** Matthew 13:52

Ait illis : Ideo omnis scriba doctus in regno cælorum, similis est homini patrifamilias, qui profert de thesauro suo nova et vetera.

** Matthew 13:53

Et factum est, cum consummasset Jesus parabolas istas, transiit inde.  

** Matthew 13:54

Et veniens in patriam suam, docebat eos in synagogis eorum, ita ut mirarentur, et dicerent : Unde huic sapientia hæc, et virtutes ?

** Matthew 13:55

Nonne hic est fabri filius ? nonne mater ejus dicitur Maria, et fratres ejus, Jacobus, et Joseph, et Simon, et Judas ?

** Matthew 13:56

et sorores ejus, nonne omnes apud nos sunt ? unde ergo huic omnia ista ?

** Matthew 13:57

Et scandalizabantur in eo. Jesus autem dixit eis : Non est propheta sine honore, nisi in patria sua, et in domo sua.

** Matthew 13:58

Et non fecit ibi virtutes multas propter incredulitatem illorum.   

* Matthew 14

** Matthew 14:1

In illo tempore audivit Herodes tetrarcha famam Jesu :

** Matthew 14:2

et ait pueris suis : Hic est Joannes Baptista : ipse surrexit a mortuis, et ideo virtutes operantur in eo.

** Matthew 14:3

Herodes enim tenuit Joannem, et alligavit eum : et posuit in carcerem propter Herodiadem uxorem fratris sui.

** Matthew 14:4

Dicebat enim illi Joannes : Non licet tibi habere eam.

** Matthew 14:5

Et volens illum occidere, timuit populum : quia sicut prophetam eum habebant.

** Matthew 14:6

Die autem natalis Herodis saltavit filia Herodiadis in medio, et placuit Herodi :

** Matthew 14:7

unde cum juramento pollicitus est ei dare quodcumque postulasset ab eo.

** Matthew 14:8

At illa præmonita a matre sua : Da mihi, inquit, hic in disco caput Joannis Baptistæ.

** Matthew 14:9

Et contristatus est rex : propter juramentum autem, et eos qui pariter recumbebant, jussit dari.

** Matthew 14:10

Misitque et decollavit Joannem in carcere.

** Matthew 14:11

Et allatum est caput ejus in disco, et datum est puellæ, et attulit matri suæ.

** Matthew 14:12

Et accedentes discipuli ejus, tulerunt corpus ejus, et sepelierunt illud : et venientes nuntiaverunt Jesu.  

** Matthew 14:13

Quod cum audisset Jesus, secessit inde in navicula, in locum desertum seorsum : et cum audissent turbæ, secutæ sunt eum pedestres de civitatibus.

** Matthew 14:14

Et exiens vidit turbam multam, et misertus est eis, et curavit languidos eorum.

** Matthew 14:15

Vespere autem facto, accesserunt ad eum discipuli ejus, dicentes : Desertus est locus, et hora jam præteriit : dimitte turbas, ut euntes in castella, emant sibi escas.

** Matthew 14:16

Jesus autem dixit eis : Non habent necesse ire : date illis vos manducare.

** Matthew 14:17

Responderunt ei : Non habemus hic nisi quinque panes et duos pisces.

** Matthew 14:18

Qui ait eis : Afferte mihi illos huc.

** Matthew 14:19

Et cum jussisset turbam discumbere super fœnum, acceptis quinque panibus et duobus piscibus, aspiciens in cælum benedixit, et fregit, et dedit discipulis panes, discipuli autem turbis.

** Matthew 14:20

Et manducaverunt omnes, et saturati sunt. Et tulerunt reliquias, duodecim cophinos fragmentorum plenos.

** Matthew 14:21

Manducantium autem fuit numerus quinque millia virorum, exceptis mulieribus et parvulis.  

** Matthew 14:22

Et statim compulit Jesus discipulos ascendere in naviculam, et præcedere eum trans fretum, donec dimitteret turbas.

** Matthew 14:23

Et dimissa turba, ascendit in montem solus orare. Vespere autem facto solus erat ibi :

** Matthew 14:24

navicula autem in medio mari jactabatur fluctibus : erat enim contrarius ventus.

** Matthew 14:25

Quarta enim vigilia noctis, venit ad eos ambulans super mare.

** Matthew 14:26

Et videntes eum super mare ambulantem, turbati sunt, dicentes : Quia phantasma est. Et præ timore clamaverunt.

** Matthew 14:27

Statimque Jesus locutus est eis, dicens : Habete fiduciam : ego sum, nolite timere.

** Matthew 14:28

Respondens autem Petrus, dixit : Domine, si tu es, jube me ad te venire super aquas.

** Matthew 14:29

At ipse ait : Veni. Et descendens Petrus de navicula, ambulabat super aquam ut veniret ad Jesum.

** Matthew 14:30

Videns vero ventum validum, timuit : et cum cœpisset mergi, clamavit dicens : Domine, salvum me fac.

** Matthew 14:31

Et continuo Jesus extendens manum, apprehendit eum : et ait illi : Modicæ fidei, quare dubitasti ?

** Matthew 14:32

Et cum ascendissent in naviculam, cessavit ventus.

** Matthew 14:33

Qui autem in navicula erant, venerunt, et adoraverunt eum, dicentes : Vere Filius Dei es.

** Matthew 14:34

Et cum transfretassent, venerunt in terram Genesar.

** Matthew 14:35

Et cum cognovissent eum viri loci illius, miserunt in universam regionem illam, et obtulerunt ei omnes male habentes :

** Matthew 14:36

et rogabant eum ut vel fimbriam vestimenti ejus tangerent. Et quicumque tetigerunt, salvi facti sunt.   

* Matthew 15

** Matthew 15:1

Tunc accesserunt ad eum ab Jerosolymis scribæ et pharisæi, dicentes :

** Matthew 15:2

Quare discipuli tui transgrediuntur traditionem seniorum ? non enim lavant manus suas cum panem manducant.

** Matthew 15:3

Ipse autem respondens ait illis : Quare et vos transgredimini mandatum Dei propter traditionem vestram ? Nam Deus dixit :

** Matthew 15:4

Honora patrem, et matrem : et, Qui maledixerit patri, vel matri, morte moriatur.

** Matthew 15:5

Vos autem dicitis : Quicumque dixerit patri, vel matri : Munus, quodcumque est ex me, tibi proderit :

** Matthew 15:6

et non honorificabit patrem suum, aut matrem suam : et irritum fecistis mandatum Dei propter traditionem vestram.

** Matthew 15:7

Hypocritæ, bene prophetavit de vobis Isaias, dicens :  

** Matthew 15:8

Populus hic labiis me honorat :  cor autem eorum longe est a me. 

** Matthew 15:9

Sine causa autem colunt me,  docentes doctrinas et mandata hominum.  

** Matthew 15:10

Et convocatis ad se turbis, dixit eis : Audite, et intelligite.

** Matthew 15:11

Non quod intrat in os, coinquinat hominem : sed quod procedit ex ore, hoc coinquinat hominem.

** Matthew 15:12

Tunc accedentes discipuli ejus, dixerunt ei : Scis quia pharisæi audito verbo hoc, scandalizati sunt ?

** Matthew 15:13

At ille respondens ait : Omnis plantatio, quam non plantavit Pater meus cælestis, eradicabitur.

** Matthew 15:14

Sinite illos : cæci sunt, et duces cæcorum ; cæcus autem si cæco ducatum præstet, ambo in foveam cadunt.

** Matthew 15:15

Respondens autem Petrus dixit ei : Edissere nobis parabolam istam.

** Matthew 15:16

At ille dixit : Adhuc et vos sine intellectu estis ?

** Matthew 15:17

Non intelligitis quia omne quod in os intrat, in ventrem vadit, et in secessum emittitur ?

** Matthew 15:18

Quæ autem procedunt de ore, de corde exeunt, et ea coinquinant hominem :

** Matthew 15:19

de corde enim exeunt cogitationes malæ, homicidia, adulteria, fornicationes, furta, falsa testimonia, blasphemiæ :

** Matthew 15:20

hæc sunt, quæ coinquinant hominem. Non lotis autem manibus manducare, non coinquinat hominem.  

** Matthew 15:21

Et egressus inde Jesus secessit in partes Tyri et Sidonis.

** Matthew 15:22

Et ecce mulier chananæa a finibus illis egressa clamavit, dicens ei : Miserere mei, Domine fili David : filia mea male a dæmonio vexatur.

** Matthew 15:23

Qui non respondit ei verbum. Et accedentes discipuli ejus rogabant eum dicentes : Dimitte eam : quia clamat post nos.

** Matthew 15:24

Ipse autem respondens ait : Non sum missus nisi ad oves, quæ perierunt domus Israël.

** Matthew 15:25

At illa venit, et adoravit eum, dicens : Domine, adjuva me.

** Matthew 15:26

Qui respondens ait : Non est bonum sumere panem filiorum, et mittere canibus.

** Matthew 15:27

At illa dixit : Etiam Domine : nam et catelli edunt de micis quæ cadunt de mensa dominorum suorum.

** Matthew 15:28

Tunc respondens Jesus, ait illi : O mulier, magna est fides tua : fiat tibi sicut vis. Et sanata est filia ejus ex illa hora.  

** Matthew 15:29

Et cum transisset inde Jesus, venit secus mare Galilææ : et ascendens in montem, sedebat ibi.

** Matthew 15:30

Et accesserunt ad eum turbæ multæ, habentes secum mutos, cæcos, claudos, debiles, et alios multos : et projecerunt eos ad pedes ejus, et curavit eos,

** Matthew 15:31

ita ut turbæ mirarentur, videntes mutos loquentes, claudos ambulantes, cæcos videntes : et magnificabant Deum Israël.

** Matthew 15:32

Jesus autem, convocatis discipulis suis, dixit : Misereor turbæ, quia triduo jam perseverant mecum, et non habent quod manducent : et dimittere eos jejunos nolo, ne deficiant in via.

** Matthew 15:33

Et dicunt ei discipuli : Unde ergo nobis in deserto panes tantos, ut saturemus turbam tantam ?

** Matthew 15:34

Et ait illis Jesus : Quot habetis panes ? At illi dixerunt : Septem, et paucos pisciculos.

** Matthew 15:35

Et præcepit turbæ ut discumberent super terram.

** Matthew 15:36

Et accipiens septem panes, et pisces, et gratias agens, fregit, et dedit discipulis suis, et discipuli dederunt populo.

** Matthew 15:37

Et comederunt omnes, et saturati sunt. Et quod superfuit de fragmentis, tulerunt septem sportas plenas.

** Matthew 15:38

Erant autem qui manducaverunt quatuor millia hominum, extra parvulos et mulieres.

** Matthew 15:39

Et, dimissa turba, ascendit in naviculam : et venit in fines Magedan.   

* Matthew 16

** Matthew 16:1

Et accesserunt ad eum pharisæi et sadducæi tentantes : et rogaverunt eum ut signum de cælo ostenderet eis.

** Matthew 16:2

At ille respondens, ait illis : Facto vespere dicitis : Serenum erit, rubicundum est enim cælum.

** Matthew 16:3

Et mane : Hodie tempestas, rutilat enim triste cælum.

** Matthew 16:4

Faciem ergo cæli dijudicare nostis : signa autem temporum non potestis scire ? Generatio mala et adultera signum quærit : et signum non dabitur ei, nisi signum Jonæ prophetæ. Et relictis illis, abiit.  

** Matthew 16:5

Et cum venissent discipuli ejus trans fretum, obliti sunt panes accipere.

** Matthew 16:6

Qui dixit illis : Intuemini, et cavete a fermento pharisæorum et sadducæorum.

** Matthew 16:7

At illi cogitabant intra se dicentes : Quia panes non accepimus.

** Matthew 16:8

Sciens autem Jesus, dixit : Quid cogitatis intra vos modicæ fidei, quia panes non habetis ?

** Matthew 16:9

Nondum intelligitis, neque recordamini quinque panum in quinque millia hominum, et quot cophinos sumpsistis ?

** Matthew 16:10

neque septem panum in quatuor millia hominum, et quot sportas sumpsistis ?

** Matthew 16:11

Quare non intelligitis, quia non de pane dixi vobis : Cavete a fermento pharisæorum et sadducæorum ?

** Matthew 16:12

Tunc intellexerunt quia non dixerit cavendum a fermento panum, sed a doctrina pharisæorum et sadducæorum.  

** Matthew 16:13

Venit autem Jesus in partes Cæsareæ Philippi : et interrogabat discipulos suos, dicens : Quem dicunt homines esse Filium hominis ?

** Matthew 16:14

At illi dixerunt : Alii Joannem Baptistam, alii autem Eliam, alii vero Jeremiam, aut unum ex prophetis.

** Matthew 16:15

Dicit illis Jesus : Vos autem, quem me esse dicitis ?

** Matthew 16:16

Respondens Simon Petrus dixit : Tu es Christus, Filius Dei vivi.

** Matthew 16:17

Respondens autem Jesus, dixit ei : Beatus es Simon Bar Jona : quia caro et sanguis non revelavit tibi, sed Pater meus, qui in cælis est.

** Matthew 16:18

Et ego dico tibi, quia tu es Petrus, et super hanc petram ædificabo Ecclesiam meam, et portæ inferi non prævalebunt adversus eam.

** Matthew 16:19

Et tibi dabo claves regni cælorum. Et quodcumque ligaveris super terram, erit ligatum et in cælis : et quodcumque solveris super terram, erit solutum et in cælis.

** Matthew 16:20

Tunc præcepit discipulis suis ut nemini dicerent quia ipse esset Jesus Christus.  

** Matthew 16:21

Exinde cœpit Jesus ostendere discipulis suis, quia oporteret eum ire Jerosolymam, et multa pati a senioribus, et scribis, et principibus sacerdotum, et occidi, et tertia die resurgere.

** Matthew 16:22

Et assumens eum Petrus, cœpit increpare illum dicens : Absit a te, Domine : non erit tibi hoc.

** Matthew 16:23

Qui conversus, dixit Petro : Vade post me Satana, scandalum es mihi : quia non sapis ea quæ Dei sunt, sed ea quæ hominum.

** Matthew 16:24

Tunc Jesus dixit discipulis suis : Si quis vult post me venire, abneget semetipsum, et tollat crucem suam, et sequatur me.

** Matthew 16:25

Qui enim voluerit animam suam salvam facere, perdet eam : qui autem perdiderit animam suam propter me, inveniet eam.

** Matthew 16:26

Quid enim prodest homini, si mundum universum lucretur, animæ vero suæ detrimentum patiatur ? aut quam dabit homo commutationem pro anima sua ?

** Matthew 16:27

Filius enim hominis venturus est in gloria Patris sui cum angelis suis : et tunc reddet unicuique secundum opera ejus.

** Matthew 16:28

Amen dico vobis, sunt quidam de hic stantibus, qui non gustabunt mortem, donec videant Filium hominis venientem in regno suo.   

* Matthew 17

** Matthew 17:1

Et post dies sex assumit Jesus Petrum, et Jacobum, et Joannem fratrem ejus, et ducit illos in montem excelsum seorsum :

** Matthew 17:2

et transfiguratus est ante eos. Et resplenduit facies ejus sicut sol : vestimenta autem ejus facta sunt alba sicut nix.

** Matthew 17:3

Et ecce apparuerunt illis Moyses et Elias cum eo loquentes.

** Matthew 17:4

Respondens autem Petrus, dixit ad Jesum : Domine, bonum est nos hic esse : si vis, faciamus tria tabernacula, tibi unum, Moysi unum, et Eliæ unum.

** Matthew 17:5

Adhuc eo loquente, ecce nubes lucida obumbravit eos. Et ecce vox de nube, dicens : Hic est Filius meus dilectus, in quo mihi bene complacui : ipsum audite.

** Matthew 17:6

Et audientes discipuli ceciderunt in faciem suam, et timuerunt valde.

** Matthew 17:7

Et accessit Jesus, et tetigit eos : dixitque eis : Surgite, et nolite timere.

** Matthew 17:8

Levantes autem oculos suos, neminem viderunt, nisi solum Jesum.

** Matthew 17:9

Et descendentibus illis de monte, præcepit eis Jesus, dicens : Nemini dixeritis visionem, donec Filius hominis a mortuis resurgat.

** Matthew 17:10

Et interrogaverunt eum discipuli, dicentes : Quid ergo scribæ dicunt, quod Eliam oporteat primum venire ?

** Matthew 17:11

At ille respondens, ait eis : Elias quidem venturus est, et restituet omnia.

** Matthew 17:12

Dico autem vobis, quia Elias jam venit, et non cognoverunt eum, sed fecerunt in eo quæcumque voluerunt. Sic et Filius hominis passurus est ab eis.

** Matthew 17:13

Tunc intellexerunt discipuli, quia de Joanne Baptista dixisset eis.  

** Matthew 17:14

Et cum venisset ad turbam, accessit ad eum homo genibus provolutus ante eum, dicens : Domine, miserere filio meo, quia lunaticus est, et male patitur : nam sæpe cadit in ignem, et crebro in aquam.

** Matthew 17:15

Et obtuli eum discipulis tuis, et non potuerunt curare eum.

** Matthew 17:16

Respondens autem Jesus, ait : O generatio incredula, et perversa, quousque ero vobiscum ? usquequo patiar vos ? Afferte huc illum ad me.

** Matthew 17:17

Et increpavit illum Jesus, et exiit ab eo dæmonium, et curatus est puer ex illa hora.

** Matthew 17:18

Tunc accesserunt discipuli ad Jesum secreto, et dixerunt : Quare nos non potuimus ejicere illum ?

** Matthew 17:19

Dixit illis Jesus : Propter incredulitatem vestram. Amen quippe dico vobis, si habueritis fidem sicut granum sinapis, dicetis monti huic : Transi hinc illuc, et transibit, et nihil impossibile erit vobis.

** Matthew 17:20

Hoc autem genus non ejicitur nisi per orationem et jejunium.  

** Matthew 17:21

Conversantibus autem eis in Galilæa, dixit illis Jesus : Filius hominis tradendus est in manus hominum :

** Matthew 17:22

et occident eum, et tertia die resurget. Et contristati sunt vehementer.  

** Matthew 17:23

Et cum venissent Capharnaum, accesserunt qui didrachma accipiebant ad Petrum, et dixerunt ei : Magister vester non solvit didrachma ?

** Matthew 17:24

Ait : Etiam. Et cum intrasset in domum, prævenit eum Jesus, dicens : Quid tibi videtur Simon ? reges terræ a quibus accipiunt tributum vel censum ? a filiis suis, an ab alienis ?

** Matthew 17:25

Et ille dixit : Ab alienis. Dixit illi Jesus : Ergo liberi sunt filii.

** Matthew 17:26

Ut autem non scandalizemus eos, vade ad mare, et mitte hamum : et eum piscem, qui primus ascenderit, tolle : et aperto ore ejus, invenies staterem : illum sumens, da eis pro me et te.   

* Matthew 18

** Matthew 18:1

In illa hora accesserunt discipuli ad Jesum, dicentes : Quis, putas, major est in regno cælorum ?

** Matthew 18:2

Et advocans Jesus parvulum, statuit eum in medio eorum,

** Matthew 18:3

et dixit : Amen dico vobis, nisi conversi fueritis, et efficiamini sicut parvuli, non intrabitis in regnum cælorum.

** Matthew 18:4

Quicumque ergo humiliaverit se sicut parvulus iste, hic est major in regno cælorum.

** Matthew 18:5

Et qui susceperit unum parvulum talem in nomine meo, me suscipit :

** Matthew 18:6

qui autem scandalizaverit unum de pusillis istis, qui in me credunt, expedit ei ut suspendatur mola asinaria in collo ejus, et demergatur in profundum maris.

** Matthew 18:7

Væ mundo a scandalis ! Necesse est enim ut veniant scandala : verumtamen væ homini illi, per quem scandalum venit.

** Matthew 18:8

Si autem manus tua, vel pes tuus scandalizat te, abscide eum, et projice abs te : bonum tibi est ad vitam ingredi debilem, vel claudum, quam duas manus vel duos pedes habentem mitti in ignem æternum.

** Matthew 18:9

Et si oculus tuus scandalizat te, erue eum, et projice abs te : bonum tibi est cum uno oculo in vitam intrare, quam duos oculos habentem mitti in gehennam ignis.

** Matthew 18:10

Videte ne contemnatis unum ex his pusillis : dico enim vobis, quia angeli eorum in cælis semper vident faciem Patris mei, qui in cælis est.

** Matthew 18:11

Venit enim Filius hominis salvare quod perierat.

** Matthew 18:12

Quid vobis videtur ? si fuerint alicui centum oves, et erravit una ex eis : nonne relinquit nonaginta novem in montibus, et vadit quærere eam quæ erravit ?

** Matthew 18:13

Et si contigerit ut inveniat eam : amen dico vobis, quia gaudet super eam magis quam super nonaginta novem, quæ non erraverunt.

** Matthew 18:14

Sic non est voluntas ante Patrem vestrum, qui in cælis est, ut pereat unus de pusillis istis.  

** Matthew 18:15

Si autem peccaverit in te frater tuus, vade, et corripe eum inter te, et ipsum solum : si te audierit, lucratus eris fratrem tuum.

** Matthew 18:16

Si autem te non audierit, adhibe tecum adhuc unum, vel duos, ut in ore duorum, vel trium testium stet omne verbum.

** Matthew 18:17

Quod si non audierit eos : dic ecclesiæ. Si autem ecclesiam non audierit, sit tibi sicut ethnicus et publicanus.

** Matthew 18:18

Amen dico vobis, quæcumque alligaveritis super terram, erunt ligata et in cælo : et quæcumque solveritis super terram, erunt soluta et in cælo.

** Matthew 18:19

Iterum dico vobis, quia si duo ex vobis consenserint super terram, de omni re quamcumque petierint, fiet illis a Patre meo, qui in cælis est.

** Matthew 18:20

Ubi enim sunt duo vel tres congregati in nomine meo, ibi sum in medio eorum.  

** Matthew 18:21

Tunc accedens Petrus ad eum, dixit : Domine, quoties peccabit in me frater meus, et dimittam ei ? usque septies ?

** Matthew 18:22

Dicit illi Jesus : Non dico tibi usque septies : sed usque septuagies septies.

** Matthew 18:23

Ideo assimilatum est regnum cælorum homini regi, qui voluit rationem ponere cum servis suis.

** Matthew 18:24

Et cum cœpisset rationem ponere, oblatus est ei unus, qui debebat ei decem millia talenta.

** Matthew 18:25

Cum autem non haberet unde redderet, jussit eum dominus ejus venundari, et uxorem ejus, et filios, et omnia quæ habebat, et reddi.

** Matthew 18:26

Procidens autem servus ille, orabat eum, dicens : Patientiam habe in me, et omnia reddam tibi.

** Matthew 18:27

Misertus autem dominus servi illius, dimisit eum, et debitum dimisit ei.

** Matthew 18:28

Egressus autem servus ille invenit unum de conservis suis, qui debebat ei centum denarios : et tenens suffocavit eum, dicens : Redde quod debes.

** Matthew 18:29

Et procidens conservus ejus, rogabat eum, dicens : Patientiam habe in me, et omnia reddam tibi.

** Matthew 18:30

Ille autem noluit : sed abiit, et misit eum in carcerem donec redderet debitum.

** Matthew 18:31

Videntes autem conservi ejus quæ fiebant, contristati sunt valde : et venerunt, et narraverunt domino suo omnia quæ facta fuerant.

** Matthew 18:32

Tunc vocavit illum dominus suus : et ait illi : Serve nequam, omne debitum dimisi tibi quoniam rogasti me :

** Matthew 18:33

nonne ergo oportuit et te misereri conservi tui, sicut et ego tui misertus sum ?

** Matthew 18:34

Et iratus dominus ejus tradidit eum tortoribus, quoadusque redderet universum debitum.

** Matthew 18:35

Sic et Pater meus cælestis faciet vobis, si non remiseritis unusquisque fratri suo de cordibus vestris.   

* Matthew 19

** Matthew 19:1

Et factum est, cum consummasset Jesus sermones istos, migravit a Galilæa, et venit in fines Judææ trans Jordanem,

** Matthew 19:2

et secutæ sunt eum turbæ multæ, et curavit eos ibi.

** Matthew 19:3

Et accesserunt ad eum pharisæi tentantes eum, et dicentes : Si licet homini dimittere uxorem suam, quacumque ex causa ?

** Matthew 19:4

Qui respondens, ait eis : Non legistis, quia qui fecit hominem ab initio, masculum et feminam fecit eos ? Et dixit :

** Matthew 19:5

Propter hoc dimittet homo patrem, et matrem, et adhærebit uxori suæ, et erunt duo in carne una.

** Matthew 19:6

Itaque jam non sunt duo, sed una caro. Quod ergo Deus conjunxit, homo non separet.

** Matthew 19:7

Dicunt illi : Quid ergo Moyses mandavit dare libellum repudii, et dimittere ?

** Matthew 19:8

Ait illis : Quoniam Moyses ad duritiam cordis vestri permisit vobis dimittere uxores vestras : ab initio autem non fuit sic.

** Matthew 19:9

Dico autem vobis, quia quicumque dimiserit uxorem suam, nisi ob fornicationem, et aliam duxerit, mœchatur : et qui dimissam duxerit, mœchatur.

** Matthew 19:10

Dicunt ei discipuli ejus : Si ita est causa hominis cum uxore, non expedit nubere.

** Matthew 19:11

Qui dixit illis : Non omnes capiunt verbum istud, sed quibus datum est.

** Matthew 19:12

Sunt enim eunuchi, qui de matris utero sic nati sunt : et sunt eunuchi, qui facti sunt ab hominibus : et sunt eunuchi, qui seipsos castraverunt propter regnum cælorum. Qui potest capere capiat.  

** Matthew 19:13

Tunc oblati sunt ei parvuli, ut manus eis imponeret, et oraret. Discipuli autem increpabant eos.

** Matthew 19:14

Jesus vero ait eis : Sinite parvulos, et nolite eos prohibere ad me venire : talium est enim regnum cælorum.

** Matthew 19:15

Et cum imposuisset eis manus, abiit inde.  

** Matthew 19:16

Et ecce unus accedens, ait illi : Magister bone, quid boni faciam ut habeam vitam æternam ?

** Matthew 19:17

Qui dixit ei : Quid me interrogas de bono ? Unus est bonus, Deus. Si autem vis ad vitam ingredi, serva mandata.

** Matthew 19:18

Dicit illi : Quæ ? Jesus autem dixit : Non homicidium facies ; non adulterabis ; non facies furtum ; non falsum testimonium dices ;

** Matthew 19:19

honora patrem tuum, et matrem tuam, et diliges proximum tuum sicut teipsum.

** Matthew 19:20

Dicit illi adolescens : Omnia hæc custodivi a juventute mea : quid adhuc mihi deest ?

** Matthew 19:21

Ait illi Jesus : Si vis perfectus esse, vade, vende quæ habes, et da pauperibus, et habebis thesaurum in cælo : et veni, sequere me.

** Matthew 19:22

Cum audisset autem adolescens verbum, abiit tristis : erat enim habens multas possessiones.

** Matthew 19:23

Jesus autem dixit discipulis suis : Amen dico vobis, quia dives difficile intrabit in regnum cælorum.

** Matthew 19:24

Et iterum dico vobis : Facilius est camelum per foramen acus transire, quam divitem intrare in regnum cælorum.

** Matthew 19:25

Auditis autem his, discipuli mirabantur valde, dicentes : Quis ergo poterit salvus esse ?

** Matthew 19:26

Aspiciens autem Jesus, dixit illis : Apud homines hoc impossibile est : apud Deum autem omnia possibilia sunt.  

** Matthew 19:27

Tunc respondens Petrus, dixit ei : Ecce nos reliquimus omnia, et secuti sumus te : quid ergo erit nobis ?

** Matthew 19:28

Jesus autem dixit illis : Amen dico vobis, quod vos, qui secuti estis me, in regeneratione cum sederit Filius hominis in sede majestatis suæ, sedebitis et vos super sedes duodecim, judicantes duodecim tribus Israël.

** Matthew 19:29

Et omnis qui reliquerit domum, vel fratres, aut sorores, aut patrem, aut matrem, aut uxorem, aut filios, aut agros propter nomen meum, centuplum accipiet, et vitam æternam possidebit.

** Matthew 19:30

Multi autem erunt primi novissimi, et novissimi primi.   

* Matthew 20

** Matthew 20:1

Simile est regnum cælorum homini patrifamilias, qui exiit primo mane conducere operarios in vineam suam.

** Matthew 20:2

Conventione autem facta cum operariis ex denario diurno, misit eos in vineam suam.

** Matthew 20:3

Et egressus circa horam tertiam, vidit alios stantes in foro otiosos,

** Matthew 20:4

et dixit illis : Ite et vos in vineam meam, et quod justum fuerit dabo vobis.

** Matthew 20:5

Illi autem abierunt. Iterum autem exiit circa sextam et nonam horam : et fecit similiter.

** Matthew 20:6

Circa undecimam vero exiit, et invenit alios stantes, et dicit illis : Quid hic statis tota die otiosi ?

** Matthew 20:7

Dicunt ei : Quia nemo nos conduxit. Dicit illis : Ite et vos in vineam meam.

** Matthew 20:8

Cum sero autem factum esset, dicit dominus vineæ procuratori suo : Voca operarios, et redde illis mercedem incipiens a novissimis usque ad primos.

** Matthew 20:9

Cum venissent ergo qui circa undecimam horam venerant, acceperunt singulos denarios.

** Matthew 20:10

Venientes autem et primi, arbitrati sunt quod plus essent accepturi : acceperunt autem et ipsi singulos denarios.

** Matthew 20:11

Et accipientes murmurabant adversus patremfamilias,

** Matthew 20:12

dicentes : Hi novissimi una hora fecerunt, et pares illos nobis fecisti, qui portavimus pondus diei, et æstus.

** Matthew 20:13

At ille respondens uni eorum, dixit : Amice, non facio tibi injuriam : nonne ex denario convenisti mecum ?

** Matthew 20:14

Tolle quod tuum est, et vade : volo autem et huic novissimo dare sicut et tibi.

** Matthew 20:15

Aut non licet mihi quod volo, facere ? an oculus tuus nequam est, quia ego bonus sum ?

** Matthew 20:16

Sic erunt novissimi primi, et primi novissimi. Multi enim sunt vocati, pauci vero electi.  

** Matthew 20:17

Et ascendens Jesus Jerosolymam, assumpsit duodecim discipulos secreto, et ait illis :

** Matthew 20:18

Ecce ascendimus Jerosolymam, et Filius hominis tradetur principibus sacerdotum, et scribis, et condemnabunt eum morte,

** Matthew 20:19

et tradent eum gentibus ad illudendum, et flagellandum, et crucifigendum, et tertia die resurget.  

** Matthew 20:20

Tunc accessit ad eum mater filiorum Zebedæi cum filiis suis, adorans et petens aliquid ab eo.

** Matthew 20:21

Qui dixit ei : Quid vis ? Ait illi : Dic ut sedeant hi duo filii mei, unus ad dexteram tuam, et unus ad sinistram in regno tuo.

** Matthew 20:22

Respondens autem Jesus, dixit : Nescitis quid petatis. Potestis bibere calicem, quem ego bibiturus sum ? Dicunt ei : Possumus.

** Matthew 20:23

Ait illis : Calicem quidem meum bibetis : sedere autem ad dexteram meam vel sinistram non est meum dare vobis, sed quibus paratum est a Patre meo.

** Matthew 20:24

Et audientes decem, indignati sunt de duobus fratribus.

** Matthew 20:25

Jesus autem vocavit eos ad se, et ait : Scitis quia principes gentium dominantur eorum : et qui majores sunt, potestatem exercent in eos.

** Matthew 20:26

Non ita erit inter vos : sed quicumque voluerit inter vos major fieri, sit vester minister :

** Matthew 20:27

et qui voluerit inter vos primus esse, erit vester servus.

** Matthew 20:28

Sicut Filius hominis non venit ministrari, sed ministrare, et dare animam suam redemptionem pro multis.  

** Matthew 20:29

Et egredientibus illis ab Jericho, secuta est eum turba multa,

** Matthew 20:30

et ecce duo cæci sedentes secus viam audierunt quia Jesus transiret : et clamaverunt, dicentes : Domine, miserere nostri, fili David.

** Matthew 20:31

Turba autem increpabat eos ut tacerent. At illi magis clamabant, dicentes : Domine, miserere nostri, fili David.

** Matthew 20:32

Et stetit Jesus, et vocavit eos, et ait : Quid vultis ut faciam vobis ?

** Matthew 20:33

Dicunt illi : Domine, ut aperiantur oculi nostri.

** Matthew 20:34

Misertus autem eorum Jesus, tetigit oculos eorum. Et confestim viderunt, et secuti sunt eum.   

* Matthew 21

** Matthew 21:1

Et cum appropinquassent Jerosolymis, et venissent Bethphage ad montem Oliveti : tunc Jesus misit duos discipulos,

** Matthew 21:2

dicens eis : Ite in castellum, quod contra vos est, et statim invenietis asinam alligatam, et pullum cum ea : solvite, et adducite mihi :

** Matthew 21:3

et si quis vobis aliquid dixerit, dicite quia Dominus his opus habet : et confestim dimittet eos.

** Matthew 21:4

Hoc autem totum factum est, ut adimpleretur quod dictum est per prophetam dicentem :  

** Matthew 21:5

Dicite filiæ Sion :  Ecce rex tuus venit tibi  mansuetus, sedens super asinam,  et pullum filium subjugalis.

** Matthew 21:6

Euntes autem discipuli fecerunt sicut præcepit illis Jesus.

** Matthew 21:7

Et adduxerunt asinam, et pullum : et imposuerunt super eos vestimenta sua, et eum desuper sedere fecerunt.

** Matthew 21:8

Plurima autem turba straverunt vestimenta sua in via : alii autem cædebant ramos de arboribus, et sternebant in via :

** Matthew 21:9

turbæ autem, quæ præcedebant, et quæ sequebantur, clamabant, dicentes : Hosanna filio David : benedictus, qui venit in nomine Domini : hosanna in altissimis.

** Matthew 21:10

Et cum intrasset Jerosolymam, commota est universa civitas, dicens : Quis est hic ?

** Matthew 21:11

Populi autem dicebant : Hic est Jesus propheta a Nazareth Galilææ.

** Matthew 21:12

Et intravit Jesus in templum Dei, et ejiciebat omnes vendentes et ementes in templo, et mensas numulariorum, et cathedras vendentium columbas evertit :

** Matthew 21:13

et dicit eis : Scriptum est : Domus mea domus orationis vocabitur : vos autem fecistis illam speluncam latronum.

** Matthew 21:14

Et accesserunt ad eum cæci, et claudi in templo : et sanavit eos.

** Matthew 21:15

Videntes autem principes sacerdotum et scribæ mirabilia quæ fecit, et pueros clamantes in templo, et dicentes : Hosanna filio David : indignati sunt,

** Matthew 21:16

et dixerunt ei : Audis quid isti dicunt ? Jesus autem dixit eis : Utique. Numquam legistis : Quia ex ore infantium et lactentium perfecisti laudem ?

** Matthew 21:17

Et relictis illis, abiit foras extra civitatem in Bethaniam : ibique mansit.  

** Matthew 21:18

Mane autem revertens in civitatem, esuriit.

** Matthew 21:19

Et videns fici arborem unam secus viam, venit ad eam : et nihil invenit in ea nisi folia tantum, et ait illi : Numquam ex te fructus nascatur in sempiternum. Et arefacta est continuo ficulnea.

** Matthew 21:20

Et videntes discipuli, mirati sunt, dicentes : Quomodo continuo aruit ?

** Matthew 21:21

Respondens autem Jesus, ait eis : Amen dico vobis, si habueritis fidem, et non hæsitaveritis, non solum de ficulnea facietis, sed et si monti huic dixeritis : Tolle, et jacta te in mare, fiet.

** Matthew 21:22

Et omnia quæcumque petieritis in oratione credentes, accipietis.  

** Matthew 21:23

Et cum venisset in templum, accesserunt ad eum docentem principes sacerdotum, et seniores populi, dicentes : In qua potestate hæc facis ? et quis tibi dedit hanc potestatem ?

** Matthew 21:24

Respondens Jesus dixit eis : Interrogabo vos et ego unum sermonem : quem si dixeritis mihi, et ego vobis dicam in qua potestate hæc facio.

** Matthew 21:25

Baptismus Joannis unde erat ? e cælo, an ex hominibus ? At illi cogitabant inter se, dicentes :

** Matthew 21:26

Si dixerimus, e cælo, dicet nobis : Quare ergo non credidistis illi ? Si autem dixerimus, ex hominibus, timemus turbam : omnes enim habebant Joannem sicut prophetam.

** Matthew 21:27

Et respondentes Jesu, dixerunt : Nescimus. Ait illis et ipse : Nec ego dico vobis in qua potestate hæc facio.  

** Matthew 21:28

Quid autem vobis videtur ? Homo quidam habebat duos filios, et accedens ad primum, dixit : Fili, vade hodie, operare in vinea mea.

** Matthew 21:29

Ille autem respondens, ait : Nolo. Postea autem, pœnitentia motus, abiit.

** Matthew 21:30

Accedens autem ad alterum, dixit similiter. At ille respondens, ait : Eo, domine, et non ivit :

** Matthew 21:31

quis ex duobus fecit voluntatem patris ? Dicunt ei : Primus. Dicit illis Jesus : Amen dico vobis, quia publicani et meretrices præcedent vos in regnum Dei.

** Matthew 21:32

Venit enim ad vos Joannes in via justitiæ, et non credidistis ei : publicani autem et meretrices crediderunt ei : vos autem videntes nec pœnitentiam habuistis postea, ut crederetis ei.  

** Matthew 21:33

Aliam parabolam audite : Homo erat paterfamilias, qui plantavit vineam, et sepem circumdedit ei, et fodit in ea torcular, et ædificavit turrim, et locavit eam agricolis, et peregre profectus est.

** Matthew 21:34

Cum autem tempus fructuum appropinquasset, misit servos suos ad agricolas, ut acciperent fructus ejus.

** Matthew 21:35

Et agricolæ, apprehensis servis ejus, alium ceciderunt, alium occiderunt, alium vero lapidaverunt.

** Matthew 21:36

Iterum misit alios servos plures prioribus, et fecerunt illis similiter.

** Matthew 21:37

Novissime autem misit ad eos filium suum, dicens : Verebuntur filium meum.

** Matthew 21:38

Agricolæ autem videntes filium dixerunt intra se : Hic est hæres, venite, occidamus eum, et habebimus hæreditatem ejus.

** Matthew 21:39

Et apprehensum eum ejecerunt extra vineam, et occiderunt.

** Matthew 21:40

Cum ergo venerit dominus vineæ, quid faciet agricolis illis ?

** Matthew 21:41

Aiunt illi : Malos male perdet : et vineam suam locabit aliis agricolis, qui reddant ei fructum temporibus suis.

** Matthew 21:42

Dicit illis Jesus : Numquam legistis in Scripturis :   Lapidem quem reprobaverunt ædificantes,  hic factus est in caput anguli :  a Domino factum est istud,  et est mirabile in oculis nostris ?

** Matthew 21:43

Ideo dico vobis, quia auferetur a vobis regnum Dei, et dabitur genti facienti fructus ejus.

** Matthew 21:44

Et qui ceciderit super lapidem istum, confringetur : super quem vero ceciderit, conteret eum.

** Matthew 21:45

Et cum audissent principes sacerdotum et pharisæi parabolas ejus, cognoverunt quod de ipsis diceret.

** Matthew 21:46

Et quærentes eum tenere, timuerunt turbas : quoniam sicut prophetam eum habebant.  

* Matthew 22

** Matthew 22:1

Et respondens Jesus, dixit iterum in parabolis eis, dicens :

** Matthew 22:2

Simile factum est regnum cælorum homini regi, qui fecit nuptias filio suo.

** Matthew 22:3

Et misit servos suos vocare invitatos ad nuptias, et nolebant venire.

** Matthew 22:4

Iterum misit alios servos, dicens : Dicite invitatis : Ecce prandium meum paravi, tauri mei et altilia occisa sunt, et omnia parata : venite ad nuptias.

** Matthew 22:5

Illi autem neglexerunt : et abierunt, alius in villam suam, alius vero ad negotiationem suam :

** Matthew 22:6

reliqui vero tenuerunt servos ejus, et contumeliis affectos occiderunt.

** Matthew 22:7

Rex autem cum audisset, iratus est : et missis exercitibus suis, perdidit homicidas illos, et civitatem illorum succendit.

** Matthew 22:8

Tunc ait servis suis : Nuptiæ quidem paratæ sunt, sed qui invitati erant, non fuerunt digni :

** Matthew 22:9

ite ergo ad exitus viarum, et quoscumque inveneritis, vocate ad nuptias.

** Matthew 22:10

Et egressi servi ejus in vias, congregaverunt omnes quos invenerunt, malos et bonos : et impletæ sunt nuptiæ discumbentium.

** Matthew 22:11

Intravit autem rex ut videret discumbentes, et vidit ibi hominem non vestitum veste nuptiali.

** Matthew 22:12

Et ait illi : Amice, quomodo huc intrasti non habens vestem nuptialem ? At ille obmutuit.

** Matthew 22:13

Tunc dicit rex ministris : Ligatis manibus et pedibus ejus, mittite eum in tenebras exteriores : ibi erit fletus et stridor dentium.

** Matthew 22:14

Multi enim sunt vocati, pauci vero electi.  

** Matthew 22:15

Tunc abeuntes pharisæi, consilium inierunt ut caperent eum in sermone.

** Matthew 22:16

Et mittunt ei discipulos suos cum Herodianis, dicentes : Magister, scimus quia verax es, et viam Dei in veritate doces, et non est tibi cura de aliquo : non enim respicis personam hominum :

** Matthew 22:17

dic ergo nobis quid tibi videtur, licet censum dare Cæsari, an non ?

** Matthew 22:18

Cognita autem Jesus nequitia eorum, ait : Quid me tentatis, hypocritæ ?

** Matthew 22:19

ostendite mihi numisma census. At illi obtulerunt ei denarium.

** Matthew 22:20

Et ait illis Jesus : Cujus est imago hæc, et superscriptio ?

** Matthew 22:21

Dicunt ei : Cæsaris. Tunc ait illis : Reddite ergo quæ sunt Cæsaris, Cæsari : et quæ sunt Dei, Deo.

** Matthew 22:22

Et audientes mirati sunt, et relicto eo abierunt.  

** Matthew 22:23

In illo die accesserunt ad eum sadducæi, qui dicunt non esse resurrectionem : et interrogaverunt eum,

** Matthew 22:24

dicentes : Magister, Moyses dixit : Si quis mortuus fuerit non habens filium, ut ducat frater ejus uxorem illius, et suscitet semen fratri suo.

** Matthew 22:25

Erant autem apud nos septem fratres : et primus, uxore ducta, defunctus est : et non habens semen, reliquit uxorem suam fratri suo.

** Matthew 22:26

Similiter secundus, et tertius usque ad septimum.

** Matthew 22:27

Novissime autem omnium et mulier defuncta est.

** Matthew 22:28

In resurrectione ergo cujus erit de septem uxor ? omnes enim habuerunt eam.

** Matthew 22:29

Respondens autem Jesus, ait illis : Erratis nescientes Scripturas, neque virtutem Dei.

** Matthew 22:30

In resurrectione enim neque nubent, neque nubentur : sed erunt sicut angeli Dei in cælo.

** Matthew 22:31

De resurrectione autem mortuorum non legistis quod dictum est a Deo dicente vobis :

** Matthew 22:32

Ego sum Deus Abraham, et Deus Isaac, et Deus Jacob ? Non est Deus mortuorum, sed viventium.

** Matthew 22:33

Et audientes turbæ, mirabantur in doctrina ejus.  

** Matthew 22:34

Pharisæi autem audientes quod silentium imposuisset sadducæis, convenerunt in unum :

** Matthew 22:35

et interrogavit eum unus ex eis legis doctor, tentans eum :

** Matthew 22:36

Magister, quod est mandatum magnum in lege ?

** Matthew 22:37

Ait illi Jesus : Diliges Dominum Deum tuum ex toto corde tuo, et in tota anima tua, et in tota mente tua.

** Matthew 22:38

Hoc est maximum, et primum mandatum.

** Matthew 22:39

Secundum autem simile est huic : Diliges proximum tuum, sicut teipsum.

** Matthew 22:40

In his duobus mandatis universa lex pendet, et prophetæ.  

** Matthew 22:41

Congregatis autem pharisæis, interrogavit eos Jesus,

** Matthew 22:42

dicens : Quid vobis videtur de Christo ? cujus filius est ? Dicunt ei : David.

** Matthew 22:43

Ait illis : Quomodo ergo David in spiritu vocat eum Dominum, dicens :

** Matthew 22:44

Dixit Dominus Domino meo : Sede a dextris meis, donec ponam inimicos tuos scabellum pedum tuorum ?

** Matthew 22:45

Si ergo David vocat eum Dominum, quomodo filius ejus est ?

** Matthew 22:46

Et nemo poterat ei respondere verbum : neque ausus fuit quisquam ex illa die eum amplius interrogare.   

* Matthew 23

** Matthew 23:1

Tunc Jesus locutus est ad turbas, et ad discipulos suos,

** Matthew 23:2

dicens : Super cathedram Moysi sederunt scribæ et pharisæi.

** Matthew 23:3

Omnia ergo quæcumque dixerint vobis, servate, et facite : secundum opera vero eorum nolite facere : dicunt enim, et non faciunt.

** Matthew 23:4

Alligant enim onera gravia, et importabilia, et imponunt in humeros hominum : digito autem suo nolunt ea movere.

** Matthew 23:5

Omnia vero opera sua faciunt ut videantur ab hominibus : dilatant enim phylacteria sua, et magnificant fimbrias.

** Matthew 23:6

Amant autem primos recubitus in cœnis, et primas cathedras in synagogis,

** Matthew 23:7

et salutationes in foro, et vocari ab hominibus Rabbi.

** Matthew 23:8

Vos autem nolite vocari Rabbi : unus est enim magister vester, omnes autem vos fratres estis.

** Matthew 23:9

Et patrem nolite vocare vobis super terram : unus est enim pater vester qui in cælis est.

** Matthew 23:10

Nec vocemini magistri : quia magister vester unus est, Christus.

** Matthew 23:11

Qui major est vestrum, erit minister vester.

** Matthew 23:12

Qui autem se exaltaverit, humiliabitur : et qui se humiliaverit, exaltabitur.  

** Matthew 23:13

Væ autem vobis scribæ et pharisæi hypocritæ, quia clauditis regnum cælorum ante homines ! vos enim non intratis, nec introëuntes sinitis intrare.

** Matthew 23:14

Væ vobis scribæ et pharisæi hypocritæ, quia comeditis domos viduarum, orationes longas orantes ! propter hoc amplius accipietis judicium.

** Matthew 23:15

Væ vobis scribæ et pharisæi hypocritæ, quia circuitis mare, et aridam, ut faciatis unum proselytum, et cum fuerit factus, facitis eum filium gehennæ duplo quam vos.

** Matthew 23:16

Væ vobis duces cæci, qui dicitis : Quicumque juraverit per templum, nihil est : qui autem juraverit in auro templi, debet.

** Matthew 23:17

Stulti et cæci : quid enim majus est ? aurum, an templum, quod sanctificat aurum ?

** Matthew 23:18

Et quicumque juraverit in altari, nihil est : quicumque autem juraverit in dono, quod est super illud, debet.

** Matthew 23:19

Cæci : quid enim majus est, donum, an altare, quod sanctificat donum ?

** Matthew 23:20

Qui ergo jurat in altari, jurat in eo, et in omnibus quæ super illud sunt.

** Matthew 23:21

Et quicumque juraverit in templo, jurat in illo, et in eo qui habitat in ipso :

** Matthew 23:22

et qui jurat in cælo, jurat in throno Dei, et in eo qui sedet super eum.

** Matthew 23:23

Væ vobis scribæ et pharisæi hypocritæ, qui decimatis mentham, et anethum, et cyminum, et reliquistis quæ graviora sunt legis, judicium, et misericordiam, et fidem ! hæc oportuit facere, et illa non omittere.

** Matthew 23:24

Duces cæci, excolantes culicem, camelum autem glutientes.

** Matthew 23:25

Væ vobis scribæ et pharisæi hypocritæ, quia mundatis quod deforis est calicis et paropsidis ; intus autem pleni estis rapina et immunditia !

** Matthew 23:26

Pharisæe cæce, munda prius quod intus est calicis, et paropsidis, ut fiat id, quod deforis est, mundum.

** Matthew 23:27

Væ vobis scribæ et pharisæi hypocritæ, quia similes estis sepulchris dealbatis, quæ a foris parent hominibus speciosa, intus vero pleni sunt ossibus mortuorum, et omni spurcitia !

** Matthew 23:28

Sic et vos a foris quidem paretis hominibus justi : intus autem pleni estis hypocrisi et iniquitate.

** Matthew 23:29

Væ vobis scribæ et pharisæi hypocritæ, qui ædificatis sepulchra prophetarum, et ornatis monumenta justorum,

** Matthew 23:30

et dicitis : Si fuissemus in diebus patrum nostrorum, non essemus socii eorum in sanguine prophetarum !

** Matthew 23:31

itaque testimonio estis vobismetipsis, quia filii estis eorum, qui prophetas occiderunt.

** Matthew 23:32

Et vos implete mensuram patrum vestrorum.

** Matthew 23:33

Serpentes, genimina viperarum, quomodo fugietis a judicio gehennæ ?  

** Matthew 23:34

Ideo ecce ego mitto ad vos prophetas, et sapientes, et scribas, et ex illis occidetis, et crucifigetis, et ex eis flagellabitis in synagogis vestris, et persequemini de civitate in civitatem :

** Matthew 23:35

ut veniat super vos omnis sanguis justus, qui effusus est super terram, a sanguine Abel justi usque ad sanguinem Zachariæ, filii Barachiæ, quem occidistis inter templum et altare.

** Matthew 23:36

Amen dico vobis, venient hæc omnia super generationem istam.

** Matthew 23:37

Jerusalem, Jerusalem, quæ occidis prophetas, et lapidas eos, qui ad te missi sunt, quoties volui congregare filios tuos, quemadmodum gallina congregat pullos suos sub alas, et noluisti ?

** Matthew 23:38

Ecce relinquetur vobis domus vestra deserta.

** Matthew 23:39

Dico enim vobis, non me videbitis amodo, donec dicatis : Benedictus, qui venit in nomine Domini.   

* Matthew 24

** Matthew 24:1

Et egressus Jesus de templo, ibat. Et accesserunt discipuli ejus, ut ostenderent ei ædificationes templi.

** Matthew 24:2

Ipse autem respondens dixit illis : Videtis hæc omnia ? amen dico vobis, non relinquetur hic lapis super lapidem, qui non destruatur.  

** Matthew 24:3

Sedente autem eo super montem Oliveti, accesserunt ad eum discipuli secreto, dicentes : Dic nobis, quando hæc erunt ? et quod signum adventus tui, et consummationis sæculi ?

** Matthew 24:4

Et respondens Jesus, dixit eis : Videte ne quis vos seducat :

** Matthew 24:5

multi enim venient in nomine meo, dicentes : Ego sum Christus : et multos seducent.

** Matthew 24:6

Audituri enim estis prælia, et opiniones præliorum. Videte ne turbemini : oportet enim hæc fieri, sed nondum est finis :

** Matthew 24:7

consurget enim gens in gentem, et regnum in regnum, et erunt pestilentiæ, et fames, et terræmotus per loca :

** Matthew 24:8

hæc autem omnia initia sunt dolorum.  

** Matthew 24:9

Tunc tradent vos in tribulationem, et occident vos : et eritis odio omnibus gentibus propter nomen meum.

** Matthew 24:10

Et tunc scandalizabuntur multi, et invicem tradent, et odio habebunt invicem.

** Matthew 24:11

Et multi pseudoprophetæ surgent, et seducent multos.

** Matthew 24:12

Et quoniam abundavit iniquitas, refrigescet caritas multorum :

** Matthew 24:13

qui autem perseveraverit usque in finem, hic salvus erit.

** Matthew 24:14

Et prædicabitur hoc Evangelium regni in universo orbe, in testimonium omnibus gentibus : et tunc veniet consummatio.  

** Matthew 24:15

Cum ergo videritis abominationem desolationis, quæ dicta est a Daniele propheta, stantem in loco sancto, qui legit, intelligat :

** Matthew 24:16

tunc qui in Judæa sunt, fugiant ad montes :

** Matthew 24:17

et qui in tecto, non descendat tollere aliquid de domo sua :

** Matthew 24:18

et qui in agro, non revertatur tollere tunicam suam.

** Matthew 24:19

Væ autem prægnantibus et nutrientibus in illis diebus !  

** Matthew 24:20

Orate autem ut non fiat fuga vestra in hieme, vel sabbato :

** Matthew 24:21

erit enim tunc tribulatio magna, qualis non fuit ab initio mundi usque modo, neque fiet.

** Matthew 24:22

Et nisi breviati fuissent dies illi, non fieret salva omnis caro : sed propter electos breviabuntur dies illi.

** Matthew 24:23

Tunc si quis vobis dixerit : Ecce hic est Christus, aut illic : nolite credere.

** Matthew 24:24

Surgent enim pseudochristi, et pseudoprophetæ : et dabunt signa magna, et prodigia, ita ut in errorem inducantur (si fieri potest) etiam electi.

** Matthew 24:25

Ecce prædixi vobis.

** Matthew 24:26

Si ergo dixerint vobis : Ecce in deserto est, nolite exire ; Ecce in penetralibus, nolite credere.

** Matthew 24:27

Sicut enim fulgur exit ab oriente, et paret usque in occidentem : ita erit et adventus Filii hominis.

** Matthew 24:28

Ubicumque fuerit corpus, illic congregabuntur et aquilæ.  

** Matthew 24:29

Statim autem post tribulationem dierum illorum sol obscurabitur, et luna non dabit lumen suum, et stellæ cadent de cælo, et virtutes cælorum commovebuntur :

** Matthew 24:30

et tunc parebit signum Filii hominis in cælo : et tunc plangent omnes tribus terræ : et videbunt Filium hominis venientem in nubibus cæli cum virtute multa et majestate.

** Matthew 24:31

Et mittet angelos suos cum tuba, et voce magna : et congregabunt electos ejus a quatuor ventis, a summis cælorum usque ad terminos eorum.  

** Matthew 24:32

Ab arbore autem fici discite parabolam : cum jam ramus ejus tener fuerit, et folia nata, scitis quia prope est æstas :

** Matthew 24:33

ita et vos cum videritis hæc omnia, scitote quia prope est, in januis.

** Matthew 24:34

Amen dico vobis, quia non præteribit generatio hæc, donec omnia hæc fiant.

** Matthew 24:35

Cælum et terra transibunt, verba autem mea non præteribunt.  

** Matthew 24:36

De die autem illa et hora nemo scit, neque angeli cælorum, nisi solus Pater.

** Matthew 24:37

Sicut autem in diebus Noë, ita erit et adventus Filii hominis :

** Matthew 24:38

sicut enim erant in diebus ante diluvium comedentes et bibentes, nubentes et nuptum tradentes, usque ad eum diem, quo intravit Noë in arcam,

** Matthew 24:39

et non cognoverunt donec venit diluvium, et tulit omnes : ita erit et adventus Filii hominis.

** Matthew 24:40

Tunc duo erunt in agro : unus assumetur, et unus relinquetur.

** Matthew 24:41

Duæ molentes in mola : una assumetur, et una relinquetur.  

** Matthew 24:42

Vigilate ergo, quia nescitis qua hora Dominus vester venturus sit.

** Matthew 24:43

Illud autem scitote, quoniam si sciret paterfamilias qua hora fur venturus esset, vigilaret utique, et non sineret perfodi domum suam.

** Matthew 24:44

Ideo et vos estote parati : quia qua nescitis hora Filius hominis venturus est.

** Matthew 24:45

Quis, putas, est fidelis servus, et prudens, quem constituit dominus suus super familiam suam ut det illis cibum in tempore ?

** Matthew 24:46

Beatus ille servus, quem cum venerit dominus ejus, invenerit sic facientem.

** Matthew 24:47

Amen dico vobis, quoniam super omnia bona sua constituet eum.

** Matthew 24:48

Si autem dixerit malus servus ille in corde suo : Moram fecit dominus meus venire :

** Matthew 24:49

et cœperit percutere conservos suos, manducet autem et bibat cum ebriosis :

** Matthew 24:50

veniet dominus servi illius in die qua non sperat, et hora qua ignorat :

** Matthew 24:51

et dividet eum, partemque ejus ponet cum hypocritis : illic erit fletus et stridor dentium.   

* Matthew 25

** Matthew 25:1

Tunc simile erit regnum cælorum decem virginibus : quæ accipientes lampades suas exierunt obviam sponso et sponsæ.

** Matthew 25:2

Quinque autem ex eis erant fatuæ, et quinque prudentes :

** Matthew 25:3

sed quinque fatuæ, acceptis lampadibus, non sumpserunt oleum secum :

** Matthew 25:4

prudentes vero acceperunt oleum in vasis suis cum lampadibus.

** Matthew 25:5

Moram autem faciente sponso, dormitaverunt omnes et dormierunt.

** Matthew 25:6

Media autem nocte clamor factus est : Ecce sponsus venit, exite obviam ei.

** Matthew 25:7

Tunc surrexerunt omnes virgines illæ, et ornaverunt lampades suas.

** Matthew 25:8

Fatuæ autem sapientibus dixerunt : Date nobis de oleo vestro, quia lampades nostræ extinguuntur.

** Matthew 25:9

Responderunt prudentes, dicentes : Ne forte non sufficiat nobis, et vobis, ite potius ad vendentes, et emite vobis.

** Matthew 25:10

Dum autem irent emere, venit sponsus : et quæ paratæ erant, intraverunt cum eo ad nuptias, et clausa est janua.

** Matthew 25:11

Novissime vero veniunt et reliquæ virgines, dicentes : Domine, domine, aperi nobis.

** Matthew 25:12

At ille respondens, ait : Amen dico vobis, nescio vos.

** Matthew 25:13

Vigilate itaque, quia nescitis diem, neque horam.  

** Matthew 25:14

Sicut enim homo peregre proficiscens, vocavit servos suos, et tradidit illis bona sua.

** Matthew 25:15

Et uni dedit quinque talenta, alii autem duo, alii vero unum, unicuique secundum propriam virtutem : et profectus est statim.

** Matthew 25:16

Abiit autem qui quinque talenta acceperat, et operatus est in eis, et lucratus est alia quinque.

** Matthew 25:17

Similiter et qui duo acceperat, lucratus est alia duo.

** Matthew 25:18

Qui autem unum acceperat, abiens fodit in terram, et abscondit pecuniam domini sui.

** Matthew 25:19

Post multum vero temporis venit dominus servorum illorum, et posuit rationem cum eis.

** Matthew 25:20

Et accedens qui quinque talenta acceperat, obtulit alia quinque talenta, dicens : Domine, quinque talenta tradidisti mihi, ecce alia quinque superlucratus sum.

** Matthew 25:21

Ait illi dominus ejus : Euge serve bone, et fidelis : quia super pauca fuisti fidelis, super multa te constituam ; intra in gaudium domini tui.

** Matthew 25:22

Accessit autem et qui duo talenta acceperat, et ait : Domine, duo talenta tradidisti mihi, ecce alia duo lucratus sum.

** Matthew 25:23

Ait illi dominus ejus : Euge serve bone, et fidelis : quia super pauca fuisti fidelis, super multa te constituam ; intra in gaudium domini tui.

** Matthew 25:24

Accedens autem et qui unum talentum acceperat, ait : Domine, scio quia homo durus es ; metis ubi non seminasti, et congregas ubi non sparsisti :

** Matthew 25:25

et timens abii, et abscondi talentum tuum in terra : ecce habes quod tuum est.

** Matthew 25:26

Respondens autem dominus ejus, dixit ei : Serve male, et piger, sciebas quia meto ubi non semino, et congrego ubi non sparsi :

** Matthew 25:27

oportuit ergo te committere pecuniam meam numulariis, et veniens ego recepissem utique quod meum est cum usura.

** Matthew 25:28

Tollite itaque ab eo talentum, et date ei qui habet decem talenta :

** Matthew 25:29

omni enim habenti dabitur, et abundabit : ei autem qui non habet, et quod videtur habere, auferetur ab eo.

** Matthew 25:30

Et inutilem servum ejicite in tenebras exteriores : illic erit fletus, et stridor dentium.  

** Matthew 25:31

Cum autem venerit Filius hominis in majestate sua, et omnes angeli cum eo, tunc sedebit super sedem majestatis suæ :

** Matthew 25:32

et congregabuntur ante eum omnes gentes, et separabit eos ab invicem, sicut pastor segregat oves ab hædis :

** Matthew 25:33

et statuet oves quidem a dextris suis, hædos autem a sinistris.

** Matthew 25:34

Tunc dicet rex his qui a dextris ejus erunt : Venite benedicti Patris mei, possidete paratum vobis regnum a constitutione mundi :

** Matthew 25:35

esurivi enim, et dedistis mihi manducare : sitivi, et dedistis mihi bibere : hospes eram, et collegistis me :

** Matthew 25:36

nudus, et cooperuistis me : infirmus, et visitastis me : in carcere eram, et venistis ad me.

** Matthew 25:37

Tunc respondebunt ei justi, dicentes : Domine, quando te vidimus esurientem, et pavimus te : sitientem, et dedimus tibi potum ?

** Matthew 25:38

quando autem te vidimus hospitem, et collegimus te : aut nudum, et cooperuimus te ?

** Matthew 25:39

aut quando te vidimus infirmum, aut in carcere, et venimus ad te ?

** Matthew 25:40

Et respondens rex, dicet illis : Amen dico vobis, quamdiu fecistis uni ex his fratribus meis minimis, mihi fecistis.

** Matthew 25:41

Tunc dicet et his qui a sinistris erunt : Discedite a me maledicti in ignem æternum, qui paratus est diabolo, et angelis ejus :

** Matthew 25:42

esurivi enim, et non dedistis mihi manducare : sitivi, et non dedistis mihi potum :

** Matthew 25:43

hospes eram, et non collegistis me : nudus, et non cooperuistis me : infirmus, et in carcere, et non visitastis me.

** Matthew 25:44

Tunc respondebunt ei et ipsi, dicentes : Domine, quando te vidimus esurientem, aut sitientem, aut hospitem, aut nudum, aut infirmum, aut in carcere, et non ministravimus tibi ?

** Matthew 25:45

Tunc respondebit illis, dicens : Amen dico vobis : Quamdiu non fecistis uni de minoribus his, nec mihi fecistis.

** Matthew 25:46

Et ibunt hi in supplicium æternum : justi autem in vitam æternam.   

* Matthew 26

** Matthew 26:1

Et factum est : cum consummasset Jesus sermones hos omnes, dixit discipulis suis :

** Matthew 26:2

Scitis quia post biduum Pascha fiet, et Filius hominis tradetur ut crucifigatur.

** Matthew 26:3

Tunc congregati sunt principes sacerdotum, et seniores populi, in atrium principis sacerdotum, qui dicebatur Caiphas :

** Matthew 26:4

et consilium fecerunt ut Jesum dolo tenerent, et occiderent.

** Matthew 26:5

Dicebant autem : Non in die festo, ne forte tumultus fieret in populo.  

** Matthew 26:6

Cum autem Jesus esset in Bethania in domo Simonis leprosi,

** Matthew 26:7

accessit ad eum mulier habens alabastrum unguenti pretiosi, et effudit super caput ipsius recumbentis.

** Matthew 26:8

Videntes autem discipuli, indignati sunt, dicentes : Ut quid perditio hæc ?

** Matthew 26:9

potuit enim istud venundari multo, et dari pauperibus.

** Matthew 26:10

Sciens autem Jesus, ait illis : Quid molesti estis huic mulieri ? opus enim bonum operata est in me.

** Matthew 26:11

Nam semper pauperes habetis vobiscum : me autem non semper habetis.

** Matthew 26:12

Mittens enim hæc unguentum hoc in corpus meum, ad sepeliendum me fecit.

** Matthew 26:13

Amen dico vobis, ubicumque prædicatum fuerit hoc Evangelium in toto mundo, dicetur et quod hæc fecit in memoriam ejus.  

** Matthew 26:14

Tunc abiit unus de duodecim, qui dicebatur Judas Iscariotes, ad principes sacerdotum :

** Matthew 26:15

et ait illis : Quid vultis mihi dare, et ego vobis eum tradam ? At illi constituerunt ei triginta argenteos.

** Matthew 26:16

Et exinde quærebat opportunitatem ut eum traderet.  

** Matthew 26:17

Prima autem die azymorum accesserunt discipuli ad Jesum, dicentes : Ubi vis paremus tibi comedere Pascha ?

** Matthew 26:18

At Jesus dixit : Ite in civitatem ad quemdam, et dicite ei : Magister dicit : Tempus meum prope est, apud te facio Pascha cum discipulis meis.

** Matthew 26:19

Et fecerunt discipuli sicut constituit illis Jesus, et paraverunt Pascha.

** Matthew 26:20

Vespere autem facto, discumbebat cum duodecim discipulis suis.

** Matthew 26:21

Et edentibus illis, dixit : Amen dico vobis, quia unus vestrum me traditurus est.

** Matthew 26:22

Et contristati valde, cœperunt singuli dicere : Numquid ego sum Domine ?

** Matthew 26:23

At ipse respondens, ait : Qui intingit mecum manum in paropside, hic me tradet.

** Matthew 26:24

Filius quidem hominis vadit, sicut scriptum est de illo : væ autem homini illi, per quem Filius hominis tradetur ! bonum erat ei, si natus non fuisset homo ille.

** Matthew 26:25

Respondens autem Judas, qui tradidit eum, dixit : Numquid ego sum Rabbi ? Ait illi : Tu dixisti.  

** Matthew 26:26

Cœnantibus autem eis, accepit Jesus panem, et benedixit, ac fregit, deditque discipulis suis, et ait : Accipite, et comedite : hoc est corpus meum.

** Matthew 26:27

Et accipiens calicem, gratias egit : et dedit illis, dicens : Bibite ex hoc omnes.

** Matthew 26:28

Hic est enim sanguis meus novi testamenti, qui pro multis effundetur in remissionem peccatorum.

** Matthew 26:29

Dico autem vobis : non bibam amodo de hoc genimine vitis usque in diem illum, cum illud bibam vobiscum novum in regno Patris mei.  

** Matthew 26:30

Et hymno dicto, exierunt in montem Oliveti.

** Matthew 26:31

Tunc dicit illis Jesus : Omnes vos scandalum patiemini in me in ista nocte. Scriptum est enim : Percutiam pastorem, et dispergentur oves gregis.

** Matthew 26:32

Postquam autem resurrexero, præcedam vos in Galilæam.

** Matthew 26:33

Respondens autem Petrus, ait illi : Et si omnes scandalizati fuerint in te, ego numquam scandalizabor.

** Matthew 26:34

Ait illi Jesus : Amen dico tibi, quia in hac nocte, antequam gallus cantet, ter me negabis.

** Matthew 26:35

Ait illi Petrus : Etiamsi oportuerit me mori tecum, non te negabo. Similiter et omnes discipuli dixerunt.  

** Matthew 26:36

Tunc venit Jesus cum illis in villam, quæ dicitur Gethsemani, et dixit discipulis suis : Sedete hic donec vadam illuc, et orem.

** Matthew 26:37

Et assumpto Petro, et duobus filiis Zebedæi, cœpit contristari et mœstus esse.

** Matthew 26:38

Tunc ait illis : Tristis est anima mea usque ad mortem : sustinete hic, et vigilate mecum.

** Matthew 26:39

Et progressus pusillum, procidit in faciem suam, orans, et dicens : Pater mi, si possibile est, transeat a me calix iste : verumtamen non sicut ego volo, sed sicut tu.

** Matthew 26:40

Et venit ad discipulos suos, et invenit eos dormientes, et dicit Petro : Sic non potuistis una hora vigilare mecum ?

** Matthew 26:41

Vigilate, et orate ut non intretis in tentationem. Spiritus quidem promptus est, caro autem infirma.

** Matthew 26:42

Iterum secundo abiit, et oravit, dicens : Pater mi, si non potest hic calix transire nisi bibam illum, fiat voluntas tua.

** Matthew 26:43

Et venit iterum, et invenit eos dormientes : erant enim oculi eorum gravati.

** Matthew 26:44

Et relictis illis, iterum abiit, et oravit tertio, eumdem sermonem dicens.

** Matthew 26:45

Tunc venit ad discipulos suos, et dicit illis : Dormite jam, et requiescite : ecce appropinquavit hora, et Filius hominis tradetur in manus peccatorum.

** Matthew 26:46

Surgite, eamus : ecce appropinquavit qui me tradet.  

** Matthew 26:47

Adhuc eo loquente, ecce Judas unus de duodecim venit, et cum eo turba multa cum gladiis et fustibus, missi a principibus sacerdotum, et senioribus populi.

** Matthew 26:48

Qui autem tradidit eum, dedit illis signum, dicens : Quemcumque osculatus fuero, ipse est, tenete eum.

** Matthew 26:49

Et confestim accedens ad Jesum, dixit : Ave Rabbi. Et osculatus est eum.

** Matthew 26:50

Dixitque illi Jesus : Amice, ad quid venisti ? Tunc accesserunt, et manus injecerunt in Jesum, et tenuerunt eum.

** Matthew 26:51

Et ecce unus ex his qui erant cum Jesu, extendens manum, exemit gladium suum, et percutiens servum principis sacerdotum amputavit auriculam ejus.

** Matthew 26:52

Tunc ait illi Jesus : Converte gladium tuum in locum suum : omnes enim, qui acceperint gladium, gladio peribunt.

** Matthew 26:53

An putas, quia non possum rogare patrem meum, et exhibebit mihi modo plusquam duodecim legiones angelorum ?

** Matthew 26:54

Quomodo ergo implebuntur Scripturæ, quia sic oportet fieri ?

** Matthew 26:55

In illa hora dixit Jesus turbis : Tamquam ad latronem existis cum gladiis et fustibus comprehendere me : quotidie apud vos sedebam docens in templo, et non me tenuistis.

** Matthew 26:56

Hoc autem totum factum est, ut adimplerentur Scripturæ prophetarum. Tunc discipuli omnes, relicto eo, fugerunt.  

** Matthew 26:57

At illi tenentes Jesum, duxerunt ad Caipham principem sacerdotum, ubi scribæ et seniores convenerant.

** Matthew 26:58

Petrus autem sequebatur eum a longe, usque in atrium principis sacerdotum. Et ingressus intro, sedebat cum ministris, ut videret finem.

** Matthew 26:59

Principes autem sacerdotum, et omne concilium, quærebant falsum testimonium contra Jesum, ut eum morti traderent :

** Matthew 26:60

et non invenerunt, cum multi falsi testes accessissent. Novissime autem venerunt duo falsi testes,

** Matthew 26:61

et dixerunt : Hic dixit : Possum destruere templum Dei, et post triduum reædificare illud.

** Matthew 26:62

Et surgens princeps sacerdotum, ait illi : Nihil respondes ad ea, quæ isti adversum te testificantur ?

** Matthew 26:63

Jesus autem tacebat. Et princeps sacerdotum ait illi : Adjuro te per Deum vivum, ut dicas nobis si tu es Christus Filius Dei.

** Matthew 26:64

Dicit illi Jesus : Tu dixisti. Verumtamen dico vobis, amodo videbitis Filium hominis sedentem a dextris virtutis Dei, et venientem in nubibus cæli.

** Matthew 26:65

Tunc princeps sacerdotum scidit vestimenta sua, dicens : Blasphemavit : quid adhuc egemus testibus ? ecce nunc audistis blasphemiam :

** Matthew 26:66

quid vobis videtur ? At illi respondentes dixerunt : Reus est mortis.

** Matthew 26:67

Tunc exspuerunt in faciem ejus, et colaphis eum ceciderunt, alii autem palmas in faciem ejus dederunt,

** Matthew 26:68

dicentes : Prophetiza nobis Christe, quis est qui te percussit ?  

** Matthew 26:69

Petrus vero sedebat foris in atrio : et accessit ad eum una ancilla, dicens : Et tu cum Jesu Galilæo eras.

** Matthew 26:70

At ille negavit coram omnibus, dicens : Nescio quid dicis.

** Matthew 26:71

Exeunte autem illo januam, vidit eum alia ancilla, et ait his qui erant ibi : Et hic erat cum Jesu Nazareno.

** Matthew 26:72

Et iterum negavit cum juramento : Quia non novi hominem.

** Matthew 26:73

Et post pusillum accesserunt qui stabant, et dixerunt Petro : Vere et tu ex illis es : nam et loquela tua manifestum te facit.

** Matthew 26:74

Tunc cœpit detestari et jurare quia non novisset hominem. Et continuo gallus cantavit.

** Matthew 26:75

Et recordatus est Petrus verbi Jesu, quod dixerat : Priusquam gallus cantet, ter me negabis. Et egressus foras, flevit amare.   

* Matthew 27

** Matthew 27:1

Mane autem facto, consilium inierunt omnes principes sacerdotum et seniores populi adversus Jesum, ut eum morti traderent.

** Matthew 27:2

Et vinctum adduxerunt eum, et tradiderunt Pontio Pilato præsidi.  

** Matthew 27:3

Tunc videns Judas, qui eum tradidit, quod damnatus esset, pœnitentia ductus, retulit triginta argenteos principibus sacerdotum, et senioribus,

** Matthew 27:4

dicens : Peccavi, tradens sanguinem justum. At illi dixerunt : Quid ad nos ? tu videris.

** Matthew 27:5

Et projectis argenteis in templo, recessit : et abiens laqueo se suspendit.

** Matthew 27:6

Principes autem sacerdotum, acceptis argenteis, dixerunt : Non licet eos mittere in corbonam : quia pretium sanguinis est.

** Matthew 27:7

Consilio autem inito, emerunt ex illis agrum figuli, in sepulturam peregrinorum.

** Matthew 27:8

Propter hoc vocatus est ager ille, Haceldama, hoc est, Ager sanguinis, usque in hodiernum diem.

** Matthew 27:9

Tunc impletum est quod dictum est per Jeremiam prophetam, dicentem : Et acceperunt triginta argenteos pretium appretiati, quem appretiaverunt a filiis Israël :

** Matthew 27:10

et dederunt eos in agrum figuli, sicut constituit mihi Dominus.  

** Matthew 27:11

Jesus autem stetit ante præsidem, et interrogavit eum præses, dicens : Tu es rex Judæorum ? Dicit illi Jesus : Tu dicis.

** Matthew 27:12

Et cum accusaretur a principibus sacerdotum et senioribus, nihil respondit.

** Matthew 27:13

Tunc dicit illi Pilatus : Non audis quanta adversum te dicunt testimonia ?

** Matthew 27:14

Et non respondit ei ad ullum verbum, ita ut miraretur præses vehementer.

** Matthew 27:15

Per diem autem solemnem consueverat præses populo dimittere unum vinctum, quem voluissent :

** Matthew 27:16

habebat autem tunc vinctum insignem, qui dicebatur Barabbas.

** Matthew 27:17

Congregatis ergo illis, dixit Pilatus : Quem vultis dimittam vobis : Barabbam, an Jesum, qui dicitur Christus ?

** Matthew 27:18

Sciebat enim quod per invidiam tradidissent eum.

** Matthew 27:19

Sedente autem illo pro tribunali, misit ad eum uxor ejus, dicens : Nihil tibi, et justo illi : multa enim passa sum hodie per visum propter eum.

** Matthew 27:20

Principes autem sacerdotum et seniores persuaserunt populis ut peterent Barabbam, Jesum vero perderent.

** Matthew 27:21

Respondens autem præses, ait illis : Quem vultis vobis de duobus dimitti ? At illi dixerunt : Barabbam.

** Matthew 27:22

Dicit illis Pilatus : Quid igitur faciam de Jesu, qui dicitur Christus ?

** Matthew 27:23

Dicunt omnes : Crucifigatur. Ait illis præses : Quid enim mali fecit ? At illi magis clamabant dicentes : Crucifigatur.

** Matthew 27:24

Videns autem Pilatus quia nihil proficeret, sed magis tumultus fieret : accepta aqua, lavit manus coram populo, dicens : Innocens ego sum a sanguine justi hujus : vos videritis.

** Matthew 27:25

Et respondens universus populus, dixit : Sanguis ejus super nos, et super filios nostros.

** Matthew 27:26

Tunc dimisit illis Barabbam : Jesum autem flagellatum tradidit eis ut crucifigeretur.  

** Matthew 27:27

Tunc milites præsidis suscipientes Jesum in prætorium, congregaverunt ad eum universam cohortem :

** Matthew 27:28

et exuentes eum, chlamydem coccineam circumdederunt ei,

** Matthew 27:29

et plectentes coronam de spinis, posuerunt super caput ejus, et arundinem in dextera ejus. Et genu flexo ante eum, illudebant ei, dicentes : Ave rex Judæorum.

** Matthew 27:30

Et exspuentes in eum, acceperunt arundinem, et percutiebant caput ejus.

** Matthew 27:31

Et postquam illuserunt ei, exuerunt eum chlamyde, et induerunt eum vestimentis ejus, et duxerunt eum ut crucifigerent.  

** Matthew 27:32

Exeuntes autem invenerunt hominem Cyrenæum, nomine Simonem : hunc angariaverunt ut tolleret crucem ejus.

** Matthew 27:33

Et venerunt in locum qui dicitur Golgotha, quod est Calvariæ locus.

** Matthew 27:34

Et dederunt ei vinum bibere cum felle mistum. Et cum gustasset, noluit bibere.

** Matthew 27:35

Postquam autem crucifixerunt eum, diviserunt vestimenta ejus, sortem mittentes : ut impleretur quod dictum est per prophetam dicentem : Diviserunt sibi vestimenta mea, et super vestem meam miserunt sortem.

** Matthew 27:36

Et sedentes servabant eum.

** Matthew 27:37

Et imposuerunt super caput ejus causam ipsius scriptam : Hic est Jesus rex Judæorum.

** Matthew 27:38

Tunc crucifixi sunt cum eo duo latrones : unus a dextris, et unus a sinistris.

** Matthew 27:39

Prætereuntes autem blasphemabant eum moventes capita sua,

** Matthew 27:40

et dicentes : Vah ! qui destruis templum Dei, et in triduo illud reædificas : salva temetipsum : si Filius Dei es, descende de cruce.

** Matthew 27:41

Similiter et principes sacerdotum illudentes cum scribis et senioribus dicebant :

** Matthew 27:42

Alios salvos fecit, seipsum non potest salvum facere : si rex Israël est, descendat nunc de cruce, et credimus ei :

** Matthew 27:43

confidit in Deo : liberet nunc, si vult eum : dixit enim : Quia Filius Dei sum.

** Matthew 27:44

Idipsum autem et latrones, qui crucifixi erant cum eo, improperabant ei.  

** Matthew 27:45

A sexta autem hora tenebræ factæ sunt super universam terram usque ad horam nonam.

** Matthew 27:46

Et circa horam nonam clamavit Jesus voce magna, dicens : Eli, Eli, lamma sabacthani ? hoc est : Deus meus, Deus meus, ut quid dereliquisti me ?

** Matthew 27:47

Quidam autem illic stantes, et audientes, dicebant : Eliam vocat iste.

** Matthew 27:48

Et continuo currens unus ex eis, acceptam spongiam implevit aceto, et imposuit arundini, et dabat ei bibere.

** Matthew 27:49

Ceteri vero dicebant : Sine, videamus an veniat Elias liberans eum.

** Matthew 27:50

Jesus autem iterum clamans voce magna, emisit spiritum.  

** Matthew 27:51

Et ecce velum templi scissum est in duas partes a summo usque deorsum : et terra mota est, et petræ scissæ sunt,

** Matthew 27:52

et monumenta aperta sunt : et multa corpora sanctorum, qui dormierant, surrexerunt.

** Matthew 27:53

Et exeuntes de monumentis post resurrectionem ejus, venerunt in sanctam civitatem, et apparuerunt multis.

** Matthew 27:54

Centurio autem, et qui cum eo erant, custodientes Jesum, viso terræmotu, et his quæ fiebant, timuerunt valde, dicentes : Vere Filius Dei erat iste.  

** Matthew 27:55

Erant autem ibi mulieres multæ a longe, quæ secutæ erant Jesum a Galilæa, ministrantes ei :

** Matthew 27:56

inter quas erat Maria Magdalene, et Maria Jacobi, et Joseph mater, et mater filiorum Zebedæi.

** Matthew 27:57

Cum autem sero factum esset, venit quidam homo dives ab Arimathæa, nomine Joseph, qui et ipse discipulus erat Jesu :

** Matthew 27:58

hic accessit ad Pilatum, et petiit corpus Jesu. Tunc Pilatus jussit reddi corpus.

** Matthew 27:59

Et accepto corpore, Joseph involvit illud in sindone munda,

** Matthew 27:60

et posuit illud in monumento suo novo, quod exciderat in petra. Et advolvit saxum magnum ad ostium monumenti, et abiit.

** Matthew 27:61

Erant autem ibi Maria Magdalene, et altera Maria, sedentes contra sepulchrum.  

** Matthew 27:62

Altera autem die, quæ est post Parasceven, convenerunt principes sacerdotum et pharisæi ad Pilatum,

** Matthew 27:63

dicentes : Domine, recordati sumus, quia seductor ille dixit adhuc vivens : Post tres dies resurgam.

** Matthew 27:64

Jube ergo custodiri sepulchrum usque in diem tertium : ne forte veniant discipuli ejus, et furentur eum, et dicant plebi : Surrexit a mortuis : et erit novissimus error pejor priore.

** Matthew 27:65

Ait illis Pilatus : Habetis custodiam, ite, custodite sicut scitis.

** Matthew 27:66

Illi autem abeuntes, munierunt sepulchrum, signantes lapidem, cum custodibus.   

* Matthew 28

** Matthew 28:1

Vespere autem sabbati, quæ lucescit in prima sabbati, venit Maria Magdalene, et altera Maria, videre sepulchrum.

** Matthew 28:2

Et ecce terræmotus factus est magnus. Angelus enim Domini descendit de cælo : et accedens revolvit lapidem, et sedebat super eum :

** Matthew 28:3

erat autem aspectus ejus sicut fulgur : et vestimentum ejus sicut nix.

** Matthew 28:4

Præ timore autem ejus exterriti sunt custodes, et facti sunt velut mortui.

** Matthew 28:5

Respondens autem angelus dixit mulieribus : Nolite timere vos : scio enim, quod Jesum, qui crucifixus est, quæritis.

** Matthew 28:6

Non est hic : surrexit enim, sicut dixit : venite, et videte locum ubi positus erat Dominus.

** Matthew 28:7

Et cito euntes, dicite discipulis ejus quia surrexit : et ecce præcedit vos in Galilæam : ibi eum videbitis : ecce prædixi vobis.

** Matthew 28:8

Et exierunt cito de monumento cum timore et gaudio magno, currentes nuntiare discipulis ejus.

** Matthew 28:9

Et ecce Jesus occurrit illis, dicens : Avete. Illæ autem accesserunt, et tenuerunt pedes ejus, et adoraverunt eum.

** Matthew 28:10

Tunc ait illis Jesus : Nolite timere : ite, nuntiate fratribus meis ut eant in Galilæam ; ibi me videbunt.  

** Matthew 28:11

Quæ cum abiissent, ecce quidam de custodibus venerunt in civitatem, et nuntiaverunt principibus sacerdotum omnia quæ facta fuerant.

** Matthew 28:12

Et congregati cum senioribus consilio accepto, pecuniam copiosam dederunt militibus,

** Matthew 28:13

dicentes : Dicite quia discipuli ejus nocte venerunt, et furati sunt eum, nobis dormientibus.

** Matthew 28:14

Et si hoc auditum fuerit a præside, nos suadebimus ei, et securos vos faciemus.

** Matthew 28:15

At illi, accepta pecunia, fecerunt sicut erant edocti. Et divulgatum est verbum istud apud Judæos, usque in hodiernum diem.

** Matthew 28:16

Undecim autem discipuli abierunt in Galilæam in montem ubi constituerat illis Jesus.  

** Matthew 28:17

Et videntes eum adoraverunt : quidam autem dubitaverunt.

** Matthew 28:18

Et accedens Jesus locutus est eis, dicens : Data est mihi omnis potestas in cælo et in terra :

** Matthew 28:19

euntes ergo docete omnes gentes : baptizantes eos in nomine Patris, et Filii, et Spiritus Sancti :

** Matthew 28:20

docentes eos servare omnia quæcumque mandavi vobis : et ecce ego vobiscum sum omnibus diebus, usque ad consummationem sæculi.    

