* Philippians 1

** Philippians 1:1

Paulus et Timotheus, servi Jesu Christi, omnibus sanctis in Christo Jesu, qui sunt Philippis, cum episcopis et diaconibus.

** Philippians 1:2

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** Philippians 1:3

Gratias ago Deo meo in omni memoria vestri,

** Philippians 1:4

semper in cunctis orationibus meis pro omnibus vobis, cum gaudio deprecationem faciens,

** Philippians 1:5

super communicatione vestra in Evangelio Christi a prima die usque nunc.

** Philippians 1:6

Confidens hoc ipsum, quia qui cœpit in vobis opus bonum, perficiet usque in diem Christi Jesu :

** Philippians 1:7

sicut est mihi justum hoc sentire pro omnibus vobis : eo quod habeam vos in corde, et in vinculis meis, et in defensione, et confirmatione Evangelii, socios gaudii mei omnes vos esse.

** Philippians 1:8

Testis enim mihi est Deus, quomodo cupiam omnes vos in visceribus Jesu Christi.

** Philippians 1:9

Et hoc oro, ut caritas vestra magis ac magis abundet in scientia, et in omni sensu :

** Philippians 1:10

ut probetis potiora, ut sitis sinceri, et sine offensa in diem Christi,

** Philippians 1:11

repleti fructu justitiæ per Jesum Christum, in gloriam et laudem Dei.  

** Philippians 1:12

Scire autem vos volo fratres, quia quæ circa me sunt, magis ad profectum venerunt Evangelii :

** Philippians 1:13

ita ut vincula mea manifesta fierent in Christo in omni prætorio, et in ceteris omnibus,

** Philippians 1:14

et plures e fratribus in Domino confidentes vinculis meis, abundantius auderent sine timore verbum Dei loqui.

** Philippians 1:15

Quidam quidem et propter invidiam et contentionem : quidam autem et propter bonam voluntatem Christum prædicant :

** Philippians 1:16

quidam ex caritate, scientes quoniam in defensionem Evangelii positus sum.

** Philippians 1:17

Quidam autem ex contentione Christum annuntiant non sincere, existimantes pressuram se suscitare vinculis meis.

** Philippians 1:18

Quid enim ? Dum omni modo sive per occasionem, sive per veritatem, Christus annuntietur : et in hoc gaudeo, sed et gaudebo.

** Philippians 1:19

Scio enim quia hoc mihi proveniet ad salutem, per vestram orationem, et subministrationem Spiritus Jesu Christi,

** Philippians 1:20

secundum exspectationem et spem meam, quia in nullo confundar : sed in omni fiducia sicut semper, et nunc magnificabitur Christus in corpore meo, sive per vitam, sive per mortem.

** Philippians 1:21

Mihi enim vivere Christus est, et mori lucrum.

** Philippians 1:22

Quod si vivere in carne, hic mihi fructus operis est, et quid eligam ignoro.

** Philippians 1:23

Coarctor autem e duobus : desiderium habens dissolvi, et esse cum Christo, multo magis melius :

** Philippians 1:24

permanere autem in carne, necessarium propter vos.

** Philippians 1:25

Et hoc confidens scio quia manebo, et permanebo omnibus vobis ad profectum vestrum, et gaudium fidei :

** Philippians 1:26

ut gratulatio vestra abundet in Christo Jesu in me, per meum adventum iterum ad vos.  

** Philippians 1:27

Tantum digne Evangelio Christi conversamini : ut sive cum venero, et videro vos, sive absens audiam de vobis, quia statis in uno spiritu unanimes, collaborantes fidei Evangelii :

** Philippians 1:28

et in nullo terreamini ab adversariis : quæ illis est causa perditionis, vobis autem salutis, et hoc a Deo :

** Philippians 1:29

quia vobis donatum est pro Christo, non solum ut in eum credatis, sed ut etiam pro illo patiamini :

** Philippians 1:30

idem certamen habentes, quale et vidistis in me, et nunc audistis de me.   

* Philippians 2

** Philippians 2:1

Si qua ergo consolatio in Christo, si quod solatium caritatis, si qua societas spiritus, si qua viscera miserationis :

** Philippians 2:2

implete gaudium meum ut idem sapiatis, eamdem caritatem habentes, unanimes, idipsum sentientes,

** Philippians 2:3

nihil per contentionem, neque per inanem gloriam : sed in humilitate superiores sibi invicem arbitrantes,

** Philippians 2:4

non quæ sua sunt singuli considerantes, sed ea quæ aliorum.  

** Philippians 2:5

Hoc enim sentite in vobis, quod et in Christo Jesu :

** Philippians 2:6

qui cum in forma Dei esset, non rapinam arbitratus est esse se æqualem Deo :

** Philippians 2:7

sed semetipsum exinanivit, formam servi accipiens, in similitudinem hominum factus, et habitu inventus ut homo.

** Philippians 2:8

Humiliavit semetipsum factus obediens usque ad mortem, mortem autem crucis.

** Philippians 2:9

Propter quod et Deus exaltavit illum, et donavit illi nomen, quod est super omne nomen :

** Philippians 2:10

ut in nomine Jesu omne genu flectatur cælestium, terrestrium et infernorum,

** Philippians 2:11

et omnis lingua confiteatur, quia Dominus Jesus Christus in gloria est Dei Patris.  

** Philippians 2:12

Itaque carissimi mei (sicut semper obedistis), non ut in præsentia mei tantum, sed multo magis nunc in absentia mea, cum metu et tremore vestram salutem operamini.

** Philippians 2:13

Deus est enim, qui operatur in vobis et velle, et perficere pro bona voluntate.

** Philippians 2:14

Omnia autem facite sine murmurationibus et hæsitationibus :

** Philippians 2:15

ut sitis sine querela, et simplices filii Dei, sine reprehensione in medio nationis pravæ et perversæ : inter quos lucetis sicut luminaria in mundo,

** Philippians 2:16

verbum vitæ continentes ad gloriam meam in die Christi, quia non in vacuum cucurri, neque in vacuum laboravi.

** Philippians 2:17

Sed et si immolor supra sacrificium, et obsequium fidei vestræ, gaudeo, et congratulor omnibus vobis.

** Philippians 2:18

Idipsum autem et vos gaudete, et congratulamini mihi.  

** Philippians 2:19

Spero autem in Domino Jesu, Timotheum me cito mittere ad vos : ut et ego bono animo sim, cognitis quæ circa vos sunt.

** Philippians 2:20

Neminem enim habeo tam unanimem, qui sincera affectione pro vobis sollicitus sit.

** Philippians 2:21

Omnes enim quæ sua sunt quærunt, non quæ sunt Jesu Christi.

** Philippians 2:22

Experimentum autem ejus cognoscite, quia sicut patri filius, mecum servivit in Evangelio.

** Philippians 2:23

Hunc igitur spero me mittere ad vos, mox ut videro quæ circa me sunt.

** Philippians 2:24

Confido autem in Domino quoniam et ipse veniam ad vos cito.

** Philippians 2:25

Necessarium autem existimavi Epaphroditum fratrem, et cooperatorem, et commilitonem meum, vestrum autem apostolum, et ministrum necessitatis meæ, mittere ad vos :

** Philippians 2:26

quoniam quidem omnes vos desiderabat : et mœstus erat, propterea quod audieratis illum infirmatum.

** Philippians 2:27

Nam et infirmatus est usque ad mortem : sed Deus misertus est ejus : non solum autem ejus, verum etiam et mei, ne tristitiam super tristitiam haberem.

** Philippians 2:28

Festinantius ergo misi illum, ut viso eo iterum gaudeatis, et ego sine tristitia sim.

** Philippians 2:29

Excipite itaque illum cum omni gaudio in Domino, et ejusmodi cum honore habetote ;

** Philippians 2:30

quoniam propter opus Christi usque ad mortem accessit, tradens animam suam ut impleret id quod ex vobis deerat erga meum obsequium.   

* Philippians 3

** Philippians 3:1

De cetero, fratres mei, gaudete in Domino. Eadem vobis scribere, mihi quidem non pigrum, vobis autem necessarium.

** Philippians 3:2

Videte canes, videte malos operarios, videte concisionem.

** Philippians 3:3

Nos enim sumus circumcisio, qui spiritu servimus Deo, et gloriamur in Christo Jesu, et non in carne fiduciam habentes,

** Philippians 3:4

quamquam ego habeam confidentiam et in carne. Si quis alius videtur confidere in carne, ego magis,

** Philippians 3:5

circumcisus octavo die, ex genere Israël, de tribu Benjamin, Hebræus ex Hebræis, secundum legem pharisæus,

** Philippians 3:6

secundum æmulationem persequens Ecclesiam Dei, secundum justitiam, quæ in lege est, conversatus sine querela.

** Philippians 3:7

Sed quæ mihi fuerunt lucra, hæc arbitratus sum propter Christum detrimenta.

** Philippians 3:8

Verumtamen existimo omnia detrimentum esse propter eminentem scientiam Jesu Christi Domini mei : propter quem omnia detrimentum feci, et arbitror ut stercora, ut Christum lucrifaciam,

** Philippians 3:9

et inveniar in illo non habens meam justitiam, quæ ex lege est, sed illam, quæ ex fide est Christi Jesu : quæ ex Deo est justitia in fide,

** Philippians 3:10

ad cognoscendum illum, et virtutem resurrectionis ejus, et societatem passionum illius : configuratus morti ejus :

** Philippians 3:11

si quo modo occurram ad resurrectionem, quæ est ex mortuis :

** Philippians 3:12

non quod jam acceperim, aut jam perfectus sim : sequor autem, si quomodo comprehendam in quo et comprehensus sum a Christo Jesu.

** Philippians 3:13

Fratres, ego me non arbitror comprehendisse. Unum autem, quæ quidem retro sunt obliviscens, ad ea vero quæ sunt priora, extendens meipsum,

** Philippians 3:14

ad destinatum persequor, ad bravium supernæ vocationis Dei in Christo Jesu.

** Philippians 3:15

Quicumque ergo perfecti sumus, hoc sentiamus : et si quid aliter sapitis, et hoc vobis Deus revelabit.

** Philippians 3:16

Verumtamen ad quod pervenimus ut idem sapiamus, et in eadem permaneamus regula.

** Philippians 3:17

Imitatores mei estote, fratres, et observate eos qui ita ambulant, sicut habetis formam nostram.

** Philippians 3:18

Multi enim ambulant, quos sæpe dicebam vobis (nunc autem et flens dico) inimicos crucis Christi :

** Philippians 3:19

quorum finis interitus : quorum Deus venter est : et gloria in confusione ipsorum, qui terrena sapiunt.

** Philippians 3:20

Nostra autem conversatio in cælis est : unde etiam Salvatorem exspectamus Dominum nostrum Jesum Christum,

** Philippians 3:21

qui reformabit corpus humilitatis nostræ, configuratum corpori claritatis suæ, secundum operationem, qua etiam possit subjicere sibi omnia.   

* Philippians 4

** Philippians 4:1

Itaque fratres mei carissimi, et desideratissimi, gaudium meum, et corona mea : sic state in Domino, carissimi.

** Philippians 4:2

Evodiam rogo, et Syntychen deprecor, idipsum sapere in Domino.

** Philippians 4:3

Etiam rogo et te, germane compar, adjuva illas, quæ mecum laboraverunt in Evangelio cum Clemente, et ceteris adjutoribus meis, quorum nomina sunt in libro vitæ.

** Philippians 4:4

Gaudete in Domino semper : iterum dico gaudete.

** Philippians 4:5

Modestia vestra nota sit omnibus hominibus : Dominus prope est.

** Philippians 4:6

Nihil solliciti sitis : sed in omni oratione, et obsecratione, cum gratiarum actione petitiones vestræ innotescant apud Deum.

** Philippians 4:7

Et pax Dei, quæ exuperat omnem sensum, custodiat corda vestra, et intelligentias vestras in Christo Jesu.

** Philippians 4:8

De cetero fratres, quæcumque sunt vera, quæcumque pudica, quæcumque justa, quæcumque sancta, quæcumque amabilia, quæcumque bonæ famæ, siqua virtus, siqua laus disciplinæ, hæc cogitate.

** Philippians 4:9

Quæ et didicistis, et accepistis, et audistis, et vidistis in me, hæc agite : et Deus pacis erit vobiscum.  

** Philippians 4:10

Gavisus sum autem in Domino vehementer, quoniam tandem aliquando refloruistis pro me sentire, sicut et sentiebatis : occupati autem eratis.

** Philippians 4:11

Non quasi propter penuriam dico : ego enim didici, in quibus sum, sufficiens esse.

** Philippians 4:12

Scio et humiliari, scio et abundare (ubique et in omnibus institutus sum) : et satiari, et esurire, et abundare, et penuriam pati.

** Philippians 4:13

Omnia possum in eo qui me confortat.

** Philippians 4:14

Verumtamen bene fecistis, communicantes tribulationi meæ.

** Philippians 4:15

Scitis autem et vos Philippenses, quod in principio Evangelii, quando profectus sum a Macedonia, nulla mihi ecclesia communicavit in ratione dati et accepti, nisi vos soli :

** Philippians 4:16

quia et Thessalonicam semel et bis in usum mihi misistis.

** Philippians 4:17

Non quia quæro datum, sed requiro fructum abundantem in ratione vestra.

** Philippians 4:18

Habeo autem omnia, et abundo : repletus sum, acceptis ab Epaphrodito quæ misistis odorem suavitatis, hostiam acceptam, placentem Deo.

** Philippians 4:19

Deus autem meus impleat omne desiderium vestrum secundum divitias suas in gloria in Christo Jesu.

** Philippians 4:20

Deo autem et Patri nostro gloria in sæcula sæculorum. Amen.  

** Philippians 4:21

Salutate omnem sanctum in Christo Jesu.

** Philippians 4:22

Salutant vos, qui mecum sunt, fratres. Salutant vos omnes sancti, maxime autem qui de Cæsaris domo sunt.

** Philippians 4:23

Gratia Domini nostri Jesu Christi cum spiritu vestro. Amen.    

