* Philemon 1

** Philemon 1:1

Paulus vinctus Christi Jesu, et Timotheus frater, Philemoni dilecto, et adjutori nostro,

** Philemon 1:2

et Appiæ sorori carissimæ, et Archippo commilitoni nostro, et ecclesiæ, quæ in domo tua est.

** Philemon 1:3

Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** Philemon 1:4

Gratias ago Deo meo, semper memoriam tui faciens in orationibus meis,

** Philemon 1:5

audiens caritatem tuam, et fidem, quam habes in Domino Jesu, et in omnes sanctos :

** Philemon 1:6

ut communicatio fidei tuæ evidens fiat in agnitione omnis operis boni, quod est in vobis in Christo Jesu.

** Philemon 1:7

Gaudium enim magnum habui, et consolationem in caritate tua : quia viscera sanctorum requieverunt per te, frater.  

** Philemon 1:8

Propter quod multam fiduciam habens in Christo Jesu imperandi tibi quod ad rem pertinet :

** Philemon 1:9

propter caritatem magis obsecro, cum sis talis, ut Paulus senex, nunc autem et vinctus Jesu Christi :

** Philemon 1:10

obsecro te pro meo filio, quem genui in vinculis, Onesimo,

** Philemon 1:11

qui tibi aliquando inutilis fuit, nunc autem et mihi et tibi utilis,

** Philemon 1:12

quem remisi tibi. Tu autem illum, ut mea viscera, suscipe :

** Philemon 1:13

quem ego volueram mecum detinere, ut pro te mihi ministraret in vinculis Evangelii :

** Philemon 1:14

sine consilio autem tuo nihil volui facere, uti ne velut ex necessitate bonum tuum esset, sed voluntarium.

** Philemon 1:15

Forsitan enim ideo discessit ad horam a te, ut æternum illum reciperes :

** Philemon 1:16

jam non ut servum, sed pro servo carissimum fratrem, maxime mihi : quanto autem magis tibi et in carne, et in Domino ?

** Philemon 1:17

Si ergo habes me socium, suscipe illum sicut me :

** Philemon 1:18

si autem aliquid nocuit tibi, aut debet, hoc mihi imputa.

** Philemon 1:19

Ego Paulus scripsi mea manu : ego reddam, ut non dicam tibi, quod et teipsum mihi debes :

** Philemon 1:20

ita, frater. Ego te fruar in Domino : refice viscera mea in Domino.

** Philemon 1:21

Confidens in obedientia tua scripsi tibi : sciens quoniam et super id, quod dico, facies.  

** Philemon 1:22

Simul autem et para mihi hospitium : nam spero per orationes vestras donari me vobis.

** Philemon 1:23

Salutat te Epaphras concaptivus meus in Christo Jesu,

** Philemon 1:24

Marcus, Aristarchus, Demas, et Lucas, adjutores mei.

** Philemon 1:25

Gratia Domini nostri Jesu Christi cum spiritu vestro. Amen.    

