* Proverbs 1

** Proverbs 1:1

Parabolæ Salomonis, filii David, regis Israël, 

** Proverbs 1:2

ad sciendam sapientiam et disciplinam ; 

** Proverbs 1:3

ad intelligenda verba prudentiæ,  et suscipiendam eruditionem doctrinæ,  justitiam, et judicium, et æquitatem : 

** Proverbs 1:4

ut detur parvulis astutia,  adolescenti scientia et intellectus. 

** Proverbs 1:5

Audiens sapiens, sapientior erit,  et intelligens gubernacula possidebit. 

** Proverbs 1:6

Animadvertet parabolam et interpretationem,  verba sapientum et ænigmata eorum. 

** Proverbs 1:7

Timor Domini principium sapientiæ ;  sapientiam atque doctrinam stulti despiciunt. 

** Proverbs 1:8

Audi, fili mi, disciplinam patris tui,  et ne dimittas legem matris tuæ : 

** Proverbs 1:9

ut addatur gratia capiti tuo,  et torques collo tuo. 

** Proverbs 1:10

Fili mi, si te lactaverint peccatores,  ne acquiescas eis. 

** Proverbs 1:11

Si dixerint : Veni nobiscum, insidiemur sanguini ;  abscondamus tendiculas contra insontem frustra ; 

** Proverbs 1:12

deglutiamus eum sicut infernus viventem,  et integrum quasi descendentem in lacum ; 

** Proverbs 1:13

omnem pretiosam substantiam reperiemus ;  implebimus domos nostras spoliis : 

** Proverbs 1:14

sortem mitte nobiscum,  marsupium unum sit omnium nostrum : 

** Proverbs 1:15

fili mi, ne ambules cum eis ;  prohibe pedem tuum a semitis eorum : 

** Proverbs 1:16

pedes enim illorum ad malum currunt,  et festinant ut effundant sanguinem. 

** Proverbs 1:17

Frustra autem jacitur rete  ante oculos pennatorum. 

** Proverbs 1:18

Ipsi quoque contra sanguinem suum insidiantur,  et moliuntur fraudes contra animas suas. 

** Proverbs 1:19

Sic semitæ omnis avari :  animas possidentium rapiunt. 

** Proverbs 1:20

Sapientia foris prædicat ;  in plateis dat vocem suam : 

** Proverbs 1:21

in capite turbarum clamitat ;  in foribus portarum urbis profert verba sua, dicens : 

** Proverbs 1:22

Usquequo, parvuli, diligitis infantiam,  et stulti ea quæ sibi sunt noxia cupient,  et imprudentes odibunt scientiam ? 

** Proverbs 1:23

convertimini ad correptionem meam.  En proferam vobis spiritum meum,  et ostendam vobis verba mea. 

** Proverbs 1:24

Quia vocavi, et renuistis ;  extendi manum meam, et non fuit qui aspiceret : 

** Proverbs 1:25

despexistis omne consilium meum,  et increpationes meas neglexistis. 

** Proverbs 1:26

Ego quoque in interitu vestro ridebo,  et subsannabo cum vobis id quod timebatis advenerit. 

** Proverbs 1:27

Cum irruerit repentina calamitas,  et interitus quasi tempestas ingruerit ;  quando venerit super vos tribulatio et angustia : 

** Proverbs 1:28

tunc invocabunt me, et non exaudiam ;  mane consurgent, et non invenient me : 

** Proverbs 1:29

eo quod exosam habuerint disciplinam,  et timorem Domini non susceperint, 

** Proverbs 1:30

nec acquieverint consilio meo,  et detraxerint universæ correptioni meæ. 

** Proverbs 1:31

Comedent igitur fructus viæ suæ,  suisque consiliis saturabuntur. 

** Proverbs 1:32

Aversio parvulorum interficiet eos,  et prosperitas stultorum perdet illos. 

** Proverbs 1:33

Qui autem me audierit, absque terrore requiescet,  et abundantia perfruetur, timore malorum sublato.  

* Proverbs 2

** Proverbs 2:1

Fili mi, si susceperis sermones meos,  et mandata mea absconderis penes te : 

** Proverbs 2:2

ut audiat sapientiam auris tua,  inclina cor tuum ad cognoscendam prudentiam. 

** Proverbs 2:3

Si enim sapientiam invocaveris,  et inclinaveris cor tuum prudentiæ ; 

** Proverbs 2:4

si quæsieris eam quasi pecuniam,  et sicut thesauros effoderis illam : 

** Proverbs 2:5

tunc intelliges timorem Domini,  et scientiam Dei invenies, 

** Proverbs 2:6

quia Dominus dat sapientiam,  et ex ore ejus prudentia et scientia. 

** Proverbs 2:7

Custodiet rectorum salutem,  et proteget gradientes simpliciter, 

** Proverbs 2:8

servans semitas justitiæ,  et vias sanctorum custodiens. 

** Proverbs 2:9

Tunc intelliges justitiam, et judicium,  et æquitatem, et omnem semitam bonam. 

** Proverbs 2:10

Si intraverit sapientia cor tuum,  et scientia animæ tuæ placuerit, 

** Proverbs 2:11

consilium custodiet te,  et prudentia servabit te : 

** Proverbs 2:12

ut eruaris a via mala,  et ab homine qui perversa loquitur ; 

** Proverbs 2:13

qui relinquunt iter rectum,  et ambulant per vias tenebrosas ; 

** Proverbs 2:14

qui lætantur cum malefecerint,  et exsultant in rebus pessimis ; 

** Proverbs 2:15

quorum viæ perversæ sunt,  et infames gressus eorum. 

** Proverbs 2:16

Ut eruaris a muliere aliena,  et ab extranea quæ mollit sermones suos, 

** Proverbs 2:17

et relinquit ducem pubertatis suæ, 

** Proverbs 2:18

et pacti Dei sui oblita est.  Inclinata est enim ad mortem domus ejus,  et ad inferos semitæ ipsius. 

** Proverbs 2:19

Omnes qui ingrediuntur ad eam non revertentur,  nec apprehendent semitas vitæ. 

** Proverbs 2:20

Ut ambules in via bona,  et calles justorum custodias : 

** Proverbs 2:21

qui enim recti sunt habitabunt in terra,  et simplices permanebunt in ea ; 

** Proverbs 2:22

impii vero de terra perdentur,  et qui inique agunt auferentur ex ea.  

* Proverbs 3

** Proverbs 3:1

Fili mi, ne obliviscaris legis meæ,  et præcepta mea cor tuum custodiat : 

** Proverbs 3:2

longitudinem enim dierum, et annos vitæ, et pacem,  apponent tibi. 

** Proverbs 3:3

Misericordia et veritas te non deserant ;  circumda eas gutturi tuo,  et describe in tabulis cordis tui : 

** Proverbs 3:4

et invenies gratiam, et disciplinam bonam,  coram Deo et hominibus. 

** Proverbs 3:5

Habe fiduciam in Domino ex toto corde tuo,  et ne innitaris prudentiæ tuæ. 

** Proverbs 3:6

In omnibus viis tuis cogita illum,  et ipse diriget gressus tuos. 

** Proverbs 3:7

Ne sis sapiens apud temetipsum ;  time Deum, et recede a malo : 

** Proverbs 3:8

sanitas quippe erit umbilico tuo,  et irrigatio ossium tuorum. 

** Proverbs 3:9

Honora Dominum de tua substantia,  et de primitiis omnium frugum tuarum da ei : 

** Proverbs 3:10

et implebuntur horrea tua saturitate,  et vino torcularia tua redundabunt. 

** Proverbs 3:11

Disciplinam Domini, fili mi, ne abjicias,  nec deficias cum ab eo corriperis : 

** Proverbs 3:12

quem enim diligit Dominus, corripit,  et quasi pater in filio complacet sibi. 

** Proverbs 3:13

Beatus homo qui invenit sapientiam,  et qui affluit prudentia. 

** Proverbs 3:14

Melior est acquisitio ejus negotiatione argenti,  et auri primi et purissimi fructus ejus. 

** Proverbs 3:15

Pretiosior est cunctis opibus,  et omnia quæ desiderantur huic non valent comparari. 

** Proverbs 3:16

Longitudo dierum in dextera ejus,  et in sinistra illius divitiæ et gloria. 

** Proverbs 3:17

Viæ ejus viæ pulchræ,  et omnes semitæ illius pacificæ. 

** Proverbs 3:18

Lignum vitæ est his qui apprehenderint eam,  et qui tenuerit eam beatus. 

** Proverbs 3:19

Dominus sapientia fundavit terram ;  stabilivit cælos prudentia. 

** Proverbs 3:20

Sapientia illius eruperunt abyssi,  et nubes rore concrescunt. 

** Proverbs 3:21

Fili mi, ne effluant hæc ab oculis tuis.  Custodi legem atque consilium, 

** Proverbs 3:22

et erit vita animæ tuæ,  et gratia faucibus tuis. 

** Proverbs 3:23

Tunc ambulabis fiducialiter in via tua,  et pes tuus non impinget. 

** Proverbs 3:24

Si dormieris, non timebis ;  quiesces, et suavis erit somnus tuus. 

** Proverbs 3:25

Ne paveas repentino terrore,  et irruentes tibi potentias impiorum. 

** Proverbs 3:26

Dominus enim erit in latere tuo,  et custodiet pedem tuum, ne capiaris. 

** Proverbs 3:27

Noli prohibere benefacere eum qui potest :  si vales, et ipse benefac. 

** Proverbs 3:28

Ne dicas amico tuo : Vade, et revertere : cras dabo tibi :  cum statim possis dare. 

** Proverbs 3:29

Ne moliaris amico tuo malum,  cum ille in te habeat fiduciam. 

** Proverbs 3:30

Ne contendas adversus hominem frustra,  cum ipse tibi nihil mali fecerit. 

** Proverbs 3:31

Ne æmuleris hominem injustum,  nec imiteris vias ejus : 

** Proverbs 3:32

quia abominatio Domini est omnis illusor,  et cum simplicibus sermocinatio ejus. 

** Proverbs 3:33

Egestas a Domino in domo impii ;  habitacula autem justorum benedicentur. 

** Proverbs 3:34

Ipse deludet illusores,  et mansuetis dabit gratiam. 

** Proverbs 3:35

Gloriam sapientes possidebunt ;  stultorum exaltatio ignominia.  

* Proverbs 4

** Proverbs 4:1

Audite, filii, disciplinam patris,  et attendite ut sciatis prudentiam. 

** Proverbs 4:2

Donum bonum tribuam vobis :  legem meam ne derelinquatis. 

** Proverbs 4:3

Nam et ego filius fui patris mei,  tenellus et unigenitus coram matre mea. 

** Proverbs 4:4

Et docebat me, atque dicebat :  Suscipiat verba mea cor tuum ;  custodi præcepta mea, et vives. 

** Proverbs 4:5

Posside sapientiam, posside prudentiam :  ne obliviscaris, neque declines a verbis oris mei. 

** Proverbs 4:6

Ne dimittas eam, et custodiet te :  dilige eam, et conservabit te. 

** Proverbs 4:7

Principium sapientiæ : posside sapientiam,  et in omni possessione tua acquire prudentiam. 

** Proverbs 4:8

Arripe illam, et exaltabit te ;  glorificaberis ab ea cum eam fueris amplexatus. 

** Proverbs 4:9

Dabit capiti tuo augmenta gratiarum,  et corona inclyta proteget te. 

** Proverbs 4:10

Audi, fili mi, et suscipe verba mea,  ut multiplicentur tibi anni vitæ. 

** Proverbs 4:11

Viam sapientiæ monstrabo tibi ;  ducam te per semitas æquitatis : 

** Proverbs 4:12

quas cum ingressus fueris, non arctabuntur gressus tui,  et currens non habebis offendiculum. 

** Proverbs 4:13

Tene disciplinam, ne dimittas eam ;  custodi illam, quia ipsa est vita tua. 

** Proverbs 4:14

Ne delecteris in semitis impiorum,  nec tibi placeat malorum via. 

** Proverbs 4:15

Fuge ab ea, nec transeas per illam ;  declina, et desere eam. 

** Proverbs 4:16

Non enim dormiunt nisi malefecerint,  et rapitur somnus ab eis nisi supplantaverint. 

** Proverbs 4:17

Comedunt panem impietatis,  et vinum iniquitatis bibunt. 

** Proverbs 4:18

Justorum autem semita quasi lux splendens procedit,  et crescit usque ad perfectam diem. 

** Proverbs 4:19

Via impiorum tenebrosa ;  nesciunt ubi corruant. 

** Proverbs 4:20

Fili mi, ausculta sermones meos,  et ad eloquia mea inclina aurem tuam. 

** Proverbs 4:21

Ne recedant ab oculis tuis :  custodi ea in medio cordis tui : 

** Proverbs 4:22

vita enim sunt invenientibus ea,  et universæ carni sanitas. 

** Proverbs 4:23

Omni custodia serva cor tuum,  quia ex ipso vita procedit. 

** Proverbs 4:24

Remove a te os pravum,  et detrahentia labia sint procul a te. 

** Proverbs 4:25

Oculi tui recta videant,  et palpebræ tuæ præcedant gressus tuos. 

** Proverbs 4:26

Dirige semitam pedibus tuis,  et omnes viæ tuæ stabilientur. 

** Proverbs 4:27

Ne declines ad dexteram neque ad sinistram ;  averte pedem tuum a malo :  vias enim quæ a dextris sunt novit Dominus :  perversæ vero sunt quæ a sinistris sunt.  Ipse autem rectos faciet cursus tuos,  itinera autem tua in pace producet.  

* Proverbs 5

** Proverbs 5:1

Fili mi, attende ad sapientiam meam,  et prudentiæ meæ inclina aurem tuam : 

** Proverbs 5:2

ut custodias cogitationes, et disciplinam labia tua conservent.  Ne attendas fallaciæ mulieris ; 

** Proverbs 5:3

favus enim distillans labia meretricis,  et nitidius oleo guttur ejus : 

** Proverbs 5:4

novissima autem illius amara quasi absinthium,  et acuta quasi gladius biceps. 

** Proverbs 5:5

Pedes ejus descendunt in mortem,  et ad inferos gressus illius penetrant. 

** Proverbs 5:6

Per semitam vitæ non ambulant ;  vagi sunt gressus ejus et investigabiles. 

** Proverbs 5:7

Nunc ergo fili mi, audi me,  et ne recedas a verbis oris mei. 

** Proverbs 5:8

Longe fac ab ea viam tuam,  et ne appropinques foribus domus ejus. 

** Proverbs 5:9

Ne des alienis honorem tuum,  et annos tuos crudeli : 

** Proverbs 5:10

ne forte impleantur extranei viribus tuis,  et labores tui sint in domo aliena, 

** Proverbs 5:11

et gemas in novissimis,  quando consumpseris carnes tuas et corpus tuum,  et dicas :

** Proverbs 5:12

Cur detestatus sum disciplinam,  et increpationibus non acquievit cor meum, 

** Proverbs 5:13

nec audivi vocem docentium me,  et magistris non inclinavi aurem meam ? 

** Proverbs 5:14

pene fui in omni malo,  in medio ecclesiæ et synagogæ. 

** Proverbs 5:15

Bibe aquam de cisterna tua,  et fluenta putei tui ; 

** Proverbs 5:16

deriventur fontes tui foras,  et in plateis aquas tuas divide. 

** Proverbs 5:17

Habeto eas solus,  nec sint alieni participes tui. 

** Proverbs 5:18

Sit vena tua benedicta,  et lætare cum muliere adolescentiæ tuæ. 

** Proverbs 5:19

Cerva carissima, et gratissimus hinnulus :  ubera ejus inebrient te in omni tempore ;  in amore ejus delectare jugiter. 

** Proverbs 5:20

Quare seduceris, fili mi, ab aliena,  et foveris in sinu alterius ? 

** Proverbs 5:21

Respicit Dominus vias hominis,  et omnes gressus ejus considerat. 

** Proverbs 5:22

Iniquitates suas capiunt impium,  et funibus peccatorum suorum constringitur. 

** Proverbs 5:23

Ipse morietur, quia non habuit disciplinam,  et in multitudine stultitiæ suæ decipietur.  

* Proverbs 6

** Proverbs 6:1

Fili mi, si spoponderis pro amico tuo,  defixisti apud extraneum manum tuam : 

** Proverbs 6:2

illaqueatus es verbis oris tui,  et captus propriis sermonibus. 

** Proverbs 6:3

Fac ergo quod dico, fili mi, et temetipsum libera,  quia incidisti in manum proximi tui.  Discurre, festina, suscita amicum tuum. 

** Proverbs 6:4

Ne dederis somnum oculis tuis,  nec dormitent palpebræ tuæ. 

** Proverbs 6:5

Eruere quasi damula de manu,  et quasi avis de manu aucupis. 

** Proverbs 6:6

Vade ad formicam, o piger,  et considera vias ejus, et disce sapientiam. 

** Proverbs 6:7

Quæ cum non habeat ducem,  nec præceptorem, nec principem, 

** Proverbs 6:8

parat in æstate cibum sibi,  et congregat in messe quod comedat. 

** Proverbs 6:9

Usquequo, piger, dormies ?  quando consurges e somno tuo ? 

** Proverbs 6:10

Paululum dormies, paululum dormitabis,  paululum conseres manus ut dormias ; 

** Proverbs 6:11

et veniet tibi quasi viator egestas,  et pauperies quasi vir armatus.  Si vero impiger fueris, veniet ut fons messis tua,  et egestas longe fugiet a te. 

** Proverbs 6:12

Homo apostata, vir inutilis, graditur ore perverso ; 

** Proverbs 6:13

annuit oculis, terit pede, digito loquitur, 

** Proverbs 6:14

pravo corde machinatur malum,  et omni tempore jurgia seminat. 

** Proverbs 6:15

Huic extemplo veniet perditio sua,  et subito conteretur, nec habebit ultra medicinam. 

** Proverbs 6:16

Sex sunt quæ odit Dominus,  et septimum detestatur anima ejus : 

** Proverbs 6:17

oculos sublimes, linguam mendacem,  manus effundentes innoxium sanguinem, 

** Proverbs 6:18

cor machinans cogitationes pessimas,  pedes veloces ad currendum in malum, 

** Proverbs 6:19

proferentem mendacia testem fallacem,  et eum qui seminat inter fratres discordias. 

** Proverbs 6:20

Conserva, fili mi, præcepta patris tui,  et ne dimittas legem matris tuæ. 

** Proverbs 6:21

Liga ea in corde tuo jugiter,  et circumda gutturi tuo. 

** Proverbs 6:22

Cum ambulaveris, gradiantur tecum ;  cum dormieris, custodiant te :  et evigilans loquere cum eis. 

** Proverbs 6:23

Quia mandatum lucerna est, et lex lux,  et via vitæ increpatio disciplinæ : 

** Proverbs 6:24

ut custodiant te a muliere mala,  et a blanda lingua extraneæ. 

** Proverbs 6:25

Non concupiscat pulchritudinem ejus cor tuum,  nec capiaris nutibus illius : 

** Proverbs 6:26

pretium enim scorti vix est unius panis,  mulier autem viri pretiosam animam capit. 

** Proverbs 6:27

Numquid potest homo abscondere ignem in sinu suo,  ut vestimenta illius non ardeant ? 

** Proverbs 6:28

aut ambulare super prunas,  ut non comburantur plantæ ejus ? 

** Proverbs 6:29

sic qui ingreditur ad mulierem proximi sui,  non erit mundus cum tetigerit eam. 

** Proverbs 6:30

Non grandis est culpa cum quis furatus fuerit :  furatur enim ut esurientem impleat animam ; 

** Proverbs 6:31

deprehensus quoque reddet septuplum,  et omnem substantiam domus suæ tradet. 

** Proverbs 6:32

Qui autem adulter est,  propter cordis inopiam perdet animam suam ; 

** Proverbs 6:33

turpitudinem et ignominiam congregat sibi,  et opprobrium illius non delebitur : 

** Proverbs 6:34

quia zelus et furor viri  non parcet in die vindictæ, 

** Proverbs 6:35

nec acquiescet cujusquam precibus,  nec suscipiet pro redemptione dona plurima.  

* Proverbs 7

** Proverbs 7:1

Fili mi, custodi sermones meos,  et præcepta mea reconde tibi.  Fili,

** Proverbs 7:2

serva mandata mea, et vives ;  et legem meam quasi pupillam oculi tui : 

** Proverbs 7:3

liga eam in digitis tuis,  scribe illam in tabulis cordis tui. 

** Proverbs 7:4

Dic sapientiæ : Soror mea es,  et prudentiam voca amicam tuam : 

** Proverbs 7:5

ut custodiant te a muliere extranea,  et ab aliena quæ verba sua dulcia facit. 

** Proverbs 7:6

De fenestra enim domus meæ  per cancellos prospexi, 

** Proverbs 7:7

et video parvulos ;  considero vecordem juvenem, 

** Proverbs 7:8

qui transit per plateam juxta angulum  et prope viam domus illius graditur : 

** Proverbs 7:9

in obscuro, advesperascente die,  in noctis tenebris et caligine. 

** Proverbs 7:10

Et ecce occurrit illi mulier ornatu meretricio,  præparata ad capiendas animas :  garrula et vaga, 

** Proverbs 7:11

quietis impatiens,  nec valens in domo consistere pedibus suis ; 

** Proverbs 7:12

nunc foris, nunc in plateis,  nunc juxta angulos insidians. 

** Proverbs 7:13

Apprehensumque deosculatur juvenem,  et procaci vultu blanditur, dicens : 

** Proverbs 7:14

Victimas pro salute vovi ;  hodie reddidi vota mea : 

** Proverbs 7:15

idcirco egressa sum in occursum tuum,  desiderans te videre, et reperi. 

** Proverbs 7:16

Intexui funibus lectulum meum ;  stravi tapetibus pictis ex Ægypto : 

** Proverbs 7:17

aspersi cubile meum myrrha,  et aloë, et cinnamomo. 

** Proverbs 7:18

Veni, inebriemur uberibus,  et fruamur cupitis amplexibus donec illucescat dies. 

** Proverbs 7:19

Non est enim vir in domo sua :  abiit via longissima : 

** Proverbs 7:20

sacculum pecuniæ secum tulit ;  in die plenæ lunæ reversurus est in domum suam. 

** Proverbs 7:21

Irretivit eum multis sermonibus,  et blanditiis labiorum protraxit illum. 

** Proverbs 7:22

Statim eam sequitur quasi bos ductus ad victimam,  et quasi agnus lasciviens,  et ignorans quod ad vincula stultus trahatur : 

** Proverbs 7:23

donec transfigat sagitta jecur ejus,  velut si avis festinet ad laqueum,  et nescit quod de periculo animæ illius agitur. 

** Proverbs 7:24

Nunc ergo, fili mi, audi me,  et attende verbis oris mei. 

** Proverbs 7:25

Ne abstrahatur in viis illius mens tua,  neque decipiaris semitis ejus ; 

** Proverbs 7:26

multos enim vulneratos dejecit,  et fortissimi quique interfecti sunt ab ea. 

** Proverbs 7:27

Viæ inferi domus ejus,  penetrantes in interiora mortis.  

* Proverbs 8

** Proverbs 8:1

Numquid non sapientia clamitat,  et prudentia dat vocem suam ? 

** Proverbs 8:2

In summis excelsisque verticibus supra viam,  in mediis semitis stans, 

** Proverbs 8:3

juxta portas civitatis,  in ipsis foribus loquitur, dicens : 

** Proverbs 8:4

O viri, ad vos clamito,  et vox mea ad filios hominum. 

** Proverbs 8:5

Intelligite, parvuli, astutiam,  et insipientes, animadvertite. 

** Proverbs 8:6

Audite, quoniam de rebus magnis locutura sum,  et aperientur labia mea ut recta prædicent. 

** Proverbs 8:7

Veritatem meditabitur guttur meum,  et labia mea detestabuntur impium. 

** Proverbs 8:8

Justi sunt omnes sermones mei :  non est in eis pravum quid, neque perversum ; 

** Proverbs 8:9

recti sunt intelligentibus,  et æqui invenientibus scientiam. 

** Proverbs 8:10

Accipite disciplinam meam, et non pecuniam ;  doctrinam magis quam aurum eligite : 

** Proverbs 8:11

melior est enim sapientia cunctis pretiosissimis,  et omne desiderabile ei non potest comparari. 

** Proverbs 8:12

Ego sapientia, habito in consilio,  et eruditis intersum cogitationibus. 

** Proverbs 8:13

Timor Domini odit malum :  arrogantiam, et superbiam,  et viam pravam, et os bilingue, detestor. 

** Proverbs 8:14

Meum est consilium et æquitas ;  mea est prudentia, mea est fortitudo. 

** Proverbs 8:15

Per me reges regnant,  et legum conditores justa decernunt ; 

** Proverbs 8:16

per me principes imperant,  et potentes decernunt justitiam. 

** Proverbs 8:17

Ego diligentes me diligo,  et qui mane vigilant ad me, invenient me. 

** Proverbs 8:18

Mecum sunt divitiæ et gloria,  opes superbæ et justitia. 

** Proverbs 8:19

Melior est enim fructus meus auro et lapide pretioso,  et genimina mea argento electo. 

** Proverbs 8:20

In viis justitiæ ambulo,  in medio semitarum judicii : 

** Proverbs 8:21

ut ditem diligentes me,  et thesauros eorum repleam. 

** Proverbs 8:22

Dominus possedit me in initio viarum suarum  antequam quidquam faceret a principio. 

** Proverbs 8:23

Ab æterno ordinata sum,  et ex antiquis antequam terra fieret. 

** Proverbs 8:24

Nondum erant abyssi, et ego jam concepta eram :  necdum fontes aquarum eruperant, 

** Proverbs 8:25

necdum montes gravi mole constiterant :  ante colles ego parturiebar. 

** Proverbs 8:26

Adhuc terram non fecerat, et flumina,  et cardines orbis terræ. 

** Proverbs 8:27

Quando præparabat cælos, aderam ;  quando certa lege et gyro vallabat abyssos ; 

** Proverbs 8:28

quando æthera firmabat sursum,  et librabat fontes aquarum ; 

** Proverbs 8:29

quando circumdabat mari terminum suum,  et legem ponebat aquis, ne transirent fines suos ;  quando appendebat fundamenta terræ : 

** Proverbs 8:30

cum eo eram, cuncta componens.  Et delectabar per singulos dies,  ludens coram eo omni tempore, 

** Proverbs 8:31

ludens in orbe terrarum ;  et deliciæ meæ esse cum filiis hominum. 

** Proverbs 8:32

Nunc ergo, filii, audite me :  beati qui custodiunt vias meas. 

** Proverbs 8:33

Audite disciplinam, et estote sapientes,  et nolite abjicere eam. 

** Proverbs 8:34

Beatus homo qui audit me,  et qui vigilat ad fores meas quotidie,  et observat ad postes ostii mei. 

** Proverbs 8:35

Qui me invenerit, inveniet vitam,  et hauriet salutem a Domino. 

** Proverbs 8:36

Qui autem in me peccaverit, lædet animam suam ;  omnes qui me oderunt diligunt mortem.  

* Proverbs 9

** Proverbs 9:1

Sapientia ædificavit sibi domum :  excidit columnas septem. 

** Proverbs 9:2

Immolavit victimas suas, miscuit vinum,  et proposuit mensam suam. 

** Proverbs 9:3

Misit ancillas suas ut vocarent  ad arcem et ad mœnia civitatis. 

** Proverbs 9:4

Si quis est parvulus, veniat ad me.  Et insipientibus locuta est : 

** Proverbs 9:5

Venite, comedite panem meum,  et bibite vinum quod miscui vobis. 

** Proverbs 9:6

Relinquite infantiam, et vivite,  et ambulate per vias prudentiæ. 

** Proverbs 9:7

Qui erudit derisorem, ipse injuriam sibi facit,  et qui arguit impium, sibi maculam generat. 

** Proverbs 9:8

Noli arguere derisorem, ne oderit te :  argue sapientem, et diliget te. 

** Proverbs 9:9

Da sapienti occasionem, et addetur ei sapientia ;  doce justum, et festinabit accipere. 

** Proverbs 9:10

Principium sapientiæ timor Domini,  et scientia sanctorum prudentia. 

** Proverbs 9:11

Per me enim multiplicabuntur dies tui,  et addentur tibi anni vitæ. 

** Proverbs 9:12

Si sapiens fueris, tibimetipsi eris ;  si autem illusor, solus portabis malum. 

** Proverbs 9:13

Mulier stulta et clamosa,  plenaque illecebris, et nihil omnino sciens, 

** Proverbs 9:14

sedit in foribus domus suæ,  super sellam in excelso urbis loco, 

** Proverbs 9:15

ut vocaret transeuntes per viam,  et pergentes itinere suo : 

** Proverbs 9:16

Qui est parvulus declinet ad me.  Et vecordi locuta est : 

** Proverbs 9:17

Aquæ furtivæ dulciores sunt,  et panis absconditus suavior. 

** Proverbs 9:18

Et ignoravit quod ibi sint gigantes,  et in profundis inferni convivæ ejus.  

* Proverbs 10

** Proverbs 10:1

Filius sapiens lætificat patrem,  filius vero stultus mœstitia est matris suæ. 

** Proverbs 10:2

Nil proderunt thesauri impietatis,  justitia vero liberabit a morte. 

** Proverbs 10:3

Non affliget Dominus fame animam justi,  et insidias impiorum subvertet. 

** Proverbs 10:4

Egestatem operata est manus remissa ;  manus autem fortium divitias parat.  Qui nititur mendaciis, hic pascit ventos ;  idem autem ipse sequitur aves volantes. 

** Proverbs 10:5

Qui congregat in messe, filius sapiens est ;  qui autem stertit æstate, filius confusionis. 

** Proverbs 10:6

Benedictio Domini super caput justi ;  os autem impiorum operit iniquitas. 

** Proverbs 10:7

Memoria justi cum laudibus,  et nomen impiorum putrescet. 

** Proverbs 10:8

Sapiens corde præcepta suscipit ;  stultus cæditur labiis. 

** Proverbs 10:9

Qui ambulat simpliciter ambulat confidenter ;  qui autem depravat vias suas manifestus erit. 

** Proverbs 10:10

Qui annuit oculo dabit dolorem ;  et stultus labiis verberabitur. 

** Proverbs 10:11

Vena vitæ os justi,  et os impiorum operit iniquitatem. 

** Proverbs 10:12

Odium suscitat rixas,  et universa delicta operit caritas. 

** Proverbs 10:13

In labiis sapientis invenitur sapientia,  et virga in dorso ejus qui indiget corde. 

** Proverbs 10:14

Sapientes abscondunt scientiam ;  os autem stulti confusioni proximum est. 

** Proverbs 10:15

Substantia divitis, urbs fortitudinis ejus ;  pavor pauperum egestas eorum. 

** Proverbs 10:16

Opus justi ad vitam,  fructus autem impii ad peccatum. 

** Proverbs 10:17

Via vitæ custodienti disciplinam ;  qui autem increpationes relinquit, errat. 

** Proverbs 10:18

Abscondunt odium labia mendacia ;  qui profert contumeliam, insipiens est. 

** Proverbs 10:19

In multiloquio non deerit peccatum,  qui autem moderatur labia sua prudentissimus est. 

** Proverbs 10:20

Argentum electum lingua justi ;  cor autem impiorum pro nihilo. 

** Proverbs 10:21

Labia justi erudiunt plurimos ;  qui autem indocti sunt in cordis egestate morientur. 

** Proverbs 10:22

Benedictio Domini divites facit,  nec sociabitur eis afflictio. 

** Proverbs 10:23

Quasi per risum stultus operatur scelus,  sapientia autem est viro prudentia. 

** Proverbs 10:24

Quod timet impius veniet super eum ;  desiderium suum justus dabitur. 

** Proverbs 10:25

Quasi tempestas transiens non erit impius ;  justus autem quasi fundamentum sempiternum. 

** Proverbs 10:26

Sicut acetum dentibus, et fumus oculis,  sic piger his qui miserunt eum. 

** Proverbs 10:27

Timor Domini apponet dies,  et anni impiorum breviabuntur. 

** Proverbs 10:28

Exspectatio justorum lætitia,  spes autem impiorum peribit. 

** Proverbs 10:29

Fortitudo simplicis via Domini,  et pavor his qui operantur malum. 

** Proverbs 10:30

Justus in æternum non commovebitur,  impii autem non habitabunt super terram. 

** Proverbs 10:31

Os justi parturiet sapientiam ;  lingua pravorum peribit. 

** Proverbs 10:32

Labia justi considerant placita,  et os impiorum perversa.  

* Proverbs 11

** Proverbs 11:1

Statera dolosa abominatio est apud Dominum,  et pondus æquum voluntas ejus. 

** Proverbs 11:2

Ubi fuerit superbia, ibi erit et contumelia ;  ubi autem est humilitas, ibi et sapientia. 

** Proverbs 11:3

Simplicitas justorum diriget eos,  et supplantatio perversorum vastabit illos. 

** Proverbs 11:4

Non proderunt divitiæ in die ultionis ;  justitia autem liberabit a morte. 

** Proverbs 11:5

Justitia simplicis diriget viam ejus,  et in impietate sua corruet impius. 

** Proverbs 11:6

Justitia rectorum liberabit eos,  et in insidiis suis capientur iniqui. 

** Proverbs 11:7

Mortuo homine impio, nulla erit ultra spes,  et exspectatio sollicitorum peribit. 

** Proverbs 11:8

Justus de angustia liberatus est,  et tradetur impius pro eo. 

** Proverbs 11:9

Simulator ore decipit amicum suum ;  justi autem liberabuntur scientia. 

** Proverbs 11:10

In bonis justorum exsultabit civitas,  et in perditione impiorum erit laudatio. 

** Proverbs 11:11

Benedictione justorum exaltabitur civitas,  et ore impiorum subvertetur. 

** Proverbs 11:12

Qui despicit amicum suum indigens corde est ;  vir autem prudens tacebit. 

** Proverbs 11:13

Qui ambulat fraudulenter, revelat arcana ;  qui autem fidelis est animi, celat amici commissum. 

** Proverbs 11:14

Ubi non est gubernator, populus corruet ;  salus autem, ubi multa consilia. 

** Proverbs 11:15

Affligetur malo qui fidem facit pro extraneo ;  qui autem cavet laqueos securus erit. 

** Proverbs 11:16

Mulier gratiosa inveniet gloriam,  et robusti habebunt divitias. 

** Proverbs 11:17

Benefacit animæ suæ vir misericors ;  qui autem crudelis est, etiam propinquos abjicit. 

** Proverbs 11:18

Impius facit opus instabile,  seminanti autem justitiam merces fidelis. 

** Proverbs 11:19

Clementia præparat vitam,  et sectatio malorum mortem. 

** Proverbs 11:20

Abominabile Domino cor pravum,  et voluntas ejus in iis qui simpliciter ambulant. 

** Proverbs 11:21

Manus in manu non erit innocens malus ;  semen autem justorum salvabitur. 

** Proverbs 11:22

Circulus aureus in naribus suis,  mulier pulchra et fatua. 

** Proverbs 11:23

Desiderium justorum omne bonum est ;  præstolatio impiorum furor. 

** Proverbs 11:24

Alii dividunt propria, et ditiores fiunt ;  alii rapiunt non sua, et semper in egestate sunt. 

** Proverbs 11:25

Anima quæ benedicit impinguabitur,  et qui inebriat, ipse quoque inebriabitur. 

** Proverbs 11:26

Qui abscondit frumenta maledicetur in populis ;  benedictio autem super caput vendentium. 

** Proverbs 11:27

Bene consurgit diluculo qui quærit bona ;  qui autem investigator malorum est, opprimetur ab eis. 

** Proverbs 11:28

Qui confidit in divitiis suis corruet :  justi autem quasi virens folium germinabunt. 

** Proverbs 11:29

Qui conturbat domum suam possidebit ventos,  et qui stultus est serviet sapienti. 

** Proverbs 11:30

Fructus justi lignum vitæ,  et qui suscipit animas sapiens est. 

** Proverbs 11:31

Si justus in terra recipit,  quanto magis impius et peccator !  

* Proverbs 12

** Proverbs 12:1

Qui diligit disciplinam diligit scientiam ;  qui autem odit increpationes insipiens est. 

** Proverbs 12:2

Qui bonus est hauriet gratiam a Domino ;  qui autem confidit in cogitationibus suis impie agit. 

** Proverbs 12:3

Non roborabitur homo ex impietate,  et radix justorum non commovebitur. 

** Proverbs 12:4

Mulier diligens corona est viro suo ;  et putredo in ossibus ejus, quæ confusione res dignas gerit. 

** Proverbs 12:5

Cogitationes justorum judicia,  et consilia impiorum fraudulenta. 

** Proverbs 12:6

Verba impiorum insidiantur sanguini ;  os justorum liberabit eos. 

** Proverbs 12:7

Verte impios, et non erunt ;  domus autem justorum permanebit. 

** Proverbs 12:8

Doctrina sua noscetur vir ;  qui autem vanus et excors est patebit contemptui. 

** Proverbs 12:9

Melior est pauper et sufficiens sibi  quam gloriosus et indigens pane. 

** Proverbs 12:10

Novit justus jumentorum suorum animas ;  viscera autem impiorum crudelia. 

** Proverbs 12:11

Qui operatur terram suam satiabitur panibus ;  qui autem sectatur otium stultissimus est.  Qui suavis est in vini demorationibus,  in suis munitionibus relinquit contumeliam. 

** Proverbs 12:12

Desiderium impii munimentum est pessimorum ;  radix autem justorum proficiet. 

** Proverbs 12:13

Propter peccata labiorum ruina proximat malo ;  effugiet autem justus de angustia. 

** Proverbs 12:14

De fructu oris sui unusquisque replebitur bonis,  et juxta opera manuum suarum retribuetur ei. 

** Proverbs 12:15

Via stulti recta in oculis ejus ;  qui autem sapiens est audit consilia. 

** Proverbs 12:16

Fatuus statim indicat iram suam ;  qui autem dissimulat injuriam callidus est. 

** Proverbs 12:17

Qui quod novit loquitur, index justitiæ est ;  qui autem mentitur, testis est fraudulentus. 

** Proverbs 12:18

Est qui promittit, et quasi gladio pungitur conscientiæ :  lingua autem sapientium sanitas est. 

** Proverbs 12:19

Labium veritatis firmum erit in perpetuum ;  qui autem testis est repentinus, concinnat linguam mendacii. 

** Proverbs 12:20

Dolus in corde cogitantium mala ;  qui autem pacis ineunt consilia, sequitur eos gaudium. 

** Proverbs 12:21

Non contristabit justum quidquid ei acciderit :  impii autem replebuntur malo. 

** Proverbs 12:22

Abominatio est Domino labia mendacia ;  qui autem fideliter agunt placent ei. 

** Proverbs 12:23

Homo versatus celat scientiam,  et cor insipientium provocat stultitiam. 

** Proverbs 12:24

Manus fortium dominabitur ;  quæ autem remissa est, tributis serviet. 

** Proverbs 12:25

Mœror in corde viri humiliabit illum,  et sermone bono lætificabitur. 

** Proverbs 12:26

Qui negligit damnum propter amicum, justus est ;  iter autem impiorum decipiet eos. 

** Proverbs 12:27

Non inveniet fraudulentus lucrum,  et substantia hominis erit auri pretium. 

** Proverbs 12:28

In semita justitiæ vita ;  iter autem devium ducit ad mortem.  

* Proverbs 13

** Proverbs 13:1

Filius sapiens doctrina patris ;  qui autem illusor est non audit cum arguitur. 

** Proverbs 13:2

De fructu oris sui homo satiabitur bonis :  anima autem prævaricatorum iniqua. 

** Proverbs 13:3

Qui custodit os suum custodit animam suam ;  qui autem inconsideratus est ad loquendum, sentiet mala. 

** Proverbs 13:4

Vult et non vult piger ;  anima autem operantium impinguabitur. 

** Proverbs 13:5

Verbum mendax justus detestabitur ;  impius autem confundit, et confundetur. 

** Proverbs 13:6

Justitia custodit innocentis viam,  impietas autem peccatorem supplantat. 

** Proverbs 13:7

Est quasi dives, cum nihil habeat,  et est quasi pauper, cum in multis divitiis sit. 

** Proverbs 13:8

Redemptio animæ viri divitiæ suæ ;  qui autem pauper est, increpationem non sustinet. 

** Proverbs 13:9

Lux justorum lætificat :  lucerna autem impiorum extinguetur. 

** Proverbs 13:10

Inter superbos semper jurgia sunt ;  qui autem agunt omnia cum consilio, reguntur sapientia. 

** Proverbs 13:11

Substantia festinata minuetur ;  quæ autem paulatim colligitur manu, multiplicabitur. 

** Proverbs 13:12

Spes quæ differtur affligit animam ;  lignum vitæ desiderium veniens. 

** Proverbs 13:13

Qui detrahit alicui rei, ipse se in futurum obligat ;  qui autem timet præceptum, in pace versabitur.  Animæ dolosæ errant in peccatis :  justi autem misericordes sunt, et miserantur. 

** Proverbs 13:14

Lex sapientis fons vitæ,  ut declinet a ruina mortis. 

** Proverbs 13:15

Doctrina bona dabit gratiam ;  in itinere contemptorum vorago. 

** Proverbs 13:16

Astutus omnia agit cum consilio ;  qui autem fatuus est aperit stultitiam. 

** Proverbs 13:17

Nuntius impii cadet in malum ;  legatus autem fidelis, sanitas. 

** Proverbs 13:18

Egestas et ignominia ei qui deserit disciplinam ;  qui autem acquiescit arguenti glorificabitur. 

** Proverbs 13:19

Desiderium si compleatur delectat animam ;  detestantur stulti eos qui fugiunt mala. 

** Proverbs 13:20

Qui cum sapientibus graditur sapiens erit ;  amicus stultorum similis efficietur. 

** Proverbs 13:21

Peccatores persequitur malum,  et justis retribuentur bona. 

** Proverbs 13:22

Bonus reliquit hæredes filios et nepotes,  et custoditur justo substantia peccatoris. 

** Proverbs 13:23

Multi cibi in novalibus patrum,  et aliis congregantur absque judicio. 

** Proverbs 13:24

Qui parcit virgæ odit filium suum ;  qui autem diligit illum instanter erudit. 

** Proverbs 13:25

Justus comedit et replet animam suam ;  venter autem impiorum insaturabilis.  

* Proverbs 14

** Proverbs 14:1

Sapiens mulier ædificat domum suam ;  insipiens exstructam quoque manibus destruet. 

** Proverbs 14:2

Ambulans recto itinere, et timens Deum,  despicitur ab eo qui infami graditur via. 

** Proverbs 14:3

In ore stulti virga superbiæ ;  labia autem sapientium custodiunt eos. 

** Proverbs 14:4

Ubi non sunt boves, præsepe vacuum est ;  ubi autem plurimæ segetes, ibi manifesta est fortitudo bovis. 

** Proverbs 14:5

Testis fidelis non mentitur ;  profert autem mendacium dolosus testis. 

** Proverbs 14:6

Quærit derisor sapientiam, et non invenit ;  doctrina prudentium facilis. 

** Proverbs 14:7

Vade contra virum stultum,  et nescit labia prudentiæ. 

** Proverbs 14:8

Sapientia callidi est intelligere viam suam,  et imprudentia stultorum errans. 

** Proverbs 14:9

Stultus illudet peccatum,  et inter justos morabitur gratia. 

** Proverbs 14:10

Cor quod novit amaritudinem animæ suæ,  in gaudio ejus non miscebitur extraneus. 

** Proverbs 14:11

Domus impiorum delebitur :  tabernacula vero justorum germinabunt. 

** Proverbs 14:12

Est via quæ videtur homini justa,  novissima autem ejus deducunt ad mortem. 

** Proverbs 14:13

Risus dolore miscebitur,  et extrema gaudii luctus occupat. 

** Proverbs 14:14

Viis suis replebitur stultus,  et super eum erit vir bonus. 

** Proverbs 14:15

Innocens credit omni verbo ;  astutus considerat gressus suos.  Filio doloso nihil erit boni ;  servo autem sapienti prosperi erunt actus,  et dirigetur via ejus. 

** Proverbs 14:16

Sapiens timet, et declinat a malo ;  stultus transilit, et confidit. 

** Proverbs 14:17

Impatiens operabitur stultitiam,  et vir versutus odiosus est. 

** Proverbs 14:18

Possidebunt parvuli stultitiam,  et exspectabunt astuti scientiam. 

** Proverbs 14:19

Jacebunt mali ante bonos,  et impii ante portas justorum. 

** Proverbs 14:20

Etiam proximo suo pauper odiosus erit :  amici vero divitum multi. 

** Proverbs 14:21

Qui despicit proximum suum peccat ;  qui autem miseretur pauperis beatus erit.  Qui credit in Domino misericordiam diligit. 

** Proverbs 14:22

Errant qui operantur malum ;  misericordia et veritas præparant bona. 

** Proverbs 14:23

In omni opere erit abundantia ;  ubi autem verba sunt plurima, ibi frequenter egestas. 

** Proverbs 14:24

Corona sapientium divitiæ eorum ;  fatuitas stultorum imprudentia. 

** Proverbs 14:25

Liberat animas testis fidelis,  et profert mendacia versipellis. 

** Proverbs 14:26

In timore Domini fiducia fortitudinis,  et filiis ejus erit spes. 

** Proverbs 14:27

Timor Domini fons vitæ,  ut declinent a ruina mortis. 

** Proverbs 14:28

In multitudine populi dignitas regis,  et in paucitate plebis ignominia principis. 

** Proverbs 14:29

Qui patiens est multa gubernatur prudentia ;  qui autem impatiens est exaltat stultitiam suam. 

** Proverbs 14:30

Vita carnium sanitas cordis ;  putredo ossium invidia. 

** Proverbs 14:31

Qui calumniatur egentem exprobrat factori ejus ;  honorat autem eum qui miseretur pauperis. 

** Proverbs 14:32

In malitia sua expelletur impius :  sperat autem justus in morte sua. 

** Proverbs 14:33

In corde prudentis requiescit sapientia,  et indoctos quosque erudiet. 

** Proverbs 14:34

Justitia elevat gentem ;  miseros autem facit populos peccatum. 

** Proverbs 14:35

Acceptus est regi minister intelligens ;  iracundiam ejus inutilis sustinebit.  

* Proverbs 15

** Proverbs 15:1

Responsio mollis frangit iram ;  sermo durus suscitat furorem. 

** Proverbs 15:2

Lingua sapientium ornat scientiam ;  os fatuorum ebullit stultitiam. 

** Proverbs 15:3

In omni loco, oculi Domini  contemplantur bonos et malos. 

** Proverbs 15:4

Lingua placabilis lignum vitæ ;  quæ autem immoderata est conteret spiritum. 

** Proverbs 15:5

Stultus irridet disciplinam patris sui ;  qui autem custodit increpationes astutior fiet.  In abundanti justitia virtus maxima est :  cogitationes autem impiorum eradicabuntur. 

** Proverbs 15:6

Domus justi plurima fortitudo,  et in fructibus impii conturbatio. 

** Proverbs 15:7

Labia sapientium disseminabunt scientiam ;  cor stultorum dissimile erit. 

** Proverbs 15:8

Victimæ impiorum abominabiles Domino ;  vota justorum placabilia. 

** Proverbs 15:9

Abominatio est Domino via impii ;  qui sequitur justitiam diligitur ab eo. 

** Proverbs 15:10

Doctrina mala deserenti viam vitæ ;  qui increpationes odit, morietur. 

** Proverbs 15:11

Infernus et perditio coram Domino ;  quanto magis corda filiorum hominum ! 

** Proverbs 15:12

Non amat pestilens eum qui se corripit,  nec ad sapientes graditur. 

** Proverbs 15:13

Cor gaudens exhilarat faciem ;  in mœrore animi dejicitur spiritus. 

** Proverbs 15:14

Cor sapientis quærit doctrinam,  et os stultorum pascitur imperitia. 

** Proverbs 15:15

Omnes dies pauperis, mali ;  secura mens quasi juge convivium. 

** Proverbs 15:16

Melius est parum cum timore Domini,  quam thesauri magni et insatiabiles. 

** Proverbs 15:17

Melius est vocari ad olera cum caritate,  quam ad vitulum saginatum cum odio. 

** Proverbs 15:18

Vir iracundus provocat rixas ;  qui patiens est mitigat suscitatas. 

** Proverbs 15:19

Iter pigrorum quasi sepes spinarum ;  via justorum absque offendiculo. 

** Proverbs 15:20

Filius sapiens lætificat patrem,  et stultus homo despicit matrem suam. 

** Proverbs 15:21

Stultitia gaudium stulto,  et vir prudens dirigit gressus suos. 

** Proverbs 15:22

Dissipantur cogitationes ubi non est consilium ;  ubi vero sunt plures consiliarii, confirmantur. 

** Proverbs 15:23

Lætatur homo in sententia oris sui,  et sermo opportunus est optimus. 

** Proverbs 15:24

Semita vitæ super eruditum,  ut declinet de inferno novissimo. 

** Proverbs 15:25

Domum superborum demolietur Dominus,  et firmos faciet terminos viduæ. 

** Proverbs 15:26

Abominatio Domini cogitationes malæ,  et purus sermo pulcherrimus firmabitur ab eo. 

** Proverbs 15:27

Conturbat domum suam qui sectatur avaritiam ;  qui autem odit munera, vivet.  Per misericordiam et fidem purgantur peccata :  per timorem autem Domini declinat omnis a malo. 

** Proverbs 15:28

Mens justi meditatur obedientiam ;  os impiorum redundat malis. 

** Proverbs 15:29

Longe est Dominus ab impiis,  et orationes justorum exaudiet. 

** Proverbs 15:30

Lux oculorum lætificat animam ;  fama bona impinguat ossa. 

** Proverbs 15:31

Auris quæ audit increpationes vitæ  in medio sapientium commorabitur. 

** Proverbs 15:32

Qui abjicit disciplinam despicit animam suam ;  qui autem acquiescit increpationibus possessor est cordis. 

** Proverbs 15:33

Timor Domini disciplina sapientiæ,  et gloriam præcedit humilitas.  

* Proverbs 16

** Proverbs 16:1

Hominis est animam præparare,  et Domini gubernare linguam. 

** Proverbs 16:2

Omnes viæ hominis patent oculis ejus ;  spirituum ponderator est Dominus. 

** Proverbs 16:3

Revela Domino opera tua,  et dirigentur cogitationes tuæ. 

** Proverbs 16:4

Universa propter semetipsum operatus est Dominus ;  impium quoque ad diem malum. 

** Proverbs 16:5

Abominatio Domini est omnis arrogans ;  etiamsi manus ad manum fuerit, non est innocens.  Initium viæ bonæ facere justitiam ;  accepta est autem apud Deum magis quam immolare hostias. 

** Proverbs 16:6

Misericordia et veritate redimitur iniquitas,  et in timore Domini declinatur a malo. 

** Proverbs 16:7

Cum placuerint Domino viæ hominis,  inimicos quoque ejus convertet ad pacem. 

** Proverbs 16:8

Melius est parum cum justitia  quam multi fructus cum iniquitate. 

** Proverbs 16:9

Cor hominis disponit viam suam,  sed Domini est dirigere gressus ejus. 

** Proverbs 16:10

Divinatio in labiis regis ;  in judicio non errabit os ejus. 

** Proverbs 16:11

Pondus et statera judicia Domini sunt,  et opera ejus omnes lapides sacculi. 

** Proverbs 16:12

Abominabiles regi qui agunt impie,  quoniam justitia firmatur solium. 

** Proverbs 16:13

Voluntas regum labia justa ;  qui recta loquitur diligetur. 

** Proverbs 16:14

Indignatio regis nuntii mortis,  et vir sapiens placabit eam. 

** Proverbs 16:15

In hilaritate vultus regis vita,  et clementia ejus quasi imber serotinus. 

** Proverbs 16:16

Posside sapientiam, quia auro melior est,  et acquire prudentiam, quia pretiosior est argento. 

** Proverbs 16:17

Semita justorum declinat mala ;  custos animæ suæ servat viam suam. 

** Proverbs 16:18

Contritionem præcedit superbia,  et ante ruinam exaltatur spiritus. 

** Proverbs 16:19

Melius est humiliari cum mitibus  quam dividere spolia cum superbis. 

** Proverbs 16:20

Eruditus in verbo reperiet bona,  et qui sperat in Domino beatus est. 

** Proverbs 16:21

Qui sapiens est corde appellabitur prudens,  et qui dulcis eloquio majora percipiet. 

** Proverbs 16:22

Fons vitæ eruditio possidentis ;  doctrina stultorum fatuitas. 

** Proverbs 16:23

Cor sapientis erudiet os ejus,  et labiis ejus addet gratiam. 

** Proverbs 16:24

Favus mellis composita verba ;  dulcedo animæ sanitas ossium. 

** Proverbs 16:25

Est via quæ videtur homini recta,  et novissima ejus ducunt ad mortem. 

** Proverbs 16:26

Anima laborantis laborat sibi,  quia compulit eum os suum. 

** Proverbs 16:27

Vir impius fodit malum,  et in labiis ejus ignis ardescit. 

** Proverbs 16:28

Homo perversus suscitat lites,  et verbosus separat principes. 

** Proverbs 16:29

Vir iniquus lactat amicum suum,  et ducit eum per viam non bonam. 

** Proverbs 16:30

Qui attonitis oculis cogitat prava,  mordens labia sua perficit malum. 

** Proverbs 16:31

Corona dignitatis senectus,  quæ in viis justitiæ reperietur. 

** Proverbs 16:32

Melior est patiens viro forti,  et qui dominatur animo suo expugnatore urbium. 

** Proverbs 16:33

Sortes mittuntur in sinum,  sed a Domino temperantur.  

* Proverbs 17

** Proverbs 17:1

Melior est buccella sicca cum gaudio  quam domus plena victimis cum jurgio. 

** Proverbs 17:2

Servus sapiens dominabitur filiis stultis,  et inter fratres hæreditatem dividet. 

** Proverbs 17:3

Sicut igne probatur argentum et aurum camino,  ita corda probat Dominus. 

** Proverbs 17:4

Malus obedit linguæ iniquæ,  et fallax obtemperat labiis mendacibus. 

** Proverbs 17:5

Qui despicit pauperem exprobrat factori ejus,  et qui ruina lætatur alterius non erit impunitus. 

** Proverbs 17:6

Corona senum filii filiorum,  et gloria filiorum patres eorum. 

** Proverbs 17:7

Non decent stultum verba composita,  nec principem labium mentiens. 

** Proverbs 17:8

Gemma gratissima exspectatio præstolantis ;  quocumque se vertit, prudenter intelligit. 

** Proverbs 17:9

Qui celat delictum quærit amicitias ;  qui altero sermone repetit, separat fœderatos. 

** Proverbs 17:10

Plus proficit correptio apud prudentem,  quam centum plagæ apud stultum. 

** Proverbs 17:11

Semper jurgia quærit malus :  angelus autem crudelis mittetur contra eum. 

** Proverbs 17:12

Expedit magis ursæ occurrere raptis fœtibus,  quam fatuo confidenti in stultitia sua. 

** Proverbs 17:13

Qui reddit mala pro bonis,  non recedet malum de domo ejus. 

** Proverbs 17:14

Qui dimittit aquam caput est jurgiorum,  et antequam patiatur contumeliam judicium deserit. 

** Proverbs 17:15

Qui justificat impium, et qui condemnat justum,  abominabilis est uterque apud Deum. 

** Proverbs 17:16

Quid prodest stulto habere divitias,  cum sapientiam emere non possit ?  Qui altum facit domum suam quærit ruinam,  et qui evitat discere incidet in mala. 

** Proverbs 17:17

Omni tempore diligit qui amicus est,  et frater in angustiis comprobatur. 

** Proverbs 17:18

Stultus homo plaudet manibus,  cum spoponderit pro amico suo. 

** Proverbs 17:19

Qui meditatur discordias diligit rixas,  et qui exaltat ostium quærit ruinam. 

** Proverbs 17:20

Qui perversi cordis est non inveniet bonum,  et qui vertit linguam incidet in malum. 

** Proverbs 17:21

Natus est stultus in ignominiam suam ;  sed nec pater in fatuo lætabitur. 

** Proverbs 17:22

Animus gaudens ætatem floridam facit ;  spiritus tristis exsiccat ossa. 

** Proverbs 17:23

Munera de sinu impius accipit,  ut pervertat semitas judicii. 

** Proverbs 17:24

In facie prudentis lucet sapientia ;  oculi stultorum in finibus terræ. 

** Proverbs 17:25

Ira patris filius stultus,  et dolor matris quæ genuit eum. 

** Proverbs 17:26

Non est bonum damnum inferre justo,  nec percutere principem qui recta judicat. 

** Proverbs 17:27

Qui moderatur sermones suos doctus et prudens est,  et pretiosi spiritus vir eruditus. 

** Proverbs 17:28

Stultus quoque, si tacuerit, sapiens reputabitur,  et si compresserit labia sua, intelligens.  

* Proverbs 18

** Proverbs 18:1

Occasiones quærit qui vult recedere ab amico :  omni tempore erit exprobrabilis. 

** Proverbs 18:2

Non recipit stultus verba prudentiæ,  nisi ea dixeris quæ versantur in corde ejus. 

** Proverbs 18:3

Impius, cum in profundum venerit peccatorum, contemnit ;  sed sequitur eum ignominia et opprobrium. 

** Proverbs 18:4

Aqua profunda verba ex ore viri,  et torrens redundans fons sapientiæ. 

** Proverbs 18:5

Accipere personam impii non est bonum,  ut declines a veritate judicii. 

** Proverbs 18:6

Labia stulti miscent se rixis,  et os ejus jurgia provocat. 

** Proverbs 18:7

Os stulti contritio ejus,  et labia ipsius ruina animæ ejus. 

** Proverbs 18:8

Verba bilinguis quasi simplicia,  et ipsa perveniunt usque ad interiora ventris.  Pigrum dejicit timor ;  animæ autem effeminatorum esurient. 

** Proverbs 18:9

Qui mollis et dissolutus est in opere suo  frater est sua opera dissipantis. 

** Proverbs 18:10

Turris fortissima nomen Domini ;  ad ipsum currit justus, et exaltabitur. 

** Proverbs 18:11

Substantia divitis urbs roboris ejus,  et quasi murus validus circumdans eum. 

** Proverbs 18:12

Antequam conteratur, exaltatur cor hominis,  et antequam glorificetur, humiliatur. 

** Proverbs 18:13

Qui prius respondet quam audiat,  stultum se esse demonstrat, et confusione dignum. 

** Proverbs 18:14

Spiritus viri sustentat imbecillitatem suam ;  spiritum vero ad irascendum facilem quis poterit sustinere ? 

** Proverbs 18:15

Cor prudens possidebit scientiam,  et auris sapientium quærit doctrinam. 

** Proverbs 18:16

Donum hominis dilatat viam ejus,  et ante principes spatium ei facit. 

** Proverbs 18:17

Justus prior est accusator sui :  venit amicus ejus, et investigabit eum. 

** Proverbs 18:18

Contradictiones comprimit sors,  et inter potentes quoque dijudicat. 

** Proverbs 18:19

Frater qui adjuvatur a fratre quasi civitas firma,  et judicia quasi vectes urbium. 

** Proverbs 18:20

De fructu oris viri replebitur venter ejus,  et genimina labiorum ipsius saturabunt eum. 

** Proverbs 18:21

Mors et vita in manu linguæ ;  qui diligunt eam comedent fructus ejus. 

** Proverbs 18:22

Qui invenit mulierem bonam invenit bonum,  et hauriet jucunditatem a Domino.  Qui expellit mulierem bonam expellit bonum ;  qui autem tenet adulteram stultus est et impius. 

** Proverbs 18:23

Cum obsecrationibus loquetur pauper,  et dives effabitur rigide. 

** Proverbs 18:24

Vir amabilis ad societatem  magis amicus erit quam frater.  

* Proverbs 19

** Proverbs 19:1

Melior est pauper qui ambulat in simplicitate sua  quam dives torquens labia sua, et insipiens. 

** Proverbs 19:2

Ubi non est scientia animæ, non est bonum,  et qui festinus est pedibus offendet. 

** Proverbs 19:3

Stultitia hominis supplantat gressus ejus,  et contra Deum fervet animo suo. 

** Proverbs 19:4

Divitiæ addunt amicos plurimos ;  a paupere autem et hi quos habuit separantur. 

** Proverbs 19:5

Testis falsus non erit impunitus,  et qui mendacia loquitur non effugiet. 

** Proverbs 19:6

Multi colunt personam potentis,  et amici sunt dona tribuentis. 

** Proverbs 19:7

Fratres hominis pauperis oderunt eum ;  insuper et amici procul recesserunt ab eo.      Qui tantum verba sectatur nihil habebit ; 

** Proverbs 19:8

qui autem possessor est mentis diligit animam suam,  et custos prudentiæ inveniet bona. 

** Proverbs 19:9

Falsus testis non erit impunitus,  et qui loquitur mendacia peribit. 

** Proverbs 19:10

Non decent stultum deliciæ,  nec servum dominari principibus. 

** Proverbs 19:11

Doctrina viri per patientiam noscitur,  et gloria ejus est iniqua prætergredi. 

** Proverbs 19:12

Sicut fremitus leonis, ita et regis ira,  et sicut ros super herbam, ita et hilaritas ejus. 

** Proverbs 19:13

Dolor patris filius stultus,  et tecta jugiter perstillantia litigiosa mulier. 

** Proverbs 19:14

Domus et divitiæ dantur a parentibus ;  a Domino autem proprie uxor prudens. 

** Proverbs 19:15

Pigredo immittit soporem,  et anima dissoluta esuriet. 

** Proverbs 19:16

Qui custodit mandatum custodit animam suam ;  qui autem negligit viam suam mortificabitur. 

** Proverbs 19:17

Fœneratur Domino qui miseretur pauperis,  et vicissitudinem suam reddet ei. 

** Proverbs 19:18

Erudi filium tuum ; ne desperes :  ad interfectionem autem ejus ne ponas animam tuam. 

** Proverbs 19:19

Qui impatiens est sustinebit damnum,  et cum rapuerit, aliud apponet. 

** Proverbs 19:20

Audi consilium, et suscipe disciplinam,  ut sis sapiens in novissimis tuis. 

** Proverbs 19:21

Multæ cogitationes in corde viri ;  voluntas autem Domini permanebit. 

** Proverbs 19:22

Homo indigens misericors est,  et melior est pauper quam vir mendax. 

** Proverbs 19:23

Timor Domini ad vitam,  et in plenitudine commorabitur absque visitatione pessima. 

** Proverbs 19:24

Abscondit piger manum suam sub ascella,  nec ad os suum applicat eam. 

** Proverbs 19:25

Pestilente flagellato stultus sapientior erit ;  si autem corripueris sapientem, intelliget disciplinam. 

** Proverbs 19:26

Qui affligit patrem, et fugat matrem,  ignominiosus est et infelix. 

** Proverbs 19:27

Non cesses, fili, audire doctrinam,  nec ignores sermones scientiæ. 

** Proverbs 19:28

Testis iniquus deridet judicium,  et os impiorum devorat iniquitatem. 

** Proverbs 19:29

Parata sunt derisoribus judicia,  et mallei percutientes stultorum corporibus.  

* Proverbs 20

** Proverbs 20:1

Luxuriosa res vinum, et tumultuosa ebrietas :  quicumque his delectatur non erit sapiens. 

** Proverbs 20:2

Sicut rugitus leonis, ita et terror regis :  qui provocat eum peccat in animam suam. 

** Proverbs 20:3

Honor est homini qui separat se a contentionibus ;  omnes autem stulti miscentur contumeliis. 

** Proverbs 20:4

Propter frigus piger arare noluit ;  mendicabit ergo æstate, et non dabitur illi. 

** Proverbs 20:5

Sicut aqua profunda, sic consilium in corde viri ;  sed homo sapiens exhauriet illud. 

** Proverbs 20:6

Multi homines misericordes vocantur ;  virum autem fidelem quis inveniet ? 

** Proverbs 20:7

Justus qui ambulat in simplicitate sua  beatos post se filios derelinquet. 

** Proverbs 20:8

Rex qui sedet in solio judicii  dissipat omne malum intuitu suo. 

** Proverbs 20:9

Quis potest dicere : Mundum est cor meum ;  purus sum a peccato ? 

** Proverbs 20:10

Pondus et pondus, mensura et mensura :  utrumque abominabile est apud Deum. 

** Proverbs 20:11

Ex studiis suis intelligitur puer,  si munda et recta sint opera ejus. 

** Proverbs 20:12

Aurem audientem, et oculum videntem :  Dominus fecit utrumque. 

** Proverbs 20:13

Noli diligere somnum, ne te egestas opprimat :  aperi oculos tuos, et saturare panibus. 

** Proverbs 20:14

Malum est, malum est, dicit omnis emptor ;  et cum recesserit, tunc gloriabitur. 

** Proverbs 20:15

Est aurum et multitudo gemmarum,  et vas pretiosum labia scientiæ. 

** Proverbs 20:16

Tolle vestimentum ejus qui fidejussor extitit alieni,  et pro extraneis aufer pignus ab eo. 

** Proverbs 20:17

Suavis est homini panis mendacii,  et postea implebitur os ejus calculo. 

** Proverbs 20:18

Cogitationes consiliis roborantur,  et gubernaculis tractanda sunt bella. 

** Proverbs 20:19

Ei qui revelat mysteria, et ambulat fraudulenter,  et dilatat labia sua, ne commiscearis. 

** Proverbs 20:20

Qui maledicit patri suo et matri,  extinguetur lucerna ejus in mediis tenebris : 

** Proverbs 20:21

hæreditas ad quam festinatur in principio,  in novissimo benedictione carebit. 

** Proverbs 20:22

Ne dicas : Reddam malum :  exspecta Dominum, et liberabit te. 

** Proverbs 20:23

Abominatio est apud Dominum pondus et pondus ;  statera dolosa non est bona. 

** Proverbs 20:24

A Domino diriguntur gressus viri :  quis autem hominum intelligere potest viam suam ? 

** Proverbs 20:25

Ruina est homini devorare sanctos,  et post vota retractare. 

** Proverbs 20:26

Dissipat impios rex sapiens,  et incurvat super eos fornicem. 

** Proverbs 20:27

Lucerna Domini spiraculum hominis,  quæ investigat omnia secreta ventris. 

** Proverbs 20:28

Misericordia et veritas custodiunt regem,  et roboratur clementia thronus ejus. 

** Proverbs 20:29

Exsultatio juvenum fortitudo eorum,  et dignitas senum canities. 

** Proverbs 20:30

Livor vulneris absterget mala,  et plagæ in secretioribus ventris.  

* Proverbs 21

** Proverbs 21:1

Sicut divisiones aquarum, ita cor regis in manu Domini :  quocumque voluerit, inclinabit illud. 

** Proverbs 21:2

Omnis via viri recta sibi videtur :  appendit autem corda Dominus. 

** Proverbs 21:3

Facere misericordiam et judicium  magis placet Domino quam victimæ. 

** Proverbs 21:4

Exaltatio oculorum est dilatatio cordis ;  lucerna impiorum peccatum. 

** Proverbs 21:5

Cogitationes robusti semper in abundantia ;  omnis autem piger semper in egestate est. 

** Proverbs 21:6

Qui congregat thesauros lingua mendacii vanus et excors est,  et impingetur ad laqueos mortis. 

** Proverbs 21:7

Rapinæ impiorum detrahent eos,  quia noluerunt facere judicium. 

** Proverbs 21:8

Perversa via viri aliena est ;  qui autem mundus est, rectum opus ejus. 

** Proverbs 21:9

Melius est sedere in angulo domatis,  quam cum muliere litigiosa, et in domo communi. 

** Proverbs 21:10

Anima impii desiderat malum :  non miserebitur proximo suo. 

** Proverbs 21:11

Mulctato pestilente, sapientior erit parvulus,  et si sectetur sapientem, sumet scientiam. 

** Proverbs 21:12

Excogitat justus de domo impii,  ut detrahat impios a malo. 

** Proverbs 21:13

Qui obturat aurem suam ad clamorem pauperis,  et ipse clamabit, et non exaudietur. 

** Proverbs 21:14

Munus absconditum extinguit iras,  et donum in sinu indignationem maximam. 

** Proverbs 21:15

Gaudium justo est facere judicium,  et pavor operantibus iniquitatem. 

** Proverbs 21:16

Vir qui erraverit a via doctrinæ  in cœtu gigantum commorabitur. 

** Proverbs 21:17

Qui diligit epulas in egestate erit ;  qui amat vinum et pinguia non ditabitur. 

** Proverbs 21:18

Pro justo datur impius,  et pro rectis iniquus. 

** Proverbs 21:19

Melius est habitare in terra deserta  quam cum muliere rixosa et iracunda. 

** Proverbs 21:20

Thesaurus desiderabilis, et oleum in habitaculo justi :  et imprudens homo dissipabit illud. 

** Proverbs 21:21

Qui sequitur justitiam et misericordiam  inveniet vitam, justitiam, et gloriam. 

** Proverbs 21:22

Civitatem fortium ascendit sapiens,  et destruxit robur fiduciæ ejus. 

** Proverbs 21:23

Qui custodit os suum et linguam suam  custodit ab angustiis animam suam. 

** Proverbs 21:24

Superbus et arrogans vocatur indoctus,  qui in ira operatur superbiam. 

** Proverbs 21:25

Desideria occidunt pigrum :  noluerunt enim quidquam manus ejus operari. 

** Proverbs 21:26

Tota die concupiscit et desiderat ;  qui autem justus est, tribuet, et non cessabit. 

** Proverbs 21:27

Hostiæ impiorum abominabiles,  quia offeruntur ex scelere. 

** Proverbs 21:28

Testis mendax peribit ;  vir obediens loquetur victoriam. 

** Proverbs 21:29

Vir impius procaciter obfirmat vultum suum ;  qui autem rectus est corrigit viam suam. 

** Proverbs 21:30

Non est sapientia, non est prudentia,  non est consilium contra Dominum. 

** Proverbs 21:31

Equus paratur ad diem belli ;  Dominus autem salutem tribuit.  

* Proverbs 22

** Proverbs 22:1

Melius est nomen bonum quam divitiæ multæ ;  super argentum et aurum gratia bona. 

** Proverbs 22:2

Dives et pauper obviaverunt sibi :  utriusque operator est Dominus. 

** Proverbs 22:3

Callidus vidit malum, et abscondit se ;  innocens pertransiit, et afflictus est damno. 

** Proverbs 22:4

Finis modestiæ timor Domini,  divitiæ, et gloria, et vita. 

** Proverbs 22:5

Arma et gladii in via perversi ;  custos autem animæ suæ longe recedit ab eis. 

** Proverbs 22:6

Proverbium est : adolescens juxta viam suam ;  etiam cum senuerit, non recedet ab ea. 

** Proverbs 22:7

Dives pauperibus imperat,  et qui accipit mutuum servus est fœnerantis. 

** Proverbs 22:8

Qui seminat iniquitatem metet mala,  et virga iræ suæ consummabitur. 

** Proverbs 22:9

Qui pronus est ad misericordiam benedicetur :  de panibus enim suis dedit pauperi.  Victoriam et honorem acquiret qui dat munera ;  animam autem aufert accipientium. 

** Proverbs 22:10

Ejice derisorem, et exibit cum eo jurgium,  cessabuntque causæ et contumeliæ. 

** Proverbs 22:11

Qui diligit cordis munditiam,  propter gratiam labiorum suorum habebit amicum regem. 

** Proverbs 22:12

Oculi Domini custodiunt scientiam,  et supplantantur verba iniqui. 

** Proverbs 22:13

Dicit piger : Leo est foris ;  in medio platearum occidendus sum. 

** Proverbs 22:14

Fovea profunda os alienæ :  cui iratus est Dominus, incidet in eam. 

** Proverbs 22:15

Stultitia colligata est in corde pueri,  et virga disciplinæ fugabit eam. 

** Proverbs 22:16

Qui calumniatur pauperem ut augeat divitias suas,  dabit ipse ditiori, et egebit. 

** Proverbs 22:17

Inclina aurem tuam, et audi verba sapientium :  appone autem cor ad doctrinam meam, 

** Proverbs 22:18

quæ pulchra erit tibi cum servaveris eam in ventre tuo,  et redundabit in labiis tuis : 

** Proverbs 22:19

ut sit in Domino fiducia tua,  unde et ostendi eam tibi hodie. 

** Proverbs 22:20

Ecce descripsi eam tibi tripliciter,  in cogitationibus et scientia : 

** Proverbs 22:21

ut ostenderem tibi firmitatem et eloquia veritatis,  respondere ex his illis qui miserunt te. 

** Proverbs 22:22

Non facias violentiam pauperi quia pauper est,  neque conteras egenum in porta : 

** Proverbs 22:23

quia judicabit Dominus causam ejus,  et configet eos qui confixerunt animam ejus. 

** Proverbs 22:24

Noli esse amicus homini iracundo,  neque ambules cum viro furioso : 

** Proverbs 22:25

ne forte discas semitas ejus,  et sumas scandalum animæ tuæ. 

** Proverbs 22:26

Noli esse cum his qui defigunt manus suas,  et qui vades se offerunt pro debitis : 

** Proverbs 22:27

si enim non habes unde restituas,  quid causæ est ut tollat operimentum de cubili tuo ? 

** Proverbs 22:28

Ne transgrediaris terminos antiquos,  quos posuerunt patres tui. 

** Proverbs 22:29

Vidisti virum velocem in opere suo ?  coram regibus stabit, nec erit ante ignobiles.  

* Proverbs 23

** Proverbs 23:1

Quando sederis ut comedas cum principe,  diligenter attende quæ apposita sunt ante faciem tuam. 

** Proverbs 23:2

Et statue cultrum in gutture tuo :  si tamen habes in potestate animam tuam. 

** Proverbs 23:3

Ne desideres de cibis ejus,  in quo est panis mendacii. 

** Proverbs 23:4

Noli laborare ut diteris,  sed prudentiæ tuæ pone modum. 

** Proverbs 23:5

Ne erigas oculos tuos ad opes quas non potes habere,  quia facient sibi pennas quasi aquilæ, et volabunt in cælum. 

** Proverbs 23:6

Ne comedas cum homine invido,  et ne desideres cibos ejus : 

** Proverbs 23:7

quoniam in similitudinem arioli et conjectoris  æstimat quod ignorat.  Comede et bibe, dicet tibi ;  et mens ejus non est tecum. 

** Proverbs 23:8

Cibos quos comederas evomes,  et perdes pulchros sermones tuos. 

** Proverbs 23:9

In auribus insipientium ne loquaris,  qui despicient doctrinam eloquii tui. 

** Proverbs 23:10

Ne attingas parvulorum terminos,  et agrum pupillorum ne introëas : 

** Proverbs 23:11

propinquus enim illorum fortis est,  et ipse judicabit contra te causam illorum. 

** Proverbs 23:12

Ingrediatur ad doctrinam cor tuum,  et aures tuæ ad verba scientiæ. 

** Proverbs 23:13

Noli subtrahere a puero disciplinam :  si enim percusseris eum virga, non morietur. 

** Proverbs 23:14

Tu virga percuties eum,  et animam ejus de inferno liberabis. 

** Proverbs 23:15

Fili mi, si sapiens fuerit animus tuus,  gaudebit tecum cor meum : 

** Proverbs 23:16

et exsultabunt renes mei,  cum locuta fuerint rectum labia tua. 

** Proverbs 23:17

Non æmuletur cor tuum peccatores,  sed in timore Domini esto tota die : 

** Proverbs 23:18

quia habebis spem in novissimo,  et præstolatio tua non auferetur. 

** Proverbs 23:19

Audi, fili mi, et esto sapiens,  et dirige in via animum tuum. 

** Proverbs 23:20

Noli esse in conviviis potatorum,  nec in comessationibus eorum qui carnes ad vescendum conferunt : 

** Proverbs 23:21

quia vacantes potibus et dantes symbola consumentur,  et vestietur pannis dormitatio. 

** Proverbs 23:22

Audi patrem tuum, qui genuit te,  et ne contemnas cum senuerit mater tua. 

** Proverbs 23:23

Veritatem eme, et noli vendere sapientiam,  et doctrinam, et intelligentiam. 

** Proverbs 23:24

Exsultat gaudio pater justi ;  qui sapientem genuit, lætabitur in eo. 

** Proverbs 23:25

Gaudeat pater tuus et mater tua,  et exsultet quæ genuit te. 

** Proverbs 23:26

Præbe, fili mi, cor tuum mihi,  et oculi tui vias meas custodiant. 

** Proverbs 23:27

Fovea enim profunda est meretrix,  et puteus angustus aliena. 

** Proverbs 23:28

Insidiatur in via quasi latro,  et quos incautos viderit, interficiet. 

** Proverbs 23:29

Cui væ ? cujus patri væ ?  cui rixæ ? cui foveæ ?  cui sine causa vulnera ? cui suffusio oculorum ? 

** Proverbs 23:30

nonne his qui commorantur in vino,  et student calicibus epotandis ? 

** Proverbs 23:31

Ne intuearis vinum quando flavescit,  cum splenduerit in vitro color ejus :  ingreditur blande, 

** Proverbs 23:32

sed in novissimo mordebit ut coluber,  et sicut regulus venena diffundet. 

** Proverbs 23:33

Oculi tui videbunt extraneas,  et cor tuum loquetur perversa. 

** Proverbs 23:34

Et eris sicut dormiens in medio mari,  et quasi sopitus gubernator, amisso clavo. 

** Proverbs 23:35

Et dices : Verberaverunt me, sed non dolui ;  traxerunt me, et ego non sensi.  Quando evigilabo, et rursus vina reperiam ?  

* Proverbs 24

** Proverbs 24:1

Ne æmuleris viros malos,  nec desideres esse cum eis : 

** Proverbs 24:2

quia rapinas meditatur mens eorum,  et fraudes labia eorum loquuntur. 

** Proverbs 24:3

Sapientia ædificabitur domus,  et prudentia roborabitur. 

** Proverbs 24:4

In doctrina replebuntur cellaria,  universa substantia pretiosa et pulcherrima. 

** Proverbs 24:5

Vir sapiens fortis est,  et vir doctus robustus et validus : 

** Proverbs 24:6

quia cum dispositione initur bellum,  et erit salus ubi multa consilia sunt. 

** Proverbs 24:7

Excelsa stulto sapientia ;  in porta non aperiet os suum. 

** Proverbs 24:8

Qui cogitat mala facere stultus vocabitur : 

** Proverbs 24:9

cogitatio stulti peccatum est,  et abominatio hominum detractor. 

** Proverbs 24:10

Si desperaveris lassus in die angustiæ,  imminuetur fortitudo tua. 

** Proverbs 24:11

Erue eos qui ducuntur ad mortem,  et qui trahuntur ad interitum, liberare ne cesses. 

** Proverbs 24:12

Si dixeris : Vires non suppetunt ;  qui inspector est cordis ipse intelligit :  et servatorem animæ tuæ nihil fallit,  reddetque homini juxta opera sua. 

** Proverbs 24:13

Comede, fili mi, mel, quia bonum est,  et favum dulcissimum gutturi tuo. 

** Proverbs 24:14

Sic et doctrina sapientiæ animæ tuæ :  quam cum inveneris, habebis in novissimis spem,  et spes tua non peribit. 

** Proverbs 24:15

Ne insidieris, et quæras impietatem in domo justi,  neque vastes requiem ejus. 

** Proverbs 24:16

Septies enim cadet justus, et resurget :  impii autem corruent in malum. 

** Proverbs 24:17

Cum ceciderit inimicus tuus ne gaudeas,  et in ruina ejus ne exsultet cor tuum : 

** Proverbs 24:18

ne forte videat Dominus, et displiceat ei,  et auferat ab eo iram suam. 

** Proverbs 24:19

Ne contendas cum pessimis,  nec æmuleris impios : 

** Proverbs 24:20

quoniam non habent futurorum spem mali,  et lucerna impiorum extinguetur. 

** Proverbs 24:21

Time Dominum, fili mi, et regem,  et cum detractoribus non commiscearis : 

** Proverbs 24:22

quoniam repente consurget perditio eorum,  et ruinam utriusque quis novit ?  

** Proverbs 24:23

Hæc quoque sapientibus.   Cognoscere personam in judicio non est bonum. 

** Proverbs 24:24

Qui dicunt impio : Justus es : maledicent eis populi,  et detestabuntur eos tribus. 

** Proverbs 24:25

Qui arguunt eum laudabuntur,  et super ipsos veniet benedictio. 

** Proverbs 24:26

Labia deosculabitur  qui recta verba respondet. 

** Proverbs 24:27

Præpara foris opus tuum,  et diligenter exerce agrum tuum,  ut postea ædifices domum tuam. 

** Proverbs 24:28

Ne sis testis frustra contra proximum tuum,  nec lactes quemquam labiis tuis. 

** Proverbs 24:29

Ne dicas : Quomodo fecit mihi, sic faciam ei ;  reddam unicuique secundum opus suum. 

** Proverbs 24:30

Per agrum hominis pigri transivi,  et per vineam viri stulti : 

** Proverbs 24:31

et ecce totum repleverant urticæ,  et operuerant superficiem ejus spinæ,  et maceria lapidum destructa erat. 

** Proverbs 24:32

Quod cum vidissem, posui in corde meo,  et exemplo didici disciplinam. 

** Proverbs 24:33

Parum, inquam, dormies, modicum dormitabis ;  pauxillum manus conseres ut quiescas : 

** Proverbs 24:34

et veniet tibi quasi cursor egestas,  et mendicitas quasi vir armatus.  

* Proverbs 25

** Proverbs 25:1

Hæ quoque parabolæ Salomonis, quas transtulerunt viri Ezechiæ regis Juda.  

** Proverbs 25:2

Gloria Dei est celare verbum,  et gloria regum investigare sermonem. 

** Proverbs 25:3

Cælum sursum, et terra deorsum,  et cor regum inscrutabile. 

** Proverbs 25:4

Aufer rubiginem de argento,  et egredietur vas purissimum. 

** Proverbs 25:5

Aufer impietatem de vultu regis,  et firmabitur justitia thronus ejus. 

** Proverbs 25:6

Ne gloriosus appareas coram rege,  et in loco magnorum ne steteris. 

** Proverbs 25:7

Melius est enim ut dicatur tibi : Ascende huc,  quam ut humilieris coram principe. 

** Proverbs 25:8

Quæ viderunt oculi tui ne proferas in jurgio cito,  ne postea emendare non possis,  cum dehonestaveris amicum tuum. 

** Proverbs 25:9

Causam tuam tracta cum amico tuo,  et secretum extraneo ne reveles : 

** Proverbs 25:10

ne forte insultet tibi cum audierit,  et exprobrare non cesset.  Gratia et amicitia liberant :  quas tibi serva, ne exprobrabilis fias. 

** Proverbs 25:11

Mala aurea in lectis argenteis,  qui loquitur verbum in tempore suo. 

** Proverbs 25:12

Inauris aurea, et margaritum fulgens,  qui arguit sapientem et aurem obedientem. 

** Proverbs 25:13

Sicut frigus nivis in die messis,  ita legatus fidelis ei qui misit eum :  animam ipsius requiescere facit. 

** Proverbs 25:14

Nubes, et ventus, et pluviæ non sequentes,  vir gloriosus et promissa non complens. 

** Proverbs 25:15

Patientia lenietur princeps,  et lingua mollis confringet duritiam. 

** Proverbs 25:16

Mel invenisti : comede quod sufficit tibi,  ne forte satiatus evomas illud. 

** Proverbs 25:17

Subtrahe pedem tuum de domo proximi tui,  nequando satiatus oderit te. 

** Proverbs 25:18

Jaculum, et gladius, et sagitta acuta,  homo qui loquitur contra proximum suum falsum testimonium. 

** Proverbs 25:19

Dens putridus, et pes lassus,  qui sperat super infideli in die angustiæ, 

** Proverbs 25:20

et amittit pallium in die frigoris.  Acetum in nitro,  qui cantat carmina cordi pessimo.  Sicut tinea vestimento, et vermis ligno,  ita tristitia viri nocet cordi. 

** Proverbs 25:21

Si esurierit inimicus tuus, ciba illum ;  si sitierit, da ei aquam bibere : 

** Proverbs 25:22

prunas enim congregabis super caput ejus,  et Dominus reddet tibi. 

** Proverbs 25:23

Ventus aquilo dissipat pluvias,  et facies tristis linguam detrahentem. 

** Proverbs 25:24

Melius est sedere in angulo domatis  quam cum muliere litigiosa et in domo communi. 

** Proverbs 25:25

Aqua frigida animæ sitienti,  et nuntius bonus de terra longinqua. 

** Proverbs 25:26

Fons turbatus pede et vena corrupta,  justus cadens coram impio. 

** Proverbs 25:27

Sicut qui mel multum comedit non est ei bonum,  sic qui scrutator est majestatis opprimetur a gloria. 

** Proverbs 25:28

Sicut urbs patens et absque murorum ambitu,  ita vir qui non potest in loquendo cohibere spiritum suum.  

* Proverbs 26

** Proverbs 26:1

Quomodo nix in æstate, et pluviæ in messe,  sic indecens est stulto gloria. 

** Proverbs 26:2

Sicut avis ad alia transvolans, et passer quolibet vadens,  sic maledictum frustra prolatum in quempiam superveniet. 

** Proverbs 26:3

Flagellum equo, et camus asino,  et virga in dorso imprudentium. 

** Proverbs 26:4

Ne respondeas stulto juxta stultitiam suam,  ne efficiaris ei similis. 

** Proverbs 26:5

Responde stulto juxta stultitiam suam,  ne sibi sapiens esse videatur. 

** Proverbs 26:6

Claudus pedibus, et iniquitatem bibens,  qui mittit verba per nuntium stultum. 

** Proverbs 26:7

Quomodo pulchras frustra habet claudus tibias,  sic indecens est in ore stultorum parabola. 

** Proverbs 26:8

Sicut qui mittit lapidem in acervum Mercurii,  ita qui tribuit insipienti honorem. 

** Proverbs 26:9

Quomodo si spina nascatur in manu temulenti,  sic parabola in ore stultorum. 

** Proverbs 26:10

Judicium determinat causas,  et qui imponit stulto silentium iras mitigat. 

** Proverbs 26:11

Sicut canis qui revertitur ad vomitum suum,  sic imprudens qui iterat stultitiam suam. 

** Proverbs 26:12

Vidisti hominem sapientem sibi videri ?  magis illo spem habebit insipiens. 

** Proverbs 26:13

Dicit piger : Leo est in via,  et leæna in itineribus. 

** Proverbs 26:14

Sicut ostium vertitur in cardine suo,  ita piger in lectulo suo. 

** Proverbs 26:15

Abscondit piger manum sub ascella sua,  et laborat si ad os suum eam converterit. 

** Proverbs 26:16

Sapientior sibi piger videtur  septem viris loquentibus sententias. 

** Proverbs 26:17

Sicut qui apprehendit auribus canem,  sic qui transit impatiens et commiscetur rixæ alterius. 

** Proverbs 26:18

Sicut noxius est qui mittit sagittas et lanceas in mortem, 

** Proverbs 26:19

ita vir fraudulenter nocet amico suo,  et cum fuerit deprehensus dicit : Ludens feci. 

** Proverbs 26:20

Cum defecerint ligna extinguetur ignis,  et susurrone subtracto, jurgia conquiescent. 

** Proverbs 26:21

Sicut carbones ad prunas, et ligna ad ignem,  sic homo iracundus suscitat rixas. 

** Proverbs 26:22

Verba susurronis quasi simplicia,  et ipsa perveniunt ad intima ventris. 

** Proverbs 26:23

Quomodo si argento sordido ornare velis vas fictile,  sic labia tumentia cum pessimo corde sociata. 

** Proverbs 26:24

Labiis suis intelligitur inimicus,  cum in corde tractaverit dolos. 

** Proverbs 26:25

Quando submiserit vocem suam, ne credideris ei,  quoniam septem nequitiæ sunt in corde illius. 

** Proverbs 26:26

Qui operit odium fraudulenter,  revelabitur malitia ejus in consilio. 

** Proverbs 26:27

Qui fodit foveam incidet in eam,  et qui volvit lapidem revertetur ad eum. 

** Proverbs 26:28

Lingua fallax non amat veritatem,  et os lubricum operatur ruinas.  

* Proverbs 27

** Proverbs 27:1

Ne glorieris in crastinum,  ignorans quid superventura pariat dies. 

** Proverbs 27:2

Laudet te alienus, et non os tuum ;  extraneus, et non labia tua. 

** Proverbs 27:3

Grave est saxum, et onerosa arena,  sed ira stulti utroque gravior. 

** Proverbs 27:4

Ira non habet misericordiam nec erumpens furor,  et impetum concitati ferre quis poterit ? 

** Proverbs 27:5

Melior est manifesta correptio  quam amor absconditus. 

** Proverbs 27:6

Meliora sunt vulnera diligentis  quam fraudulenta oscula odientis. 

** Proverbs 27:7

Anima saturata calcabit favum,  et anima esuriens etiam amarum pro dulci sumet. 

** Proverbs 27:8

Sicut avis transmigrans de nido suo,  sic vir qui derelinquit locum suum. 

** Proverbs 27:9

Unguento et variis odoribus delectatur cor,  et bonis amici consiliis anima dulcoratur. 

** Proverbs 27:10

Amicum tuum et amicum patris tui ne dimiseris,  et domum fratris tui ne ingrediaris in die afflictionis tuæ.  Melior est vicinus juxta  quam frater procul. 

** Proverbs 27:11

Stude sapientiæ, fili mi, et lætifica cor meum,  ut possis exprobranti respondere sermonem. 

** Proverbs 27:12

Astutus videns malum, absconditus est :  parvuli transeuntes sustinuerunt dispendia. 

** Proverbs 27:13

Tolle vestimentum ejus qui spopondit pro extraneo,  et pro alienis aufer ei pignus. 

** Proverbs 27:14

Qui benedicit proximo suo voce grandi,  de nocte consurgens maledicenti similis erit. 

** Proverbs 27:15

Tecta perstillantia in die frigoris  et litigiosa mulier comparantur. 

** Proverbs 27:16

Qui retinet eam quasi qui ventum teneat,  et oleum dexteræ suæ vocabit. 

** Proverbs 27:17

Ferrum ferro exacuitur,  et homo exacuit faciem amici sui. 

** Proverbs 27:18

Qui servat ficum comedet fructus ejus,  et qui custos est domini sui glorificabitur. 

** Proverbs 27:19

Quomodo in aquis resplendent vultus prospicientium,  sic corda hominum manifesta sunt prudentibus. 

** Proverbs 27:20

Infernus et perditio numquam implentur :  similiter et oculi hominum insatiabiles. 

** Proverbs 27:21

Quomodo probatur in conflatorio argentum et in fornace aurum,  sic probatur homo ore laudantis.  Cor iniqui inquirit mala,  cor autem rectum inquirit scientiam. 

** Proverbs 27:22

Si contuderis stultum in pila  quasi ptisanas feriente desuper pilo,  non auferetur ab eo stultitia ejus. 

** Proverbs 27:23

Diligenter agnosce vultum pecoris tui,  tuosque greges considera : 

** Proverbs 27:24

non enim habebis jugiter potestatem,  sed corona tribuetur in generationem et generationem. 

** Proverbs 27:25

Aperta sunt prata, et apparuerunt herbæ virentes,  et collecta sunt fœna de montibus. 

** Proverbs 27:26

Agni ad vestimentum tuum,  et hædi ad agri pretium. 

** Proverbs 27:27

Sufficiat tibi lac caprarum in cibos tuos,  et in necessaria domus tuæ, et ad victum ancillis tuis.  

* Proverbs 28

** Proverbs 28:1

Fugit impius nemine persequente ;  justus autem, quasi leo confidens, absque terrore erit. 

** Proverbs 28:2

Propter peccata terræ multi principes ejus ;  et propter hominis sapientiam, et horum scientiam quæ dicuntur,  vita ducis longior erit. 

** Proverbs 28:3

Vir pauper calumnians pauperes  similis est imbri vehementi in quo paratur fames. 

** Proverbs 28:4

Qui derelinquunt legem laudant impium ;  qui custodiunt, succenduntur contra eum. 

** Proverbs 28:5

Viri mali non cogitant judicium ;  qui autem inquirunt Dominum animadvertunt omnia. 

** Proverbs 28:6

Melior est pauper ambulans in simplicitate sua  quam dives in pravis itineribus. 

** Proverbs 28:7

Qui custodit legem filius sapiens est ;  qui autem comessatores pascit confundit patrem suum. 

** Proverbs 28:8

Qui coacervat divitias usuris et fœnore,  liberali in pauperes congregat eas. 

** Proverbs 28:9

Qui declinat aures suas ne audiat legem,  oratio ejus erit execrabilis. 

** Proverbs 28:10

Qui decipit justos in via mala, in interitu suo corruet,  et simplices possidebunt bona ejus. 

** Proverbs 28:11

Sapiens sibi videtur vir dives ;  pauper autem prudens scrutabitur eum. 

** Proverbs 28:12

In exsultatione justorum multa gloria est ;  regnantibus impiis, ruinæ hominum. 

** Proverbs 28:13

Qui abscondit scelera sua non dirigetur ;  qui autem confessus fuerit et reliquerit ea, misericordiam consequetur. 

** Proverbs 28:14

Beatus homo qui semper est pavidus ;  qui vero mentis est duræ corruet in malum. 

** Proverbs 28:15

Leo rugiens et ursus esuriens,  princeps impius super populum pauperem. 

** Proverbs 28:16

Dux indigens prudentia multos opprimet per calumniam ;  qui autem odit avaritiam, longi fient dies ejus. 

** Proverbs 28:17

Hominem qui calumniatur animæ sanguinem,  si usque ad lacum fugerit, nemo sustinet. 

** Proverbs 28:18

Qui ambulat simpliciter salvus erit ;  qui perversis graditur viis concidet semel. 

** Proverbs 28:19

Qui operatur terram suam satiabitur panibus ;  qui autem sectatur otium replebitur egestate. 

** Proverbs 28:20

Vir fidelis multum laudabitur ;  qui autem festinat ditari non erit innocens. 

** Proverbs 28:21

Qui cognoscit in judicio faciem non bene facit ;  iste et pro buccella panis deserit veritatem. 

** Proverbs 28:22

Vir qui festinat ditari, et aliis invidet,  ignorat quod egestas superveniet ei. 

** Proverbs 28:23

Qui corripit hominem gratiam postea inveniet apud eum,  magis quam ille qui per linguæ blandimenta decipit. 

** Proverbs 28:24

Qui subtrahit aliquid a patre suo et a matre,  et dicit hoc non esse peccatum,  particeps homicidæ est. 

** Proverbs 28:25

Qui se jactat et dilatat, jurgia concitat ;  qui vero sperat in Domino sanabitur. 

** Proverbs 28:26

Qui confidit in corde suo stultus est ;  qui autem graditur sapienter, ipse salvabitur. 

** Proverbs 28:27

Qui dat pauperi non indigebit ;  qui despicit deprecantem sustinebit penuriam. 

** Proverbs 28:28

Cum surrexerint impii, abscondentur homines ;  cum illi perierint, multiplicabuntur justi.  

* Proverbs 29

** Proverbs 29:1

Viro qui corripientem dura cervice contemnit,  repentinus ei superveniet interitus,  et eum sanitas non sequetur. 

** Proverbs 29:2

In multiplicatione justorum lætabitur vulgus ;  cum impii sumpserint principatum, gemet populus. 

** Proverbs 29:3

Vir qui amat sapientiam lætificat patrem suum ;  qui autem nutrit scorta perdet substantiam. 

** Proverbs 29:4

Rex justus erigit terram ;  vir avarus destruet eam. 

** Proverbs 29:5

Homo qui blandis fictisque sermonibus loquitur amico suo  rete expandit gressibus ejus. 

** Proverbs 29:6

Peccantem virum iniquum involvet laqueus,  et justus laudabit atque gaudebit. 

** Proverbs 29:7

Novit justus causam pauperum ;  impius ignorat scientiam. 

** Proverbs 29:8

Homines pestilentes dissipant civitatem ;  sapientes vero avertunt furorem. 

** Proverbs 29:9

Vir sapiens si cum stulto contenderit,  sive irascatur, sive rideat, non inveniet requiem. 

** Proverbs 29:10

Viri sanguinum oderunt simplicem ;  justi autem quærunt animam ejus. 

** Proverbs 29:11

Totum spiritum suum profert stultus ;  sapiens differt, et reservat in posterum. 

** Proverbs 29:12

Princeps qui libenter audit verba mendacii,  omnes ministros habet impios. 

** Proverbs 29:13

Pauper et creditor obviaverunt sibi :  utriusque illuminator est Dominus. 

** Proverbs 29:14

Rex qui judicat in veritate pauperes,  thronus ejus in æternum firmabitur. 

** Proverbs 29:15

Virga atque correptio tribuit sapientiam ;  puer autem qui dimittitur voluntati suæ confundit matrem suam. 

** Proverbs 29:16

In multiplicatione impiorum multiplicabuntur scelera,  et justi ruinas eorum videbunt. 

** Proverbs 29:17

Erudi filium tuum, et refrigerabit te,  et dabit delicias animæ tuæ. 

** Proverbs 29:18

Cum prophetia defecerit, dissipabitur populus ;  qui vero custodit legem beatus est. 

** Proverbs 29:19

Servus verbis non potest erudiri,  quia quod dicis intelligit, et respondere contemnit. 

** Proverbs 29:20

Vidisti hominem velocem ad loquendum ?  stultitia magis speranda est quam illius correptio. 

** Proverbs 29:21

Qui delicate a pueritia nutrit servum suum  postea sentiet eum contumacem. 

** Proverbs 29:22

Vir iracundus provocat rixas,  et qui ad indignandum facilis est erit ad peccandum proclivior. 

** Proverbs 29:23

Superbum sequitur humilitas,  et humilem spiritu suscipiet gloria. 

** Proverbs 29:24

Qui cum fure participat odit animam suam ;  adjurantem audit, et non indicat. 

** Proverbs 29:25

Qui timet hominem cito corruet ;  qui sperat in Domino sublevabitur. 

** Proverbs 29:26

Multi requirunt faciem principis,  et judicium a Domino egreditur singulorum. 

** Proverbs 29:27

Abominantur justi virum impium,  et abominantur impii eos qui in recta sunt via.  Verbum custodiens filius  extra perditionem erit.  

* Proverbs 30

** Proverbs 30:1

Verba Congregantis, filii Vomentis. Visio quam locutus est vir cum quo est Deus, et qui Deo secum morante confortatus, ait :  

** Proverbs 30:2

Stultissimus sum virorum,  et sapientia hominum non est mecum. 

** Proverbs 30:3

Non didici sapientiam,  et non novi scientiam sanctorum. 

** Proverbs 30:4

Quis ascendit in cælum, atque descendit ?  quis continuit spiritum in manibus suis ?  quis colligavit aquas quasi in vestimento ?  quis suscitavit omnes terminos terræ ?  quod nomen est ejus, et quod nomen filii ejus, si nosti ? 

** Proverbs 30:5

Omnis sermo Dei ignitus :  clypeus est sperantibus in se. 

** Proverbs 30:6

Ne addas quidquam verbis illius,  et arguaris, inveniarisque mendax. 

** Proverbs 30:7

Duo rogavi te :  ne deneges mihi antequam moriar : 

** Proverbs 30:8

vanitatem et verba mendacia longe fac a me ;  mendicitatem et divitias ne dederis mihi :  tribue tantum victui meo necessaria, 

** Proverbs 30:9

ne forte satiatus illiciar ad negandum,  et dicam : Quis est Dominus ?  aut egestate compulsus, furer,  et perjurem nomen Dei mei. 

** Proverbs 30:10

Ne accuses servum ad dominum suum,  ne forte maledicat tibi, et corruas. 

** Proverbs 30:11

Generatio quæ patri suo maledicit,  et quæ matri suæ non benedicit ; 

** Proverbs 30:12

generatio quæ sibi munda videtur,  et tamen non est lota a sordibus suis ; 

** Proverbs 30:13

generatio cujus excelsi sunt oculi,  et palpebræ ejus in alta surrectæ ; 

** Proverbs 30:14

generatio quæ pro dentibus gladios habet,  et commandit molaribus suis,  ut comedat inopes de terra,  et pauperes ex hominibus. 

** Proverbs 30:15

Sanguisugæ duæ sunt filiæ,  dicentes : Affer, affer.  Tria sunt insaturabilia,  et quartum quod numquam dicit : Sufficit. 

** Proverbs 30:16

Infernus, et os vulvæ,  et terra quæ non satiatur aqua :  ignis vero numquam dicit : Sufficit. 

** Proverbs 30:17

Oculum qui subsannat patrem,  et qui despicit partum matris suæ,  effodiant eum corvi de torrentibus,  et comedant eum filii aquilæ ! 

** Proverbs 30:18

Tria sunt difficilia mihi,  et quartum penitus ignoro : 

** Proverbs 30:19

viam aquilæ in cælo,  viam colubri super petram,  viam navis in medio mari,  et viam viri in adolescentia. 

** Proverbs 30:20

Talis est et via mulieris adulteræ,  quæ comedit, et tergens os suum  dicit : Non sum operata malum. 

** Proverbs 30:21

Per tria movetur terra,  et quartum non potest sustinere : 

** Proverbs 30:22

per servum, cum regnaverit ;  per stultum, cum saturatus fuerit cibo ; 

** Proverbs 30:23

per odiosam mulierem, cum in matrimonio fuerit assumpta ;  et per ancillam, cum fuerit hæres dominæ suæ. 

** Proverbs 30:24

Quatuor sunt minima terræ,  et ipsa sunt sapientiora sapientibus : 

** Proverbs 30:25

formicæ, populus infirmus,  qui præparat in messe cibum sibi ; 

** Proverbs 30:26

lepusculus, plebs invalida,  qui collocat in petra cubile suum ; 

** Proverbs 30:27

regem locusta non habet,  et egreditur universa per turmas suas ; 

** Proverbs 30:28

stellio manibus nititur,  et moratur in ædibus regis. 

** Proverbs 30:29

Tria sunt quæ bene gradiuntur,  et quartum quod incedit feliciter : 

** Proverbs 30:30

leo, fortissimus bestiarum,  ad nullius pavebit occursum ; 

** Proverbs 30:31

gallus succinctus lumbos ;  et aries ; nec est rex, qui resistat ei. 

** Proverbs 30:32

Est qui stultus apparuit postquam elevatus est in sublime ;  si enim intellexisset, ori suo imposuisset manum. 

** Proverbs 30:33

Qui autem fortiter premit ubera ad eliciendum lac exprimit butyrum ;  et qui vehementer emungit elicit sanguinem ;  et qui provocat iras producit discordias.  

* Proverbs 31

** Proverbs 31:1

Verba Lamuelis regis. Visio qua erudivit eum mater sua.  

** Proverbs 31:2

Quid, dilecte mi ? quid, dilecte uteri mei ?  quid, dilecte votorum meorum ? 

** Proverbs 31:3

Ne dederis mulieribus substantiam tuam,  et divitias tuas ad delendos reges. 

** Proverbs 31:4

Noli regibus, o Lamuel, noli regibus dare vinum,  quia nullum secretum est ubi regnat ebrietas ; 

** Proverbs 31:5

et ne forte bibant, et obliviscantur judiciorum,  et mutent causam filiorum pauperis. 

** Proverbs 31:6

Date siceram mœrentibus,  et vinum his qui amaro sunt animo. 

** Proverbs 31:7

Bibant, et obliviscantur egestatis suæ,  et doloris sui non recordentur amplius. 

** Proverbs 31:8

Aperi os tuum muto,  et causis omnium filiorum qui pertranseunt. 

** Proverbs 31:9

Aperi os tuum, decerne quod justum est,  et judica inopem et pauperem. 

** Proverbs 31:10

Mulierem fortem quis inveniet ?  procul et de ultimis finibus pretium ejus. 

** Proverbs 31:11

Confidit in ea cor viri sui,  et spoliis non indigebit. 

** Proverbs 31:12

Reddet ei bonum, et non malum,  omnibus diebus vitæ suæ. 

** Proverbs 31:13

Quæsivit lanam et linum,  et operata est consilia manuum suarum. 

** Proverbs 31:14

Facta est quasi navis institoris,  de longe portans panem suum. 

** Proverbs 31:15

Et de nocte surrexit,  deditque prædam domesticis suis,  et cibaria ancillis suis. 

** Proverbs 31:16

Consideravit agrum, et emit eum ;  de fructu manuum suarum plantavit vineam. 

** Proverbs 31:17

Accinxit fortitudine lumbos suos,  et roboravit brachium suum. 

** Proverbs 31:18

Gustavit, et vidit quia bona est negotiatio ejus ;  non extinguetur in nocte lucerna ejus. 

** Proverbs 31:19

Manum suam misit ad fortia,  et digiti ejus apprehenderunt fusum. 

** Proverbs 31:20

Manum suam aperuit inopi,  et palmas suas extendit ad pauperem. 

** Proverbs 31:21

Non timebit domui suæ a frigoribus nivis ;  omnes enim domestici ejus vestiti sunt duplicibus. 

** Proverbs 31:22

Stragulatam vestem fecit sibi ;  byssus et purpura indumentum ejus. 

** Proverbs 31:23

Nobilis in portis vir ejus,  quando sederit cum senatoribus terræ. 

** Proverbs 31:24

Sindonem fecit, et vendidit,  et cingulum tradidit Chananæo. 

** Proverbs 31:25

Fortitudo et decor indumentum ejus,  et ridebit in die novissimo. 

** Proverbs 31:26

Os suum aperuit sapientiæ,  et lex clementiæ in lingua ejus. 

** Proverbs 31:27

Consideravit semitas domus suæ,  et panem otiosa non comedit. 

** Proverbs 31:28

Surrexerunt filii ejus, et beatissimam prædicaverunt ;  vir ejus, et laudavit eam. 

** Proverbs 31:29

Multæ filiæ congregaverunt divitias ;  tu supergressa es universas. 

** Proverbs 31:30

Fallax gratia, et vana est pulchritudo :  mulier timens Dominum, ipsa laudabitur. 

** Proverbs 31:31

Date ei de fructu manuum suarum,  et laudent eam in portis opera ejus.    

