* Romans 1

** Romans 1:1

Paulus, servus Jesu Christi, vocatus Apostolus, segregatus in Evangelium Dei,

** Romans 1:2

quod ante promiserat per prophetas suos in Scripturis sanctis

** Romans 1:3

de Filio suo, qui factus est ei ex semine David secundum carnem,

** Romans 1:4

qui prædestinatus est Filius Dei in virtute secundum spiritum sanctificationis ex resurrectione mortuorum Jesu Christi Domini nostri :

** Romans 1:5

per quem accepimus gratiam, et apostolatum ad obediendum fidei in omnibus gentibus pro nomine ejus,

** Romans 1:6

in quibus estis et vos vocati Jesu Christi :

** Romans 1:7

omnibus qui sunt Romæ, dilectis Dei, vocatis sanctis. Gratia vobis, et pax a Deo Patre nostro, et Domino Jesu Christo.  

** Romans 1:8

Primum quidem gratias ago Deo meo per Jesum Christum pro omnibus vobis : quia fides vestra annuntiatur in universo mundo.

** Romans 1:9

Testis enim mihi est Deus, cui servio in spiritu meo in Evangelio Filii ejus, quod sine intermissione memoriam vestri facio

** Romans 1:10

semper in orationibus meis : obsecrans, si quomodo tandem aliquando prosperum iter habeam in voluntate Dei veniendi ad vos.

** Romans 1:11

Desidero enim videre vos, ut aliquid impertiar vobis gratiæ spiritualis ad confirmandos vos :

** Romans 1:12

id est, simul consolari in vobis per eam quæ invicem est, fidem vestram atque meam.

** Romans 1:13

Nolo autem vos ignorare fratres : quia sæpe proposui venire ad vos (et prohibitus sum usque adhuc) ut aliquem fructum habeam et in vobis, sicut et in ceteris gentibus.

** Romans 1:14

Græcis ac barbaris, sapientibus, et insipientibus debitor sum :

** Romans 1:15

ita (quod in me) promptum est et vobis, qui Romæ estis, evangelizare.  

** Romans 1:16

Non enim erubesco Evangelium. Virtus enim Dei est in salutem omni credenti, Judæo primum, et Græco.

** Romans 1:17

Justitia enim Dei in eo revelatur ex fide in fidem : sicut scriptum est : Justus autem ex fide vivit.  

** Romans 1:18

Revelatur enim ira Dei de cælo super omnem impietatem, et injustitiam hominum eorum, qui veritatem Dei in injustitia detinent :

** Romans 1:19

quia quod notum est Dei, manifestum est in illis. Deus enim illis manifestavit.

** Romans 1:20

Invisibilia enim ipsius, a creatura mundi, per ea quæ facta sunt, intellecta, conspiciuntur : sempiterna quoque ejus virtus, et divinitas : ita ut sint inexcusabiles.

** Romans 1:21

Quia cum cognovissent Deum, non sicut Deum glorificaverunt, aut gratias egerunt : sed evanuerunt in cogitationibus suis, et obscuratum est insipiens cor eorum :

** Romans 1:22

dicentes enim se esse sapientes, stulti facti sunt.

** Romans 1:23

Et mutaverunt gloriam incorruptibilis Dei in similitudinem imaginis corruptibilis hominis, et volucrum, et quadrupedum, et serpentium.  

** Romans 1:24

Propter quod tradidit illos Deus in desideria cordis eorum, in immunditiam, ut contumeliis afficiant corpora sua in semetipsis :

** Romans 1:25

qui commutaverunt veritatem Dei in mendacium : et coluerunt, et servierunt creaturæ potius quam Creatori, qui est benedictus in sæcula. Amen.

** Romans 1:26

Propterea tradidit illos Deus in passiones ignominiæ : nam feminæ eorum immutaverunt naturalem usum in eum usum qui est contra naturam.

** Romans 1:27

Similiter autem et masculi, relicto naturali usu feminæ, exarserunt in desideriis suis in invicem, masculi in masculos turpitudinem operantes, et mercedem, quam oportuit, erroris sui in semetipsis recipientes.

** Romans 1:28

Et sicut non probaverunt Deum habere in notitia, tradidit illos Deus in reprobum sensum, ut faciant ea quæ non conveniunt,

** Romans 1:29

repletos omni iniquitate, malitia, fornicatione, avaritia, nequitia, plenos invidia, homicidio, contentione, dolo, malignitate : susurrones,

** Romans 1:30

detractores, Deo odibiles, contumeliosos, superbos, elatos, inventores malorum, parentibus non obedientes,

** Romans 1:31

insipientes, incompositos, sine affectione, absque fœdere, sine misericordia.

** Romans 1:32

Qui cum justitiam Dei cognovissent, non intellexerunt quoniam qui talia agunt, digni sunt morte : et non solum qui ea faciunt, sed etiam qui consentiunt facientibus.   

* Romans 2

** Romans 2:1

Propter quod inexcusabilis es, o homo omnis qui judicas. In quo enim judicas alterum, teipsum condemnas : eadem enim agis quæ judicas.

** Romans 2:2

Scimus enim quoniam judicium Dei est secundum veritatem in eos qui talia agunt.

** Romans 2:3

Existimas autem hoc, o homo, qui judicas eos qui talia agunt, et facis ea, quia tu effugies judicium Dei ?

** Romans 2:4

an divitias bonitatis ejus, et patientiæ, et longanimitatis contemnis ? ignoras quoniam benignitas Dei ad pœnitentiam te adducit ?

** Romans 2:5

Secundum autem duritiam tuam, et impœnitens cor, thesaurizas tibi iram in die iræ, et revelationis justi judicii Dei,

** Romans 2:6

qui reddet unicuique secundum opera ejus :

** Romans 2:7

iis quidem qui secundum patientiam boni operis, gloriam, et honorem, et incorruptionem quærunt, vitam æternam :

** Romans 2:8

iis autem qui sunt ex contentione, et qui non acquiescunt veritati, credunt autem iniquitati, ira et indignatio.

** Romans 2:9

Tribulatio et angustia in omnem animam hominis operantis malum, Judæi primum, et Græci :

** Romans 2:10

gloria autem, et honor, et pax omni operanti bonum, Judæo primum, et Græco :

** Romans 2:11

non enim est acceptio personarum apud Deum.  

** Romans 2:12

Quicumque enim sine lege peccaverunt, sine lege peribunt : et quicumque in lege peccaverunt, per legem judicabuntur.

** Romans 2:13

Non enim auditores legis justi sunt apud Deum, sed factores legis justificabuntur.

** Romans 2:14

Cum autem gentes, quæ legem non habent, naturaliter ea, quæ legis sunt, faciunt, ejusmodi legem non habentes, ipsi sibi sunt lex :

** Romans 2:15

qui ostendunt opus legis scriptum in cordibus suis, testimonium reddente illis conscientia ipsorum, et inter se invicem cogitationibus accusantibus, aut etiam defendentibus,

** Romans 2:16

in die, cum judicabit Deus occulta hominum, secundum Evangelium meum per Jesum Christum.  

** Romans 2:17

Si autem tu Judæus cognominaris, et requiescis in lege, et gloriaris in Deo,

** Romans 2:18

et nosti voluntatem ejus, et probas utiliora, instructus per legem,

** Romans 2:19

confidis teipsum esse ducem cæcorum, lumen eorum qui in tenebris sunt,

** Romans 2:20

eruditorem insipientium, magistrum infantium, habentem formam scientiæ, et veritatis in lege.

** Romans 2:21

Qui ergo alium doces, teipsum non doces : qui prædicas non furandum, furaris :

** Romans 2:22

qui dicis non mœchandum, mœcharis : qui abominaris idola, sacrilegium facis :

** Romans 2:23

qui in lege gloriaris, per prævaricationem legis Deum inhonoras.

** Romans 2:24

(Nomen enim Dei per vos blasphematur inter gentes, sicut scriptum est.)  

** Romans 2:25

Circumcisio quidem prodest, si legem observes : si autem prævaricator legis sis, circumcisio tua præputium facta est.

** Romans 2:26

Si igitur præputium justitias legis custodiat, nonne præputium illius in circumcisionem reputabitur ?

** Romans 2:27

et judicabit id quod ex natura est præputium, legem consummans, te, qui per litteram et circumcisionem prævaricator legis es ?

** Romans 2:28

Non enim qui in manifesto, Judæus est : neque quæ in manifesto, in carne, est circumcisio :

** Romans 2:29

sed qui in abscondito, Judæus est : et circumcisio cordis in spiritu, non littera : cujus laus non ex hominibus, sed ex Deo est.   

* Romans 3

** Romans 3:1

Quid ergo amplius Judæo est ? aut quæ utilitas circumcisionis ?

** Romans 3:2

Multum per omnem modum. Primum quidem quia credita sunt illis eloquia Dei.

** Romans 3:3

Quid enim si quidam illorum non crediderunt ? numquid incredulitas illorum fidem Dei evacuabit ? Absit.

** Romans 3:4

Est autem Deus verax : omnis autem homo mendax, sicut scriptum est :   Ut justificeris in sermonibus tuis :  et vincas cum judicaris.

** Romans 3:5

Si autem iniquitas nostra justitiam Dei commendat, quid dicemus ? Numquid iniquus est Deus, qui infert iram ?

** Romans 3:6

secundum hominem dico. Absit. Alioquin quomodo judicabit Deus hunc mundum ?

** Romans 3:7

Si enim veritas Dei in meo mendacio abundavit in gloriam ipsius : quid adhuc et ego tamquam peccator judicor ?

** Romans 3:8

et non (sicut blasphemamur, et sicut aiunt quidam nos dicere) faciamus mala ut veniant bona : quorum damnatio justa est.  

** Romans 3:9

Quid ergo ? præcellimus eos ? Nequaquam. Causati enim sumus Judæos et Græcos omnes sub peccato esse,

** Romans 3:10

sicut scriptum est :   Quia non est justus quisquam : 

** Romans 3:11

non est intelligens, non est requirens Deum. 

** Romans 3:12

Omnes declinaverunt, simul inutiles facti sunt :  non est qui faciat bonum, non est usque ad unum. 

** Romans 3:13

Sepulchrum patens est guttur eorum,  linguis suis dolose agebant :  venenum aspidum sub labiis eorum : 

** Romans 3:14

quorum os maledictione, et amaritudine plenum est : 

** Romans 3:15

veloces pedes eorum ad effundendum sanguinem : 

** Romans 3:16

contritio et infelicitas in viis eorum : 

** Romans 3:17

et viam pacis non cognoverunt : 

** Romans 3:18

non est timor Dei ante oculos eorum.

** Romans 3:19

Scimus autem quoniam quæcumque lex loquitur, iis, qui in lege sunt, loquitur : ut omne os obstruatur, et subditus fiat omnis mundus Deo :

** Romans 3:20

quia ex operibus legis non justificabitur omnis caro coram illo. Per legem enim cognitio peccati.  

** Romans 3:21

Nunc autem sine lege justitia Dei manifestata est : testificata a lege et prophetis.

** Romans 3:22

Justitia autem Dei per fidem Jesu Christi in omnes et super omnes qui credunt in eum : non enim est distinctio :

** Romans 3:23

omnes enim peccaverunt, et egent gloria Dei.

** Romans 3:24

Justificati gratis per gratiam ipsius, per redemptionem quæ est in Christo Jesu,

** Romans 3:25

quem proposuit Deus propitiationem per fidem in sanguine ipsius, ad ostensionem justitiæ suæ propter remissionem præcedentium delictorum

** Romans 3:26

in sustentatione Dei, ad ostensionem justitiæ ejus in hoc tempore : ut sit ipse justus, et justificans eum, qui est ex fide Jesu Christi.  

** Romans 3:27

Ubi est ergo gloriatio tua ? Exclusa est. Per quam legem ? Factorum ? Non : sed per legem fidei.

** Romans 3:28

Arbitramur enim justificari hominem per fidem sine operibus legis.

** Romans 3:29

An Judæorum Deus tantum ? nonne et gentium ? Immo et gentium :

** Romans 3:30

quoniam quidem unus est Deus, qui justificat circumcisionem ex fide, et præputium per fidem.

** Romans 3:31

Legem ergo destruimus per fidem ? Absit : sed legem statuimus.   

* Romans 4

** Romans 4:1

Quid ergo dicemus invenisse Abraham patrem nostrum secundum carnem ?

** Romans 4:2

Si enim Abraham ex operibus justificatus est, habet gloriam, sed non apud Deum.

** Romans 4:3

Quid enim dicit Scriptura ? Credidit Abraham Deo, et reputatum est illi ad justitiam.

** Romans 4:4

Ei autem qui operatur, merces non imputatur secundum gratiam, sed secundum debitum.

** Romans 4:5

Ei vero qui non operatur, credenti autem in eum, qui justificat impium, reputatur fides ejus ad justitiam secundum propositum gratiæ Dei.

** Romans 4:6

Sicut et David dicit beatitudinem hominis, cui Deus accepto fert justitiam sine operibus :  

** Romans 4:7

Beati, quorum remissæ sunt iniquitates,  et quorum tecta sunt peccata. 

** Romans 4:8

Beatus vir, cui non imputavit Dominus peccatum.

** Romans 4:9

Beatitudo ergo hæc in circumcisione tantum manet, an etiam in præputio ? Dicimus enim quia reputata est Abrahæ fides ad justitiam.

** Romans 4:10

Quomodo ergo reputata est ? in circumcisione, an in præputio ? Non in circumcisione, sed in præputio.

** Romans 4:11

Et signum accepit circumcisionis, signaculum justitiæ fidei, quæ est in præputio : ut sit pater omnium credentium per præputium, ut reputetur et illis ad justitiam :

** Romans 4:12

et sit pater circumcisionis non iis tantum, qui sunt ex circumcisione, sed et iis qui sectantur vestigia fidei, quæ est in præputio patris nostri Abrahæ.  

** Romans 4:13

Non enim per legem promissio Abrahæ, aut semini ejus ut hæres esset mundi : sed per justitiam fidei.

** Romans 4:14

Si enim qui ex lege, hæredes sunt : exinanita est fides, abolita est promissio.

** Romans 4:15

Lex enim iram operatur. Ubi enim non est lex, nec prævaricatio.

** Romans 4:16

Ideo ex fide, ut secundum gratiam firma sit promissio omni semini, non ei qui ex lege est solum, sed et ei qui ex fide est Abrahæ, qui pater est omnium nostrum

** Romans 4:17

(sicut scriptum est : Quia patrem multarum gentium posui te) ante Deum, cui credidit, qui vivificat mortuos, et vocat ea quæ non sunt, tamquam ea quæ sunt :

** Romans 4:18

qui contra spem in spem credidit, ut fieret pater multarum gentium secundum quod dictum est ei : Sic erit semen tuum.

** Romans 4:19

Et non infirmatus est fide, nec consideravit corpus suum emortuum, cum jam fere centum esset annorum, et emortuam vulvam Saræ.

** Romans 4:20

In repromissione etiam Dei non hæsitavit diffidentia, sed confortatus est fide, dans gloriam Deo :

** Romans 4:21

plenissime sciens, quia quæcumque promisit, potens est et facere.

** Romans 4:22

Ideo et reputatum est illi ad justitiam.

** Romans 4:23

Non est autem scriptum tantum propter ipsum quia reputatum est illi ad justitiam :

** Romans 4:24

sed et propter nos, quibus reputabitur credentibus in eum, qui suscitavit Jesum Christum Dominum nostrum a mortuis,

** Romans 4:25

qui traditus est propter delicta nostra, et resurrexit propter justificationem nostram.   

* Romans 5

** Romans 5:1

Justificati ergo ex fide, pacem habeamus ad Deum per Dominum nostrum Jesum Christum :

** Romans 5:2

per quem et habemus accessum per fidem in gratiam istam, in qua stamus, et gloriamur in spe gloriæ filiorum Dei.

** Romans 5:3

Non solum autem, sed et gloriamur in tribulationibus : scientes quod tribulatio patientiam operatur :

** Romans 5:4

patientia autem probationem, probatio vero spem,

** Romans 5:5

spes autem non confundit : quia caritas Dei diffusa est in cordibus nostris per Spiritum Sanctum, qui datus est nobis.

** Romans 5:6

Ut quid enim Christus, cum adhuc infirmi essemus, secundum tempus, pro impiis mortuus est ?

** Romans 5:7

vix enim pro justo quis moritur : nam pro bono forsitan quis audeat mori.

** Romans 5:8

Commendat autem caritatem suam Deus in nobis : quoniam cum adhuc peccatores essemus, secundum tempus,

** Romans 5:9

Christus pro nobis mortuus est : multo igitur magis nunc justificati in sanguine ipsius, salvi erimus ab ira per ipsum.

** Romans 5:10

Si enim cum inimici essemus, reconciliati sumus Deo per mortem filii ejus : multo magis reconciliati, salvi erimus in vita ipsius.

** Romans 5:11

Non solum autem : sed et gloriamur in Deo per Dominum nostrum Jesum Christum, per quem nunc reconciliationem accepimus.  

** Romans 5:12

Propterea sicut per unum hominem peccatum in hunc mundum intravit, et per peccatum mors, et ita in omnes homines mors pertransiit, in quo omnes peccaverunt.

** Romans 5:13

Usque ad legem enim peccatum erat in mundo : peccatum autem non imputabatur, cum lex non esset.

** Romans 5:14

Sed regnavit mors ab Adam usque ad Moysen etiam in eos qui non peccaverunt in similitudinem prævaricationis Adæ, qui est forma futuri.

** Romans 5:15

Sed non sicut delictum, ita et donum : si enim unius delicto multi mortui sunt : multo magis gratia Dei et donum in gratia unius hominis Jesu Christi in plures abundavit.

** Romans 5:16

Et non sicut per unum peccatum, ita et donum. Nam judicium quidem ex uno in condemnationem : gratia autem ex multis delictis in justificationem.

** Romans 5:17

Si enim unius delicto mors regnavit per unum : multo magis abundantiam gratiæ, et donationis, et justitiæ accipientes, in vita regnabunt per unum Jesum Christum.

** Romans 5:18

Igitur sicut per unius delictum in omnes homines in condemnationem : sic et per unius justitiam in omnes homines in justificationem vitæ.

** Romans 5:19

Sicut enim per inobedientiam unius hominis, peccatores constituti sunt multi : ita et per unius obeditionem, justi constituentur multi.

** Romans 5:20

Lex autem subintravit ut abundaret delictum. Ubi autem abundavit delictum, superabundavit gratia :

** Romans 5:21

ut sicut regnavit peccatum in mortem : ita et gratia regnet per justitiam in vitam æternam, per Jesum Christum Dominum nostrum.   

* Romans 6

** Romans 6:1

Quid ergo dicemus ? permanebimus in peccato ut gratia abundet ?

** Romans 6:2

Absit. Qui enim mortui sumus peccato, quomodo adhuc vivemus in illo ?

** Romans 6:3

an ignoratis quia quicumque baptizati sumus in Christo Jesu, in morte ipsius baptizati sumus ?

** Romans 6:4

Consepulti enim sumus cum illo per baptismum in mortem : ut quomodo Christus surrexit a mortuis per gloriam Patris, ita et nos in novitate vitæ ambulemus.

** Romans 6:5

Si enim complantati facti sumus similitudini mortis ejus : simul et resurrectionis erimus.

** Romans 6:6

Hoc scientes, quia vetus homo noster simul crucifixus est, ut destruatur corpus peccati, et ultra non serviamus peccato.

** Romans 6:7

Qui enim mortuus est, justificatus est a peccato.

** Romans 6:8

Si autem mortui sumus cum Christo, credimus quia simul etiam vivemus cum Christo,

** Romans 6:9

scientes quod Christus resurgens ex mortuis jam non moritur : mors illi ultra non dominabitur.

** Romans 6:10

Quod enim mortuus est peccato, mortuus est semel : quod autem vivit, vivit Deo.

** Romans 6:11

Ita et vos existimate vos mortuos quidem esse peccato, viventes autem Deo, in Christo Jesu Domino nostro.  

** Romans 6:12

Non ergo regnet peccatum in vestro mortali corpore ut obediatis concupiscentiis ejus.

** Romans 6:13

Sed neque exhibeatis membra vestra arma iniquitatis peccato : sed exhibete vos Deo, tamquam ex mortuis viventes : et membra vestra arma justitiæ Deo.

** Romans 6:14

Peccatum enim vobis non dominabitur : non enim sub lege estis, sed sub gratia.

** Romans 6:15

Quid ergo ? peccabimus, quoniam non sumus sub lege, sed sub gratia ? Absit.

** Romans 6:16

Nescitis quoniam cui exhibetis vos servos ad obediendum, servi estis ejus, cui obeditis, sive peccati ad mortem, sive obeditionis ad justitiam ?

** Romans 6:17

Gratias autem Deo quod fuistis servi peccati, obedistis autem ex corde in eam formam doctrinæ, in quam traditi estis.

** Romans 6:18

Liberati autem a peccato, servi facti estis justitiæ.

** Romans 6:19

Humanum dico, propter infirmitatem carnis vestræ : sicut enim exhibuistis membra vestra servire immunditiæ, et iniquitati ad iniquitatem, ita nunc exhibete membra vestra servire justitiæ in sanctificationem.

** Romans 6:20

Cum enim servi essetis peccati, liberi fuistis justitiæ.

** Romans 6:21

Quem ergo fructum habuistis tunc in illis, in quibus nunc erubescitis ? nam finis illorum mors est.

** Romans 6:22

Nunc vero liberati a peccato, servi autem facti Deo, habetis fructum vestrum in sanctificationem, finem vero vitam æternam.

** Romans 6:23

Stipendia enim peccati, mors. Gratia autem Dei, vita æterna, in Christo Jesu Domino nostro.   

* Romans 7

** Romans 7:1

An ignoratis, fratres (scientibus enim legem loquor), quia lex in homine dominatur quanto tempore vivit ?

** Romans 7:2

Nam quæ sub viro est mulier, vivente viro, alligata est legi : si autem mortuus fuerit vir ejus, soluta est a lege viri.

** Romans 7:3

Igitur, vivente viro, vocabitur adultera si fuerit cum alio viro : si autem mortuus fuerit vir ejus, liberata est a lege viri, ut non sit adultera si fuerit cum alio viro.

** Romans 7:4

Itaque fratres mei, et vos mortificati estis legi per corpus Christi : ut sitis alterius, qui ex mortuis resurrexit, ut fructificemus Deo.

** Romans 7:5

Cum enim essemus in carne, passiones peccatorum, quæ per legem erant, operabantur in membris nostris, ut fructificarent morti.

** Romans 7:6

Nunc autem soluti sumus a lege mortis, in qua detinebamur, ita ut serviamus in novitate spiritus, et non in vetustate litteræ.  

** Romans 7:7

Quid ergo dicemus ? lex peccatum est ? Absit. Sed peccatum non cognovi, nisi per legem : nam concupiscentiam nesciebam, nisi lex diceret : Non concupisces.

** Romans 7:8

Occasione autem accepta, peccatum per mandatum operatum est in me omnem concupiscentiam. Sine lege enim peccatum mortuum erat.

** Romans 7:9

Ego autem vivebam sine lege aliquando : sed cum venisset mandatum, peccatum revixit.

** Romans 7:10

Ego autem mortuus sum : et inventum est mihi mandatum, quod erat ad vitam, hoc esse ad mortem.

** Romans 7:11

Nam peccatum occasione accepta per mandatum, seduxit me, et per illud occidit.

** Romans 7:12

Itaque lex quidem sancta, et mandatum sanctum, et justum, et bonum.  

** Romans 7:13

Quod ergo bonum est, mihi factum est mors ? Absit. Sed peccatum, ut appareat peccatum, per bonum operatum est mihi mortem : ut fiat supra modum peccans peccatum per mandatum.

** Romans 7:14

Scimus enim quia lex spiritualis est : ego autem carnalis sum, venundatus sub peccato.

** Romans 7:15

Quod enim operor, non intelligo : non enim quod volo bonum, hoc ago : sed quod odi malum, illud facio.

** Romans 7:16

Si autem quod nolo, illud facio : consentio legi, quoniam bona est.

** Romans 7:17

Nunc autem jam non ego operor illud, sed quod habitat in me peccatum.

** Romans 7:18

Scio enim quia non habitat in me, hoc est in carne mea, bonum. Nam velle, adjacet mihi : perficere autem bonum, non invenio.

** Romans 7:19

Non enim quod volo bonum, hoc facio : sed quod nolo malum, hoc ago.

** Romans 7:20

Si autem quod nolo, illud facio : jam non ego operor illud, sed quod habitat in me, peccatum.

** Romans 7:21

Invenio igitur legem, volenti mihi facere bonum, quoniam mihi malum adjacet :

** Romans 7:22

condelector enim legi Dei secundum interiorem hominem :

** Romans 7:23

video autem aliam legem in membris meis, repugnantem legi mentis meæ, et captivantem me in lege peccati, quæ est in membris meis.

** Romans 7:24

Infelix ego homo, quis me liberabit de corpore mortis hujus ?

** Romans 7:25

gratia Dei per Jesum Christum Dominum nostrum. Igitur ego ipse mente servio legi Dei : carne autem, legi peccati.   

* Romans 8

** Romans 8:1

Nihil ergo nunc damnationis est iis qui sunt in Christo Jesu : qui non secundum carnem ambulant.

** Romans 8:2

Lex enim spiritus vitæ in Christo Jesu liberavit me a lege peccati et mortis.

** Romans 8:3

Nam quod impossibile erat legi, in quo infirmabatur per carnem : Deus Filium suum mittens in similitudinem carnis peccati et de peccato, damnavit peccatum in carne,

** Romans 8:4

ut justificatio legis impleretur in nobis, qui non secundum carnem ambulamus, sed secundum spiritum.

** Romans 8:5

Qui enim secundum carnem sunt, quæ carnis sunt, sapiunt : qui vero secundum spiritum sunt, quæ sunt spiritus, sentiunt.

** Romans 8:6

Nam prudentia carnis, mors est : prudentia autem spiritus, vita et pax :

** Romans 8:7

quoniam sapientia carnis inimica est Deo : legi enim Dei non est subjecta, nec enim potest.

** Romans 8:8

Qui autem in carne sunt, Deo placere non possunt.

** Romans 8:9

Vos autem in carne non estis, sed in spiritu : si tamen Spiritus Dei habitat in vobis. Si quis autem Spiritum Christi non habet, hic non est ejus.

** Romans 8:10

Si autem Christus in vobis est, corpus quidem mortuum est propter peccatum, spiritus vero vivit propter justificationem.

** Romans 8:11

Quod si Spiritus ejus, qui suscitavit Jesum a mortuis, habitat in vobis : qui suscitavit Jesum Christum a mortuis, vivificabit et mortalia corpora vestra, propter inhabitantem Spiritum ejus in vobis.

** Romans 8:12

Ergo fratres, debitores sumus non carni, ut secundum carnem vivamus.

** Romans 8:13

Si enim secundum carnem vixeritis, moriemini : si autem spiritu facta carnis mortificaveritis, vivetis.  

** Romans 8:14

Quicumque enim Spiritu Dei aguntur, ii sunt filii Dei.

** Romans 8:15

Non enim accepistis spiritum servitutis iterum in timore, sed accepistis spiritum adoptionis filiorum, in quo clamamus : Abba (Pater).

** Romans 8:16

Ipse enim Spiritus testimonium reddit spiritui nostro quod sumus filii Dei.

** Romans 8:17

Si autem filii, et hæredes : hæredes, quidem Dei, cohæredes autem Christi : si tamen compatimur ut et conglorificemur.  

** Romans 8:18

Existimo enim quod non sunt condignæ passiones hujus temporis ad futuram gloriam, quæ revelabitur in nobis.

** Romans 8:19

Nam exspectatio creaturæ revelationem filiorum Dei exspectat.

** Romans 8:20

Vanitati enim creatura subjecta est non volens, sed propter eum, qui subjecit eam in spe :

** Romans 8:21

quia et ipsa creatura liberabitur a servitute corruptionis in libertatem gloriæ filiorum Dei.

** Romans 8:22

Scimus enim quod omnis creatura ingemiscit, et parturit usque adhuc.

** Romans 8:23

Non solum autem illa, sed et nos ipsi primitias spiritus habentes : et ipsi intra nos gemimus adoptionem filiorum Dei exspectantes, redemptionem corporis nostri.

** Romans 8:24

Spe enim salvi facti sumus. Spes autem, quæ videtur, non est spes : nam quod videt quis, quid sperat ?

** Romans 8:25

Si autem quod non videmus, speramus : per patientiam exspectamus.  

** Romans 8:26

Similiter autem et Spiritus adjuvat infirmitatem nostram : nam quid oremus, sicut oportet, nescimus : sed ipse Spiritus postulat pro nobis gemitibus inenarrabilibus.

** Romans 8:27

Qui autem scrutatur corda, scit quid desideret Spiritus : quia secundum Deum postulat pro sanctis.  

** Romans 8:28

Scimus autem quoniam diligentibus Deum omnia cooperantur in bonum, iis qui secundum propositum vocati sunt sancti.

** Romans 8:29

Nam quos præscivit, et prædestinavit conformes fieri imaginis Filii sui, ut sit ipse primogenitus in multis fratribus.

** Romans 8:30

Quos autem prædestinavit, hos et vocavit : et quos vocavit, hos et justificavit : quos autem justificavit, illos et glorificavit.

** Romans 8:31

Quid ergo dicemus ad hæc ? si Deus pro nobis, quis contra nos ?

** Romans 8:32

Qui etiam proprio Filio suo non pepercit, sed pro nobis omnibus tradidit illum : quomodo non etiam cum illo omnia nobis donavit ?

** Romans 8:33

Quis accusabit adversus electos Dei ? Deus qui justificat,

** Romans 8:34

quis est qui condemnet ? Christus Jesus, qui mortuus est, immo qui et resurrexit, qui est ad dexteram Dei, qui etiam interpellat pro nobis.

** Romans 8:35

Quis ergo nos separabit a caritate Christi ? tribulatio ? an angustia ? an fames ? an nuditas ? an periculum ? an persecutio ? an gladius ?

** Romans 8:36

(Sicut scriptum est :   Quia propter te mortificamur tota die :  æstimati sumus sicut oves occisionis.)

** Romans 8:37

Sed in his omnibus superamus propter eum qui dilexit nos.

** Romans 8:38

Certus sum enim quia neque mors, neque vita, neque angeli, neque principatus, neque virtutes, neque instantia, neque futura, neque fortitudo,

** Romans 8:39

neque altitudo, neque profundum, neque creatura alia poterit nos separare a caritate Dei, quæ est in Christo Jesu Domino nostro.  

* Romans 9

** Romans 9:1

Veritatem dico in Christo, non mentior : testimonium mihi perhibente conscientia mea in Spiritu Sancto :

** Romans 9:2

quoniam tristitia mihi magna est, et continuus dolor cordi meo.

** Romans 9:3

Optabam enim ego ipse anathema esse a Christo pro fratribus meis, qui sunt cognati mei secundum carnem,

** Romans 9:4

qui sunt Israëlitæ, quorum adoptio est filiorum, et gloria, et testamentum, et legislatio, et obsequium, et promissa :

** Romans 9:5

quorum patres, et ex quibus est Christus secundum carnem, qui est super omnia Deus benedictus in sæcula. Amen.

** Romans 9:6

Non autem quod exciderit verbum Dei. Non enim omnes qui ex Israël sunt, ii sunt Israëlitæ :

** Romans 9:7

neque qui semen sunt Abrahæ, omnes filii : sed in Isaac vocabitur tibi semen :

** Romans 9:8

id est, non qui filii carnis, hi filii Dei : sed qui filii sunt promissionis, æstimantur in semine.

** Romans 9:9

Promissionis enim verbum hoc est : Secundum hoc tempus veniam : et erit Saræ filius.

** Romans 9:10

Non solum autem illa : sed et Rebecca ex uno concubitu habens, Isaac patris nostri.

** Romans 9:11

Cum enim nondum nati fuissent, aut aliquid boni egissent, aut mali (ut secundum electionem propositum Dei maneret),

** Romans 9:12

non ex operibus, sed ex vocante dictum est ei quia major serviet minori,

** Romans 9:13

sicut scriptum est : Jacob dilexi, Esau autem odio habui.  

** Romans 9:14

Quid ergo dicemus ? numquid iniquitas apud Deum ? Absit.

** Romans 9:15

Moysi enim dicit : Miserebor cujus misereor : et misericordiam præstabo cujus miserebor.

** Romans 9:16

Igitur non volentis, neque currentis, sed miserentis est Dei.

** Romans 9:17

Dicit enim Scriptura Pharaoni : Quia in hoc ipsum excitavi te, ut ostendam in te virtutem meam : et ut annuntietur nomen meum in universa terra.

** Romans 9:18

Ergo cujus vult miseretur, et quem vult indurat.

** Romans 9:19

Dicis itaque mihi : Quid adhuc queritur ? voluntati enim ejus quis resistit ?

** Romans 9:20

O homo, tu quis es, qui respondeas Deo ? numquid dicit figmentum ei qui se finxit : Quid me fecisti sic ?

** Romans 9:21

an non habet potestatem figulus luti ex eadem massa facere aliud quidem vas in honorem, aliud vero in contumeliam ?

** Romans 9:22

Quod si Deus volens ostendere iram, et notum facere potentiam suam, sustinuit in multa patientia vasa iræ, apta in interitum,

** Romans 9:23

ut ostenderet divitias gloriæ suæ in vasa misericordiæ, quæ præparavit in gloriam.

** Romans 9:24

Quos et vocavit nos non solum ex Judæis, sed etiam in gentibus,

** Romans 9:25

sicut in Osee dicit : Vocabo non plebem meam, plebem meam : et non dilectam, dilectam : et non misericordiam consecutam, misericordiam consecutam.

** Romans 9:26

Et erit : in loco, ubi dictum est eis : Non plebs mea vos : ibi vocabuntur filii Dei vivi.

** Romans 9:27

Isaias autem clamat pro Israël : Si fuerit numerus filiorum Israël tamquam arena maris, reliquiæ salvæ fient.

** Romans 9:28

Verbum enim consummans, et abbrevians in æquitate : quia verbum breviatum faciet Dominus super terram :

** Romans 9:29

et sicut prædixit Isaias : Nisi Dominus Sabaoth reliquisset nobis semen, sicut Sodoma facti essemus, et sicut Gomorrha similes fuissemus.  

** Romans 9:30

Quid ergo dicemus ? Quod gentes, quæ non sectabantur justitiam, apprehenderunt justitiam : justitiam autem, quæ ex fide est.

** Romans 9:31

Israël vero sectando legem justitiæ, in legem justitiæ non pervenit.

** Romans 9:32

Quare ? Quia non ex fide, sed quasi ex operibus : offenderunt enim in lapidem offensionis,

** Romans 9:33

sicut scriptum est : Ecce pono in Sion lapidem offensionis, et petram scandali : et omnis qui credit in eum, non confundetur.   

* Romans 10

** Romans 10:1

Fratres, voluntas quidem cordis mei, et obsecratio ad Deum, fit pro illis in salutem.

** Romans 10:2

Testimonium enim perhibeo illis quod æmulationem Dei habent, sed non secundum scientiam.

** Romans 10:3

Ignorantes enim justitiam Dei, et suam quærentes statuere, justitiæ Dei non sunt subjecti.

** Romans 10:4

Finis enim legis, Christus, ad justitiam omni credenti.  

** Romans 10:5

Moyses enim scripsit, quoniam justitiam, quæ ex lege est, qui fecerit homo, vivet in ea.

** Romans 10:6

Quæ autem ex fide est justitia, sic dicit : Ne dixeris in corde tuo : Quis ascendet in cælum ? id est, Christum deducere :

** Romans 10:7

aut, Quis descendet in abyssum ? hoc est, Christum a mortuis revocare.

** Romans 10:8

Sed quid dicit Scriptura ? Prope est verbum in ore tuo, et in corde tuo : hoc est verbum fidei, quod prædicamus.

** Romans 10:9

Quia si confitearis in ore tuo Dominum Jesum, et in corde tuo credideris quod Deus illum suscitavit a mortuis, salvus eris.

** Romans 10:10

Corde enim creditur ad justitiam : ore autem confessio fit ad salutem.

** Romans 10:11

Dicit enim Scriptura : Omnis qui credit in illum, non confundetur.

** Romans 10:12

Non enim est distinctio Judæi et Græci : nam idem Dominus omnium, dives in omnes qui invocant illum.

** Romans 10:13

Omnis enim quicumque invocaverit nomen Domini, salvus erit.  

** Romans 10:14

Quomodo ergo invocabunt, in quem non crediderunt ? aut quomodo credent ei, quem non audierunt ? quomodo autem audient sine prædicante ?

** Romans 10:15

quomodo vero prædicabunt nisi mittantur ? sicut scriptum est : Quam speciosi pedes evangelizantium pacem, evangelizantium bona !

** Romans 10:16

Sed non omnes obediunt Evangelio. Isaias enim dicit : Domine, quis credidit auditui nostro ?

** Romans 10:17

Ergo fides ex auditu, auditus autem per verbum Christi.

** Romans 10:18

Sed dico : Numquid non audierunt ? Et quidem in omnem terram exivit sonus eorum, et in fines orbis terræ verba eorum.

** Romans 10:19

Sed dico : Numquid Israël non cognovit ? Primus Moyses dicit : Ego ad æmulationem vos adducam in non gentem : in gentem insipientem, in iram vos mittam.

** Romans 10:20

Isaias autem audet, et dicit : Inventus sum a non quærentibus me : palam apparui iis qui me non interrogabant.

** Romans 10:21

Ad Israël autem dicit : Tota die expandi manus meas ad populum non credentem, et contradicentem.   

* Romans 11

** Romans 11:1

Dico ergo : Numquid Deus repulit populum suum ? Absit. Nam et ego Israëlita sum ex semine Abraham, de tribu Benjamin :

** Romans 11:2

non repulit Deus plebem suam, quam præscivit. An nescitis in Elia quid dicit Scriptura ? quemadmodum interpellat Deum adversum Israël :

** Romans 11:3

Domine, prophetas tuos occiderunt, altaria tua suffoderunt : et ego relictus sum solus, et quærunt animam meam.

** Romans 11:4

Sed quid dicit illi divinum responsum ? Reliqui mihi septem millia virorum, qui non curvaverunt genua ante Baal.

** Romans 11:5

Sic ergo et in hoc tempore reliquiæ secundum electionem gratiæ salvæ factæ sunt.

** Romans 11:6

Si autem gratia, jam non ex operibus : alioquin gratia jam non est gratia.

** Romans 11:7

Quid ergo ? Quod quærebat Israël, hoc non est consecutus : electio autem consecuta est : ceteri vero excæcati sunt :

** Romans 11:8

sicut scriptum est : Dedit illis Deus spiritum compunctionis : oculos ut non videant, et aures ut non audiant, usque in hodiernum diem.

** Romans 11:9

Et David dicit : Fiat mensa eorum in laqueum, et in captionem, et in scandalum, et in retributionem illis.

** Romans 11:10

Obscurentur oculi eorum ne videant : et dorsum eorum semper incurva.  

** Romans 11:11

Dico ergo : Numquid sic offenderunt ut caderent ? Absit. Sed illorum delicto, salus est gentibus ut illos æmulentur.

** Romans 11:12

Quod si delictum illorum divitiæ sunt mundi, et diminutio eorum divitiæ gentium : quanto magis plenitudo eorum ?

** Romans 11:13

Vobis enim dico gentibus : Quamdiu quidem ego sum gentium Apostolus, ministerium meum honorificabo,

** Romans 11:14

si quomodo ad æmulandum provocem carnem meam, et salvos faciam aliquos ex illis.

** Romans 11:15

Si enim amissio eorum, reconciliatio est mundi : quæ assumptio, nisi vita ex mortuis ?

** Romans 11:16

Quod si delibatio sancta est, et massa : et si radix sancta, et rami.

** Romans 11:17

Quod si aliqui ex ramis fracti sunt, tu autem cum oleaster esses, insertus es in illis, et socius radicis, et pinguedinis olivæ factus es,

** Romans 11:18

noli gloriari adversus ramos. Quod si gloriaris : non tu radicem portas, sed radix te.

** Romans 11:19

Dices ergo : Fracti sunt rami ut ego inserar.

** Romans 11:20

Bene : propter incredulitatem fracti sunt. Tu autem fide stas : noli altum sapere, sed time.

** Romans 11:21

Si enim Deus naturalibus ramis non pepercit : ne forte nec tibi parcat.

** Romans 11:22

Vide ergo bonitatem, et severitatem Dei : in eos quidem qui ceciderunt, severitatem : in te autem bonitatem Dei, si permanseris in bonitate, alioquin et tu excideris.

** Romans 11:23

Sed et illi, si non permanserint in incredulitate, inserentur : potens est enim Deus iterum inserere illos.

** Romans 11:24

Nam si tu ex naturali excisus es oleastro, et contra naturam insertus es in bonam olivam : quanto magis ii qui secundum naturam inserentur suæ olivæ ?  

** Romans 11:25

Nolo enim vos ignorare, fratres, mysterium hoc (ut non sitis vobis ipsis sapientes), quia cæcitas ex parte contigit in Israël, donec plenitudo gentium intraret,

** Romans 11:26

et sic omnis Israël salvus fieret, sicut scriptum est : Veniet ex Sion, qui eripiat, et avertat impietatem a Jacob.

** Romans 11:27

Et hoc illis a me testamentum : cum abstulero peccata eorum.

** Romans 11:28

Secundum Evangelium quidem, inimici propter vos : secundum electionem autem, carissimi propter patres.

** Romans 11:29

Sine pœnitentia enim sunt dona et vocatio Dei.

** Romans 11:30

Sicut enim aliquando et vos non credidistis Deo, nunc autem misericordiam consecuti estis propter incredulitatem illorum :

** Romans 11:31

ita et isti nunc non crediderunt in vestram misericordiam : ut et ipsi misericordiam consequantur.

** Romans 11:32

Conclusit enim Deus omnia in incredulitate, ut omnium misereatur.  

** Romans 11:33

O altitudo divitiarum sapientiæ, et scientiæ Dei : quam incomprehensibilia sunt judicia ejus, et investigabiles viæ ejus !

** Romans 11:34

Quis enim cognovit sensum Domini ? aut quis consiliarius ejus fuit ?

** Romans 11:35

aut quis prior dedit illi, et retribuetur ei ?

** Romans 11:36

Quoniam ex ipso, et per ipsum, et in ipso sunt omnia : ipsi gloria in sæcula. Amen.   

* Romans 12

** Romans 12:1

Obsecro itaque vos fratres per misericordiam Dei, ut exhibeatis corpora vestra hostiam viventem, sanctam, Deo placentem, rationabile obsequium vestrum.

** Romans 12:2

Et nolite conformari huic sæculo, sed reformamini in novitate sensus vestri : ut probetis quæ sit voluntas Dei bona, et beneplacens, et perfecta.

** Romans 12:3

Dico enim per gratiam quæ data est mihi, omnibus qui sunt inter vos, non plus sapere quam oportet sapere, sed sapere ad sobrietatem : et unicuique sicut Deus divisit mensuram fidei.

** Romans 12:4

Sicut enim in uno corpore multa membra habemus, omnia autem membra non eumdem actum habent :

** Romans 12:5

ita multi unum corpus sumus in Christo, singuli autem alter alterius membra.

** Romans 12:6

Habentes autem donationes secundum gratiam, quæ data est nobis, differentes : sive prophetiam secundum rationem fidei,

** Romans 12:7

sive ministerium in ministrando, sive qui docet in doctrina,

** Romans 12:8

qui exhortatur in exhortando, qui tribuit in simplicitate, qui præest in sollicitudine, qui miseretur in hilaritate.  

** Romans 12:9

Dilectio sine simulatione : odientes malum, adhærentes bono :

** Romans 12:10

caritate fraternitatis invicem diligentes : honore invicem prævenientes :

** Romans 12:11

sollicitudine non pigri : spiritu ferventes : Domino servientes :

** Romans 12:12

spe gaudentes : in tribulatione patientes : orationi instantes :

** Romans 12:13

necessitatibus sanctorum communicantes : hospitalitatem sectantes.

** Romans 12:14

Benedicite persequentibus vos : benedicite, et nolite maledicere.

** Romans 12:15

Gaudere cum gaudentibus, flere cum flentibus :

** Romans 12:16

idipsum invicem sentientes : non alta sapientes, sed humilibus consentientes. Nolite esse prudentes apud vosmetipsos :

** Romans 12:17

nulli malum pro malo reddentes : providentes bona non tantum coram Deo, sed etiam coram omnibus hominibus.

** Romans 12:18

Si fieri potest, quod ex vobis est, cum omnibus hominibus pacem habentes :

** Romans 12:19

non vosmetipsos defendentes carissimi, sed date locum iræ. Scriptum est enim : Mihi vindicta : ego retribuam, dicit Dominus.

** Romans 12:20

Sed si esurierit inimicus tuus, ciba illum : si sitit, potum da illi : hoc enim faciens, carbones ignis congeres super caput ejus.

** Romans 12:21

Noli vinci a malo, sed vince in bono malum.   

* Romans 13

** Romans 13:1

Omnis anima potestatibus sublimioribus subdita sit : non est enim potestas nisi a Deo : quæ autem sunt, a Deo ordinatæ sunt.

** Romans 13:2

Itaque qui resistit potestati, Dei ordinationi resistit. Qui autem resistunt, ipsi sibi damnationem acquirunt :

** Romans 13:3

nam principes non sunt timori boni operis, sed mali. Vis autem non timere potestatem ? Bonum fac : et habebis laudem ex illa :

** Romans 13:4

Dei enim minister est tibi in bonum. Si autem malum feceris, time : non enim sine causa gladium portat. Dei enim minister est : vindex in iram ei qui malum agit.

** Romans 13:5

Ideo necessitate subditi estote non solum propter iram, sed etiam propter conscientiam.

** Romans 13:6

Ideo enim et tributa præstatis : ministri enim Dei sunt, in hoc ipsum servientes.

** Romans 13:7

Reddite ergo omnibus debita : cui tributum, tributum : cui vectigal, vectigal : cui timorem, timorem : cui honorem, honorem.  

** Romans 13:8

Nemini quidquam debeatis, nisi ut invicem diligatis : qui enim diligit proximum, legem implevit.

** Romans 13:9

Nam : Non adulterabis : non occides : non furaberis : non falsum testimonium dices : non concupisces : et si quod est aliud mandatum, in hoc verbo instauratur : diliges proximum tuum sicut teipsum.

** Romans 13:10

Dilectio proximi malum non operatur. Plenitudo ergo legis est dilectio.  

** Romans 13:11

Et hoc scientes tempus : quia hora est jam nos de somno surgere. Nunc enim propior est nostra salus, quam cum credidimus.

** Romans 13:12

Nox præcessit, dies autem appropinquavit. Abjiciamus ergo opera tenebrarum, et induamur arma lucis.

** Romans 13:13

Sicut in die honeste ambulemus : non in comessationibus, et ebrietatibus, non in cubilibus, et impudicitiis, non in contentione, et æmulatione :

** Romans 13:14

sed induimini Dominum Jesum Christum, et carnis curam ne feceritis in desideriis.   

* Romans 14

** Romans 14:1

Infirmum autem in fide assumite, non in disceptationibus cogitationum.

** Romans 14:2

Alius enim credit se manducare omnia : qui autem infirmus est, olus manducet.

** Romans 14:3

Is qui manducat, non manducantem non spernat : et qui non manducat, manducantem non judicet : Deus enim illum assumpsit.

** Romans 14:4

Tu quis es, qui judicas alienum servum ? domino suo stat, aut cadit : stabit autem : potens est enim Deus statuere illum.

** Romans 14:5

Nam alius judicat diem inter diem : alius autem judicat omnem diem : unusquisque in suo sensu abundet.

** Romans 14:6

Qui sapit diem, Domino sapit, et qui manducat, Domino manducat : gratias enim agit Deo. Et qui non manducat, Domino non manducat, et gratias agit Deo.

** Romans 14:7

Nemo enim nostrum sibi vivit, et nemo sibi moritur.

** Romans 14:8

Sive enim vivemus, Domino vivimus : sive morimur, Domino morimur. Sive ergo vivimus, sive morimur, Domini sumus.

** Romans 14:9

In hoc enim Christus mortuus est, et resurrexit : ut et mortuorum et vivorum dominetur.

** Romans 14:10

Tu autem quid judicas fratrem tuum ? aut tu quare spernis fratrem tuum ? omnes enim stabimus ante tribunal Christi.

** Romans 14:11

Scriptum est enim : Vivo ego, dicit Dominus, quoniam mihi flectetur omne genu : et omnis lingua confitebitur Deo.

** Romans 14:12

Itaque unusquisque nostrum pro se rationem reddet Deo.  

** Romans 14:13

Non ergo amplius invicem judicemus : sed hoc judicate magis, ne ponatis offendiculum fratri, vel scandalum.

** Romans 14:14

Scio, et confido in Domino Jesu, quia nihil commune per ipsum, nisi ei qui existimat quid commune esset, illi commune est.

** Romans 14:15

Si enim propter cibum frater tuus contristatur, jam non secundum caritatem ambulas. Noli cibo tuo illum perdere, pro quo Christus mortuus est.

** Romans 14:16

Non ergo blasphemetur bonum nostrum.

** Romans 14:17

Non est enim regnum Dei esca et potus : sed justitia, et pax, et gaudium in Spiritu Sancto :

** Romans 14:18

qui enim in hoc servit Christo, placet Deo, et probatus est hominibus.

** Romans 14:19

Itaque quæ pacis sunt, sectemur : et quæ ædificationis sunt, in invicem custodiamus.

** Romans 14:20

Noli propter escam destruere opus Dei, omnia quidem sunt munda : sed malum est homini, qui per offendiculum manducat.

** Romans 14:21

Bonum est non manducare carnem, et non bibere vinum, neque in quo frater tuus offenditur, aut scandalizatur, aut infirmatur.

** Romans 14:22

Tu fidem habes ? penes temetipsum habe coram Deo. Beatus qui non judicat semetipsum in eo quod probat.

** Romans 14:23

Qui autem discernit, si manducaverit, damnatus est : quia non ex fide. Omne autem, quod non est ex fide, peccatum est.   

* Romans 15

** Romans 15:1

Debemus autem nos firmiores imbecillitates infirmorum sustinere, et non nobis placere.

** Romans 15:2

Unusquisque vestrum proximo suo placeat in bonum, ad ædificationem.

** Romans 15:3

Etenim Christus non sibi placuit, sed sicut scriptum est : Improperia improperantium tibi ceciderunt super me.

** Romans 15:4

Quæcumque enim scripta sunt, ad nostram doctrinam scripta sunt : ut per patientiam, et consolationem Scripturarum, spem habeamus.

** Romans 15:5

Deus autem patientiæ et solatii det vobis idipsum sapere in alterutrum secundum Jesum Christum :

** Romans 15:6

ut unanimes, uno ore honorificetis Deum et patrem Domini nostri Jesu Christi.

** Romans 15:7

Propter quod suscipite invicem, sicut et Christus suscepit vos in honorem Dei.

** Romans 15:8

Dico enim Christum Jesum ministrum fuisse circumcisionis propter veritatem Dei, ad confirmandas promissiones patrum :

** Romans 15:9

gentes autem super misericordia honorare Deum, sicut scriptum est : Propterea confitebor tibi in gentibus, Domine, et nomini tuo cantabo.

** Romans 15:10

Et iterum dicit : Lætamini gentes cum plebe ejus.

** Romans 15:11

Et iterum : Laudate omnes gentes Dominum : et magnificate eum omnes populi.

** Romans 15:12

Et rursus Isaias ait : Erit radix Jesse, et qui exsurget regere gentes, in eum gentes sperabunt.

** Romans 15:13

Deus autem spei repleat vos omni gaudio, et pace in credendo : ut abundetis in spe, et virtute Spiritus Sancti.  

** Romans 15:14

Certus sum autem fratres mei et ego ipse de vobis, quoniam et ipsi pleni estis dilectione, repleti omni scientia, ita ut possitis alterutrum monere.

** Romans 15:15

Audacius autem scripsi vobis fratres ex parte, tamquam in memoriam vos reducens : propter gratiam, quæ data est mihi a Deo,

** Romans 15:16

ut sim minister Christi Jesu in gentibus : sanctificans Evangelium Dei, ut fiat oblatio gentium accepta, et sanctificata in Spiritu Sancto.

** Romans 15:17

Habeo igitur gloriam in Christo Jesu ad Deum.

** Romans 15:18

Non enim audeo aliquid loqui eorum, quæ per me non efficit Christus in obedientiam gentium, verbo et factis :

** Romans 15:19

in virtute signorum, et prodigiorum, in virtute Spiritus Sancti : ita ut ab Jerusalem per circuitum usque ad Illyricum repleverim Evangelium Christi.

** Romans 15:20

Sic autem prædicavi Evangelium hoc, non ubi nominatus est Christus, ne super alienum fundamentum ædificarem :

** Romans 15:21

sed sicut scriptum est : Quibus non est annuntiatum de eo, videbunt : et qui non audierunt, intelligent.  

** Romans 15:22

Propter quod et impediebar plurimum venire ad vos, et prohibitus sum usque adhuc.

** Romans 15:23

Nunc vero ulterius locum non habens in his regionibus, cupiditatem autem habens veniendi ad vos ex multis jam præcedentibus annis :

** Romans 15:24

cum in Hispaniam proficisci cœpero, spero quod præteriens videam vos, et a vobis deducar illuc, si vobis primum ex parte fruitus fuero.

** Romans 15:25

Nunc igitur proficiscar in Jerusalem ministrare sanctis.

** Romans 15:26

Probaverunt enim Macedonia et Achaia collationem aliquam facere in pauperes sanctorum, qui sunt in Jerusalem.

** Romans 15:27

Placuit enim eis : et debitores sunt eorum. Nam si spiritualium eorum participes facti sunt gentiles, debent et in carnalibus ministrare illis.

** Romans 15:28

Hoc igitur cum consummavero, et assignavero eis fructum hunc, per vos proficiscar in Hispaniam.

** Romans 15:29

Scio autem quoniam veniens ad vos, in abundantia benedictionis Evangelii Christi veniam.

** Romans 15:30

Obsecro ergo vos fratres per Dominum nostrum Jesum Christum, et per caritatem Sancti Spiritus, ut adjuvetis me in orationibus vestris pro me ad Deum,

** Romans 15:31

ut liberer ab infidelibus, qui sunt in Judæa, et obsequii mei oblatio accepta fiat in Jerusalem sanctis,

** Romans 15:32

ut veniam ad vos in gaudio per voluntatem Dei, et refrigerer vobiscum.

** Romans 15:33

Deus autem pacis sit cum omnibus vobis. Amen.   

* Romans 16

** Romans 16:1

Commendo autem vobis Phœben sororem nostram, quæ est in ministerio ecclesiæ, quæ est in Cenchris :

** Romans 16:2

ut eam suscipiatis in Domino digne sanctis : et assistatis ei in quocumque negotio vestri indiguerit : etenim ipsa quoque astitit multis, et mihi ipsi.

** Romans 16:3

Salutate Priscam et Aquilam, adjutores meos in Christo Jesu

** Romans 16:4

(qui pro anima mea suas cervices supposuerunt : quibus non solus ego gratias ago, sed et cunctæ ecclesiæ gentium),

** Romans 16:5

et domesticam ecclesiam eorum. Salutate Epænetum dilectum mihi, qui est primitivus Asiæ in Christo.

** Romans 16:6

Salutate Mariam, quæ multum laboravit in vobis.

** Romans 16:7

Salutate Andronicum et Juniam, cognatos, et concaptivos meos : qui sunt nobiles in Apostolis, qui et ante me fuerunt in Christo.

** Romans 16:8

Salutate Ampliatum dilectissimum mihi in Domino.

** Romans 16:9

Salutate Urbanum adjutorem nostrum in Christo Jesu, et Stachyn dilectum meum.

** Romans 16:10

Salutate Apellen probum in Christo.

** Romans 16:11

Salutate eos qui sunt ex Aristoboli domo. Salutate Herodionem cognatum meum. Salutate eos qui sunt ex Narcisi domo, qui sunt in Domino.

** Romans 16:12

Salutate Tryphænam et Tryphosam, quæ laborant in Domino. Salutate Persidem carissimam, quæ multum laboravit in Domino.

** Romans 16:13

Salutate Rufum electum in Domino, et matrem ejus, et meam.

** Romans 16:14

Salutate Asyncritum, Phlegontem, Hermam, Patrobam, Hermen, et qui cum eis sunt, fratres.

** Romans 16:15

Salutate Philologum et Juliam, Nereum, et sororem ejus, et Olympiadem, et omnes qui cum eis sunt, sanctos.

** Romans 16:16

Salutate invicem in osculo sancto. Salutant vos omnes ecclesiæ Christi.

** Romans 16:17

Rogo autem vos fratres, ut observetis eos qui dissensiones et offendicula, præter doctrinam, quam vos didicistis, faciunt, et declinate ab illis.

** Romans 16:18

Hujuscemodi enim Christo Domino nostro non serviunt, sed suo ventri : et per dulces sermones et benedictiones seducunt corda innocentium.

** Romans 16:19

Vestra enim obedientia in omnem locum divulgata est. Gaudeo igitur in vobis. Sed volo vos sapientes esse in bono, et simplices in malo.

** Romans 16:20

Deus autem pacis conterat Satanam sub pedibus vestris velociter. Gratia Domini nostri Jesu Christi vobiscum.

** Romans 16:21

Salutat vos Timotheus adjutor meus, et Lucius, et Jason, et Sosipater cognati mei.

** Romans 16:22

Saluto vos ego Tertius, qui scripsi epistolam, in Domino.

** Romans 16:23

Salutat vos Cajus hospes meus, et universa ecclesia. Salutat vos Erastus arcarius civitatis, et Quartus, frater.

** Romans 16:24

Gratia Domini nostri Jesu Christi cum omnibus vobis. Amen.  

** Romans 16:25

Ei autem, qui potens est vos confirmare juxta Evangelium meum, et prædicationem Jesu Christi, secundum revelationem mysterii temporibus æternis taciti

** Romans 16:26

(quod nunc patefactum est per Scripturas prophetarum secundum præceptum æterni Dei, ad obeditionem fidei), in cunctis gentibus cogniti,

** Romans 16:27

soli sapienti Deo, per Jesum Christum, cui honor et gloria in sæcula sæculorum. Amen.    

