* Ruth 1

** Ruth 1:1

In diebus unius judicis, quando judices præerant, facta est fames in terra. Abiitque homo de Bethlehem Juda, ut peregrinaretur in regione Moabitide cum uxore sua ac duobus liberis.

** Ruth 1:2

Ipse vocabatur Elimelech, et uxor ejus Noëmi : et duo filii, alter Mahalon, et alter Chelion, Ephrathæi de Bethlehem Juda. Ingressique regionem Moabitidem, morabantur ibi.

** Ruth 1:3

Et mortuus est Elimelech maritus Noëmi : remansitque ipsa cum filiis.

** Ruth 1:4

Qui acceperunt uxores Moabitidas, quarum una vocabatur Orpha, altera vero Ruth. Manseruntque ibi decem annis,

** Ruth 1:5

et ambo mortui sunt, Mahalon videlicet et Chelion : remansitque mulier orbata duobus liberis ac marito.

** Ruth 1:6

Et surrexit ut in patriam pergeret cum utraque nuru sua de regione Moabitide : audierat enim quod respexisset Dominus populum suum, et dedisset eis escas.  

** Ruth 1:7

Egressa est itaque de loco peregrinationis suæ, cum utraque nuru : et jam in via revertendi posita in terram Juda,

** Ruth 1:8

dixit ad eas : Ite in domum matris vestræ : faciat vobiscum Dominus misericordiam, sicut fecistis cum mortuis, et mecum.

** Ruth 1:9

Det vobis invenire requiem in domibus virorum quos sortituræ estis. Et osculata est eas. Quæ elevata voce flere cœperunt,

** Ruth 1:10

et dicere : Tecum pergemus ad populum tuum.

** Ruth 1:11

Quibus illa respondit : Revertimini, filiæ meæ, cur venitis mecum ? num ultra habeo filios in utero meo, ut viros ex me sperare possitis ?

** Ruth 1:12

Revertimini, filiæ meæ, et abite : jam enim senectute confecta sum, nec apta vinculo conjugali : etiamsi possem hac nocte concipere, et parere filios,

** Ruth 1:13

si eos expectare velitis donec crescant, et annos pubertatis impleant, ante eritis vetulæ quam nubatis. Nolite, quæso, filiæ meæ : quia vestra angustia magis me premit, et egressa est manus Domini contra me.

** Ruth 1:14

Elevata igitur voce, rursum flere cœperunt : Orpha osculata est socrum, ac reversa est ; Ruth adhæsit socrui suæ :

** Ruth 1:15

cui dixit Noëmi : En reversa est cognata tua ad populum suum, et ad deos suos, vade cum ea.

** Ruth 1:16

Quæ respondit : Ne adverseris mihi ut relinquam te et abeam : quocumque enim perrexeris, pergam, et ubi morata fueris, et ego pariter morabor. Populus tuus populus meus, et Deus tuus Deus meus.

** Ruth 1:17

Quæ te terra morientem susceperit, in ea moriar : ibique locum accipiam sepulturæ. Hæc mihi faciat Dominus, et hæc addat, si non sola mors me et te separaverit.  

** Ruth 1:18

Videns ergo Noëmi quod obstinato animo Ruth decrevisset secum pergere, adversari noluit, nec ad suos ultra reditum persuadere :

** Ruth 1:19

profectæque sunt simul, et venerunt in Bethlehem. Quibus urbem ingressis, velox apud cunctos fama percrebruit : dicebantque mulieres : Hæc est illa Noëmi.

** Ruth 1:20

Quibus ait : Ne vocetis me Noëmi (id est, pulchram), sed vocate me Mara (id est, amaram), quia amaritudine valde replevit me Omnipotens.

** Ruth 1:21

Egressa sum plena, et vacuam reduxit me Dominus. Cur ergo vocatis me Noëmi, quam Dominus humiliavit, et afflixit Omnipotens ?

** Ruth 1:22

Venit ergo Noëmi cum Ruth Moabitide nuru sua, de terra peregrinationis suæ : ac reversa est in Bethlehem, quando primum hordea metebantur.   

* Ruth 2

** Ruth 2:1

Erat autem viro Elimelech consanguineus, homo potens, et magnarum opum, nomine Booz.

** Ruth 2:2

Dixitque Ruth Moabitis ad socrum suam : Si jubes, vadam in agrum, et colligam spicas quæ fugerint manus metentium, ubicumque clementis in me patrisfamilias reperero gratiam. Cui illa respondit : Vade, filia mea.

** Ruth 2:3

Abiit itaque et colligebat spicas post terga metentium. Accidit autem ut ager ille haberet dominum nomine Booz, qui erat de cognatione Elimelech.

** Ruth 2:4

Et ecce, ipse veniebat de Bethlehem, dixitque messoribus : Dominus vobiscum. Qui responderunt ei : Benedicat tibi Dominus.

** Ruth 2:5

Dixitque Booz juveni, qui messoribus præerat : Cujus est hæc puella ?

** Ruth 2:6

Cui respondit : Hæc est Moabitis, quæ venit cum Noëmi, de regione Moabitide,

** Ruth 2:7

et rogavit ut spicas colligeret remanentes, sequens messorum vestigia : et de mane usque nunc stat in agro, et ne ad momentum quidem domum reversa est.

** Ruth 2:8

Et ait Booz ad Ruth : Audi, filia, ne vadas in alterum agrum ad colligendum, nec recedas ab hoc loco : sed jungere puellis meis,

** Ruth 2:9

et ubi messuerint, sequere. Mandavi enim pueris meis, ut nemo molestus sit tibi : sed etiam si sitieris, vade ad sarcinulas, et bibe aquas, de quibus et pueri bibunt.

** Ruth 2:10

Quæ cadens in faciem suam et adorans super terram, dixit ad eum : Unde mihi hoc, ut invenirem gratiam ante oculos tuos, et nosse me dignareris peregrinam mulierem ?

** Ruth 2:11

Cui ille respondit : Nuntiata sunt mihi omnia quæ feceris socrui tuæ post mortem viri tui : et quod reliqueris parentes tuos, et terram in qua nata es, et veneris ad populum, quem antea nesciebas.

** Ruth 2:12

Reddat tibi Dominus pro opere tuo, et plenam mercedem recipias a Domino Deo Israël, ad quem venisti, et sub cujus confugisti alas.

** Ruth 2:13

Quæ ait : Inveni gratiam apud oculos tuos, domine mi, qui consolatus es me, et locutus es ad cor ancillæ tuæ, quæ non sum similis unius puellarum tuarum.

** Ruth 2:14

Dixitque ad eam Booz : Quando hora vescendi fuerit, veni huc, et comede panem, et intinge buccellam tuam in aceto. Sedit itaque ad messorum latus, et congessit polentam sibi, comeditque et saturata est, et tulit reliquias.

** Ruth 2:15

Atque inde surrexit, ut spicas ex more colligeret. Præcepit autem Booz pueris suis, dicens : Etiamsi vobiscum metere voluerit, ne prohibeatis eam :

** Ruth 2:16

et de vestris quoque manipulis projicite de industria, et remanere permittite, ut absque rubore colligat, et colligentem nemo corripiat.

** Ruth 2:17

Collegit ergo in agro usque ad vesperam : et quæ collegerat virga cædens et excutiens, invenit hordei quasi ephi mensuram, id est, tres modios.

** Ruth 2:18

Quos portans reversa est in civitatem, et ostendit socrui suæ : insuper protulit, et dedit ei de reliquiis cibi sui, quo saturata fuerat.

** Ruth 2:19

Dixitque ei socrus sua : Ubi hodie collegisti, et ubi fecisti opus ? sit benedictus qui misertus est tui. Indicavitque ei apud quem fuisset operata : et nomen dixit viri, quod Booz vocaretur.

** Ruth 2:20

Cui respondit Noëmi : Benedictus sit a Domino : quoniam eamdem gratiam, quam præbuerat vivis, servavit et mortuis. Rursumque ait : Propinquus noster est homo.

** Ruth 2:21

Et ait Ruth : Hoc quoque, inquit, præcepit mihi, ut tamdiu messoribus ejus jungerer, donec omnes segetes meterentur.

** Ruth 2:22

Cui dixit socrus : Melius est, filia mea, ut cum puellis ejus exeas ad metendum, ne in alieno agro quispiam resistat tibi.

** Ruth 2:23

Juncta est itaque puellis Booz : et tamdiu cum eis messuit, donec hordea et triticum in horreis conderentur.   

* Ruth 3

** Ruth 3:1

Postquam autem reversa est ad socrum suam, audivit ab ea : Filia mea, quæram tibi requiem, et providebo ut bene sit tibi.

** Ruth 3:2

Booz iste, cujus puellis in agro juncta es, propinquus noster est, et hac nocte aream hordei ventilat.

** Ruth 3:3

Lavare igitur, et ungere, et induere cultioribus vestimentis, et descende in aream : non te videat homo, donec esum potumque finierit.

** Ruth 3:4

Quando autem ierit ad dormiendum, nota locum in quo dormiat : veniesque et discooperies pallium, quo operitur a parte pedum, et projicies te, et ibi jacebis : ipse autem dicet quid agere debeas.

** Ruth 3:5

Quæ respondit : Quidquid præceperis, faciam.

** Ruth 3:6

Descenditque in aream, et fecit omnia quæ sibi imperaverat socrus.  

** Ruth 3:7

Cumque comedisset Booz, et bibisset, et factus esset hilarior, issetque ad dormiendum juxta acervum manipulorum, venit abscondite, et discooperto pallio, a pedibus ejus se projecit.

** Ruth 3:8

Et ecce, nocte jam media expavit homo, et conturbatus est : viditque mulierem jacentem ad pedes suos,

** Ruth 3:9

et ait illi : Quæ es ? Illaque respondit : Ego sum Ruth ancilla tua : expande pallium tuum super famulam tuam, quia propinquus es.

** Ruth 3:10

Et ille : Benedicta, inquit, es a Domino, filia, et priorem misericordiam posteriore superasti : quia non est secuta juvenes, pauperes sive divites.

** Ruth 3:11

Noli ergo metuere, sed quidquid dixeris mihi, faciam tibi. Scit enim omnis populus, qui habitat intra portas urbis meæ, mulierem te esse virtutis.

** Ruth 3:12

Nec abnuo me propinquum, sed est alius me propinquior.

** Ruth 3:13

Quiesce hac nocte : et facto mane, si te voluerit propinquitatis jure retinere, bene res acta est : sin autem ille noluerit, ego te absque ulla dubitatione suscipiam, vivit Dominus. Dormi usque mane.

** Ruth 3:14

Dormivit itaque ad pedes ejus, usque ad noctis abscessum. Surrexit itaque antequam homines se cognoscerent mutuo, et dixit Booz : Cave ne quis noverit quod huc veneris.

** Ruth 3:15

Et rursum : Expande, inquit, pallium tuum, quo operiris, et tene utraque manu. Qua extendente, et tenente, mensus est sex modios hordei, et posuit super eam. Quæ portans ingressa est civitatem,

** Ruth 3:16

et venit ad socrum suam. Quæ dixit ei : Quid egisti, filia ? Narravitque ei omnia, quæ sibi fecisset homo.

** Ruth 3:17

Et ait : Ecce sex modios hordei dedit mihi, et ait : Nolo vacuam te reverti ad socrum tuam.

** Ruth 3:18

Dixitque Noëmi : Expecta, filia, donec videamus quem res exitum habeat : neque enim cessabit homo, nisi compleverit quod locutus est.   

* Ruth 4

** Ruth 4:1

Ascendit ergo Booz ad portam, et sedit ibi. Cumque vidisset propinquum præterire, de quo prius sermo habitus est, dixit ad eum : Declina paulisper, et sede hic : vocans eum nomine suo. Qui divertit, et sedit.

** Ruth 4:2

Tollens autem Booz decem viros de senioribus civitatis, dixit ad eos : Sedete hic.

** Ruth 4:3

Quibus sedentibus, locutus est ad propinquum : Partem agri fratris nostri Elimelech vendet Noëmi, quæ reversa est de regione Moabitide :

** Ruth 4:4

quod audire te volui, et tibi dicere coram cunctis sedentibus, et majoribus natu de populo meo. Si vis possidere jure propinquitatis, eme, et posside : sin autem displicet tibi, hoc ipsum indica mihi, ut sciam quid facere debeam : nullus enim est propinquus, excepto te, qui prior es, et me, qui secundus sum. At ille respondit : Ego agrum emam.

** Ruth 4:5

Cui dixit Booz : Quando emeris agrum de manu mulieris, Ruth quoque Moabitidem, quæ uxor defuncti fuit, debes accipere : ut suscites nomen propinqui tui in hæreditate sua.

** Ruth 4:6

Qui respondit : Cedo juri propinquitatis : neque enim posteritatem familiæ meæ delere debeo : tu meo utere privilegio, quo me libenter carere profiteor.

** Ruth 4:7

Hic autem erat mos antiquitus in Israël inter propinquos, ut siquando alter alteri suo juri cedebat, ut esset firma concessio, solvebat homo calceamentum suum, et dabat proximo suo : hoc erat testimonium cessionis in Israël.

** Ruth 4:8

Dixit ergo propinquo suo Booz : Tolle calceamentum tuum. Quod statim solvit de pede suo.

** Ruth 4:9

At ille majoribus natu, et universo populo : Testes vos, inquit, estis hodie, quod possederim omnis quæ fuerunt Elimelech, et Chelion, et Mahalon, tradente Noëmi ;

** Ruth 4:10

et Ruth Moabitidem, uxorem Mahalon, in conjugium sumpserim, ut suscitem nomen defuncti in hæreditate sua, ne vocabulum ejus de familia sua ac fratribus et populo deleatur. Vos, inquam, hujus rei testes estis.

** Ruth 4:11

Respondit omnis populus, qui erat in porta, et majores natu : Nos testes sumus : faciat Dominus hanc mulierem, quæ ingreditur domum tuam, sicut Rachel et Liam, quæ ædificaverunt domum Israël : ut sit exemplum virtutis in Ephratha, et habeat celebre nomen in Bethlehem :

** Ruth 4:12

fiatque domus tua sicut domus Phares, quem Thamar peperit Judæ, de semine quod tibi dederit Dominus ex hac puella.  

** Ruth 4:13

Tulit itaque Booz Ruth, et accepit uxorem : ingressusque est ad eam, et dedit illi Dominus ut conciperet, et pareret filium.

** Ruth 4:14

Dixeruntque mulieres ad Noëmi : Benedictus Dominus, qui non est passus ut deficeret successor familiæ tuæ, et vocaretur nomen ejus in Israël :

** Ruth 4:15

et habeas qui consoletur animam tuam, et enutriat senectutem : de nuru enim tua natus est, quæ te diligit, et multo tibi melior est, quam si septem haberes filios.

** Ruth 4:16

Susceptumque Noëmi puerum posuit in sinu suo, et nutricis ac gerulæ fungebatur officio.

** Ruth 4:17

Vicinæ autem mulieris congratulantes ei, et dicentes : Natus est filius Noëmi : vocaverunt nomen ejus Obed : hic est pater Isai, patris David.

** Ruth 4:18

Hæ sunt generationes Phares : Phares genuit Esron,

** Ruth 4:19

Esron genuit Aram, Aram genuit Aminadab,

** Ruth 4:20

Aminadab genuit Nahasson, Nahasson genuit Salmon,

** Ruth 4:21

Salmon genuit Booz, Booz genuit Obed,

** Ruth 4:22

Obed genuit Isai, Isai genuit David.    

