* Sirach 1

** Sirach 1:1

Omnis sapientia a Domino Deo est :  et cum illo fuit semper, et est ante ævum. 

** Sirach 1:2

Arenam maris, et pluviæ guttas,  et dies sæculi, quis dinumeravit ?  altitudinem cæli, et latitudinem terræ,  et profundum abyssi, quis dimensus est ? 

** Sirach 1:3

sapientiam Dei præcedentem omnia, quis investigavit ? 

** Sirach 1:4

Prior omnium creata est sapientia,  et intellectus prudentiæ ab ævo. 

** Sirach 1:5

Fons sapientiæ verbum Dei in excelsis,  et ingressus illius mandata æterna. 

** Sirach 1:6

Radix sapientiæ cui revelata est ?  et astutias illius quis agnovit ? 

** Sirach 1:7

disciplina sapientiæ cui revelata est et manifestata ?  et multiplicationem ingressus illius quis intellexit ? 

** Sirach 1:8

Unus est altissimus, Creator omnipotens,  et rex potens et metuendus nimis,  sedens super thronum illius, et dominans Deus. 

** Sirach 1:9

Ipse creavit illam in Spiritu Sancto,  et vidit, et dinumeravit, et mensus est : 

** Sirach 1:10

et effudit illam super omnia opera sua,  et super omnem carnem, secundum datum suum,  et præbuit illam diligentibus se. 

** Sirach 1:11

Timor Domini gloria, et gloriatio,  et lætitia, et corona exsultationis. 

** Sirach 1:12

Timor Domini delectabit cor,  et dabit lætitiam, et gaudium, et longitudinem dierum. 

** Sirach 1:13

Timenti Dominum bene erit in extremis,  et in die defunctionis suæ benedicetur. 

** Sirach 1:14

Dilectio Dei honorabilis sapientia : 

** Sirach 1:15

quibus autem apparuerit in visu diligunt eam in visione,  et in agnitione magnalium suorum. 

** Sirach 1:16

Initium sapientiæ timor Domini :  et cum fidelibus in vulva concreatus est :  cum electis feminis graditur,  et cum justis et fidelibus agnoscitur. 

** Sirach 1:17

Timor Domini scientiæ religiositas : 

** Sirach 1:18

religiositas custodiet et justificabit cor ;  jucunditatem atque gaudium dabit. 

** Sirach 1:19

Timenti Dominum bene erit,  et in diebus consummationis illius benedicetur. 

** Sirach 1:20

Plenitudo sapientiæ est timere Deum,  et plenitudo a fructibus illius. 

** Sirach 1:21

Omnem domum illius implebit a generationibus,  et receptacula a thesauris illius. 

** Sirach 1:22

Corona sapientiæ timor Domini,  replens pacem et salutis fructum : 

** Sirach 1:23

et vidit, et dinumeravit eam :  utraque autem sunt dona Dei. 

** Sirach 1:24

Scientiam et intellectum prudentiæ sapientia compartietur,  et gloriam tenentium se exaltat. 

** Sirach 1:25

Radix sapientiæ est timere Dominum,  et rami illius longævi. 

** Sirach 1:26

In thesauris sapientiæ intellectus et scientiæ religiositas :  execratio autem peccatoribus sapientia. 

** Sirach 1:27

Timor Domini expellit peccatum : 

** Sirach 1:28

nam qui sine timore est non poterit justificari :  iracundia enim animositatis illius subversio illius est. 

** Sirach 1:29

Usque in tempus sustinebit patiens,  et postea redditio jucunditatis. 

** Sirach 1:30

Bonus sensus usque in tempus abscondet verba illius,  et labia multorum enarrabunt sensum illius. 

** Sirach 1:31

In thesauris sapientiæ significatio disciplinæ : 

** Sirach 1:32

execratio autem peccatori cultura Dei. 

** Sirach 1:33

Fili, concupiscens sapientiam, conserva justitiam,  et Deus præbebit illam tibi. 

** Sirach 1:34

Sapientia enim et disciplina timor Domini :  et quod beneplacitum est illi, 

** Sirach 1:35

fides et mansuetudo,  et adimplebit thesauros illius. 

** Sirach 1:36

Ne sis incredibilis timori Domini,  et ne accesseris ad illum duplici corde. 

** Sirach 1:37

Ne fueris hypocrita in conspectu hominum,  et non scandalizeris in labiis tuis. 

** Sirach 1:38

Attende in illis, ne forte cadas,  et adducas animæ tuæ inhonorationem : 

** Sirach 1:39

et revelet Deus absconsa tua,  et in medio synagogæ elidat te : 

** Sirach 1:40

quoniam accessisti maligne ad Dominum,  et cor tuum plenum est dolo et fallacia.  

* Sirach 2

** Sirach 2:1

Fili, accedens ad servitutem Dei  sta in justitia et timore,  et præpara animam tuam ad tentationem. 

** Sirach 2:2

Deprime cor tuum, et sustine :  inclina aurem tuam, et suscipe verba intellectus :  et ne festines in tempore obductionis. 

** Sirach 2:3

Sustine sustentationes Dei :  conjungere Deo, et sustine,  ut crescat in novissimo vita tua. 

** Sirach 2:4

Omne quod tibi applicitum fuerit accipe :  et in dolore sustine,  et in humilitate tua patientiam habe : 

** Sirach 2:5

quoniam in igne probatur aurum et argentum,  homines vero receptibiles in camino humiliationis. 

** Sirach 2:6

Crede Deo, et recuperabit te :  et dirige viam tuam, et spera in illum :  serva timorem illius, et in illo veterasce. 

** Sirach 2:7

Metuentes Dominum, sustinete misericordiam ejus :  et non deflectatis ab illo, ne cadatis. 

** Sirach 2:8

Qui timetis Dominum, credite illi,  et non evacuabitur merces vestra. 

** Sirach 2:9

Qui timetis Dominum, sperate in illum,  et in oblectationem veniet vobis misericordia. 

** Sirach 2:10

Qui timetis Dominum, diligite illum,  et illuminabuntur corda vestra. 

** Sirach 2:11

Respicite, filii, nationes hominum :  et scitote quia nullus speravit in Domino et confusus est. 

** Sirach 2:12

Quis enim permansit in mandatis ejus, et derelictus est ?  aut quis invocavit eum, et despexit illum ? 

** Sirach 2:13

Quoniam pius et misericors est Deus,  et remittet in die tribulationis peccata,  et protector est omnibus exquirentibus se in veritate. 

** Sirach 2:14

Væ duplici corde, et labiis scelestis,  et manibus malefacientibus,  et peccatori terram ingredienti duabus viis ! 

** Sirach 2:15

Væ dissolutis corde, qui non credunt Deo,  et ideo non protegentur ab eo ! 

** Sirach 2:16

Væ his qui perdiderunt sustinentiam,  et qui dereliquerunt vias rectas,  et diverterunt in vias pravas ! 

** Sirach 2:17

Et quid facient cum inspicere cœperit Dominus ? 

** Sirach 2:18

Qui timent Dominum non erunt incredibiles verbo illius :  et qui diligunt illum conservabunt viam illius. 

** Sirach 2:19

Qui timent Dominum inquirent quæ beneplacita sunt ei,  et qui diligunt eum replebuntur lege ipsius. 

** Sirach 2:20

Qui timent Dominum præparabunt corda sua,  et in conspectu illius sanctificabunt animas suas. 

** Sirach 2:21

Qui timent Dominum custodiunt mandata illius,  et patientiam habebunt usque ad inspectionem illius, 

** Sirach 2:22

dicentes : Si pœnitentiam non egerimus,  incidemus in manus Domini, et non in manus hominum. 

** Sirach 2:23

Secundum enim magnitudinem ipsius,  sic et misericordia illius cum ipso est.  

* Sirach 3

** Sirach 3:1

Filii sapientiæ ecclesia justorum,  et natio illorum obedientia et dilectio. 

** Sirach 3:2

Judicium patris audite, filii,  et sic facite, ut salvi sitis. 

** Sirach 3:3

Deus enim honoravit patrem in filiis :  et judicium matris exquirens, firmavit in filios. 

** Sirach 3:4

Qui diligit Deum exorabit pro peccatis,  et continebit se ab illis,  et in oratione dierum exaudietur. 

** Sirach 3:5

Et sicut qui thesaurizat,  ita et qui honorificat matrem suam. 

** Sirach 3:6

Qui honorat patrem suum jucundabitur in filiis,  et in die orationis suæ exaudietur. 

** Sirach 3:7

Qui honorat patrem suum vita vivet longiore,  et qui obedit patri refrigerabit matrem. 

** Sirach 3:8

Qui timet Dominum honorat parentes,  et quasi dominis serviet his qui se genuerunt. 

** Sirach 3:9

In opere, et sermone, et omni patientia, honora patrem tuum, 

** Sirach 3:10

ut superveniat tibi benedictio ab eo,  et benedictio illius in novissimo maneat. 

** Sirach 3:11

Benedictio patris firmat domos filiorum :  maledictio autem matris eradicat fundamenta. 

** Sirach 3:12

Ne glorieris in contumelia patris tui :  non enim est tibi gloria ejus confusio. 

** Sirach 3:13

Gloria enim hominis ex honore patris sui,  et dedecus filii pater sine honore. 

** Sirach 3:14

Fili, suscipe senectam patris tui,  et non contristes eum in vita illius : 

** Sirach 3:15

et si defecerit sensu, veniam da,  et ne spernas eum in virtute tua :  eleemosyna enim patris non erit in oblivione. 

** Sirach 3:16

Nam pro peccato matris restituetur tibi bonum : 

** Sirach 3:17

et in justitia ædificabitur tibi,  et in die tribulationis commemorabitur tui,  et sicut in sereno glacies, solventur peccata tua. 

** Sirach 3:18

Quam malæ famæ est qui derelinquit patrem,  et est maledictus a Deo qui exasperat matrem ! 

** Sirach 3:19

Fili, in mansuetudine opera tua perfice,  et super hominum gloriam diligeris. 

** Sirach 3:20

Quanto magnus es, humilia te in omnibus,  et coram Deo invenies gratiam : 

** Sirach 3:21

quoniam magna potentia Dei solius,  et ab humilibus honoratur. 

** Sirach 3:22

Altiora te ne quæsieris,  et fortiora te ne scrutatus fueris :  sed quæ præcepit tibi Deus, illa cogita semper,  et in pluribus operibus ejus ne fueris curiosus. 

** Sirach 3:23

Non est enim tibi necessarium  ea, quæ abscondita sunt, videre oculis tuis. 

** Sirach 3:24

In supervacuis rebus noli scrutari multipliciter,  et in pluribus operibus ejus non eris curiosus. 

** Sirach 3:25

Plurima enim super sensum hominum ostensa sunt tibi : 

** Sirach 3:26

multos quoque supplantavit suspicio illorum,  et in vanitate detinuit sensus illorum. 

** Sirach 3:27

Cor durum habebit male in novissimo,  et qui amat periculum in illo peribit. 

** Sirach 3:28

Cor ingrediens duas vias non habebit successus,  et pravus corde in illis scandalizabitur. 

** Sirach 3:29

Cor nequam gravabitur in doloribus,  et peccator adjiciet ad peccandum. 

** Sirach 3:30

Synagogæ superborum non erit sanitas,  frutex enim peccati radicabitur in illis, et non intelligetur. 

** Sirach 3:31

Cor sapientis intelligitur in sapientia,  et auris bona audiet cum omni concupiscentia sapientiam. 

** Sirach 3:32

Sapiens cor et intelligibile abstinebit se a peccatis,  et in operibus justitiæ successus habebit. 

** Sirach 3:33

Ignem ardentem exstinguit aqua,  et eleemosyna resistit peccatis : 

** Sirach 3:34

et Deus prospector est ejus qui reddit gratiam :  meminit ejus in posterum,  et in tempore casus sui inveniet firmamentum.  

* Sirach 4

** Sirach 4:1

Fili, eleemosynam pauperis ne defraudes,  et oculos tuos ne transvertas a paupere. 

** Sirach 4:2

Animam esurientem ne despexeris,  et non exasperes pauperem in inopia sua. 

** Sirach 4:3

Cor inopis ne afflixeris,  et non protrahas datum angustianti. 

** Sirach 4:4

Rogationem contribulati ne abjicias,  et non avertas faciem tuam ab egeno. 

** Sirach 4:5

Ab inope ne avertas oculos tuos propter iram :  et non relinquas quærentibus tibi retro maledicere. 

** Sirach 4:6

Maledicentis enim tibi in amaritudine animæ,  exaudietur deprecatio illius :  exaudiet autem eum qui fecit illum. 

** Sirach 4:7

Congregationi pauperum affabilem te facito :  et presbytero humilia animam tuam,  et magnato humilia caput tuum. 

** Sirach 4:8

Declina pauperi sine tristitia aurem tuam,  et redde debitum tuum,  et responde illi pacifica in mansuetudine. 

** Sirach 4:9

Libera eum qui injuriam patitur de manu superbi,  et non acide feras in anima tua. 

** Sirach 4:10

In judicando esto pupillis misericors ut pater,  et pro viro matri illorum : 

** Sirach 4:11

et eris tu velut filius Altissimi obediens,  et miserebitur tui magis quam mater. 

** Sirach 4:12

Sapientia filiis suis vitam inspirat :  et suscipit inquirentes se,  et præibit in via justitiæ. 

** Sirach 4:13

Et qui illam diligit, diligit vitam,  et qui vigilaverint ad illam complectentur placorem ejus. 

** Sirach 4:14

Qui tenuerint illam, vitam hæreditabunt :  et quo introibit benedicet Deus. 

** Sirach 4:15

Qui serviunt ei obsequentes erunt sancto :  et eos qui diligunt illam, diligit Deus. 

** Sirach 4:16

Qui audit illam judicabit gentes :  et qui intuetur illam permanebit confidens. 

** Sirach 4:17

Si crediderit ei, hæreditabit illam,  et erunt in confirmatione creaturæ illius : 

** Sirach 4:18

quoniam in tentatione ambulat cum eo,  et in primis eligit eum. 

** Sirach 4:19

Timorem, et metum, et probationem inducet super illum :  et cruciabit illum in tribulatione doctrinæ suæ,  donec tentet eum in cogitationibus suis,  et credat animæ illius. 

** Sirach 4:20

Et firmabit illum, et iter adducet directum ad illum,  et lætificabit illum : 

** Sirach 4:21

et denudabit absconsa sua illi,  et thesaurizabit super illum scientiam et intellectum justitiæ. 

** Sirach 4:22

Si autem oberraverit, derelinquet eum,  et tradet eum in manus inimici sui. 

** Sirach 4:23

Fili, conserva tempus,  et devita a malo. 

** Sirach 4:24

Pro anima tua ne confundaris dicere verum : 

** Sirach 4:25

est enim confusio adducens peccatum,  et est confusio adducens gloriam et gratiam. 

** Sirach 4:26

Ne accipias faciem adversus faciem tuam,  nec adversus animam tuam mendacium. 

** Sirach 4:27

Ne reverearis proximum tuum in casu suo, 

** Sirach 4:28

nec retineas verbum in tempore salutis.  Non abscondas sapientiam tuam in decore suo : 

** Sirach 4:29

in lingua enim sapientia dignoscitur :  et sensus, et scientia, et doctrina in verbo sensati,  et firmamentum in operibus justitiæ. 

** Sirach 4:30

Non contradicas verbo veritatis ullo modo,  et de mendacio ineruditionis tuæ confundere. 

** Sirach 4:31

Non confundaris confiteri peccata tua,  et ne subjicias te omni homini pro peccato. 

** Sirach 4:32

Noli resistere contra faciem potentis,  nec coneris contra ictum fluvii. 

** Sirach 4:33

Pro justitia agonizare pro anima tua,  et usque ad mortem certa pro justitia :  et Deus expugnabit pro te inimicos tuos. 

** Sirach 4:34

Noli citatus esse in lingua tua,  et inutilis, et remissus in operibus tuis. 

** Sirach 4:35

Noli esse sicut leo in domo tua,  evertens domesticos tuos, et opprimens subjectos tibi. 

** Sirach 4:36

Non sit porrecta manus tua ad accipiendum,  et ad dandum collecta.  

* Sirach 5

** Sirach 5:1

Noli attendere ad possessiones iniquas,  et ne dixeris : Est mihi sufficiens vita :  nihil enim proderit in tempore vindictæ et obductionis. 

** Sirach 5:2

Ne sequaris in fortitudine tua concupiscentiam cordis tui, 

** Sirach 5:3

et ne dixeris : Quomodo potui ?  aut, Quis me subjiciet propter facta mea ?  Deus enim vindicans vindicabit. 

** Sirach 5:4

Ne dixeris : Peccavi : et quid mihi accidit triste ?  Altissimus enim est patiens redditor. 

** Sirach 5:5

De propitiatio peccato noli esse sine metu,  neque adjicias peccatum super peccatum. 

** Sirach 5:6

Et ne dicas : Miseratio Domini magna est,  multitudinis peccatorum meorum miserebitur : 

** Sirach 5:7

misericordia enim et ira ab illo cito proximant,  et in peccatores respicit ira illius. 

** Sirach 5:8

Non tardes converti ad Dominum,  et ne differas de die in diem : 

** Sirach 5:9

subito enim veniet ira illius,  et in tempore vindictæ disperdet te. 

** Sirach 5:10

Noli anxius esse in divitiis injustis :  non enim proderunt tibi in die obductionis et vindictæ. 

** Sirach 5:11

Non ventiles te in omnem ventum,  et non eas in omnem viam :  sic enim omnis peccator probatur in duplici lingua. 

** Sirach 5:12

Esto firmus in via Domini,  et in veritate sensus tui et scientia :  et prosequatur te verbum pacis et justitiæ. 

** Sirach 5:13

Esto mansuetus ad audiendum verbum, ut intelligas,  et cum sapientia proferas responsum verum. 

** Sirach 5:14

Si est tibi intellectus, responde proximo :  sin autem, sit manus tua super os tuum,  ne capiaris in verbo indisciplinato, et confundaris. 

** Sirach 5:15

Honor et gloria in sermone sensati :  lingua vero imprudentis subversio est ipsius. 

** Sirach 5:16

Non appelleris susurro,  et lingua tua ne capiaris et confundaris : 

** Sirach 5:17

super furem enim est confusio et pœnitentia,  et denotatio pessima super bilinguem :  susurratori autem odium, et inimicitia, et contumelia. 

** Sirach 5:18

Justifica pusillum  et magnum similiter.  

* Sirach 6

** Sirach 6:1

Noli fieri pro amico inimicus proximo :  improperium enim et contumeliam malus hæreditabit :  et omnis peccator invidus et bilinguis. 

** Sirach 6:2

Non te extollas in cogitatione animæ tuæ velut taurus,  ne forte elidatur virtus tua per stultitiam : 

** Sirach 6:3

et folia tua comedat, et fructus tuos perdat,  et relinquaris velut lignum aridum in eremo. 

** Sirach 6:4

Anima enim nequam disperdet qui se habet,  et in gaudium inimicis dat illum,  et deducet in sortem impiorum. 

** Sirach 6:5

Verbum dulce multiplicat amicos et mitigat inimicos,  et lingua eucharis in bono homine abundat. 

** Sirach 6:6

Multi pacifici sint tibi :  et consiliarius sit tibi unus de mille. 

** Sirach 6:7

Si possides amicum, in tentatione posside eum,  et ne facile credas ei. 

** Sirach 6:8

Est enim amicus secundum tempus suum,  et non permanebit in die tribulationis. 

** Sirach 6:9

Et est amicus qui convertitur ad inimicitiam,  et est amicus qui odium et rixam et convitia denudabit. 

** Sirach 6:10

Est autem amicus socius mensæ,  et non permanebit in die necessitatis. 

** Sirach 6:11

Amicus si permanserit fixus, erit tibi quasi coæqualis,  et in domesticis tuis fiducialiter aget. 

** Sirach 6:12

Si humiliaverit se contra te,  et a facie tua absconderit se,  unanimem habebis amicitiam bonam. 

** Sirach 6:13

Ab inimicis tuis separare,  et ab amicis tuis attende. 

** Sirach 6:14

Amicus fidelis protectio fortis :  qui autem invenit illum, invenit thesaurum. 

** Sirach 6:15

Amico fideli nulla est comparatio,  et non est digna ponderatio auri et argenti contra bonitatem fidei illius. 

** Sirach 6:16

Amicus fidelis medicamentum vitæ et immortalitatis :  et qui metuunt Dominum, invenient illum. 

** Sirach 6:17

Qui timet Deum æque habebit amicitiam bonam,  quoniam secundum illum erit amicus illius. 

** Sirach 6:18

Fili, a juventute tua excipe doctrinam,  et usque ad canos invenies sapientiam. 

** Sirach 6:19

Quasi is qui arat et seminat accede ad eam,  et sustine bonos fructus illius. 

** Sirach 6:20

In opere enim ipsius exiguum laborabis,  et cito edes de generationibus illius. 

** Sirach 6:21

Quam aspera est nimium sapientia indoctis hominibus !  et non permanebit in illa excors. 

** Sirach 6:22

Quasi lapidis virtus probatio erit in illis :  et non demorabuntur projicere illam. 

** Sirach 6:23

Sapientia enim doctrinæ secundum nomen est ejus,  et non est multis manifestata :  quibus autem cognita est,  permanet usque ad conspectum Dei. 

** Sirach 6:24

Audi, fili, et accipe consilium intellectus,  et ne abjicias consilium meum. 

** Sirach 6:25

Injice pedem tuum in compedes illius,  et in torques illius collum tuum. 

** Sirach 6:26

Subjice humerum tuum, et porta illam,  et ne acedieris vinculis ejus. 

** Sirach 6:27

In omni animo tuo accede ad illam,  et in omni virtute tua conserva vias ejus. 

** Sirach 6:28

Investiga illam, et manifestabitur tibi :  et continens factus, ne derelinquas eam : 

** Sirach 6:29

in novissimis enim invenies requiem in ea,  et convertetur tibi in oblectationem. 

** Sirach 6:30

Et erunt tibi compedes ejus in protectionem fortitudinis et bases virtutis,  et torques illius in stolam gloriæ : 

** Sirach 6:31

decor enim vitæ est in illa,  et vincula illius alligatura salutaris. 

** Sirach 6:32

Stolam gloriæ indues eam,  et coronam gratulationis superpones tibi. 

** Sirach 6:33

Fili, si attenderis mihi, disces :  et si accommodaveris animum tuum, sapiens eris. 

** Sirach 6:34

Si inclinaveris aurem tuam, excipies doctrinam :  et si dilexeris audire, sapiens eris. 

** Sirach 6:35

In multitudine presbyterorum prudentium sta,  et sapientiæ illorum ex corde conjungere,  ut omnem narrationem Dei possis audire,  et proverbia laudis non effugiant a te. 

** Sirach 6:36

Et si videris sensatum, evigila ad eum,  et gradus ostiorum illius exterat pes tuus. 

** Sirach 6:37

Cogitatum tuum habe in præceptis Dei,  et in mandatis illius maxime assiduus esto :  et ipse dabit tibi cor,  et concupiscentia sapientiæ dabitur tibi.  

* Sirach 7

** Sirach 7:1

Noli facere mala, et non te apprehendent : 

** Sirach 7:2

discede ab iniquo, et deficient mala abs te. 

** Sirach 7:3

Fili, non semines mala in sulcis injustitiæ,  et non metes ea in septuplum. 

** Sirach 7:4

Noli quærere a Domino ducatum,  neque a rege cathedram honoris. 

** Sirach 7:5

Non te justifices ante Deum,  quoniam agnitor cordis ipse est :  et penes regem noli velle videri sapiens. 

** Sirach 7:6

Noli quærere fieri judex,  nisi valeas virtute irrumpere iniquitates :  ne forte extimescas faciem potentis,  et ponas scandalum in æquitate tua. 

** Sirach 7:7

Non pecces in multitudinem civitatis,  nec te immittas in populum : 

** Sirach 7:8

neque alliges duplicia peccata,  nec enim in uno eris immunis. 

** Sirach 7:9

Noli esse pusillanimis in animo tuo : 

** Sirach 7:10

exorare et facere eleemosynam ne despicias. 

** Sirach 7:11

Ne dicas : In multitudine munerum meorum respiciet Deus,  et offerente me Deo altissimo, munera mea suscipiet. 

** Sirach 7:12

Non irrideas hominem in amaritudine animæ :  est enim qui humiliat et exaltat circumspector Deus. 

** Sirach 7:13

Noli amare mendacium adversus fratrem tuum,  neque in amicum similiter facias. 

** Sirach 7:14

Noli velle mentiri omne mendacium :  assiduitas enim illius non est bona. 

** Sirach 7:15

Noli verbosus esse in multitudine presbyterorum,  et non iteres verbum in oratione tua. 

** Sirach 7:16

Non oderis laboriosa opera,  et rusticationem creatam ab Altissimo. 

** Sirach 7:17

Non te reputes in multitudine indisciplinatorum. 

** Sirach 7:18

Memento iræ, quoniam non tardabit. 

** Sirach 7:19

Humilia valde spiritum tuum,  quoniam vindicta carnis impii ignis et vermis. 

** Sirach 7:20

Noli prævaricari in amicum pecuniam differentem,  neque fratrem carissimum auro spreveris. 

** Sirach 7:21

Noli discedere a muliere sensata et bona,  quam sortitus es in timore Domini :  gratia enim verecundiæ illius super aurum. 

** Sirach 7:22

Non lædas servum in veritate operantem,  neque mercenarium dantem animam suam. 

** Sirach 7:23

Servus sensatus sit tibi dilectus quasi anima tua :  non defraudes illum libertate,  neque inopem derelinquas illum. 

** Sirach 7:24

Pecora tibi sunt, attende illis :  et si sunt utilia, perseverent apud te. 

** Sirach 7:25

Filii tibi sunt ? erudi illos,  et curva illos a pueritia illorum. 

** Sirach 7:26

Filiæ tibi sunt ? serva corpus illarum,  et non ostendas hilarem faciem tuam ad illas. 

** Sirach 7:27

Trade filiam, et grande opus feceris :  et homini sensato da illam. 

** Sirach 7:28

Mulier si est tibi secundum animam tuam, non projicias illam :  et odibili non credas te.  In toto corde tuo 

** Sirach 7:29

honora patrem tuum,  et gemitus matris tuæ ne obliviscaris : 

** Sirach 7:30

memento quoniam nisi per illos natus non fuisses :  et retribue illis, quomodo et illi tibi. 

** Sirach 7:31

In tota anima tua time Dominum,  et sacerdotes illius sanctifica. 

** Sirach 7:32

In omni virtute tua dilige eum qui te fecit,  et ministros ejus ne derelinquas. 

** Sirach 7:33

Honora Deum ex tota anima tua,  et honorifica sacerdotes,  et propurga te cum brachiis. 

** Sirach 7:34

Da illis partem, sicut mandatum est tibi, primitiarum et purgationis,  et de negligentia tua purga te cum paucis. 

** Sirach 7:35

Datum brachiorum tuorum,  et sacrificium sanctificationis offeres Domino,  et initia sanctorum. 

** Sirach 7:36

Et pauperi porrige manum tuam,  ut perficiatur propitiatio et benedictio tua. 

** Sirach 7:37

Gratia dati in conspectu omnis viventis,  et mortuo non prohibeas gratiam. 

** Sirach 7:38

Non desis plorantibus in consolatione,  et cum lugentibus ambula. 

** Sirach 7:39

Non te pigeat visitare infirmum :  ex his enim in dilectione firmaberis. 

** Sirach 7:40

In omnibus operibus tuis memorare novissima tua,  et in æternum non peccabis.  

* Sirach 8

** Sirach 8:1

Non litiges cum homine potente,  ne forte incidas in manus illius. 

** Sirach 8:2

Non contendas cum viro locuplete,  ne forte contra te constituat litem tibi : 

** Sirach 8:3

multos enim perdidit aurum et argentum,  et usque ad cor regum extendit et convertit. 

** Sirach 8:4

Non litiges cum homine linguato,  et non strues in ignem illius ligna. 

** Sirach 8:5

Non communices homini indocto,  ne male de progenie tua loquatur. 

** Sirach 8:6

Ne despicias hominem avertentem se a peccato,  neque improperes ei :  memento quoniam omnes in correptione sumus. 

** Sirach 8:7

Ne spernas hominem in sua senectute,  etenim ex nobis senescunt. 

** Sirach 8:8

Noli de mortuo inimico tuo gaudere :  sciens quoniam omnes morimur,  et in gaudium nolumus venire. 

** Sirach 8:9

Ne despicias narrationem presbyterorum sapientium,  et in proverbiis eorum conversare : 

** Sirach 8:10

ab ipsis enim disces sapientiam et doctrinam intellectus,  et servire magnatis sine querela. 

** Sirach 8:11

Non te prætereat narratio seniorum,  ipsi enim didicerunt a patribus suis : 

** Sirach 8:12

quoniam ab ipsis disces intellectum,  et in tempore necessitatis dare responsum. 

** Sirach 8:13

Non incendas carbones peccatorum arguens eos,  et ne incendaris flamma ignis peccatorum illorum. 

** Sirach 8:14

Ne contra faciem stes contumeliosi,  ne sedeat quasi insidiator ori tuo. 

** Sirach 8:15

Noli fœnerari homini fortiori te :  quod si fœneraveris, quasi perditum habe. 

** Sirach 8:16

Non spondeas super virtutem tuam :  quod si spoponderis, quasi restituens cogita. 

** Sirach 8:17

Non judices contra judicem,  quoniam secundum quod justum est judicat. 

** Sirach 8:18

Cum audace non eas in via,  ne forte gravet mala sua in te :  ipse enim secundum voluntatem suam vadit,  et simul cum stultitia illius peries. 

** Sirach 8:19

Cum iracundo non facias rixam,  et cum audace non eas in desertum :  quoniam quasi nihil est ante illum sanguis,  et ubi non est adjutorium, elidet te. 

** Sirach 8:20

Cum fatuis consilium non habeas :  non enim poterunt diligere nisi quæ eis placent. 

** Sirach 8:21

Coram extraneo ne facias consilium :  nescis enim quid pariet. 

** Sirach 8:22

Non omni homini cor tuum manifestes,  ne forte inferat tibi gratiam falsam, et convicietur tibi.  

* Sirach 9

** Sirach 9:1

Non zeles mulierem sinus tui,  ne ostendat super te malitiam doctrinæ nequam. 

** Sirach 9:2

Non des mulieri potestatem animæ tuæ,  ne ingrediatur in virtutem tuam, et confundaris. 

** Sirach 9:3

Ne respicias mulierem multivolam,  ne forte incidas in laqueos illius. 

** Sirach 9:4

Cum saltatrice ne assiduus sis,  nec audias illam, ne forte pereas in efficacia illius. 

** Sirach 9:5

Virginem ne conspicias,  ne forte scandalizeris in decore illius. 

** Sirach 9:6

Ne des fornicariis animam tuam in ullo,  ne perdas te et hæreditatem tuam. 

** Sirach 9:7

Noli circumspicere in vicis civitatis,  nec oberraveris in plateis illius. 

** Sirach 9:8

Averte faciem tuam a muliere compta,  et ne circumspicias speciem alienam. 

** Sirach 9:9

Propter speciem mulieris multi perierunt :  et ex hoc concupiscentia quasi ignis exardescit. 

** Sirach 9:10

Omnis mulier quæ est fornicaria,  quasi stercus in via conculcabitur. 

** Sirach 9:11

Speciem mulieris alienæ multi admirati, reprobi facti sunt :  colloquium enim illius quasi ignis exardescit. 

** Sirach 9:12

Cum aliena muliere ne sedeas omnino,  nec accumbas cum ea super cubitum : 

** Sirach 9:13

et non alterceris cum illa in vino,  ne forte declinet cor tuum in illam,  et sanguine tuo labaris in perditionem. 

** Sirach 9:14

Ne derelinquas amicum antiquum :  novus enim non erit similis illi. 

** Sirach 9:15

Vinum novum amicus novus :  veterascet, et cum suavitate bibes illud. 

** Sirach 9:16

Non zeles gloriam et opes peccatoris :  non enim scis quæ futura sit illius subversio. 

** Sirach 9:17

Non placeat tibi injuria injustorum,  sciens quoniam usque ad inferos non placebit impius. 

** Sirach 9:18

Longe abesto ab homine potestatem habente occidendi,  et non suspicaberis timorem mortis. 

** Sirach 9:19

Et si accesseris ad illum, noli aliquid committere,  ne forte auferat vitam tuam. 

** Sirach 9:20

Communionem mortis scito,  quoniam in medio laqueorum ingredieris,  et super dolentium arma ambulabis. 

** Sirach 9:21

Secundum virtutem tuam cave te a proximo tuo,  et cum sapientibus et prudentibus tracta. 

** Sirach 9:22

Viri justi sint tibi convivæ,  et in timore Dei sit tibi gloriatio : 

** Sirach 9:23

et in sensu sit tibi cogitatus Dei,  et omnis enarratio tua in præceptis Altissimi. 

** Sirach 9:24

In manu artificum opera laudabuntur,  et princeps populi in sapientia sermonis sui,  in sensu vero seniorum verbum. 

** Sirach 9:25

Terribilis est in civitate sua homo linguosus :  et temerarius in verbo suo odibilis erit.  

* Sirach 10

** Sirach 10:1

Judex sapiens judicabit populum suum,  et principatus sensati stabilis erit. 

** Sirach 10:2

Secundum judicem populi, sic et ministri ejus :  et qualis rector est civitatis, tales et inhabitantes in ea. 

** Sirach 10:3

Rex insipiens perdet populum suum :  et civitates inhabitabuntur per sensum potentium. 

** Sirach 10:4

In manu Dei potestas terræ :  et utilem rectorem suscitabit in tempus super illam. 

** Sirach 10:5

In manu Dei prosperitas hominis,  et super faciem scribæ imponet honorem suum. 

** Sirach 10:6

Omnis injuriæ proximi ne memineris,  et nihil agas in operibus injuriæ. 

** Sirach 10:7

Odibilis coram Deo est et hominibus superbia,  et execrabilis omnis iniquitas gentium. 

** Sirach 10:8

Regnum a gente in gentem transfertur propter injustitias,  et injurias, et contumelias, et diversos dolos. 

** Sirach 10:9

Avaro autem nihil est scelestius.  Quid superbit terra et cinis ? 

** Sirach 10:10

Nihil est iniquius quam amare pecuniam :  hic enim et animam suam venalem habet,  quoniam in vita sua projecit intima sua. 

** Sirach 10:11

Omnis potentatus brevis vita ;  languor prolixior gravat medicum. 

** Sirach 10:12

Brevem languorem præcidit medicus :  sic et rex hodie est, et cras morietur. 

** Sirach 10:13

Cum enim morietur homo,  hæreditabit serpentes, et bestias, et vermes. 

** Sirach 10:14

Initium superbiæ hominis apostatare a Deo : 

** Sirach 10:15

quoniam ab eo qui fecit illum recessit cor ejus,  quoniam initium omnis peccati est superbia.  Qui tenuerit illam adimplebitur maledictis,  et subvertet eum in finem. 

** Sirach 10:16

Propterea exhonoravit Dominus conventus malorum,  et destruxit eos usque in finem. 

** Sirach 10:17

Sedes ducum superborum destruxit Deus,  et sedere fecit mites pro eis. 

** Sirach 10:18

Radices gentium superbarum arefecit Deus,  et plantavit humiles ex ipsis gentibus. 

** Sirach 10:19

Terras gentium evertit Dominus,  et perdidit eas usque ad fundamentum. 

** Sirach 10:20

Arefecit ex ipsis, et disperdidit eos,  et cessare fecit memoriam eorum a terra. 

** Sirach 10:21

Memoria superborum perdidit Deus,  et reliquit memoriam humilium sensu. 

** Sirach 10:22

Non est creata hominibus superbia,  neque iracundia nationi mulierum. 

** Sirach 10:23

Semen hominum honorabitur hoc, quod timet Deum :  semen autem hoc exhonorabitur, quod præterit mandata Domini. 

** Sirach 10:24

In medio fratrum rector illorum in honore :  et qui timent Dominum erunt in oculis illius. 

** Sirach 10:25

Gloria divitum, honoratorum, et pauperum,  timor Dei est. 

** Sirach 10:26

Noli despicere hominem justum pauperem,  et noli magnificare virum peccatorem divitem. 

** Sirach 10:27

Magnus, et judex, et potens est in honore :  et non est major illo qui timet Deum. 

** Sirach 10:28

Servo sensato liberi servient :  et vir prudens et disciplinatus non murmurabit correptus,  et inscius non honorabitur. 

** Sirach 10:29

Noli extollere te in faciendo opere tuo,  et noli cunctari in tempore angustiæ. 

** Sirach 10:30

Melior est qui operatur et abundat in omnibus,  quam qui gloriatur et eget pane. 

** Sirach 10:31

Fili, in mansuetudine serva animam tuam,  et da illi honorem secundum meritum suum. 

** Sirach 10:32

Peccantem in animam suam quis justificabit ?  et quis honorificabit exhonorantem animam suam ? 

** Sirach 10:33

Pauper gloriatur per disciplinam et timorem suum :  et est homo qui honorificatur propter substantiam suam. 

** Sirach 10:34

Qui autem gloriatur in paupertate, quanto magis in substantia !  et qui gloriatur in substantia, paupertatem vereatur.  

* Sirach 11

** Sirach 11:1

Sapientia humiliati exaltabit caput illius,  et in medio magnatorum consedere illum faciet. 

** Sirach 11:2

Non laudes virum in specie sua,  neque spernas hominem in visu suo. 

** Sirach 11:3

Brevis in volatilibus est apis,  et initium dulcoris habet fructus illius. 

** Sirach 11:4

In vestitu ne glorieris umquam,  nec in die honoris tui extollaris :  quoniam mirabilia opera Altissimi solius,  et gloriosa, et absconsa, et invisa opera illius. 

** Sirach 11:5

Multi tyranni sederunt in throno :  et insuspicabilis portavit diadema. 

** Sirach 11:6

Multi potentes oppressi sunt valide,  et gloriosi traditi sunt in manus alterorum. 

** Sirach 11:7

Priusquam interroges, ne vituperes quemquam :  et cum interrogaveris, corripe juste. 

** Sirach 11:8

Priusquam audias, ne respondeas verbum :  et in medio sermonum ne adjicias loqui. 

** Sirach 11:9

De ea re quæ te non molestat, ne certeris :  et in judicio peccantium ne consistas. 

** Sirach 11:10

Fili, ne in multis sint actus tui :  et si dives fueris, non eris immunis a delicto.  Si enim secutus fueris, non apprehendes :  et non effugies, si præcucurreris. 

** Sirach 11:11

Est homo laborans et festinans, et dolens :  impius, et tanto magis non abundabit. 

** Sirach 11:12

Est homo marcidus egens recuperatione,  plus deficiens virtute, et abundans paupertate : 

** Sirach 11:13

et oculus Dei respexit illum in bono,  et erexit eum ab humilitate ipsius, et exaltavit caput ejus :  et mirati sunt in illo multi, et honoraverunt Deum. 

** Sirach 11:14

Bona et mala, vita et mors,  paupertas et honestas, a Deo sunt : 

** Sirach 11:15

sapientia, et disciplina, et scientia legis, apud Deum :  dilectio, et viæ bonorum, apud ipsum. 

** Sirach 11:16

Error et tenebræ peccatoribus concreata sunt :  qui autem exsultant in malis consenescunt in malo. 

** Sirach 11:17

Datio Dei permanet justis,  et profectus illius successus habebit in æternum. 

** Sirach 11:18

Est qui locupletatur parce agendo,  et hæc est pars mercedis illius. 

** Sirach 11:19

In eo quod dicit : Inveni requiem mihi,  et nunc manducabo de bonis meis solus : 

** Sirach 11:20

et nescit quod tempus præteriet, et mors appropinquet,  et relinquat omnia aliis, et morietur. 

** Sirach 11:21

Sta in testamento tuo, et in illo colloquere,  et in opere mandatorum tuorum veterasce. 

** Sirach 11:22

Ne manseris in operibus peccatorum :  confide autem in Deo, et mane in loco tuo. 

** Sirach 11:23

Facile est enim in oculis Dei  subito honestare pauperem. 

** Sirach 11:24

Benedictio Dei in mercedem justi festinat,  et in hora veloci processus illius fructificat. 

** Sirach 11:25

Ne dicas : Quid est mihi opus ?  et quæ erunt mihi ex hoc bona ? 

** Sirach 11:26

Ne dicas : Sufficiens mihi sum :  et quid ex hoc pessimabor ? 

** Sirach 11:27

In die bonorum ne immemor sis malorum,  et in die malorum ne immemor sis bonorum : 

** Sirach 11:28

quoniam facile est coram Deo in die obitus  retribuere unicuique secundum vias suas. 

** Sirach 11:29

Malitia horæ oblivionem facit luxuriæ magnæ,  et in fine hominis denudatio operum illius. 

** Sirach 11:30

Ante mortem ne laudes hominem quemquam :  quoniam in filiis suis agnoscitur vir. 

** Sirach 11:31

Non omnem hominem inducas in domum tuam :  multæ enim sunt insidiæ dolosi. 

** Sirach 11:32

Sicut enim eructant præcordia fœtentium,  et sicut perdix inducitur in caveam, et ut caprea in laqueum :  sic et cor superborum,  et sicut prospector videns casum proximi sui. 

** Sirach 11:33

Bona enim in mala convertens insidiatur,  et in electis imponet maculam. 

** Sirach 11:34

A scintilla una augetur ignis,  et ab uno doloso augetur sanguis :  homo vero peccator sanguini insidiatur. 

** Sirach 11:35

Attende tibi a pestifero, fabricat enim mala,  ne inducat super te subsannationem in perpetuum. 

** Sirach 11:36

Admitte ad te alienigenam :  et subvertet te in turbine,  et abalienabit te a tuis propriis.  

* Sirach 12

** Sirach 12:1

Si benefeceris, scito cui feceris,  et erit gratia in bonis tuis multa. 

** Sirach 12:2

Benefac justo, et invenies retributionem magnam :  et si non ab ipso, certe a Domino. 

** Sirach 12:3

Non est enim ei bene qui assiduus est in malis,  et eleemosynas non danti :  quoniam et Altissimus odio habet peccatores,  et misertus est pœnitentibus. 

** Sirach 12:4

Da misericordi, et ne suscipias peccatorem :  et impiis et peccatoribus reddet vindictam,  custodiens eos in diem vindictæ. 

** Sirach 12:5

Da bono, et non receperis peccatorem. 

** Sirach 12:6

Benefac humili, et non dederis impio :  prohibe panes illi dari, ne in ipsis potentior te sit : 

** Sirach 12:7

nam duplicia mala invenies in omnibus bonis quæcumque feceris illi,  quoniam et Altissimus odio habet peccatores,  et impiis reddet vindictam. 

** Sirach 12:8

Non agnoscetur in bonis amicus,  et non abscondetur in malis inimicus. 

** Sirach 12:9

In bonis viri, inimici illius in tristitia :  et in malitia illius, amicus agnitus est. 

** Sirach 12:10

Non credas inimico tuo in æternum :  sicut enim æramentum æruginat nequitia illius : 

** Sirach 12:11

et si humiliatus vadat curvus,  adjice animum tuum, et custodi te ab illo. 

** Sirach 12:12

Non statuas illum penes te,  nec sedeat ad dexteram tuam,  ne forte conversus in locum tuum, inquirat cathedram tuam,  et in novissimo agnosces verba mea,  et in sermonibus meis stimuleris. 

** Sirach 12:13

Quis miserebitur incantatori a serpente percusso,  et omnibus qui appropiant bestiis ?  et sic qui comitatur cum viro iniquo,  et obvolutus est in peccatis ejus. 

** Sirach 12:14

Una hora tecum permanebit :  si autem declinaveris, non supportabit. 

** Sirach 12:15

In labiis suis indulcat inimicus,  et in corde suo insidiatur ut subvertat te in foveam. 

** Sirach 12:16

In oculis suis lacrimatur inimicus,  et si invenerit tempus, non satiabitur sanguine. 

** Sirach 12:17

Et si incurrerint tibi mala,  invenies eum illic priorem. 

** Sirach 12:18

In oculis suis lacrimatur inimicus,  et quasi adjuvans suffodiet plantas tuas. 

** Sirach 12:19

Caput suum movebit, et plaudet manu,  et multa susurrans commutabit vultum suum.  

* Sirach 13

** Sirach 13:1

Qui tetigerit picem inquinabitur ab ea :  et qui communicaverit superbo induet superbiam. 

** Sirach 13:2

Pondus super se tollat qui honestiori se communicat,  et ditiori te ne socius fueris. 

** Sirach 13:3

Quid communicabit cacabus ad ollam ?  quando enim se colliserint, confringetur. 

** Sirach 13:4

Dives injuste egit, et fremet :  pauper autem læsus tacebit. 

** Sirach 13:5

Si largitus fueris, assumet te :  et si non habueris, derelinquet te. 

** Sirach 13:6

Si habes, convivet tecum, et evacuabit te :  et ipse non dolebit super te. 

** Sirach 13:7

Si necessarius illi fueris, supplantabit te,  et subridens spem dabit, narrans tibi bona,  et dicet : Quid opus est tibi ? 

** Sirach 13:8

Et confundet te in cibis suis,  donec te exinaniat bis et ter :  et in novissimo deridebit te,  et postea videns derelinquet te,  et caput suum movebit ad te. 

** Sirach 13:9

Humiliare Deo, et exspecta manus ejus. 

** Sirach 13:10

Attende ne seductus in stultitiam humilieris. 

** Sirach 13:11

Noli esse humilis in sapientia tua,  ne humiliatus in stultitiam seducaris. 

** Sirach 13:12

Advocatus a potentiore, discede :  ex hoc enim magis te advocabit. 

** Sirach 13:13

Ne improbus sis, ne impingaris :  et ne longe sis ab eo, ne eas in oblivionem. 

** Sirach 13:14

Ne retineas ex æquo loqui cum illo,  nec credas multis verbis illius :  ex multa enim loquela tentabit te,  et subridens interrogabit te de absconditis tuis. 

** Sirach 13:15

Immitis animus illius conservabit verba tua :  et non parcet de malitia, et de vinculis. 

** Sirach 13:16

Cave tibi, et attende diligenter auditui tuo,  quoniam cum subversione tua ambulas : 

** Sirach 13:17

audiens vero illa,  quasi in somnis vide, et vigilabis. 

** Sirach 13:18

Omni vita tua dilige Deum,  et invoca illum in salute tua. 

** Sirach 13:19

Omne animal diligit simile sibi,  sic et omnis homo proximum sibi. 

** Sirach 13:20

Omnis caro ad similem sibi conjungetur,  et omnis homo simili sui sociabitur. 

** Sirach 13:21

Si communicabit lupus agno aliquando,  sic peccator justo. 

** Sirach 13:22

Quæ communicatio sancto homini ad canem ?  aut quæ pars diviti ad pauperem ? 

** Sirach 13:23

Venatio leonis onager in eremo :  sic et pascua divitum sunt pauperes. 

** Sirach 13:24

Et sicut abominatio est superbo humilitas,  sic et execratio divitis pauper. 

** Sirach 13:25

Dives commotus confirmatur ab amicis suis :  humilis autem cum ceciderit, expelletur et a notis. 

** Sirach 13:26

Diviti decepto multi recuperatores :  locutus est superbia, et justificaverunt illum. 

** Sirach 13:27

Humilis deceptus est, insuper et arguitur :  locutus est sensate, et non est datus ei locus. 

** Sirach 13:28

Dives locutus est, et omnes tacuerunt,  et verbum illius usque ad nubes perducent. 

** Sirach 13:29

Pauper locutus est, et dicunt : Quis est hic ?  et si offenderit, subvertent illum. 

** Sirach 13:30

Bona est substantia cui non est peccatum in conscientia :  et nequissima paupertas in ore impii. 

** Sirach 13:31

Cor hominis immutat faciem illius,  sive in bona, sive in mala. 

** Sirach 13:32

Vestigium cordis boni et faciem bonam  difficile invenies, et cum labore.  

* Sirach 14

** Sirach 14:1

Beatus vir qui non est lapsus verbo ex ore suo,  et non est stimulatus in tristitia delicti. 

** Sirach 14:2

Felix qui non habuit animi sui tristitiam,  et non excidit a spe sua. 

** Sirach 14:3

Viro cupido et tenaci sine ratione est substantia :  et homini livido ad quid aurum ? 

** Sirach 14:4

Qui acervat ex animo suo injuste, aliis congregat,  et in bonis illius alius luxuriabitur. 

** Sirach 14:5

Qui sibi nequam est, cui alii bonus erit ?  et non jucundabitur in bonis suis. 

** Sirach 14:6

Qui sibi invidet, nihil est illo nequius :  et hæc redditio est malitiæ illius. 

** Sirach 14:7

Et si bene fecerit, ignoranter et non volens facit :  et in novissimo manifestat malitiam suam. 

** Sirach 14:8

Nequam est oculus lividi :  et avertens faciem suam, et despiciens animam suam. 

** Sirach 14:9

Insatiabilis oculus cupidi in parte iniquitatis :  non satiabitur donec consumat arefaciens animam suam. 

** Sirach 14:10

Oculus malus ad mala, et non saturabitur pane,  sed indigens et in tristitia erit super mensam suam. 

** Sirach 14:11

Fili, si habes, benefac tecum,  et Deo dignas oblationes offer. 

** Sirach 14:12

Memor esto quoniam mors non tardat,  et testamentum inferorum, quia demonstratum est tibi :  testamentum enim hujus mundi morte morietur. 

** Sirach 14:13

Ante mortem benefac amico tuo,  et secundum vires tuas exporrigens da pauperi. 

** Sirach 14:14

Non defrauderis a die bono,  et particula boni doni non te prætereat. 

** Sirach 14:15

Nonne aliis relinques dolores et labores tuos  in divisione sortis ? 

** Sirach 14:16

Da et accipe,  et justifica animam tuam. 

** Sirach 14:17

Ante obitum tuum operare justitiam,  quoniam non est apud inferos invenire cibum. 

** Sirach 14:18

Omnis caro sicut fœnum veterascet,  et sicut folium fructificans in arbore viridi. 

** Sirach 14:19

Alia generantur, et alia dejiciuntur :  sic generatio carnis et sanguinis, alia finitur, et alia nascitur. 

** Sirach 14:20

Omne opus corruptibile in fine deficiet,  et qui illud operatur ibit cum illo. 

** Sirach 14:21

Et omne opus electum justificabitur,  et qui operatur illud honorabitur in illo. 

** Sirach 14:22

Beatus vir qui in sapientia morabitur,  et qui in justitia sua meditabitur,  et in sensu cogitabit circumspectionem Dei : 

** Sirach 14:23

qui excogitat vias illius in corde suo,  et in absconditis suis intelligens,  vadens post illam quasi investigator,  et in viis illius consistens : 

** Sirach 14:24

qui respicit per fenestras illius,  et in januis illius audiens : 

** Sirach 14:25

qui requiescit juxta domum illius,  et in parietibus illius figens palum,  statuet casulam suam ad manus illius,  et requiescent in casula illius bona per ævum. 

** Sirach 14:26

Statuet filios suos sub tegmine illius,  et sub ramis ejus morabitur. 

** Sirach 14:27

Protegetur sub tegmine illius a fervore,  et in gloria ejus requiescet.  

* Sirach 15

** Sirach 15:1

Qui timet Deum faciet bona,  et qui continens est justitiæ apprehendet illam : 

** Sirach 15:2

et obviabit illi quasi mater honorificata,  et quasi mulier a virginitate suscipiet illum. 

** Sirach 15:3

Cibabit illum pane vitæ et intellectus,  et aqua sapientiæ salutaris potabit illum :  et firmabitur in illo, et non flectetur : 

** Sirach 15:4

et continebit illum, et non confundetur :  et exaltabit illum apud proximos suos, 

** Sirach 15:5

et in medio ecclesiæ aperiet os ejus,  et adimplebit illum spiritu sapientiæ et intellectus,  et stola gloriæ vestiet illum. 

** Sirach 15:6

Jucunditatem et exsultationem thesaurizabit super illum,  et nomine æterno hæreditabit illum. 

** Sirach 15:7

Homines stulti non apprehendent illam,  et homines sensati obviabunt illi.  Homines stulti non videbunt eam :  longe enim abest a superbia et dolo. 

** Sirach 15:8

Viri mendaces non erunt illius memores :  et viri veraces invenientur in illa,  et successum habebunt usque ad inspectionem Dei. 

** Sirach 15:9

Non est speciosa laus in ore peccatoris, 

** Sirach 15:10

quoniam a Deo profecta est sapientia.  Sapientiæ enim Dei astabit laus,  et in ore fideli abundabit,  et Dominator dabit eam illi. 

** Sirach 15:11

Non dixeris : Per Deum abest :  quæ enim odit ne feceris. 

** Sirach 15:12

Non dicas : Ille me implanavit :  non enim necessarii sunt ei homines impii. 

** Sirach 15:13

Omne execramentum erroris odit Dominus,  et non erit amabile timentibus eum. 

** Sirach 15:14

Deus ab initio constituit hominem,  et reliquit illum in manu consilii sui : 

** Sirach 15:15

adjecit mandata et præcepta sua. 

** Sirach 15:16

Si volueris mandata servare, conservabunt te,  et in perpetuum fidem placitam facere. 

** Sirach 15:17

Apposuit tibi aquam et ignem,  ad quod volueris porrige manum tuam. 

** Sirach 15:18

Ante hominem vita et mors, bonum et malum :  quod placuerit ei dabitur illi : 

** Sirach 15:19

quoniam multa sapientia Dei, et fortis in potentia,  videns omnes sine intermissione. 

** Sirach 15:20

Oculi Domini ad timentes eum,  et ipse agnoscit omnem operam hominis. 

** Sirach 15:21

Nemini mandavit impie agere,  et nemini dedit spatium peccandi : 

** Sirach 15:22

non enim concupiscit multitudinem  filiorum infidelium et inutilium.  

* Sirach 16

** Sirach 16:1

Ne jucunderis in filiis impiis, si multiplicentur :  nec oblecteris super ipsos, si non est timor Dei in illis. 

** Sirach 16:2

Non credas vitæ illorum,  et ne respexeris in labores eorum. 

** Sirach 16:3

Melior est enim unus timens Deum,  quam mille filii impii : 

** Sirach 16:4

et utile est mori sine filiis,  quam relinquere filios impios. 

** Sirach 16:5

Ab uno sensato inhabitabitur patria :  tribus impiorum deseretur. 

** Sirach 16:6

Multa talia vidit oculis meus,  et fortiora horum audivit auris mea. 

** Sirach 16:7

In synagoga peccantium exardebit ignis,  et in gente incredibili exardescet ira. 

** Sirach 16:8

Non exoraverunt pro peccatis suis antiqui gigantes,  qui destructi sunt confidentes suæ virtuti. 

** Sirach 16:9

Et non pepercit peregrinationi Lot,  et execratus est eos præ superbia verbi illorum. 

** Sirach 16:10

Non misertus est illis, gentem totam perdens,  et extollentem se in peccatis suis. 

** Sirach 16:11

Et sicut sexcenta millia peditum,  qui congregati sunt in duritia cordis sui :  et si unus fuisset cervicatus,  mirum si fuisset immunis. 

** Sirach 16:12

Misericordia enim et ira est cum illo :  potens exoratio, et effundens iram. 

** Sirach 16:13

Secundum misericordiam suam,  sic correptio illius homines secundum opera sua judicat. 

** Sirach 16:14

Non effugiet in rapina peccator,  et non retardabit sufferentia misericordiam facientis. 

** Sirach 16:15

Omnis misericordia faciet locum unicuique,  secundum meritum operum suorum,  et secundum intellectum peregrinationis ipsius. 

** Sirach 16:16

Non dicas : A Deo abscondar :  et ex summo, quis mei memorabitur ? 

** Sirach 16:17

in populo magno non agnoscar :  quæ est enim anima mea in tam immensa creatura ? 

** Sirach 16:18

Ecce cælum et cæli cælorum,  abyssus, et universa terra, et quæ in eis sunt,  in conspectu illius commovebuntur. 

** Sirach 16:19

Montes simul, et colles, et fundamenta terræ,  cum conspexerit illa Deus, tremore concutientur. 

** Sirach 16:20

Et in omnibus his insensatum est cor,  et omne cor intelligitur ab illo. 

** Sirach 16:21

Et vias illius quis intelligit,  et procellam quam nec oculus videbit hominis ? 

** Sirach 16:22

Nam plurima illius opera sunt in absconsis :  sed opera justitiæ ejus quis enuntiabit, aut quis sustinebit ?  longe enim est testamentum a quibusdam,  et interrogatio omnium in consummatione est. 

** Sirach 16:23

Qui minoratur corde cogitat inania,  et vir imprudens et errans cogitat stulta. 

** Sirach 16:24

Audi me, fili, et disce disciplinam sensus,  et in verbis meis attende in corde tuo : 

** Sirach 16:25

et dicam in æquitate disciplinam,  et scrutabor enarrare sapientiam :  et in verbis meis attende in corde tuo,  et dico in æquitate spiritus virtutes  quas posuit Deus in opera sua ab initio,  et in veritate enuntio scientiam ejus. 

** Sirach 16:26

In judicio Dei opera ejus ab initio,  et ab institutione ipsorum distinxit partes illorum,  et initia eorum in gentibus suis. 

** Sirach 16:27

Ornavit in æternum opera illorum :  nec esurierunt, nec laboraverunt,  et non destiterunt ab operibus suis. 

** Sirach 16:28

Unusquisque proximum sibi non angustiabit in æternum : 

** Sirach 16:29

non sis incredibilis verbo illius. 

** Sirach 16:30

Post hæc Deus in terram respexit,  et implevit illam bonis suis : 

** Sirach 16:31

anima omnis vitalis denuntiavit ante faciem ipsius,  et in ipsam iterum reversio illorum.  

* Sirach 17

** Sirach 17:1

Deus creavit de terra hominem,  et secundum imaginem suam fecit illum : 

** Sirach 17:2

et iterum convertit illum in ipsam,  et secundum se vestivit illum virtute. 

** Sirach 17:3

Numerum dierum et tempus dedit illi,  et dedit illi potestatem eorum quæ sunt super terram. 

** Sirach 17:4

Posuit timorem illius super omnem carnem,  et dominatus est bestiarum et volatilium. 

** Sirach 17:5

Creavit ex ipso adjutorium simile sibi :  consilium, et linguam, et oculos, et aures,  et cor dedit illis excogitandi,  et disciplina intellectus replevit illos. 

** Sirach 17:6

Creavit illis scientiam spiritus,  sensu implevit cor illorum,  et mala et bona ostendit illis. 

** Sirach 17:7

Posuit oculum suum super corda illorum,  ostendere illis magnalia operum suorum : 

** Sirach 17:8

ut nomen sanctificationis collaudent,  et gloriari in mirabilibus illius ;  ut magnalia enarrent operum ejus. 

** Sirach 17:9

Addidit illis disciplinam,  et legem vitæ hæreditavit illos. 

** Sirach 17:10

Testamentum æternum constituit cum illis,  et justitiam et judicia sua ostendit illis. 

** Sirach 17:11

Et magnalia honoris ejus vidit oculus illorum,  et honorem vocis audierunt aures illorum.  Et dixit illis : Attendite ab omni iniquo. 

** Sirach 17:12

Et mandavit illis unicuique de proximo suo. 

** Sirach 17:13

Viæ illorum coram ipso sunt semper :  non sunt absconsæ ab oculis ipsius. 

** Sirach 17:14

In unamquamque gentem præposuit rectorem : 

** Sirach 17:15

et pars Dei Israël facta est manifesta. 

** Sirach 17:16

Et omnia opera illorum velut sol in conspectu Dei :  et oculi ejus sine intermissione inspicientes in viis eorum. 

** Sirach 17:17

Non sunt absconsa testamenta per iniquitatem illorum,  et omnes iniquitates eorum in conspectu Dei. 

** Sirach 17:18

Eleemosyna viri quasi signaculum cum ipso,  et gratiam hominis quasi pupillam conservabit. 

** Sirach 17:19

Et postea resurget,  et retribuet illis retributionem, unicuique in caput ipsorum,  et convertet in interiores partes terræ. 

** Sirach 17:20

Pœnitentibus autem dedit viam justitiæ,  et confirmavit deficientes sustinere,  et destinavit illis sortem veritatis. 

** Sirach 17:21

Convertere ad Dominum, et relinque peccata tua : 

** Sirach 17:22

precare ante faciem Domini, et minue offendicula. 

** Sirach 17:23

Revertere ad Dominum, et avertere ab injustitia tua,  et nimis odito execrationem : 

** Sirach 17:24

et cognosce justitias et judicia Dei,  et sta in sorte propositionis, et orationis altissimi Dei. 

** Sirach 17:25

In partes vade sæculi sancti,  cum vivis et dantibus confessionem Deo. 

** Sirach 17:26

Non demoreris in errore impiorum :  ante mortem confitere :  a mortuo, quasi nihil, perit confessio. 

** Sirach 17:27

Confiteberis vivens,  vivus et sanus confiteberis :  et laudabis Deum,  et gloriaberis in miserationibus illius. 

** Sirach 17:28

Quam magna misericordia Domini,  et propitiatio illius convertentibus ad se ! 

** Sirach 17:29

Nec enim omnia possunt esse in hominibus,  quoniam non est immortalis filius hominis,  et in vanitate malitiæ placuerunt. 

** Sirach 17:30

Quid lucidius sole ?  et hic deficiet ;  aut quid nequius quam quod excogitavit caro et sanguis ?  et hoc arguetur. 

** Sirach 17:31

Virtutem altitudinis cæli ipse conspicit :  et omnes homines terra et cinis.  

* Sirach 18

** Sirach 18:1

Qui vivet in æternum creavit omnia simul.  Deus solus justificabitur,  et manet invictus rex in æternum. 

** Sirach 18:2

Quis sufficit enarrare opera illius ? 

** Sirach 18:3

quis enim investigabit magnalia ejus ? 

** Sirach 18:4

virtutem autem magnitudinis ejus quis enuntiabit ?  aut quis adjiciet enarrare misericordiam ejus ? 

** Sirach 18:5

Non est minuere neque adjicere,  nec est invenire magnalia Dei. 

** Sirach 18:6

Cum consummaverit homo, tunc incipiet :  et cum quieverit, aporiabitur. 

** Sirach 18:7

Quid est homo ? et quæ est gratia illius ?  et quid bonum aut quid nequam illius ? 

** Sirach 18:8

Numerus dierum hominum, ut multum centum anni,  quasi gutta aquæ maris deputati sunt :  et sicut calculus arenæ, sic exigui anni in die ævi. 

** Sirach 18:9

Propter hoc patiens est Deus in illis,  et effundit super eos misericordiam suam. 

** Sirach 18:10

Vidit præsumptionem cordis eorum, quoniam mala est :  et cognovit subversionem illorum, quoniam nequam est. 

** Sirach 18:11

Ideo adimplevit propitiationem suam in illis,  et ostendit eis viam æquitatis. 

** Sirach 18:12

Miseratio hominis circa proximum suum :  misericordia autem Dei super omnem carnem. 

** Sirach 18:13

Qui misericordiam habet, docet et erudit  quasi pastor gregem suum. 

** Sirach 18:14

Miseretur excipientis doctrinam miserationis,  et qui festinat in judiciis ejus. 

** Sirach 18:15

Fili, in bonis non des querelam,  et in omni dato non des tristitiam verbi mali. 

** Sirach 18:16

Nonne ardorem refrigerabit ros ?  sic et verbum melius quam datum. 

** Sirach 18:17

Nonne ecce verbum super datum bonum ?  sed utraque cum homine justificato. 

** Sirach 18:18

Stultus acriter improperabit :  et datus indisciplinati tabescere facit oculos. 

** Sirach 18:19

Ante judicium para justitiam tibi,  et antequam loquaris, disce. 

** Sirach 18:20

Ante languorem adhibe medicinam :  et ante judicium interroga teipsum,  et in conspectu Dei invenies propitiationem. 

** Sirach 18:21

Ante languorem humilia te,  et in tempore infirmitatis ostende conversationem tuam. 

** Sirach 18:22

Non impediaris orare semper,  et ne verearis usque ad mortem justificari,  quoniam merces Dei manet in æternum. 

** Sirach 18:23

Ante orationem præpara animam tuam,  et noli esse quasi homo qui tentat Deum. 

** Sirach 18:24

Memento iræ in die consummationis,  et tempus retributionis in conversatione faciei. 

** Sirach 18:25

Memento paupertatis in tempore abundantiæ,  et necessitatum paupertatis in die divitiarum. 

** Sirach 18:26

A mane usque ad vesperam immutabitur tempus,  et hæc omnia citata in oculis Dei. 

** Sirach 18:27

Homo sapiens in omnibus metuet,  et in diebus delictorum attendet ab inertia. 

** Sirach 18:28

Omnis astutus agnoscit sapientiam,  et invenienti eam dabit confessionem. 

** Sirach 18:29

Sensati in verbis et ipsi sapienter egerunt,  et intellexerunt veritatem et justitiam,  et impluerunt proverbia et judicia. 

** Sirach 18:30

Post concupiscentias tuas non eas,  et a voluntate tua avertere. 

** Sirach 18:31

Si præstes animæ tuæ concupiscentias ejus,  faciat te in gaudium inimicis tuis. 

** Sirach 18:32

Ne oblecteris in turbis nec in modicis :  assidua enim est commissio illorum. 

** Sirach 18:33

Ne fueris mediocris in contentione ex fœnore,  et est tibi nihil in sacculo :  eris enim invidus vitæ tuæ.  

* Sirach 19

** Sirach 19:1

Operarius ebriosus non locupletabitur :  et qui spernit modica paulatim decidet. 

** Sirach 19:2

Vinum et mulieres apostatare faciunt sapientes,  et arguent sensatos. 

** Sirach 19:3

Et qui se jungit fornicariis erit nequam :  putredo et vermes hæreditabunt illum :  et extolletur in exemplum majus,  et tolletur de numero anima ejus. 

** Sirach 19:4

Qui credit cito levis corde est, et minorabitur :  et qui delinquit in animam suam, insuper habebitur. 

** Sirach 19:5

Qui gaudet iniquitate, denotabitur :  et qui odit correptionem, minuetur vita :  et qui odit loquacitatem, extinguit malitiam. 

** Sirach 19:6

Qui peccat in animam suam, pœnitebit :  et qui jucundatur in malitia, denotabitur. 

** Sirach 19:7

Ne iteres verbum nequam et durum,  et non minoraberis. 

** Sirach 19:8

Amico et inimico noli narrare sensum tuum :  et si est tibi delictum, noli denudare : 

** Sirach 19:9

audiet enim te, et custodiet te,  et quasi defendens peccatum, odiet te,  et sic aderit tibi semper. 

** Sirach 19:10

Audisti verbum adversus proximum tuum ?  commoriatur in te, fidens quoniam non te dirumpet. 

** Sirach 19:11

A facie verbi parturit fatuus,  tamquam gemitus partus infantis. 

** Sirach 19:12

Sagitta infixa femori carnis,  sic verbum in corde stulti. 

** Sirach 19:13

Corripe amicum,  ne forte non intellexerit, et dicat : Non feci :  aut, si fecerit, ne iterum addat facere. 

** Sirach 19:14

Corripe proximum, ne forte non dixerit :  et si dixerit, ne forte iteret. 

** Sirach 19:15

Corripe amicum, sæpe enim fit commissio : 

** Sirach 19:16

et non omni verbo credas.  Est qui labitur lingua, sed non ex animo : 

** Sirach 19:17

quis est enim qui non deliquerit in lingua sua ?      Corripe proximum antequam commineris, 

** Sirach 19:18

et da locum timori Altissimi :  quia omnis sapientia timor Dei, et in illa timere Deum,  et in omni sapientia dispositio legis. 

** Sirach 19:19

Et non est sapientia nequitiæ disciplina,  et non est cogitatus peccatorum prudentia. 

** Sirach 19:20

Est nequitia, et in ipsa execratio,  et est insipiens qui minuitur sapientia. 

** Sirach 19:21

Melior est homo qui minuitur sapientia,  et deficiens sensu, in timore,  quam qui abundat sensu,  et transgreditur legem Altissimi. 

** Sirach 19:22

Est solertia certa, et ipsa iniqua : 

** Sirach 19:23

et est qui emittit verbum certum enarrans veritatem.  Est qui nequiter humiliat se,  et interiora ejus plena sunt dolo : 

** Sirach 19:24

et est qui se nimium submittit a multa humilitate :  et est qui inclinat faciem suam,  et fingit se non videre quod ignoratum est : 

** Sirach 19:25

et si ab imbecillitate virium vetetur peccare,  si invenerit tempus malefaciendi, malefaciet. 

** Sirach 19:26

Ex visu cognoscitur vir,  et ab occursu faciei cognoscitur sensatus. 

** Sirach 19:27

Amictus corporis, et risus dentium,  et ingressus hominis, enuntiant de illo. 

** Sirach 19:28

Est correptio mendax in ira contumeliosi,  et est judicium quod non probatur esse bonum :  et est tacens, et ipse est prudens.  

* Sirach 20

** Sirach 20:1

Quam bonum est arguere, quam irasci,  et confitentem in oratione non prohibere ! 

** Sirach 20:2

Concupiscentia spadonis devirginabit juvenculam : 

** Sirach 20:3

sic qui facit per vim judicium iniquum. 

** Sirach 20:4

Quam bonum est correptum manifestare pœnitentiam !  sic enim effugies voluntarium peccatum. 

** Sirach 20:5

Est tacens qui invenitur sapiens :  et est odibilis qui procax est ad loquendum. 

** Sirach 20:6

Est tacens non habens sensum loquelæ :  et est tacens sciens tempus aptum. 

** Sirach 20:7

Homo sapiens tacebit usque ad tempus :  lascivus autem et imprudens non servabunt tempus. 

** Sirach 20:8

Qui multis utitur verbis lædet animam suam :  et qui potestatem sibi sumit injuste, odietur. 

** Sirach 20:9

Est processio in malis viro indisciplinato,  et est inventio in detrimentum. 

** Sirach 20:10

Est datum quod non est utile,  et est datum cujus retributio duplex. 

** Sirach 20:11

Est propter gloriam minoratio,  et est qui ab humilitate levabit caput. 

** Sirach 20:12

Est qui multa redimat modico pretio,  et restituens ea in septuplum. 

** Sirach 20:13

Sapiens in verbis seipsum amabilem facit :  gratiæ autem fatuorum effundentur. 

** Sirach 20:14

Datus insipientis non erit utilis tibi :  oculi enim illius septemplices sunt. 

** Sirach 20:15

Exigua dabit, et multa improperabit :  et apertio oris illius inflammatio est. 

** Sirach 20:16

Hodie fœneratur quis, et cras expetit :  odibilis est homo hujusmodi. 

** Sirach 20:17

Fatuo non erit amicus,  et non erit gratia bonis illius : 

** Sirach 20:18

qui enim edunt panem illius, falsæ linguæ sunt.  Quoties et quanti irridebunt eum ! 

** Sirach 20:19

neque enim quod habendum erat directo sensu distribuit ;  similiter et quod non erat habendum. 

** Sirach 20:20

Lapsus falsæ linguæ quasi qui in pavimento cadens :  sic casus malorum festinanter veniet. 

** Sirach 20:21

Homo acharis quasi fabula vana,  in ore indisciplinatorum assidua erit. 

** Sirach 20:22

Ex ore fatui reprobabitur parabola :  non enim dicit illam in tempore suo. 

** Sirach 20:23

Est qui vetatur peccare præ inopia,  et in requie sua stimulabitur. 

** Sirach 20:24

Est qui perdet animam suam præ confusione,  et ab imprudenti persona perdet eam :  personæ autem acceptione perdet se. 

** Sirach 20:25

Est qui præ confusione promittit amico,  et lucratus est eum inimicum gratis. 

** Sirach 20:26

Opprobrium nequam in homine mendacium :  et in ore indisciplinatorum assidue erit. 

** Sirach 20:27

Potior fur quam assiduitas viri mendacis :  perditionem autem ambo hæreditabunt. 

** Sirach 20:28

Mores hominum mendacium sine honore,  et confusio illorum cum ipsis sine intermissione. 

** Sirach 20:29

Sapiens in verbis producet seipsum,  et homo prudens placebit magnatis. 

** Sirach 20:30

Qui operatur terram suam inaltabit acervum frugum,  et qui operatur justitiam, ipse exaltabitur :  qui vero placet magnatis effugiet iniquitatem. 

** Sirach 20:31

Xenia et dona excæcant oculos judicum,  et quasi mutus, in ore avertit correptiones eorum. 

** Sirach 20:32

Sapientia absconsa, et thesaurus invisus,  quæ utilitas in utrisque ? 

** Sirach 20:33

Melior est qui celat insipientiam suam,  quam homo qui abscondit sapientiam suam.  

* Sirach 21

** Sirach 21:1

Fili, peccasti, non adjicias iterum :  sed et de pristinis deprecare, ut tibi dimittantur. 

** Sirach 21:2

Quasi a facie colubri fuge peccata :  et si accesseris ad illa, suscipient te. 

** Sirach 21:3

Dentes leonis dentes ejus,  interficientes animas hominum. 

** Sirach 21:4

Quasi rhomphæa bis acuta omnis iniquitas :  plagæ illius non est sanitas. 

** Sirach 21:5

Objurgatio et injuriæ annullabunt substantiam,  et domus quæ nimis locuples est annullabitur superbia :  sic substantia superbi eradicabitur. 

** Sirach 21:6

Deprecatio pauperis ex ore usque ad aures ejus perveniet,  et judicium festinato adveniet illi. 

** Sirach 21:7

Qui odit correptionem vestigium est peccatoris,  et qui timet Deum convertetur ad cor suum. 

** Sirach 21:8

Notus a longe potens lingua audaci,  et sensatus scit labi se ab ipso. 

** Sirach 21:9

Qui ædificat domum suam impendiis alienis,  quasi qui colligit lapides suos in hieme. 

** Sirach 21:10

Stupa collecta synagoga peccantium,  et consummatio illorum flamma ignis. 

** Sirach 21:11

Via peccatorum complanata lapidibus :  et in fine illorum inferi, et tenebræ, et pœnæ. 

** Sirach 21:12

Qui custodit justitiam, continebit sensum ejus. 

** Sirach 21:13

Consummatio timoris Dei, sapientia et sensus. 

** Sirach 21:14

Non erudietur  qui non est sapiens in bono. 

** Sirach 21:15

Est autem sapientia quæ abundat in malo,  et non est sensus ubi est amaritudo. 

** Sirach 21:16

Scientia sapientis tamquam inundatio abundabit,  et consilium illius sicut fons vitæ permanet. 

** Sirach 21:17

Cor fatui quasi vas confractum,  et omnem sapientiam non tenebit. 

** Sirach 21:18

Verbum sapiens quodcumque audierit scius,  laudabit, et ad se adjiciet :  audivit luxuriosus, et displicebit illi,  et projiciet illud post dorsum suum. 

** Sirach 21:19

Narratio fatui quasi sarcina in via :  nam in labiis sensati invenietur gratia. 

** Sirach 21:20

Os prudentis quæritur in ecclesia,  et verba illius cogitabunt in cordibus suis. 

** Sirach 21:21

Tamquam domus exterminata, sic fatuo sapientia :  et scientia insensati inenarrabilia verba. 

** Sirach 21:22

Compedes in pedibus, stulto doctrina :  et quasi vincula manuum super manum dextram. 

** Sirach 21:23

Fatuus in risu exaltat vocem suam :  vir autem sapiens vix tacite ridebit. 

** Sirach 21:24

Ornamentum aureum prudenti doctrina,  et quasi brachiale in brachio dextro. 

** Sirach 21:25

Pes fatui facilis in domum proximi :  et homo peritus confundetur a persona potentis. 

** Sirach 21:26

Stultus a fenestra respiciet in domum :  vir autem eruditus foris stabit. 

** Sirach 21:27

Stultitia hominis auscultare per ostium :  et prudens gravabitur contumelia. 

** Sirach 21:28

Labia imprudentium stulta narrabunt ;  verba autem prudentium statera ponderabuntur. 

** Sirach 21:29

In ore fatuorum cor illorum,  et in corde sapientium os illorum. 

** Sirach 21:30

Dum maledicit impius diabolum,  maledicit ipse animam suam. 

** Sirach 21:31

Susurro coinquinabit animam suam, et in omnibus odietur,  et qui cum eo manserit odiosus erit :  tacitus et sensatus honorabitur.  

* Sirach 22

** Sirach 22:1

In lapide luteo lapidatus est piger :  et omnes loquentur super aspernationem illius. 

** Sirach 22:2

De stercore boum lapidatus est piger :  et omnis qui tetigerit eum excutiet manus. 

** Sirach 22:3

Confusio patris est de filio indisciplinato :  filia autem in deminoratione fiet. 

** Sirach 22:4

Filia prudens hæreditas viro suo :  nam quæ confundit, in contumeliam fit genitoris. 

** Sirach 22:5

Patrem et virum confundit audax,  et ab impiis non minorabitur :  ab utrisque autem inhonorabitur. 

** Sirach 22:6

Musica in luctu importuna narratio :  flagella et doctrina in omni tempore sapientia. 

** Sirach 22:7

Qui docet fatuum,  quasi qui conglutinat testam. 

** Sirach 22:8

Qui narrat verbum non audienti,  quasi qui excitat dormientem de gravi somno. 

** Sirach 22:9

Cum dormiente loquitur qui enarrat stulto sapientiam :  et in fine narrationis dicit : Quis est hic ? 

** Sirach 22:10

Supra mortuum plora, defecit enim lux ejus :  et supra fatuum plora, defecit enim sensus. 

** Sirach 22:11

Modicum plora super mortuum, quoniam requievit : 

** Sirach 22:12

nequissimi enim nequissima vita super mortem fatui. 

** Sirach 22:13

Luctus mortui septem dies :  fatui autem et impii omnes dies vitæ illorum. 

** Sirach 22:14

Cum stulto ne multum loquaris,  et cum insensato ne abieris. 

** Sirach 22:15

Serva te ab illo, ut non molestiam habeas,  et non coinquinaberis peccato illius. 

** Sirach 22:16

Deflecte ab illo, et invenies requiem,  et non acediaberis in stultitia illius. 

** Sirach 22:17

Super plumbum quid gravabitur ?  et quod illi aliud nomen quam fatuus ? 

** Sirach 22:18

Arenam, et salem, et massam ferri facilius est ferre  quam hominem imprudentem, et fatuum, et impium. 

** Sirach 22:19

Loramentum ligneum colligatum in fundamento ædificii non dissolvetur,  sic et cor confirmatum in cogitatione consilii. 

** Sirach 22:20

Cogitatus sensati in omni tempore metu non depravabitur. 

** Sirach 22:21

Sicut pali in excelsis, et cæmenta sine impensa posita,  contra faciem venti non permanebunt : 

** Sirach 22:22

sic et cor timidum in cogitatione stulti  contra impetum timoris non resistet. 

** Sirach 22:23

Sicut cor trepidum in cogitatione fatui omni tempore non metuet,  sic et qui in præceptis Dei permanet semper. 

** Sirach 22:24

Pungens oculum deducit lacrimas,  et qui pungit cor profert sensum. 

** Sirach 22:25

Mittens lapidem in volatilia, dejiciet illa :  sic et qui conviciatur amico, dissolvit amicitiam. 

** Sirach 22:26

Ad amicum etsi produxeris gladium, non desperes :  est enim regressus.  Ad amicum

** Sirach 22:27

si aperueris os triste, non timeas :  est enim concordatio :  excepto convitio, et improperio, et superbia,  et mysterii revelatione, et plaga dolosa :  in his omnibus effugiet amicus. 

** Sirach 22:28

Fidem posside cum amico in paupertate illius,  ut et in bonis illius læteris. 

** Sirach 22:29

In tempore tribulationis illius permane illi fidelis,  ut et in hæreditate illius cohæres sis. 

** Sirach 22:30

Ante ignem camini vapor et fumus ignis inaltatur :  sic et ante sanguinem maledicta, et contumeliæ, et minæ. 

** Sirach 22:31

Amicum salutare non confundar,  a facie illius non me abscondam :  et si mala mihi evenerint per illum, sustinebo. 

** Sirach 22:32

Omnis qui audiet cavebit se ab eo. 

** Sirach 22:33

Quis dabit ori meo custodiam,  et super labia mea signaculum certum,  ut non cadam ab ipsis,  et lingua mea perdat me ?  

* Sirach 23

** Sirach 23:1

Domine, pater et dominator vitæ meæ,  ne derelinquas me in consilio eorum,  nec sinas me cadere in illis. 

** Sirach 23:2

Quis superponet in cogitatu meo flagella,  et in corde meo doctrinam sapientiæ,  ut ignorationibus eorum non parcant mihi,  et non appareant delicta eorum, 

** Sirach 23:3

et ne adincrescant ignorantiæ meæ,  et multiplicentur delicta mea,  et peccata mea abundent,  et incidam in conspectu adversariorum meorum,  et gaudeat super me inimicus meus ? 

** Sirach 23:4

Domine, pater et Deus vitæ meæ,  ne derelinquas me in cogitatu illorum. 

** Sirach 23:5

Extollentiam oculorum meorum ne dederis mihi,  et omne desiderium averte a me. 

** Sirach 23:6

Aufer a me ventris concupiscentias,  et concubitus concupiscentiæ ne apprehendant me,  et animæ irreverenti et infrunitæ ne tradas me. 

** Sirach 23:7

Doctrinam oris audite, filii :  et qui custodierit illam non periet labiis,  nec scandalizabitur in operibus nequissimis. 

** Sirach 23:8

In vanitate sua apprehenditur peccator :  et superbus et maledicus scandalizabitur in illis. 

** Sirach 23:9

Jurationi non assuescat os tuum :  multi enim casus in illa. 

** Sirach 23:10

Nominatio vero Dei non sit assidua in ore tuo,  et nominibus sanctorum non admiscearis,  quoniam non erit immunis ab eis. 

** Sirach 23:11

Sicut enim servus interrogatus assidue a livore non minuitur,  sic omnis jurans et nominans in toto a peccato non purgabitur. 

** Sirach 23:12

Vir multum jurans implebitur iniquitate,  et non discedet a domo illius plaga. 

** Sirach 23:13

Et si frustraverit, delictum illius super ipsum erit :  et si dissimulaverit, delinquit dupliciter : 

** Sirach 23:14

et si in vacuum juraverit, non justificabitur :  replebitur enim retributione domus illius. 

** Sirach 23:15

Est et alia loquela contraria morti :  non inveniatur in hæreditate Jacob. 

** Sirach 23:16

Etenim a misericordibus omnia hæc auferentur,  et in delictis non volutabuntur. 

** Sirach 23:17

Indisciplinatæ loquelæ non assuescat os tuum :  est enim in illa verbum peccati. 

** Sirach 23:18

Memento patris et matris tuæ :  in medio enim magnatorum consistis : 

** Sirach 23:19

ne forte obliviscatur te Deus in conspectu illorum,  et assiduitate tua infatuatus, improperium patiaris,  et maluisses non nasci,  et diem nativitatis tuæ maledicas. 

** Sirach 23:20

Homo assuetus in verbis improperii  in omnibus diebus suis non erudietur. 

** Sirach 23:21

Duo genera abundant in peccatis,  et tertium adducit iram et perditionem. 

** Sirach 23:22

Anima calida quasi ignis ardens,  non extinguetur donec aliquid glutiat : 

** Sirach 23:23

et homo nequam in ore carnis suæ  non desinet donec incendat ignem. 

** Sirach 23:24

Homini fornicario omnis panis dulcis :  non fatigabitur transgrediens usque ad finem. 

** Sirach 23:25

Omnis homo qui transgreditur lectum suum,  contemnens in animam suam, et dicens : Quis me videt ? 

** Sirach 23:26

Tenebræ circumdant me, et parietes cooperiunt me,  et nemo circumspicit me : quem vereor ?  delictorum meorum non memorabitur Altissimus. 

** Sirach 23:27

Et non intelligit quoniam omnia videt oculus illius,  quoniam expellit a se timorem Dei hujusmodi hominis timor,  et oculi hominum timentes illum : 

** Sirach 23:28

et non cognovit quoniam oculi Domini  multo plus lucidiores sunt super solem,  circumspicientes omnes vias hominum,  et profundum abyssi, et hominum corda,  intuentes in absconditas partes. 

** Sirach 23:29

Domino enim Deo antequam crearentur omnia sunt agnita :  sic et post perfectum respicit omnia. 

** Sirach 23:30

Hic in plateis civitatis vindicabitur,  et quasi pullus equinus fugabitur,  et ubi non speravit apprehendetur. 

** Sirach 23:31

Et erit dedecus omnibus,  eo quod non intellexerit timorem Domini. 

** Sirach 23:32

Sic et mulier omnis relinquens virum suum,  et statuens hæreditatem ex alieno matrimonio : 

** Sirach 23:33

primo enim in lege Altissimi incredibilis fuit :  secundo in virum suum deliquit :  tertio in adulterio fornicata est,  et ex alio viro filios statuit sibi. 

** Sirach 23:34

Hæc in ecclesiam adducetur,  et in filios ejus respicietur : 

** Sirach 23:35

non tradent filii ejus radices,  et rami ejus non dabunt fructum : 

** Sirach 23:36

derelinquet in maledictum memoriam ejus,  et dedecus illius non delebitur. 

** Sirach 23:37

Et agnoscent qui derelicti sunt,  quoniam nihil melius est quam timor Dei,  et nihil dulcius quam respicere in mandatis Domini. 

** Sirach 23:38

Gloria magna est sequi Dominum :  longitudo enim dierum assumetur ab eo.  

* Sirach 24

** Sirach 24:1

Sapientia laudabit animam suam,  et in Deo honorabitur,  et in medio populi sui gloriabitur, 

** Sirach 24:2

et in ecclesiis Altissimi aperiet os suum,  et in conspectu virtutis illius gloriabitur, 

** Sirach 24:3

et in medio populi sui exaltabitur,  et in plenitudine sancta admirabitur, 

** Sirach 24:4

et in multitudine electorum habebit laudem,  et inter benedictos benedicetur, dicens : 

** Sirach 24:5

Ego ex ore Altissimi prodivi,  primogenita ante omnem creaturam. 

** Sirach 24:6

Ego feci in cælis ut oriretur lumen indeficiens,  et sicut nebula texi omnem terram. 

** Sirach 24:7

Ego in altissimis habitavi,  et thronus meus in columna nubis. 

** Sirach 24:8

Gyrum cæli circuivi sola,  et profundum abyssi penetravi :  in fluctibus maris ambulavi. 

** Sirach 24:9

Et in omni terra steti :  et in omni populo, 

** Sirach 24:10

et in omni gente primatum habui : 

** Sirach 24:11

et omnium excellentium et humilium corda virtute calcavi.  Et in his omnibus requiem quæsivi,  et in hæreditate Domini morabor. 

** Sirach 24:12

Tunc præcepit, et dixit mihi Creator omnium :  et qui creavit me, requievit in tabernaculo meo. 

** Sirach 24:13

Et dixit mihi : In Jacob inhabita,  et in Israël hæreditare,  et in electis meis mitte radices. 

** Sirach 24:14

Ab initio et ante sæcula creata sum,  et usque ad futurum sæculum non desinam :  et in habitatione sancta coram ipso ministravi. 

** Sirach 24:15

Et sic in Sion firmata sum,  et in civitate sanctificata similiter requievi,  et in Jerusalem potestas mea. 

** Sirach 24:16

Et radicavi in populo honorificato,  et in parte Dei mei hæreditas illius,  et in plenitudine sanctorum detentio mea. 

** Sirach 24:17

Quasi cedrus exaltata sum in Libano,  et quasi cypressus in monte Sion : 

** Sirach 24:18

quasi palma exaltata sum in Cades,  et quasi plantatio rosæ in Jericho : 

** Sirach 24:19

quasi oliva speciosa in campis,  et quasi platanus exaltata sum juxta aquam in plateis. 

** Sirach 24:20

Sicut cinnamomum et balsamum aromatizans odorem dedi ;  quasi myrrha electa dedi suavitatem odoris : 

** Sirach 24:21

et quasi storax, et galbanus, et ungula, et gutta,  et quasi Libanus non incisus vaporavi habitationem meam,  et quasi balsamum non mistum odor meus. 

** Sirach 24:22

Ego quasi terebinthus extendi ramos meos,  et rami mei honoris et gratiæ. 

** Sirach 24:23

Ego quasi vitis fructificavi suavitatem odoris :  et flores mei fructus honoris et honestatis. 

** Sirach 24:24

Ego mater pulchræ dilectionis, et timoris,  et agnitionis, et sanctæ spei. 

** Sirach 24:25

In me gratia omnis viæ et veritatis :  in me omnis spes vitæ et virtutis. 

** Sirach 24:26

Transite ad me, omnes qui concupiscitis me,  et a generationibus meis implemini : 

** Sirach 24:27

spiritus enim meus super mel dulcis,  et hæreditas mea super mel et favum. 

** Sirach 24:28

Memoria mea in generationes sæculorum. 

** Sirach 24:29

Qui edunt me, adhuc esurient,  et qui bibunt me, adhuc sitient. 

** Sirach 24:30

Qui audit me non confundetur,  et qui operantur in me non peccabunt : 

** Sirach 24:31

qui elucidant me, vitam æternam habebunt. 

** Sirach 24:32

Hæc omnia liber vitæ,  et testamentum Altissimi, et agnitio veritatis. 

** Sirach 24:33

Legem mandavit Moyses in præceptis justitiarum,  et hæreditatem domui Jacob,  et Israël promissiones. 

** Sirach 24:34

Posuit David, puero suo,  excitare regem ex ipso fortissimum,  et in throno honoris sedentem in sempiternum. 

** Sirach 24:35

Qui implet quasi Phison sapientiam,  et sicut Tigris in diebus novorum : 

** Sirach 24:36

qui adimplet quasi Euphrates sensum,  qui multiplicat quasi Jordanis in tempore messis : 

** Sirach 24:37

qui mittit disciplinam sicut lucem,  et assistens quasi Gehon in die vindemiæ. 

** Sirach 24:38

Qui perficit primus scire ipsam,  et infirmior non investigabit eam. 

** Sirach 24:39

A mari enim abundavit cogitatio ejus,  et consilium illius ab abysso magna. 

** Sirach 24:40

Ego sapientia effudi flumina : 

** Sirach 24:41

ego quasi trames aquæ immensæ de fluvio :  ego quasi fluvii dioryx,  et sicut aquæductus exivi de paradiso. 

** Sirach 24:42

Dixi : Rigabo hortum meum plantationum,  et inebriabo prati mei fructum. 

** Sirach 24:43

Et ecce factus est mihi trames abundans,  et fluvius meus appropinquavit ad mare : 

** Sirach 24:44

quoniam doctrinam quasi antelucanum illumino omnibus,  et enarrabo illam usque ad longinquum. 

** Sirach 24:45

Penetrabo omnes inferiores partes terræ,  et inspiciam omnes dormientes,  et illuminabo omnes sperantes in Domino. 

** Sirach 24:46

Adhuc doctrinam quasi prophetiam effundam,  et relinquam illam quærentibus sapientiam,  et non desinam in progenies illorum usque in ævum sanctum. 

** Sirach 24:47

Videte quoniam non soli mihi laboravi,  sed omnibus exquirentibus veritatem.  

* Sirach 25

** Sirach 25:1

In tribus placitum est spiritui meo,  quæ sunt probata coram Deo et hominibus : 

** Sirach 25:2

concordia fratrum,  et amor proximorum,  et vir et mulier bene sibi consentientes. 

** Sirach 25:3

Tres species odivit anima mea,  et aggravor valde animæ illorum : 

** Sirach 25:4

pauperem superbum, divitem mendacem,  senem fatuum et insensatum. 

** Sirach 25:5

Quæ in juventute tua non congregasti,  quomodo in senectute tua invenies ? 

** Sirach 25:6

Quam speciosum canitiei judicium,  et presbyteris cognoscere consilium ! 

** Sirach 25:7

Quam speciosa veteranis sapientia,  et gloriosus intellectus et consilium ! 

** Sirach 25:8

Corona senum multa peritia,  et gloria illorum timor Dei. 

** Sirach 25:9

Novem insuspicabilia cordis magnificavi :  et decimum dicam in lingua hominibus : 

** Sirach 25:10

homo qui jucundatur in filiis,  vivens et videns subversionem inimicorum suorum. 

** Sirach 25:11

Beatus qui habitat cum muliere sensata,  et qui lingua sua non est lapsus,  et qui non servivit indignis se. 

** Sirach 25:12

Beatus qui invenit amicum verum,  et qui enarrat justitiam auri audienti. 

** Sirach 25:13

Quam magnus qui invenit sapientiam et scientiam !  sed non est super timentem Dominum. 

** Sirach 25:14

Timor Dei super omnia se superposuit. 

** Sirach 25:15

Beatus homo cui donatum est habere timorem Dei :  qui tenet illum, cui assimilabitur ? 

** Sirach 25:16

Timor Dei initium dilectionis ejus :  fidei autem initium agglutinandum est ei. 

** Sirach 25:17

Omnis plaga tristitia cordis est,  et omnis malitia nequitia mulieris. 

** Sirach 25:18

Et omnem plagam, et non plagam videbit cordis : 

** Sirach 25:19

et omnem nequitiam, et non nequitiam mulieris : 

** Sirach 25:20

et omnem obductum, et non obductum odientium : 

** Sirach 25:21

et omnem vindictam, et non vindictam inimicorum. 

** Sirach 25:22

Non est caput nequius super caput colubri, 

** Sirach 25:23

et non est ira super iram mulieris.  Commorari leoni et draconi placebit,  quam habitare cum muliere nequam. 

** Sirach 25:24

Nequitia mulieris immutat faciem ejus :  et obcæcat vultum suum tamquam ursus,  et quasi saccum ostendit.  In medio proximorum ejus 

** Sirach 25:25

ingemuit vir ejus,  et audiens suspiravit modicum. 

** Sirach 25:26

Brevis omnis malitia super malitiam mulieris :  sors peccatorum cadat super illam. 

** Sirach 25:27

Sicut ascensus arenosus in pedibus veterani,  sic mulier linguata homini quieto. 

** Sirach 25:28

Ne respicias in mulieris speciem,  et non concupiscas mulierem in specie. 

** Sirach 25:29

Mulieris ira, et irreverentia,  et confusio magna. 

** Sirach 25:30

Mulier si primatum habeat,  contraria est viro suo. 

** Sirach 25:31

Cor humile, et facies tristis,  et plaga cordis, mulier nequam. 

** Sirach 25:32

Manus debiles et genua dissoluta,  mulier quæ non beatificat virum suum. 

** Sirach 25:33

A muliere initium factum est peccati,  et per illam omnes morimur. 

** Sirach 25:34

Non des aquæ tuæ exitum, nec modicum :  nec mulieri nequam veniam prodeundi. 

** Sirach 25:35

Si non ambulaverit ad manum tuam,  confundet te in conspectu inimicorum. 

** Sirach 25:36

A carnibus tuis abscinde illam,  ne semper te abutatur.  

* Sirach 26

** Sirach 26:1

Mulieris bonæ beatus vir :  numerus enim annorum illius duplex. 

** Sirach 26:2

Mulier fortis oblectat virum suum,  et annos vitæ illius in pace implebit. 

** Sirach 26:3

Pars bona mulier bona,  in parte timentium Deum dabitur viro pro factis bonis : 

** Sirach 26:4

divitis autem et pauperis cor bonum,  in omni tempore vultus illorum hilaris. 

** Sirach 26:5

A tribus timuit cor meum,  et in quarto facies mea metuit : 

** Sirach 26:6

delaturam civitatis, et collectionem populi : 

** Sirach 26:7

calumniam mendacem super mortem omnia gravia : 

** Sirach 26:8

dolor cordis et luctus, mulier zelotypa. 

** Sirach 26:9

In muliere zelotypa flagellum linguæ,  omnibus communicans. 

** Sirach 26:10

Sicut boum jugum quod movetur, ita et mulier nequam :  qui tenet illam quasi qui apprehendit scorpionem. 

** Sirach 26:11

Mulier ebriosa ira magna, et contumelia :  et turpitudo illius non tegetur. 

** Sirach 26:12

Fornicatio mulieris in extollentia oculorum,  et in palpebris illius agnoscetur. 

** Sirach 26:13

In filia non avertente se, firma custodiam,  ne inventa occasione utatur se. 

** Sirach 26:14

Ab omni irreverentia oculorum ejus cave,  et ne mireris si te neglexerit. 

** Sirach 26:15

Sicut viator sitiens ad fontem os aperiet,  et ab omni aqua proxima bibet,  et contra omnem palum sedebit,  et contra omnem sagittam aperiet pharetram donec deficiat. 

** Sirach 26:16

Gratia mulieris sedulæ delectabit virum suum,  et ossa illius impinguabit. 

** Sirach 26:17

Disciplina illius datum Dei est. 

** Sirach 26:18

Mulier sensata et tacita,  non est immutatio eruditæ animæ. 

** Sirach 26:19

Gratia super gratiam  mulier sancta et pudorata. 

** Sirach 26:20

Omnis autem ponderatio non est digna  continentis animæ. 

** Sirach 26:21

Sicut sol oriens mundo in altissimis Dei,  sic mulieris bonæ species in ornamentum domus ejus. 

** Sirach 26:22

Lucerna splendens super candelabrum sanctum,  et species faciei super ætatem stabilem. 

** Sirach 26:23

Columnæ aureæ super bases argenteas,  et pedes firmi super plantas stabilis mulieris. 

** Sirach 26:24

Fundamenta æterna supra petram solidam,  et mandata Dei in corde mulieris sanctæ. 

** Sirach 26:25

In duobus contristatum est cor meum,  et in tertio iracundia mihi advenit : 

** Sirach 26:26

vir bellator deficiens per inopiam ;  et vir sensatus contemptus ; 

** Sirach 26:27

et qui transgreditur a justitia ad peccatum :  Deus paravit eum ad rhomphæam. 

** Sirach 26:28

Duæ species difficiles et periculosæ mihi apparuerunt :  difficile exuitur negotians a negligentia,  et non justificabitur caupo a peccatis labiorum.  

* Sirach 27

** Sirach 27:1

Propter inopiam multi deliquerunt :  et qui quærit locupletari avertit oculum suum. 

** Sirach 27:2

Sicut in medio compaginis lapidum palus figitur,  sic et inter medium venditionis et emptionis angustiabitur peccatum : 

** Sirach 27:3

conteretur cum delinquente delictum. 

** Sirach 27:4

Si non in timore Domini tenueris te instanter,  cito subvertetur domus tua. 

** Sirach 27:5

Sicut in percussura cribri remanebit pulvis,  sic aporia hominis in cogitatu illius. 

** Sirach 27:6

Vasa figuli probat fornax,  et homines justos tentatio tribulationis. 

** Sirach 27:7

Sicut rusticatio de ligno ostendit fructum illius,  sic verbum ex cogitatu cordis hominis. 

** Sirach 27:8

Ante sermonem non laudes virum :  hæc enim tentatio est hominum. 

** Sirach 27:9

Si sequaris justitiam, apprehendes illam,  et indues quasi poderem honoris :  et inhabitabis cum ea, et proteget te in sempiternum,  et in die agnitionis invenies firmamentum. 

** Sirach 27:10

Volatilia ad sibi similia conveniunt :  et veritas ad eos qui operantur illam revertetur. 

** Sirach 27:11

Leo venationi insidiatur semper :  sic peccata operantibus iniquitates. 

** Sirach 27:12

Homo sanctus in sapientia manet sicut sol :  nam stultus sicut luna mutatur. 

** Sirach 27:13

In medio insensatorum serva verbum tempori :  in medio autem cogitantium assiduus esto. 

** Sirach 27:14

Narratio peccantium odiosa,  et risus illorum in deliciis peccati. 

** Sirach 27:15

Loquela multum jurans horripilationem capiti statuet,  et irreverentia ipsius obturatio aurium. 

** Sirach 27:16

Effusio sanguinis in rixa superborum,  et maledictio illorum auditus gravis. 

** Sirach 27:17

Qui denudat arcana amici fidem perdit,  et non inveniet amicum ad animum suum. 

** Sirach 27:18

Dilige proximum,  et conjungere fide cum illo. 

** Sirach 27:19

Quod si denudaveris absconsa illius,  non persequeris post eum. 

** Sirach 27:20

Sicut enim homo qui perdit amicum suum,  sic et qui perdit amicitiam proximi sui. 

** Sirach 27:21

Et sicut qui dimittit avem de manu sua,  sic dereliquisti proximum tuum, et non eum capies. 

** Sirach 27:22

Non illum sequaris, quoniam longe abest :  effugit enim quasi caprea de laqueo, quoniam vulnerata est anima ejus : 

** Sirach 27:23

ultra eum non poteris colligare.  Et maledicti est concordatio : 

** Sirach 27:24

denudare autem amici mysteria, desperatio est animæ infelicis. 

** Sirach 27:25

Annuens oculo fabricat iniqua,  et nemo eum abjiciet. 

** Sirach 27:26

In conspectu oculorum tuorum condulcabit os suum,  et super sermones tuos admirabitur :  novissime autem pervertet os suum,  et in verbis tuis dabit scandalum. 

** Sirach 27:27

Multa odivi, et non coæquavi ei,  et Dominus odiet illum. 

** Sirach 27:28

Qui in altum mittit lapidem, super caput ejus cadet :  et plaga dolosa dolosi dividet vulnera. 

** Sirach 27:29

Et qui foveam fodit incidet in eam :  et qui statuit lapidem proximo offendet in eo :  et qui laqueum alii ponit, peribit in illo. 

** Sirach 27:30

Facienti nequissimum consilium, super ipsum devolvetur,  et non agnoscet unde adveniat illi. 

** Sirach 27:31

Illusio et improperium superborum,  et vindicta sicut leo insidiabitur illi. 

** Sirach 27:32

Laqueo peribunt qui oblectantur casu justorum,  dolor autem consumet illos antequam moriantur. 

** Sirach 27:33

Ira et furor utraque execrabilia sunt,  et vir peccator continens erit illorum.  

* Sirach 28

** Sirach 28:1

Qui vindicari vult, a Domino inveniet vindictam,  et peccata illius servans servabit. 

** Sirach 28:2

Relinque proximo tuo nocenti te,  et tunc deprecanti tibi peccata solventur. 

** Sirach 28:3

Homo homini reservat iram,  et a Deo quærit medelam : 

** Sirach 28:4

in hominem similem sibi non habet misericordiam,  et de peccatis suis deprecatur. 

** Sirach 28:5

Ipse cum caro sit reservat iram,  et propitiationem petit a Deo :  quis exorabit pro delictis illius ? 

** Sirach 28:6

Memento novissimorum, et desine inimicari : 

** Sirach 28:7

tabitudo enim et mors imminent in mandatis ejus. 

** Sirach 28:8

Memorare timorem Dei,  et non irascaris proximo. 

** Sirach 28:9

Memorare testamentum Altissimi,  et despice ignorantiam proximi. 

** Sirach 28:10

Abstine te a lite,  et minues peccata. 

** Sirach 28:11

Homo enim iracundus incendit litem,  et vir peccator turbabit amicos,  et in medio pacem habentium immittet inimicitiam. 

** Sirach 28:12

Secundum enim ligna silvæ sic ignis exardescit :  et secundum virtutem hominis sic iracundia illius erit,  et secundum substantiam suam exaltabit iram suam. 

** Sirach 28:13

Certamen festinatum incendit ignem,  et lis festinans effundit sanguinem :  et lingua testificans adducit mortem. 

** Sirach 28:14

Si sufflaveris in scintillam, quasi ignis exardebit :  et si exspueris super illam, extinguetur :  utraque ex ore proficiscuntur. 

** Sirach 28:15

Susurro et bilinguis maledictus,  multos enim turbabit pacem habentes. 

** Sirach 28:16

Lingua tertia multos commovit,  et dispersit illos de gente in gentem. 

** Sirach 28:17

Civitates muratas divitum destruxit,  et domus magnatorum effodit. 

** Sirach 28:18

Virtutes populorum concidit,  et gentes fortes dissolvit. 

** Sirach 28:19

Lingua tertia mulieres viratas ejecit,  et privavit illas laboribus suis. 

** Sirach 28:20

Qui respicit illam non habebit requiem,  nec habebit amicum in quo requiescat. 

** Sirach 28:21

Flagelli plaga livorem facit :  plaga autem linguæ comminuet ossa. 

** Sirach 28:22

Multi ceciderunt in ore gladii :  sed non sic quasi qui interierunt per linguam suam. 

** Sirach 28:23

Beatus qui tectus est a lingua nequam,  qui in iracundiam illius non transivit,  et qui non attraxit jugum illius,  et in vinculis ejus non est ligatus : 

** Sirach 28:24

jugum enim illius jugum ferreum est,  et vinculum illius vinculum æreum est ; 

** Sirach 28:25

mors illius mors nequissima :  et utilis potius infernus quam illa. 

** Sirach 28:26

Perseverantia illius non permanebit,  sed obtinebit vias injustorum,  et in flamma sua non comburet justos. 

** Sirach 28:27

Qui relinquunt Deum incident in illam,  et exardebit in illis, et non extinguetur,  et immittetur in illos quasi leo,  et quasi pardus lædet illos. 

** Sirach 28:28

Sepi aures tuas spinis :  linguam nequam noli audire :  et ori tuo facito ostia et seras. 

** Sirach 28:29

Aurum tuum et argentum tuum confla,  et verbis tuis facito stateram,  et frenos ori tuo rectos : 

** Sirach 28:30

et attende ne forte labaris in lingua,  et cadas in conspectu inimicorum insidiantium tibi,  et sit casus tuus insanabilis in mortem.  

* Sirach 29

** Sirach 29:1

Qui facit misericordiam fœneratur proximo suo :  et qui prævalet manu mandata servat. 

** Sirach 29:2

Fœnerare proximo tuo in tempore necessitatis illius :  et iterum redde proximo in tempore suo. 

** Sirach 29:3

Confirma verbum, et fideliter age cum illo :  et in omni tempore invenies quod tibi necessarium est. 

** Sirach 29:4

Multi quasi inventionem æstimaverunt fœnus,  et præstiterunt molestiam his qui se adjuverunt. 

** Sirach 29:5

Donec accipiant, osculantur manus dantis,  et in promissionibus humiliant vocem suam : 

** Sirach 29:6

et in tempore redditionis postulabit tempus,  et loquetur verba tædii et murmurationum,  et tempus causabitur. 

** Sirach 29:7

Si autem potuerit reddere, adversabitur :  solidi vix reddet dimidium,  et computabit illud quasi inventionem : 

** Sirach 29:8

sin autem, fraudabit illum pecunia sua,  et possidebit illum inimicum gratis : 

** Sirach 29:9

et convitia et maledicta reddet illi,  et pro honore et beneficio reddet illi contumeliam. 

** Sirach 29:10

Multi non causa nequitiæ non fœnerati sunt,  sed fraudari gratis timuerunt. 

** Sirach 29:11

Verumtamen super humilem animo fortior esto,  et pro eleemosyna non trahas illum. 

** Sirach 29:12

Propter mandatum assume pauperem,  et propter inopiam ejus ne dimittas eum vacuum. 

** Sirach 29:13

Perde pecuniam propter fratrem et amicum tuum,  et non abscondas illam sub lapide in perditionem. 

** Sirach 29:14

Pone thesaurum tuum in præceptis Altissimi,  et proderit tibi magis quam aurum. 

** Sirach 29:15

Conclude eleemosynam in corde pauperis,  et hæc pro te exorabit ab omni malo. 

** Sirach 29:16

Super scutum potentis

** Sirach 29:17

et super lanceam 

** Sirach 29:18

adversus inimicum tuum pugnabit. 

** Sirach 29:19

Vir bonus fidem facit pro proximo suo :  et qui perdiderit confusionem derelinquet sibi. 

** Sirach 29:20

Gratiam fidejussoris ne obliviscaris :  dedit enim pro te animam suam. 

** Sirach 29:21

Repromissorem fugit peccator et immundus. 

** Sirach 29:22

Bona repromissoris sibi ascribit peccator :  et ingratus sensu derelinquet liberantem se. 

** Sirach 29:23

Vir repromittit de proximo suo :  et cum perdiderit reverentiam, derelinquetur ab eo. 

** Sirach 29:24

Repromissio nequissima multos perdidit dirigentes,  et commovit illos quasi fluctus maris. 

** Sirach 29:25

Viros potentes gyrans migrare fecit,  et vagati sunt in gentibus alienis. 

** Sirach 29:26

Peccator transgrediens mandatum Domini incidet in promissionem nequam :  et qui conatur multa agere incidet in judicium. 

** Sirach 29:27

Recupera proximum secundum virtutem tuam,  et attende tibi ne incidas. 

** Sirach 29:28

Initium vitæ hominis, aqua et panis,  et vestimentum, et domus protegens turpitudinem. 

** Sirach 29:29

Melior est victus pauperis sub tegmine asserum  quam epulæ splendidæ in peregre sine domicilio. 

** Sirach 29:30

Minimum pro magno placeat tibi,  et improperium peregrinationis non audies. 

** Sirach 29:31

Vita nequam hospitandi de domo in domum :  et ubi hospitabitur non fiducialiter aget, nec aperiet os. 

** Sirach 29:32

Hospitabitur, et pascet, et potabit ingratos,  et ad hæc amara audiet : 

** Sirach 29:33

transi, hospes, et orna mensam,  et quæ in manu habes ciba ceteros. 

** Sirach 29:34

Exi a facie honoris amicorum meorum :  necessitudine domus meæ hospitio mihi factus est frater. 

** Sirach 29:35

Gravia hæc homini habenti sensum :  correptio domus, et improperium fœneratoris.  

* Sirach 30

** Sirach 30:1

Qui diligit filium suum assiduat illi flagella,  ut lætetur in novissimo suo,  et non palpet proximorum ostia. 

** Sirach 30:2

Qui docet filium suum laudabitur in illo,  et in medio domesticorum in illo gloriabitur. 

** Sirach 30:3

Qui docet filium suum in zelum mittit inimicum,  et in medio amicorum gloriabitur in illo. 

** Sirach 30:4

Mortuus est pater ejus, et quasi non est mortuus :  similem enim reliquit sibi post se. 

** Sirach 30:5

In vita sua vidit, et lætatus est in illo :  in obitu suo non est contristatus,  nec confusus est coram inimicis : 

** Sirach 30:6

reliquit enim defensorem domus contra inimicos,  et amicis reddentem gratiam. 

** Sirach 30:7

Pro animabus filiorum colligabit vulnera sua,  et super omnem vocem turbabuntur viscera ejus. 

** Sirach 30:8

Equus indomitus evadit durus,  et filius remissus evadet præceps. 

** Sirach 30:9

Lacta filium, et paventem te faciet :  lude cum eo, et contristabit te. 

** Sirach 30:10

Non corrideas illi, ne doleas,  et in novissimo obstupescent dentes tui. 

** Sirach 30:11

Non des illi potestatem in juventute,  et ne despicias cogitatus illius. 

** Sirach 30:12

Curva cervicem ejus in juventute,  et tunde latera ejus dum infans est,  ne forte induret, et non credat tibi,  et erit tibi dolor animæ. 

** Sirach 30:13

Doce filium tuum, et operare in illo,  ne in turpitudinem illius offendas. 

** Sirach 30:14

Melior est pauper sanus, et fortis viribus,  quam dives imbecillis et flagellatus malitia. 

** Sirach 30:15

Salus animæ in sanctitate justitiæ  melior est omni auro et argento :  et corpus validum quam census immensus. 

** Sirach 30:16

Non est census super censum salutis corporis,  et non est oblectamentum super cordis gaudium. 

** Sirach 30:17

Melior est mors quam vita amara,  et requies æterna quam languor perseverans. 

** Sirach 30:18

Bona abscondita in ore clauso,  quasi appositiones epularum circumpositæ sepulchro. 

** Sirach 30:19

Quid proderit libatio idolo ?  nec enim manducabit, nec odorabit. 

** Sirach 30:20

Sic qui effugatur a Domino,  portans mercedes iniquitatis : 

** Sirach 30:21

videns oculis et ingemiscens,  sicut spado complectens virginem, et suspirans. 

** Sirach 30:22

Tristitiam non des animæ tuæ,  et non affligas temetipsum in consilio tuo. 

** Sirach 30:23

Jucunditas cordis, hæc est vita hominis,  et thesaurus sine defectione sanctitatis :  et exsultatio viri est longævitas. 

** Sirach 30:24

Miserere animæ tuæ placens Deo, et contine :  congrega cor tuum in sanctitate ejus,  et tristitiam longe repelle a te. 

** Sirach 30:25

Multos enim occidit tristitia,  et non est utilitas in illa. 

** Sirach 30:26

Zelus et iracundia minuunt dies,  et ante tempus senectam adducet cogitatus. 

** Sirach 30:27

Splendidum cor et bonum in epulis est :  epulæ enim illius diligenter fiunt.  

* Sirach 31

** Sirach 31:1

Vigilia honestatis tabefaciet carnes,  et cogitatus illius auferet somnum. 

** Sirach 31:2

Cogitatus præscientiæ avertit sensum,  et infirmitas gravis sobriam facit animam. 

** Sirach 31:3

Laboravit dives in congregatione substantiæ,  et in requie sua replebitur bonis suis. 

** Sirach 31:4

Laboravit pauper in diminutione victus,  et in fine inops fit. 

** Sirach 31:5

Qui aurum diligit non justificabitur,  et qui insequitur consumptionem replebitur ex ea. 

** Sirach 31:6

Multi dati sunt in auri casus,  et facta est in specie ipsius perditio illorum. 

** Sirach 31:7

Lignum offensionis est aurum sacrificantium :  væ illis qui sectantur illud !  et omnis imprudens deperiet in illo. 

** Sirach 31:8

Beatus dives qui inventus est sine macula,  et qui post aurum non abiit,  nec speravit in pecunia et thesauris. 

** Sirach 31:9

Quis est hic ? et laudabimus eum :  fecit enim mirabilia in vita sua. 

** Sirach 31:10

Qui probatus est in illo, et perfectus est, erit illi gloria æterna :  qui potuit transgredi, et non est transgressus ;  facere mala, et non fecit. 

** Sirach 31:11

Ideo stabilita sunt bona illius in Domino,  et eleemosynas illius enarrabit omnis ecclesia sanctorum. 

** Sirach 31:12

Supra mensam magnam sedisti ?  non aperias super illam faucem tuam prior. 

** Sirach 31:13

Non dicas sic : Multa sunt, quæ super illam sunt. 

** Sirach 31:14

Memento quoniam malus est oculus nequam. 

** Sirach 31:15

Nequius oculo quid creatum est ?  ideo ab omni facie sua lacrimabitur, cum viderit. 

** Sirach 31:16

Ne extendas manum tuam prior,  et invidia contaminatus erubescas. 

** Sirach 31:17

Ne comprimaris in convivio. 

** Sirach 31:18

Intellige quæ sunt proximi tui ex teipso. 

** Sirach 31:19

Utere quasi homo frugi his quæ tibi apponuntur :  ne, cum manducas multum, odio habearis. 

** Sirach 31:20

Cessa prior causa disciplinæ :  et noli nimius esse, ne forte offendas. 

** Sirach 31:21

Et si in medio multorum sedisti,  prior illis ne extendas manum tuam,  nec prior poscas bibere. 

** Sirach 31:22

Quam sufficiens est homini erudito vinum exiguum !  et in dormiendo non laborabis ab illo,  et non senties dolorem. 

** Sirach 31:23

Vigilia, cholera et tortura viro infrunito, 

** Sirach 31:24

somnus sanitatis in homine parco :  dormiet usque mane,  et anima illius cum ipso delectabitur. 

** Sirach 31:25

Et si coactus fueris in edendo multum,  surge e medio, evome, et refrigerabit te,  et non adduces corpori tuo infirmitatem. 

** Sirach 31:26

Audi me, fili, et ne spernas me,  et in novissimo invenies verba mea. 

** Sirach 31:27

In omnibus operibus tuis esto velox,  et omnis infirmitas non occurret tibi. 

** Sirach 31:28

Splendidum in panibus benedicent labia multorum,  et testimonium veritatis illius fidele. 

** Sirach 31:29

Nequissimo in pane murmurabit civitas,  et testimonium nequitiæ illius verum est. 

** Sirach 31:30

Diligentes in vino noli provocare :  multos enim exterminavit vinum. 

** Sirach 31:31

Ignis probat ferrum durum :  sic vinum corda superborum arguet in ebrietate potatum. 

** Sirach 31:32

Æqua vita hominibus vinum in sobrietate :  si bibas illud moderate, eris sobrius. 

** Sirach 31:33

Quæ vita est ei qui minuitur vino ? 

** Sirach 31:34

Quid defraudat vitam ? mors. 

** Sirach 31:35

Vinum in jucunditatem creatum est,  et non in ebrietatem ab initio. 

** Sirach 31:36

Exsultatio animæ et cordis vinum moderate potatum. 

** Sirach 31:37

Sanitas est animæ et corpori sobrius potus. 

** Sirach 31:38

Vinum multum potatum irritationem,  et iram, et ruinas multas facit. 

** Sirach 31:39

Amaritudo animæ  vinum multum potatum. 

** Sirach 31:40

Ebrietatis animositas, imprudentis offensio,  minorans virtutem, et faciens vulnera. 

** Sirach 31:41

In convivio vini non arguas proximum,  et non despicias eum in jucunditate illius. 

** Sirach 31:42

Verba improperii non dicas illi,  et non premas illum repetendo.  

* Sirach 32

** Sirach 32:1

Rectorem te posuerunt ? noli extolli :  esto in illis quasi unus ex ipsis. 

** Sirach 32:2

Curam illorum habe, et sic conside,  et omni cura tua explicita recumbe : 

** Sirach 32:3

ut læteris propter illos,  et ornamentum gratiæ accipias coronam,  et dignationem consequaris corrogationis. 

** Sirach 32:4

Loquere major natu :  decet enim te 

** Sirach 32:5

primum verbum diligenti scientia,  et non impedias musicam. 

** Sirach 32:6

Ubi auditus non est, non effundas sermonem,  et importune noli extolli in sapientia tua. 

** Sirach 32:7

Gemmula carbunculi in ornamento auri,  et comparatio musicorum in convivio vini. 

** Sirach 32:8

Sicut in fabricatione auri signum est smaragdi,  sic numerus musicorum in jucundo et moderato vino. 

** Sirach 32:9

Audi tacens,  et pro reverentia accedet tibi bona gratia. 

** Sirach 32:10

Adolescens, loquere in tua causa vix. 

** Sirach 32:11

Si bis interrogatus fueris,  habeat caput responsum tuum. 

** Sirach 32:12

In multis esto quasi inscius,  et audi tacens simul et quærens. 

** Sirach 32:13

In medio magnatorum non præsumas :  et ubi sunt senes non multum loquaris. 

** Sirach 32:14

Ante grandinem præibit coruscatio :  et ante verecundiam præibit gratia,  et pro reverentia accedet tibi bona gratia. 

** Sirach 32:15

Et hora surgendi non te trices :  præcurre autem prior in domum tuam,  et illic avocare, et illic lude, 

** Sirach 32:16

et age conceptiones tuas,  et non in delictis et verbo superbo : 

** Sirach 32:17

et super his omnibus benedicito Dominum, qui fecit,  et inebriantem te ab omnibus bonis suis. 

** Sirach 32:18

Qui timet Dominum excipiet doctrinam ejus :  et qui vigilaverint ad illum invenient benedictionem. 

** Sirach 32:19

Qui quærit legem replebitur ab ea,  et qui insidiose agit scandalizabitur in ea. 

** Sirach 32:20

Qui timent Dominum invenient judicium justum,  et justitias quasi lumen accendent. 

** Sirach 32:21

Peccator homo vitabit correptionem,  et secundum voluntatem suam inveniet comparationem. 

** Sirach 32:22

Vir consilii non disperdet intelligentiam :  alienus et superbus non pertimescet timorem : 

** Sirach 32:23

etiam postquam fecit cum eo sine consilio,  et suis insectationibus arguetur. 

** Sirach 32:24

Fili, sine consilio nihil facias,  et post factum non pœnitebis. 

** Sirach 32:25

In via ruinæ non eas, et non offendes in lapides :  nec credas te viæ laboriosæ, ne ponas animæ tuæ scandalum. 

** Sirach 32:26

Et a filiis tuis cave,  et a domesticis tuis attende. 

** Sirach 32:27

In omni opere tuo crede ex fide animæ tuæ,  hoc est enim conservatio mandatorum. 

** Sirach 32:28

Qui credit Deo attendit mandatis :  et qui confidit in illo non minorabitur.  

* Sirach 33

** Sirach 33:1

Timenti Dominum non occurrent mala :  sed in tentatione Deus illum conservabit, et liberabit a malis.  Sapiens non odit mandata et justitias, 

** Sirach 33:2

et non illidetur quasi in procella navis. 

** Sirach 33:3

Homo sensatus credit legi Dei,  et lex illi fidelis. 

** Sirach 33:4

Qui interrogationem manifestat parabit verbum,  et sic deprecatus exaudietur :  et conservabit disciplinam, et tunc respondebit. 

** Sirach 33:5

Præcordia fatui quasi rota carri,  et quasi axis versatilis cogitatus illius. 

** Sirach 33:6

Equus emissarius, sic et amicus subsannator :  sub omni supra sedente hinnit. 

** Sirach 33:7

Quare dies diem superat, et iterum lux lucem,  et annus annum a sole ? 

** Sirach 33:8

A Domini scientia separati sunt,  facto sole, et præceptum custodiente. 

** Sirach 33:9

Et immutavit tempora, et dies festos ipsorum,  et in illis dies festos celebraverunt ad horam. 

** Sirach 33:10

Ex ipsis exaltavit et magnificavit Deus,  et ex ipsis posuit in numerum dierum :  et omnes homines de solo et ex terra unde creatus est Adam. 

** Sirach 33:11

In multitudine disciplinæ Dominus separavit eos,  et immutavit vias eorum. 

** Sirach 33:12

Ex ipsis benedixit et exaltavit,  et ex ipsis sanctificavit, et ad se applicavit,  et ex ipsis maledixit, et humiliavit,  et convertit illos a separatione ipsorum. 

** Sirach 33:13

Quasi lutum figuli in manu ipsius,  plasmare illud et disponere. 

** Sirach 33:14

Omnes viæ ejus secundum dispositionem ejus :  sic homo in manu illius qui se fecit,  et reddet illi secundum judicium suum. 

** Sirach 33:15

Contra malum bonum est, et contra mortem vita :  sic et contra virum justum peccator,  et sic intuere in omnia opera Altissimi,  duo et duo, et unum contra unum. 

** Sirach 33:16

Et ego novissimus evigilavi,  et quasi qui colligit acinos post vindemiatores. 

** Sirach 33:17

In benedictione Dei et ipse speravi,  et quasi qui vindemiat replevi torcular. 

** Sirach 33:18

Respicite quoniam non mihi soli laboravi,  sed omnibus exquirentibus disciplinam. 

** Sirach 33:19

Audite me, magnates et omnes populi :  et rectores ecclesiæ, auribus percipite. 

** Sirach 33:20

Filio et mulieri, fratri et amico,  non des potestatem super te in vita tua :  et non dederis alii possessionem tuam,  ne forte pœniteat te, et depreceris pro illis. 

** Sirach 33:21

Dum adhuc superes et aspiras,  non immutabit te omnis caro. 

** Sirach 33:22

Melius est enim ut filii tui te rogent,  quam te respicere in manus filiorum tuorum. 

** Sirach 33:23

In omnibus operibus tuis præcellens esto. 

** Sirach 33:24

Ne dederis maculam in gloria tua.  In die consummationis dierum vitæ tuæ, et in tempore exitus tui,  distribue hæreditatem tuam. 

** Sirach 33:25

Cibaria, et virga, et onus asino :  panis, et disciplina, et opus servo. 

** Sirach 33:26

Operatur in disciplina, et quærit requiescere :  laxa manus illi, et quærit libertatem. 

** Sirach 33:27

Jugum et lorum curvant collum durum,  et servum inclinant operationes assiduæ. 

** Sirach 33:28

Servo malevolo tortura et compedes :  mitte illum in operationem, ne vacet : 

** Sirach 33:29

multam enim malitiam docuit otiositas. 

** Sirach 33:30

In opera constitue eum :  sic enim condecet illum.  Quod si non obaudierit, curva illum compedibus,  et non amplifices super omnem carnem :  verum sine judicio nihil facias grave. 

** Sirach 33:31

Si est tibi servus fidelis, sit tibi quasi anima tua :  quasi fratrem sic eum tracta,  quoniam in sanguine animæ comparasti illum. 

** Sirach 33:32

Si læseris eum injuste,  in fugam convertetur : 

** Sirach 33:33

et si extollens discesserit,  quem quæras et in qua via quæras illum nescis.  

* Sirach 34

** Sirach 34:1

Vana spes et mendacium viro insensato :  et somnia extollunt imprudentes. 

** Sirach 34:2

Quasi qui apprehendit umbram et persequitur ventum,  sic et qui attendit ad visa mendacia. 

** Sirach 34:3

Hoc secundum hoc visio somniorum,  ante faciem hominis similitudo hominis. 

** Sirach 34:4

Ab immundo, quid mundabitur ?  et a mendace, quid verum dicetur ? 

** Sirach 34:5

Divinatio erroris, et auguria mendacia,  et somnia malefacientium, vanitas est : 

** Sirach 34:6

et sicut parturientis, cor tuum phantasias patitur.  Nisi ab Altissimo fuerit emissa visitatio,  ne dederis in illis cor tuum : 

** Sirach 34:7

multos enim errare fecerunt somnia,  et exciderunt sperantes in illis. 

** Sirach 34:8

Sine mendacio consummabitur verbum legis,  et sapientia in ore fidelis complanabitur. 

** Sirach 34:9

Qui non est tentatus quid scit ?  vir in multis expertus cogitabit multa :  et qui multa didicit enarrabit intellectum. 

** Sirach 34:10

Qui non est expertus pauca recognoscit :  qui autem in multis factus est, multiplicat malitiam. 

** Sirach 34:11

Qui tentatus non est qualia scit ?  qui implanatus est abundabit nequitia. 

** Sirach 34:12

Multa vidi errando,  et plurimas verborum consuetudines. 

** Sirach 34:13

Aliquoties usque ad mortem periclitatus sum horum causa,  et liberatus sum gratia Dei. 

** Sirach 34:14

Spiritus timentium Deum quæritur,  et in respectu illius benedicetur. 

** Sirach 34:15

Spes enim illorum in salvantem illos,  et oculi Dei in diligentes se. 

** Sirach 34:16

Qui timet Dominum nihil trepidabit :  et non pavebit, quoniam ipse est spes ejus. 

** Sirach 34:17

Timentis Dominum, beata est anima ejus. 

** Sirach 34:18

Ad quem respicit, et quis est fortitudo ejus ? 

** Sirach 34:19

Oculi Domini super timentes eum :  protector potentiæ, firmamentum virtutis,  tegimen ardoris, et umbraculum meridiani : 

** Sirach 34:20

deprecatio offensionis, et adjutorium casus :  exaltans animam, et illuminans oculos,  dans sanitatem, et vitam, et benedictionem. 

** Sirach 34:21

Immolantis ex iniquo oblatio est maculata,  et non sunt beneplacitæ subsannationes injustorum. 

** Sirach 34:22

Dominus solus sustinentibus se  in via veritatis et justitiæ. 

** Sirach 34:23

Dona iniquorum non probat Altissimus,  nec respicit in oblationes iniquorum,  nec in multitudine sacrificiorum eorum propitiabitur peccatis. 

** Sirach 34:24

Qui offert sacrificium ex substantia pauperum,  quasi qui victimat filium in conspectu patris sui. 

** Sirach 34:25

Panis egentium vita pauperum est :  qui defraudat illum homo sanguinis est. 

** Sirach 34:26

Qui aufert in sudore panem,  quasi qui occidit proximum suum. 

** Sirach 34:27

Qui effundit sanguinem,  et qui fraudem facit mercenario, fratres sunt. 

** Sirach 34:28

Unus ædificans, et unus destruens :  quid prodest illis, nisi labor ? 

** Sirach 34:29

Unus orans, et unus maledicens :  cujus vocem exaudiet Deus ? 

** Sirach 34:30

Qui baptizatur a mortuo, et iterum tangit eum,  quid proficit lavatio illius ? 

** Sirach 34:31

Sic homo qui jejunat in peccatis suis,  et iterum eadem faciens :  quid proficit humiliando se ?  orationem illius quis exaudiet ?  

* Sirach 35

** Sirach 35:1

Qui conservat legem  multiplicat oblationem. 

** Sirach 35:2

Sacrificium salutare est attendere mandatis,  et discedere ab omni iniquitate. 

** Sirach 35:3

Et propitiationem litare sacrificii super injustitias :  et deprecatio pro peccatis, recedere ab injustitia. 

** Sirach 35:4

Retribuet gratiam qui offert similaginem :  et qui facit misericordiam offert sacrificium. 

** Sirach 35:5

Beneplacitum est Domino recedere ab iniquitate :  et deprecatio pro peccatis recedere ab injustitia. 

** Sirach 35:6

Non apparebis ante conspectum Domini vacuus : 

** Sirach 35:7

hæc enim omnia propter mandatum Dei fiunt. 

** Sirach 35:8

Oblatio justi impinguat altare,  et odor suavitatis est in conspectu Altissimi. 

** Sirach 35:9

Sacrificium justi acceptum est,  et memoriam ejus non obliviscetur Dominus. 

** Sirach 35:10

Bono animo gloriam redde Deo,  et non minuas primitias manuum tuarum. 

** Sirach 35:11

In omni dato hilarem fac vultum tuum,  et in exsultatione sanctifica decimas tuas. 

** Sirach 35:12

Da Altissimo secundum datum ejus,  et in bono oculo adinventionem facito manuum tuarum, 

** Sirach 35:13

quoniam Dominus retribuens est,  et septies tantum reddet tibi. 

** Sirach 35:14

Noli offerre munera prava,  non enim suscipiet illa. 

** Sirach 35:15

Et noli inspicere sacrificum injustum,  quoniam Dominus judex est,  et non est apud illum gloria personæ. 

** Sirach 35:16

Non accipiet Dominus personam in pauperem,  et deprecationem læsi exaudiet. 

** Sirach 35:17

Non despiciet preces pupilli,  nec viduam, si effundat loquelam gemitus. 

** Sirach 35:18

Nonne lacrimæ viduæ ad maxillam descendunt,  et exclamatio ejus super deducentem eas ? 

** Sirach 35:19

A maxilla enim ascendunt usque ad cælum,  et Dominus exauditor non delectabitur in illis. 

** Sirach 35:20

Qui adorat Deum in oblectatione suscipietur,  et deprecatio illius usque ad nubes propinquabit. 

** Sirach 35:21

Oratio humiliantis se nubes penetrabit,  et donec propinquet non consolabitur,  et non discedet donec Altissimus aspiciat. 

** Sirach 35:22

Et Dominus non elongabit :  et judicabit justos, et faciet judicium :  et Fortissimus non habebit in illis patientiam,  ut contribulet dorsum ipsorum : 

** Sirach 35:23

et gentibus reddet vindictam,  donec tollat plenitudinem superborum,  et sceptra iniquorum contribulet : 

** Sirach 35:24

donec reddat hominibus secundum actus suos,  et secundum opera Adæ, et secundum præsumptionem illius : 

** Sirach 35:25

donec judicet judicium plebis suæ,  et oblectabit justos misericordia sua. 

** Sirach 35:26

Speciosa misericordia Dei in tempore tribulationis,  quasi nubes pluviæ in tempore siccitatis.  

* Sirach 36

** Sirach 36:1

Miserere nostri, Deus omnium, et respice nos,  et ostende nobis lucem miserationum tuarum : 

** Sirach 36:2

et immitte timorem tuum super gentes quæ non exquisierunt te,  ut cognoscant quia non est deus nisi tu,  et enarrent magnalia tua. 

** Sirach 36:3

Alleva manum tuam super gentes alienas,  ut videant potentiam tuam. 

** Sirach 36:4

Sicut enim in conspectu eorum sanctificatus es in nobis,  sic in conspectu nostro magnificaberis in eis : 

** Sirach 36:5

ut cognoscant te, sicut et nos cognovimus  quoniam non est deus præter te, Domine. 

** Sirach 36:6

Innova signa, et immuta mirabilia. 

** Sirach 36:7

Glorifica manum et brachium dextrum. 

** Sirach 36:8

Excita furorem, et effunde iram. 

** Sirach 36:9

Tolle adversarium, et afflige inimicum. 

** Sirach 36:10

Festina tempus, et memento finis,  ut enarrent mirabilia tua. 

** Sirach 36:11

In ira flammæ devoretur qui salvatur :  et qui pessimant plebem tuam inveniant perditionem. 

** Sirach 36:12

Contere caput principum inimicorum,  dicentium : Non est alius præter nos. 

** Sirach 36:13

Congrega omnes tribus Jacob,  ut cognoscant quia non est deus nisi tu,  et enarrent magnalia tua,  et hæreditabis eos sicut ab initio. 

** Sirach 36:14

Miserere plebi tuæ, super quam invocatum est nomen tuum,  et Israël quem coæquasti primogenito tuo. 

** Sirach 36:15

Miserere civitati sanctificationis tuæ,  Jerusalem, civitati requiei tuæ. 

** Sirach 36:16

Reple Sion inenarrabilibus verbis tuis,  et gloria tua populum tuum. 

** Sirach 36:17

Da testimonium his qui ab initio creaturæ tuæ sunt,  et suscita prædicationes quas locuti sunt in nomine tuo prophetæ priores. 

** Sirach 36:18

Da mercedem sustinentibus te,  ut prophetæ tui fideles inveniantur :  et exaudi orationes servorum tuorum, 

** Sirach 36:19

secundum benedictionem Aaron de populo tuo :  et dirige nos in viam justitiæ,  et sciant omnes qui habitant terram  quia tu es Deus conspector sæculorum. 

** Sirach 36:20

Omnem escam manducabit venter :  et est cibus cibo melior. 

** Sirach 36:21

Fauces contingunt cibum feræ,  et cor sensatum verba mendacia. 

** Sirach 36:22

Cor pravum dabit tristitiam,  et homo peritus resistet illi. 

** Sirach 36:23

Omnem masculum excipiet mulier :  et est filia melior filia. 

** Sirach 36:24

Species mulieris exhilarat faciem viri sui,  et super omnem concupiscentiam hominis superducit desiderium. 

** Sirach 36:25

Si est lingua curationis,  est et mitigationis et misericordiæ :  non est vir illius secundum filios hominum. 

** Sirach 36:26

Qui possidet mulierem bonam inchoat possessionem :  adjutorium secundum illum est, et columna ut requies. 

** Sirach 36:27

Ubi non est sepes, diripietur possessio :  et ubi non est mulier, ingemiscit egens. 

** Sirach 36:28

Quis credit ei qui non habet nidum,  et deflectens ubicumque obscuraverit,  quasi succinctus latro exiliens de civitate in civitatem ?  

* Sirach 37

** Sirach 37:1

Omnis amicus dicet : Et ego amicitiam copulavi :  sed est amicus solo nomine amicus.  Nonne tristitia inest usque ad mortem ? 

** Sirach 37:2

sodalis autem et amicus ad inimicitiam convertentur. 

** Sirach 37:3

O præsumptio nequissima, unde creata es  cooperire aridam malitia et dolositate illius ? 

** Sirach 37:4

Sodalis amico conjucundatur in oblectationibus,  et in tempore tribulationis adversarius erit. 

** Sirach 37:5

Sodalis amico condolet causa ventris,  et contra hostem accipiet scutum. 

** Sirach 37:6

Non obliviscaris amici tui in animo tuo,  et non immemor sis illius in opibus tuis. 

** Sirach 37:7

Noli consiliari cum eo qui tibi insidiatur,  et a zelantibus te absconde consilium. 

** Sirach 37:8

Omnis consiliarius prodit consilium,  sed est consiliarius in semetipso. 

** Sirach 37:9

A consiliario serva animam tuam :  prius scito quæ sit illius necessitas :  et ipse enim animo suo cogitabit : 

** Sirach 37:10

ne forte mittat sudem in terram,  et dicat tibi : 

** Sirach 37:11

Bona est via tua :  et stet e contrario videre quid tibi eveniat. 

** Sirach 37:12

Cum viro irreligioso tracta de sanctitate,  et cum injusto de justitia,  et cum muliere de ea quæ æmulatur,  cum timido de bello,  cum negotiatore de trajectione,  cum emptore de venditione,  cum viro livido de gratiis agendis, 

** Sirach 37:13

cum impio de pietate,  cum inhonesto de honestate,  cum operario agrario de omni opere, 

** Sirach 37:14

cum operario annuali de consummatione anni,  cum servo pigro de multa operatione.  Non attendas his in omni consilio : 

** Sirach 37:15

sed cum viro sancto assiduus esto,  quemcumque cognoveris observantem timorem Dei : 

** Sirach 37:16

cujus anima est secundum animam tuam,  et qui, cum titubaveris in tenebris, condolebit tibi. 

** Sirach 37:17

Cor boni consilii statue tecum :  non est enim tibi aliud pluris illo. 

** Sirach 37:18

Anima viri sancti enuntiat aliquando vera,  quam septem circumspectores sedentes in excelso ad speculandum. 

** Sirach 37:19

Et in his omnibus deprecare Altissimum,  ut dirigat in veritate viam tuam. 

** Sirach 37:20

Ante omnia opera verbum verax præcedat te,  et ante omnem actum consilium stabile. 

** Sirach 37:21

Verbum nequam immutabit cor :  ex quo partes quatuor oriuntur :  bonum et malum, vita et mors :  et dominatrix illorum est assidua lingua.  Est vir astutus multorum eruditor,  et animæ suæ inutilis est. 

** Sirach 37:22

Vir peritus multos erudivit,  et animæ suæ suavis est. 

** Sirach 37:23

Qui sophistice loquitur odibilis est :  in omni re defraudabitur. 

** Sirach 37:24

Non est illi data a Domino gratia,  omni enim sapientia defraudatus est. 

** Sirach 37:25

Est sapiens animæ suæ sapiens,  et fructus sensus illius laudabilis. 

** Sirach 37:26

Vir sapiens plebem suam erudit,  et fructus sensus illius fideles sunt. 

** Sirach 37:27

Vir sapiens implebitur benedictionibus,  et videntes illum laudabunt. 

** Sirach 37:28

Vita viri in numero dierum :  dies autem Israël innumerabiles sunt. 

** Sirach 37:29

Sapiens in populo hæreditabit honorem,  et nomen illius erit vivens in æternum. 

** Sirach 37:30

Fili, in vita tua tenta animam tuam,  et si fuerit nequam non des illi potestatem : 

** Sirach 37:31

non enim omnia omnibus expediunt,  et non omni animæ omne genus placet. 

** Sirach 37:32

Noli avidus esse in omni epulatione,  et non te effundas super omnem escam : 

** Sirach 37:33

in multis enim escis erit infirmitas,  et aviditas appropinquabit usque ad choleram. 

** Sirach 37:34

Propter crapulam multi obierunt :  qui autem abstinens est adjiciet vitam.  

* Sirach 38

** Sirach 38:1

Honora medicum propter necessitatem :  etenim illum creavit Altissimus. 

** Sirach 38:2

A Deo est enim omnis medela,  et a rege accipiet donationem. 

** Sirach 38:3

Disciplina medici exaltabit caput illius,  et in conspectu magnatorum collaudabitur. 

** Sirach 38:4

Altissimus creavit de terra medicamenta,  et vir prudens non abhorrebit illa. 

** Sirach 38:5

Nonne a ligno indulcata est aqua amara ? 

** Sirach 38:6

Ad agnitionem hominum virtus illorum :  et dedit hominibus scientiam Altissimus,  honorari in mirabilibus suis. 

** Sirach 38:7

In his curans mitigabit dolorem :  et unguentarius faciet pigmenta suavitatis,  et unctiones conficiet sanitatis :  et non consummabuntur opera ejus. 

** Sirach 38:8

Pax enim Dei super faciem terræ. 

** Sirach 38:9

Fili, in tua infirmitate ne despicias teipsum :  sed ora Dominum, et ipse curabit te. 

** Sirach 38:10

Averte a delicto, et dirige manus,  et ab omni delicto munda cor tuum. 

** Sirach 38:11

Da suavitatem et memoriam similaginis,  et impingua oblationem, et da locum medico : 

** Sirach 38:12

etenim illum Dominus creavit, et non discedat a te,  quia opera ejus sunt necessaria. 

** Sirach 38:13

Est enim tempus quando in manus illorum incurras : 

** Sirach 38:14

ipsi vero Dominum deprecabuntur, ut dirigat requiem eorum,  et sanitatem, propter conversationem illorum. 

** Sirach 38:15

Qui delinquit in conspectu ejus qui fecit eum,  incidet in manus medici. 

** Sirach 38:16

Fili, in mortuum produc lacrimas,  et quasi dira passus incipe plorare :  et secundum judicium contege corpus illius,  et non despicias sepulturam illius. 

** Sirach 38:17

Propter delaturam autem amare fer luctum illius uno die,  et consolare propter tristitiam : 

** Sirach 38:18

et fac luctum secundum meritum ejus  uno die, vel duobus, propter detractionem : 

** Sirach 38:19

a tristitia enim festinat mors, et cooperit virtutem,  et tristitia cordis flectit cervicem. 

** Sirach 38:20

In abductione permanet tristitia,  et substantia inopis secundum cor ejus. 

** Sirach 38:21

Ne dederis in tristitia cor tuum,  sed repelle eam a te, et memento novissimorum. 

** Sirach 38:22

Noli oblivisci, neque enim est conversio :  et huic nihil proderis, et teipsum pessimabis. 

** Sirach 38:23

Memor esto judicii mei : sic enim erit et tuum :  mihi heri, et tibi hodie. 

** Sirach 38:24

In requie mortui requiescere fac memoriam ejus,  et consolare illum in exitu spiritus sui. 

** Sirach 38:25

Sapientia scribæ in tempore vacuitatis,  et qui minoratur actu sapientiam percipiet,  qua sapientia replebitur. 

** Sirach 38:26

Qui tenet aratrum,  et qui gloriatur in jaculo, stimulo boves agitat,  et conversatur in operibus eorum,  et enarratio ejus in filiis taurorum. 

** Sirach 38:27

Cor suum dabit ad versandos sulcos,  et vigilia ejus in sagina vaccarum. 

** Sirach 38:28

Sic omnis faber et architectus,  qui noctem tamquam diem transigit :  qui sculpit signacula sculptilia,  et assiduitas ejus variat picturam :  cor suum dabit in similitudinem picturæ,  et vigilia sua perficiet opus. 

** Sirach 38:29

Sic faber ferrarius sedens juxta incudem,  et considerans opus ferri :  vapor ignis uret carnes ejus,  et in calore fornacis concertatur. 

** Sirach 38:30

Vox mallei innovat aurem ejus,  et contra similitudinem vasis oculus ejus. 

** Sirach 38:31

Cor suum dabit in consummationem operum,  et vigilia sua ornabit in perfectionem. 

** Sirach 38:32

Sic figulus sedens ad opus suum,  convertens pedibus suis rotam,  qui in sollicitudine positus est semper propter opus suum,  et in numero est omnis operatio ejus. 

** Sirach 38:33

In brachio suo formabit lutum,  et ante pedes suos curvabit virtutem suam. 

** Sirach 38:34

Cor suum dabit ut consummet linitionem,  et vigilia sua mundabit fornacem. 

** Sirach 38:35

Omnes hi in manibus suis speraverunt,  et unusquisque in arte sua sapiens est. 

** Sirach 38:36

Sine his omnibus non ædificatur civitas, 

** Sirach 38:37

et non inhabitabunt, nec inambulabunt,  et in ecclesiam non transilient. 

** Sirach 38:38

Super sellam judicis non sedebunt,  et testamentum judicii non intelligent,  neque palam facient disciplinam et judicium,  et in parabolis non invenientur : 

** Sirach 38:39

sed creaturam ævi confirmabunt :  et deprecatio illorum in operatione artis,  accomodantes animam suam,  et conquirentes in lege Altissimi.  

* Sirach 39

** Sirach 39:1

Sapientiam omnium antiquorum exquiret sapiens,  et in prophetis vacabit. 

** Sirach 39:2

Narrationem virorum nominatorum conservabit,  et in versutias parabolarum simul introibit. 

** Sirach 39:3

Occulta proverbiorum exquiret,  et in absconditis parabolarum conversabitur. 

** Sirach 39:4

In medio magnatorum ministrabit,  et in conspectu præsidis apparebit. 

** Sirach 39:5

In terram alienigenarum gentium pertransiet :  bona enim et mala in hominibus tentabit. 

** Sirach 39:6

Cor suum tradet ad vigilandum diluculo ad Dominum, qui fecit illum,  et in conspectu Altissimi deprecabitur. 

** Sirach 39:7

Aperiet os suum in oratione,  et pro delictis suis deprecabitur. 

** Sirach 39:8

Si enim Dominus magnus voluerit,  spiritu intelligentiæ replebit illum : 

** Sirach 39:9

et ipse tamquam imbres mittet eloquia sapientiæ suæ,  et in oratione confitebitur Domino : 

** Sirach 39:10

et ipse diriget consilium ejus, et disciplinam,  et in absconditis suis consiliabitur. 

** Sirach 39:11

Ipse palam faciet disciplinam doctrinæ suæ,  et in lege testamenti Domini gloriabitur. 

** Sirach 39:12

Collaudabunt multi sapientiam ejus,  et usque in sæculum non delebitur. 

** Sirach 39:13

Non recedet memoria ejus,  et nomen ejus requiretur a generatione in generationem. 

** Sirach 39:14

Sapientiam ejus enarrabunt gentes,  et laudem ejus enuntiabit ecclesia. 

** Sirach 39:15

Si permanserit, nomen derelinquet plus quam mille :  et si requieverit, proderit illi. 

** Sirach 39:16

Adhuc consiliabor ut enarrem :  ut furore enim repletus sum. 

** Sirach 39:17

In voce dicit : Obaudite me, divini fructus,  et quasi rosa plantata super rivos aquarum fructificate. 

** Sirach 39:18

Quasi Libanus odorem suavitatis habete. 

** Sirach 39:19

Florete flores quasi lilium :  et date odorem, et frondete in gratiam :  et collaudate canticum, et benedicite Dominum in operibus suis. 

** Sirach 39:20

Date nomini ejus magnificentiam,  et confitemini illi in voce labiorum vestrorum,  et in canticis labiorum, et citharis :  et sic dicetis in confessione : 

** Sirach 39:21

Opera Domini universa bona valde. 

** Sirach 39:22

In verbo ejus stetit aqua sicut congeries :  et in sermone oris illius sicut exceptoria aquarum : 

** Sirach 39:23

quoniam in præcepto ipsius placor fit,  et non est minoratio in salute ipsius. 

** Sirach 39:24

Opera omnis carnis coram illo,  et non est quidquam absconditum ab oculis ejus. 

** Sirach 39:25

A sæculo usque in sæculum respicit,  et nihil est mirabile in conspectu ejus. 

** Sirach 39:26

Non est dicere : Quid est hoc, aut quid est istud ?  omnia enim in tempore suo quærentur. 

** Sirach 39:27

Benedictio illius quasi fluvius inundavit. 

** Sirach 39:28

Quomodo cataclysmus aridam inebriavit,  sic ira ipsius gentes quæ non exquisierunt eum hæreditabit. 

** Sirach 39:29

Quomodo convertit aquas in siccitatem, et siccata est terra,  et viæ illius viis illorum directæ sunt,  sic peccatoribus offensiones in ira ejus. 

** Sirach 39:30

Bona bonis creata sunt ab initio :  sic nequissimis bona et mala. 

** Sirach 39:31

Initium necessariæ rei vitæ hominum, aqua, ignis, et ferrum,  sal, lac, et panis similagineus, et mel,  et botrus uvæ, et oleum, et vestimentum. 

** Sirach 39:32

Hæc omnia sanctis in bona,  sic et impiis et peccatoribus in mala convertentur. 

** Sirach 39:33

Sunt spiritus qui ad vindictam creati sunt,  et in furore suo confirmaverunt tormenta sua. 

** Sirach 39:34

In tempore consummationis effundent virtutem,  et furorem ejus qui fecit illos placabunt. 

** Sirach 39:35

Ignis, grando, fames, et mors,  omnia hæc ad vindictam creata sunt : 

** Sirach 39:36

bestiarum dentes, et scorpii, et serpentes,  et rhomphæa vindicans in exterminium impios. 

** Sirach 39:37

In mandatis ejus epulabuntur :  et super terram in necessitatem præparabuntur,  et in temporibus suis non præterient verbum. 

** Sirach 39:38

Propterea ab initio confirmatus sum, et consiliatus sum,  et cogitavi, et scripta dimisi. 

** Sirach 39:39

Omnia opera Domini bona,  et omne opus hora sua subministrabit. 

** Sirach 39:40

Non est dicere : Hoc illo nequius est :  omnia enim in tempore suo comprobabuntur. 

** Sirach 39:41

Et nunc in omni corde et ore collaudate,  et benedicite nomen Domini.  

* Sirach 40

** Sirach 40:1

Occupatio magna creata est omnibus hominibus,  et jugum grave super filios Adam,  a die exitus de ventre matris eorum  usque in diem sepulturæ in matrem omnium. 

** Sirach 40:2

Cogitationes eorum, et timores cordis,  adinventio exspectationis, et dies finitionis, 

** Sirach 40:3

a residente super sedem gloriosam,  usque ad humiliatum in terra et cinere : 

** Sirach 40:4

ab eo qui utitur hyacintho et portat coronam,  usque ad eum qui operitur lino crudo :  furor, zelus, tumultus, fluctuatio, et timor mortis,  iracundia perseverans, et contentio : 

** Sirach 40:5

et in tempore refectionis in cubili,  somnus noctis immutat scientiam ejus. 

** Sirach 40:6

Modicum tamquam nihil in requie,  et ab eo in somnis, quasi in die respectus. 

** Sirach 40:7

Conturbatus est in visu cordis sui,  tamquam qui evaserit in die belli :  in tempore salutis suæ exsurrexit,  et admirans ad nullum timorem : 

** Sirach 40:8

cum omni carne, ab homine usque ad pecus,  et super peccatores septuplum. 

** Sirach 40:9

Ad hæc mors, sanguis, contentio, et rhomphæa,  oppressiones, fames, et contritio, et flagella : 

** Sirach 40:10

super iniquos creata sunt hæc omnia :  et propter illos factus est cataclysmus. 

** Sirach 40:11

Omnia quæ de terra sunt in terram convertentur,  et omnes aquæ in mare revertentur. 

** Sirach 40:12

Omne munus et iniquitas delebitur,  et fides in sæculum stabit. 

** Sirach 40:13

Substantiæ injustorum sicut fluvius siccabuntur,  et sicut tonitruum magnum in pluvia personabunt. 

** Sirach 40:14

In aperiendo manus suas lætabitur :  sic prævaricatores in consummatione tabescent. 

** Sirach 40:15

Nepotes impiorum non multiplicabunt ramos :  et radices immundæ super cacumen petræ sonant. 

** Sirach 40:16

Super omnem aquam viriditas,  et ad oram fluminis ante omne fœnum evelletur. 

** Sirach 40:17

Gratia sicut paradisus in benedictionibus,  et misericordia in sæculum permanet. 

** Sirach 40:18

Vita sibi sufficientis operarii condulcabitur,  et in ea invenies thesaurum. 

** Sirach 40:19

Filii et ædificatio civitatis confirmabit nomen :  et super hæc mulier immaculata computabitur. 

** Sirach 40:20

Vinum et musica lætificant cor :  et super utraque dilectio sapientiæ. 

** Sirach 40:21

Tibiæ et psalterium suavem faciunt melodiam :  et super utraque lingua suavis. 

** Sirach 40:22

Gratiam et speciem desiderabit oculus tuus :  et super hæc virides sationes. 

** Sirach 40:23

Amicus et sodalis in tempore convenientes,  et super utrosque mulier cum viro. 

** Sirach 40:24

Fratres in adjutorium in tempore tribulationis :  et super eos misericordia liberabit. 

** Sirach 40:25

Aurum et argentum est constitutio pedum :  et super utrumque consilium beneplacitum. 

** Sirach 40:26

Facultates et virtutes exaltant cor,  et super hæc timor Domini. 

** Sirach 40:27

Non est in timore Domini minoratio :  et non est in eo inquirere adjutorium. 

** Sirach 40:28

Timor Domini sicut paradisus benedictionis,  et super omnem gloriam operuerunt illum. 

** Sirach 40:29

Fili, in tempore vitæ tuæ ne indigeas :  melius est enim mori quam indigere. 

** Sirach 40:30

Vir respiciens in mensam alienam,  non est vita ejus in cogitatione victus :  alit enim animam suam cibis alienis : 

** Sirach 40:31

vir autem disciplinatus et eruditus custodiet se. 

** Sirach 40:32

In ore imprudentis condulcabitur inopia,  et in ventre ejus ignis ardebit.  

* Sirach 41

** Sirach 41:1

O mors, quam amara est memoria tua  homini pacem habenti in substantiis suis : 

** Sirach 41:2

viro quieto, et cujus viæ directæ sunt in omnibus,  et adhuc valenti accipere cibum ! 

** Sirach 41:3

O mors, bonum est judicium tuum homini indigenti,  et qui minoratur viribus, 

** Sirach 41:4

defecto ætate, et cui de omnibus cura est,  et incredibili, qui perdit patientiam ! 

** Sirach 41:5

Noli metuere judicium mortis :  memento quæ ante te fuerunt,  et quæ superventura sunt tibi :  hoc judicium a Domino omni carni. 

** Sirach 41:6

Et quid superveniet tibi in beneplacito Altissimi ?  sive decem, sive centum, sive mille anni : 

** Sirach 41:7

non est enim in inferno accusatio vitæ. 

** Sirach 41:8

Filii abominationum fiunt filii peccatorum,  et qui conversantur secus domos impiorum. 

** Sirach 41:9

Filiorum peccatorum periet hæreditas,  et cum semine illorum assiduitas opprobrii. 

** Sirach 41:10

De patre impio queruntur filii,  quoniam propter illum sunt in opprobrio. 

** Sirach 41:11

Væ vobis, viri impii,  qui dereliquistis legem Domini Altissimi ! 

** Sirach 41:12

Et si nati fueritis, in maledictione nascemini :  et si mortui fueritis, in maledictione erit pars vestra. 

** Sirach 41:13

Omnia quæ de terra sunt in terram convertentur :  sic impii a maledicto in perditionem. 

** Sirach 41:14

Luctus hominum in corpore ipsorum :  nomen autem impiorum delebitur. 

** Sirach 41:15

Curam habe de bono nomine :  hoc enim magis permanebit tibi  quam mille thesauri pretiosi et magni. 

** Sirach 41:16

Bonæ vitæ numerus dierum :  bonum autem nomen permanebit in ævum. 

** Sirach 41:17

Disciplinam in pace conservate, filii :  sapientia enim abscondita, et thesaurus invisus,  quæ utilitas in utrisque ? 

** Sirach 41:18

Melior est homo qui abscondit stultitiam suam,  quam homo qui abscondit sapientiam suam. 

** Sirach 41:19

Verumtamen reveremini in his quæ procedunt de ore meo : 

** Sirach 41:20

non est enim bonum omnem reverentiam observare,  et non omnia omnibus bene placent in fide. 

** Sirach 41:21

Erubescite a patre et a matre de fornicatione :  et a præsidente et a potente de mendacio : 

** Sirach 41:22

a principe et a judice de delicto :  a synagoga et plebe de iniquitate : 

** Sirach 41:23

a socio et amico de injustitia,  et de loco in quo habitas : 

** Sirach 41:24

de furto, de veritate Dei, et testamento :  de discubitu in panibus, et ab obfuscatione dati et accepti : 

** Sirach 41:25

a salutantibus de silentio,  a respectu mulieris fornicariæ,  et ab aversione vultus cognati. 

** Sirach 41:26

Ne avertas faciem a proximo tuo,  et ab auferendo partem et non restituendo. 

** Sirach 41:27

Ne respicias mulierem alieni viri,  et ne scruteris ancillam ejus,  neque steteris ad lectum ejus. 

** Sirach 41:28

Ab amicis de sermonibus improperii :  et cum dederis, ne improperes.  

* Sirach 42

** Sirach 42:1

Non duplices sermonem auditus de revelatione sermonis absconditi :  et eris vere sine confusione,  et invenies gratiam in conspectu omnium hominum.  Ne pro his omnibus confundaris,  et ne accipias personam ut delinquas : 

** Sirach 42:2

de lege Altissimi, et testamento,  et de judicio justificare impium, 

** Sirach 42:3

de verbo sociorum et viatorum,  et de datione hæreditatis amicorum, 

** Sirach 42:4

de æqualitate stateræ et ponderum,  de acquisitione multorum et paucorum, 

** Sirach 42:5

de corruptione emptionis et negotiatorum,  et de multa disciplina filiorum,  et servo pessimo latus sanguinare. 

** Sirach 42:6

Super mulierem nequam bonum est signum. 

** Sirach 42:7

Ubi manus multæ sunt, claude :  et quodcumque trades, numera et appende :  datum vero et acceptum omne describe. 

** Sirach 42:8

De disciplina insensati et fatui,  et de senioribus qui judicantur ab adolescentibus :  et eris eruditus in omnibus,  et probabilis in conspectu omnium vivorum. 

** Sirach 42:9

Filia patris abscondita est vigilia,  et sollicitudo ejus aufert somnum :  ne forte in adolescentia sua adulta efficiatur,  et cum viro commorata odibilis fiat : 

** Sirach 42:10

nequando polluatur in virginitate sua,  et in paternis suis gravida inveniatur :  ne forte cum viro commorata transgrediatur,  aut certe sterilis efficiatur. 

** Sirach 42:11

Super filiam luxuriosam confirma custodiam,  nequando faciat te in opprobrium venire inimicis,  a detractione in civitate, et objectione plebis,  et confundat te in multitudine populi. 

** Sirach 42:12

Omni homini noli intendere in specie,  et in medio mulierum noli commorari : 

** Sirach 42:13

de vestimentis enim procedit tinea,  et a muliere iniquitas viri. 

** Sirach 42:14

Melior est enim iniquitas viri quam mulier benefaciens,  et mulier confundens in opprobrium. 

** Sirach 42:15

Memor ero igitur operum Domini,  et quæ vidi annuntiabo.  In sermonibus Domini opera ejus. 

** Sirach 42:16

Sol illuminans per omnia respexit,  et gloria Domini plenum est opus ejus. 

** Sirach 42:17

Nonne Dominus fecit sanctos enarrare omnia mirabilia sua,  quæ confirmavit Dominus omnipotens stabiliri in gloria sua ? 

** Sirach 42:18

Abyssum et cor hominum investigavit,  et in astutia eorum excogitavit. 

** Sirach 42:19

Cognovit enim Dominus omnem scientiam,  et inspexit in signum ævi,  annuntians quæ præterierunt et quæ superventura sunt,  revelans vestigia occultorum. 

** Sirach 42:20

Non præterit illum omnis cogitatus,  et non abscondit se ab eo ullus sermo. 

** Sirach 42:21

Magnalia sapientiæ suæ decoravit,  qui est ante sæculum et usque in sæculum :  neque adjectum est, 

** Sirach 42:22

neque minuitur,  et non eget alicujus consilio. 

** Sirach 42:23

Quam desiderabilia omnia opera ejus !  et tamquam scintilla quæ est considerare ! 

** Sirach 42:24

Omnia hæc vivunt, et manent in sæculum,  et in omni necessitate omnia obaudiunt ei. 

** Sirach 42:25

Omnia duplicia, unum contra unum,  et non fecit quidquam deesse. 

** Sirach 42:26

Uniuscujusque confirmavit bona :  et quis satiabitur videns gloriam ejus ?  

* Sirach 43

** Sirach 43:1

Altitudinis firmamentum pulchritudo ejus est,  species cæli in visione gloriæ. 

** Sirach 43:2

Sol in aspectu annuntians in exitu,  vas admirabile, opus Excelsi. 

** Sirach 43:3

In meridiano exurit terram,  et in conspectu ardoris ejus quis poterit sustinere ?  fornacem custodiens in operibus ardoris : 

** Sirach 43:4

tripliciter sol exurens montes,  radios igneos exsufflans,  et refulgens radiis suis obcæcat oculos. 

** Sirach 43:5

Magnus Dominus qui fecit illum,  et in sermonibus ejus festinavit iter. 

** Sirach 43:6

Et luna in omnibus in tempore suo,  ostensio temporis, et signum ævi. 

** Sirach 43:7

A luna signum diei festi :  luminare quod minuitur in consummatione. 

** Sirach 43:8

Mensis secundum nomen ejus est,  crescens mirabiliter in consummatione. 

** Sirach 43:9

Vas castrorum in excelsis,  in firmamento cæli resplendens gloriose. 

** Sirach 43:10

Species cæli gloria stellarum :  mundum illuminans in excelsis Dominus. 

** Sirach 43:11

In verbis Sancti stabunt ad judicium,  et non deficient in vigiliis suis. 

** Sirach 43:12

Vide arcum, et benedic eum qui fecit illum :  valde speciosus est in splendore suo. 

** Sirach 43:13

Gyravit cælum in circuitu gloriæ suæ :  manus Excelsi aperuerunt illum. 

** Sirach 43:14

Imperio suo acceleravit nivem,  et accelerat coruscationes emittere judicii sui. 

** Sirach 43:15

Propterea aperti sunt thesauri,  et evolaverunt nebulæ sicut aves. 

** Sirach 43:16

In magnitudine sua posuit nubes,  et confracti sunt lapides grandinis. 

** Sirach 43:17

In conspectu ejus commovebuntur montes,  et in voluntate ejus aspirabit notus. 

** Sirach 43:18

Vox tonitrui ejus verberavit terram,  tempestas aquilonis, et congregatio spiritus : 

** Sirach 43:19

et sicut avis deponens ad sedendum, aspergit nivem,  et sicut locusta demergens descensus ejus. 

** Sirach 43:20

Pulchritudinem candoris ejus admirabitur oculus,  et super imbrem ejus expavescet cor. 

** Sirach 43:21

Gelu sicut salem effundet super terram :  et dum gelaverit, fiet tamquam cacumina tribuli. 

** Sirach 43:22

Frigidus ventus aquilo flavit,  et gelavit crystallus ab aqua :  super omnem congregationem aquarum requiescet,  et sicut lorica induet se aquis : 

** Sirach 43:23

et devorabit montes, et exuret desertum,  et extinguet viride, sicut igne. 

** Sirach 43:24

Medicina omnium in festinatione nebulæ :  et ros obvians ab ardore venienti humilem efficiet eum. 

** Sirach 43:25

In sermone ejus siluit ventus,  et cogitatione sua placavit abyssum :  et plantavit in illa Dominus insulas. 

** Sirach 43:26

Qui navigant mare enarrent pericula ejus,  et audientes auribus nostris admirabimur. 

** Sirach 43:27

Illic præclara opera et mirabilia,  varia bestiarum genera, et omnium pecorum, et creatura belluarum. 

** Sirach 43:28

Propter ipsum confirmatus est itineris finis,  et in sermone ejus composita sunt omnia. 

** Sirach 43:29

Multa dicemus, et deficiemus in verbis :  consummatio autem sermonum ipse est in omnibus. 

** Sirach 43:30

Gloriantes ad quid valebimus ?  ipse enim omnipotens super omnia opera sua. 

** Sirach 43:31

Terribilis Dominus, et magnus vehementer,  et mirabilis potentia ipsius. 

** Sirach 43:32

Glorificantes Dominum quantumcumque potueritis,  supervalebit enim adhuc : et admirabilis magnificentia ejus. 

** Sirach 43:33

Benedicentes Dominum, exaltate illum quantum potestis :  major enim est omni laude. 

** Sirach 43:34

Exaltantes eum, replemini virtute, ne laboretis,  non enim comprehendetis. 

** Sirach 43:35

Quis videbit eum et enarrabit ?  et quis magnificabit eum sicut est ab initio ? 

** Sirach 43:36

Multa abscondita sunt majora his :  pauca enim vidimus operum ejus. 

** Sirach 43:37

Omnia autem Dominus fecit,  et pie agentibus dedit sapientiam.  

* Sirach 44

** Sirach 44:1

Laudemus viros gloriosos,  et parentes nostros in generatione sua. 

** Sirach 44:2

Multam gloriam fecit Dominus :  magnificentia sua a sæculo. 

** Sirach 44:3

Dominantes in potestatibus suis,  homines magni virtute et prudentia sua præditi,  nuntiantes in prophetis dignitatem prophetarum : 

** Sirach 44:4

et imperantes in præsenti populo,  et virtute prudentiæ populis sanctissima verba : 

** Sirach 44:5

in peritia sua requirentes modos musicos,  et narrantes carmina Scripturarum : 

** Sirach 44:6

homines divites in virtute,  pulchritudinis studium habentes,  pacificantes in domibus suis. 

** Sirach 44:7

Omnes isti in generationibus gentis suæ gloriam adepti sunt,  et in diebus suis habentur in laudibus. 

** Sirach 44:8

Qui de illis nati sunt reliquerunt nomen  narrandi laudes eorum. 

** Sirach 44:9

Et sunt quorum non est memoria :  perierunt quasi qui non fuerint :  et nati sunt quasi non nati,  et filii ipsorum cum ipsis. 

** Sirach 44:10

Sed illi viri misericordiæ sunt,  quorum pietates non defuerunt. 

** Sirach 44:11

Cum semine eorum permanent bona : 

** Sirach 44:12

hæreditas sancta nepotes eorum,  et in testamentis stetit semen eorum : 

** Sirach 44:13

et filii eorum propter illos usque in æternum manent :  semen eorum et gloria eorum non derelinquetur. 

** Sirach 44:14

Corpora ipsorum in pace sepulta sunt,  et nomen eorum vivit in generationem et generationem. 

** Sirach 44:15

Sapientiam ipsorum narrent populi,  et laudem eorum nuntiet ecclesia. 

** Sirach 44:16

Enoch placuit Deo, et translatus est in paradisum,  ut det gentibus pœnitentiam. 

** Sirach 44:17

Noë inventus est perfectus, justus,  et in tempore iracundiæ factus est reconciliatio. 

** Sirach 44:18

Ideo dimissum est reliquum terræ,  cum factum est diluvium. 

** Sirach 44:19

Testamenta sæculi posita sunt apud illum,  ne deleri possit diluvio omnis caro. 

** Sirach 44:20

Abraham magnus pater multitudinis gentium,  et non est inventus similis illi in gloria :  qui conservavit legem Excelsi,  et fuit in testamento cum illo. 

** Sirach 44:21

In carne ejus stare fecit testamentum,  et in tentatione inventus est fidelis. 

** Sirach 44:22

Ideo jurejurando dedit illi gloriam in gente sua,  crescere illum quasi terræ cumulum, 

** Sirach 44:23

et ut stellas exaltare semen ejus,  et hæreditare illos a mari usque ad mare,  et a flumine usque ad terminos terræ. 

** Sirach 44:24

Et in Isaac eodem modo fecit,  propter Abraham patrem ejus. 

** Sirach 44:25

Benedictionem omnium gentium dedit illi Dominus,  et testamentum confirmavit super caput Jacob. 

** Sirach 44:26

Agnovit eum in benedictionibus suis,  et dedit illi hæreditatem,  et divisit illi partem in tribubus duodecim. 

** Sirach 44:27

Et conservavit illi homines misericordiæ,  invenientes gratiam in oculis omnis carnis.  

* Sirach 45

** Sirach 45:1

Dilectus Deo et hominibus Moyses,  cujus memoria in benedictione est. 

** Sirach 45:2

Similem illum fecit in gloria sanctorum,  et magnificavit eum in timore inimicorum,  et in verbis suis monstra placavit. 

** Sirach 45:3

Glorificavit illum in conspectu regum,  et jussit illi coram populo suo,  et ostendit illi gloriam suam. 

** Sirach 45:4

In fide et lenitate ipsius sanctum fecit illum,  et elegit eum ex omni carne. 

** Sirach 45:5

Audivit enim eum, et vocem ipsius,  et induxit illum in nubem. 

** Sirach 45:6

Et dedit illi coram præcepta,  et legem vitæ et disciplinæ,  docere Jacob testamentum suum,  et judicia sua Israël. 

** Sirach 45:7

Excelsum fecit Aaron fratrem ejus,  et similem sibi, de tribu Levi. 

** Sirach 45:8

Statuit ei testamentum æternum,  et dedit illi sacerdotium gentis,  et beatificavit illum in gloria : 

** Sirach 45:9

et circumcinxit eum zona gloriæ,  et induit eum stolam gloriæ,  et coronavit eum in vasis virtutis. 

** Sirach 45:10

Circumpedes, et femoralia, et humerale posuit ei :  et cinxit illum tintinnabulis aureis plurimis in gyro : 

** Sirach 45:11

dare sonitum in incessu suo,  auditum facere sonitum in templo  in memoriam filiis gentis suæ. 

** Sirach 45:12

Stolam sanctam auro, et hyacintho, et purpura,  opus textile viri sapientis, judicio et veritate præditi : 

** Sirach 45:13

torto cocco opus artificis  gemmis pretiosis figuratis in ligatura auri,  et opere lapidarii sculptis,  in memoriam secundum numerum tribuum Israël. 

** Sirach 45:14

Corona aurea super mitram ejus  expressa signo sanctitatis, et gloria honoris :  opus virtutis, et desideria oculorum ornata. 

** Sirach 45:15

Sic pulchra ante ipsum non fuerunt talia  usque ad originem. 

** Sirach 45:16

Non est indutus illa alienigena aliquis,  sed tantum filii ipsius soli,  et nepotes ejus per omne tempus. 

** Sirach 45:17

Sacrificia ipsius  consumpta sunt igne quotidie. 

** Sirach 45:18

Complevit Moyses manus ejus,  et unxit illum oleo sancto. 

** Sirach 45:19

Factum est illi in testamentum æternum,  et semini ejus, sicut dies cæli,  fungi sacerdotio, et habere laudem,  et glorificare populum suum in nomine ejus. 

** Sirach 45:20

Ipsum elegit ab omni vivente,  offerre sacrificium Deo, incensum, et bonum odorem,  in memoriam placare pro populo suo : 

** Sirach 45:21

et dedit illi in præceptis suis potestatem,  in testamentis judiciorum :  docere Jacob testimonia,  et in lege sua lucem dare Israël. 

** Sirach 45:22

Quia contra illum steterunt alieni,  et propter invidiam circumdederunt illum homines in deserto,  qui erant cum Dathan et Abiron,  et congregatio Core in iracundia. 

** Sirach 45:23

Vidit Dominus Deus, et non placuit illi,  et consumpti sunt in impetu iracundiæ. 

** Sirach 45:24

Fecit illis monstra,  et consumpsit illos in flamma ignis. 

** Sirach 45:25

Et addidit Aaron gloriam,  et dedit illi hæreditatem,  et primitias frugum terræ divisit illi. 

** Sirach 45:26

Panem ipsis in primis paravit in satietatem :  nam et sacrificia Domini edent,  quæ dedit illi et semini ejus. 

** Sirach 45:27

Ceterum in terra gentes non hæreditabit,  et pars non est illi in gente :  ipse est enim pars ejus, et hæreditas. 

** Sirach 45:28

Phinees, filius Eleazari, tertius in gloria est,  imitando eum in timore Domini, 

** Sirach 45:29

et stare in reverentia gentis :  in bonitate et alacritate animæ suæ placuit Deo pro Israël. 

** Sirach 45:30

Ideo statuit illi testamentum pacis,  principem sanctorum et gentis suæ,  ut sit illi et semini ejus sacerdotii dignitas in æternum. 

** Sirach 45:31

Et testamentum David regi filio Jesse de tribu Juda,  hæreditas ipsi et semini ejus :  ut daret sapientiam in cor nostrum,  judicare gentem suam in justitia,  ne abolerentur bona ipsorum :  et gloriam ipsorum in gentem eorum æternam fecit.  

* Sirach 46

** Sirach 46:1

Fortis in bello Jesus Nave, successor Moysi in prophetis,  qui fuit magnus secundum nomen suum, 

** Sirach 46:2

maximus in salutem electorum Dei,  expugnare insurgentes hostes,  ut consequeretur hæreditatem Israël. 

** Sirach 46:3

Quam gloriam adeptus est in tollendo manus suas,  et jactando contra civitates rhomphæas ! 

** Sirach 46:4

Quis ante illum sic restitit ?  nam hostes ipse Dominus perduxit. 

** Sirach 46:5

An non in iracundia ejus impeditus est sol,  et una dies facta est quasi duo ? 

** Sirach 46:6

Invocavit Altissimum potentem,  in oppugnando inimicos undique :  et audivit illum magnus et sanctus Deus,  in saxis grandinis virtutis valde fortis. 

** Sirach 46:7

Impetum fecit contra gentem hostilem,  et in descensu perdidit contrarios : 

** Sirach 46:8

ut cognoscant gentes potentiam ejus,  quia contra Deum pugnare non est facile.  Et secutus est a tergo potentis : 

** Sirach 46:9

et in diebus Moysi misericordiam fecit,  ipse, et Caleb filius Jephone,  stare contra hostem, et prohibere gentem a peccatis,  et perfringere murmur malitiæ. 

** Sirach 46:10

Et ipsi duo constituti a periculo liberati sunt  a numero sexcentorum millium peditum,  inducere illos in hæreditatem,  in terram quæ manat lac et mel. 

** Sirach 46:11

Et dedit Dominus ipsi Caleb fortitudinem,  et usque in senectutem permansit illi virtus,  ut ascenderet in excelsum terræ locum,  et semen ipsius obtinuit hæreditatem, 

** Sirach 46:12

ut viderent omnes filii Israël  quia bonum est obsequi sancto Deo. 

** Sirach 46:13

Et judices singuli suo nomine, quorum non est corruptum cor,  qui non aversi sunt a Domino, 

** Sirach 46:14

ut sit memoria illorum in benedictione,  et ossa eorum pullulent de loco suo : 

** Sirach 46:15

et nomen eorum permaneat in æternum,  permanens ad filios illorum, sanctorum virorum gloria. 

** Sirach 46:16

Dilectus a Domino Deo suo Samuel, propheta Domini,  renovavit imperium,  et unxit principes in gente sua. 

** Sirach 46:17

In lege Domini congregationem judicavit,  et vidit Deus Jacob :  et in fide sua probatus est propheta, 

** Sirach 46:18

et cognitus est in verbis suis fidelis,  quia vidit Deum lucis. 

** Sirach 46:19

Et invocavit Dominum omnipotentem,  in oppugnando hostes circumstantes undique,  in oblatione agni inviolati. 

** Sirach 46:20

Et intonuit de cælo Dominus,  et in sonitu magno auditam fecit vocem suam : 

** Sirach 46:21

et contrivit principes Tyriorum,  et omnes duces Philisthiim : 

** Sirach 46:22

et ante tempus finis vitæ suæ et sæculi,  testimonium præbuit in conspectu Domini et christi :  pecunias et usque ad calceamenta ab omni carne non accepit,  et non accusavit illum homo. 

** Sirach 46:23

Et post hoc dormivit : et notum fecit regi,  et ostendit illi finem vitæ suæ :  et exaltavit vocem suam de terra in prophetia,  delere impietatem gentis.  

* Sirach 47

** Sirach 47:1

Post hæc surrexit Nathan,  propheta in diebus David. 

** Sirach 47:2

Et quasi adeps separatus a carne,  sic David a filiis Israël. 

** Sirach 47:3

Cum leonibus lusit quasi cum agnis,  et in ursis similiter fecit sicut in agnis ovium, in juventute sua. 

** Sirach 47:4

Numquid non occidit gigantem,  et abstulit opprobrium de gente ? 

** Sirach 47:5

In tollendo manum,  saxo fundæ dejecit exsultationem Goliæ : 

** Sirach 47:6

nam invocavit Dominum omnipotentem,  et dedit in dextera ejus tollere hominem fortem in bello,  et exaltare cornu gentis suæ. 

** Sirach 47:7

Sic in decem millibus glorificavit eum :  et laudavit eum in benedictionibus Domini,  in offerendo illi coronam gloriæ : 

** Sirach 47:8

contrivit enim inimicos undique,  et extirpavit Philisthiim contrarios usque in hodiernum diem :  contrivit cornu ipsorum usque in æternum. 

** Sirach 47:9

In omni opere dedit confessionem Sancto,  et Excelso in verbo gloriæ. 

** Sirach 47:10

De omni corde suo laudavit Dominum :  et dilexit Deum, qui fecit illum,  et dedit illi contra inimicos potentiam : 

** Sirach 47:11

et stare fecit cantores contra altare,  et in sono eorum dulces fecit modos. 

** Sirach 47:12

Et dedit in celebrationibus decus,  et ornavit tempora usque ad consummationem vitæ,  ut laudarent nomen sanctum Domini,  et amplificarent mane Dei sanctitatem. 

** Sirach 47:13

Dominus purgavit peccata ipsius,  et exaltavit in æternum cornu ejus :  et dedit illi testamentum regni,  et sedem gloriæ in Israël. 

** Sirach 47:14

Post ipsum surrexit filius sensatus,  et propter illum dejecit omnem potentiam inimicorum. 

** Sirach 47:15

Salomon imperavit in diebus pacis,  cui subjecit Deus omnes hostes,  ut conderet domum in nomine suo,  et pararet sanctitatem in sempiternum.  Quemadmodum eruditus es in juventute tua, 

** Sirach 47:16

et impletus es, quasi flumen, sapientia,  et terram retexit anima tua. 

** Sirach 47:17

Et replesti in comparationibus ænigmata :  ad insulas longe divulgatum est nomen tuum,  et dilectus es in pace tua. 

** Sirach 47:18

In cantilenis, et proverbiis,  et comparationibus, et interpretationibus, miratæ sunt terræ : 

** Sirach 47:19

et in nomine Domini Dei,  cui est cognomen Deus Israël. 

** Sirach 47:20

Collegisti quasi auricalcum aurum,  et ut plumbum complesti argentum : 

** Sirach 47:21

et inclinasti femora tua mulieribus :  potestatem habuisti in corpore tuo. 

** Sirach 47:22

Dedisti maculam in gloria tua,  et profanasti semen tuum,  inducere iracundiam ad liberos tuos,  et incitari stultitiam tuam : 

** Sirach 47:23

ut faceres imperium bipartitum,  et ex Ephraim imperare imperium durum. 

** Sirach 47:24

Deus autem non derelinquet misericordiam suam :  et non corrumpet, nec delebit opera sua,  neque perdet a stirpe nepotes electi sui,  et semen ejus qui diligit Dominum non corrumpet. 

** Sirach 47:25

Dedit autem reliquum Jacob,  et David de ipsa stirpe. 

** Sirach 47:26

Et finem habuit Salomon cum patribus suis. 

** Sirach 47:27

Et dereliquit post se de semine suo, gentis stultitiam, 

** Sirach 47:28

et imminutum a prudentia, Roboam,  qui avertit gentem consilio suo : 

** Sirach 47:29

et Jeroboam filium Nabat, qui peccare fecit Israël,  et dedit viam peccandi Ephraim :  et plurima redundaverunt peccata ipsorum. 

** Sirach 47:30

Valde averterunt illos a terra sua. 

** Sirach 47:31

Et quæsivit omnes nequitias,  usque dum perveniret ad illos defensio,  et ab omnibus peccatis liberavit eos.  

* Sirach 48

** Sirach 48:1

Et surrexit Elias propheta quasi ignis,  et verbum ipsius quasi facula ardebat. 

** Sirach 48:2

Qui induxit in illos famem :  et irritantes illum invidia sua pauci facti sunt :  non enim poterant sustinere præcepta Domini. 

** Sirach 48:3

Verbo Domini continuit cælum,  et dejecit de cælo ignem ter. 

** Sirach 48:4

Sic amplificatus est Elias in mirabilibus suis.  Et quis potest similiter sic gloriari tibi ? 

** Sirach 48:5

qui sustulisti mortuum ab inferis de sorte mortis,  in verbo Domini Dei : 

** Sirach 48:6

qui dejecisti reges ad pernicem,  et confregisti facile potentiam ipsorum,  et gloriosos de lecto suo : 

** Sirach 48:7

qui audis in Sina judicium,  et in Horeb judicia defensionis : 

** Sirach 48:8

qui ungis reges ad pœnitentiam,  et prophetas facis successores post te : 

** Sirach 48:9

qui receptus es in turbine ignis,  in curru equorum igneorum : 

** Sirach 48:10

qui scriptus es in judiciis temporum,  lenire iracundiam Domini,  conciliare cor patris ad filium,  et restituere tribus Jacob. 

** Sirach 48:11

Beati sunt qui te viderunt,  et in amicitia tua decorati sunt. 

** Sirach 48:12

Nam nos vita vivimus tantum :  post mortem autem non erit tale nomen nostrum. 

** Sirach 48:13

Elias quidem in turbine tectus est,  et in Eliseo completus est spiritus ejus :  in diebus suis non pertimuit principem,  et potentia nemo vicit illum : 

** Sirach 48:14

nec superavit illum verbum aliquod,  et mortuum prophetavit corpus ejus. 

** Sirach 48:15

In vita sua fecit monstra,  et in morte mirabilia operatus est. 

** Sirach 48:16

In omnibus istis non pœnituit populus,  et non recesserunt a peccatis suis,  usque dum ejecti sunt de terra sua,  et dispersi sunt in omnem terram : 

** Sirach 48:17

et relicta est gens perpauca,  et princeps in domo David. 

** Sirach 48:18

Quidam ipsorum fecerunt quod placeret Deo :  alii autem multa commiserunt peccata. 

** Sirach 48:19

Ezechias munivit civitatem suam,  et induxit in medium ipsius aquam :  et fodit ferro rupem,  et ædificavit ad aquam puteum. 

** Sirach 48:20

In diebus ipsius ascendit Sennacherib,  et misit Rabsacen, et sustulit manum suam contra illos :  et extulit manum suam in Sion,  et superbus factus est potentia sua. 

** Sirach 48:21

Tunc mota sunt corda et manus ipsorum :  et doluerunt quasi parturientes mulieres. 

** Sirach 48:22

Et invocaverunt Dominum misericordem,  et expandentes manus suas extulerunt ad cælum :  et Sanctus, Dominus Deus, audivit cito vocem ipsorum. 

** Sirach 48:23

Non est commemoratus peccatorum illorum,  neque dedit illos inimicis suis :  sed purgavit eos in manu Isaiæ sancti prophetæ. 

** Sirach 48:24

Dejecit castra Assyriorum,  et contrivit illos angelus Domini : 

** Sirach 48:25

nam fecit Ezechias quod placuit Deo,  et fortiter ivit in via David patris sui,  quam mandavit illi Isaias, propheta magnus,  et fidelis in conspectu Dei. 

** Sirach 48:26

In diebus ipsius retro rediit sol,  et addidit regi vitam. 

** Sirach 48:27

Spiritu magno vidit ultima,  et consolatus est lugentes in Sion  usque in sempiternum. 

** Sirach 48:28

Ostendit futura,  et abscondita antequam evenirent.  

* Sirach 49

** Sirach 49:1

Memoria Josiæ in compositionem odoris facta  opus pigmentarii. 

** Sirach 49:2

In omni ore quasi mel indulcabitur ejus memoria,  et ut musica in convivio vini. 

** Sirach 49:3

Ipse est directus divinitus in pœnitentiam gentis,  et tulit abominationes impietatis. 

** Sirach 49:4

Et gubernavit ad Dominum cor ipsius,  et in diebus peccatorum corroboravit pietatem. 

** Sirach 49:5

Præter David et Ezechiam et Josiam,  omnes peccatum commiserunt : 

** Sirach 49:6

nam reliquerunt legem Altissimi reges Juda,  et contempserunt timorem Dei. 

** Sirach 49:7

Dederunt enim regnum suum aliis,  et gloriam suam alienigenæ genti. 

** Sirach 49:8

Incenderunt electam sanctitatis civitatem,  et desertas fecerunt vias ipsius in manu Jeremiæ. 

** Sirach 49:9

Nam male tractaverunt illum  qui a ventre matris consecratus est propheta,  evertere, et eruere, et perdere,  et iterum ædificare, et renovare : 

** Sirach 49:10

Ezechiel, qui vidit conspectum gloriæ  quam ostendit illi in curru cherubim. 

** Sirach 49:11

Nam commemoratus est inimicorum in imbre,  benefacere illis qui ostenderunt rectas vias. 

** Sirach 49:12

Et duodecim prophetarum ossa pullulent de loco suo :  nam corroboraverunt Jacob,  et redemerunt se in fide virtutis. 

** Sirach 49:13

Quomodo amplificemus Zorobabel ?  nam et ipse quasi signum in dextera manu : 

** Sirach 49:14

sic et Jesum filium Josedec,  qui in diebus suis ædificaverunt domum,  et exaltaverunt templum sanctum Domino,  paratum in gloriam sempiternam. 

** Sirach 49:15

Et Nehemias in memoriam multi temporis,  qui erexit nobis muros eversos,  et stare fecit portas et seras,  qui erexit domos nostras. 

** Sirach 49:16

Nemo natus est in terra qualis Henoch,  nam et ipse receptus est a terra : 

** Sirach 49:17

neque ut Joseph, qui natus est homo princeps fratrum,  firmamentum gentis, rector fratrum, stabilimentum populi : 

** Sirach 49:18

et ossa ipsius visitata sunt,  et post mortem prophetaverunt. 

** Sirach 49:19

Seth et Sem apud homines gloriam adepti sunt,  et super omnem animam in origine Adam.  

* Sirach 50

** Sirach 50:1

Simon, Oniæ filius, sacerdos magnus,  qui in vita sua suffulsit domum,  et in diebus suis corroboravit templum. 

** Sirach 50:2

Templi etiam altitudo ab ipso fundata est,  duplex ædificatio, et excelsi parietes templi. 

** Sirach 50:3

In diebus ipsius emanaverunt putei aquarum,  et quasi mare adimpleti sunt supra modum. 

** Sirach 50:4

Qui curavit gentem suam,  et liberavit eam a perditione : 

** Sirach 50:5

qui prævaluit amplificare civitatem,  qui adeptus est gloriam in conversatione gentis,  et ingressum domus et atrii amplificavit. 

** Sirach 50:6

Quasi stella matutina in medio nebulæ,  et quasi luna plena, in diebus suis lucet : 

** Sirach 50:7

et quasi sol refulgens,  sic ille effulsit in templo Dei. 

** Sirach 50:8

Quasi arcus refulgens inter nebulas gloriæ,  et quasi flos rosarum in diebus vernis,  et quasi lilia quæ sunt in transitu aquæ,  et quasi thus redolens in diebus æstatis : 

** Sirach 50:9

quasi ignis effulgens,  et thus ardens in igne : 

** Sirach 50:10

quasi vas auri solidum,  ornatum omni lapide pretioso : 

** Sirach 50:11

quasi oliva pullulans, et cypressus in altitudinem se extollens,  in accipiendo ipsum stolam gloriæ,  et vestiri eum in consummationem virtutis. 

** Sirach 50:12

In ascensu altaris sancti  gloriam dedit sanctitatis amictum. 

** Sirach 50:13

In accipiendo autem partes de manu sacerdotum,  et ipse stans juxta aram :  et circa illum corona fratrum :  quasi plantatio cedri in monte Libano, 

** Sirach 50:14

sic circa illum steterunt quasi rami palmæ :  et omnes filii Aaron in gloria sua. 

** Sirach 50:15

Oblatio autem Domini in manibus ipsorum  coram omni synagoga Israël :  et consummatione fungens in ara,  amplificare oblationem excelsi Regis, 

** Sirach 50:16

porrexit manum suam in libatione,  et libavit de sanguine uvæ. 

** Sirach 50:17

Effudit in fundamento altaris  odorem divinum excelso Principi. 

** Sirach 50:18

Tunc exclamaverunt filii Aaron,  in tubis productilibus sonuerunt :  et auditam fecerunt vocem magnam in memoriam coram Deo. 

** Sirach 50:19

Tunc omnis populus simul properaverunt,  et ceciderunt in faciem super terram,  adorare Dominum Deum suum,  et dare preces omnipotenti Deo excelso. 

** Sirach 50:20

Et amplificaverunt psallentes in vocibus suis,  et in magna domo auctus est sonus suavitatis plenus. 

** Sirach 50:21

Et rogavit populus Dominum excelsum in prece,  usque dum perfectus est honor Domini,  et munus suum perfecerunt. 

** Sirach 50:22

Tunc descendens, manus suas extulit  in omne congregationem filiorum Israël,  dare gloriam Deo a labiis suis,  et in nomine ipsius gloriari : 

** Sirach 50:23

et iteravit orationem suam,  volens ostendere virtutem Dei. 

** Sirach 50:24

Et nunc orate Deum omnium, qui magna fecit in omni terra,  qui auxit dies nostros a ventre matris nostræ,  et fecit nobiscum secundum suam misericordiam : 

** Sirach 50:25

det nobis jucunditatem cordis,  et fieri pacem in diebus nostris in Israël per dies sempiternos : 

** Sirach 50:26

credere Israël nobiscum esse Dei misericordiam,  ut liberet nos in diebus suis. 

** Sirach 50:27

Duas gentes odit anima mea :  tertia autem non est gens quam oderim : 

** Sirach 50:28

qui sedent in monte Seir, et Philisthiim,  et stultus populus qui habitat in Sichimis. 

** Sirach 50:29

Doctrinam sapientiæ et disciplinæ scripsit in codice isto  Jesus, filius Sirach, Jerosolymita,  qui renovavit sapientiam de corde suo. 

** Sirach 50:30

Beatus qui in istis versatur bonis :  qui ponit illa in corde suo, sapiens erit semper. 

** Sirach 50:31

Si enim hæc fecerit, ad omnia valebit, quia lux Dei vestigium ejus est.  

* Sirach 51

** Sirach 51:1

Oratio Jesu filii Sirach.   Confitebor tibi, Domine rex,  et collaudabo te Deum salvatorem meum. 

** Sirach 51:2

Confitebor nomini tuo,  quoniam adjutor et protector factus es mihi, 

** Sirach 51:3

et liberasti corpus meum a perditione :  a laqueo linguæ iniquæ, et a labiis operantium mendacium :  et in conspectu astantium factus es mihi adjutor. 

** Sirach 51:4

Et liberasti me, secundum multitudinem misericordiæ nominis tui,  a rugientibus præparatis ad escam : 

** Sirach 51:5

de manibus quærentium animam meam,  et de portis tribulationum quæ circumdederunt me ; 

** Sirach 51:6

a pressura flammæ quæ circumdedit me,  et in medio ignis non sum æstuatus ; 

** Sirach 51:7

de altitudine ventris inferi,  et a lingua coinquinata, et a verbo mendacii,  a rege iniquo, et a lingua injusta. 

** Sirach 51:8

Laudabit usque ad mortem anima mea Dominum, 

** Sirach 51:9

et vita mea appropinquans erat in inferno deorsum. 

** Sirach 51:10

Circumdederunt me undique, et non erat qui adjuvaret :  respiciens eram ad adjutorium hominum, et non erat. 

** Sirach 51:11

Memoratus sum misericordiæ tuæ Domine,  et operationis tuæ, quæ a sæculo sunt : 

** Sirach 51:12

quoniam eruis sustinentes te, Domine,  et liberas eos de manibus gentium. 

** Sirach 51:13

Exaltasti super terram habitationem meam,  et pro morte defluente deprecatus sum. 

** Sirach 51:14

Invocavi Dominum patrem Domini mei,  ut non derelinquat me in die tribulationis meæ,  et in tempore superborum, sine adjutorio. 

** Sirach 51:15

Laudabo nomen tuum assidue,  et collaudabo illud in confessione :  et exaudita est oratio mea, 

** Sirach 51:16

et liberasti me de perditione,  et eripuisti me de tempore iniquo. 

** Sirach 51:17

Propterea confitebor, et laudem dicam tibi,  et benedicam nomini Domini. 

** Sirach 51:18

Cum adhuc junior essem, priusquam oberrarem,  quæsivi sapientiam palam in oratione mea. 

** Sirach 51:19

Ante templum postulabam pro illis,  et usque in novissimis inquiram eam :  et effloruit tamquam præcox uva. 

** Sirach 51:20

Lætatum est cor meum in ea :  ambulavit pes meus iter rectum :  a juventute mea investigabam eam. 

** Sirach 51:21

Inclinavi modico aurem meam,  et excepi illam. 

** Sirach 51:22

Multam inveni in meipso sapientiam,  et multum profeci in ea. 

** Sirach 51:23

Danti mihi sapientiam dabo gloriam : 

** Sirach 51:24

consiliatus sum enim ut facerem illam.  Zelatus sum bonum, et non confundar. 

** Sirach 51:25

Colluctata est anima mea in illa,  et in faciendo eam confirmatus sum. 

** Sirach 51:26

Manus meas extendi in altum,  et insipientiam ejus luxi ; 

** Sirach 51:27

animam meam direxi ad illam,  et in agnitione inveni eam. 

** Sirach 51:28

Possedi cum ipsa cor ab initio :  propter hoc, non derelinquar. 

** Sirach 51:29

Venter meus conturbatus est quærendo illam :  propterea bonam possidebo possessionem. 

** Sirach 51:30

Dedit mihi Dominus linguam mercedem meam,  et in ipsa laudabo eum. 

** Sirach 51:31

Appropiate ad me, indocti,  et congregate vos in domum disciplinæ. 

** Sirach 51:32

Quid adhuc retardatis ? et quid dicitis in his ?  animæ vestræ sitiunt vehementer. 

** Sirach 51:33

Aperui os meum, et locutus sum :  Comparate vobis sine argento, 

** Sirach 51:34

et collum vestrum subjicite jugo :  et suscipiat anima vestra disciplinam :  in proximo est enim invenire eam. 

** Sirach 51:35

Videte oculis vestris, quia modicum laboravi,  et inveni mihi multam requiem. 

** Sirach 51:36

Assumite disciplinam in multo numero argenti,  et copiosum aurum possidete in ea. 

** Sirach 51:37

Lætetur anima vestra in misericordia ejus,  et non confundemini in laude ipsius. 

** Sirach 51:38

Operamini opus vestrum ante tempus,  et dabit vobis mercedem vestram in tempore suo.    

