* Titus 1

** Titus 1:1

Paulus servus Dei, Apostolus autem Jesu Christi secundum fidem electorum Dei, et agnitionem veritatis, quæ secundum pietatem est

** Titus 1:2

in spem vitæ æternæ, quam promisit qui non mentitur, Deus, ante tempora sæcularia :

** Titus 1:3

manifestavit autem temporibus suis verbum suum in prædicatione, quæ credita est mihi secundum præceptum Salvatoris nostri Dei :

** Titus 1:4

Tito dilecto filio secundum communem fidem, gratia, et pax a Deo Patre, et Christo Jesu Salvatore nostro.  

** Titus 1:5

Hujus rei gratia reliqui te Cretæ, ut ea quæ desunt, corrigas, et constituas per civitates presbyteros, sicut et ego disposui tibi,

** Titus 1:6

si quis sine crimine est, unius uxoris vir, filios habens fideles, non in accusatione luxuriæ, aut non subditos.

** Titus 1:7

Oportet enim episcopum sine crimine esse, sicut Dei dispensatorem : non superbum, non iracundum, non vinolentum, non percussorem, non turpis lucri cupidum :

** Titus 1:8

sed hospitalem, benignum, sobrium, justum, sanctum, continentem,

** Titus 1:9

amplectentem eum, qui secundum doctrinam est, fidelem sermonem : ut potens sit exhortari in doctrina sana, et eos qui contradicunt, arguere.  

** Titus 1:10

Sunt enim multi etiam inobedientes, vaniloqui, et seductores : maxime qui de circumcisione sunt :

** Titus 1:11

quos oportet redargui : qui universas domos subvertunt, docentes quæ non oportet, turpis lucri gratia.

** Titus 1:12

Dixit quidam ex illis, proprius ipsorum propheta : Cretenses semper mendaces, malæ bestiæ, ventres pigri.

** Titus 1:13

Testimonium hoc verum est. Quam ob causam increpa illos dure, ut sani sint in fide,

** Titus 1:14

non intendentes judaicis fabulis, et mandatis hominum, aversantium se a veritate.

** Titus 1:15

Omnia munda mundis : coinquinatis autem et infidelibus, nihil est mundum, sed inquinatæ sunt eorum et mens et conscientia.

** Titus 1:16

Confitentur se nosse Deum, factis autem negant : cum sint abominati, et incredibiles, et ad omne opus bonum reprobi.   

* Titus 2

** Titus 2:1

Tu autem loquere quæ decent sanam doctrinam :

** Titus 2:2

senes ut sobrii sint, pudici, prudentes, sani in fide, in dilectione, in patientia :

** Titus 2:3

anus similiter in habitu sancto, non criminatrices, non multo vino servientes, bene docentes :

** Titus 2:4

ut prudentiam doceant adolescentulas, ut viros suos ament, filios suos diligant,

** Titus 2:5

prudentes, castas, sobrias, domus curam habentes, benignas, subditas viris suis, ut non blasphemetur verbum Dei.

** Titus 2:6

Juvenes similiter hortare ut sobrii sint.

** Titus 2:7

In omnibus teipsum præbe exemplum bonorum operum, in doctrina, in integritate, in gravitate,

** Titus 2:8

verbum sanum, irreprehensibile : ut is qui ex adverso est, vereatur, nihil habens malum dicere de nobis.

** Titus 2:9

Servos dominis suis subditos esse, in omnibus placentes, non contradicentes,

** Titus 2:10

non fraudantes, sed in omnibus fidem bonam ostendentes : ut doctrinam Salvatoris nostri Dei ornent in omnibus.

** Titus 2:11

Apparuit enim gratia Dei Salvatoris nostri omnibus hominibus,

** Titus 2:12

erudiens nos, ut abnegantes impietatem, et sæcularia desideria, sobrie, et juste, et pie vivamus in hoc sæculo,

** Titus 2:13

exspectantes beatam spem, et adventum gloriæ magni Dei, et Salvatoris nostri Jesu Christi :

** Titus 2:14

qui dedit semetipsum pro nobis, ut nos redimeret ab omni iniquitate, et mundaret sibi populum acceptabilem, sectatorem bonorum operum.

** Titus 2:15

Hæc loquere, et exhortare, et argue cum omni imperio. Nemo te contemnat.   

* Titus 3

** Titus 3:1

Admone illos principibus, et potestatibus subditos esse, dicto obedire, ad omne opus bonum paratos esse :

** Titus 3:2

neminem blasphemare, non litigiosos esse, sed modestos, omnem ostendentes mansuetudinem ad omnes homines.

** Titus 3:3

Eramus enim aliquando et nos insipientes, increduli, errantes, servientes desideriis, et voluptatibus variis, in malitia et invidia agentes, odibiles, odientes invicem.

** Titus 3:4

Cum autem benignitas et humanitas apparuit Salvatoris nostri Dei,

** Titus 3:5

non ex operibus justitiæ, quæ fecimus nos, sed secundum suam misericordiam salvos nos fecit per lavacrum regenerationis et renovationis Spiritus Sancti,

** Titus 3:6

quem effudit in nos abunde per Jesum Christum Salvatorem nostrum :

** Titus 3:7

ut justificati gratia ipsius, hæredes simus secundum spem vitæ æternæ.

** Titus 3:8

Fidelis sermo est : et de his volo te confirmare : ut curent bonis operibus præesse qui credunt Deo. Hæc sunt bona, et utilia hominibus.

** Titus 3:9

Stultas autem quæstiones, et genealogias, et contentiones, et pugnas legis devita : sunt enim inutiles, et vanæ.

** Titus 3:10

Hæreticum hominem post unam et secundam correptionem devita :

** Titus 3:11

sciens quia subversus est, qui ejusmodi est, et delinquit, cum sit proprio judicio condemnatus.  

** Titus 3:12

Cum misero ad te Artemam, aut Tychicum, festina ad me venire Nicopolim : ibi enim statui hiemare.

** Titus 3:13

Zenam legisperitum et Apollo sollicite præmitte, ut nihil illis desit.

** Titus 3:14

Discant autem et nostri bonis operibus præesse ad usus necessarios : ut non sint infructuosi.

** Titus 3:15

Salutant te qui mecum sunt omnes : saluta eos qui nos amant in fide. Gratia Dei cum omnibus vobis. Amen.    

