* Tobit 1

** Tobit 1:1

Tobias ex tribu et civitate Nephthali (quæ est in superioribus Galilææ supra Naasson, post viam quæ ducit ad occidentem, in sinistro habens civitatem Sephet)

** Tobit 1:2

cum captus esset in diebus Salmanasar regis Assyriorum, in captivitate tamen positus, viam veritatis non deseruit,

** Tobit 1:3

ita ut omnia quæ habere poterat, quotidie concaptivis fratribus, qui erant ex ejus genere, impertiret.

** Tobit 1:4

Cumque esset junior omnibus in tribu Nephthali, nihil tamen puerile gessit in opere.

** Tobit 1:5

Denique, cum irent omnes ad vitulos aureos quos Jeroboam fecerat rex Israël, hic solus fugiebat consortia omnium.

** Tobit 1:6

Sed pergebat in Jerusalem ad templum Domini, et ibi adorabat Dominum Deum Israël, omnia primitiva sua et decimas suas fideliter offerens,

** Tobit 1:7

ita ut in tertio anno proselytis et advenis ministraret omnem decimationem.

** Tobit 1:8

Hæc et his similia secundum legem Dei puerulus observabat.

** Tobit 1:9

Cum vero factus esset vir, accepit uxorem Annam de tribu sua, genuitque ex ea filium, nomen suum imponens ei :

** Tobit 1:10

quem ab infantia timere Deum docuit, et abstinere ab omni peccato.

** Tobit 1:11

Igitur, cum per captivitatem devenisset cum uxore sua et filio in civitatem Niniven cum omni tribu sua

** Tobit 1:12

(cum omnes ederent ex cibis gentilium), iste custodivit animam suam, et numquam contaminatus est in escis eorum.

** Tobit 1:13

Et quoniam memor fuit Domini in toto corde suo, dedit illi Deus gratiam in conspectu Salmanasar regis,

** Tobit 1:14

et dedit illi potestatem quocumque vellet ire, habens libertatem quæcumque facere voluisset.

** Tobit 1:15

Pergebat ergo ad omnes qui erant in captivitate, et monita salutis dabat eis.

** Tobit 1:16

Cum autem venisset in Rages civitatem Medorum, et ex his quibus honoratus fuerat a rege, habuisset decem talenta argenti :

** Tobit 1:17

et cum in multa turba generis sui Gabelum egentem videret, qui erat ex tribu ejus, sub chirographo dedit illi memoratum pondus argenti.

** Tobit 1:18

Post multum vero temporis, mortuo Salmanasar rege, cum regnaret Sennacherib filius ejus pro eo, et filios Israël exosos haberet in conspectu suo,

** Tobit 1:19

Tobias quotidie pergebat per omnem cognationem suam, et consolabatur eos, dividebatque unicuique, prout poterat, de facultatibus suis :

** Tobit 1:20

esurientes alebat, nudisque vestimenta præbebat, et mortuis atque occisis sepulturam sollicitus exhibebat.

** Tobit 1:21

Denique cum reversus esset rex Sennacherib, fugiens a Judæa plagam quam circa eum fecerat Deus propter blasphemiam suam, et iratus multos occideret ex filiis Israël, Tobias sepeliebat corpora eorum.

** Tobit 1:22

At ubi nuntiatum est regi, jussit eum occidi, et tulit omnem substantiam ejus.

** Tobit 1:23

Tobias vero cum filio suo et cum uxore suo fugiens, nudus latuit, quia multi diligebant eum.

** Tobit 1:24

Post dies vero quadraginta quinque occiderunt regem filii ipsius,

** Tobit 1:25

et reversus est Tobias in domum suam, omnisque facultas ejus restituta est ei.   

* Tobit 2

** Tobit 2:1

Post hæc vero, cum esset dies festus Domini, et factum esset prandium bonum in domo Tobiæ,

** Tobit 2:2

dixit filio suo : Vade, et adduc aliquos de tribu nostra, timentes Deum, ut epulentur nobiscum.

** Tobit 2:3

Cumque abiisset, reversus nuntiavit ei unum ex filiis Israël jugulatum jacere in platea. Statimque exiliens de accubitu suo, relinquens prandium, jejunus pervenit ad corpus :

** Tobit 2:4

tollensque illud portavit ad domum suam occulte, ut dum sol occubuisset, caute sepeliret eum.

** Tobit 2:5

Cumque occultasset corpus, manducavit panem cum luctu et tremore,

** Tobit 2:6

memorans illum sermonem, quem dixit Dominus per Amos prophetam : Dies festi vestri convertentur in lamentationem et luctum.

** Tobit 2:7

Cum vero sol occubuisset, abiit, et sepelivit eum.

** Tobit 2:8

Arguebant autem eum omnes proximi ejus, dicentes : Jam hujus rei causa interfici jussus es, et vix effugisti mortis imperium, et iterum sepelis mortuos ?

** Tobit 2:9

Sed Tobias plus timens Deum quam regem, rapiebat corpora occisorum, et occultabat in domo sua, et mediis noctibus sepeliebat ea.  

** Tobit 2:10

Contigit autem ut quadam die fatigatus a sepultura, veniens in domum suam, jactasset se juxta parietem, et obdormisset,

** Tobit 2:11

et ex nido hirundinum dormienti illi calida stercora inciderent super oculos ejus, fieretque cæcus.

** Tobit 2:12

Hanc autem tentationem ideo permisit Dominus evenire illi, ut posteris daretur exemplum patientiæ ejus, sicut et sancti Job.

** Tobit 2:13

Nam cum ab infantia sua semper Deum timuerit, et mandata ejus custodierit, non est contristatus contra Deum quod plaga cæcitatis evenerit ei,

** Tobit 2:14

sed immobilis in Dei timore permansit, agens gratias Deo omnibus diebus vitæ suæ.

** Tobit 2:15

Nam sicut beato Job insultabant reges, ita isti parentes et cognati ejus irridebant vitam ejus, dicentes :

** Tobit 2:16

Ubi est spes tua, pro qua eleemosynas et sepulturas faciebas ?

** Tobit 2:17

Tobias vero increpabat eos, dicens : Nolite ita loqui :

** Tobit 2:18

quoniam filii sanctorum sumus, et vitam illam expectamus, quam Deus daturus est his qui fidem suam numquam mutant ab eo.

** Tobit 2:19

Anna vero uxor ejus ibat ad opus textrinum quotidie, et de labore manuum suarum victum quem consequi poterat, deferebat.

** Tobit 2:20

Unde factum est ut hædum caprarum accipiens detulisset domi :

** Tobit 2:21

cujus cum vocem balantis vir ejus audisset, dixit : Videte, ne forte furtivus sit : reddite eum dominis suis, quia non licet nobis aut edere ex furto aliquid, aut contingere.

** Tobit 2:22

Ad hæc uxor ejus irata respondit : Manifeste vana facta est spes tua, et eleemosynæ tuæ modo apparuerunt.

** Tobit 2:23

Atque his et aliis hujuscemodi verbis exprobrabat ei.   

* Tobit 3

** Tobit 3:1

Tunc Tobias ingemuit, et cœpit orare cum lacrimis,

** Tobit 3:2

dicens :   Justus es, Domine, et omnia judicia tua justa sunt,  et omnes viæ tuæ, misericordia, et veritas, et judicium. 

** Tobit 3:3

Et nunc Domine, memor esto mei,  et ne vindictam sumas de peccatis meis,  neque reminiscaris delicta mea, vel parentum meorum. 

** Tobit 3:4

Quoniam non obedivimus præceptis tuis,  ideo traditi sumus in direptionem,  et captivitatem, et mortem,  et in fabulam, et in improperium omnibus nationibus  in quibus dispersisti nos. 

** Tobit 3:5

Et nunc Domine, magna judicia tua,  quia non egimus secundum præcepta tua,  et non ambulavimus sinceriter coram te. 

** Tobit 3:6

Et nunc Domine, secundum voluntatem tuam fac mecum,  et præcipe in pace recipi spiritum meum :  expedit enim mihi mori magis quam vivere.  

** Tobit 3:7

Eadem itaque die, contigit ut Sara filia Raguelis in Rages civitate Medorum et ipsa audiret improperium ab una ex ancillis patris sui,

** Tobit 3:8

quoniam tradita fuerat septem viris, et dæmonium nomine Asmodæus occiderat eos, mox ut ingressi fuissent ad eam.

** Tobit 3:9

Ergo cum pro culpa sua increparet puellam, respondit ei, dicens : Amplius ex te non videamus filium aut filiam super terram, interfectrix virorum tuorum.

** Tobit 3:10

Numquid et occidere me vis, sicut jam occidisti septem viros ? Ad hanc vocem perrexit in superius cubiculum domus suæ : et tribus diebus, et tribus noctibus non manducavit, neque bibit :

** Tobit 3:11

sed in oratione persistens cum lacrimis deprecabatur Deum, ut ab isto improperio liberaret eam.

** Tobit 3:12

Factum est autem die tertia, dum compleret orationem, benedicens Dominum

** Tobit 3:13

dixit : Benedictum est nomen tuum, Deus patrum nostrorum : qui cum iratus fueris, misericordiam facies, et in tempore tribulationis peccata dimittis his qui invocant te.

** Tobit 3:14

Ad te, Domine, faciem meam converto ; ad te oculos meos dirigo.

** Tobit 3:15

Peto, Domine, ut de vinculo improperii hujus absolvas me, aut certe desuper terram eripias me.

** Tobit 3:16

Tu scis, Domine, quia numquam concupivi virum, et mundam servavi animam meam ab omni concupiscentia.

** Tobit 3:17

Numquam cum ludentibus miscui me, neque cum his qui in levitate ambulant, participem me præbui.

** Tobit 3:18

Virum autem cum timore tuo, non cum libidine mea, consensi suscipere.

** Tobit 3:19

Et, aut ego indigna fui illis, aut illi forsitan me non fuerunt digni, quia forsitan viro alii conservasti me.

** Tobit 3:20

Non est enim in hominis potestate consilium tuum.

** Tobit 3:21

Hoc autem pro certo habet omnis qui te colit : quod vita ejus, si in probatione fuerit, coronabitur ; si autem in tribulatione fuerit, liberabitur ; et si in correptione fuerit, ad misericordiam tuam venire licebit.

** Tobit 3:22

Non enim delectaris in perditionibus nostris : quia post tempestatem tranquillum facis, et post lacrimationem et fletum, exultationem infundis.

** Tobit 3:23

Sit nomen tuum, Deus Israël, benedictum in sæcula.

** Tobit 3:24

In illo tempore exauditæ sunt preces amborum in conspectu gloriæ summi Dei :

** Tobit 3:25

et missus est angelus Domini sanctus Raphaël ut curaret eos ambos, quorum uno tempore sunt orationes in conspectu Domini recitatæ.   

* Tobit 4

** Tobit 4:1

Igitur cum Tobias putaret orationem suam exaudiri ut mori potuisset, vocavit ad se Tobiam filium suum,

** Tobit 4:2

dixitque ei : Audi, fili mi, verba oris mei, et ea in corde tuo quasi fundamentum construe.

** Tobit 4:3

Cum acceperit Deus animam meam, corpus meum sepeli : et honorem habebis matri tuæ omnibus diebus vitæ ejus :

** Tobit 4:4

memor enim esse debes, quæ et quanta pericula passa sit propter te in utero suo.

** Tobit 4:5

Cum autem et ipsa compleverit tempus vitæ suæ, sepelias eam circa me.

** Tobit 4:6

Omnibus autem diebus vitæ tuæ in mente habeto Deum : et cave ne aliquando peccato consentias, et prætermittas præcepta Domini Dei nostri.

** Tobit 4:7

Ex substantia tua fac eleemosynam, et noli avertere faciem tuam ab ullo paupere : ita enim fiet ut nec a te avertatur facies Domini.

** Tobit 4:8

Quomodo potueris, ita esto misericors.

** Tobit 4:9

Si multum tibi fuerit, abundanter tribue : si exiguum tibi fuerit, etiam exiguum libenter impertiri stude.

** Tobit 4:10

Præmium enim bonum tibi thesaurizas in die necessitatis :

** Tobit 4:11

quoniam eleemosyna ab omni peccato et a morte liberat, et non patietur animam ire in tenebras.

** Tobit 4:12

Fiducia magna erit coram summo Deo, eleemosyna omnibus facientibus eam.

** Tobit 4:13

Attende tibi, fili mi, ab omni fornicatione, et præter uxorem tuam numquam patiaris crimen scire.

** Tobit 4:14

Superbiam numquam in tuo sensu aut in tuo verbo dominari permittas : in ipsa enim initium sumpsit omnis perditio.

** Tobit 4:15

Quicumque tibi aliquid operatus fuerit, statim ei mercedem restitue, et merces mercenarii tui apud te omnino non remaneat.

** Tobit 4:16

Quod ab alio oderis fieri tibi, vide ne tu aliquando alteri facias.

** Tobit 4:17

Panem tuum cum esurientibus et egenis comede, et de vestimentis tuis nudos tege.

** Tobit 4:18

Panem tuum et vinum tuum super sepulturam justi constitue, et noli ex eo manducare et bibere cum peccatoribus.

** Tobit 4:19

Consilium semper a sapiente perquire.

** Tobit 4:20

Omni tempore benedic Deum : et pete ab eo ut vias tuas dirigat, et omnia consilia tua in ipso permaneant.

** Tobit 4:21

Indico etiam tibi, fili mi, dedisse me decem talenta argenti, dum adhuc infantulus esses, Gabelo, in Rages civitate Medorum, et chirographum ejus apud me habeo :

** Tobit 4:22

et ideo perquire quomodo ad eum pervenias, et recipias ab eo supra memoratum pondus argenti, et restituas ei chirographum suum.

** Tobit 4:23

Noli timere, fili mi : pauperem quidem vitam gerimus, sed multa bona habebimus si timuerimus Deum, et recesserimus ab omni peccato, et fecerimus bene.   

* Tobit 5

** Tobit 5:1

Tunc respondit Tobias patri suo, et dixit : Omnia quæcumque præcepisti mihi faciam, pater.

** Tobit 5:2

Quomodo autem pecuniam hanc requiram, ignoro : ille me nescit, et ego eum ignoro : quod signum dabo ei ? sed neque viam per quam pergatur illuc aliquando cognovi.

** Tobit 5:3

Tunc pater suus respondit illi, et dixit : Chirographum quidem illius penes me habeo : quod dum illi ostenderis, statim restituet.

** Tobit 5:4

Sed perge nunc, et inquire tibi aliquem fidelem virum, qui eat tecum salva mercede sua, ut dum adhuc vivo, recipias eam.

** Tobit 5:5

Tunc egressus Tobias, invenit juvenem splendidum stantem præcinctum, et quasi paratum ad ambulandum.

** Tobit 5:6

Et ignorans quod angelus Dei esset, salutavit eum, et dixit : Unde te habemus, bone juvenis ?

** Tobit 5:7

At ille respondit : Ex filiis Israël. Et Tobias dixit ei : Nosti viam quæ ducit in regionem Medorum ?

** Tobit 5:8

Cui respondit : Novi : et omnia itinera ejus frequenter ambulavi, et mansi apud Gabelum fratrem nostrum, qui moratur in Rages civitate Medorum, quæ posita est in monte Ecbatanis.

** Tobit 5:9

Cui Tobias ait : Sustine me obsecro, donec hæc ipsa nuntiem patri meo.

** Tobit 5:10

Tunc ingressus Tobias, indicavit universa hæc patri suo. Super quæ admiratus pater, rogavit ut introiret ad eum.

** Tobit 5:11

Ingressus itaque salutavit eum, et dixit : Gaudium tibi sit semper.

** Tobit 5:12

Et ait Tobias : Quale gaudium mihi erit, qui in tenebris sedeo, et lumen cæli non video ?

** Tobit 5:13

Cui ait juvenis : Forti animo esto : in proximo est ut a Deo cureris.

** Tobit 5:14

Dixit itaque illi Tobias : Numquid poteris perducere filium meum ad Gabelum in Rages civitatem Medorum ? et cum redieris, restituam tibi mercedem tuam.

** Tobit 5:15

Et dixit ei angelus : Ego ducam, et reducam eum ad te.

** Tobit 5:16

Cui Tobias respondit : Rogo te, indica mihi de qua domo aut de qua tribu es tu.

** Tobit 5:17

Cui Raphaël angelus dixit : Genus quæris mercenarii, an ipsum mercenarium qui cum filio tuo eat ?

** Tobit 5:18

sed ne forte sollicitum te reddam, ego sum Azarias Ananiæ magni filius.

** Tobit 5:19

Et Tobias respondit : Ex magno genere es tu. Sed peto ne irascaris quod voluerim cognoscere genus tuum.

** Tobit 5:20

Dixit autem illi angelus : Ego sanum ducam, et sanum tibi reducam filium tuum.

** Tobit 5:21

Respondens autem Tobias, ait : Bene ambuletis, et sit Deus in itinere vestro, et angelus ejus comitetur vobiscum.  

** Tobit 5:22

Tunc paratis omnibus quæ erant in via portanda, fecit Tobias vale patri suo et matri suæ, et ambulaverunt ambo simul.

** Tobit 5:23

Cumque profecti essent, cœpit mater ejus flere, et dicere : Baculum senectutis nostræ tulisti, et transmisisti a nobis.

** Tobit 5:24

Numquam fuisset ipsa pecunia, pro qua misisti eum :

** Tobit 5:25

sufficiebat enim nobis paupertas nostra, ut divitias computaremus hoc, quod videbamus filium nostrum.

** Tobit 5:26

Dixitque ei Tobias : Noli flere : salvus perveniet filius noster, et salvus revertetur ad nos, et oculi tui videbunt illum.

** Tobit 5:27

Credo enim quod angelus Dei bonus comitetur ei, et bene disponat omnia quæ circa eum geruntur, ita ut cum gaudio revertatur ad nos.

** Tobit 5:28

Ad hanc vocem cessavit mater ejus flere, et tacuit.   

* Tobit 6

** Tobit 6:1

Profectus est autem Tobias, et canis secutus est eum, et mansit prima mansione juxta fluvium Tigris.

** Tobit 6:2

Et exivit ut lavaret pedes suos, et ecce piscis immanis exivit ad devorandum eum.

** Tobit 6:3

Quem expavescens Tobias clamavit voce magna, dicens : Domine, invadit me.

** Tobit 6:4

Et dixit ei angelus : Apprehende branchiam ejus, et trahe eum ad te. Quod cum fecisset, attraxit eum in siccum, et palpitare cœpit ante pedes ejus.

** Tobit 6:5

Tunc dixit ei angelus : Exentera hunc piscem, et cor ejus, et fel, et jecur repone tibi : sunt enim hæc necessaria ad medicamenta utiliter.

** Tobit 6:6

Quod cum fecisset, assavit carnes ejus, et secum tulerunt in via : cetera salierunt, quæ sufficerent eis, quousque pervenirent in Rages civitatem Medorum.

** Tobit 6:7

Tunc interrogavit Tobias angelum, et dixit ei : Obsecro te, Azaria frater, ut dicas mihi quod remedium habebunt ista, quæ de pisce servare jussisti ?

** Tobit 6:8

Et respondens angelus, dixit ei : Cordis ejus particulam si super carbones ponas, fumus ejus extricat omne genus dæmoniorum sive a viro, sive a muliere, ita ut ultra non accedat ad eos.

** Tobit 6:9

Et fel valet ad ungendos oculos in quibus fuerit albugo, et sanabuntur.  

** Tobit 6:10

Et dixit ei Tobias : Ubi vis ut maneamus ?

** Tobit 6:11

Respondensque angelus, ait : Est hic Raguel nomine, vir propinquus de tribu tua, et hic habet filiam nomine Saram, sed neque masculum neque feminam ullam habet aliam præter eam.

** Tobit 6:12

Tibi debetur omnis substantia ejus, et oportet eam te accipere conjugem.

** Tobit 6:13

Pete ergo eam a patre ejus, et dabit tibi eam in uxorem.

** Tobit 6:14

Tunc respondit Tobias, et dixit : Audio quia tradita est septem viris, et mortui sunt : sed et hoc audivi, quia dæmonium occidit illos.

** Tobit 6:15

Timeo ergo, ne forte et mihi hæc eveniant : et cum sim unicus parentibus meis, deponam senectutem illorum cum tristitia ad inferos.

** Tobit 6:16

Tunc angelus Raphaël dixit ei : Audi me, et ostendam tibi qui sunt, quibus prævalere potest dæmonium.

** Tobit 6:17

Hi namque qui conjugium ita suscipiunt, ut Deum a se et a sua mente excludant, et suæ libidini ita vacent sicut equus et mulus quibus non est intellectus : habet potestatem dæmonium super eos.

** Tobit 6:18

Tu autem cum acceperis eam, ingressus cubiculum, per tres dies continens esto ab ea, et nihil aliud nisi orationibus vacabis cum ea.

** Tobit 6:19

Ipsa autem nocte, incenso jecore piscis, fugabitur dæmonium.

** Tobit 6:20

Secunda vero nocte in copulatione sanctorum patriarcharum admitteris.

** Tobit 6:21

Tertia autem nocte, benedictionem consequeris, ut filii ex vobis procreentur incolumes.

** Tobit 6:22

Transacta autem tertia nocte, accipies virginem cum timore Domini, amore filiorum magis quam libidine ductus, ut in semine Abrahæ benedictionem in filiis consequaris.   

* Tobit 7

** Tobit 7:1

Ingressi sunt autem ad Raguelem, et suscepit eos Raguel cum gaudio.

** Tobit 7:2

Intuensque Tobiam Raguel, dixit Annæ uxori suæ : Quam similis est juvenis iste consobrino meo !

** Tobit 7:3

Et cum hæc dixisset, ait : Unde estis juvenes fratres nostri ? At illi dixerunt : Ex tribu Nephthali sumus, ex captivitate Ninive.

** Tobit 7:4

Dixitque illis Raguel : Nostis Tobiam fratrem meum ? Qui dixerunt : Novimus.

** Tobit 7:5

Cumque multa bona loqueretur de eo, dixit angelus ad Raguelem : Tobias, de quo interrogas, pater istius est.

** Tobit 7:6

Et misit se Raguel, et cum lacrimis osculatus est eum, et plorans supra collum ejus

** Tobit 7:7

dixit : Benedictio sit tibi, fili mi, quia boni et optimi viri filius es.

** Tobit 7:8

Et Anna uxor ejus, et Sara ipsorum filia, lacrimatæ sunt.

** Tobit 7:9

Postquam autem locuti sunt, præcepit Raguel occidi arietem, et parari convivium. Cumque hortaretur eos discumbere ad prandium,

** Tobit 7:10

Tobias dixit : Hic ego hodie non manducabo neque bibam, nisi prius petitionem meam confirmes, et promittas mihi dare Saram filiam tuam.

** Tobit 7:11

Quo audito verbo Raguel expavit, sciens quid evenerit illis septem viris qui ingressi sunt ad eam : et timere cœpit ne forte et hunc similiter contingeret. Et cum nutaret, et non daret petenti ullum responsum,

** Tobit 7:12

dixit ei angelus : Noli timere dare eam isti, quoniam huic timenti Deum debetur conjux filia tua : propterea alius non potuit habere illam.

** Tobit 7:13

Tunc dixit Raguel : Non dubito quod Deus preces et lacrimas meas in conspectu suo admiserit.

** Tobit 7:14

Et credo quoniam ideo fecit vos venire ad me, ut ista conjungeretur cognationi suæ secundum legem Moysi : et nunc noli dubium gerere quod tibi eam tradam.

** Tobit 7:15

Et apprehendens dexteram filiæ suæ, dexteræ Tobiæ tradidit, dicens : Deus Abraham, et Deus Isaac, et Deus Jacob vobiscum sit, et ipse conjungat vos, impleatque benedictionem suam in vobis.

** Tobit 7:16

Et accepta carta, fecerunt conscriptionem conjugii.

** Tobit 7:17

Et post hæc epulati sunt, benedicentes Deum.

** Tobit 7:18

Vocavitque Raguel ad se Annam uxorem suam, et præcepit ei ut præpararet alterum cubiculum.

** Tobit 7:19

Et introduxit illuc Saram filiam suam, et lacrimata est.

** Tobit 7:20

Dixitque ei : Forti animo esto, filia mea : Dominus cæli det tibi gaudium pro tædio quod perpessa es.   

* Tobit 8

** Tobit 8:1

Postquam vero cœnaverunt, introduxerunt juvenem ad eam.

** Tobit 8:2

Recordatus itaque Tobias sermonum angeli, protulit de cassidili suo partem jecoris, posuitque eam super carbones vivos.

** Tobit 8:3

Tunc Raphaël angelus apprehendit dæmonium, et religavit illud in deserto superioris Ægypti.

** Tobit 8:4

Tunc hortatus est virginem Tobias, dixitque ei : Sara, exsurge, et deprecemur Deum hodie, et cras, et secundum cras : quia his tribus noctibus Deo jungimur ; tertia autem transacta nocte, in nostro erimus conjugio.

** Tobit 8:5

Filii quippe sanctorum sumus, et non possumus ita conjungi sicut gentes quæ ignorant Deum.

** Tobit 8:6

Surgentes autem pariter, instanter orabant ambo simul, ut sanitas daretur eis.

** Tobit 8:7

Dixitque Tobias : Domine Deus patrum nostrorum, benedicant te cæli et terræ, mareque et fontes, et flumina, et omnes creaturæ tuæ quæ in eis sunt.

** Tobit 8:8

Tu fecisti Adam de limo terræ, dedistique ei adjutorium Hevam.

** Tobit 8:9

Et nunc Domine, tu scis quia non luxuriæ causa accipio sororem meam conjugem, sed sola posteritatis dilectione, in qua benedicatur nomen tuum in sæcula sæculorum.

** Tobit 8:10

Dixit quoque Sara : Miserere nobis Domine, miserere nobis, et consenescamus ambo pariter sani.

** Tobit 8:11

Et factum est circa pullorum cantum, accersiri jussit Raguel servos suos, et abierunt cum eo pariter ut foderent sepulchrum.

** Tobit 8:12

Dicebat enim : Ne forte simili modo evenerit ei, quo et ceteris illis septem viris qui sunt ingressi ad eam.

** Tobit 8:13

Cumque parassent fossam, reversus Raguel ad uxorem suam, dixit ei :

** Tobit 8:14

Mitte unam de ancillis tuis, et videat si mortuus est, ut sepeliam eum antequam illucescat dies.

** Tobit 8:15

At illa misit unam ex ancillis suis. Quæ ingressa cubiculum, reperit eos salvos et incolumes, secum pariter dormientes.

** Tobit 8:16

Et reversa nuntiavit bonum nuntium : et benedixerunt Dominum, Raguel videlicet et Anna uxor ejus,

** Tobit 8:17

et dixerunt : Benedicimus te, Domine Deus Israël, quia non contigit quemadmodum putabamus.

** Tobit 8:18

Fecisti enim nobiscum misericordiam tuam, et exclusisti a nobis inimicum persequentem nos.

** Tobit 8:19

Misertus es autem duobus unicis. Fac eos, Domine, plenius benedicere te, et sacrificium tibi laudis tuæ et suæ sanitatis offerre, ut cognoscat universitas gentium quia tu es Deus solus in universa terra.

** Tobit 8:20

Statimque præcepit servis suis Raguel ut replerent fossam quam fecerant priusquam elucesceret.

** Tobit 8:21

Uxori autem suæ dixit ut instrueret convivium, et præpararet omnia quæ in cibos erant iter agentibus necessaria.

** Tobit 8:22

Duas quoque pingues vaccas, et quatuor arietes, occidi fecit, et parari epulas omnibus vicinis suis, cunctisque amicis.

** Tobit 8:23

Et adjuravit Raguel Tobiam ut duas hebdomadas moraretur apud se.

** Tobit 8:24

De omnibus autem quæ possidebat Raguel, dimidiam partem dedit Tobiæ, et fecit scripturam, ut pars dimidia quæ supererat, post obitum eorum Tobiæ dominio deveniret.   

* Tobit 9

** Tobit 9:1

Tunc vocavit Tobias angelum ad se, quem quidem hominem existimabat, dixitque ei : Azaria frater, peto ut auscultes verba mea.

** Tobit 9:2

Si meipsum tradam tibi servum, non ero condignus providentiæ tuæ :

** Tobit 9:3

tamen obsecro te ut assumas tibi animalia sive servitia, et vadas ad Gabelum in Rages civitatem Medorum, reddasque ei chirographum suum, et recipias ab eo pecuniam, et roges eum venire ad nuptias meas.

** Tobit 9:4

Scis enim ipse quoniam numerat pater meus dies, et si tardavero una die plus, contristatur anima ejus.

** Tobit 9:5

Et certe vides quomodo adjuravit me Raguel, cujus adjuramentum spernere non possum.

** Tobit 9:6

Tunc Raphaël assumens quatuor ex servis Raguelis, et duos camelos, in Rages civitatem Medorum perrexit : et inveniens Gabelum, reddidit ei chirographum suum, et recepit ab eo omnem pecuniam.

** Tobit 9:7

Indicavitque ei de Tobia filio Tobiæ omnia quæ gesta sunt, fecitque eum secum venire ad nuptias.

** Tobit 9:8

Cumque ingressus esset domum Raguelis, invenit Tobiam discumbentem : et exiliens, osculati sunt se invicem : et flevit Gabelus, benedixitque Deum,

** Tobit 9:9

et dixit : Benedicat te Deus Israël, quia filius es optimi viri et justi, et timentis Deum, et eleemosynas facientis :

** Tobit 9:10

et dicatur benedictio super uxorem tuam, et super parentes vestros,

** Tobit 9:11

et videatis filios vestros, et filios filiorum vestrorum, usque in tertiam et quartam generationem : et sit semen vestrum benedictum a Deo Israël, qui regnat in sæcula sæculorum.

** Tobit 9:12

Cumque omnes dixissent : Amen : accesserunt ad convivium : sed et cum timore Domini nuptiarum convivium exercebant.   

* Tobit 10

** Tobit 10:1

Cum vero moras faceret Tobias, causa nuptiarum, sollicitus erat pater ejus Tobias, dicens : Putas quare moratur filius meus, aut quare detentus est ibi ?

** Tobit 10:2

Putasne Gabelus mortuus est, et nemo reddet illi pecuniam ?

** Tobit 10:3

Cœpit autem contristari nimis ipse, et Anna uxor ejus cum eo : et cœperunt ambo simul flere, eo quod die statuto minime reverteretur filius eorum ad eos.

** Tobit 10:4

Flebat igitur mater ejus irremediabilibus lacrimis, atque dicebat : Heu, heu me, fili mi ! ut quid te misimus peregrinari, lumen oculorum nostrorum, baculum senectutis nostræ, solatium vitæ nostræ, spem posteritatis nostræ ?

** Tobit 10:5

omnia simul in te uno habentes, te non debuimus dimittere a nobis.

** Tobit 10:6

Cui dicebat Tobias : Tace, et noli turbari : sanus est filius noster : satis fidelis est vir ille, cum quo misimus eum.

** Tobit 10:7

Illa autem nullo modo consolari poterat, sed quotidie exiliens circumspiciebat, et circuibat vias omnes per quas spes remeandi videbatur, ut procul videret eum, si fieri posset, venientem.

** Tobit 10:8

At vero Raguel dicebat ad generum suum : Mane hic, et ego mittam nuntium salutis de te ad Tobiam patrem tuum.

** Tobit 10:9

Cui Tobias ait : Ego novi quia pater meus et mater mea modo dies computant, et cruciatur spiritus eorum in ipsis.

** Tobit 10:10

Cumque verbis multis rogaret Raguel Tobiam, et ille eum nulla ratione vellet audire, tradidit ei Saram, et dimidiam partem omnis substantiæ suæ in pueris, in puellis, in pecudibus, in camelis, et in vaccis, et in pecunia multa : et salvum atque gaudentem dimisit eum a se,

** Tobit 10:11

dicens : Angelus Domini sanctus sit in itinere vestro, perducatque vos incolumes, et inveniatis omnia recte circa parentes vestros, et videant oculi mei filios vestros priusquam moriar.

** Tobit 10:12

Et apprehendentes parentes filiam suam, osculati sunt eam : et dimiserunt ire,

** Tobit 10:13

monentes eam honorare soceros, diligere maritum, regere familiam, gubernare domum, et seipsam irreprehensibilem exhibere.   

* Tobit 11

** Tobit 11:1

Cumque reverterentur, pervenerunt ad Charan, quæ est in medio itinere contra Niniven, undecimo die.

** Tobit 11:2

Dixitque angelus : Tobia frater, scis quemadmodum reliquisti patrem tuum.

** Tobit 11:3

Si placet itaque tibi, præcedamus, et lento gradu sequantur iter nostrum familiæ, simul cum conjuge tua, et cum animalibus.

** Tobit 11:4

Cumque hoc placuisset ut irent, dixit Raphaël ad Tobiam : Tolle tecum ex felle piscis : erit enim necessarium. Tulit itaque Tobias ex felle illo, et abierunt.

** Tobit 11:5

Anna autem sedebat secus viam quotidie in supercilio montis, unde respicere poterat de longinquo.

** Tobit 11:6

Et dum ex eodem loco specularetur adventum ejus, vidit a longe, et illico agnovit venientem filium suum : currensque nuntiavit viro suo, dicens : Ecce venit filius tuus.

** Tobit 11:7

Dixitque Raphaël ad Tobiam : At ubi introieris domum tuam, statim adora Dominum Deum tuum : et gratias agens ei, accede ad patrem tuum, et osculare eum.

** Tobit 11:8

Statimque lini super oculos ejus ex felle isto piscis, quod portas tecum : scias enim quoniam mox aperientur oculi ejus, et videbit pater tuus lumen cæli, et in aspectu tuo gaudebit.

** Tobit 11:9

Tunc præcucurrit canis, qui simul fuerat in via : et quasi nuntius adveniens, blandimento suæ caudæ gaudebat.

** Tobit 11:10

Et consurgens cæcus pater ejus, cœpit offendens pedibus currere : et data manu puero, occurrit obviam filio suo.

** Tobit 11:11

Et suscipiens osculatus est eum cum uxore sua, et cœperunt ambo flere præ gaudio.

** Tobit 11:12

Cumque adorassent Deum, et gratias egissent, consederunt.  

** Tobit 11:13

Tunc sumens Tobias de felle piscis, linivit oculos patris sui.

** Tobit 11:14

Et sustinuit quasi dimidiam fere horam : et cœpit albugo ex oculis ejus, quasi membrana ovi, egredi.

** Tobit 11:15

Quam apprehendens Tobias, traxit ab oculis ejus : statimque visum recepit.

** Tobit 11:16

Et glorificabant Deum, ipse videlicet et uxor ejus, et omnes qui sciebant eum.

** Tobit 11:17

Dicebatque Tobias : Benedico te, Domine Deus Israël, quia tu castigasti me, et tu salvasti me : et ecce ego video Tobiam filium meum.

** Tobit 11:18

Ingressa est etiam post septem dies Sara uxor filii ejus et omnis familia sana, et pecora, et cameli, et pecunia multa uxoris ; sed et illa pecunia, quam receperat a Gabelo.

** Tobit 11:19

Et narravit parentibus suis omnia beneficia Dei, quæ fecisset circa eum per hominem qui eum duxerat.

** Tobit 11:20

Veneruntque Achior et Nabath consobrini Tobiæ gaudentes ad Tobiam, et congratulantes ei de omnibus bonis quæ circa illum ostenderat Deus.

** Tobit 11:21

Et per septem dies epulantes, omnes cum gaudio magno gavisi sunt.   

* Tobit 12

** Tobit 12:1

Tunc vocavit ad se Tobias filium suum, dixitque ei : Quid possumus dare viro isti sancto, qui venit tecum ?

** Tobit 12:2

Respondens Tobias, dixit patri suo : Pater, quam mercedem dabimus ei ? aut quid dignum poterit esse beneficiis ejus ?

** Tobit 12:3

Me duxit et reduxit sanum, pecuniam a Gabelo ipse recepit, uxorem ipse me habere fecit, et dæmonium ab ea ipse compescuit : gaudium parentibus ejus fecit, meipsum a devoratione piscis eripuit, te quoque videre fecit lumen cæli, et bonis omnibus per eum repleti sumus. Quid illi ad hæc poterimus dignum dare ?

** Tobit 12:4

Sed peto te, pater mi, ut roges eum, si forte dignabitur medietatem de omnibus quæ allata sunt, sibi assumere.

** Tobit 12:5

Et vocantes eum, pater scilicet et filius, tulerunt eum in partem : et rogare cœperunt ut dignaretur dimidiam partem omnium quæ attulerant acceptam habere.  

** Tobit 12:6

Tunc dixit eis occulte : Benedicite Deum cæli, et coram omnibus viventibus confitemini ei, quia fecit vobiscum misericordiam suam.

** Tobit 12:7

Etenim sacramentum regis abscondere bonum est : opera autem Dei revelare et confiteri honorificum est.

** Tobit 12:8

Bona est oratio cum jejunio, et eleemosyna magis quam thesauros auri recondere :

** Tobit 12:9

quoniam eleemosyna a morte liberat, et ipsa est quæ purgat peccata, et facit invenire misericordiam et viam æternam.

** Tobit 12:10

Qui autem faciunt peccatum et iniquitatem, hostes sunt animæ suæ.

** Tobit 12:11

Manifesto ergo vobis veritatem, et non abscondam a vobis occultum sermonem.

** Tobit 12:12

Quando orabas cum lacrimis, et sepeliebas mortuos, et derelinquebas prandium tuum, et mortuos abscondebas per diem in domo tua, et nocte sepeliebas eos, ego obtuli orationem tuam Domino.

** Tobit 12:13

Et quia acceptus eras Deo, necesse fuit ut tentatio probaret te.

** Tobit 12:14

Et nunc misit me Dominus ut curarem te, et Saram uxorem filii tui a dæmonio liberarem.

** Tobit 12:15

Ego enim sum Raphaël angelus, unus ex septem qui adstamus ante Dominum.

** Tobit 12:16

Cumque hæc audissent, turbati sunt, et trementes ceciderunt super terram in faciem suam.

** Tobit 12:17

Dixitque eis angelus : Pax vobis : nolite timere.

** Tobit 12:18

Etenim cum essem vobiscum, per voluntatem Dei eram : ipsum benedicite, et cantate illi.

** Tobit 12:19

Videbar quidem vobiscum manducare et bibere : sed ego cibo invisibili, et potu qui ab hominibus videri non potest, utor.

** Tobit 12:20

Tempus est ergo ut revertar ad eum qui me misit : vos autem benedicite Deum, et narrate omnia mirabilia ejus.

** Tobit 12:21

Et cum hæc dixisset, ab aspectu eorum ablatus est, et ultra eum videre non potuerunt.

** Tobit 12:22

Tunc prostrati per horas tres in faciem, benedixerunt Deum : et exsurgentes narraverunt omnia mirabilia ejus.   

* Tobit 13

** Tobit 13:1

Aperiens autem Tobias senior os suum, benedixit Dominum, et dixit :   Magnus es, Domine, in æternum,  et in omnia sæcula regnum tuum : 

** Tobit 13:2

quoniam tu flagellas, et salvas ;  deducis ad inferos, et reducis :  et non est qui effugiat manum tuam. 

** Tobit 13:3

Confitemini Domino, filii Israël,  et in conspectu gentium laudate eum : 

** Tobit 13:4

quoniam ideo dispersit vos inter gentes quæ ignorant eum,  ut vos enarretis mirabilia ejus,  et faciatis scire eos  quia non est alius deus omnipotens præter eum. 

** Tobit 13:5

Ipse castigavit nos propter iniquitates nostras,  et ipse salvabit nos propter misericordiam suam. 

** Tobit 13:6

Aspicite ergo quæ fecit nobiscum,  et cum timore et tremore confitemini illi :  regemque sæculorum exaltate in operibus vestris. 

** Tobit 13:7

Ego autem in terra captivitatis meæ confitebor illi :  quoniam ostendit majestatem suam in gentem peccatricem. 

** Tobit 13:8

Convertimini itaque peccatores,  et facite justitiam coram Deo,  credentes quod faciat vobiscum misericordiam suam. 

** Tobit 13:9

Ego autem et anima mea in eo lætabimur. 

** Tobit 13:10

Benedicite Dominum omnes electi ejus :  agite dies lætitiæ, et confitemini illi. 

** Tobit 13:11

Jerusalem civitas Dei,  castigavit te Dominus in operibus manuum tuarum. 

** Tobit 13:12

Confitere Domino in bonis tuis,  et benedic Deum sæculorum :  ut reædificet in te tabernaculum suum,  et revocet ad te omnes captivos,  et gaudeas in omnia sæcula sæculorum. 

** Tobit 13:13

Luce splendida fulgebis,  et omnes fines terræ adorabunt te. 

** Tobit 13:14

Nationes ex longinquo ad te venient,  et munera deferentes adorabunt in te Dominum,  et terram tuam in sanctificationem habebunt : 

** Tobit 13:15

nomen enim magnum invocabunt in te. 

** Tobit 13:16

Maledicti erunt qui contempserint te,  et condemnati erunt omnes qui blasphemaverint te :  benedictique erunt qui ædificaverint te. 

** Tobit 13:17

Tu autem lætaberis in filiis tuis,  quoniam omnes benedicentur,  et congregabuntur ad Dominum. 

** Tobit 13:18

Beati omnes qui diligunt te,  et qui gaudent super pace tua. 

** Tobit 13:19

Anima mea, benedic Dominum,  quoniam liberavit Jerusalem civitatem suam  a cunctis tribulationibus ejus  Dominus Deus noster. 

** Tobit 13:20

Beatus ero si fuerint reliquiæ seminis mei  ad videndam claritatem Jerusalem. 

** Tobit 13:21

Portæ Jerusalem ex sapphiro et smaragdo ædificabuntur,  et ex lapide pretioso omnis circuitus murorum ejus. 

** Tobit 13:22

Ex lapide candido et mundo omnes plateæ ejus sternentur,  et per vicos ejus alleluja cantabitur. 

** Tobit 13:23

Benedictus Dominus, qui exaltavit eam,  et sit regnum ejus in sæcula sæculorum super eam. Amen.  

* Tobit 14

** Tobit 14:1

Et consummati sunt sermones Tobiæ. Et postquam illuminatus est Tobias, vixit annis quadraginta duobus, et vidit filios nepotum suorum.

** Tobit 14:2

Completis itaque annis centum duobus, sepultus est honorifice in Ninive.

** Tobit 14:3

Quinquaginta namque et sex annorum lumen oculorum amisit, sexagenarius vero recepit.

** Tobit 14:4

Reliquum vero vitæ suæ in gaudio fuit, et cum bono profectu timoris Dei perrexit in pace.

** Tobit 14:5

In hora autem mortis suæ vocavit ad se Tobiam filium suum, et septem juvenes filios ejus nepotes suos, dixitque eis :

** Tobit 14:6

Prope erit interitus Ninive : non enim excidit verbum Domini : et fratres nostri, qui dispersi sunt a terra Israël, revertentur ad eam.

** Tobit 14:7

Omnis autem deserta terra ejus replebitur, et domus Dei, quæ in ea incensa est, iterum reædificabitur : ibique revertentur omnes timentes Deum,

** Tobit 14:8

et relinquent gentes idola sua, et venient in Jerusalem, et inhabitabunt in ea :

** Tobit 14:9

et gaudebunt in ea omnes reges terræ, adorantes regem Israël.

** Tobit 14:10

Audite ergo, filii mei, patrem vestrum : servite Domino in veritate, et inquirite ut faciatis quæ placita sunt illi :

** Tobit 14:11

et filiis vestris mandate ut faciant justitias et eleemosynas, ut sint memores Dei, et benedicant eum in omni tempore in veritate, et in tota virtute sua.

** Tobit 14:12

Nunc ergo filii, audite me, et nolite manere hic : sed quacumque die sepelieritis matrem vestram circa me in uno sepulchro, ex eo dirigite gressus vestros ut exeatis hinc :

** Tobit 14:13

video enim quia iniquitas ejus finem dabit ei.

** Tobit 14:14

Factum est autem post obitum matris suæ, Tobias abscessit ex Ninive cum uxore sua, et filiis, et filiorum filiis, et reversus est ad soceros suos :

** Tobit 14:15

invenitque eos incolumes in senectute bona : et curam eorum gessit, et ipse clausit oculos eorum : et omnem hæreditatem domus Raguelis ipse percepit : viditque quintam generationem, filios filiorum suorum.

** Tobit 14:16

Et completis annis nonaginta novem in timore Domini, cum gaudio sepelierunt eum.

** Tobit 14:17

Omnis autem cognatio ejus et omnis generatio ejus in bona vita et in sancta conversatione permansit, ita ut accepti essent tam Deo quam hominibus, et cunctis habitantibus in terra.    

