* Wisdom 1

** Wisdom 1:1

Diligite justitiam, qui judicatis terram.  Sentite de Domino in bonitate,  et in simplicitate cordis quærite illum : 

** Wisdom 1:2

quoniam invenitur ab his qui non tentant illum,  apparet autem eis qui fidem habent in illum. 

** Wisdom 1:3

Perversæ enim cogitationes separant a Deo ;  probata autem virtus corripit insipientes. 

** Wisdom 1:4

Quoniam in malevolam animam non introibit sapientia,  nec habitabit in corpore subdito peccatis. 

** Wisdom 1:5

Spiritus enim sanctus disciplinæ effugiet fictum,  et auferet se a cogitationibus quæ sunt sine intellectu,  et corripietur a superveniente iniquitate. 

** Wisdom 1:6

Benignus est enim spiritus sapientiæ,  et non liberabit maledicum a labiis suis :  quoniam renum illius testis est Deus,  et cordis illius scrutator est verus,  et linguæ ejus auditor. 

** Wisdom 1:7

Quoniam spiritus Domini replevit orbem terrarum,  et hoc quod continet omnia, scientiam habet vocis. 

** Wisdom 1:8

Propter hoc qui loquitur iniqua non potest latere,  nec præteriet illum corripiens judicium. 

** Wisdom 1:9

In cogitationibus enim impii interrogatio erit ;  sermonum autem illius auditio ad Deum veniet,  ad correptionem iniquitatum illius. 

** Wisdom 1:10

Quoniam auris zeli audit omnia,  et tumultus murmurationum non abscondetur. 

** Wisdom 1:11

Custodite ergo vos a murmuratione quæ nihil prodest,  et a detractione parcite linguæ :  quoniam sermo obscurus in vacuum non ibit,  os autem quod mentitur occidit animam. 

** Wisdom 1:12

Nolite zelare mortem in errore vitæ vestræ,  neque acquiratis perditionem in operibus manuum vestrarum. 

** Wisdom 1:13

Quoniam Deus mortem non fecit,  nec lætatur in perditione vivorum. 

** Wisdom 1:14

Creavit enim ut essent omnia,  et sanabiles fecit nationes orbis terrarum :  et non est in illis medicamentum exterminii,  nec inferorum regnum in terra. 

** Wisdom 1:15

Justitia enim perpetua est, et immortalis. 

** Wisdom 1:16

Impii autem manibus et verbis accersierunt illam,  et æstimantes illam amicam, defluxerunt ;  et sponsiones posuerunt ad illam,  quoniam digni sunt qui sint ex parte illius.  

* Wisdom 2

** Wisdom 2:1

Dixerunt enim cogitantes apud se non recte :  Exiguum et cum tædio est tempus vitæ nostræ,  et non est refrigerium in fine hominis,  et non est qui agnitus sit reversus ab inferis. 

** Wisdom 2:2

Quia ex nihilo nati sumus,  et post hoc erimus tamquam non fuerimus.  Quoniam fumus flatus est in naribus nostris,  et sermo scintilla ad commovendum cor nostrum : 

** Wisdom 2:3

qua extincta, cinis erit corpus nostrum,  et spiritus diffundetur tamquam mollis aër ;  et transibit vita nostra tamquam vestigium nubis,  et sicut nebula dissolvetur quæ fugata est a radiis solis,  et a calore illius aggravata. 

** Wisdom 2:4

Et nomen nostrum oblivionem accipiet per tempus,  et nemo memoriam habebit operum nostrorum. 

** Wisdom 2:5

Umbræ enim transitus est tempus nostrum,  et non est reversio finis nostri :  quoniam consignata est, et nemo revertitur. 

** Wisdom 2:6

Venite ergo, et fruamur bonis quæ sunt,  et utamur creatura tamquam in juventute celeriter. 

** Wisdom 2:7

Vino pretioso et unguentis nos impleamus,  et non prætereat nos flos temporis. 

** Wisdom 2:8

Coronemus nos rosis antequam marcescant ;  nullum pratum sit quod non pertranseat luxuria nostra : 

** Wisdom 2:9

nemo nostrum exsors sit luxuriæ nostræ.  Ubique relinquamus signa lætitiæ,  quoniam hæc est pars nostra, et hæc est sors. 

** Wisdom 2:10

Opprimamus pauperem justum, et non parcamus viduæ,  nec veterani revereamur canos multi temporis : 

** Wisdom 2:11

sit autem fortitudo nostra lex justitiæ ;  quod enim infirmum est, inutile invenitur. 

** Wisdom 2:12

Circumveniamus ergo justum, quoniam inutilis est nobis,  et contrarius est operibus nostris,  et improperat nobis peccata legis,  et diffamat in nos peccata disciplinæ nostræ. 

** Wisdom 2:13

Promittit se scientiam Dei habere,  et filium Dei se nominat. 

** Wisdom 2:14

Factus est nobis in traductionem cogitationum nostrarum. 

** Wisdom 2:15

Gravis est nobis etiam ad videndum,  quoniam dissimilis est aliis vita illius,  et immutatæ sunt viæ ejus. 

** Wisdom 2:16

Tamquam nugaces æstimati sumus ab illo,  et abstinet se a viis nostris tamquam ab immunditiis,  et præfert novissima justorum,  et gloriatur patrem se habere Deum. 

** Wisdom 2:17

Videamus ergo si sermones illius veri sint,  et tentemus quæ ventura sunt illi,  et sciemus quæ erunt novissima illius. 

** Wisdom 2:18

Si enim est verus filius Dei, suscipiet illum,  et liberabit eum de manibus contrariorum. 

** Wisdom 2:19

Contumelia et tormento interrogemus eum,  ut sciamus reverentiam ejus,  et probemus patientiam illius. 

** Wisdom 2:20

Morte turpissima condemnemus eum ;  erit enim ei respectus ex sermonibus illius. 

** Wisdom 2:21

Hæc cogitaverunt, et erraverunt :  excæcavit enim illos malitia eorum. 

** Wisdom 2:22

Et nescierunt sacramenta Dei :  neque mercedem speraverunt justitiæ,  nec judicaverunt honorem animarum sanctarum. 

** Wisdom 2:23

Quoniam Deus creavit hominem inexterminabilem,  et ad imaginem similitudinis suæ fecit illum. 

** Wisdom 2:24

Invidia autem diaboli mors introivit in orbem terrarum : 

** Wisdom 2:25

imitantur autem illum qui sunt ex parte illius.  

* Wisdom 3

** Wisdom 3:1

Justorum autem animæ in manu Dei sunt,  et non tanget illos tormentum mortis. 

** Wisdom 3:2

Visi sunt oculis insipientium mori,  et æstimata est afflictio exitus illorum, 

** Wisdom 3:3

et quod a nobis est iter exterminium ;  illi autem sunt in pace : 

** Wisdom 3:4

etsi coram hominibus tormenta passi sunt,  spes illorum immortalitate plena est. 

** Wisdom 3:5

In paucis vexati sunt, in multis bene disponentur,  quoniam Deus tentavit eos,  et invenit illos dignos se. 

** Wisdom 3:6

Tamquam aurum in fornace probavit illos,  et quasi holocausti hostiam accepit illos,  et in tempore erit respectus illorum. 

** Wisdom 3:7

Fulgebunt justi  et tamquam scintillæ in arundineto discurrent. 

** Wisdom 3:8

Judicabunt nationes, et dominabuntur populis,  et regnabit Dominus illorum in perpetuum. 

** Wisdom 3:9

Qui confidunt in illo intelligent veritatem,  et fideles in dilectione acquiescent illi,  quoniam donum et pax est electis ejus. 

** Wisdom 3:10

Impii autem secundum quæ cogitaverunt  correptionem habebunt :  qui neglexerunt justum,  et a Domino recesserunt. 

** Wisdom 3:11

Sapientiam enim et disciplinam qui abjicit infelix est :  et vacua est spes illorum,  et labores sine fructu,  et inutilia opera eorum. 

** Wisdom 3:12

Mulieres eorum insensatæ sunt,  et nequissimi filii eorum. 

** Wisdom 3:13

Maledicta creatura eorum, quoniam felix est sterilis ;  et incoinquinata, quæ nescivit thorum in delicto,  habebit fructum in respectione animarum sanctarum ; 

** Wisdom 3:14

et spado qui non operatus est per manus suas iniquitatem,  nec cogitavit adversus Deum nequissima :  dabitur enim illi fidei donum electum,  et sors in templo Dei acceptissima. 

** Wisdom 3:15

Bonorum enim laborum gloriosus est fructus,  et quæ non concidat radix sapientiæ. 

** Wisdom 3:16

Filii autem adulterorum in inconsummatione erunt,  et ab iniquo thoro semen exterminabitur. 

** Wisdom 3:17

Et si quidem longæ vitæ erunt, in nihilum computabuntur,  et sine honore erit novissima senectus illorum : 

** Wisdom 3:18

et si celerius defuncti fuerint, non habebunt spem,  nec in die agnitionis allocutionem. 

** Wisdom 3:19

Nationis enim iniquæ diræ sunt consummationes.  

* Wisdom 4

** Wisdom 4:1

O quam pulchra est casta generatio, cum claritate !  immortalis est enim memoria illius,  quoniam et apud Deum nota est, et apud homines. 

** Wisdom 4:2

Cum præsens est, imitantur illam,  et desiderant eam cum se eduxerit ;  et in perpetuum coronata triumphat,  incoinquinatorum certaminum præmium vincens. 

** Wisdom 4:3

Multigena autem impiorum multitudo non erit utilis,  et spuria vitulamina non dabunt radices altas,  nec stabile firmamentum collocabunt. 

** Wisdom 4:4

Etsi in ramis in tempore germinaverint,  infirmiter posita, a vento commovebuntur,  et a nimietate ventorum eradicabuntur. 

** Wisdom 4:5

Confringentur enim rami inconsummati ;  et fructus illorum inutiles et acerbi ad manducandum,  et ad nihilum apti. 

** Wisdom 4:6

Ex iniquis enim somnis filii qui nascuntur,  testes sunt nequitiæ adversus parentes in interrogatione sua. 

** Wisdom 4:7

Justus autem si morte præoccupatus fuerit,  in refrigerio erit ; 

** Wisdom 4:8

senectus enim venerabilis est non diuturna,  neque annorum numero computata :  cani autem sunt sensus hominis, 

** Wisdom 4:9

et ætas senectutis vita immaculata. 

** Wisdom 4:10

Placens Deo factus est dilectus,  et vivens inter peccatores translatus est. 

** Wisdom 4:11

Raptus est, ne malitia mutaret intellectum ejus,  aut ne fictio deciperet animam illius. 

** Wisdom 4:12

Fascinatio enim nugacitatis obscurat bona,  et inconstantia concupiscentiæ transvertit sensum sine malitia. 

** Wisdom 4:13

Consummatus in brevi,  explevit tempora multa ; 

** Wisdom 4:14

placita enim erat Deo anima illius :  propter hoc properavit educere illum de medio iniquitatum.  Populi autem videntes, et non intelligentes,  nec ponentes in præcordiis talia, 

** Wisdom 4:15

quoniam gratia Dei et misericordia est in sanctos ejus,  et respectus in electos illius. 

** Wisdom 4:16

Condemnat autem justus mortuus vivos impios,  et juventus celerius consummata longam vitam injusti. 

** Wisdom 4:17

Videbunt enim finem sapientis,  et non intelligent quid cogitaverit de illo Deus,  et quare munierit illum Dominus. 

** Wisdom 4:18

Videbunt, et contemnent eum ;  illos autem Dominus irridebit. 

** Wisdom 4:19

Et erunt post hæc decidentes sine honore,  et in contumelia inter mortuos in perpetuum :  quoniam disrumpet illos inflatos sine voce,  et commovebit illos a fundamentis,  et usque ad supremum desolabuntur,  et erunt gementes, et memoria illorum peribit. 

** Wisdom 4:20

Venient in cogitatione peccatorum suorum timidi,  et traducent illos ex adverso iniquitates ipsorum.  

* Wisdom 5

** Wisdom 5:1

Tunc stabunt justi in magna constantia  adversus eos qui se angustiaverunt,  et qui abstulerunt labores eorum. 

** Wisdom 5:2

Videntes turbabuntur timore horribili,  et mirabuntur in subitatione insperatæ salutis ; 

** Wisdom 5:3

dicentes intra se, pœnitentiam agentes,  et præ angustia spiritus gementes :  Hi sunt quos habuimus aliquando in derisum,  et in similitudinem improperii. 

** Wisdom 5:4

Nos insensati, vitam illorum æstimabamus insaniam,  et finem illorum sine honore ; 

** Wisdom 5:5

ecce quomodo computati sunt inter filios Dei,  et inter sanctos sors illorum est. 

** Wisdom 5:6

Ergo erravimus a via veritatis,  et justitiæ lumen non luxit nobis,  et sol intelligentiæ non est ortus nobis. 

** Wisdom 5:7

Lassati sumus in via iniquitatis et perditionis,  et ambulavimus vias difficiles :  viam autem Domini ignoravimus. 

** Wisdom 5:8

Quid nobis profuit superbia ?  aut divitiarum jactantia quid contulit nobis ? 

** Wisdom 5:9

Transierunt omnia illa tamquam umbra,  et tamquam nuntius percurrens, 

** Wisdom 5:10

et tamquam navis quæ pertransit fluctuantem aquam,  cujus cum præterierit non est vestigium invenire,  neque semitam carinæ illius in fluctibus ; 

** Wisdom 5:11

aut tamquam avis quæ transvolat in aëre,  cujus nullum invenitur argumentum itineris,  sed tantum sonitus alarum verberans levem ventum,  et scindens per vim itineris aërem :  commotis alis transvolavit,  et post hoc nullum signum invenitur itineris illius ; 

** Wisdom 5:12

aut tamquam sagitta emissa in locum destinatum,  divisus aër continuo in se reclusus est,  ut ignoretur transitus illius : 

** Wisdom 5:13

sic et nos nati continuo desivimus esse ;  et virtutis quidem nullum signum valuimus ostendere,  in malignitate autem nostra consumpti sumus. 

** Wisdom 5:14

Talia dixerunt in inferno hi qui peccaverunt : 

** Wisdom 5:15

quoniam spes impii tamquam lanugo est quæ a vento tollitur,  et tamquam spuma gracilis quæ a procella dispergitur,  et tamquam fumus qui a vento diffusus est,  et tamquam memoria hospitis unius diei prætereuntis. 

** Wisdom 5:16

Justi autem in perpetuum vivent,  et apud Dominum est merces eorum,  et cogitatio illorum apud Altissimum. 

** Wisdom 5:17

Ideo accipient regnum decoris,  et diadema speciei de manu Domini :  quoniam dextera sua teget eos,  et brachio sancto suo defendet illos. 

** Wisdom 5:18

Accipiet armaturam zelus illius,  et armabit creaturam ad ultionem inimicorum. 

** Wisdom 5:19

Induet pro thorace justitiam,  et accipiet pro galea judicium certum ; 

** Wisdom 5:20

sumet scutum inexpugnabile æquitatem. 

** Wisdom 5:21

Acuet autem duram iram in lanceam,  et pugnabit cum illo orbis terrarum contra insensatos. 

** Wisdom 5:22

Ibunt directe emissiones fulgurum,  et tamquam a bene curvato arcu nubium exterminabuntur,  et ad certum locum insilient. 

** Wisdom 5:23

Et a petrosa ira plenæ mittentur grandines ;  excandescet in illos aqua maris,  et flumina concurrent duriter. 

** Wisdom 5:24

Contra illos stabit spiritus virtutis,  et tamquam turbo venti dividet illos ;  et ad eremum perducet omnem terram iniquitas illorum,  et malignitas evertet sedes potentium.  

* Wisdom 6

** Wisdom 6:1

Melior est sapientia quam vires,  et vir prudens quam fortis. 

** Wisdom 6:2

Audite ergo, reges, et intelligite ;  discite, judices finium terræ. 

** Wisdom 6:3

Præbete aures, vos qui continetis multitudines,  et placetis vobis in turbis nationum. 

** Wisdom 6:4

Quoniam data est a Domino potestas vobis,  et virtus ab Altissimo :  qui interrogabit opera vestra, et cogitationes scrutabitur. 

** Wisdom 6:5

Quoniam cum essetis ministri regni illius,  non recte judicastis, nec custodistis legem justitiæ,  neque secundum voluntatem Dei ambulastis. 

** Wisdom 6:6

Horrende et cito apparebit vobis,  quoniam judicium durissimum his qui præsunt fiet. 

** Wisdom 6:7

Exiguo enim conceditur misericordia ;  potentes autem potenter tormenta patientur. 

** Wisdom 6:8

Non enim subtrahet personam cujusquam Deus,  nec verebitur magnitudinem ejus cujusquam,  quoniam pusillum et magnum ipse fecit,  et æqualiter cura est illi de omnibus. 

** Wisdom 6:9

Fortioribus autem fortior instat cruciatio. 

** Wisdom 6:10

Ad vos ergo, reges, sunt hi sermones mei :  ut discatis sapientiam, et non excidatis. 

** Wisdom 6:11

Qui enim custodierint justa juste, justificabuntur ;  et qui didicerint ista, invenient quid respondeant. 

** Wisdom 6:12

Concupiscite ergo sermones meos ;  diligite illos, et habebitis disciplinam. 

** Wisdom 6:13

Clara est, et quæ numquam marcescit, sapientia :  et facile videtur ab his qui diligunt eam,  et invenitur ab his qui quærunt illam. 

** Wisdom 6:14

Præoccupat qui se concupiscunt,  ut illis se prior ostendat. 

** Wisdom 6:15

Qui de luce vigilaverit ad illam non laborabit ;  assidentem enim illam foribus suis inveniet. 

** Wisdom 6:16

Cogitare ergo de illa sensus est consummatus,  et qui vigilaverit propter illam cito securus erit. 

** Wisdom 6:17

Quoniam dignos se ipsa circuit quærens,  et in viis ostendit se hilariter,  et in omni providentia occurrit illis. 

** Wisdom 6:18

Initium enim illius verissima est disciplinæ concupiscentia. 

** Wisdom 6:19

Cura ergo disciplinæ dilectio est,  et dilectio custodia legum illius est ;  custoditio autem legum consummatio incorruptionis est ; 

** Wisdom 6:20

incorruptio autem facit esse proximum Deo. 

** Wisdom 6:21

Concupiscentia itaque sapientiæ deducit ad regnum perpetuum. 

** Wisdom 6:22

Si ergo delectamini sedibus et sceptris, o reges populi,  diligite sapientiam, ut in perpetuum regnetis : 

** Wisdom 6:23

diligite lumen sapientiæ, omnes qui præestis populis. 

** Wisdom 6:24

Quid est autem sapientia, et quemadmodum facta sit, referam,  et non abscondam a vobis sacramenta Dei :  sed ab initio nativitatis investigabo,  et ponam in lucem scientiam illius,  et non præteribo veritatem. 

** Wisdom 6:25

Neque cum invidia tabescente iter habebo,  quoniam talis homo non erit particeps sapientiæ. 

** Wisdom 6:26

Multitudo autem sapientium sanitas est orbis terrarum,  et rex sapiens stabilimentum populi est. 

** Wisdom 6:27

Ergo accipite disciplinam per sermones meos,  et proderit vobis.  

* Wisdom 7

** Wisdom 7:1

Sum quidem et ego mortalis homo, similis omnibus,  et ex genere terreni illius qui prior factus est :  et in ventre matris figuratus sum caro ; 

** Wisdom 7:2

decem mensium tempore coagulatus sum in sanguine :  ex semine hominis, et delectamento somni conveniente. 

** Wisdom 7:3

Et ego natus accepi communem aërem,  et in similiter factam decidi terram,  et primam vocem similem omnibus emisi plorans. 

** Wisdom 7:4

In involumentis nutritus sum, et curis magnis : 

** Wisdom 7:5

nemo enim ex regibus aliud habuit nativitatis initium. 

** Wisdom 7:6

Unus ergo introitus est omnibus ad vitam,  et similis exitus. 

** Wisdom 7:7

Propter hoc optavi, et datus est mihi sensus ;  et invocavi, et venit in me spiritus sapientiæ : 

** Wisdom 7:8

et præposui illam regnis et sedibus,  et divitias nihil esse duxi in comparatione illius. 

** Wisdom 7:9

Nec comparavi illi lapidem pretiosum,  quoniam omne aurum in comparatione illius arena est exigua,  et tamquam lutum æstimabitur argentum in conspectu illius. 

** Wisdom 7:10

Super salutem et speciem dilexi illam,  et proposui pro luce habere illam,  quoniam inextinguibile est lumen illius. 

** Wisdom 7:11

Venerunt autem mihi omnia bona pariter cum illa,  et innumerabilis honestas per manus illius ; 

** Wisdom 7:12

et lætatus sum in omnibus,  quoniam antecedebat me ista sapientia,  et ignorabam quoniam horum omnium mater est. 

** Wisdom 7:13

Quam sine fictione didici,  et sine invidia communico,  et honestatem illius non abscondo. 

** Wisdom 7:14

Infinitus enim thesaurus est hominibus ;  quo qui usi sunt, participes facti sunt amicitiæ Dei,  propter disciplinæ dona commendati. 

** Wisdom 7:15

Mihi autem dedit Deus dicere ex sententia,  et præsumere digna horum quæ mihi dantur :  quoniam ipse sapientiæ dux est,  et sapientium emendator. 

** Wisdom 7:16

In manu enim illius et nos et sermones nostri,  et omnis sapientia, et operum scientia, et disciplina. 

** Wisdom 7:17

Ipse enim dedit mihi horum quæ sunt scientiam veram,  ut sciam dispositionem orbis terrarum, et virtutes elementorum, 

** Wisdom 7:18

initium, et consummationem, et medietatem temporum,  vicissitudinum permutationes, et commutationes temporum, 

** Wisdom 7:19

anni cursus, et stellarum dispositiones, 

** Wisdom 7:20

naturas animalium, et iras bestiarum,  vim ventorum, et cogitationes hominum,  differentias virgultorum, et virtutes radicum. 

** Wisdom 7:21

Et quæcumque sunt absconsa et improvisa didici :  omnium enim artifex docuit me sapientia. 

** Wisdom 7:22

Est enim in illa spiritus intelligentiæ,  sanctus, unicus, multiplex, subtilis,  disertus, mobilis, incoinquinatus, certus,  suavis, amans bonum, acutus,  quem nihil vetat, benefaciens, 

** Wisdom 7:23

humanus, benignus, stabilis, certus, securus,  omnem habens virtutem, omnia prospiciens,  et qui capiat omnes spiritus,  intelligibilis, mundus, subtilis. 

** Wisdom 7:24

Omnibus enim mobilibus mobilior est sapientia :  attingit autem ubique propter suam munditiam. 

** Wisdom 7:25

Vapor est enim virtutis Dei,  et emanatio quædam est claritatis omnipotentis Dei sincera,  et ideo nihil inquinatum in eam incurrit : 

** Wisdom 7:26

candor est enim lucis æternæ,  et speculum sine macula Dei majestatis,  et imago bonitatis illius. 

** Wisdom 7:27

Et cum sit una, omnia potest ;  et in se permanens omnia innovat :  et per nationes in animas sanctas se transfert ;  amicos Dei et prophetas constituit. 

** Wisdom 7:28

Neminem enim diligit Deus,  nisi eum qui cum sapientia inhabitat. 

** Wisdom 7:29

Est enim hæc speciosior sole,  et super omnem dispositionem stellarum :  luci comparata, invenitur prior. 

** Wisdom 7:30

Illi enim succedit nox ;  sapientiam autem non vincit malitia.  

* Wisdom 8

** Wisdom 8:1

Attingit ergo a fine usque ad finem fortiter,  et disponit omnia suaviter. 

** Wisdom 8:2

Hanc amavi, et exquisivi a juventute mea,  et quæsivi sponsam mihi eam assumere,  et amator factus sum formæ illius. 

** Wisdom 8:3

Generositatem illius glorificat,  contubernium habens Dei ;  sed et omnium Dominus dilexit illam. 

** Wisdom 8:4

Doctrix enim est disciplinæ Dei,  et electrix operum illius. 

** Wisdom 8:5

Et si divitiæ appetuntur in vita,  quid sapientia locupletius quæ operatur omnia ? 

** Wisdom 8:6

Si autem sensus operatur,  quis horum quæ sunt magis quam illa est artifex ? 

** Wisdom 8:7

Et si justitiam quis diligit,  labores hujus magnas habent virtutes :  sobrietatem enim et prudentiam docet,  et justitiam, et virtutem,  quibus utilius nihil est in vita hominibus. 

** Wisdom 8:8

Et si multitudinem scientiæ desiderat quis,  scit præterita, et de futuris æstimat ;  scit versutias sermonum, et dissolutiones argumentorum ;  signa et monstra scit antequam fiant,  et eventus temporum et sæculorum. 

** Wisdom 8:9

Proposui ergo hanc adducere mihi ad convivendum,  sciens quoniam mecum communicabit de bonis,  et erit allocutio cogitationis et tædii mei. 

** Wisdom 8:10

Habebo propter hanc claritatem ad turbas,  et honorem apud seniores juvenis ; 

** Wisdom 8:11

et acutus inveniar in judicio,  et in conspectu potentium admirabilis ero,  et facies principum mirabuntur me : 

** Wisdom 8:12

tacentem me sustinebunt,  et loquentem me respicient,  et sermocinante me plura, manus ori suo imponent. 

** Wisdom 8:13

Præterea habebo per hanc immortalitatem,  et memoriam æternam his qui post me futuri sunt relinquam. 

** Wisdom 8:14

Disponam populos,  et nationes mihi erunt subditæ : 

** Wisdom 8:15

timebunt me audientes reges horrendi.  In multitudine videbor bonus,  et in bello fortis. 

** Wisdom 8:16

Intrans in domum meam, conquiescam cum illa :  non enim habet amaritudinem conversatio illius,  nec tædium convictus illius,  sed lætitiam et gaudium. 

** Wisdom 8:17

Hæc cogitans apud me  et commemorans in corde meo,  quoniam immortalitas est in cognatione sapientiæ, 

** Wisdom 8:18

et in amicitia illius delectatio bona,  et in operibus manuum illius honestas sine defectione,  et in certamine loquelæ illius sapientia,  et præclaritas in communicatione sermonum ipsius :  circuibam quærens, ut mihi illam assumerem. 

** Wisdom 8:19

Puer autem eram ingeniosus,  et sortitus sum animam bonam. 

** Wisdom 8:20

Et cum essem magis bonus,  veni ad corpus incoinquinatum. 

** Wisdom 8:21

Et ut scivi quoniam aliter non possem esse continens, nisi Deus det ;  et hoc ipsum erat sapientiæ, scire cujus esset hoc donum :  adii Dominum, et deprecatus sum illum,  et dixi ex totis præcordiis meis :  

* Wisdom 9

** Wisdom 9:1

Deus patrum meorum, et Domine misericordiæ,  qui fecisti omnia verbo tuo, 

** Wisdom 9:2

et sapientia tua constituisti hominem,  ut dominaretur creaturæ quæ a te facta est, 

** Wisdom 9:3

ut disponat orbem terrarum in æquitate et justitia,  et in directione cordis judicium judicet : 

** Wisdom 9:4

da mihi sedium tuarum assistricem sapientiam,  et noli me reprobare a pueris tuis : 

** Wisdom 9:5

quoniam servus tuus sum ego, et filius ancillæ tuæ ;  homo infirmus, et exigui temporis,  et minor ad intellectum judicii et legum. 

** Wisdom 9:6

Nam etsi quis erit consummatus inter filios hominum,  si ab illo abfuerit sapientia tua, in nihilum computabitur. 

** Wisdom 9:7

Tu elegisti me regem populo tuo,  et judicem filiorum tuorum et filiarum : 

** Wisdom 9:8

et dixisti me ædificare templum in monte sancto tuo,  et in civitate habitationis tuæ altare :  similitudinem tabernaculi sancti tui quod præparasti ab initio. 

** Wisdom 9:9

Et tecum sapientia tua, quæ novit opera tua,  quæ et affuit tunc cum orbem terrarum faceres,  et sciebat quid esset placitum oculis tuis,  et quid directum in præceptis tuis. 

** Wisdom 9:10

Mitte illam de cælis sanctis tuis,  et a sede magnitudinis tuæ,  ut mecum sit et mecum laboret,  ut sciam quid acceptum sit apud te : 

** Wisdom 9:11

scit enim illa omnia, et intelligit,  et deducet me in operibus meis sobrie,  et custodiet me in sua potentia. 

** Wisdom 9:12

Et erunt accepta opera mea,  et disponam populum tuum juste,  et ero dignus sedium patris mei. 

** Wisdom 9:13

Quis enim hominum poterit scire consilium Dei ?  aut quis poterit cogitare quid velit Deus ? 

** Wisdom 9:14

Cogitationes enim mortalium timidæ,  et incertæ providentiæ nostræ ; 

** Wisdom 9:15

corpus enim quod corrumpitur aggravat animam,  et terrena inhabitatio deprimit sensum multa cogitantem. 

** Wisdom 9:16

Et difficile æstimamus quæ in terra sunt,  et quæ in prospectu sunt invenimus cum labore :  quæ autem in cælis sunt, quis investigabit ? 

** Wisdom 9:17

Sensum autem tuum, quis sciet, nisi tu dederis sapientiam,  et miseris spiritum sanctum tuum de altissimis, 

** Wisdom 9:18

et sic correctæ sint semitæ eorum qui sunt in terris,  et quæ tibi placent didicerint homines ? 

** Wisdom 9:19

Nam per sapientiam sanati sunt  quicumque placuerunt tibi, Domine, a principio.  

* Wisdom 10

** Wisdom 10:1

Hæc illum qui primus formatus est a Deo patre orbis terrarum,  cum solus esset creatus, custodivit, 

** Wisdom 10:2

et eduxit illum a delicto suo,  et dedit illi virtutem continendi omnia. 

** Wisdom 10:3

Ab hac ut recessit injustus in ira sua,  per iram homicidii fraterni deperiit. 

** Wisdom 10:4

Propter quem cum aqua deleret terram, sanavit iterum sapientia,  per contemptibile lignum justum gubernans. 

** Wisdom 10:5

Hæc et in consensu nequitiæ, cum se nationes contulissent,  scivit justum, et conservavit sine querela Deo,  et in filii misericordia fortem custodivit. 

** Wisdom 10:6

Hæc justum a pereuntibus impiis liberavit fugientem,  descendente igne in Pentapolim : 

** Wisdom 10:7

quibus in testimonium nequitiæ  fumigabunda constat deserta terra,  et incerto tempore fructus habentes arbores :  et incredibilis animæ memoria stans figmentum salis. 

** Wisdom 10:8

Sapientiam enim prætereuntes,  non tantum in hoc lapsi sunt ut ignorarent bona,  sed et insipientiæ suæ reliquerunt hominibus memoriam,  ut in his quæ peccaverunt nec latere potuissent. 

** Wisdom 10:9

Sapientia autem hos qui se observant  a doloribus liberavit. 

** Wisdom 10:10

Hæc profugum iræ fratris justum deduxit per vias rectas,  et ostendit illi regnum Dei,  et dedit illi scientiam sanctorum ;  honestavit illum in laboribus,  et complevit labores illius. 

** Wisdom 10:11

In fraude circumvenientium illum affuit illi,  et honestum fecit illum. 

** Wisdom 10:12

Custodivit illum ab inimicis,  et a seductoribus tutavit illum :  et certamen forte dedit illi ut vinceret,  et sciret quoniam omnium potentior est sapientia. 

** Wisdom 10:13

Hæc venditum justum non dereliquit,  sed a peccatoribus liberavit eum ;  descenditque cum illo in foveam, 

** Wisdom 10:14

et in vinculis non dereliquit illum,  donec afferret illi sceptrum regni,  et potentiam adversus eos qui eum deprimebant :  et mendaces ostendit qui maculaverunt illum,  et dedit illi claritatem æternam. 

** Wisdom 10:15

Hæc populum justum et semen sine querela liberavit  a nationibus quæ illum deprimebant. 

** Wisdom 10:16

Intravit in animam servi Dei,  et stetit contra reges horrendos in portentis et signis. 

** Wisdom 10:17

Et reddidit justis mercedem laborum suorum,  et deduxit illos in via mirabili :  et fuit illis in velamento diei,  et in luce stellarum per noctem ; 

** Wisdom 10:18

transtulit illos per mare Rubrum,  et transvexit illos per aquam nimiam. 

** Wisdom 10:19

Inimicos autem illorum demersit in mare,  et ab altitudine inferorum eduxit illos.  Ideo justi tulerunt spolia impiorum, 

** Wisdom 10:20

et decantaverunt, Domine, nomen sanctum tuum,  et victricem manum tuam laudaverunt pariter : 

** Wisdom 10:21

quoniam sapientia aperuit os mutorum,  et linguas infantium fecit disertas.  

* Wisdom 11

** Wisdom 11:1

Direxit opera eorum in manibus prophetæ sancti. 

** Wisdom 11:2

Iter fecerunt per deserta quæ non habitabantur,  et in locis desertis fixerunt casas. 

** Wisdom 11:3

Steterunt contra hostes,  et de inimicis se vindicaverunt. 

** Wisdom 11:4

Sitierunt, et invocaverunt te,  et data est illis aqua de petra altissima,  et requies sitis de lapide duro. 

** Wisdom 11:5

Per quæ enim pœnas passi sunt inimici illorum  a defectione potus sui,  et in eis cum abundarent filii Israël lætati sunt : 

** Wisdom 11:6

per hæc, cum illis deessent, bene cum illis actum est. 

** Wisdom 11:7

Nam pro fonte quidem sempiterni fluminis,  humanum sanguinem dedisti injustis. 

** Wisdom 11:8

Qui cum minuerentur in traductione infantium occisorum,  dedisti illis abundantem aquam insperate, 

** Wisdom 11:9

ostendens per sitim quæ tunc fuit,  quemadmodum tuos exaltares,  et adversarios illorum necares. 

** Wisdom 11:10

Cum enim tentati sunt,  et quidem cum misericordia disciplinam accipientes,  scierunt quemadmodum cum ira judicati impii tormenta paterentur. 

** Wisdom 11:11

Hos quidem tamquam pater monens probasti ;  illos autem tamquam durus rex interrogans condemnasti. 

** Wisdom 11:12

Absentes enim, et præsentes, similiter torquebantur. 

** Wisdom 11:13

Duplex enim illos acceperat tædium et gemitus,  cum memoria præteritorum. 

** Wisdom 11:14

Cum enim audirent per sua tormenta bene secum agi,  commemorati sunt Dominum, admirantes in finem exitus. 

** Wisdom 11:15

Quem enim in expositione prava projectum deriserunt,  in finem eventus mirati sunt,  non similiter justis sitientes. 

** Wisdom 11:16

Pro cogitationibus autem insensatis iniquitatis illorum,  quod quidam errantes colebant mutos serpentes  et bestias supervacuas,  immisisti illis multitudinem mutorum animalium in vindictam ; 

** Wisdom 11:17

ut scirent quia per quæ peccat quis, per hæc et torquetur. 

** Wisdom 11:18

Non enim impossibilis erat omnipotens manus tua,  quæ creavit orbem terrarum ex materia invisa,  immittere illis multitudinem ursorum, aut audaces leones, 

** Wisdom 11:19

aut novi generis ira plenas ignotas bestias,  aut vaporem ignium spirantes,  aut fumi odorem proferentes,  aut horrendas ab oculis scintillas emittentes ; 

** Wisdom 11:20

quarum non solum læsura poterat illos exterminare,  sed et aspectus per timorem occidere. 

** Wisdom 11:21

Sed et sine his uno spiritu poterant occidi,  persecutionem passi ab ipsis factis suis,  et dispersi per spiritum virtutis tuæ :  sed omnia in mensura, et numero et pondere disposuisti. 

** Wisdom 11:22

Multum enim valere, tibi soli supererat semper :  et virtuti brachii tui quis resistet ? 

** Wisdom 11:23

Quoniam tamquam momentum stateræ,  sic est ante te orbis terrarum,  et tamquam gutta roris antelucani quæ descendit in terram. 

** Wisdom 11:24

Sed misereris omnium, quia omnia potes ;  et dissimulas peccata hominum, propter pœnitentiam. 

** Wisdom 11:25

Diligis enim omnia quæ sunt,  et nihil odisti eorum quæ fecisti ;  nec enim odiens aliquid constituisti aut fecisti. 

** Wisdom 11:26

Quomodo autem posset aliquid permanere, nisi tu voluisses ?  aut quod a te vocatum non esset conservaretur ? 

** Wisdom 11:27

Parcis autem omnibus, quoniam tua sunt, Domine,  qui amas animas.  

* Wisdom 12

** Wisdom 12:1

O quam bonus et suavis est, Domine, spiritus tuus in omnibus ! 

** Wisdom 12:2

Ideoque eos qui exerrant partibus corripis,  et de quibus peccant admones et alloqueris,  ut relicta malitia credant in te, Domine. 

** Wisdom 12:3

Illos enim antiquos inhabitatores terræ sanctæ tuæ,  quos exhorruisti, 

** Wisdom 12:4

quoniam odibilia opera tibi faciebant  per medicamina et sacrificia injusta, 

** Wisdom 12:5

et filiorum suorum necatores sine misericordia,  et comestores viscerum hominum,  et devoratores sanguinis a medio sacramento tuo, 

** Wisdom 12:6

et auctores parentes animarum inauxiliatarum,  perdere voluisti per manus parentum nostrorum : 

** Wisdom 12:7

ut dignam perciperent peregrinationem puerorum Dei,  quæ tibi omnium carior est terra. 

** Wisdom 12:8

Sed et his tamquam hominibus pepercisti,  et misisti antecessores exercitus tui vespas,  ut illos paulatim exterminarent. 

** Wisdom 12:9

Non quia impotens eras in bello subjicere impios justis,  aut bestiis sævis, aut verbo duro simul exterminare : 

** Wisdom 12:10

sed partibus judicans,  dabas locum pœnitentiæ,  non ignorans quoniam nequam est natio eorum,  et naturalis malitia ipsorum,  et quoniam non poterat mutari cogitatio illorum in perpetuum. 

** Wisdom 12:11

Semen enim erat maledictum ab initio ;  nec timens aliquem, veniam dabas peccatis illorum. 

** Wisdom 12:12

Quis enim dicet tibi : Quid fecisti ?  aut quis stabit contra judicium tuum ?  aut quis in conspectu tuo veniet vindex iniquorum hominum ?  aut quis tibi imputabit, si perierint nationes quas tu fecisti ? 

** Wisdom 12:13

Non enim est alius deus quam tu,  cui cura est de omnibus,  ut ostendas quoniam non injuste judicas judicium. 

** Wisdom 12:14

Neque rex, neque tyrannus in conspectu tuo inquirent  de his quos perdidisti. 

** Wisdom 12:15

Cum ergo sis justus, juste omnia disponis ;  ipsum quoque qui non debet puniri, condemnare,  exterum æstimas a tua virtute. 

** Wisdom 12:16

Virtus enim tua justitiæ initium est,  et ob hoc quod Dominus es,  omnibus te parcere facis. 

** Wisdom 12:17

Virtutem enim ostendis tu,  qui non crederis esse in virtute consummatus,  et horum qui te nesciunt audaciam traducis. 

** Wisdom 12:18

Tu autem dominator virtutis, cum tranquillitate judicas,  et cum magna reverentia disponis nos :  subest enim tibi, cum volueris posse. 

** Wisdom 12:19

Docuisti autem populum tuum per talia opera,  quoniam oportet justum esse et humanum ;  et bonæ spei fecisti filios tuos,  quoniam judicans das locum in peccatis pœnitentiæ. 

** Wisdom 12:20

Si enim inimicos servorum tuorum, et debitos morti,  cum tanta cruciasti attentione,  dans tempus et locum per quæ possent mutari a malitia : 

** Wisdom 12:21

cum quanta diligentia judicasti filios tuos,  quorum parentibus juramenta et conventiones dedisti bonarum promissionum ! 

** Wisdom 12:22

Cum ergo das nobis disciplinam,  inimicos nostros multipliciter flagellas,  ut bonitatem tuam cogitemus judicantes,  et cum de nobis judicatur, speremus misericordiam tuam. 

** Wisdom 12:23

Unde et illis qui in vita sua insensate et injuste vixerunt,  per hæc quæ coluerunt dedisti summa tormenta. 

** Wisdom 12:24

Etenim in erroris via diutius erraverunt,  deos æstimantes hæc quæ in animalibus sunt supervacua,  infantium insensatorum more viventes. 

** Wisdom 12:25

Propter hoc tamquam pueris insensatis judicium in derisum dedisti. 

** Wisdom 12:26

Qui autem ludibriis et increpationibus non sunt correcti,  dignum Dei judicium experti sunt. 

** Wisdom 12:27

In quibus enim patientes indignabantur  per hæc quos putabant deos,  in ipsis cum exterminarentur videntes,  illum quem olim negabant se nosse, verum Deum agnoverunt ;  propter quod et finis condemnationis eorum venit super illos.  

* Wisdom 13

** Wisdom 13:1

Vani autem sunt omnes homines  in quibus non subest scientia Dei ;  et de his quæ videntur bona,  non potuerunt intelligere eum qui est,  neque operibus attendentes agnoverunt quis esset artifex : 

** Wisdom 13:2

sed aut ignem, aut spiritum, aut citatum aërem,  aut gyrum stellarum, aut nimiam aquam, aut solem et lunam,  rectores orbis terrarum deos putaverunt. 

** Wisdom 13:3

Quorum si specie delectati, deos putaverunt,  sciant quanto his dominator eorum speciosior est :  speciei enim generator hæc omnia constituit. 

** Wisdom 13:4

Aut si virtutem et opera eorum mirati sunt,  intelligant ab illis quoniam qui hæc fecit fortior est illis : 

** Wisdom 13:5

a magnitudine enim speciei et creaturæ  cognoscibiliter poterit creator horum videri. 

** Wisdom 13:6

Sed tamen adhuc in his minor est querela ;  et hi enim fortasse errant,  Deum quærentes, et volentes invenire. 

** Wisdom 13:7

Etenim cum in operibus illius conversentur inquirunt,  et persuasum habent quoniam bona sunt quæ videntur. 

** Wisdom 13:8

Iterum autem nec his debet ignosci. 

** Wisdom 13:9

Si enim tantum potuerunt scire  ut possent æstimare sæculum,  quomodo hujus Dominum non facilius invenerunt ? 

** Wisdom 13:10

Infelices autem sunt,  et inter mortuos spes illorum est,  qui appellaverunt deos opera manuum hominum :  aurum et argentum, artis inventionem,  et similitudines animalium, aut lapidem inutilem,  opus manus antiquæ. 

** Wisdom 13:11

Aut si quis artifex faber de silva lignum rectum secuerit,  et hujus docte eradat omnem corticem,  et arte sua usus  diligenter fabricet vas utile in conversationem vitæ ; 

** Wisdom 13:12

reliquiis autem ejus operis  ad præparationem escæ abutatur, 

** Wisdom 13:13

et reliquum horum quod ad nullos usus facit,  lignum curvum et vorticibus plenum  sculpat diligenter per vacuitatem suam,  et per scientiam suæ artis figuret illud,  et assimilet illud imagini hominis, 

** Wisdom 13:14

aut alicui ex animalibus illud comparet :  perliniens rubrica, et rubicundum faciens fuco colorem illius,  et omnem maculam quæ in illo est perliniens ; 

** Wisdom 13:15

et faciat ei dignam habitationem,  et in pariete ponens illud,  et confirmans ferro

** Wisdom 13:16

ne forte cadat,  prospiciens illi :  sciens quoniam non potest adjuvare se :  imago enim est, et opus est illi adjutorium. 

** Wisdom 13:17

Et de substantia sua, et de filiis suis,  et de nuptiis votum faciens inquirit :  non erubescit loqui cum illo qui sine anima est. 

** Wisdom 13:18

Et pro sanitate quidem infirmum deprecatur,  et pro vita rogat mortuum,  et in adjutorium inutilem invocat. 

** Wisdom 13:19

Et pro itinere petit ab eo qui ambulare non potest ;  et de acquirendo, et de operando,  et de omnium rerum eventu,  petit ab eo qui in omnibus est inutilis.  

* Wisdom 14

** Wisdom 14:1

Iterum alius navigare cogitans,  et per feros fluctus iter facere incipiens,  ligno portante se, fragilius lignum invocat. 

** Wisdom 14:2

Illud enim cupiditas acquirendi excogitavit,  et artifex sapientia fabricavit sua. 

** Wisdom 14:3

Tua autem, Pater, providentia gubernat :  quoniam dedisti et in mari viam,  et inter fluctus semitam firmissimam, 

** Wisdom 14:4

ostendens quoniam potens es ex omnibus salvare,  etiam si sine arte aliquis adeat mare. 

** Wisdom 14:5

Sed ut non essent vacua sapientiæ tuæ opera,  propter hoc etiam et exiguo ligno credunt homines animas suas,  et transeuntes mare per ratem liberati sunt. 

** Wisdom 14:6

Sed et ab initio cum perirent superbi gigantes,  spes orbis terrarum ad ratem confugiens,  remisit sæculo semen nativitatis quæ manu tua erat gubernata. 

** Wisdom 14:7

Benedictum est enim lignum per quod fit justitia ; 

** Wisdom 14:8

per manus autem quod fit idolum,  maledictum est et ipsum, et qui fecit illud :  quia ille quidem operatus est,  illud autem cum esset fragile, deus cognominatus est. 

** Wisdom 14:9

Similiter autem odio sunt Deo impius et impietas ejus ; 

** Wisdom 14:10

etenim quod factum est, cum illo qui fecit tormenta patietur. 

** Wisdom 14:11

Propter hoc et in idolis nationum non erit respectus,  quoniam creaturæ Dei in odium factæ sunt,  et in tentationem animabus hominum,  et in muscipulam pedibus insipientium. 

** Wisdom 14:12

Initium enim fornicationis est exquisitio idolorum,  et adinventio illorum corruptio vitæ est : 

** Wisdom 14:13

neque enim erant ab initio,  neque erunt in perpetuum. 

** Wisdom 14:14

Supervacuitas enim hominum hæc advenit in orbem terrarum,  et ideo brevis illorum finis est inventus. 

** Wisdom 14:15

Acerbo enim luctu dolens pater,  cito sibi rapti filii fecit imaginem ;  et illum qui tunc quasi homo mortuus fuerat,  nunc tamquam deum colere cœpit,  et constituit inter servos suos sacra et sacrificia. 

** Wisdom 14:16

Deinde interveniente tempore, convalescente iniqua consuetudine,  hic error tamquam lex custoditus est,  et tyrannorum imperio colebantur figmenta. 

** Wisdom 14:17

Et hos quos in palam homines honorare non poterant  propter hoc quod longe essent,  e longinquo figura eorum allata,  evidentem imaginem regis quem honorare volebant fecerunt,  ut illum qui aberat, tamquam præsentem colerent sua sollicitudine. 

** Wisdom 14:18

Provexit autem ad horum culturam  et hos qui ignorabant artificis eximia diligentia. 

** Wisdom 14:19

Ille enim, volens placere illi qui se assumpsit,  elaboravit arte sua ut similitudinem in melius figuraret. 

** Wisdom 14:20

Multitudo autem hominum, abducta per speciem operis,  eum qui ante tempus tamquam homo honoratus fuerat,  nunc deum æstimaverunt. 

** Wisdom 14:21

Et hæc fuit vitæ humanæ deceptio,  quoniam aut affectui aut regibus deservientes homines,  incommunicabile nomen lapidibus et lignis imposuerunt. 

** Wisdom 14:22

Et non suffecerat errasse eos circa Dei scientiam,  sed et in magno viventes inscientiæ bello,  tot et tam magna mala pacem appellant. 

** Wisdom 14:23

Aut enim filios suos sacrificantes,  aut obscura sacrificia facientes,  aut insaniæ plenas vigilias habentes, 

** Wisdom 14:24

neque vitam, neque nuptias mundas jam custodiunt :  sed alius alium per invidiam occidit,  aut adulterans contristat, 

** Wisdom 14:25

et omnia commista sunt : sanguis, homicidium,  furtum et fictio, corruptio et infidelitas,  turbatio et perjurium, tumultus bonorum, 

** Wisdom 14:26

Dei immemoratio, animarum inquinatio,  nativitatis immutatio, nuptiarum inconstantia,  inordinatio mœchiæ et impudicitiæ. 

** Wisdom 14:27

Infandorum enim idolorum cultura  omnis mali causa est, et initium et finis. 

** Wisdom 14:28

Aut enim dum lætantur insaniunt,  aut certe vaticinantur falsa,  aut vivunt injuste, aut pejerant cito. 

** Wisdom 14:29

Dum enim confidunt in idolis quæ sine anima sunt,  male jurantes noceri se non sperant. 

** Wisdom 14:30

Utraque ergo illis evenient digne,  quoniam male senserunt de Deo, attendentes idolis,  et juraverunt injuste,  in dolo contemnentes justitiam. 

** Wisdom 14:31

Non enim juratorum virtus,  sed peccantium pœna,  perambulat semper injustorum prævaricationem.  

* Wisdom 15

** Wisdom 15:1

Tu autem, Deus noster, suavis et verus es,  patiens, et in misericordia disponens omnia. 

** Wisdom 15:2

Etenim si peccaverimus, tui sumus,  scientes magnitudinem tuam ;  et si non peccaverimus,  scimus quoniam apud te sumus computati. 

** Wisdom 15:3

Nosse enim te, consummata justitia est ;  et scire justitiam et virtutem tuam, radix est immortalitatis. 

** Wisdom 15:4

Non enim in errorem induxit nos  hominum malæ artis excogitatio,  nec umbra picturæ labor sine fructu,  effigies sculpta per varios colores : 

** Wisdom 15:5

cujus aspectus insensato dat concupiscentiam,  et diligit mortuæ imaginis effigiem sine anima. 

** Wisdom 15:6

Malorum amatores digni sunt qui spem habeant in talibus,  et qui faciunt illos, et qui diligunt, et qui colunt. 

** Wisdom 15:7

Sed et figulus mollem terram premens,  laboriose fingit ad usus nostros unumquodque vas ;  et de eodem luto fingit quæ munda sunt in usum vasa,  et similiter quæ his sunt contraria :  horum autem vasorum quis sit usus,  judex est figulus. 

** Wisdom 15:8

Et cum labore vano deum fingit de eodem luto  ille qui paulo ante de terra factus fuerat,  et post pusillum reducit se unde acceptus est,  repetitus animæ debitum quam habebat. 

** Wisdom 15:9

Sed cura est illi non quia laboraturus est,  nec quoniam brevis illi vita est :  sed concertatur aurificibus et argentariis ;  sed et ærarios imitatur,  et gloriam præfert, quoniam res supervacuas fingit. 

** Wisdom 15:10

Cinis est enim cor ejus,  et terra supervacua spes illius,  et luto vilior vita ejus : 

** Wisdom 15:11

quoniam ignoravit qui se finxit,  et qui inspiravit illi animam quæ operatur,  et qui insufflavit ei spiritum vitalem. 

** Wisdom 15:12

Sed et æstimaverunt ludum esse vitam nostram,  et conversationem vitæ compositam ad lucrum,  et oportere undecumque etiam ex malo acquirere. 

** Wisdom 15:13

Hic enim scit se super omnes delinquere,  qui ex terræ materia fragilia vasa et sculptilia fingit. 

** Wisdom 15:14

Omnes enim insipientes,  et infelices supra modum animæ superbi,  sunt inimici populi tui, et imperantes illi : 

** Wisdom 15:15

quoniam omnia idola nationum deos æstimaverunt,  quibus neque oculorum usus est ad videndum,  neque nares ad percipiendum spiritum,  neque aures ad audiendum,  neque digiti manuum ad tractandum,  sed et pedes eorum pigri ad ambulandum. 

** Wisdom 15:16

Homo enim fecit illos ;  et qui spiritum mutuatus est, is finxit illos.  Nemo enim sibi similem homo poterit deum fingere. 

** Wisdom 15:17

Cum enim sit mortalis, mortuum fingit manibus iniquis.  Melior enim est ipse his quos colit,  quia ipse quidem vixit, cum esset mortalis, illi autem numquam. 

** Wisdom 15:18

Sed et animalia miserrima colunt ;  insensata enim comparata his, illis sunt deteriora. 

** Wisdom 15:19

Sed nec aspectu aliquis ex his animalibus bona potest conspicere :  effugerunt autem Dei laudem et benedictionem ejus.  

* Wisdom 16

** Wisdom 16:1

Propter hæc et per his similia passi sunt digne tormenta,  et per multitudinem bestiarum exterminati sunt. 

** Wisdom 16:2

Pro quibus tormentis bene disposuisti populum tuum,  quibus dedisti concupiscentiam delectamenti sui novum saporem,  escam parans eis ortygometram : 

** Wisdom 16:3

ut illi quidem, concupiscentes escam  propter ea quæ illis ostensa et missa sunt,  etiam a necessaria concupiscentia averterentur.  Hi autem in brevi inopes facti, novam gustaverunt escam. 

** Wisdom 16:4

Oportebat enim illis sine excusatione quidem  supervenire interitum exercentibus tyrannidem ;  his autem tantum ostendere  quemadmodum inimici eorum exterminabantur. 

** Wisdom 16:5

Etenim cum illis supervenit sæva bestiarum ira,  morsibus perversorum colubrorum exterminabantur. 

** Wisdom 16:6

Sed non in perpetuum ira tua permansit,  sed ad correptionem in brevi turbati sunt,  signum habentes salutis ad commemorationem mandati legis tuæ. 

** Wisdom 16:7

Qui enim conversus est,  non per hoc quod videbat sanabatur,  sed per te, omnium salvatorem. 

** Wisdom 16:8

In hoc autem ostendisti inimicis nostris  quia tu es qui liberas ab omni malo. 

** Wisdom 16:9

Illos enim locustarum et muscarum occiderunt morsus,  et non est inventa sanitas animæ illorum,  quia digni erant ab hujuscemodi exterminari. 

** Wisdom 16:10

Filios autem tuos nec draconum venenatorum vicerunt dentes :  misericordia enim tua adveniens sanabat illos. 

** Wisdom 16:11

In memoria enim sermonum tuorum examinabantur,  et velociter salvabantur :  ne in altam incidentes oblivionem  non possent tuo uti adjutorio. 

** Wisdom 16:12

Etenim neque herba, neque malagma sanavit eos :  sed tuus, Domine, sermo, qui sanat omnia. 

** Wisdom 16:13

Tu es enim, Domine, qui vitæ et mortis habes potestatem,  et deducis ad portas mortis, et reducis. 

** Wisdom 16:14

Homo autem occidit quidem per malitiam ;  et cum exierit spiritus, non revertetur,  nec revocabit animam quæ recepta est. 

** Wisdom 16:15

Sed tuam manum effugere impossibile est. 

** Wisdom 16:16

Negantes enim te nosse impii,  per fortitudinem brachii tui flagellati sunt :  novis aquis, et grandinibus,  et pluviis persecutionem passi,  et per ignem consumpti. 

** Wisdom 16:17

Quod enim mirabile erat, in aqua, quæ omnia extinguit,  plus ignis valebat :  vindex est enim orbis justorum. 

** Wisdom 16:18

Quodam enim tempore mansuetabatur ignis,  ne comburerentur quæ ad impios missa erant animalia,  sed ut ipsi videntes scirent  quoniam Dei judicio patiuntur persecutionem. 

** Wisdom 16:19

Et quodam tempore in aqua  supra virtutem ignis exardescebat undique,  ut iniquæ terræ nationem exterminaret. 

** Wisdom 16:20

Pro quibus angelorum esca nutrivisti populum tuum,  et paratum panem de cælo præstitisti illis sine labore,  omne delectamentum in se habentem,  et omnis saporis suavitatem. 

** Wisdom 16:21

Substantia enim tua dulcedinem tuam,  quam in filios habes, ostendebat ;  et deserviens uniuscujusque voluntati,  ad quod quisque volebat convertebatur. 

** Wisdom 16:22

Nix autem et glacies sustinebant vim ignis, et non tabescebant :  ut scirent quoniam fructus inimicorum exterminabat  ignis ardens in grandine et pluvia coruscans ; 

** Wisdom 16:23

hic autem iterum ut nutrirentur justi,  etiam suæ virtutis oblitus est. 

** Wisdom 16:24

Creatura enim tibi factori deserviens,  exardescit in tormentum adversus injustos,  et lenior fit ad benefaciendum pro his qui in te confidunt. 

** Wisdom 16:25

Propter hoc et tunc in omnia transfigurata,  omnium nutrici gratiæ tuæ deserviebat,  ad voluntatem eorum qui a te desiderabant : 

** Wisdom 16:26

ut scirent filii tui quos dilexisti, Domine,  quoniam non nativitatis fructus pascunt homines,  sed sermo tuus hos qui in te crediderint conservat. 

** Wisdom 16:27

Quod enim ab igne non poterat exterminari,  statim ab exiguo radio solis calefactum tabescebat : 

** Wisdom 16:28

ut notum omnibus esset  quoniam oportet prævenire solem ad benedictionem tuam,  et ad ortum lucis te adorare. 

** Wisdom 16:29

Ingrati enim spes tamquam hibernalis glacies tabescet,  et disperiet tamquam aqua supervacua.  

* Wisdom 17

** Wisdom 17:1

Magna sunt enim judicia tua, Domine,  et inenarrabilia verba tua :  propter hoc indisciplinatæ animæ erraverunt. 

** Wisdom 17:2

Dum enim persuasum habent iniqui  posse dominari nationi sanctæ,  vinculis tenebrarum et longæ noctis compediti,  inclusi sub tectis,  fugitivi perpetuæ providentiæ jacuerunt. 

** Wisdom 17:3

Et dum putant se latere in obscuris peccatis,  tenebroso oblivionis velamento dispersi sunt,  paventes horrende,  et cum admiratione nimia perturbati. 

** Wisdom 17:4

Neque enim quæ continebat illos spelunca sine timore custodiebat,  quoniam sonitus descendens perturbabat illos,  et personæ tristes illis apparentes pavorem illis præstabant. 

** Wisdom 17:5

Et ignis quidem nulla vis poterat illis lumen præbere,  nec siderum limpidæ flammæ  illuminare poterant illam noctem horrendam. 

** Wisdom 17:6

Apparebat autem illis subitaneus ignis, timore plenus ;  et timore perculsi illius quæ non videbatur faciei,  æstimabant deteriora esse quæ videbantur. 

** Wisdom 17:7

Et magicæ artis appositi erant derisus,  et sapientiæ gloriæ correptio cum contumelia. 

** Wisdom 17:8

Illi enim qui promittebant  timores et perturbationes expellere se ab anima languente,  hi cum derisu pleni timore languebant. 

** Wisdom 17:9

Nam etsi nihil illos ex monstris perturbabat,  transitu animalium et serpentium sibilatione commoti,  tremebundi peribant,  et aërem quem nulla ratione quis effugere posset, negantes se videre. 

** Wisdom 17:10

Cum sit enim timida nequitia,  dat testimonium condemnationis :  semper enim præsumit sæva,  perturbata conscientia : 

** Wisdom 17:11

nihil enim est timor nisi proditio cogitationis auxiliorum. 

** Wisdom 17:12

Et dum ab intus minor est exspectatio,  majorem computat inscientiam ejus causæ,  de qua tormentum præstat. 

** Wisdom 17:13

Illi autem qui impotentem vere noctem,  et ab infimis et ab altissimis inferis supervenientem,  eumdem somnum dormientes, 

** Wisdom 17:14

aliquando monstrorum exagitabantur timore,  aliquando animæ deficiebant traductione :  subitaneus enim illis et insperatus timor supervenerat. 

** Wisdom 17:15

Deinde si quisquam ex illis decidisset,  custodiebatur in carcere sine ferro reclusus. 

** Wisdom 17:16

Si enim rusticus quis erat, aut pastor,  aut agri laborum operarius præoccupatus esset,  ineffugibilem sustinebat necessitatem ; 

** Wisdom 17:17

una enim catena tenebrarum omnes erant colligati.  Sive spiritus sibilans,  aut inter spissos arborum ramos avium sonus suavis,  aut vis aquæ decurrentis nimium, 

** Wisdom 17:18

aut sonus validus præcipitatarum petrarum,  aut ludentium animalium cursus invisus,  aut mugientium valida bestiarum vox,  aut resonans de altissimis montibus echo :  deficientes faciebant illos præ timore. 

** Wisdom 17:19

Omnis enim orbis terrarum limpido illuminabatur lumine,  et non impeditis operibus continebatur. 

** Wisdom 17:20

Solis autem illis superposita erat gravis nox,  imago tenebrarum quæ superventura illis erat :  ipsi ergo sibi erant graviores tenebris.  

* Wisdom 18

** Wisdom 18:1

Sanctis autem tuis maxima erat lux,  et horum quidem vocem audiebant, sed figuram non videbant.  Et quia non et ipsi eadem passi erant, magnificabant te ; 

** Wisdom 18:2

et qui ante læsi erant, quia non lædebantur, gratias agebant,  et ut esset differentia, donum petebant. 

** Wisdom 18:3

Propter quod ignis ardentem columnam  ducem habuerunt ignotæ viæ,  et solem sine læsura boni hospitii præstitisti. 

** Wisdom 18:4

Digni quidem illi carere luce,  et pati carcerem tenebrarum,  qui inclusos custodiebant filios tuos,  per quos incipiebat incorruptum legis lumen sæculo dari. 

** Wisdom 18:5

Cum cogitarent justorum occidere infantes,  et uno exposito filio et liberato,  in traductionem illorum, multitudinem filiorum abstulisti,  et pariter illos perdidisti in aqua valida. 

** Wisdom 18:6

Illa enim nox ante cognita est a patribus nostris,  ut vere scientes quibus juramentis crediderunt,  animæquiores essent. 

** Wisdom 18:7

Suscepta est autem a populo tuo sanitas quidem justorum,  injustorum autem exterminatio. 

** Wisdom 18:8

Sicut enim læsisti adversarios,  sic et nos provocans magnificasti. 

** Wisdom 18:9

Absconse enim sacrificabant justi pueri bonorum,  et justitiæ legem in concordia disposuerunt ;  similiter et bona et mala recepturos justos,  patrum jam decantantes laudes. 

** Wisdom 18:10

Resonabat autem inconveniens inimicorum vox,  et flebilis audiebatur planctus ploratorum infantium. 

** Wisdom 18:11

Simili autem pœna servus cum domino afflictus est,  et popularis homo regi similia passus. 

** Wisdom 18:12

Similiter ergo omnes, uno nomine mortis,  mortuos habebant innumerabiles :  nec enim ad sepeliendum vivi sufficiebant,  quoniam uno momento quæ erat præclarior  natio illorum exterminata est. 

** Wisdom 18:13

De omnibus enim non credentes, propter veneficia ;  tunc vero primum cum fuit exterminium primogenitorum,  spoponderunt populum Dei esse. 

** Wisdom 18:14

Cum enim quietum silentium contineret omnia,  et nox in suo cursu medium iter haberet, 

** Wisdom 18:15

omnipotens sermo tuus de cælo, a regalibus sedibus,  durus debellator in mediam exterminii terram prosilivit, 

** Wisdom 18:16

gladius acutus insimulatum imperium tuum portans :  et stans, replevit omnia morte,  et usque ad cælum attingebat stans in terra. 

** Wisdom 18:17

Tunc continuo visus somniorum malorum turbaverunt illos,  et timores supervenerunt insperati. 

** Wisdom 18:18

Et alius alibi projectus semivivus,  propter quam moriebatur causam demonstrabat mortis. 

** Wisdom 18:19

Visiones enim quæ illos turbaverunt hæc præmonebant,  ne inscii quare mala patiebantur perirent. 

** Wisdom 18:20

Tetigit autem tunc et justos tentatio mortis,  et commotio in eremo facta est multitudinis :  sed non diu permansit ira tua. 

** Wisdom 18:21

Prosperans enim homo sine querela deprecari pro populis,  proferens servitutis suæ scutum,  orationem et per incensum deprecationem allegans,  restitit iræ, et finem imposuit necessitati,  ostendens quoniam tuus est famulus. 

** Wisdom 18:22

Vicit autem turbas non in virtute corporis,  nec armaturæ potentia :  sed verbo illum qui se vexabat subjecit,  juramenta parentum et testamentum commemorans. 

** Wisdom 18:23

Cum enim jam acervatim cecidissent super alterutrum mortui,  interstitit, et amputavit impetum,  et divisit illam quæ ad vivos ducebat viam. 

** Wisdom 18:24

In veste enim poderis quam habebat, totus erat orbis terrarum ;  et parentum magnalia in quatuor ordinibus lapidum erant sculpta,  et magnificentia tua in diademate capitis illius sculpta erat. 

** Wisdom 18:25

His autem cessit qui exterminabat, et hæc extimuit :  erat enim sola tentatio iræ sufficiens.  

* Wisdom 19

** Wisdom 19:1

Impiis autem usque in novissimum  sine misericordia ira supervenit.  Præsciebat enim et futura illorum : 

** Wisdom 19:2

quoniam cum ipsi permisissent ut se educerent,  et cum magna sollicitudine præmisissent illos,  consequebantur illos, pœnitentia acti. 

** Wisdom 19:3

Adhuc enim inter manus habentes luctum,  et deplorantes ad monumenta mortuorum,  aliam sibi assumpserunt cogitationem inscientiæ,  et quos rogantes projecerant,  hos tamquam fugitivos persequebantur. 

** Wisdom 19:4

Ducebat enim illos ad hunc finem digna necessitas ;  et horum quæ acciderant commemorationem amittebant,  ut quæ deerant tormentis repleret punitio : 

** Wisdom 19:5

et populus quidem tuus mirabiliter transiret,  illi autem novam mortem invenirent. 

** Wisdom 19:6

Omnis enim creatura ad suum genus ab initio refigurabatur,  deserviens tuis præceptis,  ut pueri tui custodirentur illæsi. 

** Wisdom 19:7

Nam nubes castra eorum obumbrabat,  et ex aqua quæ ante erat, terra arida apparuit,  et in mari Rubro via sine impedimento,  et campus germinans de profundo nimio : 

** Wisdom 19:8

per quem omnis natio transivit quæ tegebatur tua manu,  videntes tua mirabilia et monstra. 

** Wisdom 19:9

Tamquam enim equi depaverunt escam,  et tamquam agni exsultaverunt,  magnificantes te, Domine, qui liberasti illos. 

** Wisdom 19:10

Memores enim erant adhuc eorum  quæ in incolatu illorum facta fuerant :  quemadmodum pro natione animalium eduxit terra muscas,  et pro piscibus eructavit fluvius multitudinem ranarum. 

** Wisdom 19:11

Novissime autem viderunt novam creaturam avium,  cum, adducti concupiscentia, postulaverunt escas epulationis. 

** Wisdom 19:12

In allocutione enim desiderii ascendit illis de mari ortygometra :  et vexationes peccatoribus supervenerunt,  non sine illis quæ ante facta erant argumentis per vim fulminum :  juste enim patiebantur secundum suas nequitias. 

** Wisdom 19:13

Etenim detestabiliorem inhospitalitatem instituerunt :  alii quidem ignotos non recipiebant advenas ;  alii autem bonos hospites in servitutem redigebant. 

** Wisdom 19:14

Et non solum hæc, sed et alius quidam respectus illorum erat,  quoniam inviti recipiebant extraneos. 

** Wisdom 19:15

Qui autem cum lætitia receperunt hos  qui eisdem usi erant justitiis,  sævissimis afflixerunt doloribus. 

** Wisdom 19:16

Percussi sunt autem cæcitate :  sicut illi in foribus justi,  cum subitaneis cooperti essent tenebris,  unusquisque transitum ostii sui quærebat. 

** Wisdom 19:17

In se enim elementa dum convertuntur,  sicut in organo qualitatis sonus immutatur,  et omnia suum sonum custodiunt :  unde æstimari ex ipso visu certo potest. 

** Wisdom 19:18

Agrestia enim in aquatica convertebantur,  et quæcumque erant natantia, in terram transibant. 

** Wisdom 19:19

Ignis in aqua valebat supra suam virtutem,  et aqua extinguentis naturæ obliviscebatur. 

** Wisdom 19:20

Flammæ e contrario corruptibilium animalium  non vexaverunt carnes coambulantium,  nec dissolvebant illam, quæ facile dissolvebatur sicut glacies, bonam escam.  In omnibus enim magnificasti populum tuum, Domine,  et honorasti, et non despexisti,  in omni tempore et in omni loco assistens eis.    

